### PR TITLE
fix: remove sudo auto-install of the udevrules, simplify it

### LINKED ISSUE #15074: Automatic trezor UDEV rules instalaltion loads indefinetly
When you try to use the automatic udev rules installation on Linux, it loads indefinitely and never progresses.

**Info:**
Suite Version: app 24.10.1
OS: Ubuntu 24.04
Bridge: 2.0.33

image

Since the udev rules have now been merged into systemd, this function might not be needed anymore? https://github.com/systemd/systemd/commit/a78a52465298e8f5a927da9c9fc56c41837018aa

### PR DESCRIPTION
**Pull request by peter-sanderson**
Packaging formats are moving towards sand-boxing, we no longer can do a root-code-execution. 
 - https://docs.flatpak.org/en/latest/sandbox-permissions.html
 - https://snapcraft.io/docs/security-policies
 - https://snapcraft.io/docs/interfaces

Also udev rules [are now in the systemd](https://github.com/systemd/systemd/pull/33829/commits/5888f032ea75fb7e4df0e0b7532e1b3fdc597df3) (https://github.com/systemd/systemd/pull/33813) we can expect that it will bubble up through releases of the distribution over few years.  

Resolves: https://github.com/trezor/trezor-suite/issues/15074

image

### CODE REVIEW

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx [hunk 1]
```diff
@@ -114,14 +27,14 @@ interface DeviceUnreadableProps {
 export const DeviceUnreadable = ({ device }: DeviceUnreadableProps) => {
     const selectedDevice = useSelector(selectSelectedDevice);
 
+    // generic troubleshooting tips
+    const items = [];
+
     // this error is dispatched by trezord when udev rules are missing
     if (isLinux() && device?.error === 'LIBUSB_ERROR_ACCESS') {
-        return <> {isDesktop() ? <UdevDesktop /> : <UdevWeb />}</>;
+        items.push(TROUBLESHOOTING_TIP_UDEV);
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:35]: Instead of download flow, we just shot tip to install udev rules. Its same tip as on Web where user selects from deb vs. rpm.

File: packages/suite/src/components/suite/UdevDownload.tsx [hunk 2]
```diff
@@ -5,10 +5,10 @@ import styled from 'styled-components';
 import { DATA_URL, HELP_CENTER_UDEV_URL } from '@trezor/urls';
 import { Button, Select, Spinner } from '@trezor/components';
 import { spacings, typography } from '@trezor/theme';
+import { suggestUdevInstaller } from '@trezor/connect';
+import { getInstallerPackage } from '@trezor/connect-common'; // Todo: this import is not dependency, and shall not be
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/UdevDownload.tsx]: I need help from somebody from connect team to help me figure out the best way how to incorporate this into suite. :pray:

File: packages/suite/src/components/suite/UdevDownload.tsx [hunk 3]
```diff
@@ -51,16 +51,12 @@ interface Installer {
...
-    const transport = useSelector(selectTransport);
+    const installers: Installer[] = suggestUdevInstaller(getInstallerPackage()).packages.map(p => ({
+        label: p.name,
+        value: DATA_URL + p.url.substring(1),
+        preferred: p.preferred,
+    }));
 
-    const installers: Installer[] =
-        transport && transport.udev
-            ? transport.udev.packages.map(p => ({
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/UdevDownload.tsx]: - [ ] This is only available on the web. It was fixed [here](https://github.com/trezor/trezor-suite/pull/15771) I think we shall do something similar for desktop as well.

File: packages/connect/src/exports.ts [hunk 4]
```diff
@@ -3,3 +3,4 @@ export * from './events';
 export * from './types';
 
 export { parseConnectSettings } from './data/connectSettings';
+export { suggestUdevInstaller } from './data/udevInfo';
```
Comment (peter-sanderson) [inline packages/connect/src/exports.ts]: Probably shall not be done and it shall be send to state via emitting event the same way it is done on the web

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx [hunk 5]
```diff
@@ -1,106 +1,19 @@
...
-        );
-    }
-
-    return (
-        <TroubleshootingTips
-            opened={response === 0}
-            label={<Translation id="TR_TROUBLESHOOTING_UNREADABLE_UDEV" />}
-            cta={
-                <Button onClick={handleCtaClick}>
-                    <Translation id="TR_TROUBLESHOOTING_UDEV_INSTALL_TITLE" />
```
Comment (mroz22) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:84]: some records in messages.ts should probably be cleared as well (`TR_TROUBLESHOOTING_UDEV_INSTALL_TITLE`...)

File: packages/suite/src/components/suite/UdevDownload.tsx (hunk 2 above)
Comment (mroz22) [reply packages/suite/src/components/suite/UdevDownload.tsx]: hmm the only place where suggestUdevInstaller is now used in connect is this 
https://github.com/trezor/trezor-suite/blob/udev-rules/packages/connect-web/src/module/index.ts#L35
and this is also only used by suite now so we are free to decide where we want it. maybe we can keep  this logic in suite only now? any ideas? @marekrjpolak

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx [hunk 6]
```diff
@@ -1,106 +1,19 @@
...
+    TROUBLESHOOTING_TIP_UDEV,
 } from 'src/components/suite/troubleshooting/tips';
-import { useSelector, useDispatch } from 'src/hooks/suite';
+import { useSelector } from 'src/hooks/suite';
 import type { TrezorDevice } from 'src/types/suite';
 
-// linux web
-const UdevWeb = () => (
-    <TroubleshootingTips
-        label={<Translation id="TR_TROUBLESHOOTING_UNREADABLE_UDEV" />}
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:24]: translation deleted

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx [hunk 7]
```diff
@@ -1,106 +1,19 @@
...
-        items={[
-            {
-                key: 'udev-about',
-                noBullet: true,
-                description: <Translation id="TR_UDEV_DOWNLOAD_DESC" />,
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:29]: still used in `UdevRules` compoent

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx [hunk 8]
```diff
@@ -1,106 +1,19 @@
...
-
-            setResponse(0);
-        }
-    };
-
-    if (response === 1) {
-        return (
-            <TroubleshootingTips
-                opened={false}
-                label={<Translation id="TR_RECONNECT_IN_NORMAL" />}
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:71]: still used in `ReconnectDevicePrompt`

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx [hunk 9]
```diff
@@ -1,106 +1,19 @@
...
-                items={[]}
-                data-testid="@connect-device-prompt/unreadable-udev"
-            />
-        );
-    }
-
-    return (
-        <TroubleshootingTips
-            opened={response === 0}
-            label={<Translation id="TR_TROUBLESHOOTING_UNREADABLE_UDEV" />}
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:81]: deleted

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx (hunk 5 above)
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:84]: deleted

Comment (peter-sanderson) [reply packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:84]: Good point, deleted

File: packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx [hunk 10]
```diff
@@ -1,106 +1,19 @@
...
-            cta={
-                <Button onClick={handleCtaClick}>
-                    <Translation id="TR_TROUBLESHOOTING_UDEV_INSTALL_TITLE" />
-                </Button>
-            }
-            items={[
-                {
-                    key: 'udev-about',
-                    description: <Translation id="TR_UDEV_DOWNLOAD_DESC" />,
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PrerequisitesGuide/DeviceUnreadable.tsx:90]: used in `UdevRules`

**Review by mroz22 — APPROVED** [review]

**Comment by peter-sanderson** [comment]
## For QA:

Linux only :point_down: 

1. desktop suite 
2. uninstall udev-rules 
3. reconnect device
4. you see the info with hints
5. if you click through udev-rules -> you shall see the modal and you shall be able to download deb or rmp package

**Comment by bosomt** [comment]
**QA OK**

- tested on mint and ubuntu
- tested on latest dev build
- rpm is preselected and probably not detected
- more common package is deb, maybe we can consider changing this behavior ?
