### PR TITLE
Fix/catch missing bt settings

### LINKED ISSUE #22272: Can't pair BT device on Linux env other than Gnome or KDE
[open_bluetooth_ui](https://github.com/trezor/trezor-suite/blob/d9af3b65aa9274707edb7463f93dc91c1c2e2193/packages/transport-bluetooth/src/server/platform/linux.rs#L176) handles only Gnome and KDE to open OS BT pairing modal.

For other Linux envs, nothing happens, and you get `"Authentication failed"`, which is unfortunately the same error if you cancel pairing on the OS modal.

This can be solved by **either**:

1. move opening the BT settings to Suite
2. or `transport-bluetooth` shall return a specific error message so that Suite can distinguish if authentication was cancelled, or if we are unable to open the system dialog

👉  **Important:**, this includes the flow where you manually pair a device in OS BT settings, not via Suite. And that can be done theoretically **on any platform**, not just Linux. It's just that in these Linux edge cases there's no other way than that, but even on Windows and macOS user can choose to do this. Therefore:

## QA instructions

- Turn on a TS7 via bluetooth, not known by Suite or the OS before
- Open Suite, start BT scan, but do not pair the device now
- Pair it via OS BT settings
- Now you should be able to see the device in the scanning list, and proceed with connection, THP, etc.
  - as shown [at the end of this video](https://github.com/user-attachments/assets/24946ccd-38c8-4fda-9d9d-25f43204b4cd)

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

Followup for https://github.com/trezor/trezor-suite/pull/22466

- add `isManualPairingRequired`  flag to desktopBluetoothReducer
- display UI instructing user to pair device manually, if isManualPairingRequired is set
- fix connecting a device that was paired manually via OS settings
  - which is particularly relevant for this situation, but it could also be a problem on other platforms – currently the device is a `nearbyDevice` with `connected` status, but it is not known, which was not handled so far, so the device was hidden and not possible to continue
  - now it lets user see the device in list, and initiate connection

## Related issue

Resolve: https://github.com/trezor/trezor-suite/issues/22272

### Screenshots

[Screencast from 2025-10-29 12-15-17.webm](https://github.com/user-attachments/assets/24946ccd-38c8-4fda-9d9d-25f43204b4cd)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/catch-missing-bt-settings&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/catch-missing-bt-settings&lookback=7)

### CODE REVIEW

File: packages/suite/src/actions/bluetooth/bluetoothConnectDeviceThunk.ts [hunk 1]
```diff
@@ -30,6 +31,13 @@ export const bluetoothConnectDeviceThunk = createThunk<
         desktopApi.appFocus();
 
         if (!result.success) {
+            if (result.error === 'PairingUiMissing') {
+                dispatch(stopConnectingBluetoothDevice({ deviceId }));
+                dispatch(setBluetoothDeviceNeedsManualPairing(true));
+
+                return fulfillWithValue({ success: result.success });
```
Comment (Lemonexe) [inline packages/suite/src/actions/bluetooth/bluetoothConnectDeviceThunk.ts:39]: 💭  It's a bit weird to `fulfillWithValue` with an unsuccessful state, semantically it should be reject, but I can see the same thing in this thunk, and the [consuming code](https://github.com/trezor/trezor-suite/blob/e1bcdb7e7e45ad975cb8f270fd768be454630842/packages/suite/src/components/connection/hook/useBluetoothConnection.tsx#L60-L63) counts with it that way, so this is consistent.

File: packages/suite/src/components/connection/BluetoothConnectionModal.tsx [hunk 2]
```diff
@@ -13,7 +13,7 @@ type BluetoothConnectionModalProps = {
     onClose: () => void;
 };
 
-const selectedDeviceConnectionTypes = ['connecting', 'pairing'];
+const selectedDeviceConnectionTypes = ['connecting', 'pairing', 'connected'];
```
Comment (Lemonexe) [inline packages/suite/src/components/connection/BluetoothConnectionModal.tsx]: am looking where this is used, and it seems to me this change is not relevant, and perhaps unwanted?

**Review by Lemonexe — COMMENTED** [review]
Added commits:
ed89dcb2 to fix tests
e2287c3e to finish the manual pairing UI
86349b84 to continue this flow: let user see the device in list and connect it (otherwise it's stuck)

EDIT: fixed up, rebased, commit pointers are invalidated.

File: packages/suite/src/components/connection/BluetoothConnectionModal.tsx (hunk 2 above)
Comment (Lemonexe) [reply packages/suite/src/components/connection/BluetoothConnectionModal.tsx]: Ok I confirmed, this is not relevant for this flow, because the device is not yet selected. Reverting...

**Review by OriginalEveres — APPROVED** [review]
LGTM! ship it :shipit:
