### PR TITLE
14332 coin icon in accounts list not centered

### LINKED ISSUE #14332: Coin icon in accounts list not centered
**Describe the bug**
Coin icon in accounts list not centered.
See production on second screenshot as comparison.

**Info:**
 - Suite version: desktop 24.9.1 (e2177b22af8251cd1e81e2fec0a0019e664e053a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by seibei-iguchi**
## Description

- fixed alignment issues in sidebar account list
- removed style overrides
- updated device selector modals to use NewModal

### Before
Screenshot 2024-09-18 at 10 38 15
Screenshot 2024-09-18 at 10 37 26

### After
Screenshot 2024-09-18 at 10 35 34
Screenshot 2024-09-18 at 10 35 53

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ModalSwitcher/DiscoveryLoader.tsx [hunk 1]
```diff
@@ -1,35 +1,30 @@
...
+        <NewModal.Backdrop alignment={{ x: 'left', y: 'top' }} padding={5}>
+            <SwitchDeviceModal data-testid="@discovery/loader">
+                <CardWithDevice device={device} isFullHeaderVisible={false}>
+                    <Column
+                        justifyContent="center"
+                        margin={{ top: spacings.xxxl, bottom: spacings.xl }}
+                    >
+                        <Spinner size={80} isGrey={false} />
+                        <H3 align="center" margin={{ top: spacings.xxxxl }}>
+                            <Translation id="TR_COIN_DISCOVERY_LOADER_DESCRIPTION" />
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/ModalSwitcher/DiscoveryLoader.tsx:23]: Interesting that it's named description  and it's considered like a heading 🤔

**Review by jvaclavik — APPROVED** [review]
