### PR TITLE
fix(suite): align promo buttons to the right

### LINKED ISSUE #15575: Align app download banners to the right
Screenshot 2024-11-26 at 10 44 59

### PR DESCRIPTION
**Pull request by MiroslavProchazka**
Resolves: https://github.com/trezor/trezor-suite/issues/15575
Before
image

After
image

### CODE REVIEW

**Review by tomasklim — COMMENTED** [review]
I think the whole footer needs more love. It is really weird because for examply on smaller screens it becomes rounded. The "tooltip" has weird colors,... 
Screenshot 2024-11-27 at 11 38 33
Screenshot 2024-11-27 at 11 41 39

File: packages/suite/src/views/dashboard/PromoBanner.tsx [hunk 1]
```diff
@@ -241,27 +238,29 @@ export const PromoBanner = () => {
...
-                        analyticsPayload="ios"
-                        shownQRState={shownQRState}
-                    />
-                    <StoreBadge
-                        url={SUITE_MOBILE_PLAY_STORE}
-                        image="PLAY_STORE"
-                        type="play-store"
-                        analyticsPayload="android"
-                        shownQRState={shownQRState}
+                <Flex alignItems="center" justifyContent="space-between" width="100%">
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/PromoBanner.tsx]: Please use `Row` instead of `Flex`

File: packages/suite/src/views/dashboard/PromoBanner.tsx [hunk 2]
```diff
@@ -241,27 +238,29 @@ export const PromoBanner = () => {
...
-                        analyticsPayload="ios"
-                        shownQRState={shownQRState}
-                    />
-                    <StoreBadge
-                        url={SUITE_MOBILE_PLAY_STORE}
-                        image="PLAY_STORE"
-                        type="play-store"
-                        analyticsPayload="android"
-                        shownQRState={shownQRState}
+                <Row alignItems="center" justifyContent="space-between" width="100%">
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/PromoBanner.tsx]: you don't have to specify `alignItems="center"`, because it's default value for `Row`

File: packages/suite/src/views/dashboard/PromoBanner.tsx [hunk 3]
```diff
@@ -52,15 +52,12 @@ const DesktopPromoContainer = styled.div`
...
     ${promoContainerCss}
-    justify-content: start;
-    margin: ${spacingsPx.sm} ${spacingsPx.xxxl} auto auto;
-    padding-bottom: ${spacingsPx.sm};
+    width: 100%;
 
     ${variables.SCREEN_QUERY.MOBILE} {
         flex-direction: column;
-        gap: 0;
+        gap: ${spacingsPx.sm};
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/PromoBanner.tsx]: what about define this in `Row`?

**Review by jvaclavik — COMMENTED** [review]
Two more comments, and ready to merge!

File: packages/suite/src/views/dashboard/PromoBanner.tsx [hunk 4]
```diff
@@ -241,27 +236,31 @@ export const PromoBanner = () => {
...
-                        shownQRState={shownQRState}
+                <Row justifyContent="space-between" width="100%">
+                    <Translation
+                        values={{ b: text => <b>{text}</b> }}
+                        id="TR_MOBILE_APP_PROMO_TEXT_FOOTER"
                     />
-                </BadgeContainer>
+
+                    <Row>
+                        <BadgeContainer>
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/PromoBanner.tsx]: Does it work without using `BadgeContainer`?

(Row and BadgeContainer are defacto duplicity here)

Comment (MiroslavProchazka) [reply packages/suite/src/views/dashboard/PromoBanner.tsx]: I will try

**Review by jvaclavik — APPROVED** [review]
LGTM
