### PR TITLE
fix(trading): update fiat amount validation to use token balance

### LINKED ISSUE #23564: Fiat input not working for tokens in Swap
**Describe the bug**
The fiat input option does not work for tokens during swap. When attempting to enter an amount in USD for a token (e.g., USDC), the interface shows a red error border and displays "You don't have enough funds," even though the token balance is sufficient. 

**Screenshots**
Swap screen showing fiat input not working

**Info:**
 - Suite version: desktop 25.12.0 (6bc08d96f5cb92981973e9fc30ec8cd38b52f955)
 - Browser: Trezor Suite 25.12.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3W1 2.9.5 universal (revision aecac16bb1261988d146079e9ab235056cee422e)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by sherpaPSX**
## Description

Fixed fiat validation in trading swap

## Notes for QA
Check if validation matching token amount

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23564

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/swap-validation&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/swap-validation&lookback=7)

### CODE REVIEW

**Review by tomasklim — APPROVED** [review]
LGTM, not tested

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiat.tsx [hunk 1]
```diff
@@ -64,8 +65,12 @@ export const TradingFormInputFiat = ({
     const sendCryptoSelect = getValues(TRADING_FORM_SEND_CRYPTO_CURRENCY_SELECT);
     const tokenAddress = sendCryptoSelect?.contractAddress as TokenAddress | undefined;
 
+    const tokenBalance = tokenAddress
```
Comment (vytick) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiat.tsx]: pls change the name to something like this because it is not always token

```suggestion
    const balance = tokenAddress
```

Comment (sherpaPSX) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiat.tsx]: done

**Review by vytick — APPROVED** [review]
