### PR TITLE
Fix: analytics button storage

### LINKED ISSUE #11216: connect-analytics floating menu - saved state not respected
it looks like it has never respected what is saved in state. select should be switched on/off based on what is stored in storage

https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/components/DataAnalytics.tsx#L122

reporting / not-reporting works correcly, only visual issue

please @karliatto if you could check on this 🙏

### PR DESCRIPTION
**Pull request by karliatto**
## Description

Fix analytics button in Trezor Popup show it as non-checked when it is not enabled.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11216

## Screenshots:

image

### CODE REVIEW

**Review by mroz22 — COMMENTED** [review]
it looks ok, but did not test. leaving it to @martykan for review 🙏

**Comment by martykan** [comment]
It fixes the issue, but it's not on by default if you visit for the first time. I think that's what we want, so more users opt in right?

File: packages/connect-ui/src/components/BottomRightFloatingBar.tsx [hunk 1]
```diff
@@ -34,13 +32,16 @@ type BottomRightFloatingBarProps = {
 };
 
 export const BottomRightFloatingBar = ({ onAnalyticsConfirm }: BottomRightFloatingBarProps) => {
-    const [view, setView] = useState(getView());
+    const initialStorage = storage.load();
+    const [view, setView] = useState(getView(initialStorage.tracking_enabled === undefined));
+    const isInitialTrackingEnabled = !!initialStorage.tracking_enabled;
```
Comment (martykan) [inline packages/connect-ui/src/components/BottomRightFloatingBar.tsx]:
```suggestion
    const isInitialTrackingEnabled = initialStorage.tracking_enabled !== false;
```
To keep it on by default

**Comment by mroz22** [comment]
yes, on by default, it should be opt-out feature.

File: packages/connect-ui/src/components/BottomRightFloatingBar.tsx (hunk 1 above)
Comment (karliatto) [reply packages/connect-ui/src/components/BottomRightFloatingBar.tsx]: DONE https://github.com/trezor/trezor-suite/pull/11299/commits/12c47e46aba2f76d613115129d003b0119657c7c

**Review by martykan — APPROVED** [review]
