### PR TITLE
fix(native): place usePreventRemove to screen to prevent unmount

### LINKED ISSUE #25111: Receive address stuck on device after using Android "back" button
When a receive address is shown on the device and the user navigates back using the Android system back gesture/button instead of the in-app “X”, the address remains stuck on the device screen. If the user then switches to another account or coin and opens a new receive address, the previously displayed address is still shown.

**Steps to reproduce:**
1. Open any account and display a receive address on the device.
2. Use the Android system back gesture/button instead of tapping the in-app close button.
3. Switch to a different account or coin.
4. Display a new receive address.

**Info:**
- Suite Version: develop-26.2.1, commit bf775303b80276f08c184f31151eaaf937ae6c70
- OS: Android 15

### PR DESCRIPTION
**Pull request by OriginalEveres**
`usePreventRemove` was placed in `ReceiveScreenHeader.tsx` component which was unmounted, because when `revealConfirmOnTrezorSheet` is called -> isFullscreen mode is set to false and that unmounts the `defaultHeader` which was `ReceiveScreenHeader.tsx`.

I fixed it by moving the `usePreventRemove` into a `ReceiveAddressScreen.tsx`.

## Notes for QA

- when you go back, using the os back button, the call on device should be canceled
- please test other cases like returning back when address is confirmed, etc.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/25111

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/receive-address-stuck&lookback=7)

### CODE REVIEW

**Review by matejkriz — APPROVED** [review]
Makes sense and works as expected.

File: suite-native/receive/src/screens/ReceiveAddressScreen.tsx [hunk 1]
```diff
@@ -68,6 +68,14 @@ export const ReceiveAddressScreen = ({
     const { address, isReceiveApproved, isUnverifiedAddressRevealed, handleShowAddress } =
         useAccountReceiveAddress(accountKey);
 
+    usePreventRemove(true, ({ data }) => {
```
Comment (matejkriz) [inline suite-native/receive/src/screens/ReceiveAddressScreen.tsx:71]: I'm not sure when ReceiveAddressScreen is unmounted 🤔 I'd rather try it out.

Comment (matejkriz) [reply suite-native/receive/src/screens/ReceiveAddressScreen.tsx:71]: Tested and works as expected 🆗

Comment (OriginalEveres) [reply suite-native/receive/src/screens/ReceiveAddressScreen.tsx:71]: > Tested and works as expected 🆗 

Great, I tested it on real android device and iOS emulator.
