### PR TITLE
fix(suite): ethereum staking time in progress bar

### LINKED ISSUE #24929: Staking time in progress bar is increasing and not decreasing every day
Staking queue is rising everyday. 

In case user staked when the queue was 30 days, now he sees even more days in the progress bar. It does not take his "order" in the queue into account

https://www.reddit.com/r/TREZOR/comments/1qrgxil/eth_staking_time_only_increasing/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Fixes an issue where the staking progress bar showed increasing activation time.
Now activation estimates account for the current epoch timestamp.

## QA

Progress time of staking should now decrease by elapsed days. It should not copy ethereum staking queue

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/24929

### CODE REVIEW

File: suite-common/wallet-utils/src/ethereumStakingUtils.ts [hunk 1]
```diff
@@ -147,3 +147,18 @@ export const getStakeType = (precomposedForm: FormState, outputs: ReviewOutput[]
...
+
+export const hasStakeInPendingDepositedState = (account: Account) => {
+    if (account?.networkType !== 'ethereum') return false;
+
+    const pool = getAccountEverstakeStakingPool(account);
+    if (!pool) return false;
+
+    const { pendingDepositedBalance, pendingBalance } = pool;
+
+    if (new BigNumber(pendingDepositedBalance).gt(0) && !new BigNumber(pendingBalance).gt(0)) {
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/ethereumStakingUtils.ts]:
```suggestion
    if (new BigNumber(pendingDepositedBalance).gt(0) && new BigNumber(pendingBalance).lte(0)) {
```

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx [hunk 2]
```diff
@@ -73,6 +77,21 @@ export const EthStakingDashboard = ({ selectedAccount }: EthStakingDashboardProp
 
     const isStakingActive = useSelector(state => selectAccountIsStakingActive(state, account.key));
 
+    useEffect(() => {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx]: This will result into flashing different values. It is not correct solution to do it like this.

Try to check https://github.com/trezor/trezor-suite/pull/24538

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: suite-common/wallet-utils/src/ethereumStakingUtils.ts (hunk 1 above)
Comment (dev-pvl) [reply suite-common/wallet-utils/src/ethereumStakingUtils.ts]: fixed here, https://github.com/trezor/trezor-suite/pull/25115/changes/5a26e25448a8013a9b7fcc65119bf22b2db281e6

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx (hunk 2 above)
Comment (dev-pvl) [reply packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx]: That's true. Didn't know we have tanstack query in the project. Should be fixed here https://github.com/trezor/trezor-suite/pull/25115/changes/5a26e25448a8013a9b7fcc65119bf22b2db281e6

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx [hunk 3]
```diff
@@ -53,6 +55,31 @@ export const EthStakingDashboard = ({ selectedAccount }: EthStakingDashboardProp
...
+
+        return stakeTxs[0]?.blockTime;
+    }, [stakeTxs]);
+
+    const { data: validatorQueueData, isLoading: isValidatorQueueLoading } = useQuery({
+        enabled: !!account,
+        queryKey: commonQueryKeys.validatorsQueue(accountKey, lastTxBlockTime),
+        staleTime: 60 * 1000, // 1 minute
+        queryFn: () => {
+            if (!account) return;
```
Comment (sherpaPSX) [inline packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx]: question: Is this check needed when query is disabled byt the `enabled: !!account,`

Comment (sherpaPSX) [inline packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx:69]: Why do you need this since you have  `enabled: !!account`

**Review by sherpaPSX — APPROVED** [review]

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx (hunk 3 above)
Comment (sherpaPSX) [reply packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx:69]: Ahh ok, it is typeguard to `hasStakeInPendingDepositedState`.

File: suite-common/react-query/src/constants/queryKeys.ts [hunk 4]
```diff
@@ -3,6 +3,12 @@ import type { AllowedQueryKey } from '../types';
 export const commonQueryKeys = {
     txSimulationEVM: (input?: any) => ['tx-simulation-evm', input],
     dappScan: (url?: string) => ['dapp-scan', url],
+    validatorsQueue: (accountKey: string, timestamp?: number) => [
+        'everstake',
+        'validatorsQueue',
+        accountKey,
+        timestamp ?? 'no-ts',
```
Comment (tomasklim) [inline suite-common/react-query/src/constants/queryKeys.ts:10]:
```suggestion
        timestamp,
```

better to just use undefined or why to use this `no-ts`?

**Review by tomasklim — APPROVED** [review]
