### PR TITLE
Fix tx.amount without fee, totalSpent part 2 (suite integration)

### LINKED ISSUE #3412: tx.amount inconsistency between bitcoin-like and ethereum
`tx.amount` for sent bitcoin-like transactions includes a fee, but ethereum txs don't include fee in `tx.amount` field leading to various inconsistencies for example:

Screenshot of an ethereum account, sum of txs for 5th of february should be non-zero, but because of bitcoin-like txs when computing this sum we subtract `tx.fee` from `tx.amount` for all sent transactions, which leads in incorrect result.
image

similar issues that are imo caused by the same problem
https://github.com/trezor/trezor-suite/issues/3366
https://github.com/trezor/trezor-suite/issues/3459

### LINKED ISSUE #3459: Incorrect incoming fiat value
**Describe the bug**
Incorrect incoming fiat value (+$0.00) is displayed in transaction history. 

**Info:**
 - Suite Version: 21.2.1 (21.2.1.10324)

 - OS: OS X 10.15.6

**Expected result:**
Adequate incoming fiat value should be displayed. 

**Screenshots:**
SuiteBugBalance

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/3412
close https://github.com/trezor/trezor-suite/issues/3459

depends on new B-L https://github.com/trezor/trezor-suite/pull/3472

### CODE REVIEW

File: packages/blockchain-link/src/types/common.ts [hunk 1]
```diff
@@ -60,6 +60,7 @@ export interface Transaction {
     blockHeight?: number;
     blockHash?: string;
 
+    totalSpent: string;
     amount: string;
     fee: string;
     // total: string, // amount + total
```
Comment (szymonlesisz) [inline packages/blockchain-link/src/types/common.ts]: its here already :)

File: packages/blockchain-link/tests/unit/fixtures/utils.ts [hunk 2]
```diff
@@ -618,7 +618,8 @@ export default {
             },
             parsed: {
                 type: 'sent',
-                amount: '50', // B.value + fee
```
Comment (slowbackspace) [inline packages/blockchain-link/tests/unit/fixtures/utils.ts]: according to this it really looks like it was on purpose

File: packages/blockchain-link/src/workers/blockbook/utils.ts [hunk 3]
```diff
@@ -182,13 +185,21 @@ export const transformTransaction = (
...
+                totalSpent = new BigNumber(amount).plus(tx.fees ?? '0').toString();
+            }
         } else if (voutLength) {
             // bitcoin-like transaction
             // sum all my inputs
             const myInputsSum = sumVinVout(outgoing, '0');
             // reduce sum by my outputs values
-            amount = sumVinVout(incoming, myInputsSum, 'reduce');
+            totalSpent = sumVinVout(incoming, myInputsSum, 'reduce');
+            console.log('tx.fee', tx.fees);
```
Comment (slowbackspace) [inline packages/blockchain-link/src/workers/blockbook/utils.ts]: rm

File: packages/suite/src/storage/migrations/index.ts [hunk 4]
```diff
@@ -147,4 +148,47 @@ export const migrate = async (
             cursor = await cursor.continue();
         }
     }
+
+    if (oldVersion < 21) {
+        // do the same thing as in blockchain-link's transformTransaction
```
Comment (slowbackspace) [inline packages/suite/src/storage/migrations/index.ts:153]: next time, we need to implement additional logic to trigger refetch of all transactions. this is pain.

File: packages/suite/src/utils/wallet/transactionUtils.ts [hunk 5]
```diff
@@ -76,11 +75,10 @@ export const sumTransactionsFiat = (
...
     let totalAmount = new BigNumber(0);
     transactions.forEach(tx => {
-        // count only recv/sent txs
-        if (tx.type === 'sent') {
-            totalAmount = totalAmount
-                .minus(toFiatCurrency(tx.amount, fiatCurrency, tx.rates, -1) ?? 0)
-                .minus(toFiatCurrency(tx.fee, fiatCurrency, tx.rates, -1) ?? 0);
+        if (tx.type === 'sent' || tx.type === 'self') {
+            totalAmount = totalAmount.minus(
+                toFiatCurrency(tx.amount, fiatCurrency, tx.rates, -1) ?? 0,
```
Comment (slowbackspace) [inline packages/suite/src/utils/wallet/transactionUtils.ts:80]: there is a dilema. if we have 2 txs: one sent, one received. each with amount 0.1 and fee 0.01, then what we show in txs overview is
\- 0.1
\+ 0.1
(cause we don't display fee in txs list)

which would sum to 0, but in reality you lost more than received due to fee paid on sent tx. so shouldn't we  show you that, at the end of the day, you had 0.01 less? imo yes, but then everyone will be confused because all they see is 
\- 0.1
\+ 0.1
from which it makes sense that it leads to 0 delta at the end of the day, not -0.01. I guess that's the reason we were doing it this  way

So for now I will keep it as it is and if we can deal with it later if someone finds it confusing.

Comment (slowbackspace) [reply packages/suite/src/utils/wallet/transactionUtils.ts:80]: cc @matejzak

**Review by szymonlesisz — APPROVED** [review]
nice
