### PR TITLE
Fix inactive button when device check is disabled

### LINKED ISSUE #14088: Not able to onboard device after storage reset and device check disabling
**Describe the bug**

I'm not able to onboard device after storage reset and device check disabling.
Have you used this Trezor before? dialogue does not respond.
Managed to replicate it multiple times

**Steps to reproduce:**
1. Reset app storage
2. Navigate to `Settings/Device`
3. Disable device checks
4. Navigate back to onboarding
5. `Yes, continue` button does not respond

**Info:**
 - Suite version: web 24.9.0 (983e42f2cc2f6fb51463a26c7f6206c4f56a3d14)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.2 regular (revision 9e18e72a2c7896cbcce1df4c2d908eab0f01564f)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/c2971eef-9447-4b14-b0ba-2d9c168f4c72

### PR DESCRIPTION
**Pull request by komret**
## Description

`goToSuiteOrNextDevice` did not take `isDeviceAuthenticityCheckDisabled` into account so it just kept reselecting the same device.

I am still not too happy with this, I want the function to select the next device regardless of it supporting authenticity check or not. I will try to do that later, this is just a quick fix.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14088

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx [hunk 1]
```diff
@@ -126,14 +127,6 @@ const firmwareInstalledChecklist = [
     },
 ] as const;
 
-const isAuthenticationSupportedMap: Record<DeviceModelInternal, boolean> = {
-    [DeviceModelInternal.T1B1]: false,
-    [DeviceModelInternal.T2T1]: false,
-    [DeviceModelInternal.T2B1]: true,
-    [DeviceModelInternal.T3B1]: true,
-    [DeviceModelInternal.T3T1]: true,
-};
```
Comment (Lemonexe) [inline packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx:135]: Good riddance :+1:

**Review by Lemonexe — APPROVED** [review]
Codewise LGTM.
Did not test though, as it is a QA issue
