### PR TITLE
fix(suite-native): fix e2e tests

### LINKED ISSUE #18907: Bottom Sheet replacemenet
Replace all occurrences of the old [Bottom Sheet ](https://github.com/trezor/trezor-suite/blob/develop/suite-native/atoms/src/Sheet/BottomSheet.tsx)with the [BottomSheetModal](https://github.com/trezor/trezor-suite/blob/develop/suite-native/atoms/src/Sheet/BottomSheetModal.tsx) component

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

fixed device fw version
returned `btcWalletPreloaded` to the original state

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/18907

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/e2d-firmware&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/e2d-firmware&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/e2d-firmware&lookback=7)

### CODE REVIEW

**Review by juriczech — APPROVED** [review]

File: suite-native/app/e2e/fixtures/walletWithBtcAcc.ts [hunk 1]
```diff
@@ -1,3 +1,5 @@
+// eslint-disable-next-line @typescript-eslint/ban-ts-comment
+// @ts-nocheck
```
Comment (juriczech) [inline suite-native/app/e2e/fixtures/walletWithBtcAcc.ts]: Please explain why is this necessary for future reference or remove if it's not needed 🙏

Comment (BrantalikP) [reply suite-native/app/e2e/fixtures/walletWithBtcAcc.ts]: Oh, I forgot to mention it..  the issue is with the `types` of those parameters I added. Initially, they were already part of @jbazant ’s PR, but since they didn’t pass the type check, I assumed they might have been removed. However, they are actually required and without them, the trading buy flow fails.

My guess is that although the values don’t satisfy the types, this is the bare minimum required for the address to be displayed in the flow.

Comment (BrantalikP) [reply suite-native/app/e2e/fixtures/walletWithBtcAcc.ts]: updated
