### PR TITLE
Report firmware check failure to Sentry on mobile

### LINKED ISSUE #17409: Firmware version check fail reporting on mobile
Basic implementation of firmware version check for mobile. We're still testing it, so let's not display any UI yet, perform the check and report failures to Sentry similarly to desktop.

### PR DESCRIPTION
**Pull request by OriginalEveres**
Reports failed version check to Sentry when:
- unexpectedly device reports a version change
- device returns false version check after successfull update

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17409

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/mobile-firmware-version-check&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/mobile-firmware-version-check&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/mobile-firmware-version-check&lookback=7)

### CODE REVIEW

File: suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx [hunk 1]
```diff
@@ -141,13 +145,30 @@ export const FirmwareInstallationScreenContent = ({
             return;
         }
 
+        const { versionCheck, bootloaderVersion, binaryVersion, installedVersion, releaseVersion } =
+            result.payload;
+
+        if (!versionCheck) {
```
Comment (Lemonexe) [inline suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx]: :pray: 
```suggestion
        if (versionCheck === false) {
```

File: suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx [hunk 2]
```diff
@@ -141,13 +145,30 @@ export const FirmwareInstallationScreenContent = ({
...
+
         handleAnalyticsReportFinished();
     }, [
         setIsFirmwareInstallationRunning,
-        onFirmwareInstallationFailure,
         firmwareUpdate,
         handleAnalyticsReportFinished,
         handleAnalyticsReportCancelled,
+        onFirmwareInstallationFailure,
+        originalDevice,
```
Comment (Lemonexe) [inline suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx]: I hope `originalDevice` is referentially stable?
If you've tested it then fine, otherwise it'd be safer to define three variables and use them as deps..

File: packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts [hunk 3]
```diff
@@ -9,37 +10,35 @@ import { hashCheckErrorScenarios, revisionCheckErrorScenarios } from 'src/consta
...
-    console.warn(payloadLabel, contextData, warningPayload);
-
-    withSentryScope(scope => {
-        scope.setLevel('warning');
-        scope.setTag('deviceAuthenticityError', `firmware ${checkType} check warning`);
-        scope.setExtra('warningPayload', warningPayload);
-        captureSentryMessage(`${payloadLabel} ${JSON.stringify(contextData)}`, scope);
-    });
-};
+) => reportCheck('warning', checkType, contextData, warningPayload);
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts:41]: amazing, thank you! :raised_hands:

File: suite-common/firmware/src/types.ts [hunk 4]
```diff
@@ -0,0 +1,8 @@
+/**
+ * Firmware check types used in the firmware security checks.
+ */
+export type FirmwareCheckType =
+    | 'Entropy'
+    | 'Firmware hash'
+    | 'Firmware revision'
+    | 'Firmware version';
```
Comment (Lemonexe) [inline suite-common/firmware/src/types.ts]: Circular deps between workspaces, let's revert to duplicated union at each place :cry:

**Review by Lemonexe — COMMENTED** [review]
Codewise LGTM.
After resolving circular deps it looks good to go.

File: suite-common/firmware/src/types.ts (hunk 4 above)
Comment (OriginalEveres) [reply suite-common/firmware/src/types.ts]: b05de2a4c8abfd99f156db3641be1c38ec1f9cbf moved to `suite-types`

File: suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx (hunk 1 above)
Comment (OriginalEveres) [reply suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx]: e5eb59fe0c25ae4b0abecaa5585bb8e4e0233aca 😅

File: suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx (hunk 2 above)
Comment (OriginalEveres) [reply suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx]: my test went fine, but as I was thinking about it I've decided to create a variables and use them instead of the `originalDevice`

**Review by Lemonexe — APPROVED** [review]
Perfect :rocket:
