### PR TITLE
fix: hack-fix for selected device vs. thp-device, pick forst THP devie insetad of selected one

### LINKED ISSUE #21818: A picture of remembered device is shown instead of the T3W1 that I am connecting.
**Describe the bug**
If I connect T3W1 when I have some other device remembered, I am shown the remembered device on the connecting picture instead of the T3W1. The picture is wrong in the beanie as well.

**Info:**
 - Suite version: desktop 25.10.0 (0c38f599d12923ffe53305b8575b1f7cf9b944dc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.10.0 Chrome/140.0.7339.41 Electron/38.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.9.1 universal (revision acd56d0113a547e9b5983510b0ce9de079e30e05)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0
 
**How to reproduce**

1. Connect a device (T2T1 for example)
2. Disconnect it
3. Connect T3W1
4. After BLE pairing, the picture shows the remembered device instead of T3W1

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/21818

Before:
image

After:

image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=hack-fix-selected-device-vs-thp-device&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=hack-fix-selected-device-vs-thp-device&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=hack-fix-selected-device-vs-thp-device&lookback=7)

### CODE REVIEW

File: suite-native/thp/src/hooks/useThpAutoconnectAlerts.tsx [hunk 1]
```diff
@@ -15,10 +18,13 @@ export const useThpAutoconnectAlerts = () => {
     const { showToast } = useToast();
 
     const autoconnectCredentials = useSelector(selectDeviceAutoconnectCredentials);
+    const device = useSelector(selectSelectedDevice);
```
Comment (peter-sanderson) [inline suite-native/thp/src/hooks/useThpAutoconnectAlerts.tsx:21]: On native, we can simply use selected device I guess to keep current behavior

cc @juriczech

File: suite-common/thp/src/startThpAutoconnectThunk.ts [hunk 2]
```diff
@@ -1,20 +1,18 @@
...
-export const startThpAutoconnectThunk = createThunk<void, void, void>(
-    `${THP_PREFIX}/startThpAutoconnectThunk`,
-    async (_, { getState, dispatch }) => {
-        const device = selectSelectedDevice(getState());
-
-        if (device === undefined) {
-            return;
-        }
+type StartThpAutoconnectThunkParam = {
+    device: TrezorDevice;
```
Comment (juriczech) [inline suite-common/thp/src/startThpAutoconnectThunk.ts:10]: What about having the device parameter as optional? If you send device, use it, if not, then use selectedDevice. Seems better if it's going to be removed anyway and requires zero changes on native.

File: suite-native/thp/src/hooks/useThpAutoconnectAlerts.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/thp/src/hooks/useThpAutoconnectAlerts.tsx:21]: https://github.com/trezor/trezor-suite/pull/22023#discussion_r2390849468

File: suite-common/thp/src/startThpAutoconnectThunk.ts (hunk 2 above)
Comment (peter-sanderson) [reply suite-common/thp/src/startThpAutoconnectThunk.ts:10]: This is not going to be removed. The parameter here will stay. Only the selector shall change (to select by some ID in the THP state and not assuming "the-first")

File: suite-common/wallet-core/src/device/deviceSelectors.ts [hunk 3]
```diff
@@ -34,6 +34,26 @@ export const selectSelectedDevice = (state: DeviceRootState) => state.device.sel
 export const selectIsDeviceAutoEjectEnabled = (state: DeviceRootState) =>
     state.device.isDeviceAutoEjectEnabled;
 
+/**
+ * @deprecated This is a HACK, and it shall be refactored. See: https://github.com/trezor/trezor-suite/issues/22022
+ */
+export const selectSelectedFirstThpDevice = (state: DeviceRootState) => {
+    const unacquiredThp = state.device.devices.find(
+        device => getStatus(device) === 'unacquired-thp-required',
+    );
```
Comment (juriczech) [inline suite-common/wallet-core/src/device/deviceSelectors.ts]: nit: find gives you the first device it finds in the array. IMO, you should use the last one as its more probable you want to use that one. While neither is correct, I assume you will more likely be trying to pair the more recent device.

Comment (peter-sanderson) [reply suite-common/wallet-core/src/device/deviceSelectors.ts]: fixed

Comment (juriczech) [reply suite-common/wallet-core/src/device/deviceSelectors.ts]: It would be better to use [.findLast](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findLast)

Comment (peter-sanderson) [reply suite-common/wallet-core/src/device/deviceSelectors.ts]: fixed

**Review by juriczech — APPROVED** [review]
LGTM. I haven't tested it and don't have desktop THP knowledge so might be better to wait for some desktop approve.

**Review by komret — APPROVED** [review]
