### PR TITLE
Fix/testnet account fixes

### LINKED ISSUE #7956: Coin amount changes after it was imported
**Describe the bug**
Coin amount changes from time to time with my test account.
Account showed 0,1 then 0,005 and back.

https://tbtc1.trezor.io/xpub/vpub5YiQAEKHWwmdG1qMm1y5FryfPmMCm4ANtZTNthSpLRC1ATZ9CpQddrTKXDrw9xbxvPPhjKJyUfWc8xQJQLx5KyoComWt1Ho18mb6P86ed2u

**Info:**

-   Suite Version: mobile 23.3.1
-   OS: Android

**Screenshots**

image

image

image

image

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- testnet account detail shows the correct account balance (do not read it from the hidden chart)
- testnet transaction list item does not show abandoned amount sign

## Related Issue

Resolve #7956

### CODE REVIEW

File: suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx [hunk 1]
```diff
@@ -41,13 +46,21 @@ const hasPriceIncreasedAtom = atom(get => {
     return percentageChange >= 0;
 });
 
-const CryptoBalance = ({ accountSymbol }: { accountSymbol: NetworkSymbol }) => {
+const CryptoBalance = ({ accountKey }: { accountKey: AccountKey }) => {
+    const account = useSelector((state: AccountsRootState) =>
```
Comment (Nodonisko) [inline suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx]: Please explain why it's needed. Also we can't do this here, this component must be maximally performant, these two selectors will affect it quite a lot.

File: suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx [hunk 2]
```diff
@@ -29,28 +31,36 @@ export const signValueMap = {
...
+            <TransactionListItemContainer
+                symbol={transaction.symbol}
+                txid={transaction.txid}
+                transactionType={transaction.type}
+                accountKey={accountKey}
+                isFirst={isFirst}
+                isLast={isLast}
+            >
+                <Box flexDirection="row">
+                    {!isTestnetAccount && (
```
Comment (Nodonisko) [inline suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: I do not understand why we hide sign just for non testnet accounts? Shouldn't we hide both sign and crypto value for testnet accounts instead?

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx [hunk 3]
```diff
@@ -41,13 +46,21 @@ const hasPriceIncreasedAtom = atom(get => {
...
+    );
     const selectedPoint = useAtomValue(selectedPointAtom);
 
+    if (!account) return null;
+
     return (
         <CryptoAmountFormatter
-            value={selectedPoint.cryptoBalance}
-            network={accountSymbol}
+            value={isTestnetAccount ? account.formattedBalance : selectedPoint.cryptoBalance}
```
Comment (Nodonisko) [inline suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx]: Please never use anything with `formatted` prefix or suffix. Purpose of formatters is that it's only place where you format values and they should always receive raw values.

File: suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: Because if we hide also crypto value, the layout of the transaction item changes. Crypto value has a check inside and displays empty box for testnet coins.

But I agree that the code is not clear like this. I've refactored it to hide both sign and value and explicitly render EmptyAmountText instead for testnets. 274ce39a2

File: suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx]: We need this because the account header balance was calculated from the value of Graph `selectedPointAtom`. For testnet accounts, it was displaying zero or balance of the last displayed graph (very confusing). 

I've refactored it to hide completely AccountDetailGraphHeader for testnet accounts to keep performance and make the code clearer. 274ce39a2

File: suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx (hunk 3 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx]: Ok, my bad. I copy pasted that from `TransactionListItem`. I removed `formattedBalance` from both places in 274ce39a2.

File: suite-native/module-accounts/src/components/TransactionListHeader.tsx [hunk 4]
```diff
@@ -51,28 +81,27 @@ export const TransactionListHeader = memo(
 
         const isTokenAccount = !!tokenSymbol;
 
+        // Graph is temporarily hidden also for ERC20 tokens.
+        // Will be solved in issue: https://github.com/trezor/trezor-suite/issues/7839
+        const isGraphDisplayed = accountHasTransactions && !isTestnetAccount && !isTokenAccount;
```
Comment (juriczech) [inline suite-native/module-accounts/src/components/TransactionListHeader.tsx:64]: I would put this condition in AccountDetailGraph itself

File: suite-native/module-accounts/src/components/TransactionListHeader.tsx [hunk 5]
```diff
@@ -32,6 +36,32 @@ type AccountsNavigationProps = TabToStackCompositeNavigationProp<
     AccountsStackParamList
 >;
 
+const GraphlessHeader = ({ accountKey }: { accountKey: AccountKey }) => {
```
Comment (juriczech) [inline suite-native/module-accounts/src/components/TransactionListHeader.tsx]:
```suggestion
const TestnetAccountTransactionListHeader = ({ accountKey }: { accountKey: AccountKey }) => {
```

File: suite-native/module-accounts/src/components/TransactionListHeader.tsx [hunk 6]
```diff
@@ -32,6 +36,32 @@ type AccountsNavigationProps = TabToStackCompositeNavigationProp<
...
+        >
+            <CryptoIcon name={account.symbol} />
+            <CryptoAmountFormatter
+                value={account.balance}
+                network={account.symbol}
+                isBalance={false}
+                adjustsFontSizeToFit
+            />
+        </HStack>
+    );
```
Comment (juriczech) [inline suite-native/module-accounts/src/components/TransactionListHeader.tsx]: You could create component TransactionListHeaderBalance or something like this and use it for testnet and normal coins. This feels like it's duplication of parts of AccountDetailGraphHeader component. You could then use the component there so when we need to restyle it, you only need to change one file so it's less error prone

**Review by juriczech — CHANGES_REQUESTED** [review]

File: suite-native/module-accounts/src/components/TransactionListHeader.tsx [hunk 7]
```diff
@@ -51,28 +81,27 @@ export const TransactionListHeader = memo(
...
                     </>
                 )}
+                {isTestnetAccount && <GraphlessHeader accountKey={accountKey} />}
+
+                <Box marginBottom="large" paddingHorizontal="medium">
+                    <Button iconLeft="receive" size="large" onPress={handleReceive}>
+                        Receive
+                    </Button>
+                </Box>
+                <Divider />
```
Comment (juriczech) [inline suite-native/module-accounts/src/components/TransactionListHeader.tsx:87]: Nice one 👌 Didn't make sense to be only on accounts with txs

File: suite-native/module-accounts/src/components/TransactionListHeader.tsx (hunk 5 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/TransactionListHeader.tsx]: The component was renamed and moved to separate  file in f5d488e1f.

File: suite-native/module-accounts/src/components/TransactionListHeader.tsx (hunk 6 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/TransactionListHeader.tsx]: Applied in f5d488e1f.

File: suite-native/module-accounts/src/components/TransactionListHeader.tsx (hunk 4 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/TransactionListHeader.tsx:64]: We would have to put this condition to both Graph and GraphHeader. I agree that it should be the responsibility of these graph components as you suggest. But please let's wait until the graph is displayed also for eth tokens. Then the evaluation logic will be simpler and we can just check if the network is a testnet inside of the graph components.

**Review by juriczech — APPROVED** [review]

File: suite-native/module-accounts/src/components/AccountDetailBalance.tsx [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+type AccountDetailBalanceProps = {
+    value: string;
+    networkSymbol: NetworkSymbol;
+    isBalance?: boolean;
+};
+
+export const AccountDetailBalance = ({
+    value,
+    networkSymbol,
+    isBalance = true,
```
Comment (Nodonisko) [inline suite-native/module-accounts/src/components/AccountDetailBalance.tsx]: Shoudn't this be always true because component itself has `Balance` in name?

**Review by Nodonisko — APPROVED** [review]

File: suite-native/module-accounts/src/components/AccountDetailBalance.tsx (hunk 8 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/AccountDetailBalance.tsx]: Actually should not. isBalance is saying if the value is already formatted rather than if it is a balance. So it may be false. I renamed this component to `AccountDetailCryptoValue` to avoid this confusion.
