### PR TITLE
fix(suite): show ConfirmValueModals's label button in correct circumstances

### LINKED ISSUE #22928: Show Add label in ConfirmValueModal with Secure sync labeling

### PR DESCRIPTION
**Pull request by 5K1PY**
- Show `Add label` if Secure Sync labeling is enabled
- Don't show `Add label` if there are no providers for Legacy labeling

## Related Issue

Resolve #22928

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/receive-labeling&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/receive-labeling&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmValueModal/ConfirmValueModal.tsx [hunk 1]
```diff
@@ -34,14 +34,13 @@ import { QrCode } from 'src/components/suite/QrCode';
...
-import {
-    selectIsMetadataEnabled,
-    selectLabelingDataForSelectedAccount,
-} from 'src/reducers/suite/metadataReducer';
+import { selectLabelingDataForSelectedAccount } from 'src/reducers/suite/metadataReducer';
 import { selectIsActionAbortable } from 'src/selectors/suite/suiteSelectors';
 import { ThunkAction } from 'src/types/suite';
 import { DESTINATION_TAG_GUIDE_PATH } from 'src/views/wallet/send/Options/MiscNetworkOptions/DestinationTag';
 
+import { useLabelingCombined } from '../../../../../hooks/suite/useLabelingCombined';
```
Comment (OriginalEveres) [inline packages/suite/src/components/suite/modals/ReduxModal/ConfirmValueModal/ConfirmValueModal.tsx]: `'../../../../../hooks/suite/useLabelingCombined';` is wierd path. We shoud use `src/hooks/suite/useLabelingCombined`

**Review by OriginalEveres — APPROVED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmValueModal/ConfirmValueModal.tsx [hunk 2]
```diff
@@ -72,15 +70,19 @@ export const ConfirmValueModal = ({
     const { accountLabel } = useSelector(selectLabelingDataForSelectedAccount);
```
Comment (vytick) [inline packages/suite/src/components/suite/modals/ReduxModal/ConfirmValueModal/ConfirmValueModal.tsx]: interesting thing  and completely not related to your changes: `selectLabelingDataForSelectedAccount` is used and destructured twice in this component for different props.
