### PR TITLE
fix new wallet on-demand quota allocation

### LINKED ISSUE #25539: Cannot connect to production relay on new wallets
**Describe the bug**

Quota manager error:

https://github.com/user-attachments/assets/6e2a1bd1-7a6e-42ae-9fbc-e2bef5f99821

Websocket errors:

Image

Image

**Info:**
 - Suite version: desktop 26.3.0 (a328218e82e6078de9ff56b6d6d8cf7282b1a52a)
 - Browser: Trezor Suite 26.3.0
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3W1 2.10.0 universal (revision de4b70e2e89a64f3894dba2124f6ec56e5cbd088)
 - Transport: BluetoothTransport, BridgeTransport 3.2.1

### PR DESCRIPTION
**Pull request by OriginalEveres**
NOTE: this should be cherry-picked into RC

**changes**:
- fixed incosistent naming
- fixed bug with returning the same storage even in write mode

## Notes for QA

- fresh devices should be able to request quota on demand

Resolve https://github.com/trezor/trezor-suite/issues/25539

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/qm/write-mode-cache&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/qm/write-mode-cache&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/qm/write-mode-cache&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 9 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Labeling migration > Migration from Dropbox | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-12T13:27:27.274Z • 9 test(s) total_

<details><summary>Trezor Suite (desktop) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-03-11T15:51:22.090Z • 7 test(s) total_

### CODE REVIEW

File: suite-common/suite-sync-types/src/data/subscribeSuiteSyncData.ts [hunk 1]
```diff
@@ -41,5 +41,5 @@ export type SubscribeSuiteSyncData = (
 >;
 
 export type SubscribeSuiteSyncDataDep = {
-    ensureSuiteSyncData: SubscribeSuiteSyncData;
+    ensureSubscribeSuiteSyncData: SubscribeSuiteSyncData;
```
Comment (OriginalEveres) [inline suite-common/suite-sync-types/src/data/subscribeSuiteSyncData.ts:44]: fixed naming

File: suite-common/suite-sync/src/storage/tests/createEnsureWalletSuiteSyncOn.test.ts
Comment (OriginalEveres) [inline suite-common/suite-sync/src/storage/tests/createEnsureWalletSuiteSyncOn.test.ts:1]: fixed naming

File: suite-common/suite-sync/src/storage/createEnsureStorage.ts [hunk 2]
```diff
@@ -48,10 +51,12 @@ export const createEnsureStorage =
     (deps: EnsureStorageDeps): CreateEnsureStorage =>
     async ({ deviceStaticSessionId, isWriteMode }): ReturnType<CreateEnsureStorage> => {
         const storageId = createStorageIdFromDeviceStaticSessionId(deviceStaticSessionId);
+        const { walletDescriptor } = parseDeviceStaticSessionId(deviceStaticSessionId);
 
         const storage = deps.suiteSyncStorageRepository.get(storageId);
 
-        if (isNotNull(storage)) {
+        // if storage exists and we are not in write mode, return it immediately without refreshing keys or checking quota.
```
Comment (matejkriz) [inline suite-common/suite-sync/src/storage/createEnsureStorage.ts]: useless and outdated comment?

File: suite-common/suite-sync/src/data/__tests__/createEnsureSubscribeSuiteSyncData.test.ts
Comment (OriginalEveres) [inline suite-common/suite-sync/src/data/__tests__/createEnsureSubscribeSuiteSyncData.test.ts:1]: fixing naming

File: suite-common/suite-sync/src/storage/createEnsureStorage.ts [hunk 3]
```diff
@@ -69,23 +74,23 @@ export const createEnsureStorage =
...
+
+        // Set the relay URL if quota is allocated or if storage was not yet initialized.
         if (quotaResult.success || quotaResult.error.type === 'WriteModeRequiredForAllocation') {
-            await newStorage.updateRelayUrl(deps.getRelayUrl());
+            await resolvedStorage.updateRelayUrl(deps.getRelayUrl());
         }
 
-        deps.suiteSyncStorageRepository.set(storageId, newStorage);
+        if (!isNotNull(storage)) {
+            deps.suiteSyncStorageRepository.set(storageId, resolvedStorage);
```
Comment (matejkriz) [inline suite-common/suite-sync/src/storage/createEnsureStorage.ts:98]: nitpick:
﻿﻿This took me quite a while to read... 

But it's basically the same as this, right? 
```ts
const resolvedStorage = () => {
            if (storage) return storage;

            const newStorage = deps.createSuiteStorage({ suiteSyncOwner: owner });
            deps.suiteSyncStorageRepository.set(storageId, newStorage);

            return newStorage;
        }();
```
With the only difference, that your implementation calls the `suiteSyncStorageRepository.set` only after `await resolvedStorage.updateRelayUrl`, but is that important?

What makes it harder to read is `!isNotNull` (negated isNotNull instead of `isNull`) and that the condition is checking existence of `storage` and the setter is setting `resolvedStorage`.

Comment (matejkriz) [reply suite-common/suite-sync/src/storage/createEnsureStorage.ts:98]: I don't see this covered in `createEnsureStorage.test.ts`

File: suite-common/suite-sync/src/storage/createEnsureStorage.ts [hunk 4]
```diff
@@ -48,10 +51,12 @@ export const createEnsureStorage =
...
     async ({ deviceStaticSessionId, isWriteMode }): ReturnType<CreateEnsureStorage> => {
         const storageId = createStorageIdFromDeviceStaticSessionId(deviceStaticSessionId);
+        const { walletDescriptor } = parseDeviceStaticSessionId(deviceStaticSessionId);
 
         const storage = deps.suiteSyncStorageRepository.get(storageId);
 
-        if (isNotNull(storage)) {
+        // if storage exists and we are not in write mode, return it immediately without refreshing keys or checking quota.
+        if (isNotNull(storage) && deps.hasOwnerAllowance(walletDescriptor)) {
             return ok(storage);
```
Comment (OriginalEveres) [inline suite-common/suite-sync/src/storage/createEnsureStorage.ts:65]: **there is a case in which**:
- user starts with new passphrase & has no quota allocated on owner yet
- thus he gets a storage instance and we do early return next time (because cached user instance)

and this is wrong, when user writes a label (thus in write mode) we should allocate the quota if he has no one yet. 

**There are 2 solutions**:
1. is to extend the if with `&& isWriteMode === false` but this would mean that we will dispatch the quota on every write request. That could potentially spam the QM and is not a good practise
2. option is to include the `deps.hasOwnerAllowance` which is a check if user has already allocated quota from QM. In that case we return the storage, because increasing owner storage is handled by `increaseOwnerQuotaThunk`

File: suite-common/suite-sync/src/storage/createEnsureStorage.ts (hunk 3 above)
Comment (OriginalEveres) [reply suite-common/suite-sync/src/storage/createEnsureStorage.ts:98]: yes, thats basically the same.

I'll double check the tests

File: suite-common/suite-sync/src/storage/tests/createEnsureWalletSuiteSyncOn.test.ts [hunk 5]
```diff
@@ -72,7 +72,7 @@ describe(createEnsureWalletSuiteSyncOn.name, () => {
         const deps = createMockDeps<EnsureWalletSuiteSyncOnDeps>({
             getState: () => createMockState([DEVICE_123]),
             refreshSuiteSyncKeys: null,
-            ensureSuiteSyncData: () => Promise.resolve(ensureResult),
+            ensureSubscribeSuiteSyncData: () => Promise.resolve(ensureResult),
             subscriptionStorage: createSubscriptionStorageMock(),
```
[the remark this answers is not in the document]
Comment (matejkriz) [reply suite-common/suite-sync/src/storage/tests/createEnsureWalletSuiteSyncOn.test.ts:75]: @OriginalEveres copilot is right...

File: suite-common/suite-sync/src/createSuiteSyncCompositionRoot.ts [hunk 6]
```diff
@@ -141,7 +144,7 @@ export const createSuiteSyncCompositionRoot = (
         ensureWalletSuiteSyncOn: createEnsureWalletSuiteSyncOn({
             getState: deps.getState,
             refreshSuiteSyncKeys,
-            ensureSuiteSyncData: subscribeSuiteSyncData,
+            ensureSubscribeSuiteSyncData: subscribeSuiteSyncData,
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/createSuiteSyncCompositionRoot.ts]: nit but pls unify the naming so we dont have this:  `subscribeSuiteSyncData => ensureSubscribeSuiteSyncData`

File: suite-common/suite-sync/src/createSuiteSyncCompositionRoot.ts [hunk 7]
```diff
@@ -124,6 +125,8 @@ export const createSuiteSyncCompositionRoot = (
         createSuiteStorage,
         getRelayUrl: toGetter(deps.getState, selectSuiteSyncRelayUrl),
         getDeviceForStaticSessionId,
+        hasOwnerAllowance: walletDescriptor =>
+            selectHasOwnerAllowance(deps.getState(), walletDescriptor),
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/createSuiteSyncCompositionRoot.ts:132]: I think `toGetter` helper shall be exactly for this

Comment (matejkriz) [reply suite-common/suite-sync/src/createSuiteSyncCompositionRoot.ts:132]: But toGetter doesn't accept aprams, right? We would need currying for it, I guess.

Comment (peter-sanderson) [reply suite-common/suite-sync/src/createSuiteSyncCompositionRoot.ts:132]: Hmm. True.. Seems like unfinished business of mine. I thought I did that, ..

Comment (peter-sanderson) [reply suite-common/suite-sync/src/createSuiteSyncCompositionRoot.ts:132]: But maybe lets do it, stuff like this is now one prompt away :D

File: suite-common/suite-sync/src/storage/createEnsureStorage.ts [hunk 8]
```diff
@@ -48,10 +51,11 @@ export const createEnsureStorage =
     (deps: EnsureStorageDeps): CreateEnsureStorage =>
     async ({ deviceStaticSessionId, isWriteMode }): ReturnType<CreateEnsureStorage> => {
         const storageId = createStorageIdFromDeviceStaticSessionId(deviceStaticSessionId);
+        const { walletDescriptor } = parseDeviceStaticSessionId(deviceStaticSessionId);
 
         const storage = deps.suiteSyncStorageRepository.get(storageId);
 
-        if (isNotNull(storage)) {
+        if (isNotNull(storage) && deps.hasOwnerAllowance(walletDescriptor)) {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/createEnsureStorage.ts:64]: I think this shall only take place in write mode

Also I would add a comment to explain it

=> 
```ts
(
    isNotNull(storage) 
    
    // when user tries to write for the first time, we need to recreate the instance
    // and allocate the quota
    && (deps.hasOwnerAllowance(walletDescriptor) || !isWriteMode)
)
```

**Review by matejkriz — APPROVED** [review]
