### PR TITLE
Trading - Fixes

### LINKED ISSUE #23842: Unable to continue revoking USDT approval – missing continue button in revoke flow
**Describe the bug**
When attempting to increase an existing USDT approval in Trezor Suite, users are prompted to revoke the current allowance due to USDT's contract limitations. However, after clicking the revoke button, there is no visible 'Continue' or similar button to proceed. 

**How to reproduce**
1. Go to DEX/Trading in Trezor Suite
2. Try to increase your USDT approval/allowance
3. App prompts to revoke current approval before setting a higher one
4.  No option to proceed — user is stuck, as there is no continue button

**Screenshots**
Missing continue button in revoke USDT spending modal

**Additional context**
- Related to: [#19220](https://github.com/trezor/trezor-suite/issues/19220)
- Requested flow can be seen in Figma: [Revoke then Approve USDT](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4236-5989&t=fsNTebgxEYdgeCr2-4) + [modal](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4230-1842&t=dbFipQsIFgKzPSV1-4)

### LINKED ISSUE #23844: Swap button greyed out with no explanation when only floating-rate offers are present
**Describe the bug**

The Swap button is greyed out with no explanation in many token pairs. It appears to occur when there are no fixed-rate offers available but there are some floating-rate offers. Users are left with no indication as to why the button is disabled, leading to confusion.

**How to reproduce**
1. Go to the Swap screen in Trezor Suite
2. Select certain token pairs (e.g. USDT to LTC)
3. Try to enter an amount to swap
4. Observe that the Swap button is greyed out, but wrong message is shown

**Expected behavior**

A clear explanation to the user about why the Swap button is disabled (e.g. "No fixed-rate offers available, only floating-rate offers are present"). Ideally, the UI should indicate the specific limitation rather than just disabling the button silently.

**Screenshots**
Swap button greyed out with no explanation

Image

### LINKED ISSUE #23851: Buy form doesn't refresh when asset is changed
**Describe the bug**
Buy form doesn't refresh when asset (You buy) is changed.

**How to reproduce**

1. Go to Buy
1. Enter the amount in You pay
1. Select USDT on Ethereum in You buy
1. Wait for quotes to be fetched
1. Select different token on Ethereum in You buy
1. Quotes are not refetched

**Expected behavior**
Form (quotes) should refresh after asset is changed

**Screenshots**

https://github.com/user-attachments/assets/8738276f-8c99-46f4-9d54-4c5d30be0a61

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

This PR fixes several bugs in Trading:

- https://github.com/trezor/trezor-suite/issues/23851
- https://github.com/trezor/trezor-suite/issues/23842
- https://github.com/trezor/trezor-suite/issues/23844
- fixed `Continue` button width in Trading when no receive address was selected (before it was shrank, now it's full width)

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23851
Resolve https://github.com/trezor/trezor-suite/issues/23842
Resolve https://github.com/trezor/trezor-suite/issues/23844

## Screenshots

https://github.com/user-attachments/assets/345da281-31f7-4a35-9b2d-19b16f66a7df

https://github.com/user-attachments/assets/c3ff717f-05b1-471e-8104-6b61ddd1563c

https://github.com/user-attachments/assets/2189e0d2-e9d9-491d-b851-63f364e99cf2

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-fixes&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-fixes&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/trading-fixes&lookback=7)

### CODE REVIEW

**Review by izmy — APPROVED** [review]

File: suite-common/trading/src/reducers/tradingReducer.ts [hunk 1]
```diff
@@ -47,7 +47,6 @@ const tradingSlice = createSliceWithExtraDeps({
                 state.buy.amountLimits = undefined;
                 state.buy.quotes = [];
                 state.buy.quotesRequest = undefined;
-                state.buy.isLoading = false;
```
Comment (cermakjiri) [inline suite-common/trading/src/reducers/tradingReducer.ts:50]: Why? Shouldn't it stop loading on error?

Comment (TomasBoda) [reply suite-common/trading/src/reducers/tradingReducer.ts:50]: I added this line a few months back due to some other functionality, but it seems it's not needed anymore and fixes an issue where the loading indicator in buy was not shown when switching between different networks.
