### PR TITLE
fix(suite): missing images in Guide

### LINKED ISSUE #23049: Support and Feedback form issues with images and borders
**Describe the bug**
Images are not loading in Support and Feedback menu.
No borders of dropdown menu element.
Text field should be white or different color from the background.

Regression from production 25.10.2 where I see images (but no borders).

Image

Image

**Info:**
 - Suite version: desktop 25.11.0 (8110dbc912c6fc457d824a18b169e6c237f19786)
 - Browser: Trezor Suite 25.11.0
 - OS: MacIntel
 - Screen: 2048x1152
 - Device: Trezor T2T1 2.9.1 universal (revision acd56d0113a547e9b5983510b0ce9de079e30e05)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Reintroduce images `understand@2x.png` and `recovery@2x.png` that were removed in https://github.com/trezor/trezor-suite/pull/22265

This was very old React code, predating our design system, so it used a custom way to reference the image path rather than using the `Image` component. That's why it couldn't have been easily noticed that these images are not unused, and were deleted by mistake.

:point_right: So I updated this UI to use the `Image` component, and rationalized the CSS around it.

I see that there are no other such brokencases in our codebase :heavy_check_mark:

## Related issues

Resolve https://github.com/trezor/trezor-suite/issues/23049

### Fixed

fixed

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/suite-guide-missing-images&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/guide/SupportFeedbackSelection.tsx [hunk 1]
```diff
@@ -29,12 +29,12 @@ const SectionHeader = styled.h3`
 `;
 
 const SectionButton = styled.button<{ $hasBackground?: boolean }>`
-    left: auto;
```
Comment (Lemonexe) [inline packages/suite/src/components/guide/SupportFeedbackSelection.tsx:32]: this ofc didn't do anything with the default `position: static` 🤦

File: packages/suite/src/components/guide/SupportFeedbackSelection.tsx [hunk 2]
```diff
@@ -29,12 +29,12 @@ const SectionHeader = styled.h3`
...
     cursor: pointer;
     border-radius: ${borders.radii.xs};
     width: 100%;
     margin: 0 0 10px;
     display: flex;
+    gap: 10px;
```
Comment (Lemonexe) [inline packages/suite/src/components/guide/SupportFeedbackSelection.tsx:37]: instead of the `margin-left`

**Review by seibei-iguchi — APPROVED** [review]
