### PR TITLE
Message system - experiment features view

### LINKED ISSUE #20481: Message system experiments display your group
**Describe the bug**
Add button to show all active experiments and display your group in debug mode for message system experiments.  

Image

**Info:**
 - Suite version: desktop 25.8.0 (0f04977ce64b503a1017ae468dbe8be90a983ce5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.8.0 Chrome/138.0.7204.97 Electron/37.2.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.9.0 universal (revision a09e6f04d4204607d821d9b742dcf7ffe9c4e2f5)
 - Transport: BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by izmy**
## Description

Introduces a new UI for displaying experimental features.

- Added bar track visualization of group distribution
- Highlighted the assigned group for the current user
- Better validation when group percentages do not sum to 100
- Better DX

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20481

## Screenshots:

image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/message-system-experiments-view&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/message-system-experiments-view&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/message-system-experiments-view&lookback=7)

### CODE REVIEW

File: suite-common/message-system/src/experimentUtils.ts [hunk 1]
```diff
@@ -24,25 +24,28 @@ export const getInclusionFromInstanceId = (instanceId: string, experimentId: Exp
     return getIntegerInRangeFromString(combinedId, 100);
 };
 
+export function buildExperimentGroupRanges(groups: ExperimentsGroupsType) {
+    let cursor = 0;
```
Comment (tomasklim) [inline suite-common/message-system/src/experimentUtils.ts:28]: nit: 
it would be possible to use `reduce` and `accumulator` for cursor but maybe it is overkill

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm/MessageSystemForm.tsx [hunk 2]
```diff
@@ -93,12 +93,14 @@ export const MessageSystemForm = () => {
...
-        const bucket = parsedData.conditions[0] as Record<keyof Condition, unknown>;
-        const used = new Set(Object.keys(bucket));
+        const conditions = parsedData.conditions[0] as Record<keyof Condition, unknown>;
+        const used = new Set(Object.keys(conditions));
 
-        return CONDITION_OPTIONS.filter(o => !used.has(o.value));
+        return CONDITION_OPTIONS.filter(option => !used.has(option.value));
     }, [parsedData]);
 
+    console.log({ availableConditionOptions });
```
Comment (tomasklim) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm/MessageSystemForm.tsx]: console.log

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemExperiment/MessageSystemExperiments.tsx [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+};
+
+export const MessageSystemExperiments = ({
+    experiments,
+    onCloseModal,
+}: MessageSystemManagerProps) => {
+    const allValidExperiments = useSelector(selectAllValidExperiments);
+    const instanceId = useSelector(selectAnalyticsInstanceId);
+
+    const [showActive, setIsActive] = useState<boolean>(true);
```
Comment (tomasklim) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemExperiment/MessageSystemExperiments.tsx]: nit: [isActive, setIsActive]

**Review by tomasklim — APPROVED** [review]
Wow, amazing!  
4cdb6055396941b5e52a9d93caed3e13

File: suite-common/message-system/src/experimentUtils.ts (hunk 1 above)
Comment (izmy) [reply suite-common/message-system/src/experimentUtils.ts:28]: Tried a reduce + accumulator, but it made the code harder to read... so I would stick with the current map + cursor.
