### PR TITLE
fix: filtering in the CoinControll correctly filters legacy addresses as they useses UPPER_CASE letters

### LINKED ISSUE #16970: Search in coin control of BTC Legacy accounts section does not work as expected.
**Describe the bug**
Search in coin control Legacy accounts section does not work as expected.
Results are filtered out even they shouldnt 
I was not able to reproduce it in search in transaction history or in other accounts probably as they only use lower case in transaction ids.

**Steps to reproduce:**
1. Load wallet with transaction history and funds in BTC legacy accounts
2. Navigate to send section and open coin control
3. Try to search for input/output

**Info:**
 - Suite version: desktop 25.2.1 (4b92a096a8ac719cea3917d5c0fba5f6d2c97810)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.2.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.8 regular (revision 592590cf66a9b62dfeee7e4d2afb6e01005e5b2c)
 - Transport: BridgeTransport 3.0.0-bundled.25.2.1

**Screenshots:**

https://github.com/user-attachments/assets/939c637e-f028-46e4-ac95-00de3b3896c3

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/16970

### CODE REVIEW

File: packages/suite/src/utils/wallet/filterAndCategorizeUtxosUtils.ts [hunk 1]
```diff
@@ -23,8 +23,8 @@ export const filterAndCategorizeUtxos = ({
 }: FilterAndCategorizeUtxosParams) => {
     const lowerCaseSearchQuery = searchQuery.toLowerCase();
     const filterUtxos = (utxo: Utxo) =>
-        utxo.address.includes(lowerCaseSearchQuery) ||
-        utxo.txid.includes(lowerCaseSearchQuery) ||
+        utxo.address.toLowerCase().includes(lowerCaseSearchQuery) ||
+        utxo.txid.toLowerCase().includes(lowerCaseSearchQuery) ||
```
Comment (peter-sanderson) [inline packages/suite/src/utils/wallet/filterAndCategorizeUtxosUtils.ts:27]: `txid` is lowercase on legacy account as well, but just for sake of defensive programming lets lowercase it as well, who knows how it can be on some other networks

File: packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts [hunk 2]
```diff
@@ -1,28 +1,46 @@
-import * as fixtures from '../__fixtures__/filterAndCategorizeUtxosFixture';
```
Comment (peter-sanderson) [inline packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts:1]: I really don't like those `*` default exports so I improved it a bit

File: packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts [hunk 3]
```diff
@@ -1,28 +1,46 @@
...
         });
     });
+
+    it('filters tle legacy addresses with uppercase letters with lowercase query', () => {
+        const categorized = filterAndCategorizeUtxos({
+            searchQuery: '1GD',
+            dustUtxos: [],
+            spendableUtxos: [],
+            lowAnonymityUtxos: [],
+            utxos: [{ ...baseUtxo, address: 'mvbu1Gdy8SUjTenqerxUaZyYjmveZvt33q' }],
```
Comment (peter-sanderson) [inline packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts:38]: I was thinking about putting this into fixtures but TBH I think this pattern of huge fixture files makes tests less underrstandable and its harder to navigate there. 

I like when test is clear and it is obvious on first site what is tested and what is expected,

File: packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts [hunk 4]
```diff
@@ -1,28 +1,46 @@
...
-            const categorized = filterAndCategorizeUtxos.filterAndCategorizeUtxos(params);
+    it('filters and categorizes correctly while searching by label', () => {
+        filterAndCategorizeUtxosFixtures.filterByLabel.forEach(({ params, checkResult }) => {
+            const categorized = filterAndCategorizeUtxos(params);
 
             expect(checkResult(categorized)).toBe(true);
         });
     });
+
+    it('filters tle legacy addresses with uppercase letters with lowercase query', () => {
```
Comment (Lemonexe) [inline packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts]: nit: typo "tle", idk what word was supposed to be there

**Review by Lemonexe — APPROVED** [review]
Codewise LGTM, did not test, but it has great coverage now

File: packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts (hunk 4 above)
Comment (peter-sanderson) [reply packages/suite/src/utils/wallet/__tests__/filterAndCategorizeUtxosUtils.test.ts]: its `the` i'll fix it :) thanks!
