### PR TITLE
fix(trade): refresh trading offers after app visibility restore

### LINKED ISSUE #19124: Trade offers do not refresh, and the timer goes negative.
**Describe the bug**
Trade offers do not refresh, and the timer goes into negative numbers.  

Image

**Info:**
 - Suite version: web 25.6.0 (de0dd25795ae153f4d7d9a3af83abf6103c62449)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.10 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by sherpaPSX**
## Description
Fixes a trading offers refresh regression where the countdown could go below zero and offers did not refresh after the timer elapsed while the app window was not visible.

Changes included:
- stop the trading refresh timer when the refresh interval has elapsed while app visibility is false
- when visibility is restored and the interval is already elapsed, trigger quote refresh immediately
- clamp the refresh countdown/progress UI to prevent rendering negative values

## Notes for QA
Please verify in Buy/Sell/Exchange offers flows:
1. Open offers and wait for the refresh countdown.
2. Hide/minimize the app (or switch tab) before countdown reaches zero, wait until interval elapses, then return.
3. Confirm offers refresh after returning to visible state.
4. Confirm the timer never shows negative values.
5. Confirm no regressions on confirm/retry pages (timer should remain stopped there).

## Related Issue
Resolve #19124

## Screenshots:
N/A (behavioral fix)

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-offers-refresh-19124&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-offers-refresh-19124&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/trading-offers-refresh-19124&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 9 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Labeling migration > Migration from Dropbox | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-18T09:23:15.459Z • 9 test(s) total_

<details><summary>Trezor Suite (desktop) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-03-17T06:43:47.767Z • 7 test(s) total_

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingInitializer.ts [hunk 1]
```diff
@@ -36,25 +36,43 @@ export const useTradingInitializer = ({
         (callback: () => Promise<void>) => {
             if (isLoading) return;
 
-            if (!timer.isLoading && !timer.isStopped) {
```
Comment (jbazant) [inline packages/suite/src/hooks/wallet/trading/form/common/useTradingInitializer.ts:39]: **nitpick (non-blocking):** ‏Is there a reason to not have tests for this?

File: packages/suite/src/views/wallet/trading/common/TradingRefreshTime.tsx [hunk 2]
```diff
@@ -44,8 +44,9 @@ export const TradingRefreshTime = ({
     refetchInterval,
     label,
 }: TradingRefreshTimeProps) => {
-    const remaining = refetchInterval - seconds;
-    const progress = (remaining / refetchInterval) * 100;
+    const remaining = Math.max(refetchInterval - seconds, 0);
+    const progress =
+        refetchInterval > 0 ? Math.min(Math.max((remaining / refetchInterval) * 100, 0), 100) : 0;
```
Comment (jbazant) [inline packages/suite/src/views/wallet/trading/common/TradingRefreshTime.tsx]: **nitpick (non-blocking):** ‏In coinjoin there is a utility `clamp` function

```ts
const clamp = (value: number, min = Number.NEGATIVE_INFINITY, max = Number.POSITIVE_INFINITY) =>
    Math.min(Math.max(value, min), max);
```

maybe it would be worth to extract the clamping logic here as well.

**Review by jbazant — APPROVED** [review]
LGTM, just two nits. (Definitely non-blocking ones)

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingInitializer.ts (hunk 1 above)
Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/common/useTradingInitializer.ts:39]: Test added

File: packages/suite/src/views/wallet/trading/common/TradingRefreshTime.tsx (hunk 2 above)
Comment (sherpaPSX) [reply packages/suite/src/views/wallet/trading/common/TradingRefreshTime.tsx]: done with tests
