### PR TITLE
fix: incorrect amount formatting for FiatValue in Cancel Transaction flow

### LINKED ISSUE #17171: Incorrect return to your wallet fiat value during canceling transaction
**Describe the bug**
Incorrect return to your wallet fiat value during canceling transaction

**Steps to reproduce:**
1. Send tx
2. try to cancel tx
3. Observe `Return to your wallet` fiat value 

**Info:**
 - Suite version: desktop 25.3.0 (669cfe48f7e295810d0abdcc96821c7dc58333d9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.3.0 Chrome/132.0.6834.194 Electron/34.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.8 regular (revision 592590cf66a9b62dfeee7e4d2afb6e01005e5b2c)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

Image

Image

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolve: https://github.com/trezor/trezor-suite/issues/17171

image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/CancelTransaction/CancelTransaction.tsx [hunk 1]
```diff
@@ -106,13 +108,13 @@ export const CancelTransaction = ({ tx, selectedAccount }: CancelTransactionProp
...
                             disableHiddenPlaceholder
-                            value={formatNetworkAmount(output.amount.toString(), tx.symbol)}
+                            value={formattedOutputAmount}
                             symbol={tx.symbol}
                         />
                         <Text variant="tertiary" typographyStyle="label">
                             <FiatValue
                                 disableHiddenPlaceholder
-                                amount={output.amount.toString()}
+                                amount={formattedOutputAmount}
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/CancelTransaction/CancelTransaction.tsx:117]: Fiat Value requires amount in `BTC` not sats

**Review by komret — APPROVED** [review]
