### PR TITLE
fix(trade): crashing app

### LINKED ISSUE #14578: Trading - TypeError: Cannot read properties of undefined (reading 'split')
Sentry Issue: [TREZOR-SUITE-111C](https://satoshilabs.sentry.io/issues/5911272253/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'split')
  at parseCryptoId (@trezor/suite-build/../suite/src/utils/wallet/coinmarket/coinmarketUtils.ts:46:28)
  at CoinmarketCoinLogo (@trezor/suite-build/../suite/src/views/wallet/coinmarket/common/CoinmarketCoinLogo.tsx:14:44)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
Fixed sentry error that causes the app crashing

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/14578

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ export const CoinmarketInfoItem = ({
         {type === 'exchange' || isReceive ? (
             <Column alignItems="flex-end" gap={spacings.xxxs}>
                 <Row gap={spacings.xs}>
-                    <CoinmarketCoinLogo cryptoId={currency!} size={20} />
+                    {currency && <CoinmarketCoinLogo cryptoId={currency} size={20} />}
                     <CoinmarketCryptoAmount amount={amount} cryptoId={currency!} />
```
Comment (LukasRada) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx]: Should we handle CoinmarketCryptoAmount's currency as well?
```suggestion
                    {currency && <CoinmarketCryptoAmount amount={amount} cryptoId={currency} />}
```

**Review by LukasRada — DISMISSED** [review]

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx (hunk 1 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx]: Nice catch, fixed

**Review by tomasklim — APPROVED** [review]
