### PR TITLE
23653 mobile trade wrong ordering of quotes

### LINKED ISSUE #23653: Mobile Trade: Wrong ordering of quotes
We order incoming quotes based on the rate even though they are already ordered correctly on backend. 

It should not be locally reordered

**Expected behavior**
- quotes are not reordered locally
- best quote for each payment method (buy/sell) is selected as a first one in the array
- swap quotes are also not reordered
- order for the same parameters should be the same for desktop and for mobile

**Additional context**
- dont use getBestRatedQuote for selecting the best quote. It selects best quote by rate but not according to smart routing.

### PR DESCRIPTION
**Pull request by jbazant**
## Description

- Never reorder quotes on frontend.
- Removed unused trading selectors.
- 

## Related Issue

Resolve #23653

## Screenshots:

Simulator Screenshot - iPhone 16e - 2025-12-11 at 09 13 11

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=23653-mobile-trade-wrong-ordering-of-quotes&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=23653-mobile-trade-wrong-ordering-of-quotes&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=23653-mobile-trade-wrong-ordering-of-quotes&lookback=7)

### CODE REVIEW

**Comment by jbazant** [comment]
@coderabbitai review

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/trading-state/src/selectors/buySelectors.ts [hunk 1]
```diff
@@ -135,17 +134,15 @@ export const selectBuyBestQuotesForAvailablePaymentMethods = createMemoizedSelec
 
             const existingQuotes = quotesByPaymentMethodMap.get(paymentMethod);
             if (!existingQuotes) {
```
Comment (vytick) [inline suite-native/trading-state/src/selectors/buySelectors.ts]: nit: 
```suggestion
// we only want one quote per payment method (and the 1st is considered the best)
            if (!existingQuotes) {
                quotesByPaymentMethodMap.set(paymentMethod, quote);
            }
```

File: suite-native/trading-state/src/selectors/sellSelectors.ts [hunk 2]
```diff
@@ -85,17 +84,15 @@ export const selectSellBestQuotesForAvailablePaymentMethods = createMemoizedSele
 
             const existingQuotes = quotesByPaymentMethodMap.get(paymentMethod);
             if (!existingQuotes) {
```
Comment (vytick) [inline suite-native/trading-state/src/selectors/sellSelectors.ts]: similar nit

**Review by vytick — APPROVED** [review]
Tested against desktop and it now delivers the same order 👌

File: suite-native/trading-state/src/selectors/buySelectors.ts (hunk 1 above)
Comment (jbazant) [reply suite-native/trading-state/src/selectors/buySelectors.ts]: Updated in 3c09d11cdb76bd2fb90fb4cb9ed4f186519228ac.

File: suite-native/trading-state/src/selectors/sellSelectors.ts (hunk 2 above)
Comment (jbazant) [reply suite-native/trading-state/src/selectors/sellSelectors.ts]: Updated in 3c09d11cdb76bd2fb90fb4cb9ed4f186519228ac.

File: suite-native/trading-state/src/selectors/buySelectors.ts [hunk 3]
```diff
@@ -129,23 +128,17 @@ export const selectBuyBestQuotesForAvailablePaymentMethods = createMemoizedSelec
     quotes => {
         const allQuotesByPaymentMethodMap = quotes.reduce((quotesByPaymentMethodMap, quote) => {
```
Comment (vytick) [inline suite-native/trading-state/src/selectors/buySelectors.ts]: nit: `allQuotesByPaymentMethodMap` should be named differently since it now contains only one quote per method

File: suite-native/trading-state/src/selectors/sellSelectors.ts [hunk 4]
```diff
@@ -79,23 +78,17 @@ export const selectSellBestQuotesForAvailablePaymentMethods = createMemoizedSele
     quotes => {
         const allQuotesByPaymentMethodMap = quotes.reduce((quotesByPaymentMethodMap, quote) => {
```
Comment (vytick) [inline suite-native/trading-state/src/selectors/sellSelectors.ts]: nit: `allQuotesByPaymentMethodMap` should be named differently since it now contains only one quote per method

**Review by vytick — APPROVED** [review]

File: suite-native/trading-state/src/selectors/buySelectors.ts (hunk 3 above)
Comment (jbazant) [reply suite-native/trading-state/src/selectors/buySelectors.ts]: Fixed in 1ad4f69b4e5890f1cf02029549986f7f8c0f0a37.

File: suite-native/trading-state/src/selectors/sellSelectors.ts (hunk 4 above)
Comment (jbazant) [reply suite-native/trading-state/src/selectors/sellSelectors.ts]: Fixed in 1ad4f69b4e5890f1cf02029549986f7f8c0f0a37.

**Review by vytick — APPROVED** [review]
