### PR TITLE
fix(coinmarket): Fix address label not showing in dropdown

### LINKED ISSUE #9532: Address label not showing in dropdown
**Describe the bug**
When user sets a label for any bitcoin or bitcoin-like receiving address, the label is then not showing in the exchange flow.

**How to reproduce**
- Open any BTC account
- Go to Receive
- Set a label for any of the used addresses
- Open Ethereum account
- Select Trade and Exchange, compare offers and choose deal
- Open Receive address dropdown

**Expected behavior**
Instead of the address, user will see their label, in Exchange flow, Buy and DCA.

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by FreeWall**
Fix address label not showing in dropdown.

## Description

When user sets a label for any bitcoin or bitcoin-like receiving address, the label is then not showing in the exchange flow.

## Related Issue

Resolve #9532 

## Screenshots:
image

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx [hunk 1]
```diff
@@ -87,6 +89,9 @@ export const AddressOptions = <TFieldValues extends AddressOptionsFormState>({
     const addresses = account?.addresses;
     const addressDictionary = useAccountAddressDictionary(account);
     const value = address ? addressDictionary[address] : undefined;
+    const accountMetadata = useSelector(
+        state => account && selectLabelingDataForAccount(state, account.key),
+    );
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx]:
```suggestion
    const accountMetadata = useSelector(
        state => selectLabelingDataForAccount(state, account?.key),
    );
```

If this component can be rendered without `account`
I believe it would be better to modify `selectLabelingDataForAccount` so that it accepts `undefined` as a key and handle it inside the method instead of this conditional selector

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx (hunk 1 above)
Comment (dahaca) [reply packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx]: Another option is to simply pass `account?.key || ''`

Comment (mroz22) [reply packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx]: if you are about to make changes to selector, please consider changes in selectors in this branch https://github.com/trezor/trezor-suite/pull/9130 so that I don't have to solve too many conflicts :D

Comment (FreeWall) [reply packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx]: fixed by `account?.key || ''` as also used in other places

**Review by tomasklim — APPROVED** [review]
