### PR TITLE
Transport device disconnected

### LINKED ISSUE #15336: node bridge - another case of segfault 11
1. get address 
2. show address on device active
3. disconnect device 
4. node-bridge dies 

```
@trezor/transport-bridge Handling request for POST /release/3
@trezor/transport-bridge usb: closeDevice. device.opened: true
@trezor/transport-bridge usb: device.releaseInterface: 0
@trezor/transport-bridge Request POST /release/3 aborted
@trezor/transport-bridge usb: releaseInterface error Error: reset error: Error: LIBUSB_ERROR_TIMEOUT. device: {"productName":"TREZOR","manufacturerName":"SatoshiLabs","serialNumber":"C320C738E14062788C37A51E","vendorId":4617,"productId":21441,"deviceVersionMajor":1,"deviceVersionMinor":0,"opened":true}
@trezor/transport-bridge usb: device.close
Segmentation fault: 11
```

it looks like that we are trying to releaseInterface for a device that is no longer there but we don't know about it because disconnect event is not fired in this case.

the culprit causing it is this https://github.com/trezor/trezor-suite/pull/14092/files#diff-c3affa910cc3a7ed65bcf910b11dc07b7407c5ba91394f76b80f14677a3c14faR369-R372

### PR DESCRIPTION
**Pull request by mroz22**
- 1st commit - narrow error cases from all node-usb and web-usb and convert them to "device disconnected during action" in the same way legacy bridge does. This helps with proper error handling on the trezor-connect layer. 
- 2nd commit - do not release disconnected devices.
     - Trying to do this causes #15336 on my machine (mac-arm). I am unaware of anyone else who could reproduce it locally.
     - The legacy bridge is okay with it, and I haven't found out yet what the key difference is. But anyway, it doesn't feel right to me to release devices that are no longer present. The only possible problem this may cause could be when we false positively handle an error as a disconnected device and omit proper clean up. 
     - Here is a little table where I tested the scenario explained in #15336 and it worked for me locally.

 | fixes #15336  	|   legacy bridge	| node bridge  	| webusb  	|
  |---	|---	|---	|---	|
  | enable labelling - button request - disconnect    	|   	|   	|   	|  
  | get address - button request disconnect  	|   	|   	|   	|  
-  3rd commit - split the 'unacquired screen' into two 1] unacquired 2] device-used-elsewhere 
    - now there is a common "unacquired" screen. Unacquired here means that features of the device are not known because some bug happened. There is a "Try again" button. image
    - then there is a special case of "used-elsewhere" screen that appears if we know `device.transportSessionOwner`. image
    - todo: maybe it could be shown also when `device.used = true`? This way this screen never renders for the legacy bridge since it never returns `transportSessionOwner`.
- 4th commit - rework device.run error handling
    - in general, there are the following categories of errors: 
        - recoverable -> show try again button
        -  non-recoverable -> don't show button. only maybe reloading or reconnect could help
        - device disconnected -> do nothing. `todo: maybe we should enumerate in this case to be sure that it really disconnected`?
- 5th commit - thanks to previous changes, unreadable device state is now better targeted and we don't need to show that many troubleshooting tips anymore.  
    - unreadable non-hid device. this is not recoverable. This is typically the case of missing synchronization between apps for whatever reason.
    - image
    - webusb + unreadable hid device 
    - image
    - unreadable hid device + suite desktop - allows to toggle legacy bridge 
    - image

related issues:
- #15336 
- #15676
- #15480

### CODE REVIEW

File: packages/suite/src/utils/suite/prerequisites.ts [hunk 1]
```diff
@@ -28,6 +28,9 @@ export const getPrerequisiteName = ({ router, device, transport }: GetPrerequisi
         return 'device-disconnect-required';
     }
 
+    if (device.type === 'unacquired' && device?.transportSessionOwner)
```
Comment (mroz22) [inline packages/suite/src/utils/suite/prerequisites.ts:31]: todo: device.used ?

**Review by marekrjpolak — APPROVED** [review]
No objections from me.
