### PR TITLE
fix(suite): allow to verify change address

### LINKED ISSUE #5342: Enable sign message using change address
It used to be possible to sign messages using a change address. Now the GUI has been updated with a drop-down menu instead of copy-pasting the address in. Change addresses are not available in the menu, so you can't sign messages with them.

**How to reproduce**

1. Go to 'sign & verify'
2. Click on 'address'
3. Impossible to select the address you want to use
4. You have to use Electrum instead

**Expected behavior**
Allow making signatures with all the addresses that are part of the wallet.

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

Allows for sign and verify of the change addresses

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/5342

## Screenshots:
image

Or

image

### CODE REVIEW

File: packages/suite/src/hooks/wallet/sign-verify/useSignAddressOptions.ts [hunk 1]
```diff
@@ -59,30 +63,38 @@ export const useSignAddressOptions = (
 
     const { translationString } = useTranslation();
 
-    const groupedOptions = useMemo(
-        () =>
-            Object.entries(
-                Object.values(signAddresses).reduce<{
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/wallet/sign-verify/useSignAddressOptions.ts:65]: I really hate this nesting, Its hard to read and hard to orient

**Review by jvaclavik — APPROVED** [review]
