### PR TITLE
Fix SecurityCheck displaying when not initialRun

### LINKED ISSUE #15881: Asked if you ever used device after you just reconnect device
**Describe the bug**
Asked if you ever used device after you just reconnect device.
Expected behavior is ask only once when connecting device for first time

**Steps to reproduce:**
1. Connect and discover device
2. Change behavior in `Settings/Device` `Wallet loading` switch
3. Reconnect device

**Info:**
 - Suite version: desktop 24.12.1 (0d4070d9dcac69cfad8e208ed8acc09f89a5c985)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.6 regular (revision 17f2a3256b2631823c2bad1855fab61b27985fd2)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/14aae597-5bbb-4398-b3f8-0e11faa83a8f

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

:eyes: CR recommended commit by commit 

- eb25f5c3 fix root cause, [described in this comment](https://github.com/trezor/trezor-suite/pull/17259/commits/8643f89cb205b8c7c078df656f12dc265638940d#r1971844946)
- eaf52789 extract component `LoggedOutSidebar`, as it is used equally by `WelcomeLayout` & `LoggedOutLayout`

## Related Issue

Resolve #15881

## Screenshots:

The most simple reproduction fixed:
[easier bug fixed.webm](https://github.com/user-attachments/assets/898f61e6-802a-4b47-bfbd-14da6d89c1de)

The whole flow. BTW I noticed unrelated #17261, that's why I need to load `/` path at 0:12)
[fixed.webm](https://github.com/user-attachments/assets/e5149dea-0cd5-44fa-a162-57723c149ce8)

### CODE REVIEW

File: packages/suite/src/components/suite/layouts/LoggedOutSidebar.tsx [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+                                />
+                            </Nav>
+                            <QuickActions hideUpdateStatusBar isSidebarCollapsed />
+                        </Column>
+                    </TrafficLightOffset>
+                </SidebarNavColumn>
+            </ElevationUp>
+        </SidebarWrapper>
+    );
+};
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/LoggedOutSidebar.tsx:61]: In 5b74098bea0d08853a19c3a85ee4fa2d86d2f78b, the only thing I changed during the move was rename components:
- `WelcomeWrapper` → `SidebarWrapper`
- `WelcomeNavColumn` → `SidebarNavColumn`
(not just Welcome, but LoggedOut too! Though they're local only, so no need for overly specific names)

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx [hunk 2]
```diff
@@ -74,6 +76,9 @@ const WelcomeNavColumn = styled.div<{ $elevation: Elevation; $minWidth: number }
 export const LoggedOutSidebar = () => {
     const { elevation } = useElevation();
 
+    const isInitialRun = useSelector(selectIsInitialRun);
+    const startRoute: Route['name'] = isInitialRun ? 'suite-start' : 'suite-index';
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx]: The root cause of the problem:
`LoggedOutSidebar` is rendered by `WelcomeLayout` during onboarding, but also by `LoggedOutLayout` when device is disconnected.
Just clicking the Trezor Icon during disconnected device [is the easiest reproduction of the bug](https://github.com/trezor/trezor-suite/issues/15881#issuecomment-2685420868).
When onboarding has been completed (initialRun=false), it should instead lead to `suite-index`.

:warning: but **not** when still in onboarding (initialRun=true), because Dashboard is not meant to be displayed under the `WelcomeLayout`. It crashes React because of missing `ResponsiveContextProvider` (present in `SuiteLayout`). Adding the provider to Welcome is not a solution, because the Dashboard just doesn't make sense to be displayed during Onboarding!

I believe this is the proper fix.

**Review by peter-sanderson — APPROVED** [review]
LGTM, not tested
