### PR TITLE
Fix: intermediary and compatible

### LINKED ISSUE #21267: Cannot update FW on devices with BL older then 1.12.0
Cannot update FW on devices with BL older then 1.12.0

**Info:**
 - Suite version: desktop 25.9.1 (3e5133fe89674211936afd7db19e62914598b471)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.9.1 Chrome/138.0.7204.185 Electron/37.2.6 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T1B1 1.11.2 universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by karliatto**
## Description

It should properly select intermediaries and it should offer to update to T1B1 devices with FW version that requires intermediary.

I also add some test cases to make sure this stays solid and refactor it a bit for better readability.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21267

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/intermediary-and-compatible&lookback=7)

### CODE REVIEW

File: packages/connect/src/data/firmwareInfo.ts [hunk 1]
```diff
@@ -351,37 +351,32 @@ const getCurrentVersion = (features: Features): CurrentVersion => {
...
-                  versionUtils.isNewer(inter.min_firmware_version, firmwareVersion),
-              )
-            : undefined;
+
+    const { bootloaderVersion, firmwareVersion } = getCurrentVersion(features);
+
+    const currentVersion = features.bootloader_mode ? bootloaderVersion : firmwareVersion;
+    const minVersionKey = features.bootloader_mode
+        ? 'min_bootloader_version'
+        : 'min_firmware_version';
```
Comment (marekrjpolak) [inline packages/connect/src/data/firmwareInfo.ts:370]: Definitely better readable than before :+1:

File: packages/connect/src/data/firmwareInfo.ts [hunk 2]
```diff
@@ -589,6 +597,13 @@ export const getFirmwareLocation = ({
     const isRealBundled = !bundledBaseUrl.includes('data.trezor.io');
     const bundledVersion = getBundledFirmwareVersion(deviceModel, firmwareType);
 
+    if (intermediaryVersion) {
+        return {
+            baseUrl: bundledBaseUrl,
+            path: `firmware/${deviceModel.toLowerCase()}/${firmwareName}`,
+        };
+    }
+
```
Comment (marekrjpolak) [inline packages/connect/src/data/firmwareInfo.ts]: From what I understand, shouldn't this be part of the condition below? 

I mean, the return value is the same, `bundledBaseUrl && isRealBundled` part of the condition could be valid here as well, and the last part can be simplified to something like `(intermediaryVersion || (bundledVersion === versionString)` ? Also, `versionString` can be always `firmwareVersion.join('.')` as in intermediary case it's unused.

File: packages/connect/src/data/firmwareInfo.ts [hunk 3]
```diff
@@ -497,40 +496,49 @@ export const getReleaseInfo = ({
...
+        );
+        // If an alternative is found, use it. Otherwise, we proceed with the original.
+        if (alternativeRelease) {
+            suitableRelease = alternativeRelease;
+        }
+    }
 
     const intermediary = getIntermediaryMessageRelease(features);
-    const isBitcoinOnlyAvailable = getIsBitcoinOnlyAvailable(features);
+    const finalTargetRelease = intermediary ? release : suitableRelease;
```
Comment (marekrjpolak) [inline packages/connect/src/data/firmwareInfo.ts:536]: This ternary condition can be probably moved above, as in `if (!isCompatible && !intermediary) {...` ? Then, `suitableRelease` can be used directly instead of `finalTargetRelease`.

Comment (marekrjpolak) [reply packages/connect/src/data/firmwareInfo.ts:536]: Also, to be sure: This means that when intermediary firmware is needed to install, the last known release is always advertised even if incompatible with the current version?

File: packages/connect/src/data/firmwareInfo.ts [hunk 4]
```diff
@@ -480,6 +475,10 @@ export const getReleaseInfo = ({
     const { rollout_probability } = conditions;
     const shouldBeOffered = calculateShouldOfferRelease(rollout_probability, features.device_id);
 
+    if (requiresIntermediary && intermediary) {
+        isNewer = true;
+    }
```
Comment (marekrjpolak) [inline packages/connect/src/data/firmwareInfo.ts:480]: To be sure: This means that whenever an intermediary firmware is needed to install, it is signalled that there's update available?

Comment (karliatto) [reply packages/connect/src/data/firmwareInfo.ts:480]: Yes.

File: packages/connect/src/data/firmwareInfo.ts (hunk 2 above)
Comment (karliatto) [reply packages/connect/src/data/firmwareInfo.ts]: I see,you are right, what about this https://github.com/trezor/trezor-suite/pull/21330/commits/1ec33d267528014f485706a209de1629aebb2a6f ?

File: packages/connect/src/data/firmwareInfo.ts (hunk 3 above)
Comment (karliatto) [reply packages/connect/src/data/firmwareInfo.ts:536]: Yes, that is what I understand, when `intermediary` FW we use latest available since the intermediary should allow to install to latest FW.

Comment (karliatto) [reply packages/connect/src/data/firmwareInfo.ts:536]: I think that should be the case for T1B1, but if we use intermediary FWs more often in the future we might need to add more information to those intermediary FW like if there is any limit to what they make possible to update.

**Review by marekrjpolak — APPROVED** [review]
Seems to work :+1:
