### PR TITLE
fix(suite): Enable account details when discovery fails

### LINKED ISSUE #17353: Enable account details when offline/discovery fails
Users should be able to access Account Detail and Show public key even if there was discovery error.

Currently it gets stuck on the Account discovery error together with the Account Overview. 

- fix detail page
- fix also the header, it should not be called `Dashboard`
- fix also account in sidebar, it should not have balance and fiat. Maybe a warning icon should be there

Data are available in redux
Image

Note: What works might vary per network.

### PR DESCRIPTION
**Pull request by izmy**
## Description

When an account ends in a _discovery error_, it is now still possible to open **Details** and access account-specific information.

Additionally:
- The page header is fixed – instead of showing *Dashboard*, it now correctly displays the **account name**
- In the sidebar, accounts with a discovery error no longer display a balance and are marked with a **warning icon**
- Components related to **WalletLayout** were refactored to improve readability and maintainability

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17353

## Screenshots:

image

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/account-details-discovery-error&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/account-details-discovery-error&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/account-details-discovery-error&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageHeader.tsx [hunk 1]
```diff
@@ -34,33 +34,42 @@ const Container = styled.div`
...
-    const isAccountTabPage = useSelector(selectIsAccountTabPage);
     const routeName = useSelector(selectRouteName);
+    const isAccountTabPage = useSelector(selectIsAccountTabPage);
 
     // handle moment when children are not rendered yet in the Trade section
-    const isTradeSection = routeName?.includes('wallet-trading');
+    const isTradeSection = !!routeName?.includes('wallet-trading');
+
+    if (isTradeSection || children != null) {
+        return <Container>{children ?? null}</Container>;
```
Comment (matusbalascak) [inline packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageHeader.tsx]: no need to `?? null` here

File: packages/suite/src/views/wallet/details/index.tsx [hunk 2]
```diff
@@ -47,25 +48,22 @@ const DetailsRow = ({ title, description, learnMoreUrl, children }: DetailsRowPr
...
 
     return (
-        <ContentFlex gap={spacings.xxxl} justifyContent="space-between">
+        <ContentFlex gap={40} justifyContent="space-between">
             <InfoItem
                 label={<Translation id={title} />}
                 typographyStyle="body"
                 variant="default"
-                gap={spacings.xs}
+                gap={8}
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/details/index.tsx:56]: what problem is with spacings in this file?

File: packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/PageName.tsx [hunk 3]
```diff
@@ -12,6 +14,16 @@ export const PageName = () => {
     const currentRoute = useSelector(state => state.router.route?.name);
     const selectedAccount = useSelector(selectSelectedAccount);
     const isAccountTabPage = useSelector(selectIsAccountTabPage);
+    const { params } = useSelector(state => state.wallet.selectedAccount);
+
+    const fallbackAccount = useSelector(state =>
```
Comment (tomasklim) [inline packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/PageName.tsx:19]: Why is fallbackAccount needed?

Comment (tomasklim) [reply packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/PageName.tsx:19]: I expect that `selectedAccount` also holds failed discovery accounts, maybe I am wrong, but I do not see reason why it should not

File: packages/suite/src/views/wallet/details/index.tsx (hunk 2 above)
Comment (izmy) [reply packages/suite/src/views/wallet/details/index.tsx:56]: Spacings are now deprecated, so I changed them right away.
image

File: packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/PageName.tsx (hunk 3 above)
Comment (izmy) [reply packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/PageName.tsx:19]: No, the `account` info in `selectedAccount` is missing when a discovery error occurs.

image

File: packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageHeader.tsx (hunk 1 above)
Comment (izmy) [reply packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageHeader.tsx]: done

**Review by matusbalascak — APPROVED** [review]

File: packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/PageName.tsx (hunk 3 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/PageName.tsx:19]: okay, do not waste time on it

**Review by tomasklim — APPROVED** [review]
