### PR TITLE
Mobile: sending Solana

### LINKED ISSUE #15497: Send Solana + Tokens
- [x] Validate recipient address
- [x] fetch fee
- [x] send Solana
- [x] send Tokens
- [x] error state when txn times out or is marked as failed
- [x] send max

### PR DESCRIPTION
**Pull request by vytick**
Enables sending Solana and tokens including basic error handling for failed send. No custom fees are allowed (same as desktop).

## Related Issue

Resolve #15497

## Screenshots:

happy path:

https://github.com/user-attachments/assets/90a1adda-35a1-4d42-9e6a-d82ba2371550

unhappy path:

https://github.com/user-attachments/assets/bea40671-511a-4ad3-98f0-5e8ffcd942da

### CODE REVIEW

File: packages/connect/src/data/defaultFeeLevels.ts [hunk 1]
```diff
@@ -102,8 +102,8 @@ const SOLANA_FEE_INFO: FeeInfoWithLevels = {
             blocks: -1,
         },
     ],
-    minFee: -1, // unused
-    maxFee: -1, // unused
+    minFee: 25000,
+    maxFee: 1000000000,
```
Comment (mroz22) [inline packages/connect/src/data/defaultFeeLevels.ts:106]: how come that suite didn't need this? 🤔

Comment (vytick) [reply packages/connect/src/data/defaultFeeLevels.ts:106]: There is probably no validation on this. And the fees are determined automatically by fetching the on chain data

File: suite-native/module-send/src/components/CustomFee.tsx [hunk 2]
```diff
@@ -36,6 +41,11 @@ export const CustomFee = () => {
         setIsBottomSheetVisible(false);
     };
 
+    // custom fees are not allowed for solana
+    if (['sol', 'dsol'].includes(networkSymbol)) {
```
Comment (PeKne) [inline suite-native/module-send/src/components/CustomFee.tsx]:
```suggestion
    const networkType = getNetworkType(networkSymbol);
    if (networkType === 'solana') {
```

Comment (PeKne) [reply suite-native/module-send/src/components/CustomFee.tsx]: Or you can send `networkType` prop directly from the parent.

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx [hunk 3]
```diff
@@ -22,13 +22,14 @@ import { Translation } from '@suite-native/intl';
...
 import { selectAccountTokenSymbol, TokensRootState } from '@suite-native/tokens';
+import { useAlert } from '@suite-native/alerts';
 
 import { SendConfirmOnDeviceImage } from '../components/SendConfirmOnDeviceImage';
 import { cleanupSendFormThunk } from '../sendFormThunks';
 import { wasAppLeftDuringReviewAtom } from '../atoms/wasAppLeftDuringReviewAtom';
 import { selectIsTransactionAlreadySigned } from '../selectors';
 
-const navigateToAccountDetail = ({
+const navigateToTransactionDetail = ({
```
Comment (PeKne) [inline suite-native/module-send/src/components/OutputsReviewFooter.tsx:46]: fix the comment as well please 🙏

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx [hunk 4]
```diff
@@ -145,6 +172,27 @@ export const OutputsReviewFooter = ({
...
+        } else if (isRejected(sendResponse)) {
+            showAlert({
+                icon: 'warningCircle',
+                title: <Translation id="moduleSend.review.toasts.sendTxnFailed" />,
+                description:
+                    sendResponse.payload?.metadata.payload.error ?? sendResponse.error.message,
+                primaryButtonTitle: <Translation id="generic.buttons.close" />,
+                primaryButtonVariant: 'redBold',
+                onPressPrimaryButton: () => {
+                    hideAlert();
```
Comment (PeKne) [inline suite-native/module-send/src/components/OutputsReviewFooter.tsx]:
```suggestion
```
redundant call. It is already called in inside of the `showAlert()` implementation.

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx [hunk 5]
```diff
@@ -145,6 +172,27 @@ export const OutputsReviewFooter = ({
             }
 
             setTxid(sentTxid);
+        } else if (isRejected(sendResponse)) {
```
Comment (PeKne) [inline suite-native/module-send/src/components/OutputsReviewFooter.tsx]: nit: `else if` is not needed. There is no other unhandled option. So you can call return inside of the `if` and unwrap this code block.

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx [hunk 6]
```diff
@@ -145,6 +172,27 @@ export const OutputsReviewFooter = ({
...
+                title: <Translation id="moduleSend.review.toasts.sendTxnFailed" />,
+                description:
+                    sendResponse.payload?.metadata.payload.error ?? sendResponse.error.message,
+                primaryButtonTitle: <Translation id="generic.buttons.close" />,
+                primaryButtonVariant: 'redBold',
+                onPressPrimaryButton: () => {
+                    hideAlert();
+                    dispatch(cleanupSendFormThunk({ accountKey, shouldDeleteDraft: true }));
+                    navigation.dispatch(
+                        navigateToAccountDetail({
```
Comment (PeKne) [inline suite-native/module-send/src/components/OutputsReviewFooter.tsx]: Are we sure that we want to navigation back to the account detail from here? What about navigation the user back to the send form, so he can try it again? Does @shenkys know that we will show an extra alert?

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx (hunk 5 above)
Comment (PeKne) [inline suite-native/module-send/src/components/OutputsReviewFooter.tsx]: Now this alert sheet will be displayed for any failed transaction. Not only those related to a SOL timeout. Please change this so the sheet is triggered only for the timeout. 

All the other states will be handled separately in: https://github.com/trezor/trezor-suite/issues/15464

**Review by PeKne — CHANGES_REQUESTED** [review]
If I get to the state of timeouted transaction once, I am unable the send any other SOL transaction again. It always resolves in the timeout error. Only that helps is restart of the app. There is probably something rotting in the redux state.

https://github.com/user-attachments/assets/6645d65f-146e-4cbc-9c9b-a4005a833ebd

File: packages/connect/src/data/defaultFeeLevels.ts (hunk 1 above)
Comment (mroz22) [reply packages/connect/src/data/defaultFeeLevels.ts:106]: ok, good with me 👍

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx (hunk 5 above)
Comment (vytick) [reply suite-native/module-send/src/components/OutputsReviewFooter.tsx]: I can drop this completely in favour of #15464 as timeout of txn should be just another error

Comment (vytick) [reply suite-native/module-send/src/components/OutputsReviewFooter.tsx]: As we discussed, I'll leave it as is for now, but it will be probably redone in #15464 for better error handling.

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx (hunk 6 above)
Comment (vytick) [reply suite-native/module-send/src/components/OutputsReviewFooter.tsx]: d05da19b76

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx (hunk 5 above)
Comment (vytick) [reply suite-native/module-send/src/components/OutputsReviewFooter.tsx]: d05da19b76

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx (hunk 4 above)
Comment (vytick) [reply suite-native/module-send/src/components/OutputsReviewFooter.tsx]: d05da19b76

File: suite-native/module-send/src/components/OutputsReviewFooter.tsx (hunk 3 above)
Comment (vytick) [reply suite-native/module-send/src/components/OutputsReviewFooter.tsx:46]: d05da19b76

File: suite-native/module-send/src/components/CustomFee.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/module-send/src/components/CustomFee.tsx]: d05da19b76

File: suite-native/module-send/src/screens/SendFeesScreen.tsx [hunk 7]
```diff
@@ -16,6 +18,24 @@ export const SendFeesScreen = ({
         selectAccountByKey(state, accountKey),
     );
 
+    useEffect(() => {
+        // Subscribe to blocks for Solana, since they are not fetched globally
+        // this is needed for correct Solana fee estimation
+        if (account && account.networkType === 'solana') {
+            TrezorConnect.blockchainSubscribe({
```
Comment (Nodonisko) [inline suite-native/module-send/src/screens/SendFeesScreen.tsx:25]: nit: maybe create variable for that params and use in both calls?

Comment (vytick) [reply suite-native/module-send/src/screens/SendFeesScreen.tsx:25]: This is a copy of what @martykan used for desktop.

Comment (Nodonisko) [reply suite-native/module-send/src/screens/SendFeesScreen.tsx:25]: That doesn't mean it coudn't be improved a bit :D

**Review by Nodonisko — APPROVED** [review]

**Review by PeKne — APPROVED** [review]
