### PR TITLE
Fix/multiple discovery runs

### LINKED ISSUE #10142: App stucks on the `Connecting` screen
After merging of #10109, the app sometimes freezes on the connecting screen on device connection.

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- c21772678cc9cc2bad70fc76b463e570c13f4a59 
  - on device disconnect the deviceAccessMutex is cleared, so it is ready to use during the next device connection
- 90079fadda8761a2cf7904edac9da7dc472262d8 
  - authDevice is dispatched only once, so the discovery is not executed multiple times
  - discoveryThunks refactored to not take `device` argument that is selectable from the redux state
## Related Issue

Resolve #10142

### CODE REVIEW

File: suite-native/device-mutex/src/DeviceAccessMutex.ts [hunk 1]
```diff
@@ -43,6 +43,11 @@ class DeviceAccessMutex {
             this.isLocked = false;
         }
     }
+
+    clearQueue() {
```
Comment (Nodonisko) [inline suite-native/device-mutex/src/DeviceAccessMutex.ts:47]: I not sure about just emptying `taskQueue`, wouldn't that cause that some lock will never be resolved so some thunks will hang in pending state forever?

Comment (Nodonisko) [reply suite-native/device-mutex/src/DeviceAccessMutex.ts:47]: I don't think it's big issue but there may some memory leak or something

Comment (PeKne) [reply suite-native/device-mutex/src/DeviceAccessMutex.ts:47]: Tasks from the cleared taskQueue rejected. Changed in [a0291ae](https://github.com/trezor/trezor-suite/pull/10154/commits/a0291ae0704856c3171b2ac60831f8250ec3654d).

File: suite-native/discovery/src/discoveryThunks.ts [hunk 2]
```diff
@@ -215,7 +219,7 @@ export const createDescriptorPreloadedDiscoveryThunk = createThunk(
         }
         const networks = areTestnetsEnabled ? supportedNetworkSymbols : supportedMainnetSymbols;
 
-        const availableCardanoDerivations = await requestDeviceAccess(() =>
+        const deviceAccessResponse = await requestDeviceAccess(() =>
```
Comment (juriczech) [inline suite-native/discovery/src/discoveryThunks.ts:222]: nit: `cardanoDerivationsDeviceResponse` so it's apparent what is the value within device response, but feel free to resolve if you disagree

**Review by juriczech — APPROVED** [review]
