### PR TITLE
fix(suite): discreet mode cut off in accounts

### LINKED ISSUE #2886: Discreet mode: Accounts
Screenshot 2020-11-05 at 00 39 09

### PR DESCRIPTION
**Pull request by tomexx**
Just a one-liner for fixing discreet mode cut offs in Accounts

### CODE REVIEW

File: packages/suite/src/components/wallet/CoinBalance/index.tsx [hunk 1]
```diff
@@ -4,7 +4,9 @@ import { Account } from '@wallet-types';
 import { formatCoinBalance } from '@wallet-utils/balanceUtils';
 import { HiddenPlaceholder } from '@suite-components';
 
-const Wrapper = styled.div``;
+const Wrapper = styled.div`
+    padding-right: 10px;
```
Comment (slowbackspace) [inline packages/suite/src/components/wallet/CoinBalance/index.tsx]: shouldn't we also add negative margin like before? otherwise it'll affect the scenario in which another component is placed next to it (eg. in dashboard https://github.com/trezor/trezor-suite/blob/287269484aba3929c713d985379ca1eaa987c0b2/packages/suite/src/views/dashboard/components/AssetsCard/components/Asset/index.tsx#L133)

**Review by slowbackspace — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/wallet/CoinBalance/index.tsx (hunk 1 above)
Comment (tomexx) [reply packages/suite/src/components/wallet/CoinBalance/index.tsx]: That's true. 👍 I even found a better place where to put the hack so we'll be safer regarding cutoffs.

**Review by slowbackspace — APPROVED** [review]

**Comment by slowbackspace** [comment]
Ci is failing on e2e tests, I restarted the job it should pass just fine imo 🤷

**Comment by tomexx** [comment]
Seems to be OK now, thx
