### PR TITLE
fix - show suite sync labeling dropdown option in correct cases

### LINKED ISSUE #24844: Labeling settings - fix show Suite Sync when enabled
- fix turning on legacy when you accidentally turned on suite snyc
- fix not showing SS when its not turned on

### PR DESCRIPTION
**Pull request by OriginalEveres**
✅ NOTE: this [PR](https://github.com/trezor/trezor-suite/pull/24834) needs to be merged first

changes (fixes):
- you should se SS in labeling select only if its enabled in experimental mode
- some cleaning in terms of calling turn off suite sync fn
 
## Notes for QA

- you should be able to turn on and off legacy labeling (from OFF or Suite Sync state)
- you should be able to turn on the suite sync

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/24844

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/show-ss-correctly&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/show-ss-correctly&lookback=7)

### CODE REVIEW

**Review by komret — APPROVED** [review]

File: packages/suite/src/views/settings/SettingsGeneral/Labeling.tsx [hunk 1]
```diff
@@ -57,6 +50,11 @@ export const Labeling = () => {
                 : translationString(option.label),
     }));
 
+    const handleLegacyOptionSelect = async () => {
+        await suiteSync.turnOffSuiteSync();
+        if (legacyMetadataState.enabled === false) dispatch(metadataLabelingActions.init(true));
```
Comment (matejkriz) [inline packages/suite/src/views/settings/SettingsGeneral/Labeling.tsx]: nitpick: I would prefer a block around the dispatch call for readability. Early return is fine without the block, but anything longer is better in {}.

Comment (OriginalEveres) [reply packages/suite/src/views/settings/SettingsGeneral/Labeling.tsx]: nitpick accepted and implemented. 🫡
