### PR TITLE
fix(suite-native): remove the Sync my coins button from the Home screen

### LINKED ISSUE #15554: Revise the placement of Sync another coin / Sync my coins buttons
The _Sync another coin_ button, alternatively called _Sync my coins,_ seems to be present on too many places/screens.

- In the _Portfolio Tracker_ switcher
- On the _Home_ screen
- As the `+` button on the _My assets_ and _Receive_ screens

Revise the placement of the buttons and remove the ones that do not make sense any more.

Also unifying the naming of the button might make sense.

**Based on discussion with @shenkys, we're removing the _Sync my coins_ button from the Home screen.**

### PR DESCRIPTION
**Pull request by yanascz**
## Related Issue

Resolve #15554

## Screenshots:
image

### CODE REVIEW

File: suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx [hunk 1]
```diff
@@ -42,31 +32,14 @@ export const PortfolioContent = forwardRef<PortfolioGraphRef>((_props, ref) => {
...
-                            testID="@home/portfolio/sync-coins-button"
-                            colorScheme="tertiaryElevation0"
-                            size="large"
-                            onPress={handleImportAssets}
-                        >
-                            <Translation id="moduleHome.buttons.syncMyCoins" />
-                        </Button>
-                    </Box>
-                )}
-                {!isUsbDeviceConnectFeatureEnabled && (
```
Comment (yanascz) [inline suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx:56]: What was the motivation to hide the Receive button when a device is connected?

File: suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx [hunk 2]
```diff
@@ -42,31 +32,14 @@ export const PortfolioContent = forwardRef<PortfolioGraphRef>((_props, ref) => {
                     <Assets />
                 </Box>
                 {isPortfolioTrackerDevice && (
```
Comment (yanascz) [inline suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx:34]: The `IsDeviceConnectEnabled` FF is configured in such a way that using `!isUsbDeviceConnectFeatureEnabled` hides the Recieve button in Simulator even though it's visible in the dev app.

**Review by PeKne — APPROVED** [review]
