### PR TITLE
fix(coinmarket): minor fixes

### LINKED ISSUE #14767: Coinmarket - minor bugs
## Description
- missing Invity Footer in confirm pages(1)
- in the Last transaction pages
  - replace `exchanges` → `swaps` (2)
  - send in swaps transactions using contract address instead of symbol (3)
- infinity loading when the response contains empty quotes (edge case - do not know how to replicate without localhost API)
- bad `watchTrade` account - change account to selectedAccount (some trades were saved in bad account) (4)

## Screenshots
**Missing footer (1)**
obrazek
**Rename `exchanges` (2)** 
obrazek
**Bad symbol (3)**
obrazek

## Other
**Steps to reproduce (4)**
1. Select ETH account 
2. Go to Swap
3. Choose `From` SOL and `To` USDT
4. Make the trade
5. After transaction confirmation you will be on SOL account instead of ETH account

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
- missing Invity Footer in confirm pages(1)
- in the Last transaction pages
  - replace `exchanges` → `swaps` (2)
  - send in swaps transactions using contract address instead of symbol (3)
- infinity loading when the response contains empty quotes (edge case - do not know how to replicate without localhost API)
- bad `watchTrade` account - change account to selectedAccount (some trades were saved in bad account) (4)

## Screenshots
**Missing footer (1)**
obrazek
**Rename `exchanges` (2)** 
obrazek
**Bad symbol (3)**
obrazek

## Other
**Steps to reproduce (4)**
1. Select ETH account 
2. Go to Swap
3. Choose `From` SOL and `To` USDT
4. Make the trade
5. After transaction confirmation you will be on SOL account instead of ETH account

## Related 
Resolve https://github.com/trezor/trezor-suite/issues/14767
Will be rebased on develop branch after https://github.com/trezor/trezor-suite/pull/14758 will be merged

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketAccountTransactions/CoinmarketAccountTransactions.tsx [hunk 1]
```diff
@@ -84,7 +84,7 @@ export const CoinmarketAccountTransactions = () => {
                                 {buyTransactions.length} <Translation id="TR_TRADE_BUYS" /> •{' '}
                                 {sellTransactions.length} <Translation id="TR_TRADE_SELLS" /> •{' '}
                                 {exchangeTransactions.length}{' '}
-                                <Translation id="TR_TRADE_EXCHANGES" />
+                                <Translation id="TR_COINMARKET_SWAPS" />
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketAccountTransactions/CoinmarketAccountTransactions.tsx]: How about creating one big translation string for the content of `TransactionCount` and just use values for numbers.
Or other option - create translation strings together with numbers so that it works with plurals - 1 buy, 2 buys, if needed

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -1419,6 +1419,10 @@ export default defineMessages({
         defaultMessage: 'Swap',
         id: 'TR_COINMARKET_SWAP',
     },
+    TR_COINMARKET_SWAPS: {
+        defaultMessage: 'swaps',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: I find it quit dangerous to have it lowercase here. I am scared that in some languages somebody will uppercase it without the context. As mentioned above I would add it here with numbers/dates,...

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/support/messages.ts (hunk 2 above)
Comment (adderpositive) [reply packages/suite/src/support/messages.ts]: Updated

**Review by tomasklim — APPROVED** [review]
