### PR TITLE
fix: show latest fw fingerprint if intermediary

### LINKED ISSUE #4156: Wrong fingerprint shown for intermediary firmware when installing out-of-the-box Trezor
Per [this report](https://www.reddit.com/r/TREZOR/comments/p43xn0/mismatched_firmware_fingerprints_on_brand_new/h8wariv/?utm_source=reddit&utm_medium=web2x&context=3), the fingerprint shown in Suite is for firmware 1.6.3, but what's sent to Trezor is actually the intermediary firmware.
[suite fingerprint](https://jumpshare.com/v/Coxbn5blhEtL1pSrTT85): e8dbb4b7fe8384afd4c99790277c2f2f366a1a0f3957aa3545c75371a99a8fcc
[Trezor fingerprint](https://jumpshare.com/v/IMduurLvImGFvmUecK4Q): ba37d1523ec4cf003b5e28b2fe50a380d694bf53c99d3d4c7a7ffb0d93984d6c

I don't have the hardware to reproduce this personally.

### PR DESCRIPTION
**Pull request by dimasivan**
should fix #4156

### CODE REVIEW

File: packages/suite/src/components/firmware/Fingerprint.tsx [hunk 1]
```diff
@@ -17,7 +17,11 @@ const Wrapper = styled.pre`
 const Fingerprint = ({ device }: { device: TrezorDevice }) => (
     <Wrapper>
         {/* device.firmwareRelease should be always defined here (this renders upon dispatching ButtonRequest_FirmwareCheck) */}
-        {getFormattedFingerprint(device.firmwareRelease!.release.fingerprint)}
+        {getFormattedFingerprint(
+            device.features!.major_version === 1 // support intermediary
```
Comment (matejkriz) [inline packages/suite/src/components/firmware/Fingerprint.tsx]: you could use `import { supportIntermediary } from '@suite-utils/device';` that you introduced and then the comment is no more needed...

Comment (dimasivan) [reply packages/suite/src/components/firmware/Fingerprint.tsx]: 12a2a46

**Review by matejkriz — APPROVED** [review]
LGTM, please rebase and merge
