### PR TITLE
fix(suite): account polish

### LINKED ISSUE #10556: Accounts Page polish
* use `Card` for the trade section
* adjust the trade section. Do not use the ButtonGroup though. On mobile keep the current layout 
image

* remove background from the transaction date header + do not make months ALL CALS
image

* bring the transaction actions closer
image

* remove custom card paddings from transactions, the graph and the account stat cards
* add `min-width: 170px` to the "Show public key" button to align better 
* make the loader for the wallet holdings larger 
image

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Polishing account as per issue. Made screenshots with card padding fixes that will take place in #10691. So currently everything is with small padding in this branch but that will change.

## Related Issue

Resolve #10556 

## Screenshots:
B55A1E5C-53B5-434C-A146-1E702E2D068A
034FB20B-F1EC-4A75-AF0F-AC277C64A610
F8E6A363-CB08-495B-B1BF-E220CF259873
9377C48D-551B-4F97-AE00-578A9115CB26_4_5005_c

### CODE REVIEW

File: packages/suite/src/views/dashboard/components/SecurityCard.tsx [hunk 1]
```diff
@@ -44,15 +44,17 @@ const Action = styled.div`
...
     border-radius: 50%;
     width: 24px;
     height: 24px;
     top: ${spacingsPx.xs};
     right: ${spacingsPx.xs};
     overflow: hidden;
-    box-shadow: inset 0 1px ${({ theme }) => theme.borderOnElevation1};
+    border: 1px solid
+        ${({ theme, isDone }) =>
+            isDone ? theme.backgroundPrimarySubtleOnElevation1 : theme.borderOnElevation1};
```
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/SecurityCard.tsx:57]: 🔥

**Review by dahaca — APPROVED** [review]
Nice fixes all around! 

I've noticed some bugs in the highlight styling – old stuff  don’t think you’ve introduced it! And as a challenge for myself improved the UX of the TX search input, curious what you think about it 🙌
