### PR TITLE
fix(suite): prevent default value overwriting user amount input

### LINKED ISSUE #21013: Trading - compare offers does not respect user input
**Describe the bug**
User initiates Buy BTC flow. Selects fiat currency and changes the amount. But when user continues to compared offers, the offers are for default currency and amount. Not respecting what user filled in in the form.

**Info:**

- Remembered Wallet: yes/no
- Suite Version: web develop
- Browser: Chrome latest
- Browser Installation Method:  app store
- OS: Ubuntu 24
- Bridge: version
- Firmware Version: released

**How to reproduce**

1. Go to Bitcoin Buy form
2. Change fiat currency to CZK
3. Change amount to 1234
4. Wait for offer
5. Click compare offers
6. Notice initially, offers correspond to your original offer, but the input on the top is already 150 USD
7. Offers refresh for 150 USD

**Expected behavior**
Compared offers respect user input and stay for 1234 CZK

**Screenshots**

https://github.com/user-attachments/assets/ecd0c339-f9bc-44cd-9607-6bdcacb93bae

**Additional context**
Automated test - Trading - Buy BTC > Buy Bitcoin from compared offer

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

Prevent default value overwriting user amount input.

## Related Issue

Resolve #21013

## Screenshots:

https://github.com/user-attachments/assets/1b93a4bb-1b3c-4df6-8391-228ba1155539

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/21013-compare-offers-fiat&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/21013-compare-offers-fiat&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormRedirectValues.ts [hunk 1]
```diff
@@ -15,19 +15,22 @@ export const useTradingBuyFormRedirectValues = (
...
+    return {
+        amountInCrypto: quotesRequest.wantCrypto,
+        cryptoSelect: buildDefaultCryptoOption(quotesRequest.receiveCurrency),
+        currencySelect: buildTradingFiatOption(quotesRequest.fiatCurrency as FiatCurrencyCode),
+        countrySelect: getDefaultCountry(quotesRequest.country as TradingCountryCode),
+
+        // fill the input that corresponds to the entered amount type
+        ...(quotesRequest.wantCrypto
+            ? { cryptoInput: quotesRequest.cryptoStringAmount }
+            : { fiatInput: quotesRequest.fiatStringAmount }),
```
Comment (cermakjiri) [inline packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormRedirectValues.ts:29]: This has changed.

**Review by izmy — APPROVED** [review]
