### PR TITLE
fix(suite): search input issues (cursor, and unresponsive clear button)

### LINKED ISSUE #11312: Search button/field doesn't work properly
**Describe the bug**
Search button/field doesn't work properly.
image

1. when mouse over the button, there should be the "hand" and not cursor.
image

2. when you type something into the field, the "x" button doesn't work 
image

**Info:**

-   Remembered Wallet: yes
-   Suite Version: 24.2.2

**How to reproduce**

1. hover over the button
2. type some text into the text field and try to delete with the "x" button

**Expected behavior**
1. See a hand on hover
2. be able to delete the whole text with the "x" button

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11312

### CODE REVIEW

File: packages/suite/src/views/wallet/transactions/TransactionList/TransactionListActions/SearchAction.tsx [hunk 1]
```diff
@@ -51,15 +51,10 @@ const StyledInput = styled(Input)<{ $isExpanded: boolean }>`
         height: ${INPUT_WIDTH};
         border: none;
     }
-
-    /* TODO: remove this when clicking on addons in Input is handled better */
-    div > div:first-child {
-        pointer-events: none;
```
Comment (peter-sanderson) [inline packages/suite/src/views/wallet/transactions/TransactionList/TransactionListActions/SearchAction.tsx:57]: No idea why this was used instead of simple managed state.

File: packages/suite/src/views/wallet/transactions/TransactionList/TransactionListActions/SearchAction.tsx [hunk 2]
```diff
@@ -93,7 +88,7 @@ export const SearchAction = ({ account, searchQuery, setSearch, setSelectedPage
 
     const onKeyDown = useCallback(
         (event: KeyboardEvent) => {
-            // Handle esc (unfocus)
+            // Handle ESC (un-focus)
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/transactions/TransactionList/TransactionListActions/SearchAction.tsx:91]: love your OCD 😂

**Review by jvaclavik — APPROVED** [review]

File: packages/suite/src/views/wallet/transactions/TransactionList/TransactionListActions/SearchAction.tsx (hunk 2 above)
Comment (peter-sanderson) [reply packages/suite/src/views/wallet/transactions/TransactionList/TransactionListActions/SearchAction.tsx:91]: its: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker ;)
