### PR TITLE
Fix/native/cancel pin on passphrase

### LINKED ISSUE #12875: Cancel pin screen on opening passphrase wallet
If device is in remember mode & locked and user starts opening passphrase wallet, pin screen pops up to unlock the device. If the screen is cancelled, user hangs in unacquired device. 

Expected: User should go back to standard wallet and locked device

https://github.com/trezor/trezor-suite/assets/36101761/7cb273f2-e2ed-4d57-b25e-22c0e94f1429

### PR DESCRIPTION
**Pull request by juriczech**
## Description
- first commit refactors the global passphrase hook a little bit to improve global passphrase handling
- second commit fixes the bug in related issue

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12875

## Screenshots:

https://github.com/trezor/trezor-suite/assets/36101761/104eb229-e01e-4b0a-8251-4f4362a9d7f0

### CODE REVIEW

File: suite-native/passphrase/src/passphraseSlice.ts [hunk 1]
```diff
@@ -7,8 +7,11 @@ import {
     createDeviceInstanceThunk,
 } from '@suite-common/wallet-core';
 
+import { verifyPassphraseOnEmptyWalletThunk } from './passphraseThunks';
+
 type PassphraseState = {
     error: AuthorizeDeviceError | CreateDeviceInstanceError | null;
+    isVefifyingPassphraseOnEmptyWallet: boolean;
```
Comment (PeKne) [inline suite-native/passphrase/src/passphraseSlice.ts]:
```suggestion
    isVerifyingPassphraseOnEmptyWallet: boolean;
```

File: suite-common/wallet-core/src/device/deviceReducer.ts [hunk 2]
```diff
@@ -908,3 +908,18 @@ export const selectInstacelessUnselectedDevices = memoize((state: DeviceRootStat
...
+    return device?.instance ?? null;
+};
+
+export const selectIsUnauthorizedPassphraseDevice = (state: DeviceRootState) => {
+    const isDeviceConnectedAndAuthorized = selectIsDeviceConnectedAndAuthorized(state);
+    const deviceInstance = selectDeviceInstance(state);
+
+    if (!deviceInstance) return false;
+
+    return !isDeviceConnectedAndAuthorized && deviceInstance > 1;
```
Comment (PeKne) [inline suite-common/wallet-core/src/device/deviceReducer.ts]: Just and idea... What about creating also `selectIsPassphraseDevice` selector that would be returning `deviceInstance > 1`?

It would not change the code, but would make it bit more understandable and reusable. But feel free to resolve this.

File: suite-native/app/src/navigation/AppTabNavigator.tsx [hunk 3]
```diff
@@ -5,7 +5,7 @@ import { HomeStackNavigator } from '@suite-native/module-home';
 import { AccountsStackNavigator } from '@suite-native/module-accounts-management';
 import { SettingsStackNavigator } from '@suite-native/module-settings';
 import { AppTabsParamList, AppTabsRoutes, TabBar } from '@suite-native/navigation';
-import { useHandleDeviceRequestsPassphrase } from '@suite-native/device';
+import { useHandleDeviceRequestsPassphrase } from '@suite-native/passphrase';
```
Comment (PeKne) [inline suite-native/app/src/navigation/AppTabNavigator.tsx:8]: Does it make sense to have the hook here? Why not to put it into a RootStack? I'm asking because it is still unsure if the send will be in the TabNavigator. It will be very likely, but let's see.

File: suite-native/passphrase/src/useHandleDeviceRequestsPassphrase.ts [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+    PassphraseStackParamList,
+    PassphraseStackRoutes.PassphraseForm,
+    RootStackParamList
+>;
+
+export const useHandleDeviceRequestsPassphrase = () => {
+    const navigation = useNavigation<NavigationProp>();
+
+    const deviceState = useSelector(selectDeviceState);
+    const isVefifyingPassphraseOnEmptyWallet = useSelector(
```
Comment (PeKne) [inline suite-native/passphrase/src/useHandleDeviceRequestsPassphrase.ts]:
```suggestion
    const isVerifyingPassphraseOnEmptyWallet = useSelector(
```

File: suite-native/module-connect-device/src/components/PinOnDevice.tsx [hunk 5]
```diff
@@ -48,14 +50,21 @@ export const PinOnDevice = ({ deviceModel }: PinOnDeviceProps) => {
 
     const device = useSelector(selectDevice);
     const hasDeviceRequestedPin = useSelector(selectDeviceRequestedPin);
+    const isUnauthorizedPassphraseDevice = useSelector(selectIsUnauthorizedPassphraseDevice);
+
     const { applyStyle } = useNativeStyles();
 
     const handleSuccess = useCallback(() => {
+        // If pin screen was triggered from opening passphrase wallet (which creates new instance) and is cancelled, we need to select standard wallet
```
Comment (PeKne) [inline suite-native/module-connect-device/src/components/PinOnDevice.tsx]: This comment is talking about the flow being `canceled` but the callback is called `handleSuccess`. Could you clarify this please?

**Review by PeKne — COMMENTED** [review]
Looks good to me, good job :).

File: suite-native/module-connect-device/src/components/PinOnDevice.tsx (hunk 5 above)
Comment (juriczech) [reply suite-native/module-connect-device/src/components/PinOnDevice.tsx]: I copied the comment, it should be `close` I guess.  https://github.com/trezor/trezor-suite/pull/12876/commits/a3937fd599788239f40cd82fa5f816f3b1f98bf5

File: suite-native/passphrase/src/useHandleDeviceRequestsPassphrase.ts (hunk 4 above)
Comment (juriczech) [reply suite-native/passphrase/src/useHandleDeviceRequestsPassphrase.ts]: https://github.com/trezor/trezor-suite/pull/12876/commits/a3937fd599788239f40cd82fa5f816f3b1f98bf5

File: suite-native/passphrase/src/passphraseSlice.ts (hunk 1 above)
Comment (juriczech) [reply suite-native/passphrase/src/passphraseSlice.ts]: Good catch! Couldn't even see the difference when comparing these 2 diffs :D 
https://github.com/trezor/trezor-suite/pull/12876/commits/a3937fd599788239f40cd82fa5f816f3b1f98bf5

File: suite-common/wallet-core/src/device/deviceReducer.ts (hunk 2 above)
Comment (juriczech) [reply suite-common/wallet-core/src/device/deviceReducer.ts]: https://github.com/trezor/trezor-suite/pull/12876/commits/a3937fd599788239f40cd82fa5f816f3b1f98bf5

File: suite-native/app/src/navigation/AppTabNavigator.tsx (hunk 3 above)
Comment (juriczech) [reply suite-native/app/src/navigation/AppTabNavigator.tsx:8]: I'd keep it for now and we can move it if there's need for it. For now, it seems that you only need it in TabNavigator

Comment (PeKne) [reply suite-native/app/src/navigation/AppTabNavigator.tsx:8]: ok, let's keep it for now, can be refactored later.

**Review by PeKne — APPROVED** [review]
