### PR TITLE
fix(suite-native): init state in useRef

### LINKED ISSUE #24282: Android back navigation breaks Connect deeplink (warm launch)
1. Open a Connect popup deeplink
2. Press back button (or gesture) multiple times to close out of the Trezor app
3. Open a Connect popup deeplink again
4. Get a blank screen

https://github.com/user-attachments/assets/2adf9644-b3b6-460d-9eb3-87dc940adf58

This scenario seems to be called `LaunchState: WARM`

```
$ adb shell am start -W -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d https://connect.trezor.io/9/deeplink/1
Starting: Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://connect.trezor.io/... }
Status: ok
LaunchState: WARM
Activity: io.trezor.suite/.MainActivity
TotalTime: 44
WaitTime: 47
Complete
```

The problem seems to lie in AppComponent or BaseStoreProvider. 
In this scenario AppComponent is recreated, but global JS state remains. Therefore `isApplicationInitDispatched = true`, init doesn't run again and `isAppReady = false`.

### PR DESCRIPTION
**Pull request by martykan**
## Description

Move `isApplicationInitDispatched` into `useRef` to resolve issue with warm launch on Android, where the App component is recreated but global JS stay.

## Related Issue

Resolve #24282

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/suite-android-warm-start&lookback=7)

### CODE REVIEW

File: suite-native/app/src/App.tsx [hunk 1]
```diff
@@ -50,9 +50,8 @@ SplashScreen.preventAutoHideAsync();
 // https://github.com/react-native-netinfo/react-native-netinfo?tab=readme-ov-file#configure
 configureNetInfo();
 
-let isApplicationInitDispatched = false;
-
 const AppComponent = () => {
+    const isApplicationInitDispatched = useRef(false);
```
Comment (yanascz) [inline suite-native/app/src/App.tsx]: Would expect this one just before `isAppReady`.

Comment (yanascz) [inline suite-native/app/src/App.tsx]: I'd personally add `Ref` suffix... However, it seems it's not used consistently throughout the code. 😕

**Review by yanascz — APPROVED** [review]
Looks good.

File: suite-native/app/src/App.tsx (hunk 1 above)
Comment (martykan) [reply suite-native/app/src/App.tsx]: efbb4164245557a9df97fd62375f18026a00adfd

Comment (martykan) [reply suite-native/app/src/App.tsx]: efbb4164245557a9df97fd62375f18026a00adfd
