### PR TITLE
Fix/tokens design

### LINKED ISSUE #13155: EVM Tokens/ Receive address modal tweaks
- Copy shouldn’t be desctructive.
- Cancel shouldn’t be primary
- Icon BG shouldn’t be green

image

approx like this pls
image

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- follow up issue for table structure and `price` aligned to right #13152
- follow up issue for `unhide` token modal mentioned here https://github.com/trezor/trezor-suite/issues/12165
- dropdown uses some old icons pack. I do not want to change whole dropdown design here

## Related Issue

see ondras comment
https://www.notion.so/satoshilabs/Tokens-tab-improvements-b1a0a31ef3dd43fcb1079401c84c0bc6#983713f2a51d4eb9bde746474a632d90
Resolve #13155

## Screenshots:

Screenshot 2024-07-03 at 11 40 48
Screenshot 2024-07-03 at 11 41 17
Screenshot 2024-07-03 at 11 41 37
Screenshot 2024-07-03 at 11 42 03
Screenshot 2024-07-03 at 11 42 48

### CODE REVIEW

File: packages/suite/src/views/wallet/transactions/TradeBox/TradeBox.tsx [hunk 1]
```diff
@@ -77,7 +81,7 @@ export const TradeBox = ({ account }: TradeBoxProps) => {
             <StyledCard>
                 <Left>
                     <CoinWrapper>
-                        <CoinLogo size={24} symbol={network.symbol} />
+                        <StyledCoinLogo size={24} symbol={network.symbol} />
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/transactions/TradeBox/TradeBox.tsx]: Could you use Row instead of CoinWrapper and might not  need to use `StyledCoinLogo`

```tsx
import { Row } from '@trezor/components';

...
<Left>
  <Row gap={spacings.xs} alignItems="center">
    <CoinLogo size={24} symbol={network.symbol} />
    ...

File: packages/components/src/components/modals/DialogModal/DialogModal.tsx [hunk 2]
```diff
@@ -10,11 +10,19 @@ const BodyHeading = styled.div`
     ${typography.titleMedium}
 `;
 
-const StyledIcon = styled(Icon)`
+const StyledIcon = styled(Icon)<{ iconVariant: 'success' | 'warning' }>`
```
Comment (jvaclavik) [inline packages/components/src/components/modals/DialogModal/DialogModal.tsx:13]: Can't you use just `<StyledIcon variant="warning />` etc.?

This way it's really hard to maintain it.

File: packages/suite/src/views/wallet/tokens/hidden-tokens/components/HiddenTokensTable.tsx [hunk 3]
```diff
@@ -67,10 +82,15 @@ export const HiddenTokensTable = ({ selectedAccount, searchQuery }: HiddenTokens
...
                 <UnverifiedTokens>
-                    <QuestionTooltip
-                        label="TR_TOKEN_UNRECOGNIZED_BY_TREZOR"
-                        tooltip="TR_TOKEN_UNRECOGNIZED_BY_TREZOR_TOOLTIP"
-                    />
+                    <UnrecognizedTokensWrapper>
+                        <H3>
+                            <Translation id="TR_TOKEN_UNRECOGNIZED_BY_TREZOR" />
+                        </H3>
+                        <SubHeading>
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/tokens/hidden-tokens/components/HiddenTokensTable.tsx]: Could you refactor it this way?

```tsx

import { Text, Row } from '@trezor/components';

...

<Row alignItems="center" gap={spacingsPx.xxs} margin={{bottom: spacingsPx.xl, top: spacingsPx.xxs}}>
  <Icon variant="tertiary" size={16} icon="WARNING" />
  <Text variant="tertiary" typographyStyle="hint">
    <Translation id="TR_TOKEN_UNRECOGNIZED_BY_TREZOR_TOOLTIP" />
  </Text>
</Row>
```

Comment (tomasklim) [reply packages/suite/src/views/wallet/tokens/hidden-tokens/components/HiddenTokensTable.tsx]: 260e50a74be6560cb7f820b01e1e4c9c98fa84b1

File: packages/suite/src/views/wallet/transactions/TradeBox/TradeBox.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/views/wallet/transactions/TradeBox/TradeBox.tsx]: 02a82943877edae0c66a2ae68b58bdbb38f61eb7

**Review by jvaclavik — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.7.1 (d97e8c2769f8b2751a8db3c4109c10619cf8b926)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33
