### PR TITLE
fix(suite-native): graph with testnetTestnet account does not break t…

### LINKED ISSUE #8481: Portfolio graph does not work with imported testnet asset
Current behaviour:
If there is any testnet account imported, then the portfolio graph shows a zero balance and error message.

Expected behaviour:
The testnet does not affects the portfolio graph at all and it shows balance of other imported assets.

## Screenshot of the bug
Image

### PR DESCRIPTION
**Pull request by PeKne**
## Description

- portfolio graph works with testnets

## Related Issue

Resolve #8481 

## Screenshots:
Screenshot 2023-05-15 at 16 08 18

### CODE REVIEW

File: suite-common/graph/src/hooks.ts [hunk 1]
```diff
@@ -46,7 +47,7 @@ export const useGraphForAccounts = ({
 
             try {
                 const points = await getMultipleAccountBalanceHistoryWithFiat({
-                    accounts,
+                    accounts: accounts.filter(account => !isTestnet(account.coin)),
```
Comment (Nodonisko) [inline suite-common/graph/src/hooks.ts]: I think this should be better handled in place where data are passed for this hook. For example have selector that selects only non-testnet accounts.

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-common/graph/src/hooks.ts (hunk 1 above)
Comment (PeKne) [reply suite-common/graph/src/hooks.ts]: Changed to use a selector for mainnet accounts only.

**Review by Nodonisko — APPROVED** [review]

**Review by Nodonisko — APPROVED** [review]
