### PR TITLE
Mobile trade fixes

### LINKED ISSUE #18426: Fix useNetworkChangeEffect hook in useTradingBuyForm
## Issue
  
There's a TODO comment in `suite-native/module-trading/src/hooks/useTradingBuyForm.ts` that needs to be addressed.

The `useNetworkChangeEffect` hook doesn't use React's `useEffect` pattern unlike all other effect hooks in the same file. This can cause:
- Code execution on every render instead of only when dependencies change
- Potential performance issues
- Inconsistent behavior compared to other hooks

## Proposed Solution

Refactor the hook to use the `useEffect` pattern:

```typescript
const useNetworkChangeEffect = (form: TradingBuyForm) => {
    const dispatch = useDispatch();
    const prevNetworkId = useRef<string | undefined>(undefined);

    useEffect(() => {
        const asset = form.watch('asset');
        
        if (asset?.networkId !== prevNetworkId.current) {
            prevNetworkId.current = asset?.networkId;
            dispatch(setBuySelectedReceiveAccount({ selectedReceiveAccount: undefined }));
        }
    }, [form, dispatch]);
};
```

Or consider using form.watch() within useEffect as is done in other hooks in the file.

## Related PR
This issue was identified during PR review: https://github.com/trezor/trezor-suite/pull/18421#discussion_r2048473599

### PR DESCRIPTION
**Pull request by jbazant**
## Description

Various mobile trade fixes.

## Related Issue

Resolve [#18426](https://github.com/trezor/trezor-suite/issues/18426)

### CODE REVIEW

File: suite-native/module-trading/src/hooks/useTradingBuyForm.ts [hunk 1]
```diff
@@ -73,10 +64,18 @@ const useAmountAndCurrencyFieldsChangeEffect = (form: TradingBuyForm) => {
                     form.trigger(['cryptoValue', 'fiatValue']);
                     break;
 
-                case 'asset':
+                case 'asset': {
                     form.setValue('cryptoValue', undefined);
                     form.trigger('cryptoValue');
```
Comment (vytick) [inline suite-native/module-trading/src/hooks/useTradingBuyForm.ts:69]: user could have originally inserted `cryptoValue`, what would you think about clearing even `fiatValue` in this case?

Comment (vytick) [reply suite-native/module-trading/src/hooks/useTradingBuyForm.ts:69]: resolving as this will be resolved in #18421

**Review by vytick — APPROVED** [review]
🚀
