### PR TITLE
23918 fix multi instnace account error

### LINKED ISSUE #23918: Labelling error should be limited to one instance
1. Enable Suite Sync in Suite but do not confirm on Trezor. (0:03)
2. Try to change an account label but do not confirm on Trezor. (0:33)
3. See the unexpected error state when you switch to a different account. (0:43)

https://github.com/user-attachments/assets/045d35fc-cc96-4334-9207-4455ea05dde6

### PR DESCRIPTION
**Pull request by vojtatranta**
## Notes for QA

Well, it should just fix the issue from the ticket

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/23918

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=23918-fix-multi-instnace-account-error&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=23918-fix-multi-instnace-account-error&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/AccountName/AccountName.tsx [hunk 1]
```diff
@@ -37,5 +37,11 @@ export const AccountName = ({ selectedAccount }: AccountNameProps) => {
         // eslint-disable-next-line react-hooks/exhaustive-deps
     }, [balanceSectionRef?.current]);
 
-    return <AccountDetails selectedAccount={selectedAccount} isBalanceShown={isScrolled} />;
+    return (
+        <AccountDetails
+            key={selectedAccount.key}
```
Comment (vojtatranta) [inline packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/AccountName/AccountName.tsx:42]: note: using key here to ensure that the account Details is using a different instnace of hte component.

File: packages/suite/src/components/suite/labeling/MetadataLabeling/withEditable.tsx [hunk 2]
```diff
@@ -74,7 +82,8 @@ export const withEditable =
 
         return (
             <Row gap={8}>
-                <WrappedComponent {...props}>
+                {/* @ts-expect-error: this is just passing props on I am not sure why it throws here */}
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/labeling/MetadataLabeling/withEditable.tsx:85]: this is very sus

Comment (vojtatranta) [reply packages/suite/src/components/suite/labeling/MetadataLabeling/withEditable.tsx:85]: yeah, I moved it at least to the place, where it is isn't that harmful

**Review by peter-sanderson — APPROVED** [review]
