### PR TITLE
Mitigation for crashes when send precomposed fee level is error

### LINKED ISSUE #22037: Mobile app crashing when trying to send TX sometimes
Sometimes for someone, both ios and android app is crashing while sending XRP or SOL or ETH. 

Reproduced on Preview version 25.9.1 (301) but also on current develop. 

Most probably you need to Send Max to reproduce it.

### PR DESCRIPTION
**Pull request by vytick**
Somehow when sending max amount (we have easily reproduced on XRP) the app crashes on send, because app tries to compose send max txn once more, but there is no XRP left (txn sending everything out was success), and FeeFooter expects final txn level, but receives error txn level and the change propagates before FeeFooter is removed from tree.

This PR checks type of the fee level and handles error level gracefully.

## Related Issue

Resolve #22037

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/send-max-crash&lookback=7)

### CODE REVIEW

File: suite-native/module-send/src/components/SendFeesForm.tsx [hunk 1]
```diff
@@ -134,11 +138,13 @@ export const SendFeesForm = ({ accountKey, tokenContract }: SendFormProps) => {
             {/*// BottomSheetModalProvider must be inside FormProvider to keep context available for sheets rendered via portal*/}
             <BottomSheetModalProvider>
                 <VStack spacing="sp32" flex={1}>
-                    <RecipientsSummary
-                        accountKey={accountKey}
-                        tokenContract={tokenContract}
-                        selectedFeeLevel={selectedFeeLevelTransaction}
-                    />
+                    {selectedFeeLevelTransaction && (
```
Comment (matejkriz) [inline suite-native/module-send/src/components/SendFeesForm.tsx]: `selectedFeeLevelTransaction` is not a boolean
```suggestion
                    {!!selectedFeeLevelTransaction && (
```

File: suite-native/module-send/src/components/SendFeesForm.tsx [hunk 2]
```diff
@@ -166,16 +172,18 @@ export const SendFeesForm = ({ accountKey, tokenContract }: SendFormProps) => {
...
-                            accountKey={accountKey}
-                            isSubmittable={isSubmittable}
-                            onSubmit={handleNavigateToReviewScreen}
-                            totalAmount={totalAmount}
-                            fee={fee}
-                            symbol={symbol}
-                            tokenContract={tokenContract}
-                            withSubmitButton={true}
-                        />
+                        {totalAmount && fee && (
```
Comment (matejkriz) [inline suite-native/module-send/src/components/SendFeesForm.tsx]:
```suggestion
                        {!!totalAmount && !!fee && (
```

File: suite-native/module-trading/src/components/fees/TradingFeesForm.tsx [hunk 3]
```diff
@@ -92,15 +92,17 @@ export const TradingFeesForm = ({ accountKey, tokenContract }: TradingFeesFormPr
...
-                    <FeesFooter
-                        accountKey={accountKey}
-                        isSubmittable={isSubmittable}
-                        totalAmount={totalAmount}
-                        fee={fee}
-                        symbol={symbol}
-                        tokenContract={tokenContract}
-                        withSubmitButton={false}
-                    />
+                    {totalAmount && fee && (
```
Comment (matejkriz) [inline suite-native/module-trading/src/components/fees/TradingFeesForm.tsx]:
```suggestion
                    {!!totalAmount && !!fee && (
```

**Review by matejkriz — COMMENTED** [review]
EDIT: I was probably just not patient enough, now it worked twice for me, I just had to wait ~ 17s. 

The app is not crashing anymore, but I'm now always stucked in the sending state, never redirected to Pending transaction detail

Image

File: suite-native/module-trading/src/components/fees/TradingFeesForm.tsx (hunk 3 above)
Comment (vytick) [reply suite-native/module-trading/src/components/fees/TradingFeesForm.tsx]: updated in 036bd6f17b6

File: suite-native/module-send/src/components/SendFeesForm.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/module-send/src/components/SendFeesForm.tsx]: updated in 036bd6f17b6

File: suite-native/module-send/src/components/SendFeesForm.tsx (hunk 1 above)
Comment (vytick) [reply suite-native/module-send/src/components/SendFeesForm.tsx]: updated in 036bd6f17b6

**Review by matejkriz — APPROVED** [review]

**Review by matejkriz — COMMENTED** [review]
It doesn’t fix the root cause, but it’s a good mitigation that should, in my opinion, be merged even if the root cause is addressed (namely that the transaction is recalculated even after being sent, leaving insufficient funds for a second transaction)
