### PR TITLE
fix: exchange button removed

### LINKED ISSUE #2343: Remove "Exchange (soon)" from top navigation
Screen Shot 2020-09-14 at 11 18 16

### PR DESCRIPTION
**Pull request by robertbrada**
Fix https://github.com/trezor/trezor-suite/issues/2343

Removed **exchnage button** from main navigation

### CODE REVIEW

File: packages/suite/src/components/suite/NavigationBar/components/MainNavigation/index.tsx [hunk 1]
```diff
@@ -158,6 +155,7 @@ const MainNavigation = (props: Props) => {
                             <ItemTitle isActive={isActive} isDisabled={isDisabled}>
                                 <Translation id={translationId} />
                             </ItemTitle>
+                            {/* if the button is disabled, diplay "SOON" badge */}
```
Comment (prusnak) [inline packages/suite/src/components/suite/NavigationBar/components/MainNavigation/index.tsx]:
```suggestion
                            {/* if the button is disabled, display "SOON" badge */}
```

**Review by prusnak — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/NavigationBar/components/MainNavigation/index.tsx (hunk 1 above)
Comment (keraf) [reply packages/suite/src/components/suite/NavigationBar/components/MainNavigation/index.tsx]: I highly suggest getting a spell checker for VSCode (most other editors have them available too). Just recently started using one and it helped me more than once to catch typos in comments, strings and even variables

**Review by keraf — APPROVED** [review]

**Comment by keraf** [comment]
Committed @prusnak suggestion (fix typo in comment) via the pretty neat GH interface (it committed & resolved the comment :open_mouth: ). All good to merge!
