### PR TITLE
Add coin changes and fixes

### LINKED ISSUE #11653: Create new account type duplicates existing account type Segwit
Steps to reproduce:

1. Connect Trezor with some existing accounts
2. Click on My Asset
3. Click on "+" and create new account - type Segwit - account is added and marked correctly
4. Go back to My Assets
5. Click on "+" and create new account - type Taproot, go back to My Assets, you see new Bitcoin item but it is marked as Segwit and inherits the balances from BTC#1 account - watch the attached video.

https://github.com/trezor/trezor-suite/assets/84183817/094539d9-f247-4a0c-9319-243f4d24c6c3

### PR DESCRIPTION
**Pull request by vytick**
- [x] Open add coin directly from home when empty screen
- [x] Accounts are off by account type #11653 
- [x] Accounts are off by derivation path index

Resolve #11653

### CODE REVIEW

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts [hunk 1]
```diff
@@ -106,11 +106,14 @@ export const useAddCoinAccount = () => {
         return availableTypes;
     }, []);
 
-    const getAvailableAccountTypesForNetwork = ({ network }: { network: Network }) =>
-        availableNetworkAccountTypes.get(network.symbol) ?? [NORMAL_ACCOUNT_TYPE as AccountType];
+    const getAvailableAccountTypesForNetworkSymbol = ({
+        networkSymbol,
+    }: {
+        networkSymbol: NetworkSymbol;
+    }) => availableNetworkAccountTypes.get(networkSymbol) ?? [NORMAL_ACCOUNT_TYPE as AccountType];
```
Comment (PeKne) [inline suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: why is this type casting necessary? `NORMAL_ACCOUNT_TYPE` should be already correct type. IF not change it at the place where it is defined please.

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts [hunk 2]
```diff
@@ -106,11 +106,14 @@ export const useAddCoinAccount = () => {
...
 
-    const getDefaultAccountType = ({ network }: { network: Network }) =>
-        getAvailableAccountTypesForNetwork({ network })[0];
+    const getDefaultAccountType = ({ networkSymbol }: { networkSymbol: NetworkSymbol }) =>
```
Comment (PeKne) [inline suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: Is not this function redundant? Could not you always use `NORMAL_ACCOUNT_TYPE`? If I'm not mistaken, it will be always on index 0.

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts [hunk 3]
```diff
@@ -122,7 +125,7 @@ export const useAddCoinAccount = () => {
         const type =
             accountType ??
             getDefaultAccountType({
```
Comment (PeKne) [inline suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: then you could just replace this call by `NORMAL_ACCOUNT_TYPE`

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts [hunk 4]
```diff
@@ -281,38 +294,46 @@ export const useAddCoinAccount = () => {
...
         const account = await dispatch(
             addAndDiscoverNetworkAccountThunk({
                 network,
-                accountType: selectedType,
                 deviceState: device.state,
             }),
         ).unwrap();
 
         if (!account) {
+            let screen = 'accounts';
```
Comment (PeKne) [inline suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: `accounts` is not a valid route from `routes.ts`. Why do you assign it here?

Comment (vytick) [reply suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: good catch, that is a mistake

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts (hunk 2 above)
Comment (vytick) [reply suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: Good idea 👍

Comment (vytick) [reply suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: 9dd5a668c4

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts (hunk 1 above)
Comment (vytick) [reply suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: 9dd5a668c4

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts (hunk 4 above)
Comment (vytick) [reply suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: 9dd5a668c4

File: suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts (hunk 3 above)
Comment (vytick) [reply suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts]: 9dd5a668c4

**Review by PeKne — APPROVED** [review]
I haven' test it, but all my objetions been resolved. Approving 👍
