### PR TITLE
wipe device with webusb [need help]

### LINKED ISSUE #1064: Wipe device with webusb transport
Steps to reproduce

- transport webusb 
- model t1 
- onboarding -> create new wallet
- settings -> wipe device
- no we see fallback screen for uninitialized device, which leads to onboarding again -> go to onboarding
- try to create new wallet
- now get error "device disconnected"

Probably needs fix in trezor-link. Webusb transport uses device_id as path, which changes after device wipe internally but is not propagated to more high level layers (connect, suite).

### LINKED ISSUE #1504: Webusb troubles
## Unreadable hid device listing 

~~I have just found that webusb stopped listing unreadable hid devices. Doing this helps: https://github.com/trezor/connect/pull/558/files~~ fixed

## Firmware update

~~After firmware update is finished, error in console and features are not reloaded~~ 
image  seems to be solved

## Wipe device 
https://github.com/trezor/trezor-suite/issues/1064

### PR DESCRIPTION
**Pull request by mroz22**
this does fix https://github.com/trezor/trezor-suite/issues/1064 and closes #1504
but I also found few more problems. Please check it @matejzak 

### with nothing remembered

before wipe
image

after wipe. not possible to cancel. after disconnect or reload device is not paired. works fine.
image

### with remembered wallets

state of affairs right before wipe

image

after wipe

image

after disconnecting device switch-device modal still looks like this. that is expected 

image

what happens when I connect the device again? lets see. right after it is connected nothing happens. it is not paired yet.

In switch-device modal I may click on "Find Trezor" button 

image

After I do so and pair device: 

image

- [ ] question: here I would expect another device to appear alongside with the device previously saved and already wiped. 
- [ ] question: also, shouldnt wipe wipe everything? Or is it expected usecase that user wipes device but wants to keep it saved in read only mode? 

then I click on the solve issue button and get this:

image

- [ ] question: should swith device button here be either shown only if there are multiple physical devices or kept as it is and reworded to "switch wallet"? 

So, I pass through onboarding and switch device modal looks like this again

image

but of course saved addresses and maybe transactions are no longer valid. this does not happen only with webusb but also with bridge transport

### CODE REVIEW

File: packages/suite/src/actions/settings/deviceSettingsActions.ts [hunk 1]
```diff
@@ -108,9 +108,7 @@ export const resetDevice = (params: ResetDevice = {}) => async (
         ...defaults,
         ...params,
     });
-    if (result.success) {
-        dispatch(addToast({ type: 'settings-applied' }));
```
Comment (mroz22) [inline packages/suite/src/actions/settings/deviceSettingsActions.ts:112]: only used in onbaording, we probably don't want to see 'settings-applied' toast there
