### PR TITLE
fix(suite): coin filter outline

### LINKED ISSUE #10927: Empower/Outer circle of coins in filter is misaligned
Specifically on Linux the circles around coins are misaligned. 

image
image

### PR DESCRIPTION
**Pull request by dahaca**
## Description

* fix coin filter outline

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10927

## Screenshots:

image

### CODE REVIEW

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx [hunk 1]
```diff
@@ -8,16 +8,26 @@ import { spacingsPx } from '@trezor/theme';
 
 const StyledCoinLogo = styled(CoinLogo)<{ isSelected?: boolean }>`
     display: block;
-    ${({ isSelected }) => !isSelected && `filter: grayscale(100%);`}
+    border-radius: 50%;
```
Comment (AdamSchinzel) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx]:
```suggestion
    border-radius: ${borders.radii.full};
```

**Review by AdamSchinzel — APPROVED** [review]
Just a small thing
