### PR TITLE
fix(suite): fixed Suite crash on cancelling stake transaction

### LINKED ISSUE #17646: Solana staking modal can be exited and canceling the transaction on the device causes Trezor Suite to crash.
**Describe the bug**  

**This bug occurs only with Trezord 2.0.27.**  

The "X" button does not cancel the transaction on the device. If you navigate to another part of Trezor Suite and then manually cancel the transaction on the device, Trezor Suite crashes.  

**Steps to reproduce:** 
- Enable Trezord 2.0.27
- Start staking SOL.  
- Close the staking confirmation popup in Trezor Suite (without taking any action on the Trezor device).  
- Leave the Solana account and navigate to another section, such as the dashboard. (If you stay on the Solana account, the crash does not occur.)  
- Cancel the transaction on the Trezor device.  
- Trezor Suite crashes with the following message:  

**Info:**
 - Suite version: web 25.3.1 (9fd7070b92298fa6477655ded905df186fa3e209)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2880x1800
 - Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 2.0.27

**Screenshots:**

Image

Image

**Note(s):**
https://satoshilabs.sentry.io/issues/6363391606/?query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D%20destructure%20property%20%27symbol%27%20of%20%27s%27&stream_index=0

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Fixed Suite crashing when the user cancels a transaction in the stake/unstake/claim modal and then cancels the transaction on the device.

Happens when using `BridgeTransport` version `2.0.27`.

## Related Issue

Resolve #17646 

## Screenshots:

https://github.com/user-attachments/assets/2a3a41b6-fd1e-4c57-ad99-be3bf6a7820f

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 1]
```diff
@@ -210,9 +210,7 @@ export const TransactionReviewModalContent = ({
               .find(type => type) || null;
 
     const onCancel = () => {
-        if (isRbfConfirmedError || shouldCheckTxTimeValidity) {
-            dispatch(modalActions.onCancel());
-        }
+        dispatch(modalActions.onCancel());
```
Comment (TomasBoda) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx:213]: Removed the condition because it doesn't make sense to me. The modal should close every time the user clicks on the `X` button.

**Review by tomasklim — APPROVED** [review]
LGTM
