### PR TITLE
fix(suite-native): better trade close handling

### LINKED ISSUE #18332: Mobile Trade: webview does not close on finished buy
When going through buy flow, I can correctly buy some asset, but after the trade is done, webview does not close. Not automatically nor on clicking designated button -> url callback does not work properly there. 

**Expected behavior**
when the url callback is triggered, webview should hide

### PR DESCRIPTION
**Pull request by vytick**
Moonpay was returning close url with some extra parameters and exact matching make it not work. This should do the trick

## Related Issue

Resolve #18332

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/webview-close&lookback=7)

### CODE REVIEW

File: suite-native/module-trading/src/screens/TradingWebviewScreen.tsx [hunk 1]
```diff
@@ -37,11 +37,14 @@ export const TradingWebViewScreen = () => {
     const dispatch = useDispatch();
     const receivedDeeplinkUrl = useURL();
 
-    // when url matches closeCallbackUrl or TRADING_URL_DEFAULT_BACK, go back and mark the trade to be opened
+    // when url contains closeCallbackUrl or TRADING_URL_DEFAULT_BACK, go back and mark the trade to be opened
     const checkForGoBackOnUrl = useCallback(
         (url: string | null) => {
             const urlString = url ?? '';
-            if ([closeCallbackUrl, TRADING_URL_DEFAULT_BACK].includes(urlString)) {
```
Comment (jbazant) [inline suite-native/module-trading/src/screens/TradingWebviewScreen.tsx:44]: **issue:** Add tests please.

**Review by jbazant — COMMENTED** [review]
Reviewed from mobile (waiting at hospital again), but I believe this can be tested. Even if it will need to move this logic to the utility function.

File: suite-native/module-trading/src/screens/TradingWebviewScreen.tsx (hunk 1 above)
Comment (vytick) [reply suite-native/module-trading/src/screens/TradingWebviewScreen.tsx:44]: updated in [baf6ba7](https://github.com/trezor/trezor-suite/pull/18852/commits/baf6ba74b338409b1eaeac1b1c95f30cbf0ab1dc)

**Review by jbazant — APPROVED** [review]
LGTM!
