### PR TITLE
fix(suite-desktop): buffer overload  of spawned process (bridge, tor)

### LINKED ISSUE #4306: Stuck transaction signing (coin stuck)
**Describe the bug**
People are complaining about stucked transaction signing. See more info here https://satoshilabs.slack.com/archives/CL1D61PQF/p1632439318059100 and support ticket #96208. 

**Note(s):**
- probably Connect issue
- it happens in Suite and old wallet too
- happens on T1
- resolved using Electrum
- it's probably not about complexity of the transaction

### PR DESCRIPTION
**Pull request by tomasklim**
closes #4306

### CODE REVIEW

File: packages/suite-desktop/src-electron/libs/processes/BaseProcess.ts [hunk 1]
```diff
@@ -135,6 +135,7 @@ abstract class BaseProcess {
         this.process = spawn(processPath, params, {
             cwd: processDir,
             env: processEnv,
+            stdio: ['ignore', 'ignore', 'ignore'],
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/libs/processes/BaseProcess.ts:138]: 'ignore': equivalent to ['ignore', 'ignore', 'ignore'], but never mind...
```suggestion
            stdio: 'ignore',
```

**Review by matejkriz — APPROVED** [review]
👏 🎖️

**Review by szymonlesisz — APPROVED** [review]
