### PR TITLE
fix(transactions): ERC20 token amount search

### LINKED ISSUE #3440: Search in Ethereum transaction history error:  Cannot read property 'amount' of undefined
**Describe the bug**
I see `Uncaught TypeError: Cannot read property 'amount' of undefined` error when i try to seach in Ethereum transactions.
Other coins are OK. Please see video and screenshots.
Same results in development master 21.3.0 2d0d60b3e27062c63812a720d365b15e109f5d33 in Firefox

**Steps to reproduce:**
1. load Ethereum wallet with transaction history
2. search in transaction hsitory
3. observe Chrome or Firefox console

**Info:**
 - Suite version: web 21.2.3 (9cf47b5b526bbb5cda585e717fbbf0f5b93b8cc0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Screenshots:**

https://www.youtube.com/watch?v=JzWYflQ5vjU&amp%3Bfeature=youtu.be

image

image

### PR DESCRIPTION
**Pull request by keraf**
Fixes #3440

### CODE REVIEW

**Review by slowbackspace — APPROVED** [review]

**Review by szymonlesisz — APPROVED** [review]

File: packages/suite/src/utils/wallet/transactionUtils.ts [hunk 1]
```diff
@@ -495,7 +495,11 @@ const numberSearchFilter = (
     amount: BigNumber,
     operator: typeof searchOperators[number],
 ) => {
-    const targetAmount = getTargetAmount(transaction.targets[0], transaction);
+    const targetAmount =
+        transaction.targets[0] !== undefined
+            ? getTargetAmount(transaction.targets[0], transaction)
```
Comment (slowbackspace) [inline packages/suite/src/utils/wallet/transactionUtils.ts:500]: now I realised, does it mean that you can't search a tx by the amount in, for example, its 3rd output? 
Eg. when you sent btc tx to multiple recipients: 1st will receive 0.1 btc, 2nd 0.2 btc, 3rd, 0.3b tc. Will I be able to find such transaction by typing "0.3"? It most likely won't affect many users, but would be nice to handle properly.

Anyway, I would merge this as it is since it should fix the issue, and for the rest we can create an issue for now. What do you think?

Comment (slowbackspace) [reply packages/suite/src/utils/wallet/transactionUtils.ts:500]: aand it is merged

Comment (keraf) [reply packages/suite/src/utils/wallet/transactionUtils.ts:500]: That's a good point. Can't remember the exact reason it was done this way but I guess it's worth testing/investigating. If anyone from @trezor/qa could check it out and open an issue if relevant, that would be awesome :black_heart:

Comment (bosomt) [reply packages/suite/src/utils/wallet/transactionUtils.ts:500]: i was able to reproduce it, i will send issue in the morning
