### PR TITLE
Tor Statuses prerequisite: Stability Improvements

### LINKED ISSUE #5612: Tor toggle is slow and doesn't reflect connection state
**Describe the bug**
It takes about 10 seconds to switch on the Tor.
If you click twice, the toggle switches right away, but it doesn't mean Tor is immediately connected.

**Steps to reproduce:**
1. Go to Setting/Device
2. Turn on Tor
3. Wait

**Info:**
 - Suite version: desktop 22.6.2 (f45c75705f153ec0dc44cb72fec2e5ec4a031b7c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: 
 - Transport: bridge 2.0.27

**Expected result:**
- After turning Tor on from anywhere the `Loading` state is initiated
- Toggle in settings is green on `ON` or `Loading`
- When `Loading` the indicator on the Tor icon in the header becomes a blinking orange dot to signify the loading state
- When `Loading`,  in settings show "Enabling Tor" and a spinner to the left of the toggle on desktop and a spinner next to the header on mobile.
- When `Loading`, in onboarding show a loader in the button until loaded, then proceed.
- When `Loading`, in custom backends don't enable onion backends until Tor is finished loading and enabled.
- When loading fails - revert the Tor state to OFF and show a notification 
- In onboarding and custom backends that means that the processes do not continue and simply stay the same as before attempting to enable Tor 

**Actual result:**

https://user-images.githubusercontent.com/26002916/173539627-9e17611f-36c2-44a0-818b-db49ee7a3793.mov

### PR DESCRIPTION
**Pull request by dahaca**
Update tor toggle logic to make sure Tor is definitely working if it's toggled.

### CODE REVIEW

File: packages/suite/src/components/suite/Translation/components/BaseTranslation/index.tsx [hunk 1]
```diff
@@ -14,13 +14,15 @@ type OwnProps = {
...
+export type TranslationKey = keyof typeof messages;
+
 type PrimitiveType = string | number | boolean | Date | null | undefined;
 
 // Add MessageDescriptor type to values entry
 // eslint-disable-next-line @typescript-eslint/ban-types
 type FormatXMLElementFn = (...args: any[]) => string | object;
 export interface ExtendedMessageDescriptor extends MessageDescriptor {
-    id: keyof typeof messages;
+    id: TranslationKey;
```
Comment (tomasklim) [inline packages/suite/src/components/suite/Translation/components/BaseTranslation/index.tsx:24]: `keyof typeof messages;` has 1 more occurrence at the top of this file. Change it also there

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 2]
```diff
@@ -39,54 +39,79 @@ const init: Module = async ({ mainWindow, store, interceptor }) => {
...
-        const payload = start
-            ? {
-                  proxy: `socks://${address}`,
-                  useOnionLinks: true,
-              }
-            : { proxy: '', useOnionLinks: false };
-
-        logger.info('tor', `${start ? 'Enable' : 'Disable'} proxy ${payload.proxy}`);
-        await TrezorConnect.setProxy(payload);
+    ipcMain.handle('tor/toggle', async (_: unknown, shouldEnableTor: boolean) => {
```
Comment (tomasklim) [inline packages/suite-desktop/src-electron/modules/tor.ts:68]: I definitely agree with renaming `start` parameter. Do it also in other files. However, I am not sure if `shouldEnableTor` is a good name. It sounds like I am not able to disable it

File: packages/suite-desktop-api/src/factory.ts [hunk 3]
```diff
@@ -87,9 +87,7 @@ export const factory = <R extends StrictIpcRenderer<any>>(ipcRenderer?: R): Desk
 
         // Tor
         getTorStatus: () => ipcRenderer.send('tor/get-status'),
-        toggleTor: start => {
-            if (validation.isPrimitive('boolean', start)) ipcRenderer.send('tor/toggle', start);
-        },
+        toggleTor: start => ipcRenderer.invoke('tor/toggle', start),
```
Comment (marekrjpolak) [inline packages/suite-desktop-api/src/factory.ts]: Why is the validation no longer needed?

File: packages/suite/src/actions/suite/suiteActions.ts [hunk 4]
```diff
@@ -19,6 +19,7 @@ import type {
     AppState,
 } from '@suite-types';
 import type { DebugModeOptions, AutodetectSettings } from '@suite-reducers/suiteReducer';
+import { TranslationKey } from '@suite-components/Translation/components/BaseTranslation';
```
Comment (tomasklim) [inline packages/suite/src/actions/suite/suiteActions.ts]: `import type`

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 5]
```diff
@@ -39,54 +39,79 @@ const init: Module = async ({ mainWindow, store, interceptor }) => {
...
+        const shouldEnableTor = settings.running;
+        const isTorRunning = (await tor.status()).process;
+
+        if (shouldEnableTor === isTorRunning) {
+            return;
         }
 
-        // Start (or stop) routing all communication through tor.
-        if (settings.running) {
+        if (shouldEnableTor === true) {
```
Comment (tomasklim) [inline packages/suite-desktop/src-electron/modules/tor.ts:57]:
```suggestion
        if (shouldEnableTor) {
```

File: packages/suite/src/utils/suite/tor.ts [hunk 6]
```diff
@@ -36,3 +36,13 @@ export const isOnionUrl = (url: string) => {
     const hostname = parseHostname(url);
     return !!hostname && isTorDomain(hostname);
 };
+
+export const baseFetch = window.fetch;
```
Comment (marekrjpolak) [inline packages/suite/src/utils/suite/tor.ts:41]: Will we have global `window` object wherever we realistically could import this file? Probably yes, just wanted to be sure.

File: packages/suite/src/actions/suite/suiteActions.ts (hunk 4 above)
Comment (marekrjpolak) [inline packages/suite/src/actions/suite/suiteActions.ts]: nit: `import type`

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 7]
```diff
@@ -39,54 +39,79 @@ const init: Module = async ({ mainWindow, store, interceptor }) => {
...
-            : { proxy: '', useOnionLinks: false };
-
-        logger.info('tor', `${start ? 'Enable' : 'Disable'} proxy ${payload.proxy}`);
-        await TrezorConnect.setProxy(payload);
+    ipcMain.handle('tor/toggle', async (_: unknown, shouldEnableTor: boolean) => {
+        logger.info('tor', `Toggling ${shouldEnableTor ? 'ON' : 'OFF'}`);
+
+        const settings: TorSettings = { ...store.getTorSettings(), running: shouldEnableTor };
+
+        try {
```
Comment (tomasklim) [inline packages/suite-desktop/src-electron/modules/tor.ts:73]: Split this into two `try, catch` blocks.

Deduplicate 
```
const payload = !shouldEnableTor
    ? {
          proxy: `socks://${address}`,
          useOnionLinks: true,
      }
    : { proxy: '', useOnionLinks: false };
```

File: packages/suite/src/reducers/suite/notificationReducer.ts [hunk 8]
```diff
@@ -5,6 +5,7 @@ import { Action, TrezorDevice } from '@suite-types';
 import { Network } from '@wallet-types';
 import { UpdateState } from '@suite-reducers/desktopUpdateReducer';
 import type { PROTOCOL_SCHEME } from '@suite-constants/protocol';
+import { TranslationKey } from '@suite-components/Translation/components/BaseTranslation';
```
Comment (marekrjpolak) [inline packages/suite/src/reducers/suite/notificationReducer.ts]: nit: `import type`

File: packages/suite/src/actions/suite/suiteActions.ts [hunk 9]
```diff
@@ -156,25 +157,39 @@ export const updateTorStatus = (payload: boolean): SuiteAction => ({
     payload,
 });
 
-export const toggleTor = (enable: boolean) => async (dispatch: Dispatch, getState: GetState) => {
+export const toggleTor = (isEnabled: boolean) => async (dispatch: Dispatch, getState: GetState) => {
```
Comment (marekrjpolak) [inline packages/suite/src/actions/suite/suiteActions.ts]: Not sure about the naming convention here. Does `isEnabled` param of `toggle` function mean it is already enabled, or that it should be enabled?

File: packages/suite/src/actions/suite/suiteActions.ts [hunk 10]
```diff
@@ -156,25 +157,39 @@ export const updateTorStatus = (payload: boolean): SuiteAction => ({
...
     }
-    desktopApi.toggleTor(enable);
 
-    analytics.report({
-        type: EventType.SettingsTor,
-        payload: {
-            value: enable,
-        },
-    });
+    const ipcResponce = await desktopApi.toggleTor(isEnabled);
```
Comment (marekrjpolak) [inline packages/suite/src/actions/suite/suiteActions.ts]: nit: respon**s**e

**Review by tomasklim — CHANGES_REQUESTED** [review]
Closes https://github.com/trezor/trezor-suite/issues/5593

1. When I enable Tor, the first request to `http://data.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion` takes ~25seconds. **OLD BUG which is also in current EAP.**

Screenshot 2022-06-20 at 11 59 26
 
1) Is now 10 seconds. It is also available in the current production version. The problem I see there is that the user is waiting for the tor loader and then he has to wait another 10 seconds.

File: packages/suite-desktop-api/src/api.ts [hunk 11]
```diff
@@ -90,7 +90,7 @@ export interface DesktopApi {
     getHttpReceiverAddress: DesktopApiInvoke<'server/request-address'>;
     // Tor
     getTorStatus: DesktopApiSend<'tor/get-status'>;
-    toggleTor: DesktopApiSend<'tor/toggle'>;
+    toggleTor: DesktopApiInvoke<'tor/toggle'>;
```
Comment (szymonlesisz) [inline packages/suite-desktop-api/src/api.ts:93]: CI validation fails because you've changed toggleTor message from send to invoke, but you didnt update unit tests in desktop-api package.
I would separate all changes regarding desktop-api package (including modified tests) and suite-desktop implementation. [reference example](https://github.com/trezor/trezor-suite/pull/5632/commits)

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 12]
```diff
@@ -39,54 +39,79 @@ const init: Module = async ({ mainWindow, store, interceptor }) => {
...
+
+            return { success: false, error: errorMessage };
+        }
+
+        return { success: true };
     });
 
+    // TODO: Change to ipcMain.handle?
+    // desktopApi.getTorStatus();
+    // desktopApi.on('tor/status', updateTorStatus);
```
Comment (marekrjpolak) [inline packages/suite-desktop/src-electron/modules/tor.ts]: Not now imo, because this way, you're able to handle renderer-initiated `getTorStatus` query and electron-initiated `tor/status` change in the same way.

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 13]
```diff
@@ -39,54 +39,79 @@ const init: Module = async ({ mainWindow, store, interceptor }) => {
...
+            await TrezorConnect.setProxy(payload);
+
+            logger.info(
+                'tor',
+                `${shouldEnableTor ? 'Enabled' : 'Disabled'} proxy ${payload.proxy}`,
+            );
+        } catch (error) {
+            await setupTor({ ...settings, running: !shouldEnableTor });
+
+            const payload = !shouldEnableTor
```
Comment (marekrjpolak) [inline packages/suite-desktop/src-electron/modules/tor.ts]: Maybe extract the repeated code (only the boolean is flipped) into a subroutine?

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 14]
```diff
@@ -39,54 +39,79 @@ const init: Module = async ({ mainWindow, store, interceptor }) => {
...
+            await tor.start();
+
             setProxy(`socks5://${host}:${port}`);
         } else {
+            await tor.stop();
             setProxy('');
         }
 
-        // Notify the renderer.
-        mainWindow.webContents.send('tor/status', settings.running);
```
Comment (marekrjpolak) [inline packages/suite-desktop/src-electron/modules/tor.ts:69]: By not emitting `tor/status` here but explicitly returning it from `tor/toggle` instead (if I understand it correctly), it isn't emitted from the top level `setupTor` call at the end of this file anymore. Was it intended? Couldn't it cause an error in the renderer?

File: packages/suite/src/support/suite/useTor.tsx [hunk 15]
```diff
@@ -1,40 +1,30 @@
...
-    }, [isTor]);
 
     const { updateTorStatus } = useActions({
         updateTorStatus: suiteActions.updateTorStatus,
     });
 
+    // For initial render, not toggle. Will be removed once state init rework is merged
+    useEffect(() => {
+        window.fetch = isTor ? torFetch : window.fetch;
+    }, []); // eslint-disable-line
```
Comment (marekrjpolak) [inline packages/suite/src/support/suite/useTor.tsx]: Given that this `useEffect` should trigger only once, based on the first value in `state.suite.tor`, wouldn't it be cleaner to move it to a middleware, maybe to the `STORAGE.LOADED` event? That way we'd be sure that it's initialized with the value from IndexedDB (and not hardcoded initial value in the reducer).

**Comment by karliatto** [comment]
I think if we really want to wait until Tor is working to show it in the switch to the user we will have to block the UI and show a loading, otherwise in the current implementation the user could start the process multiple times by clicking multiple times in the switch when Tor is starting and it is a bit messy.

It is an asynchronous process and should be treated as it is.

If we really want to give the feedback to the user that Tor is active or not in the switch, I think we need to add a new status to the switch, loading. Maybe it could be a spinner loading in the button. 

Wdyt?

**Review by marekrjpolak — CHANGES_REQUESTED** [review]

**Comment by marekrjpolak** [comment]
> If we really want to give the feedback to the user that Tor is active or not in the switch, I think we need to add a new status to the switch, loading. Maybe it could be a spinner loading in the button.

@karliatto Yes that's exactly what @dahaca is working on right now (or in a moment). It's even possible that we cherrypick only the UI changes and not this PR in the end.

File: packages/suite-desktop-api/src/api.ts (hunk 11 above)
Comment (marekrjpolak) [reply packages/suite-desktop-api/src/api.ts:93]: https://github.com/trezor/trezor-suite/pull/5651/commits/82f86643829356cdbbcae390412dffb71bf614ca

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 16]
```diff
@@ -38,55 +38,81 @@ const init: Module = async ({ mainWindow, store, interceptor }) => {
...
             setProxy(`socks5://${host}:${port}`);
         } else {
+            await tor.stop();
             setProxy('');
         }
 
+        persistSettings(settings);
+
         // Notify the renderer.
         mainWindow.webContents.send('tor/status', settings.running);
```
Comment (tomasklim) [inline packages/suite-desktop/src-electron/modules/tor.ts]: On toggle tor, tor status change is emitted twice in renderer layer.
Screenshot 2022-06-23 at 8 51 51

Which results into this ugly bug:
Immediately when the tor is started, you click on the switch (because it is not disabled anymore), and it disables Tor but then another tor status comes and enables it again. And then it is disabled again.


https://user-images.githubusercontent.com/33235762/175234549-58e87a16-89ba-48d3-8835-36eaa6230285.mov

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite-desktop/src-electron/modules/tor.ts (hunk 16 above)
Comment (marekrjpolak) [reply packages/suite-desktop/src-electron/modules/tor.ts]: Hopefully resolved by https://github.com/trezor/trezor-suite/pull/5651/commits/9fb0247f6482d184e1874323c46bddc4ba1e87c7

**Review by tomasklim — APPROVED** [review]

**Review by marekrjpolak — APPROVED** [review]
