### PR TITLE
fix(suite): add new tor icon & fix badges misplacement

### LINKED ISSUE #4228: New tor icon + badges misplacement
**Badges** on Tor icon and Activity icon are misplaced in the Desktop app: 

Screen Shot 2021-09-03 at 16 07 04

While were are at it, please replace the Tor icon with the new (outline) design: [Zeplin](https://zpl.io/b65ylYy)

image

### PR DESCRIPTION
**Pull request by dimasivan**
fix #4228

### CODE REVIEW

**Review by tomasklim — CHANGES_REQUESTED** [review]
Indicators are still misplaced

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx [hunk 1]
```diff
@@ -128,6 +112,22 @@ const NavigationActions = (props: Props) => {
...
+                        },
+                    });
+                    setDiscreetMode(!discreetMode);
+                }}
+                isActive={discreetMode}
+                label={<Translation id="TR_DISCREET" />}
+                icon={discreetMode ? 'HIDE' : 'SHOW'}
+                isMobileLayout={props.isMobileLayout}
+            />
+
```
Comment (tomasklim) [inline packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx]: Why was it moved?

File: packages/components/src/images/icons/tor.svg [hunk 2]
```diff
@@ -1 +1,3 @@
...
\ No newline at end of file
+<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
+    <path fill="gray" fill-rule="evenodd" d="M11 3.055C6.5 3.552 3 7.367 3 12s3.5 8.448 8 8.945V3.055zm2 17.89c4.5-.497 8-4.312 8-8.945s-3.5-8.448-8-8.945v1.343c3.762.49 6.667 3.707 6.667 7.602 0 3.896-2.905 7.113-6.667 7.602v1.343zM12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1zm1 6.782v-1.36c2.653.472 4.667 2.79 4.667 5.578 0 2.789-2.014 5.107-4.667 5.58v-1.363c1.911-.452 3.333-2.168 3.333-4.217 0-2.05-1.422-3.766-3.333-4.218zM14.333 12c0 .93-.545 1.734-1.333 2.108V9.891c.788.374 1.333 1.178 1.333 2.109z" clip-rule="evenodd"/>
+</svg>
```
Comment (tomasklim) [inline packages/components/src/images/icons/tor.svg]:
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <path fill-rule="evenodd" d="M11 3.055C6.5 3.552 3 7.367 3 12s3.5 8.448 8 8.945V3.055zm2 17.89c4.5-.497 8-4.312 8-8.945s-3.5-8.448-8-8.945v1.343c3.762.49 6.667 3.707 6.667 7.602 0 3.896-2.905 7.113-6.667 7.602v1.343zM12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1zm1 6.782v-1.36c2.653.472 4.667 2.79 4.667 5.578 0 2.789-2.014 5.107-4.667 5.58v-1.363c1.911-.452 3.333-2.168 3.333-4.217 0-2.05-1.422-3.766-3.333-4.218zM14.333 12c0 .93-.545 1.734-1.333 2.108V9.891c.788.374 1.333 1.178 1.333 2.109z" clip-rule="evenodd"/>
</svg>
```
I prefer SVG without default colour. It can cause potential colour bugs.

**Review by tomasklim — CHANGES_REQUESTED** [review]
Design:
Screenshot 2021-09-07 at 13 27 45
Now:
Screenshot 2021-09-07 at 13 27 48

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx (hunk 1 above)
Comment (dimasivan) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx]: fixed in 4dc13ab

File: packages/components/src/images/icons/tor.svg (hunk 2 above)
Comment (dimasivan) [reply packages/components/src/images/icons/tor.svg]: 4dc13ab

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx [hunk 3]
```diff
@@ -78,8 +78,8 @@ const Indicator = styled.div`
     width: 10px;
     border-radius: 50%;
     position: absolute;
-    top: 10px;
-    right: 10px;
+    top: 0px;
+    right: -1px;
```
Comment (tomasklim) [inline packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx:82]: Looks like that this is not shared with Bell

Screenshot 2021-09-09 at 10 32 03

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx (hunk 3 above)
Comment (dimasivan) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx:82]: 73a67f5

**Review by tomasklim — APPROVED** [review]
