### PR TITLE
connect: script_types 

### LINKED ISSUE #6234: Trezor Connect P2WSH 2of3 multisig change address ignores multisig
I am having an issue with using trezor-connect to send a p2wsh multisig change output. 
I have setup a repeatable example here:

[example](https://github.com/CaveRock/trezor-connect-p2wsh-multisig)

I have not been able to find any examples on how to use trezor connect to send a change output to a p2wsh 2of3 change address.

In my example above the change is instead being sent to a pay-to-script-hash for the keypath instead of using the multisig.

My apologies in advance if I am using the incorrect place for this post. Additionally apologies in the instance I have made some elementary error.

### LINKED ISSUE #6343: Trezor Connect and BIP-48 multisig wallets with segwit not working
**Describe the bug**
BIP-48 compatible multisig wallets using segwit not supported by Trezor Connect.

**Info:**

-  Trezor connect version 9; I think it affects all versions

**How to reproduce**
Create a BIP-48 multisig wallet with spendp2shwitness or spendwitness and use a change output.

**Expected behavior**
There are four types of BIP-48 wallets:
- old format (not compatible with BIP-48) `m/48'/coin'/account'` (PAYTOMULTISIG)
- multisig without segwit: `m/48'/coin'/account'/0'`  (PAYTOMULTISIG)
- multisig with p2sh segwit: `m/48'/coin'/account'/1'` (PAYTOP2SHWITNESS)
- multisig with native segwit: `m/48'/coin'/account'/2'` (PAYTOWITNESS)

Note that segwit multisig wallets need to use `PAYTOP2SHWITNESS` or `PAYTOWITNESS`; `PAYTOMULTISIG` is only used for non-segwit wallets.  This was a design decision for segwit to avoid adding PAYTOMULTISIGP2SHWITNESS, etc.  Instead multisig is simply indicated by the presence of the multisig structure.

The checks for  `getOutputScriptType` and `getScriptType` are wrong for segwit multisig wallets:

https://github.com/trezor/connect/blob/develop/src/js/utils/pathUtils.js#L66-L105

Compare this with the correct checks that the Trezor One does:

https://github.com/trezor/trezor-firmware/blob/master/legacy/firmware/crypto.c#L566-L606

Here is an example transaction structure that complains that output type should be PAYTOMULTISIG (which would create a non-segwit address):

```json
{
  "coin": "TEST",
  "inputs": [
    {
      "address_n": [
        2147483696,
        2147483649,
        2147483652,
        2147483649,
        0,
        0
      ],
      "amount": 200000,
      "multisig": {
        "m": 2,
        "pubkeys": [
          {
            "address_n": [
              0,
              0
            ],
            "node": "tpubDFQZ2zbh87ztfQvvB9sbPxUzmp8gghwzNETtmFw9cGD9Z6qPo2Fs3ohp3J6M3e1uJCpsXq9z52JBC4Ey3BsncaXTdiv68cgZ9SFpg1RmHft"
          },
          {
            "address_n": [
              0,
              0
            ],
            "node": "tpubDEs6bv9sDm5DWbcQujozo4AyByVgirWjtDxa7wJ5bPFvbLgBwFfUtyjaFUops3qVu3LtC3CJuXjBMQYEsTTZviDD8B5VZ2y8XVeHgMKWoJS"
          },
          {
            "address_n": [
              0,
              0
            ],
            "node": "tpubDErpDGjyZFY6fAx2vZDz9fch43byUQwBA92om8H9MKnduEEABr7xv7xvxz7QCULpMRKV4bbaYqkqbcJH3tZKYko8cnnJKpebLGcNMW2b1jq"
          }
        ],
        "signatures": [
          "",
          "",
          ""
        ]
      },
      "prev_hash": "1b98f348b2129f5ae6dc976ef24cc8bb1a47e011ee9bbf2d49721e207485d412",
      "prev_index": 0,
      "script_type": "SPENDP2SHWITNESS"
    }
  ],
  "outputs": [
    {
      "address": "2NDzn3wDCJLcyY26gMvHJN1Eh7buX6yGoas",
      "amount": 10000,
      "script_type": "PAYTOADDRESS"
    },
    {
      "address_n": [
        2147483696,
        2147483649,
        2147483652,
        2147483649,
        1,
        0
      ],
      "amount": 188930,
      "multisig": {
        "m": 2,
        "pubkeys": [
          {
            "address_n": [
              1,
              0
            ],
            "node": "tpubDFQZ2zbh87ztfQvvB9sbPxUzmp8gghwzNETtmFw9cGD9Z6qPo2Fs3ohp3J6M3e1uJCpsXq9z52JBC4Ey3BsncaXTdiv68cgZ9SFpg1RmHft"
          },
          {
            "address_n": [
              1,
              0
            ],
            "node": "tpubDEs6bv9sDm5DWbcQujozo4AyByVgirWjtDxa7wJ5bPFvbLgBwFfUtyjaFUops3qVu3LtC3CJuXjBMQYEsTTZviDD8B5VZ2y8XVeHgMKWoJS"
          },
          {
            "address_n": [
              1,
              0
            ],
            "node": "tpubDErpDGjyZFY6fAx2vZDz9fch43byUQwBA92om8H9MKnduEEABr7xv7xvxz7QCULpMRKV4bbaYqkqbcJH3tZKYko8cnnJKpebLGcNMW2b1jq"
          }
        ]
      },
      "script_type": "PAYTOP2SHWITNESS"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by mroz22**
## Description

- stop doing outputs script_type  validation based on path for change addreses (todo link issue)
- only provide script_type as a fallback in cases we can reasonable guess it, otherwise let it fallback to SPENDADDRESS from protobuf
- in verifyTx (which is called after initial outputs validation/fallback) use provided script_types instead of retrieving them from getOutputScript type method

## Related Issue

- depends on #6389 
- resolves #6343 
- resolves #6234

### CODE REVIEW

File: packages/connect/src/utils/pathUtils.ts [hunk 1]
```diff
@@ -63,42 +63,75 @@ export const getAccountType = (path: number[] | undefined) => {
...
 
     const p = fromHardened(path[0]);
+
     switch (p) {
-        case 48:
-            return 'PAYTOMULTISIG';
+        case 44:
+            return 'PAYTOADDRESS';
+        case 48: {
+            if (path.length !== 6) return undefined;
```
Comment (mroz22) [inline packages/connect/src/utils/pathUtils.ts]: < 4

**Review by szymonlesisz — APPROVED** [review]

**Comment by CaveRock** [comment]
@mroz22  Will this update remove the need to confirm p2wsh multisig change addresses on device?
