### PR TITLE
Fix/missing fiat rates for txs

### LINKED ISSUE #12762: Fiat rates not showing for transactions on remembered wallet
**Describe the bug**
FIAT rate is not showing for past transactions on the "Overview" tab of the accounts for remembered wallet after Suite update.

**Steps to reproduce:**
1. Install older version then 24.6.1
2. Connect Trezor
3. Wait for discovery and click on remember wallet
4. Close Suite
5. Install version 24.6.1
6. Click on any account
7. Scroll to transaction history

**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.7.1 regular (revision 8c63c1ce7be90a6ff33b79ec7afa742e04f6e7b8)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Fiat rate is shown for transactions

**Actual result:**
Fiat rate is not shown for transactions

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

This should fix the problem with fiat rates not loading into a remembered wallet that was already remembered in an older version of Suite.

## Related Issue

Resolve #12762

### CODE REVIEW

File: packages/suite/src/middlewares/wallet/storageMiddleware.ts [hunk 1]
```diff
@@ -89,12 +90,25 @@ const storageMiddleware = (api: MiddlewareAPI<Dispatch, AppState>) => {
...
+                }
+            }
+
+            if (
+                isAnyOf(
+                    transactionsActions.removeTransaction,
+                    updateTxsFiatRatesThunk.fulfilled,
+                )(action)
+            ) {
+                const { account } = action.payload;
```
Comment (tomasklim) [inline packages/suite/src/middlewares/wallet/storageMiddleware.ts:106]: I think `account` is available in `action.meta.arg`. It does not need to be returned from thunk

File: packages/suite/src/actions/suite/initAction.ts [hunk 2]
```diff
@@ -66,13 +66,13 @@ export const init = () => async (dispatch: Dispatch, getState: GetState) => {
     await dispatch(periodicCheckTokenDefinitionsThunk());
 
     // 8. init periodic fetching of fiat rates
-    await dispatch(
+    dispatch(
```
Comment (tomasklim) [inline packages/suite/src/actions/suite/initAction.ts]: Please remove it in another PR. This goes to current release and it is dangerous to do those changes now

File: packages/suite/src/actions/suite/initAction.ts [hunk 3]
```diff
@@ -79,17 +80,20 @@ export const init = () => async (dispatch: Dispatch, getState: GetState) => {
         }),
     );
 
-    // 9. dispatch initial location change
+    // 9. fetch rates for transactions with missing rates
+    dispatch(updateMissingTxFiatRatesThunk({ localCurrency: selectLocalCurrency(getState()) }));
```
Comment (tomasklim) [inline packages/suite/src/actions/suite/initAction.ts]: nit:
It is used at least 3x times in this file `selectLocalCurrency(getState())` can you assign it to const or just add it here
```
    const {
        suite: {
            settings: { language },
            lifecycle: { status },
        },
    } = getState();
```

File: packages/suite/src/actions/suite/initAction.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/actions/suite/initAction.ts]: I am not sure how `periodicFetchFiatRatesThunk` will work with the new method you added

File: packages/suite/src/middlewares/wallet/storageMiddleware.ts (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts:106]: Meta args seem to be available only in reducers (at least by TypeScript)

Comment (tomasklim) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts:106]: aha ok

File: packages/suite/src/actions/suite/initAction.ts (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/actions/suite/initAction.ts]: Okey, actually even awaiting transaction fiat rates is not slowing down that much (tested on QA wallet)

Comment (AdamSchinzel) [reply packages/suite/src/actions/suite/initAction.ts]: Done

File: packages/suite/src/actions/suite/initAction.ts (hunk 3 above)
Comment (AdamSchinzel) [reply packages/suite/src/actions/suite/initAction.ts]: Done

**Review by tomasklim — APPROVED** [review]
