### PR TITLE
fix(suite-native): Remove blockchain drilling

### LINKED ISSUE #7414: Transaction detail is rerendering like crazy
Turn on rerender indicator in debug menu and go to TransactionDetailScreeen to check and reproduce.

I traced issue down do `blockchain` selector. It's because it is not respecting advice to always select only smallest neccessary part of state but here is selector whole blockchain part of state, which is changed very often. 

Also it seems it is not even necessary, because it is used for generating Explorer url, but you can get this from static object `networks` from network-config.

Then it's passed all way down through many components `TransactionDetailParametersSheet` and it's rerendering everything on the way only because to get one number `blockchain.blockHeight`. This should be solved by selector directly in component where it is used and which will select only that `blockHeight`.

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/7414

### CODE REVIEW

File: suite-common/wallet-core/src/blockchain/blockchainReducer.ts [hunk 1]
```diff
@@ -166,3 +167,18 @@ export const selectBlockchainState = (state: BlockchainRootState) => state.walle
...
+
+export const selectBlockchainHeightBySymbol = memoizeWithArgs(
+    (state: BlockchainRootState, symbol: NetworkSymbol) => {
+        const blockchain = selectNetworkBlockchainInfo(symbol)(state);
+        return blockchain.blockHeight;
+    },
+);
+
+export const selectBlockchainExplorerBySymbol = memoizeWithArgs(
+    (state: BlockchainRootState, symbol?: NetworkSymbol) => {
```
Comment (Nodonisko) [inline suite-common/wallet-core/src/blockchain/blockchainReducer.ts:179]: Why is `symbol` optional? It doesn't make sense IMHO

**Review by Nodonisko — APPROVED** [review]

File: suite-common/wallet-core/src/blockchain/blockchainReducer.ts (hunk 1 above)
Comment (juriczech) [reply suite-common/wallet-core/src/blockchain/blockchainReducer.ts:179]: Because if we're getting transaction from selector, the symbol is not guaranteed, so it's optional

**Review by Nodonisko — APPROVED** [review]
