### PR TITLE
fix(transport-bridge): compatibility with trezorctl (and electrum) when using bundled node-bridge version

### LINKED ISSUE #19253: electrum vs node-bridge
electrum does not detect device using node bridge. 

It appears to be sending this sequence of calls 

Image

using node-bridge, it appears that it stops after calling the `/configure` endpoint indicating that there might be some breaking change between versions

### PR DESCRIPTION
**Pull request by mroz22**
image

Resolve #19253

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-node-bridge-bundled-compatibility&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-node-bridge-bundled-compatibility&lookback=7)

### CODE REVIEW

File: packages/transport-bridge/src/http.ts [hunk 1]
```diff
@@ -121,9 +121,7 @@ export class TrezordNode {
         this.port = port || defaults.port;
         this.logger = logger;
         this.descriptors = [];
-        if (bundledVersion) {
-            this.version = `${this.version}-bundled.${bundledVersion}`;
-        }
```
Comment (mroz22) [inline packages/transport-bridge/src/http.ts:126]: this non standard version format has been causing issues for some time already

**Review by marekrjpolak — APPROVED** [review]
LGTM

**Comment by STew790** [comment]
**QA OK**
image

**Info:**
 - Suite version: desktop 25.7.0 (766356e7700d10ba024bc4abd8fa7622a7ce74b5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteLocal/25.7.0 Chrome/134.0.6998.178 Electron/35.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1800x1169
 - Device: 
 - Transport: BridgeTransport 3.1.0
