### PR TITLE
Fix/cardano min amount

### LINKED ISSUE #21185: Cardano: total when sending token should also show token
Token is totally missing in Total section.

To be able to send ada token, it also have to transfer min amount of ada which is `~1.17`

Image

Image

### LINKED ISSUE #21186: Cardano: not enough funds to send token
Mention somewhere that when you are sending token, you need fee + `1.15508 ADA`

Image

Image

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

Implemented according to [Figma](https://www.figma.com/design/g9LLS8q9IpUY8UTTBvQAJF/Send?node-id=2231-2974&p=f&t=cH1U1Q5ZyoIOkHAx-0) designs.

## Related Issue

Resolve [#21185](https://github.com/trezor/trezor-suite/issues/21185)
Resolve [#21186](https://github.com/trezor/trezor-suite/issues/21186)

### Showing all tokens being sent in Total section
token-info

### Minimum ADA amount banner for single recipient
min-amount-single

### Minimum ADA amount banner for multiple recipients
min-amount-multiple

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/cardano-min-amount&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/cardano-min-amount&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/cardano-min-amount&lookback=7)

### CODE REVIEW

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -10889,4 +10889,17 @@ export default defineMessages({
...
     },
+    TR_SEND_MIN_ADA_AMOUNT: {
+        id: 'TR_SEND_MIN_ADA_AMOUNT',
+        defaultMessage: 'Not enough ADA for the transaction.',
+    },
+    TR_SEND_MIN_ADA_AMOUNT_TITLE: {
+        id: 'TR_SEND_MIN_ADA_AMOUNT_TITLE',
+        defaultMessage: 'Min ADA',
+    },
+    TR_SEND_MIN_ADA_AMOUNT_TOOLTIP: {
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts:10810]: should it be visible when it is not token tx?

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -10889,4 +10889,17 @@ export default defineMessages({
         id: 'TR_CONFIRM_BLUETOOTH_PAIRING',
         defaultMessage: 'Confirm the Bluetooth pairing request on your Trezor as well.',
     },
+    TR_SEND_MIN_ADA_AMOUNT: {
+        id: 'TR_SEND_MIN_ADA_AMOUNT',
+        defaultMessage: 'Not enough ADA for the transaction.',
+    },
+    TR_SEND_MIN_ADA_AMOUNT_TITLE: {
+        id: 'TR_SEND_MIN_ADA_AMOUNT_TITLE',
+        defaultMessage: 'Min ADA',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: use networkDisplaySymbol

**Review by tomasklim — CHANGES_REQUESTED** [review]
.

**Review by tomasklim — COMMENTED** [review]
please check how Adalite works

File: packages/suite/src/support/messages.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/support/messages.ts:10810]: maybe better copy fixes it

File: suite-common/wallet-constants/src/cardanoConstants.ts [hunk 3]
```diff
@@ -12,3 +12,4 @@ export const MIN_CARDANO_FOR_WITHDRAWALS = new BigNumber(2);
 export const MIN_CARDANO_BALANCE_FOR_STAKING = MIN_CARDANO_AMOUNT_FOR_STAKING.plus(
     MIN_CARDANO_FOR_WITHDRAWALS,
 );
+export const MIN_CARDANO_AMOUNT_FOR_SEND = new BigNumber(1_000_000);
```
Comment (tomasklim) [inline suite-common/wallet-constants/src/cardanoConstants.ts:21]: How?
Screenshot 2025-09-26 at 16 19 14
Screenshot 2025-09-26 at 16 19 27

File: packages/suite/src/support/messages.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/support/messages.ts:10810]: On adalite it is visible only when sending token Screenshot 2025-09-26 at 16 20 20

File: suite-common/wallet-constants/src/cardanoConstants.ts (hunk 3 above)
Comment (matusbalascak) [reply suite-common/wallet-constants/src/cardanoConstants.ts:21]: What's shown there is the minimum ADA amount needed (~1 ADA) and also fee amount ~0.14 ADA. I checked Adalite's code and they are calculating this 'properly' based on the size of utxo etc.

It would take much more time to implement this in suite therefore I opted for this solution as we discussed. If we want to have a proper solution, let me know, but it's gonna take some time to implement.

File: packages/suite/src/views/wallet/send/Outputs/Outputs.tsx [hunk 4]
```diff
@@ -31,11 +41,86 @@ export const Outputs = ({ disableAnim }: OutputsProps) => {
...
+                    <Banner variant="destructive" icon>
+                        <Translation
+                            id="TR_SEND_MIN_ADA_AMOUNT"
+                            values={{ networkDisplaySymbol }}
+                        />
+                    </Banner>
+                )}
+            </>
+        );
+    };
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/send/Outputs/Outputs.tsx]: Can we move to a standalone component, e.g. `MinAmountInfo` under this component in the dir. tree?

File: packages/suite/src/views/wallet/send/TotalSent/TotalSent.tsx [hunk 5]
```diff
@@ -40,6 +45,20 @@ export const TotalSent = () => {
...
+    );
+
+    const sentTokenList = tokens
+        ?.filter(
+            token =>
+                tokenAmountsMap.has(token.contract) &&
+                new BigNumber(tokenAmountsMap.get(token.contract) ?? 0).gt(0),
+        )
+        .map(token => [token.symbol?.toUpperCase(), tokenAmountsMap.get(token.contract)]);
+
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/send/TotalSent/TotalSent.tsx]: `useMemo` 🙏

File: packages/suite/src/views/wallet/send/TotalSent/TotalSent.tsx [hunk 6]
```diff
@@ -52,35 +71,51 @@ export const TotalSent = () => {
...
+        networkType === 'cardano' &&
+        hasTransactionInfo &&
+        sentTokenList?.map(([tokenSymbol, amount]) => (
+            <FormattedCryptoAmount
+                key={tokenSymbol}
+                disableHiddenPlaceholder
+                value={asAmountUnit(new BigNumber(amount ?? 0))}
+                symbol={tokenSymbol}
+            />
+        ));
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/send/TotalSent/TotalSent.tsx]: Again, why not just create a new component with its related logic for creating `sentTokenList`?

File: suite-common/wallet-constants/src/cardanoConstants.ts (hunk 3 above)
Comment (tomasklim) [reply suite-common/wallet-constants/src/cardanoConstants.ts:21]: okay agree, let's skip it for now

**Review by tomasklim — APPROVED** [review]
