### PR TITLE
fix(suite): Add missing SuiteBanners to LoggedOutLayout and unify usage across layouts

### LINKED ISSUE #16505: Message system banner is missing in the global settings
When device is not connected, banner is missing

v24.11.3

Settings
Image

Welcome screen
Image

### PR DESCRIPTION
**Pull request by izmy**
## Description

- Added `SuiteBanners` to `LoggedOutLayout` (was missing)

- Unified usage of `SuiteBanners` in `OnboardingLayout` and `WelcomeLayoutWithoutModalSwitcher`

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16505

## Screenshots:

image

image

image

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/missing-suite-banners-in-layouts&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/missing-suite-banners-in-layouts&lookback=7)

### CODE REVIEW

**Review by jvaclavik — APPROVED** [review]
very nice!

File: packages/suite/src/components/onboarding/OnboardingLayout.tsx [hunk 1]
```diff
@@ -166,15 +165,12 @@ type OnboardingLayoutProps = {
...
-    const bannerMessage = useSelector(selectBannerMessage);
     const theme = useSelector(state => state.suite.settings.theme);
 
     return (
         <TrafficLightOffset>
             <Wrapper>
-                {bannerMessage && (
-                    <MessageSystemBanner message={bannerMessage} margin={spacings.xs} />
-                )}
+                <SuiteBanners fill />
```
Comment (tomasklim) [inline packages/suite/src/components/onboarding/OnboardingLayout.tsx]: In onboarding, it now shows backup warning immediately after creating a wallet 

Screenshot 2025-07-21 at 17 28 21

Comment (tomasklim) [reply packages/suite/src/components/onboarding/OnboardingLayout.tsx]: So `selectIsDeviceBackupRequired` rule has to be somehow lifted in onboarding or at least in this step

Comment (izmy) [reply packages/suite/src/components/onboarding/OnboardingLayout.tsx]: For this case, I added the `isOnboarding` prop to the `SuiteBanners` component.

**Review by tomasklim — APPROVED** [review]

**Review by matusbalascak — APPROVED** [review]
