### PR TITLE
fix(coinjoin): accept only known request codes from coordinator

### LINKED ISSUE #6674: Refactor request-manager interceptor http and https to extracted funciton

### PR DESCRIPTION
**Pull request by szymonlesisz**
happens yesterday. Coordinator request was blocked by cloudlflare (probably because of tor) and returned: 403. Forbidden witch some cloudflare captcha html page:

`
{"time":1668102029359,"value":"Registration 6fb4e868...02000000 to 4c90ee87...fee86bad failed: https://dev-coinjoin-testnet.trezor.io/WabiSabi/input-registration Forbidden: <!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n    <title>Just a moment...</title>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\n..... dev-coinjoin-testnet.trezor.io needs to review the security of your connection before proceeding....
`

## Solution

Only listed request codes should be threated as valid, other codes should try to repeat the request

## Additional changes
- json parsing decision should be done by response content-type not by options (removed `parseJson`)
- modified server responses (not all coordinator requests returns json)

## Edit

i've ended up doing some changes in request-manager package. CC @karliatto 

- block requests with Proxy-Authorization header when TOR is disabled
> Cleanup in code (types), one function to cover both http and https interception cases

- change identity when password is provided
> Workaround for 403, if this error happens during coinjoin process try to change circuit and try again

## Issues
- resolves https://github.com/trezor/trezor-suite/issues/6674

### CODE REVIEW

**Review by marekrjpolak — APPROVED** [review]
LGTM

**Review by mroz22 — APPROVED** [review]

File: packages/coinjoin/src/utils/http.ts [hunk 1]
```diff
@@ -62,25 +67,57 @@ export const coordinatorRequest = async <R = void>(
...
+        }
+
+        // throw unexpected network errors => retry scheduledAction
+        if (![200, 404, 500].includes(response.status)) {
+            if (response.status === 403 && options.identity) {
+                // NOTE: possibly blocked by cloudflare
+                // set random password to reset TOR circuit for this identity and then try again
+                const [user] = options.identity.split(':');
+                options.identity = `${user}:${Math.random()}`;
+            }
```
Comment (karliatto) [inline packages/coinjoin/src/utils/http.ts:90]: :+1: Nice.
I hope cloudfare does not block many of our requests. It is weird to me since this service is intended to be used only from Tor network exit nodes. But I do not really know if cloudfare has some kind of config that will not block requests with the only reason that they come from Tor.

Maybe this is happening because the testnet coordinator is run by Trezor, but the one from mainnet is not going to have such blocking.

**Review by karliatto — APPROVED** [review]
Nice!
