### PR TITLE
fix(suite-native): filter out non-balance tokens for assets

### LINKED ISSUE #25028: Dashboard reports "+Tokens" when there are only phishing ones
See there are no tokens.

- fix badge on dashboard
- fix the layout so that the BNB account with only phishing tokens is rounded

Image

Image

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

do not display token badge if the num of known tokens is zero
fix styles for assests with non-valid tokens

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/25028

## 🔍 Currents Test Results

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/token-badge&lookback=7)

### CODE REVIEW

**Review by izmy — APPROVED** [review]

File: suite-native/accounts/src/selectors.ts [hunk 1]
```diff
@@ -160,7 +160,12 @@ export const getAccountListSections = (
         account.networkType === 'stellar'
             ? (account.tokens ?? [])
             : filterKnownTokens(tokenDefinitions, account.symbol, account.tokens ?? []);
-    const hasAnyKnownTokens = isNetworkSupportingTokens && !!tokens.length;
+
+    const tokensWithBalance =
+        account.networkType === 'stellar'
+            ? tokens
+            : tokens.filter(token => parseFloat(token?.balance ?? '0') > 0);
```
Comment (cermakjiri) [inline suite-native/accounts/src/selectors.ts:167]: shouldn't there rather be `BigNumber` instead of parseFloat?
