### PR TITLE
fix(suite): discreet mode menu border-top outside mobile view

### LINKED ISSUE #2843: Discreet mode menu
Browser: Chrome
Version: 8f4d1eedd6eb7648b17853a9a780a0688c0370e6

- [x]  The line above the discreet mode icon should not be present.

- [x]  Icon jumps when used for the first time during the given session 

Screenshot 2020-11-03 at 09 40 17 

ezgif com-gif-maker (1)

### PR DESCRIPTION
**Pull request by tomexx**
- there was a missing style for non-mobile view (border-top should be visible only in mobile view)
- the discreet mode icon is loaded dynamically on the first load, I fixed the jumping by setting fixed size to the Icon instance wrapper 

Maybe it would be better to have an option to preload the icon for cases like discreet mode or set the fixed size on the Icon component level, not just this instance. But I'd rather do that in an another PR so I don't block the release causing more issues

### CODE REVIEW

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx [hunk 1]
```diff
@@ -61,6 +61,12 @@ const AlertDot = styled.div`
     background: ${colors.NEUE_TYPE_RED};
 `;
 
+// The Icon can be switched dynamically (e.g. Discreet mode icon) and without fixed size the whole row of NavigationActions jumps on the first switch
+const StyledIcon = styled(Icon)`
```
Comment (szymonlesisz) [inline packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx:65]: shouldn't this be fixed in `Icon` component? 
there might be other places where this jumping happens.
i see that `Icon` component `SvgWrapper` already sets height based on Icon.size prop, should be enough to put the width as well, no?
@slowbackspace ?

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx (hunk 1 above)
Comment (tomexx) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx:65]: I was thinking about it, but I don't want to introduce new bugs right now :/

Comment (szymonlesisz) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx:65]: yeah, thats why i've tagged @slowbackspace to confirm that.
correct me if im wrong but i think all icons are square shaped

Comment (tomexx) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx:65]: I can create a new PR with global change for the next release right after this is merged.

Comment (szymonlesisz) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx:65]: ok, i've created an issue for that https://github.com/trezor/trezor-suite/issues/2868

**Review by szymonlesisz — APPROVED** [review]
