### PR TITLE
fix(suite-native): bottomsheet container has fixed size

### LINKED ISSUE #15852: Modals on tx details are a broken / jumping
**Describe the bug**
When you open a modal on some tx detail, it jumps a little from top to bottom.

**Info:**

-   Mobile Suite Version: 24.11.3 f6fa667
-   OS: Android

**How to reproduce**

1. Go to any account of any coin
2. Go to any tx detail
3. Open any info from that tx detail

**Screenshots**

https://github.com/user-attachments/assets/01f5fe09-3582-4d36-9a51-2cca179cd614

### PR DESCRIPTION
**Pull request by vytick**
make fixed size container for bottomsheet not to jump

## Related Issue

Resolve #15852

## Screenshots:

https://github.com/user-attachments/assets/7aae62fa-d0b9-4952-b6c5-5460942746c1

### CODE REVIEW

File: suite-native/atoms/src/Sheet/BottomSheetContainer.tsx [hunk 1]
```diff
@@ -1,17 +1,23 @@
...
     isVisible: boolean;
     onClose: () => void;
     ExtraProvider?: React.ComponentType;
 };
 
-const ContentWrapperStyle = prepareNativeStyle(_ => ({ flex: 1 }));
+const ContentWrapperStyle = prepareNativeStyle(_ => ({
+    flex: 1,
+    width: SCREEN_SIZE.width,
+    height: SCREEN_SIZE.height,
```
Comment (yanascz) [inline suite-native/atoms/src/Sheet/BottomSheetContainer.tsx]: What about using `EnvUtils` instead?

Comment (matejkriz) [reply suite-native/atoms/src/Sheet/BottomSheetContainer.tsx]: Yes, and the name screen_size is confusing since it is window size...

Comment (vytick) [reply suite-native/atoms/src/Sheet/BottomSheetContainer.tsx]: EnvUtils use the same thing under the hood. But sure I can use it

Comment (matejkriz) [reply suite-native/atoms/src/Sheet/BottomSheetContainer.tsx]: Yes, that is why you should use it...

Comment (vytick) [reply suite-native/atoms/src/Sheet/BottomSheetContainer.tsx]: We should probably then replace all usage of `Dimensions.get('screen')` and replace it by this through the app, because that is how it is being used for now.

Comment (vytick) [reply suite-native/atoms/src/Sheet/BottomSheetContainer.tsx]: changed in f379a0f34e

**Review by yanascz — APPROVED** [review]

File: suite-native/atoms/src/Sheet/BottomSheetContainer.tsx (hunk 1 above)
Comment (matejkriz) [reply suite-native/atoms/src/Sheet/BottomSheetContainer.tsx]: Yes, we should... Thanks for this change!
