### PR TITLE
fix(suite-desktop): url decoding before sanitization

### LINKED ISSUE #18549: Trading - Can not complete trade on Desktop
## Describe the bug
Via Simplex trade can't be completed at the moment.

## Info 

It occurs in TS version 25.4.2, but it doesn’t happen in version 25.3.3. We've tested with BTC and ETH. Video for reference

## Screenshots

https://github.com/user-attachments/assets/d8d7e886-48ef-4902-a10f-6c0e7e63ee41

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
- fixed bug when decoded URL was rejected with `403` 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/18549

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/url-decoding-in-http&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/url-decoding-in-http&lookback=7)

### CODE REVIEW

File: packages/node-utils/src/http.ts [hunk 1]
```diff
@@ -405,9 +406,13 @@ export class HttpServer<T extends EventMap> extends TypedEmitter<T & BaseEvents>
...
-                if (!paramsSegments[index]) return acc;
-                const sanitized = sanitizeUrl(paramsSegments[index]);
-                if (sanitized !== paramsSegments[index]) {
+                const paramsSegment = paramsSegments[index];
+                if (!paramsSegment) return acc;
+
+                const decoded = decodeURIComponent(paramsSegment);
+                const sanitized = sanitizeUrl(decoded);
+
+                if (sanitized !== decoded) {
```
Comment (mroz22) [inline packages/node-utils/src/http.ts]: I'd say that it params should never contain URL encoded strings. At least I have never seen a rest API doing this. 🤔

File: packages/node-utils/src/tests/http.test.ts [hunk 2]
```diff
@@ -365,12 +365,15 @@ describe('HttpServer', () => {
...
+        const res = await fetch(
+            `http://${address.address}:${address.port}/foo?a=1&a=2&b=3&c=%2Fredirect%2Fdetail`,
+            {
+                method: 'POST',
+                body: 'foo',
+            },
+        );
         expect(res.status).toEqual(200);
-        expect(await res.text()).toEqual('?a=1&a=2&b=3');
+        expect(await res.text()).toEqual('?a=1&a=2&b=3&c=%2Fredirect%2Fdetail');
```
Comment (mroz22) [inline packages/node-utils/src/tests/http.test.ts]: I added a test like this 
```
  test('query string as url encoded strings', async () => {
        const handler = jest.fn((request, response) => {
            const { search } = url.parse(request.url, true);
            response.end(search);
        });
        server.post('/foo', [parseBodyText, handler]);
        await server.start();
        const address = server.getServerAddress();
        expect(address).toBeDefined();
        const res = await fetch(
            `http://${address.address}:${address.port}/foo?c=%2Fredirect%2Fdetail`,
            {
                method: 'POST',
                body: 'foo',
            },
        );
        expect(res.status).toEqual(200);
        expect(await res.text()).toEqual('?c=%2Fredirect%2Fdetail');
    });
```

and it passed even on develop. I'd prefer adding a test that would fail on develop. Also maybe lets please add a new test case instead of modifying the already existing one

File: packages/node-utils/src/http.ts (hunk 1 above)
Comment (adderpositive) [reply packages/node-utils/src/http.ts:415]: It happens in the endpoint `/buy-post` called in `submitRequestForm`. We use `encodedURIcomponent` for params on the backend side of the trading API.

Comment (adderpositive) [reply packages/node-utils/src/http.ts]: True!

**Review by martykan — APPROVED** [review]
