### PR TITLE
Fix/freeze between navigation stacks

### LINKED ISSUE #10487: Android app freezes for few seconds during welcome flow - after consent screen
When you go through the Welcome flow and click on Confirm button on Analytics tracking screen, app freezes for few seconds. See the video:
https://drive.google.com/file/d/1kM-VCsaIRtD-OyxgeQfpAHW5JgwU05Ew/view?usp=drive_link

### LINKED ISSUE #10558: Homescreen paddings inside screen
Since https://github.com/trezor/trezor-suite/pull/10371/files#diff-cb8f9c0ba0d1dea0981e79281aa4214ef5bbac94c81df06720d44a2dff4184b5 there is 0 horizontal padding inside Homescreen. Fix this, but maintain 0 padding for graph

### PR DESCRIPTION
**Pull request by juriczech**
## Description
[chore(suite-native): upgrade navigation pkgs](https://github.com/trezor/trezor-suite/pull/10582/commits/e75f7426d62ec47675c0558cac30132e9559cd37) - initially thought it's a problem with navigation. Updated all libs, but in the end this wasn't helpful, just keeping the update
[fix(suite-native): svg loading in suite native](https://github.com/trezor/trezor-suite/pull/10582/commits/50db433d9c1c32e69567b9b443dae0d182b8d342) - this is the fix - instead of passing svg to native code with expo-image, react-native-svg renders directly and it seems to be more performant
[refactor(suite-native): receive screen](https://github.com/trezor/trezor-suite/pull/10582/commits/524311f073730592d59e5c1bf5bbd1d96da81253) - while looking at some components that were using react-native-svg, I noticed unnecessary duplication, so I refactored this to be nicer
[fix(suite-native): homescreen padding](https://github.com/trezor/trezor-suite/pull/10582/commits/c826ff46d64e55790bc50a5dc3ed1ce49ce58443) - fix homescreen padding

Note: This seems to speed up the transition quite a bit, but maybe it will still be slow. While checking profiler, it seems that modals slow down rendering of Homescreen as well. I would like to merge this, check develop (debug flavor is slower than built apps) and then see if we need to dig into this more.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10558
Resolve https://github.com/trezor/trezor-suite/issues/10487

## Screenshots:
New:
https://github.com/trezor/trezor-suite/assets/36101761/6f0db0f4-e9cd-409c-b285-353d0b9ddc89

Old:
https://github.com/trezor/trezor-suite/assets/36101761/a8df52a4-60f7-4234-92e9-b3e2ded112f5

image

### CODE REVIEW

File: suite-native/device/src/hooks/useHandleDeviceConnection.ts [hunk 1]
```diff
@@ -53,14 +53,6 @@ export const useHandleDeviceConnection = () => {
     // set connecting screen to be displayed again on the next device connection.
     useEffect(() => {
         if (isNoPhysicalDeviceConnected && isOnboardingFinished) {
-            // This accidentally gets triggered by finishing onboarding with no device connected,
```
Comment (Nodonisko) [inline suite-native/device/src/hooks/useHandleDeviceConnection.ts]: This is not useful anymore? I think it's still nice not to redirect twice

**Review by Nodonisko — COMMENTED** [review]
It still kind of strange that is caused by quite simple SVG, but if it helps... Maybe it's bug in expo-image

File: suite-native/device/src/hooks/useHandleDeviceConnection.ts (hunk 1 above)
Comment (juriczech) [reply suite-native/device/src/hooks/useHandleDeviceConnection.ts]: I can put it back. Thought it would be simpler like this and doesn't seem to affect performance (haven't measured this)

**Comment by juriczech** [comment]
@Nodonisko This is relevant to your comment https://susuthapa19961227.medium.com/i-wouldnt-say-react-native-svg-doesn-t-render-natively-6ef980fbb436

I'm surprised the difference is this big. However I didn't verify this, it helped, so I assume it to be correct.

File: suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx [hunk 2]
```diff
@@ -7,82 +9,71 @@ import {
...
+        title: 'moduleOnboarding.featureReceiveScreen.usb.title',
+        subtitle: 'moduleOnboarding.featureReceiveScreen.usb.subtitle',
+        redirectTarget: OnboardingStackRoutes.TrackBalances,
+    },
+    noUsb: {
+        title: 'moduleOnboarding.featureReceiveScreen.noUsb.title',
+        subtitle: 'moduleOnboarding.featureReceiveScreen.noUsb.subtitle',
+        redirectTarget: OnboardingStackRoutes.AnalyticsConsent,
+    },
+} as const satisfies Record<'usb' | 'noUsb', ScreenContent>;
```
Comment (PeKne) [inline suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx]: What about changing the `usb | noUsb` to something like `device | portfolioTracker`? I don't like usb, because in the near future it won't be the only way how to connect device. Just a tiny nit, won't block the PR because of this.

**Review by PeKne — APPROVED** [review]

File: suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx]: [e774f1c](https://github.com/trezor/trezor-suite/pull/10582/commits/e774f1cf85d1f956857b77e409db6ef14cfc8c5a)

**Review by PeKne — APPROVED** [review]

**Review by matejkriz — COMMENTED** [review]
You can easily check release flavor locally, I did and it looks way smoother 👍 

`SIGNING_KEY_FILE=debug.keystore SIGNING_KEY_STORE_PASSWORD=android SIGNING_KEY_ALIAS=androiddebugkey SIGNING_KEY_PASSWORD=android ./gradlew assembleFirebaseDevelopRelease` (we can prepare easier way of building "release" build locally...)

File: suite-native/intl/src/en.ts [hunk 3]
```diff
@@ -348,23 +348,23 @@ export const en = {
                 'Manage your portfolio with your Trezor hardware wallet connected directly to your mobile device.',
         },
         featureReceiveScreen: {
-            noUsb: {
+            portfolioTracker: {
```
Comment (matejkriz) [inline suite-native/intl/src/en.ts:351]: type error https://github.com/trezor/trezor-suite/actions/runs/7473006842/job/20336315082?pr=10582#step:15:586

**Review by Nodonisko — APPROVED** [review]

File: suite-native/intl/src/en.ts (hunk 3 above)
Comment (juriczech) [reply suite-native/intl/src/en.ts:351]: Fixed

**Comment by juriczech** [comment]
> You can easily check release flavor locally, I did and it looks way smoother 👍
> 
> `SIGNING_KEY_FILE=debug.keystore SIGNING_KEY_STORE_PASSWORD=android SIGNING_KEY_ALIAS=androiddebugkey SIGNING_KEY_PASSWORD=android ./gradlew assembleFirebaseDevelopRelease` (we can prepare easier way of building "release" build locally...)

I was talking about this yesterday but for some reason, I didn't think of that :) Thanks!
