### PR TITLE
fix: fiat input for tokens

### LINKED ISSUE #1847: Send: ERC20 Fiat input and calculation
Allow calculation `ERC20 > Fiat` and `Fiat < ERC20` in send form like Ethereum or any other coin.

NOTE: not all ERC20 have fiat value (could be unknown, could be below 1 cent)

Screenshot from 2021-09-06 10-24-14
Screenshot from 2021-09-06 10-24-28

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Display fiat input in send form also for tokens with fiat rates. Also removed the message displaying total token balance (we are not doing for ETH and other stuff so why here).

## Related Issue

Resolve #1847

## Screenshots:

Screenshot 2024-02-09 at 5 07 43 PM

### CODE REVIEW

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx [hunk 1]
```diff
@@ -219,11 +207,6 @@ export const Amount = ({ output, outputId }: AmountProps) => {
             <Row>
                 <Heading>
                     <Translation id="AMOUNT" />
-                    {tokenBalance && (
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: Because you can see `ETH` at the top
Screenshot 2024-02-12 at 9 15 02
but you do not know how many tokens you have, so this should stay here. 

I think that we should also show token fiat rate somewhere here.

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx [hunk 2]
```diff
@@ -129,13 +121,9 @@ export const Amount = ({ output, outputId }: AmountProps) => {
...
-    const tokenBalance = token ? (
-        <HiddenPlaceholder>
-            <TokenBalanceValue>{`${
-                token.balance
-            } ${token.symbol!.toUpperCase()}`}</TokenBalanceValue>
-        </HiddenPlaceholder>
-    ) : undefined;
+    const coins = useSelector(selectCoinsLegacy);
+    const tokensWithRates = enhanceTokensWithRates(account.tokens, coins);
+    const isTokenWithRates = tokensWithRates.some(t => t.contract === token?.contract);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: It would be nice not to use deprecated method. 

How about using something like `selectEthereumTokenHasFiatRates` which is also used in native

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx [hunk 3]
```diff
@@ -249,7 +232,7 @@ export const Amount = ({ output, outputId }: AmountProps) => {
                     />
                 </Left>
 
-                {!token && (
+                {(!token || (token && isTokenWithRates)) && (
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: Screenshot 2024-02-12 at 9 25 43

This does not work because token always has fiat rate thanks to `enchance...` method even thought it is undefined.

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: Discuss with @Hermez-cz and also take in mind this https://github.com/trezor/trezor-suite/issues/10435 so that it fits

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx [hunk 4]
```diff
@@ -27,6 +28,7 @@ import {
 } from 'src/utils/suite/validation';
 import { spacingsPx } from '@trezor/theme';
 import { breakpointMediaQueries } from '@trezor/styles';
+import { selectCoinsLegacy, selectSpecificTokenDefinition } from '@suite-common/wallet-core';
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: `selectSpecificTokenDefinition` unused

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 5]
```diff
@@ -107,6 +104,17 @@ export const useSendForm = (props: UseSendFormProps): SendContextValues => {
...
+    const token = values?.outputs?.[0]?.token;
+
+    const fiatRates = props.coins.find(item => {
+        const hasToken = !!token;
+        return (
+            item.symbol === props.selectedAccount.account.symbol &&
+            (!hasToken || item.tokenAddress === token)
+        );
+    });
+
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendForm.ts:117]: `useSendForm` is extremely complex, I would avoid adding more lines if not necessary. Could you just create/use a selector which return `CoinFiatRates` (or what is necessary)?

Then you can remove `coins` from `props`

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx [hunk 6]
```diff
@@ -192,7 +192,10 @@ export const Fiat = ({ output, outputId }: FiatProps) => {
                 // Get (fresh) fiat rates for newly selected currency
                 const updateFiatRatesResult = await dispatch(
                     updateFiatRatesThunk({
-                        ticker: { symbol: account.symbol as NetworkSymbol },
+                        ticker: {
+                            symbol: account.symbol as NetworkSymbol,
+                            tokenAddress: (token?.contract as TokenAddress) ?? undefined,
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]:
```suggestion
                            tokenAddress: token?.contract as TokenAddress
```
Does the same job right?

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx (hunk 6 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]: d12a573208bc86ea095dac7106213470b4e2b0f2

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx (hunk 4 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: d12a573208bc86ea095dac7106213470b4e2b0f2

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx (hunk 3 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: d12a573208bc86ea095dac7106213470b4e2b0f2

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: d12a573208bc86ea095dac7106213470b4e2b0f2

File: packages/suite/src/hooks/wallet/useSendForm.ts (hunk 5 above)
Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useSendForm.ts:117]: Agree but I don't see anything better than this atm. I will followup on this PR with [this issue](https://github.com/trezor/trezor-suite/issues/10464), where I will refactor how we access rates using `selectFiatRatesByFiatRateKey` so I will make it then easier here too

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: Ok, makes sense. Why I originally deleted it was because on smaller screens with hover it looked bad since switch for send max is there (see screenshot). Texted @Hermez-cz and will improve it with https://github.com/trezor/trezor-suite/issues/10435

Screenshot 2024-02-12 at 2 44 03 PM

Comment (tomasklim) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx]: This mobile screenshot should be fixed from empower guys. oka

**Review by tomasklim — APPROVED** [review]
