### PR TITLE
fix(metadata): fix rerender of address metadata

### LINKED ISSUE #2632: Text in labeling field will disappear if cursor crosses certain div bounds
**Info:**
OS Windows 10 Suite Type APP Commit e6ba320 (@bosomt is this right?)
OS Nixos web Commit e6ba320 
Device TT 2.3.4. 50854b921
 
**Describe the bug**
This happens when user is creating a label for a transaction. When they move the cursor during the creation of the label through certain div bounds (in or out of the div containing said transaction), the text will automatically be erased. 

**Steps to reproduce:**
1. Enable labeling
2. Go to Accounts > Transactions > Click on Add label
3. Write something (do not hit enter or approve it) and move the mouse around

**Expected result:**
Did not expect the text to disappear.

**Actual result:**
Text disappears under certain conditions.

**video**
https://drive.google.com/file/d/1ZAIY9v2vJMFFagxv4CKqqCyEfGI8l48-/view

### PR DESCRIPTION
**Pull request by mroz22**
This PR shall fix #2632 issue. It works in practice but I don't like it very much. According to react docs:
 
> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

I'd say it would be better to fix it by ditching using `useState` for `isHovered` and replace it with css hover instead. 
There are always 3 grid elements, so something like this could work:
1st element on hover -> set 2nd sibling child to visible
2nd element on hover -> set 1st sibling child to visible
3rd element on hover -> set own child to visible. 

what do you think @slowbackspace

### CODE REVIEW

**Review by tomexx — APPROVED** [review]

File: packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx [hunk 1]
```diff
@@ -122,25 +122,33 @@ const Item = ({ addr, symbol, onClick, metadataPayload, index }: ItemProps) => {
     const fresh = addr.transfers < 1;
     const address = addr.address.substring(0, 20);
 
+    // prevent re-rendering of MetadataLabeling when isHovered state changes
+    const MemoizedMetadataLabeling = useMemo(
```
Comment (szymonlesisz) [inline packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx]: shouldn't `useMemo` be declared inside `MetadataLabeling` component?

**Review by szymonlesisz — COMMENTED** [review]
i would also prefer to use css instead react like @mroz22 suggested

File: packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx (hunk 1 above)
Comment (mroz22) [reply packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx]: yes!

**Comment by mroz22** [comment]
Hmm, it seems it [can't be done with css](https://stackoverflow.com/questions/44428250/css-style-nth-sibling).
So I only moved useMemo into labeling component where it truly belongs

**Review by szymonlesisz — APPROVED** [review]
