### PR TITLE
fix(suite-native): fix alert bottom offset

### LINKED ISSUE #23353: Alerts overlapping the navbar on mobile Suite
**Describe the bug**
Alerts are not correctly aligned from the bottom navbar on mobile. They are overlapping a little.

**Info:**

- Mobile Suite Version: 
- OS: Android

**How to reproduce**

1. Enable the navbar function in OS settings
2. Open Suite
3. Click on the wallet switcher
4. CLick on Connect device
5. Click on "Connect via Bluetooth"
6. Wait for the alert to open up

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

fix Alert bottom offset

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23353

## Screenshots:

IMG_2537

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/overlaping-alert-nav-bar&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/overlaping-alert-nav-bar&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/overlaping-alert-nav-bar&lookback=7)

### CODE REVIEW

File: suite-native/alerts/src/components/AlertSheet.tsx [hunk 1]
```diff
@@ -58,6 +59,7 @@ export const AlertSheet = ({ alert }: AlertSheetProps) => {
     const { hideAlert } = useAlert();
     const { applyStyle } = useNativeStyles();
     const { runShakeAnimation, shakeAnimatedStyle } = useShakeAnimation();
+    const { bottom } = useBannerAwareSafeAreaInsets();
```
Comment (matejkriz) [inline suite-native/alerts/src/components/AlertSheet.tsx]: useBannerAwareSafeAreaInsets have special handling only for banners on top of the screen, right? What about using `const { bottom } = useSafeAreaInsets();` here directly?

Comment (BrantalikP) [reply suite-native/alerts/src/components/AlertSheet.tsx]:
```
export const useBannerAwareSafeAreaInsets = (): EdgeInsets => {
    const { top, ...rest } = useSafeAreaInsets();

    const isCurrentlyAnyBannerRendered = useAtomValue(isAnyBannerRenderedAtom);

    return { top: isCurrentlyAnyBannerRendered ? 0 : top, ...rest };
};
```


it modifying only the top value. The main reason was that the Alert Sheet already has '@suite-native/atoms' as dependency but not `react-native-safe-area-context`

Comment (BrantalikP) [reply suite-native/alerts/src/components/AlertSheet.tsx]: https://github.com/trezor/trezor-suite/pull/23382/commits/dcd2a54efb888d69603c8de5267694c2554d2014 ✅

File: suite-native/alerts/src/components/AlertSheet.tsx [hunk 2]
```diff
@@ -25,14 +26,14 @@ type AlertSheetProps = {
 const SCREEN_WIDTH = getScreenWidth();
 const SCREEN_HEIGHT = getScreenHeight();
 
-const alertSheetContainerStyle = prepareNativeStyle(utils => ({
+const alertSheetContainerStyle = prepareNativeStyle<{ bottom: number }>((utils, { bottom }) => ({
```
Comment (yanascz) [inline suite-native/alerts/src/components/AlertSheet.tsx]: Might be better to name it `safeAreaBottomInset` or something like that.

**Review by yanascz — APPROVED** [review]
LGTM.
