### PR TITLE
Fix coinjoin pausing while device is locked

### LINKED ISSUE #7484: Its easy to break this via entering Send dialogue multiple times and leaving to main CJ page.
Its easy to break this via entering Send dialogue multiple times and leaving to main CJ page.
You will get device error and CJ will stay paused till you resume it manually.

@hynek-jina follow up issue ?

image

image

**Info:**
 - Suite version: desktop 23.2.0 (1715c7a70a103c5ce94f9ca7a9e5075b06d99746)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

_Originally posted by @bosomt in https://github.com/trezor/trezor-suite/issues/7416#issuecomment-1408259030_

### PR DESCRIPTION
**Pull request by komret**
## Description

When coinjoin session was paused shortly after it had been resumed (or started), it sometimes resulted in an error: `Device call in progress`. This error is caused by `connect` being occupied with another action and lead to the new action being discarded (i.e. coinjoin did not pause or in other case did not restore as reported in #7484).

This has been solved 1) on the main page by disabling the resume button while device is locked (515d458c14462d3088de3d0885f4bc611d695950), and 2) on closing/opening send form by moving the logic to `coinjoinMiddleware` and making sure the action is called once device is not locked 5740e2ef4e22f632d1150e6bb8aaaa4da047018a.

The `starting` property was added to `session` to prevent pausing or restoring the session while it is already being restored. This prevents an error which was sometimes visible in the console: `Trying to register account that already exists`

The conditions for restoring coinjoin session in `coinjoinMiddleware` have been unified into `checkIsCoinjoinResumeBlocked`. This adds some new conditions and also fixes this repeating condition which seems to be wrong. @karliatto please check this part out.
```ts
const isCoinjoinResumeAllowed = !isCoinJoinBlockedByTor || isDeviceConnected;
```

## Related Issue

Resolve #7484

## Screenshots:
Same error as described in #7484, but on the main page (tackled by 515d458c14462d3088de3d0885f4bc611d695950):
https://user-images.githubusercontent.com/42465546/216056362-7845781a-25ca-419f-9964-841651ca90d0.mov

### CODE REVIEW

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts [hunk 1]
```diff
@@ -75,10 +88,8 @@ export const coinjoinMiddleware =
                     api.dispatch(coinjoinAccountActions.pauseCoinjoinSession(account.key, true));
                 }
             } else if (
-                account &&
-                selectedAccountPrevStatus === 'out-of-sync' &&
                 selectedAccountNextStatus === 'ready' &&
-                isCoinjoinResumeAllowed
+                !checkIsCoinjoinResumeBlocked(state)
```
Comment (karliatto) [inline packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: This is run before changing the status so what happens when account is `out-of-sync` and next status is going to be `ready` but at this point it is sill `out-of-sync`?
I think `checkIsCoinjoinResumeBlocked` will return true and paused accounts are not going to be resumed.

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts [hunk 2]
```diff
@@ -133,18 +144,13 @@ export const coinjoinMiddleware =
...
-            const isCoinjoinResumeAllowed = !isAccountOutOfSync || isDeviceConnected;
-
             if (['Disabling', 'Disabled', 'Error'].includes(action.payload)) {
                 api.dispatch(coinjoinAccountActions.pauseInterruptAllCoinjoinSessions());
             }
             // We restore sessions that were interrupted when successfully Enabled if
             // there is not any other condition blocking coinjoin resume.
-            if (action.payload === 'Enabled' && isCoinjoinResumeAllowed) {
+            const state = api.getState();
+            if (action.payload === 'Enabled' && !checkIsCoinjoinResumeBlocked(state)) {
```
Comment (karliatto) [inline packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: At this point the actions are propagated to reducers so it is likely that the next state is already applied but it does not have to be always like that, there could be some race conditions. 
So it could happen that when this run in the state Tor is still disable and `isCoinJoinBlockedByTor` will return true.

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts [hunk 3]
```diff
@@ -28,6 +29,26 @@ export const coinjoinMiddleware =
...
+            const isCoinjoinBlockedByRoute = state.router.route?.name === 'wallet-send';
+            return (
+                isAccountOutOfSync ||
+                isDeviceDisconnected ||
+                isCoinJoinBlockedByTor ||
+                isCoinJoinDisabledByFeatureFlag ||
+                isCoinjoinBlockedByRoute ||
+                !state.suite.online
+            );
+        };
```
Comment (karliatto) [inline packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: It looks lo me that this functions tries to make the same thing that `isCoinjoinResumeBlocked` from useBlockedCoinjoinResume https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/hooks/coinjoin/useBlockedCoinjoinResume.ts#L40

It would be nice to extend the some how the function in that hook with the new requirements

**Review by karliatto — CHANGES_REQUESTED** [review]

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts (hunk 3 above)
Comment (komret) [reply packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: Already working on that: #7524

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts (hunk 1 above)
Comment (komret) [reply packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: You are right, I removed this condition from the function so that it is not checked here. 766664de83cfe6631e86b13b3afddca5dbe30f93

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts (hunk 2 above)
Comment (komret) [reply packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: I think, as long as this is run after the `next()` call, there should be no such issue because `updateTorStatus' is just a simple synchronous action. Or am I wrong?

**Comment by komret** [comment]
I realised that the check whether an account is out of sync considers only the `selectedAccount`, i.e. applying this condition prevents restoring the session while no account is selected. To solve this, 766664de83cfe6631e86b13b3afddca5dbe30f93 adds `restoreSessionOfEligibleAccounts` function which restores all eligible interrupted sessions. Therefore, automatic restoring will also work when navigating from send form to another account or when tor turns on while in settings or dashboard.

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts [hunk 4]
```diff
@@ -176,5 +195,36 @@ export const coinjoinMiddleware =
...
+        if (action.type === ROUTER.LOCATION_CHANGE || action.type === SUITE.LOCK_DEVICE) {
+            const state = api.getState();
+            const { locks } = state.suite;
+            if (!locks.includes(SUITE.LOCK_TYPE.DEVICE) && !locks.includes(SUITE.LOCK_TYPE.UI)) {
+                if (
+                    state.router.settingsBackRoute.name === 'wallet-send' &&
+                    !isCoinjoinSessionBlockedGlobally(state)
+                ) {
+                    // restore all interrupted sessions upon leaving send form
+                    restoreSessionOfEligibleAccounts(state);
```
Comment (karliatto) [inline packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: So we restore all sessions when leaving send form.
But when entering send form we pause only the current one?
Why?

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts [hunk 5]
```diff
@@ -22,12 +23,45 @@ import {
...
 
 import { Feature, selectIsFeatureDisabled } from '@suite-reducers/messageSystemReducer';
-import { getIsCoinjoinOutOfSync } from '@wallet-utils/coinjoinUtils';
 
 export const coinjoinMiddleware =
     (api: MiddlewareAPI<Dispatch, AppState>) =>
     (next: Dispatch) =>
     (action: Action): Action => {
+        // check for conditions that block restoring coinjoin session for all accounts
+        const isCoinjoinSessionBlockedGlobally = (state: AppState) => {
```
Comment (karliatto) [inline packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts:32]: :+1:

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts (hunk 4 above)
Comment (komret) [reply packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: When leaving the send form, we restore all interrupted sessions because at that point we do not know which one we have stopped.

When entering the send form, we only pause the session for the current account because sending does not affect any other account.

Comment (karliatto) [reply packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: I see, yes, resuming all interrupted accounts makes sense.

I am not sure if `restoreSessionOfEligibleAccounts` is the best name since sounds a bit vague meaning. But that is maybe just my feeling.

**Review by karliatto — APPROVED** [review]
Looks good :rocket:

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts (hunk 4 above)
Comment (komret) [reply packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: Renamed to `restoreInterruptedCoinjoinSessions`.
