### PR TITLE
fix(suite-native): homescreen spacings

### LINKED ISSUE #10620: Discovery skeletons overflow
**Describe the bug**
While discovery, the loading skeletons are overflowing their parent component. See the video attached. 

**Screenshots**

https://github.com/trezor/trezor-suite/assets/26143964/97727038-6dab-4e91-a949-db3b5dd360d7

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve [Discovery skeletons overflow](https://github.com/trezor/trezor-suite/issues/10620)

## Screenshots:

https://github.com/trezor/trezor-suite/assets/36101761/56370193-87c7-4a27-9cdf-ea1343f9785c

### CODE REVIEW

File: suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ const MAIN_ITEM_HEIGHT = 48;
 const SUBITEM_HEIGHT = 20;
 
 const SCREEN_WIDTH = Dimensions.get('window').width;
-const MAIN_ITEM_WIDTH = SCREEN_WIDTH * 0.56;
+const MAIN_ITEM_WIDTH = SCREEN_WIDTH * 0.6;
```
Comment (Nodonisko) [inline suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx:19]: We should make this dynamic by container size so we don't need to change this with every slight padding change :D

**Review by Nodonisko — APPROVED** [review]

File: suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx:19]: It shouldn't happen that we change this often. The fix yesterday was redundant so I just returned it and it should stay as it is. 

AFAIK dynamic size is not possible due to skia. 
@Nodonisko
