### PR TITLE
fix: make use of tor settings in news feed

### LINKED ISSUE #3793: App, Settings - Tor - Onion links switch does not reflect OFF state with blog posts
**Describe the bug**
Selecting any article link from the Dashboard's News section (blog.trezor.io/*) redirects to an onion link when _Tor_ connection is **ON** and the _Open trezor.io links as .onion links_ button is **OFF** ; however all other *.trezor.io (Support link in the floating BETA badge, wiki.trezor.io links) are not affected and reflect the button's state correctly.

**Info:**
 - Remembered Wallet: any
 - Suite Version: app 21.5.1 4d09d88
 - OS: any (tested macOS Big Sur 11.3.1)
 - Bridge: any (2.0.31 rev 5f53132)
 - Firmware Version: any (tested model T 2.4.0 RC)

**Steps to reproduce:**
1. Switch Tor connection ON,
2. Switch _Open trezor.io links as .onion links_ button OFF,
3. Open an article on Dashboard, News section.

**Expected result:**
Warning dialog about redirection to **clearsite link** is displayed (and subsequently redirected to it after confirmation).

**Actual result:**
Warning dialog contains a message about onion link, even when the  _Open trezor.io links as .onion links_ button is in OFF state.

**Screenshots:**
Tor ON, onion links button OFF
image
Warning dialog
image

**Note(s):**
Please note that the undesirable behavior when both Tor and the .onion links button are in the **ON** state which opened a clearsite link was already reported in https://github.com/trezor/trezor-suite/issues/3542#issue-829042032.

Also please note that there is no (at least apparent) reason to keep the onion links button enabled when Tor is in OFF state, I'd suggest it's disabled when Tor is OFF.

### PR DESCRIPTION
**Pull request by mroz22**
Hello, I am opening this PR to resolve #3793

cce61c6 implements suite.settings.torOnionLinks in dashboard news feed 
92794ea makes an attempt to refactor duplicated logic between NewsFeed and TrezorLink component by introducing useTorUrl hook. I have always hard time deciding if I actually like these hook-like solutions, so your input is welcome here definitely
b76f451 turning tor off should probably also turn suite.settings.torOnionLinks off.

### CODE REVIEW

File: packages/suite/src/views/settings/index.tsx [hunk 1]
```diff
@@ -256,6 +256,10 @@ const Settings = () => {
                                                 },
                                             });
                                             window.desktopApi!.toggleTor(!tor);
+                                            // does not make sense to use onion links if tor is being disabled
```
Comment (tomasklim) [inline packages/suite/src/views/settings/index.tsx]: _I am not Tor professional._

Does it make sense to disable it? Maybe someone wants to open onion links even when Suite Tor is disabled, because he has some kind of Tor for the whole system. 
But it looks like that when you have Tor disabled, but onion links enabled, it does not respect it.

Another problem is that if you disable Tor, it takes some time for the switch to move to the left, but onion links switch moves instantly. Maybe we should wait for Tor to be properly disabled and then disable onion links?

File: packages/suite/src/hooks/suite/useTorUrl.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
+import { useMemo } from 'react';
+import { useSelector } from '@suite-hooks';
+import { toTorUrl } from '@suite-utils/tor';
+
+export const useTorUrl = (originalUrl?: string) => {
```
Comment (tomasklim) [inline packages/suite/src/hooks/suite/useTorUrl.ts]: I dont like the name of hook. It sounds like that it always returns Tor URL. 

What about `useExternalLink`, `useExternalLinkUrl` or something similar?

In message system config we use `external-link` and `internal-link`.

Comment (tomasklim) [reply packages/suite/src/hooks/suite/useTorUrl.ts]: When talking about Messaging system, could you please use your hook in `MessageSystemBanner` component, line 36? We do not use onion link there. I am not sure if we can use Tor URL for links which are not `trezor.io` but at least we can do it for `trezor.io` links?

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/hooks/suite/useTorUrl.ts (hunk 2 above)
Comment (mroz22) [reply packages/suite/src/hooks/suite/useTorUrl.ts]: added in 39d4834 
also needed to make tor domain handling more generic which you can see here 
3c2a737

File: packages/suite-web-landing/pages/_document.tsx [hunk 3]
```diff
@@ -48,7 +48,10 @@ export default class MyDocument extends Document {
                     <meta httpEquiv="cache-control" content="no-cache" />
                     <meta httpEquiv="expires" content="-1" />
                     {isOnionLocation && (
-                        <meta httpEquiv="onion-location" content={`http://suite.${TOR_DOMAIN}`} />
+                        <meta
+                            httpEquiv="onion-location"
+                            content={`http://suite.${TOR_URLS['trezor.io']}`}
+                        />
```
Comment (tomasklim) [inline packages/suite-web-landing/pages/_document.tsx:54]: Does it make sense to have onion meta tag on landing page? Landing page is not in desktop app

File: packages/suite/src/components/suite/Banners/MessageSystemBanner.tsx [hunk 4]
```diff
@@ -33,15 +36,16 @@ const MessageSystemBanner = ({ message }: Props) => {
             // @ts-ignore: impossible to add all href options to the message system config json schema
             onClick = () => goto(link);
         } else if (action === 'external-link') {
-            onClick = () => window.open(link, '_blank');
+            onClick = () =>
+                window.open(tor && torOnionLinks ? getTorUrlIfAvailable(link) : link, '_blank');
```
Comment (tomasklim) [inline packages/suite/src/components/suite/Banners/MessageSystemBanner.tsx:40]: We cannot use `useExternalLink` hook here right? 😞  So we duplicate the logic again

File: packages/suite/src/views/dashboard/components/NewsFeed/index.tsx [hunk 5]
```diff
@@ -4,10 +4,10 @@ import Truncate from 'react-truncate';
 import { Translation } from '@suite-components';
 import { Section } from '@dashboard-components';
 import { Button, variables } from '@trezor/components';
-import { useSelector } from '@suite-hooks';
+import { useExternalLink } from '@suite-hooks';
 import { useFetchNews } from '@dashboard-hooks/useNews';
-import { toTorUrl } from '@suite-utils/tor';
 import { BLOG_URL } from '@suite-constants/urls';
+import { ArrayElement } from '@suite/types/utils';
```
Comment (tomasklim) [inline packages/suite/src/views/dashboard/components/NewsFeed/index.tsx:10]:
```suggestion
import type { ArrayElement } from '@suite/types/utils';
```

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/Banners/MessageSystemBanner.tsx (hunk 4 above)
Comment (mroz22) [reply packages/suite/src/components/suite/Banners/MessageSystemBanner.tsx:40]: we can, but does it make sense? does it help imporve readabilit? using externalLink hook for general link which might be of type internal or external? not sure  about that.

File: packages/suite/src/views/settings/index.tsx (hunk 1 above)
Comment (mroz22) [reply packages/suite/src/views/settings/index.tsx]: @alex-jerechinsky ? product? heeelp

**Review by tomasklim — APPROVED** [review]
