### PR TITLE
fix(suite): simplify and fix  op_return as receive address

### LINKED ISSUE #18894: Transaction detail identifies op_return output as receive address and explorer link leads to incorrect url
**Describe the bug**
Transaction detail identifies op_return output as receive address and explorer link leads to incorrect url

**Steps to reproduce:**
1. Send BTC tx with op_return
2. Open transaction detail
3. Click on op_return output

**Info:**
 - Suite version: web 25.6.0 (86970a6d706f9ebeafcda0631344aa841536a3c6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.10 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport

**Screenshots:**

Image

https://github.com/user-attachments/assets/6529e66c-0a00-4231-a330-03211ae275c5

### PR DESCRIPTION
**Pull request by OriginalEveres**
Simplified huge file `IODetails.tsx` into smaller components to make it more readable.

Fixed OP_RETURN output - it was treated as receive address, thus it had link to explorer. (wrong link)

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/18894

## Screenshots:
**BEFORE**
https://github.com/user-attachments/assets/6073b11c-df8c-4191-8bfe-aeec1d62185c

**AFTER**
Screenshot 2025-08-10 at 22 55 03

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/opreturn-wrong-as-receive-address&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/opreturn-wrong-as-receive-address&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/IODetails/IOGroup.tsx [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+`;
+
+const IconWrapper = styled.div`
+    position: absolute;
+    top: 50%;
+    left: 50%;
+    transform: translate(-50%, -50%);
+`;
+
+const shouldHideExplorerLink = (vout: IODetails) =>
```
Comment (OriginalEveres) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/IODetails/IOGroup.tsx:25]: this checks if the output is OP_RETURN.

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/IODetails/IOItem.tsx [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+};
+
+export const IOItem = ({
+    anonymitySet,
+    address,
+    symbol,
+    contractAddress,
+    amount,
+    isPhishingTransaction,
+    hideExplorerLink = false,
```
Comment (OriginalEveres) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/IODetails/IOItem.tsx:36]: I've added this prop to hide the explorer link

**Review by Lemonexe — APPROVED** [review]
Looks LGTM to me.
It's nice that you have split the files, but pls next time do it in separate commits (does not matter what order).
It's difficult to see what was just moved, and where are the changes, but I thank you for pointing them out with comments :slightly_smiling_face:

**Comment by Lemonexe** [comment]
Works perfectly :ok_hand:
