### PR TITLE
Dark mode

### LINKED ISSUE #2226: Scrollbars
The problem is that native scrollbars are ugly on most platform except macOS. We can restyle them via CSS for chrome-based browsers that would probably cover most of our userbase (and ofc electron apps too). 

The other option, that should also cover firefox users, would be to use a library such as https://github.com/Grsmto/simplebar, we tried once and failed. As I recall there was some weird issue in accounts menu. It is certainly worth another shot though!

Current state is that in some critical places such as accounts menu, app navigation and modals we have implemented the first option (and it works quite nicely).

Basically someone (I guess that's me) needs to sit down and figure out if the first option (css-way) will be enough (confirmed: it is) and if it should be use globally, or if there is some catch and it needs to be used on component basis. (ohh, the catch is native scrollbars on mac have auto hide functionality, restyled css scrollbars don't allow that, but I guess it's fine).

update: ohh, since firefox 64 there is a way to customize scrollbars thanks to the `scrollbar-color` prop. REJOICE.

### LINKED ISSUE #2738: Dark mode 🌃
Design: [Zeplin](https://zpl.io/beZg7nN)

### LINKED ISSUE #2793: Accounts bar in APP is missing bottom part
**Info:**
 - OS: Windows 10 Home Edition (happens also on NixOS)
 - Suite Version: app commit 46ab9e5b99354942d8ddec2df8ccc5db734c12be
 - Firmware Version: model  TT 2.3.4 , revision public
 
**Describe the bug**
Accounts bar is missing a small part on the bottom of the app when scrolling is necessary - FIAT amount for the last account is not seen. And if legacy accounts are wrapped up and scrolling is necessary, this account section will no longer be visible (see gif, or video).

**Steps to reproduce:**
1. Open APP
2. Open coin accounts where scrolling is necessary in Accounts bar and coin has several account types
3. Wrap up Legacy accounts

**Expected result:**
Bottom of the Accounts bar will still be visible.

**Actual result:**
Bottom of the Accounts bar is missing/not visible. 

**Screenshots:**

photo_2020-10-29_12-13-47

https://drive.google.com/file/d/1eLBvEGZlGY4XRe-2xFmjzs1wxdngZdEp/view

**Note(s):**
You can see in the video that APP is maximized, but legacy accounts section goes missing when wrapped up.

### LINKED ISSUE #2841: Unwanted scrolling of Suite in background
**Info:**
 - OS: Nixos 
 - Browser: Firefox , version 82.0 (64-bit)
 - Wallet Version: web, commit 11ef2d377f2131ca74ddc6c7979e013082b9b061
 - Firmware Version: 2.3.2 model t  , revision **63ebb8ccb**
 
**Describe the bug**
I noticed unwanted scrolling of Suite in background of modal in Firefox.
Chromium works fine / see video from chromium/

**Steps to reproduce:**
1. Load suite in Firefox
2. Open firmware update modal
3. Scroll up and down and observe

**Expected result:**
Scrolling only scrolls opened modal.

**Actual result:**
Scrolling moves Suite background when end of modal is reached.

**Screenshots:**

`Firefox`
Peek 2020-11-03 09-04

`Chromium`

https://www.youtube.com/watch?v=E4sf-BlXhcA&feature=youtu.be

### LINKED ISSUE #2888: New coin icons
Please update the coin icons. The current set is a mix of styles and colors. 

Therefore we created this custom set instead: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide/components?cseid=5fa3cd3a61208235de302db6)

### LINKED ISSUE #2894: Missing scrollbars in Firefox
**Describe the bug**
Missing scollbars in borh left and right panels.

**Info:**
 - Suite Version: web, commit 513631a9fa62c438e60397a9942b04275bcd621a
 - Browser: Firefox , version 82.0 (64-bit)
 - OS: Nixos
 - Firmware Version: model One FW 1.9.3  , revision 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8,

**Steps to reproduce:**
1. Load Suite in Firefox 
2. Load wallet with enough accounts and coins so you can scroll
3. Try to scroll right and left panel

**Expected result:**
You can scroll accounts and transactions separately 

**Actual result:**
You can only scroll whole Suite

**Screenshots:**
Peek 2020-11-05 13-30

**Chrome**

image

**Firefox**

image

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/2738
close https://github.com/trezor/trezor-suite/issues/2226
close https://github.com/trezor/trezor-suite/issues/2894
close https://github.com/trezor/trezor-suite/issues/2888
apparently it also fixes https://github.com/trezor/trezor-suite/issues/2793
apparently it also fixes https://github.com/trezor/trezor-suite/issues/2841

for another PR:
 - desktop: avoid flash of default theme (on mac with dark mode enabled you will still see the flash of light theme, even tho we can tell the OS is in dark mode even before running javascript), maybe we could take it further and save selected theme to a file, so we don't even have to wait for idb to load our favorite theme. I'm leaving this for another PR as it will take more time to find the best solution.

## tldr; on what happened:
- Cleaned up colors definition in `@trezor/components` (converted everything to colors from our current design, removed old colors). Added new `THEME` object which holds color scheme for each theme (`THEME = {light: {...}, dark: {} }`)

- Whole component tree is now wrapped with our custom `ThemeProvider`, which uses `ThemeProvider` from styled-components under the hood. Its purpose is to pass colors for selected theme to SC's ThemeProvider which automatically takes care of injecting theme prop to all styled components. There is also additional logic for automatically selecting the theme based on OS theme (tested on mac, it works!). 
**Then in the component itself, instead of doing `color: ${colors.NEUE_TYPE_DARK_GREY}` you simply use passed theme prop `color: ${props => props.theme.NEUE_TYPE_DARK_GREY}`. Now the color will change automatically with selected theme. The `theme` prop is also correctly typed, on hover you can see what are the values given color resolves in.
Sometimes you need to use a correct color outside of styled component, eg. typically passing color as a prop to a component in JSX (`<Icon color={...})`), to help you with this, there is `useTheme` hook which will return colors object for currently active theme. `const theme = useTheme(); ... <Icon color={theme.NEUE_TYPE_RED} ... />`**

- Theme setting is stored inside a  a suite reducer (`suite.settings.theme`) and it is synced to persistent storage. Themes defined by us (right now "light" and "dark") will only use `theme.variant` field. However in debug settings there is an option to pick your own colors for dark mode. For this case the `theme.variant` will be set to 'custom', and all custom colors will be stored in `theme.colors`.

- reworked the way we inject global styles to be more idiomatic, now leveraging the injected `theme` prop

- There are bunch of little things, such as for images we are lowering their brightness and increasing contrast otherwise they look washed-out (you might say that they still do, but that's designer's problem now!), scrollbars also gets darker (even in firefox), updated coin icons, fixed images that had transparent layer

ohh, btw while I was working on this I run into this awesome write-up on dark mode from UI/UX perspective https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/

### CODE REVIEW

**Comment by mroz22** [comment]
I would suggest merging this rather soon and put it behind a feature flag. Otherwise you will die from resolving conflicts..

**Comment by slowbackspace** [comment]
@mroz22 It will be fine :) I am gonna resolve them all at once, and also I'll update newly added components, once everything is ready for review (probably later today) which I hope will be quick.

**Comment by slowbackspace** [comment]
🎉 🎉 🎉  I am marking this as ready for review, I am still waiting for few things from our beloved product team, but these will boring changes anyway so feel free to take a look (PR looks big, but these are mostly 'search-n-replace' type of changes, so don't be scared). There is certainly room for improvements which I would like to make in another PR(s). Mainly we could get of some colors definitions and derive them from existing colors using something like `color` lib and also find a way to solve  "flash of default theme" in desktop build.

I am sure there will be some things missing/visually broken (most likely dark text on dark bg) so the sooner we can merge it into the develop the better is our chance to catch these issues before next release :)

**Review by keraf — CHANGES_REQUESTED** [review]
Glanced over the functional changes of this PR and code looks mostly good to me. Just a few comments.

I found an issue with the toggling of the dark/light freezing the window for a second on Firefox (haven't checked in Chrome). This is from the performance tab when toggling it on and off.
Screenshot from 2020-11-12 15-24-25.

Regarding the design, I'm not sure if we really need to have the dark-mode switch button in the nav bar. It feels to me like it's a setting that once enabled will rarely get fiddled with. Detection is automatic and I feel we should only have it in the settings. I would also maybe suggest changing it into a list instead of a toggle and change the wording around theming. It would be nice to have more themes in the future (community contributions, secret unlockable or even accessibility focused theme) and would show also that we're open to the idea of adding more.

I've also noticed analytics is missing. It would be interesting to see if people use themes or not.

And lastly, some documentation would be really nice. That would be even more useful if we would consider the multi-theme way I described above. The community could use it to design their own themes.

Overall, nice work, I love it :heart:

**Comment by mroz22** [comment]
> Regarding the design, I'm not sure if we really need to have the dark-mode switch button in the nav bar. It feels to me like it's a setting that once enabled will rarely get fiddled with

My words. I'd say this can go into settings. But who am I to judge designers choices?
And actually, for now, the switch on a reachable position may be helpful to quickly validate that there are no unexpected differences between normal and dark mode.

File: packages/components/src/components/Icon/index.tsx [hunk 1]
```diff
@@ -102,6 +102,8 @@ const Icon = React.forwardRef(
         }: Props,
         ref?: React.Ref<HTMLDivElement>
     ) => {
+        const theme = useTheme();
+        const defaultColor = color ?? theme.TYPE_LIGHT_GREY;
```
Comment (mroz22) [inline packages/components/src/components/Icon/index.tsx:106]: probably good idea to adapt mentally to using `??` everywhere instead of `||`

File: packages/components/src/components/buttons/Pin/index.tsx [hunk 2]
```diff
@@ -1,30 +1,30 @@
...
     position: relative;
     cursor: pointer;
+    margin: 4px;
+
+    padding-top: 30%;
+    width: 100%;
+
+    border-radius: 4px;
+    border: 1px solid ${props => props.theme.STROKE_GREY};
+    background: ${props => props.theme.BG_LIGHT_GREY};
```
Comment (mroz22) [inline packages/components/src/components/buttons/Pin/index.tsx:17]: just ideas, haven't checked yet, but:
1. doesn't it break some nested modal pin window?
1. does it keep buttons squared?

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx [hunk 3]
```diff
@@ -132,6 +136,15 @@ const NavigationActions = (props: Props) => {
                 );
             })}
             <ActionsContainer desktop={isDesktop()} mobileLayout={props.isMobileLayout}>
+                <ActionItem
+                    onClick={() => {
+                        setTheme(theme.variant === 'light' ? 'dark' : 'light');
+                    }}
+                    isActive={theme.variant === 'dark'}
+                    label={<Translation id="TR_DISCREET" />}
```
Comment (mroz22) [inline packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx]: This is one of the todos you mentioned for a future PR, right?

File: packages/suite/src/components/suite/PasswordStrengthIndicator/index.tsx [hunk 4]
```diff
@@ -10,7 +10,7 @@ interface WrapperProps {
 const Wrapper = styled.div<WrapperProps>`
     display: flex;
     margin: 8px 0;
-    flex: 1;
+    /* flex: 1; */
```
Comment (mroz22) [inline packages/suite/src/components/suite/PasswordStrengthIndicator/index.tsx]: everything works nice even after commenting it out?

File: packages/suite/src/components/suite/TransactionsGraph/components/RangeSelector/index.tsx [hunk 5]
```diff
@@ -15,7 +15,7 @@ const RangeItem = styled.div<{ selected: boolean }>`
     font-size: ${variables.FONT_SIZE.SMALL};
     text-align: center;
     font-weight: ${props => (props.selected ? 600 : 500)};
-    color: ${props => (props.selected ? colors.NEUE_TYPE_DARK_GREY : colors.NEUE_TYPE_LIGHT_GREY)};
+    color: ${props => (props.selected ? props.theme.TYPE_DARK_GREY : props.theme.TYPE_LIGHT_GREY)};
```
Comment (mroz22) [inline packages/suite/src/components/suite/TransactionsGraph/components/RangeSelector/index.tsx:18]: does props.theme exist here?

File: packages/suite/src/support/suite/ThemeProvider.tsx [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+        case 'dark':
+            return THEME.dark;
+        case 'custom':
+            // custom theme is a secret feature accessible in debug settings
+            return {
+                ...THEME.dark, // spread default colors, so we can be sure no new colors are missing in user's palette
+                ...theme.colors, // custom saved colors
+            };
+        default:
+            return THEME.light;
```
Comment (mroz22) [inline packages/suite/src/support/suite/ThemeProvider.tsx:23]: I am thinking about whether it won't be better to do migration and fill store with theme default. But this is probably good enough as long as somebody does not remove this default.

File: packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/index.tsx [hunk 7]
```diff
@@ -43,12 +43,12 @@ const DividerMiddle = styled.div`
...
     padding: 5px 20px;
-    color: ${colors.NEUE_TYPE_LIGHT_GREY};
+    color: ${props => props.theme.TYPE_LIGHT_GREY};
     font-weight: ${variables.FONT_WEIGHT.MEDIUM};
     font-size: ${variables.FONT_SIZE.SMALL};
     border-radius: 25px;
-    border: 1px solid ${colors.NEUE_STROKE_GREY};
-    background: ${colors.WHITE};
+    border: 1px solid ${props => props.theme.STROKE_GREY};
+    color: ${props => props.theme.BG_WHITE};
```
Comment (mroz22) [inline packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/index.tsx]: original 'background', new: 'color', color is doubled, is that expected?

File: packages/suite/src/views/wallet/transactions/components/TransactionList/components/Pagination/index.tsx [hunk 8]
```diff
@@ -11,10 +11,10 @@ const Wrapper = styled.div`
 const PageItem = styled.div<{ isActive?: boolean }>`
     cursor: pointer;
     font-size: ${variables.FONT_SIZE.SMALL};
-    background: ${props => (props.isActive ? colors.GREEN : 'transparent')};
-    color: ${props => (props.isActive ? colors.WHITE : colors.GREEN)};
+    background: ${props => (props.isActive ? props.theme.BG_GREEN : 'transparent')};
+    color: ${props => (props.isActive ? props.theme.TYPE_WHITE : props.theme.TYPE_GREEN)};
     padding: 4px 8px;
-    border-radius: 2px;
+    border-radius: 2px;s
```
Comment (mroz22) [inline packages/suite/src/views/wallet/transactions/components/TransactionList/components/Pagination/index.tsx]: here is some left behind 's'.
this is actually something I don't like very much about styled components, you may miss `;` and checks still pass

**Review by mroz22 — CHANGES_REQUESTED** [review]

**Comment by slowbackspace** [comment]
> Glanced over the functional changes of this PR and code looks mostly good to me. Just a few comments.
> 
> I found an issue with the toggling of the dark/light freezing the window for a second on Firefox (haven't checked in Chrome). This is from the performance tab when toggling it on and off.
> Screenshot from 2020-11-12 15-24-25.
> 
I would expect some lag as react needs to rerender whole component tree (which is rather big), chrome is a bit faster with these things it seems (for me it is instant on Chrome, up to 1s lag in Firefox). Do you know some way how this can be optimised?

> Regarding the design, I'm not sure if we really need to have the dark-mode switch button in the nav bar. It feels to me like it's a setting that once enabled will rarely get fiddled with. Detection is automatic and I feel we should only have it in the settings.

You are correct, there won't be a switch in the nav bar, only in settings :) I was just waiting for product decision.

>I would also maybe suggest changing it into a list instead of a toggle and change the wording around theming. It would be nice to have more themes in the future (community contributions, secret unlockable or even accessibility focused theme) and would show also that we're open to the idea of adding more.

I agree, but right know the decision is to only include one dark mode, if in the future we will decide to support more themes it will be easy pretty easy to replace switch with select component, I find it more intuitive to have dark mode toggle than selector with 2 themes (light, dark). Let's get the basics of the dark mode right and later we will come up with more themes :)

> 
> I've also noticed analytics is missing. It would be interesting to see if people use themes or not.

Good points! @mroz22 will you take care of it please?
> 
> And lastly, some documentation would be really nice. That would be even more useful if we would consider the multi-theme way I described above. The community could use it to design their own themes.

Ohh, you probably mean documentation for the color palette in debug settings, that's is not supposed to be very user accessible. These settings are hidden from the user (It's really an ad-hoc solution). The purpose of it  is to provide a bit easier way to tinker our dark theme for product team (and devs I guess). Also I want to take time to refactor some of the color definitions, so it wouldn't make much sense to document it right now.

If you mean docs for the technical part then let me now the rough outline what would you like to see in it. I thought the implementation is pretty straight-forward, but ofc that may be just because I was the one doing it 😁 

> 
> Overall, nice work, I love it ❤️

❤️

File: packages/suite/src/views/wallet/transactions/components/TransactionList/components/Pagination/index.tsx (hunk 8 above)
Comment (slowbackspace) [reply packages/suite/src/views/wallet/transactions/components/TransactionList/components/Pagination/index.tsx]: good thing we have good reviewers :) I thought that would be caught by some of our linters, weird.

File: packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/index.tsx (hunk 7 above)
Comment (slowbackspace) [reply packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/index.tsx]: good catch :) I'll probably ping invity team to take a look at their part of the app as they are more likely to notice unusual things

File: packages/components/src/components/buttons/Pin/index.tsx (hunk 2 above)
Comment (slowbackspace) [reply packages/components/src/components/buttons/Pin/index.tsx:17]: ohh, it should be the same. I noticed there were two pin button components. One in suite and one in trezor/components. We were using one from suite, so I copied its guts to the trezor/component's pin button and switched the import (and ofc removed no longed used pin button from suite).

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx (hunk 3 above)
Comment (slowbackspace) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx]: this will get fixed (removed) in this PR :) We are going to need only switch in the settings.

File: packages/suite/src/components/suite/PasswordStrengthIndicator/index.tsx (hunk 4 above)
Comment (slowbackspace) [reply packages/suite/src/components/suite/PasswordStrengthIndicator/index.tsx]: huh, indeed that was probably not necessary. I noticed the strength indicator wasn't showing at all (latest develop), so I tried to figure out what happened to it. This is probably some left over from this.

File: packages/suite/src/support/suite/ThemeProvider.tsx (hunk 6 above)
Comment (slowbackspace) [reply packages/suite/src/support/suite/ThemeProvider.tsx:23]: yeah, if we are gonna do some changes we are supposed to do proper migration. this is just for the events when we forget about it :)

Comment (slowbackspace) [reply packages/suite/src/support/suite/ThemeProvider.tsx:23]: ohh wait. you werent talking about the `default` case. give me a sec.

Comment (slowbackspace) [reply packages/suite/src/support/suite/ThemeProvider.tsx:23]: that spread in `custom` case is really a safety check, as the feature is intended only for internal use I wanted to prevent weird things happening to our beloved product team. I do not expect we are going to bother with migrations for this hidden top secret interal-only feature.

**Comment by mroz22** [comment]
Regarding analytics, just please create an issue whenever you feel there is something worth reporting.

**Comment by slowbackspace** [comment]
Thank you guys! I've fixed a few things and removed the toggle from navbar. I see invity managed to get some of their stuff merged so I'm gonna rebase later once we made sure that the fixups commits actually fixed things :)

heey, btw @keraf did you noticed fixed scrolling in firefox? 😁 also new sexy themed scrollbars (well, only their color changed, it's now based on selected theme)!

**Comment by slowbackspace** [comment]
Ohh and I got an update from design, we are gonna use a bit lighter colors (🎉 🎉 🎉 ), so I'll update the definitions (one file change only, don't worry)

**Comment by mroz22** [comment]
Good please rebase and let's merge this hydra

**Comment by keraf** [comment]
Let's not jump the gun on this one and wait at least for Monday before merging. There are still a few things to be looked at, especially the performance issues on Firefox. It would also be a good idea to let QA run the branch first (cc @trezor/qa).

**Comment by slowbackspace** [comment]
@keraf  The perf issue you are talking about is only while you are actually switching themes, which most users don't do daily. If there is a room for optimisation then I am more than happy to do it, but I don't know how it could be improved. Our component tree is huge and it just might be the cause that rerendering  of everything is pretty heavy op, or do you see other problems?

There are tons of places that could use some optimizations I am not sure if action that user will be doing 2 times in their whole life is worth it to maybe save half a sec in one browser.

edit: Just to be clear, I am not saying that lag in firefox is not a bad for an UX, I just find weird we are making a blocker out of this. Rebasing this branch is not something I enjoy doing :)

**Comment by slowbackspace** [comment]
Added some more commits, last 2 or 3 are adding new invity stuff that got added after the rebase

**Comment by keraf** [comment]
Any action that freezes the whole render process for a second is bad UX, no matter how often the user does it. If it's fast in Chrome and not Firefox, there must be reason for that and we should be looking into it. We have some creeping performance problems and adding more on top of it is unwise in my opinion. I'll check out the branch and look into it.

**Comment by slowbackspace** [comment]
@keraf attached gif of firefox when changing theme in settings, no perf issues here. As I already said, if you had slow experience in the dashboard, it might be because of our huge component tree that is taking some time to rerender (chrome is always way faster). If that't the case then fixing it is really out of scope of this PR (and I would still say it doesn't matter that much since the switch will be only in settings 😁). 
But ofc feel free to take a look at it, I just don't wanna keep rebasing this forever.

Screen Recording 2020-11-13 at 15 01 03

**Comment by keraf** [comment]
I can constantly reproduce the slow down on the settings page on two different machines (both running Ubuntu 20.04) in Firefox. I just tried it in Chromium and it's totally broken there (the toggle is even slower to react and it never switches to dark mode). I haven't tested a prod build yet but we can check on the deployed environment on the CI passes.

The culprit according to the React profiler is the `GlobalStyle` component. Haven't dug too deep into it yet but will do so shortly.

**Comment by slowbackspace** [comment]
@keraf  waait, you are testing the performance locally on dev builds? these are gonna be slow by design - https://reactjs.org/docs/optimizing-performance.html#use-the-production-build
also make sure you did git pull :) probably also clear storage if you tried this branch before (I did some incompatible changes since the first introduction of this branch)

the gif I posted is taken from https://suite.corp.sldev.cz/suite-web/feat/dark/web/

**Comment by keraf** [comment]
Local dev builds are slower than prod builds, that's no contest, but not slow to this point. We should try to keep our development builds relatively fast or we'll end-up in situations where debugging is painful. I guess for this one it's not too bad apart from the startup dip. Checked in the deployed build, about 100ms freeze which is negligible imo. 

Edit: Checked local dev build with latest changes, freeze is less noticeable (< 1s). That's good enough for me.

**Comment by tomexx** [comment]
First of all - very good job! 👍 🔥

+ I have couple of suggestions regarding the design:

1) I'd go for lighter color when hovering/selecting an item e.g. in dropdown select etc.
Screenshot 2020-11-16 at 12 28 51

2) I'd maybe adjust the background color of secondary buttons to a lighter (greyish) version. See now and my suggestion
Screenshot 2020-11-16 at 12 30 11
Screenshot 2020-11-16 at 12 30 02

3) I'd lower the contranst on pure white elements, e.g. toggle switches. See my propsoal for the off state of a toggle switch
Screenshot 2020-11-16 at 12 31 33

4) Transaction graph colors + graph tooltip colors looks a bit odd now also
Screenshot 2020-11-16 at 12 32 58
Screenshot 2020-11-16 at 12 33 06

5) "Soon" tag seems to be too bright
Screenshot 2020-11-16 at 12 35 13

Please consider changing these (consult with designers) :)

**Comment by slowbackspace** [comment]
> First of all - very good job! 👍 🔥
> 
> * I have couple of suggestions regarding the design:
> 
> 1. I'd go for lighter color when hovering/selecting an item e.g. in dropdown select etc.
> 2. I'd maybe adjust the background color of secondary buttons to a lighter (greyish) version. See now and my suggestion
> 4. Transaction graph colors + graph tooltip colors looks a bit odd now also
> 5. "Soon" tag seems to be too bright
> 
> Please consider changing these (consult with designers) :)

Thank you!
passed 1, 2 and 4 to our designer. I also have a few idea how to make things better so do not worry, this is not like we are gonna release it tomorrow and never improve. I would rather expect more changes to the design in upcoming weeks :)

3  - should be better now, it looks like our override for switch color never worked 🎉 
5 -  I did ad-hoc fix. I expect the soon badge will be gone before the release anyway.

I also fixed color for elements that haven't defined their own color and the color was also not defined anywhere in an ancestors (invity stuff)

**Comment by slowbackspace** [comment]
I am gonna express my concerns once more, The sooner it will land into the develop the better as we'll all have more time to catch visually subtle things that could have real impact (eg. dark text on dark bg), although I think there won't be many of these. There is no way 1 person/QA can catch all in a few days. That's why I made this PR early in our release cycle.

The basics are done, it works and can be iteratively improved

✌️

**Comment by prusnak** [comment]
I agree with Maros here. Let's get this in ASAP if it's not breaking anything and we can deal with the smaller visual changes later.
Ideally we should start another issue for collecting these ideas for improvements.

**Review by keraf — APPROVED** [review]

**Review by mroz22 — APPROVED** [review]

**Review by tomexx — APPROVED** [review]
