### PR TITLE
fix(coinmarket): delete temporarly best rate & update exchange list

### LINKED ISSUE #13927: Exchange offers are now showing mix of float/fixed/dex offers
Because we launched partial redesign of trade features, the comparator for exchange is now lacking some element to describe fixed rate/floating rate/dex offers.

Additionally "Best rate" label is not always assigned to correct offer with best rate within it's category.

We need to temporarily add headlines for each section in Exchange offer comparison screen to inform user what type of offer they choose.

Screenshot 2024-08-22 at 13 58 31

**Temporary fix (will be removed after the exchange flow redesign)**
- Add headlines Fixed-rate offer / Floating-rate offer / Decentralised exchange offer
- Hide "Best rate" label

**To test**
- Exchange comparator screen has headlines for fixed-rate offers and floating-rate offers (+ dex if there is dex offer available for EVM token pairs)
- No change in comparator screen for buy or sell flow

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
- temporarily removed the `Best rate` tag
- temporarily created sections for exchange offers 

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/13927

## Design before
Screenshot 2024-08-22 at 13 58 31

## Design after
obrazek

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx [hunk 1]
```diff
@@ -23,8 +79,11 @@ const CoinmarketOffers = () => {
                 titleTimer="TR_COINMARKET_OFFERS_REFRESH"
                 showTimerNextToTitle={isCoinmarketExchangeOffers(context)}
             />
+            {/* eslint-disable-next-line no-nested-ternary */}
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx]: Can we do it without nested ternary operator please? 🙏

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketFeaturedOffers/CoinmarketFeaturedOffersItem.tsx [hunk 2]
```diff
@@ -131,11 +127,11 @@ const CoinmarketFeaturedOffersItem = ({
             <Offer>
                 <OfferColumn1>
                     <OfferBadgeWrap>
-                        {isBestRate && (
+                        {/*isBestRate && (
                             <OfferBadge variant="primary">
                                 <Translation id="TR_COINMARKET_BEST_RATE" />
                             </OfferBadge>
-                        )}
+                        ) */}
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketFeaturedOffers/CoinmarketFeaturedOffersItem.tsx]: I know you might use this code in the future, but I believe we shouldn't keep these comments in the codebase. 🙏  We can restore it later from this PR.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx [hunk 3]
```diff
@@ -6,6 +6,62 @@ import {
...
+// temporary solution for exchange, will be deleted in next release
+const CoinmarketOffersExchange = () => {
+    const { quotes, exchangeInfo } = useCoinmarketOffersContext<CoinmarketTradeExchangeType>();
+
+    if (!quotes) return null;
+
+    const fixed =
+        quotes.filter(
+            q => exchangeInfo?.providerInfos[q.exchange || '']?.isFixedRate && !q.isDex,
+        ) || [];
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx]: I think you shouldn't need `|| []` because it returns empty array if no elements pass

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx [hunk 4]
```diff
@@ -6,6 +6,62 @@ import {
...
+    const float =
+        quotes.filter(
+            q => !exchangeInfo?.providerInfos[q.exchange || '']?.isFixedRate && !q.isDex,
+        ) || [];
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx]: could you simplify this please? 🙏 


Maybe something like this?

```tsx
const getQuotesByRateType = (isFixedRate) =>
    quotes.filter(q => exchangeInfo?.providerInfos[q.exchange || '']?.isFixedRate === isFixedRate && !q.isDex);

const fixed = getQuotesByRateType(true);
const float = getQuotesByRateType(false);

**Review by jvaclavik — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx [hunk 5]
```diff
@@ -6,6 +6,62 @@ import {
...
+    const dex = quotes.filter(q => q.isDex) || [];
+
+    const renderQuotes = (quotes: ExchangeTrade[], heading: ExtendedMessageDescriptor['id']) => {
+        if (quotes.length === 0) return null;
+
+        return (
+            <>
```
Comment (seibei-iguchi) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx:41]: I suggest using section here instead of a fragment, and apply the top margin here instead of the heading.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx [hunk 6]
```diff
@@ -6,6 +6,62 @@ import {
...
 } from 'src/hooks/wallet/coinmarket/offers/useCoinmarketCommonOffers';
 import { getBestRatedQuote } from 'src/utils/wallet/coinmarket/coinmarketUtils';
+import { CoinmarketTradeExchangeType } from 'src/types/coinmarket/coinmarket';
+import { ExchangeTrade } from 'invity-api';
+import { ExtendedMessageDescriptor } from '@suite-common/intl-types';
+import { Translation } from 'src/components/suite';
+import styled from 'styled-components';
+import { spacingsPx } from '@trezor/theme';
+
+const CoinmarketSectionHeading = styled.div`
```
Comment (seibei-iguchi) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx:16]: Using H3, while moving the top margin to the section itself (see my other comment), might be better.

**Review by LukasRada — APPROVED** [review]

**Review by LukasRada — CHANGES_REQUESTED** [review]
Please fix tests

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx (hunk 6 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx:16]: We tested the size of the font, it doesn't look good. It is just a temporary solution.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx (hunk 5 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx:41]: It would be a better solution if a negative bottom margin weren't necessary for the heading.

**Review by LukasRada — APPROVED** [review]

**Review by jvaclavik — APPROVED** [review]

**Review by MiroslavProchazka — APPROVED** [review]
