### PR TITLE
fix: make sure that the we can use the suite sync when device is not …

### LINKED ISSUE #23677: User should be able to use Suite Sync without need of connected Trezor
**Describe the bug**
If your selected device is connected, you can use labelling for all devices/wallets and if your selected device is not connected, you can't use it anywhere.

**Expected behavior**
User should be able to use Suite Sync without need of connected Trezor.

https://github.com/user-attachments/assets/0c941701-a957-4150-b73b-9d9be01ebacd

### PR DESCRIPTION
**Pull request by vojtatranta**
…connected but the keys are available

## Description

We have forgotten on if-case here. Because we want to allow the user to use the suite-sync without the need for the device to be connected if the keys are available.

## Notes for QA

You should be able to use the Suite Sync even when the device is not connected (but you have the keys provided already eg. when the app runs some time before)

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23677

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=23677-suite-sync-without-keys&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=23677-suite-sync-without-keys&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=23677-suite-sync-without-keys&lookback=7)

### CODE REVIEW

**Comment by vojtatranta** [comment]
Will addd tests and promise to rename the file, asi it is not refresh in fact, it is rather an ensure.

File: suite-common/suite-sync/src/createRefreshSuiteSync.ts [hunk 1]
```diff
@@ -11,19 +11,32 @@ import { notificationsActions } from '@suite-common/toast-notifications';
...
 export type RefreshSuiteSyncKeysDeps = {
     dispatch: Dispatch;
 } & EnsureSuiteSyncOwnerDep &
+    LoadSuiteSyncOwnerFromStateDep &
     EnsureDelegatedIdentityKeyDep;
 
 export const createRefreshSuiteSync =
     (deps: RefreshSuiteSyncKeysDeps): RefreshSuiteSyncKeys =>
     async ({ device }): ReturnType<RefreshSuiteSyncKeys> => {
+        if (!device || !isTrezorDeviceWithState(device)) {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/createRefreshSuiteSync.ts:33]: image

Comment (vojtatranta) [reply suite-common/suite-sync/src/createRefreshSuiteSync.ts:33]: Haters gonna hate

Comment (vojtatranta) [reply suite-common/suite-sync/src/createRefreshSuiteSync.ts:33]: added

File: suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts [hunk 2]
```diff
@@ -0,0 +1,185 @@
...
+    >(),
+    ensureDelegatedIdentityKey: jest.fn<
+        ReturnType<EnsureDelegatedIdentityKey>,
+        Parameters<EnsureDelegatedIdentityKey>
+    >(),
+});
+
+const createDevice = (
+    overrides: Partial<TrezorDevice> = {},
+    stateOverrides?: Record<string, unknown>,
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts]:
```suggestion
    deviceStateOverrides?: Partial<TrezorDevice["state"]>,
```

File: suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts [hunk 3]
```diff
@@ -0,0 +1,185 @@
...
+                      },
+                      staticSessionId: 'test-session-id',
+                      ...stateOverrides,
+                  },
+              }
+            : {}),
+        ...overrides,
+    }) as unknown as TrezorDevice;
+
+describe('refreshSuiteSyncKeys', () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts]:
```suggestion
describe(refreshSuiteSyncKeys.name, () => {
```

File: suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts [hunk 4]
```diff
@@ -0,0 +1,185 @@
...
+    it('returns refresh suite sync unavailable when device is not with state', async () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts]:
```suggestion
    it('fails with "unable to get keys" when device is not initialized', async () => {
```

File: suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts [hunk 5]
```diff
@@ -0,0 +1,185 @@
...
+        const deps = createDeps();
+        const refreshSuiteSyncKeys = createRefreshSuiteSync(deps);
+        const result = await refreshSuiteSyncKeys({
+            device: createDevice(),
+        });
+
+        expect(result.ok).toEqual(false);
+        if (!result.ok) {
+            expect(result.error.type).toBe('RefreshSuiteKeysUnavailable');
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts]: I do it usually:
```ts
expect(!result.ok && result.error.type).toBe('RefreshSuiteKeysUnavailable');
```

But not sure it its better actually... :thinking:

File: suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts [hunk 6]
```diff
@@ -0,0 +1,185 @@
...
+        });
+
+        expect(result.ok).toEqual(false);
+        if (!result.ok) {
+            expect(result.error.type).toBe('RefreshSuiteKeysUnavailable');
+        }
+    });
+
+    it('returns an suite sync owner when device has state and is available', async () => {
+        const mockOwner = {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts]: you can extract some `OWNER_1` as global file const to use it in all tests

File: suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts [hunk 7]
```diff
@@ -0,0 +1,185 @@
...
+    >(),
+    ensureDelegatedIdentityKey: jest.fn<
+        ReturnType<EnsureDelegatedIdentityKey>,
+        Parameters<EnsureDelegatedIdentityKey>
+    >(),
+});
+
+const createDevice = (
+    overrides: Partial<TrezorDevice> = {},
+    deviceStateOverrides?: Partial<TrezorDevice["state"]>,
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts]:
```suggestion
    deviceStateOverrides: Partial<TrezorDevice["state"]> = {},
```

Shall work as well so then you can ommit the ternal

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts [hunk 8]
```diff
@@ -0,0 +1,185 @@
...
+        };
+        const deps = createDeps();
+        deps.loadSuiteSyncOwnerFromState.mockResolvedValue(null);
+        deps.ensureSuiteSyncOwner.mockResolvedValue(ok(ensuredOwner));
+        deps.ensureDelegatedIdentityKey.mockResolvedValue(
+            ok(asDelegatedIdentityKey('delegated-key-value')),
+        );
+
+        const refreshSuiteSyncKeys = createRefreshSuiteSync(deps);
+        await refreshSuiteSyncKeys({
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts]: I think return shall be asserted as well here

File: suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts [hunk 9]
```diff
@@ -0,0 +1,185 @@
...
+
+        const refreshSuiteSyncKeys = createRefreshSuiteSync(deps);
+        await refreshSuiteSyncKeys({
+            device: createDevice({}, {}),
+        });
+
+        expect(deps.ensureDelegatedIdentityKey).toHaveBeenCalled();
+    });
+
+    it('returns refresh unavailable when device is disconnected', async () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/tests/refreshSuiteSyncKeys.test.ts]:
```suggestion
    it('fails to get keys, when device is disconnected', async () => {
```

You shall go for `returns` as only last resort

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts [hunk 10]
```diff
@@ -0,0 +1,185 @@
...
+            device: createDevice({ connected: false }, {}),
+        });
+
+        expect(result.ok).toEqual(false);
+        if (!result.ok) {
+            expect(result.error.type).toEqual('RefreshSuiteKeysUnavailable');
+        }
+    });
+
+    it('requests ensureDelegatedIdentityKey when owner is not in state', async () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts]: This test is imo redundant to the thest after this.

I would simplify to:

`it('ensures both DelegatedIdentityKey and Owner when device has no Owner'`

And do both asserts:
- `expect(deps.ensureDelegatedIdentityKey).toHaveBeenCalled();`
- `expect(deps.ensureSuiteSyncOwner).toHaveBeenCalled();`

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts [hunk 11]
```diff
@@ -0,0 +1,185 @@
...
+
+        const refreshSuiteSyncKeys = createRefreshSuiteSync(deps);
+        await refreshSuiteSyncKeys({
+            device: createDevice({}, {}),
+        });
+
+        expect(deps.ensureSuiteSyncOwner).toHaveBeenCalled();
+    });
+
+    it('finally returns the new refreshed owner', async () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts:136]: `finally` wut? AI slop?

Also this test is imo duplicate of `it('requests refreshing of the keys when they arent available in the state', async () => {`

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts [hunk 12]
```diff
@@ -0,0 +1,185 @@
...
+                          path: 'test-path',
+                          instance: 1,
+                      },
+                      staticSessionId: 'test-session-id',
+                      ...stateOverrides,
+                  },
+              }
+            : {}),
+        ...overrides,
+    }) as unknown as TrezorDevice;
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts:55]: I am trying to not to have to do it. (Do some `Pick<..>`) But its kinda hard on the top-level)

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts (hunk 11 above)
Comment (vojtatranta) [reply suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts:136]: No, this says that this is a final return when the delegate and ensure is called.

What here shoudn't be "finally" it says that this is done after all refreshes a are done.

Requests refreshing chckes, if it is called. Not if a completle result is return after all is done.

Valid case here.

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts (hunk 12 above)
Comment (vojtatranta) [reply suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts:55]: Corect would be to have a function for mocking the device object as universal.

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts (hunk 10 above)
Comment (vojtatranta) [reply suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts]: one expect, one test - golden rule.

Or... We can put all expects in one test! :-D 
Why not have it transparent, have as few expects as possible in a test? 

If we had like "oh, let's expect everything", then te test description can be: "it('should work')".

These are unit test, unit is a I test a unit of code. 

now, if it was integration tests, then it's okay to have multiple expects.

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts (hunk 8 above)
Comment (vojtatranta) [reply suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts]: no, I test "the request".

Comment (vojtatranta) [reply suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts]: Reason: The fact that this returns is a coincidence. I just testing here that I wanted is requested. The test is resiliant, because why should it fail, if it stops returning this? 

These are 2 different things, that it returns the result of this, and it requests when X.

File: suite-common/suite-sync/src/refreshSuiteSyncKeys.ts
Comment (vojtatranta) [inline suite-common/suite-sync/src/refreshSuiteSyncKeys.ts:59]: I'd like to say that I intuitively avodied thesting taht this was requests.

Thunks sucks, coz they are imported staticaly..

That's my radical opinion.

**Review by peter-sanderson — APPROVED** [review]

File: suite-common/suite-sync/tests/utils.ts [hunk 13]
```diff
@@ -1,3 +1,38 @@
-export const mockNotExpected = (key: string) => () => {
-    throw new Error(`Method ${key} was not expected to be called`);
-};
+import type { Dispatch, ThunkAction, UnknownAction } from '@reduxjs/toolkit';
+
+export const mockNotExpected = <T extends (...args: any[]) => any>(key: string) =>
```
Comment (vojtatranta) [inline suite-common/suite-sync/tests/utils.ts:1]: I know that @peter-sanderson hatest jest, but this is, I think, super useful.

It combines that reliability with mocking

File: suite-common/suite-sync/tests/utils.ts [hunk 14]
```diff
@@ -1,3 +1,38 @@
...
+    jest.fn<ReturnType<T>, Parameters<T>>().mockImplementation(() => {
+        throw new Error(`Method ${key} was not expected to be called`);
+    });
+
+export const mockDispatch = () => mockNotExpected<Dispatch>('dispatch');
+
+export const resolveWhenDispatched = (
```
Comment (vojtatranta) [inline suite-common/suite-sync/tests/utils.ts]: Util to test dispatching

File: suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts [hunk 15]
```diff
@@ -0,0 +1,188 @@
...
+                      },
+                      staticSessionId: 'test-session-id',
+                      ...deviceStateOverrides,
+                  },
+              }
+            : {}),
+        ...overrides,
+    }) as unknown as TrezorDevice;
+
+describe('refreshSuiteSyncKeys', () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts]:
```suggestion
describe(refreshSuiteSyncKeys.name, () => {
```

Comment (vojtatranta) [reply suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts]: This didn't work. It doesn't have property name, per TS. I think name only has `function refreshSuiteSyncKeys ()`

Comment (peter-sanderson) [reply suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts]: * `createRefreshSuiteSync.name` then

Comment (peter-sanderson) [reply suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts]: btw this: https://github.com/trezor/trezor-suite/pull/23954

File: suite-common/suite-sync/tests/utils.ts (hunk 13 above)
Comment (peter-sanderson) [reply suite-common/suite-sync/tests/utils.ts:1]: this is good

File: suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts [hunk 16]
```diff
@@ -0,0 +1,188 @@
...
+
+        const ensureDeviceHasQuotaThunkPendingPromise = resolveWhenDispatched(
+            deps.dispatch,
+            action => action.type === ensureDeviceHasQuotaThunk.pending.type,
+        );
+        await refreshSuiteSyncKeys({
+            device: createDevice(),
+        });
+
+        await ensureDeviceHasQuotaThunkPendingPromise;
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts]: `expect(deps.dispatch).hasBeenCalledWithParams({type: ensureDeviceHasQuotaThunk.pending.type})`

File: suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts [hunk 17]
```diff
@@ -0,0 +1,188 @@
...
+const createMockDeps = (): jest.Mocked<RefreshSuiteSyncKeysDeps> => ({
+    dispatch: mockDispatch(),
+    ensureSuiteSyncOwner: mockNotExpected<EnsureSuiteSyncOwner>('ensureSuiteSyncOwner'),
+    loadSuiteSyncOwnerFromState: mockNotExpected<LoadSuiteSyncOwnerFromState>(
+        'loadSuiteSyncOwnerFromState',
+    ),
+    ensureDelegatedIdentityKey: mockNotExpected<EnsureDelegatedIdentityKey>(
+        'ensureDelegatedIdentityKey',
+    ),
+});
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/refreshSuiteSyncKeys.test.ts]:
```suggestion
} satisfies RefreshSuiteSyncKeysDeps);
```

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts [hunk 18]
```diff
@@ -0,0 +1,176 @@
...
+        const refreshSuiteSyncKeys = createRefreshSuiteSync(deps);
+        const result = await refreshSuiteSyncKeys({
+            device: createDevice({ connected: false }),
+        });
+
+        expect(result.ok).toEqual(false);
+        expect(!result.ok && result.error.type).toEqual('RefreshSuiteKeysUnavailable');
+    });
+
+    it('requests ensureDelegatedIdentityKey when owner is not in state', async () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts]:
```suggestion
    it('ensures that DelegatedIdentityKey is available', async () => {
```

File: suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts [hunk 19]
```diff
@@ -0,0 +1,176 @@
...
+            device: mockDevice,
+        });
+
+        expect(deps.ensureSuiteSyncOwner).toHaveBeenCalledWith({
+            device: mockDevice,
+            delegatedKey: 'delegated-key-value',
+        });
+    });
+
+    it.skip('SKIPPED: test this dispatch: dispatches ensureDeviceHasQuotaThunk when refreshing keys', async () => {
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/tests/createRefreshSuiteSync.test.ts]: extract pls to separate PR for @OriginalEveres to finish

**Review by peter-sanderson — APPROVED** [review]
