### PR TITLE
fix: empower bugs

### LINKED ISSUE #10379: Remove `canAnimate` from the `Icon` component
I believe there is no reason to have animations (especially when there's only 1) defined in the `Icon` component itself.

* remove the prop
* add the animation via Styled Components where needed 
* the animation can be moved to `packages/components/src/config/animations.ts`

### LINKED ISSUE #10614: Review: full width device rename on mobile
As everything is full width on mobile I think it makes sense that device name section is full width too.
9654D07A-591B-47D7-96B6-0B086207228E

### LINKED ISSUE #10749: Use `IconButton` as `AbortButton`
The close button seen below should be an `IconButton`.

image

Related issue: https://github.com/trezor/trezor-suite/issues/5618

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Fixing bugs in Suite empower.

## Related Issue

Resolve #10379
Resolve #10749
Resolve #10614 

## Screenshots:
86790B96-69F3-4B94-BFA6-761E57372B74
0B2CBB87-1AAE-42E4-8D4A-87DC95DE5F2A
BD51AE2D-4D62-4A1D-80E1-D92773A69954

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx [hunk 1]
```diff
@@ -76,10 +75,10 @@ const DevicePromptModalRenderer = ({
                             deviceModelInternal={deviceModelInternal}
                             deviceUnitColor={device?.features?.unit_color}
                             isConfirmed={isConfirmed}
+                            onCancel={isActionAbortable ? onAbort : undefined}
                         />
                     )
                 }
-                headerComponent={isActionAbortable ? <AbortButton onAbort={onAbort} /> : undefined}
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx:82]: The [issue](https://github.com/trezor/trezor-suite/issues/10749) was about using the `IconButton` component styling for the `AbortButton` 🙏  Meaning that the `AbortButton` should stay (for now). Just make sure that the icon size and paddings are in line with `IconButton` + remove `text-transform: uppercase` from it, since we are slowly moving away from it now. 

It should essentially share behavior with the freshly refreshed TX search input! When it's collapsed – it looks exactly like the `IconButton` ;) That is what I mean.

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx [hunk 2]
```diff
@@ -20,10 +21,16 @@ const ChevronContainer = styled.div`
...
-const ChevronIcon = styled(Icon)`
+const ChevronIcon = styled(Icon)<{ isActive: boolean; canAnimate: boolean }>`
     padding: ${spacingsPx.sm};
     border-radius: 50%;
     transition: background 0.2s;
+
+    ${({ canAnimate, isActive }) =>
+        canAnimate &&
+        css`
+            animation: ${isActive ? ROTATE_180_UP : ROTATE_180_DOWN} 0.2s linear 1 forwards;
```
Comment (dahaca) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx]: honestly, I believe this can be handled by a simple `transition`, don't u think? 🤔 `animation` sounds like something that's happening either on mount, perpetually or when there's orchestration involved, e.g. multiple properties are being changed. Here we are simply changing one `transform`.

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx [hunk 3]
```diff
@@ -20,10 +21,16 @@ const ChevronContainer = styled.div`
...
 `;
 
-const ChevronIcon = styled(Icon)`
+const ChevronIcon = styled(Icon)<{ isActive: boolean; canAnimate: boolean }>`
     padding: ${spacingsPx.sm};
     border-radius: 50%;
     transition: background 0.2s;
+
+    ${({ canAnimate, isActive }) =>
+        canAnimate &&
```
Comment (dahaca) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx]: `canAnimate` is no longer needed

File: packages/suite/src/components/firmware/FirmwareOffer.tsx [hunk 4]
```diff
@@ -34,7 +34,7 @@ const FwVersion = styled.div`
 `;
 
 const Version = styled.div<{ isNew?: boolean }>`
-    color: ${({ isNew, theme }) => (isNew ? theme.TYPE_GREEN : theme.TYPE_LIGHT_GREY)};
+    color: ${({ isNew, theme }) => (isNew ? theme.backgroundPrimaryDefault : theme.textSubdued)};
```
Comment (dahaca) [inline packages/suite/src/components/firmware/FirmwareOffer.tsx:37]: 🔥

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountSearchBox.tsx [hunk 5]
```diff
@@ -13,6 +13,7 @@ const StyledInput = styled(Input)`
     input {
         /* to line up with the coin filter  */
         padding-left: 46px;
+        min-height: 38px;
```
Comment (dahaca) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountSearchBox.tsx:16]: Could you tell me what is this here for? Cannot understand :(

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ApplicationLogModal.tsx [hunk 6]
```diff
@@ -32,6 +33,7 @@ const LogWrapper = styled.pre`
 `;
 
 const BalanceInfoSection = styled(SectionItem)`
+    margin-top: ${spacingsPx.md};
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ApplicationLogModal.tsx:36]: nice catch!

File: packages/suite/src/components/settings/DeviceBanner.tsx [hunk 7]
```diff
@@ -12,13 +12,10 @@ const StyledLottieAnimation = styled(LottieAnimation)`
     background: ${({ theme }) => theme.BG_GREY};
 `;
 
-const Wrapper = styled.div`
+const Wrapper = styled(Card)`
```
Comment (dahaca) [inline packages/suite/src/components/settings/DeviceBanner.tsx:15]: nit: can simply be:

```
const Wrapper = styled(Card)`
    flex-direction: row;
`;
```

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountSearchBox.tsx (hunk 5 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountSearchBox.tsx:16]: The plus icon next to this input is 38px high so wanted to aligned the input with the plus icon.

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx (hunk 3 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx]: Then I was moving it I was doing it first without it but is has to be there, it then animates the wrong way

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx:82]: Ok but isn't actually this better?

Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx:82]: I see similar pattern during onboarding
93930FB7-9129-4E28-B0AD-EE33C5BBA118

File: packages/suite/src/components/settings/DeviceBanner.tsx (hunk 7 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/settings/DeviceBanner.tsx:15]: c6c0d40ef00dd874f2c611892cb1e0bacc7992d0

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx]: changing this to a transition doesn't work...

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx (hunk 1 above)
Comment (dahaca) [reply packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx:82]: This change was not in the scope of the issue. It might be better but I am not sure and did not want to solve that. Also, it would be nice to either remove the `AbortButton` completely or keep it there. It's currently still used in 1 place i believe.

To make it quick, please make it tertiary and we will solve the rest later :)

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx (hunk 3 above)
Comment (dahaca) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx]: It's already used working [here](https://github.com/trezor/trezor-suite/blob/f02413b6b16088879177c98efde86cfcaa6de2bc/packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx#L82). No need ffor a complex transition ofc but it's literally the same thing, no? Might be wrong!

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx (hunk 2 above)
Comment (dahaca) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx]: https://github.com/trezor/trezor-suite/pull/10754#discussion_r1467882919

**Review by dahaca — APPROVED** [review]

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountGroup.tsx]: 281bbd1074b0682bc3fbacbdbc0e08ed92c67915

Actually I didn't keep any animation since for example similar the chevron for show and hide security section on dashboard doesn't have any animation at all

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DevicePromptModal.tsx:82]: a3e4aab07883b154062ee7c60b8c33b64d381013
