### PR TITLE
fix(suite): cardano staking dashboard unknown apy

### LINKED ISSUE #22793: Cardano staking - unknown APY for non-Everstake pools
When the `Update/Change provider` banner is visible, show `Unknown` APY
**Proposed**
Image

**Now**

Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description
Display “Unknown APY” when the Update/Change provider banner is visible.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22793

## Screenshots:
image

### CODE REVIEW

File: packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx [hunk 1]
```diff
@@ -76,7 +76,13 @@ export const NewCardanoStakingDashboard = ({
                                 >
                                     <ClaimCard />
                                     <Flex direction={canClaim ? 'column' : 'row'} gap={spacings.sm}>
-                                        <ApyCard apy={apy} />
+                                        <ApyCard
+                                            apy={
+                                                !isCardanoUpdateProviderFlow(account)
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx:81]: isCardanoStakedWithEverstake + no staking would be better?

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -9528,6 +9528,10 @@ export default defineMessages({
         id: 'TR_STAKE_APY_APPROX',
         defaultMessage: '~{apyPercent}% APY',
     },
+    TR_STAKE_UNKNOWN: {
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]:
```suggestion
    TR_STAKE_UNKNOWN_APY: {
```

File: packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx (hunk 1 above)
Comment (dev-pvl) [reply packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx:81]: `isCardanoUpdateProviderFlow = isStakeActive && !isCardanoStakedWithEverstake(account) `
It might be a bit confusing for now, but let's keep it as is

File: packages/suite/src/support/messages.ts (hunk 2 above)
Comment (dev-pvl) [reply packages/suite/src/support/messages.ts]: fixed and rebased

**Review by tomasklim — APPROVED** [review]
