### PR TITLE
fix: fw update with multiple devices using forceRemember approach

### LINKED ISSUE #2813: Fw update - multiple devices
Investigate

### PR DESCRIPTION
**Pull request by mroz22**
this resolves #2813 (fw update while multiple devices are connected) using "forceRememeber" approach. 

there are some genaral changes that require review attetion (sortByPriority function)

tested: 
- [x] test 2 devices, other device not remembered
- [x] test 2 devices, other device remembered
- [x] onboarding, model T 2.1.1, update fw

### CODE REVIEW

File: packages/suite/src/actions/suite/suiteActions.ts [hunk 1]
```diff
@@ -334,6 +334,7 @@ const actions = [
     SUITE.RECEIVE_AUTH_CONFIRM,
     SUITE.UPDATE_PASSPHRASE_MODE,
     SUITE.ADD_BUTTON_REQUEST,
+    SUITE.REMEMBER_DEVICE,
```
Comment (mroz22) [inline packages/suite/src/actions/suite/suiteActions.ts:337]: hmm this might not be needed actually

Comment (szymonlesisz) [reply packages/suite/src/actions/suite/suiteActions.ts:337]: it depends. 
it's needed if you want to reload `suite.selectedDevice`, so if you force-remembered and want to have this information later on (some checking if its force remembered)

**Review by szymonlesisz — APPROVED** [review]
looks good, didnt test it
