### PR TITLE
UI overflow glitches

### LINKED ISSUE #6770: Broken formating when name of the asset is long
When the name of asset is longer and the amount has too many number of digits after zero, design is broken. 

We agreed with designers to go with these rules:
1. Values (FIAT and crypto balance)
- Dashboard and Asset detail header - Dynamic type 
- Dashboard coin tiles - crop the text

2. Texts (name of asset)
- ✅ Dashboard, asset list and TX Detail - Overflow
- Header text - crop

3. TX ID
- ✅ cropping in the middle

Types of how to approach the text and values are in Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/tCSmT0EOdXmhAst051Nxal/s2-Mobile?node-id=7568%3A47342&t=z17h9eezA2fRAay3-0

Printscreens:
Dynamic type:
Image

Overflow:
Image

Cropping
Image

Crop in the middle (TX Detail)
Image

### PR DESCRIPTION
**Pull request by PeKne**
Batch of UI bug fixes:

- header amount values change the font size to always fit the screen (portfolio graph, asset detail graph, transaction detail)
- account and transaction lists adjust it's contents layout to always fit
- screen headers are tail cropped if too long
- shortened addresses android glitch fixed
- other minor UI improvements

## Related Issue

Resolve #6770 

### Header amount values change the font size to always fit the screen:

<div style="flex-direction: row">
Screenshot 2023-03-07 at 8 49 27

Screenshot 2023-03-07 at 8 49 27

Screenshot 2023-03-07 at 8 49 27
</div>

### Account and transaction lists adjust it's contents layout to always fit:

<div>
Screenshot 2023-03-07 at 8 49 27

</div>

### Screen headers are tail cropped if too long:
<div>
Screenshot 2023-03-07 at 8 49 27

Screenshot 2023-03-07 at 8 49 27
</div>

### Shortened addresses android glitch fixed:
Screenshot 2023-03-07 at 8 49 27

### CODE REVIEW

File: suite-native/formatters/src/components/AccountAddressFormatter.tsx [hunk 1]
```diff
@@ -4,18 +4,34 @@ import { useSelector } from 'react-redux';
...
 import { AccountKey } from '@suite-common/wallet-types';
+import { prepareNativeStyle, useNativeStyles, mergeNativeStyleObjects } from '@trezor/styles';
 
 import { FormatterProps } from '../types';
 
 type AccountAddressFormatterProps = FormatterProps<AccountKey> & TextProps;
 
-export const AccountAddressFormatter = ({ value, ...rest }: AccountAddressFormatterProps) => {
+const addressStyle = prepareNativeStyle(_ => ({
+    // ellipsizeMode="middle" is not working  on Android with negative letterSpacing defined in @trezor/theme typography.
```
Comment (Nodonisko) [inline suite-native/formatters/src/components/AccountAddressFormatter.tsx]: maybe then use `extend` and Platform.OS === 'android' so we can keep letter spacing on iOS since it works here correctly

File: suite-native/formatters/src/components/AccountAddressFormatter.tsx [hunk 2]
```diff
@@ -4,18 +4,34 @@ import { useSelector } from 'react-redux';
...
+    ...rest
+}: AccountAddressFormatterProps) => {
+    const { applyStyle } = useNativeStyles();
     const accountLabel = useSelector((state: AccountsRootState) =>
         selectAccountLabel(state, value),
     );
 
+    const baseAddressStyle = applyStyle(addressStyle);
+    const mergedAddressStyle = style
+        ? mergeNativeStyleObjects([style, baseAddressStyle])
```
Comment (Nodonisko) [inline suite-native/formatters/src/components/AccountAddressFormatter.tsx:36]: You may try just fix types of `Text` to `style?: NativeStyleObject | NativeStyleObject[];` so you can pass array of styles, it should work without any other changes. If not don't bother with that and use this solution.

File: suite-native/module-home/src/components/PortfolioGraphHeader.tsx [hunk 3]
```diff
@@ -39,7 +39,13 @@ const Balance = () => {
     const point = useAtomValue(selectedPointAtom);
 
     return (
-        <FiatAmountFormatter value={String(point.value)} variant="titleLarge" color="textDefault" />
+        <FiatAmountFormatter
+            value={String(`${point.value}`)}
```
Comment (Nodonisko) [inline suite-native/module-home/src/components/PortfolioGraphHeader.tsx]: Why it is wrapped both in upper ticks and String? String itself should be enough.

**Review by Nodonisko — APPROVED** [review]

File: suite-native/formatters/src/components/AccountAddressFormatter.tsx (hunk 2 above)
Comment (Nodonisko) [reply suite-native/formatters/src/components/AccountAddressFormatter.tsx:36]: Or maybe you can pass that array directly to `applyStyle([style, addressStyle])`

File: suite-native/module-home/src/components/PortfolioGraphHeader.tsx (hunk 3 above)
Comment (PeKne) [reply suite-native/module-home/src/components/PortfolioGraphHeader.tsx]: fixed

File: suite-native/formatters/src/components/AccountAddressFormatter.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/formatters/src/components/AccountAddressFormatter.tsx]: fixed

File: suite-native/formatters/src/components/AccountAddressFormatter.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/formatters/src/components/AccountAddressFormatter.tsx:36]: None of these solutions fixed the problem. Changing `Text `props to accept a list of styles did not help because the `AccountAddressFormatter` is extending the `Text` props. So instead of these three lines merging the style objects, I would have to add a check if the incoming style is an array or a single style object. 

The second soluting did not work because the `style` is a `NativeStyleObject` ( `applyStyle` already applied) and is not compatible as a `applyStyle` parameter.

For this reason, i left the original solution in place since it is only three extra lines of code.
