### PR TITLE
Ref/navigation tabs

### LINKED ISSUE #8242: Refactor navigators
Currently we have some weird logic in navigation in the mobile app. Since we use nested navigators, it's weird that we have `AccountDetail` in HomeStack, `TransactionDetail` and `AccountSettings` in RootStack.

- Refactor navigators so that account stack has account detail and account list
- TransactionDetail should also be in account list as an account namespace
- Account settings should be in account stack as well

There will be some problems with navigation handlers that should be addressed.

### LINKED ISSUE #8287: Receive - icons switch, receive address displayed without warning when switching between accounts
Steps to reproduce:
Have BTC and ETH assets in the app

1. Go to Receive and generate receive address, click Show address
2. Go to Home
3. Go my assets and click on ETH and Receive
4. Receive screen is displayed with revealed address - warning message is not displayed

Expected behaviour:
When user clicks on Receive the coin, address should be always hidden and the warning message is displayed before revealing
When user leaves the Receive screen without closing it by himself, we should reset it on our own - it means everytime user clicks on Receive on the menu, we should display screen with accounts where user would like to receive to

Icon switch:
1. Go to ETH and click Receive - reveal the address
2. Go to My assets and click on BTC and Receive
3. Receive screen is displayed directly with revealed address and the icon is ETH instead of BTC

Videos:
https://user-images.githubusercontent.com/84183817/234895003-24623735-8923-4c2d-9f72-d0e1c1e46a7f.MOV
https://user-images.githubusercontent.com/84183817/234895002-a3f4b6c4-ed20-4ff6-8442-207761ee093c.MP4

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/8242
Resolve https://github.com/trezor/trezor-suite/issues/8287

## Screenshots:

https://user-images.githubusercontent.com/36101761/235875083-457fff98-80fd-4a32-8bf7-f356463d2df8.mov

### CODE REVIEW

File: suite-native/app/src/navigation/RootStackNavigator.tsx [hunk 1]
```diff
@@ -39,29 +40,39 @@ export const RootStackNavigator = () => {
...
-            <RootStack.Screen
-                options={{ title: RootStackRoutes.TransactionDetail }}
-                name={RootStackRoutes.TransactionDetail}
-                component={TransactionDetailScreen}
-            />
-            <RootStack.Screen
-                name={RootStackRoutes.DevUtilsStack}
-                component={DevUtilsStackNavigator}
-            />
+            <RootStack.Group>
```
Comment (PeKne) [inline suite-native/app/src/navigation/RootStackNavigator.tsx]: I a `Group` has no parameter, it is IMO redundant. Remove it please.

File: suite-native/app/src/navigation/RootStackNavigator.tsx [hunk 2]
```diff
@@ -39,29 +40,39 @@ export const RootStackNavigator = () => {
...
+                    options={{ title: RootStackRoutes.AccountDetail }}
+                    name={RootStackRoutes.AccountDetail}
+                    component={AccountDetailScreen}
+                />
+                <RootStack.Screen
+                    name={RootStackRoutes.DevUtilsStack}
+                    component={DevUtilsStackNavigator}
+                />
+            </RootStack.Group>
+            <RootStack.Group>
```
Comment (PeKne) [inline suite-native/app/src/navigation/RootStackNavigator.tsx]: Same here.

File: suite-native/module-home/src/components/DashboardNavigationButtons.tsx [hunk 3]
```diff
@@ -28,18 +27,16 @@ export const DashboardNavigationButtons = () => {
...
-    };
-
     const handleImportAssets = () => {
         navigation.navigate(RootStackRoutes.AccountsImport, {
             screen: AccountsImportStackRoutes.SelectNetwork,
         });
     };
 
+    const handleReceive = () => {
+        navigation.navigate(RootStackRoutes.ReceiveModal, {});
```
Comment (PeKne) [inline suite-native/module-home/src/components/DashboardNavigationButtons.tsx:29]: nit: `{}` is IMO redundant.

File: suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx [hunk 4]
```diff
@@ -1,21 +1,31 @@
...
 import { AccountKey } from '@suite-common/wallet-types';
 import { EthereumTokenSymbol } from '@suite-native/ethereum-tokens';
 
-export const ReceiveAccountsScreen = ({
-    navigation,
-}: StackProps<SendReceiveStackParamList, SendReceiveStackRoutes.ReceiveAccounts>) => {
+export const ReceiveAccountsScreen = () => {
+    const navigation =
+        useNavigation<
+            StackToStackCompositeNavigationProps<
```
Comment (PeKne) [inline suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx]: You don't need `StackToStackComposite` in this case. You are navigating inside if the same stack. The `RootStackParamList` is redundant.

File: suite-native/navigation/src/navigators.ts [hunk 5]
```diff
@@ -42,15 +48,15 @@ export type SettingsStackParamList = {
     [SettingsStackRoutes.SettingsFAQ]: undefined;
 };
 
-export type SendReceiveStackParamList = {
-    [SendReceiveStackRoutes.ReceiveAccounts]: undefined;
-    [SendReceiveStackRoutes.Receive]: { accountKey: AccountKey; tokenSymbol?: TokenSymbol };
+export type ReceiveStackParamList = {
+    [ReceiveStackRoutes.ReceiveAccounts]: ReceiveAccountsParams;
```
Comment (PeKne) [inline suite-native/navigation/src/navigators.ts]: Why `ReceiveAccounts` need these parameters? You do not access them in `ReceiveAccountsScreen` IMO should be `undefined`.

File: suite-native/navigation/src/navigators.ts [hunk 6]
```diff
@@ -85,11 +91,16 @@ export type RootStackParamList = {
     [RootStackRoutes.AppTabs]: NavigatorScreenParams<AppTabsParamList>;
     [RootStackRoutes.Onboarding]: NavigatorScreenParams<AppTabsParamList>;
     [RootStackRoutes.AccountsImport]: NavigatorScreenParams<AccountsImportStackParamList>;
+    [RootStackRoutes.ReceiveModal]: ReceiveAccountsParams;
```
Comment (PeKne) [inline suite-native/navigation/src/navigators.ts:92]:
```suggestion
    [RootStackRoutes.ReceiveModal]: ReceiveAccountParams;
```

File: suite-native/receive/src/components/AccountReceive.tsx [hunk 7]
```diff
@@ -0,0 +1,75 @@
+import React, { useState } from 'react';
```
Comment (PeKne) [inline suite-native/receive/src/components/AccountReceive.tsx]: nit: I would rename this file as `ReceiveAccount.tsx` so it has same prefix as other files in this folder.

File: suite-native/transactions/src/components/TransactionsEmptyState.tsx [hunk 8]
```diff
@@ -36,8 +36,8 @@ export const TransactionsEmptyState = ({ accountKey }: { accountKey: string }) =
     const { applyStyle } = useNativeStyles();
 
     const handleReceive = () => {
-        navigation.navigate(AppTabsRoutes.SendReceiveStack, {
-            screen: SendReceiveStackRoutes.Receive,
+        navigation.navigate(AppTabsRoutes.ReceiveStack, {
+            screen: ReceiveStackRoutes.Receive,
```
Comment (PeKne) [inline suite-native/transactions/src/components/TransactionsEmptyState.tsx]: Should not this go to ReceiveModal? Not sure.

File: suite-native/app/src/navigation/RootStackNavigator.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/app/src/navigation/RootStackNavigator.tsx:43]: I completely missed this. The modal presentation is missing at the bottom. Will need slight change. Thanks

File: suite-native/app/src/navigation/AppTabNavigator.tsx [hunk 9]
```diff
@@ -18,18 +18,15 @@ export const AppTabNavigator = () => (
             initialRouteName={AppTabsRoutes.HomeStack}
             screenOptions={{
                 headerShown: false,
-                unmountOnBlur: false,
+                unmountOnBlur: true,
```
Comment (Nodonisko) [inline suite-native/app/src/navigation/AppTabNavigator.tsx:21]: Why?

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/app/src/navigation/AppTabNavigator.tsx (hunk 9 above)
Comment (juriczech) [reply suite-native/app/src/navigation/AppTabNavigator.tsx:21]: It was requested by product to always reset stacks on tab change. That's why there were errors on settings, receive screen and other stacks. I tested that this didn't bring any real performance problems

File: suite-native/transactions/src/components/TransactionsEmptyState.tsx (hunk 8 above)
Comment (juriczech) [reply suite-native/transactions/src/components/TransactionsEmptyState.tsx]: https://github.com/trezor/trezor-suite/pull/8316/commits/eaebbfb6a11e30414886e378d6cc6708f05b6ca5

File: suite-native/receive/src/components/AccountReceive.tsx (hunk 7 above)
Comment (juriczech) [reply suite-native/receive/src/components/AccountReceive.tsx]: https://github.com/trezor/trezor-suite/pull/8316/commits/eaebbfb6a11e30414886e378d6cc6708f05b6ca5

File: suite-native/navigation/src/navigators.ts (hunk 6 above)
Comment (juriczech) [reply suite-native/navigation/src/navigators.ts:92]: https://github.com/trezor/trezor-suite/pull/8316/commits/eaebbfb6a11e30414886e378d6cc6708f05b6ca5

File: suite-native/navigation/src/navigators.ts (hunk 5 above)
Comment (juriczech) [reply suite-native/navigation/src/navigators.ts]: https://github.com/trezor/trezor-suite/pull/8316/commits/eaebbfb6a11e30414886e378d6cc6708f05b6ca5

File: suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx (hunk 4 above)
Comment (juriczech) [reply suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx]: https://github.com/trezor/trezor-suite/pull/8316/commits/eaebbfb6a11e30414886e378d6cc6708f05b6ca5

File: suite-native/app/src/navigation/RootStackNavigator.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/app/src/navigation/RootStackNavigator.tsx]: https://github.com/trezor/trezor-suite/pull/8316/commits/eaebbfb6a11e30414886e378d6cc6708f05b6ca5

File: suite-native/app/src/navigation/RootStackNavigator.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/app/src/navigation/RootStackNavigator.tsx]: https://github.com/trezor/trezor-suite/pull/8316/commits/eaebbfb6a11e30414886e378d6cc6708f05b6ca5

File: suite-native/module-home/src/components/DashboardNavigationButtons.tsx (hunk 3 above)
Comment (juriczech) [reply suite-native/module-home/src/components/DashboardNavigationButtons.tsx:29]: No it's not. Since the param is not undefined but an object with properties that can be undefined

Comment (PeKne) [reply suite-native/module-home/src/components/DashboardNavigationButtons.tsx:29]: Then I would vote for making the whole object optional. So if you don't want to send any params, you send undefined (implicitly).

**Review by PeKne — APPROVED** [review]

**Review by Nodonisko — APPROVED** [review]
