### PR TITLE
fix(trading): slip-24

### LINKED ISSUE #22818: Trading - SLIP24 - signing error
`Transaction signing error: Unable to send transaction, missing data`

### PR DESCRIPTION
**Pull request by FreeWall**
## Description

- add purchase address to payment request
- skip slip24 if receive address is outside suite
- add slip24 as experimental feature

## Related Issue

Resolve #22818

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-payment-request&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-payment-request&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/trading-payment-request&lookback=7)

### CODE REVIEW

File: suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import { createThunk } from '@suite-common/redux-utils';
+import type { Network } from '@suite-common/wallet-config';
+import { GeneralPrecomposedTransactionFinal } from '@suite-common/wallet-types';
+import TrezorConnect from '@trezor/connect';
+
+import { TRADING_THUNK_PREFIX } from '../../constants';
+import { TradingSendRejectedProps } from '../../types';
+import { formatSlip24SendAmountByNetwork } from '../../utils/signature/signatureUtils';
+
+export const getPamyentRequestOutputs = createThunk<
```
Comment (matusbalascak) [inline suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts]:
```suggestion
export const getPaymentRequestOutputs = createThunk<
```

File: suite-common/trading/src/utils/signature/signatureUtils.ts [hunk 2]
```diff
@@ -52,25 +70,35 @@ export const tradingExchangeCreatePaymentRequest = ({
...
-    }).toString();
+    if (!sendNetworkData.network) {
+        return undefined;
+    }
+
+    const sendAmount = formatSlip24SendAmountByNetwork({
+        value: unitsToSubunits({
+            value: asAmountUnit(new BigNumber(sendStringAmount)),
+            symbol: sendNetworkSymbol,
+            ...(sendTokenDecimals ? { decimals: sendTokenDecimals } : undefined),
```
Comment (matusbalascak) [inline suite-common/trading/src/utils/signature/signatureUtils.ts]: erc20 tokens can have `0` decimals which would make this not work properly, it's better to check for `sendTokenDecimals !== undefined`

**Review by matusbalascak — COMMENTED** [review]
I don't really know what to test here, there's no info in the pull request nor in the issue itself, so just some nits from me.

File: suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts (hunk 1 above)
Comment (FreeWall) [reply suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts]: fixed

File: suite-common/trading/src/utils/signature/signatureUtils.ts (hunk 2 above)
Comment (FreeWall) [reply suite-common/trading/src/utils/signature/signatureUtils.ts]: fixed

**Comment by FreeWall** [comment]
removed slip24 from debug mode and added as experimental feature

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts [hunk 3]
```diff
@@ -125,9 +126,17 @@ export const useTradingExchangeForm = ({
         navigateToExchangeConfirm,
     } = useTradingNavigation(account);
 
-    const isDebug = useSelector(selectIsDebugModeActive);
+    // we consider this feature enabled unless disabled by message system
+    const isSlip24FeatureEnabled = useSelector(state =>
```
Comment (sherpaPSX) [inline packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts:131]: question: I see we have some selector files where selectors are defined (same as you did here). To be honest I prefer you way, but which way is correct with regard to our code standards?

Comment (FreeWall) [reply packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts:131]: I guess its the way we write this, I can see the same style everywhere else

Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts:131]: Ok, i just saw files like this `packages/suite/src/selectors`

**Comment by vytick** [comment]
@coderabbitai review

File: packages/suite/src/constants/suite/experimental.ts [hunk 4]
```diff
@@ -59,6 +60,11 @@ export const EXPERIMENTAL_FEATURES: Record<ExperimentalFeature, ExperimentalFeat
         title: { id: 'TR_EXPERIMENTAL_NFT_SECTION' },
         description: { id: 'TR_EXPERIMENTAL_NFT_SECTION_DESCRIPTION' },
     },
+    slip24: {
+        title: { id: 'TR_EXPERIMENTAL_SLIP24' },
+        description: { id: 'TR_EXPERIMENTAL_SLIP24_DESCRIPTION' },
+        isDisabled: ({ isDebug }) => !isDebug,
+    },
```
[the remark this answers is not in the document]
Comment (vytick) [reply packages/suite/src/constants/suite/experimental.ts:67]: this is intentional

File: suite-common/trading/src/thunks/common/__tests__/createPaymentRequestsThunk.test.ts [hunk 5]
```diff
@@ -4,14 +4,15 @@ import { CryptoId, ExchangeTradeSigned } from 'invity-api';
 import { createThunk } from '@suite-common/redux-utils';
 import { configureMockStore, extraDependenciesCommonMock } from '@suite-common/test-utils';
 import { Account, GeneralPrecomposedTransaction } from '@suite-common/wallet-types';
-import { PROTO } from '@trezor/connect';
+import TrezorConnect, { Address, PROTO } from '@trezor/connect';
+import { validatePath } from '@trezor/connect/src/utils/pathUtils';
```
[the remark this answers is not in the document]
Comment (vytick) [reply suite-common/trading/src/thunks/common/__tests__/createPaymentRequestsThunk.test.ts:9]: @FreeWall imo worth updating

File: suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+                            id: 'TR_PAYMENT_REQUESTS_ERROR',
+                        },
+                    });
+                }
+
+                outputs.push({
+                    amount: formatSlip24SendAmountByNetwork({ value: output.amount, network }),
+                    address: getAddress.payload.address,
+                });
+            }
```
[the remark this answers is not in the document]
Comment (vytick) [reply suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts:49]: can this happen @FreeWall ?

File: suite-common/trading/src/thunks/common/createPaymentRequestsThunk.ts [hunk 7]
```diff
@@ -64,51 +68,26 @@ export const createPaymentRequestsThunk = createThunk<
...
-                const receiveSlip44 = await tradingGetCoinSlip44(quote?.receive);
                 const receiveDisplaySymbol = selectTradingCoinSymbolByCryptoId(
                     getState(),
                     quote?.receive,
                 );
 
+                const receiveAccountKey = selectTradingExchangeReceiveAccountKey(getState());
+                const receiveAddress = selectTradingExchangeReceiveAddress(getState());
+                const receiveAccount = selectAccountByKey(getState(), receiveAccountKey);
+                const sendNetwork = quote?.send ? cryptoIdToNetwork(quote.send) : undefined;
```
Comment (vytick) [inline suite-common/trading/src/thunks/common/createPaymentRequestsThunk.ts]: if we change  cryptoIdToNetwork to accept undefined, we can simplify this to 

`const sendNetwork = cryptoIdToNetwork(quote.send)`

wdyt?

File: suite-common/trading/src/utils/signature/signatureUtils.ts [hunk 8]
```diff
@@ -1,33 +1,31 @@
...
-export const tradingGetCoinSlip44 = async (cryptoId: CryptoId | undefined) => {
-    if (!cryptoId) return;
+export const formatSlip24SendAmountByNetwork = ({
+    value,
+    network,
+}: {
+    value: string | number;
+    network: Network;
+}): string => {
+    const bytesLength = network.networkType === 'ethereum' ? 32 : 8;
```
Comment (vytick) [inline suite-common/trading/src/utils/signature/signatureUtils.ts:24]: can you please add comment why this is here?

File: suite-common/trading/src/utils/signature/signatureUtils.ts [hunk 9]
```diff
@@ -1,33 +1,31 @@
...
-import { cryptoIdToNetwork, cryptoIdToNetworkAndContractAddress } from '../../utils';
+import { cryptoIdToNetworkAndContractAddress } from '../../utils';
 
-export const tradingGetCoinSlip44 = async (cryptoId: CryptoId | undefined) => {
-    if (!cryptoId) return;
+export const formatSlip24SendAmountByNetwork = ({
+    value,
+    network,
+}: {
+    value: string | number;
```
Comment (vytick) [inline suite-common/trading/src/utils/signature/signatureUtils.ts:20]: should the number be here?

File: suite-common/wallet-utils/src/amountUtils.ts [hunk 10]
```diff
@@ -138,3 +138,26 @@ export const formatTokenAmount = (tokenTransfer: TokenTransfer) => {
...
 };
+
+type FormatBigNumberToLEParams = { value: BigNumber; bytesLength: number };
+
+/**
+ * Formats BigNumber to little-endian hex string of given byte length
+ */
+export const formatBigNumberToLE = (params: FormatBigNumberToLEParams): string => {
+    const paddingLength = params.bytesLength * 2;
+    let hexString = params.value.toString(16);
```
Comment (vytick) [inline suite-common/wallet-utils/src/amountUtils.ts:164]: apparently this might not work for negative nubers

File: suite-common/trading/src/utils/signature/signatureUtils.ts (hunk 8 above)
Comment (FreeWall) [reply suite-common/trading/src/utils/signature/signatureUtils.ts:24]: is "slip24 protocol" enough? I don't really know the real reason

File: suite-common/trading/src/utils/signature/signatureUtils.ts (hunk 9 above)
Comment (FreeWall) [reply suite-common/trading/src/utils/signature/signatureUtils.ts:20]: `output.amount` of composedLevels is `string | number`

File: suite-common/trading/src/thunks/common/__tests__/createPaymentRequestsThunk.test.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (FreeWall) [reply suite-common/trading/src/thunks/common/__tests__/createPaymentRequestsThunk.test.ts:9]: its not available via public export

File: suite-common/trading/src/thunks/common/createPaymentRequestsThunk.ts (hunk 7 above)
Comment (FreeWall) [reply suite-common/trading/src/thunks/common/createPaymentRequestsThunk.ts]: fixed https://github.com/trezor/trezor-suite/pull/22778/commits/0a0c7e07a01d60a7c30891faf630833244602092

File: suite-common/trading/src/utils/signature/signatureUtils.ts (hunk 8 above)
Comment (vytick) [reply suite-common/trading/src/utils/signature/signatureUtils.ts:24]: imo even that is better than nothing 👍

File: suite-common/wallet-utils/src/amountUtils.ts (hunk 10 above)
Comment (FreeWall) [reply suite-common/wallet-utils/src/amountUtils.ts:164]: reflected in https://github.com/trezor/trezor-suite/pull/22778/commits/1f8212892620462bb2c871c4eb3aa168f9420483

File: suite-common/trading/src/utils/signature/signatureUtils.ts (hunk 8 above)
Comment (FreeWall) [reply suite-common/trading/src/utils/signature/signatureUtils.ts:24]: fixed in https://github.com/trezor/trezor-suite/pull/22778/commits/a0dc81ffcd3f7d6c0715826c4723bc823ad5da40

File: suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (FreeWall) [reply suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts:49]: not sure about this, @adderpositive can you confirm this?

[the remark this answers is not in the document]
Comment (adderpositive) [reply suite-common/trading/src/thunks/common/getPaymentRequestOutputs.ts:49]: If I am not mistaken, there will never by both at the same time. Maybe skip cycle could be a great solution. I would verify it with @marekrjpolak

**Review by vytick — APPROVED** [review]
lgtm, good job!

**Comment by tomasklim** [comment]
Slip24 enabled in experimental. ETH <-> LTC also does not work. Do I have to change trading backend url? Screenshot 2026-01-31 at 10 26 01

**Comment by FreeWall** [comment]
@tomasklim backend servers are not configured for new slip24 signing mechanism yet

**Comment by vytick** [comment]
lets finish in another PR once we have server set up
