### PR TITLE
Ethereum staking fixes

### LINKED ISSUE #11716: Hide only rewards in ETH staking when below 0.1
Hide `Only rewards` part if unstaking minimum is not met
Screenshot 2024-03-25 at 9 34 54

### LINKED ISSUE #11717: Show Ethereum staking banners when user has ETH enabled
Now we show it only in case user has more than `0.1` ETH. Let's show it when `Ethereum` is enabled because user can have funds on CEX, in `WETH`, he can stake somewhere else or he just want to buy new eth to stake.

### LINKED ISSUE #11718: Staking in a nutshell days improvement
Use `Unstaking currently takes {x} days. Once completed, you can trade or send it.`
Screenshot 2024-03-25 at 9 38 49

### LINKED ISSUE #11757: Content: Learn more about staking link to KB
URL: https://trezor.io/learn/a/stake-ethereum-eth-in-trezor-suite

### LINKED ISSUE #11773: Unstaking: 'Other amount' fields empty
**Describe the bug**
Other amount offer a suggestion, but the field is not field

**Info:**

-   Suite Version: develop

**How to reproduce**
* Click on unstake

**Expected behavior**
Fields to be prefilled

**Screenshots**

https://github.com/trezor/trezor-suite/assets/216917/6780b268-298b-4199-861a-4328290a1c4e

### PR DESCRIPTION
**Pull request by tomasklim**
## Description + issue + screenshot

Closes https://github.com/trezor/trezor-suite/issues/11773
All option chosen by default
Closes https://github.com/trezor/trezor-suite/issues/11716
Only rewards is hidden when less than 0.1
Screenshot 2024-03-27 at 11 42 55

-------

Closes https://github.com/trezor/trezor-suite/issues/11757
KB article
Screenshot 2024-03-27 at 11 51 20

-------

Resolves https://satoshilabs.slack.com/archives/C0543DJBK0C/p1711376966480799?thread_ts=1708498757.748759&cid=C0543DJBK0C
Managed to Maintained
Screenshot 2024-03-27 at 11 53 19

-------
Closes https://github.com/trezor/trezor-suite/issues/11718
Dynamic value in modal
Screenshot 2024-03-27 at 12 00 53

-------
Fixes gap between banners 
Closes https://github.com/trezor/trezor-suite/issues/11717
Show banner in account even though user does not have unstaking minimum
Screenshot 2024-03-27 at 12 13 25

----

Closes https://github.com/trezor/trezor-suite/issues/11717
Show banner on dashboard even though user does not have unstaking minimum
Screenshot 2024-03-27 at 12 16 54

---
Resolves https://satoshilabs.slack.com/archives/C0543DJBK0C/p1711441444731379
Banner on dashboard is not visible after clicking on `Maybe later`

https://github.com/trezor/trezor-suite/assets/33235762/1aec2477-03e1-4ff5-9c0f-935c515e9a1f

---

Dynamic apy does not change from backup to actual when loading
Screenshot 2024-03-31 at 14 49 33

---

Hide fiat value of testnet
Screenshot 2024-03-31 at 15 17 56

--- 

TODO CREATE CONNECT ISSUE:

Fetch error of token definitions when staking

has to be done in connect, not sure how to fix it now

Screenshot 2024-03-31 at 15 23 01

it thinks that it is token but it is not

### CODE REVIEW

File: packages/suite/src/hooks/suite/useDaysTo.ts [hunk 1]
```diff
@@ -4,20 +4,30 @@ import {
...
     const stakeTxs = useSelector(state =>
         selectAccountStakeTransactions(state, selectedAccountKey || ''),
     );
+
     const daysToAddToPool = useMemo(() => {
+        if (
+            validatorsQueue?.validatorAddingDelay === undefined ||
+            validatorsQueue?.validatorActivationTime === undefined ||
+            Number.isNaN(validatorsQueue?.validatorAddingDelay) ||
+            Number.isNaN(validatorsQueue?.validatorActivationTime)
```
Comment (tomasklim) [inline packages/suite/src/hooks/suite/useDaysTo.ts]: Remove those `isNaN`s

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/StakingDashboard.tsx [hunk 2]
```diff
@@ -39,11 +44,18 @@ const FlexRow = styled.div`
...
+
+    const ethApy = useSelector(state => selectPoolStatsApyData(state, account?.symbol));
+    const nextRewardPayout = useSelector(state =>
+        selectPoolStatsNextRewardPayout(state, account?.symbol),
+    );
+
     const { daysToAddToPool, daysToUnstake } = useDaysTo({
         selectedAccountKey: account?.key ?? '',
-        validatorsQueue,
+        validatorsQueue: data || {},
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/StakingDashboard.tsx]: just `data`

File: suite-common/wallet-core/src/stake/stakeThunks.ts [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+
+const EVERSTAKE_ENDPOINT_PREFIX = {
+    eth: 'https://eth-api-b2c.everstake.one/api/v1',
+    thol: 'https://eth-api-b2c-stage.everstake.one/api/v1',
+};
+
+const EVERSTAKE_ENDPOINT_TYPES = {
+    poolStats: 'stats',
+    validatorsQueue: 'validators/queue',
+};
```
Comment (tomasklim) [inline suite-common/wallet-core/src/stake/stakeThunks.ts]: Move this somewhere

File: suite-common/wallet-core/src/stake/stakeThunks.ts [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+
+        const ethereumBasedNetworksWithStaking = enabledNetworks.filter(
+            networkSymbol =>
+                getNetworkType(networkSymbol) === 'ethereum' &&
+                getNetworkFeatures(networkSymbol).includes('staking'),
+        ) as Array<SupportedNetworkSymbol>;
+
+        const endpointTypes = Object.keys(EVERSTAKE_ENDPOINT_TYPES) as Array<
+            keyof typeof EVERSTAKE_ENDPOINT_TYPES
+        >;
```
Comment (tomasklim) [inline suite-common/wallet-core/src/stake/stakeThunks.ts]: import it from somewhere

File: packages/urls/src/urls.ts [hunk 5]
```diff
@@ -61,6 +61,8 @@ export const HELP_CENTER_ZERO_VALUE_ATTACKS =
 export const HELP_CENTER_LABELING = 'https://trezor.io/learn/a/labels-in-trezor-suite-app';
 export const HELP_CENTER_DEVICE_AUTHENTICATION =
     'https://trezor.io/learn/a/trezor-safe-3-authentication-check';
+export const HELP_CENTER_ETH_STAKING =
+    'https://trezor.io/learn/a/stake-ethereum-eth-in-trezor-suite';
```
Comment (StanCheb) [inline packages/urls/src/urls.ts:65]: Знімок екрана 2024-04-01 о 12 17 48

Comment (sime) [reply packages/urls/src/urls.ts:65]: It's not live yet.

File: packages/suite/src/hooks/wallet/useUnstakeEthForm.ts [hunk 6]
```diff
@@ -214,6 +215,7 @@ export const useUnstakeEthForm = ({
                 shouldDirty: true,
                 shouldValidate: true,
             });
+            console.log('cau cau', amount);
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/wallet/useUnstakeEthForm.ts]: Čau!

File: packages/suite/src/hooks/suite/useDaysTo.ts [hunk 7]
```diff
@@ -4,20 +4,28 @@ import {
...
 
 const secondsToDays = (seconds: number) => Math.round(seconds / 60 / 60 / 24);
 
 interface UseDaysToParams {
-    validatorsQueue: ValidatorsQueueState;
+    validatorsQueue?: ValidatorsQueue;
     selectedAccountKey: string;
 }
 
 export const useDaysTo = ({ selectedAccountKey, validatorsQueue }: UseDaysToParams) => {
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/suite/useDaysTo.ts]: optional: split to 3 non-hook pure functions

File: packages/suite/src/utils/suite/stake.ts [hunk 8]
```diff
@@ -464,5 +465,10 @@ export const getStakeTxGasLimit = async ({
     }
 };
 
-export const getUnstakingPeriod = (validatorWithdrawTime: number) =>
-    Math.round(validatorWithdrawTime / 60 / 60 / 24);
+export const getUnstakingPeriod = (validatorWithdrawTime?: number) => {
```
Comment (peter-sanderson) [inline packages/suite/src/utils/suite/stake.ts]: validatorWithdrawTimeInSeconds

Comment (peter-sanderson) [reply packages/suite/src/utils/suite/stake.ts]: getUnstakingPeriod -> getUnstakingPeriodInDays

File: suite-common/wallet-core/src/stake/stakeSelectors.ts [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+
+export const selectEverstakeData = (
+    state: StakeRootState,
+    networkSymbol: NetworkSymbol,
+    endpointType: 'poolStats' | 'validatorsQueue',
+) => state.wallet.stake?.data?.[networkSymbol]?.[endpointType];
+
+export const selectPoolStatsApyData = (state: StakeRootState, networkSymbol?: NetworkSymbol) => {
+    if (!networkSymbol) {
+        throw new Error('Missing network symbol');
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/stake/stakeSelectors.ts]: not needed there is fallback

File: suite-common/wallet-core/src/stake/stakeSelectors.ts [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+    }
+
+    return state.wallet.stake?.data?.[networkSymbol]?.poolStats.data.ethApy || BACKUP_ETH_APY;
+};
+
+export const selectPoolStatsNextRewardPayout = (
+    state: StakeRootState,
+    networkSymbol?: NetworkSymbol,
+) => {
+    if (!networkSymbol) {
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/stake/stakeSelectors.ts:23]: not needed return indefined

File: suite-common/wallet-core/src/stake/stakeSelectors.ts [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+        throw new Error('Missing network symbol');
+    }
+
+    return state.wallet.stake?.data?.[networkSymbol]?.poolStats.data?.nextRewardPayout;
+};
+
+export const selectValidatorsQueueData = (state: StakeRootState, networkSymbol?: NetworkSymbol) => {
+    if (!networkSymbol) {
+        throw new Error('Missing network symbol');
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/stake/stakeSelectors.ts]: return undefined,

File: suite-common/wallet-core/src/stake/stakeSelectors.ts [hunk 12]
```diff
@@ -0,0 +1,45 @@
...
+    }
+
+    return state.wallet.stake?.data?.[networkSymbol]?.validatorsQueue.data || {};
+};
+
+export const selectValidatorsQueue = (state: StakeRootState, networkSymbol?: NetworkSymbol) => {
+    if (!networkSymbol) {
+        throw new Error('Missing network symbol');
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/stake/stakeSelectors.ts]: return undefined

File: packages/suite/src/hooks/suite/useDaysTo.ts (hunk 7 above)
Comment (tomasklim) [reply packages/suite/src/hooks/suite/useDaysTo.ts]: 82dadfc79a291941d75676190c23fbbf2dbe84bd

File: packages/suite/src/utils/suite/stake.ts [hunk 13]
```diff
@@ -460,3 +472,75 @@ export const getStakeTxGasLimit = async ({
...
+
+    const lastTx = unstakeTxs[0];
+
+    if (!lastTx?.blockTime) return 1;
+
+    const now = Math.floor(Date.now() / 1000);
+    const secondsToWait = lastTx.blockTime + validatorsQueue.validatorWithdrawTime - now;
+    const daysToWait = secondsToDays(secondsToWait);
+
+    return daysToWait <= 0 ? 1 : daysToWait;
```
Comment (peter-sanderson) [inline packages/suite/src/utils/suite/stake.ts:531]: nit: Not sure, but I think that this  can be done (more elegantly maybe?) by `Math.max(1, daysToWait)`?

File: packages/suite/src/utils/suite/stake.ts [hunk 14]
```diff
@@ -460,3 +472,75 @@ export const getStakeTxGasLimit = async ({
...
+        validatorsQueue?.validatorActivationTime === undefined
+    ) {
+        return undefined;
+    }
+
+    const lastTx = stakeTxs[0];
+
+    if (!lastTx?.blockTime) return 1;
+
+    const sevenDays = 7 * 24 * 60 * 60;
```
Comment (peter-sanderson) [inline packages/suite/src/utils/suite/stake.ts]: This can be extracted to a const out of the function scope:

Also please lets name it `const SEVEN_DAYS_IN_SECONDS`

File: packages/suite/src/utils/suite/stake.ts [hunk 15]
```diff
@@ -460,3 +472,75 @@ export const getStakeTxGasLimit = async ({
         };
     }
 };
+
+export const getUnstakingPeriodInDays = (validatorWithdrawTimeInSeconds?: number) => {
+    if (!validatorWithdrawTimeInSeconds) {
```
Comment (peter-sanderson) [inline packages/suite/src/utils/suite/stake.ts]: this can be both `0` and `undefined` is it intended to pass this condition in both cases?

File: packages/suite/src/utils/suite/stake.ts [hunk 16]
```diff
@@ -460,3 +472,75 @@ export const getStakeTxGasLimit = async ({
...
+        return UNSTAKING_ETH_PERIOD;
+    }
+
+    return Math.round(validatorWithdrawTimeInSeconds / 60 / 60 / 24);
```
Comment (peter-sanderson) [inline packages/suite/src/utils/suite/stake.ts]:
```suggestion
    return secondsToDays(validatorWithdrawTimeInSeconds);
```

File: packages/suite/src/utils/suite/stake.ts [hunk 17]
```diff
@@ -460,3 +472,75 @@ export const getStakeTxGasLimit = async ({
...
+    unstakeTxs: WalletAccountTransaction[],
+    validatorsQueue?: ValidatorsQueue,
+) => {
+    if (validatorsQueue?.validatorWithdrawTime === undefined) {
+        return undefined;
+    }
+
+    const lastTx = unstakeTxs[0];
+
+    if (!lastTx?.blockTime) return 1;
```
Comment (peter-sanderson) [inline packages/suite/src/utils/suite/stake.ts:525]: this can be both undefined and (I assume `0`) is it intentional to pass this as `0`?

File: packages/suite/src/utils/suite/stake.ts (hunk 15 above)
Comment (tomasklim) [reply packages/suite/src/utils/suite/stake.ts]: 17a49b68d6ccfd6fdac64509f574d96be9480573

File: packages/suite/src/utils/suite/stake.ts (hunk 14 above)
Comment (tomasklim) [reply packages/suite/src/utils/suite/stake.ts]: 01fcab5e90501501990bc3dfeed93ed268d7e0e3

File: packages/suite/src/utils/suite/stake.ts (hunk 16 above)
Comment (tomasklim) [reply packages/suite/src/utils/suite/stake.ts]: 01fcab5e90501501990bc3dfeed93ed268d7e0e3

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/utils/suite/stake.ts (hunk 17 above)
Comment (tomasklim) [reply packages/suite/src/utils/suite/stake.ts:525]: You are right, but in this case I think blockTime cannot be `0`
