### PR TITLE
fix(suite-native): manage Electrum connection based on app state

### LINKED ISSUE #26432: Mobile Suite crashes after several minutes in background when Electrum server is configured
Easily reproducible on iOS since it's quite aggressive in suspending the app after it goes to background.

### Steps to reproduce

1. Start the iOS mobile Suite app and finish onboarding.
2. Add a Bitcoin account to Portfolio Tracker.
3. Configure an Electrum backend in _Settings_ 👉 _Advanced_.
4. Return to dashboard and refresh the balance.
5. Lock your iPhone and wait at least 2 minutes.
6. The app crashes when you unlock your iPhone.

### DEV notes

It seems the crash is caused by `ElectrumClient` trying to keep the Electrum TCP connection alive. However, once the app goes to background, the OS suspends it and most likely closes the TCP connection. That's why later `JsonRpcClient#send` [fails](https://satoshilabs.sentry.io/issues/7204095437/?project=4504214699245568) and crashes the app.

### PR DESCRIPTION
**Pull request by yanascz**
`ElectrumClient` tries to keep its server connection alive, which causes issues when the mobile app is moved to the background. Since the app is eventually suspended and the connection closed, the app later crashes when it tries to use an already closed connection. So we need to manage the connection based on the app state.

## Related Issue

Resolve #26432

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/electrum-backend-in-background&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/electrum-backend-in-background&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/electrum-backend-in-background&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Account metadata,google - watches files over time" | 🙋 manual |
| Quarantine test: "Account metadata,dropbox - watches files over time" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-07T13:16:49.207Z • 7 test(s) total_

<details><summary>Trezor Suite (desktop) — 4 test(s)</summary>

| Test | Type |
|------|------|
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-07T13:15:07.459Z • 4 test(s) total_

### CODE REVIEW

**Review by marekrjpolak — APPROVED** [review]

File: suite-native/blockchain/src/useBlockchainConnectionManager.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+const symbol: NetworkSymbol = 'btc';
+
+// ElectrumClient tries to keep its server connection alive, which causes issues when the mobile
+// app is moved to the background. Since the app is eventually suspended and the connection closed,
+// the app later crashes when it tries to use an already closed connection. So we need to manage
+// the connection based on the app state.
+export const useBlockchainConnectionManager = () => {
+    const dispatch = useDispatch();
+
+    const {
```
Comment (PeKne) [inline suite-native/blockchain/src/useBlockchainConnectionManager.ts]: nit: Could you create a specific selector for this? 

e.g

`selectSelectedNetworkBlockchain`

File: suite-native/app/src/hooks/useGlobalHooks.tsx [hunk 2]
```diff
@@ -19,6 +20,7 @@ import { useConnectPopupNavigation } from '@suite-native/module-connect-popup';
 export const useGlobalHooks = () => {
     const device = useSelector(selectSelectedDevice);
 
+    useBlockchainConnectionManager();
```
Comment (PeKne) [inline suite-native/app/src/hooks/useGlobalHooks.tsx:23]: nit: could you please change the naming so it is clear that it is relevant only for the custom backends?

**Review by PeKne — APPROVED** [review]

File: suite-native/blockchain/src/useBlockchainConnectionManager.ts (hunk 1 above)
Comment (yanascz) [reply suite-native/blockchain/src/useBlockchainConnectionManager.ts]: Will use `selectBlockchainBackendType`.

File: suite-native/app/src/hooks/useGlobalHooks.tsx (hunk 2 above)
Comment (yanascz) [reply suite-native/app/src/hooks/useGlobalHooks.tsx:23]: As discussed in person, I believe the current naming is correct. The fact the only Electrum backends are currently managed is an implementation detail.

**Review by PeKne — APPROVED** [review]
