### PR TITLE
fix(suite): fix that you need to click twice to access an account wit…

### LINKED ISSUE #20668: Cannot move from tokens tab in one account to another account without tokens
**Describe the bug**
You cannot traverse directly from one account's tokens tab to another account that does not have tokens available.

https://github.com/user-attachments/assets/1ef279ab-8cbd-4190-ac8f-691ebf31220b

**Info:**
- Suite version: desktop 25.8.1 (c9e29dcb0c730bd79daadcbbb7db11397298b273)
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.8.1 Chrome/138.0.7204.97 Electron/37.2.0 Safari/537.36
- OS: Linux x86_64 (Screen: 2560x1440)
- Device: Trezor T3T1 2.9.0 universal (revision a09e6f04d4204607d821d9b742dcf7ffe9c4e2f5)
- Transport: BridgeTransport 3.1.0

**How to reproduce**
1. Go to one account with tokens available.
2. Click on the tokens tab.
3. Switch to another account that does not have tokens.
4. Notice you cannot traverse directly between these accounts via the tokens tab.

**Expected behavior**
You should be able to move directly from one account's tokens tab to another account, even if the second account does not have tokens available.

### PR DESCRIPTION
**Pull request by vojtatranta**
…hout tokens

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20668

## Screenshots:

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=20668-cannot-switch-tokens-tab&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=20668-cannot-switch-tokens-tab&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/tokens/index.tsx [hunk 1]
```diff
@@ -17,15 +19,17 @@ export const Tokens = () => {
...
     const selectedAccount = useSelector(state => state.wallet.selectedAccount);
     const dispatch = useDispatch();
+    const routeName = useSelector(selectRouteName);
 
     useEffect(() => {
         if (
             selectedAccount.status === 'loaded' &&
-            !selectedAccount.network?.features.includes('tokens')
+            !hasNetworkFeatures(selectedAccount.account, 'tokens') &&
+            routeName !== 'wallet-index'
```
Comment (vojtatranta) [inline packages/suite/src/views/wallet/tokens/index.tsx:28]: this fixes the issue, but the problem now is that there flashes "no data" for a page of a coin that doesn't have tokens page. But I guess that's fixable

**Comment by vojtatranta** [comment]
@Ondra-Zik-SL says that this problem is fixed, however, there is nwo this problem  https://github.com/trezor/trezor-suite/issues/20669

But that's a different issue

**Review by jvaclavik — APPROVED** [review]

**Comment by honzauher** [comment]
**QA OK**

Working as expected

**Info:**
 - Suite version: web 25.9.0 (8294c42c91912ba16c617f309d3ea19cb21ecb0d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.10 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport
