### PR TITLE
Store remembered device, discovery, accounts, txs in db

### LINKED ISSUE #745: Unit tests failing with Node.js v11+
I started using node v12 in my branch because I use some killer bleeding-edge features (`array.flat` lol) and jest wouldn't let me use it otherwise. But since then our unit tests started failing. The cause is change dsort algo (it is stable now 🎉) in the V8, shipped in Node.js v11.

I will fix the tests in my branch and after merging the branch we can bump the required node version to 12.

https://www.reddit.com/r/javascript/comments/9sb87m/chrome_70_and_nodejs_11_no_longer_sort_arrays/
https://github.com/nodejs/node/pull/22754#issuecomment-419551068

### PR DESCRIPTION
**Pull request by slowbackspace**
fix https://github.com/trezor/trezor-suite/issues/745
part of https://github.com/trezor/trezor-suite/issues/8 (web/electron covered)

- bumped node to v12
- fixed failing tests under node 12
- enabled es2019 syntax
- misc fixes

### CODE REVIEW

File: packages/suite-storage/src/native/index.ts [hunk 1]
```diff
@@ -251,6 +289,26 @@ class CommonDB<TDBStructure> {
         const items = await tx.store.getAll();
         return items;
```
Comment (szymonlesisz) [inline packages/suite-storage/src/native/index.ts]: `return tx.store.getAll()` ?

Comment (szymonlesisz) [reply packages/suite-storage/src/native/index.ts]: and the same in line 285 and 220

File: packages/suite-storage/src/web/index.ts [hunk 2]
```diff
@@ -290,6 +328,26 @@ class CommonDB<TDBStructure> {
         const items = await tx.store.getAll();
```
Comment (szymonlesisz) [inline packages/suite-storage/src/web/index.ts]: same as native/index:
return tx.store.getAll() ?

File: package.json [hunk 3]
```diff
@@ -5,7 +5,7 @@
     "repository": "https://github.com/trezor/trezor-suite.git",
     "license": "SEE LICENSE IN LICENSE.md",
     "engines": {
-        "node": "10.x"
+        "node": "12.x"
```
Comment (szymonlesisz) [inline package.json]: does it mean that i will not be able to run suite with LTS node@10 ?

File: packages/suite-storage/src/web/index.ts [hunk 4]
```diff
@@ -7,33 +7,41 @@ import {
...
     version!: number;
     db!: IDBPDatabase<TDBStructure> | null;
     broadcastChannel!: BroadcastChannel;
     onUpgrade!: (
-        db: IDBPDatabase<TDBStructure>,
-        oldVersion: number,
-        newVersion: number | null,
-        transaction: any
-    ) => void;
+        db: OnUpgradeProps<TDBStructure>['db'],
```
Comment (szymonlesisz) [inline packages/suite-storage/src/web/index.ts]: wouldn't be cleaner to declare this function once?
Since you are using it here and then the same declaration in constructor?

File: packages/suite/src/middlewares/wallet/storageMiddleware.ts [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+        case TRANSACTION.REMOVE:
+            storageActions.removeAccountTransactions(action.account);
+            break;
+
+        case DISCOVERY.UPDATE:
+        case DISCOVERY.INTERRUPT:
+        case DISCOVERY.STOP:
+        case DISCOVERY.COMPLETE: {
+            // TODO: explore better way to update discovery only
+            const device = api.getState().devices.find(d => d.state === action.payload.deviceState);
```
Comment (szymonlesisz) [inline packages/suite/src/middlewares/wallet/storageMiddleware.ts]: you can use `getState().suite.device` instead, discovery is designed to run only on currently selected device

Comment (szymonlesisz) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts]: wait :) i don't get why you are saving device instead of discovery?

Comment (szymonlesisz) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts]: `rememberDevice` should be triggered from `SUITE.REMEMBER_DEVICE`, right?

Comment (szymonlesisz) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts]: + additionaly device should be updated after DEVICE.UPDATE as well, for example changing label/FW/pin/passphrase settings
