### PR TITLE
fix(suite): dont fetch graph unless outdated

### LINKED ISSUE #21188: Cardano: graph in account is always refetched even without change of data
It applies for all networks but Cardano is the most problematic one in case of cost of backend.

- [ ] Everytime I visit account, graph data are refetched. This should not happen without change.

Image

Image

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

I changed the logic for selecting accounts that trigger a graph refetch. Graph transactions are now compared against total account transactions and only if there's a difference, graph is refetched. This also works for new accounts thus `newAccountsOnly` parameter doesn't make sense anymore.

## Related Issue

Resolve #21188

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/graph-refetching&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/graph-refetching&lookback=7)

### CODE REVIEW

File: packages/blockchain-link-types/src/common.ts [hunk 1]
```diff
@@ -125,6 +125,7 @@ export type FiatRatesBySymbol = {
 export interface AccountBalanceHistory {
     time: number;
     txs: number;
+    txids?: string[];
```
Comment (cermakjiri) [inline packages/blockchain-link-types/src/common.ts]: Is it used anywhere?

File: packages/suite/src/actions/wallet/graphActions.ts [hunk 2]
```diff
@@ -159,26 +168,45 @@ export const updateGraphData = createThunk<
...
+
+                return [key, txCount];
+            }),
+        );
+
+        const accountsToFetch = supportedAccounts.filter(account => {
+            const txCount = graphTxCountByAccount.get(account.key) ?? 0;
+
+            return txCount !== account.history.total;
+        });
```
Comment (cermakjiri) [inline packages/suite/src/actions/wallet/graphActions.ts:194]: Easily readable 👍 

Would it make sense to move these functions to selector so it's being memoized?

**Review by cermakjiri — APPROVED** [review]

**Review by izmy — APPROVED** [review]

File: packages/blockchain-link-types/src/common.ts (hunk 1 above)
Comment (matusbalascak) [reply packages/blockchain-link-types/src/common.ts]: No actually, at first I was using this to find the latest transaction but then I realized it's only available on Cardano network so I'll delete it.

File: packages/suite/src/actions/wallet/graphActions.ts [hunk 3]
```diff
@@ -143,12 +152,12 @@ export const fetchAccountGraphData =
 
 export const updateGraphData = createThunk<
     void,
-    { accounts: Account[]; newAccountsOnly?: boolean; abortSignal?: AbortSignal },
```
Comment (TomasBoda) [inline packages/suite/src/actions/wallet/graphActions.ts:146]: You removed the `newAccountsOnly` parameter but it is still used in `packages/suite/src/hooks/suite/useGraph.ts` in the passed `options` parameter. Can you please check it and remove it?

**Review by TomasBoda — APPROVED** [review]
LGTM

File: packages/suite/src/actions/wallet/graphActions.ts (hunk 3 above)
Comment (matusbalascak) [reply packages/suite/src/actions/wallet/graphActions.ts:146]: How was typescript not complaining about this 🤔  Good point tho, thanks!
