### PR TITLE
fix(suite): disable trading button when balance is insufficient

### LINKED ISSUE #14927: Trading - disable trade buttons when they should not be active
Related to [#15650](https://github.com/trezor/trezor-suite/issues/15650) and [#14928](https://github.com/trezor/trezor-suite/issues/14928). Buttons are not disabled after 1 click or not disabled when they should be disabled

Comparator allows you to proceed with a swap without funds on the account 

https://github.com/user-attachments/assets/5f1360ed-43f4-413b-ac5c-09efd461535f

### LINKED ISSUE #14928: Trading - you are able to sell funds you don't have
https://github.com/user-attachments/assets/db20e645-5e73-4e0d-a19f-a481860f9d2f

### PR DESCRIPTION
**Pull request by izmy**
## Description

Added a balance check to properly disable the trade button when the account has insufficient funds.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14927
Resolve https://github.com/trezor/trezor-suite/issues/14928

## Video:

https://github.com/user-attachments/assets/ef387f27-fef0-47ad-8615-2646bbd2f078

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-form-disabled-button-validation&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-form-disabled-button-validation&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/trading-form-disabled-button-validation&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/send/sendFormCardanoThunks.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ export const composeCardanoTransactionFeeLevelsThunk = createThunk<
     ComposeTransactionThunkArguments,
     { rejectValue: ComposeFeeLevelsError }
 >(
-    `${SEND_MODULE_PREFIX}/composeBitcoinTransactionFeeLevelsThunk`,
+    `${SEND_MODULE_PREFIX}/composeCardanoTransactionFeeLevelsThunk`,
```
Comment (adderpositive) [inline suite-common/wallet-core/src/send/sendFormCardanoThunks.ts:32]: 👌

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts [hunk 2]
```diff
@@ -381,3 +383,53 @@ export const getTradeTypeByRoute = (
...
 };
+
+type AmountValidationResult =
+    | { type: 'ok' }
+    | { type: 'not_enough' }
+    | { type: 'reserve'; reserve: string };
+
+interface GetAmountValidationResultParams {
+    amount: string | undefined;
+    tokenAddress?: string | null;
```
Comment (adderpositive) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]: Nit:
It would be more precise to use `contractAddress` I guess.

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts [hunk 3]
```diff
@@ -381,3 +383,53 @@ export const getTradeTypeByRoute = (
...
+    account: Account;
+    areSatsUsed?: boolean;
+}
+
+export const getAmountValidationResult = ({
```
Comment (adderpositive) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]: Add test please

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts [hunk 4]
```diff
@@ -381,3 +383,53 @@ export const getTradeTypeByRoute = (
...
+            return { type: 'reserve', reserve };
+        }
+
+        return { type: 'not_enough' };
+    }
+
+    return { type: 'ok' };
+};
+
+export const isAmountTooHigh = (params: GetAmountValidationResultParams): boolean =>
```
Comment (adderpositive) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]: Also add test 🫣😍🙏

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 5]
```diff
@@ -105,6 +108,27 @@ export const TradingFormOffer = () => {
         await goToOffers();
     };
 
+    const amount = isTradingSellContext(context)
+        ? (context.quotesRequest?.cryptoStringAmount ?? '0')
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: Using the `amount` from `formState.outputs[0]` will be more accurate.

Comment (adderpositive) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: And what about `isTradingExchangeContext(context)`, is will return `0`, if I am not mistaken

File: packages/suite/src/utils/suite/validation.ts [hunk 6]
```diff
@@ -14,6 +12,8 @@ import { BigNumber } from '@trezor/utils/src/bigNumber';
 
 import { TranslationFunction } from 'src/hooks/suite/useTranslation';
 
+import { getAmountValidationResult } from '../wallet/trading/tradingUtils';
```
Comment (adderpositive) [inline packages/suite/src/utils/suite/validation.ts]: Absolute path

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts (hunk 3 above)
Comment (adderpositive) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]: Can you move it from `tradingUtils`? It doesn't have only a trading signature. It is used in `validateReserveOrBalance` and it is used also in Send and Staking

**Review by adderpositive — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 7]
```diff
@@ -108,23 +108,28 @@ export const TradingFormOffer = () => {
...
     let tokenAddress: TokenAddress | undefined;
     let areSatsUsed = false;
 
     if (isTradingSellContext(context) || isTradingExchangeContext(context)) {
-        const { shouldSendInSats, getValues } = context;
-        const { outputs } = getValues();
+        const { shouldSendInSats, getValues, feeInfo } = context;
+        const { outputs, selectedFee } = getValues();
+
+        console.log(feeInfo, selectedFee);
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: Delete console.log

File: packages/suite/src/utils/suite/validation.ts [hunk 8]
```diff
@@ -197,7 +196,7 @@ export const validateReserveOrBalance =
             amount: value,
             account,
             areSatsUsed,
-            tokenAddress,
+            contractAddress: tokenAddress,
```
Comment (adderpositive) [inline packages/suite/src/utils/suite/validation.ts]: I would also consider renaming tokenAddress, but that is beyond the scope of this change.

File: suite-common/wallet-utils/src/__tests__/sendFormUtils.test.ts [hunk 9]
```diff
@@ -406,4 +408,121 @@ describe('sendForm utils', () => {
         expect(excludedUtxos[getUtxoOutpoint(lowAnonymityUtxo)]).toBe('low-anonymity');
         expect(excludedUtxos[getUtxoOutpoint(spendableUtxo)]).toBe(undefined);
     });
+
+    describe('getAmountValidationResult & isAmountTooHigh', () => {
```
Comment (adderpositive) [inline suite-common/wallet-utils/src/__tests__/sendFormUtils.test.ts]: This should be separated. In my opinion, it is not a unit test. Also, it would be nice to follow the convention of test descriptions (big kudos to @jbazant 🥳).

```ts
describe('getAmountValidationResult', () => {
   describe('should test bitcoin without tokens', () => {
      it('when amount is within available balance', () => {
        // test
     })
  })
})
```

**Review by adderpositive — APPROVED** [review]
I have found only not-blocking nitpicks. LGTM

File: suite-common/wallet-utils/src/__tests__/sendFormUtils.test.ts (hunk 9 above)
Comment (adderpositive) [reply suite-common/wallet-utils/src/__tests__/sendFormUtils.test.ts]: There is also a failing test.

File: packages/suite/src/utils/suite/validation.ts (hunk 8 above)
Comment (izmy) [reply packages/suite/src/utils/suite/validation.ts]: renamed

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx (hunk 7 above)
Comment (izmy) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: deleted

File: suite-common/wallet-utils/src/__tests__/sendFormUtils.test.ts (hunk 9 above)
Comment (izmy) [reply suite-common/wallet-utils/src/__tests__/sendFormUtils.test.ts]: changed
