### PR TITLE
fix(suite-native): prevent biometrics request deadlock on ios

### LINKED ISSUE #10647: Canceling FaceID to unlock the app "glitches" the FaceID and makes it unusable for the whole iPhone
**Describe the bug**
When you fail the FaceID scan and then cancel the "retry" of it, it somehow "glitches" the FaceID but not only for the app but for my whole phone. I was unable to use the FaceID to unlock my iPhones (15 for a couple of minutes, then it was OK but 11 just wouldn't work and I had to actually restart it to make it work again).

**Info:**

-   Mobile Suite Version: version/commit
-   OS: name, version

**How to reproduce**

1. Fail FaceID to unlock your app
2. Cancel the retry of the FaceID
3. FaceID in app starts "glitching"

**Expected behavior**
I think the cancelling of the FaceID should maybe close the app? 

**Screenshots**

https://github.com/trezor/trezor-suite/assets/48477147/8bab4688-63e9-4f24-bf57-d3d4ba865da1

### PR DESCRIPTION
**Pull request by vytick**
Cancel authentication in case user cancels the biometrics. 
Button is added to biometrics overlay to start it again when user wants to do that after canceling.

Resolve #10647

### CODE REVIEW

**Comment by juriczech** [comment]
Where is this design from? Also, it's not aligned properly. Can we avoid having a button here and adjust the flow so it's working automatically? It seems quite confusing that user would have to click on `Enable biometrics` as it's already enabled.

File: suite-native/biometrics/src/components/BiometricOverlay.tsx [hunk 1]
```diff
@@ -13,10 +16,26 @@ const overlayWrapperStyle = prepareNativeStyle(utils => ({
...
+        useIsBiometricsAuthenticationCanceled();
+
+    const handleReenable = () => {
+        // Setting this to true lets useBiometrics to ask for biometrics in case it was canceled by user before
+        // https://github.com/trezor/trezor-suite/issues/10647
+        setIsBiometricsAuthenticationCanceled(false);
+    };
 
     return (
         <Box style={applyStyle(overlayWrapperStyle)}>
```
Comment (juriczech) [inline suite-native/biometrics/src/components/BiometricOverlay.tsx:67]: Redundant box now. Please remove it and apply the styles to VStack so the content is centered.

File: suite-native/biometrics/src/components/BiometricOverlay.tsx [hunk 2]
```diff
@@ -13,10 +16,26 @@ const overlayWrapperStyle = prepareNativeStyle(utils => ({
...
     const { applyStyle } = useNativeStyles();
+    const { translate } = useTranslate();
+    const { isBiometricsAuthenticationCanceled, setIsBiometricsAuthenticationCanceled } =
+        useIsBiometricsAuthenticationCanceled();
+
+    const handleReenable = () => {
+        // Setting this to true lets useBiometrics to ask for biometrics in case it was canceled by user before
+        // https://github.com/trezor/trezor-suite/issues/10647
+        setIsBiometricsAuthenticationCanceled(false);
+    };
```
Comment (juriczech) [inline suite-native/biometrics/src/components/BiometricOverlay.tsx:63]: Can this be done automatically in the useBiometrics hook?

**Review by juriczech — CHANGES_REQUESTED** [review]

File: suite-native/biometrics/src/components/BiometricOverlay.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/biometrics/src/components/BiometricOverlay.tsx:63]: The problem now is neverending flow of biometrics auth requests. I needed to stop that. That can be done by catching `user_cancel` error and stopping auth. 

This button is the way to allow it again somehow. 

Only other way I came with would be adding a delay before the next auth. But how long? And how to reenable earlier? 

This is where the button comes handy, because it is up to user to resolve this, since he was the one canceling the auth previously by tapping the cancel button.

**Comment by vytick** [comment]
> Where is this design from? Also, it's not aligned properly. Can we avoid having a button here and adjust the flow so it's working automatically? It seems quite confusing that user would have to click on `Enable biometrics` as it's already enabled.

There is no design for this. The need for a button emerged from the solution found. Ideally the design wont be seen at all, but in case the user cancels biometrics, this at least works. I'll update the layout, I havent seen icon not being aligned correctly.

**Comment by vytick** [comment]
I've asked Sheny for some design once he is back.

**Comment by vytick** [comment]
We will use this design:
https://www.figma.com/file/RlWH784CRUIvooy8aq6XoR/Main-Flow?type=design&node-id=628-20028&mode=design

**Comment by vytick** [comment]
Design was checked by Kuba

File: suite-native/biometrics/src/components/BiometricOverlay.tsx [hunk 3]
```diff
@@ -11,12 +16,74 @@ const overlayWrapperStyle = prepareNativeStyle(utils => ({
     backgroundColor: utils.colors.backgroundTertiaryDefaultOnElevation0,
 }));
 
+const bottomWrapperStyle = prepareNativeStyle(() => ({
+    position: 'absolute',
+    bottom: 40,
+    left: 0,
+    right: 0,
+    alignItems: 'center',
+}));
```
Comment (juriczech) [inline suite-native/biometrics/src/components/BiometricOverlay.tsx]: Nit: I believe this is redundant and you can apply positioning styles to the `TouchableOpacity`

File: suite-native/biometrics/src/components/BiometricOverlay.tsx [hunk 4]
```diff
@@ -11,12 +16,74 @@ const overlayWrapperStyle = prepareNativeStyle(utils => ({
...
     return (
         <Box style={applyStyle(overlayWrapperStyle)}>
-            <Icon name="trezor" size="extraLarge" color="iconOnPrimary" />
+            <Icon name="trezor" size="extraLarge" color="iconDefault" />
+            {isBiometricsAuthenticationCanceled && (
+                <View style={applyStyle(bottomWrapperStyle)}>
+                    <TouchableOpacity onPress={handleReenable} style={applyStyle(touchAreaStyle)}>
+                        <BiometricsIcons
+                            isFacialEnabled={isFacialEnabled}
+                            isFingerprintEnabled={isFingerprintEnabled}
```
Comment (juriczech) [inline suite-native/biometrics/src/components/BiometricOverlay.tsx]: These could be extracted from the hook from inside the component

File: suite-native/biometrics/src/components/BiometricsIcons.tsx [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+    iconSize = ICON_SIZE_DEFAULT,
+    showShadow = false,
+}: BiometricsIconsProps) => {
+    const { applyStyle } = useNativeStyles();
+
+    const faceRecognitionIcon: IconName = Platform.OS === 'ios' ? 'faceId' : 'face';
+    const fingerprintIcon: IconName = Platform.OS === 'ios' ? 'touchId' : 'fingerprint';
+    const primaryIcon: IconName = isFingerprintEnabled ? fingerprintIcon : faceRecognitionIcon;
+
+    const iconWrapperSize = iconSize + 12 + 12;
```
Comment (juriczech) [inline suite-native/biometrics/src/components/BiometricsIcons.tsx]: nit: Please add const for this number so it's obvious why this number specifically

File: suite-native/biometrics/src/useBiometrics.tsx [hunk 6]
```diff
@@ -39,23 +42,44 @@ export const useBiometrics = () => {
...
+        setIsBiometricsAuthenticationCanceled,
     ]);
 
+    // This is to relaunch authentication if the user canceled it previously by a button
+    // and now wanted to reenable it.
+    useEffect(() => {
+        if (!isBiometricsAuthenticationCanceled) {
+            handleAuthentication();
+        }
+        // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (juriczech) [inline suite-native/biometrics/src/useBiometrics.tsx]: Please explain why this is necessary and why `handleAuthentication` is not included in deps list? If there is no valid reason, I'd prefer not to disable this rule.

**Review by juriczech — COMMENTED** [review]
Minor nits. Open to discussion. Good job 👏

File: suite-native/biometrics/src/components/BiometricOverlay.tsx (hunk 3 above)
Comment (vytick) [reply suite-native/biometrics/src/components/BiometricOverlay.tsx]: 492763e1d2

File: suite-native/biometrics/src/components/BiometricOverlay.tsx (hunk 4 above)
Comment (vytick) [reply suite-native/biometrics/src/components/BiometricOverlay.tsx]: 492763e1d2

File: suite-native/biometrics/src/components/BiometricsIcons.tsx (hunk 5 above)
Comment (vytick) [reply suite-native/biometrics/src/components/BiometricsIcons.tsx]: 492763e1d2

File: suite-native/biometrics/src/useBiometrics.tsx (hunk 6 above)
Comment (vytick) [reply suite-native/biometrics/src/useBiometrics.tsx]: 492763e1d2

**Review by juriczech — APPROVED** [review]
