### PR TITLE
fix(suite): replace changelog links

### LINKED ISSUE #4665: Device firmware changelog linked to Github not to blogpost
**Describe the bug**
See this issue https://github.com/trezor/trezor-suite/issues/4161 that was created to change behavior of linking changelog of device firmware/update from Github to Blogpost if available. 
Is it possible that this change was not yet merged/release ?

Last tow FW revisions:

    revision: 20 bytes 0x9276b1702361f70e094286e2f89e919d8a230d5c,
    revision: 20 bytes 0x595b14254c1abb2be3f69e42c7932f1eca8cf1b1,

**Info:**
 - Suite version: desktop 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Expected result:**
2.4.3: https://blog.trezor.io/trezor-suite-and-firmware-updates-december-2021-d1e74c3ea283
2.4.2: https://blog.trezor.io/trezor-suite-and-firmware-updates-september-2021-a490f2ea16c1

**Actual result:**
2.4.3: https://github.com/trezor/trezor-firmware/commit/595b14254c1abb2be3f69e42c7932f1eca8cf1b1
2.4.2: https://github.com/trezor/trezor-firmware/commit/9276b1702361f70e094286e2f89e919d8a230d5c

**Screenshot**
obrazek

### PR DESCRIPTION
**Pull request by komret**
Provide correct links to FW changelog in Device Settings.
## Description

1. Remove link from firmware type button because it is redundant (repeated from the line above).
2. Link to the changelog file rather than the whole commit which is hard to read.
3. Link to the changelog corresponding to the device, not statically to core changelog.

## Related Issue

Resolve #4665

## Screenshots (if appropriate):

Screenshot 2022-08-03 at 14 39 55

### CODE REVIEW

File: packages/suite/src/views/settings/device/FirmwareVersion.tsx [hunk 1]
```diff
@@ -69,7 +68,10 @@ export const FirmwareVersion = ({ isDeviceLocked }: FirmwareVersionProps) => {
     const currentFwVersion = getFwVersion(device);
     const availableFwVersion = getFwUpdateVersion(device);
     const { revision } = device.features;
-    const githubUrl = GITHUB_FW_COMMIT_URL + revision;
+    const githubUrl = `https://github.com/trezor/trezor-firmware/blob/${revision}/${
```
Comment (matejkriz) [inline packages/suite/src/views/settings/device/FirmwareVersion.tsx]: I think that using revision instead of just master is not beneficial to the users and more fragile. see https://github.com/trezor/trezor-suite/issues/4665#issuecomment-1206215039

Comment (matejkriz) [reply packages/suite/src/views/settings/device/FirmwareVersion.tsx]: the switch between `core` and `legacy/firmware` should be implemented also here https://github.com/trezor/trezor-suite/blob/fix/4665-changelog-links/packages/suite/src/components/firmware/FirmwareOffer.tsx#L156 (I know, it wasn't part of this issue, but would be nice to fix it.)

I would propose to create a separate constant by model in @trezor/urls for it.

Comment (komret) [reply packages/suite/src/views/settings/device/FirmwareVersion.tsx]: I went for a util to determine the URL based on the device and firmware revision. 238ba0ac47ea0577c06a640a71aee903cbf9336c

**Review by matejkriz — APPROVED** [review]
👍
