### PR TITLE
fix(suite-desktop): desktop update just updated

### LINKED ISSUE #23604: Suite Desktop becoems unavailable after checking current version
**Describe the bug**
Desktop update no longer displayed as available after checking current version changelog.

**Info:**

- Suite Version: Desktop < 25.11

**How to reproduce**

1. Open Suite Desktop of version <25.11
1. Click on Settings > Application > Trezor Suite version > Current version chip
1. Information about available update is gone

**Expected behavior**
Should just open and close the modal.

**Screenshots**

https://github.com/user-attachments/assets/33941e8a-2c6c-4d2f-b80f-6d7f583706b4

**Additional context**
This is not an easy fix, it's wired together all wrong. There currently really isn't any function to just open the info modal for you to see, instead it is currently done by _advancing the flow_ to "just updated" state, which is very wrong because it loses the original state "available".

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Fix issue where just viewing the current Suite version breaks the update flow (hides available update).

I simplified and cleaned up a lot of stuff in `suite-desktop-ui`, so CR commit-by-commit recommended :eyes: 

## Notes for QA

Please test the whole update flow, particularly all modals should be visible in appropriate step.
Also test opting in and out of EAP (curiously, it's the same modal).

## Related Issue

Resolve #23604

### before

FYI I tested with version _mocked_ to 25.9.0, not the actual old release, to test how it is gonna look like when latest version becomes outdated in future (that's what needs to be tested)

https://github.com/user-attachments/assets/33941e8a-2c6c-4d2f-b80f-6d7f583706b4

### after

[fixed.webm](https://github.com/user-attachments/assets/f00ccce0-9f38-4c35-85ba-19f2fcdcbfb8)

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsGeneral/VersionWithUpdate.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ const getUpdateStateMessage = (state: UpdateState) => {
 const Description = ({ desktopUpdateState }: { desktopUpdateState: DesktopUpdateState }) => {
     const appVersion = process.env.VERSION || '';
     const dispatch = useDispatch();
-    const openChangelog = () => dispatch(openJustUpdatedChangelog());
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsGeneral/VersionWithUpdate.tsx:34]: see, this is the core issue.
The name of the function `openJustUpdatedChangelog` is misleading, because it sounds like it just opens the changelog `JustUpdated` modal, and that's just what we want to do here, but no, there currently isn't really any such function!
This function _advances the state_, and in this case that's wrong (loses the `available` state ), so I've renamed it appropriately, to make it less likely to be misused like this.

File: packages/suite/src/reducers/suite/desktopUpdateReducer.ts [hunk 2]
```diff
@@ -8,26 +8,20 @@ import { Action } from 'src/types/suite';
 
 export { DesktopAppUpdateState as UpdateState } from '@suite-common/suite-constants';
 
-export type UpdateModalVisibility = 'maximized' | 'minimized' | 'hidden';
```
Comment (Lemonexe) [inline packages/suite/src/reducers/suite/desktopUpdateReducer.ts:11]: `minimized` was never used anywhere, so I simplified it to `boolean`

File: packages/suite-desktop-ui/src/support/DesktopUpdater.tsx [hunk 3]
```diff
@@ -112,10 +111,7 @@ export const DesktopUpdater = ({ children }: DesktopUpdaterProps) => {
         ready: <Ready hideWindow={hideWindow} />,
     };
 
-    return (
-        <>
-            {isVisible && updateModalMap[desktopUpdateState]}
-            <ModalContextProvider isDisabled={isVisible}>{children}</ModalContextProvider>
```
Comment (Lemonexe) [inline packages/suite-desktop-ui/src/support/DesktopUpdater.tsx:118]: dinosaur alert!
This was context provider for old modals, it was probably forgotten to delete it in 0dc4d1d4, because all of these modals are new already.
And we don't need to wrap children anymore.

File: packages/suite-desktop-ui/src/support/DesktopUpdater.tsx [hunk 4]
```diff
@@ -80,26 +88,17 @@ export const DesktopUpdater = ({ children }: DesktopUpdaterProps) => {
...
+    if (desktopUpdate.isVersionInfoModalVisible) {
+        return <VersionInfoModal onCancel={hideVersionInfoModal} />;
+    }
 
-        // Enable to setup Early Access even after updater error (when desktopUpdate.latest is undefined).
-        return isHackyModalOpen || desktopUpdate.latest !== undefined;
-    }, [desktopUpdate.modalVisibility, desktopUpdateState, desktopUpdate.latest]);
+    const isUpdateInfoAvailable = desktopUpdate.latest !== undefined;
+    const isAlwaysOpenState = isArrayMember(desktopUpdateState, alwaysOpenStates);
+    const isVisible = desktopUpdate.isModalVisible && (isAlwaysOpenState || isUpdateInfoAvailable);
```
Comment (Lemonexe) [inline packages/suite-desktop-ui/src/support/DesktopUpdater.tsx:101]: this does not need to be a memo, it isn't an expensive calculation, and it is `boolean` so referentially stable.

File: packages/suite-desktop-ui/src/support/DesktopUpdater.tsx [hunk 5]
```diff
@@ -80,26 +88,17 @@ export const DesktopUpdater = ({ children }: DesktopUpdaterProps) => {
...
+    };
 
-        const isHackyModalOpen = [
-            UpdateState.EarlyAccessDisable,
-            UpdateState.EarlyAccessEnable,
-            UpdateState.JustUpdated,
-        ].includes(desktopUpdateState);
+    if (desktopUpdate.isVersionInfoModalVisible) {
+        return <VersionInfoModal onCancel={hideVersionInfoModal} />;
+    }
```
Comment (Lemonexe) [inline packages/suite-desktop-ui/src/support/DesktopUpdater.tsx:97]: I extracted this case from the global modal, but it should better be rendered locally, instead of redux 🤮 
Currently I can't do that – can't import `suite-desktop-ui` into `suite`, so maybe all those components should be moved?

Or a better DI-like solution TBD?

Without further refactoring I think this is the best I can do.

**Review by seibei-iguchi — APPROVED** [review]
