### PR TITLE
fix(suite-native): handle cancelling of Bluetooth pairing correctly

### LINKED ISSUE #21933: Cancelling BT pairing on Trezor leads to pairing failed alert to be shown
However, this alert is intended only for situations where pairing failed due to broken pairing. Investigate if it's possible to distinguish between these situations.

### PR DESCRIPTION
**Pull request by yanascz**
- When Bluetooth pairing is cancelled on either end, a previously removed toast message is shown.
- When Bluetooth pairing is broken (paired on host OS but unpaired on TS7) and pairing fails, show the existing alert.
- In both cases, a corresponding device is removed from `nearbyDevices` as it's no longer connectable.

## Related Issue

Resolve #21933

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/bluetooth-pairing-canceled&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/bluetooth-pairing-canceled&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/bluetooth-pairing-canceled&lookback=7)

### CODE REVIEW

**Review by juriczech — APPROVED** [review]
LGTM. Haven't tested this.

File: packages/transport-native-bluetooth/src/api/bluetoothManager.ts [hunk 1]
```diff
@@ -104,13 +104,19 @@ class BluetoothManager {
...
-        this.nearbyDevices = this.nearbyDevices.map(d =>
-            // Make sure that pairing-error is the final state, reconnecting is not possible.
-            d.id === deviceId && d.connectionStatus.type !== 'pairing-error'
-                ? { ...d, lastUpdatedTimestamp: Date.now(), connectionStatus }
-                : d,
-        );
-        // TODO: Do not emit any other events when the connection status is pairing-error?
+        if (
+            connectionStatus.type === 'pairing-canceled' ||
+            connectionStatus.type === 'pairing-error'
```
Comment (peter-sanderson) [inline packages/transport-native-bluetooth/src/api/bluetoothManager.ts:109]: nit: `['pairing-error', 'pairing-canceled'].includes(connectionStatus.type)`

Comment (peter-sanderson) [reply packages/transport-native-bluetooth/src/api/bluetoothManager.ts:109]: or maybe even to introduce some `const PAITING_FAIELD_TYPES = ['pairing-error', 'pairing-canceled']`
