### PR TITLE
Fix home screen

### LINKED ISSUE #21787: Homescreen for the device is missing in settings and onboarding
**Describe the bug**
Homescreen for the device is missing in settings and onboarding

**Steps to reproduce:**
1. Connect a device
2. Navigate to settings>device settings
3. There is no Homescreen settings

**Info:**
 - Suite version: desktop 25.10.0 (0c38f599d12923ffe53305b8575b1f7cf9b944dc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.10.0 Chrome/140.0.7339.41 Electron/38.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: Trezor T3W1 2.9.2 universal (revision 938939a47f4e23c0119fff579b68dd18f36b1488)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**Screenshots:**

Image

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolve: https://github.com/trezor/trezor-suite/issues/21787

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-home-screen&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsDevice/Homescreen/ChangeHomescreenButtons.tsx [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+    const isHomescreenGallerySupportedOnDevice = deviceModelInternal !== DeviceModelInternal.T3W1;
+
+    if (isHomescreenGallerySupportedOnDevice) {
+        return (
+            <ButtonGroup size="small">
+                <UploadButton />
+                <GalleryButton />
+            </ButtonGroup>
+        );
+    }
```
Comment (OriginalEveres) [inline packages/suite/src/views/settings/SettingsDevice/Homescreen/ChangeHomescreenButtons.tsx]: instead of `isHomescreenGallerySupportedOnDevice` you could check if the gallery has any available images.

see `packages/suite/src/constants/suite/homescreens.ts`.

File: packages/suite/src/utils/suite/homescreen.ts [hunk 2]
```diff
@@ -278,36 +282,44 @@ export const isValidImageSize = (file: File, deviceModelInternal: DeviceModelInt
...
+
+                const isBlack = red === 0 && green === 0 && blue === 0;
+                const isWhite = red === 255 && green === 255 && blue === 255;
+
+                if (!isBlack && !isWhite) {
+                    return ImageValidationError.InvalidColorCombination;
+                }
+            }
         }
     }
```
Comment (OriginalEveres) [inline packages/suite/src/utils/suite/homescreen.ts:309]: I really that like you went from `.forEach` to normal `for loop`. 👍🏻

**Review by OriginalEveres — APPROVED** [review]
code LGTM, tested and it works on TS3 - changing the homescreen from gallery.

File: packages/suite/src/views/settings/SettingsDevice/Homescreen/ChangeHomescreenButtons.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/views/settings/SettingsDevice/Homescreen/ChangeHomescreenButtons.tsx]: fixed
