### PR TITLE
EVM poisoning vol. 2

### LINKED ISSUE #8007: Detecting fraud tx on many places within a codebase
Right now we check `isZeroValuePhishing` on many places within a code. 

I suggest to detect it on one place and store it together with tx object.

If there is a plan to detect it in blockbook, this can be taken as preparation.

### LINKED ISSUE #8119: Address poisoning attack: Label unverified token transactions in TX detail
BACKGROUND
---
Related to https://github.com/trezor/trezor-suite/issues/7278

Scammers employ a similar logic to that of zero-value transactions by utilizing unverified tokens that hold no fiat value but still carry a positive number of units in the transaction.

Example of the token: https://etherscan.io/token/0x8744dab2fa43055130a85c70d6b0676a82ae4704
Transaction example: https://etherscan.io/tx/0xfd7788d4ac55a9b1024d39a5d124f9e2012fc2dca197daa10c12e178d50b26ec

PROPOSED CHANGES
---
- Check the token contract address against Ethereum definitions
- If the contract address is not in Ethereum definitions label tx in the tx history
- Design remains as it is

### LINKED ISSUE #10783: Do not fetch fiat rates for tokens without definitions
**Describe the bug**
Do not fetch fiat rates for tokens without definitions Screenshot 2024-01-02 at 5 02 55

### LINKED ISSUE #11037: Do not show zero balance tokens in Send form select
**Describe the bug**

Pre-issue of https://github.com/trezor/trezor-suite/issues/6595 to distinguish potential scams

Do not show zero balance tokens in Send form select

### LINKED ISSUE #11040: Categorise tokens into verified/unverified in send form and tokens section
**Describe the bug**

Pre-issue of https://github.com/trezor/trezor-suite/issues/6595 to distinguish potential scams

By introducing token definitions, we can categorise tokens into two sections. Normal (has token definition) and unverified (does not have token definition)

**Send select:**
ETH + verified tokens in one section and `Unverified Tokens` the others 

**Tokens section:**
Verified tokens (no heading) and `Unverified Tokens` the other section with some tooltip explaining it `Unverified Tokens pose potential risks. Use caution.`

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- fetch token definitions for each token available in account, it is done on redux action `updateSelectedAccount`
- use this token definition in send form for checking if we know this token
- mark fake txs 
- do not fetch fiat rates for unknown tokens
- hide zero balance tokens in send form
- categorise tokens in send form into known and unknown according to token definitions **NO ISSUE**
- categorise tokens page

## Related Issue

Resolves https://github.com/trezor/trezor-suite/issues/8119
Resolves https://github.com/trezor/trezor-suite/issues/10783
Resolves #8007 I slightly refactored the logic, it cannot be part of tx as we need to fetch token definitions first
Resolves  #11037
Resolves #11040

## Screenshots:

Screenshot 2024-01-29 at 15 49 14

Screenshot 2024-02-06 at 19 18 42
Screenshot 2024-02-06 at 19 18 22

### CODE REVIEW

File: suite-common/wallet-core/src/tokenDefinitions/tokenDefinitionsActions.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { createAction } from '@reduxjs/toolkit';
+
+import { NetworkSymbol } from '@suite-common/wallet-config';
+import { TokenDefinition } from '@suite-common/wallet-types';
+
+const actionsPrefix = '@common/token-definitions';
```
Comment (AdamSchinzel) [inline suite-common/wallet-core/src/tokenDefinitions/tokenDefinitionsActions.ts]: Nitpicks:
1. Based on other part of `wallet-core` it should be `@common/wallet-core/token-definitions`
2. Also the folder should be token-definitions, not tokenDefinitions

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 2]
```diff
@@ -423,21 +424,16 @@ export const signTransaction =
...
-            const isTokenKnown = await fetch(
-                `https://data.trezor.io/firmware/eth-definitions/chain-id/${
-                    network.chainId
-                }/token-${enhancedTxInfo.token.contract.substring(2).toLowerCase()}.dat`,
-            )
-                .then(response => response.ok)
-                .catch(() => false);
-
-            enhancedTxInfo.isTokenKnown = isTokenKnown;
+        if (account.networkType === 'ethereum' && !isCardanoTx(account, enhancedTxInfo)) {
```
Comment (AdamSchinzel) [inline packages/suite/src/actions/wallet/sendFormActions.ts]: I think that the correct condition should be:

`(account.networkType === 'ethereum' && enhancedTxInfo.token?.contract)`

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 3]
```diff
@@ -423,21 +424,16 @@ export const signTransaction =
...
+            const contractAddress = enhancedTxInfo.token?.contract;
+            if (contractAddress) {
```
Comment (AdamSchinzel) [inline packages/suite/src/actions/wallet/sendFormActions.ts]: If we will check the existence of contract address in the condition above this is not needed then

File: suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts [hunk 4]
```diff
@@ -86,7 +87,19 @@ type UpdateCurrentFiatRatesThunkPayload = {
 
 export const updateFiatRatesThunk = createThunk(
     `${fiatRatesActionsPrefix}/updateFiatRates`,
-    async ({ ticker, localCurrency, rateType }: UpdateCurrentFiatRatesThunkPayload) => {
+    async (
+        { ticker, localCurrency, rateType }: UpdateCurrentFiatRatesThunkPayload,
+        { getState },
+    ) => {
+        if (ticker.tokenAddress) {
+            const tokenDefinitions = selectTokenDefinitions(ticker.symbol)(getState());
```
Comment (AdamSchinzel) [inline suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts]: It would be better to use `selectSpecificTokenDefinition` so then the return can be more obvious with just `!tokenDefinitions`

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx [hunk 5]
```diff
@@ -150,12 +150,14 @@ interface IOGridRow {
     anonymitySet?: AnonymitySet;
     tx: WalletAccountTransaction;
     vinvout: WalletAccountTransaction['details']['vin'][number];
+    isPhishingTransaction?: boolean;
```
Comment (AdamSchinzel) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:153]: This is a false-positive field, ESlint is claiming that it is not used. You can add `// eslint-disable-next-line react/no-unused-prop-types` to solve it.

Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:153]: I added it to `CollapsibleIOSection` which extends the `IOSectionColumnProps` type

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/actions/wallet/sendFormActions.ts]: Oh I will check, that's probably some wrong conflict resolution

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx (hunk 5 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:153]: Then it would be nice to refactor the types a bit so the `type-check_and_lint` passes

File: suite-common/wallet-core/src/tokenDefinitions/tokenDefinitionsActions.ts (hunk 1 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/tokenDefinitions/tokenDefinitionsActions.ts]: fb056f24aeaa7c54a17ad73299fa3530e9c90036
726defcd3fdc7fc585b569e25e9b6df8d8038d3d
3f64548e333013df5180297ebed6d38377fc3902

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/actions/wallet/sendFormActions.ts]: 52ef3043a0d6e73f882cbc48a2a12690e521897f

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx (hunk 5 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:153]: b346f01311c2489fe6a8a09e2350b9651260dd85

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 3 above)
Comment (tomasklim) [reply packages/suite/src/actions/wallet/sendFormActions.ts]: 52ef3043a0d6e73f882cbc48a2a12690e521897f

File: suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts (hunk 4 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts]: actually it cant, but i will redo it to use `token-definitions` from config

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/actions/wallet/sendFormActions.ts]: I am almost sure that checking `!isCardanoTx(account, enhancedTxInfo)` is not needed since it just returns if `account.networkType === 'cardano'` and we have a condition to check `account.networkType === 'ethereum'`.

Comment (tomasklim) [reply packages/suite/src/actions/wallet/sendFormActions.ts]: This cardano thing is all over send form actions, typecheck complains without it

File: suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts (hunk 4 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts]: 6ae7d78123563d0bc24bee44c4a74553e576fdbe

It would be nice to type whole networks config but let's leave it for another time

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+                const fetchedTokenDefinition = await fetch(
+                    `https://data.trezor.io/firmware/eth-definitions/chain-id/${
+                        network.chainId
+                    }/token-${contractAddress.substring(2).toLowerCase()}.dat`,
+                    { method: 'HEAD' },
+                );
+
+                isTokenKnown = fetchedTokenDefinition.ok;
+
+                dispatch(
```
Comment (Nodonisko) [inline suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts]: Don't create extra actions for success/fail thunks. RTK has built-in support for these https://redux-toolkit.js.org/api/createAsyncThunk#examples and https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-errors

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/TxDetailModal.tsx [hunk 7]
```diff
@@ -103,15 +104,17 @@ export const TxDetailModal = ({ tx, rbfForm, onCancel }: TxDetailModalProps) =>
     );
     const account = useSelector(state => selectAccountByKey(state, accountKey));
     const network = account && getAccountNetwork(account);
-    const isZeroValuePhishing = getIsZeroValuePhishing(tx);
+    const tokenDefinitions = useSelector(state => selectTokenDefinitions(tx.symbol)(state));
+
+    const isPhishingTransaction = getIsPhishingTransaction(tx, tokenDefinitions);
```
Comment (Nodonisko) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/TxDetailModal.tsx]: Why not create selector for this?

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+                state[networkSymbol]![contractAddress] = {
+                    isTokenKnown: undefined,
+                    isLoading: false,
+                    error: true,
+                };
+            });
+    },
+);
+
+export const selectTokenDefinitions =
```
Comment (PeKne) [inline suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: Why are these selectors returning a function instead of a value? What about using simple function wrappen in `memoizeWithArgs` instead?

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+
+                state[networkSymbol]![contractAddress] = {
+                    isTokenKnown,
+                    isLoading: false,
+                    error: false,
+                };
+            })
+            .addCase(tokenDefinitionsActions.fetchError, (state, action) => {
+                const { networkSymbol, contractAddress } = action.payload;
+                state[networkSymbol]![contractAddress] = {
```
Comment (PeKne) [inline suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: For safety: 
```suggestion
            if(state[networkSymbol])
                state[networkSymbol][contractAddress] = {
```

File: packages/suite/src/support/messages.ts [hunk 10]
```diff
@@ -2805,6 +2805,14 @@ export default defineMessages({
         defaultMessage: 'Community',
         id: 'TR_COMMUNITY_LANGUAGES',
     },
+    TR_TOKEN_UNVERIFIED_BY_TREZOR: {
+        defaultMessage: 'Unverified tokens',
+        id: 'TR_TOKEN_UNVERIFIED_BY_TREZOR',
+    },
+    TR_TREZOR_UNVERIFIED_BY_TREZOR_TOOLTIP: {
+        defaultMessage: 'Unverified Tokens pose potential risks. Use caution.',
```
Comment (PeKne) [inline packages/suite/src/support/messages.ts]: Maybe typo?
```suggestion
        defaultMessage: 'Unverified tokens pose potential risks. Use caution.',
```

File: packages/suite/src/views/wallet/tokens/components/TokenList.tsx [hunk 11]
```diff
@@ -68,92 +76,134 @@ const StyledNoRatesTooltip = styled(NoRatesTooltip)`
...
+    margin-bottom: ${spacingsPx.sm};
+`;
+
 interface TokenListProps {
     tokens: Account['tokens'];
     networkType: Account['networkType'];
     explorerUrl: string;
     explorerUrlQueryString: string;
     isTestnet?: boolean;
+    symbol: Account['symbol'];
```
Comment (PeKne) [inline packages/suite/src/views/wallet/tokens/components/TokenList.tsx]: nit: for better readibility

```suggestion
    networkSymbol: NetworkSymbol;
```

File: suite-common/suite-utils/src/antiFraud.ts [hunk 12]
```diff
@@ -1,8 +1,25 @@
...
     transaction.tokens.every(token => new BigNumber(token.amount).isEqualTo(0));
+
+export const getIsFakeTokenPhishing = (
+    transaction: WalletAccountTransaction,
+    tokenDefinitions: TokenDefinitions,
+) =>
+    new BigNumber(transaction.amount).isEqualTo(0) && // native currency is zero
+    !!transaction.tokens.length && // there are tokens in tx
+    transaction.tokens.every(tokenTx => ['ERC20', 'SPL'].includes(tokenTx?.standard || '')) && // non-nfts
+    !transaction.tokens.some(tokenTx => tokenDefinitions[tokenTx.contract]?.isTokenKnown); // all are tokens are unknown
```
Comment (PeKne) [inline suite-common/suite-utils/src/antiFraud.ts]: nit:
```suggestion
    !transaction.tokens.some(tokenTx => tokenDefinitions[tokenTx.contract]?.isTokenKnown); // all tokens are unknown
```

File: suite-common/suite-utils/src/antiFraud.ts [hunk 13]
```diff
@@ -1,8 +1,25 @@
...
     !!transaction.tokens.length &&
     transaction.tokens.every(token => new BigNumber(token.amount).isEqualTo(0));
+
+export const getIsFakeTokenPhishing = (
+    transaction: WalletAccountTransaction,
+    tokenDefinitions: TokenDefinitions,
+) =>
+    new BigNumber(transaction.amount).isEqualTo(0) && // native currency is zero
+    !!transaction.tokens.length && // there are tokens in tx
+    transaction.tokens.every(tokenTx => ['ERC20', 'SPL'].includes(tokenTx?.standard || '')) && // non-nfts
```
Comment (PeKne) [inline suite-common/suite-utils/src/antiFraud.ts]: what about creating some util function `isNFTStandard` and use it here? Just an idea.

File: suite-common/suite-utils/src/antiFraud.ts [hunk 14]
```diff
@@ -1,8 +1,25 @@
...
+    !transaction.tokens.some(tokenTx => tokenDefinitions[tokenTx.contract]?.isTokenKnown); // all are tokens are unknown
+
+export const getIsPhishingTransaction = (
+    transaction: WalletAccountTransaction,
+    tokenDefinitions: TokenDefinitions,
+) =>
+    getIsZeroValuePhishing(transaction) ||
+    (!!Object.keys(tokenDefinitions).length && // at least one token definition is available
```
Comment (PeKne) [inline suite-common/suite-utils/src/antiFraud.ts]: nit I preffer to use guard functions for these common checks. It is shorter and more readable. But I understand if you don't want to apply this. Feel free to resolve.
```suggestion
    import {D} from "@mobily/ts-belt";

    (D.isNotEmpty() && // at least one token definition is available
```

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts [hunk 15]
```diff
@@ -0,0 +1,56 @@
...
+        const { network, contractAddress } = params;
+        const tokenDefinition = selectSpecificTokenDefinition(
+            network.symbol,
+            contractAddress,
+        )(getState());
+
+        let isTokenKnown = tokenDefinition?.isTokenKnown;
+
+        // if token was never fetched and is not loading right now
+        if (typeof isTokenKnown === 'undefined' && !tokenDefinition?.isLoading) {
```
Comment (PeKne) [inline suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts]: Why not:
```
        if (isTokenKnown === undefined && !tokenDefinition?.isLoading) {
```

**Review by PeKne — COMMENTED** [review]
Small things, otherwise looks good to me.

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts (hunk 15 above)
Comment (Nodonisko) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts]: or `!isTokenKnown` :D

File: packages/suite/src/support/messages.ts (hunk 10 above)
Comment (tomasklim) [reply packages/suite/src/support/messages.ts]: @Hannsek ?

Comment (Hannsek) [reply packages/suite/src/support/messages.ts]: Let's go with _tokens_, we can change the text in the future.

File: suite-common/suite-utils/src/antiFraud.ts (hunk 13 above)
Comment (tomasklim) [reply suite-common/suite-utils/src/antiFraud.ts]: We already have that `isNftTokenTransfer`. I will use it, I just have to move whole `antiFraud` to `wallet-utils` package, which makes sense

Comment (tomasklim) [reply suite-common/suite-utils/src/antiFraud.ts]: d92a071ef81b4e9b442cf6e9d8b59f367bcd0d6c

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts (hunk 15 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts]: Because it can also be `false`

Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts]: cc7017c8a25c3a1ef1efd882dbc35d0f50c255cf

File: suite-common/suite-utils/src/antiFraud.ts (hunk 14 above)
Comment (tomasklim) [reply suite-common/suite-utils/src/antiFraud.ts]: 84a195fa785048842a2b5cdcf3187cfdf2623cc2

File: packages/suite/src/support/messages.ts (hunk 10 above)
Comment (tomasklim) [reply packages/suite/src/support/messages.ts]: 5bf6ce2e962ee3bbf83d508b1943235f5254b99f

File: packages/suite/src/views/wallet/tokens/components/TokenList.tsx (hunk 11 above)
Comment (tomasklim) [reply packages/suite/src/views/wallet/tokens/components/TokenList.tsx]: 23fb1f90fcfd1b7599914eaa492bf5a4b0d2058b

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts (hunk 9 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: cd8a41fb52b1fb018dc26df6792f9d3522db20d3

File: suite-common/suite-utils/src/antiFraud.ts (hunk 14 above)
Comment (PeKne) [reply suite-common/suite-utils/src/antiFraud.ts]: Could be applied also few lines above, but I won't block this PR because of that.

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts (hunk 8 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: I was using `blockchainReducer` as example fail. I changed it

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts (hunk 9 above)
Comment (PeKne) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: remove the exclamation mark on the next line please

```ts
state[networkSymbol]![contractAddress] ==> state[networkSymbol][contractAddress]
```

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts (hunk 8 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: 267dd9f7aa290873e42e58211e3fd2e0036f53b0
b219e996e528cc57f065c4307f58b88d87144d67
8139611e26641db2144ad5228807bb33ac3a4ace
ee7bff11c1e0ec8f2ca8db5cf86850109394f46e
3a9f75b6be39bd74ab990ac5901cb4967110b3ba

File: suite-common/suite-utils/src/antiFraud.ts (hunk 14 above)
Comment (tomasklim) [reply suite-common/suite-utils/src/antiFraud.ts]: e7e24be0919bc33b6546171f9d8126e7dea5dd78

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts (hunk 9 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: 1392726d11396c5c98f19050f898470c9fb3f939

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts (hunk 6 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunk.ts]: 1392726d11396c5c98f19050f898470c9fb3f939

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts (hunk 9 above)
Comment (PeKne) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: now is the original if redundant :D 

remove this piece of code please:
```
               if (!state[network.symbol]) {
                    state[network.symbol] = {};
                }
```

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/TxDetailModal.tsx (hunk 7 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/TxDetailModal.tsx]: 9eeaae54cc33ca286ea640b134cded092f083a60

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts (hunk 9 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: I can't do that. It is undefined for the first occurence of `network.symbol`

Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: It has to be there at least for `pending`

Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts]: 70504962abf7fef20191e402fcae9a9e413564d9

**Review by PeKne — APPROVED** [review]
Perfect 👍

File: suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunks.ts [hunk 16]
```diff
@@ -0,0 +1,35 @@
...
+        params: { network: Network; contractAddress: string },
+        { getState, rejectWithValue },
+    ) => {
+        const { network, contractAddress } = params;
+        const { isTokenKnown } =
+            selectSpecificTokenDefinition(getState(), network.symbol, contractAddress) || {};
+
+        if (isTokenKnown === undefined) {
+            try {
+                const fetchedTokenDefinition = await fetch(
```
Comment (Nodonisko) [inline suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunks.ts:20]: are you sure that this will work? you are not returning these fetched values anywhere so you can't use them anywhere in `fullfiled` in reducer etc.

Comment (tomasklim) [reply suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunks.ts:20]: It does not return any values, i just check that the link exist (HEAD request)

**Review by Nodonisko — APPROVED** [review]
