### PR TITLE
Trading - copyable contract with font matching to txid font

### LINKED ISSUE #18239: Trading - font tx id
**Describe the bug**

Approval tx id has different font than `FET contract`. Let's use same component also for contract so that it matches

Image

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Changed contract font to match txid font + added option to copy it to clipboard.

## Related Issue

Resolve #18239 

## Screenshots:

Screenshot 2025-05-05 at 15 10 42

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-contract-font&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-contract-font&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/copy/Copy.tsx [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+        ${onHoverTextOverflowContainerHover}
+    }
+`;
+
+interface CopyProps {
+    value: string;
+    isAddress?: boolean;
+}
+
+export const Copy = ({ value, isAddress = false }: CopyProps) => {
```
Comment (tomasklim) [inline packages/suite/src/components/suite/copy/Copy.tsx]: how is this component different from `TokenAddressRow` and `IOAddress`?

**Review by tomasklim — CHANGES_REQUESTED** [review]
We should avoid introducing third component doing the same

**Review by tomasklim — CHANGES_REQUESTED** [review]
.

File: packages/suite/src/components/suite/copy/Copy.tsx (hunk 1 above)
Comment (TomasBoda) [reply packages/suite/src/components/suite/copy/Copy.tsx]: done - removed `Copy` component and updated `IOAddress` to support chunking

Comment (TomasBoda) [reply packages/suite/src/components/suite/copy/Copy.tsx]: also renamed `IOAddress` to `TxAddress`

**Review by izmy — APPROVED** [review]

**Review by tomasklim — APPROVED** [review]
