### PR TITLE
fix(suite): make sure that the order isnt changed when there isnt a p…

### LINKED ISSUE #20659: Wallet switcher appears when redirected from the sell partner.
**Describe the bug**
Wallet switcher shows up in the web version when going back from the sell partner, causing confusion and sometimes an infinite loop.

Image

**Info:**
 - Suite version: web 25.9.0 (c6ba3649027ae6cb9d8250ad14f4eceeb9562fde)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2880x1800
 - Device: Trezor T3T1 2.9.0 universal (revision a09e6f04d4204607d821d9b742dcf7ffe9c4e2f5)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by vojtatranta**
…ortfolio tracker device

## Description

Problem: the sorting was wrong, when there was multiple devices it order was switched `(likely missed a branch like b.id === portfolioTrackerId) return -1`

Replaced with explicit puting to the end.

This may fix bug: https://github.com/trezor/trezor-suite/issues/20659

And also similar bugs when device swithcer opens completley needleslly (eg. when the disconnected device is first in the list)

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/20659

Also fixes bug when the device switcher is opened wrongly coz there is always first device selected when there are 2 devices

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=wrongly-sorted-initial-devices&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=wrongly-sorted-initial-devices&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=wrongly-sorted-initial-devices&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/device/deviceThunks.ts [hunk 1]
```diff
@@ -292,17 +292,21 @@ export const switchDuplicatedDevice = createThunk(
...
+        device => device.id === PORTFOLIO_TRACKER_DEVICE_ID,
+    );
 
-        return -1;
-    });
+    if (!containsPortfolioTrackerDevice) {
+        return sortedDevicesByTimestamp;
+    }
+
+    return sortedDevicesByTimestamp
```
Comment (vojtatranta) [inline suite-common/wallet-core/src/device/deviceThunks.ts:302]: this ensures that the timestamp sorting remains primary

File: suite-common/wallet-core/src/device/deviceThunks.ts [hunk 2]
```diff
@@ -292,17 +292,21 @@ export const switchDuplicatedDevice = createThunk(
...
+
+    const containsPortfolioTrackerDevices = sortedDevicesByTimestamp.filter(
+        device => device.id === PORTFOLIO_TRACKER_DEVICE_ID,
+    );
 
-        return -1;
-    });
+    if (!containsPortfolioTrackerDevices.length) {
+        return sortedDevicesByTimestamp;
+    }
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/device/deviceThunks.ts]: after changing to filter, this condition is useless, but also it does not hurt anything :shrug:

**Review by Lemonexe — APPROVED** [review]

File: suite-common/wallet-core/src/device/deviceThunks.test.ts [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+                createTestDevice('b', 3),
+            ];
+            const original = [...input];
+
+            void sortDevices(input);
+
+            expect(input).toEqual(original);
+        });
+    });
+});
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/device/deviceThunks.test.ts:62]: :+1:

File: packages/suite/src/actions/suite/initAction.ts [hunk 4]
```diff
@@ -75,16 +75,33 @@ export const init = () => async (dispatch: Dispatch, getState: GetState) => {
         await dispatch(
             trezorConnectActions.connectInitThunk({
                 [DEVICE.CONNECT]: (_device, prevConnectedDevices) => {
-                    const previouslyConnectedDevices = prevConnectedDevices.filter(
-                        device => device.connected,
-                    );
+                    const previouslyConnectedUniqueDevices = prevConnectedDevices
```
Comment (vojtatranta) [inline packages/suite/src/actions/suite/initAction.ts:78]: @Lemonexe there was a problem that there were same devices twice... SO I took only unique by ids.

**Review by Lemonexe — APPROVED** [review]
LGTM, good catch!

**Comment by honzauher** [comment]
**QA OK**

Working as expected

**Info:**
 - Suite version: web 25.9.0 (388dafd45ebdbf5cde695a86a00a6cc4a93a0499)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
 - OS: Win32
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.10 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport
