### PR TITLE
fix(suite): Fix staking cards

### LINKED ISSUE #14360: Remove or align icons in Staking section
**Describe the bug**
Remove or align icons in Staking section. 
See screenshot.
Same results in release candidate and dev version

**Steps to reproduce:**
1. Stake funds ETH or Holesky
3. Navigate to Staking section after funds are staked
4. Observe info section

**Info:**
 - Suite version: web 24.10.0 (f79a333eaf6bc23caa9ecd9c851ac7d24240e176)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14360

## Screenshots:

Screenshot 2024-09-17 at 11 34 31

### CODE REVIEW

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/ApyCard.tsx [hunk 1]
```diff
@@ -12,14 +12,16 @@ export const ApyCard = ({ apy }: ApyCardProps) => {
...
+                <Icon name="percent" color={theme.iconSubdued} />
 
-            <CardBottomContent>
-                <AccentP>{`${apy}%`}</AccentP>
-                <GreyP>
-                    <Translation id="TR_STAKE_APY" />
-                </GreyP>
-            </CardBottomContent>
+                <CardBottomContent>
+                    <AccentP>{`${apy}%`}</AccentP>
```
Comment (seibei-iguchi) [inline packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/ApyCard.tsx:19]: Should we get rid of these custom components?

**Review by seibei-iguchi — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

image

**Info:**
 - Suite version: web 24.10.0 (863c74fb0ef670adc1bc7066f9dac6bd16b681c3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0
