### PR TITLE
fix: onboarding modal layout

### LINKED ISSUE #21369: Onboarding layout w/ banner
Banner is above the backdrop

Image

### PR DESCRIPTION
**Pull request by OriginalEveres**
Fixes ModalBackdrop gap in OnboardingLayout.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21369

## Screenshots:
**BEFORE**:
486825571-5cd26def-b20d-429f-ab38-6c08d697f1c5
**AFTER**:
Screenshot 2025-09-10 at 14 40 07

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/onboarding-modal-layout&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/onboarding-modal-layout&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/onboarding/OnboardingLayout.tsx [hunk 1]
```diff
@@ -164,13 +174,24 @@ type OnboardingLayoutProps = {
...
+    const allowedModal = useFilteredModal(
+        [MODAL.CONTEXT_USER],
+        ['advanced-coin-settings', 'disable-tor'],
+    );
+
     return (
-        <TrafficLightOffset>
-            <Wrapper>
-                <SuiteBanners isOnboarding />
+        <TrafficLightOffset isVisible={false}>
```
Comment (Lemonexe) [inline packages/suite/src/components/onboarding/OnboardingLayout.tsx]: you can remove this, right?
`isVisible={false}` always just returns children

File: packages/suite/src/components/onboarding/OnboardingLayout.tsx [hunk 2]
```diff
@@ -39,6 +43,12 @@ const Body = styled.div`
 const ScrollingWrapper = styled.div`
     position: relative;
     display: flex;
+    flex-direction: column;
+    width: 100%;
+`;
+
+const OnboardingSpacer = styled.div`
+    height: 35px;
```
Comment (Lemonexe) [inline packages/suite/src/components/onboarding/OnboardingLayout.tsx]: could you please define a new constant `TrafficLightOffset = 35`, use it [in TrafficLight](https://github.com/trezor/trezor-suite/blob/106f815ed9f4611fcc875c749f98413064c41fad/packages/suite/src/components/suite/TrafficLightOffset.tsx#L49) and import to here?

Or even better, can't you reuse <TrafficLightOffset> inside the ScrollingWrapper? And get rid of `OnboardingSpacer`?
Because now it's not effective ([comment](https://github.com/trezor/trezor-suite/pull/21422/files#r2336743869)), I would move it there.

File: packages/suite/src/components/onboarding/OnboardingLayout.tsx [hunk 3]
```diff
@@ -164,13 +174,24 @@ type OnboardingLayoutProps = {
...
+        ['advanced-coin-settings', 'disable-tor'],
+    );
+
     return (
-        <TrafficLightOffset>
-            <Wrapper>
-                <SuiteBanners isOnboarding />
+        <TrafficLightOffset isVisible={false}>
+            <ConnectionGlobalModal />
+            {allowedModal && <ReduxModal {...allowedModal} />}
```
Comment (Lemonexe) [inline packages/suite/src/components/onboarding/OnboardingLayout.tsx]: I know this is moved code, but an opportunity to make it more explicit :slightly_smiling_face:  
```suggestion
            {allowedModal !== null ? <ReduxModal {...allowedModal} /> : null}
```

File: packages/suite/src/components/onboarding/OnboardingLayout.tsx (hunk 1 above)
Comment (OriginalEveres) [reply packages/suite/src/components/onboarding/OnboardingLayout.tsx]: yes

**Review by Lemonexe — COMMENTED** [review]
I cannot test as I do not have macOS, but codewise it seems it can be simplified a lot..

File: packages/suite/src/components/suite/banners/SuiteBanners/SuiteBanners.tsx [hunk 4]
```diff
@@ -26,9 +26,10 @@ import { NoBackup } from './NoBackupBanner';
 import { NoConnectionBanner } from './NoConnectionBanner';
 import { SafetyChecksBanner } from './SafetyChecksBanner';
 
-const Container = styled.div<{ $fill?: boolean }>`
+const Container = styled.div<{ $fill?: boolean; $onboarding?: boolean }>`
     width: 100%;
     max-width: ${({ $fill }) => ($fill ? 'none' : MAX_CONTENT_WIDTH)};
+    margin: ${({ $onboarding }) => ($onboarding ? 'auto' : '')};
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/banners/SuiteBanners/SuiteBanners.tsx]: ah, so this is for horizontal centering. Previously, this was taken care of by `<Wrapper>` with flex. So wouldn't it be a better solution to wrap `<SuiteBanners`> at their new position, as they were wrapped before, rather than margin: auto?
But this is a nit.

**Comment by evgenysl** [comment]
QA OK
banner is always on the background

**Review by Lemonexe — APPROVED** [review]
LGTM, only nits remain

**Review by Lemonexe — APPROVED** [review]
Perfect :heart:
