### PR TITLE
fix(suite-common): increment THP connection counter during THP confirmation

### LINKED ISSUE #22451: Increment THP connection counter during THP confirmation
Currently, THP connection counter is incremented on every `DEVICE.CONNECT` event. That means that two restarts of Suite after FW install lead to the connection counter to equal to `3` and auto-connect alert could show. However, as discussed with @Hannsek, THP auto-connect alert shall be displayed only if THP connection confirmation is displayed right before that.

### PR DESCRIPTION
**Pull request by yanascz**
Resolve #22451

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/common/thp-connection-counter&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/common/thp-connection-counter&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/common/thp-connection-counter&lookback=7)

### CODE REVIEW

File: suite-common/thp/src/connectThpDeviceThunk.ts [hunk 1]
```diff
@@ -16,29 +16,23 @@ export const connectThpDeviceThunk = createThunk<void, ConnectThpDeviceThinkPara
...
-        if (credential !== undefined) {
-            // We do not want to offer Autoconnect after reconnection dues to Firmware installation.
-            // Autoconnect will be offered on the next reconnection.
-            if (!isFwInstall) {
-                dispatch(thpActions.incrementCredentialConnectionCounter({ credential }));
-            }
-
-            const hasAutoconnectCredential =
-                device?.thp?.credentials?.find(it => it?.autoconnect) !== undefined;
+        if (credential !== undefined && !isFwInstall && isThpInProgress) {
```
Comment (matejkriz) [inline suite-common/thp/src/connectThpDeviceThunk.ts:27]: The only real change is adding `isThpInProgress` condition, right? The rest is only refactoring?

File: suite-common/thp/src/connectThpDeviceThunk.ts [hunk 2]
```diff
@@ -16,29 +16,23 @@ export const connectThpDeviceThunk = createThunk<void, ConnectThpDeviceThinkPara
...
+            // Increment the counter only after FW installation and during a THP confirmation.
+            dispatch(thpActions.incrementCredentialConnectionCounter({ credential }));
 
+            const hasAutoConnectCredential = device?.thp?.credentials?.some(it => it?.autoconnect);
```
Comment (peter-sanderson) [inline suite-common/thp/src/connectThpDeviceThunk.ts]: supernit: extract to some `const deviceCredentials = device?.thp?.credentials ?? []`

And then no need for many `?`

File: suite-common/thp/src/connectThpDeviceThunk.ts (hunk 1 above)
Comment (yanascz) [reply suite-common/thp/src/connectThpDeviceThunk.ts:27]: And moving other conditions one level up to simplify the code.

**Review by juriczech — APPROVED** [review]
LGTM. Let's wait for someone from desktop to approve 🙏

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts [hunk 3]
```diff
@@ -11,7 +11,7 @@ import { ThpState, prepareThpReducer } from '../src/thpReducer';
 const thpReduce = prepareThpReducer(extraDependenciesMock);
 const firmwareReduce = prepareFirmwareReducer(extraDependenciesMock);
 
-const thpCredential1 = createCredential({ credential: 'credential-1' });
+const thpCredential1 = createCredential({ credential: 'credential-1', connectionCounter: 2 });
```
Comment (peter-sanderson) [inline suite-common/thp/tests/connectThpDeviceThunk.test.ts:14]:
```suggestion
const thpCredentialAtCunter2 = createCredential({ credential: 'credential-1', connectionCounter: 2 });
```

Comment (peter-sanderson) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts:14]: Also this is now the default state of credentials for all tests. This seems confusing. The Counter at `2` is needed only for one test so IMO it shall be used only there.

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts [hunk 4]
```diff
@@ -39,31 +39,37 @@ describe(connectThpDeviceThunk.name, () => {
         const store = configureMockStore({
```
Comment (peter-sanderson) [inline suite-common/thp/tests/connectThpDeviceThunk.test.ts]: `it('goes to AutoconnectInfo step, when counter reaches number 3 by connection device that requires THP'`

(I cannot comment line above)

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts [hunk 5]
```diff
@@ -39,31 +39,37 @@ describe(connectThpDeviceThunk.name, () => {
...
         });
 
         store.dispatch(connectThpDeviceThunk({ device }));
-        expect(store.getState().thp.credentials[0].connectionCounter).toEqual(1);
+        expect(store.getState().thp.credentials[0].connectionCounter).toEqual(3);
         expect(store.getState().thp.credentials[1].connectionCounter).toEqual(0);
-        expect(store.getState().thp.step).toEqual(null);
+        expect(store.getState().thp.step).toEqual('AutoconnectInfo');
 
         store.dispatch(connectThpDeviceThunk({ device }));
```
Comment (peter-sanderson) [inline suite-common/thp/tests/connectThpDeviceThunk.test.ts]: This shall be another `it` in a context of what we discussed yesterday

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts [hunk 6]
```diff
@@ -39,31 +39,37 @@ describe(connectThpDeviceThunk.name, () => {
...
+        expect(store.getState().thp.credentials[0].connectionCounter).toEqual(4);
         expect(store.getState().thp.credentials[1].connectionCounter).toEqual(0);
         expect(store.getState().thp.step).toEqual(null);
+    });
 
-        store.dispatch(connectThpDeviceThunk({ device }));
-        expect(store.getState().thp.credentials[0].connectionCounter).toEqual(3);
-        expect(store.getState().thp.credentials[1].connectionCounter).toEqual(0);
-        expect(store.getState().thp.step).toEqual('AutoconnectInfo');
+    it('does not update the connection counter for credential without THP confirmation', () => {
```
Comment (peter-sanderson) [inline suite-common/thp/tests/connectThpDeviceThunk.test.ts]: :+1:

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts [hunk 7]
```diff
@@ -39,31 +39,37 @@ describe(connectThpDeviceThunk.name, () => {
...
+        const store = configureMockStore({
+            extra: {},
+            reducer: combineReducers({ thp: thpReduce, firmware: firmwareReduce }),
```
Comment (peter-sanderson) [inline suite-common/thp/tests/connectThpDeviceThunk.test.ts:71]: I think here you should have this:
`thp: { ...initialThpState, step: 'ConfirmOnlyConnection' },`

Please test, that this test increment counter when you remove the `firmware` part from the state, and then it WONT increment when you add that `firmare` state. 

I suspect that because the `step: 'ConfirmOnlyConnection'` is missing this test actually tests something else then it is supposed to.

Comment (yanascz) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts:71]: Good point, added `step` as well.

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts (hunk 3 above)
Comment (yanascz) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts:14]: I don't see anything confusing about that. It's required in two tests and it doesn't matter what value is there for the third one.

Comment (peter-sanderson) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts:14]: :+1:  ok then

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts (hunk 5 above)
Comment (yanascz) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts]: I did split the first test into two and believe now it's sufficient. Splitting it more would mean more duplicated code without any benefit, IMHO.

Comment (peter-sanderson) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts]: benefit is the readability, now the test is named in generic way: `updates the connection counter for credential` and the readed needs to dig deeper into test to figure out what it means.

This can be improved to having 2 tests named:

- `it('goes to AutoconnectInfo step, when counter reaches number 3 by connection device that requires THP'`
- `it('increments the counter by connection device that requires THP, but wont got to AutoconnectInfo as counter did not reach the threshold of 3')`

(or any similar naming - whatever you seem to fit)

Absence of this atomicity of the test cases, was the original issue we have discussed after all.

Comment (peter-sanderson) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts]: Yes, this small test is maybe whatever, but if you want to do it right, this is the way. I am ok if you want to be lazy/have-no-time and you can ignore it.

Comment (yanascz) [reply suite-common/thp/tests/connectThpDeviceThunk.test.ts]: The first test is generic because it tests that the counter is correctly incremented. Yes, it does tests two different outcomes to make the test setup easier and the code shorter.

Anyway, I parametrized it and added one more scenario.

File: suite-common/thp/tests/connectThpDeviceThunk.test.ts [hunk 8]
```diff
@@ -35,46 +35,61 @@ const device: Pick<Device, 'thp'> = {
 };
 
 describe(connectThpDeviceThunk.name, () => {
-    it('updates the connection counter for credential', () => {
+    it.each([
+        [1, 2, null],
+        [2, 3, 'AutoconnectInfo'],
+        [3, 4, null],
```
Comment (peter-sanderson) [inline suite-common/thp/tests/connectThpDeviceThunk.test.ts:41]: :clap:

**Review by peter-sanderson — APPROVED** [review]
