### PR TITLE
fix(suite): cardano staking claim toast

### LINKED ISSUE #22850: Cardano staking: claim toast shows full stake balance instead of reward amount
**Describe the bug**
When claiming staked Cardano (ADA) rewards, the toast notification incorrectly shows the whole balance as claimed, instead of only the actual reward amount. The transaction itself is correct and only claims the rewards, but the notification is misleading.

**Info:**
 - Suite version: desktop 25.11.0 (1d5380e1170f76e36938e7d85af29aabee46ac75)
 - Browser: Trezor Suite 25.11.0
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3W1 2.9.4 universal (revision c49d212db01a57177550aa46836c14f5ee584f01)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0
 -
**How to reproduce**

1. Go to Cardano account with staked ADA.
2. Open the 'Staking' tab.
3. Click 'Claim rewards' when rewards are available.
4. Toast notification shows almost the full ADA balance as claimed, instead of just the rewards.

**Expected behavior**
Toast notification should display only the ADA rewards amount that was actually claimed.

**Screenshots**
Toast with wrong claim amount

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Fixed an issue where the claim toast shows the full stake balance instead of the reward amount. 
Claim toast now displays rewards minus fee.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22850

### CODE REVIEW

File: packages/suite/src/actions/wallet/stake/stakeFormCardanoActions.ts [hunk 1]
```diff
@@ -199,6 +200,33 @@ const getTransactionData = (
...
+
+    let amount: BigNumber;
+
+    switch (stakeType) {
+        case 'stake':
+        case 'unstake':
+            amount = accountBalance.minus(totalSpent ?? '0');
+            break;
+        case 'claim':
+            amount = accountBalance.minus(account.availableBalance ?? '0').minus(totalSpent ?? '0');
```
Comment (tomasklim) [inline packages/suite/src/actions/wallet/stake/stakeFormCardanoActions.ts]: Do not substract fee 🙏  This can get amount below zero.

Comment (tomasklim) [reply packages/suite/src/actions/wallet/stake/stakeFormCardanoActions.ts]: Screenshot 2025-11-05 at 10 29 29

Comment (dev-pvl) [reply packages/suite/src/actions/wallet/stake/stakeFormCardanoActions.ts]: done, https://github.com/trezor/trezor-suite/pull/22890/commits/3c3ec64698e395f11cd1a831ea67398ae1a3a02b

**Review by tomasklim — APPROVED** [review]
