### PR TITLE
Fix: Send custom gas limit to device for ETH staking/unstaking

### LINKED ISSUE #17419: ETH staking and unstaking custom gas limit does not get sent to the device.
**Describe the bug**
staking and unstaking custom gas limit does not get sent to the device.  

**Steps to reproduce:**  

1. Try to stake/unstake ETH.  
2. Set a custom gas limit.  
3. The device uses a different gas limit.  

**Info:**
 - Suite version: web 25.3.1 (e5b4203432360b831bb87d2bbfb2e0131e8aeae0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 5120x1440
 - Device: Trezor T3T1 2.8.9 regular (revision 11517f46fdd964261aca734d87badcc9880ffd92)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

Image

Image

### PR DESCRIPTION
**Pull request by izmy**
## Description

The custom gas limit is now correctly sent to the device during ETH staking/unstaking.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17419

## Screenshots:

image

image

IMG_3356

### CODE REVIEW

File: packages/suite/src/utils/suite/ethereumStaking.ts [hunk 1]
```diff
@@ -113,7 +115,7 @@ export const stake = async ({
             from,
             to: contractPoolAddress,
             value: amountWei,
-            gasLimit: getAdjustedGasLimitConsumption(estimatedFee),
+            gasLimit: feeLimit ?? getAdjustedGasLimitConsumption(estimatedFee),
```
Comment (tomasklim) [inline packages/suite/src/utils/suite/ethereumStaking.ts:118]: good idea, we should not modify it 👍

**Review by tomasklim — APPROVED** [review]
