### PR TITLE
Make Suite update modal non-cancellable during auto-update

### LINKED ISSUE #6655: Update app modal is overlapped by Enter passphrase modal.
**Describe the bug**
See video, sometimes you have to go to settings to finalize app update beacause enter passphrase modal cancels update modal.

**Steps to reproduce:**
1. Start older version of Suite that asks you to update
2. Connect device and wait till it starts and its recognized by Suite
3. Click on Update modal
4. Observe Enter passphrase modal.

**Info:**
 - Suite version: desktop 22.9.3 (2b9595fdfee9d36935d72af4af536d2fe4742f5e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.11.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**
https://www.youtube.com/watch?v=jV89GNT9dVI

### PR DESCRIPTION
**Pull request by komret**
## Description

Set `isCancellable` to false when current `route.name` is not `settings-index`. The goal is to make the update non-cancellable if it was opened by `autoUpdater` because the user might not expect it to close on click outside and this can lead to some confusion during auto-update. The route is used in the condition because the modal is not aware what opened it. I added a button to keep the option of downloading in the background.

I could not figure out how to fully test it without a signed version. I was only able to test it partially by lowering the app version in `package.json` and building the app as described in `suite-desktop` README. But download fails as the app is not signed. See the video. (There is an error toast not captured in the video.)

The wallet modal still opens right after the download ends, it is not ideal, but I don't know about a better solution.

## Related Issue

Resolve #6655

## Screenshots:

https://user-images.githubusercontent.com/42465546/224301872-ef830de6-4a9b-42bd-9aa1-ad2f15bc599c.mov

### CODE REVIEW

**Review by tomasklim — CHANGES_REQUESTED** [review]
The solution looks too complicated for me and the button `Download in the background` looks weird 😇
What about only changing `onClickBackdrop` in `DefaultRenderer` component? So that it is not possible to close this modal by clicking outside.

(tbh i dont think we should "fix" this behavior as i think it is not a bug)

**Comment by komret** [comment]
> The solution looks too complicated for me and the button `Download in the background` looks weird 😇 What about only changing `onClickBackdrop` in `DefaultRenderer` component? So that it is not possible to close this modal by clicking outside.
> 
> (tbh i dont think we should "fix" this behavior as i think it is not a bug)

I considered that but did not want to introduce a third type of modal closing. Let's discuss that on standup.

File: packages/suite-desktop-ui/src/support/DesktopUpdater/Downloading.tsx [hunk 1]
```diff
@@ -84,6 +91,11 @@ export const Downloading = ({ hideWindow, progress }: DownloadingProps) => {
                     </>
                 )}
             </DownloadWrapper>
+            {!isCancelable && (
```
Comment (dahaca) [inline packages/suite-desktop-ui/src/support/DesktopUpdater/Downloading.tsx]: Why shouldn't a user be able to download in the background outside of the settings page?

**Review by dahaca — COMMENTED** [review]
@tomasklim  I'd change the `Downloading` modal to something like this to not change it woo much:

image

File: packages/suite-desktop-ui/src/support/DesktopUpdater/Downloading.tsx (hunk 1 above)
Comment (komret) [reply packages/suite-desktop-ui/src/support/DesktopUpdater/Downloading.tsx]: It is always possible to download in the background. But while outside of settings page, it might not be clear that closing the modal means that the download continues in the background, so I replaced the default closing option with the button.

Comment (dahaca) [reply packages/suite-desktop-ui/src/support/DesktopUpdater/Downloading.tsx]: I'd say it's not clear that it continues on background on any page :) Maybe it's worth always showing the `download in the bg` button?

Comment (komret) [reply packages/suite-desktop-ui/src/support/DesktopUpdater/Downloading.tsx]: 93dec6d93ba740e858e5105abacf9be25c1bdb4b
This modal now always look like this and is not closing by clicking outside:
Screenshot 2023-03-16 at 14 29 39

**Comment by komret** [comment]
d52f5037b9181e4295bf4c7ccebaf07299681681
This is just a small refactoring. I did not like the `Progress` element being conditionally rendered depending on the heading. It seems to be tightly coupled with the `Backup` component where we do not want to show progress during loading.
Now, `Progress` only depends on `currentProgressBarStep` and `totalProgressBarSteps`.

**Review by tomasklim — APPROVED** [review]
