### PR TITLE
fix(suite-native): receive cancel

### LINKED ISSUE #10239: Receive flow - cancel the receive does not work
**No1: Cancel Receive address from Trezor device**
Steps to reproduce:
1. Connect Trezor
2. Choose some coin to Receive and click Show address
3. Show address screen appears
4. Click on Cancel button on Trezor device and cancel the Address confirming
5. Mobile app shows confirmation screen
Right behaviour: Mobile app should cancel the Receive and user should be redirected back to previous screen

**No2:Cancel Receive in mobile app:**
Steps to reproduce:
1. Connect Trezor
2. Choose some coin to Receive and click Show address
3. Show address screen appears
4. Click on back in mobile app
5. Trezor Device keep showing address to confirm
Right behaviour: When user cancel the Receive in the app, Trezor device should cancel it too

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10239

### CODE REVIEW

File: suite-native/receive/src/screens/ReceiveModalScreen.tsx [hunk 1]
```diff
@@ -43,8 +46,15 @@ const ReceiveModalScreenSubHeader = ({ accountKey, tokenContract }: ScreenSubHea
     const iconName = tokenContract ?? networkSymbol;
     const coinSymbol = (ethereumTokenSymbol ?? networkSymbol)?.toUpperCase();
 
+    const handleGoBack = () => {
```
Comment (Nodonisko) [inline suite-native/receive/src/screens/ReceiveModalScreen.tsx]: Use screen events instead, use `useFocusEvent` https://reactnavigation.org/docs/navigation-lifecycle#react-navigation-lifecycle-events instead

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/receive/src/screens/ReceiveModalScreen.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/receive/src/screens/ReceiveModalScreen.tsx]: The blur didn't work but I attached an event listener for removing the screen from stack https://github.com/trezor/trezor-suite/pull/10250/commits/cd8402c5e0a7497e79fb608b8692c434eb0f2d94

File: suite-native/receive/src/screens/ReceiveModalScreen.tsx [hunk 2]
```diff
@@ -40,6 +43,15 @@ const ReceiveModalScreenSubHeader = ({ accountKey, tokenContract }: ScreenSubHea
         selectEthereumAccountTokenSymbol(state, accountKey, tokenContract),
     );
 
+    useEffect(() => {
+        const unsubscribe = navigation.addListener('beforeRemove', () => {
```
Comment (Nodonisko) [inline suite-native/receive/src/screens/ReceiveModalScreen.tsx:47]: useLayoutEffect did not work?

**Review by Nodonisko — APPROVED** [review]

File: suite-native/receive/src/hooks/receiveSelectors.ts [hunk 3]
```diff
@@ -0,0 +1,9 @@
+import { pipe, A } from '@mobily/ts-belt';
+
+import { DeviceRootState, selectDeviceButtonRequestsCodes } from '@suite-common/wallet-core';
+
+export const hasReceiveAddressButtonRequest = (state: DeviceRootState) =>
+    pipe(
+        selectDeviceButtonRequestsCodes(state),
+        A.some(code => code === 'ButtonRequest_Address'),
```
Comment (Nodonisko) [inline suite-native/receive/src/hooks/receiveSelectors.ts:8]: Don't we have some const available somewhere instead of text?

File: suite-native/receive/src/screens/ReceiveModalScreen.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/receive/src/screens/ReceiveModalScreen.tsx:47]: That works as well, good point
https://github.com/trezor/trezor-suite/pull/10250/commits/91a17d64cd1a4c17fe4aac3fa91217bc126f4599

File: suite-native/receive/src/hooks/receiveSelectors.ts (hunk 3 above)
Comment (juriczech) [reply suite-native/receive/src/hooks/receiveSelectors.ts:8]: Unfortunetaly no, that's why I created a selector for this. Luckily though, it's typed well so any typo will be caught with TS error

File: suite-native/receive/src/screens/ReceiveModalScreen.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/receive/src/screens/ReceiveModalScreen.tsx:47]: useEffect used after discussion 
https://github.com/trezor/trezor-suite/pull/10250/commits/0577321da19e9e968bdd20d375301b70bff2ef32
