### PR TITLE
fix(suite): Portfolio header skeleton for 0.00 wallet

### LINKED ISSUE #19572: Remembered $0.00 wallet shows skeleton instead of number
**Describe the bug**
Remembered wallet shows skeleton when fiat balance is 0

**Info:**

- Remembered Wallet: yes
- Suite Version: web as of cf676186
- Browser: Chrome

**How to reproduce**

1. Go to develop Suite Web
1. Connect `all` seed device 
1. Remember wallet
1. Disconnect device
2. observe skeleton 💀 💀 💀 
3. skeleton persists even after reconnecting??

**Screenshots**

not rememberd wallet ok ✔ 

Image

remembered broken ❌ 
Image

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Do not show skeleton for remembered device when balance is 0.00

## Related Issue

Resolve #19572

## Screenshots:

**Before:** See issue

**After:** Remembered `all` seed standard wallet:

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/portfolio-skeleton-when-0.00&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/portfolio-skeleton-when-0.00&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/dashboard/PortfolioCard/PortfolioCardHeader.tsx [hunk 1]
```diff
@@ -30,7 +29,6 @@ export const PortfolioCardHeader = ({
     isWalletLoading,
     isWalletError,
     isDiscoveryRunning,
-    isMissingFiatRate,
```
Comment (Lemonexe) [inline packages/suite/src/views/dashboard/PortfolioCard/PortfolioCardHeader.tsx:33]: the prop was never assigned..

File: packages/suite/src/views/dashboard/PortfolioCard/PortfolioCardHeader.tsx [hunk 2]
```diff
@@ -65,8 +63,7 @@ export const PortfolioCardHeader = ({
         }
     }
 
-    const valueLoading =
-        isDiscoveryRunning || isMissingFiatRate || (!discovery && !Number(fiatAmount));
+    const valueLoading = isDiscoveryRunning || (!discovery && isNaN(Number(fiatAmount)));
```
Comment (Lemonexe) [inline packages/suite/src/views/dashboard/PortfolioCard/PortfolioCardHeader.tsx:66]: I don't know when it can be not number, but `isNaN` will work, `!` does not work when exactly 0

**Review by vojtatranta — APPROVED** [review]
