### PR TITLE
Fix/3913 onboarding animation inconsistencies

### LINKED ISSUE #3913: Trezor model T hologram displayed during onboarding even when model One connected
**Describe the bug**
Trezor  T hologram displayed during onboarding even when Trezor model One is connected.

**Steps to reproduce:**
1. Start Suite 21.6.2
2. Connect not initialized device model One 
3. Hover over hologram tooltip

**Info:**
 - Suite version: desktop 21.6.2 (c0e30df7aa3c7b37e6f0a19b5201744a5de66a90)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.2 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.0 regular

**Screenshots:**

image

### LINKED ISSUE #3938: T1 bootloader instruction text vs animation inconsistency
**Describe the bug:**
The animation shows that only 1 button (on T1 >1.8.0) should be pressed to get into bootloader, but the text says to press both.

**Steps to reproduce:**
1. Update firmware
2. Read instructions

**Screenshots:**
Screenshot 2021-06-24 at 9 36 56

### PR DESCRIPTION
**Pull request by tomasklim**
closes #3913, #3938

1. Commit (c5cb738263d782866af707d49411f00672050964)
- device.features.model returns `'T' | '1'`
- our helper function which determines the model based on fw version returned `'T' | 'One'`
- I made it consistent. So now both return `'T' | '1'`

2. Commit (0d374da176bdca90d1b7abdd2f762fa7aff4b566)
- removing compare-versions library which do the same as semver lib which is already in the project

3. Commit (db0311681d392f22f2d54ba246731360208cb748)
- DeviceAnimation now accept device prop and shows animation type based on fw version instead of feature.model (because feature.model is not available in older devices)
- If device is not available, it fallbacks to `T` model. The only case when user sees T model animation is when device is not connected
Screenshot 2021-06-22 at 15 39 34

4. Commit (28da3d5f19998c84a84545f5d9182a255b364f6f)
- Fix incorrect bootloader text which says different instruction than animation
Screenshot 2021-06-24 at 11 55 56

5. Commit (110703535b1c6ca508408b57d3817c6404cfdff7)
- I moved T1 bootloader animation logic to the animation component to avoid possible future bugs if this animation is required somewhere else.

### CODE REVIEW

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx [hunk 1]
```diff
@@ -105,7 +105,11 @@ const Heading = styled(H1)`
     font-weight: ${variables.FONT_WEIGHT.DEMI_BOLD};
 `;
 
-const getTextForMode = (requestedMode: 'bootloader' | 'normal', deviceVersion: number) => {
+const getTextForMode = (
+    requestedMode: 'bootloader' | 'normal',
+    deviceModel: '1' | 'T',
+    deviceFwVersion: string,
+) => {
```
Comment (goodhoko) [inline packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: In the previous commit we refactored several components to take the whole device, instead of individual model and version params. Any reason not to do the same thing here?

**Review by goodhoko — APPROVED** [review]
Very nice set of clean-ups and fixes. I have one minor question.

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: I was thinking about it before but I decided not to do it. 

However, now it is changed (5d826e40b7a39fa598d27ad785d1ae084b5844ce)

Comment (goodhoko) [reply packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: ok. .) Resolving. Merge this when you're ready. .)

**Comment by tomasklim** [comment]
Together with implementation of @goodhoko's suggestion, I added 5th commit. So please check it again and shout/merge.

**Review by goodhoko — APPROVED** [review]
LGTM
