### PR TITLE
fix(wallet-utils): bump unstake eth tx

### LINKED ISSUE #16014: Unable to bump fee of unstake ETH if unstake amount > balance
**Describe the bug**

I cannot bump fee of unstaking tx when I want to unstake more than my current balance

**Info:**

-   Suite Version: 24.12.1

**How to reproduce**

1. Unstake more than your current balance
2. Try to bump fee

**Expected behavior**
It would allow me to unstake as the unstaking amount has nothing to do with my balance 

**Screenshots**

24.12.1

https://github.com/user-attachments/assets/32685e98-6799-4ab8-9e1a-14c2fe375d60

24.11.3
Screenshot 2024-12-17 at 21 20 51

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- allow user to bump fee of unstaking tx

## Related Issue

Resolve #16014

## Screenshots:
Before:
Screenshot 2025-06-02 at 15 17 39

Now:
Screenshot 2025-06-02 at 15 13 31
Screenshot 2025-06-02 at 15 13 37

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/unstaking-bump&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/unstaking-bump&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/unstaking-bump&lookback=7)

### CODE REVIEW

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 1]
```diff
@@ -617,7 +617,7 @@ const getEthereumRbfParams = (
 
     const { data, nonce, gasPrice, maxFeePerGas, maxPriorityFeePerGas } = tx.ethereumSpecific;
 
-    const ethereumData = data?.indexOf('0x') === 0 ? data.substring(2) : '';
+    const ethereumData = data ?? '';
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts:620]: this should not change anything

**Review by adderpositive — APPROVED** [review]
