### PR TITLE
Earn - Add DeFi Section to Tokens

### LINKED ISSUE #25636: EVM DeFi token section
~Waiting for BlockBook https://github.com/trezor/blockbook/issues/1428~

Use custom ETH backend https://blockbook-dev.corp.sldev.cz:9116/ (VPN required). (Make it backwards compatible so that suite does not crash without new BB version)

In Trezor Suite, because of stablecoin yield, we need to introduce new token section DeFi for EVM. This section will contain tokens which has ERC4626 extension. They should not be available in `Tokens` tab, only in `DeFi`. As it will not be released for all blockbooks in 26.4. Please show this section only if there are some tokens available

Design: [Figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=4900-10904&m=dev)

https://blockbook-dev.corp.sldev.cz:9116/api/address/0x21c6FbB3E5dEEa96ec940f1166922A10d062df12?details=tokenBalances&includeErc4626=true

Image

Desktop for now, mobile coming later with https://www.notion.so/satoshilabs/Mobile-Better-token-management-2b8dc5260606809abdc2c263b4844bc9?source=copy_link

### LINKED ISSUE #25637: Add info about ERC4626 into send form
~Waiting for blockbook and https://github.com/trezor/trezor-suite/issues/25636~

use https://blockbook-dev.corp.sldev.cz:9116/ (make it backwards compatible so that suite does not crash without new blockbook version)

Add banner to send form on desktop and mobile when token has ERC4626 extension

Design: [Figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=4900-12212&m=dev)

Image

Image

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

- add new `DeFi` section to account tokens with supply/withdraw buttons.
- add DeFi token banner to send form

## Related Issue

Resolve #25636 
Resolve #25637 

## Screenshots

Screenshot 2026-04-20 at 16 45 12

Screenshot 2026-04-22 at 11 02 45

Screenshot 2026-04-22 at 11 06 04

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/defi&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/defi&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/defi&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 29 test(s)</summary>

| Test | Type |
|------|------|
| Trading - Swap history > View swap order history details | 🤖 auto |
| Trading - Buy Negative scenarios > Buy form handles input limits and empty quotes | 🤖 auto |
| Trading - Buy Ethereum > Enable Ethereum on account by buying it | 🤖 auto |
| Trading - Buy Solana > Buy Solana Jupiter token - amount specified in crypto | 🤖 auto |
| Trading - Swap token to disabled network asset > Show provider info for disabled network asset XLM | 🤖 auto |
| Trading - Swap tokens > Swap Solana tokens | 🤖 auto |
| Send - Solana > Send max | 🤖 auto |
| Trading - Swap coins > Swap Solana to Bitcoin | 🤖 auto |
| Trading - Sell Solana > Sell Solana | 🤖 auto |
| Trading - Sell Solana > Sell Solana for compared offer | 🤖 auto |
| Trading - Swap coin to token > Swap Solana to USDC | 🤖 auto |
| Trading - Swap token to coin > Swap Solana Tether token to Bitcoin | 🤖 auto |
| sol staking > first stake on SOL account | 🤖 auto |
| sol staking > display stake rewards on SOL staking account | 🤖 auto |
| sol staking > stake more on SOL account | 🤖 auto |
| sol staking > unstake and claim on SOL account | 🤖 auto |
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-22T10:05:40.585Z • 29 test(s) total_

<details><summary>Trezor Suite (desktop) — 12 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Global receive and send,Global receive" | 🙋 manual |
| Bridge > App acquired device, EXTERNAL bridge is restarted, app reconnects | 🤖 auto |
| Bridge > App spawns bundled bridge and stops it after app quit | 🤖 auto |
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Onboarding - create wallet > Success (basic) | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-22T12:06:42.230Z • 12 test(s) total_

## 🌐 Preview deployments

🌐 **Suite Web preview:** [https://dev.suite.sldev.cz/suite-web/feat/defi/web/](https://dev.suite.sldev.cz/suite-web/feat/defi/web/)

### CODE REVIEW

File: packages/blockchain-link-types/src/blockbook-api.ts [hunk 1]
```diff
@@ -308,6 +308,8 @@ export interface Token {
     totalReceived?: string;
     /** Total amount of tokens sent. */
     totalSent?: string;
+    /** Data containing information about the ERC4626 vault token. */
+    erc4626?: any;
```
Comment (TomasBoda) [inline packages/blockchain-link-types/src/blockbook-api.ts]: This needs to be replaced by appropriate type instead of `any`

File: packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx [hunk 2]
```diff
@@ -37,7 +37,12 @@ export const AccountNavigation = () => {
             },
             title: <Translation id="TR_NAV_TOKENS" />,
             isHidden: !hasNetworkFeatures(account, 'tokens'),
-            activeRoutes: ['wallet-tokens', 'wallet-tokens-hidden', 'wallet-tokens-inactive'],
+            activeRoutes: [
+                'wallet-tokens',
+                'wallet-tokens-hidden',
+                'wallet-tokens-inactive',
+                'wallet-tokens-defi',
+            ],
```
Comment (cermakjiri) [inline packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx:45]: What about placing it somewhere to common place as constant?

File: packages/suite/src/views/wallet/tokens/defi/DefiTokensTable.tsx [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        fiatRates,
+    );
+    const sortedTokens = tokensWithRates.sort(sortTokensWithRates);
+
+    const tokens = getTokens({
+        tokens: sortedTokens,
+        symbol: account.symbol,
+        tokenDefinitions: coinDefinitions,
+        searchQuery,
+    });
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/tokens/defi/DefiTokensTable.tsx]: This is very suitable for useMemo (or memoize selector, however we know how well they work 😄 ). Also, could be divided for two because of the `searchQuery`:
```ts
    const erc4626Tokens = account.tokens?.filter(isErc4626);

    const tokensWithRates = enhanceTokensWithRates(
        erc4626Tokens,
        baseCurrencyCode,
        account.symbol,
        fiatRates,
    );
    const sortedTokens = tokensWithRates.sort(sortTokensWithRates);
```
and the 2nd one:
```ts
    const tokens = getTokens({
        tokens: sortedTokens,
        symbol: account.symbol,
        tokenDefinitions: coinDefinitions,
        searchQuery,
    });
```

File: packages/suite/src/views/wallet/tokens/coins/CoinsTable.tsx [hunk 4]
```diff
@@ -24,11 +24,12 @@ export const CoinsTable = ({ selectedAccount, searchQuery }: CoinsTableProps) =>
     const baseCurrencyCode = useSelector(selectBaseCurrency);
 
     const { account, network } = selectedAccount;
+    const accountTokens = account.tokens?.filter(token => !isErc4626(token));
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/tokens/coins/CoinsTable.tsx]: similar here (useMemo https://github.com/trezor/trezor-suite/pull/26344/changes#r3027690127) 🙏

File: packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx [hunk 5]
```diff
@@ -104,6 +107,9 @@ export const TokenRow = ({
     const isDeviceLocked = isLocked(true);
     const isDeviceCompromised = useSelector(selectIsDeviceCompromised);
     const [showDeactivateModal, setShowDeactivateModal] = useState(false);
+    const { yieldOpportunities } = useAllYieldOpportunities();
```
Comment (izmy) [inline packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx]: `useAllYieldOpportunities()` is now called from every `TokenRow`, including non-ERC4626 tokens. That means opening the regular token list will trigger the yield opportunities query even when DeFi is not used. Can you move this higher up or only enable it for ERC4626 rows?

File: packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx [hunk 6]
```diff
@@ -244,266 +295,289 @@ export const TokenRow = ({
...
-                                    onClick: () => {
-                                        goToWithAnalytics({
-                                            routeName: 'wallet-send',
-                                            params: {
-                                                symbol: account.symbol,
-                                                accountIndex: account.index,
-                                                accountType: account.accountType,
-                                            },
-                                        });
+                {!isErc4626Token ? (
```
Comment (izmy) [inline packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx]: It would be much better to create a component for actions, something like `TokenRowActions`, wdyt?

**Review by izmy — CHANGES_REQUESTED** [review]

File: suite/intl/src/messages.ts [hunk 7]
```diff
@@ -1758,6 +1758,15 @@ export const messages = defineMessages({
...
         id: 'TR_HIDDEN',
     },
+    TR_DEFI: {
+        defaultMessage: 'DeFi',
+        id: 'TR_DEFI',
+    },
+    TR_DEFI_BANNER_TEXT: {
+        id: 'TR_DEFI_BANNER_TEXT',
+        defaultMessage:
+            'These tokens represent your position. Sending or swapping them will also remove your positions.',
```
Comment (tomasklim) [inline suite/intl/src/messages.ts]: TODO: weird sentence

**Review by tomasklim — COMMENTED** [review]
migration is missing, users launching new version of app need to refetch tokens

maybe it will be auto solved by `isAccountOutdated` comment

File: packages/suite/src/views/wallet/tokens/defi/DefiTokensTable.tsx (hunk 3 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/tokens/defi/DefiTokensTable.tsx]: done

File: packages/suite/src/views/wallet/tokens/coins/CoinsTable.tsx (hunk 4 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/tokens/coins/CoinsTable.tsx]: done

File: packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx (hunk 5 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx]: done, moved higher up

File: packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx (hunk 6 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx]: agreed, done

File: packages/blockchain-link-types/src/blockbook-api.ts (hunk 1 above)
Comment (tomasklim) [reply packages/blockchain-link-types/src/blockbook-api.ts]: Will be deployed this week by Jakub Liška. In case of any changes needed, there is still time. 

```
{
  "erc4626": {
    "asset": { "contract": "...", "name": "...", "symbol": "...", "decimals": 18 },
    "share": { "contract": "...", "name": "...", "symbol": "...", "decimals": 18 },
    "totalAssets": "...",
    "convertToAssets1Share": "...",
    "convertToShares1Asset": "...",
    "previewDeposit1Asset": "...",
    "previewRedeem1Share": "...",
    "error": "..."
  }
}
```

**Review by tomasklim — COMMENTED** [review]
`erc4626` info is not persisted

**Review by tomasklim — CHANGES_REQUESTED** [review]
In hidden section, there is missing `Show`, `...`.
I would add `+ Supply`, `- Withdraw` to `...` 
Image

In this section, there is `...` missing. I would add `send` and `receive` into `...`. User will have `send` warning in send form so ok
Image

@matous-jemelka

File: suite/intl/src/messages.ts (hunk 7 above)
Comment (tomasklim) [inline suite/intl/src/messages.ts]: I would do
`These tokens represent your DeFi positions. Sending or swapping them will transfer ownership of those positions.`

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx [hunk 8]
```diff
@@ -31,14 +33,27 @@ type SubTabItem = {
...
             onClick: goToRoute(isNft ? 'wallet-nfts' : 'wallet-tokens'),
-            count: tokens.shownWithBalance.length,
+            count: normalTokens.length,
             labelId: isNft ? 'TR_NAV_COLLECTIONS' : 'TR_NAV_TOKENS',
         },
+        ...(erc4626Tokens.length
+            ? [
+                  {
+                      id: 'wallet-tokens-defi',
+                      iconName: 'percent',
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/tokens/TokensNavigation.tsx:50]: imo the `percent` icon is weird @matous-jemelka 

Image

how about some coins with droplets?
Image

File: suite-common/wallet-core/src/accounts/accountsThunks.ts [hunk 9]
```diff
@@ -122,6 +122,7 @@ export const fetchAndUpdateAccountThunk = createThunk(
             page: 1, // useful for every network except ripple and stellar
             pageSize,
             suppressBackupWarning: true,
+            includeErc4626: account.networkType === 'ethereum' ? true : undefined,
```
Comment (tomasklim) [inline suite-common/wallet-core/src/accounts/accountsThunks.ts:137]: `isAccountOutdated` has to be extended to support updating `erc4626`

However, i am worried of spamming backends because the price there is changing, let's discuss on call

**Comment by tomasklim** [comment]
`7d change column` does not make sense here, please remove. It will always be something like `0.05%`

**Comment by tomasklim** [comment]
I think some fetches do not use `includeErc4626=true` because `DeFi` section sometimes dissapears

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx (hunk 8 above)
Comment (matous-jemelka) [reply packages/suite/src/views/wallet/tokens/TokensNavigation.tsx:50]: I liked it the most from the stuff I was considering and is available our iconset, since with DeFi you are always seeking some ROI (%). See attached examples.

Creating new icon isn't something we want to deal with at this point. Too much hassle. 

image

File: suite-common/wallet-core/src/accounts/accountsThunks.ts (hunk 9 above)
Comment (TomasBoda) [reply suite-common/wallet-core/src/accounts/accountsThunks.ts:137]: created a db migration that resets Ethereum account nonces to `-1`, as discussed on call

File: packages/blockchain-link-types/src/common.ts [hunk 10]
```diff
@@ -322,6 +322,7 @@ export interface TokenInfo {
     accounts?: TokenAccount[];
     policyId?: string;
     fingerprint?: string;
+    erc4626?: any;
```
Comment (tomasklim) [inline packages/blockchain-link-types/src/common.ts]: `any`

File: packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRowActions.tsx [hunk 11]
```diff
@@ -0,0 +1,653 @@
...
+import type { TokensTableType } from './types';
+
+interface TokenRowYieldActionsProps {
+    token: EnhancedTokenInfo;
+    account: Account;
+    network: Network;
+    yieldOpportunities?: YieldDto[];
+}
+
+const TokenRowYieldActions = ({
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRowActions.tsx]: I would not introduce special actions for yield. Please keep everything what is for normal tokens there and just add Send and Receive to `...`

- add everything from the tooltip also here
Image
Image

**Review by tomasklim — DISMISSED** [review]

File: packages/blockchain-link-types/src/common.ts (hunk 10 above)
Comment (TomasBoda) [reply packages/blockchain-link-types/src/common.ts]: done

File: packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRowActions.tsx (hunk 11 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRowActions.tsx]: done

Comment (TomasBoda) [reply packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRowActions.tsx]: Screenshot 2026-04-22 at 11 02 45

**Review by cermakjiri — APPROVED** [review]

**Review by izmy — APPROVED** [review]

File: packages/blockchain-link-types/src/blockbook-api.ts (hunk 1 above)
Comment (TomasBoda) [reply packages/blockchain-link-types/src/blockbook-api.ts]: done: updated types
