### PR TITLE
Hotfix/everstake api validators

### LINKED ISSUE #25547: Validate structure of data from external endpoints
To prevent issues with API changes, please validate structure of staking data fetched from our external partners (Everstake). In case of error, report it to sentry but do not break app. It is better when e.g. APY is not available than crashed app

https://satoshilabs.slack.com/archives/C0543DJBK0C/p1771955395136659

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

- Validate API responses from Everstake APIs with Zod schemas. Validation errors are reported to Sentry.
- Use those schemas to infer types.
- There's avail. OpenAPI spec only for everstake eth b2c API (generate Zod schemas with Orval only for this one), use LLM / manual changes to create Zod schemas for rest of those APIs.
- Place it in a new package `@suite-common/wallet-api` to prevent cir. dep. with zero deps.

## Commits

* refactor: infer some types from schemas in staking
* refactor: move everstake api schema and types to @suite-common/wallet-api to prevent cir. dep.
* feat: add Everstake APIs response validations
* feat(suite-common-wallet-core): fetch everstake eth b2c api spec and generate zod schemas

## Notes for QA

Staking page should load without any issue: ETH, ADA, SOL.

## Related Issue

Resolve #25547

### Validation error (i.e. Suite receives invalid data from the API)
The UI doesn't break, nor there's some weird error message: "TypeError: ...".

Snímek obrazovky 2026-03-02 v 14 44 31
Snímek obrazovky 2026-03-02 v 14 44 35

### Staking pages successfully load:
Snímek obrazovky 2026-03-02 v 14 33 27

Snímek obrazovky 2026-03-02 v 14 12 12
Snímek obrazovky 2026-03-02 v 14 14 58

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=hotfix/everstake-api-validators&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=hotfix/everstake-api-validators&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=hotfix/everstake-api-validators&lookback=7)

## 🔍 Currents Test Results

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=hotfix/everstake-api-validators&lookback=7)

### CODE REVIEW

File: suite-common/wallet-api/scripts/fetchSpec.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+    }
+}
+
+async function fetchSpec(
+    swaggerUrl: string,
+    fileType: NonNullable<ReturnType<typeof getFileType>>,
+) {
+    const response = await fetch(swaggerUrl, {
+        headers: {
+            Accept: fileType === 'json' ? 'application/json' : 'application/yaml',
```
Comment (TomasBoda) [inline suite-common/wallet-api/scripts/fetchSpec.ts:25]: For now this is fine, but for future changes, I'd rather create a function with a `switch` that returns the correct `Accept` string for the given `fileType`. WDYT?

File: suite-common/wallet-api/src/stake/schemas/everstake-eth-b2c.ts [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+        .number()
+        .describe('Delay in seconds before validator become known at Beacon chain'),
+    updated_at: zod.number().describe('Timestamp of last values update'),
+});
+
+/**
+ * @summary Account transactions
+ */
+export const AccountTransactionsParams = zod.object({
+    account: zod.string().describe('Account ID'),
```
Comment (TomasBoda) [inline suite-common/wallet-api/src/stake/schemas/everstake-eth-b2c.ts:56]: nitpick: `accountId` instead of `account`?

File: suite-common/staking/src/utils/ethereumStaking.ts [hunk 3]
```diff
@@ -568,9 +569,9 @@ export const getDaysToAddToPool = (
 
 export const getDaysToUnstake = (
     unstakeTxs: WalletAccountTransaction[],
-    validatorsQueue?: EthereumValidatorsQueue,
+    validatorsQueue?: EthereumValidatorsQueue | null,
 ) => {
-    if (validatorsQueue?.validatorWithdrawTime === undefined) {
+    if (!validatorsQueue || validatorsQueue?.validatorWithdrawTime === undefined) {
```
Comment (TomasBoda) [inline suite-common/staking/src/utils/ethereumStaking.ts]: Can we simply do `!validatorsQueue?.validatorWithdrawTime` ?

File: suite-common/wallet-core/src/stake/stakeThunks.ts [hunk 4]
```diff
@@ -36,12 +38,77 @@ import { selectEverstakeData } from './stakeSelectors';
...
+
+    if (!response.ok) {
+        throw Error(response.statusText);
+    }
+
+    const data = await response.json();
+    const { apr, next_reward_payout_in = 0 } = PoolStatsResponse.parse(data);
+
+    return {
+        ethApy: Number(new BigNumber(apr).times(100).toPrecision(3, BigNumber.ROUND_DOWN)),
```
Comment (TomasBoda) [inline suite-common/wallet-core/src/stake/stakeThunks.ts:92]: nitpick: `new BigNumber(apr).times(100).toPrecision(3, BigNumber.ROUND_DOWN).toNumber()`

File: suite-common/wallet-api/scripts/fetchSpec.ts (hunk 1 above)
Comment (cermakjiri) [reply suite-common/wallet-api/scripts/fetchSpec.ts:25]: Swagger files are either in yaml or json. It should be fine.

File: suite-common/wallet-api/src/stake/schemas/everstake-eth-b2c.ts (hunk 2 above)
Comment (cermakjiri) [reply suite-common/wallet-api/src/stake/schemas/everstake-eth-b2c.ts:56]: These ones are generated from the OpenAPI spec. Ideally, we would want to update the original OpenAPI spec in Everstake repo.

File: suite-common/staking/src/utils/ethereumStaking.ts (hunk 3 above)
Comment (cermakjiri) [reply suite-common/staking/src/utils/ethereumStaking.ts]: This wouldn't work for `0` but I'll change it to `typeof validatorsQueue?.validatorWithdrawTime !== 'number'`

File: suite-common/wallet-core/src/stake/stakeThunks.ts (hunk 4 above)
Comment (cermakjiri) [reply suite-common/wallet-core/src/stake/stakeThunks.ts:92]: good point 👍

Comment (cermakjiri) [reply suite-common/wallet-core/src/stake/stakeThunks.ts:92]: Oh, it isn't actually possible:

Snímek obrazovky 2026-03-10 v 7 50 02

File: suite-common/wallet-api/scripts/fetchSpec.ts (hunk 1 above)
Comment (cermakjiri) [reply suite-common/wallet-api/scripts/fetchSpec.ts:25]: In general, I think we should have some kind of abstraction layer build around `fetch` API. The same code repeats in many places in the codebase (parsing the res., constructing URL with uri/search params, etc), a http client would solve it.

**Comment by cermakjiri** [comment]
The failing unit test (nx run @suite-common/connect-init:test:unit) succeeded locally. Also, it doesn't seem related to any change in this PR.

File: suite-common/wallet-api/scripts/fetchSpec.ts (hunk 1 above)
Comment (TomasBoda) [reply suite-common/wallet-api/scripts/fetchSpec.ts:25]: I see, then i'm fine with it. I agree with the wrapper around `fetch`. we can create an issue for it

File: suite-common/wallet-api/src/stake/schemas/everstake-eth-b2c.ts (hunk 2 above)
Comment (TomasBoda) [reply suite-common/wallet-api/src/stake/schemas/everstake-eth-b2c.ts:56]: alright, resolving this comment

File: suite-common/wallet-api/scripts/fetchSpec.ts (hunk 1 above)
Comment (cermakjiri) [reply suite-common/wallet-api/scripts/fetchSpec.ts:25]: True, I'm going to do it, else it will fade it in the past

File: suite-common/wallet-core/src/stake/stakeThunks.ts (hunk 4 above)
Comment (TomasBoda) [reply suite-common/wallet-core/src/stake/stakeThunks.ts:92]: oh, I see, okay then :)

**Review by TomasBoda — APPROVED** [review]

File: suite-common/wallet-api/scripts/fetchSpec.ts (hunk 1 above)
Comment (cermakjiri) [reply suite-common/wallet-api/scripts/fetchSpec.ts:25]: https://github.com/trezor/trezor-suite/issues/25833
