### PR TITLE
Speed up fee of evm token & approval tx

### LINKED ISSUE #22601: RBF broken for ERC-20 approve
If you have a stuck EC-20 approve TX, it's not possible to do RBF on it. 
Compose will fail on this condition: 

https://github.com/trezor/trezor-suite/blob/e23faf16dbe93befaea3deec4ddd4a3eff52a401/suite-common/wallet-core/src/send/sendFormEthereumThunks.ts#L161-L166

### LINKED ISSUE #22871: Gas limit too low on replace transaction for token send (DAI) causes failure
**Describe the bug**
When attempting to replace a token transaction (sending DAI), the transaction fails due to the gas limit being set too low. 

**Info:**
 - Suite version: desktop 25.11.0 (f489285232575f9a891824ddc8e3161d088bfa8e)
 - Browser: Trezor Suite 25.11.0
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3W1 2.9.4 universal (revision c49d212db01a57177550aa46836c14f5ee584f01)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0
 
**How to reproduce**

1. Go to token send and attempt to replace an existing DAI transaction
2. Approve the replacement transaction
3. Confirm and broadcast
4. See the transaction fail due to gas limit https://etherscan.io/tx/0x5b51c3445f05f1b37a215ab12e64635e067d8bebb42c7d86e0f6e48658dc763a

**Expected behavior**
The replacement transaction should succeed and the gas limit should be set high enough for DAI token transfers.

**Screenshots**
Transaction failed screenshot

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

⚠️ THIS PR fixes the issues but it does not make Suite perfect. I think we should stop using `token` on tx and just use tx data. It is a huge mess ⚠️ 

- remove double token in total in sent total
- fix speed up of approval/revoke tx
- fix speed up of token tx

## Notes for QA

- check all kinds of EVM txs
- check all kinds of speed ups on EVM (token, staking, swap, classic)

Replace tx of sending token does not show token amount, the logic should be improved. Now it is a mess

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/22601
Resolve #22871 

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/approve-bump-fee&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/approve-bump-fee&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/approve-bump-fee&lookback=7)

### CODE REVIEW

File: suite-common/wallet-utils/src/ethUtils.ts [hunk 1]
```diff
@@ -68,13 +78,46 @@ export const getEvmApprovalTxData = (data?: string): EvmApprovalTxData | null =>
     }
 };
 
+export const getEvmTransferTxData = (data?: string): EvmTxTransferData | null => {
+    if (!data) return null;
+
+    const d = normalizeHex(data);
```
Comment (matusbalascak) [inline suite-common/wallet-utils/src/ethUtils.ts:84]: nitpick; maybe we can use better name here? `data` -> `rawData`, `d` -> `data` or `normalizedData` or whatever.. just something that can be understood later in the code?

**Review by matusbalascak — APPROVED** [review]
