### PR TITLE
Fix: feerate

### LINKED ISSUE #3336: Send dialogue - Inconsistent fee info
**Describe the bug**
See screens and gif I recorded, I selected 1 sat/b in send dialogue but in confirmation dialogue it's 4 sat/b.
Both dialogues have same fee displayed 645 sat but rate is different.
This happens only when you try to send funds from B32 account, Segwit and Legacy accounts works fine.
This only happens when you set manually see to 1 sat/b

**Steps to reproduce:**
1. go to Bech32 account send dialogue
2. Change fee to 1 sat/b
3. press Review and Send button and check fee

**Info:**
 - Suite version: desktop 21.2.1 (c2448b3a66c2850c2a99acc8574edadf5771d565)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Expected result:**
Send dialogue and confirm transaction display same fee rate
**Actual result:**
Some send dialogue and confirm dialogue have different fee rates

**Screenshots:**
fee

image

image

### PR DESCRIPTION
**Pull request by szymonlesisz**
should fix #3336

additional changes:

- hide rbf form if tx is not possible to bump (missing change output)
Screenshot from 2021-02-05 14-09-20

- add missing size in FeeDetail (btc only)
- fixed decimals validation in getFeeRate util

### CODE REVIEW

File: packages/suite/src/utils/wallet/transactionUtils.ts [hunk 1]
```diff
@@ -301,9 +301,9 @@ export const isTxUnknown = (transaction: WalletAccountTransaction) => {
     );
 };
 
-export const getFeeRate = (tx: AccountTransaction, convertToDecimals?: number) => {
+export const getFeeRate = (tx: AccountTransaction, decimals?: number) => {
     // calculate fee rate, TODO: add this to blockchain-link tx details
-    const fee = convertToDecimals ? amountToSatoshi(tx.fee, convertToDecimals) : tx.fee;
+    const fee = typeof decimals === 'number' ? amountToSatoshi(tx.fee, decimals) : tx.fee;
```
Comment (slowbackspace) [inline packages/suite/src/utils/wallet/transactionUtils.ts:306]: just quick question, shouldn't it be handled by typescript, when you pass something other than a number then type-check will fail right? Or is there added advantage in doing manual check?
