### PR TITLE
fix(suite-native): Mobile Trade: do not display simplex provider

### LINKED ISSUE #19143: Mobile Trade: discard simplex quotes
As we currently do not support Simplex on mobile we should never display it to user.

## ACs
- when quotes are received, filter out all quotes with `exchange` simplex.
- Simplex is never displayed to user

### LINKED ISSUE #19171: Mobile Buy: Do not show Apple Pay quotes on android
When the app runs on android, do not show quotes with Apple Pay method

### PR DESCRIPTION
**Pull request by jbazant**
## Description

- Simplex provider is not supported in mobile trading. Never display it to user
- Also filtering out apple pay on android devices

## Related Issue

Resolve #19143
Resolve #19171

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=19143-mobile-trade-no-simplex&lookback=7)

### CODE REVIEW

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/module-trading/src/components/buy/BuyProviderPicker.tsx [hunk 1]
```diff
@@ -2,18 +2,15 @@ import { useSelector } from 'react-redux';
...
-    selectTradingBuyProviders,
-} from '@suite-common/trading';
+import { selectTradingBuyIsLoading, selectTradingBuyProviders } from '@suite-common/trading';
 import { EventType, analytics } from '@suite-native/analytics';
 import { HStack, Text } from '@suite-native/atoms';
 import { useTranslate } from '@suite-native/intl';
 
 import { useBuyFormContext } from '../../hooks/buy/useBuyFormContext';
 import { useSheetControls } from '../../hooks/general/useSheetControls';
+import { selectMobileBuyQuotesByPaymentMethod } from '../../selectors/buySelectors';
```
Comment (vytick) [inline suite-native/module-trading/src/components/buy/BuyProviderPicker.tsx]: Can we use native instead to have naming same with the project? Smthng like
```suggestion
import { selectBuyQuotesByPaymentMethodNative } from '../../selectors/buySelectors';
```

File: suite-native/module-trading/src/selectors/buySelectors.ts [hunk 2]
```diff
@@ -99,12 +101,17 @@ export const selectBuySupportedFiatCurrenciesList = createMemoizedSelector(
 export const selectBuyAmountLimits = (state: TradingRootState) =>
     selectTradingBuy(state).amountLimits;
 
-export const selectBuyBestQuotesForAvailablePaymentMethods = createMemoizedSelector(
+export const selectValidMobileTradingBuyQuotes = createMemoizedSelector(
```
Comment (vytick) [inline suite-native/module-trading/src/selectors/buySelectors.ts]: something like?
```suggestion
export const selectValidTradingBuyQuotesNative = createMemoizedSelector(
```

File: suite-native/module-trading/src/selectors/buySelectors.ts [hunk 3]
```diff
@@ -127,3 +134,17 @@ export const selectBuyBestQuotesForAvailablePaymentMethods = createMemoizedSelec
         ) as BuyTrade[];
     },
 );
+
+export const selectMobileBuyQuotesByPaymentMethod = createMemoizedSelector(
```
Comment (vytick) [inline suite-native/module-trading/src/selectors/buySelectors.ts]:
```suggestion
export const selectBuyQuotesByPaymentMethodNative = createMemoizedSelector(
```

**Review by vytick — APPROVED** [review]
works nicely 👌

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/module-trading/src/selectors/buySelectors.ts [hunk 4]
```diff
@@ -99,12 +103,25 @@ export const selectBuySupportedFiatCurrenciesList = createMemoizedSelector(
...
     [
-        selectTradingBuyQuotes as unknown as (
+        selectValidTradingBuyQuotes as unknown as (
             state: TradingRootState,
-        ) => ReturnType<typeof selectTradingBuyQuotes>,
+        ) => ReturnType<typeof selectValidTradingBuyQuotes>,
     ],
+    quotes => {
+        const isValidNativeQuote =
+            Platform.OS === 'ios'
```
Comment (vytick) [inline suite-native/module-trading/src/selectors/buySelectors.ts]: thought: this feels complicated on a first sight so maybe splitting it to two booleans might make it more readable.

I dont have a really strong opinion on this, so if you do not agree, feel free to resolve this comment.

**Review by vytick — APPROVED** [review]
It works nicely 👌. I have one thought about readability, but looks good otherwise.

File: suite-native/module-trading/src/selectors/buySelectors.ts (hunk 4 above)
Comment (jbazant) [reply suite-native/module-trading/src/selectors/buySelectors.ts]: Updated to improve readability

**Review by vytick — APPROVED** [review]
👌
