### PR TITLE
fix(coinmarket): switch off coinjoin

### LINKED ISSUE #14303: Coinmarket - Disable coinjoin account in trade section
**Describe the bug**
Disable coinjoin account in trade section when trying to buy BTC.
Its useless and it crashes app in next steps

**Steps to reproduce:**
1. Navigate to Trade/Buy section
2. Select bitcoin
3. Select add new account
4. Coinjoin account is available to add

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**
image

image

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
 Disable coinjoin account in the trade section when trying to buy/exchange BTC. Also if a coinjoin account is already active, it will not be visible in the select list of discovered accounts.

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/14303

### CODE REVIEW

**Review by Hermez-cz — APPROVED** [review]
Thanks, I can't see how it looks like, but it makes sense and all the code changes look like it will simply be gone 👍

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx [hunk 1]
```diff
@@ -116,7 +123,8 @@ export const AddAccountModal = ({ device, onCancel, symbol, noRedirect }: AddAcc
              * By default it is visible publicly, but it can be remotely hidden under debug menu.
              */
             .filter(({ backendType }) => backendType !== 'coinjoin' || isCoinjoinVisible)
-            .filter(({ isDebugOnlyAccountType }) => !isDebugOnlyAccountType || isDebug);
+            .filter(({ isDebugOnlyAccountType }) => !isDebugOnlyAccountType || isDebug)
+            .filter(({ accountType }) => (isCoinjoinDisabled ? accountType !== 'coinjoin' : true));
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx]: Nit: This seems fine but I think it would be better readable if there was only one `.filter` that concerns coinjoin, rather than having two. How about doing this at line 112?
`const isCoinjoinVisible = (isCoinjoinPublic || isDebug) && !isCoinjoinDisabled;`

Note: current filter filters by `backendType`, not `accountType`, but with our data this is equivalent :heavy_check_mark:

**Review by Lemonexe — APPROVED** [review]
Codewise LGTM, does what it's supposed to, just one comment :rocket: 

Btw you can still sell & swap _from_ existing coinjoin accounts. I assume we don't want to remove that? Just checking.
EDIT: removed.

**Review by Lemonexe — APPROVED** [review]
Thanks for implementing the modal bugfix here

**Review by tomasklim — APPROVED** [review]
