### PR TITLE
fix(suite-native): add isReady check to NavigationRef

### LINKED ISSUE #22067: Investigate Sentry issues "The 'navigation' object hasn't been initialized yet."
There are multiple navigation related issues reported in Sentry in 25.9.3, [see in Sentry](https://satoshilabs.sentry.io/issues/views/177564/?environment=production&project=4504214699245568&query=is%3Aunresolved%20release.version%3A25.9.3%20navigation&referrer=issue-list&sort=date&statsPeriod=30d).

Those are reported when the app is in background!

It might be easy to handle this case by adding `.isReady()` check on the navigation ref, see:
https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization

[Internal notes](https://www.notion.so/satoshilabs/Sentry-Mobile-Crashlytics-e00e823e84a34024b908c696dcffe5d0?source=copy_link#27fdc526060680a18b96fa30f9a5ffdc)

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

 add `isReady` check to NavigationRef to prevent background calls

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22067

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/nav-ref-handling&lookback=7)

### CODE REVIEW

File: suite-native/device/src/hooks/useDetectDeviceError.tsx [hunk 1]
```diff
@@ -240,7 +240,8 @@ export const useDetectDeviceError = () => {
             shouldFactoryResetBeVisible &&
             !isFirmwareInstallationRunning &&
             !wasDeviceEjectedByUser &&
-            isOnboardingFinished
+            isOnboardingFinished &&
+            navigationContainerRef.isReady()
```
Comment (juriczech) [inline suite-native/device/src/hooks/useDetectDeviceError.tsx:244]: Actually I have no idea why this is not using `useNavigation()`. I think it's a mistake and it should.

File: suite-native/device/src/middlewares/deviceConnectionMiddleware.ts [hunk 2]
```diff
@@ -59,6 +59,7 @@ const handleDeviceConnectNavigation = ({
     isDeviceSetupSupported: boolean;
     wasDeviceOnboardingCancelled: boolean;
 }) => {
+    if (!navigationContainerRef.isReady()) return;
```
Comment (juriczech) [inline suite-native/device/src/middlewares/deviceConnectionMiddleware.ts:62]: Unnecessary, it's already handled in the middleware that calls it. I would either keep it here and pass it in the middleware before navigation to CompromisedDevice, or just keep the one at the beginning of the middleware maybe 🤔 Not a biggie though, since at least it will be handled if we call this from other place too.

File: suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx [hunk 3]
```diff
@@ -53,11 +53,15 @@ export const NavigationContainerWithAnalytics = ({ children }: { children: React
     }, [colors, isDarkColor]);
 
     const handleNavigationReady = () => {
+        if (!navigationContainerRef.isReady()) return;
```
Comment (juriczech) [inline suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx]: I would be very surprised if this is ever fulfilled, as it's passed as `onReady` handler in the JSX 🤣

**Review by juriczech — APPROVED** [review]
Some of these conditions feel redundant, but it's not a blocker for me.

File: suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx (hunk 3 above)
Comment (BrantalikP) [reply suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx]: oh yeh, its true. I was just paranoid, when it was calling `navigationContainerRef.getCurrentRoute()`, because I think Ive seen an error in sentry related to this calling

Comment (BrantalikP) [reply suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx]: oh ive mistaken it with navigationContainerRef.getState() going to remove it, good catch
