### PR TITLE
fix(suite): fix pin input styles

### LINKED ISSUE #22930: THP pairing code inputs are not well readable
@Lemonexe 

>THP pairing code entry on Suite Desktop/Web: it's easy to accidentally click or press Tab and I start writing the code from the 2nd field. Then I am puzzled why can't I write the 6th digit.
In a bad contrast environemnt it's easy to miss that there is an empty 1st field.
Suggestion: either increase contrast, or force code entry from beginning.
What do you think?

Image

Right design: https://www.figma.com/design/yl2g0XLU9iIgJsrxSOqkS9/Bluetooth---THP--Final-?node-id=2212-16826&t=jtq6nVf933ENzyl5-11

### PR DESCRIPTION
**Pull request by OriginalEveres**
Fixed the styles for the pin input.

## Notes for QA

**How to test**:
1. start suite
2. connect THP non paired device
3. see the modal with THP pairing code

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22930

## Screenshots:
Before:
Screenshot 2025-11-05 at 16 06 36

After:
Screenshot 2025-11-05 at 16 06 49
Screenshot 2025-11-06 at 13 00 14
Screenshot 2025-11-06 at 13 09 03
Screenshot 2025-11-06 at 13 09 11

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/pair-input-style&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/pair-input-style&lookback=7)

### CODE REVIEW

File: packages/components/src/components/PinInput/PinInput.tsx [hunk 1]
```diff
@@ -10,6 +10,8 @@ import { baseInputDisabledStyle, baseInputStyle } from '../form/styles';
 
 const SymbolBox = styled.input<{ $elevation: Elevation; $fakeDisabled?: boolean }>`
     ${baseInputStyle};
+    background-color: #f2f2f2; // this color does not exist in the theme yet TODO: implement in the theme
```
Comment (vojtatranta) [inline packages/components/src/components/PinInput/PinInput.tsx]: @seibei-iguchi pls pls, would you recommend us how to make it properly?

**Review by vojtatranta — APPROVED** [review]
I am approving so taht it is mergable, but like I am not sure about the Dark theme, I guess sit will be broken there as the bordr has the same color.  I think the color has to be set properly for both themes

File: packages/components/src/components/PinInput/PinInput.tsx (hunk 1 above)
Comment (seibei-iguchi) [reply packages/components/src/components/PinInput/PinInput.tsx]: Use theme.baseFillElementNeutralSoft

Comment (vojtatranta) [reply packages/components/src/components/PinInput/PinInput.tsx]: cc @OriginalEveres

Comment (OriginalEveres) [reply packages/components/src/components/PinInput/PinInput.tsx]: done

**Review by seibei-iguchi — APPROVED** [review]
