### PR TITLE
Fix/fiat rates 1234

### LINKED ISSUE #1772: Fetch missing txs rates when loading txs from storage
It may happen that transaction will be stored without a fiat rate for the transaction's timestamp (fetching could fail for various reasons).
Some logic to refetch missing rates would be nice.

### LINKED ISSUE #3365: ETH transactions sometimes don't display fiat amounts
Some ETH transactions don't show the fiat amount (see screenshot).

**Info:**
- Suite Version: App, Version 20.12.1 (20.12.1.9537)
- OS: MacOS
- Firmware Version: Trezor One (1.9.3), Trezor Model T (2.3.4)

**Screenshots:**
ethbug

### LINKED ISSUE #3459: Incorrect incoming fiat value
**Describe the bug**
Incorrect incoming fiat value (+$0.00) is displayed in transaction history. 

**Info:**
 - Suite Version: 21.2.1 (21.2.1.10324)

 - OS: OS X 10.15.6

**Expected result:**
Adequate incoming fiat value should be displayed. 

**Screenshots:**
SuiteBugBalance

### LINKED ISSUE #3662: Missing fiat balance for some transactions
**Describe the bug**

Some of my transactions in the transactions history are missing fiat equivalent (the suite shows `$0.00`) next to the transaction.

Screenshot 2021-04-19 at 11 54 29

When I click on the TX detail I see the historical fiat balance is missing:

Screenshot 2021-04-19 at 11 52 35

This is not limited to outgoing TXs. I see the same behaviour for some of the incoming TXs as well.

**Firmware version and revision**

FW 2.3.6

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite Desktop
 - OS: macOS
 - Browser 
 - Version: 21.4.1

**Expected behavior**

To see fiat balance on all transactions in the history

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/3459
close https://github.com/trezor/trezor-suite/issues/3662
close https://github.com/trezor/trezor-suite/issues/1772
close https://github.com/trezor/trezor-suite/issues/3365

I think the biggest problem was that after sending and/or receiving new tx fiat rates were not downloaded properly because Blockbook won't return any rates for too recent timestamps, it was already work-arounded long time ago I just failed to use the workaround properly. (1st commit)

As a bonus I added global limiter (more like slowdown-ner) for all request to coingecko as I realised since all fiat rates are periodically updated Suite would probably fire requests for all tokens at the same time next time the update is needed. However, this still won't resolve the problem that our own proxy is getting rate limited (this fix won't prevent 1000 users firing 1 request at the same time) and if the proxy is implemented correctly this shouldn't even help with anything. (2nd commit)

And for rare cases when some user has stored transactions in idb without historical rates attached to them I added refetch logic that is triggered after connecting to blockchain (basically happens after app is launched and data from storage are loaded). (3rd commit).

plus I added some docs https://github.com/trezor/trezor-suite/blob/06469fdddf61e539a38ceecbac5d8626256633f6/docs/misc/fiat_rates.md

### CODE REVIEW

File: packages/suite/src/utils/suite/date.ts [hunk 1]
```diff
@@ -84,14 +85,18 @@ export const calcTicksFromData = (data: { time: number }[]) => {
 };
 
 /**
- * Returns Blockbook-safe current unix timestamp (current time - 3 mins).
+ * Returns Blockbook-safe current unix timestamp (time - 3 mins).
```
Comment (goodhoko) [inline packages/suite/src/utils/suite/date.ts]: nit: Please correct me if I got the semantics wrong. I think this function could be documented as this
```suggestion
 * Returns the given timestamp coerced to at most 3 minutes ago.
 * If no timestamp is given a timestamp of 3 minutes ago is returned.
```

It would be nice to briefly explain what does "blockbook safe" mean. I don't know honestly. .)

File: packages/suite/src/utils/suite/date.ts [hunk 2]
```diff
@@ -84,14 +85,18 @@ export const calcTicksFromData = (data: { time: number }[]) => {
...
-export const getBlockbookSafeTime = () => {
-    const timestamp = getUnixTime(new Date());
-    return timestamp - 180; // current time - 3 mins
+export const getBlockbookSafeTime = (ts?: number) => {
+    const currentTimestamp = getUnixTime(new Date());
+    if (ts && differenceInMinutes(currentTimestamp * 1000, ts * 1000) > 3) {
+        // timestamp is older than 3 mins, no adjustment needed
+        return ts;
+    }
+    return currentTimestamp - 180;
```
Comment (goodhoko) [inline packages/suite/src/utils/suite/date.ts]: A shorter alternative could be this. I like that it doesn't use the `differenceInMinutes` function which isn't particularly clear on first sight. I'm not sure if I like the ternary though. Feel free to take/edit/discard this as you wish and resolve this yourself. .)

```suggestion
export const getBlockbookSafeTime = (ts?: number) => {
    const threeMinutesAgo = getUnixTime(new Date()) - 180;
    return ts !== undefined ? min(ts, threeMinutesAgo) : threeMinutesAgo;
}
```

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts [hunk 3]
```diff
@@ -51,23 +51,19 @@ const fiatRatesMiddleware = (api: MiddlewareAPI<Dispatch, AppState>) => (next: D
...
-                                }),
-                            );
-                        }, i * 500);
-                    }
-                });
-            }
+            account.tokens?.forEach(t => {
+                if (!t.symbol) {
+                    return;
+                }
```
Comment (goodhoko) [inline packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: Could be nice to this filtering in an actual `filter` function

```suggestion
account.tokens?
    .filter(t => t.symbol)
    .forEach(t => {
```

Afaik the typescript can infer that t.symbol cannot be `undefined` in the `forEach` block.

File: packages/suite/src/services/coingecko.ts [hunk 4]
```diff
@@ -1,12 +1,56 @@
+/* eslint-disable max-classes-per-file */
 import { LastWeekRates, TickerId } from '@wallet-types/fiatRates';
 import FIAT_CONFIG from '@suite-config/fiat';
+import { differenceInMilliseconds } from 'date-fns';
 
+// const COINGECKO_API_BASE_URL = 'https://api.coingecko.com/api/v3';
```
Comment (goodhoko) [inline packages/suite/src/services/coingecko.ts]: Is there any reason to keep this around? Let's either remove it altogether (still keeping it in git history) or make it a comment to make clear what is this URL.

```suggestion
// a proxy for https://api.coingecko.com/api/v3
```

File: packages/suite/src/services/coingecko.ts [hunk 5]
```diff
@@ -1,12 +1,56 @@
...
 
 interface HistoricalResponse extends LastWeekRates {
     symbol: string;
 }
 
+class RateLimiter {
+    // Poor man's coingecko rate limiter
+    // Slows down requests so there is `delayMs` gap between them
+    public delayMs: number; // gap between each request
+    public lastFetchTimestamp: number;
```
Comment (goodhoko) [inline packages/suite/src/services/coingecko.ts]: Any reason to have this public?

File: packages/suite/src/services/coingecko.ts [hunk 6]
```diff
@@ -1,12 +1,56 @@
...
+
+    constructor(delayMs: number) {
+        this.delayMs = delayMs;
+
+        this.lastFetchTimestamp = 0;
+        this.queued = 0;
+        this.totalDelay = 0;
+    }
+
+    async limit(fn: any) {
```
Comment (goodhoko) [inline packages/suite/src/services/coingecko.ts]: Any reason we escape the type-checking here with `any`? This function could be fully typed with generics
```suggestion
    async limit<T>(fn: () => Promise<T>): Promise<T> {
```

File: packages/suite/src/actions/wallet/fiatRatesActions.ts [hunk 7]
```diff
@@ -306,6 +306,26 @@ export const updateTxsRates = (account: Account, txs: AccountTransaction[]) => a
...
 
+const updateMissingTxRates = (symbol?: Network['symbol']) => (
+    dispatch: Dispatch,
+    getState: GetState,
+) => {
+    const { accounts, transactions } = getState().wallet;
+    accounts.forEach(account => {
+        if (symbol && account.symbol !== symbol) {
+            return;
+        }
```
Comment (goodhoko) [inline packages/suite/src/actions/wallet/fiatRatesActions.ts:317]: Checking that symbol isn't `undefined` could be pulled out of the loop. Actually, why are we even allowing it to be `undefined` in the function signature when it's required by the function logic? .)

Comment (goodhoko) [reply packages/suite/src/actions/wallet/fiatRatesActions.ts:317]: I.e. I think it would be better to move the check that `symbol` isn't `undefined` to the call site. .)

File: docs/misc/fiat_rates.md [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+
+Suite provides several types of fiat rates:
+- Current fiat rate: Used on Dashboard, next to the account balance, for converting a crypto amount in send form to a fiat currency, etc...
+- Weekly rates: In addition to current rate we also fetch 7 days old rate and based on the difference we either show green or red arrow next to an exchange rate (can be seen in assets table on Dashboard).
+- Historical fiat rate: Exchange rate at the time of facilitating a transaction. Used in list of transactions to calculate daily deltas and in transaction detail modal. Not supported for ERC20 tokens.
+
+### Providers
+- Blockbook: For all main networks (BTC, LTC, ETH) except XRP and ERC20 tokens
+- Blockbook "live" updates: Apart from using Blockbook to manually fetch fiat rates, it also provides us with "live" fiat rate updates (basically push notifications via websocket) for all blockbook-supported coins (see above).
+- CoinGecko: Used for XRP, ERC20 tokens and as a fallback for failed requests to blockbook (via connect).
```
Comment (goodhoko) [inline docs/misc/fiat_rates.md]: > (via connect).

I guess this doesn't refer to [THE connect](https://github.com/trezor/connect), right? What is it then? .)

File: docs/misc/fiat_rates.md [hunk 9]
```diff
@@ -0,0 +1,100 @@
+# Fiat rates
+
+Suite provides several types of fiat rates:
+- Current fiat rate: Used on Dashboard, next to the account balance, for converting a crypto amount in send form to a fiat currency, etc...
+- Weekly rates: In addition to current rate we also fetch 7 days old rate and based on the difference we either show green or red arrow next to an exchange rate (can be seen in assets table on Dashboard).
+- Historical fiat rate: Exchange rate at the time of facilitating a transaction. Used in list of transactions to calculate daily deltas and in transaction detail modal. Not supported for ERC20 tokens.
+
+### Providers
```
Comment (goodhoko) [inline docs/misc/fiat_rates.md]: Seems like this heading is one level deeper than it should be. (`###` instead of `##`) Applies to all its subheading as well.

File: docs/misc/fiat_rates.md [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+
+### First fetch
+#### Current fiat rates
+For main networks: On app launch for enabled networks and then immediately after enabling new coin/network
+##### Current fiat rates for ERC20 tokens
+ERC20 tokens: On `ACCOUNT.CREATE` which is triggered during account discovery (if account were not remembered), on `ACCOUNT.UPDATE` when `account.tokens` has some new items.
+#### Weekly fiat rates
+Weekly rates are downloaded on app launch and on enabling new network.
+
+
```
Comment (goodhoko) [inline docs/misc/fiat_rates.md]:
```suggestion
```

**Review by goodhoko — COMMENTED** [review]
Very nice! Below are some improvements that came to my mind. Mostly code-style related. (It's amazing how many ways you can do every single thing in Javascript!)

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts [hunk 11]
```diff
@@ -51,23 +51,19 @@ const fiatRatesMiddleware = (api: MiddlewareAPI<Dispatch, AppState>) => (next: D
...
+                api.dispatch(
+                    fiatRatesActions.updateCurrentRates({
+                        symbol: t.symbol!,
```
Comment (tomasklim) [inline packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]:
```suggestion
                        symbol: t.symbol,
```
On line 55, you checked that t.symbol is not undefined/null.

Maroš 23-05-2021 17:56 ` ja moc nemam rad tie !`

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts [hunk 12]
```diff
@@ -51,23 +51,19 @@ const fiatRatesMiddleware = (api: MiddlewareAPI<Dispatch, AppState>) => (next: D
...
-                                    symbol: s,
-                                    mainNetworkSymbol: account.symbol,
-                                    tokenAddress: t.address,
-                                }),
-                            );
-                        }, i * 500);
-                    }
-                });
-            }
+            account.tokens?.forEach(t => {
```
Comment (tomasklim) [inline packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: nit:
```suggestion
            account.tokens?.forEach(token => {
```
I would rather see here `token` instead of just `t`

File: packages/suite/src/services/coingecko.ts [hunk 13]
```diff
@@ -1,12 +1,56 @@
...
+        const msSinceLastFetch = differenceInMilliseconds(
+            new Date().getTime(),
+            this.lastFetchTimestamp,
+        );
+        if (msSinceLastFetch < this.delayMs) {
+            this.queued += 1;
+            this.totalDelay += this.delayMs;
+            // dummy wait for this.totalDelay before we fire next request
+            await new Promise(resolve => setTimeout(resolve, this.totalDelay)); // slow down firing next request
```
Comment (tomasklim) [inline packages/suite/src/services/coingecko.ts:38]: note:
`await new Promise(resolve => setTimeout(resolve, 2000)); `

We use this in more places in the code. I would suggest refactoring to be able to use something like 
`await sleep(2000);` which is clearer

```
export const sleep = (ms) => {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```

File: packages/suite/src/services/coingecko.ts [hunk 14]
```diff
@@ -1,12 +1,56 @@
...
+        this.queued -= 1;
+        if (this.queued === 0) {
+            // if all queued requests were fired, we need to reset totalDelay to properly delay next batch of requests
+            this.totalDelay = 0;
+        }
+        return results;
+    }
+}
+
+const limiter = new RateLimiter(1000);
```
Comment (tomasklim) [inline packages/suite/src/services/coingecko.ts]: nit:
```suggestion
const rateLimiter = new RateLimiter(1000);
```

I would change it because you use use it below like this `limiter.limit(() => fetch(url))` and it is kinda painful for me 😆

File: packages/suite/src/utils/suite/date.ts [hunk 15]
```diff
@@ -84,14 +85,18 @@ export const calcTicksFromData = (data: { time: number }[]) => {
...
- * Returns Blockbook-safe current unix timestamp (current time - 3 mins).
+ * Returns Blockbook-safe current unix timestamp (time - 3 mins).
  * Little workaround for Blockbook as it doesn't return rates data for too recent timestamps.
  *
  * @returns
  */
-export const getBlockbookSafeTime = () => {
-    const timestamp = getUnixTime(new Date());
-    return timestamp - 180; // current time - 3 mins
+export const getBlockbookSafeTime = (ts?: number) => {
```
Comment (tomasklim) [inline packages/suite/src/utils/suite/date.ts]: nit:
```suggestion
export const getBlockbookSafeTime = (timestamp?: number) => {
```
Again I would rather see here `timestamp` instead of acronym

**Review by tomasklim — APPROVED** [review]

**Comment by tomasklim** [comment]
Btw I am not sure what is the problem, but I sometimes get CORS error on localhost.

Screenshot 2021-05-27 at 12 23 12

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts [hunk 16]
```diff
@@ -51,23 +51,19 @@ const fiatRatesMiddleware = (api: MiddlewareAPI<Dispatch, AppState>) => (next: D
...
+                if (!t.symbol) {
+                    return;
+                }
+                api.dispatch(
+                    fiatRatesActions.updateCurrentRates({
```
Comment (tomasklim) [inline packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts:60]: note:
We start to update data periodically. However, we do not stop this when device is disconnected or coin having tokens is disabled.

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts (hunk 3 above)
Comment (slowbackspace) [reply packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: > Afaik the typescript can infer that t.symbol cannot be `undefined` in the `forEach` block.

it really can't

File: packages/suite/src/actions/wallet/fiatRatesActions.ts (hunk 7 above)
Comment (slowbackspace) [reply packages/suite/src/actions/wallet/fiatRatesActions.ts:317]: `symbol` is not required by the function logic, that's why it is optional.

if you won't pass the parameter you will trigger the update logic for all accounts (well, transactions belonging to these accounts), if you pass it than it will run only for accounts belonging to the `symbol` network

File: docs/misc/fiat_rates.md (hunk 8 above)
Comment (slowbackspace) [reply docs/misc/fiat_rates.md]: I meant the connect, but the wording is so confusing I'll remove it since it doesn't add much value.

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts (hunk 11 above)
Comment (slowbackspace) [reply packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: good catch :) it is not necessary anymore. same as in `ACCOUNT.UPDATE` few lines above!

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts (hunk 12 above)
Comment (slowbackspace) [reply packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: you will get use to it! 😁 Or you can refactor it across the suite later (also `a` for an account) 😛

File: packages/suite/src/services/coingecko.ts (hunk 13 above)
Comment (slowbackspace) [reply packages/suite/src/services/coingecko.ts:38]: where else did you found it? I found it only in jest setup. anyway I am not going to refactor other parts of suite in this PR. could you create an issue for this please?

File: packages/suite/src/services/coingecko.ts (hunk 14 above)
Comment (slowbackspace) [reply packages/suite/src/services/coingecko.ts]: jeez ok :D

File: packages/suite/src/utils/suite/date.ts (hunk 15 above)
Comment (slowbackspace) [reply packages/suite/src/utils/suite/date.ts]: but what about all the bytes we could save! 😁  (you can add it to the issue)

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts (hunk 16 above)
Comment (slowbackspace) [reply packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts:60]: What do you mean? Higlighted part runs on `account.create` which is fired during account discovery which  means the device is connected. even if it isn't, we can update rates without a device just fine.

If you disable whole network then rates for that network won't be updated anymore.

File: packages/suite/src/utils/suite/date.ts (hunk 2 above)
Comment (slowbackspace) [reply packages/suite/src/utils/suite/date.ts]: I find both equally hard to read 😁  I'll leave it as it is if you don't mind

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts (hunk 12 above)
Comment (goodhoko) [reply packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: I agree with @tomasklim that descriptive names are usually better for readability than abbreviations. I.e. I lean bit more towards Java rather than C.

However there are many cases where shorter identifiers make a difference, especially in these functional-style collection-processing pipelines like `forEach`, `filter`, `map`...

In JS the developer have to name the variable themselves every time. I like how this is done in Kotlin where the scoped variable is implicitly named `it` in all functions that accept a lambda. For example the code above would be written as this in Kotlin
```kotlin
account.tokens?.foreach {
    api.dispatch(it.symbol)
}
```

Note that we haven't defined the `it` variable anywhere. It was automatically provided to the scope by the `forEach` function. The variable can still be renamed. eg. like this
```kotlin
account.tokens?.foreach { token ->
    api.dispatch(token.symbol)
}
```

which is handy especially when there're multiple nested scopes.

The nice thing about implicit `it` is that with basic knowledge of the language one can immediately know what does it refer to -- the subject of the closest lambda scope. In javascript the reader must remember where each of these abbreviated variables were defined and keep it in mind.

In my wild imagination we'd have a convention that we name all left-most lambda arguments `it` except for cases where a longer name makes more sense. This could prevent review threads as this one and would make the code a bit more readable. It has one catch tough: the convention must be upheld across the codebase, which in itself is quite hard without a help of some custom linter rules.

---

I digress. I vote for `token` here. .)

File: packages/suite/src/actions/wallet/fiatRatesActions.ts (hunk 7 above)
Comment (goodhoko) [reply packages/suite/src/actions/wallet/fiatRatesActions.ts:317]: Oh jeez, I read the condition totally wrong. 🤦 Sorry for noise. Resolving.

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts (hunk 3 above)
Comment (goodhoko) [reply packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: Ah sorry. It really can't *on itself*. (I was expecting otherwise). There still is a way to do this with a help of type-guards:
```typescript
consr arr = [1, 2, 3, undefined]

arr
    .filter((it): it is number => it !== undefined)
    .forEach(it => { /* `it` is inferred to be number here */ })
```

However I found no wat to apply a typeguard to this particular case (on a nested property) and it would be combersome anyway. Early return is best here. Resolving.

File: docs/misc/fiat_rates.md (hunk 9 above)
Comment (goodhoko) [reply docs/misc/fiat_rates.md]: thx

File: docs/misc/fiat_rates.md (hunk 8 above)
Comment (goodhoko) [reply docs/misc/fiat_rates.md]: allright.

File: packages/suite/src/services/coingecko.ts (hunk 6 above)
Comment (goodhoko) [reply packages/suite/src/services/coingecko.ts]: thx

File: packages/suite/src/services/coingecko.ts (hunk 5 above)
Comment (goodhoko) [reply packages/suite/src/services/coingecko.ts]: thx

File: packages/suite/src/services/coingecko.ts (hunk 4 above)
Comment (goodhoko) [reply packages/suite/src/services/coingecko.ts]: thx

File: packages/suite/src/utils/suite/date.ts (hunk 2 above)
Comment (goodhoko) [reply packages/suite/src/utils/suite/date.ts]: no prob. Resolving.

File: packages/suite/src/utils/suite/date.ts (hunk 1 above)
Comment (goodhoko) [reply packages/suite/src/utils/suite/date.ts]: The new comment is perfect. Thanks!

**Review by goodhoko — APPROVED** [review]

**Comment by goodhoko** [comment]
Good from my side. There're still some open threads by @tomasklim let's wait for these and merge. 🚀

File: packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts (hunk 12 above)
Comment (slowbackspace) [reply packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts]: 👀 , kay... let's have `token` here since it seems it is really important for you 😁

File: packages/suite/src/utils/suite/date.ts (hunk 15 above)
Comment (slowbackspace) [reply packages/suite/src/utils/suite/date.ts]: done

**Comment by slowbackspace** [comment]
@goodhoko @tomasklim I renamed the variables (t => token, ts => timestamp). All comments should be resolved now :)

**Comment by goodhoko** [comment]
ok. [pushing the button](https://youtu.be/Xu3FTEmN-eg?t=135)!
