### PR TITLE
Suppress backup warning modal when getPublicKey is not initiated by user

### LINKED ISSUE #5280: Show address anyway displayed when you try to backup wallet during discovery
**Describe the bug**
See video, `Create backup` modal is not consistent when triggered during discovery of accounts and you can see receive address modal.
I was not able to reproduce issue when discovery is over.

**Steps to reproduce:**
1. Connect device that needs backup and start discovery
2. Press `Create backup` and cancel it 
3. Repeat till you see different dialogue modal than usually

**Info:**
 - Suite version: desktop 22.4.1 (157aec2030adbb7280d8b90ef0452df2a8400aff)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.4.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.0 regular

**Screenshots:**
Screenshot 2022-04-21 at 14 14 56

https://user-images.githubusercontent.com/31506317/164456686-5e127edb-e26f-4902-9f30-e3921aaaf2a9.mov

### LINKED ISSUE #9059: Show public key / not backed up modal when creating a coinjoin account
**Describe the bug**
When creating a coinjoin account on a device without a backup, after confirmation of the "Do you want to access your coinjoin account?" prompt on the device, the _Show public key / not backed up_ modal modal window is shown by mistake. See screenshots below.

**Info:**

-   Remembered Wallet: no
-   Suite Version: macOS arm app version 23.7.2
-   OS: macOS Ventura 13.2.1
-   Bridge: version 20.0.33
-   Firmware Version: Model T: 2.6.0 Universal; Model One: 1.12.1 BTC-Only
 
**How to reproduce**

1. Go to Accounts
2. Click on "+" to add another account
3. Choose Bitcoin or Bitcoin Testnet
4. Account type select menu appears, choose coinjoin from it and confirm
5. Confirm on device
6. See the modal (that is not expected in this place and time)

**Expected behavior**
Coinoin account should be created without this warning modal. Or the warning about no backup should be tailored to the situation of adding a coinjoin account.

**Screenshots**
Image

**Additional context**

### PR DESCRIPTION
**Pull request by komret**
## Description

When device is not backed up, we want to show a warning when user displays a receive address or public key. We also want to show the warning when a third-party implementation calls `getAccountInfo`. However, there are cases in Suite, when `getPublicKey` or `getAccountInfo` is called, but we do not want to show the warning. The new `suppressBackupWarning` param handles that. It also allows us to remove the workaround from `discoveryMiddleware` and probably fixes #5280, although I have not tested that.

Adding the param to every call of `getPublicKey` is a bit annoying, maybe there is a better way... @mroz22
I have not added it to the address method because there is a lot of them and they would not use it anyway.

## Related Issue

Resolve #9059
Resolve #5280

### CODE REVIEW

File: packages/connect/src/api/getPublicKey.ts [hunk 1]
```diff
@@ -113,6 +113,11 @@ export default class GetPublicKey extends AbstractMethod<'getPublicKey', Params[
     }
 
     async noBackupConfirmation() {
+        // Do not show warning modal when the public key is not requested by user.
+        // E.g. it is accessed during creation of a coinjoin account.
+        if (!this.params[0].show_display) {
```
Comment (szymonlesisz) [inline packages/connect/src/api/getPublicKey.ts]: maybe it would be better to check whole bundle? like:
if (!this.params.some(p => p.show_display))

Comment (szymonlesisz) [reply packages/connect/src/api/getPublicKey.ts]: once it's done we can remove this workaround https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/middlewares/wallet/discoveryMiddleware.ts#L33-L47

Comment (komret) [reply packages/connect/src/api/getPublicKey.ts]: Checking the whole bundle in b4acfb0a4969c96d77fd32381543f07eb7ba0381

Regarding the workaround, I did not find a reason to have `noBackupConfirmation` on `TrezorConnect.getAccountInfo`, perhaps it should be removed to get rid of the workaround?

https://github.com/trezor/trezor-suite/blob/db702eaeb7ee0a918db2c1c1d131f3f23624512f/packages/connect/src/api/getAccountInfo.ts#L164-L180

Comment (szymonlesisz) [reply packages/connect/src/api/getPublicKey.ts]: ah, right, i forgot that this is requested by getAccountInfo not by getPublicKey

i know one good reason why to have it there. this method is also used by 3rd party popup implementations and we want to show this warning in that case. But maybe we can disable it in trusted mode, what do you think @mroz22 ?

Comment (mroz22) [reply packages/connect/src/api/getPublicKey.ts]: i'd rather add a new parameter "suppressNoBackupConfirmation: bool"  (maybe in combination with trusted mode). I just don't like magic happening automagically

Comment (komret) [reply packages/connect/src/api/getPublicKey.ts]: @mroz22 Ok, I will add the param to `getPublicKey`, `getAccountInfo` and `getAddress` and set it to `true`in all calls from Suite except when user displays an address or public key.

It should also resolve #5280.

Comment (komret) [reply packages/connect/src/api/getPublicKey.ts]: Done, can you take a look, @mroz22?

File: docs/packages/connect/methods/cardanoGetPublicKey.md [hunk 2]
```diff
@@ -18,6 +18,7 @@ const result = await TrezorConnect.cardanoGetPublicKey(params);
 -   `path` — _required_ `string | Array<number>` minimum length is `3`. [read more](../path.md)
 -   `showOnTrezor` — _optional_ `boolean` determines if publick key will be displayed on device. Default is set to `true`
 -   `derivationType` — _optional_ `CardanoDerivationType` enum. determines used derivation type. Default is set to ICARUS_TREZOR=2
+-   `suppressBackupWarning` - _optional_ `boolean` By default, this method will send a postMessage to show a warning if the wallet does not have a backup. This option suppresses the message.
```
Comment (szymonlesisz) [inline docs/packages/connect/methods/cardanoGetPublicKey.md]: this method will send a uiRequest/uiConfirmationRequest?

File: packages/connect/src/api/cardanoGetPublicKey.ts [hunk 3]
```diff
@@ -7,10 +7,11 @@ import { getMiscNetwork } from '../data/coinInfo';
 import { validatePath, fromHardened, getSerializedPath } from '../utils/pathUtils';
 import { UI, createUiMessage } from '../events';
 
-export default class CardanoGetPublicKey extends AbstractMethod<
-    'cardanoGetPublicKey',
-    PROTO.CardanoGetPublicKey[]
-> {
+interface Params extends PROTO.CardanoGetPublicKey {
+    suppressBackupWarning?: boolean;
```
Comment (szymonlesisz) [inline packages/connect/src/api/cardanoGetPublicKey.ts:11]: just thinking out loud maybe it would be better to add it in to `CommonParams`?

File: packages/connect/src/api/cardanoGetPublicKey.ts [hunk 4]
```diff
@@ -87,6 +90,9 @@ export default class CardanoGetPublicKey extends AbstractMethod<
     }
 
     async noBackupConfirmation() {
+        if (this.params.some(batch => batch.suppressBackupWarning)) {
```
Comment (szymonlesisz) [inline packages/connect/src/api/cardanoGetPublicKey.ts]: we only want to suppress if `show_display` === false **and** `suppressBackupWarning` === true, no?
and maybe only for trusted implementations? :)
 
I would do it like this:

in core.ts:
```
 await method.noBackupConfirmation(trustedHost && !isUsingPopup);
```
 
in each method:
```
 noBackupConfirmation(allowSuppression: boolean)
```
 
 in each params validation (method init):
 ```
 const show_display = typeof batch.showOnTrezor === 'boolean' ? batch.showOnTrezor : false;
 suppress_backup_warning: !show_display && batch.suppressBackupWarning,
 
 // or if we decide to have it as CommonParam then:
  suppress_backup_warning: !show_display && params.suppressBackupWarning,
 ```
 
 final condition:
 if it's trusted/nonpopup mode and all items in params bundle have suppressBackupWarning === true
 ```
if (allowSuppression && !this.params.some(batch => !batch.suppressBackupWarning)) {
    return true;
}
 ```
 
 

 if (allowSuppression && !this.params.some(p => p.show_display))

File: docs/packages/connect/methods/cardanoGetPublicKey.md (hunk 2 above)
Comment (mroz22) [reply docs/packages/connect/methods/cardanoGetPublicKey.md]: yes, wording could be improved. It would cause connect to emit event (underlying mechanism is not important here)

File: packages/connect/src/api/cardanoGetPublicKey.ts (hunk 3 above)
Comment (mroz22) [reply packages/connect/src/api/cardanoGetPublicKey.ts:11]: It could be there. In common params, there are already params that are not trully common (meaning a param that can affect every method). It is probably better to move it to common 🤔

File: packages/connect/src/api/cardanoGetPublicKey.ts (hunk 4 above)
Comment (mroz22) [reply packages/connect/src/api/cardanoGetPublicKey.ts]: sounds reasonable, but let me please think about it on Monday a bit. energy low now.

Comment (komret) [reply packages/connect/src/api/cardanoGetPublicKey.ts]: > we only want to suppress if `show_display` === false **and** `suppressBackupWarning` === true, no? and maybe only for trusted implementations? :)

`showOnTrezor` param is not present on `getAccountInfo` method, so this would only apply for `getPublicKey` and `cardanoGetPublicKey`. In that case, `suppressBackupWarning` param is redundant because there is no case when `showOnTrezor == true && suppressBackupWarning == true`. And I would still have to specify `suppressBackupWarning: false` for all `getAccountInfo` calls. Did I miss something?

Comment (mroz22) [reply packages/connect/src/api/cardanoGetPublicKey.ts]: what szymon says makes sense to me. just I would do

```
 await method.noBackupConfirmation(!isUsingPopup);
```
instead of 

```
 await method.noBackupConfirmation(trustedHost && !isUsingPopup);
```
imho it does not really matter if we force emitting some event in non trusted mode since we don't have any power over how implementator handles this evnet anyway. On the other hand `!isUsingPopup` makes perfect sense here because we want to show "no backup" screen in popup.

as for the noBackupConfirmation method, I would maybe do something like 

```
 async noBackupConfirmation(allowSupression) {
        if (allowSuppression && !this.params.filter(batch => batch.show_display).every((batch) => batch.suppressBackupWarning)) {
            return true;
        }
        
```
maybe every bundle item that has show_display:false should be also supressed?

and lastly, I would not include supression param into commonParams since we are working with single batch items in what I outlined here.

Comment (komret) [reply packages/connect/src/api/cardanoGetPublicKey.ts]: > !this.params.filter(batch => batch.show_display).every((batch) => batch.suppressBackupWarning)

The first `!` shouldn't be there, right @mroz22?

> maybe every bundle item that has show_display:false should be also supressed?

In that case it could be just:

```ts
if (
    allowSuppression &&
    this.params.every(batch => batch.suppressBackupWarning || !batch.show_display)
) {
    return true;
}
```

**Review by mroz22 — COMMENTED** [review]
Looks ok. I just can't decide whether szymons proposed solution to put this newly added param to common params wasn't actually better.

Also please:
- squash commits to something reasonable. 
- maybe run popup-manual test before merging.

File: docs/packages/connect/methods/cardanoGetPublicKey.md (hunk 2 above)
Comment (komret) [reply docs/packages/connect/methods/cardanoGetPublicKey.md]: Changed to `By default, this method will emit an event to show a warning if the wallet does not have a backup. This option suppresses the message.`

**Review by mroz22 — APPROVED** [review]
it looks acceptable now I think.
