### PR TITLE
fix(suite): run estimateFee on approval limit change

### LINKED ISSUE #20328: Trading - changing approval limit does not refresh fees
**Describe the bug**
Changing approval limit does not do new estimateFee so it can show incorrect fee
Image

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

This PR implements fees refetching when approval limit is changed.

## Related Issue

Resolve #20328

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/refresh-fees-on-approval-limit-change&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/refresh-fees-on-approval-limit-change&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ApproveModal.tsx [hunk 1]
```diff
@@ -139,6 +140,7 @@ export const ApproveModal = ({
         };
 
         dispatch(tradingExchangeActions.saveSelectedQuote(updatedSelectedQuote));
+        dispatch(updateFeeInfoThunk({ networkSymbol: account.symbol }));
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ApproveModal.tsx]: I am not sure if this will solve the issue, gas limit does not change

**Review by tomasklim — DISMISSED** [review]
I am not 100% sure but we set ethereumDataHex here

```  
  // save approval tx data for approval fee estimation
    useEffect(() => {
        if (isApproval && selectedQuote?.status === 'APPROVAL_REQ' && selectedQuote?.dexTx) {
            setValue('ethereumDataHex', selectedQuote?.dexTx.data);
            setValue(TRADING_FORM_OUTPUT_ADDRESS, selectedQuote?.dexTx.to);
        }

        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isApproval, selectedQuote]);
   ```
when quote is updated, which is when you change minimum x infinite approve amount
but I am not sure if recompose is done

**Comment by TomasBoda** [comment]
> I am not 100% sure but we set ethereumDataHex here
> 
> ```
>   // save approval tx data for approval fee estimation
>     useEffect(() => {
>         if (isApproval && selectedQuote?.status === 'APPROVAL_REQ' && selectedQuote?.dexTx) {
>             setValue('ethereumDataHex', selectedQuote?.dexTx.data);
>             setValue(TRADING_FORM_OUTPUT_ADDRESS, selectedQuote?.dexTx.to);
>         }
> 
>         // eslint-disable-next-line react-hooks/exhaustive-deps
>     }, [isApproval, selectedQuote]);
> ```
> 
> when quote is updated, which is when you change minimum x infinite approve amount but I am not sure if recompose is done

Correct, once the user changes the `minimum` vs. `infinite` approve amount, this hook is called, but I don't think recompose is called. There is another hook right below this one that calls recompose once the approval modal is opened/closed to fetch fresh fees. @matusbalascak I think the first hook needs to be refactored to call recompose as well and the second hook can then maybe be deleted, but I'm not sure

```ts
// refresh fees when user opens/closes approval modal
useEffect(() => {
    composeRequest();
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, [isApproval]);
```

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts [hunk 2]
```diff
@@ -765,21 +767,10 @@ export const useTradingExchangeForm = ({
...
-            setValue('ethereumDataHex', selectedQuote?.dexTx.data);
-            setValue(TRADING_FORM_OUTPUT_ADDRESS, selectedQuote?.dexTx.to);
-        }
-
-        // eslint-disable-next-line react-hooks/exhaustive-deps
-    }, [isApproval, selectedQuote]);
-
-    // refresh fees when user opens/closes approval modal
-    useEffect(() => {
+    const fetchFeesAndCompose = async () => {
```
Comment (TomasBoda) [inline packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts:784]: nitpick: I'd move this function above the `useEffect` hook, since all `useEffect` hooks are below all functions

**Review by TomasBoda — APPROVED** [review]
LGTM 🎉

File: packages/components/src/components/RadioCard/RadioCard.tsx [hunk 3]
```diff
@@ -42,17 +47,28 @@ const Wrapper = styled.div<
...
-    &:hover,
-    &:focus {
-        outline-color: ${({ theme }) => theme.baseContentEmphasis};
-    }
+    ${({ $isDisabled }) =>
+        !$isDisabled &&
+        css`
+            &:hover,
+            &:focus {
+                outline-color: ${({ theme }) => theme.baseContentEmphasis};
```
Comment (vojtatranta) [inline packages/components/src/components/RadioCard/RadioCard.tsx:55]: pls, add this option to storybook. I checked it there and visually it looks okay. Altough, final approval should be on @jvaclavik 

And, in Storybook, make sure you define the type of this prop. Currently, you have to manually write it as an object. It should be a boolean switch.

Thanks

Comment (jvaclavik) [reply packages/components/src/components/RadioCard/RadioCard.tsx:55]: LGTM now
