### PR TITLE
fix(suite): amount decimal formating

### LINKED ISSUE #10500: Review: Show proper decimal formatting for amount
Design:
https://www.figma.com/file/mQhdQPKzdi93Swb8FNX9wL/branch/pewjlOfequOKYVC6h3v0YL/%5Bs2.0%5D-Desktop?type=design&node-id=3245%3A152587&mode=dev

Current state: 
Screenshot 2024-01-05 at 9 51 16

Desired state:
Screenshot 2024-01-05 at 9 49 14

**Warning: there are currencies with suffix (like "Kč"). Solution here:** https://www.figma.com/file/pewjlOfequOKYVC6h3v0YL?node-id=3245:149262&mode=dev#625351699

It's mainly about updating formatter. Styling itself should be ready on branch `suite-e` in this file: `packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx`
image

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Amount formatting is now according to the design.

## Related Issue

Resolve #10500 

## Screenshots:
519F4360-1345-4B76-86C9-0FF267186B2C
37999929-74CF-47B6-ADE7-74C521C7518F

### CODE REVIEW

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx [hunk 1]
```diff
@@ -59,8 +76,18 @@ export interface HeaderProps {
 }
 
 export const Header = (props: HeaderProps) => {
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: Screenshot 2024-01-08 at 15 43 52

This way of showing amount should be shared between Dashboard and AssetCard. Could you create common component for it? (not sure if all font sizes are the same, please check the design)

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx [hunk 2]
```diff
@@ -20,11 +22,26 @@ const Wrapper = styled.div<{ hideBorder: boolean }>`
...
 `;
 
+const DecimalValue = styled.div<{ withLeftMargin?: boolean }>`
+    ${typography.hint};
+    font-variant-numeric: tabular-nums;
+    align-self: flex-end;
+    letter-spacing: 0.565px;
+    margin-left: ${({ withLeftMargin }) => `${withLeftMargin ? '4px' : 0}`};
+    margin-bottom: 6px;
+    color: ${({ theme }) => theme.TYPE_LIGHT_GREY};
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: Btw in the new design system, we try to refactor old color values to new ones. Old are written with CAPITALIZED value, new ones are not. You can find new ones here: `packages/theme/src/colors.ts`

It should be self explanatory, but it might be hard to understand it when you see it for the first time. It's `textSubdued` in this case: 
```
color: ${({ theme }) => theme.textSubdued}; 
```

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx [hunk 3]
```diff
@@ -59,8 +76,18 @@ export interface HeaderProps {
...
     const accounts = useFastAccounts();
+    const formattedValue = FiatAmountFormatter({
+        value: props.portfolioValue,
+        currency: props.localCurrency,
+    });
+
+    const formattedFiatValue = formattedValue?.props.children;
+    const [whole, fractional] = ['en', 'ja'].includes(language)
+        ? formattedFiatValue.split('.')
+        : formattedFiatValue.split(',');
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: How do you know that it's for `en` and `ja`?

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx [hunk 4]
```diff
@@ -99,16 +126,12 @@ export const Header = (props: HeaderProps) => {
...
-                                    value={props.portfolioValue}
-                                    currency={props.localCurrency}
-                                />
-                            </span>
-                        </HiddenPlaceholder>
-                    </ValueWrapper>
+                    <HiddenPlaceholder intensity={7}>
+                        <ValueWrapper>
+                            <WholeValue>{whole}</WholeValue>
+                            <DecimalValue>.{fractional}</DecimalValue>
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: Screenshot 2024-01-08 at 16 00 35

**Review by jvaclavik — COMMENTED** [review]
Good job! Few comments added.

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: Will also do it for other variables in the files I have touched

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx (hunk 3 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: Currently these are the only languages that are available in Suite and they have this formatting where the currency is before the amount and they use different separators, commas etc. Was thinking about it and didn't come up with better solution fot this.

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: 13af45ff0fd892f46e4753f172ddd8adb1e1fa95

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: 13af45ff0fd892f46e4753f172ddd8adb1e1fa95

File: packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx (hunk 4 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx]: 13af45ff0fd892f46e4753f172ddd8adb1e1fa95

**Review by jvaclavik — APPROVED** [review]
Looks good to me! 🚢 it
