### PR TITLE
fix(trading): trading field name

### LINKED ISSUE #17256: Trading: Cannot finish buy transaction after adding new coin
Reprosteps:
1. Select any BTC account
2. Go to Buy
3. Select coin which is not discovered yet by Suite to buy
4. Get offer for the coin
5. Select any offer
6. Create new account for the coin
7. Confirm address on Trezor
8. See disabled button "Finish transaction"

https://github.com/user-attachments/assets/116db557-a6ae-4940-a3af-8334768204cc

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- fix trading

## Related Issue

Resolve 
Also resolve https://github.com/trezor/trezor-suite/issues/17256 (@adderpositive)

## Screenshots:
Screenshot 2025-02-28 at 12 44 16
Screenshot 2025-02-28 at 12 53 21

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx [hunk 1]
```diff
@@ -38,7 +42,12 @@ export const TradingVerifyDestinationTag = ({
                 <Switch
                     isChecked={enabled}
                     onChange={handleToggle}
-                    label={<Translation id="DESTINATION_TAG_SWITCH" />}
+                    label={
+                        <Translation
+                            id="TR_EXCHANGE_EXTRA_FIELD_SWITCH"
+                            values={{ extraFieldName: extraFieldDescription?.name }}
+                        />
+                    }
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx]: Since `extraFieldDescription` can be `undefined`, don't we want to render `<Translation id="DESTINATION_TAG_SWITCH" />` as fallback?

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx [hunk 2]
```diff
@@ -233,13 +246,7 @@ export const TradingVerify = ({ tradingVerifyAccount, cryptoId }: TradingVerifyP
                                     confirmTrade(address, extraField);
                                 }
                             }}
-                            isDisabled={
-                                !form.formState.isValid ||
-                                address === '' ||
-                                callInProgress ||
-                                (exchangeQuote?.extraFieldDescription?.required &&
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx:240]: `exchangeQuote?.extraFieldDescription?.required` I would roll it back.

**Review by adderpositive — DISMISSED** [review]
One small thing, otherwise it is fine by me.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx (hunk 2 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx:240]: Or include it in `isButtonDisabled` logic

Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx:240]: @tomasklim is there a reason why you removed it?

Comment (tomasklim) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx:240]: no i thought that thats the problem, rollback it

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx]: makes sense, yes

Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx]: done

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx (hunk 2 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx:240]: done

File: packages/suite-desktop-core/e2e/tests/trading/buy-ethereum.test.ts [hunk 3]
```diff
@@ -46,7 +46,6 @@ test.describe('Trading - Buy Ethereum', { tag: ['@group=other', '@webOnly'] }, (
                 'Select ETHEREUM receive account',
             );
             await expect(marketPage.confirmationAddress).toHaveText('');
-            await expect(page.getByText('Receive address is required')).toBeVisible();
```
Comment (tomasklim) [inline packages/suite-desktop-core/e2e/tests/trading/buy-ethereum.test.ts:49]: why?

**Review by TomasBoda — APPROVED** [review]

**Comment by STew790** [comment]
**QA OK**
image

image

**Info:**
 - Suite version: web 25.3.0 (49d0a6959a4d69f8b0b4285d16c33689fd39e150)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T2T1 2.8.9 regular (revision 7614a29c9a9cc138fff446937b7d9489fd57821f)
 - Transport: WebUsbTransport
