### PR TITLE
fix(suite): decrease line height for the label in Coin logo in CoinList

### LINKED ISSUE #16945: Text alignment on Coins view
It looks like the text for Coins having tokens is not vertically aligned with the button

Image

### PR DESCRIPTION
**Pull request by vojtatranta**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16945

## Screenshots:
BFR
Screenshot 2025-02-12 at 9 49 32 AM

AFTR
Screenshot 2025-02-12 at 9 49 42 AM

### CODE REVIEW

File: packages/suite/src/components/suite/CoinList/Coin.tsx [hunk 1]
```diff
@@ -140,7 +140,7 @@ const NameLabeled = styled.div`
 
 const Label = styled.div`
     ${typography.label}
-
+    line-height: 13px;
```
Comment (vojtatranta) [inline packages/suite/src/components/suite/CoinList/Coin.tsx:143]: I guess this isn't great tho, like the solution and overriding the `typography.label`

**Review by jvaclavik — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

Screenshot 2025-02-13 at 09 35 19
Screenshot 2025-02-13 at 09 35 12

**Info:**
 - Suite version: web 25.3.0 (aa490cac5028e2ecf8e4b355f8b3bc6e198b4a7d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.8 regular (revision 592590cf66a9b62dfeee7e4d2afb6e01005e5b2c)
 - Transport: WebUsbTransport
