### PR TITLE
fix(suite): Show fiat value in AssetCard

### LINKED ISSUE #10984: Dashboard shows amount of coins and not fiat value
**Describe the bug**
Dashboard shows amount of coins and not fiat value.
See screenshot

**Steps to reproduce:**
1. Load wallet with funds
2. Change view to grid
3. Check fiat value in dashboard

**Info:**
 - Suite version: web 24.2.0 (3ba71cbdf7a956185ce627ecd7aa0364ad35fc0b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve #10984

## Screenshots:

Screenshot 2024-02-05 at 17 20 49

### CODE REVIEW

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx [hunk 1]
```diff
@@ -147,7 +150,7 @@ export const AssetCard = ({
                         <FiatAmount>
                             <FiatHeader
                                 size="medium"
-                                portfolioValue={cryptoValue}
+                                portfolioValue={fiatAmount ?? '0'}
```
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx]: The hook should be a part of the `FiatHeader` component :) All amounts passed in all the value-related components are in crypto, not fiat. 

Also the `FiatValue` component is able to provide the fiat value to its [children](https://github.com/trezor/trezor-suite/blob/ab34249019dc721205edea90c1b277afccc8786c/packages/suite/src/components/suite/Ticker/TrendTicker.tsx#L48), which I agree is not the best but then you do not need the hook :)

File: packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts
Comment (dahaca) [inline packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts:1]: Would be good to leave a comment that eventually it would be great to have this shared between native and desktop, since they already have a [hook with a same name](https://github.com/trezor/trezor-suite/blob/84eb403eb19652f7b01baadc8e7bbc400b5d8fc0/suite-native/formatters/src/hooks/useFiatFromCryptoValue.ts#L25) but they use different selectors. 

Do you think this would make sense, @PeKne ?

Comment (PeKne) [reply packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts:1]: Good catch. Yes, I think that when the desktop will migrate from the deprecated fiat-rates select `selectCoinsLegacy` you should be able to use the selector implemented in `suite-native`. Then it would make sense to move it to `suite-common`.

Comment (PeKne) [reply packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts:1]: @Nodonisko It is planned to migrate the desktop to the new fiat rate selectors that you made last year, right?

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx (hunk 1 above)
Comment (jvaclavik) [reply packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx]: In my opinion component `FiatValue` is too heavy and it makes sense to have extracted logic somewhere outside. Also I agree with you that `FiatHeader` should accept crypto and make all the magic inside. I will explore it more.

File: packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts
Comment (jvaclavik) [reply packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts:1]: It totally makes sense, but not now, because we need to merge it before freeze. But I will create an issue for it.

Comment (jvaclavik) [reply packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts:1]: https://github.com/trezor/trezor-suite/issues/11062

File: packages/suite/src/components/suite/FiatValue.tsx [hunk 2]
```diff
@@ -74,30 +57,26 @@ export const FiatValue = ({
...
+    const value = shouldConvert ? fiatAmount : amount;
 
-    const ratesSource = useCustomSource ? source : currentFiatRates?.rates;
-    let fiatAmount: string | null = amount;
-    if (shouldConvert) {
-        fiatAmount = ratesSource ? toFiatCurrency(amount, targetCurrency, ratesSource) : null;
-    }
     const WrapperComponent = disableHiddenPlaceholder ? SameWidthNums : StyledHiddenPlaceholder;
-    if (fiatAmount) {
+    if (value) {
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/FiatValue.tsx:73]: I smell non-strict comparison.

**Review by peter-sanderson — APPROVED** [review]
