### PR TITLE
fix(suite): Show address in Sign&Verify for non-ethereum based networks

### LINKED ISSUE #20249: Missing address in Sign&Verify review
**Describe the bug**
When signing a message, adress is sometimes missing in the review model. (Likely happens for bitcoin-based networks.)

**How to reproduce**
1. Sign a message on a bitcoin account

**Expected behavior**
Address is present.

**Screenshots**

Bitcoin:
Image

Ethereum:
Image

### PR DESCRIPTION
**Pull request by 5K1PY**
Finds account address correctly even when current network is not ethereum.

## Related Issue

Resolve #20249

## Screenshots:

Before:
address-before

After:
address-after

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/missing-address-sign-verify&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/missing-address-sign-verify&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/missing-address-sign-verify&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/accounts/accountsSelectors.ts [hunk 1]
```diff
@@ -278,3 +283,27 @@ export const selectSolAccountHasStaked = createMemoizedSelector([selectAccountBy
...
+
+export const selectAddressByNetworkAndPath = createMemoizedSelector(
+    [
+        selectAccounts,
+        (_state: AccountsRootState, network?: Network) => network,
+        (_state: AccountsRootState, _network?: Network, path?: string) => path,
+    ],
+    (accounts, network, path) => {
+        if (!network || !path) return undefined;
+        for (const account of accounts.filter(a => a.symbol === network.symbol)) {
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/accounts/accountsSelectors.ts]: nit: I would extract `accounts.filter(a => a.symbol === network.symbol)` to variable for better readability

File: suite-common/wallet-core/src/accounts/accountsSelectors.ts [hunk 2]
```diff
@@ -278,3 +283,27 @@ export const selectSolAccountHasStaked = createMemoizedSelector([selectAccountBy
 
     return !!account.misc.solStakingAccounts?.length;
 });
+
+export const selectAddressByNetworkAndPath = createMemoizedSelector(
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/accounts/accountsSelectors.ts:287]: I'd like to see test for this selector , it seem rather complicated

File: suite-common/wallet-core/src/accounts/accountsSelectors.ts [hunk 3]
```diff
@@ -278,3 +283,29 @@ export const selectSolAccountHasStaked = createMemoizedSelector([selectAccountBy
...
+    [
+        selectAccounts,
+        (_state: AccountsRootState, network?: Network) => network,
+        (_state: AccountsRootState, _network?: Network, path?: string) => path,
+    ],
+    (accounts, network, path) => {
+        if (!network || !path) return undefined;
+
+        const network_accounts = accounts.filter(a => a.symbol === network.symbol);
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/accounts/accountsSelectors.ts]:
```suggestion
        const networkAccounts = accounts.filter(a => a.symbol === network.symbol);
```

**Review by peter-sanderson — APPROVED** [review]
