### PR TITLE
fix: suite-sync available vs enabled

### LINKED ISSUE #26427: TT and T1 show incompatible Suite Sync message even with Legacy labeling
**Describe the bug**

https://github.com/user-attachments/assets/8939bd87-a1b2-4601-8df3-a39f7eb8e1c8

**Info:**
 - Suite version: desktop 26.4.0 (091ce6065cf54493582a9e001a94abdd68a44cf3)
 - Browser: Trezor Suite 26.4.0
 - OS: MacIntel
 - Screen: 3008x1692
 - Device: Trezor T2T1 2.11.0 universal (revision 725c0c01879329900f08fc453d8fd0fcb4d86090)
 - Transport: BridgeTransport 3.2.1, BluetoothTransport

### PR DESCRIPTION
**Pull request by peter-sanderson**
Fixes https://github.com/trezor/trezor-suite/issues/26427

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=levacy-not-working&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=levacy-not-working&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=levacy-not-working&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Account metadata,google - watches files over time" | 🙋 manual |
| Quarantine test: "Account metadata,dropbox - watches files over time" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-07T13:57:26.272Z • 7 test(s) total_

<details><summary>Trezor Suite (desktop) — 4 test(s)</summary>

| Test | Type |
|------|------|
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-07T13:56:09.183Z • 4 test(s) total_

### CODE REVIEW

File: packages/suite/src/components/suite/labeling/Labeling/selectIsLabelActionEnabled.ts [hunk 1]
```diff
@@ -38,16 +46,5 @@ export const selectIsLabelActionEnabled = (
         deviceStaticSessionId,
     );
 
-    const isSuiteSyncFeatureEnabled = selectIsSuiteSyncFeatureAvailable(state);
-
-    if (isSuiteSyncFeatureEnabled) {
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/labeling/Labeling/selectIsLabelActionEnabled.ts:43]: This was the issue

File: suite-common/suite-sync/src/suiteSyncSelectors.ts [hunk 2]
```diff
@@ -46,7 +52,7 @@ export const selectSuiteSyncOwnerForDeviceStaticId = (
         : null;
 
 export const selectSuiteSyncInteraction = (
-    state: WithSuiteSyncAndDeviceState,
+    state: WithSuiteSyncAndDeviceState & MessageSystemRootState,
```
Comment (juriczech) [inline suite-common/suite-sync/src/suiteSyncSelectors.ts:55]: This is unnecessary in the end, right?

Comment (peter-sanderson) [reply suite-common/suite-sync/src/suiteSyncSelectors.ts:55]: in is needed, you call `selectIsSuiteSyncEnabled` inside that needs message system there

**Review by juriczech — APPROVED** [review]
