### PR TITLE
Send bug fixes

### LINKED ISSUE #1366: Send form: Review tx modal,
disable possibility to quickly click into "Confirm transaction" button which will throw error "device call in progress" to toast notification

### LINKED ISSUE #1615: Move "clear all" out of the box & change icon
Screen Shot 2020-04-22 at 15 56 34

**[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e79c9b69ad455629e3ea640)** (for icon)

### PR DESCRIPTION
**Pull request by vladimirvolek**
resolves: https://github.com/trezor/trezor-suite/issues/1366
resolves: https://github.com/trezor/trezor-suite/issues/1615

### CODE REVIEW

File: packages/suite/src/actions/suite/trezorConnectActions.ts [hunk 1]
```diff
@@ -43,6 +43,13 @@ export const init = () => async (dispatch: Dispatch, getState: GetState) => {
         'rippleGetAddress',
         'applySettings',
         'changePin',
+        'pushTransaction',
+        'ethereumSignTransaction',
+        'blockchainEstimateFee',
+        'signTransaction',
+        'rippleSignTransaction',
+        'ethereumSignTransaction',
```
Comment (szymonlesisz) [inline packages/suite/src/actions/suite/trezorConnectActions.ts]: ethereumSignTransaction twice
