### PR TITLE
Fix(suite): FW hash check Sentry reporting

### LINKED ISSUE #16584: FW hash check fix Sentry reporting
- correctly append `errorPayload` to sentry errors/warnings (currently broken!)
- only report `other-error` on attempt 3 (meaning retries maxed), not errors received in meantime
- also log FW revision|hash check errors|warnings to console

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

- solve broken errorPayloads due to bad serialization
- only report `other-error` on attempt 3 (meaning retries maxed), not errors received in meantime
- log FW revision|hash check errors|warnings to console
  - :warning: must use `console.warn`, not `.error`, as Sentry'd pick it up and send a duplicate event :see_no_evil:  
- cleanup in variable names, I'm also intentionally changing the `contextData` object that is sent in event message, see [comment](https://github.com/trezor/trezor-suite/pull/16585#discussion_r1928558299)

## Related Issue

Resolve #16584

## Screenshots:

N/A, but see illustrative Sentry events from localhost.
Sent from testing branch https://github.com/trezor/trezor-suite/commit/e0668b8a810c99bb67697850660eeb6db50b5ef5 . You can try for yourself - comment/uncomment to pick from the 3 scenarios.

For all cases see trace: that there is only FW revision failure alongside, but no other FW hash check events

- [1st other-error, then success](https://satoshilabs.sentry.io/issues/6241035716/events/318b41816fd240dbba84042e7158d32c/?project=5193825), see warningPayload at the bottom
- [other-error maxed out](https://satoshilabs.sentry.io/issues/6240996662/events/f486f6aaf78d40549d331486f93b28da/), see errorPayload at the bottom
- [1st other-error, then hash-mismatch](https://satoshilabs.sentry.io/issues/6240996891/events/cdf804c96769496681aaad3bce6233ac/?project=5193825). Only theoretical concern: it means a counterfeit device that is flaky

### CODE REVIEW

File: packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts [hunk 1]
```diff
@@ -10,20 +12,35 @@ import { hashCheckErrorScenarios } from 'src/constants/suite/firmware';
 
 export const reportCheckFail = (
     checkType: 'Firmware revision' | 'Firmware hash' | 'Entropy',
-    contextData: any,
-) =>
+    contextData: Record<string, any>,
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts:15]: nit: better than any, at least we safeguard that it's JSON.stringifiable

File: packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts [hunk 2]
```diff
@@ -40,13 +57,13 @@ const useCommonData = () => {
 
 const useReportRevisionCheck = () => {
     const commonData = useCommonData();
-    const revisionCheckError = useSelector(selectFirmwareRevisionCheckError);
+    const errorType = useSelector(selectFirmwareRevisionCheckError);
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts:60]: nit: rename to more sensible label; ditto in hash check:
- no need to repeat that it's revision
- it's _error type_, to distinguish it from payload
- side effect: after this change, Sentry will track the new format as separate issues
  - IMHO it will be much clearer to analyze that way (no wondering if the new changes don't work or it's just old suite versions)

File: packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts [hunk 3]
```diff
@@ -55,28 +72,30 @@ const useReportHashCheck = () => {
...
-        }
-    }, [commonData, hashCheckError, hashCheckErrorPayload]);
+        if (!errorType) return;
+        if (!hashCheckErrorScenarios[errorType].shouldReport) return;
+        const willBeRetried =
+            isArrayMember(errorType, FIRMWARE.HASH_CHECK_RETRIABLE_ERRORS) &&
+            (attemptCount ?? 0) < FIRMWARE.HASH_CHECK_MAX_ATTEMPTS;
+        if (willBeRetried) return;
+
+        reportCheckFail('Firmware hash', { ...commonData, errorType, attemptCount }, errorPayload);
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/SecurityCheck/useReportDeviceCompromised.ts:88]: added `attemptCount`, which is non-null only in case of 3 `other-error` failures.
It lets us confirm that this Sentry event was sent **after no less than 3**  attempts

**Review by komret — APPROVED** [review]
