### PR TITLE
fix(suite): reload app after enabling autoForget

### LINKED ISSUE #22738: Disabling “store device-related data” reconnects the device when using THP connection.
**Describe the bug**
If the user disables “store device-related data” while the device is connected via THP, the Suite still remembers the THP credentials and pairs the device again.
A possible solution could be to automatically perform an app restart after the user disables this feature.
If the automatic app restart is implemented, the user should be informed about it in the copy (that a reset will occur).

**Info:**
 - Suite version: desktop 25.11.0 (10406ea38e999cc56acd32af088fc01fa23d49ba)
 - Browser: Trezor Suite 25.11.0
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: Trezor T3W1 2.9.3 universal (revision 0bd923c78990d8d58f82fe18660e57399aafc0f1)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**Video:**

https://github.com/user-attachments/assets/5fb4d01a-1547-4fac-bed4-5b284ddf85fd

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Reload app after disabling device data storage (a.k.a. enabling auto forget), to ensure that Connect session is cleared.
That's because Connect keeps actie THP sessions, would reconnect the device (Suite can't prevent it from doing so), and Suite "gets a new device" so it becomes remembered again.

## Related Issue

Resolve #22738

## Screenshots:

Web:

[Screencast from 2025-11-11 14-07-23.webm](https://github.com/user-attachments/assets/56c9741d-5c3e-404a-96ee-6529af6f83a3)

Desktop: (I forgot to update copy in this video, but it'll be there..)

[Screencast from 2025-11-11 14-16-14.webm](https://github.com/user-attachments/assets/203259e4-d54d-48e9-be6d-8fbb1e1f475e)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/reload-suite-when-enable-autoForget&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/reload-suite-when-enable-autoForget&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/reload-suite-when-enable-autoForget&lookback=7)

### CODE REVIEW

**Review by seibei-iguchi — APPROVED** [review]

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -2873,7 +2873,7 @@ export default defineMessages({
     TR_STORE_DEVICE_DATA_MODAL_DISABLED_WARNING: {
         id: 'TR_STORE_DEVICE_DATA_MODAL_DISABLED_WARNING',
         defaultMessage:
-            'All wallets will be automatically ejected when your Trezor is disconnected.',
+            'All wallets will be ejected. Trezor Suite will automatically restart once the process is complete',
```
Comment (Lemonexe) [inline packages/suite/src/support/messages.ts:2876]: the second sentence is taken from `TR_CLEAR_STORAGE_DESCRIPTION`

**Comment by Lemonexe** [comment]
En-US Crowdin for `TR_STORE_DEVICE_DATA_MODAL_DISABLED_WARNING` is updated :heavy_check_mark:

**Comment by Lemonexe** [comment]
Merging, Suite desktop E2E `settings/autodetect.test.ts` is confirmed broken
