### PR TITLE
fix(desktop): border around app for Win/Linux

### LINKED ISSUE #2878: Desktop app: missing app frame border on windows
**Describe the bug**
App border is completely missing

**Info:**
 - Suite Version: desktop app, 1188894
 - OS: Windows 10

**Expected result:**
Other applications got at least thin 1px around itself

**Screenshots:**
missing-border

### PR DESCRIPTION
**Pull request by tomexx**
Fix of #2878

- Desktop Suite running on Linux/Windows should have a 1px border around app
- Trezor Modal component is wrapped with a thin Suite component to offset the backdrop blur (so it wont blur the borders)
- isMac helper handles Electron environment as well now
- fixed alignment of initial loading spinner in desktop app
- fixed alignment of modals in desktop app (the height of custom titlebar is taken into account now)

### CODE REVIEW

File: packages/suite/.stylelintignore [hunk 1]
```diff
@@ -2,5 +2,6 @@
 # files below doesn't contains any styles so it's safe to ignore them
 
 src/components/suite/index.tsx
+src/components/suite/Modal/index.tsx
```
Comment (slowbackspace) [inline packages/suite/.stylelintignore:5]: just a nitpick, this will ignore whole file, so if we later add some styling to it it won't get linted and nobody will remember this is the reason. I would prefer to disable stylelint just for single line that is causing a problem.

File: packages/suite/src/components/suite/Modal/index.tsx [hunk 2]
```diff
@@ -0,0 +1,15 @@
+import React from 'react';
+import { Modal as TrezorModal, ModalProps } from '@trezor/components';
+import { DESKTOP_WRAPPER_BORDER_WIDTH } from '@suite-constants/layout';
+import { isDesktop, isMac } from '@suite-utils/env';
+
+const Modal = (props: ModalProps) => (
+    <TrezorModal
+        {...{
+            ...props,
+            ...(isDesktop() && !isMac() && { desktopBorder: DESKTOP_WRAPPER_BORDER_WIDTH }),
```
Comment (slowbackspace) [inline packages/suite/src/components/suite/Modal/index.tsx]: couldn't it be simplified to this?
```javascript
<TrezorModal 
    {...props} 
    desktopBorder={isDesktop() && !isMac() ? DESKTOP_WRAPPER_BORDER_WIDTH : undefined}
/>
```
I don't know why but the double spread seems weird to me :D

File: packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx [hunk 3]
```diff
@@ -1,5 +1,10 @@
 import React, { useEffect, useState } from 'react';
 import { Loading } from '@suite-components';
+import styled from 'styled-components';
+
+const StyledLoading = styled(props => <Loading {...props} />)`
```
Comment (slowbackspace) [inline packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx:5]:
```
const StyledLoading = styled(Loading)`
```
should be enough unless you run into one bug and in order to resolve it you really needed to spread props like that. I am nitpicking this just to make sure.

Comment (slowbackspace) [reply packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx:5]: There are few other places like this, I am gonna keep only this one comment so it won't get too messy

File: packages/suite/src/components/wallet/AccountsMenu/index.tsx [hunk 4]
```diff
@@ -82,7 +84,7 @@ const Heading = styled(H2)<{ isMobileLayout?: boolean }>`
 const MenuItemsWrapper = styled.div`
     position: relative;
     width: 100%;
-    height: 100vh;
+    height: ${isDesktop() ? `calc(100vh - ${DESKTOP_TITLEBAR_HEIGHT})` : '100vh'};
```
Comment (slowbackspace) [inline packages/suite/src/components/wallet/AccountsMenu/index.tsx]: I am not sure about this one, just making note I'll test it later. but most likely it works correctly.
(this component is used only in mobile layout)

File: packages/suite/src/views/suite/notifications/index.tsx [hunk 5]
```diff
@@ -33,7 +34,7 @@ const EmptyWrapper = styled.div`
     flex-direction: column;
     align-items: center;
     padding: 16px 32px 32px 32px;
-    height: 100vh;
+    height: ${isDesktop() ? `calc(100vh - ${DESKTOP_TITLEBAR_HEIGHT})` : '100vh'};
```
Comment (slowbackspace) [inline packages/suite/src/views/suite/notifications/index.tsx:37]: hmm I think there shouldn't even be specified height for this component (it is vertically centering few elements that shouldn't really be centered, offset from the top would be much better), but ofc it's out of scope of this PR

**Review by slowbackspace — CHANGES_REQUESTED** [review]
just a few nitpicks so it looks like I am working hard. You can decide if they do make sense or are not worth the effort 🙇 

I haven't tested it, if you also haven't then pls check realy quick with QA to make sure there is nothing obviously broken 🙏

File: packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx (hunk 3 above)
Comment (tomexx) [reply packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx:5]: I added this, because I had problems with circular dependencies and the build didn't work :( I found this "fix" in some other places...

Comment (slowbackspace) [reply packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx:5]: yup I was afraid this was the case, no problem here then :)

**Comment by szymonlesisz** [comment]
this change looks huge to archive what we want
`body { border: 1px solid black; }` is not enough? :)

**Comment by tomexx** [comment]
> this change looks huge to archive what we want
> `body { border: 1px solid black; }` is not enough? :)

I thought so too but it turned into a rabbit hole 😅

**Comment by tsusanka** [comment]
No reason to rush this into the release, it's quite big and not critical.

File: packages/suite/.stylelintignore (hunk 1 above)
Comment (tomexx) [reply packages/suite/.stylelintignore:5]: For some reason it doesn't stop failing with inline disable rule. It still fails with `Unexpected token`, so I keep it in packages/suite/.stylelintignore

File: packages/suite/src/components/wallet/AccountsMenu/index.tsx (hunk 4 above)
Comment (tomexx) [reply packages/suite/src/components/wallet/AccountsMenu/index.tsx]: I just wanted to keep it consistent but it might be better to remove it when user is not allowed to make the desktop window small enough to trigger this component. I'll do that 👍

Comment (slowbackspace) [reply packages/suite/src/components/wallet/AccountsMenu/index.tsx]: yeah that was more note to myself, I actually think there will be some visual bug as height 100vh for this component would mean it will get outside of viewport because there are some additional components on top that are eating from the 100vh 😁

File: packages/suite/src/components/suite/Modal/index.tsx (hunk 2 above)
Comment (slowbackspace) [reply packages/suite/src/components/suite/Modal/index.tsx]: @tomexx what do you think? 😁

**Review by slowbackspace — APPROVED** [review]
