### PR TITLE
Don't use zero keypair in first THP pairing

### LINKED ISSUE #22263: THP pairing shown only after first reconnection and never after that (even though the device connects)
**Describe the bug**
The THP pairing for already connected and paired device is shown only once after the first reconnection and never again after any other reconnection if I kill the app and open it again.

**Info:**

- Mobile Suite Version: version/commit
- OS: name, version

**How to reproduce**

1. Connect and pair a device
2. Wait for the discovery to finish
3. Kill the app
4. Open the app again
5. THP pairing should be shown on the device 
6. Kill app again
7. Open the app once again
8. There is no THP pairing and the device blinks for a split second
9. This happens for every other reconnect like this

**Additional context**
Slack [here](https://satoshilabs.slack.com/archives/C078GRAK58U/p1759821854443279)

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

a) Don't mutate input param in `getCurve25519KeyPair` (small bug, but because of it `staticKey` silently changed when `hostStaticKeys` were first derived from it)

b) Don't use dummy zero keypair for the first pairing, but the same randomly generated `hostStaticKeys` as in the consecutive pairings (which was discussed in https://satoshilabs.slack.com/archives/C078GRAK58U/p1740132971826629?thread_ts=1739181741.870599&cid=C078GRAK58U but didn't make it into THP spec).

This should resolve the behavior where the device asks for THP confirmation after the first reconnection (= no channel replacement) but doesn't after the second one ( = channel replacement).

Resolves https://github.com/trezor/trezor-suite/issues/22263

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/thp-channel-replacement&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/thp-channel-replacement&lookback=7)

### CODE REVIEW

File: packages/protocol/src/protocol-thp/crypto/curve25519.ts [hunk 1]
```diff
@@ -245,7 +245,8 @@ export function elligator2(point: Uint8Array): Uint8Array {
 
 // https://cr.yp.to/ecdh.html
 // Computing secret keys
-export const getCurve25519KeyPair = (randomPriv: Buffer) => {
+export const getCurve25519KeyPair = (randomBytes: Buffer) => {
+    const randomPriv = Buffer.from(randomBytes);
```
Comment (M1nd3r) [inline packages/protocol/src/protocol-thp/crypto/curve25519.ts:249]: Q: Will this result in the same static private key being used for all Trezors? I am unsure where was the original issue this aims to solve. :)

**Review by M1nd3r — COMMENTED** [review]
The fix - not using base-point for static key derivation is Approved by me.

I have a question in the comment about the mutability of the input params.

File: packages/protocol/src/protocol-thp/crypto/curve25519.ts (hunk 1 above)
Comment (marekrjpolak) [reply packages/protocol/src/protocol-thp/crypto/curve25519.ts:249]: No, the issue was that in `handshake.ts` after this:
```typescript
    const staticKey = settings?.staticKey
        ? Buffer.from(settings.staticKey, 'hex')
        : randomBytes(32);
    const hostStaticKeys = protocolThp.getCurve25519KeyPair(staticKey);
```
`staticKey` was different than before calling `getCurve25519KeyPair` because of the bit operations inside.

But with or without this fix, it really looks like `staticKey`, once generated, is being used for all devices.

Comment (M1nd3r) [reply packages/protocol/src/protocol-thp/crypto/curve25519.ts:249]: ok, the reuse of the staticKey is a smaller issue that can be fixed later 🤔 

The idea is that a random static key is used when the device is unknown. Once the pairing is finished/credential received, this static key should be stored - on per-Trezor base.

But the use of the base point for static key is a bigger problem, so I am in favor of merging this asap.

utACK

**Review by M1nd3r — APPROVED** [review]
utACK
