### PR TITLE
9052 maximum characters on account import

### LINKED ISSUE #9052: Maximum characters not checked during account import
**Describe the bug**
- during import of account/address you can change default Coin label  but we dont limit characters amount till you press Confirm
- during renaming  of account  when already imported we check characters amount and we display count and maximum of 30 chars allowed

**Info:**

-  1b4cd62 - [develop] - fix(suite-native): use base jest config instead of native in assets pkg

**Screenshots**
image

### PR DESCRIPTION
**Pull request by jbazant**
## Description

Also fixed some translations.

## Related Issue

Resolve #9052

## Screenshots:

https://github.com/user-attachments/assets/d2eca68a-6b6a-4571-81c4-683b22b31aa2

### CODE REVIEW

File: suite-native/module-accounts-management/src/components/AccountRenameButton.tsx [hunk 1]
```diff
@@ -22,7 +28,7 @@ export const AccountRenameButton = ({ accountKey }: AccountRenameModalProps) =>
                 onPress={handleOpen}
                 testID="@account-detail/settings/edit-button"
             />
-            <BottomSheet title="Rename coin" isVisible={isVisible} onClose={handleClose}>
+            <BottomSheet title={bottomSheetTitle} isVisible={isVisible} onClose={handleClose}>
```
Comment (vytick) [inline suite-native/module-accounts-management/src/components/AccountRenameButton.tsx]: You can use `title={<Translation id="translation-id-string" />}`

Please use Translation where possible, because we might add more functionality to `Translation` later (thinking about adding string formatting there).

File: suite-native/module-accounts-import/src/components/AccountImportOverview.tsx [hunk 2]
```diff
@@ -37,12 +51,16 @@ export const AccountImportOverview = ({ balance, symbol }: AssetsOverviewProps)
...
-                    testID="@account-import/coin-synced/label-input"
-                    name="accountLabel"
-                    label="Coin label"
-                    elevation="1"
-                />
+                <VStack spacing="sp8">
+                    <TextInputField
+                        testID="@account-import/coin-synced/label-input"
+                        name="accountLabel"
+                        label={coinLabelFieldLabel}
```
Comment (vytick) [inline suite-native/module-accounts-import/src/components/AccountImportOverview.tsx:58]: please, also here use `<Translation `

**Review by vytick — COMMENTED** [review]
Works nicely 👍. Just a minor thing: Please, use `<Translation ...` instead of `useTranslate` hook where possible.

File: suite-native/module-accounts-import/src/components/AccountImportOverview.tsx (hunk 2 above)
Comment (jbazant) [reply suite-native/module-accounts-import/src/components/AccountImportOverview.tsx:58]: Actually no, it is not possible to use Translation component here. `label` prop expects `string` not an `Element`

File: suite-native/module-accounts-management/src/components/AccountRenameButton.tsx (hunk 1 above)
Comment (jbazant) [reply suite-native/module-accounts-management/src/components/AccountRenameButton.tsx]: Fixed

File: suite-native/module-accounts-import/src/components/AccountImportOverview.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/module-accounts-import/src/components/AccountImportOverview.tsx:58]: Oh, my bad, you are right 👍

**Review by vytick — APPROVED** [review]
Good job 👍 🚀
