### PR TITLE
fix(suite): rephrase dust limit validation message

### LINKED ISSUE #6154: Rephrase dust limit validation message
**Describe the bug**
When the user attempts to send an amount equal to dust limit, validation message says they are below dust limit.

**How to reproduce**
Try to send 546 sats from a bitcoin account.

**Expected behavior**
Either the message should change or the transaction should be allowed.

**Screenshots**
Screenshot 2022-08-30 at 19 04 23

### PR DESCRIPTION
**Pull request by komret**
Change validation message.

## Related Issue

Resolve #6154

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -4917,7 +4917,7 @@ export default defineMessages({
         id: 'AMOUNT_IS_TOO_LOW',
     },
     AMOUNT_IS_BELOW_DUST: {
-        defaultMessage: 'Amount is below the dust limit ({dust})',
+        defaultMessage: 'Amount must be greater than the dust limit ({dust})',
```
Comment (matejkriz) [inline packages/suite/src/support/messages.ts:4920]: This change would be overwritten by next Crowdin synchronization, see https://satoshilabs.slack.com/archives/CKZHV2G13/p1662039720132549

I just applied this one for you https://crowdin.com/translate/trezor-suite/103/en-en?filter=basic&value=3#q=AMOUNT_IS_BELOW_DUST
