### PR TITLE
fix(suite-native): legacy segwit address T1B1

### LINKED ISSUE #10351: T1: Receive address on device has different break point than on mobile screen
Steps to reproduce:
- Connect Trezor One to mobile app
- Receive BTC Segwit
- Show full address
- Compare the addresses on device and mobile screen - the line breaking is different

Expected behaviour: line breaking should be same on both screens

Image
Image

### PR DESCRIPTION
**Pull request by PeKne**
Legacy Segwit address is only 34 characters long. T1B1 displays it in two lines, 17 characters each for a symmetric look. This PR adds check for Legacy Segwit address. If matched, breaks the line same as device does.

Closes #10351 

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/17a7398b-0e6a-4887-b297-a68b19a6b57d

### CODE REVIEW

File: suite-native/receive/src/utils.ts [hunk 1]
```diff
@@ -34,7 +37,14 @@ export const parseAddressToDeviceLines = ({
 >) => {
     // T1B1 does not have support fro address chunking
     if (deviceModel === DeviceModelInternal.T1B1) {
-        return pipe(address, S.toArray, A.splitEvery(21), A.map(A.join('')));
+        // Legacy Segwit address is only 34 characters long. T1B1 displays it in two lines, 17 characters each for a symmetric look.
+        // Any other address takes the full line length.
+        const charactersPerLine =
```
Comment (Nodonisko) [inline suite-native/receive/src/utils.ts:42]: Would be better to pass address type directly, but this is good enough.

**Review by Nodonisko — APPROVED** [review]
