### PR TITLE
fix(suite-native): tweak fiat amount skeletons to prevent layout shift

### LINKED ISSUE #13299: Loading fiat value should show skeleton instead of 0 value
**Describe the bug**
- fiat values of portfolio are not cached
- when you start app when offline you see all fiat values with zero value
- before fiat values are fetched from servers after you see start app all values are zero too for quite a long time
- same results for latest dev version, 24.7.1 version and two weeks old dev version

**Steps to reproduce:**
1. Import multiple accounts
2. Kill app
3. Start app with phone in flight mode or observe app before values are fetched from servers

**Info:**
 - Suite version: Release notes for 24.6.0 (350)
Last commit hash: 8a20d9cf4567a8077dd95d88212f9bd2eb66f89e

**Screenshots:**

telegram-cloud-photo-size-4-5801191960428528094-y

https://github.com/trezor/trezor-suite/assets/31506317/f965e330-d720-4c4c-add4-57c88a00244a

### PR DESCRIPTION
**Pull request by yanascz**
Also one big skeleton for fiat balance was split into two smaller ones.

## Related Issue

Resolve #13299

## Screenshots:
graph
accounts

### CODE REVIEW

File: suite-native/graph/src/components/GraphFiatBalance.tsx [hunk 1]
```diff
@@ -37,13 +46,13 @@ export const GraphFiatBalance = ({
     const firstGraphPoint = useAtomValue(referencePointAtom);
 
     if (!firstGraphPoint) {
-        return <BoxSkeleton width={120} height={73} />;
+        return <Skeleton />;
     }
 
     return (
-        <>
+        <Box alignItems="center" style={{ height: 72 }}>
```
Comment (matejkriz) [inline suite-native/graph/src/components/GraphFiatBalance.tsx]: Avoid inline styles, please. 

And also - is the fixed height here really necessary? It's kind of ok for the skeletons, but here it's container for real values and if user have bigger font stale, the value can't fit here, I guess

File: suite-native/formatters/src/components/EmptyAmountSkeleton.tsx [hunk 2]
```diff
@@ -0,0 +1,13 @@
+import { BoxSkeleton, HStack } from '@suite-native/atoms';
+
+import { EmptyAmountText } from './EmptyAmountText';
+
+export const EmptyAmountSkeleton = () => {
+    // Usage of EmptyAmountText ensures the correct line height.
```
Comment (matejkriz) [inline suite-native/formatters/src/components/EmptyAmountSkeleton.tsx:6]: Good idea!

File: suite-native/graph/src/components/GraphFiatBalance.tsx (hunk 1 above)
Comment (yanascz) [reply suite-native/graph/src/components/GraphFiatBalance.tsx]: I don't like it here either but I don't know how to ensure that the height doesn't change after the loading is done. That's what causes the layout to shift. 😕 

I'm open to other ideas if you have some.

Comment (matejkriz) [reply suite-native/graph/src/components/GraphFiatBalance.tsx]: Never mind, it looks OK even on the biggest scale, so let's not spend more time on it now
image

**Review by matejkriz — APPROVED** [review]
Very nice beautiful 😍
