### PR TITLE
Cardano token definitions fix

### LINKED ISSUE #13169: Carano tokens with same policy id are hidden at once
**Describe the bug**
Carano tokens with same policy id are hidden at once.
When sending via Token section first and not actual token with same id is selected

**Steps to reproduce:**
see both videos

**Info:**
 - Suite version: desktop 24.7.1 (3856b5e5f845e68f754487dee863c6ea0c347070)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/ae43a0b4-83ca-41f8-90e6-a3cbc64ceaf5

https://github.com/trezor/trezor-suite/assets/31506317/f64e965e-ecef-4345-b8f4-af5cc5a27a79

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- revert using policy id as contract address as it is not really needed and it was breaking send form because policy id is not unique (aha) and this solution is better (no changes to critical methods)
- fixes coins without token definitions have all tokens "legit" by default
- fiats are now fetched first for policy id, then for unit
  - coingecko mixes them together (token definitions are modified so that they use only policy ids)
- policy id is now used for token definitions (policy id is part of unit which is contract address so it works!)
- show also unit to a user

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13169

## Screenshots:

if you compare it with  #13093 we also have fiat for banker coin! because that one uses unit and not policy id on coingecko 🙃 
Screenshot 2024-07-04 at 13 19 40

(token-definitions turned on just for this screenshot)
Screenshot 2024-07-04 at 13 19 48
Screenshot 2024-07-04 at 13 25 51

### CODE REVIEW

**Comment by tomasklim** [comment]
@trezor/qa 
- check that cardano tokens can be send (also the ones with same policy id)
- check migration again please and that it works after the migration
- check that fiat rates and historic rates work for coins using and not blockbook
- coins without token definitions (e.g. testnet ada should have tokens by default legit)

File: packages/suite/src/utils/wallet/tokenUtils.ts [hunk 1]
```diff
@@ -93,11 +95,11 @@ export const getTokens = (
...
-        if ((isKnown && !isHidden) || isShown) {
+        if ((!hasCoinDefinitions && !isHidden) || (isKnown && !isHidden) || isShown) {
             shown.push(token);
-        } else if (!isKnown && !isShown) {
+        } else if (hasCoinDefinitions && !isKnown && !isShown) {
             unverified.push(token);
-        } else if (isKnown && isHidden) {
+        } else if ((isKnown && isHidden) || (!hasCoinDefinitions && isHidden)) {
             hidden.push(token);
         }
```
Comment (marekrjpolak) [inline packages/suite/src/utils/wallet/tokenUtils.ts:106]: Isn't this a bit better readable? It should be equivalent I believe.
```
if (isShown) {
    shown.push(token);
} else if (hasCoinDefinitions && !isKnown) { 
    unverified.push(token);
} else if (isHidden) {
    hidden.push(token);
} else {
    shown.push(token);
}
```

Comment (tomasklim) [reply packages/suite/src/utils/wallet/tokenUtils.ts:106]: I think it is 35861a2d508ba415eb27f86b26b618e0341bcf59

**Review by marekrjpolak — APPROVED** [review]

**Comment by bosomt** [comment]
**work in progress**

Upgrade from
2.6.0 8ca01119 to
24.8.0 13658c435355c2c398260f028a1e802813f07c32

- [send TADA
](https://preview.cexplorer.io/tx/4a1851463607b9913d5129f1d8a09663942529312ec4435b4957fcf97e7a6ea9) 
-  explorer link ok
- [send TADA token](https://preview.cexplorer.io/tx/d21698db85d78b0b625d295025d8b5f5ad18963deaf1ecf0329dde6cdfd731d9)
-  explorer link ok
- hide token ok
- show token ok
- view token in explorer ok
- fingerprint copy ok
- policy id ok

**Comment by tomasklim** [comment]
do not merge yet please
