### PR TITLE
fix(suite-common): sanitise fetching graph history rates for empty account

### LINKED ISSUE #14502: Error in graph on empty account with range "ALL"
**Describe the bug**
When I sync or connect and empty account and select "ALL" on the graph range, the graph shows an error.

**Info:**

-   Mobile Suite Version: version/commit
-   OS: name, version

**How to reproduce**

1. Connect an empty seed device or sync empty account
2. On the graph select the "ALL" range
3. Observer the error in the graph

**Screenshots**
image

### PR DESCRIPTION
**Pull request by vytick**
When no start timestamp was selected for wallet with only empty accounts, it threw range error. This was because `getTimestampsInTimeFrame` would receive equal start date and end date. This can happen only if user has no account with txn history at all.  

So in such case I check and change the start date to 1y ago, to work the same as when such option(1y) is  selected.

## Related Issue

Resolve #14502

### CODE REVIEW

File: suite-common/graph/src/graphDataFetching.ts [hunk 1]
```diff
@@ -409,6 +409,13 @@ export const getMultipleAccountBalanceHistoryWithFiat = async ({
             findOldestBalanceMovementTimestamp,
             fromUnixTime,
         );
+
+        // if there were no balance movements at all,
+        // findOldestBalanceMovementTimestamp resulted with start date being the same as end date
+        // use 1 year into past instead, otherwise getTimestampsInTimeFrame will throw range error
+        if (startOfTimeFrameDate.getTime() === endOfTimeFrameDate.getTime()) {
```
Comment (Nodonisko) [inline suite-common/graph/src/graphDataFetching.ts:416]: I am not sure if this si best fix. I think it may be better to just return early here since if there is no movement we know that graph will just zero all the time. I think `return []` or return `[{ date: 1, value: 0 }, {date: 2, value: 0}]` should work and it will be faster because otherwise we will be fetching timestamps for that whole year.

Comment (vytick) [reply suite-common/graph/src/graphDataFetching.ts:416]: So in such case it should probably check for every time if there are no movements of any coin to return early for each option 1d/1w/1m/...

I was thinking about this, but it felt suboptimal for such edge case. And this is the same behaviour there is for 1y option.

Comment (vytick) [reply suite-common/graph/src/graphDataFetching.ts:416]: Ok. I'll modify the behaviour for empty history.

Comment (matejkriz) [reply suite-common/graph/src/graphDataFetching.ts:416]: Another thing I'd be a little worried about is mutating `startOfTimeFrameDate` which is passed as parameter to this function. I'd rather define a new constant for it locally... But maybe it's ok, it's just harder to think about possible consequences. (But the mutation was there even before this PR, I know...)

Comment (vytick) [reply suite-common/graph/src/graphDataFetching.ts:416]: I've added check for empty account in 2091d876ab and kept the timeframe update to better UX when touching the graph.

Comment (Nodonisko) [reply suite-common/graph/src/graphDataFetching.ts:416]: Sorry but it seems unecessary complicated now, I need to take a proper look and think about it.

Comment (Nodonisko) [reply suite-common/graph/src/graphDataFetching.ts:416]: I still think that best solution is return early if  `startOfTimeFrameDate === endOfTimeFrameDate` because that's easy and will fix the issue. Don't care about the other timeframes it's not worth added complexity.

Comment (vytick) [reply suite-common/graph/src/graphDataFetching.ts:416]: simplified [49b17fd](https://github.com/trezor/trezor-suite/pull/14506/commits/49b17fd0b5ef5065cce409f9e1a7d69e19f0f1d9)

**Review by Nodonisko — APPROVED** [review]
