### PR TITLE
fix(suite-native): TradeDetailSheet scrolling issues

### LINKED ISSUE #18792: Mobile Trade: refactor TradeDetailSheet to use BottomSheetModal instead of BottomSheet
`TradeDetailSheet` sometimes isn't draggable. The root cause seems to be that `BottomSheet` somehow wrongly hijacks scroll event as a drag event for the whole sheet and does not scroll. 

**Task:** Rewrite `TradeDetailSheet` to use `BottomSheetModal` instead and also use `useBottomSheetModal` to handle open / close. See how `TransactionDetailSheet` has it implemented

### PR DESCRIPTION
**Pull request by tomasjakl**
## Description

- c77ef73 Switches from BottomSheet to BottomSheetModal in TradeDetailSheet to address problems with unscrollable content.

- e6ff633 Extracts the scrollable content of BottomSheetModal into a separate memoized BottomSheetModalContent component. This prevents unnecessary rerenders of BottomSheetScrollView when scrollDivider changes, resolving scroll jump issues caused by rerendering.

## Related Issue

Resolve #18792 

### Before

https://github.com/user-attachments/assets/b3cab653-61f9-419d-b2fc-eea47bcba95f

https://github.com/user-attachments/assets/c5462e71-38a8-44d4-be91-51406860c576

### After 

https://github.com/user-attachments/assets/3fdf214b-fda6-4964-8e7f-56eda09b17e8

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=18792-mobile-trade-refactor-tradedetailsheet-to-use-bottomsheetmodal-instead-of-bottomsheet&lookback=7)

### CODE REVIEW

**Comment by tomasjakl** [comment]
@coderabbitai full review

File: suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+        const { bottom } = useSafeAreaInsets();
+
+        return (
+            <BottomSheetScrollView
+                style={applyStyle(containerStyle)}
+                onScroll={handleScroll}
+                testID="@bottom-sheet/scroll-view"
+            >
+                <AnimatedBox
+                    paddingHorizontal="sp16"
```
Comment (jbazant) [inline suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx]: **nitpick (non-blocking):** I understand that was just copy&pasted, but I would like much more if we put this style to `childWrapperStyle` as well. Just to have all styles on one place.‏

File: suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+const containerStyle = prepareNativeStyle(() => ({
+    flex: 1,
+}));
+
+interface BottomSheetModalContentProps extends BoxProps {
+    handleScroll: (event: NativeSyntheticEvent<NativeScrollEvent>) => void;
+}
+
+export const BottomSheetModalContent = memo<BottomSheetModalContentProps>(
```
Comment (jbazant) [inline suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx:27]: **praise:** Nice separation of concerns. I really like that this was refactored to separate component!‏

**Review by jbazant — APPROVED** [review]
Looks great, just one a bit out-of-scope nitpick.

File: suite-native/module-trading/src/components/general/TradeDetailSheet/TradeDetailSheet.tsx [hunk 3]
```diff
@@ -12,29 +15,46 @@ import { TradeDetailTransactionInfo } from './TradeDetailTransactionInfo';
...
     gap: spacings.sp16,
 }));
 
-export const TradeDetailSheet = ({ orderId, isVisible, onClose }: TradeDetailSheetProps) => {
+export const TradeDetailSheet = memo(({ orderId, isVisible, onDismiss }: TradeDetailSheetProps) => {
     const { applyStyle } = useNativeStyles();
     const trade = useSelector((state: TradingRootState) =>
         selectTradingTradeByOrderId(state, orderId),
     );
+    const bottomSheetModalRef = useRef<BottomSheetModalType>(null);
```
Comment (BrantalikP) [inline suite-native/module-trading/src/components/general/TradeDetailSheet/TradeDetailSheet.tsx:31]: not crucial, but in order to save some lines you can use https://github.com/trezor/trezor-suite/blob/develop/suite-native/atoms/src/Sheet/hooks/useBottomSheetModal.ts useBottomSheetModal:)

File: suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx]: Hey @jbazant hmm, I would say its fine as its actually purpose of the Component to accept the props this way

**Review by BrantalikP — APPROVED** [review]
works nicely 👌

File: suite-native/module-trading/src/components/general/TradeDetailSheet/TradeDetailSheet.tsx (hunk 3 above)
Comment (vytick) [reply suite-native/module-trading/src/components/general/TradeDetailSheet/TradeDetailSheet.tsx:31]: @tomasjakl please, use this hook 🙏 thanks

Comment (vytick) [reply suite-native/module-trading/src/components/general/TradeDetailSheet/TradeDetailSheet.tsx:31]: After the discussion, we'll do this together with LegalSheet in followup PR to unify the usage. Closing this for now. Thanks Petr

File: suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx (hunk 1 above)
Comment (tomasjakl) [reply suite-native/atoms/src/Sheet/BottomSheetModalContent.tsx]: Agree with @jbazant  on not mixing styling approaches. Fixed in: b7b2f1c1a9ef8f31a973fe44d931da040ad2803a, b933e574622aeeca144f0d4f90ad8d2ac406abc7

**Comment by STew790** [comment]
**QA OK**
LGTM now, easily scrollable without any issues.

**Info**
25.5.1 https://github.com/trezor/trezor-suite/commit/8664975974b0d8e2033e8566543e8fb8ec894bd7
