### PR TITLE
fix(suite-native): staking icon size

### LINKED ISSUE #17036: Staking icon for ETH is bigger then others in assets view
**Describe the bug**
The icon for staking is bigger then others.

**Info:**

-   Mobile Suite Version: 25.2.1 5336151
-   OS: name, version

**How to reproduce**

1. On the dashboard, click on ETH
2. See the icon for staking on your account
3. It is larger then the others

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by vytick**
Changed size of staking icon to fit other icons style

## Related Issue

Resolve #17036

## Screenshots:

before:

after:

### CODE REVIEW

**Review by PeKne — APPROVED** [review]

File: suite-native/accounts/src/components/AccountsList/AccountsListStakingItem.tsx [hunk 1]
```diff
@@ -20,27 +21,37 @@ export const AccountsListStakingItem = ({
...
+        <AccountsListItemBase
+            {...props}
+            isLast={isLast}
+            showDivider={!isLast}
+            icon={
+                <RoundedIcon
+                    name="piggyBankFilled"
+                    color="iconSubdued"
+                    containerSize={utils.spacings.sp32}
+                />
```
Comment (matejkriz) [inline suite-native/accounts/src/components/AccountsList/AccountsListStakingItem.tsx:37]: I would make the icon bit smaller
image
```suggestion
                <RoundedIcon
                    name="piggyBankFilled"
                    color="iconSubdued"
                    containerSize={utils.spacings.sp32}
                    iconSize="mediumLarge"
                />
```

Comment (matejkriz) [reply suite-native/accounts/src/components/AccountsList/AccountsListStakingItem.tsx:37]: And the background color seems too subtle to me, but that’s a different issue.

Comment (matejkriz) [reply suite-native/accounts/src/components/AccountsList/AccountsListStakingItem.tsx:37]: I'm taking my comment back, it looks better in the app with the original icon size (because background color is invisible anyway), than on the screenshot...

**Review by matejkriz — APPROVED** [review]
