### PR TITLE
fix(connect): module dynamic import issue

### LINKED ISSUE #23593: @trezor/connect v9.6.4 doesn't work with solana correctly.
I've been developing a trezor integration for a node.js cli app and appears to be no solana methods can be invoked at all with the @trezor/connect v9.6.4 node package.

For e.g. invoking the `solanaGetPublicKey` method throw an error with the following message (same for other sol methods):
```
'Cannot find module ../api/solana/api/index.ts' from '/MY_APP/node_modules/@trezor/connect/lib/core/method.js'
```

Somehow I downgraded the @trezor/connect package to 9.4.2 and it suddenly just works.

Maybe it's all related to the node.js module system that changes all the time. I tried to run a simple cli app with Node 25 via ts-node and tsx and with bun.js. It always produces the same error under any tsconfig.json I set up.

Maybe there's specific env requirements to develop with newer versions of @trezor/connect which I don't know (like a specific Node version or tsconfig.json must be setup with distinct options).
Would be great if the documentation is improved on this matter and more working examples are provided.

Let me know if you need more details about my dev env.

### PR DESCRIPTION
**Pull request by martykan**
## Description

Changes in #17152 added `index.ts` to the runtime import path for Connect modules, which is not available in the published package. It should be `index.js`
However for Webpack and Vite we want to keep `index.ts`.

This is fixed by updating the replace-imports babel script to handle this case, resulting in the following change in the build:
```
lib/core/method.js newlib/core/method.js
20c20
<   const methods = methodModule ? await Promise.resolve(`${`../api/${methodModule}/api/index.ts`}`).then(s => tslib_1.__importStar(require(s))) : Methods;
---
>   const methods = methodModule ? await Promise.resolve(`${`../api/${methodModule}/api/index.js`}`).then(s => tslib_1.__importStar(require(s))) : Methods;
```

## Related Issue

Resolve #23593

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/connect-module-import&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/connect-module-import&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/connect-module-import&lookback=7)

### CODE REVIEW

File: scripts/publish/replace-imports.sh [hunk 1]
```diff
@@ -28,5 +28,4 @@ else
     BABEL_CONFIG="$SCRIPT_DIR/babel.config.cjs.json"
 fi
 
-
-babel "$1" --out-dir "$1" --extensions ".js" --config-file "$BABEL_CONFIG"
+yarn run -T babel "$1" --out-dir "$1" --extensions ".js" --config-file "$BABEL_CONFIG"
```
Comment (Lemonexe) [inline scripts/publish/replace-imports.sh:31]: oh yeah, @OriginalEveres also reported that `babel` is not found.
Guess that's macOS specific.

**Review by Lemonexe — APPROVED** [review]
LGTM, thanks for fixing this!
