### PR TITLE
fix(suite): prevent multiple clicks on the backup selection

### LINKED ISSUE #7867: "Error: Device call in progress" in onboarding
**Describe the bug**
When I go through the onboarding process and I get to choosing either "Standard backup" or "Shamir backup" I should be better navigated to use the Trezor device for confirmation of this. When I try to click one of the options again I get "Error: Device call in progress" because the Trezor wants me to confirm the option I chose earlier. There should be something like "Accepts on device" or something like that.

**Steps to reproduce:**
1. Trezor T without seed.
2. Go through the onboarding till you get to choosing the backup type.
3. Select one of the backup types and try to click on (or the other one) multiple times
4. You will see "Error: Device call in progress"

**Info:**
 - Suite version: desktop 23.4.0 (1c4c12d8d0b0cc76145c20a0b2475b21fc7bd745)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/110.0.5481.104 Electron/23.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision e2416bcec2072baf65dda2d3c2359cc7217753bc)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
User should be shown to continue on device after selecting the type of backup in the onboarding process.

**Actual result:**
Unclear instructions in onboarding process can lead to selecting the type of backup again in Suite which results in "Error: Device call in progress" error.

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

This PR implements a lock for `resetDevice` so it is not possible to get `"Error: Device call in progress"`

## Related Issue 

Resolve https://github.com/trezor/trezor-suite/issues/7867

### CODE REVIEW

**Comment by mroz22** [comment]
imho "suite.locks" and connect methods override should be used here. see here https://github.com/trezor/trezor-suite/pull/9858

File: suite-common/connect-init/src/connectInitThunks.ts [hunk 1]
```diff
@@ -52,31 +52,32 @@ export const connectInitThunk = createThunk(
...
+            'checkFirmwareAuthenticity',
+            'cipherKeyValue',
+            'ethereumGetAddress',
+            'ethereumSignTransaction',
+            'getAddress',
+            'getDeviceState',
+            'getFeatures',
             'getOwnershipProof',
-            'setBusy',
+            'pushTransaction',
```
Comment (peter-sanderson) [inline suite-common/connect-init/src/connectInitThunks.ts:71]: this added, otherwise just sorted alphabetically for more readability

File: suite-common/connect-init/src/connectInitThunks.ts [hunk 2]
```diff
@@ -52,31 +52,32 @@ export const connectInitThunk = createThunk(
...
             'rebootToBootloader',
-            'cipherKeyValue',
+            'recoveryDevice',
+            'resetDevice',
```
Comment (peter-sanderson) [inline suite-common/connect-init/src/connectInitThunks.ts:74]: this added, otherwise just sorted alphabetically for more readability

**Review by komret — APPROVED** [review]
👏
