### PR TITLE
fix(suite): T1B1 initialization

### LINKED ISSUE #20165: Cannot initialize wiped T1B1. Invalid version error.
**Describe the bug**
Cannot initialize new T1B1. `Invalid Version:` error.

**Steps to reproduce:**
1. Connect factory wiped T1B1
2. Click Set up my Trezor
3. Observe error
4. Clearing storage and reset do not help.

Image

**Info:**
 - Suite version: desktop 25.7.1 (3d86e4b326236bb1cbe13ff7fb185be665c1f059)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.7.1 Chrome/134.0.6998.178 Electron/35.1.2 Safari/537.36
 - OS: MacIntel and Windows
 - Screen: 1512x982
 - Device: Trezor T1B1  undefined (revision null)
 - Transport: BridgeTransport 2.0.33

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Device in bootloader mode returns `''` as FW version, so detect it and early return.

## Related Issue

Resolve #20165

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/T1B1-initialization&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/T1B1-initialization&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/suite/useFirmwareInstallationProgressCheck.ts [hunk 1]
```diff
@@ -15,6 +15,8 @@ const MIN_T1B1_FW_VERSION = '1.12.1';
  */
 const getCheckSupport = (device?: TrezorDevice): boolean => {
     const isT1B1 = device?.features?.internal_model === DeviceModelInternal.T1B1;
+    const deviceFWVersion = getFirmwareVersion(device);
+    if (semver.valid(deviceFWVersion) === null) return false;
```
Comment (Lemonexe) [inline packages/suite/src/hooks/suite/useFirmwareInstallationProgressCheck.ts:19]: it returns string or null
https://github.com/npm/node-semver/blob/main/functions/valid.js
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/semver/functions/valid.d.ts

**Review by peter-sanderson — APPROVED** [review]
