### PR TITLE
Fix/graph axis overflow

### LINKED ISSUE #10639: Graph value is cropped when user goes from Home to My Assets and back
The graph at Home screen does not show the balance correctly after tapping “My assets” and then “Home”.

Image

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- b4649f566120d052eaf8a206824d87ae5547f9bf: redundant axis clamping removed 
- c70aae63d0ef70287e2d939fea0cb85b32dfbb61: axis overflow checked after every transition back to the screen
## Related Issue

Resolve #10639 

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/83991b72-44d2-4329-869c-180c5bca7fca

### CODE REVIEW

File: suite-native/graph/src/components/AxisLabel.tsx [hunk 1]
```diff
@@ -52,6 +55,12 @@ export const AxisLabel = ({ x, value }: AxisLabelProps) => {
         }
     }, [utils]);
 
+    // We need to check the axis overflow on every return to a already rendered graph screen, because it might be shifted by the previous screen transition animation.
+    // The timeout is needed because the calculation has to be started after the screen transition animation is finished.
+    useFocusEffect(() => {
+        setTimeout(handleLayoutOverflow, SCREEN_TRANSITION_ANIMATION_DURATION);
```
Comment (Nodonisko) [inline suite-native/graph/src/components/AxisLabel.tsx]: cleanup missing

Comment (PeKne) [reply suite-native/graph/src/components/AxisLabel.tsx]: fixup 852e237e17

**Review by Nodonisko — APPROVED** [review]
