### PR TITLE
fix(suite-native): transaction list item layout

### LINKED ISSUE #7519: TransactionListItem broken design
There is broken layout for transaction list item on different view ports. Fix according to design using flex and remove margins. 

Design: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=8232%3A51930&t=K0bxw9NMaP2HuR9F-4

Image

### PR DESCRIPTION
**Pull request by PeKne**
## Related Issue
fixes #7519

## Screenshots:

Screenshot 2023-02-02 at 18 54 16

Tested on the iOS phone and Android tablet.

### CODE REVIEW

File: suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx [hunk 1]
```diff
@@ -117,27 +118,29 @@ export const TransactionListItem = memo(
...
+                        <Box flexDirection="row" justifyContent="center">
+                            <Text>{transactionTypeProperties.prefix}</Text>
+                            <Box style={applyStyle(addressStyle)}>
+                                <Text
+                                    variant="label"
+                                    color="gray600"
+                                    numberOfLines={1}
+                                    ellipsizeMode="middle"
+                                >
+                                    {transaction.txid}
```
Comment (Nodonisko) [inline suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: I think we have this wrong all the time. `txid` is not equal from/to I think.

**Review by Nodonisko — CHANGES_REQUESTED** [review]

**Review by juriczech — APPROVED** [review]

File: suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: True. I didn't notice that. So there should be an input address for incoming transitions and an output address for outcoming transactions. What about the other types as `self`, `joint`, `failed` etc.?

Comment (Nodonisko) [reply suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: I think there should be output/input for every type of transaction

Comment (PeKne) [reply suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: It was changed in 4999afd8d to show the first transaction targets as `transaction.targets[0].addresses?.[0]`. Could you let me know if this is the correct solution?

In suite-desktop, they show all target addresses, not only the first one: https://github.com/trezor/trezor-suite/blob/d8b77aafb150766efa0c348f6e2b85299371e6dc/packages/suite/src/components/wallet/TransactionItem/components/TargetAddressLabel.tsx#L32-L43

File: suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx [hunk 2]
```diff
@@ -117,27 +118,29 @@ export const TransactionListItem = memo(
...
+                        <Box flexDirection="row" justifyContent="center">
+                            <Text>{transactionTypeProperties.prefix}</Text>
+                            <Box style={applyStyle(addressStyle)}>
+                                <Text
+                                    variant="label"
+                                    color="gray600"
+                                    numberOfLines={1}
+                                    ellipsizeMode="middle"
+                                >
+                                    {transaction.targets[0].addresses?.[0]}
```
Comment (Nodonisko) [inline suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: `transaction.targets[0]` could be undefined, so this will crash app in some cases with specific transactions (ERC tokens). Please create selectors `selectTransactionTargets` and `selectTransactionFirstTargetAddress` and handle all possible cases when things could be undefined.

Please use the same selector also for TransactionDetail (which is already crashing app for tokens).

Sorry for bloating this PR but we can't merge something that will crash app even more.

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx (hunk 1 above)
Comment (Nodonisko) [reply suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: We will have to create something like AddressFormatter, which will show for example only first adress (or any adress with label and onPress it will show some modal with other outputs). There is task for this but some parts need to be refined with @mnuky

Comment (mnuky) [reply suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: I'm not sure if I understand correctly the issue here. There is a improvement planned for shorten transaction IDs and addressed to be "clickable" and if user taps on it, toaster with full address appears. 
Screenshot 2023-02-06 at 13 07 02

File: suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx]: Selectors created in commit  [d26ca95](https://github.com/trezor/trezor-suite/pull/7529/commits/d26ca9505d9d5803da0acbf232d1f97b58971c98).

**Review by Nodonisko — APPROVED** [review]

File: suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx [hunk 3]
```diff
@@ -23,12 +28,15 @@ export const TransactionDetailData = ({ transaction, accountKey }: TransactionDe
         selectTransactionBlockTimeById(state, transaction.txid, accountKey),
     );
 
-    // Only one input and output address for now until UX comes up with design to support multiple outputs
-    const transactionOriginAddresses = transaction.details.vin[0].addresses;
-    const transactionTargetAddresses = transaction.targets[0].addresses;
+    // Only one input and output address for now until UX comes up with design to support multiple inputs/outputs.
+    const transactionInputAddres = useSelector((state: TransactionsRootState) =>
```
Comment (Nodonisko) [inline suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx]: typo: Addre**ss**

File: suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx [hunk 4]
```diff
@@ -23,12 +28,15 @@ export const TransactionDetailData = ({ transaction, accountKey }: TransactionDe
...
+        selectTransactionFirstInputAddress(state, transaction.txid, accountKey),
+    );
+    const transactionOutputAddres = useSelector((state: TransactionsRootState) =>
```
Comment (Nodonisko) [inline suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx]: typo: Addre**ss**

File: suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx (hunk 3 above)
Comment (PeKne) [reply suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx]: Good catch. fixed here d573289cc.

File: suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx (hunk 4 above)
Comment (PeKne) [reply suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx]: Fixed here d573289cc.

**Review by Nodonisko — APPROVED** [review]
