### PR TITLE
fix(suite-native): add qrcode padding

### LINKED ISSUE #10674: QR Code with dark mode
### **Describe the bug**
The border of the QR code on the receive screen is too narrow. Sometimes if you try to scan a QR code with dark mode enabled, the reader can not recognize the code.

### **How to reproduce**

1. Enabled dark theme
1. Open the receive screen with the address QR code
1. Try to scan the QR code with a low quality camera code reader

### **Expected behavior**
- The QR code is always recognized even when is the dark mode on.

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- qrcode white border padding made larger to avoid scanning problems with dark mode enabled
## Related Issue

Resolve #10674

### CODE REVIEW

File: suite-native/qr-code/src/components/QRCode.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ type QRCodeProps = {
 const SCREEN_WIDTH = Dimensions.get('screen').width;
 
 const MAX_QRCODE_SIZE = 250;
-const QRCODE_PADDING = 12;
+const QRCODE_PADDING = 24;
```
Comment (juriczech) [inline suite-native/qr-code/src/components/QRCode.tsx:15]: you can use `utils.spacing.large * 2` in styles below

Comment (PeKne) [reply suite-native/qr-code/src/components/QRCode.tsx:15]: This const is used also outside of the style object.

**Review by juriczech — APPROVED** [review]
