### PR TITLE
fix(suite-native): correct AlertSheet layout

### LINKED ISSUE #12035: Alert sheet layout glitch
**Describe the bug**
Alert sheet layout is broken. The pictogram is not centered.

**How to reproduce**
Open any alert sheet.
**Expected behavior**

**Screenshots**

Screenshot 2024-04-16 at 15 04 53

### PR DESCRIPTION
**Pull request by vytick**
Pictogram in AlertSheet had wrong layout after latest changes

Resolve #12035

### CODE REVIEW

File: suite-native/alerts/src/components/AlertSheet.tsx [hunk 1]
```diff
@@ -93,9 +95,11 @@ export const AlertSheet = ({ alert }: AlertSheetProps) => {
                         onStartShouldSetResponder={_ => true} // Stop the shake event trigger propagation.
                     >
                         <Card style={applyStyle(alertSheetContainerStyle)}>
-                            <VStack style={applyStyle(alertSheetContentStyle)} spacing="large">
+                            <VStack style={applyStyle(alertSheetContentStyle)}>
```
Comment (juriczech) [inline suite-native/alerts/src/components/AlertSheet.tsx:98]: Whyyy? 😄

**Review by juriczech — APPROVED** [review]

File: suite-native/alerts/src/components/AlertSheet.tsx (hunk 1 above)
Comment (vytick) [reply suite-native/alerts/src/components/AlertSheet.tsx:98]: I believe there si no reason to have two different ways to style the same component
