### PR TITLE
fix(suite-native): Process other cancel code in recovery

### LINKED ISSUE #21703: Cannot cancel recovery
1. Trigger recovery flow in app
2. choose number of words on Trezor
3. Cancel recovery flow on Trezor (see `processing` loader → homescreen)
4. Recovery flow starts over automatically

(Suite cannot detect changed state)

**Info:**
 - Suite version: mobile 6bc05ed
 - OS: Android 15

### PR DESCRIPTION
**Pull request by 5K1PY**
## Description

Added other cancel code to prevent recovery loops.

## Notes for QA

**Affected areas:** Recovery flow on Android & iOS

## Related Issue

Resolve #21703

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/recovery-loop&lookback=7)

### CODE REVIEW

**Review by juriczech — APPROVED** [review]

File: suite-native/module-device-onboarding/src/screens/WalletRecoveryScreen.tsx [hunk 1]
```diff
@@ -24,7 +24,11 @@ export const WalletRecoveryScreen = ({
             });
         }
         // Do not retry if user cancelled the flow via the app UI
-        if (response.error.code && response.error.code === 'Method_Interrupted') return;
+        if (
+            response.error.code === 'Failure_ActionCancelled' ||
```
Comment (juriczech) [inline suite-native/module-device-onboarding/src/screens/WalletRecoveryScreen.tsx:28]: I think in this case you should call `navigateToInitialScreen`, because you're now left hanging on continue on your trezor screen if you cancel on device.

**Review by juriczech — CHANGES_REQUESTED** [review]

**Review by juriczech — APPROVED** [review]

File: suite-native/module-device-onboarding/src/screens/WalletRecoveryScreen.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/module-device-onboarding/src/screens/WalletRecoveryScreen.tsx:28]: As discussed, there will be a follow up for this.
