### PR TITLE
Strech banner full size security check

### LINKED ISSUE #17412: Incorrect align of banner in new welcome screen
**Describe the bug**
Incorrect align of banner in new welcome screen.
Attached web and app version screenshots

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 25.3.1 (e5b4203432360b831bb87d2bbfb2e0131e8aeae0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.3.1 Chrome/132.0.6834.194 Electron/34.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2B1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

Image

Image

### PR DESCRIPTION
**Pull request by vojtatranta**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17412#issuecomment-2733221608

### CODE REVIEW

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx [hunk 1]
```diff
@@ -83,7 +83,11 @@ export const WelcomeLayout = ({ children }: WelcomeLayoutProps) => {
                     <Right
                         bannerSlot={
                             bannerMessage && (
-                                <MessageSystemBanner message={bannerMessage} margin={spacings.xs} />
+                                <MessageSystemBanner
+                                    message={bannerMessage}
+                                    margin={spacings.xs}
+                                    width="100%"
```
Comment (komret) [inline packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx:89]: This could be the default value.

Comment (vojtatranta) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx:89]: That was my first though, but one never knows regarding styling around here :). cc @jvaclavik

Comment (jvaclavik) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx:89]: 100% as a default value could be safe here IMHO

**Review by jvaclavik — APPROVED** [review]

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx (hunk 1 above)
Comment (vojtatranta) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx:89]: Well, `< MessageSystemBanner>` is used also in Suitebanners, OnboardingLayout.

Comment (jvaclavik) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx:89]: OK, let's keep it this way. It doesn't matter much and it can break something if we will change the behaviour.

**Comment by bosomt** [comment]
**QA OK**

Linux:
image
