### PR TITLE
fix(suite): fix blinking connection modal

### LINKED ISSUE #22145: Connect your Trezor modal flashes for a second after successful BLE pairing
**Describe the bug**
After you successfully pair device with Suite, there is a brief flash of the "Connect your Trezor" modal before the flow continues to the onboarding.

**Steps to reproduce:**
1. Connect uninitialized device
2. After pairing over BLE, you will see the modal for a second

**Info:**
 - Suite version: desktop 25.10.0 (b14be45f53d9b12be6f093bfed53af6041ad7d4e)
 - Browser: Trezor Suite 25.10.0
 - OS: MacIntel
 - Screen: 1800x1169
 - Device:  T3W1 2.9.2.10
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**Screenshots:**
https://satoshilabs.slack.com/archives/C082Q0Y6WP3/p1759479816857799

### PR DESCRIPTION
**Pull request by OriginalEveres**
Fixes blinking modal when the device is connected and pairing.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22145

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/fix-blinking-modal&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/fix-blinking-modal&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/connection/ConnectDeviceGlobalModal.tsx [hunk 1]
```diff
@@ -125,7 +126,7 @@ export const ConnectDeviceGlobalModal = ({ onCancel }: { onCancel: () => void })
     }
 
     // there are nearby devices, show the list and let user connect
-    if (isBluetoothMode && notConnectedNearbyDevices.length > 0) {
+    if (isBluetoothMode && (notConnectedNearbyDevices.length > 0 || selectedDevice)) {
```
Comment (Lemonexe) [inline packages/suite/src/components/connection/ConnectDeviceGlobalModal.tsx:129]: I assume that the `selectedDevice` at this point is the remembered device of the TS7? Then it'd make perfect sense, but what if it isn't?
Can't it happen that you are pairing a TS7 while having remembered wallet, or other connected device?
Then this would erroneously render `BluetoothConnectionModal` instead of the stuff below this.

Comment (OriginalEveres) [reply packages/suite/src/components/connection/ConnectDeviceGlobalModal.tsx:129]: No, `selectedDevice` in this case is the selected bluetooth device that you interact with, eg.: connecting, pairing, etc.

Comment (Lemonexe) [reply packages/suite/src/components/connection/ConnectDeviceGlobalModal.tsx:129]: oh riiiight it's not a `device` from `selectSelectedDevice`, it's something completely different from `useBluetoothConnection` thansk 🤦

**Review by Lemonexe — APPROVED** [review]
LGTM, an simple elegant fix 👍
