### PR TITLE
fix:(blockchain-link): omit solana foreign tx effects

### LINKED ISSUE #10915: "Receiving" SOL when receiving token
**Describe the bug**
It looks like that I got some Solana together with a token but it is not true

**Info:**

-   Suite Version: 24.2.0

**How to reproduce**

1. Send solana tokens

**Expected behavior**
It should not be visible

**Screenshots**

Screenshot 2024-01-30 at 14 32 16
Screenshot 2024-01-30 at 14 32 30
Screenshot 2024-01-30 at 14 32 44

### PR DESCRIPTION
**Pull request by tomasklim**
Omit token transaction effects if sender not receiver is the account Omit SOL positive transaction effects on foreign addresses for transactions other than sent

origin https://github.com/trezor/trezor-suite/pull/12993
closes #10915

### CODE REVIEW

File: packages/blockchain-link-utils/src/solana.ts [hunk 1]
```diff
@@ -251,6 +251,12 @@ export const getTargets = (
                 return false;
             }
 
+            // exclude effects on foreign addresses for tx types other then sent, otherwise it
+            // leads to the foreign address being displayed next to users own address which might lead to confusion
```
Comment (komret) [inline packages/blockchain-link-utils/src/solana.ts]:
```suggestion
            // Exclude effects on foreign addresses for tx types other than sent, otherwise it
            // leads to the foreign address being displayed next to user's own address which might lead to confusion.
```

File: packages/blockchain-link-utils/src/solana.ts [hunk 2]
```diff
@@ -356,7 +362,11 @@ export const getDetails = (
     txType: Transaction['type'],
 ): Transaction['details'] => {
     const senders = effects.filter(({ amount }) => amount.isNegative());
-    const receivers = effects.filter(({ amount }) => amount.isPositive());
+    const receivers = effects
+        .filter(({ amount }) => amount.isPositive())
+        // include positive effects only on accountAddress for tx types other then sent, otherwise it
+        // leads to foreign address being displayed next to users own address which might lead to confusion
+        .filter(({ address }) => txType !== 'sent' ? address === accountAddress : true);
```
Comment (komret) [inline packages/blockchain-link-utils/src/solana.ts]: The condition and comment are repeated, let's abstract it to a function?

File: packages/blockchain-link-utils/src/solana.ts [hunk 3]
```diff
@@ -356,7 +362,11 @@ export const getDetails = (
     txType: Transaction['type'],
 ): Transaction['details'] => {
     const senders = effects.filter(({ amount }) => amount.isNegative());
-    const receivers = effects.filter(({ amount }) => amount.isPositive());
+    const receivers = effects
+        .filter(({ amount }) => amount.isPositive())
```
Comment (komret) [inline packages/blockchain-link-utils/src/solana.ts]: I'd merge the two filters to avoid looping twice.

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/blockchain-link-utils/src/solana.ts (hunk 3 above)
Comment (tomasklim) [reply packages/blockchain-link-utils/src/solana.ts]: a2c1eeaea0fdcd908163b94f12cea63c8549706d

File: packages/blockchain-link-utils/src/solana.ts (hunk 1 above)
Comment (tomasklim) [reply packages/blockchain-link-utils/src/solana.ts]: a2c1eeaea0fdcd908163b94f12cea63c8549706d

**Review by komret — APPROVED** [review]
