### PR TITLE
Invity - skip passphrase entry after redirect from Buy payment gateway

### LINKED ISSUE #2691: Invity - Passphrase entry prompted after redirect from Buy payment gateway
OS: any (tested NixOS)
Browser: Chromium 85.0.4183.102
Suite Version: /release/2020-10-beta/ 2f07979
Firmware Version: any (tested model T, 50854b921)
 
**Describe the bug**
The standard _Select wallet type_ modal is displayed after redirecting from Buy payment gateway which allows the user to enter other wallet's passphrase - which in case of passphrase mismatch results in the Buy transaction detail being displayed but the transaction is not displayed in the Buy transactions list.

**Steps to reproduce:**
1. Enter passphrase #1 when launching Suite,
2. Complete a Trade -> Buy flow,
3. Enter passphrase #2 when redirected back to Suite from the payment gateway.

**Expected result:**
1) Passphrase isn't prompted and user is redirected to the wallet that they've made the transaction with automatically,
2) Passphrase confirmation modal (similar to after an empty passphrase is entered), which should not allow to enter a different passphrase of another wallet, is displayed.

**Actual result:**
_Select wallet type_ modal, which allows to enter a different passphrase than what the transaction was being made with was, is displayed.

**Screenshots:**
N/A

### PR DESCRIPTION
**Pull request by martinboehm**
To skip passphrase entry after return from the payment gate, current device is set to remember mode before switching to the payment gate.
To not to change the setting for ever, after return from the payment gate, the remember mode is reset.

Fixes #2691.

### CODE REVIEW

File: packages/suite/src/reducers/suite/suiteReducer.ts [hunk 1]
```diff
@@ -21,6 +21,7 @@ interface Flags {
     // pinCompleted: boolean;
     // passphraseCompleted: boolean;
     discreetModeCompleted: boolean;
+    forcedRememberDevice: boolean;
```
Comment (szymonlesisz) [inline packages/suite/src/reducers/suite/suiteReducer.ts]: it would be better to have as optional string `forcedRememberDevice?: string` where value would be `device.state`

then you don't have to add this field everywhere (initialState, tests etc)

File: packages/suite/src/actions/wallet/coinmarketCommonActions.ts [hunk 2]
```diff
@@ -91,3 +94,27 @@ export const verifyAddress = (path: string, address: string) => async (
...
+    const { device } = getState().suite;
+    if (device && !device.remember) {
+        dispatch(suiteActions.setFlag('forcedRememberDevice', true));
+        dispatch(suiteActions.rememberDevice(device));
+    }
+    utilsSubmitRequestForm(tradeForm);
+};
+
+export const forgetForcedRememberDevice = () => (dispatch: Dispatch, getState: GetState) => {
+    const { forcedRememberDevice } = getState().suite.flags;
```
Comment (szymonlesisz) [inline packages/suite/src/actions/wallet/coinmarketCommonActions.ts]: if you keep `device.state` in forcedRememberDevice field then here you should be able forget desired device. 
we need to be careful here, there might be potential race condition with two devices connected
`const device = getState().devices.find(d => d.state === forcedRememberDevice)`

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

**Comment by martinboehm** [comment]
Force pushed changes from a discussion, previous comments are obsolete.

File: packages/suite/src/actions/suite/suiteActions.ts [hunk 3]
```diff
@@ -174,10 +179,15 @@ export const selectDevice = (device?: Device | TrezorDevice) => async (
     });
 };
 
-export const rememberDevice = (payload: TrezorDevice): Action => ({
+export const rememberDevice = (
+    payload: TrezorDevice,
+    forceRemember: true | undefined = undefined,
```
Comment (szymonlesisz) [inline packages/suite/src/actions/suite/suiteActions.ts]:
```suggestion
    forceRemember?: true,
```
it will be undefined by default

File: packages/suite/src/actions/wallet/coinmarketCommonActions.ts [hunk 4]
```diff
@@ -91,3 +94,14 @@ export const verifyAddress = (path: string, address: string) => async (
         );
     }
 };
+
+export const submitRequestForm = (tradeForm: BuyTradeFormResponse) => async (
+    dispatch: Dispatch,
+    getState: GetState,
+) => {
+    const { device } = getState().suite;
+    if (device) {
```
Comment (szymonlesisz) [inline packages/suite/src/actions/wallet/coinmarketCommonActions.ts]:
```suggestion
    if (device && !device.remember) {
```
better safe than sorry :)

File: packages/suite/src/middlewares/suite/suiteMiddleware.ts [hunk 5]
```diff
@@ -36,7 +36,19 @@ const suite = (api: MiddlewareAPI<Dispatch, AppState>) => (next: Dispatch) => as
...
             ) {
-                api.dispatch(suiteActions.selectDevice(action.payload.devices[0]));
+                // if there are force remember devices, forget them and pick the first one of them as selected device
+                const forcedDevices = action.payload.devices.filter(
+                    d => d.forceRemember && d.remember,
+                );
+                forcedDevices.forEach(d => {
+                    api.dispatch(suiteActions.rememberDevice(d));
+                });
+                // possible improvement - if there are no forcedDevices, try to pick the connected device instead of the first device
```
Comment (szymonlesisz) [inline packages/suite/src/middlewares/suite/suiteMiddleware.ts:46]: there is already [utility](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/utils/suite/device.ts#L211) for that, i'll address it in another PR

File: packages/suite/src/reducers/suite/deviceReducer.ts [hunk 6]
```diff
@@ -314,12 +314,19 @@ const createInstance = (draft: State, device: TrezorDevice) => {
  * @param {State} draft
  * @param {TrezorDevice} device
  */
-const remember = (draft: State, device: TrezorDevice, remember: boolean) => {
+const remember = (
+    draft: State,
+    device: TrezorDevice,
+    remember: boolean,
+    forceRemember: true | undefined,
```
Comment (szymonlesisz) [inline packages/suite/src/reducers/suite/deviceReducer.ts]:
```suggestion
    forceRemember?: true,
```

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite/src/actions/suite/suiteActions.ts (hunk 3 above)
Comment (martinboehm) [reply packages/suite/src/actions/suite/suiteActions.ts]: It is a function parameter: "Parameter cannot have question mark and initializer.ts(1015)"

File: packages/suite/src/actions/wallet/coinmarketCommonActions.ts (hunk 4 above)
Comment (martinboehm) [reply packages/suite/src/actions/wallet/coinmarketCommonActions.ts]: It is checked inside rememberDevice but I added it there as you suggest it. Also, I added a check which will force remember device only in the web version, in the destop version we do not leave the Suite.

File: packages/suite/src/middlewares/suite/suiteMiddleware.ts (hunk 5 above)
Comment (martinboehm) [reply packages/suite/src/middlewares/suite/suiteMiddleware.ts:46]: OK, I will leave the comment there.

File: packages/suite/src/reducers/suite/deviceReducer.ts (hunk 6 above)
Comment (martinboehm) [reply packages/suite/src/reducers/suite/deviceReducer.ts]: It is a function parameter: "Parameter cannot have question mark and initializer.ts(1015)"

File: packages/suite/src/actions/suite/suiteActions.ts (hunk 3 above)
Comment (szymonlesisz) [reply packages/suite/src/actions/suite/suiteActions.ts]: do not use initializer ( = undefined) just `forceRemember?: true`
it will be "true | undefined" and undefined by defualt

File: packages/suite/src/reducers/suite/deviceReducer.ts (hunk 6 above)
Comment (szymonlesisz) [reply packages/suite/src/reducers/suite/deviceReducer.ts]: same as above

File: packages/suite/src/utils/suite/storage.ts [hunk 7]
```diff
@@ -12,10 +12,14 @@ export const serializeDiscovery = (discovery: Discovery) => ({ ...discovery, run
...
-});
+export const serializeDevice = (device: AcquiredDevice, forceRemember: true | undefined) => {
+    const sd = {
+        ...device,
+        path: '',
+        remember: true,
+        connected: false,
+        buttonRequests: [],
+    };
+    if (forceRemember) sd.forceRemember = true;
```
Comment (szymonlesisz) [inline packages/suite/src/utils/suite/storage.ts:23]: i dont think this is the right way, `device.forceRemember` should be either true or shouldn't be present in device object at all

**Comment by martinboehm** [comment]
The parameters are fixed. It was giving me errors "Parameter cannot have question mark and initializer.ts(1015)", after yarn it disappeared, strange...

File: packages/suite/src/utils/suite/storage.ts (hunk 7 above)
Comment (martinboehm) [reply packages/suite/src/utils/suite/storage.ts:23]: It is not present in the passed device because the parameter passed in the SUITE.REMEMBER action is action.payload, not device after change state.
```
        case SUITE.REMEMBER_DEVICE:
            api.dispatch(
                storageActions.rememberDevice(
                    action.payload,
                    action.remember,
                    action.forceRemember,
                ),
            );
            break;
```
We could change the code in the middleware to `api.getState().devices.find(...))` but I did not want to do it for for me unknown side effects.

**Comment by tsusanka** [comment]
Is the review done? Let's merge this ASAP please @szymonlesisz.

**Review by szymonlesisz — APPROVED** [review]

**Comment by szymonlesisz** [comment]
now its ok, approved

**Comment by martinboehm** [comment]
Fixups are squashed...
