### PR TITLE
fix: ButtonRequest_FirmwareCheck

### LINKED ISSUE #3036: Fw update - fingerprint
It used to work but is broken now

- Modal redurer reacts to the corresponding button request 
- modal component does not havy any corresponding view for this button request
- Fingerprint component is rendered but overlayed by empty modal.

### PR DESCRIPTION
**Pull request by mroz22**
Ok, this should fix #3036

I tested onboarding flow including incremental firmware update and it worked all properly.
image

Did not test standalone firmware update modal but it should work as well. Unfortunately this is very hard to test as you need to burn a new device for that. I used my metalic anniversary edition which I indeded to sell on ebay few years later  and retire on Bahamas :cry:

### CODE REVIEW

File: packages/suite/src/views/firmware/index.tsx [hunk 1]
```diff
@@ -194,12 +211,13 @@ const Firmware = ({ closeModalApp, resetReducer, firmware, device }: Props) => {
...
             heading={Component.Heading}
-            bottomBar={<Buttons>{Component.BottomBar}</Buttons>}
+            bottomBar={!modal && <Buttons>{Component.BottomBar}</Buttons>}
             totalProgressBarSteps={stepsInProgressBar.length}
             currentProgressBarStep={getCurrentStepIndex()}
             hiddenProgressBar={false}
         >
-            {Component.Body}
+            {modal && <InnerModalWrapper>{modal}</InnerModalWrapper>}
+            {!modal && Component.Body}
```
Comment (keraf) [inline packages/suite/src/views/firmware/index.tsx]: Would be cleaner with an if-else statement.

File: packages/suite/src/views/firmware/index.tsx [hunk 2]
```diff
@@ -182,7 +199,7 @@ const Firmware = ({ closeModalApp, resetReducer, firmware, device }: Props) => {
                 'error',
             ].includes(firmware.status)}
             header={
-                ['waiting-for-confirmation', 'check-fingerprint'].includes(firmware.status) && (
+                ['waiting-for-confirmation'].includes(firmware.status) && (
```
Comment (keraf) [inline packages/suite/src/views/firmware/index.tsx]: Could be changed to `firmware.status === 'waiting-for-confirmation'`.

File: packages/suite/src/components/suite/modals/confirm/Fingerprint/index.tsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+import { TrezorDevice } from '@suite-types';
+import { Fingerprint } from '@firmware-components';
+import { getFormattedFingerprint } from '@firmware-utils';
+
+interface Props extends ModalProps {
+    device: TrezorDevice;
+}
+
+const ConfirmFingerprint = ({ device, ...rest }: Props) => {
+    return (
```
Comment (keraf) [inline packages/suite/src/components/suite/modals/confirm/Fingerprint/index.tsx]: Explicit return statement isn't necessary here.

**Review by keraf — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/confirm/Fingerprint/index.tsx (hunk 3 above)
Comment (mroz22) [reply packages/suite/src/components/suite/modals/confirm/Fingerprint/index.tsx]: True. If you would like to enforce these, please add eslint rule for this. https://eslint.org/docs/rules/arrow-body-style
I believe that it would save us time during future reviews.

File: packages/suite/src/views/firmware/index.tsx (hunk 1 above)
Comment (mroz22) [reply packages/suite/src/views/firmware/index.tsx]: I changed that but I dont like the proposed solution. two lines if negated if statement feels more readable to me. probably depends on individual taste

**Review by keraf — APPROVED** [review]
