### PR TITLE
Fix/case sensitive token symbol

### LINKED ISSUE #8552: Do not use .toLower/Upper case for token symbol anywhere
We used this quite a lot in code, but we shouldn't according to @tomasklima. I guess it because symbol names could be case sensitive?

### PR DESCRIPTION
**Pull request by PeKne**
## Description
The PR is divided into three commits:
- df07f085fbfc2087b47b987c15cace3f06590dca - tokenIcons are defined based on contract address, not the token symbol
- 0eee49f7f9d9c3b606507003fb81786116dd669e - `fiatRateKey` was redesigned not to contain a token symbol since the symbol is not unique at all. Now has only `networkSymbol + contractAddress`
- da35db339a33d5f77f58aeb42ac121cadcca3d89 - the token case is not changed anywhere but in one place where it is still necessary

## Related Issue

Resolve #8552

### CODE REVIEW

File: suite-native/accounts/src/components/AccountListItem.tsx [hunk 1]
```diff
@@ -49,9 +45,7 @@ export const valuesContainerStyle = prepareNativeStyle(utils => ({
 
 export const AccountListItem = ({ account, areTokensDisplayed = false }: AccountListItemProps) => {
     const { applyStyle } = useNativeStyles();
-    const accountLabel = useSelector((state: AccountsRootState) =>
-        selectAccountLabel(state, account.key),
-    );
+    const { accountLabel } = account.metadata;
```
Comment (juriczech) [inline suite-native/accounts/src/components/AccountListItem.tsx:48]: nit: If the selector is unnecessary, you could create a task for removing it and applying just this destructuring, otherwise it's creating inconsistency.

If we were to change the selector, I would expect that new logic gets applied everywhere but it will break here

File: suite-native/assets/src/assetsSelectors.ts [hunk 2]
```diff
@@ -45,25 +49,22 @@ export const selectBalancesPerNetwork = memoize((state: AssetsRootState): Format
...
+            const fiatRateKey = getFiatRateKey(networkSymbol, fiatCurrencyCode);
+            const fiatRate = selectFiatRatesByFiatRateKey(state, fiatRateKey);
 
-            const currentFiatRates = coins.find(
-                f => f.symbol?.toLowerCase() === networkSymbol.toLowerCase(),
-            )?.current;
 
-            // Note: This shouldn't be happening in a selector but rather in component itself.
-            // In future, we will probably have something like `CryptoAmountToFiatFormatter` in component just using value sent from this selector.
+            // We need to calculate fiat Currency value already in the selector be able to compare one account value to another later in the code.
```
Comment (juriczech) [inline suite-native/assets/src/assetsSelectors.ts]: nit: can you refrase? Sentence doesn't make sense :D

File: suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts [hunk 3]
```diff
@@ -39,6 +39,21 @@ export const selectEthereumAccountToken = (
...
+    accountKey: AccountKey,
+    tokenAddress?: TokenAddress,
+): TokenSymbol | null => {
+    const tokenInfo = selectEthereumAccountTokenInfo(state, accountKey, tokenAddress);
+
+    if (!tokenInfo) return null;
+
+    // FIXME: This is the only place in the codebase where we change case of token symbol.
+    // The `toUpperCase()` operation is necessary because we are receiving wrongly formatted token symbol from connect.
+    // Can be removed at the moment whe desktop issue https://github.com/trezor/trezor-suite/issues/8037 is resolved.
```
Comment (juriczech) [inline suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts]:
```suggestion
    // Can be removed at the moment when desktop issue https://github.com/trezor/trezor-suite/issues/8037 is resolved.
```

File: suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx [hunk 4]
```diff
@@ -35,17 +33,17 @@ export const EthereumTokenToFiatAmountFormatter = ({
     numberOfLines,
     ...rest
 }: EthereumTokenToFiatAmountFormatterProps) => {
-    const fiatCurrency = useSelector(selectFiatCurrency);
+    const fiatCurrencyCode = useSelector(selectFiatCurrencyCode);
     const { FiatAmountFormatter } = useFormatters();
-    const fiatRateKey = getFiatRateKey(ethereumToken, fiatCurrency.label, contract);
+    const fiatRateKey = getFiatRateKey('eth', fiatCurrencyCode, contract);
     const rate = useSelector((state: any) => selectFiatRatesByFiatRateKey(state, fiatRateKey));
```
Comment (juriczech) [inline suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx:39]:
```suggestion
    const rate = useSelector((state: FiatRatesRootState) => selectFiatRatesByFiatRateKey(state, fiatRateKey));
```

If you're going to make any changes to this PR, could you please change this? Tested locally that type check will pass with this and it's better than leaving `any`

File: suite-native/module-dev-utils/src/screens/DemoScreen.tsx [hunk 5]
```diff
@@ -372,16 +372,16 @@ export const DemoScreen = () => {
...
+                                    key={iconContract}
                                     marginRight="large"
                                     marginBottom="large"
                                     justifyContent="center"
                                     alignItems="center"
                                 >
-                                    <CryptoIcon symbol={icon as TokenSymbol} />
-                                    <Text>{icon}</Text>
+                                    <CryptoIcon symbol={iconContract as TokenAddress} />
+                                    <Text>{iconContract}</Text>
```
Comment (juriczech) [inline suite-native/module-dev-utils/src/screens/DemoScreen.tsx]: Doesn't make sense anymore as contract is super unreadable and we should ideally want something like symbol + contract string, but I'm happy to leave it like this. Also expect the UI to be pretty shit with those long contract strings

File: suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx [hunk 6]
```diff
@@ -35,27 +39,29 @@ const TodayHeaderCell = ({
...
     historicalRates,
 }: TodayHeaderCellProps) => {
-    const coins = useSelector(selectCoinsLegacy);
-    const fiatCurrency = useSelector(selectFiatCurrency);
-    const currentRates = coins.find(coin => coin.symbol === network)?.current?.rates;
+    const fiatCurrencyCode = useSelector(selectFiatCurrencyCode);
+    const fiatRateKey = getFiatRateKey(network, fiatCurrencyCode);
+    const currentRates = useSelector((state: FiatRatesRootState) =>
+        selectFiatRatesByFiatRateKey(state, fiatRateKey),
+    );
```
Comment (juriczech) [inline suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx:46]: This could be a new selector which gets the fiat rate key itself. It's in couple of places in this PR

File: suite-native/module-accounts/src/components/AccountDetailTokenHeader.tsx [hunk 7]
```diff
@@ -21,25 +24,25 @@ export const AccountDetailTokenHeader = ({
...
     return (
         <VStack alignItems="center" spacing="small" marginVertical="medium">
             <HStack spacing="small" flexDirection="row" alignItems="center" justifyContent="center">
-                <CryptoIcon symbol={tokenAccount.symbol} size="extraSmall" />
-                <EthereumTokenAmountFormatter
-                    value={tokenAccount?.balance}
-                    ethereumToken={tokenAccount.symbol}
-                />
+                <CryptoIcon symbol={tokenAccount.contract} size="extraSmall" />
+                <EthereumTokenAmountFormatter value={tokenAccount?.balance} symbol={tokenSymbol} />
```
Comment (Nodonisko) [inline suite-native/module-accounts/src/components/AccountDetailTokenHeader.tsx:40]: Why not pass contract to formatter and use selector inside of Formatter?

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/assets/src/assetsSelectors.ts (hunk 2 above)
Comment (PeKne) [reply suite-native/assets/src/assetsSelectors.ts]: fixed in https://github.com/trezor/trezor-suite/pull/8670/commits/e15c6ed81f350883b251beb3f5ecaf8c993b355d

File: suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts (hunk 3 above)
Comment (PeKne) [reply suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts]: fixed in https://github.com/trezor/trezor-suite/pull/8670/commits/e15c6ed81f350883b251beb3f5ecaf8c993b355d

File: suite-native/module-dev-utils/src/screens/DemoScreen.tsx (hunk 5 above)
Comment (PeKne) [reply suite-native/module-dev-utils/src/screens/DemoScreen.tsx]: fixed in https://github.com/trezor/trezor-suite/pull/8670/commits/3607920b6bad1b440dc450b4e1353d433122d8ba

File: suite-native/accounts/src/components/AccountListItem.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/accounts/src/components/AccountListItem.tsx:48]: The selector is unnecessary in this file but is needed in another filed where the account object is not present. But you are right that the selector itself is unnecessarily complicated. I refactored the selector in https://github.com/trezor/trezor-suite/pull/8670/commits/3607920b6bad1b440dc450b4e1353d433122d8ba

File: suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx (hunk 6 above)
Comment (PeKne) [reply suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx:46]: good idea, selector added in https://github.com/trezor/trezor-suite/pull/8670/commits/1ae1f4f3b19ce2359717de448fea907dc4548be3

File: suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx (hunk 4 above)
Comment (PeKne) [reply suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx:39]: fixed in https://github.com/trezor/trezor-suite/pull/8670/commits/1ae1f4f3b19ce2359717de448fea907dc4548be3

File: suite-native/module-accounts/src/components/AccountDetailTokenHeader.tsx (hunk 7 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/AccountDetailTokenHeader.tsx:40]: What are the benefits?

I would prefer to keep it this way. If we would be selecting only the token symbol inside of the formatter, I would agree with you but we need also `tokenAccount.balance` or `tokenTransfer.value`. To distinguish if the formatter should select an account or a tokenTransfer would make the inner logic unnecessarily complicated. 

Another thing is how to get `tokenTranfer.value`. To get this we would have to create a new selector which returns single and specific tokenTransfer from the account. But there is a catch... The token transfer has no unique ID:

```tsx
export interface TokenTransfer {
    type: string;
    from: string;
    to: string;
    contract: string;
    name: string;
    symbol: string;
    decimals: number;
    value?: string;
    multiTokenValues?: MultiTokenValue[];
}
```
The search for a specific tokenTransfer would be super complicated and unnecessary IMO.

File: suite-native/module-accounts/src/components/AccountRenameForm.tsx [hunk 8]
```diff
@@ -46,7 +46,7 @@ export const AccountRenameForm = ({ accountKey, onSubmit }: AccountRenameFormPro
         selectAccountLabel(state, accountKey),
     );
 
-    const form = useAccountLabelForm(accountLabel);
+    const form = useAccountLabelForm(accountLabel ?? undefined);
```
Comment (juriczech) [inline suite-native/module-accounts/src/components/AccountRenameForm.tsx:49]:
```suggestion
    const form = useAccountLabelForm(accountLabel ?? null);
```

Why fallback? Selector returns label or null. Should be enough? You changed type signature, so if it's null, we should retype form to work with null as well.

File: suite-native/accounts/src/components/AccountListItem.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/accounts/src/components/AccountListItem.tsx:48]: Yeah, I understand, but point of selectors is not only to have memoization etc, but also unify selecting state pieces. I would still like to use the selector here so we can only change selector without having to make changes to this file as well when data structure changes.

File: suite-native/module-accounts/src/components/AccountRenameForm.tsx (hunk 8 above)
Comment (PeKne) [reply suite-native/module-accounts/src/components/AccountRenameForm.tsx:49]: Because I would have to change  the form `useAccountLabelForm.accountLabel` yup schema definition from `required` to `nullable`:
### Original code
```tsx
const accountFormValidationSchema = yup.object({
    accountLabel: yup.string().required().max(MAX_ACCOUNT_LABEL_LENGTH),
});
```

### Potential code
```tsx
const accountFormValidationSchema = yup.object({
    accountLabel: yup.string().max(MAX_ACCOUNT_LABEL_LENGTH).nullable(),
});
```

Then the user would be able to send a form with no `accountLabel` which we certainly don't want to happen. 

Another solution would be that I would return `undefined` instead of `null` directly from the `selectAccountLabel` selector. I would be happy like that, but we already had this discussion and I guess you don't like it.

File: suite-native/module-accounts/src/components/AccountDetailTokenHeader.tsx (hunk 7 above)
Comment (Nodonisko) [reply suite-native/module-accounts/src/components/AccountDetailTokenHeader.tsx:40]: I don't like that much that you need to do this everywhere:
```
const tokenSymbol = useSelector((state: AccountsRootState) =>
        selectEthereumAccountTokenSymbol(state, accountKey, tokenContract),
    );
```
Downside is that then you will have to pass extra props accountKey and tokenContract. Even with that I would say I still prefer it little bit because these two props you have already available everywhere where Formatter is used and it's easier to just pass them then doing that extra select everytime you want to use Formatter.

You can always pass `tokenTranfer.value` or `tokenTranfer.balance` as prop to Formatter, I don't see any problem with that.

I don't have strong preference about this but, from DX perspective is much easier to just pass props you already have that importing whole new selector everywhere where you need to use only because you need only `symbol`. 

Another problem with my approach could be that then you will always have to use Formatter with accountKey, which decrease reusability...

Hope this summarization makes sense :D I will leave it up to you, if you want to keep your implementation I am OK with that.

**Review by Nodonisko — APPROVED** [review]

File: suite-native/fiat-rates/src/fiatRatesSelectors.ts [hunk 9]
```diff
@@ -10,6 +10,7 @@ import {
     selectTransactions,
 } from '@suite-common/wallet-core';
 import { Account, AccountKey, WalletAccountTransaction } from '@suite-common/wallet-types';
+import { selectFiatCurrencyCode, SettingsSliceRootState } from '@suite-native/module-settings';
```
Comment (Nodonisko) [inline suite-native/fiat-rates/src/fiatRatesSelectors.ts]: Do not import from other modules, this lib should be moved to common soon hopefully.

File: suite-native/assets/src/assetsSelectors.ts [hunk 10]
```diff
@@ -45,25 +45,20 @@ export const selectBalancesPerNetwork = memoize((state: AssetsRootState): Format
...
     const networksWithAssets = Object.keys(balancesPerNetwork) as NetworkSymbol[];
-    const coins = selectCoinsLegacy(state);
 
-    const fiatCurrency = selectFiatCurrencyCode(state);
+    const fiatCurrencyCode = selectFiatCurrencyCode(state);
 
     return networksWithAssets
         .map((networkSymbol: NetworkSymbol) => {
             const network = networks[networkSymbol];
+            const fiatRate = selectFiatRatesByTicker(state, { symbol: networkSymbol });
```
Comment (Nodonisko) [inline suite-native/assets/src/assetsSelectors.ts]: You don't need new selector, you can use this one:
```tsx
const currentFiatRates = selectFiatRatesByFiatRateKey(
                state,
                getFiatRateKey(networkSymbol, fiatCurrency),
            );
```

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/module-accounts/src/components/AccountRenameForm.tsx (hunk 8 above)
Comment (juriczech) [reply suite-native/module-accounts/src/components/AccountRenameForm.tsx:49]: Wouldn't it be possible to fix this by defaulting the value to empty string / string created from selector (e.g. Bitcoin #1) and remove the `.nullable()`?

Comment (PeKne) [reply suite-native/module-accounts/src/components/AccountRenameForm.tsx:49]: The empty string would be possible. On the other hand the placeholder solution e.g. `Bitcoin #1` would not make sense. The selector would return data that are not right. Also, you would have to calculate which `#<number>` to append which makes the whole selector overcomplicated.

File: suite-native/assets/src/assetsSelectors.ts (hunk 10 above)
Comment (PeKne) [reply suite-native/assets/src/assetsSelectors.ts]: Alright. I've created this selector on @juriczech request. I will revert this fixup then and keep the original solution with the selector you suggest.

File: suite-native/accounts/src/components/AccountListItem.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/accounts/src/components/AccountListItem.tsx:48]: I agree but make sense to me only if you modify the content of the selected attribute (e.g if we would making the `accountLabel` upperCase).

We are accessing objects attributes received from selector all over the codebase. eg we are selecting an account and then directly  accessing `account.symbol` without use of a new selector for an accountSymbol:
```ts
const account = useSelector((state: AccountsRootState) =>
        selectAccountByKey(state, accountKey),
    );
    
   ....
  ... account.symbol ...
```

Why in this case it is ok, but in case of `accountLabel` it is not?

File: suite-native/fiat-rates/src/fiatRatesSelectors.ts (hunk 9 above)
Comment (PeKne) [reply suite-native/fiat-rates/src/fiatRatesSelectors.ts]: fixed in fixup fixup https://github.com/trezor/trezor-suite/pull/8670/commits/c2e42d090e921371cfd42ad5645b7d7eabb49430. This whole change of selectors files was reverted.

File: suite-native/assets/src/assetsSelectors.ts (hunk 10 above)
Comment (PeKne) [reply suite-native/assets/src/assetsSelectors.ts]: fixed in fixup fixup https://github.com/trezor/trezor-suite/commit/c2e42d090e921371cfd42ad5645b7d7eabb49430. Same as above.

File: suite-native/module-accounts/src/components/AccountRenameForm.tsx (hunk 8 above)
Comment (juriczech) [reply suite-native/module-accounts/src/components/AccountRenameForm.tsx:49]: We already do that. If the value of account label is undefined, we use `<Coin> #<Length of coins>`. So in that case we're not giving the form undefined but predefined string so the validation doesn't need nullable, just non empty string.

Comment (juriczech) [reply suite-native/module-accounts/src/components/AccountRenameForm.tsx:49]: But now that I look at the form I don't see it there so it must be connect handling this logic now.

File: suite-native/accounts/src/components/AccountListItem.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/accounts/src/components/AccountListItem.tsx:48]: Well you can argue that it should be for accountSymbol as well but I'm not advocating for that. I just see change from selector to accessing directly and I see no reason to do that. It's pointless to discuss as it doesn't have any performance drawbacks, just wanted to maintain single source of truth. Won't make an impact and don't won't to lose time arguing about it so I'm approving this PR and leave it up to you. @PeKne

**Review by juriczech — APPROVED** [review]

**Review by Nodonisko — APPROVED** [review]
