### PR TITLE
fix(suite): Tx review details

### LINKED ISSUE #23027: Tx review details missing
**Describe the bug**
In Tx review modal in Send form, there is the ℹ️ Details section, available for BTC-like & ADA.
But currently it displays the same thing as the main modal contant, minus [this header](https://github.com/user-attachments/assets/bffcaba9-bd15-407b-b894-b9449761e1dd), so it is completely useless.

**How to reproduce**

1. Go to Send form for any BTC-like or Cardano coin
1. FIll out send form
1. Click Review & Send
1. Click ℹ️ 

**Expected behavior**
Should display the Tx details (inputs, outputs, raw Tx if signed)

**Screenshots**

https://github.com/user-attachments/assets/b12fb51c-154b-4db8-9b33-a2878d31dac4

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Bring back forgotten `TransactionReviewDetails` component, which is currently never rendered.
Small code tweaks along the way.

## Related Issue

Resolve #23027

### Before

https://github.com/user-attachments/assets/b12fb51c-154b-4db8-9b33-a2878d31dac4

### After

at first not signed, then signed

[AFTER.webm](https://github.com/user-attachments/assets/e0ab6e2c-7044-4130-8dda-6285fd9199ce)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/tx-review-details&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/tx-review-details&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewModalBottomContent.tsx [hunk 1]
```diff
@@ -152,10 +150,6 @@ export const TransactionReviewModalBottomContent = ({
         );
     }
 
-    if (areDetailsVisible) {
-        return null;
-    }
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewModalBottomContent.tsx:157]: rather just skip rendering the component, makes it simpler to read,
see TransactionReviewModalBodyInner.tsx L274

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalBodyInner.tsx [hunk 2]
```diff
@@ -300,6 +301,7 @@ export const TransactionReviewModalBodyInner = ({
                     reviewStep={reviewStep}
                     isRbfConfirmedError={isRbfConfirmedError}
                     onTryAgain={handleTryAgain}
+                    areDetailsVisible={areDetailsVisible}
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalBodyInner.tsx:304]: this was forgotten
so [this condition](https://github.com/trezor/trezor-suite/blob/1108aeb19de43a263641b2d03d9b6f0c99ce0860/packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewModalContent.tsx#L93) never rendered

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewModalContent.tsx [hunk 3]
```diff
@@ -33,7 +33,7 @@ type TransactionReviewModalContentProps = {
     onTryAgain: (cancel: boolean) => void;
     reviewStep: number;
     serializedTx?: SerializedTx;
-    areDetailsVisible?: boolean;
+    areDetailsVisible: boolean;
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewModalContent.tsx:36]: :clap:

**Review by peter-sanderson — APPROVED** [review]

**Comment by Lemonexe** [comment]
Merging, suite desktop E2E `unstake.test.ts` [confirmed broken](https://satoshilabs.slack.com/archives/CKYFBT2C9/p1762797768751979?thread_ts=1762763521.214019&cid=CKYFBT2C9)
