### PR TITLE
fix(suite): fix coinjoin pausing with several ongoing sessions

### LINKED ISSUE #6812: Incorrect wallet is paused when you run multiple instances of CoinJoin in one Trezor Suite.
**Describe the bug**
Incorrect wallet is paused when you run multiple instances of CoinJoin in one Trezor Suite.
See video, I was able to replicate this issue multiple times.

**Steps to reproduce:**
1. Start CJ in Standard wallet
2. Start CJ in hidden wallet
3. Pause one of wallet and observe status of both wallets

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
https://youtu.be/_9h7x10uCgk

### PR DESCRIPTION
**Pull request by dahaca**
## Description

* correctly handle CJ session pausing when several are ongoing

## Related Issue

Resolve #6812

## Screenshots:

https://user-images.githubusercontent.com/45338719/202210933-609e1d9d-1481-46f4-a3ec-593cd126ff2f.mov

### CODE REVIEW

File: packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatus.tsx [hunk 1]
```diff
@@ -12,12 +12,20 @@ import {
...
 import { Translation } from '@suite-components/Translation';
 import { CountdownTimer } from '@suite-components';
+import { selectAccountByKey } from '@suite-common/wallet-core';
 import { COINJOIN_PHASE_MESSAGES } from '@suite-constants/coinjoin';
 import {
     calculateSessionProgress,
     getPhaseTimerFormat,
     getSessionDeadlineFormat,
 } from '@wallet-utils/coinjoinUtils';
+import { useDispatch } from 'react-redux';
```
Comment (matejkriz) [inline packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatus.tsx:21]: I know it's not a first usage, but would be nice to discuss what is the current preferred way https://www.notion.so/satoshilabs/Redux-b0a4c3b7e71b499a8d592fb44cd794fe#31445739321c401dbf1d2396ee4ad3bc

File: packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatus.tsx [hunk 2]
```diff
@@ -151,12 +154,12 @@ export const CoinjoinStatus = ({
     const togglePause = useCallback(async () => {
         if (isPaused) {
             setIsLoading(true);
-            await restoreSession();
+            await dispatch(restoreCoinjoinSession(account!));
```
Comment (matejkriz) [inline packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatus.tsx]: how do you know, that `account` is always defined here? What about some `if(!account) return null` check at the top?

Comment (matejkriz) [reply packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatus.tsx]: now I see that it is changed in next commit

File: packages/suite/src/components/suite/modals/CancelCoinjoin.tsx [hunk 3]
```diff
@@ -29,11 +29,13 @@ interface CancelCoinjoinProps {
...
-    const { account } = useSelector(state => state.wallet.selectedAccount) as SelectedAccountLoaded;
+    const account = useSelector(selectSelectedAccount);
 
-    const { stopCoinjoinSession } = useActions({
-        stopCoinjoinSession: coinjoinAccountActions.stopCoinjoinSession,
-    });
+    const dispatch = useDispatch();
+
+    if (!account) {
+        return;
```
Comment (matejkriz) [inline packages/suite/src/components/suite/modals/CancelCoinjoin.tsx]: return null instead of undefined to be usable as a JSX component in UserContextModal.tsx
see https://github.com/trezor/trezor-suite/actions/runs/3480766521/jobs/5820987582#step:13:203
```suggestion
        return null;
```

File: packages/suite/src/components/suite/modals/CancelCoinjoin.tsx [hunk 4]
```diff
@@ -48,7 +50,7 @@ export const CancelCoinjoin = ({ onClose }: CancelCoinjoinProps) => {
                     <StyledButton
                         variant="danger"
                         onClick={() => {
-                            stopCoinjoinSession(account);
+                            dispatch(stopCoinjoinSession(account?.key));
```
Comment (matejkriz) [inline packages/suite/src/components/suite/modals/CancelCoinjoin.tsx]: nit: `?` is redundant here
```suggestion
                            dispatch(stopCoinjoinSession(account.key));
```

File: packages/suite/src/actions/wallet/coinjoinAccountActions.ts [hunk 5]
```diff
@@ -398,16 +402,23 @@ export const startCoinjoinSession =
...
-    client?.unregisterAccount(account.key);
+        if (!account) {
+            return;
+        }
 
-    // dispatch data to reducer
-    dispatch(coinjoinSessionPause(account.key));
-};
+        // get @trezor/coinjoin client if available
+        const client = getCoinjoinClient(account?.symbol);
```
Comment (matejkriz) [inline packages/suite/src/actions/wallet/coinjoinAccountActions.ts]: nit: same here, redundant `?`
```suggestion
        const client = getCoinjoinClient(account.symbol);
```

File: .github/pull_request_template.md [hunk 6]
```diff
@@ -8,4 +8,4 @@
 
 Resolve <!--- link the issue here -->
 
-## Screenshots (if appropriate):
+## Screenshots:
```
Comment (karliatto) [inline .github/pull_request_template.md:11]: This looks like totally unrelated to this PR.

File: packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatus.tsx (hunk 1 above)
Comment (dahaca) [reply packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatus.tsx:21]: Far from the first one, I've been using it for several months, I think 😅  Also, the mobile team has been using it for a while. But we can definitely discuss it and compare pros and cons.

File: .github/pull_request_template.md (hunk 6 above)
Comment (dahaca) [reply .github/pull_request_template.md:11]: It is, I think this change is not really worth CI time...

File: packages/suite/src/components/suite/modals/CancelCoinjoin.tsx (hunk 3 above)
Comment (dahaca) [reply packages/suite/src/components/suite/modals/CancelCoinjoin.tsx]: Interesting TS still throws, when React 18 is supposed to [not throw](https://github.com/facebook/react/pull/21869) :D

File: packages/suite/src/components/suite/modals/CancelCoinjoin.tsx (hunk 4 above)
Comment (dahaca) [reply packages/suite/src/components/suite/modals/CancelCoinjoin.tsx]: 76c7b1d6d177798b40a8c34a8fb43461eb3aec34

File: packages/suite/src/actions/wallet/coinjoinAccountActions.ts (hunk 5 above)
Comment (dahaca) [reply packages/suite/src/actions/wallet/coinjoinAccountActions.ts]: 76c7b1d6d177798b40a8c34a8fb43461eb3aec34

File: packages/suite/src/components/suite/modals/CancelCoinjoin.tsx (hunk 3 above)
Comment (dahaca) [reply packages/suite/src/components/suite/modals/CancelCoinjoin.tsx]: 76c7b1d6d177798b40a8c34a8fb43461eb3aec34

Comment (matejkriz) [reply packages/suite/src/components/suite/modals/CancelCoinjoin.tsx]: this is not because of React types but our modal types...

File: .github/pull_request_template.md (hunk 6 above)
Comment (matejkriz) [reply .github/pull_request_template.md:11]: Totally agree, that unrelated things should be in separate PRs. No need to change it for this PR, but for the future it's better not to save the CI time that much.

**Review by matejkriz — APPROVED** [review]
LGTM, please rebase on develop and resolve conflicts

**Comment by matejkriz** [comment]
@dahaca please check the failing unit test
