### PR TITLE
fix: do not show incompatible warning when legacy labeling is on

### LINKED ISSUE #26427: TT and T1 show incompatible Suite Sync message even with Legacy labeling
**Describe the bug**

https://github.com/user-attachments/assets/8939bd87-a1b2-4601-8df3-a39f7eb8e1c8

**Info:**
 - Suite version: desktop 26.4.0 (091ce6065cf54493582a9e001a94abdd68a44cf3)
 - Browser: Trezor Suite 26.4.0
 - OS: MacIntel
 - Screen: 3008x1692
 - Device: Trezor T2T1 2.11.0 universal (revision 725c0c01879329900f08fc453d8fd0fcb4d86090)
 - Transport: BridgeTransport 3.2.1, BluetoothTransport

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/26427

Very straightforward fix, just ignore any suite-sync tooltip if legacy is enabled

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-t1-tt-suite-sync-tooltip&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-t1-tt-suite-sync-tooltip&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Account metadata,google - watches files over time" | 🙋 manual |
| Quarantine test: "Account metadata,dropbox - watches files over time" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-07T11:26:21.639Z • 7 test(s) total_

<details><summary>Trezor Suite (desktop) — 3 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-07T11:23:59.185Z • 3 test(s) total_

### CODE REVIEW

File: packages/suite/src/actions/suiteSync/suiteSyncSlice.ts [hunk 1]
```diff
@@ -88,6 +88,8 @@ export const selectDesktopSuiteSyncInteraction = (
     deviceStaticSessionId: StaticSessionId | null,
 ): SuiteSyncInteraction | null => {
     const isSuiteSyncFeatureEnabled = selectIsSuiteSyncFeatureAvailable(state);
+    console.log('isSuiteSyncFeatureEnabled', isSuiteSyncFeatureEnabled);
+
```
Comment (juriczech) [inline packages/suite/src/actions/suiteSync/suiteSyncSlice.ts]: Forgotten console.log

**Review by juriczech — APPROVED** [review]
LGTM

File: packages/suite/src/actions/suiteSync/suiteSyncSlice.ts (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/suiteSync/suiteSyncSlice.ts]: fixed
