### PR TITLE
Fix/fw update remembered device macos

### LINKED ISSUE #4307: After the fw update, the application shows two devices
**Describe the bug**
Trezor Suite shows two devices

Few customers has recently reported this sort of an issue in Trezor forum thread:
https://forum.trezor.io/t/info-trezor-stuck-in-bootloader-mode-1-10-0-during-firmware-update/2402/14

After updating from from previous to the latest FW version on MacOS the desktop application shows two devices connected.
After entering passphrase (in order to get into hidden wallet) "Passphrase duplicated" error appears.
(apparently web version of Suite works fine).

Users asked to provide more info (Suite log) if possible. 

**Steps to reproduce:**
1. load standard and passphrase wallet and remember them
2. proceed with firmware update
3.  observe wallet/device selector after update

**Info:**
 - Suite version: 21.9.2 
 - OS: MacOS
 - Device: model Trezor One
 - Bootloader: 1.10.0

**Video:**

https://www.youtube.com/watch?v=g7I4zFb_qUA

**Screenshots:**

obrazek

obrazek2

obrazek3

### PR DESCRIPTION
**Pull request by tomasklim**
Close #4307

This is only macOS problem when updating Trezor 1 while having remembered accounts.

> fix(suite): no update of remembered device in indexDB if bootloader mode

- if user refreshes app to cancel firmware update (before fw update starts) he ended with remembered devices in bootloader mode

> chore(suite): acquire device after fw update if not available

- remembered devices are sometimes changed to be `occupied` or `used` after fw update, acquire them when closing fw update modal

> fix(suite): update remembered devices in bootloader mode

- remembered devices are turned into `bootloader` mode so they lose `id`. When fw update is `done`, they are also disconnected so they lose `path`. We can get their `id` from `state` and refresh them.

### CODE REVIEW

File: packages/suite/src/middlewares/wallet/storageMiddleware.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ const storageMiddleware =
             }
 
             case SUITE.UPDATE_SELECTED_DEVICE:
-                if (isDeviceRemembered(action.payload)) {
+                if (isDeviceRemembered(action.payload) && action.payload.mode !== 'bootloader') {
```
Comment (szymonlesisz) [inline packages/suite/src/middlewares/wallet/storageMiddleware.ts]:
```suggestion
                if (isDeviceRemembered(action.payload) && action.payload.mode === 'normal') {
```
just to be safe, there are more modes that we dont want to store: initialize -> after wipe device + seedless -> should not happen in suite but...

File: packages/suite/src/reducers/suite/deviceReducer.ts [hunk 2]
```diff
@@ -138,12 +138,18 @@ const changeDevice = (
     if (!device.features) return;
 
     // find devices with the same "device_id"
-    const affectedDevices = draft.filter(
-        d =>
+    const affectedDevices = draft.filter(d => {
+        const parsedDeviceState = d.state?.split(/@|:/); // address@device_id:instance
```
Comment (szymonlesisz) [inline packages/suite/src/reducers/suite/deviceReducer.ts]: not sure that this will be the best approach, device state format may change in the future.
we set current state/format for debugging purposes and never went back but i think it should be a shorter hash (see[ this commented line](https://github.com/trezor/connect/blob/develop/src/js/device/DeviceCommands.js#L323))

 maybe we should always prevent device_id from overrinding when switched to bootloader? (see merge func. above)  or maybe we should introduce additional field in device for that purpose?

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite/src/reducers/suite/deviceReducer.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/reducers/suite/deviceReducer.ts]: I preserved id if it wanted to be changed to null. c5b217a48d721263d0e398cfd8c3537dc647c778

File: packages/suite/src/middlewares/wallet/storageMiddleware.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts]: changed and squashed because of a change of commit message

File: packages/suite/src/reducers/suite/deviceReducer.ts (hunk 2 above)
Comment (szymonlesisz) [reply packages/suite/src/reducers/suite/deviceReducer.ts]: could you pls double check if there are places where device.id is **expected** to be null?

Comment (tomasklim) [reply packages/suite/src/reducers/suite/deviceReducer.ts]: Double checked, everything looks okay

**Review by szymonlesisz — APPROVED** [review]
