### PR TITLE
fix(suite): Make coin filter visibility persistent

### LINKED ISSUE #18453: CoinsFilter follow up
**Describe the bug**
Follow up https://github.com/trezor/trezor-suite/pull/18099

❌ opened/closed filter is stored in local storage so if you leave it open, it will remain open for next launch
❌ enable filter, disable coins and leave only one enabled, filter is always open
❌ consider renaming `Accounts` to something more appropriate as you filter by tokens, address....
❌ see [this](https://github.com/trezor/trezor-suite/pull/18099#issuecomment-2780620548) its easy to mess-up filter by clicking on coins in dashboard /see second screenshot that shows only Eth accounts in left bar but POL account is opened in main window/

**Info:**
 - Suite version: desktop 25.5.0 (aa08fd85a5fb62774cf0e766c71892a8f24250a0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.5.0 Chrome/134.0.6998.178 Electron/35.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3B1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

Image\

Image

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/18453

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=make-coin-filter-visbility-persistent&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=make-coin-filter-visbility-persistent&lookback=7)

### CODE REVIEW

**Comment by vojtatranta** [comment]
this has got potetntial to break the E2E tests btw. Coz it can be persistent over multiple browser windows and hence break the tests that click on coinf filter after some other tests filtesr some coins.

But maybe the window is breand new, not sure.

File: packages/suite/src/middlewares/wallet/storageMiddleware.ts [hunk 1]
```diff
@@ -265,6 +265,7 @@ const storageMiddleware = (api: MiddlewareAPI<Dispatch, AppState>) => {
                 case SUITE.TOGGLE_FIRMWARE_HASH_CHECK:
                 case SUITE.EVM_CONFIRM_EXPLANATION_MODAL:
                 case SUITE.EVM_CLOSE_EXPLANATION_BANNER:
+                case SUITE.SET_IS_COINS_FILTER_VISIBLE:
```
Comment (vojtatranta) [inline packages/suite/src/middlewares/wallet/storageMiddleware.ts:260]: this only changes the facdt that settings is saved right after this action is dispatched.

Is the key really persisted? Like, it should be persistent even without this change.

Comment (jvaclavik) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts:260]: It wasn't persistent before this change, now it is

Comment (vojtatranta) [reply packages/suite/src/middlewares/wallet/storageMiddleware.ts:260]: yeah, so I tested it out and it **is** persisted alredy, however, it is not saved directly when the filter visibility is toggled.

So you are basically fixing a bug.

**Review by vojtatranta — APPROVED** [review]
