### PR TITLE
fix: cursor in search-action when collaped

### LINKED ISSUE #11312: Search button/field doesn't work properly
**Describe the bug**
Search button/field doesn't work properly.
image

1. when mouse over the button, there should be the "hand" and not cursor.
image

2. when you type something into the field, the "x" button doesn't work 
image

**Info:**

-   Remembered Wallet: yes
-   Suite Version: 24.2.2

**How to reproduce**

1. hover over the button
2. type some text into the text field and try to delete with the "x" button

**Expected behavior**
1. See a hand on hover
2. be able to delete the whole text with the "x" button

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/11312

image

### CODE REVIEW

**Review by Lemonexe — APPROVED** [review]
LGTM, tested :heavy_check_mark:

File: packages/suite/src/components/wallet/SearchAction.tsx [hunk 1]
```diff
@@ -104,14 +107,14 @@ export const SearchAction = ({
                 innerAddon={
                     <Icon
                         name="search"
-                        cursorPointer
```
Comment (Lemonexe) [inline packages/suite/src/components/wallet/SearchAction.tsx]: now I noticed that the icon is clickable when the input is expanded (it folds it), so it should have 
`cursorPointer`

Comment (peter-sanderson) [reply packages/suite/src/components/wallet/SearchAction.tsx]: Wow, nice catch. :clap:
