### PR TITLE
Fix/eth tokens discovery

### LINKED ISSUE #10525: Discovery of tokens does not work properly
Steps to reproduce:
1. Connect Trezor which has some ERC20 tokens
2. Let the discovery finish
3. Go to My assets
4. You see only ETH account
5. Click on ETH account and go back to My Assets
6. ERC20 token appear

See the video:
https://drive.google.com/file/d/1uKZBK_WzUSnfV_RK1ClwXI9RodQFwbM8/view?usp=sharing

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- 95cbc47b41b38b666db67e4405fbd12f99c995ca: After discovery of ETH account, the fiat rates middleware downloads fiat rates for all its tokens. This step is crucial, because we are displaying only tokens that have fiat rates. Other are considered as scam tokens and ignored.
- 360d54198a7a315858c66c13d711ec2579b67068: `AccountListItem` is now wrapped into Box component, to avoid malformed layout created by parent `VStack` component.

## Related Issue

Resolve #10525 

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/c85fdeba-ca0b-4cd7-899f-b01d39ede5ae

### CODE REVIEW

File: suite-native/discovery/src/discoveryThunks.ts [hunk 1]
```diff
@@ -88,9 +88,13 @@ const finishNetworkTypeDiscoveryThunk = createThunk(
...
-    const network = getNetwork(coin);
+    const networkType = getNetworkType(coin);
     // For Cardano we need to fetch at least one tx otherwise it will not generate correctly new receive addresses (xpub instead of address)
-    if (network?.networkType === 'cardano') return { details: 'txs', pageSize: 1 } as const;
+    if (networkType === 'cardano') return { details: 'txs', pageSize: 1 } as const;
+
+    // For Ethereum we need to fetch token balances to be able to get their fiat rates and later display them in the UI.
+    if (networkType === 'ethereum') return { details: 'tokenBalances' } as const;
+
     return { details: 'tokens' } as const;
```
Comment (Nodonisko) [inline suite-native/discovery/src/discoveryThunks.ts]: What's difference between `tokens` and `tokenBalances`. Maybe we should put default fallback to `tokenBalances`?

Comment (PeKne) [reply suite-native/discovery/src/discoveryThunks.ts]: `token` return array of included account tokens metadata. `tokenBalances` return the same array, but also information how much balance the account have.

Btw. why are we fetching `tokens` for any network? Should not be enought to fetch `basic` by default? Then only `tokenBalances` for Ethereum and `txs` for Cardano?

Comment (Nodonisko) [reply suite-native/discovery/src/discoveryThunks.ts]: I guess it will do nothing for other networks like 'btc' where are no tokens and return just 'basic'

Comment (Nodonisko) [reply suite-native/discovery/src/discoveryThunks.ts]: You may try to set `basic` or `tokenBalances` instead.

Comment (PeKne) [reply suite-native/discovery/src/discoveryThunks.ts]: I am confident that the' basic' level is sufficient for all coins other than Ethereum-like ones. Fixed with ba5c3b5f98.

**Review by juriczech — APPROVED** [review]
