### PR TITLE
Fix trading layout header

### LINKED ISSUE #25612: Merge Swap + Buy&Sell together
Please merge SWAP + BUY&SELL together. The switching is done by tabs on the top of the page.
- [Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=7691-26465&t=tBuSyYBao9NwFJKn-4)
- Wherever user clicks `Buy&Sell` or `Swap` buttons, open him this page with the correct tab active

Image

### PR DESCRIPTION
**Pull request by seibei-iguchi**
# Notes for QA
Added Swap to the tab navigation in Buy & sell, renamed the whole section to Trade, instead of Buy & Sell and Swap.

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=refactor/trade-navigation&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=refactor/trade-navigation&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 2 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-09T15:37:08.845Z • 2 test(s) total_

<details><summary>Trezor Suite (desktop) — 3 test(s)</summary>

| Test | Type |
|------|------|
| Staking - Cardano > Stake Cardano | 🤖 auto |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-03-09T10:13:35.756Z • 3 test(s) total_

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingLayout/TradingLayout.tsx [hunk 1]
```diff
@@ -1,23 +1,14 @@
...
-    return (
-        <Column data-testid="@trading" gap={spacings.xl}>
-            {!routeName?.includes(`wallet-trading-exchange`) && (
-                <TradingLayoutNavigation route={routeName} />
-            )}
-            {children}
-        </Column>
-    );
-};
+export const TradingLayout = ({ children }: TradingLayoutProps) => (
```
Comment (sherpaPSX) [inline packages/suite/src/views/wallet/trading/common/TradingLayout/TradingLayout.tsx]: `export const TradingLayout = ({ children }: PropsWithChildren)`

You don't need to define Props if you don't need them

**Review by sherpaPSX — CHANGES_REQUESTED** [review]

**Review by sherpaPSX — APPROVED** [review]

**Review by izmy — APPROVED** [review]

**Comment by zako05** [comment]
QA OK ✅


https://github.com/user-attachments/assets/f4693ccd-32f5-465e-8d45-c5a29498a080
