### PR TITLE
fix(native): fixed BTC fees rounding, correct decimal pad for custom fee

### LINKED ISSUE #22400: Buggy decimals in fee rate
- [ ] Missing fee rate decimals
- [ ] Button `Review and Sign` doesn't work when I select fee rate below 1 sat/vB
- [ ] There is no option in `custom` fee rate field to specify decimals - https://github.com/trezor/trezor-suite/issues/21917

| Image | Image |
| --- | --- |

### PR DESCRIPTION
**Pull request by OriginalEveres**
**Changes**:
- fixed correct rounding for BTC fees
- shows a correct decimal pad for BTC custom fee

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22400

## Screenshots:
**BEFORE**:
499877285-4fa91cab-842f-4eb1-bd61-c1e6e8d93939
499877284-a1548086-6a48-42cc-9112-3e6b8807a468

**AFTER**:
simulator_screenshot_9CF399FF-173D-4F99-BDF4-0B8C90CE46DC
simulator_screenshot_0EFBE276-54AA-479E-AB9B-BB4B909D289A

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/btc-fees&lookback=7)

### CODE REVIEW

File: suite-native/transaction-management/src/components/fees/FeeOptionList/FeeOption.tsx [hunk 1]
```diff
@@ -75,7 +75,9 @@ const getFeePerUnit = ({
     }
 
     if (networkType === 'bitcoin') {
-        return String(Math.round(Number(feeLevel.fee) / transactionBytes));
+        const feePerVb = Number(feeLevel.fee) / transactionBytes;
+
+        return Number.isInteger(Number(feePerVb)) ? String(feePerVb) : Number(feePerVb).toFixed(2);
```
Comment (Lemonexe) [inline suite-native/transaction-management/src/components/fees/FeeOptionList/FeeOption.tsx:80]: `feePerVb` was alredy cast to number
```suggestion
        return Number.isInteger(feePerVb) ? String(feePerVb) : feePerVb.toFixed(2);
```

**Review by Lemonexe — APPROVED** [review]
LGTM. Can't test because my local dev env is now broken 🙈 
I'll take a look again when I can get it to work.

EDIT: works
