### PR TITLE
fix(suite-native): non closable device onboarding screen

### LINKED ISSUE #21780: Handle THP cancellation during FW install
**Steps to reproduce:**
1. Fresh app, factory reset, connect via Ble
2. FW install
3. After FW is installed and Trezor restarted, user is prompted to THP connection
4. Cancel THP flow within device onboarding
5. User is in incorrect state on dashboard with non-THP authorized device

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21780

## Screenshots:

https://github.com/user-attachments/assets/f52e4095-261e-4167-ad93-e14897920fdb

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/disable-closing-fw-install-in-onboarding&lookback=7)

### CODE REVIEW

File: suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+type NonClosableDeviceOnboardingScreenProps = {
+    screenHeaderRightIcon?: ReactNode;
+    onAlertContinueButtonPress?: () => void;
+} & ScreenProps;
+
+export const NonClosableDeviceOnboardingScreen = ({
+    children,
+    screenHeaderRightIcon,
+    onAlertContinueButtonPress,
```
Comment (PeKne) [inline suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx]: Unused. probably leftover from `DeviceOnboardingScreenWithExitButton` component.

**Review by PeKne — APPROVED** [review]

File: suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx]: Fixed and squashed. Good catch

File: suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+export const NonClosableDeviceOnboardingScreen = ({
+    children,
+    screenHeaderRightIcon,
+    ...screenProps
+}: NonClosableDeviceOnboardingScreenProps) => {
+    useOverrideBackNavigation();
+
+    return (
+        <Screen
+            header={<DynamicScreenHeader rightIcon={screenHeaderRightIcon} leftIcon={null} />}
```
Comment (yanascz) [inline suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx]: Nit:
```suggestion
            header={<DynamicScreenHeader leftIcon={null} rightIcon={screenHeaderRightIcon} />}
```

Comment (juriczech) [reply suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx]: Done

File: suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx [hunk 3]
```diff
@@ -27,12 +28,14 @@ export const ThpConfirmationScreen = ({
...
     return (
-        <DeviceOnboardingScreenWithExitButton
+        <NonClosableDeviceOnboardingScreen
             isScrollable={false}
             noBottomPadding={true}
             hasBottomInset={false}
         >
-            <ContinueOnTrezorScreenContent />
-        </DeviceOnboardingScreenWithExitButton>
+            <Box flex={1}>
```
Comment (yanascz) [inline suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx]: This wrapping has no effect, may be reverted.

File: suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+export const NonClosableDeviceOnboardingScreen = ({
+    children,
+    screenHeaderRightIcon,
+    ...screenProps
+}: NonClosableDeviceOnboardingScreenProps) => {
+    useOverrideBackNavigation();
+
+    return (
+        <Screen
+            header={<DynamicScreenHeader leftIcon={null} rightIcon={screenHeaderRightIcon} />}
```
Comment (yanascz) [inline suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx]: I guess you should use `isCompactOnly={true}` here.

File: suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx [hunk 5]
```diff
@@ -0,0 +1,32 @@
...
+            {...screenProps}
```
Comment (yanascz) [inline suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx:24]: I guess you should also add `isScrollable={false}`.

**Review by yanascz — CHANGES_REQUESTED** [review]
It's possible to swipe back on iOS.

File: suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx (hunk 5 above)
Comment (juriczech) [reply suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx:24]: Done

File: suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx (hunk 4 above)
Comment (juriczech) [reply suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx]: Done

Comment (juriczech) [reply suite-native/module-device-onboarding/src/components/NonClosableDeviceOnboardingScreen.tsx]: DynamicScreenHeader is not necessary, replaced by normal ScreenHeader where compact prop is not needed.

File: suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx (hunk 3 above)
Comment (juriczech) [reply suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx]: Done

File: suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx [hunk 6]
```diff
@@ -27,12 +27,12 @@ export const ThpConfirmationScreen = ({
     }, [thpStep, navigation]);
 
     return (
-        <DeviceOnboardingScreenWithExitButton
+        <NonClosableDeviceOnboardingScreen
             isScrollable={false}
```
Comment (yanascz) [inline suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx]: I guess this is redundant now.

**Review by yanascz — APPROVED** [review]
Looks better now! 👏
