### PR TITLE
@trezor/transport refactor

### LINKED ISSUE #4268: Discovery crashes when opening device selector sometimes
**Describe the bug**
When opening and closing device selector modal in Suite during discovery after connecting a device, the discovery process crashes randomly. See video below.

**Steps to reproduce:**
1. Open suite without having Trezor connected
2. Connect Trezor, enter PIN
3. Optional: try to open device selector modal before Suite asks for passphrase
4. Choose standard wallet (or enter passphrase)
5. Approve labeling in Trezor (if enabled), discovery process begins
6. Open and close device selector modal multiple times
7. The discovery process will fail in such circumstances in random time and result

**Info:**
 - Suite version: desktop 21.8.1 (bde9e100c5ef37d7ef99c2953f14cc053cfd015d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.8.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.1 regular

**Expected result:**
Discovery process should run and succeed no matter what the user clicks (except active cancelation like ejecting the device)

**Actual result:**
Discovery process fails randomly. See video below.

**Screenshots:**
https://user-images.githubusercontent.com/88533514/133215608-2a9402b3-6636-4af3-803a-8124645e971a.mov

**Note(s):**
Edge case, users can figure out easily to be tender during the discovery phase to avoid the bug. So priority low.

### LINKED ISSUE #4601: [TRACKER] @trezor/transport followup
- [x] archive https://github.com/trezor/trezor-link
- [x] update index redme
- [x] release @trezor/transport to npm (under @trezor org)
- [ ] add logging back (sorry, forgot about it) [original decorator](https://github.com/trezor/trezor-link/blob/9c200cc5608976cff0542484525e98c753ba1888/src/debug-decorator.js), [implementations 1](https://github.com/trezor/trezor-link/blob/9c200cc5608976cff0542484525e98c753ba1888/src/bridge/v2.js#L56), [implementations 2](https://github.com/trezor/trezor-link/blob/9c200cc5608976cff0542484525e98c753ba1888/src/lowlevel/webusb.js#L49) +withSharedConentions 
- [x] implement @trezor/transport as dependency into connect
- [x] resolve exceptions in eslint config in @trezor/transport package. these are going to require some refactoring of transport layer
- [x] finish transport e2e tests that were separated into this branch https://github.com/trezor/trezor-suite/tree/transport-e2e
- [x] #5068 
- [x] #5069 

consider (ideas from #2923): 
 - ~~use .proto files~~ probably doesnt make sense, but we may revisit it later
 - ~~allow multiple protobuf sets/instances~~ this is imho antipattern
 - http requests cancelation
 - general cancel logic (currently handled by connect)
 - enumeration cycle module (currently handled by connect) #5035
 - http requests race conditions (currently handled by connect)

-----

consider https://github.com/trezor/trezor-suite/issues/1642 (discuss with matejcik)

____ 

tansferred from https://github.com/trezor/trezor-link/issues/40

problems:

- incremental device path is missing (there could be two unreadable devices)
- error handling needs to be implemented differently on user side (example in connect)

solution:
- process hid devices is the same way as bootloader devices
- master/src/lowlevel/webusb.js#L86

process unreadableHidDeviceChange internally and resolve it by enumerate response

___

transferred from https://github.com/trezor/trezor-link/issues/4

We need to export error messages up, to avoid string comparison.
Example:

trezor-link will throw Error("device not found"); to catch it and react properly i need to compare error.message with local string "device not found".

Better solution is:

```
export const DEVICE_NOT_FOUND = new Error('device not found');

```
then:

```
import { DEVICE_NOT_FOUND } from 'trezor-link';
```
and then:
```
if (error === DEVICE_NOT_FOUND) { ... }
```

### LINKED ISSUE #5035: @trezor/transport enumaration cycle
Refactor and move enumaration from trezor-connect into @trezor/transport package. 

- [ ] Finish abstract transport, bridge transport and webusb transport.
Once we are happy with it we can work in parallel on next steps:
- Add native Node.js USB library to @transport -  https://github.com/trezor/trezor-suite/issues/4770
- Reinventing shared connections, fallback and so on.

### LINKED ISSUE #5036: @trezor/transport logging
In some recent refactor we removed logging from @trezor/transport lib. It used decorators and did not fit into code base well. I would like to introduce it back again. My idea is that this lib could accept unified logger instance from outside. In the end all low level libs could be using the same logger.

### LINKED ISSUE #5336: WebUsbPlugin does not conform to LowlevelTransportSharedPlugin in @trezor/transport
**Describe the bug**

WebUsbPlugin does not conform to LowlevelTransportSharedPlugin in @trezor/transport

**How to reproduce**

Given the following TypeScript file

```TypeScript
import trezorTransport from "@trezor/transport";

const link = new trezorTransport.Lowlevel(
  new trezorTransport.WebUsb(),
  undefined
);
```

Running `tsc` will yield the following error

```
src/app.ts:4:3 - error TS2345: Argument of type 'WebUsbPlugin' is not assignable to parameter of type 'LowlevelTransportSharedPlugin'.
  The types returned by 'init(...)' are incompatible between these types.
    Type 'void' is not assignable to type 'Promise<void>'.

4   new trezorTransport.WebUsb(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/app.ts:4
```

**Expected behavior**

This should compile

### LINKED ISSUE #5597: TrezorConnect.cancel() throws random errors
**Describe the bug**
After calling `TrezorConnect.cancel()`, from time to time the SDK or the device refuses to perform subsequent actions (for example, getting device features or requesting xpub) and throws various errors.

We noticed that this behavior takes place when the operation is cancelled quickly after it’s requested (under ~5 seconds).

Most often, the error we were getting was `Device_CallInProgress`, however from time to time we could observe other types of errors such as `Error: assertType: Response of unexpected type: CardanoTxItemAck. Should be Features`

**Info:**

-   Remembered Wallet: yes & no - tried both
-   Suite Version: 22.5.2
-   Browser: NodeJS v14
-   OS: macOS 12.1
-   Bridge: 2.0.27
-   Firmware Version: 2.4.4 and 2.5.1

**How to reproduce**

1. Export public key
1. Cancel the operation in 5 seconds
1. Try to export public key again
1. See error

**Expected behavior**
`TrezorConnect.cancel()` cancels the operation and always allows to continue interacting with the device.

**Screenshots**
Some error examples:
Screenshot 2022-06-01 at 17 41 26
Screenshot 2022-06-01 at 22 25 59 

**Additional context**
Observed in Daedalus 4.11.0

Possibly the error is related to this commit: https://github.com/trezor/connect/commit/fc60c3c03d6e689f3de2d518cc51f62e649a20e2

### PR DESCRIPTION
**Pull request by mroz22**
### Based on
- [x] #7321
- [x]  https://github.com/trezor/trezor-suite/pull/7411
- [x] https://github.com/trezor/trezor-suite/pull/7409
- [x] https://github.com/trezor/trezor-suite/pull/7336
- [x] https://github.com/trezor/trezor-suite/pull/7346
- [x] https://github.com/trezor/trezor-suite/pull/7383
- [x] https://github.com/trezor/trezor-suite/pull/7411
- [x] https://github.com/trezor/trezor-suite/pull/7443
- [x] #7821
- [x] #7870, #7844, #7857 needed to updated jest and run tests with AbortController in connect
- [x] #7922 needed to run make AbortController in tests work
 
Changes in @trezor/transport: 
- removed debug-link support all together. We have not used it since trezor-user-env came into service.
- sessions management. I am adding a module that is called "sessions background" it is used to control access to usb/device and holds information about sessions. This is not new, previously it was implemented [here](https://github.dev/trezor/trezor-suite/blob/develop/packages/transport/src/lowlevel/sharedConnectionWorker.ts#L150).  This module could be used in various contexts. At the moment, we only have [SharedWorker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker). 
- created `interfaces` folder with lowest-possible-level unifying abstraction over native transport interfaces. so far only webusb.
- added abstract transport class for API unification which itself inhertis from a strongly typed event emiter. no method from transport should throw error. each method should return either `Success` or `Error`
- added abstract USB class, derived from abstract transport class. Used for code sharing between webusb and nodeusb. This is basically compilation of [withSharedConnections.ts](https://github.dev/trezor/trezor-suite/blob/develop/packages/transport/src/lowlevel/withSharedConnections.ts) and [webusb.ts](https://github.dev/trezor/trezor-suite/blob/55f7ea4f0f0c544e300dc1d8a080d558404ae876/packages/transport/src/lowlevel/webusb.ts). This is the place that implements low-level transport interface and sessions.
- webusb now does not run iteration cycle in 500ms endless loop. The reasons are that it does not feel right if there are connection events available and also it probably would not work for nodeusb where enumaration cycle takes considerably longer than 500ms 
- all transport calls are now abortable
- race conditions related to "cancel" method should now be fixed. Errors such as "Unexpected response, expected Address, received Featrues" should not appear anymore or at least should appear less often.

### Related issues
- resolves #5036
- resolves #5035 by moving former DescriptorStream logic into the abstract transport class. 
- resolves #5336 because these files will not exist anymore and there will be only transports that inherit from abstract transport class
- resolves #5597
- resolves #4268
- closes #4601 - problems described there do not seem relevant anymore
- related #5332
- related #4041
- enables #4770
- #5068 - should at least not be unhandled now.
- #5069 - should at least not be unhandeld now and might even be fixed. This seems to be part of cancelling problem, here trying to read/write from device that has been released by bridge.
- related #6886 - connect now accepts transport as a param in init method.
- please retest #5543
- please retest #4670
- please retest #4267
- #5056 would be interesting to check/finish this test

## QA testing tips:
In the first place, focus on regression in communication with device. Nodeusb feature is still hidden behind debug (and I am even considering pulling it out into separate PR based on this). Some tips what to test:
- `google-chrome http://localhost:8000/ http://localhost:8000/` open multiple tabs at once
- debugging shared workers [chrome://inspect/#workers](chrome://inspect/#workers)
- multiple devices connected
- mad-reconnecting in the middle of communication with device
- cancel message (pin, passphrase, etc)
- all of above for both webusb and bridge
- when using bridge transport, app should survive when computer goes to sleep 

### QA
- [first smoke test](https://www.notion.so/satoshilabs/Test-connect-branch-before-merge-d72cc3ebffb94771b46a25ab6ed0997c)
- [test 2](https://www.notion.so/satoshilabs/Transport-refactor-final-retest-b3e498a0a87a4c77bfd5a07e6ba53a59?pvs=4)

### CODE REVIEW

**Comment by mroz22** [comment]
Finally managed to get to the point where desktop app works with nodeusb transport and code is structured more or less in a good way. Of course it is still terribly messy and I needed to disable few features (sessions, unacquired devices etc) to make it work for now.

File: packages/connect/src/events/transport.ts [hunk 1]
```diff
@@ -1,17 +1,10 @@
...
-export const TRANSPORT = {
-    START: 'transport-start',
-    ERROR: 'transport-error',
-    UPDATE: 'transport-update',
-    STREAM: 'transport-stream',
-    REQUEST: 'transport-request_device',
-    DISABLE_WEBUSB: 'transport-disable_webusb',
-    START_PENDING: 'transport-start_pending',
-} as const;
+import { TRANSPORT as $TRANSPORT } from '@trezor/transport';
```
Comment (szymonlesisz) [inline packages/connect/src/events/transport.ts]: export { TRANSPORT } from '@trezor/transport'; ?

File: suite-common/suite-types/src/debug.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import { Transport } from '@trezor/transport';
```
Comment (mroz22) [inline suite-common/suite-types/src/debug.ts]: export from connect

File: packages/connect/src/device/DeviceList.ts [hunk 3]
```diff
@@ -59,99 +47,293 @@ export interface DeviceList {
...
-
-            // detection of environment browser/node
-            // todo: code should not be detecting environment itself. imho it should be built with this information passed from build process maybe?
-            const isNode =
-                !!process?.release?.name && process.release.name.search(/node|io\.js/) !== -1;
-            BridgeV2.setFetch(fetchWithSignal, isNode);
-            // @ts-expect-error TODO: https://github.com/trezor/trezor-suite/issues/5332
-            transports.push(bridge);
+        if (!transports?.length) {
+            transports = ['BridgeTransport', 'WebUsbTransport'];
```
Comment (karliatto) [inline packages/connect/src/device/DeviceList.ts]: It could be interesting to create some enum or similar for this kind of transports strings.


Something like the below that can be used in other places as well:

```typescript
enum TransportType {
  NodeUsbTransport = 'NodeUsbTransport',
  WebUsbTransport = 'WebUsbTransport',
  BridgeTransport = 'BridgeTransport',
}
```

File: packages/connect/src/device/DeviceList.ts [hunk 4]
```diff
@@ -59,99 +47,293 @@ export interface DeviceList {
...
+                        this.transports.push(new NodeUsbTransport({ messages: this.messages }));
+                        break;
+                    case 'WebUsbTransport':
+                        // todo: any idea how to configure typescript here?
+                        this.transports.push(
+                            // @ts-expect-error
+                            new WebUsbTransport({
+                                messages: this.messages,
+                            }),
+                        );
```
Comment (karliatto) [inline packages/connect/src/device/DeviceList.ts]: It looks like WebUsbTransport does not take any arguments and here it is taking an object, based on:

`packages/transport/src/transports/webusb.ts`
```typescript
export class WebUsbTransport {
    init() {
        return Promise.resolve({
            success: false,
            message: WRONG_ENVIRONMENT,
        });
    }
}
```

Maybe if the message is necessary to be passed, we should update `WebUsbTransport` definition, to use the passed message or to take message optionally.

File: packages/connect/src/device/DeviceList.ts [hunk 5]
```diff
@@ -59,99 +47,293 @@ export interface DeviceList {
...
+                            'Runtime',
+                            `DeviceList.init: transports[] of unexpected type: ${transportType}`,
+                        );
+                    // not implemented
+                    // case 'UdpTransport':
+                }
 
-        this.transport = new Fallback(transports);
-        this.messages = DataManager.getProtobufMessages();
+                // todo: a better check whether abstract transport class is in prototype of provided transport object?
```
Comment (karliatto) [inline packages/connect/src/device/DeviceList.ts]: Yes, at least checking that the provided transport is instance of the abstract transport class. This will help catch any potential runtime errors due to using an incompatible object as a transport.

File: packages/connect/src/device/DeviceList.ts (hunk 4 above)
Comment (karliatto) [inline packages/connect/src/device/DeviceList.ts]: Maybe this could be extracted into functions that would make it more readable:

```typescript
const createWebUsbTransport = (messages: string) => {
  return new WebUsbTransport({
    messages,
  });
}
```

And then used in the switch like:

```typescript
         case TransportType.WebUsbTransport:
            this.transports.push(createWebUsbTransport(this.messages));
            break;
          case Tran
```

File: packages/connect/src/events/transport.ts [hunk 6]
```diff
@@ -1,18 +1,11 @@
...
-    START: 'transport-start',
-    ERROR: 'transport-error',
-    UPDATE: 'transport-update',
-    STREAM: 'transport-stream',
-    REQUEST_DEVICE: 'transport-request_device',
-    DISABLE_WEBUSB: 'transport-disable_webusb',
-    START_PENDING: 'transport-start_pending',
-} as const;
-
+export const TRANSPORT = $TRANSPORT;
```
Comment (karliatto) [inline packages/connect/src/events/transport.ts]: This importing `{ TRANSPORT as $TRANSPORT }` and then doing `const TRANSPORT = $TRANSPORT` looks a bit weird to my eyes, is there a reason for that? :thinking:

File: packages/transport/src/constants.ts [hunk 7]
```diff
@@ -1,3 +1,12 @@
+export const MESSAGE_HEADER_BYTE = 0x23;
+export const HEADER_SIZE = 1 + 1 + 4 + 2;
+export const BUFFER_SIZE = 63;
+
+export const T1HID_VENDOR = 0x534c;
+export const CONFIGURATION_ID = 1;
+export const INTERFACE_ID = 0;
+export const ENDPOINT_ID = 1;
+
 export const TREZOR_DESCS = [
```
Comment (karliatto) [inline packages/transport/src/constants.ts]: What does `DESCS` means here? Descriptions? Very cryptic name :exploding_head:

File: packages/transport/src/index.ts [hunk 8]
```diff
@@ -11,22 +6,38 @@ import WebUsbPlugin from './lowlevel/webusb';
...
+
+export { SessionsBackground } from './sessions/background';
+export { SessionsClient } from './sessions/client';
 
-export default {
-    BridgeV2: BridgeTransportV2,
-    Fallback: FallbackTransport,
-    Lowlevel: LowlevelTransportWithSharedConnections,
-    WebUsb: WebUsbPlugin,
+export const ERROR = {
```
Comment (karliatto) [inline packages/transport/src/index.ts]: Maybe we could export this as `TRANSPORT_ERROR` to make it ore clear when importing them.

File: packages/connect/src/core/index.ts [hunk 9]
```diff
@@ -1,5 +1,8 @@
 /* eslint-disable @typescript-eslint/no-use-before-define */
 import EventEmitter from 'events';
+
+import { TRANSPORT, ERROR as TRANSPORT_ERROR } from '@trezor/transport';
```
Comment (karliatto) [inline packages/connect/src/core/index.ts]: If we export it as `TRANSPORT_ERROR`  it would be more clear to import here?

File: packages/transport/src/transports/usb.ts [hunk 10]
```diff
@@ -0,0 +1,332 @@
...
+                    this.transportInterface.read(path).then(result => {
+                        if (result.success) {
+                            return result.payload;
+                        }
+                        // todo:
+                        throw new Error(result.error);
+                    }),
+                );
+
+                resolve(this.success(message));
```
Comment (karliatto) [inline packages/transport/src/transports/usb.ts]: I see in lines 174 and 177 that resolve and reject are returned, but here and below it not, it would be nice to do it the same way across this.

File: packages/transport/src/transports/usb.ts [hunk 11]
```diff
@@ -0,0 +1,332 @@
...
+                session,
+            });
+            if (!getPathBySessionResponse.success) {
+                // session not found means that device was disconnected
+                if (getPathBySessionResponse.error === 'session not found') {
+                    return reject(this.error({ error: 'device disconnected during action' }));
+                } else {
+                    // should never happen
+                    return reject(this.error({ error: 'unexpected error' }));
+                }
```
Comment (karliatto) [inline packages/transport/src/transports/usb.ts]: Since there is a return in the previous if, this else should be unnecessary:

```suggestion
                }
               // should never happen
               return reject(this.error({ error: 'unexpected error' }));
```

File: packages/transport/src/transports/usb.ts [hunk 12]
```diff
@@ -0,0 +1,332 @@
...
+                        }),
+                    name,
+                    data,
+                );
+                resolve(this.success(undefined));
+            } catch (err) {
+                if (err.message === INTERFACE_ERRORS.DEVICE_DISCONNECTED_WEBUSB) {
+                    this.enumerate();
+                }
+                reject(this.error(err));
```
Comment (karliatto) [inline packages/transport/src/transports/usb.ts]: Here it is calling `resolve` and `reject` without returning it , but above in the same promise those are returned. Wouldn't be nice to do it the same way?

File: packages/transport/src/transports/usb.ts [hunk 13]
```diff
@@ -0,0 +1,332 @@
...
+                    (buffer: Buffer) =>
+                        this.transportInterface.write(path, buffer).then(result => {
+                            if (!result.success) {
+                                // todo:
+                                throw new Error(result.error);
+                            }
+                        }),
+                    name,
+                    data,
+                );
```
Comment (karliatto) [inline packages/transport/src/transports/usb.ts]: It looks a bit confusing the mix using of `async/await` syntax with promise.then. all in a `try {} catch() {}`.

Maybe it would make more sense to use something like:

```typescript
 const result = await this.transportInterface.write(path, buffer);
 if (!result.success) {
    throw new Error(result.error);
 }
```

File: packages/transport/src/transports/usb.ts [hunk 14]
```diff
@@ -0,0 +1,332 @@
...
+
+                const message = await receiveAndParse(this.messages, () =>
+                    this.transportInterface.read(path).then(result => {
+                        if (result.success) {
+                            return result.payload;
+                        }
+                        // todo:
+                        throw new Error(result.error);
+                    }),
```
Comment (karliatto) [inline packages/transport/src/transports/usb.ts]: Maybe it would be more consistent to use only async/await syntax like:

```suggestion
const result = await this.transportInterface.read(path);
if (result.success) {
   return result.payload;
 }
throw new Error(result.error);
```

File: packages/transport/src/index.ts [hunk 15]
```diff
@@ -11,22 +6,38 @@ import WebUsbPlugin from './lowlevel/webusb';
 import * as protobuf from 'protobufjs/light';
 import * as Long from 'long';
 
+import * as COMMON_ERRORS from './errors';
+import * as SESSION_ERRORS from './sessions/errors';
+import * as TRANSPORT_ERRORS from './transports/errors';
+import * as INTERFACE_ERRORS from './interfaces/errors';
+
```
Comment (karliatto) [inline packages/transport/src/index.ts]: I am not sure if having all those errors separated make sense, since there are not that many of them, maybe having them all in `./errors.ts` would be more handy.

But maybe makes sense, just wondering if you have a clear preference about it.

File: packages/transport/src/constants.ts [hunk 16]
```diff
@@ -1,3 +1,12 @@
+export const MESSAGE_HEADER_BYTE = 0x23;
+export const HEADER_SIZE = 1 + 1 + 4 + 2;
+export const BUFFER_SIZE = 63;
+
+export const T1HID_VENDOR = 0x534c;
```
Comment (karliatto) [inline packages/transport/src/constants.ts]: Maybe `T1_HID_VENDOR` would be more clear separating `T1` from `HID`?

File: packages/transport/src/transports/abstract.ts [hunk 17]
```diff
@@ -0,0 +1,399 @@
...
+        // bridge
+        | typeof TRANSPORT_ERRORS.DEVICE_DISCONNECTED
+        | typeof TRANSPORT_ERRORS.DEVICE_CLOSED
+        | typeof TRANSPORT_ERRORS.WRONG_RESULT_TYPE // local
+        | typeof TRANSPORT_ERRORS.HTTP_ERROR
+        // webusb + bridge
+        | typeof INTERFACE_ERRORS.DEVICE_NOT_FOUND
+        | typeof SESSION_ERRORS.WRONG_PREVIOUS_SESSION
+        | typeof COMMON_ERRORS.UNEXPECTED_ERROR
+    >;
```
Comment (karliatto) [inline packages/transport/src/transports/abstract.ts]: I like having all those errors type here. Nice!

**Review by karliatto — COMMENTED** [review]
Over all it is a huge improvement. I like the new structure.
I added some comments of ideas I was having while reading it.

File: packages/connect/src/device/DeviceList.ts (hunk 4 above)
Comment (mroz22) [reply packages/connect/src/device/DeviceList.ts]: I ended up doing it like this c695d43f1d33c019c7a6e80dd5cf7ea35862de2f changing packages/transport/src/transports/webusb.ts type definition in that way that it satisfies abstract transport types. it required few expect-errors but these are ok since this file (packages/transport/src/transports/webusb.ts) is meant to by replaced by webusb.browser anyway

Comment (mroz22) [reply packages/connect/src/device/DeviceList.ts]: I got rid of expect-error here   https://github.com/trezor/trezor-suite/commit/c695d43f1d33c019c7a6e80dd5cf7ea35862de2f 
 and from my point of view it feels ok now - quite readable whats going on

File: packages/connect/src/device/DeviceList.ts (hunk 5 above)
Comment (mroz22) [reply packages/connect/src/device/DeviceList.ts]: types tightened here cb98dae0cf170debd64ffc3812df4dab1fbd4a50

File: packages/transport/src/index.ts (hunk 15 above)
Comment (mroz22) [reply packages/transport/src/index.ts]: I am not sure yet myself. lets keep this topic open. It felt like a good idea to have a distict separation of layers from which these errors may originate

File: packages/transport/src/constants.ts (hunk 16 above)
Comment (mroz22) [reply packages/transport/src/constants.ts]: sure, no problem with that b3a8b0afa86b0426a7fdba05b99ef47aa2839b8d

File: packages/connect/src/events/transport.ts (hunk 6 above)
Comment (mroz22) [reply packages/connect/src/events/transport.ts]: yes, there is, I need to access TRANSPORTS for example on line 43 so I need to assign it to a local variable && I need to keep named export from this module as it is

File: packages/transport/src/transports/abstract.ts (hunk 17 above)
Comment (mroz22) [reply packages/transport/src/transports/abstract.ts]: Cool, actually my plan is to change it a bit in the end. Right now, public methods return either `success` or `error` or `unknownError`. The `unknownError` is useful for development - to find out about all the different errors that might appear. But it doesn't make that much sense to match error messages and either return `error` or `'unexpected error'` because for example these strings might differ based on platform. 
I am going to use simply `error` more often and return my own errors based on context where it is used. Example:

1. interface.write threw an error.
2. I caught it but I don't know what it is.
3. optional step I am thinking about this one. lets say the caught error.message was either "device disconnected" or "data transfer". I could use `unknownError` to try to guess and return one or another strongly typed error. 
4. But of course I know about context (I was about to write right), so if I return only strongly typed 'data-transfer-error' it should be probably enough.

File: packages/transport/src/transports/nodeusb.ts [hunk 18]
```diff
@@ -0,0 +1,40 @@
+import { WebUSB } from 'usb';
+
+import { Transport } from './abstract';
+import { UsbTransport } from './usb';
+import { SessionsClient } from '../sessions/client';
+import { SessionsBackground } from '../sessions/background';
+import { TransportUsbInterface } from '../interfaces/usb';
+
+// notes:
+// to make it work I needed to run `sudo chmod -R 777 /dev/bus/usb/`
```
Comment (karliatto) [inline packages/transport/src/transports/nodeusb.ts]: Interesting, that makes sense, since the browser can manage the permisions but without browser in a linux system the user has to grant access to usb port. This is not nice for user, since many users are not going to be happy to do that.

If this is This could be a VERY interesting point to use webusb from electron since I assume the permissions would be granted in a similar way as in the browser.

File: packages/transport/src/transports/nodeusb.browser.ts [hunk 19]
```diff
@@ -0,0 +1,10 @@
+import { WRONG_ENVIRONMENT } from './errors';
+
+export class NodeUsbTransport {
```
Comment (karliatto) [inline packages/transport/src/transports/nodeusb.browser.ts]: Shouldn't be the name of this `NodeUsbBrowserTransport` to be consisten with the file name and to avoid confusion with `nodeusb.ts`?

What is the purpose of this? Just to let the developer know it is being used in the wrong environment?

File: packages/transport/src/transports/abstract.ts [hunk 20]
```diff
@@ -0,0 +1,408 @@
...
+    messages: Record<string, any>;
+    signal?: AbortSignal;
+};
+
+export abstract class Transport extends TypedEmitter<{
+    [TRANSPORT.UPDATE]: DeviceDescriptorDiff;
+    // todo: transport error type better
+    [TRANSPORT.ERROR]: string;
+}> {
+    public name: 'BridgeTransport' | 'NodeUsbTransport' | 'WebUsbTransport' | 'AbstractTransport';
```
Comment (karliatto) [inline packages/transport/src/transports/abstract.ts]: Is 'AbstractTransport' a transport as well? Does it make sense to have it here listed?

File: packages/transport/src/transports/nodeusb.browser.ts (hunk 19 above)
Comment (karliatto) [reply packages/transport/src/transports/nodeusb.browser.ts]: OK, I got it know, it is just a way to display error when baddly used.

File: packages/transport/src/transports/nodeusb.ts (hunk 18 above)
Comment (mroz22) [reply packages/transport/src/transports/nodeusb.ts]: no browser, this is the nodejs part. we also can not really use webusb in render because we transport is part of connect and connect lives in the electron layer. I'dont think it is possible to use websub native api in electron, or is it? it must be only renderer.

File: packages/transport/src/transports/nodeusb.browser.ts (hunk 19 above)
Comment (mroz22) [reply packages/transport/src/transports/nodeusb.browser.ts]: Yes, this is just replacement for NodeUsbTransport class in browser environment.

File: packages/transport/src/transports/abstract.ts (hunk 20 above)
Comment (mroz22) [reply packages/transport/src/transports/abstract.ts]: good idea, lets get rid of it 499db778c179f5be2213dddec83d686f283d7ba7

File: packages/transport/src/index.ts (hunk 8 above)
Comment (mroz22) [reply packages/transport/src/index.ts]: need to think about it a bit, but probably it could be done

File: packages/transport/src/constants.ts (hunk 7 above)
Comment (mroz22) [reply packages/transport/src/constants.ts]: added couple of changes here a2e4f821f592b041e853390468543ceeff6c6b0c

File: packages/connect/src/core/index.ts (hunk 9 above)
Comment (mroz22) [reply packages/connect/src/core/index.ts]: 204934120cf210577dbb42af7c850eb686f4bd18

File: packages/transport/src/index.ts (hunk 8 above)
Comment (mroz22) [reply packages/transport/src/index.ts]: ok, makes sense 204934120cf210577dbb42af7c850eb686f4bd18

**Comment by karliatto** [comment]
@mroz22 I have being trying to debug why when I run this branch in my computer the app sometimes crashes and it is because of `LIBUSB_ERROR_ACCESS` error form node-usb it looks like a known [issue](https://github.com/node-usb/node-usb/issues/302) regarding permissions,  but I am curious why I was not having that issue before.

```
DEVICE.LIST init
-> [backend] handshake 0 payload  {"type":"handshake","caller":"FdY","id":0}
<- [backend]: with:  handshake 0   {"success":true} sessions:  {}
result from transport init in DeviceList { success: true, payload: undefined }
@trezor/transport enumerate!
-> [backend] enumerateIntent 1 payload  {"type":"enumerateIntent","caller":"FdY","id":1}
<- [backend]: with:  enumerateIntent 1   {"success":true,"payload":{"sessions":{}}} sessions:  {}
@trezor/transport enumerateIntentResult { success: true, payload: { sessions: {} }, id: 1 }
unexpected error:  initialize error: Error: LIBUSB_ERROR_ACCESS
@trezor/transport enumerateResult {
  success: false,
  error: 'unexpected error',
  message: 'initialize error: Error: LIBUSB_ERROR_ACCESS'
}
```

**Comment by mroz22** [comment]
>  I have being trying to debug why when I run this branch 

Cool, thanks for testing. Will think about it, but this could be probably left for "post mvp". In this PR nodeusb is still in debug menu so there will be space for debugging after this is merged. Now I'd focus mainly on possible regressions introduced during refactoring.

File: packages/connect/src/core/index.ts [hunk 21]
```diff
@@ -628,6 +635,7 @@ export const onCall = async (message: CoreMessage) => {
         // TODO: This requires a massive refactoring https://github.com/trezor/trezor-suite/issues/5323
         // @ts-expect-error TODO: messageResponse should be assigned from the response of "inner" function
         const response = messageResponse;
+        console.log('response core', response);
```
Comment (szymonlesisz) [inline packages/connect/src/core/index.ts]: console

File: packages/connect/src/workers/workers-react-native.ts [hunk 22]
```diff
@@ -1,19 +1,8 @@
...
-
-export {
-    WebUsbPlugin,
-    ReactNativeUsbPlugin,
-    BlockbookWorker,
-    RippleWorker,
-    BlockfrostWorker,
-    ElectrumWorker,
-};
+export { WebUsbPlugin, BlockbookWorker, RippleWorker, BlockfrostWorker, ElectrumWorker };
```
Comment (szymonlesisz) [inline packages/connect/src/workers/workers-react-native.ts]: what about ReactNativeUsbPlugin ?

File: packages/connect/src/types/settings.ts [hunk 23]
```diff
@@ -17,7 +17,7 @@ export interface ConnectSettings {
     popup?: boolean;
     transportReconnect?: boolean;
     webusb?: boolean; // deprecated
-    transports?: Transport['name'][];
+    transports?: Transport['name'][] | Transport[];
```
Comment (szymonlesisz) [inline packages/connect/src/types/settings.ts]: (Transport['name'] | Transport)[]

File: packages/connect/src/device/Device.ts [hunk 24]
```diff
@@ -151,39 +149,40 @@ export class Device extends EventEmitter {
...
-                throw error;
+                throw acquireResult.error;
             }
             this.runPromise = null;
+            return;
         }
+
+        const sessionID = acquireResult.payload;
+
+        console.log('device.acquire sessionId', sessionID);
```
Comment (szymonlesisz) [inline packages/connect/src/device/Device.ts]: console

File: packages/connect-web/src/iframe/index.ts [hunk 25]
```diff
@@ -91,7 +92,11 @@ export const init = async (settings: ConnectSettings) => {
     if (settings.webusb) {
         console.warn('webusb option is deprecated. use `transports: ["WebUsbTransport"] instead`');
     }
-    if (settings.webusb || settings.transports?.includes('WebUsbTransport')) {
+    if (
+        settings.webusb ||
+        (!isTransportInterface(settings.transports) &&
+            settings.transports?.includes('WebUsbTransport'))
```
Comment (szymonlesisz) [inline packages/connect-web/src/iframe/index.ts]: && navigator.usb (firefox)

File: packages/connect/src/core/index.ts [hunk 26]
```diff
@@ -617,8 +623,9 @@ export const onCall = async (message: CoreMessage) => {
             // thrown while acquiring device
             // it's a race condition between two tabs
             // workaround is to enumerate transport again and report changes to get a valid session number
-            if (_deviceList && error.message === ERRORS.WRONG_PREVIOUS_SESSION_ERROR_MESSAGE) {
-                _deviceList.enumerate();
+            if (_deviceList && error.message === TRANSPORT_ERROR.WRONG_PREVIOUS_SESSION) {
+                console.log('EDGECASE: deviceList.enumerate!');
```
Comment (szymonlesisz) [inline packages/connect/src/core/index.ts]: warn? error?

File: packages/transport/src/transports/nodeusb.ts [hunk 27]
```diff
@@ -0,0 +1,41 @@
...
+    public name = 'NodeUsbTransport' as const;
+
+    constructor({ messages }: ConstructorParameters<typeof Transport>[0]) {
+        const sessionsBackground = new SessionsBackground();
+
+        // in nodeusb there is no synchronization yet. this is a followup and needs to be decided
+        // so far, sessionsClient has direct access to sessionBackground
+        const sessionsClient = new SessionsClient({
+            // @ts-expect-error
+            requestFn: args => sessionsBackground.handleMessage(args),
```
Comment (szymonlesisz) [inline packages/transport/src/transports/nodeusb.ts]:
```suggestion
            requestFn: sessionsBackground.handleMessage.bind(sessionsBackground),
```

File: suite-common/connect-init/src/connectInitThunks.ts [hunk 28]
```diff
@@ -85,6 +89,8 @@ export const connectInitThunk = createThunk(
             await TrezorConnect.init({
                 ...connectInitSettings,
                 pendingTransportEvent: selectIsPendingTransportEvent(getState()),
+                transports: selectDebugSettings(getState()).transports,
+                debug: true,
```
Comment (szymonlesisz) [inline suite-common/connect-init/src/connectInitThunks.ts]: debug

File: packages/transport/package.json [hunk 29]
```diff
@@ -39,20 +45,23 @@
...
     },
     "dependencies": {
         "@trezor/utils": "workspace:^9.0.6",
         "bytebuffer": "^5.0.1",
         "json-stable-stringify": "^1.0.2",
         "long": "^4.0.0",
         "prettier": "2.8.4",
-        "protobufjs": "^6.11.3"
+        "protobufjs": "^6.11.3",
+        "usb": "^2.5.2"
```
Comment (szymonlesisz) [inline packages/transport/package.json]: require shell.nix buildInputs `udev`, nodeusb transport throws LIBUSB_ERROR_ACCESS

File: packages/transport/src/transports/bridge.ts [hunk 30]
```diff
@@ -0,0 +1,341 @@
...
+        if (this.acquirePromise?.promise) {
+            await this.acquirePromise.promise;
+        }
+
+        this.handleDescriptorsChange(response.payload);
+        return this._listen();
+    }
+
+    // https://github.dev/trezor/trezord-go/blob/f559ee5079679aeb5f897c65318d3310f78223ca/core/core.go#L235
+    public async enumerate() {
```
Comment (szymonlesisz) [inline packages/transport/src/transports/bridge.ts]:
```suggestion
    public enumerate() {
```

File: packages/transport/src/transports/bridge.ts [hunk 31]
```diff
@@ -0,0 +1,341 @@
...
+             * emitting transport.start event in time and suite rendering
+             * "loading takes too long" error screen.
+             */
+        }, 5000);
+
+        const response = await bridgeApiCall({
+            ...restOptions,
+            signal: abortable ? this.abortController.signal : undefined,
+            method: 'POST',
+            url: `${this.url + endpoint}${options?.params ? `/${options.params}` : ''}`,
```
Comment (szymonlesisz) [inline packages/transport/src/transports/bridge.ts:365]: use fetch `timeout` option instead of `requestTimeout`

File: packages/transport/src/transports/usb.ts [hunk 32]
```diff
@@ -0,0 +1,353 @@
...
+        this.sessionsClient.on('descriptors', descriptors => {
+            // 4. we propagate new descriptors to higher levels
+            this.handleDescriptorsChange(descriptors);
+        });
+
+        return this.success(undefined);
+    }
+
+    public enumerate() {
+        return new AbortablePromise<
```
Comment (szymonlesisz) [inline packages/transport/src/transports/usb.ts]: use scheduledAction

File: packages/connect/src/events/transport.ts (hunk 1 above)
Comment (mroz22) [reply packages/connect/src/events/transport.ts]: I need to have access to TRANSPORT in this file to be able to contruct derived types below
such as
```
export interface TransportDisableWebUSB {
    type: typeof TRANSPORT.DISABLE_WEBUSB;
    payload?: undefined;
}

```

File: packages/transport/src/transports/nodeusb.ts (hunk 27 above)
Comment (mroz22) [reply packages/transport/src/transports/nodeusb.ts]: moved to #7820

File: packages/connect-web/src/iframe/index.ts (hunk 25 above)
Comment (mroz22) [reply packages/connect-web/src/iframe/index.ts]: just thinking. would something happen if we changed it here like this?
```
if (navigator.usb ) {
        instance.setAttribute('allow', 'usb');
    }
```
simply ignore settings and set this attributed always? whether webusb transport should be used is controled elsewhere anyway.

File: packages/connect/src/types/settings.ts (hunk 23 above)
Comment (mroz22) [reply packages/connect/src/types/settings.ts]: 071a485e4b140dfb10612d9e528087e819cc16fc

File: packages/connect/src/device/Device.ts (hunk 24 above)
Comment (mroz22) [reply packages/connect/src/device/Device.ts]: 071a485e4b140dfb10612d9e528087e819cc16fc

File: packages/connect-web/src/iframe/index.ts (hunk 25 above)
Comment (mroz22) [reply packages/connect-web/src/iframe/index.ts]: experimentaly changed here too 071a485e4b140dfb10612d9e528087e819cc16fc

File: packages/connect/src/core/index.ts (hunk 21 above)
Comment (mroz22) [reply packages/connect/src/core/index.ts]: 071a485e4b140dfb10612d9e528087e819cc16fc

File: packages/connect/src/core/index.ts (hunk 26 above)
Comment (mroz22) [reply packages/connect/src/core/index.ts]: https://github.com/trezor/trezor-suite/commit/071a485e4b140dfb10612d9e528087e819cc16fc

File: packages/connect/src/workers/workers-react-native.ts (hunk 22 above)
Comment (mroz22) [reply packages/connect/src/workers/workers-react-native.ts]: `ReactNativeUsbPlugin` is not expected to be baked into @trezor/connect. For mobile, their transport interface should be passed in TrezorConnect.init({ transports: [ my custom transport that satisfies abstract transport] }). I suggest that we implement it once this is in develop or in another branch based on this branch. cc @Nodonisko 

I also suggest completely removing `WebUsbPlugin` plugin from here, it is not used anywhere.

File: suite-common/connect-init/src/connectInitThunks.ts (hunk 28 above)
Comment (mroz22) [reply suite-common/connect-init/src/connectInitThunks.ts]: eaaff77fb2d9cb564b665f1f3d037d98ee3739c9

File: packages/transport/src/transports/bridge.ts (hunk 30 above)
Comment (mroz22) [reply packages/transport/src/transports/bridge.ts]: b18599a494870c84b7a6733fc8505b343bbd8347

File: packages/transport/src/transports/bridge.ts (hunk 31 above)
Comment (mroz22) [reply packages/transport/src/transports/bridge.ts:365]: b18599a494870c84b7a6733fc8505b343bbd8347 but lets keep this open, I need to test if it really works

File: packages/transport/package.json (hunk 29 above)
Comment (mroz22) [reply packages/transport/package.json]: please :pray: push it here if you know how to

**Comment by mroz22** [comment]
reacted to most of @szymonlesisz comments and created some separated PR's

#7821 - debug menu related changes, should not depend on this PR, can be based on develop directly
#7820 - adding nodeusb transport, depends on this PR 

this PR requires rebasing but I don't want to change commit hashes in comments now

File: packages/transport/src/transports/nodeusb.browser.ts (hunk 19 above)
Comment (mroz22) [reply packages/transport/src/transports/nodeusb.browser.ts]: nodeusb moved to another PR

File: packages/transport/src/transports/nodeusb.ts (hunk 18 above)
Comment (mroz22) [reply packages/transport/src/transports/nodeusb.ts]: nodeusb moved to another PR

File: packages/transport/src/transports/usb.ts (hunk 32 above)
Comment (mroz22) [reply packages/transport/src/transports/usb.ts]: 1dc9a648900cc6d6d102206286a90887f8fe85ce and a0022aa33f924d6d574ac28ddb91a31738ab578a

File: packages/transport/package.json (hunk 29 above)
Comment (mroz22) [reply packages/transport/package.json]: actually we can move here https://github.com/trezor/trezor-suite/pull/7820 with this

File: packages/connect/src/core/index.ts (hunk 26 above)
Comment (mroz22) [reply packages/connect/src/core/index.ts]: logger debug

File: packages/connect/src/types/settings.ts [hunk 33]
```diff
@@ -17,7 +17,7 @@ export interface ConnectSettings {
     popup?: boolean;
     transportReconnect?: boolean;
     webusb?: boolean; // deprecated
-    transports?: Transport['name'][];
+    transports?: (Transport['name'] | Transport)[];
```
Comment (marekrjpolak) [inline packages/connect/src/types/settings.ts:21]: Dunno, this seems a bit strange. Why is there a reason to pass either strings or instances?

File: packages/connect/src/device/DeviceList.ts [hunk 34]
```diff
@@ -66,99 +55,268 @@ export interface DeviceList {
...
+                    default:
+                        throw ERRORS.TypedError(
+                            'Runtime',
+                            `DeviceList.init: transports[] of unexpected type: ${transportType}`,
+                        );
+                    // not implemented
+                    // case 'UdpTransport':
+                }
+            } else if (transportType instanceof Transport) {
+                this.transports.unshift(transportType);
```
Comment (marekrjpolak) [inline packages/connect/src/device/DeviceList.ts:108]: This should somehow prefer already instantiated transports before their names?

File: packages/connect/src/device/Device.ts [hunk 35]
```diff
@@ -508,82 +503,9 @@ export class Device extends EventEmitter {
         return this.features === undefined;
     }
 
-    async updateDescriptor(upcomingDescriptor: DeviceDescriptor) {
```
Comment (marekrjpolak) [inline packages/connect/src/device/Device.ts:513]: Why isn't `updateDescriptor` necessary anymore?

File: packages/transport/src/types/typed-emitter.ts [hunk 36]
```diff
@@ -0,0 +1,26 @@
...
+    }
+
+    off<K extends EventKey<T>>(eventName: K, fn: EventReceiver<T[K]>) {
+        this.emitter.off(eventName, fn);
+    }
+
+    emit<K extends EventKey<T>>(eventName: K, params: T[K]) {
+        this.emitter.emit(eventName, params);
+    }
+}
```
Comment (marekrjpolak) [inline packages/transport/src/types/typed-emitter.ts]: Is there a reason why the real emitter should be nested, or could it be simplified like this?
```suggestion
export interface TypedEmitter<T extends EventMap> {
    on<K extends EventKey<T>>(eventName: K, fn: EventReceiver<T[K]>): this;
    off<K extends EventKey<T>>(eventName: K, fn: EventReceiver<T[K]>): this;
    emit<K extends EventKey<T>>(eventName: K, params: T[K]): boolean;
}

export class TypedEmitter<T extends EventMap> extends EventEmitter {}
```

File: packages/transport/src/transports/abstract.ts [hunk 37]
```diff
@@ -0,0 +1,449 @@
...
+        const releasedByMyself = released.filter(
+            d =>
+                this.descriptors.find(prevD => prevD.path === d.path)?.session ===
+                this.releasingSession,
+        );
+        const releasedElsewhere = released.filter(
+            d =>
+                this.descriptors.find(prevD => prevD.path === d.path)?.session !==
+                this.releasingSession,
+        );
```
Comment (marekrjpolak) [inline packages/transport/src/transports/abstract.ts]: Nit: for cases like this `arrayPartition` from `@trezor/utils` can be used.

File: packages/transport/src/transports/bridge.ts [hunk 38]
```diff
@@ -0,0 +1,436 @@
...
+
+        if (!response.success) {
+            const time = new Date().getTime() - listenTimestamp;
+            if (time > 1100) {
+                await createTimeoutPromise(1000);
+                return this._listen();
+            }
+            this.emit('transport-error', response.error);
+            return;
+        }
```
Comment (marekrjpolak) [inline packages/transport/src/transports/bridge.ts:127]: This means that I care about errors only when they were returned under 1100 ms?

File: packages/transport/src/sessions/background.ts [hunk 39]
```diff
@@ -0,0 +1,318 @@
...
+            error = payload.previous !== previous;
+        }
+
+        if (payload.previous == null) {
+            error = false;
+        }
+
+        if (error) {
+            return this.error(ERRORS.SESSION_WRONG_PREVIOUS);
+        }
```
Comment (marekrjpolak) [inline packages/transport/src/sessions/background.ts]: Is this equivalent?
```suggestion
        const previous = this.sessions[payload.path];

        if (payload.previous && payload.previous !== previous) {
            return this.error(ERRORS.SESSION_WRONG_PREVIOUS);
        }
```

File: packages/transport/src/transports/abstract.ts (hunk 37 above)
Comment (marekrjpolak) [reply packages/transport/src/transports/abstract.ts]: > Nit: for cases like this arrayPartition from @trezor/utils can be used.

He is right.

**Review by marekrjpolak — APPROVED** [review]
:cold_sweat:
