### PR TITLE
Desktop Titlebar - Fixes and improvements (functionality and style)

### LINKED ISSUE #2754: App can't be closed on Linux
**Info:**
 - OS: NixOS
 - Browser: desktop
 - Wallet Version: 34e505ec96de077e9064e76ac4e835e62d53a338
 
**Describe the bug**
You click on the "cross" icon but nothing happens.

**Steps to reproduce:**
1. Try to close the app

---

Probably introduced by the custom title bar. Most likely will be fixed by https://github.com/trezor/trezor-suite/pull/2733.

### PR DESCRIPTION
**Pull request by keraf**
This change addresses the following issues:
- Buttons were not clickable (drag area was overlaying them).
- Maximize/Unmaximize state was properly set.
- Maximize/Unmaximize is now setting the window to fullscreen on Mac (as it's commonly done on this platform).

Also includes visual changes:
- Reduced height of the title bar from 40px to 28px.
- Win/Linux buttons get highlighted on hover and have a background (grey for all buttons except close which has a red background).
- Icons in Mac buttons get displayed on hover (mimic native system behaviour).
- Increased icon size for Mac.

Future improvements (not part of this PR):
- Mac specific icons for maximize/unmaximize buttons.

**Current**
Win/Linux
Mac

**New**
Win/Linux
Mac

### CODE REVIEW

File: packages/suite-desktop/src-electron/electron.ts [hunk 1]
```diff
@@ -208,10 +208,10 @@ const init = async () => {
     ipcMain.on('client/ready', () => {
         notifyWindowMaximized(mainWindow);
     });
-    mainWindow.on('resize', () => {
+    mainWindow.on('maximize', () => {
```
Comment (tomexx) [inline packages/suite-desktop/src-electron/electron.ts:222]: `resize` and `move` events were used to handle situations such as moving or resizing window after maximization (they are also triggered when maximizing and unmaximizing) (Mac only issue I guess)

File: packages/suite-desktop/src/support/DesktopTitlebar.tsx [hunk 2]
```diff
@@ -1,10 +1,10 @@
-import React, { useEffect, useState } from 'react';
+import React, { useEffect, useState, useCallback } from 'react';
 import styled from 'styled-components';
 import NoSSR from '@suite-support/NoSSR';
 import { colors, TrezorLogo, Icon } from '@trezor/components';
 import { isMac as isMacOS } from '@suite-utils/env';
 
-const TITLEBAR_HEIGHT = 40;
+const TITLEBAR_HEIGHT = 28;
```
Comment (tomexx) [inline packages/suite-desktop/src/support/DesktopTitlebar.tsx:7]: this should be consulted with @matejzak, the original size matches the design, also applies for the size of Mac controls

File: packages/suite-desktop/src/support/DesktopTitlebar.tsx [hunk 3]
```diff
@@ -86,46 +97,96 @@ const LogoWrapper = styled.div`
...
-                <ActionClose isMac={isMac} onClick={close}>
-                    <Icon color={iconColor} size={iconSize} icon="WINDOW_CLOSE" />
+                <ActionClose
+                    isMac={isMac}
+                    onClick={() => window.desktopApi!.windowClose()}
+                    data-button="close"
+                    onMouseEnter={mouseEnter}
+                    onMouseLeave={mouseLeave}
+                >
+                    {(!isMac || hover !== '') && (
```
Comment (tomexx) [inline packages/suite-desktop/src/support/DesktopTitlebar.tsx]: maybe let's create a helper for this as it is used more times

File: packages/suite-desktop/src/support/DesktopTitlebar.tsx [hunk 4]
```diff
@@ -86,46 +97,96 @@ const LogoWrapper = styled.div`
...
+                        <Icon
+                            color={!isMac && hover === 'close' ? colors.WHITE : iconColor}
```
Comment (tomexx) [inline packages/suite-desktop/src/support/DesktopTitlebar.tsx]: let's also create a parametric helper for this

**Review by tomexx — CHANGES_REQUESTED** [review]
some cosmetics, otherwise I like it 👍

File: packages/suite-desktop/src/support/DesktopTitlebar.tsx (hunk 4 above)
Comment (keraf) [reply packages/suite-desktop/src/support/DesktopTitlebar.tsx]: Addressed in 4ae6b40

File: packages/suite-desktop/src/support/DesktopTitlebar.tsx (hunk 3 above)
Comment (keraf) [reply packages/suite-desktop/src/support/DesktopTitlebar.tsx]: Addressed in 4ae6b40

File: packages/suite-desktop/src-electron/electron.ts (hunk 1 above)
Comment (keraf) [reply packages/suite-desktop/src-electron/electron.ts:222]: Addressed in 4ae6b40

Comment (keraf) [reply packages/suite-desktop/src-electron/electron.ts:222]: I used the `moved` event instead. It should always be fired once after the window gets moved or resized on Mac.

Comment (tomexx) [reply packages/suite-desktop/src-electron/electron.ts:222]: Resize is still needed :(

It handles the case when you maximize and then resize the screen. Currently after you maximize and then resize the screen the restore button stays in "restore" mode and does nothing when you click on it (on Mac).

**Review by tomexx — CHANGES_REQUESTED** [review]

File: packages/suite-desktop/src/support/DesktopTitlebar.tsx (hunk 2 above)
Comment (glacierbits) [reply packages/suite-desktop/src/support/DesktopTitlebar.tsx:7]: Thank you guys! The change is OK with me. We will enlarge the bar again, once search is included.. 🔜  🙏🏽 ☺️

**Review by tomexx — APPROVED** [review]

**Comment by tsusanka** [comment]
Squashed on Raf's behalf and merged.

**Comment by tsusanka** [comment]
Cherry-picked to `release/2020-10-beta`.
