### PR TITLE
fix(suite): can't change device name from onboarding

### LINKED ISSUE #14981: Onboarding: Rename wallet step improvements
At the end of the onboarding, when renaming the device:

- After entering the edit mode (by clicking the [Edit name] button),
     - Rename the [Edit name] button to [Save name]
     - Instead of the default name being a placeholder, please make it pre-filled input content and all of it selected and in focus
          - That means when user starts typing right away, the content will be replaced by theirs
          - If they click into the content or use arrow keys, they will be able to edit the content
     - **Save the new name even when clicking the [Access Suite –>] button**
     - Add 'esc' keyboard button functionality to close the input without saving

Please mind feasibility. If it would be effort-heavy, let's at least do the bold one ☝️ and discuss the rest.

Current implementation:
Image

### PR DESCRIPTION
**Pull request by viktordanko**
## Description

Improves changing of the name of the device while onboarding.

- whenever user click on `Access suite` button, current name is saved
- add option to exit rename mode, when pressing `Esc` key

## Related Issue

Resolves:  #14981 

## Screenshots:
onboarding

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/Final.tsx [hunk 1]
```diff
@@ -120,16 +124,55 @@ export const FinalStep = () => {
...
+
+        try {
+            await onSubmit();
+            goToSuite();
+        } catch (error) {
+            console.error(error);
+            dispatch(
+                notificationsActions.addToast({
+                    type: 'error',
+                    // TODO: replace with `translationString('TR_DEVICE_SETTINGS_DEVICE_EDIT_LABEL_ERROR')`,
```
Comment (viktordanko) [inline packages/suite/src/views/onboarding/steps/Final.tsx]: What's the workflow for generating new messages for `L10N`, pls?
cc @komret

File: packages/suite/src/hooks/suite/useChangeDeviceLabel.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+export const useChangeDeviceLabel = () => {
+    const { translationString } = useTranslation();
+    const deviceLabel = useSelector(selectDeviceLabel);
+    const deviceName = useSelector(selectDeviceName);
+    const dispatch = useDispatch();
+
+    const form = useForm({
+        resolver: yupResolver(changeDeviceLabelSchema(translationString)),
+        defaultValues: {
+            deviceLabel: deviceLabel ?? deviceName,
```
Comment (viktordanko) [inline packages/suite/src/hooks/suite/useChangeDeviceLabel.ts]: This was a bit confusing to me, since I'm missing the context.
I assume `label !== name`, but don't know what has higher prio

File: packages/suite/src/views/onboarding/steps/Final.tsx [hunk 3]
```diff
@@ -197,29 +240,19 @@ export const FinalStep = () => {
                     )}
                     {state === 'rename' && (
                         <SetupActions>
-                            <ChangeDeviceLabel onClick={onClick} isDeviceLocked={isDeviceLocked} />
+                            <FormProvider {...form}>
+                                <ChangeDeviceLabelForm
+                                    isDeviceLocked={isDeviceLocked}
+                                    onClick={handleClick}
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/Final.tsx]: This takes me to Suite settings after I click "Change name", but I would expect to stay on the Final screen so that I can set homescreen.

**Review by komret — COMMENTED** [review]
Thanks for the contribution! Can you please separate the changes into more commits, one commit per feature? The ESC functionality is undoubtedly a nice improvement, removing the placeholder is OK, but I am not so keen on changing the device name after clicking the "Go to Suite" button as it requires confirmation on Trezor. Unfortunately, the issue is quite old and I am not sure as to its validity. Personally, I'd rather remove this whole screen from onboarding. @Hermez-cz, WDYT?

File: packages/suite/src/hooks/suite/useChangeDeviceLabel.ts (hunk 2 above)
Comment (komret) [reply packages/suite/src/hooks/suite/useChangeDeviceLabel.ts]: This is correct. Label is set by user, while name is defined by the device. Perhapst you can use `selectSelectedDeviceLabelOrName` selector here.

File: packages/suite/src/views/onboarding/steps/Final.tsx (hunk 1 above)
Comment (komret) [reply packages/suite/src/views/onboarding/steps/Final.tsx]: A new message should be added to `messages.ts`. But I wouldn't handle errors here, we never had an issue here, probably not worth adding new translation strings.

File: packages/suite/src/hooks/suite/useChangeDeviceLabel.ts
Comment (Lemonexe) [inline packages/suite/src/hooks/suite/useChangeDeviceLabel.ts:1]: Very nice that you've rewritten this form to `react-hook-form`, incl. `yup` instead of homecooked validation, so there will be better codestyle consistency with other forms :tada:

File: packages/suite/src/views/onboarding/steps/Final.tsx [hunk 4]
```diff
@@ -120,16 +124,55 @@ export const FinalStep = () => {
...
+        };
+        delete payload.startTime;
+
+        analytics.report({
+            type: EventType.DeviceSetupCompleted,
+            payload,
+        });
+
+        try {
+            await onSubmit();
```
Comment (Lemonexe) [inline packages/suite/src/views/onboarding/steps/Final.tsx]: this works well when changing a name, but needs to be conditionally called only if formstate.value is different from initial value. Now the device prompts me to change name from Hello to Hello even when I don't interact with the form: 
[Screencast from 2025-05-14 15-32-37.webm](https://github.com/user-attachments/assets/f8ce20c8-4a0d-4aff-9e40-988e5898500e)

File: packages/suite/src/views/onboarding/steps/Final.tsx (hunk 1 above)
Comment (Lemonexe) [reply packages/suite/src/views/onboarding/steps/Final.tsx]: In any case, the error while changing name effectively blocks you from proceeding to Suite.

File: packages/suite/src/views/onboarding/steps/Final.tsx (hunk 3 above)
Comment (Lemonexe) [reply packages/suite/src/views/onboarding/steps/Final.tsx]: Yes, the function would be best split into two.
`ChangeDeviceLabelForm onClick`: submit form, catch error to display notification (but don't go to Suite) 
`EnterSuiteButton onClick`: do this :arrow_up: if values have changed, and go to Suite regardless of success.

File: packages/suite/src/hooks/suite/useChangeDeviceLabel.ts [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+        deviceLabel: yup
+            .string()
+            .max(
+                MAX_LABEL_LENGTH,
+                t('TR_LABEL_ERROR_LENGTH', {
+                    length: MAX_LABEL_LENGTH,
+                }),
+            )
+            .test({
+                test: value => isAscii(value),
```
Comment (Lemonexe) [inline packages/suite/src/hooks/suite/useChangeDeviceLabel.ts]: small nit to simplify:
```suggestion
                test: isAscii,
```

File: packages/suite/src/views/settings/SettingsDevice/DeviceLabel.tsx [hunk 6]
```diff
@@ -1,23 +1,40 @@
...
     isDeviceLocked: boolean;
-}
+};
+
+export const DeviceLabel = ({ isDeviceLocked }: DeviceLabelProps) => {
+    const { form, onSubmit } = useChangeDeviceLabel();
+
+    const handleClick = async () => {
+        await onSubmit();
+    };
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDevice/DeviceLabel.tsx]: I believe you can delete this and pass `onSubmit` directly to `ChangeDeviceLabelForm`, right?

**Review by Lemonexe — COMMENTED** [review]
Thank you for your contribution :raised_hands: 
Overall very nice work, the user flow specified by issue is works well :heavy_check_mark: 

But in order for this PR to be mergable, other user flows should be fixed, particularly [this](https://github.com/trezor/trezor-suite/pull/18814#discussion_r2084545728) and [this](https://github.com/trezor/trezor-suite/pull/18814#discussion_r2088964300) comments.

**Comment by Lemonexe** [comment]
Oh and @Hermez-cz confirmed that the issue is indeed relevant.
FWIW to me it definitely makes sense, as I've found this very confusing in past when I first interacted with it.

File: packages/suite/src/hooks/suite/useChangeDeviceLabel.ts (hunk 2 above)
Comment (viktordanko) [reply packages/suite/src/hooks/suite/useChangeDeviceLabel.ts]: Nice, that should do the trick. Thanks 🙏

File: packages/suite/src/views/onboarding/steps/Final.tsx (hunk 4 above)
Comment (viktordanko) [reply packages/suite/src/views/onboarding/steps/Final.tsx]: Good catch, thanks!

File: packages/suite/src/views/onboarding/steps/Final.tsx (hunk 1 above)
Comment (viktordanko) [reply packages/suite/src/views/onboarding/steps/Final.tsx]: Okay, np. Gonna remove it

File: packages/suite/src/views/onboarding/steps/Final.tsx (hunk 3 above)
Comment (viktordanko) [reply packages/suite/src/views/onboarding/steps/Final.tsx]: That's right, thx!

File: packages/suite/src/views/settings/SettingsDevice/DeviceLabel.tsx (hunk 6 above)
Comment (viktordanko) [reply packages/suite/src/views/settings/SettingsDevice/DeviceLabel.tsx]: Absolutely :]

**Comment by viktordanko** [comment]
Thanks for your valid inputs 🙇 
I overlooked the conditional submitting of the form at first. Now, it should be all fine.
Here's separate PR for resetting the state when pressing `Esc` button - https://github.com/trezor/trezor-suite/pull/18954

**Review by Lemonexe — APPROVED** [review]
Perfect, all user flows now work correctly, LGTM :rocket: 
I'm gonna force push to resolve conflicts with `develop` and also because merge commits are not allowed in the repo.

Like with the other PRs, I'm gonna run CI checks in another PR #18968 and then merge this one.

EDIT: CI passed except for tests temporarily confirmed broken ([slack](https://satoshilabs.slack.com/archives/CKYFBT2C9/p1747318218774009))

**Comment by bosomt** [comment]
**QA OK**

- escape cancels edit
- after i change name and select go to TS im asked to change device name upon entering to TS

**Info:**
 - Suite version: web 25.6.0 (3a8214d7953b03f3648e9bf592d1ce7b16e8cd99)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3T1 2.8.8 regular (revision bbcb920213b0ab847a2fedf825eac70652e33279)
 - Transport: WebUsbTransport

**Comment by tomasklim** [comment]
@bosomt renamed `Change name` to `Save name` in crowdin

@viktordanko you can edit `messages.ts` and `en.json` next time just to have it correct in the screenshot without syncing crowdin
