### PR TITLE
Fix/axis label

### LINKED ISSUE #7910: Graph axis label horizontal overflow
If the axis label of a graph is too long, it horizontally overflows. A check that controls the length of the label text and adjusts its position accordingly needs to be introduced. 

Image

### PR DESCRIPTION
**Pull request by juriczech**
## Description
Offset highest value from range by percentage of elements width (divided by 2 as the whole width shift is not necessary IMO)

## Related Issue

Resolve #7910 [Graph axis label horizontal overflow](https://github.com/trezor/trezor-suite/issues/7910)

## Screenshots:
image

### CODE REVIEW

File: suite-native/graph/src/components/Graph.tsx [hunk 1]
```diff
@@ -86,11 +88,14 @@ export const Graph = <TGraphPoint extends EnhancedGraphPoint>({
...
         if (extremaFromGraphPoints?.max && extremaFromGraphPoints?.min) {
+            const topAxisClampedAxis = clampAxisLabels(extremaFromGraphPoints.max.x);
+
             return {
                 TopAxisLabel: () => (
                     <AxisLabel
-                        x={clampAxisLabels(extremaFromGraphPoints.max.x)}
+                        x={topAxisClampedAxis}
                         value={extremaFromGraphPoints.max.value}
+                        isEndOfRange={topAxisClampedAxis === MAX_CLAMP_VALUE}
```
Comment (Nodonisko) [inline suite-native/graph/src/components/Graph.tsx]: You probably don't need to pass this as prop. If you move `const MAX_CLAMP_VALUE` to AxisLabel you can do check here.

**Review by Nodonisko — APPROVED** [review]

**Review by PeKne — APPROVED** [review]

File: suite-native/graph/src/components/Graph.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/graph/src/components/Graph.tsx]: Good point. Fixed here
https://github.com/trezor/trezor-suite/pull/8077/commits/21eadf02da2a05f096d9325ebff489b007b40212
