### PR TITLE
Fix/font accessibility

### LINKED ISSUE #10562: enlarged fonts check
Adjust the newly implemented UI (connect trezor and receive features) so it works with font enlarging accessibility settings builtin both Android and iOS.

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- iOS Text atom uses standard `react-native/Text` component to enable accessibility font enlarging
- minor UI glitches fixed in Android Onboarding flow

## Related Issue

Resolve #10562

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/3d1dd6b2-469e-42bc-9c5c-8a38ec0ceb10

### CODE REVIEW

**Comment by PeKne** [comment]
Trezor Suite Lite Header alignment fixed in fixup 2475f9bace. See the screenshot attached: 
Screenshot 2024-01-09 at 13 55 07

File: suite-native/atoms/src/TrezorSuiteLiteHeader.tsx [hunk 1]
```diff
@@ -1,30 +1,36 @@
...
-                    </Text>
-                ),
-            }}
-        />
-    </Text>
-);
+}: TrezorSuiteLiteHeaderProps) => {
+    const { applyStyle } = useNativeStyles();
+    return (
+        <Text variant={textVariant} color="textSecondaryHighlight" style={applyStyle(headerStyle)}>
```
Comment (juriczech) [inline suite-native/atoms/src/TrezorSuiteLiteHeader.tsx]: You can use `textAlign="center"` prop

File: suite-native/module-onboarding/src/screens/WelcomeScreen.tsx [hunk 2]
```diff
@@ -91,15 +91,15 @@ export const WelcomeScreen = () => {
...
+            <Screen backgroundColor="transparent">
                 <LinearGradient
                     style={applyStyle(cardStyle)}
                     colors={[
                         utils.colors.gradientNeutralBottomFadeSurfaceElevation1Start,
                         utils.colors.gradientNeutralBottomFadeSurfaceElevation1End,
                     ]}
                 >
-                    <Box flex={0.7} />
+                    <Box flex={1.2} />
```
Comment (juriczech) [inline suite-native/module-onboarding/src/screens/WelcomeScreen.tsx]: Can you please add comment why this is needed? Seems obscure without explanation.

File: suite-native/atoms/src/TrezorSuiteLiteHeader.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/atoms/src/TrezorSuiteLiteHeader.tsx]: fixed 37b7698db1

File: suite-native/module-onboarding/src/screens/WelcomeScreen.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/module-onboarding/src/screens/WelcomeScreen.tsx]: fixed 37b7698db1

**Review by juriczech — APPROVED** [review]

**Review by Nodonisko — APPROVED** [review]
