### PR TITLE
fix(suite): destructuring error

### LINKED ISSUE #8973: TypeError: Cannot destructure property 'prices' of '(intermediate value)' as it is undefined.
Probably related to https://github.com/trezor/trezor-suite/pull/8642

Sentry Issue: [TREZOR-SUITE-TKG](https://satoshilabs.sentry.io/issues/4329625172/?referrer=github_integration)

```
TypeError: Cannot destructure property 'prices' of '(intermediate value)' as it is undefined.
  at DE (/js/main.9bc5c8c1.js:1:343529)
  at None (/js/main.9bc5c8c1.js:1:347732)
```

### PR DESCRIPTION
**Pull request by AdamSchinzel**
Destructuring of response was failing because it could be undefined

## Description

Moved destructuring after response validation.

## Related Issue

Resolve #8973

### CODE REVIEW

File: suite-common/fiat-services/src/coingecko.ts [hunk 1]
```diff
@@ -154,9 +154,12 @@ export const getFiatRatesForTimestamps = async (
...
 
     // returns pairs of [timestamp, fiatRate]
-    const { prices }: { prices: Array<[number, number]> } = await fetchCoinGecko(url);
+    const response = await fetchCoinGecko(url);
+    if (!response || !response.prices || response.prices.length === 0) {
+        return null;
+    }
 
-    if (!prices || prices.length === 0) return null;
+    const { prices }: { prices: Array<[number, number]> } = response;
```
Comment (dahaca) [inline suite-common/fiat-services/src/coingecko.ts]: nit: move the type to `fetchCoinGecko()`

File: suite-common/fiat-services/src/coingecko.ts [hunk 2]
```diff
@@ -154,9 +154,12 @@ export const getFiatRatesForTimestamps = async (
     const url = `${coinUrl}/${urlEndpoint}${params}`;
 
     // returns pairs of [timestamp, fiatRate]
-    const { prices }: { prices: Array<[number, number]> } = await fetchCoinGecko(url);
+    const response = await fetchCoinGecko(url);
+    if (!response || !response.prices || response.prices.length === 0) {
```
Comment (dahaca) [inline suite-common/fiat-services/src/coingecko.ts]:
```suggestion
    if (!response?.prices || response?.prices.length === 0) {
```

File: suite-common/fiat-services/src/coingecko.ts (hunk 1 above)
Comment (dahaca) [reply suite-common/fiat-services/src/coingecko.ts]: and there's no need to restructure at this point, just do `findClosestTimestampValue(ts, rates.prices)` :DD

File: suite-common/fiat-services/src/coingecko.ts (hunk 2 above)
Comment (AdamSchinzel) [reply suite-common/fiat-services/src/coingecko.ts]: bbc05a105ca2900a481c640ebf479a5366a66691

File: suite-common/fiat-services/src/coingecko.ts (hunk 1 above)
Comment (AdamSchinzel) [reply suite-common/fiat-services/src/coingecko.ts]: bbc05a105ca2900a481c640ebf479a5366a66691 - removed the type since the API is returning results based on parameters and we are using just few (imo not really needed + `fetchLastWeekRates` is also not typed)

**Review by dahaca — APPROVED** [review]

**Comment by AdamSchinzel** [comment]
After discussion with @marekrjpolak I'm also adding here a fix related to recent change in casing in Coinjoin so tests will pass
