### PR TITLE
fix(suite-common): add check for bitcoin-only firmware type

### LINKED ISSUE #10612: Solana enabled when using older bitcoin only firmware
**Describe the bug**
Solana enabled when using older bitcoin only firmware.
As soon you install new one Solana is not displayed anymore

**Steps to reproduce:**
1. Connect device with 2.6.3 bitcoin only firmware
2. observe settings/coins section

**Info:**
 - Suite version: desktop 24.1.1 (66325e1a9834a4e8f59eea9bb893bda13ca4470d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.6.4 bitcoin-only (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

_2.6.4_
Screenshot 2024-01-11 at 11 27 35
Screenshot 2024-01-11 at 11 27 32

_2.6.3_
Screenshot 2024-01-11 at 11 25 47
Screenshot 2024-01-11 at 11 25 42

### PR DESCRIPTION
**Pull request by enjojoy**
## Description

Before, if the coin is not supported on this firmware version, it would be shown there with a CTA to update firmware, even if it was Bitcoin-only firmware. 

Added a check for non-bitcoin networks if the firmware is bitcoin only.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10612

## Screenshots:
image

### CODE REVIEW

File: suite-common/wallet-core/src/device/deviceReducer.ts [hunk 1]
```diff
@@ -773,6 +773,13 @@ export const selectDeviceSupportedNetworks = (state: DeviceRootState) => {
                 return false;
             }
 
+            if (
+                device?.firmwareType === 'bitcoin-only' &&
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/device/deviceReducer.ts]: Nit: you can use [hasBitcoinOnlyFirmware](https://github.com/trezor/trezor-suite/blob/bef8f3c4378237d4cf63580d4ab50756f56e3ec1/packages/device-utils/src/firmwareUtils.ts#L41)

**Review by Lemonexe — APPROVED** [review]

File: suite-common/wallet-core/src/device/deviceReducer.ts [hunk 2]
```diff
@@ -773,6 +773,10 @@ export const selectDeviceSupportedNetworks = (state: DeviceRootState) => {
                 return false;
             }
 
+            if (hasBitcoinOnlyFirmware(device) && !['btc', 'test', 'regtest'].includes(symbol)) {
```
Comment (tomasklim) [inline suite-common/wallet-core/src/device/deviceReducer.ts]: please try to reuse `['btc', 'test', 'regtest']` it is used on more places in codebase
look for `['btc', 'test', 'regtest']`, `['btc', 'test']`

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Comment by enjojoy** [comment]
@trezor/qa Please test on different devices with different versions, both bitcoin only and universal

**Review by tomasklim — APPROVED** [review]
