### PR TITLE
fix(suite): handle keys needed in labeling

### LINKED ISSUE #24288: Add label button functionality
Functionality for `Add label` button press on mobile. 

**Suite Sync disabled** 
- on TS with compatible FW: turn on suite sync and retrieve keys
- on TS with outdated FW: turn on suite sync and then prompt user to update FW

**Suite Sync enabled**
- nothing changes, you should be able to edit label
- if you don't have keys for device, turning on suite sync process is called which will retrieve the keys 

Desktop design here: https://www.figma.com/design/N6cztyt3c8BhvCF9CVVldo/Suite-Sync--Final-?node-id=2209-21137&m=dev
For mobile, draft design with alert instead of modal and then continue to FW update.

### PR DESCRIPTION
**Pull request by juriczech**
## Description
Trigger keys retrieval on `Add label` button press. 

## Related Issue

Desktop follow-up for: https://github.com/trezor/trezor-suite/issues/24288

## Screenshots:

https://github.com/user-attachments/assets/0d052012-fd75-4240-b32a-c3a2446245ad

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/suite-sync/labeling-prerequisites&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/suite-sync/labeling-prerequisites&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/labeling/MetadataLabeling/MetadataLabeling.tsx [hunk 1]
```diff
@@ -393,14 +395,31 @@ export const Labeling = ({
...
-                dispatch(updateShowEnableSuiteSyncModal({ deviceStaticSessionId }));
+                // Keys needed is not handled by the same modal, because it in DeviceInteraction context
+                if (suiteSyncInteraction === 'keys-needed') {
+                    const result = await suiteSync.ensureWalletSuiteSyncOn({
+                        deviceStaticSessionId,
+                        isWriteMode: false,
+                    });
+
+                    if (!result.success) {
+                        suiteSyncErrorHandler({
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/labeling/MetadataLabeling/MetadataLabeling.tsx:412]: :clap:

**Review by peter-sanderson — APPROVED** [review]

**Comment by peter-sanderson** [comment]
Not tested tho, code looks ok

File: packages/suite/src/components/suite/labeling/MetadataLabeling/MetadataLabeling.tsx [hunk 2]
```diff
@@ -393,14 +395,31 @@ export const Labeling = ({
...
             // Is there something that needs to be initiated?
             !isLegacyLabelingEnabled
         ) {
             if (suiteSyncInteraction !== null) {
-                dispatch(updateShowEnableSuiteSyncModal({ deviceStaticSessionId }));
+                // Keys needed is not handled by the same modal, because it in DeviceInteraction context
+                if (suiteSyncInteraction === 'keys-needed') {
+                    const result = await suiteSync.ensureWalletSuiteSyncOn({
+                        deviceStaticSessionId,
+                        isWriteMode: false,
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/labeling/MetadataLabeling/MetadataLabeling.tsx:408]: is this correct Matt? I think yes but just want to double check

Comment (juriczech) [reply packages/suite/src/components/suite/labeling/MetadataLabeling/MetadataLabeling.tsx:408]: I checked that this param is used mostly everywhere so I just copied it. cc @OriginalEveres

Comment (OriginalEveres) [reply packages/suite/src/components/suite/labeling/MetadataLabeling/MetadataLabeling.tsx:408]: double check with @peter-sanderson  on call and this seems fine, the only ensure call with isWriteMode true should be the one saving the label (eg.: when user click or hits enter while typin label)
