### PR TITLE
fix(suite): force 1sat/vb for RBF

### LINKED ISSUE #20710: Force 1sat/vb for RBF
Lot of nodes does accept `minrelaytxfee` as `0.1 sat/vb`. But they forgot to lower the incremental fee (used for RBF).

Bcs of that we need to force `1 sat/vb` for RBF transactions, otherwise the RBF tx would not be propagated and it would be required to do the RBF of the former tx manually.

### PR DESCRIPTION
**Pull request by OriginalEveres**
Forces 1 sat/vb for RFB.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20710

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/btc-rbf-for-min-1sat-per-vb&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/btc-rbf-for-min-1sat-per-vb&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 1]
```diff
@@ -54,7 +56,7 @@ const getBitcoinFeeInfo = (info: FeeInfo, rbfParams: RbfTransactionParamsBitcoin
     return {
         ...feeInfo,
         levels,
-        minFee: new BigNumber(feeRate).plus(feeInfo.minFee).toNumber(), // increase required minFee rate
+        minFee: Math.max(new BigNumber(feeRate).plus(feeInfo.minFee).toNumber(), MIN_FEE_RATE),
```
Comment (Lemonexe) [inline packages/suite/src/hooks/wallet/useRbfForm.ts:59]: Nit: you could use `BigNumber.maximum` and then cast the final bignumber toNumber() but can be done later..

**Review by Lemonexe — APPROVED** [review]
LGTM.
vorks.
image

File: packages/suite/src/hooks/wallet/useRbfForm.ts (hunk 1 above)
Comment (OriginalEveres) [reply packages/suite/src/hooks/wallet/useRbfForm.ts:59]: good to know, will improve later on
