### PR TITLE
Fix/preload state

### LINKED ISSUE #5118: Fix handling asynchronicity of init process to prevent race conditions
@szymonlesisz have noticed that the init process is no longer synchronous which may (and probably is) causing race conditions on application start.
Main purpose of suiteMiddleware was to control the initialization process correct order until all essential data/prerequisites are initialized:
1. SUITE.INIT (should be first action ever) ->
2. LOAD STORAGE ->
3. LOAD LOCALES ->
4. INIT CONNECT ->
... (for more steps see suiteMiddleware)
5. SUITE.READY -> initialization done, now suite app is ready to do other stuff like render, fetch etc

Currently there are multiple actions that are fired up immediately on first render without respecting that order (see components in suite-web/src/Main.tsx and suite-desktop/src/index.tsx)
Potential race conditions:
1. Autodetect component is accessing the reducer state before LOAD STORAGE action (this one is probably handled by checking state.suite.storageLoaded)
2. Protocol component > saveCoinProtocol action (writing to state) may be called before LOAD STORAGE > STORAGE LOADED
3. Tor component > updateTorStatus action (writing to state) may be called before LOAD STORAGE > STORAGE LOADED
4. DesktopUpdater component actions (fetch, desktopApi, writing to state) are called in parallel to initialization

It probably starts when Tor component was placed above Preloader and then more components followed that pattern

Possibly related to https://github.com/trezor/trezor-suite/issues/3438 (One of the components (updater? tor?) is trying to write to indexeddb in the middle of db migration process)

### PR DESCRIPTION
**Pull request by szymonlesisz**
different approach for https://github.com/trezor/trezor-suite/pull/5125
fix https://github.com/trezor/trezor-suite/issues/5118

__!!! Looking for volunteer to finish this !!!__

## Preloading store before first render

This solves multiple issues:
- reading from db and eventual migration happens before react/redux kicks in, there should be no race conditions between loading state and writing to state (sentry issue)
- state is fully loaded before first redux action whatever the action is (originally it was designed to be `SUITE.INIT` but for a long time now multiple actions are fired up before that)
- 10 times faster loading!!! 40ms vs +500ms on current develop
- reducers are handling preloaded state, there is no need to create full `AppState` object like it was before (see previous/deleted storageActions.loadStorage), each reducer will pick related part of initial `STORAGE.LOAD` action (PreloadedState) and process it @marekrjpolak 
- no need to preload "suiteSettings" to get theme value, it should be always present in reducer (see point 2) @marekrjpolak 

EXTEND after [desktopApi.handshake](https://github.com/trezor/trezor-suite/pull/5632) implementation:
- [ ] preload data from indexedDB and use themto initialize TOR (as a parameter of handshake method), then get rid of "parallel storage", source of thruth will be only in indexedDB (tor url, port, enabled etc)

TODO:
- [ ] decide where to place `preloadStore` function, is "@suite-support" dir a right place for that? (note that this is not regular redux/redux-thunk action)
- [ ] fix tests where `STORAGE.LOADED` is used (not exists anymore)
- [ ] solve inconsistencies marked TODO-NOTE (especially coinmarket trades)
- [ ] handle `db.onBlocked` and `db.onBlocking` events properly (see storageActions.init and note in preloadStore function)
- [ ] consider using same approach in future react-native initialization @Nodonisko 
- [ ] write e2e tests for migration and db.onBlocked/db.onBlocking events mentioned above (optional, could be done as follow up)

## Update 18. 7. 2022

- Potential DB errors are now handled like this: When an error occurs even before successful `db.getDb()`, redux store is initialized by `STORAGE.ERROR` action instead of `STORAGE.LOAD` and db popup is immediately shown. Otherwise, `blocking` and `blocked` events are subscribed to in `storageMiddleware`. https://github.com/trezor/trezor-suite/pull/5534/commits/35df68c1166987a0a0fde57aafb5138d6a24010c
- By implementing different storage loading with stronger type checking, Coinmarket trade types became incompatible between redux and db (there was no enforced correlation between `TradeType` and corresponding `Trade` data type). Now it's hopefully fixed, but it must be very carefully reviewed. https://github.com/trezor/trezor-suite/pull/5534/commits/423af0fe0dc4dd36f03216357011dad072e75225
- Whole Suite initialization process was refactored into a single serial `init` action. `SUITE.CONNECT_INITIALIZED` and `BLOCKCHAIN.READY` could've been removed because of this. I think even more things could be now improved, but I've tried to preserve the previous behavior as much as possible. https://github.com/trezor/trezor-suite/pull/5534/commits/451891e7cb9ce4f619fd55b04ec682d60776a41e

### CODE REVIEW

**Comment by szymonlesisz** [comment]
rebased over prerequisite PR (and current develop)

File: packages/suite/src/reducers/wallet/coinmarketReducer.ts [hunk 1]
```diff
@@ -155,6 +155,12 @@ const coinmarketReducer = (
 ): State =>
     produce(state, draft => {
         switch (action.type) {
+            case STORAGE.LOAD:
+                // TODO-NOTE: this is inconsistent, in previous implementation coinmarketTrades.trades was filled with data from DB, but types are incorrect
+                // investigate more
+                // @ts-ignore
```
Comment (szymonlesisz) [inline packages/suite/src/reducers/wallet/coinmarketReducer.ts]: this

File: packages/suite/src/reducers/suite/analyticsReducer.ts [hunk 2]
```diff
@@ -20,6 +20,9 @@ export const initialState: AnalyticsState = {
 const analyticsReducer = (state: AnalyticsState = initialState, action: Action): AnalyticsState =>
     produce(state, draft => {
         switch (action.type) {
+            // NOTE: storage loaded was not used here before?
+            // case 'STO':
+            //     return action.payload?.analytics || state;
```
Comment (szymonlesisz) [inline packages/suite/src/reducers/suite/analyticsReducer.ts]: this

File: packages/suite/src/support/suite/preloadStore.ts [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    const fiatRates = await db.getItemsExtended('fiatRates');
+    const coinmarketTrades = await db.getItemsExtended('coinmarketTrades');
+    const graph = await db.getItemsExtended('graph');
+    const analytics = await db.getItemByPK('analytics', 'suite');
+    const metadata = await db.getItemByPK('metadata', 'state');
+    const txs = await db.getItemsExtended('txs', 'order');
+    const messageSystem = await db.getItemByPK('messageSystem', 'suite');
+    const backendSettings = await db.getItemsWithKeys('backendSettings');
+    const sendFormDrafts = await db.getItemsWithKeys('sendFormDrafts');
+    const formDrafts = await db.getItemsWithKeys('formDrafts');
```
Comment (szymonlesisz) [inline packages/suite/src/support/suite/preloadStore.ts:40]: note: make sure that all state is loaded (i already saw some changes in develop while rebasing)

File: packages/suite/src/support/suite/preloadStore.ts [hunk 4]
```diff
@@ -0,0 +1,54 @@
+import { db } from '@suite/storage';
+
+// This function should be called before first render
+// PreloadedState will be used in redux store creation
+export const preloadStore = async () => {
+    if (!(await db.isSupported())) return;
+
+    // check if db is blocked/blocking before preloading start
+    // TODO-NOTE: maybe it should return { suite: { dbError: '' }} instead?
```
Comment (szymonlesisz) [inline packages/suite/src/support/suite/preloadStore.ts]: this

**Comment by marekrjpolak** [comment]
I think it could be slowly reviewed. ~One thing which I know needs to be fixed are the `blocked`/`blocking` db states, which are currently handled only during initial loading and ignored later.~

**Comment by mroz22** [comment]
May I ask @LukasRada to cast an eye on https://github.com/trezor/trezor-suite/commit/423af0fe0dc4dd36f03216357011dad072e75225 please?

File: packages/suite/src/actions/suite/initAction.ts [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+    }
+
+    // 6. init backends
+    await dispatch(blockchainActions.init()).catch(err => console.error(err));
+
+    // 7. dispatch initial location change
+    dispatch(routerActions.init());
+
+    // 8. backend connected, suite is ready to use
+    dispatch({ type: SUITE.READY });
```
Comment (karliatto) [inline packages/suite/src/actions/suite/initAction.ts:58]: Nicely clear order of actions! :+1:

File: packages/suite/src/actions/suite/initAction.ts [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+    dispatch(routerActions.initialRedirection());
+
+    // 5. init connect (could throw an error,
+    // then the error is caught in <ErrorBoundary /> in Main.tsx
+    try {
+        await dispatch(trezorConnectActions.init());
+    } catch (err) {
+        dispatch({ type: SUITE.ERROR, error: err.message });
+        throw err;
+    }
```
Comment (karliatto) [inline packages/suite/src/actions/suite/initAction.ts:49]: If I understand well, this is the reason we do not need `CONNECT_INITIALIZED` anymore? because it will be initialized or it will throw error and will not be initialized.
So we can assume that it is initialized if there was no error?

Is that assumption right or am I missing something?

File: packages/suite/src/actions/suite/initAction.ts (hunk 5 above)
Comment (marekrjpolak) [reply packages/suite/src/actions/suite/initAction.ts:58]: :heart:

File: packages/suite/src/actions/suite/initAction.ts (hunk 6 above)
Comment (marekrjpolak) [reply packages/suite/src/actions/suite/initAction.ts:49]: Exactly. Because previously, the subsequent steps were performed by middleware on `SUITE.CONNECT_INITIALIZED` (which was dispatched by `trezorConnectActions.init` itself) and if it failed, `SUITE.ERROR` was dispatched instead (which is currently the same, except it's from `init` instead of `trezorConnect.init`).

**Review by karliatto — APPROVED** [review]
Very clear!
I have the feeling that the initialization is a bit faster.

**Comment by LukasRada** [comment]
> May I ask @LukasRada to cast an eye on [423af0f](https://github.com/trezor/trezor-suite/commit/423af0fe0dc4dd36f03216357011dad072e75225) please?

LGTM

**Review by mroz22 — APPROVED** [review]
