### PR TITLE
fix(suite): basic handling of some migration errors

### LINKED ISSUE #18601: NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
Sentry Issue: [TREZOR-SUITE-13AM](https://satoshilabs.sentry.io/issues/6525989047/?referrer=github_integration)

```
NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
  at connect (@trezor/suite-build/../suite-storage/src/web/index.ts:357:23)
  at preloadAction (@trezor/suite-build/../suite/src/support/suite/preloadStore.ts:48:9)
  at init (@trezor/suite-build/../suite-desktop-ui/src/MainDesktop.tsx:89:11)
```

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

We are having somewhat noisy migration errors – [example sentry issue](https://satoshilabs.sentry.io/issues/6525989047/events/c0f232871f9f400ea289df5b6d4f628f/?project=5193825).
Unfortunately it doesn't even say which store failed, just this, making it impossible to debug:
```
NotFoundError: Failed to execute 'objectStore' on 'IDBTransaction': The specified object store was not found.
NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```

Now it shall emit [an issue like this](https://satoshilabs.sentry.io/issues/6578617512/), so we'll be able to debug after next release cycle :crossed_fingers: 

## Related Issue

Resolve #18601
:thought_balloon:  _(technically solves the issue, but really we'll need to followup on the new, more specific Sentry issues that'll arise)_

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/migration-error-handling&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/migration-error-handling&lookback=7)

### CODE REVIEW

File: packages/suite/src/storage/migrations/index.ts [hunk 1]
```diff
@@ -747,6 +747,9 @@ export const migrate: OnUpgradeFunc<SuiteDBSchema> = async (
 
     if (oldVersion < 41) {
         await updateAll(transaction, 'metadata', metadata => {
+            if (!metadata.selectedProvider) {
+                metadata.selectedProvider = { labels: '', passwords: '' };
+            }
```
Comment (Lemonexe) [inline packages/suite/src/storage/migrations/index.ts:752]: [some of the events](https://satoshilabs.sentry.io/issues/6525989047/events/b5198a676df647bab8170a5aff200f8d/?project=5193825) have this
```
TypeError: Cannot set properties of undefined (setting 'passwords')
```

idk, this might solve this. But really, here I'm just throwing eggs at the wall hoping it will stick.

File: packages/suite-storage/src/web/index.ts [hunk 2]
```diff
@@ -309,6 +309,17 @@ class CommonDB<TDBStructure> {
...
     ) => {
         const db = await this.getDB();
+
+        // Stores are expected to exist, but if migrations go wrong, the error mustn't go unhandled,
+        // because it crashes Suite and also the raw error doesn't bear enough info for debugging.
+        // This shall help pinpoint issues in Sentry to specific stores & their migrations.
+        if (!Object.values(db.objectStoreNames).includes(store)) {
+            console.error(`IDB store ${store} (indexName: ${indexName ?? ''}) not found!`);
+
+            // this fn always returns an Array, so falling back to an empty one gives a chance that Suite won't crash completely
```
Comment (Lemonexe) [inline packages/suite-storage/src/web/index.ts:319]: Locally I mocked crashing _all_ of the stores that are loaded with `getItemsExtended`, and Suite still works when I return an empty array! That's

Current behavior is infinite loader, because [the Promise.all](https://github.com/trezor/trezor-suite/blob/a8ce0de663b1563b7156088d17f1a46e9aad3612/packages/suite/src/support/suite/preloadStore.ts#L49) never resolves :scream: So this might make Suite slightly more usable for the unlucky users who get these errors.

File: packages/suite-storage/src/web/index.ts [hunk 3]
```diff
@@ -309,6 +309,17 @@ class CommonDB<TDBStructure> {
...
+            return Promise.resolve([]);
```
Comment (Lemonexe) [inline packages/suite-storage/src/web/index.ts:320]: Locally [I mocked](https://satoshilabs.sentry.io/issues/trace/174de84f74fa413da3020b336f40ade9) crashing _all_ of the stores that are loaded with `getItemsExtended`, and Suite still works when I return an empty array! That's certainly an improvement, because current behavior is infinite loader, making the Suite probably unusable for those affected users :scream:
(because [the Promise.all](https://github.com/trezor/trezor-suite/blob/a8ce0de663b1563b7156088d17f1a46e9aad3612/packages/suite/src/support/suite/preloadStore.ts#L49) never resolves)

**Review by peter-sanderson — APPROVED** [review]
