### PR TITLE
fix(components): allow passing of multiple contract addresses to AssetLogo

### LINKED ISSUE #14806: Cardano: AssetLogo token icon should fallback to other contract address if available
**Describe the bug**
The API of token Icon was unfortunately not correctly specified and tested #13630. The described case for Cardano is not implemented.

`in case network is ada please try fetch 2 urls, see buildCoinUrls in coingecko.ts`

The reason is, coingecko is mixing policy id with token fingerprint and we have to try both as we try for fiat rates and token definitions

**Expected behavior**

`AssetLogo` should accept array of contract addresses and in case of fetch error it should try the next address in a row

**Screenshots**
https://www.coingecko.com/en/coins/bankercoin

Screenshot 2024-10-11 at 9 55 17

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

This PR updates `AssetLogo` and related components to support multiple possible contract addresses per token.
For Cardano tokens, some assets can only be resolved by `policyId`, while others require a `fingerprint`. This change ensures that if one address fails, the next candidate is tried automatically.

## Related Issue

Resolve #14806

### Before
Screenshot 2025-10-17 at 09 01 31

### After
image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/cardano-token-icons&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/cardano-token-icons&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/cardano-token-icons&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx [hunk 1]
```diff
@@ -206,7 +214,7 @@ export const TokenRow = ({
                     <AssetLogo
                         coingeckoId={coingeckoId || ''}
                         placeholder={token.name || token.symbol || 'token'}
-                        contractAddress={networkContractAddress}
+                        contractAddress={contractAddresses}
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx]: I am worried that someone will add token icon on a new place and forget about this logic. Can you move the logic to some special component to avoid "duplicating" the code into three components? If not, low prio

File: packages/components/src/components/AssetLogo/AssetLogo.tsx [hunk 2]
```diff
@@ -93,45 +107,107 @@ export const AssetLogo = ({
...
     const frameProps = pickAndPrepareFrameProps(rest, allowedAssetLogoFrameProps);
 
-    const handleError = () => {
-        setIsPlaceholder(true);
+    const handleLoadError = () => {
+        if (!current) return;
+
+        failedAddressesCache.add(makeAddressKey(coingeckoIdLogo, current.address));
+        setCandidateIndex(prev => (prev + 1 < candidates.length ? prev + 1 : prev));
+    };
```
Comment (TomasBoda) [inline packages/components/src/components/AssetLogo/AssetLogo.tsx]: nit:
```suggestion
        setCandidateIndex(prev => Math.min(prev + 1, candidates.length - 1))
```

File: packages/components/src/components/AssetLogo/AssetLogo.tsx [hunk 3]
```diff
@@ -60,26 +62,38 @@ const ElevatedLogo = (props: LogoProps) => {
...
-        isNetworkSymbol(mainNetworkSymbol)
-    ) {
-        return {
-            coingeckoId: getNetwork(mainNetworkSymbol).tradeCryptoId ?? coingeckoId,
-            contractAddress: undefined,
-        };
-    }
+    const addresses = ([] as Array<string | undefined>)
+        .concat(contractAddress ?? [])
+        .map(addr => (!addr ? ZERO_ADDRESS : addr));
```
Comment (TomasBoda) [inline packages/components/src/components/AssetLogo/AssetLogo.tsx]: nit:
```suggestion
        .map(addr => addr ?? ZERO_ADDRESS);
```

File: packages/components/src/components/AssetLogo/AssetLogo.tsx [hunk 4]
```diff
@@ -27,13 +27,15 @@ type AllowedFrameProps = Pick<FrameProps, (typeof allowedAssetLogoFrameProps)[nu
 export type AssetLogoProps = AllowedFrameProps & {
     size: AssetLogoSize;
     coingeckoId: string;
-    contractAddress?: string;
+    contractAddress?: string | string[];
```
Comment (TomasBoda) [inline packages/components/src/components/AssetLogo/AssetLogo.tsx]: Is there a reason why we cannot always use `string[]` instead of `string | string[]`? I am generally not a fan of using ambiguous types unless necessary. But that is just my opinion.

**Review by tomasklim — APPROVED** [review]
