### PR TITLE
fix(suite): consider staking balances and ignore fake tokens in AccountsNonZeroBalance and AccountsTokensStatus

### LINKED ISSUE #18251: Analytics - AccountsNonZeroBalance should consider also staking and ignore fake tokens
**Describe the bug**
`AccountsNonZeroBalance` event

- take staking into account
- ignore fake tokens
- consider legit nfts

### LINKED ISSUE #18252: Analytics - AccountsTokensStatus - filter out fake tokens
**Describe the bug**
Filter out accounts which have only fake tokens

### PR DESCRIPTION
**Pull request by izmy**
## Description

- `AccountsNonZeroBalance` now considers staking balances.
- Both `AccountsNonZeroBalance` and `AccountsTokensStatus` ignore fake tokens.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/18251
Resolve https://github.com/trezor/trezor-suite/issues/18252

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/analytics-AccountsTokensStatus-AccountsNonZeroBalance&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/analytics-AccountsTokensStatus-AccountsNonZeroBalance&lookback=7)

### CODE REVIEW

File: packages/suite/src/middlewares/suite/analyticsMiddleware.ts [hunk 1]
```diff
@@ -166,17 +168,23 @@ const analyticsMiddleware =
...
                     .reduce(accumulateAccountCountBySymbolAndType, {});
 
                 const accountsWithTokens = state.wallet.accounts
                     .filter(account => new BigNumber((account.tokens || []).length).gt(0))
-                    .reduce((acc: { [key: string]: number }, { symbol }: Account) => {
+                    .reduce((acc: { [key: string]: number }, { symbol, tokens }) => {
+                        if (tokens && tokens.length > 0) {
+                            if (!hasVisibleTokens(symbol, tokens, state.tokenDefinitions))
+                                return acc;
+                        }
```
Comment (adderpositive) [inline packages/suite/src/middlewares/suite/analyticsMiddleware.ts]: Maybe make just one condition

**Review by adderpositive — APPROVED** [review]

File: packages/suite/src/middlewares/suite/analyticsMiddleware.ts (hunk 1 above)
Comment (izmy) [reply packages/suite/src/middlewares/suite/analyticsMiddleware.ts]: done
