### PR TITLE
fix(suite): error page dashboard link

### LINKED ISSUE #7049: Error page Dashboard link
**Describe the bug**
`Go to Dashboard` button navigates to the landing page and not to the dashboard

**Info:**

-   Suite Version: 22.11.1

**How to reproduce**

1. Go to non-existing suite route e.g. https://suite.trezor.io/web/sdfsdfdsf

**Expected behavior**
It should take to dashboard and not landing page

**Screenshots**
lala

### PR DESCRIPTION
**Pull request by AdamSchinzel**
Button link will now redirect user to Dashboard page (if Trezor connected) or to Connect Trezor page (if Trezor is not connected)

## Description

Changed `href="/"` to `href="/web"` for proper redirect.

## Related Issue

Resolve #7049 

## Screenshots:

https://github.com/trezor/trezor-suite/assets/66002635/4044ce01-71fa-4a4c-9462-b6dfdc36606b

### CODE REVIEW

File: packages/suite/src/views/suite/error/index.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ const ErrorPage = () => (
             <Translation id="TR_404_DESCRIPTION" />
         </P>
         <Image image="ERROR_404" />
-        <Link variant="nostyle" target="_self" href="/">
+        <Link variant="nostyle" target="_self" href="/web">
```
Comment (tomasklim) [inline packages/suite/src/views/suite/error/index.tsx]: This is going to work only on production. Please use asset prefix.

I believe something like that is necessary. 
```
const assetPrefix = process.env.ASSET_PREFIX || '';
```

```suggestion
        <Link variant="nostyle" target="_self" href={`/${assetPrefix}`}>
```

It has to work on localhost
http://localhost:8000/
https://suite.trezor.io/web/
https://staging-suite.trezor.io/web
https://suite.corp.sldev.cz/suite-web/develop/web/

error page does not work on sldev now because of wrong configuration (cc @matejkriz) so please test that it works by putting this link to another page just for your testing purposes

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/suite/error/index.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/suite/error/index.tsx]: Thanks for the suggestion. It was a bit of blind fix by me (tested only in product with inspect) because I have somehow broken routing and webusb in web dev mode (only desktop dev mode is fully working for me, was trying to fix it with @matejkriz but so far no luck).

Comment (tomasklim) [reply packages/suite/src/views/suite/error/index.tsx]: Check it again
(Do not resolve conversations by your own)

**Review by tomasklim — APPROVED** [review]
