### PR TITLE
Fix/unable to bump fee

### LINKED ISSUE #8972: Unable to bump fee to an amount lower than current base gas price
**Describe the bug**
Unable to bump gas price to an amount lower than current network gas price 

**Info:**

-   Suite Version: 23.8.0

**How to reproduce**

1. Create tx with small gas price `1`
2. Bump fee in custom, try to put there `2`. The minimum is currect network fee

**Expected behavior**
It will allow me to insert what ever I want higher than `1`, probably `2` or even better `1.00000001`

**Screenshots**

Screenshot 2023-07-21 at 11 27 29

### PR DESCRIPTION
**Pull request by AdamSchinzel**
Fixed minimum gas price when replacing tx

## Description

Form error handler not accepts for replacing tx  minimum gas price `2`  (tx created with gas price `1`).

## Related Issue

Resolve #8972 

## Screenshots:

This was created with gas price 5
Screenshot 2023-07-26 at 1 17 36 PM

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 1]
```diff
@@ -38,24 +38,24 @@ const getEthereumFeeInfo = (info: FeeInfo, gasPrice: string) => {
...
     const levels = getFeeLevels('ethereum', info).map(l => ({
         ...l,
-        feePerUnit: minFee.toString(),
+        feePerUnit: fee.toString(),
     }));
     return {
         ...info,
         levels,
-        minFee: minFee.toNumber(), // increase required minFee rate
+        minFee: current.plus(1).toNumber(), // increase required minFee rate
```
Comment (szymonlesisz) [inline packages/suite/src/hooks/wallet/useRbfForm.ts:58]: isn't it what `getMinFee` should do in previous code?

if minimum fee from the network (from backend) is lower than `current` then use current + 1 otherwise use minimum which is greater than current?

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts:58]: It should prefill the input with the correct amount (that was fixed) but it was also passed to the form error handler.

We want to always set the error handler to `current + 1` but the prefill with the network fee or `current + 1`.

Because if user used gas price `2` and wants to replace the tx and the network fee is let's say `15` than he can't try just `10` but amount more than `15`.

Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useRbfForm.ts:58]: ah, i get it now. i see that before t[his change](https://github.com/trezor/trezor-suite/pull/8787/files) minFee was indeed set current + 1

**Review by tomasklim — APPROVED** [review]
LGTM
Screenshot 2023-07-27 at 21 40 28
