### PR TITLE
fix(suite-native): include account staking dashboard in navigation af…

### LINKED ISSUE #27090: After stake tx takes me to Earn instead of staking account
When I send stake tx and I hit `X`, it takes me to `Earn` tab

Image
Image

It would be better to end on staking dashboard for specific account
Image

If I open tx in tx history, there is `<` instead of `X` and everything works correctly
Image

### PR DESCRIPTION
**Pull request by omykhailovskyi**
## Description

Earn staking transaction review now resets navigation with the staking dashboard under transaction detail, so back navigates correctly after signing.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/27090

### CODE REVIEW

File: suite-native/module-earn/src/screens/ClaimTransactionDataReviewScreen.tsx [hunk 1]
```diff
@@ -33,21 +34,30 @@ import {
...
 
 const navigateToClaimedTransactionAction = ({
     accountKey,
+    symbol,
     txid,
 }: {
     accountKey: AccountKey;
+    symbol: NetworkSymbol;
     txid: string;
 }) =>
```
Comment (TomasBoda) [inline suite-native/module-earn/src/screens/ClaimTransactionDataReviewScreen.tsx:47]: Not in the scope of this PR, but could you please move this into `NavigateToClaimedTransactionActionProps` interface above?

File: suite-native/module-earn/src/screens/EarnTransactionDataReviewScreen.tsx [hunk 2]
```diff
@@ -33,22 +35,31 @@ import {
...
 const navigateToStakedTransactionAction = ({
     accountKey,
+    symbol,
     txid,
 }: {
-    accountKey: string;
+    accountKey: AccountKey;
+    symbol: NetworkSymbol;
     txid: string;
 }) =>
```
Comment (TomasBoda) [inline suite-native/module-earn/src/screens/EarnTransactionDataReviewScreen.tsx:49]: Not in the scope of this PR, but could you please move this into `NavigateToStakedTransactionActionProps` interface above?

File: suite-native/module-earn/src/screens/UnstakeTransactionDataReviewScreen.tsx [hunk 3]
```diff
@@ -33,22 +35,31 @@ import {
...
 const navigateToUnstakedTransactionAction = ({
     accountKey,
+    symbol,
     txid,
 }: {
-    accountKey: string;
+    accountKey: AccountKey;
+    symbol: NetworkSymbol;
     txid: string;
 }) =>
```
Comment (TomasBoda) [inline suite-native/module-earn/src/screens/UnstakeTransactionDataReviewScreen.tsx:49]: Not in the scope of this PR, but could you please move this into `NavigateToUnstakedTransactionActionProps` interface above?

**Review by TomasBoda — APPROVED** [review]
Code-wise LGTM, just a few nitpicks.

**Comment by tomasklim** [comment]
Merging, please address @omykhailovskyi the comments in different PR 🙏
