### PR TITLE
fix(suite): enforce that the Security Check List icon is NOT just a s…

### LINKED ISSUE #16692: Missing info icon during onboarding device check
**Describe the bug**
Missing info icon during onboarding device check

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 25.2.0 (366cb0904a6c16d7f08d0a88c6a776ea90587e35)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.2.0 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3T1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

Image

### PR DESCRIPTION
**Pull request by vojtatranta**
…tring

## Description

- an imperfect react type caused that needed updates were overlooked
- we improved the typing and fixed the cases so that it shouldn't happen again (altough, `<div />` still passes)

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16692
## Screenshots:
Before
Screenshot 2025-01-29 at 10 34 38 AM
After
Screenshot 2025-01-29 at 10 34 42 AM

## Summary by CodeRabbit

- **New Features**
	- Enhanced type safety for security checklist items
	- Improved icon rendering in security checklists

- **Tests**
	- Added type validation tests for security checklist items

- **Refactor**
	- Updated icon type definitions to be more specific
	- Replaced string-based icon references with React component icons

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx [hunk 1]
```diff
@@ -88,17 +89,17 @@ const TooltipWrapper = styled.span`
...
+const firmwareInstalledChecklist: readonly SecurityChecklistItem[] = [
     {
-        icon: 'info',
+        icon: <Icon size={24} name="info" />,
         content: <Translation id="TR_ONBOARDING_DEVICE_CHECK_4" />,
     },
 ] as const;
 
-const getNoFirmwareChecklist = (isMobileLayout: boolean) =>
+const getNoFirmwareChecklist = (isMobileLayout: boolean): readonly SecurityChecklistItem[] =>
```
Comment (vojtatranta) [inline packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx]: @Lemonexe why you put `readonly` there? I don't know how that works, so I copied your thing here.

Comment (Lemonexe) [reply packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx]: I also just copied the same thing  from before in https://github.com/trezor/trezor-suite/commit/946be5d11bb0259e53a64d71f3a942a58976e8a4, originally done in https://github.com/trezor/trezor-suite/commit/5e6071801df2315155f307ca705f99e00bca521c

IMO it does make sense though.. Restricting does not directly help anything, but makes code well readable - we can see that `SecurityChecklistProps` is supposed to have it read only. But not important :shrug:

File: packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx [hunk 2]
```diff
@@ -88,17 +89,17 @@ const TooltipWrapper = styled.span`
     position: relative;
 `;
 
-const firmwareInstalledChecklist = [
+const firmwareInstalledChecklist: readonly SecurityChecklistItem[] = [
```
Comment (Lemonexe) [inline packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx]: Tiny nit: in _this_ case, `readonly` doesn't do anything because `as const` has precedence.
BTW declarative type actually _does not declare_ the type when used with `as const`, it acts only as typecheck, but the variable will have the narrower, const type. 
I'd instead suggest `as const satisfies SecurityChecklistItem[]`, it has the same function but it's clearer.

File: packages/suite/src/views/onboarding/steps/SecurityCheck/types.ts [hunk 3]
```diff
@@ -1,7 +1,9 @@
-import { ReactNode } from 'react';
+import { ReactElement, ReactNode } from 'react';
+
+import { Icon } from '@trezor/components';
 
 export type SecurityChecklistItem = {
-    icon: ReactNode;
+    icon: ReactElement<typeof Icon>;
```
Comment (Lemonexe) [inline packages/suite/src/views/onboarding/steps/SecurityCheck/types.ts]: The `<typeof Icon>` has only informative value, but why not :shrug:

**Review by Lemonexe — APPROVED** [review]
LGTM, thanks for fixing my mess :bow:

File: packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx (hunk 1 above)
Comment (Lemonexe) [reply packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx]: FYI if an object-type variable is declared `readonly`, it means that TS throws e.g. on `items.pop()` or `items[1] = whatever` , because it mutates the array. Though it does not prevent you from mutating array members, because technically that does not mutate the object.

File: packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx (hunk 2 above)
Comment (vojtatranta) [reply packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx]: fixed according to you

**Comment by vojtatranta** [comment]
added some type tests, unfortunately, we haven't find a way to prevent others from passing stuff like `<div />` as `<Icon />`

**Review by Lemonexe — APPROVED** [review]

File: packages/suite/src/views/onboarding/steps/SecurityCheck/__tests__/types.test.tsx
Comment (komret) [inline packages/suite/src/views/onboarding/steps/SecurityCheck/__tests__/types.test.tsx:1]: Is this necessary now that you narrowed the type?

Comment (vojtatranta) [reply packages/suite/src/views/onboarding/steps/SecurityCheck/__tests__/types.test.tsx:1]: Well, the aim was to ensure that this won't happen again. More tests will hardly hurt us, I guess.
