### PR TITLE
fix: prevent jump of focus to he next elemnt for THP PIN (prevent accidental cancel)

### LINKED ISSUE #21756: Do not autofocus close button in ThpPairingPinEntryModal
Focusing the close button can lead to accidentally closing the modal when user wants to confirm the code by pressing Enter. Do not autofocus on it when the last character is filled. Instead keep the focus on the last digit.

https://github.com/user-attachments/assets/2e5cc72a-155a-498e-98d8-7073bd605c05

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves https://github.com/trezor/trezor-suite/issues/21756

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=autofocus-thp&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=autofocus-thp&lookback=7)

### CODE REVIEW

**Comment by vojtatranta** [comment]
@jvaclavik context:
we discussed this with @peter-sanderson and the case is:
- these are THP PIN inputs
- these are submitted once you fill in the last one
- because they are submitted, they are immediatly "disabled"
- but when an input is disabled, it loses focus for the next focusable element, this is now "Close" button in the top right of the pin modal

I suggested that this is an internal problem of the input and hence we should be solving this within an input itself. So we need a special kind of "disabled" that would only disable inputing and make it look like disabled, but the HTML itself won't be disabled

File: packages/components/src/components/PinInput/PinInput.tsx [hunk 1]
```diff
@@ -80,7 +86,8 @@ const SymbolInput = forwardRef<HTMLInputElement, SymbolInputProps>(
                 onClick={onClick}
                 $elevation={elevation}
                 onPaste={onPaste}
-                disabled={disabled}
+                disabled={false} // intentionally `false` always use `$fakeDisabled` instead
```
Comment (vojtatranta) [inline packages/components/src/components/PinInput/PinInput.tsx:95]: `preventDefault()` to that `onKeyDown` to disable inputing?

File: packages/components/src/components/form/styles.ts [hunk 2]
```diff
@@ -54,6 +54,14 @@ export interface BaseInputProps {
     $elevation: Elevation;
 }
 
+export const baseInputDisabledStyle = css`
+    box-shadow: none;
+    background: ${({ theme }) => theme.backgroundNeutralDisabled};
+    color: ${({ theme }) => theme.textDisabled};
+    pointer-events: none;
```
Comment (vojtatranta) [inline packages/components/src/components/form/styles.ts:61]: isn't this the problem of why it isn't focused, once disabled? I guess this would disable the focusing even without html disable

File: packages/components/src/components/PinInput/PinInput.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/components/src/components/PinInput/PinInput.tsx:95]: fixed

Comment (vojtatranta) [reply packages/components/src/components/PinInput/PinInput.tsx:95]: I'd like just @jvaclavik to see it. To let him know about it

**Review by jvaclavik — APPROVED** [review]
I would prefer solution outside of `PinInput` - with having hidden input after PinInput to have it as next focusable element, but this is also acceptable, so approving
