### PR TITLE
fix(suite): preserve correct swap amount when navigating back to trade

### LINKED ISSUE #19344: Trading – coming back into the trade sets wrong amount
**Describe the bug**
Coming back one step in the swap sets the wrong amount if you use the fiat value. See the video for the best demonstration.

https://github.com/user-attachments/assets/99cf2248-813f-4eef-b51b-8195e30b30f1

**Info:**
 - Suite version: desktop 25.6.1 (d14eb885016cefe147b2e6532ba04412230aaee0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.6.1 Chrome/136.0.7103.49 Electron/36.2.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.10 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: BridgeTransport 3.0.0-bundled.25.6.1

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

`TRADING_FORM_OUTPUT_MAX` is reset whenever `setFractionButton` button is called with different value than `1`.

## Related Issue

Resolve #19344

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feature/wrong-trade-amount-on-back&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feature/wrong-trade-amount-on-back&lookback=7)

### CODE REVIEW

**Review by izmy — APPROVED** [review]

**Comment by tomasklim** [comment]
@matusbalascak please resolve conflict

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts [hunk 1]
```diff
@@ -72,7 +72,7 @@ export const useTradingFormActions = <T extends TradingSellExchangeFormProps>({
         deviceState: device?.state?.staticSessionId,
     });
     const isNotFormPage = pageType !== 'form';
-    const [fractionButton, setFractionButton] = useState<number | undefined>(undefined);
+    const [fractionButton, setFractionButtonState] = useState<number | undefined>(undefined);
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts]:
```suggestion
    const [fractionButtonState, setFractionButton] = useState<number | undefined>(undefined);
```
