### PR TITLE
fix(suite): Fix firmware update progress bar

### LINKED ISSUE #16215: The loading bar gets stuck at 99% even after the firmware installation is complete
Image

### PR DESCRIPTION
**Pull request by jvaclavik**
## Description

- also component and color refactoring included 

## Related Issue

Resolve #16215

## Screenshots:

before

image

after
Screenshot 2025-01-17 at 13 57 54

Screenshot 2025-01-17 at 13 58 10

Screenshot 2025-01-17 at 13 58 54

### CODE REVIEW

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx [hunk 1]
```diff
@@ -68,20 +29,29 @@ export const FirmwareProgressBar = () => {
...
-            <StyledProgressBar value={progress} />
-            <Percentage>
-                {isDone ? (
-                    <Icon name="check" color={theme.legacy.TYPE_GREEN} size={24} />
-                ) : (
-                    `${progress} %`
-                )}
-            </Percentage>
-        </Wrapper>
+        <Box width="100%">
```
Comment (jvaclavik) [inline packages/suite/src/components/firmware/FirmwareProgressBar.tsx:32]: I'm not happy about this one (it should be part of `Column`), but I would need to update `alignItems:stretch` in `OnboardingStepBox` which could lead many issues across the app. Not brave enough right now :D let's leave it for broader refactoring.

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx [hunk 2]
```diff
@@ -1,54 +1,15 @@
...
-        border-radius: ${borders.radii.xxs};
-    }
-`;
 const Percentage = styled.div`
-    display: flex;
-    margin-left: ${spacingsPx.sm};
-    font-weight: ${variables.FONT_WEIGHT.DEMI_BOLD};
     font-variant-numeric: tabular-nums;
-    height: ${spacingsPx.xl};
+    width: 30px;
```
Comment (jvaclavik) [inline packages/suite/src/components/firmware/FirmwareProgressBar.tsx:12]: It's intended not have fixed width, because otherwise progress bar is moving according to percentage value or checkmark

File: packages/components/src/components/loaders/ProgressBar/ProgressBar.tsx [hunk 3]
```diff
@@ -1,35 +1,58 @@
...
+    $color: CSSColor;
 };
 
 const Value = styled.div<ValueProps>`
-    background: ${({ theme }) => theme.iconPrimaryDefault};
+    background: ${({ $color }) => $color};
     height: 5px;
     max-width: 100%;
-    width: 1%;
-    transform: ${({ $max, $value }) => `scaleX(${(100 / $max) * $value})`};
```
Comment (jvaclavik) [inline packages/components/src/components/loaders/ProgressBar/ProgressBar.tsx:19]: There is a rounding bug in cases of long progressbar, so I rewrote it with width. Looks like everything is still working.

File: packages/components/src/utils/frameProps.tsx [hunk 4]
```diff
@@ -80,7 +80,7 @@ export type FramePropsKeys = keyof FrameProps;
 type TransientFrameProps = TransientProps<FrameProps>;
 
 const getValueWithUnit = (value: string | number) =>
-    typeof value === 'string' ? value : `${value}px`;
+    typeof value === 'number' ? `${value}px` : value;
```
Comment (jvaclavik) [inline packages/components/src/utils/frameProps.tsx:83]: Actually this makes sense to have it this way IMHO

File: packages/components/src/components/loaders/ProgressBar/ProgressBar.tsx [hunk 5]
```diff
@@ -1,35 +1,58 @@
...
-    transform-origin: left;
-    transition: transform 0.5s;
+    width: ${({ $max, $value }) => `calc((100% / ${$max}) * ${$value})`};
```
Comment (seibei-iguchi) [inline packages/components/src/components/loaders/ProgressBar/ProgressBar.tsx:21]: I've changed this because it's better to use transform than to animate width:) It should be the same, do you think it bug is caused by this?

Comment (jvaclavik) [reply packages/components/src/components/loaders/ProgressBar/ProgressBar.tsx:21]: Yes, I'm pretty sure it was, now it's working fine

File: packages/components/src/components/loaders/ProgressBar/ProgressBar.tsx (hunk 3 above)
Comment (seibei-iguchi) [reply packages/components/src/components/loaders/ProgressBar/ProgressBar.tsx:19]: Can't we just use Math.round?:)

**Review by seibei-iguchi — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

image

image


**Info:**
 - Suite version: web 25.1.2 (2db40a5dfed7c8743da2ff2cce78e86e557a0aaa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: WebUsbTransport
