### PR TITLE
fix(suite): cardano staking fivebinaries footer

### LINKED ISSUE #22785: Cardano staking - powered by XYZ
Add "Powered by 5binaries" into footer of staking screen in case customer is still staked with 5B

5B pools are fetched from https://trezor-cardano-mainnet.blockfrost.io/api/v0/pools/

Make sure that app does not die in case this website goes down.

[Figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Staking--Final-?node-id=3277-22808&t=PP4snrAMkb0EcHG4-4)

Image

In case user is staking with Everstake or whoever else. Leave there powered by Everstake

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Added “Powered by Five Binaries” footer to the staking screen for users currently staked with Five Binaries.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22785

## Screenshots:
image

### CODE REVIEW

File: suite-common/wallet-utils/src/cardanoStakingUtils.ts [hunk 1]
```diff
@@ -34,6 +35,14 @@ export const isCardanoUpdateProviderFlow = (account?: Account) => {
     return !isCardanoStakedWithEverstake(account) && isStakeActive;
 };
 
+export const isStakedWithFivebinaries = (account?: Account, trezorPools?: PoolsResponse) => {
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/cardanoStakingUtils.ts]:
```suggestion
export const isStakedWithFiveBinaries = (account?: Account, fiveBinariesPools?: PoolsResponse) => {
```

Comment (dev-pvl) [reply suite-common/wallet-utils/src/cardanoStakingUtils.ts]: fixed and rebased

**Review by tomasklim — APPROVED** [review]
