### PR TITLE
fix(suite): nft id spaces and link

### LINKED ISSUE #18338: Transaction modal view - nft text is missing spaces
**Describe the bug**

In crowdin, there are spaces, but not in app
Image

Now:
Image

Expected:

Image

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- fix nft link to not contain double `//`
- spaces around nft symbol

## Related Issue

Resolve #18338

## Screenshots:
Screenshot 2026-01-22 at 12 16 31
Screenshot 2026-01-22 at 12 07 09

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/nft/ui&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/nft/ui&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const FormattedNftAmount = ({
                         </Row>
                         {isWithLink && network?.networkType === 'ethereum' ? (
                             <TrezorLink
-                                href={`${getExplorerUrl(explorer, 'nft')}/${transfer.contract}/${token.id}`}
+                                href={`${getExplorerUrl(explorer, 'nft')}${transfer.contract}/${token.id}`}
```
Comment (izmy) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx:73]: Maybe consider extracting `href` building into a small helper function (`getNftExplorerHref()` or something like that)

**Review by izmy — APPROVED** [review]

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx:73]: Let's do this when reworking NFTs 😬
