### PR TITLE
fix(localizeNumber): long numbers were replaced by empty string

### LINKED ISSUE #6252: Transactions with huge amounts have missing amount in transaction list
**Describe the bug**
Transactions with huge amounts have missing amount in transaction list

**Info:**

-   Suite Version: 22.9.x (introduced here)

**Expected behavior**
The amount should be there.

**Screenshots**
Screenshot 2022-09-12 at 16 45 59

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- The amount was missing in case the amount was bigger than `Number.MAX_SAFE_INTEGER`

## Related Issue

Closes #6252

## Screenshots (if appropriate):
Screenshot 2022-09-12 at 16 46 20

### CODE REVIEW

File: suite-common/wallet-utils/src/localizeNumber.ts [hunk 1]
```diff
@@ -1,28 +1,39 @@
...
-    return Intl.NumberFormat(locale, {
+    const amount = new BigNumber(value);
+
+    if (amount.isNaN() || !amount.isFinite()) {
+        return '';
+    }
+
+    const wholeNumber = BigInt(amount.toFixed(0, BigNumber.ROUND_DOWN));
+    const formattedWholeNumber = Intl.NumberFormat(locale, {
+        style: 'decimal',
```
Comment (komret) [inline suite-common/wallet-utils/src/localizeNumber.ts]: The `decimal` value is default and it seems quite redundant here.

File: suite-common/wallet-utils/src/localizeNumber.ts [hunk 2]
```diff
@@ -1,28 +1,39 @@
...
     }
 
-    return Intl.NumberFormat(locale, {
+    const amount = new BigNumber(value);
+
+    if (amount.isNaN() || !amount.isFinite()) {
+        return '';
+    }
+
+    const wholeNumber = BigInt(amount.toFixed(0, BigNumber.ROUND_DOWN));
```
Comment (komret) [inline suite-common/wallet-utils/src/localizeNumber.ts]:
```suggestion
    const roundedDown = amount.toFixed(0, BigNumber.ROUND_DOWN)
    const wholeNumber = BigInt(roundedDown);
```

This can be reused on line 26.

**Review by komret — CHANGES_REQUESTED** [review]
Nice! Can you just add some comments explaining this approach?

File: suite-common/wallet-utils/src/localizeNumber.ts (hunk 1 above)
Comment (tomasklim) [reply suite-common/wallet-utils/src/localizeNumber.ts]: 4eaafaa841c1e28c7df48e77bb8cac4ac2896b36

File: suite-common/wallet-utils/src/localizeNumber.ts (hunk 2 above)
Comment (tomasklim) [reply suite-common/wallet-utils/src/localizeNumber.ts]: 4eaafaa841c1e28c7df48e77bb8cac4ac2896b36

**Review by komret — DISMISSED** [review]
Looks good to me, just missing the comments :)

**Review by komret — APPROVED** [review]
