### PR TITLE
fix: pass THP props into evoluGetDelegatedIdentityKey

### LINKED ISSUE #23229: Fix THP device for evoluGetDelegatedIdentityKey
Image

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/23229

## QA:

Secure Sync (get keys flow) shall work for THP devices (TS7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-evoluGetDelegatedIdentityKey-thp&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-evoluGetDelegatedIdentityKey-thp&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix-evoluGetDelegatedIdentityKey-thp&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/device/delegatedIdentityKey/retrieveDelegatedIdentityKeyThunk.ts [hunk 1]
```diff
@@ -18,19 +19,30 @@ type RetrieveResult = {
...
     device: TrezorDeviceWithState;
+    thpStaticHostKey: string | undefined;
 };
 
 const retrieveDelegatedIdentityKey = async ({
     device,
+    thpStaticHostKey,
 }: RetrieveDelegatedIdentityKeyParams): Promise<Result<DelegatedIdentityKey, RetrieveResult>> => {
     try {
+        const thpCredential = device.thp?.credentials?.[0].credential;
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/device/delegatedIdentityKey/retrieveDelegatedIdentityKeyThunk.ts]: I don't think the `[0]` is quite correct here. There can be multiple credentials per device, but I think I shall pass the one, that was used to connect the device. But I don't think this information is exposed.

Comment (peter-sanderson) [reply suite-common/wallet-core/src/device/delegatedIdentityKey/retrieveDelegatedIdentityKeyThunk.ts]: According to [this conversation](https://satoshilabs.slack.com/archives/C08MBHVN3K5/p1763580540164669) it may be ok.

**Review by OriginalEveres — APPROVED** [review]

**Review by martykan — APPROVED** [review]
