### PR TITLE
fix(suite): optimize TransactionReviewModalContent

### LINKED ISSUE #19876: Send and other buttons sometimes remains inactive even after hovering
Describe the bug

The Send button occasionally remains inactive even after the user hovers over it.
I’ve experienced this multiple times—clicking the button several times was necessary before the transaction was actually sent.

This issue is clearly visible in the video below.

https://github.com/user-attachments/assets/2d2e1ac7-b835-41e6-a78d-1743d7b7b2f9

seems this has to be introduced between https://github.com/trezor/trezor-suite/commit/d6bedb2912b4d9a870d6a99dd65327c90701defd (working) and https://github.com/trezor/trezor-suite/commit/3c1af7a9fa872dc0770e798e77d4e56a7095b736 (not working)

it seems to happen with other buttons especially after refreshing the app.

Image

Image

**Info:**
 - Suite version: web 25.7.0 (766356e7700d10ba024bc4abd8fa7622a7ce74b5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.9.0 regular (revision a09e6f04d4204607d821d9b742dcf7ffe9c4e2f5)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

See issue.
When a cluster of `updateAccountRefreshTimestamp` actions is dispatched, `TransactionReviewModalContent` rerenders so often that React can't cope and it temporarily breaks the Send button.
There is also a visual glitch in hover state as a visible symptom of the broken button.

:thought_balloon:  When investigating the issue, it took me a long time to realize this is actually a performance problem, not a business logic problem as I initially suspected – the `onClick` is wired just fine.
We might go through React code and find other such `selectAccounts` calls, because they might cause problems too.  

## Related Issue

Resolve #19876

## Screenshots:

Nothing to show – the visible symptom of the bug is gone, and the Send button is now calm & working :relieved: 

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/optimize-TransactionReviewModalContent&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/optimize-TransactionReviewModalContent&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/optimize-TransactionReviewModalContent&lookback=7)

### CODE REVIEW

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 1]
```diff
@@ -412,9 +412,9 @@ export const findAccountsByAddress = (
         .filter(a => {
             if (a.addresses) {
                 return (
-                    a.addresses.used.find(u => u.address === address) ||
-                    a.addresses.unused.find(u => u.address === address) ||
-                    a.addresses.change.find(u => u.address === address) ||
+                    a.addresses.used.some(u => u.address === address) ||
+                    a.addresses.unused.some(u => u.address === address) ||
+                    a.addresses.change.some(u => u.address === address) ||
```
Comment (Lemonexe) [inline suite-common/wallet-utils/src/accountUtils.ts:417]: just random tweak as I walked by, this does not affect anything,

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 2]
```diff
@@ -116,7 +116,6 @@ export const TransactionReviewModalContent = ({
 }: TransactionReviewModalContentProps) => {
     const dispatch = useDispatch();
     const account = useSelector(selectAccountIncludingChosenInTrading);
-    const accounts = useSelector(selectAccounts);
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx:119]: :point_up: :warning: this right here was the source of the problem.
`selectAccounts` causes insane rerender hell, because it changes when _any_ account changes due to `updateAccountRefreshTimestamp`.
It triggers for accounts of other networks, so the more coins you have enabled, the worse it is :scream: 
Potentially it could trigger for accounts of other devices but I did not verify that..

It'd be a small improvement just if we replaced it with `selectDeviceAccountsByNetworkSymbol`, but ofc the proper solution is to memoize the result of the calculation which we use it for.

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 3]
```diff
@@ -60,25 +58,27 @@ const getTxValidityTimeoutInMs = (networkType?: NetworkType) => {
...
+};
+
+const shouldShowTxValidityTimer = ({
+    deadline,
+    buttonRequestsCount,
+    serializedTx,
+    stakeType,
+    shouldCheckTxTimeValidity,
+    isInternalTransfer,
+}: ShouldShowTxValidityTimerProps) => {
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx:77]: 8 positional arguments is IMO a bit too much :smile:

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 4]
```diff
@@ -175,6 +174,18 @@ export const TransactionReviewModalContent = ({
         selectSendFormReviewButtonRequestsCount(state, account?.symbol, decreaseOutputId),
     );
 
+    const outputs = constructTransactionReviewOutputsOptional({
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx:177]: this is stupid, the original function requires non nullable, but because I need outputs for a useSelector hook I had to move it before the early returns :see_no_evil:

**Review by tomasklim — APPROVED** [review]
