### PR TITLE
fix(suite-native): fix navigation redirects

### LINKED ISSUE #8056: Import screen is displayed when currency is changed
Steps to reproduce the bug:
1. You have at least one XPUB imported
2. Go to settings and switch the currency
3. You are redirected to import asset screen without no reason - look at the video

https://user-images.githubusercontent.com/84183817/231257246-150f4955-5537-43e6-b8be-3d8819f0df53.MP4

### PR DESCRIPTION
**Pull request by juriczech**
## Description
After importing, navigation is reset so that app doesn't take previous screens from onboarding into account.

## Related Issue

Resolve #8056

## Screenshots:

https://user-images.githubusercontent.com/36101761/232418924-72fbe6ab-586e-4032-8861-096b1af0420b.mov

### CODE REVIEW

**Review by PeKne — APPROVED** [review]

File: suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx [hunk 1]
```diff
@@ -75,12 +75,20 @@ export const AccountImportSummaryForm = ({
...
             }),
         );
-        navigation.navigate(RootStackRoutes.AppTabs, {
-            screen: AppTabsRoutes.HomeStack,
-            params: {
-                screen: HomeStackRoutes.Home,
-            },
-        });
+
+        navigation.dispatch(
```
Comment (Nodonisko) [inline suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx]: Why you did not use `navigation.reset`?

**Review by Nodonisko — CHANGES_REQUESTED** [review]

**Review by Nodonisko — APPROVED** [review]
