### PR TITLE
Put Optimism, Base and Arbitrum one into one experimental feature

### LINKED ISSUE #16084: Move L2s to experimental features
Base, Arbitrum One, Optimism under 1 experimental feature toggle

### LINKED ISSUE #16115: Trading - allowed to add account not available in Suite
**Describe the bug**

- Suite allows to add accounts which does not exist in Suite app

**Info:**

-   Suite Version: 24.10.1

**How to reproduce**

1. Buy XLM

**Screenshots**
Screenshot 2024-12-29 at 12 39 31

### PR DESCRIPTION
**Pull request by enjojoy**
## Description

- Optimism, Base and Arbitrum are moved into an experimental feature
- fix coinmarket allow to add non-existing account
- use shared logic for sidebar networks filter

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16084
Resolve #16115

## Screenshots:

Screenshot 2024-12-29 at 12 37 01
Screenshot 2024-12-29 at 12 36 56

Experimental not enabled
Screenshot 2024-12-29 at 12 32 23

Experimental enabled 
Screenshot 2024-12-29 at 12 35 03

XLM
Screenshot 2024-12-29 at 12 35 49

### CODE REVIEW

File: packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts [hunk 1]
```diff
@@ -64,7 +65,7 @@ export const useCoinmarketFormActions = <T extends CoinmarketSellExchangeFormPro
 }: CoinmarketUseFormActionsProps<T>): CoinmarketUseFormActionsReturnProps => {
     const { symbol } = account;
     const { shouldSendInSats } = useBitcoinAmountUnit(symbol);
-    const accounts = useSelector(selectAccounts);
+    const { accounts } = useAccounts();
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts]: what is the reason for this refactor? I do not see benefit of using this hook

**Review by tomasklim — CHANGES_REQUESTED** [review]
This PR is too complicated, I would not add this logic to app. Just allow to enable networks when it is enabled in experimental features. That's enough. 

Check https://github.com/trezor/trezor-suite/pull/13634/commits/d6da7cc46fac12c3ea63069bf3e6adc1e10b2a03

File: packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts]: oh I see. Please revert it

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -5000,6 +5005,14 @@ export default defineMessages({
         defaultMessage:
             'Access the NFTs stored in your wallet. Currently available for EVM-based chains only.',
     },
+    TR_EXPERIMENTAL_ETHEREUM_L2_SUPPORT: {
+        id: 'TR_EXPERIMENTAL_ETHEREUM_L2_SUPPORT',
+        defaultMessage: 'Support for Ethereum L2 networks (Optimism, Arbitrum One, Base)',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]:
```suggestion
        defaultMessage: 'Support for Ethereum L2 networks (Base, Optimism, Arbitrum One)',
```

File: packages/suite/src/support/messages.ts [hunk 3]
```diff
@@ -5000,6 +5005,14 @@ export default defineMessages({
...
+    },
+    TR_EXPERIMENTAL_ETHEREUM_L2_SUPPORT_DESCRIPTION: {
+        id: 'TR_EXPERIMENTAL_ETHEREUM_L2_SUPPORT_DESCRIPTION',
+        defaultMessage: 'Access your Optimism, Arbitrum One, and Base accounts.',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: I think we do not use `my`, `your` in the app

So please change it to something like `Allows to enable Base, Optimism and Arbitrum one networks.`

File: packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts (hunk 1 above)
Comment (enjojoy) [reply packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts]: Since we agreed to not filter already discovered accounts I will remove this change

File: packages/suite/src/support/messages.ts (hunk 2 above)
Comment (enjojoy) [reply packages/suite/src/support/messages.ts]: Why like that? If the order matters I'd put it alphabetically (Arbitrum One, Base, Optimism)

File: packages/suite/src/support/messages.ts (hunk 3 above)
Comment (enjojoy) [reply packages/suite/src/support/messages.ts]: I'll say that it enables discovery and creation of those accounts

Comment (tomasklim) [reply packages/suite/src/support/messages.ts]: just discovery is enough I think, the accounts "exist", we do not create them, I will change it and merge it. thanks

File: packages/suite/src/support/messages.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/support/messages.ts]: Base is probably most popular but yea lets stick to order in networks config

File: packages/suite/src/support/messages.ts (hunk 3 above)
Comment (tomasklim) [reply packages/suite/src/support/messages.ts]: fixed

**Review by tomasklim — APPROVED** [review]
LGTM

File: packages/suite/src/actions/suite/constants/suiteConstants.ts [hunk 4]
```diff
@@ -1,3 +1,5 @@
+import { NetworkSymbol } from '@suite-common/wallet-config';
+
```
Comment (adderpositive) [inline packages/suite/src/actions/suite/constants/suiteConstants.ts]:
```suggestion
import type { NetworkSymbol } from '@suite-common/wallet-config';

```

File: packages/suite/src/actions/suite/constants/suiteConstants.ts [hunk 5]
```diff
@@ -35,3 +37,4 @@ export const LOCK_TYPE = {
 export const REQUEST_DEVICE_RECONNECT = '@suite/request-device-reconnect';
 export const SET_EXPERIMENTAL_FEATURES = '@suite/set-experimental-features';
 export const SET_SIDEBAR_WIDTH = '@suite/set-sidebar-width';
+export const EXPERIMENTAL_L2_NETWORKS = ['op', 'arb', 'base'] as NetworkSymbol[];
```
Comment (adderpositive) [inline packages/suite/src/actions/suite/constants/suiteConstants.ts]:
```suggestion
export const EXPERIMENTAL_L2_NETWORKS: readonly NetworkSymbol[] = ['op', 'arb', 'base'];
```

**Review by adderpositive — CHANGES_REQUESTED** [review]
I am not able to add LTC account in Buy flow, if LTC account is not enabled.

File: packages/suite/src/hooks/settings/useNetworkSupport.ts [hunk 6]
```diff
@@ -5,14 +5,28 @@ import { hasBitcoinOnlyFirmware } from '@trezor/device-utils';
...
+        selectHasExperimentalFeature('ethereum-l2-support'),
+    );
+    const enabledNetworks = useSelector(selectEnabledNetworks);
 
-    const mainnets = getMainnets(isDebug);
+    const mainnets = getMainnets(isDebug).filter(
+        network =>
+            isEthereumL2SupportEnabled ||
+            !EXPERIMENTAL_L2_NETWORKS.includes(network.symbol) ||
+            enabledNetworks.includes(network.symbol),
```
Comment (adderpositive) [inline packages/suite/src/hooks/settings/useNetworkSupport.ts]: Is this correct? In my point of view in `mainnets` should be all symbols (except L2 if not turned on) regardless `enabledNetworks`. `enabledNetworks` are defined by user actions, if I get it right. E.g. VTC is not in `enabledNetworks`, but it is supported network.

**Review by adderpositive — CHANGES_REQUESTED** [review]

**Comment by adderpositive** [comment]
> I cannot add an LTC account in the Buy flow if the LTC account is not enabled.

image

File: packages/suite/src/hooks/settings/useNetworkSupport.ts (hunk 6 above)
Comment (tomasklim) [reply packages/suite/src/hooks/settings/useNetworkSupport.ts:28]: you are right, last minute change

**Comment by adderpositive** [comment]
> I am not able to add LTC account in Buy flow, if LTC account is not enabled.

I'm sorry 🫣, it works 👌.

File: packages/suite/src/hooks/settings/useNetworkSupport.ts (hunk 6 above)
Comment (tomasklim) [reply packages/suite/src/hooks/settings/useNetworkSupport.ts]: 9f439c53605ebe7d6b78d755acc509dc37c44d61

File: packages/suite/src/actions/suite/constants/suiteConstants.ts (hunk 5 above)
Comment (tomasklim) [reply packages/suite/src/actions/suite/constants/suiteConstants.ts]: 9f439c53605ebe7d6b78d755acc509dc37c44d61

File: packages/suite/src/actions/suite/constants/suiteConstants.ts (hunk 4 above)
Comment (tomasklim) [reply packages/suite/src/actions/suite/constants/suiteConstants.ts]: 9f439c53605ebe7d6b78d755acc509dc37c44d61

**Review by adderpositive — APPROVED** [review]
