### PR TITLE
fix(suite): only ASCII characters in device label

### LINKED ISSUE #8604: Restrict sending non-ASCII characters to Trezor as a name/label
Screenshot 2023-05-31 at 8 18 25

When changing name of the device, user can input there any characters (including emojis). However, Trezor [supports](https://github.com/trezor/trezor-firmware/blob/master/core/embed/lib/fonts/font_roboto_bold_20.c) only 7-bit ASCII (code points 32-126) characters.

Suite shouldn't allow sending unsupported characters to Trezor. 

If user would click on "edit name", there should be a warning saying there are unsupported characters in the input field.

_Unsupported characters in device name. Please use [standard ASCII characters](https://trezor.io/learn/a/trezor-suite-settings#ASCII-chars) only._

### PR DESCRIPTION
**Pull request by AdamSchinzel**
Added check so that label can only have ASCIII characters.

## Description

Used `isAscii` to check if label has only ASCII characters.

Translations changed: `TR_LABEL_REQUIREMENTS`
Translations added: `TR_LABEL_ERROR_LENGHT`, `TR_LABEL_ERROR_CHARACTERS`

## Related Issue

Resolve #8604 

## Screenshots:

Device settings:
Screenshot 2023-07-27 at 11 20 15 AM

Onboarding:
Screenshot 2023-07-27 at 11 22 52 AM

### CODE REVIEW

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -4870,10 +4870,20 @@ export default defineMessages({
...
+        defaultMessage:
+            'Names can be up to {length} characters and only characters of the English alphabet are allowed.',
+        description: 'How many characters may be in device label and of what type.',
+    },
+    TR_LABEL_ERROR_LENGHT: {
+        id: 'TR_LABEL_REQUIREMENTS',
+        defaultMessage: 'Name must be {length} characters or less',
+    },
+    TR_LABEL_ERROR_CHARACTERS: {
+        id: 'TR_LABEL_REQUIREMENTS',
```
Comment (matejkriz) [inline packages/suite/src/support/messages.ts]: beware of the id's, it has to be the same as the key...
```suggestion
        id: 'TR_LABEL_ERROR_LENGHT',
        defaultMessage: 'Name must be {length} characters or less',
    },
    TR_LABEL_ERROR_CHARACTERS: {
        id: 'TR_LABEL_ERROR_CHARACTERS',
```

**Comment by Hannsek** [comment]
[Again](https://github.com/trezor/trezor-suite/pull/8793#issuecomment-1609407348), please use this text:
Unsupported characters in device name. Please use [standard ASCII characters](https://trezor.io/learn/a/trezor-suite-settings#ASCII-chars) only.

**Comment by AdamSchinzel** [comment]
> [Again](https://github.com/trezor/trezor-suite/pull/8793#issuecomment-1609407348), please use this text: Unsupported characters in device name. Please use [standard ASCII characters](https://trezor.io/learn/a/trezor-suite-settings#ASCII-chars) only.

Do you mean for the error message at onboarding? It's is really long to even fit it in and most users even don't know what ASCII is and not sure that giving them a link would help much.

Also we are giving the user instant feedback when validating the input value so he should not right away what character he typed is unsupported.

I have discussed the copy with @matejkriz and he said it is okey for now.

**Comment by Hannsek** [comment]
We should provide users with the information which are the supported characters. The info is in the knowledge-base article.

During the onboarding, there is plenty of space for two lines text.

But if you see it as a problem, can we, at least put the link under "Unsupported characters".

+ in settings, we can put there "Learn more" button with the same link.

File: packages/suite/src/views/onboarding/steps/Final/index.tsx [hunk 2]
```diff
@@ -35,6 +36,10 @@ const StyledButton = styled(Button)`
     }
 `;
 
+const RenameButton = styled(Button)`
+    height: 48px;
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/Final/index.tsx]: It will be safer to use `INPUT_HEIGHTS.large`. In case we change input height in the future, the button will stay aligned.

File: packages/suite/src/views/onboarding/steps/Final/index.tsx [hunk 3]
```diff
@@ -232,27 +256,35 @@ export const FinalStep = () => {
...
                             <Input
+                                width={250}
                                 noTopLabel
-                                noError
                                 value={label}
+                                bottomText={error}
                                 placeholder={DEFAULT_LABEL}
-                                inputState={label.length > MAX_LABEL_LENGTH ? 'error' : undefined}
+                                inputState={
+                                    label.length > MAX_LABEL_LENGTH || !isAscii(label)
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/Final/index.tsx]:
```suggestion
                                    error
```

File: packages/suite/src/support/messages.ts [hunk 4]
```diff
@@ -4870,10 +4870,20 @@ export default defineMessages({
...
-        defaultMessage: 'Names can be up to {length} characters.',
-        description: 'How many characters may be in device label.',
+    TR_LABEL_REQUIREMENTS: {
+        id: 'TR_LABEL_REQUIREMENTS',
+        defaultMessage:
+            'Names can be up to {length} characters and only characters of the English alphabet are allowed.',
+        description: 'How many characters may be in device label and of what type.',
+    },
+    TR_LABEL_ERROR_LENGHT: {
+        id: 'TR_LABEL_ERROR_LENGHT',
```
Comment (komret) [inline packages/suite/src/support/messages.ts]: Typo in `LENGHT` -> `LENGTH`.

File: packages/suite/src/views/onboarding/steps/Final/index.tsx [hunk 5]
```diff
@@ -158,6 +166,22 @@ export const FinalStep = () => {
         setState(null);
     };
 
+    const onChange = (value: string) => {
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/Final/index.tsx]: It looks like the original change handler was typed incorrectly. I suggest typing it this way and just passing the function name to the `onChange` prop instead of inlining it.

```suggestion
    const handleChange: React.ChangeEventHandler<HTMLInputElement> = ({ target: { value } }) => {
```
Also, `handleChange` sounds like a better function name than `onChange`, but I'll leave that up to you.

File: packages/suite/src/views/settings/device/DeviceLabel.tsx
Comment (komret) [inline packages/suite/src/views/settings/device/DeviceLabel.tsx:1]: There is a lot of repeated code. Could you move the input and the button to a separate component? `ActionInput` could then be removed altogether.

File: packages/suite/src/views/onboarding/steps/Final/index.tsx [hunk 6]
```diff
@@ -232,27 +256,35 @@ export const FinalStep = () => {
...
+                            <RenameButton
                                 onClick={async () => {
                                     await onRename();
                                 }}
                                 isDisabled={
-                                    isDeviceLocked || !label || label.length > MAX_LABEL_LENGTH
+                                    isDeviceLocked ||
+                                    !label ||
+                                    label.length > MAX_LABEL_LENGTH ||
+                                    !isAscii(label)
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/Final/index.tsx]:
```suggestion
                                    !!error
```

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/onboarding/steps/Final/index.tsx (hunk 5 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/onboarding/steps/Final/index.tsx]: We maybe should introduce some code guidelines regarding this because I saw at least 3 different implementations of onChange functions

File: packages/suite/src/views/settings/device/DeviceLabel.tsx
Comment (AdamSchinzel) [reply packages/suite/src/views/settings/device/DeviceLabel.tsx:1]: Not sure about this, in terms of styling they are really different both input and button and moving them to separate component would not reduce the amount of code much.

File: packages/suite/src/views/onboarding/steps/Final/index.tsx [hunk 7]
```diff
@@ -35,6 +46,10 @@ const StyledButton = styled(Button)`
     }
 `;
 
+const RenameButton = styled(Button)`
+    height: ${({ variant }) => `${INPUT_HEIGHTS[variant as InputVariant]}px`};
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/Final/index.tsx]: You used a `Button` prop here, which is `undefined`. What I meant is this:

```suggestion
    height: ${INPUT_HEIGHTS.large}px;
```

It is not dynamic, but at least the value is set in one place.

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/onboarding/steps/Final/index.tsx (hunk 5 above)
Comment (komret) [reply packages/suite/src/views/onboarding/steps/Final/index.tsx]: Agreed! I don't know if you've seen our [code style guide](https://www.notion.so/satoshilabs/Code-style-guide-4cf109fe3c0d4d65a42dbd82ba4b0104). This is indeed not covered, feel free to add a proposal.

File: packages/suite/src/views/settings/device/DeviceLabel.tsx
Comment (komret) [reply packages/suite/src/views/settings/device/DeviceLabel.tsx:1]: I think it's a good opportunity to unify some small differences. The layout difference can be dealt with by a custom prop or styles passed into the component via `className` prop.

I think it should be possible, but I haven't tried. If not, at least the logic can be separated into a hook.

File: packages/suite/src/components/suite/Settings/components/ActionColumn.tsx [hunk 8]
```diff
@@ -19,7 +19,7 @@ export const ActionColumn = styled.div`
 
 const InputWrapper = styled.div`
     margin: 4px 0 4px 4px;
-    width: 170px;
+    width: 250px;
```
Comment (tomasklim) [inline packages/suite/src/components/suite/Settings/components/ActionColumn.tsx]: Looks like a big change to me. We allow 16 chars, why to have such a big input. Error can be `Unsupported characters`, thats it

Screenshot 2023-08-02 at 8 29 23

File: packages/suite/src/views/settings/device/DeviceLabel.tsx [hunk 9]
```diff
@@ -25,14 +26,33 @@ export const DeviceLabel = ({ isDeviceLocked }: DeviceLabelProps) => {
         applySettings: deviceSettingsActions.applySettings,
     });
     const { anchorRef, shouldHighlight } = useAnchor(SettingsAnchor.DeviceLabel);
+    const { translationString } = useTranslation();
```
Comment (tomasklim) [inline packages/suite/src/views/settings/device/DeviceLabel.tsx]: You can store just an error key in `error` state and use translation component with value `length: 16` even though the string is different. It would in my opinion make it little bit more easier to read

File: packages/suite/src/views/onboarding/steps/Final/index.tsx [hunk 10]
```diff
@@ -232,27 +266,24 @@ export const FinalStep = () => {
...
-                                    setLabel(event.currentTarget.value)
-                                }
+                                inputState={error ? 'error' : undefined}
+                                onChange={handleChange}
                                 data-test="@settings/device/label-input"
                             />
-                            <Button
+                            <RenameButton
                                 onClick={async () => {
                                     await onRename();
```
Comment (tomasklim) [inline packages/suite/src/views/onboarding/steps/Final/index.tsx]: we miss analytics here ☹️ is it possible to reuse DeviceLabel component here somehow? instead of the duplication

if not, lets add analytics here please

**Review by tomasklim — DISMISSED** [review]

File: packages/suite/src/views/settings/device/DeviceLabel.tsx (hunk 9 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/settings/device/DeviceLabel.tsx]: I saw it used like this in other onChange functions so I would keep it like that

File: packages/suite/src/views/onboarding/steps/Final/index.tsx (hunk 10 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/onboarding/steps/Final/index.tsx]: Will do it when creating new component that will be reused in settings and onboarding

File: packages/suite/src/components/suite/Settings/components/ActionColumn.tsx [hunk 11]
```diff
@@ -19,7 +19,7 @@ export const ActionColumn = styled.div`
 
 const InputWrapper = styled.div`
     margin: 4px 0 4px 4px;
-    width: 170px;
+    width: 210px;
```
Comment (tomasklim) [inline packages/suite/src/components/suite/Settings/components/ActionColumn.tsx]: It is really needed? 16 chars can fit into 170px

Comment (AdamSchinzel) [reply packages/suite/src/components/suite/Settings/components/ActionColumn.tsx]: That is true but error messages will be splitted into two lines. I think we don't want that.

Comment (AdamSchinzel) [reply packages/suite/src/components/suite/Settings/components/ActionColumn.tsx]: I discussed this with @Hermez-cz and basically he said that design is not a priority now since we're going to have new design in the upcoming months

Comment (Hannsek) [reply packages/suite/src/components/suite/Settings/components/ActionColumn.tsx]: Can you post here a screen shots of both solutions?

Comment (AdamSchinzel) [reply packages/suite/src/components/suite/Settings/components/ActionColumn.tsx]: `210px`:
Screenshot 2023-08-03 at 3 51 39 PM
Screenshot 2023-08-03 at 3 50 23 PM


`170px`:
Screenshot 2023-08-03 at 3 52 35 PM
Screenshot 2023-08-03 at 3 52 23 PM

Comment (Hannsek) [reply packages/suite/src/components/suite/Settings/components/ActionColumn.tsx]: Thanks! I would use the shorter one as displaying the message seems corner-case-ish.

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+import styled, { css } from 'styled-components';
+
+import { Button, INPUT_HEIGHTS, Input } from '@trezor/components';
+import { Translation } from 'src/components/suite';
+import { useTranslation } from 'src/hooks/suite';
+import { MAX_LABEL_LENGTH } from 'src/constants/suite/device';
+import { SCREEN_SIZE } from '@trezor/components/src/config/variables';
+import { isAscii } from '@trezor/utils';
+
+interface ChangeDeviceLabelProps {
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: Put the interface right above the component please, see [discussion on file structure](https://www.notion.so/satoshilabs/Components-9159b639d21b43ef8b66be150854b6b6).

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx:1]: Nice! Maybe more logic could be moved into the component to avoid duplication? `error`, `setError`, `label`, `setLabel`, and `isButtonDisabled`.

File: packages/suite/src/views/settings/device/DeviceLabel.tsx [hunk 13]
```diff
@@ -26,9 +20,8 @@ export const DeviceLabel = ({ isDeviceLocked }: DeviceLabelProps) => {
         applySettings: deviceSettingsActions.applySettings,
     });
     const { anchorRef, shouldHighlight } = useAnchor(SettingsAnchor.DeviceLabel);
-    const { translationString } = useTranslation();
 
-    const [label, setLabel] = useState('');
+    const [label, setLabel] = useState<string>('');
```
Comment (komret) [inline packages/suite/src/views/settings/device/DeviceLabel.tsx]: The type can be inferred from the default state, not necessary to be explicit here.

File: packages/suite/package.json [hunk 14]
```diff
@@ -65,7 +65,7 @@
         "@trezor/suite-storage": "workspace:*",
         "@trezor/type-utils": "workspace:*",
         "@trezor/urls": "workspace:*",
-        "@trezor/utils": "workspace:*",
+        "@trezor/utils": "workspace:^",
```
Comment (komret) [inline packages/suite/package.json]: Why this change? It does not seem related.

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 15]
```diff
@@ -0,0 +1,118 @@
...
+                margin: 0;
+            }
+        `}
+`;
+
+export const ChangeDeviceLabel = ({
+    label,
+    error,
+    isButtonDisabled,
+    isInputDisabled,
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: I know it was here originally, but I don't think we need to disable the input. The `isLocked` state is usually very short-lived. You can remove it so that it works the same in both instances.

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 16]
```diff
@@ -0,0 +1,118 @@
...
+    placeholder,
+    isVertical,
+    setLabel,
+    setError,
+    handleOnClick,
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: Please rename to `onClick`. We typically use `onClick` for a prop name and `handleClick` for function name.

Also, there is some repeated logic in the parent components that can be moved inside this one. If the parent component needs to do some additional logic (e.g. `setState` in `FinalStep`), it can be passed in the `onClick` prop a called like this:

```ts
    const handleClick = () => {
        applySettings({ label });
        analytics.report({
            type: EventType.SettingsDeviceChangeLabel,
        });
        onClick?.()
    };
```

**Review by komret — CHANGES_REQUESTED** [review]
It is already looking better, but I think we can remove even more code!

File: packages/suite/package.json (hunk 14 above)
Comment (AdamSchinzel) [reply packages/suite/package.json]: Not sure, when I added the package Typescript was complaining that it is not in the package so I installed it with yarn to suite but seems to not be needed...

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/ChangeDeviceLabel.tsx:1]: Was thinking about it the first time and I guess it can be done because we are still introducing the `isVertical` prop. Also moved `placeholder`

File: packages/suite/package.json (hunk 14 above)
Comment (komret) [reply packages/suite/package.json]: Maybe you just need to call `yarn build:libs` and it will work. You are not importing anything from the package, so I don't think the change is necessary. Also make sure `yarn.lock` does not have any changes.

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx
Comment (komret) [reply packages/suite/src/components/suite/ChangeDeviceLabel.tsx:1]: Personally, I wouldn't mind leaving the placeholder as a prop because it is not really related to the layout.

File: packages/suite/package.json (hunk 14 above)
Comment (AdamSchinzel) [reply packages/suite/package.json]: Yes, thanks, putted back

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 17]
```diff
@@ -0,0 +1,123 @@
+import React, { useState } from 'react';
+import { analytics, EventType } from '@trezor/suite-analytics';
+import styled, { css } from 'styled-components';
+
+import { Button, INPUT_HEIGHTS, Input } from '@trezor/components';
+import { Translation } from 'src/components/suite';
+import { useDevice, useDispatch, useTranslation } from 'src/hooks/suite';
+import * as deviceSettingsActions from 'src/actions/settings/deviceSettingsActions';
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: This import pattern was used because of `useActions`, we can now simply do:

```suggestion
import { applySeetings } from 'src/actions/settings/deviceSettingsActions';
```

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 18]
```diff
@@ -0,0 +1,123 @@
...
+
+const StyledButton = styled(Button)<{ isVertical?: boolean; isDisabled: boolean }>`
+    height: ${INPUT_HEIGHTS.large}px;
+
+    ${props =>
+        props.isVertical &&
+        css`
+            min-width: 170px;
+            margin: 4px 0 4px 4px;
+            cursor: ${props.isDisabled ? 'not-allowed' : 'pointer'};
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: Not needed, let's use the default `Button` behaviour.

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 19]
```diff
@@ -0,0 +1,123 @@
...
+
+    return (
+        <>
+            <StyledInput
+                width={170}
+                isVertical={isVertical}
+                noTopLabel
+                bottomText={error}
+                value={label}
+                placeholder={placeholder || ''}
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: No problem if it is `undefined`.

```suggestion
                placeholder={placeholder}
```

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 20]
```diff
@@ -0,0 +1,123 @@
...
+                inputState={error ? 'error' : undefined}
+                onChange={handleChange}
+                data-test="@settings/device/label-input"
+            />
+            <StyledButton
+                isVertical={isVertical}
+                onClick={handleClick}
+                isDisabled={
+                    isDeviceLocked || (!placeholder && label === device?.label) || !!error || !label
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: I'd rather put this into a variable to keep the JSX simple.

File: packages/suite/src/views/onboarding/steps/Final/index.tsx [hunk 21]
```diff
@@ -180,7 +176,10 @@ export const FinalStep = () => {
                     </Heading>
                     {!state && (
                         <SetupActions>
-                            <StyledButton onClick={() => setState('rename')}>
+                            <StyledButton
+                                onClick={() => setState('rename')}
+                                isDisabled={isWaitingForConfirm}
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/Final/index.tsx]: Nice fix, but disable the Homescreen button as well.

**Review by komret — CHANGES_REQUESTED** [review]
Great job!
This PR now
- introduces new logic
- improves code
- fixes a bug where it was possible to interact with UI while awaiting confirmation on device

I added a few nitpicks to make it perfect.

Please rebase on develop, squash the refactor commits and give them some more meaningful message. (Using fixups usually makes this easier).

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 22]
```diff
@@ -0,0 +1,123 @@
...
+
+            @media (max-width: ${SCREEN_SIZE.SM}) {
+                width: 100%;
+                margin: 0;
+            }
+        `}
+`;
+
+interface ChangeDeviceLabelProps {
+    isDeviceLocked: boolean;
```
Comment (komret) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx:54]: Also, this could be checked inside the component.

Comment (AdamSchinzel) [reply packages/suite/src/components/suite/ChangeDeviceLabel.tsx:54]: Yes but then we would need to refactor every component in `SettingsDevice` so it's same for every component but it makes since there so I would leave this one as it is.

Comment (komret) [reply packages/suite/src/components/suite/ChangeDeviceLabel.tsx:54]: Not necessarily. The other child component use it directly, while this one is nested one level deeper. And also reused.

**Review by komret — APPROVED** [review]
