### PR TITLE
Fix/repeated anchor clicks

### LINKED ISSUE #4588: You can't switch devices by clicking on "Select device" button in notifications
**Describe the bug**
The "Select device" button in the notifications is not working. You can't switch between devices back and forth using these buttons. These buttons are also, in my opinion, not really neccessary, since you can switch devices more easily in the select wallet modal.

**Steps to reproduce:**
1. Have one device already connected to the Suite.
2. Connect another device and click on Notifications button
3. Show "All activity" notifications
4. Click on the "Select device" button within the first "Device XY connected" notification.
5. This should change the device.
6. Click on the other "Select device" button in the notifications.
5. Nothing happens.

**Info:**
 - Suite version: desktop 21.12.1 (4a5547dd0d5c3608718f736e2f34638dc427e2d4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.4 regular

**Expected result:**
Button should switch to the device I want to select.

**Actual result:**
"Select device" button is not switching to the device I want to switch.

**Screenshots:**
image

### LINKED ISSUE #4915: Anchor links are not highlighted on repeated clicks
**Describe the bug**
Anchor link works just fine but if I repeatedly click on an action (because I am dull or blind) it is not highlighted more, it even disappears. Usually it is solved in a way that the highlighted piece is animated a bit or it at least stays highlighted but I do not think it should just disappear.

**Info:**
 - Remembered Wallet: no
 - Suite Version: EAP v22.2.1 https://github.com/trezor/trezor-suite/commit/520802b8052d558de9c5f0ee55f9151ea5122eb4
 - OS: macOS 12.1

**How to reproduce**
1. Launch Suite and click on the Tor icon repeatedly
2. The anchor is highlighted only once but not repeatedly

**Expected behavior**
The anchor is highlighted more.

**Screenshots**
I am clicking on Tor once and it gets highlighted but on further clicks it is not:

a

### PR DESCRIPTION
**Pull request by tomasklim**
closes #4915, #4588

- fix(anchor): make it work on repeated clicks on the same app page
   - scroll listener cannot be added easily because it is also activated by auto anchor scrolling
   - click listener has to be added on `id="app"` div otherwise it behaves randomly (probably because of event propagation)
   - to make it work on the same page more times in a row, we need to delete the anchor from redux and set it there again. This is why it is wrapped in `setTimeout` in `goto` function to have bigger chance that "deleting" event is faster than "setting" event
- fix(anchor): do not reload device if the device is same
   - activating anchor from notification did not work properly because it also updated device on click. However, we do not need to update device if we do not navigate to different device
   - I was thinking about putting some `isSameDevice` check into `selectDevice` method. However, it can potentially break a lot of things, so I did not do that. It is not only `id` check but also `isRemembered`,... checks
- fix(suite): dont show not working notification buttons in notifications
   - when I was into playing with notifications, I found a bug which was already reported, so i fixed it here as it was easy

### CODE REVIEW

File: packages/suite/src/components/suite/NotificationRenderer/renderers/ActionRenderer.tsx [hunk 1]
```diff
@@ -19,19 +19,19 @@ const ActionRenderer = ({ render: View, ...props }: ActionRendererProps) => {
         case DEVICE.CONNECT:
             action = {
                 label: 'TR_SELECT_DEVICE',
-                onClick: () => (!seen ? selectDevice(device) : undefined),
```
Comment (matejkriz) [inline packages/suite/src/components/suite/NotificationRenderer/renderers/ActionRenderer.tsx:22]: do you have any idea why the condition was originally there?

File: packages/suite/src/components/suite/NotificationRenderer/renderers/TransactionRenderer.tsx [hunk 2]
```diff
@@ -55,7 +56,10 @@ const TransactionRenderer = ({ render: View, ...props }: TransactionRendererProp
             }}
             action={{
                 onClick: () => {
-                    selectDevice(accountDevice || device);
+                    const deviceToSelect = accountDevice || device;
+                    if (deviceToSelect?.id !== currentDevice?.id) {
```
Comment (matejkriz) [inline packages/suite/src/components/suite/NotificationRenderer/renderers/TransactionRenderer.tsx:60]: note to myself: try it

File: packages/suite/src/components/suite/NotificationRenderer/renderers/ActionRenderer.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/NotificationRenderer/renderers/ActionRenderer.tsx:22]: c623bae4699c4786dffeea2ca49d07f87086155c

File: packages/suite/src/components/suite/NotificationRenderer/renderers/TransactionRenderer.tsx (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/NotificationRenderer/renderers/TransactionRenderer.tsx:60]: @matejkriz try it

File: packages/suite/src/components/suite/NotificationRenderer/renderers/ActionRenderer.tsx (hunk 1 above)
Comment (matejkriz) [reply packages/suite/src/components/suite/NotificationRenderer/renderers/ActionRenderer.tsx:22]: nevermid, your approach looks good to me, let's try it

File: packages/suite/src/components/suite/NotificationRenderer/renderers/TransactionRenderer.tsx (hunk 2 above)
Comment (matejkriz) [reply packages/suite/src/components/suite/NotificationRenderer/renderers/TransactionRenderer.tsx:60]: 👌

**Review by matejkriz — APPROVED** [review]
it's working nicely!
