### PR TITLE
Fix/android navbar

### LINKED ISSUE #8065: Android weird menu behaviour
open android version of the app
menu seems to be higher than it should be
click on settings and localize
menu is too low

https://user-images.githubusercontent.com/84183817/231464992-9dfb5257-ed9c-4556-98fc-382e486ab401.mp4

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- android navigation resize bug fixed
  -  BottomSheet was using `useAnimatedKeyboard` hook which is only [experimental for Android](https://www.reanimated2.com/docs/next/api/hooks/useAnimatedKeyboard). This hook was removed and used KeyboardAvoidingView instead.
- bottom tab bar made responsive and  centered
- android bottom navigation bar changes color according to app color theme
## Related Issue

Resolve #8065 

### before:
image
### after:

Snímek obrazovky 2023-04-13 v 12 57 16

### CODE REVIEW

File: suite-native/atoms/src/Sheet/BottomSheetContainer.tsx [hunk 1]
```diff
@@ -18,8 +22,18 @@ const BottomSheetGestureHandler = gestureHandlerRootHOC<{ children: ReactNode }>
...
-        <BottomSheetGestureHandler>{children}</BottomSheetGestureHandler>
-    </RNModal>
-);
+export const BottomSheetContainer = ({ children, isVisible, onClose }: SheetProps) => {
+    const { applyStyle } = useNativeStyles();
+    return (
+        <RNModal transparent visible={isVisible} onRequestClose={onClose}>
+            <BottomSheetGestureHandler>
+                <KeyboardAvoidingView
+                    behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
```
Comment (juriczech) [inline suite-native/atoms/src/Sheet/BottomSheetContainer.tsx:31]: Same thing is in xpubhint component. We could create a component out of it but the only benefit would be to reuse 2 lines so feel free to resolve if you don't think it's beneficial

**Review by juriczech — APPROVED** [review]

File: suite-native/navigation/src/components/Screen.tsx [hunk 2]
```diff
@@ -68,11 +70,17 @@ export const Screen = ({
...
+    const theme = useActiveColorScheme();
 
     useEffect(() => {
         // this prevents some weird flashing of splash screen on Android during screen transitions
         SystemUI.setBackgroundColorAsync(backgroundCSSColor);
-    }, [backgroundCSSColor]);
+
+        if (Platform.OS === 'android') {
+            NavigationBar.setBackgroundColorAsync(backgroundCSSColor);
+            NavigationBar.setButtonStyleAsync(theme === 'standard' ? 'dark' : 'light');
```
Comment (Nodonisko) [inline suite-native/navigation/src/components/Screen.tsx]: maybe do it here in same style as `barStyle` above is done?

File: suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts [hunk 3]
```diff
@@ -38,7 +37,6 @@ export const useBottomSheetAnimation = ({
     const colorOverlay = utils.transparentize(0.3, utils.colors.backgroundNeutralBold);
     const translatePanY = useSharedValue(SCREEN_HEIGHT);
     const animatedTransparency = useSharedValue(transparency);
-    const keyboard = useAnimatedKeyboard();
```
Comment (Nodonisko) [inline suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts:41]: Can you please briefly explain what was wrong here?

Comment (PeKne) [reply suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts:41]: It is described in the PR description:

> BottomSheet was using useAnimatedKeyboard hook which is only [experimental for Android](https://www.reanimated2.com/docs/next/api/hooks/useAnimatedKeyboard). This hook was removed and used KeyboardAvoidingView instead.

The useAniamtedKeyboard does not work as expected on Android.

File: suite-native/navigation/src/components/Screen.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/navigation/src/components/Screen.tsx]: fixed c3461d799

**Review by Nodonisko — APPROVED** [review]

File: suite-native/atoms/src/Sheet/BottomSheetContainer.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/atoms/src/Sheet/BottomSheetContainer.tsx:31]: I think there is still no need for an extra component. If we will use it again in the future, let's create it.
