### PR TITLE
Fix: mobile entropy check

### LINKED ISSUE #18994: Onboarding - entropy check false positive
**Describe the bug**
When you switch from suite app to another during the seed/wallet creation process in onboarding, the entropy check can be false positive. More info here https://satoshilabs.slack.com/archives/C03H2Q5MX51/p1747385915410679
Sentry report here https://satoshilabs.sentry.io/issues/6573225725/events/0cfc453e0f2c4f898684bffd18b33730/

**Info:**

- Mobile Suite Version: 25.5.1
- OS: Android

**How to reproduce**

1. Connect device with fw installed
2. Continue in onboarding to wallet creation
3. During the wallet creation switch to different app and back
4. You can see the entropy security check fails

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Fix problem where Connect considers cancelled backup check an entropy check failure :scream: 
Happens only on mobile, because `TrezorConnect.resetDevice` is called with `skip_backup: false`, so that the backup check is all part of the resetDevice call.

## Related Issue

Resolve #18994

## Screenshots:

Start wallet creation → entropy check succeeds → close UI during backup → repeat wallet creation, finish backup: 
[part1.webm](https://github.com/user-attachments/assets/e37d52b3-caef-4b13-b369-775c2e60ca50)
[part2.webm](https://github.com/user-attachments/assets/909c4250-9fcd-4691-980e-d5e7202cb017) _(had to stop to rewatch part1 so I could pass backup check xD )_

Mocked entropy check failure error (during wallet creation)
[entropy check failure.webm](https://github.com/user-attachments/assets/98a62beb-cec6-4ec9-88ff-a362b16fa90e)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/mobile-entropy-check&lookback=7)

### CODE REVIEW

**Comment by Lemonexe** [comment]
Will merge despite failing E2E tests: confirmed to be broken ([slack](https://satoshilabs.slack.com/archives/C03H2Q5MX51/p1747388172006409))

**Review by mroz22 — APPROVED** [review]
looks good

File: packages/connect/src/api/resetDevice.ts [hunk 1]
```diff
@@ -117,17 +119,26 @@ export default class ResetDevice extends AbstractMethod<'resetDevice', PROTO.Res
...
+            // permissible error.message during entropy check should be one of these: see ReadWriteError in packages/transport/src/transports/abstract.ts
             if (
                 error.cause === 'transport-error' &&
                 ERRORS_WITHOUT_DEVICE_INTERACTION.includes(error.message)
             ) {
                 throw error;
             }
+
+            // wallet backup flow may follow after successful entropy check, so don't consider errors thrown there as entropy check failure
+            if (this.isEntropyCheckSuccessful === true) throw error;
```
Comment (matejkriz) [inline packages/connect/src/api/resetDevice.ts:139]: Throw error if successful? Am I reading it right?

Comment (matejkriz) [reply packages/connect/src/api/resetDevice.ts:139]: Oh, now I get it reading rest of the catch block...

Comment (Lemonexe) [reply packages/connect/src/api/resetDevice.ts:139]: No, this is in `catch` block.
So if any error happens when `isEntropyCheckSuccessful`, rethrow the same error, rather than replacing it with `throw Failure_EntropyCheck`

**Review by matejkriz — APPROVED** [review]
👏
