### PR TITLE
fix(suite-native): connect device analytics improvements

### LINKED ISSUE #16446: Fix reporting of `device_connect` analytics event on mobile
I found that we are reporting the device_connect event questionably.

- If connected physical Trezor had view-only enabled, `device_connect` is not reported anymore for that device if you plug it in. 
- If you are adding new Passphrase wallets, every new wallet reporting `device_connect`
- There is an extra condition to report only if `isDeviceReadyToUseAndAuthorized` is true. So we don't report connection in bootloader, or with not supported FW, or uninitialized Trezor...

I guess we want to **report every time user plug in the physical Trezor**.

### LINKED ISSUE #16698: Data Analytics: Connected Device Mode
We would like to track the mode of connected device, especially one indicating device is yet to be initialised.
There should be the new parameter `mode` of event [Connect Device](https://www.notion.so/satoshilabs/connect_device-f1106223e5044c04a26029139e9475af) similar to the [desktop Suite](https://www.notion.so/satoshilabs/mode-b44a47f491a5498ba016135c894df568?pvs=4).

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- [fix(suite-native): connect device analytics trigger](https://github.com/trezor/trezor-suite/commit/e62b69bf48df247767bc2715123024c0675fbfde): `device_connect` analytics event was fixed, now it is reported for every physical device connection and nothing else (solution inspired by desktop)
  - Resolves #16446 
- [feat(suite-native): report device mode on connection](https://github.com/trezor/trezor-suite/commit/4e6822343a051d4902c5de5051fdbe467c47c008): `device_connect` event now contains `mode` prop telling in which mode was device connected (` 'normal' | 'bootloader' | 'initialize' | 'seedless'`)
  -  Resolves #16698 
  - analytics Notion documentation: [Changelog link](https://www.notion.so/satoshilabs/Mobile-app-data-analytics-changelog-946307159a294bcdb90b94e90eefd292?pvs=4#1e0dc52606068078902efd92626a71c7)

________________
🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/connect-device-analytics-event&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/connect-device-analytics-event&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/connect-device-analytics-event&lookback=7)

### CODE REVIEW

**Comment by PeKne** [comment]
New events mentioned in the 📓 Notion analytics changelog: https://www.notion.so/satoshilabs/Mobile-app-data-analytics-changelog-946307159a294bcdb90b94e90eefd292?pvs=4

File: suite-native/device/src/middlewares/deviceMiddleware.ts [hunk 1]
```diff
@@ -78,11 +84,32 @@ export const prepareDeviceMiddleware = createMiddlewareWithExtraDeps(
...
             case DEVICE.CONNECT:
-            case DEVICE.CONNECT_UNACQUIRED:
+            case DEVICE.CONNECT_UNACQUIRED: {
                 if (isUsbDeviceConnectFeatureEnabled) {
                     dispatch(selectDeviceThunk(action.payload));
                 }
+
+                const {
+                    device: { features, mode },
+                } = action.payload;
```
Comment (yanascz) [inline suite-native/device/src/middlewares/deviceMiddleware.ts]: What about this?
```suggestion
                const { device } = action.payload;
                const { features, mode } = device;
```

That way you could replace three usages of `action.payload.device`.

**Review by yanascz — APPROVED** [review]

File: suite-native/device/src/middlewares/deviceMiddleware.ts (hunk 1 above)
Comment (PeKne) [reply suite-native/device/src/middlewares/deviceMiddleware.ts]: fixed and squashed
