### PR TITLE
fix(suite): close modal by clicking on ModalBackdrop

### LINKED ISSUE #20730: Missing option to close wallet switcher by clicking on the background.
Users can't get back to previous flow. For example they might be preparing transaction. And when the wallet switcher opens user can't get back /close the wallet switcher.

Image

### PR DESCRIPTION
**Pull request by OriginalEveres**
Fixes ability to close modal by clicking on Modal Backdrop.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20730

## Screenshots:
**BEFORE**

https://github.com/user-attachments/assets/a696c44f-6397-4cf9-ad54-125a4e04d30e

**AFTER**

https://github.com/user-attachments/assets/7b253f47-bbf4-4477-8ff7-761941451415

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/close-wallet-switcher-by-clicking-on-the-background&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/close-wallet-switcher-by-clicking-on-the-background&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/TrafficLightOffset.tsx [hunk 1]
```diff
@@ -24,8 +24,6 @@ const FixForNotBeingAbleToDragWindow = styled.div`
 
 const Container = styled.div<{ $offset: number }>`
     ${({ $offset }) => `padding-top: ${$offset}px;`}
-    width: 100%;
-    height: 100%;
```
Comment (OriginalEveres) [inline packages/suite/src/components/suite/TrafficLightOffset.tsx:28]: @jvaclavik was there any reason to include this? I tested it without it and it seems to ok in all use cases.

Otherwise this caused the issue of not being able to close the modal by clicking on the ModalBackdrop (since the InnerWrapper has `e.stopPropagation`).

**Review by Lemonexe — APPROVED** [review]
I verified on a macOS Suite that the bug is there on Desktop and not on Web, so it's really the trafiic light offset.
Did not test the fix, but LGTM

File: packages/suite/src/components/suite/TrafficLightOffset.tsx (hunk 1 above)
Comment (jvaclavik) [reply packages/suite/src/components/suite/TrafficLightOffset.tsx:28]: Sorry I don't know anymore, if you tested it well and it works, I'm fine with removing it

**Comment by martykan** [comment]
You broke the sidebar height! 🥲 

Screenshot 2025-08-19 at 09 28 38

**Comment by OriginalEveres** [comment]
> You broke the sidebar height! 🥲
> 
> Screenshot 2025-08-19 at 09 28 38

already fixed it in https://github.com/trezor/trezor-suite/pull/20855
