### PR TITLE
test: entropy check E2E Desktop & Web

### LINKED ISSUE #22545: E2E tests for entropy check failure
Currently, E2E tests can more or less naturally simulate all kinds of security check failures:
- revision check with user-env 2-main
- hash check with any user-env
- device authenticity check with any user-env && not debug keys enabled

But entropy check failure remains untestable, it always succeeds. For manual testing I am maintaining [this testing branch](https://github.com/trezor/trezor-suite/compare/develop...FW-check-UI-testing-branch), which allows you to fail any check with global variables in console – not suitable for E2E.

 So let's create a `process.env.SIMULATE_ENTROPY_CHECK_FAIL` that Connect will read and fail entropy test in a similar way as the testing branch.

TODO:
- [x] the new process env for connect to fail
  - let's simulate more kinds of error, to ensure correct behavior of [conditions like this](https://github.com/trezor/trezor-suite/blob/d0742f13ee2597436735b6e19be7e1ba538bb3ce/suite-common/wallet-core/src/device/deviceThunks.ts#L602). It's already covered by unit test, but why not E2E as well? 
- [x] make playwright Web E2E
- [x] make detox Android E2E

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

- create a hidden setting in deviceReducer to always fail entropy check with a specified result
- use it for a new Playwright test (Web + Desktop)
  - fix `window.store` on Desktop with a utility `ensureStoreOnDesktop`
- use it for a new Detox test (Android)
- small refactoring to prevent circular imports
- fix message system import in Detox runtime

This will ensure correct handling of a entropy check result: hard failures vs. soft failures, which has been notorically a problem in the past.

## Notes for QA

I have added the debug value to redux, but it should not play any role except in E2E tests.
So test that creating wallet is unaffected. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22545

## Screenshots

Just for reference, this is how the tested behaviors **should** look in app:

[web/desktop soft failure](https://github.com/user-attachments/assets/8c0ec5c2-c5f0-48e0-9f05-a7e3e84a76de)
[web/desktop hard failure](https://github.com/user-attachments/assets/84ff6b60-c2b5-4cea-a59d-85aa302a1ea6)
[native soft failure](https://github.com/user-attachments/assets/955a9d23-2780-434a-803c-af7c8470f01a)
[native hard failure](https://github.com/user-attachments/assets/d0f2768c-7ac8-4d4b-9248-b75546488fc4)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=test/entropy-check-E2E&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=test/entropy-check-E2E&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=test/entropy-check-E2E&lookback=7)

### CODE REVIEW

File: suite/e2e/support/enums/seedType.ts [hunk 1]
```diff
@@ -1,4 +0,0 @@
-export enum SeedType {
-    Default = 'single',
-    Advanced = 'shamir-advanced',
-}
```
Comment (Lemonexe) [inline suite/e2e/support/enums/seedType.ts:4]: Option `Default` was wrong ❌, until now there was no safeguard that the enum conforms.

It was also unnecessary, we can use strings directly in type safe manner:

Image

File: suite/e2e/support/testExtends/enhancePage.ts [hunk 2]
```diff
@@ -64,6 +70,13 @@ export const enhancePage = (page: Page): Page => {
         });
     };
 
+    page.ensureStoreOnDesktop = async () => {
+        await expect(async () => {
+            const store = await page.evaluate(() => window.store);
+            expect(store).toBeDefined();
+        }).toPass({ timeout: 5000 });
+    };
```
Comment (Lemonexe) [inline suite/e2e/support/testExtends/enhancePage.ts:79]: inspiration taken from `expectReduxObjectToEqual`.
It's a hack that overcomes known playwright bug. 
This can be later used in `onboardingPage` to unify behavior between Web & Desktop E2E tests

File: suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+            },
+            async ({ page, onboardingPage, devicePrompt, trezorUserEnvLink }) => {
+                await page.ensureStoreOnDesktop();
+
+                await page.evaluate(
+                    action => window.store.dispatch(action),
+                    deviceActions.setSimulatedEntropyCheckFail({
+                        success: false,
+                        payload: { code: 'Failure_EntropyCheck', error: 'SIMULATED ERROR' },
+                    }),
```
Comment (Lemonexe) [inline suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts:38]: note: [compare here](https://github.com/trezor/trezor-suite/blob/1954b9167c598bf80fd5e99f4a078286bb439abe/suite/e2e/support/pageObjects/onboarding/onboardingPage.ts#L198-L203). I think this is better – no need to pass the whole `actions` object to the renderer evaluation callback, when we can prepare the `action` object itself in Playwright runtime, and pass only that to the callback.

I did it mainly because `deviceActions` cannot be passed this way (unlike `SuiteActions`, here we use redux toolkit helpers which are non-serializable) , and also to avoid the eslint shadowing 🙂

File: suite-native/app/e2e/pageObjects/deviceOnboardingActions.ts [hunk 4]
```diff
@@ -128,6 +133,57 @@ class DeviceOnboardingActions {
         }
         await element(by.id('@thpSecurityCode/Input')).replaceText(code);
     }
+
```
Comment (Lemonexe) [inline suite-native/app/e2e/pageObjects/deviceOnboardingActions.ts:141]: both of the helpers below extracted from `deviceOnboarding.test.ts‎`

File: .github/workflows/template-suite-native-e2e-android.yml [hunk 5]
```diff
@@ -83,6 +83,11 @@ jobs:
           echo -e "\nenableHardenedMode: false" >> .yarnrc.yml
           yarn install
 
+      # Detox runtime may indirectly import the built config, and that would crash if message-system is not built
+      - name: Sign message system config
+        working-directory: ./suite-common/message-system
+        run: yarn sign-config
+
```
Comment (Lemonexe) [inline .github/workflows/template-suite-native-e2e-android.yml:90]: Because detox runtime doesn't have a bundler, whatever you import from `wallet-core` import also message system, and the code we have expects it to be built, and crashes otherwise ↓↓↓

Nobody has imported `wallet-core` here yet, so it was a trap just waiting for someone to fall in, luckily I solved exactly the same problem for Playwright a while ago in 667acf1f287ef67c7ee1821aa60b400e5230aa36 😆 

Note that we sign config in `template-suite-native-prepare-test-app-android.yml` but that's not enough, because the environment is not carried over to this job (just the cached apk build).

```
FAIL e2e/tests/entropyCheckFailT3T1.test.ts
  ● Test suite failed to run

    Cannot find module '../files/config.v1' from '../../suite-common/message-system/src/messageSystemThunks.ts'

    Require stack:
      /home/runner/work/trezor-suite/trezor-suite/suite-common/message-system/src/messageSystemThunks.ts
      /home/runner/work/trezor-suite/trezor-suite/suite-common/message-system/src/index.ts
      /home/runner/work/trezor-suite/trezor-suite/suite-common/device-authenticity/src/deviceAuthenticityThunks.ts
      /home/runner/work/trezor-suite/trezor-suite/suite-common/device-authenticity/src/index.ts
      /home/runner/work/trezor-suite/trezor-suite/suite-common/wallet-core/src/device/deviceReducer.ts
      /home/runner/work/trezor-suite/trezor-suite/suite-common/wallet-core/src/index.ts
      e2e/tests/entropyCheckFailT3T1.test.ts

      21 |     selectMessageSystemTimestamp,
      22 | } from './messageSystemSelectors';
    > 23 | import { jws as configJwsLocal } from '../files/config.v1';
```

File: suite-native/app/e2e/support/setup.ts [hunk 6]
```diff
@@ -114,12 +114,6 @@ export const openApp = async ({
     }
 };
 
-export function getModelFromEnv(): Model {
-    const envValue = process.env.EMULATOR_MODEL as Model;
-
-    return MODELS.includes(envValue) ? envValue : 'T3T1';
-}
```
Comment (Lemonexe) [inline suite-native/app/e2e/support/setup.ts:121]: moved to `utils`, where I feel it belongs.
But mainly to solve circular dependency – I want to use this in `deviceOnboardingActions.ts` but that's imported in `setup.ts`...

File: suite-native/app/e2e/tests/deviceOnboarding.test.ts [hunk 7]
```diff
@@ -60,48 +26,33 @@ const preloadedState = preparePreloadedReduxState(
     btcCoinEnabled,
 );
 
+const LONG_RUNNING_TEST_TIMEOUT = 3 * 60 * 1000; // [ms]
```
Comment (Lemonexe) [inline suite-native/app/e2e/tests/deviceOnboarding.test.ts]: default timeout it 2:00 `thrown: "Exceeded timeout of 120000 ms for a test.`
[in another PR](https://app.currents.dev/instance/8ZfShiF1SXfaHBBH) it takes 2:30 and it's fine, even though ti exceeds?

[but here](https://app.currents.dev/instance/ULLOgljMmLsM07Xh) it takes 2:47 and fails??

I don't know why it only started failing now, but evidently it needs a longer timeout 🐌 

Locally I observed that the flow really just takes long, there's no obvious delay which could be fixed.

File: suite-native/app/e2e/tests/entropyCheckFailT3T1.test.ts [hunk 8]
```diff
@@ -0,0 +1,68 @@
...
+import { onDeviceOnboarding } from '../pageObjects/deviceOnboardingActions';
+import { openApp, preparePreloadedReduxState, prepareTrezorEmulator } from '../support/setup';
+import { wait, waitForVisible } from '../support/utils';
+
+const getPreloadedState = (payload: DeviceReducerState['simulatedEntropyCheckFail']) =>
+    preparePreloadedReduxState(onboardingCompletedState, deviceChecksEnabledState, {
+        device: { ...deviceReducerInitialState, simulatedEntropyCheckFail: payload },
+    });
+
+const LONG_RUNNING_TEST_TIMEOUT = 3 * 60 * 1000; // [ms]
```
Comment (Lemonexe) [inline suite-native/app/e2e/tests/entropyCheckFailT3T1.test.ts]: this test shares the `startCreatingWallet` flow which takes long time, so [this also takes](https://app.currents.dev/instance/mOqBL8Jv6mQcTQ0M) over two minutes

File: suite-native/app/e2e/tests/entropyCheckFailT3T1.test.ts [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+                                code: 'Failure_EntropyCheck',
+                                error: 'device disconnected during action',
+                            },
+                        }),
+                    },
+                });
+                await onDeviceOnboarding.proceedToCreateOrRecoverCrossroads();
+                await onDeviceOnboarding.startCreatingWallet();
+
+                await waitForVisible(by.id('@toast'));
```
Comment (Vere-Grey) [inline suite-native/app/e2e/tests/entropyCheckFailT3T1.test.ts:62]: IMHO, would be good to assert the toast text
```suggestion
                await waitForVisible(by.id('@toast'));
                await detoxExpect(element(by.id('@toast'))).toHaveText('device disconnected during action')

File: suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts (hunk 3 above)
Comment (Vere-Grey) [reply suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts:38]: Nice, I made note for my next refactoring 👍

File: suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts [hunk 10]
```diff
@@ -0,0 +1,94 @@
...
+                    await onboardingPage.selectSeedType('12-words');
+                    await devicePrompt.confirmOnDevicePromptIsShown();
+                    await trezorUserEnvLink.pressYes();
+                });
+
+                await test.step('Land on entropy check failure', async () => {
+                    await expect(onboardingPage.deviceCompromisedModal).toBeVisible();
+                });
+            },
+        );
```
Comment (Vere-Grey) [inline suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts:53]: Since we are mocking that (setting in redux), it is stably and instantly shown right here?
I thought it is kind of unpredictable step that appears once the check is finished on background.

File: suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts [hunk 11]
```diff
@@ -0,0 +1,94 @@
...
+                await test.step('Start creating wallet', async () => {
+                    await onboardingPage.firmware.continueThroughFirmware();
+                    await onboardingPage.createWalletButton.click();
+                    await onboardingPage.selectSeedType('12-words');
+                    await devicePrompt.confirmOnDevicePromptIsShown();
+                    await trezorUserEnvLink.pressYes();
+                });
+
+                await test.step('Display error toast, but stay on the same screen (no device compromised)', async () => {
+                    await expect(page.getByTestId('@toast/error')).toBeVisible();
```
Comment (Vere-Grey) [inline suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts]: text assert improves value and also checks visibility

```suggestion
                    await expect(page.getByTestId('@toast/error')).toHaveText('device disconnected during action);
```

**Review by Vere-Grey — APPROVED** [review]
Well done 👍 
few suggestions and one question

File: suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts (hunk 10 above)
Comment (Lemonexe) [reply suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts:53]: Yes, entropy check is 100% predictable. I think you meant firmware hash check – that is done in background async.
Entropy check is takes place on device during creating wallet, and that does not complete until it's done.

File: suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts (hunk 11 above)
Comment (Lemonexe) [reply suite/e2e/tests/onboarding/t2t1/t2t1-entropy-check-failure.test.ts]: Done :heavy_check_mark:

File: suite-native/app/e2e/tests/entropyCheckFailT3T1.test.ts (hunk 9 above)
Comment (Lemonexe) [reply suite-native/app/e2e/tests/entropyCheckFailT3T1.test.ts:62]: Done :heavy_check_mark:

**Review by juriczech — APPROVED** [review]
LGTM on native & common
