### PR TITLE
chore(suite): bump version of the hookform/resolvers + fix the typing…

### LINKED ISSUE #9863: Dependencies: @hookform/resolvers
- update `@hookform/resolvers` to version `3.3.2+

**Issues:**
- https://github.com/react-hook-form/resolvers/releases/tag/v3.1.1
Screenshot 2023-11-06 at 16 03 03

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

This PR bumps version of the hookform/resolvers + fixies the typing error in the SignForm.

(The type of the form shall be always inferred from the validation scheme.)

### Sidenote:
This Sign & Verify forms shall be separate. This is wrong abstraction. This leads to many ifs (checks for `isSignPage`) all over the place effectively implementing both forms separately but in very messy way, smashed together.

This shall be refactored to implement those two forms separately. 

## Related Issue 

Resolve https://github.com/trezor/trezor-suite/issues/9863

### CODE REVIEW

File: packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts [hunk 1]
```diff
@@ -52,10 +34,7 @@ const signVerifySchema = yup.object<ValidationSchema<Omit<SignVerifyFields, 'isE
                 options.context?.accountNetwork &&
                 isAddressValid(value, options.context?.accountNetwork),
         )
-        .when('$isSignPage', {
-            is: false,
-            then: schema => schema.required(),
-        }),
+        .required(),
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts:37]: In both cases,`message` shall be required (both Verfy and Sing forms needs it).

File: packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts [hunk 2]
```diff
@@ -64,9 +43,21 @@ const signVerifySchema = yup.object<ValidationSchema<Omit<SignVerifyFields, 'isE
         is: false,
         then: schema => schema.required(),
     }),
-    hex: yup.boolean(),
+    hex: yup.boolean().required(),
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts:46]: This relates to the message and therefore shall be required for the very same reason as message is.

File: packages/suite/src/views/wallet/sign-verify/index.tsx [hunk 3]
```diff
@@ -167,16 +167,18 @@ const SignVerify = () => {
     }, [isSignPage, formValues.message, formValues.address, formValues.signature]);
 
     const onSubmit = async (data: SignVerifyFields) => {
+        console.log(data);
+
         const { address, path, message, signature, hex, isElectrum } = data;
 
-        if (isSignPage) {
+        if (isSignPage && path !== undefined) {
```
Comment (peter-sanderson) [inline packages/suite/src/views/wallet/sign-verify/index.tsx:172]: Those are hacky ifs that are required due to bad abstraction. Sign and Verfy forms shall be separate.

- Something that shall never happen (on Sign, the yup validation shall make `path` required`).
- Same for `signature` on the Verify version of the form.

File: suite-native/forms/package.json [hunk 4]
```diff
@@ -11,7 +11,7 @@
         "type-check": "tsc --build"
     },
     "dependencies": {
-        "@hookform/resolvers": "3.1.0",
+        "@hookform/resolvers": "3.3.2",
```
Comment (peter-sanderson) [inline suite-native/forms/package.json:14]: Is this safe to do for `suite-native`? Who shall I ask to approve this from the Mobile Team?

Comment (dahaca) [reply suite-native/forms/package.json:14]: Feel free to tag anyone from the mobile team, as far as I know @Nodonisko or @PeKne are the best contendors for that time of inquiry :D

Comment (matejkriz) [reply suite-native/forms/package.json:14]: you can tag whole @trezor/suite-mobile team or ask @Nodonisko

File: packages/suite/src/views/wallet/sign-verify/index.tsx [hunk 5]
```diff
@@ -297,7 +297,7 @@ const SignVerify = () => {
                             <Textarea
                                 maxLength={MAX_LENGTH_SIGNATURE}
                                 characterCount={{
-                                    current: formValues.signature.length,
+                                    current: formValues.signature?.length ?? 0,
```
Comment (dahaca) [inline packages/suite/src/views/wallet/sign-verify/index.tsx]: I would set it globally [here](https://github.com/trezor/trezor-suite/blob/5f4098a3bcdd4f3fb7f00dc9a7b9490426cd77e2/packages/components/src/components/form/Textarea/CharacterCount.tsx#L30) on the `suite-e` branch

**Review by dahaca — APPROVED** [review]

File: suite-native/forms/package.json (hunk 4 above)
Comment (Nodonisko) [reply suite-native/forms/package.json:14]: Should be safe, it's just minor version and we use hook form in super basic form only.
