### PR TITLE
fix(suite-native): flat graph for zero value

### LINKED ISSUE #10632: Graph shows balances when the total balance is "0"
Steps to reproduce:
Connect All seed device to mobile app
1. Wait for discovery to finish
2. Total balance shows 0
3. Graph shows balances
4. Tap on the graph move on it
5. Total balance still displayes 0

App version: 24.01.1

See the video: 

https://github.com/trezor/trezor-suite/assets/84183817/042ec9b7-b69a-46d3-9809-8c21956b3ad6

### PR DESCRIPTION
**Pull request by PeKne**
In the UI displays only two decimal points in the graph. Sometimes, if there was a value lower than 0.01,  the graph was raising and dropping even though that value was displayed as 0.00. This change fixes that by rounding every value lower than 0.01 to zero.

Closes #10632

### CODE REVIEW

File: suite-common/graph/src/graphUtils.ts [hunk 1]
```diff
@@ -79,11 +79,15 @@ export const mapCryptoBalanceMovementToFixedTimeFrame = ({
             });
 
             const fiatRate = fiatRatePoint.rates[fiatCurrency] ?? 0;
+            const fiatValue = cryptoBalance.multipliedBy(fiatRate).toNumber();
```
Comment (matejkriz) [inline suite-common/graph/src/graphUtils.ts]: can https://mikemcl.github.io/bignumber.js/#toFix be used?

Comment (PeKne) [reply suite-common/graph/src/graphUtils.ts]: fixed dcf824438f

Comment (matejkriz) [reply suite-common/graph/src/graphUtils.ts]: but now you left out `toNumber`, toFix returns string

Comment (PeKne) [reply suite-common/graph/src/graphUtils.ts]: See mentioned fixup commit. The whole expression is wrapped in `Number()` so the result is converted to number again.

Comment (matejkriz) [reply suite-common/graph/src/graphUtils.ts]: 🤦‍♂️ I see now, I missed that. Both variants would work the same in this case, so it's a matter of taste...

Comment (matejkriz) [reply suite-common/graph/src/graphUtils.ts]: my bad, `toNumber` can't be used on string...

**Review by matejkriz — APPROVED** [review]
It did fix the issue for me 👍
