### PR TITLE
fix(suite): disable send button when TX validity expires

### LINKED ISSUE #19918: Solana timer runs out, but the modal is still active.
**Describe the bug**
If you sign a Solana transaction on device right before the timer expires, the timer says that the transaction has failed, but you can still broadcast the transaction.

Image

**Info:**
 - Suite version: web 25.8.0 (d6a38ac198997708e8a5ebd452c396c88065c5d7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.9.0 regular (revision a09e6f04d4204607d821d9b742dcf7ffe9c4e2f5)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by izmy**
## Description

Ensure the send button is disabled when the Solana TX validity timer runs out.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19918

## Screenshots:

https://github.com/user-attachments/assets/9ac01f4e-e04e-4261-b458-7328b1d0b422

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/solana-tx-timeout-modal-state&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/solana-tx-timeout-modal-state&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 1]
```diff
@@ -123,6 +123,7 @@ export const TransactionReviewModalContent = ({
     const [areDetailsVisible, setAreDetailsVisible] = useState(false);
     const deviceModelInternal = device?.features?.internal_model;
     const { precomposedTx, serializedTx } = txInfoState;
+    const [txTimeoutStatus, setTxTimeoutStatus] = useState(false);
```
Comment (TomasBoda) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: since the variable is a `boolean`, I'd use a more representative name, e.g. `hasTxExpired`

**Review by TomasBoda — DISMISSED** [review]
What happens in that short time frame when the timer displays `Send transaction failed` and you click on the `Send` button?

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 1 above)
Comment (izmy) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: changed

**Comment by izmy** [comment]
> What happens in that short time frame when the timer displays `Send transaction failed` and you click on the `Send` button?

The blockhash changes all the time but stays valid for ~2 minutes. We assume 1 minute plus a buffer. So if you click Send right after **Send failed**, it might still work if the blockhash didn’t expire yet.

**Review by tomasklim — APPROVED** [review]
