### PR TITLE
fix: metadata should not disconnect when internet disconnects

### LINKED ISSUE #5187: Unintentional disconnection of the labelling storage
**Describe the bug**
When Suite is unaware of the loss of internet connection while the user is uses labelling, the connection to Dropbox or Google is disconnected. Meanwhile, the token is still valid, making the disconnection unnecessary.

**Steps to reproduce:**
1. Turn on labelling 
2. Disconnect from internet without having noticed it by Suite _(So for example stay on wifi or use mobile hotspot)_
3. Change some label

**Info:**
 - Suite version: desktop 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model 1 1.10.5 Bitcoin only

**Expected result:**
Cloud connection remains valid:
Snímek obrazovky 2022-03-25 v 9 12 46

**Actual result:**
Labelling connection was cancelled:
Snímek obrazovky 2022-03-25 v 9 12 17

_Originally posted by @tsusanka in https://github.com/trezor/trezor-suite/issues/4849#issuecomment-1078727508_

### PR DESCRIPTION
**Pull request by mroz22**
this should resolve #5187

QA please test before merging:
- [ ] disconnecting internet, doing something with metadata, reconnecting internet -> works normally. no disconnection
- [ ] also this should work -> disconnect interent -> do something, it fails to sync but stays in app memory -> turn on internet and change another different label -> both labels should be synced now in the cloud provider
- [ ] google drive authentication. both web and desktop. this PR updates google-auth-lib by one major version https://github.com/googleapis/google-auth-library-nodejs/blob/main/CHANGELOG.md

possible followups: 
- error handling could be rethought abit
- code cleanup and refactoring could definitely be done here
- syncing after internet connection starts working again could be cleverer. Now you need to edit another label so that those that previously failed sync.

### CODE REVIEW

File: packages/suite/src/services/suite/metadata/DropboxProvider.ts [hunk 1]
```diff
@@ -200,6 +200,11 @@ class DropboxProvider extends AbstractMetadataProvider {
             // this should never happen
             message = 'unknown error';
         }
+
+        if (message.includes('Failed to fetch')) {
```
Comment (dahaca) [inline packages/suite/src/services/suite/metadata/DropboxProvider.ts:204]: Is there a more stable method of detection rather than checking the message?

Comment (dahaca) [reply packages/suite/src/services/suite/metadata/DropboxProvider.ts:204]: I've tried figuring out but seems like only that message is being returned? And do we have/need a global handler for connection outage? Perhaps if we centralize the state of being w/o a connection it would be easier to handle issues related to it?

Comment (mroz22) [reply packages/suite/src/services/suite/metadata/DropboxProvider.ts:204]: Would love to see a better solution than this. Some centralized http/fetch module would be nice.

Comment (dahaca) [reply packages/suite/src/services/suite/metadata/DropboxProvider.ts:204]: Let's discuss it on the next code improvements meeting c: @Nodonisko It can at lest be Axios with some handling logic in a separate config file.

File: packages/suite/src/actions/suite/metadataActions.ts [hunk 2]
```diff
@@ -172,6 +171,9 @@ const handleProviderError =
             case 'AUTH_ERROR':
                 dispatch(disconnectProvider());
                 break;
+            case 'CONNECTIVITY_ERROR':
+                // do nothing
+                break;
```
Comment (tomasklim) [inline packages/suite/src/actions/suite/metadataActions.ts]:
```suggestion
```

**Review by tomasklim — APPROVED** [review]

**Comment by bosomt** [comment]
**QA NOK**

Labels are present after i reconnect to internet /Google Drive/ but after some time they disappear and older labels appear.
I was able to reproduce it multiple times.

**Steps to reproduce:**
1. Disconnect from internet
2. Create or edit labels
3. Connect to internet
4. add account /maybe all you have to do is wait/
5. Labels are gone and previously saved labels are present.

https://user-images.githubusercontent.com/31506317/169803100-35d29e96-4288-41a3-823a-375ffeea9e20.mov
