### PR TITLE
Let connect validate bitcoin like addresses

### LINKED ISSUE #1342: DGB BCH VTC bad address validation
Expected:
Send address validation will work correctly for all coins.

Actual:
**Cannot send transactions to valid addresses on these coins: DigiByte DGB, Vertcoin VTC, Bitcoin Cash BCH.** Suite will flag the addresses as incorrect, but they are not (wallet.io flags them as valid and sent coins do end up on the receiving accounts successfully). 

@vladimirvolek please look into this, thank you!

### PR DESCRIPTION
**Pull request by vladimirvolek**
- (BTC only) added loading for address validation - compose progress

resolves: https://github.com/trezor/trezor-suite/issues/1342

### CODE REVIEW

File: packages/suite/src/reducers/wallet/sendFormReducer.ts [hunk 1]
```diff
@@ -79,7 +79,8 @@ export default (state: State | null = null, action: WalletAction): State | null
                     return draft;
                 }
 
-                if (!isAddressValid(action.address, symbol)) {
+                // turn off validation for bitcoin like coins - handled by connect compose transaction
+                if (!isAddressValid(action.address, symbol) && networkType !== 'bitcoin') {
```
Comment (szymonlesisz) [inline packages/suite/src/reducers/wallet/sendFormReducer.ts]: this should be flipped
`if (networkType !== 'bitcoin' && !isAddressValid(action.address, symbol))`
this way isAddressValid fuction will not be called on bitcoin addresses
