### PR TITLE
fix: UI bugs

### LINKED ISSUE #10108: Update WelcomeLayout
* Update WelcomeLayout colors
* fix content overflowing 
image 

* make the support button `small`
image

* ~~move collapsible heading to the left~~ the WebUSB button is there and those changes are out of scope.
image

### LINKED ISSUE #10383: Change default Card padding type to `large`
* Change default Card padding type to `large`

### LINKED ISSUE #10522: Review: Polish Recovery check modal
Screenshot 2024-01-05 at 14 31 49

design
Screenshot 2024-01-09 at 15 09 04

### LINKED ISSUE #10529: Review: Replace some secondary buttons with tertiary ones
We added tertiary style for buttons and in previous design. Right now some of the designs, especially in modals with two buttons looks very weird:

Screenshot 2024-01-05 at 14 19 06

Screenshot 2024-01-05 at 14 22 26

Screenshot 2024-01-05 at 17 20 23

Screenshot 2024-01-05 at 17 22 35

Screenshot 2024-01-05 at 14 25 13

Screenshot 2024-01-08 at 14 37 51

These whole modal should be polished a bit.

We should keep primary button and other one should be tertiary.

Vscode regexp for check:

`<Button(.(?!>)|\n|\t)*variant="tertiary"`

### LINKED ISSUE #10587: Remove the `success` inputState from inputs.
It is not a part of the design system, so it should be removed from everywhere

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Addresses several issues with Suite empower.

## Related Issue

Resolve #10587
Resolve #10522
Resolve #10383
Resolve #10108
Resolve #10529 

## Screenshots:
ED0400C8-17B2-46DD-A5BB-6E1C6727080F
733D619D-AF4E-4BD5-B181-25FBEE59D7A3

### CODE REVIEW

File: packages/components/src/components/Card/Card.tsx
Comment (dahaca) [inline packages/components/src/components/Card/Card.tsx:1]: [The issue](https://github.com/trezor/trezor-suite/issues/10383) was not about _removing_ the `small` padding type but simply making `large` the default 🙏  As it seemed to me there were more instances of cards with `paddingType="large"` than `paddingType="small"`

File: packages/suite/src/components/suite/WebUsbButton.tsx [hunk 1]
```diff
@@ -1,22 +1,25 @@
...
-                title={translationString('TR_CHECK_FOR_DEVICES')}
-                variant="tertiary"
-                onClick={e => {
-                    e.stopPropagation();
-                    TrezorConnect.requestWebUSBDevice();
-                }}
-                size="small"
-            />
-        </div>
+        <Tooltip content={<Translation id="TR_CHECK_FOR_DEVICES" />}>
```
Comment (dahaca) [inline packages/suite/src/components/suite/WebUsbButton.tsx]: As we discussed, feel free to update the `IconButton` component in this PR, so that the `Tooltip` is rendered if a `label` prop passed, rename the existing `label` prop to `bottomLabel` :)  And please include [the delay](https://github.com/trezor/trezor-suite/blob/89834958042c4e046a0d8faf4e316b3ca37066e7/packages/suite/src/components/suite/Preloader/SuiteLayout/NavigationBar/NavigationActions/ActionItem.tsx#L196)

File: packages/components/src/components/Timerange/Timerange.tsx
Comment (dahaca) [inline packages/components/src/components/Timerange/Timerange.tsx:1]: I would close [the issue](https://github.com/trezor/trezor-suite/issues/10529) as a part of the PR but the story is far from being over, as many other places which have not been mentioned should be updated. I do not think it's time to update it all now. I have already asked for more clarification regarding the `secondary` type usage. 🫡

File: packages/components/src/components/Card/Card.tsx
Comment (dahaca) [reply packages/components/src/components/Card/Card.tsx:1]: Also, there are type errors now in [some components](https://github.com/trezor/trezor-suite/blob/035475f84f436d349811ecb81709ac069dc17aa3/packages/suite/src/views/wallet/send/components/TotalSent.tsx#L73), since `large` is gone. 

I'd say, you can keep `default = spacings.lg` and `small = spacings.sm`.

**Review by dahaca — CHANGES_REQUESTED** [review]

File: packages/components/src/components/Timerange/Timerange.tsx
Comment (AdamSchinzel) [reply packages/components/src/components/Timerange/Timerange.tsx:1]: Okey makes sense

File: packages/components/src/components/Card/Card.tsx
Comment (AdamSchinzel) [reply packages/components/src/components/Card/Card.tsx:1]: 535dca1a5f88c85c40427e4bb45aeb0cd76be6e3

File: packages/components/src/components/Timerange/Timerange.tsx
Comment (AdamSchinzel) [reply packages/components/src/components/Timerange/Timerange.tsx:1]: 34ee63187ec5953d80d909960decadf84f39c217

File: packages/suite/src/components/suite/WebUsbButton.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/WebUsbButton.tsx]: 1672076e0dfc442f8263f2e18885918a3c17d9ff

File: packages/components/src/components/Timerange/Timerange.tsx
Comment (dahaca) [reply packages/components/src/components/Timerange/Timerange.tsx:1]: Just for clarity, I did not mean to revert the changes, but that the aforementioned issue should be linked _(already done!)_ and that we should not care much about all the other buttons in this PR but create appropriate issues later! ;)

File: packages/suite/src/components/suite/CoinList/Coin.tsx
Comment (dahaca) [inline packages/suite/src/components/suite/CoinList/Coin.tsx:1]: 🔥 ❗

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AdvancedCoinSettingsModal/CustomBackends/CustomBackends.tsx [hunk 2]
```diff
@@ -144,14 +151,20 @@ export const CustomBackends = ({ network, onCancel }: CustomBackendsProps) => {
...
+                ) : (
+                    (editable ? urls : defaultUrls).map(url => (
+                        <BackendInput
+                            key={url}
+                            url={url}
+                            active={url === blockchain[coin]?.url}
+                            onRemove={editable ? () => removeUrl(url) : undefined}
+                        />
+                    ))
+                )}
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AdvancedCoinSettingsModal/CustomBackends/CustomBackends.tsx]: IMO wasn't as smooth, so I changed slightly 🙏 279dfe50ee88fca1c6f108c828373222351a7ac6

File: packages/suite/src/components/suite/WebUsbButton.tsx (hunk 1 above)
Comment (dahaca) [reply packages/suite/src/components/suite/WebUsbButton.tsx]: Thanks! Definitely a useful addition. I have also adjusted storybook a tiny bit 4fd17646c8040d2b842b688e2a244bf23ee72ef5

**Review by dahaca — APPROVED** [review]
I have rebased and added a couple commits as well, feel free to check before squashing :)
