### PR TITLE
fix(suite): setting device.useDeviceState fixes

### LINKED ISSUE #19801: Discovery refactoring - adding standard wallet shows as passphrase wallet
**Describe the bug**
When I eject my standard wallet and I try to add it as an empty string passphrase on device it shows as "passphrase wallet" in Suite ui even though it is actually a standard wallet.

**Steps to reproduce:**
1. Connect device to Suite
2. After initial discovery, eject the standard wallet
3. Click on add passphrase wallet
4. Click on enter passphrase on device
5. On device click on ✅ 
6. Suite opens a wallet and the wallet switcher says it is "Passphrase wallet" even though it is actually the standard wallet

**Info:**
 - Suite version: web 25.7.0 (380d594162870361b533008c42c3c4b6bae30116)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.9.0 regular (revision 5e4c97f98d2e139aa82135a0ee43003816f62c6c)
 - Transport: WebUsbTransport

**Expected result:**
Entering empty passphrase should open standard wallet. Either change the UI in Suite or possibly forbid entering empty string on device.

### PR DESCRIPTION
**Pull request by mroz22**
resolve #19801

## QA notes 

I made couple of changes, so please check:
- #19801
- passphrase flow did not break, wallets are named and numbered correctly...

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=use-device-state&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=use-device-state&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=use-device-state&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/device/deviceSelectors.ts [hunk 1]
```diff
@@ -359,15 +359,16 @@ export const selectRememberedStandardWalletsCount = createMemoizedSelector(
     [selectPhysicalDevices],
     devices =>
         returnStableArrayIfEmpty(
-            devices.filter(device => device.remember && device.useEmptyPassphrase),
+            // todo:
```
Comment (martykan) [inline suite-common/wallet-core/src/device/deviceSelectors.ts]: !

**Review by martykan — APPROVED** [review]
Lint + mentioned selector needs fixing, otherwise LGTM

File: suite-common/wallet-core/src/device/deviceSelectors.ts [hunk 2]
```diff
@@ -359,15 +359,16 @@ export const selectRememberedStandardWalletsCount = createMemoizedSelector(
...
+            devices.filter(device => device.remember && device.useEmptyPassphrase === false),
         ).length,
 );
 
 export const selectRememberedHiddenWalletsCount = createMemoizedSelector(
     [selectPhysicalDevices],
     devices =>
         returnStableArrayIfEmpty(
-            devices.filter(device => device.remember && !device.useEmptyPassphrase),
+            devices.filter(device => device.remember && device.useEmptyPassphrase === false),
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/device/deviceSelectors.ts:370]: shouldn't this be rather `!== true`, since it can be undefined too?

File: suite-common/wallet-core/src/device/deviceThunks.ts [hunk 3]
```diff
@@ -228,6 +222,7 @@ export const acquireDevice = createThunk(
 
         const response = await TrezorConnect.getFeatures({
             device,
+            // todo: it shouldn't be needed I think - getFeatures is not touching device.state, is it?
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/device/deviceThunks.ts:225]: yes that can be deleted. I verified that the getFeatures response is identical.

File: suite-common/wallet-core/src/discovery/discoveryThunks.ts [hunk 4]
```diff
@@ -114,13 +115,38 @@ const applyDeviceStatesThunk = createThunk(
...
+                if (!emptyPassphraseDeviceState) {
+                    const res = await TrezorConnect.getDeviceState({
+                        device,
+                        useEmptyPassphrase: true,
+                    });
+                    if (res.success) {
+                        emptyPassphraseDeviceState = res.payload._state;
+                    }
+
+                    // todo: how to handle error?
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/discovery/discoveryThunks.ts:133]: well what can we do really? This `getDeviceState` call is just for detection of empty passphrase. If we can't detect it, we can just let it be → it will stay `!isAddingHiddenWallet` (very reasonable)

**Review by Lemonexe — APPROVED** [review]
codewise LGTM but please fix analytics [definitely here](https://github.com/trezor/trezor-suite/pull/20748#discussion_r2276684949) and [maybe here](https://github.com/trezor/trezor-suite/pull/20748#discussion_r2277023286)

File: suite-common/wallet-core/src/device/deviceSelectors.ts (hunk 2 above)
Comment (mroz22) [reply suite-common/wallet-core/src/device/deviceSelectors.ts:370]: well that should not really happen - if useEmptyPassphrase is still undefined we don't know yet whether it is hidden or standard wallet at that moment.

File: suite-common/wallet-core/src/device/deviceActions.ts [hunk 5]
```diff
@@ -69,7 +63,7 @@ const setTemporaryRememberedDevice = createAction(
 
 const forgetDevice = createAction(
     `${DEVICE_MODULE_PREFIX}/forgetDevice`,
-    (payload: { device: TrezorDevice; settings: ConnectDeviceSettings }) => ({
```
Comment (vojtatranta) [inline suite-common/wallet-core/src/device/deviceActions.ts:72]: 🙏 thank god for this

**Comment by honzauher** [comment]
**QA OK**

Passphrase flow working correctly, wallets named and numbered correctly as well

**Info:**
 - Suite version: web 25.9.0 (b40e984db1ca1910525a63c9993f152bbbc87f4c)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.10 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport
