### PR TITLE
fix(trade): fix missing space in translation

### LINKED ISSUE #24223: Trade - Missing space in the Trade TCs (DEX)
Image

### PR DESCRIPTION
**Pull request by sherpaPSX**
## Description

According to missing space in the Czech translation, I've refactor whole sentence whit was previously composed from 3 translation keys. Now is one with dynamic parameters.

## Notes for QA

Please verify that provider link and name is working correctly. It should work as before but we need to re-translate in Crowdin, cause I changed translation keys

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/24223

## Screenshots:
image
image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/footer-translation&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/footer-translation&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx [hunk 1]
```diff
@@ -8,39 +10,48 @@ type TradingFooterProps = {
...
-            ) : (
-                <Translation id="TR_TRADING_TERMS_2" />
-            )}
-        </Text>
+export const TradingFooter = ({ provider }: TradingFooterProps) => {
+    const intl = useIntl();
+
+    const providerName = provider?.companyName
+        ? provider.companyName
+        : intl.formatMessage({ id: 'TR_TRADING_PROVIDER' }).toLowerCase();
```
Comment (vytick) [inline packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: q: I would fix this in translation itself rather than force lowercase here. Wdyt?

Comment (vytick) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: q2: Is the hook needed? Maybe  `<Translation id="TR_TRADING_PROVIDER" />` can be used instead?

File: suite/intl/src/messages.ts [hunk 2]
```diff
@@ -802,17 +802,10 @@ export const messages = defineMessages({
...
-    },
-    TR_TRADING_TERMS_2: {
-        id: 'TR_TRADING_TERMS_2',
-        defaultMessage: "provider's Terms & Conditions.",
-    },
-    TR_TRADING_TERMS_PROVIDER: {
-        id: 'TR_TRADING_TERMS_PROVIDER',
-        defaultMessage: "{companyName}'s Terms & Conditions.",
+        defaultMessage:
+            "Trezor doesn't provide this service. It's governed by <comp>{provider}</comp>'s Terms & Conditions.",
```
Comment (vytick) [inline suite/intl/src/messages.ts:791]: Please, make sure these are updated mainly in the [Crowdin](https://crowdin.com/project/trezor-suite). 

[Here is a great summary](https://www.notion.so/satoshilabs/Translations-Crowdin-2b2dc5260606807da91ffb6eae59a6ed?source=copy_link#2b2dc526060680cab6dbca35f95382ad) on how to work with translations:

**Review by vytick — DISMISSED** [review]

File: suite/intl/src/messages.ts (hunk 2 above)
Comment (tomasklim) [reply suite/intl/src/messages.ts:791]: as it is completely new key, it is not needed to do anything with crowdin

Comment (vytick) [reply suite/intl/src/messages.ts:791]: Oh, i missed that. good point

File: packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx (hunk 1 above)
Comment (sherpaPSX) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: a1: When I do it, I suppose we need do uppercase here `packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailProviderInfo.tsx`

```
 <InfoItem label={<Translation id="TR_BUY_PROVIDER" />} direction="row">
       <TradingProviderInfo exchange={trade.exchange} provider={provider} />
</InfoItem>
```

a2: It is needed to call `.toLowerCase()` on translation

Comment (vytick) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: In that case, imo, it should be two different translation keys and no hook will be needed. Wdyt?

Comment (sherpaPSX) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: I don't see anything wrong on using official hook. Would you have rather 2 same translations?

Comment (sherpaPSX) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: According to documentation, I used useTransaltion hook insted
https://www.notion.so/satoshilabs/Translations-Crowdin-2b2dc5260606807da91ffb6eae59a6ed?source=copy_link

Comment (vytick) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: Imo we should not change the translation at all here. If we do that, it probably means those translations are not the same and are used different way => different keys. 

And as a side effect no hook is needed nad less hooks the merrier :)

Comment (sherpaPSX) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: So I should add new translation key as `TR_TRADING_PROVIDER_LOWERCASE`?

Comment (sherpaPSX) [reply packages/suite/src/views/wallet/trading/common/TradingFooter/TradingFooter.tsx]: added a new key ` TR_TERMS_PROVIDER_PLACEHOLDER`

**Review by vytick — APPROVED** [review]
🫶 Thanks for making Suite nicer place!
