### PR TITLE
Fix asset list view

### LINKED ISSUE #10847: Empower/Dashboard > Assets List view
Reference design: https://www.figma.com/file/mQhdQPKzdi93Swb8FNX9wL/branch/pewjlOfequOKYVC6h3v0YL/%5Bs2.0%5D-Desktop?type=design&node-id=6076%3A13023&mode=design&t=LpdUfFZ6Diaodpzd-1

1. **Clicking change to sat also redirects to account. Should only change to sats.**
2. Wrong header alignment
3. Wrong font colors (amount in fiat vs. amount in crypto)
4. Radial graph inconsistent rounding 
    - In the case above, BTC is fully filled and ETH also has a part of the graph filled
image

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10847

## Screenshots:

image

image

### CODE REVIEW

File: packages/suite/src/components/suite/AmountUnitSwitchWrapper.tsx [hunk 1]
```diff
@@ -47,7 +47,10 @@ export const AmountUnitSwitchWrapper = ({ symbol, children }: AmountUnitSwitchWr
             content={<Translation id={areSatsDisplayed ? 'TR_TO_BTC' : 'TR_TO_SATOSHIS'} />}
         >
             <Container
-                onClick={toggleBitcoinAmountUnits}
+                onClick={e => {
```
Comment (AdamSchinzel) [inline packages/suite/src/components/suite/AmountUnitSwitchWrapper.tsx]: Nitpick: would be better to have it in separate function such as `handleToggleBitcoinAmountUnits` for better readability

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetRow.tsx [hunk 2]
```diff
@@ -110,13 +111,18 @@ const CryptoBalanceWrapper = styled(Col)`
...
 `;
 
-const FiatBalanceWrapper = styled.div`
-    color: ${({ theme }) => theme.textSubdued};
-`;
+const FiatBalanceWrapper = styled.div``;
 
 const ExchangeRateWrapper = styled(Col)`
     font-variant-numeric: tabular-nums;
     padding-right: 0;
```
Comment (AdamSchinzel) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetRow.tsx]: remove this, it's also why validation is failing because you're later setting padding-right again

**Review by AdamSchinzel — CHANGES_REQUESTED** [review]
Also can we do something about the mobile layout of rows.
C961835F-7D2B-49BF-9DA3-08FA7EB369A2

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetRow.tsx (hunk 2 above)
Comment (peter-sanderson) [reply packages/suite/src/views/dashboard/components/AssetsView/components/AssetRow.tsx]: :heavy_check_mark:

File: packages/suite/src/components/suite/AmountUnitSwitchWrapper.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/components/suite/AmountUnitSwitchWrapper.tsx]: :heavy_check_mark:

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx [hunk 3]
```diff
@@ -28,12 +28,18 @@ export const AssetCoinLogo = ({ symbol, assetsFiatBalances, index }: CoinLogoPro
...
     return (
         <LogoWrapper>
-            <AssetShareIndicator
-                symbol={symbol}
-                size={24}
-                percentageShare={assetPercentage}
-                index={index}
-            />
+            <Tooltip
+                content={<>{(assetPercentage ?? 0).toFixed(2)} %</>}
```
Comment (AdamSchinzel) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx]: Nitpick: Imo using template strings seems like a better option here
```suggestion
                content={`${(assetPercentage ?? 0).toFixed(2)} %`}
```

**Review by AdamSchinzel — CHANGES_REQUESTED** [review]

**Review by AdamSchinzel — APPROVED** [review]
lgtm

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx [hunk 4]
```diff
@@ -28,12 +28,18 @@ export const AssetCoinLogo = ({ symbol, assetsFiatBalances, index }: CoinLogoPro
...
     return (
         <LogoWrapper>
-            <AssetShareIndicator
-                symbol={symbol}
-                size={24}
-                percentageShare={assetPercentage}
-                index={index}
-            />
+            <Tooltip
+                content={`${(assetPercentage ?? 0).toFixed(2)} %`}
```
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx:32]: `localizeNumber`, like [here](https://github.com/trezor/trezor-suite/blob/a513f54f8c10fb8d008170397a7cd647ac2ff125/packages/suite/src/components/suite/Ticker/TrendTicker.tsx#L56). Should be a convention, maybe even mentioned in Code Style Guide for clarity?

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx [hunk 5]
```diff
@@ -28,12 +28,18 @@ export const AssetCoinLogo = ({ symbol, assetsFiatBalances, index }: CoinLogoPro
...
+                cursor="pointer"
+                delay={1000}
```
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx:34]: Nice touch!

nit: delay={[600, 0]} for all [label tooltips](https://github.com/trezor/trezor-suite/blob/23667022e37223dd6c446ce2e3c4af9fc91b5422/packages/components/src/components/buttons/IconButton/IconButton.tsx#L59) (I should create a constant!) and probably no delay here, actually.

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx (hunk 4 above)
Comment (peter-sanderson) [reply packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx:32]: https://github.com/trezor/trezor-suite/pull/10973

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx (hunk 5 above)
Comment (peter-sanderson) [reply packages/suite/src/views/dashboard/components/AssetsView/components/AssetCoinLogo.tsx:34]: https://github.com/trezor/trezor-suite/pull/10973
