### PR TITLE
connect device communication fixes

### LINKED ISSUE #4385: Change of device settings when discovery is not finished kills my device
**Describe the bug**
This bug affects only me from dev team. I am the only one using Intel mac.
When I want to change settings of device before discovery is done, it kills my device. It happens on both Bridge and Web USB. 

**Background**
When user navigates to different route than `Dashboard` and `Accounts` when discovery is in progress, the discovery process is paused. 

**Steps to reproduce:**
1. Open Suite
2. Select wallet type
3. During discovery process open Settings
4. Try to change settings of device. (PIN, image, name,...)
5. You get error`Error: assertType: Response of unexpected type: Features. Should be Success`
6. Device is stuck and you cannot do anything
7. Refresh app
8. `Loading takes too long`

You need to replug device to be able to use Suite.

**Info:**
 - Suite version: web 21.10.2 (3cb57ead18474b380841b479a542c0b910b3d936)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model 1 1.10.3 regular
 - Transport: USB API, Bridge
 
It happens also with `trezor-user-env`

### PR DESCRIPTION
**Pull request by mroz22**
Before:
- go to suite (webusb)
- get address
- reload
- observe that the device is stuck

After:
- sending cancel seems to be the universal remedy, that flushes all the communication and forces the device to cooperate again after exiting the initial communication ungracefully.

Another possible scenario
- trezorctl get-address --show-display --coin Bitcoin -n "44'/0'/0'/0/0"
- kill terminal window without approving on device 
- go to suite 

possibly related issues:
maybe resolve #4385 (at least the point where app doesn't load after reload)

### CODE REVIEW

File: packages/connect/src/device/Device.ts [hunk 1]
```diff
@@ -555,10 +555,10 @@ export class Device extends TypedEmitter<DeviceEvents> {
                         // set the timeout for this call so whenever it happens "unacquired device" will be created instead
                         // next time device should be called together with "Initialize" (calling "acquireDevice" from the UI)
                         new Promise((_resolve, reject) => {
-                            getFeaturesTimeoutId = setTimeout(
-                                () => reject(new Error('GetFeatures timeout')),
-                                getFeaturesTimeout,
-                            );
+                            getFeaturesTimeoutId = setTimeout(async () => {
+                                await cancelPrompt(this, false);
```
Comment (szymonlesisz) [inline packages/connect/src/device/Device.ts]: maybe more defensive approach?
```suggestion
                                cancelPrompt(this, false).finally(() => reject(new Error('GetFeatures timeout')));
```

**Review by szymonlesisz — APPROVED** [review]

**Comment by evgenysl** [comment]
Bug is reproducible only with T1B1.

**Comment by mroz22** [comment]
> Bug is reproducible only with T1B1.

and fixed after this, right?

**Comment by evgenysl** [comment]
Yes, on current devel (webUSB), when reloading Trezor Suite, T1 get's reacquired again without any issues.

**Comment by evgenysl** [comment]
In both scenarios:
- get address in Suite (webUSB)
- trezorctl get-address --show-display --coin Bitcoin -n "44'/0'/0'/0/0"

T1 loads correctly 


**QA OK**
