### PR TITLE
fix(suite): add staking to the total balance

### LINKED ISSUE #12828: Staking in dashboard portfolio balance
Include the Ethereum staking balance in the portfolio summary.

Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Include the Ethereum staking balance in the portfolio summary and wallet modal.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12828

### CODE REVIEW

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 1]
```diff
@@ -588,6 +591,20 @@ export const getTokensFiatBalance = (
...
+
+    if (account.networkType !== 'ethereum') return null;
+
+    const { autocompoundBalance } = account?.misc?.stakingPools?.[0] ?? {};
+    if (!autocompoundBalance) return null;
+
+    const balanceInEther = new BigNumber(fromWei(autocompoundBalance, 'ether')).toString();
+    const fiatBalance = toFiatCurrency(balanceInEther, coinFiatRate.rate, 2);
+
+    return fiatBalance;
```
Comment (StanCheb) [inline suite-common/wallet-utils/src/accountUtils.ts]:
```suggestion
    return toFiatCurrency(balanceInEther, coinFiatRate.rate, 2);
```

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 2]
```diff
@@ -588,6 +591,20 @@ export const getTokensFiatBalance = (
...
 
+export const getStakeFiatBalance = (account: Account, coinFiatRate: Rate | undefined) => {
+    if (!coinFiatRate?.rate) return null;
+
+    if (account.networkType !== 'ethereum') return null;
+
+    const { autocompoundBalance } = account?.misc?.stakingPools?.[0] ?? {};
+    if (!autocompoundBalance) return null;
+
+    const balanceInEther = new BigNumber(fromWei(autocompoundBalance, 'ether')).toString();
```
Comment (StanCheb) [inline suite-common/wallet-utils/src/accountUtils.ts]: Why using `BigNumber` and then still converting to a string? IIRC, `fromWei()` already returns a string.

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 3]
```diff
@@ -588,6 +591,20 @@ export const getTokensFiatBalance = (
     return totalBalance.toFixed();
 };
 
+export const getStakeFiatBalance = (account: Account, coinFiatRate: Rate | undefined) => {
+    if (!coinFiatRate?.rate) return null;
```
Comment (StanCheb) [inline suite-common/wallet-utils/src/accountUtils.ts]: Can we pass the rate itself? So that we don't have to `coinFiatRate.rate` twice in the func.

**Review by tomasklim — APPROVED** [review]
