### PR TITLE
fix: disable keybinds or wallet switcher during discovery

### LINKED ISSUE #15579: Missing `Passphrase wallet` in wallet/device selector
**Describe the bug**
Missing `Passphrase wallet` in wallet/device selector there is just * present
Labeling is disabled

**Steps to reproduce:**
1. Add standard wallet
2. Add passphrase wallet
3. Open wallet selector

**Info:**
 - Suite version: web 24.12.0 (d29333b063cf1cb8a9785d596be9191301fd0c0b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by peter-sanderson**
This is probably not a proper fix. But our wallet-switcher & discovery are not a best friends. 

=> until discovery is not finished, we shall not allow wallet switcher stuff (it is [already disabled in the UI](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/layouts/SuiteLayout/DeviceSelector/DeviceSelector.tsx#L145) so I assume we shall disable keybinds as well

Resolves: https://github.com/trezor/trezor-suite/issues/15579

### CODE REVIEW

File: packages/suite/src/components/suite/layouts/SuiteLayout/useAppShortcuts.tsx [hunk 1]
```diff
@@ -20,15 +25,16 @@ export const useAppShortcuts = () => {
...
+            !discoveryInProgress
         ) {
             dispatch(addWalletThunk({ walletType: 'passphrase', device: selectedDevice }));
             dispatch(closeModalApp());
             e.preventDefault();
         }
 
         // press ALT + D to show SwitchDevice
-        if (altKey && e.code === KEYBOARD_CODE.KEY_D && isDeviceSelected) {
+        if (altKey && e.code === KEYBOARD_CODE.KEY_D && isDeviceSelected && !discoveryInProgress) {
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/SuiteLayout/useAppShortcuts.tsx]: Please move this to a nested `if(!discoveryInProgress) dispatch()`, but do the preventDefault in the _this_ if body, so it fires nevertheless.

Firefox has a default on Alt D: open address bar
This leads to unexpected inconsistent behavior - if I'm used to Alt D opening the device popup, the shortcut does something different based on state of discovery. Worse yet, pressing Alt D during discovery takes focus out of the page, so pressing it again after discovery is finished does not have effect.

**Review by Lemonexe — APPROVED** [review]
LGTM, works as expected!

File: packages/suite/src/components/suite/layouts/SuiteLayout/useAppShortcuts.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/components/suite/layouts/SuiteLayout/useAppShortcuts.tsx]: fixed

**Review by Lemonexe — APPROVED** [review]
