### PR TITLE
Fix/4728 access settings

### LINKED ISSUE #4728: Access Settings: Trezor disconnected followup
- [x] sticky close button in settings (always visible on scroll) ?

- [x] improve visibility of disabled state for toggles
  - [x] cursor on all the options that are disabled should be cursor: not-allowed (crossed out circle)
  - [x] there should be an explanation tooltip on disabled toggles
image
Figma: https://www.figma.com/file/BUMem1C7j4roQDyJf9yxQT/Exploring-Onboarding?node-id=862%3A1446

  
- [x]  Remembered device -  add banner on top of coins tab (only if the device is remembered and not connected)

- [x] improve banner paddings on small screens

- [ ] ~add Tooltips for navigation actions:  Discrete mode,  Custom backends, Tor, Early Access Program, Notifications, Settings~

### PR DESCRIPTION
**Pull request by dimasivan**
fix #4728

### CODE REVIEW

File: packages/suite/src/components/settings/SettingsMenu/index.tsx [hunk 1]
```diff
@@ -1,10 +1,29 @@
 import React, { useState } from 'react';
 
+import styled, { css } from 'styled-components';
+
 import { CloseButton, Translation, AppNavigationPanel, AppNavigation } from '@suite-components';
 import { useActions, useSelector } from '@suite-hooks';
 import * as routerActions from '@suite-actions/routerActions';
 import * as suiteActions from '@suite-actions/suiteActions';
 
+const StyledCloseButton = styled(CloseButton)``;
```
Comment (tomasklim) [inline packages/suite/src/components/settings/SettingsMenu/index.tsx]: Not necessary to wrap it with `styled()`

File: packages/suite/src/components/settings/SettingsMenu/index.tsx [hunk 2]
```diff
@@ -1,10 +1,29 @@
...
+
+const FloatingTitleContent = styled.div<{ inView?: boolean }>`
+    position: absolute;
+    right: 0;
+    top: 0;
+    width: 32px;
+    height: 32px;
+    ${props =>
+        !props.inView &&
```
Comment (tomasklim) [inline packages/suite/src/components/settings/SettingsMenu/index.tsx]: It would look better if it fades away from the top bar and appears in the bottom bar on scroll. (some opacity animations)

File: packages/suite/src/components/settings/SettingsMenu/index.tsx [hunk 3]
```diff
@@ -82,10 +101,12 @@ const SettingsMenu = () => {
                 />
             }
             titleContent={
-                <CloseButton
-                    onClick={() => goto(settingsBackRoute.name, settingsBackRoute.params)}
-                    data-test="@settings/menu/close"
-                />
+                <FloatingTitleContent>
```
Comment (tomasklim) [inline packages/suite/src/components/settings/SettingsMenu/index.tsx]: It is not vertically centered in the bottom bar

File: packages/suite/src/components/settings/SettingsMenu/index.tsx [hunk 4]
```diff
@@ -1,10 +1,29 @@
 import React, { useState } from 'react';
```
Comment (tomasklim) [inline packages/suite/src/components/settings/SettingsMenu/index.tsx:1]: There is a problem on small screens when `Debug` is active
Screenshot 2022-01-24 at 13 53 25

File: packages/suite/src/views/settings/coins/components/CoinsGroup/index.tsx [hunk 5]
```diff
@@ -202,14 +202,28 @@ const CoinsGroup = ({
...
-                                    <Switch
-                                        data-test={`@settings/wallet/network/${network.symbol}`}
-                                        onChange={(visible: boolean) => {
-                                            onToggleOneFn(network.symbol, visible);
-                                        }}
-                                        checked={enabledNetworks.includes(network.symbol)}
-                                        isDisabled={isDeviceLocked}
-                                    />
+
+                                    <Tooltip
```
Comment (tomasklim) [inline packages/suite/src/views/settings/coins/components/CoinsGroup/index.tsx]: It would be nice to create a new component `SwitchWithTooltip` or maybe better upgrade `Switch` to have a `tooltip` option.
 
I think we will use it in more places in the app (e.g. remember device switch in switch device modal when discovery is active) so it would be nice to have it to avoid code duplicates.

File: packages/suite/src/views/settings/coins/index.tsx [hunk 6]
```diff
@@ -47,6 +51,14 @@ const Settings = () => {
 
     return (
         <SettingsLayout>
+            {isDeviceLocked && (
+                <DeviceBanner
```
Comment (tomasklim) [inline packages/suite/src/views/settings/coins/index.tsx]: I added a comment to the original issue. On small screens, it looks bad. Probably some padding on the right and using `font-weight: 500;` instead of `600` could help.
Screenshot 2022-01-24 at 13 54 19

Comment (tomasklim) [reply packages/suite/src/views/settings/coins/index.tsx]: Screenshot 2022-01-24 at 14 05 49

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/settings/coins/components/CoinsGroup/index.tsx (hunk 5 above)
Comment (matejkriz) [reply packages/suite/src/views/settings/coins/components/CoinsGroup/index.tsx]: I'm against `tooltip` option for Switch component – [composition over configuration](https://johno.com/composition-over-configuration).  I don't see the code duplication, could you please add a link, @tomasklim?

File: packages/suite/src/views/settings/index.tsx [hunk 7]
```diff
@@ -209,22 +208,39 @@ const Settings = () => {
...
-                            data-test="@settings/metadata-switch"
-                            checked={metadata.enabled}
-                            onChange={() =>
-                                metadata.enabled ? disableMetadata() : initMetadata(true)
+                        <Tooltip
+                            maxWidth={280}
+                            offset={10}
+                            placement="top"
+                            dashed={false}
+                            cursor="default"
```
Comment (matejkriz) [inline packages/suite/src/views/settings/index.tsx]: cursor should be `not-allowed` according the https://github.com/trezor/trezor-suite/issues/4728#issue-1101387663

File: packages/suite/src/components/settings/SettingsMenu/index.tsx (hunk 2 above)
Comment (dimasivan) [reply packages/suite/src/components/settings/SettingsMenu/index.tsx]: I added only `fade_in` animation for bottom bar in e3ef7b0

File: packages/suite/src/components/settings/SettingsMenu/index.tsx (hunk 3 above)
Comment (dimasivan) [reply packages/suite/src/components/settings/SettingsMenu/index.tsx]: e3ef7b0

File: packages/suite/src/components/settings/SettingsMenu/index.tsx (hunk 4 above)
Comment (dimasivan) [reply packages/suite/src/components/settings/SettingsMenu/index.tsx:1]: e3ef7b0

File: packages/suite/src/views/settings/coins/index.tsx (hunk 6 above)
Comment (dimasivan) [reply packages/suite/src/views/settings/coins/index.tsx]: 99a7501

File: packages/suite/src/views/settings/index.tsx (hunk 7 above)
Comment (matejkriz) [reply packages/suite/src/views/settings/index.tsx]: still not working 🤔 react-switch has defined cursor: default

Comment (matejkriz) [reply packages/suite/src/views/settings/index.tsx]: @pingpwned still not fixed, right?

File: packages/suite/src/components/suite/AppNavigation/index.tsx [hunk 8]
```diff
@@ -93,6 +93,9 @@ const Primary = styled.div`
     display: flex;
     justify-content: flex-start;
     align-items: center;
+    @media (max-width: ${variables.SCREEN_SIZE.SM}) {
+        width: calc(100% - 48px);
+    }
```
Comment (matejkriz) [inline packages/suite/src/components/suite/AppNavigation/index.tsx]: what does this do? I see no difference on small screen.

File: packages/suite/src/components/settings/SettingsMenu/index.tsx (hunk 4 above)
Comment (tomasklim) [reply packages/suite/src/components/settings/SettingsMenu/index.tsx:1]: I think `20px` to `22px` would be better than `15px`

File: packages/suite/src/components/settings/SettingsMenu/index.tsx (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/components/settings/SettingsMenu/index.tsx]: Looks definitely better.

Screenshot 2022-01-28 at 22 09 03

I do not like that it appears "so late". I would add it there immediately after scrolling `1px`. I do not like that there is no "fade out" animation

File: packages/suite/src/views/settings/coins/components/CoinsGroup/index.tsx (hunk 5 above)
Comment (tomasklim) [reply packages/suite/src/views/settings/coins/components/CoinsGroup/index.tsx]: I was thinking about future cases

File: packages/suite/src/views/settings/coins/index.tsx (hunk 6 above)
Comment (tomasklim) [reply packages/suite/src/views/settings/coins/index.tsx]: `font-weight` not changed

File: packages/suite/src/components/suite/AppNavigation/index.tsx (hunk 8 above)
Comment (dimasivan) [reply packages/suite/src/components/suite/AppNavigation/index.tsx]: I tried to reduce wrapper width for some space for close button, but it seems like text overflows anyway, so removing in 6c919e8

File: packages/suite/src/views/settings/index.tsx (hunk 7 above)
Comment (dimasivan) [reply packages/suite/src/views/settings/index.tsx]: it is possible to achieve custom cursor when disabled with absolute positioned pseudo element with higher z-index.

File: packages/suite/src/components/settings/SettingsMenu/index.tsx (hunk 4 above)
Comment (dimasivan) [reply packages/suite/src/components/settings/SettingsMenu/index.tsx:1]: lets keep it 15px because in other than english languages it can do more harm than good imho

File: packages/suite/src/views/settings/index.tsx (hunk 7 above)
Comment (matejkriz) [reply packages/suite/src/views/settings/index.tsx]: it is possible, but not resolved, right?


https://user-images.githubusercontent.com/3729633/152010449-3726c555-d0d0-4ab4-8c55-472fbc56fda9.mov

File: packages/suite/src/views/settings/coins/index.tsx [hunk 9]
```diff
@@ -18,8 +19,19 @@ const StyledCoinsGroup = styled(CoinsGroup)`
...
+    const { device, isLocked } = useDevice();
+    const isDeviceLocked = !!device && isLocked();
+
     return (
         <StyledSettingsLayout>
+            {isDeviceLocked && (
+                <DeviceBanner
+                    title={<Translation id="TR_SETTINGS_DEVICE_BANNER_TITLE_UNAVAILABLE" />}
+                    description={
+                        <Translation id="TR_SETTINGS_DEVICE_BANNER_DESCRIPTION_UNAVAILABLE" />
```
Comment (matejkriz) [inline packages/suite/src/views/settings/coins/index.tsx]: Those can't be the same translation id with those on Device tab because the text doesn't make sense for coins tab.

File: packages/suite/src/views/settings/index.tsx (hunk 7 above)
Comment (dimasivan) [reply packages/suite/src/views/settings/index.tsx]: added in 66999f3. Also added cursor: not-allowed for disabled ActionButtons

File: packages/suite/src/components/suite/AppNavigation/index.tsx [hunk 10]
```diff
@@ -342,7 +342,7 @@ const AppNavigation = ({ items, primaryContent, maxWidth, inView }: Props) => {
                                         </StyledButton>
                                     );
                                 })}
-                                {itemsSecondaryWithExtra.length ? (
+                                {itemsSecondaryWithExtra.length > 0 ? (
```
Comment (tomasklim) [inline packages/suite/src/components/suite/AppNavigation/index.tsx]:
```suggestion
                                {itemsSecondaryWithExtra.length ? (
```

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx [hunk 11]
```diff
@@ -12,7 +12,7 @@ import { NavTor } from './components/NavTor';
 import { NavEarlyAccess } from './components/NavEarlyAccess';
```
Comment (tomasklim) [inline packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx]: I find it very annoying, ugly and not working correctly
https://user-images.githubusercontent.com/33235762/158424381-a20c277b-ba67-4c36-918a-4f07366bc778.mov

**Review by tomasklim — APPROVED** [review]
I would not add the tooltips. But it depends on you.

File: packages/suite/src/components/suite/AppNavigation/index.tsx (hunk 10 above)
Comment (matejkriz) [reply packages/suite/src/components/suite/AppNavigation/index.tsx]: https://github.com/trezor/trezor-suite/pull/4784/commits/7eeb4682a1589467df83ae12a493b49b89230172

File: packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx (hunk 11 above)
Comment (matejkriz) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx]: Try it now, please. I just added `hideOnClick={false}` and I believe it's way better. It happens to me all the time that I click before I see the tooltip and so I don't see it at all.
https://github.com/trezor/trezor-suite/pull/4784/commits/fdb1beb26983d2c9413eef753dfba23b27310e2e

Comment (matejkriz) [reply packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx]: I didn't find nice solution, let's solve it as separate issue when it comes to priorities: https://github.com/trezor/trezor-suite/issues/5162

**Review by tomasklim — APPROVED** [review]
🌷
