### PR TITLE
fix(suite): align approval flow outputs highlighting

### LINKED ISSUE #20404: Trading - token approval progress points do not align properly
> **QA OK** with comments.  
> The flow is now aligned.
> 
> Small issue:  
> The progress points do not align properly and get stuck.  
> 
> Image
> 
> **Info:**
>  - Suite version: web 25.8.0 (4c25b6fafccb616de138cd40d0e58534bc4b809b)
>  - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
>  - OS: Linux x86_64
>  - Screen: 2560x1440
>  - Device: Trezor T3T1 2.9.0 universal (revision a09e6f04d4204607d821d9b742dcf7ffe9c4e2f5)
>  - Transport: WebUsbTransport 

 _Originally posted by @Ondra-Zik-SL in [#19830](https://github.com/trezor/trezor-suite/issues/19830#issuecomment-3125985540)_

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

This PR fixes confirmation steps highlighting in tx review modal for approve/revoke flow.

## Related Issue

Resolve #20404

## Screenshots:

https://github.com/user-attachments/assets/35966be6-7798-4619-82e5-9fd6ce8b710d

https://github.com/user-attachments/assets/58061421-bd3d-4aba-a88c-2915a85ecaa3

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/token-approval-tx-flow&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/token-approval-tx-flow&lookback=7)

### CODE REVIEW

**Review by izmy — APPROVED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx [hunk 1]
```diff
@@ -86,11 +84,8 @@ export const TransactionReviewOutputList = ({
         selectSendFormReviewLastButtonCode(state, symbol),
     );
 
-    const totalRecipients = outputs.filter(({ type }) => type === 'address').length;
-    const hasOpReturn = outputs.some(output => output.type === 'opreturn');
-
     const reviewState = getTransactionReviewState({
-        index: totalRecipients * TOTAL_STEPS_PER_RECIPIENT + (hasOpReturn ? 1 : 0),
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx:93]: this is btc specific, please check that it does not break bitcoin like coins

Comment (matusbalascak) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx:93]: I tested even with multiple recipients and everything was working correctly
