### PR TITLE
Fix/pin-passphrase-loading design

### LINKED ISSUE #1118: Passphrase: Styling
**Zeplin** [here ](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/dashboard?seid=5e315abc3c48197f8d2cc4b7)

**InVision flow** [here](https://projects.invisionapp.com/share/Y8VQJ28PUZ7#/screens/402575375_7-5-0-Pass_Source_Select_-_Home_-)

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/1118

### CODE REVIEW

File: packages/suite/src/components/suite/images/DeviceConfirmImage/index.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+}
+
+const getImage = (majorVersion: number) => {
+    switch (majorVersion) {
+        case 1:
+            return 'one-device-confirm';
+        case 2:
+            return 't-device-confirm';
+        default:
+            return 'T2';
```
Comment (mroz22) [inline packages/suite/src/components/suite/images/DeviceConfirmImage/index.tsx]: kviiik

**Review by mroz22 — APPROVED** [review]
