### PR TITLE
fix(suite-native): remove jws as env variable

### LINKED ISSUE #11760: Missing ERC20 tokens from transaction history and from My assets section
**Describe the bug**
Missing ERC20 tokens from transaction history and from `My assets` section

**Info:**

-   Mobile Suite Version: 24.4.1 / 6adc53f
-   OS: iOS
- Ethereum Address: 0xAbDf06c8Aa5b44FAa601394da733235A06C4285A

**Screenshots**
image
image
image
image

### PR DESCRIPTION
**Pull request by juriczech**
## Description
JWS token is located in code and it's unnecessary to use it as environment variable so I removed it and added it to envUtils.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11760

## Screenshots:
image

### CODE REVIEW

**Comment by juriczech** [comment]
@SocketSecurity ignore-all

File: suite-common/wallet-constants/src/jws.ts [hunk 1]
```diff
@@ -1,12 +1,5 @@
-const publicKey = {
+export const publicKey = {
     dev: '-----BEGIN PUBLIC KEY-----MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEbSUHJlr17+NywPS/w+xMkp3dSD8eWXSuAfFKwonZPe5fL63kISipJC+eJP7Mad0WxgyJoiMsZCV6BZPK2jIFdg==-----END PUBLIC KEY-----',
     codesign:
         '-----BEGIN PUBLIC KEY-----MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAES7MbBzU/v5BsljkTM8Mz0Jsk+Nn5n2wH\no2/+MUI3TgCVdTbEHhn3HXaY7GJ6TLyWqxn+pIDY9wUUAyUqOStTUQ==-----END PUBLIC KEY-----',
 };
-
-export const getJWSPublicKey = () => {
-    const isCodesignBuild = process.env.IS_CODESIGN_BUILD === 'true';
-    console.log(`Bundling ${isCodesignBuild ? 'production' : 'develop'} public key.`);
```
Comment (matejkriz) [inline suite-common/wallet-constants/src/jws.ts:9]: This is removed without replacement, right? It's probably fine, not sure if anyone checking this log. If so, it would be ease to put it back on the place where it was used (but keep it outside this method). cc @komret

**Review by matejkriz — APPROVED** [review]
Nice simplification. 

It should be ease to get rid off JWS_PUBLIC_KEY completely as followup. Just use getJWSPublicKey in messageSystemThunks same way as it is used in tokenDefinitionsThunks... 

tested:
- suite web on sldev
- suite-desktop build on github
- suite-desktop local mac build

not tested:
- codesign build

File: suite-common/wallet-constants/src/jws.ts (hunk 1 above)
Comment (juriczech) [reply suite-common/wallet-constants/src/jws.ts:9]: Yes, log was removed, I forgot to mention that in description. Hopefully it's fine, if now, I'll return it in a follow-up.
https://github.com/trezor/trezor-suite/issues/11817
