### PR TITLE
fix/address and xpub not showing on device when the device has no backup

### LINKED ISSUE #19062: Address and XPUB not showing on device when the device has no backup
**Describe the bug**
If I have a device that has seed but no backup yet, I can go to the address verification or XPUB and after selecting to confirm on the device, the device doesn't show me the address or XPUB. There should be probably some warning and after that the address has to be shown (same as it is on desktop)

**Info:**

- Mobile Suite Version: 25.5.1
- OS: Android

**How to reproduce**

1. Connect device without a backup
2. Navigate to any receive address
3. Proceed to verify on the Trezor
4. The device won't show the address
Same goes for XPUB

**Expected behavior**
I am shown a warning about the backup needed and after that I am shown the address or XPUB on the device.

### PR DESCRIPTION
**Pull request by OriginalEveres**
Show device no backup warning bottom sheet when user wants to display receive address or xpub.

## Description

- `WalletBackupNotSetBottomSheet.tsx`
  - bottom sheet that notifies user about not having a backed up device
  - when user choose to "Continue anyway" the bottom sheet sends confirmation to Trezor (needed for showing xpub/receive adress when device has no backup)
- Implemented the warning
  - `ReceiveAddressScreen.tsx`
  - `AccountSettingsShowXpubButton.tsx`
- added `@trezor/connect` and `@suite-native/module-device-onboarding` as deps to `@suite-native/module-accounts-management` mainly because of the need to call to device and use the new bottom sheet
- added new translations to the `en.ts` for the bottom sheet

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19062

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/address-and-XPUB-not-showing-on-device-when-the-device-has-no-backup&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/address-and-XPUB-not-showing-on-device-when-the-device-has-no-backup&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/address-and-XPUB-not-showing-on-device-when-the-device-has-no-backup&lookback=7)

### CODE REVIEW

File: suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx [hunk 1]
```diff
@@ -1,19 +1,75 @@
...
+import { Account } from '@suite-common/wallet-types';
+import { getDerivationType, isAddressBasedNetwork } from '@suite-common/wallet-utils';
+import { Button, useBottomSheetModal } from '@suite-native/atoms';
 import { Translation } from '@suite-native/intl';
+import { WalletBackupNotSetWarningBottomSheet } from '@suite-native/module-device-onboarding';
 import { XpubQRCodeBottomSheet } from '@suite-native/qr-code';
+import TrezorConnect, { Success, Unsuccessful } from '@trezor/connect';
 import { convertTaprootXpub } from '@trezor/utils';
 
+export const showXpubOnDevice = async (device: TrezorDevice, account: Account) => {
```
Comment (OriginalEveres) [inline suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: I put the showXpubOnDevice here, because we do not use it elsewhere in mobile app. 

This could be simplified and put into a shared package, but it would require a bit more refactoring. Eg.: we could make use of `showXpub` in `publicKeyActions.ts`

File: suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx [hunk 2]
```diff
@@ -8,6 +8,10 @@ import {
 
 import { AppTabNavigator } from '../AppTabNavigator';
 
+jest.mock('@suite-native/module-device-onboarding', () => ({
```
Comment (OriginalEveres) [inline suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx]: I'm not sure if this is the best solution, but I needed to mock the bottom sheet in order to pass the test. It was being rendered no matter what.

File: suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx [hunk 3]
```diff
@@ -1,19 +1,75 @@
...
+            break;
+        case 'solana':
+            response = await TrezorConnect.solanaGetPublicKey(params);
+            break;
+        default:
+            response = {
+                success: false,
+                payload: { error: 'Method for getPublicKey not defined', code: undefined },
+            };
+    }
```
Comment (juriczech) [inline suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: It seems like it's duplicity of `showXpub` from `packages/suite/src/actions/wallet/publicKeyActions.ts`. I'd prefer to have this in a function that is globally shared and used in both places 🙏

**Review by juriczech — CHANGES_REQUESTED** [review]

File: suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx (hunk 3 above)
Comment (OriginalEveres) [reply suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: it is, but publicKeyActions.ts also contain desktop related logic to modals, I believe I`ve added some comment to this file

Comment (OriginalEveres) [reply suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: https://github.com/trezor/trezor-suite/pull/19620/files#r2151936075

Comment (juriczech) [reply suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: You can just extract the code that's same into a function and call from both places. That should be pretty simple, no?

Comment (OriginalEveres) [reply suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: Yes, it is simple. Initially I planned to do a little bit of refactoring later (since there is more stuff to be globally shared), but I have moved now the function into a wallet-core common module.

File: suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx]: @jbazant What do you think about this?

**Review by juriczech — APPROVED** [review]
Code looks good to me. Haven't tested it.

File: suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx (hunk 2 above)
Comment (jbazant) [reply suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx]: `GorhomBottomSheet` is mocked in tests as component that just renders its content (See [`@gorhom/bottom-sheet/mock`](https://github.com/gorhom/react-native-bottom-sheet/blob/master/mock.js)). 🤷 

Therefore this is IMO valid solution.

But I would do it a bit differently:
- create file `suite-native/module-device-onboarding/src/jest.setup.ts`
```ts
jest.mock('./components/SwipeableWalkthrough/HoldToConfirmButton', () => ({
    HoldToConfirmButton: () => null,
}));
```
- and update `jest.config.native.js`
```diff
        '<rootDir>/../../suite-native/module-connect-popup/src/jest.setup.ts',
+.       '<rootDir>/../../suite-native/module-device-onboarding/src/jest.setup.ts',
    ],
```
