### PR TITLE
fix(suite): do not remove leading zereos on the incomplate number

### LINKED ISSUE #12106: Disappearing zero while adding small amounts in send form
https://github.com/trezor/trezor-suite/assets/152851523/20b64d81-83d2-45a0-a605-0d8cadc50bc9

While you will be at it, please also fix this thingy 

https://github.com/trezor/trezor-suite/assets/152851523/ecdcf266-bfc5-494a-bd1c-2bc592f17fdd

### PR DESCRIPTION
**Pull request by peter-sanderson**
When typing `0,` or just `,000` the number is not complete and cannot be normalized. 

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/12106

image
image
image
image

### CODE REVIEW

File: packages/suite/src/components/suite/NumberInput.tsx [hunk 1]
```diff
@@ -34,7 +32,7 @@ const cleanValueString = (value: string, locale: Locale) => {
 
     const { decimalSeparator, thousandsSeparator } = getLocaleSeparators(locale);
 
-    // clean the entered number string if it's not convertable to Number or if it has a non-conventional format
+    // clean the entered number string if it's not conversable to Number or if it has a non-conventional format
```
Comment (komret) [inline packages/suite/src/components/suite/NumberInput.tsx]:
```suggestion
    // clean the entered number string if it's not convertible to Number or if it has a non-conventional format
```
😅

**Review by komret — CHANGES_REQUESTED** [review]

**Review by komret — APPROVED** [review]
