### PR TITLE
Fix/3153 Labelling - Cursor dismissed when clicking account title during editing label

### LINKED ISSUE #3153: Labelling - Cursor dismissed when clicking account title during editing label
**Describe the bug**
Clicking anywhere during label editing results in cursor dismissal and needs to be confirmed or 

**Info:**
 - Suite Version: app/web, commit 
 - Browser: , version
 - OS: 
 - Firmware Version: model , revision 

**Steps to reproduce:**
Prerequisite - labelling enabled.
1. Select an arbitrary account and select edit label
2. Click into the account name field (instead of typing),
3. Type the new label title.

**Expected result:**
Cursor is displayed and label editing stays active until it is confirmed, dismissed or navigated to another screen.

**Actual result:**
Cursor is hidden and editing can not be resumed after clicking anywhere during editing.

**Screenshots:**
Screen-Recording-2020-12-08-at-1 (1)

### PR DESCRIPTION
**Pull request by dimasivan**
fix caret and its position:
labeling wallet :white_check_mark:  
labeling account :white_check_mark: 
labeling transaction :white_check_mark: 

fix #3153

### CODE REVIEW

**Review by tomasklim — CHANGES_REQUESTED** [review]
I would change the cursor to `cursor: text` when editing of the label is enabled. 🔴 

- Transactions ✅ 
- Received address ✅ 
- Account ✅ 
- Switch wallet ✅

File: packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx [hunk 1]
```diff
@@ -23,9 +23,20 @@ const Placeholder = styled.div`
...
+        !props.value
+            ? `
+          ${props.isButton ? `left: 22px;` : `left: 0;`}
+          right: 0;
+          position: absolute;`
+            : `
+          position: unset;
+      `}
+
     color: ${props => (!props.touched ? props.theme.TYPE_LIGHT_GREY : 'inherit')};
```
Comment (tomasklim) [inline packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx]:
```suggestion
    color: ${props => (!props.touched ? props.theme.TYPE_LIGHT_GREY : 'inherit')};
    
    ${props =>
        props.value &&
        css`
            position: unset;
        `}
        
    ${props =>
        !props.value &&
        css`
          left: ${props.isButton ? '22px' : '0px'}
          right: 0;
          position: absolute;`}

```

Comment (dimasivan) [reply packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx]: 45460d0

**Review by tomasklim — CHANGES_REQUESTED** [review]
- [x] Is it possible to add e.preventDefault to the whole rectangle? I missed the ✅  button by 1px and it closed the modal. I also clicked on disabled `[Loader] Edit Label` and `[Check] Renamed` buttons and it closed the modal 😢
Screenshot 2021-10-27 at 14 22 42

- [x] Cursor was not changed in the previous review. I would like to have `cursor: text` over the input when editing of the label is active. 
(e.g. when mouse cursor is over `Bitcoin #1` input)
Screenshot 2021-10-27 at 14 26 31

**Comment by dimasivan** [comment]
>     * [x]  Is it possible to add e.preventDefault to the whole rectangle? I missed the white_check_mark  button by 1px and it closed the modal. I also clicked on disabled `[Loader] Edit Label` and `[Check] Renamed` buttons and it closed the modal cry
>       Screenshot 2021-10-27 at 14 22 42
> 
>     * [x]  Cursor was not changed in the previous review. I would like to have `cursor: text` over the input when editing of the label is active.
>       (e.g. when mouse cursor is over `Bitcoin #1` input)
>       Screenshot 2021-10-27 at 14 26 31

@tomasklim 674c0e6e522ab1cc48540f7ae73f95122ef75ea7

`cursor: text` is already presented on your screenshot, but it was missed in the account select modal

**Review by tomasklim — APPROVED** [review]
