### PR TITLE
fix(suite-native): refactor block navigation hooks

### LINKED ISSUE #21982: Refatoring navigation blocker hooks

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

Fixing the logic for blocking iOS gestures.

also fix: 
https://github.com/user-attachments/assets/456dd4fd-f1e7-4231-9a30-36e55986b0fa

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21982 
https://github.com/trezor/trezor-suite/issues/21959

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/useoverride-navigation&lookback=7)

### CODE REVIEW

File: suite-native/module-device-settings/src/screens/ContinueOnTrezorScreen.tsx [hunk 1]
```diff
@@ -1,9 +1,14 @@
...
 
 import { DeviceInteractionScreenWrapper } from '../components/DeviceInteractionScreenWrapper';
 
-export const ContinueOnTrezorScreen = () => (
-    <DeviceInteractionScreenWrapper>
-        <ContinueOnTrezorScreenContent />
-    </DeviceInteractionScreenWrapper>
-);
+export const ContinueOnTrezorScreen = () => {
+    useHandleHardwareBackNavigation();
```
Comment (juriczech) [inline suite-native/module-device-settings/src/screens/ContinueOnTrezorScreen.tsx]: On this screen, it doesn't seem to work well. 

If you go to change pin and swipe back on Continue on Your trezor, there's a bug

**Review by juriczech — CHANGES_REQUESTED** [review]
Noticed one issue. Other things seem to work as expected 👏

File: suite-native/module-device-settings/src/screens/ContinueOnTrezorScreen.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/module-device-settings/src/screens/ContinueOnTrezorScreen.tsx]: fixed, sorry I had to rebase so it got lost in the initial commit but the fixed has been applied directly in the iOS hook

File: suite-native/navigation/src/hooks/useDisableIOSGesture.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+        if (Platform.OS === 'ios') {
+            const disableGestures = (nav: typeof navigation) => {
+                nav?.setOptions({ gestureEnabled: false });
+                const parent = nav?.getParent?.();
+                if (parent) {
+                    disableGestures(parent);
+                }
+            };
+
+            disableGestures(navigation);
```
Comment (juriczech) [inline suite-native/navigation/src/hooks/useDisableIOSGesture.ts]: Please create a callback for this that takes a param as it's same as the function below (apart from the param).

Comment (BrantalikP) [reply suite-native/navigation/src/hooks/useDisableIOSGesture.ts]: https://github.com/trezor/trezor-suite/pull/21983/commits/1bc7d0fe928efc096806eaa95e69422b87576399

**Review by juriczech — APPROVED** [review]

**Comment by juriczech** [comment]
Works well. Thanks for this! 💪

**Comment by PeKne** [comment]
🎉
