### PR TITLE
Fixing circular modules vol. 1

### LINKED ISSUE #23731: Circular dependencies
### The issue

Currently, there a lot of circular dependencies which lead to unexpected issues. 

__Circular dependencies types__:
1. __ESM (ecma-script module) circular modules__ ->  They cause __runtime errors__ such as __undefined ESM__ during import. These are high prio to be fixed.
2. __Typescript circular references__ -> They won't cause any runtime errors. They might or might not cause perf. and memory issues during type-check and types resolvement. AFAIK it needs further analysis. 

----

### The process

1. Distinguishing between those cir. dep. and get only the ESM cir. modules.
   - This can be done by adjusting ESLint rules to require `type` keyword in imports/exports for all types.
   - Then we run special script applying `eslint --fix` across the codebase. A special script because the traditional eslint --fix fails due enormous input amount.
   - Then we can run adjust madge command to exclude `type` imports/exports leaving us with the ESM modules.
2. Fixing all ESM modules in initial state (i.e. without added the `type` keywords -> focusing only on fixing the ESM modules, not introducing another issue in this step)
3. Doing analysis and research if the TS cir. references are causing any real harm or not.

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

- Based on my analysis, there are 19 circular ESMs of 71 total (i.e. including 52 TS circular references).
- This PR focuses on fixing the ESM ones.
- I've solved 16/19. The `1)` and `2)` are going to be solved during working on Connect 10 by the Connect Team and the `3)` should be solved as I was told during a refactoring planned by @juriczech soon. 
- Each commit fixes single or related circular ESMs. So the PR can be hopefully reviewed quite easily even though it shows so many changes. 🙏 
- There's __no other coding logic introduced__ in the PR (apart of enabling eslint concurrency), other than moving stuff around and adjusting imports to prevent circular ES modules. 

## Changes overview

@trezor/suite-mobile:
* fix: use direct imports to avoid cir. ESM in device and firmware in suite-native

__package/components__:
* ~~fix(components): move TableContext to separate file to prevent circular ESMs~~ fixed by @mroz22 

__package/suite__:
* fix(suite): move common util to separate file to avoid cir. ESM in onboarding steps
* fix(suite): use direct import to avoid cir. ESM in AnalyticsConsentScreen
* fix(suite): prevent cir. ESMs in TransactionReviewModal by moving common types and utils to separate files
* fix(suite): divide metadata actions to thunks and plain actions to prevent circular ESMs

__suite-common/*__:
* fix: circular ESMs between wallet-core and bluetooth, thp packages
* fix(wallet-utils): move amounts utils from accountsUtils to amountsUtils to prevent circular ESMs
* fix: move asBaseCurrencyAmount to wallet-types to prevent circular ESMs
* fix(wallet-core): move thunk from actions to thunks to prevent circular ESMs

----

__Before:__
```
1) packages/connect/src/data/DataManager.ts > packages/connect/src/data/firmwareInfo.ts
2) packages/connect/src/data/DataManager.ts > packages/connect/src/data/firmwareInfo.ts > packages/connect/src/utils/firmwareUtils.ts
6) suite-common/wallet-utils/src/baseCurrency.ts > suite-common/wallet-utils/src/fiatConverterUtils.ts
7) suite-common/wallet-utils/src/accountUtils.ts > suite-common/wallet-utils/src/stakingUtils.ts > suite-common/wallet-utils/src/solanaStakingUtils.ts
8) suite-common/wallet-utils/src/accountUtils.ts > suite-common/wallet-utils/src/transactionUtils.ts
9) suite-common/wallet-core/src/settings/walletSettingsReducer.ts > suite-common/wallet-core/src/settings/walletSettingsActions.ts
10) suite-common/wallet-core/src/index.ts > suite-common/wallet-core/src/device/deviceThunks.ts > suite-common/bluetooth/src/index.ts > suite-common/bluetooth/src/bluetoothReducer.ts
11) suite-common/wallet-core/src/index.ts > suite-common/wallet-core/src/device/deviceThunks.ts > suite-common/thp/src/index.ts > suite-common/thp/src/autoInitThpAfterDeviceConnectionThunk.ts
12) suite-common/wallet-core/src/index.ts > suite-common/wallet-core/src/device/deviceThunks.ts > suite-common/thp/src/index.ts > suite-common/thp/src/finishThpAutoconnectThunk.ts
13) suite-common/wallet-core/src/index.ts > suite-common/wallet-core/src/device/deviceThunks.ts > suite-common/thp/src/index.ts > suite-common/thp/src/removeThpAutoconnectThunk.ts
14) packages/suite/src/actions/suite/metadataActions.ts > packages/suite/src/actions/suite/metadataProviderActions.ts
27) packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModal.tsx > packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalBody.tsx
28) packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalBody.tsx > packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalBodyInner.tsx > packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewModalBottomContent.tsx
29) packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalBody.tsx > packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalBodyInner.tsx > packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewModalContent.tsx
30) packages/suite/src/components/suite/index.tsx > packages/suite/src/components/suite/Preloader/Preloader.tsx > packages/suite/src/views/start/AnalyticsConsentScreen.tsx
31) packages/suite/src/views/onboarding/steps/SelectBackupType/SelectBackupType.tsx > packages/suite/src/views/onboarding/steps/SelectBackupType/FloatingSelections.tsx
32) suite-native/device/src/index.ts > suite-native/device/src/hooks/useDetectDeviceError.tsx > suite-native/firmware/src/index.ts > suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
```

__After:__
```
1) packages/connect/src/data/DataManager.ts > packages/connect/src/data/firmwareInfo.ts
2) packages/connect/src/data/DataManager.ts > packages/connect/src/data/firmwareInfo.ts > packages/connect/src/utils/firmwareUtils.ts
11) suite-common/wallet-core/src/device/deviceThunks.ts > suite-common/thp/src/autoInitThpAfterDeviceConnectionThunk.ts
```

image

## Related Issue

Resolve #23731 

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/23731-circular-modules&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/23731-circular-modules&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/23731-circular-modules&lookback=7)

### CODE REVIEW

File: suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { useSelector } from 'react-redux';
 import { useNavigation } from '@react-navigation/native';
 
 import { selectThpStep } from '@suite-common/thp';
-import { FirmwareInstallationScreenContent } from '@suite-native/firmware';
+import { FirmwareInstallationScreenContent } from '@suite-native/firmware/src/components/FirmwareInstallationScreenContent';
```
Comment (juriczech) [inline suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: This is exactly something that we don't want to do, right? Why is this better? You don't get an error and just hide the problem IMO.

Comment (cermakjiri) [reply suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: Fair point and thanks for the feedback. I agree this is not the perfect solution. After all the goal was to fix the cir. modules which lead to unpredictable bugs (e.g. undefined imports, memory leaks) and then iterate forward. 

The pain point here is the huge `index.ts` files aggregating all type of exports into single access point. It's nice from package encapsulation point of view but it's very prone to these cir. modules. So how can we fix it without these nested imports?

1. __Recompose__:
Extract the common code code into new (3rd) package.
2. __Create specialized index files__
  I mean instead of creating single huge index file, let's create index file per `components`, `hooks`, `actions`, etc., i.e. index file for each category/type of exports.
  This would allow to preserve current package structure and could still offer package encapsulation.
 3. __??__

I believe the 2nd solution would suite this use-case the best:
```diff
- import { FirmwareInstallationScreenContent } from '@suite-native/firmware/src/components/FirmwareInstallationScreenContent';
+ import { FirmwareInstallationScreenContent } from '@suite-native/firmware/components';
```

Also, maybe there's no need to always created these specialized index files. Instead as the package grows, it could come naturally. You know, why to over-engineer it from the beginning.

What do you think?

Comment (juriczech) [reply suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: I actually think number one is the desired way to do this and is in line with how we approach packages. The point of these packages is to export from index files to allow this kind of composition. 

I do agree that not all places are ideal and we do have circular deps across packages, but your proposed solution will only lead to more and more of these, if it becomes standard. IMO, this doesn't fix the problem unfortunately. 

What does @matejkriz think about this? I don't want to block this PR, but I also don't want to go this way because once we do, it will be even harder to get out of it. 😢

Comment (juriczech) [reply suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: Disclaimer: I haven't spent much time actually digging into what's the source of the problem here, just commenting on the approach at first glance. 

Tomorrow I could look into this in greater detail and see where the problem is and we could discuss how to restructure it if you won't object with going with the restructure of packages.

Comment (cermakjiri) [reply suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: > I do agree that not all places are ideal and we do have circular deps across packages, but your proposed solution will only lead to more and more of these, if it becomes standard. IMO, this doesn't fix the problem unfortunately.

Why do you think that? Sorry but I don't see that. This approach worked very well for me on other huge projects. The nice thing about it, there's no need to create more packages and potentially complicate the structure. 
I don't by any mean forcing it here just wanted to be clear what I meant and it can bring.

I think it's fine to properly discuss it and find the best suitable approach, no pressure. :)

Comment (juriczech) [reply suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: Yeah, I appreciate that. As well as you jumping into thing like this to improve our codebase. 

Agreed, I think we need to discuss whether this is acceptable to export straight from the files rather than from the package itself.

Comment (cermakjiri) [reply suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: What do you think @juriczech, @trezor/suite-mobile? Are you ok with adding `index` file to `components` and possibly other top level package dirs to allow importing only specific module category and thus to avoid oversized single index which soon or later leads to cir. dep.?

File: suite-common/wallet-types/src/baseCurrency.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+import { Branded } from '@trezor/type-utils';
+
+/**
+ * Value in EUR, USD, ... but also it can be in BTC, currently the global BaseCurrency from the Settings is used.
+ * In case of BTC this also can contain value converted to Sats. // Todo: Consider to separate those situations.
+ */
+export type BaseCurrencyAmount = BigNumber & Branded<`base-currency-amount`>;
+export const asBaseCurrencyAmount = (value: BigNumber) => value as BaseCurrencyAmount;
```
Comment (TomasBoda) [inline suite-common/wallet-types/src/baseCurrency.ts:9]: `BigNumber` not imported from `@trezor/utils` here

Comment (cermakjiri) [reply suite-common/wallet-types/src/baseCurrency.ts:9]: Good point, thanks. Fixed. ✅

File: suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx (hunk 1 above)
Comment (cermakjiri) [reply suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx:7]: Discussed with @juriczech on Google Meet. Let me summarize it: 

We agreeded this solution is fine for fixing circular module and that's the goal of this PR. And that there'll be a new issue created with the goal of solving package circular reference too. Here's the issue: https://github.com/trezor/trezor-suite/issues/23931

**Review by izmy — APPROVED** [review]
