### PR TITLE
Adjust signTransactions params

### LINKED ISSUE #1599: DASH, DOGECOIN, NAMECOIN, ZCASH - Sign transaction error: Invalid parameters
**WHERE:** suite browser version, suite app (nixos, 20-Apr-2020 11:26)

**Expected:**
User can sign and confirm transaction for said coins.

**Actual:**
Suite (both app and browser version) will display the following errror: "Sign transaction error: Invalid parameters: Parameter "amount" has invalid type. "string" expected."

DASH SUITE WEB string
DOGECOIN SUITE WEB string
NAMECOIN SUITE WEB string
ZCASH SUITE WEB string

### PR DESCRIPTION
**Pull request by vladimirvolek**
resolves: https://github.com/trezor/trezor-suite/issues/1599

The separated issue for zcash bug: https://github.com/trezor/trezor-suite/issues/1675

### CODE REVIEW

File: packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts [hunk 1]
```diff
@@ -150,8 +150,18 @@ export const send = () => async (dispatch: Dispatch, getState: GetState) => {
...
     }));
 
-    // TODO: add more params to alt coins txs (zcash: version_branch_id & version, etc...)
-    const signedTx = await TrezorConnect.signTransaction({
+    let signEnhancement = {};
+
+    if (account.symbol === 'zec') {
+        signEnhancement = ZEC_SIGN_ENHANCEMENT;
+    } else {
+        // connect undefined amount hotfix (not for zcash)
```
Comment (szymonlesisz) [inline packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts]: why not for zcash? zcash is not affected by this?
