### PR TITLE
fix: Add some exclusion to types to better handle remmaped DeviceEvent type to Redux Actions

### LINKED ISSUE #16839: Refactoring: TrezorConnectEvents
Actions are now defined in two different ways. There was an attempt to unify it in https://github.com/trezor/trezor-suite/pull/16477, but not really finished. Check [this thread](https://github.com/trezor/trezor-suite/pull/16477#discussion_r1933744510) and come up with some reasonable (simple 🙏 ) solution.

### PR DESCRIPTION
**Pull request by peter-sanderson**
This is an alternative (compromise) solution to [this](https://github.com/trezor/trezor-suite/issues/16839#issuecomment-2710311736) problem.

Resolves: https://github.com/trezor/trezor-suite/issues/16839

@coderabbitai ignore

### CODE REVIEW

File: packages/type-utils/src/utils.ts [hunk 1]
```diff
@@ -108,3 +108,23 @@ export type DefinedUnionMember<T> = T extends string ? T : never;
...
+ *
+ *  // { type: 'A', a: string } | { type: 'B', b: number } | { type: 'D' | 'E', cde: boolean };
+ *  type NotC = FilterOutFromUnionByTypeProperty<T1, 'C'>;
+ *  ```
+ */
+export type FilterOutFromUnionByTypeProperty<T, U> = T extends { type: infer P }
+    ? P extends U
+        ? never
+        : { type: Exclude<P, U> } & Omit<T, 'type'>
+    : T;
```
Comment (Lemonexe) [inline packages/type-utils/src/utils.ts]: Suggestion for enhancement - several things:
- mainly a new generic argument instead of hardcoded `'type'` :pray: 
- I personally prefer named types everywhere, instead of `T,P,U` one-letter variables for generics :shrug: 
- also new safeguard  `ValueToExclude extends Union[KeyName]`, because without it you can do this: 
`type WhatIsThis = FilterOutFromUnionByTypeProperty<T1, 'type', 123>;`

EDIT: fixed
```
/**
 * Removed the type from the union where `{ KeyName: ValueToExclude }`.
 *
 * Example:
 *  ```
 *  type T1 =
 *     | { type: 'A'; a: string }
 *     | { type: 'B'; b: number }
 *     | { type: 'C' | 'D' | 'E'; cde: boolean };
 *
 *  // { type: 'A', a: string } | { type: 'B', b: number } | { type: 'D' | 'E', cde: boolean };
 *  type NotC = FilterOutFromUnionByTypeProperty<T1, 'type', 'C'>;
 *  ```
 */
export type FilterOutFromUnionByTypeProperty<
    Union,
    KeyName extends keyof Union,
    ValueToExclude extends Union[KeyName],
> = Union extends { [K in KeyName]: infer ActualValue }
    ? ActualValue extends ValueToExclude
        ? never
        : { [K in KeyName]: Exclude<ActualValue, ValueToExclude> } & Omit<Union, KeyName>
    : Union;
```

File: packages/suite/src/views/onboarding/UnexpectedState/index.tsx [hunk 2]
```diff
@@ -44,7 +43,7 @@ const UnexpectedState = ({ children }: UnexpectedStateProps) => {
         }
 
         return deviceId !== prevDeviceId;
-    }, [prevDevice, device]);
+    }, [prevDeviceId, device]);
```
Comment (Lemonexe) [inline packages/suite/src/views/onboarding/UnexpectedState/index.tsx:46]: if I understand correctly, the reason for this change is that the `useEffect` would fire after each connect state update unnecessarily, because `prevDevice` is unstable?

**Review by Lemonexe — APPROVED** [review]
LGTM!

File: packages/type-utils/src/utils.ts (hunk 1 above)
Comment (peter-sanderson) [reply packages/type-utils/src/utils.ts]: I knew you would love thy TS stuff :smile:

File: packages/suite/src/views/onboarding/UnexpectedState/index.tsx (hunk 2 above)
Comment (peter-sanderson) [reply packages/suite/src/views/onboarding/UnexpectedState/index.tsx:46]: No, it is just that in that action the device is either `Deice | TrezorDevice` those two types are (temporarily) incompatible and Marek pointed to me, that all I need is `id` (not the whole `device`). So I simplified it to just `id` avoiding the `Device` vs `TrezorDevice` madness at all.

**Review by Lemonexe — APPROVED** [review]
oh, you didn't have to credit me, you're too nice :blush:
