### PR TITLE
fix(trading): enhance default asset creation with network symbol support

### LINKED ISSUE #24381: ETH is not preselected in Buy section when coming from ETH account (BTC is selected by default)
**Describe the bug**
When navigating to the Buy section from an ETH account, Bitcoin is preselected as the cryptocurrency. ETH should be preselected in this case to match the user's context. This is confusing and leads to errors if a user is expecting to buy ETH but sees BTC options instead.

**Info:**
 - Suite version: desktop 26.1.1 (72ba67df1a5d11a69ea2ee1cf4d04b1563d78eba)
 - Browser: Trezor Suite 26.1.1
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3W1 2.10.0 universal (revision de4b70e2e89a64f3894dba2124f6ec56e5cbd088)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**How to reproduce**
1. Go to an ETH account in Suite after fresh discovery
2. Enter the Buy section from that account's page
3. See that Bitcoin is preselected instead of ETH

**Expected behavior**
ETH should be preselected in the Buy section if coming from an ETH account page.

**Screenshots**

https://github.com/user-attachments/assets/cb2a094f-19ab-4c93-a6f4-47338a1de0c7

### PR DESCRIPTION
**Pull request by sherpaPSX**
## Description

Fix buy default assent on wallet fresh load

## Notes for QA

Try to replicate steps described in the issue

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/24381

## Screenshots:

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/buy-default-asset&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/buy-default-asset&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.ts [hunk 1]
```diff
@@ -36,9 +37,16 @@ export const useTradingBuyFormDefaultValues = (
         ? (buyInfo?.buyInfo?.country as TradingCountryCode | undefined)
         : regional.UNKNOWN_COUNTRY;
     const defaultCountry = useMemo(() => getDefaultCountry(country), [country]);
+
+    // For testnet accounts, use default currency instead of casting to mainnet-only type
+    const isTestnetAccount = networks[accountSymbol]?.testnet ?? false;
```
Comment (vytick) [inline packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.ts]: maybe this?
```suggestion
    const isTestnetAccount = !!networks[accountSymbol]?.testnet;
```

**Review by vytick — APPROVED** [review]

File: packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.ts (hunk 1 above)
Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.ts]: you are right
