### PR TITLE
fix(suite-native): connect device copy changes

### LINKED ISSUE #10005: Copy changes
1. Portfolio tracker (iOS)
- [x] #10039

2. Android connected Trezor 

- [x] #10056
- [x] #10057
- [x] #10058
- [x] #10059
- [x] #10060

### LINKED ISSUE #10039: Copy changes iOS
**Welcome flow**
1. Screen Track balances:
Current: Easily sync your coin addresses and keep up with the crypto on your hardware wallet without exposing your private data.
New: Easily sync your coin addresses and keep up with the crypto on your hardware wallet.

2. Consent analytics screen:
Current: Help us help you
New: Better with you

Current: We’re all about making the best, most user-friendly app for you. You can help us achieve it.
New: Improve Trezor Suite Lite with your anonymous data.

Current: Your data is safe
New: Your data is private

Current: Rest assured, we’re all about respecting your privacy - no sensitive stuff like your balances, transactions, or profile specifics. 
New: We don't gather sensitive personal data like balances, transactions, or profile details.

Current: We gather info on app performance, user interaction, and technical issues to create a better experience for you. 
New: We collect data on app performance, user interaction, and potential technical issues to enhance the user experience.

3. Enable Biometric:
Current: Enable Face ID
New: Enable FaceID

**Empty dashboard**
Current: This requires your Trezor hardware wallet and access to Trezor Suite.
New: This requires access to Trezor Suite coin addresses.

Current: Sync my coins
New: Sync & Track

**Synced coin page**
Current: Coin synced
New: Confirm to add coin

### LINKED ISSUE #10056: Welcome flow
Welcome flow
1. Consent analytics screen:
Current: Help us help you
New: Better with you

Current: We’re all about making the best, most user-friendly app for you. You can help us achieve it.
New: Improve Trezor Suite Lite with your anonymous data.

Current: Your data is safe
New: Your data is private

Current: Rest assured, we’re all about respecting your privacy - no sensitive stuff like your balances, transactions, or profile specifics. 
New: We don't gather sensitive personal data like balances, transactions, or profile details.

Current: We gather info on app performance, user interaction, and technical issues to create a better experience for you. 
New: We collect data on app performance, user interaction, and potential technical issues to enhance the user experience.

### LINKED ISSUE #10057: Connect&Unlock flow
**Connecting&Unlock flow**

**Connect&Unlock screen**
Click on Question mark bottom sheet
Current: Connecting Trezor
New: Connect my Trezor

Current: Follow these steps:
New: Try these steps

Current:
1. Use different USB data cable. 
2. Use different USB port.
3. Use a different device

New:
1. Reconnect your Trezor
2. Use a different USB data cable
3. Use a different mobile device
4. Enable connection for Trezor Suite Lite via phone system message

**PIN entry Trezor ONE**
Enter PIN
Current: The keypad is displayed on your Trezor
New: Follow the keypad layout on your Trezor

**Enter PIN help (click on question mark)**
Current:
New: Follow the keypad layout on your Trezor device to enter your PIN on your mobile display. Your PIN will be hidden on your mobile display for your security. Learn more here. (Link: https://trezor.io/support/a/how-to-enter-pin-on-model-one)

**Wrong PIN inserted:**
Current: Entered wrong PIN
New: Incorrect PIN

Button Entry PIN help is missing (https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=2353%3A18741&mode=design&t=51d7K9uXZZNndSbV-1) - it should lead to: https://trezor.io/support/a/how-to-enter-pin-on-model-one

### LINKED ISSUE #10058: Receive flow
**Receive flow:**
**1. Bottom sheets with explanation after click on Show address**
#1 Bottom sheet
Current: Why is it important to verify
New: How to verify address

Current: Confirm that the address on your Trezor display matches the one on the following screen
New: Confirm that the address on your Trezor device matches the one on your mobile device.

#2 Bottom sheet
Current: Why is it important to verify on device?
New: Why verify on your Trezor

Current: While hacker can put fake info in your mobile phone, your Trezor’s screen always tells the truth. 
New: Your Trezor never lies. Mobile devices are vulnerable to hacks and malicious apps.

**2. Receive address confirming**
Current: The receive address shown above should match the one on your Trezor device.
New: This receive address should march the one on your Trezor device. 

**3. Bottom sheet click on element Confirm on Trezor**
Current: See the connected Trezor. The receive address shown here in the app should match the one on your Trezor device. 
New: Go to your device and verify that the receive address on your Trezor matches the one displayed here.

**4. Address does not match bottom sheet**
Current: The receive address shown on the app should march the one on your Trezor device. 
New: The receive address shown on the app should match the one on your Trezor device.

Current: 
- Always trust your trezor’s screen, it never lies. Your mobile may be vulnerable to hacks and security breaches. 
- For any security concerns about your app or device, contact Trezor Support. 

New: 
- Always trust your Trezor's screen, it never lies. Your mobile may be vulnerable to hacks and security breaches.
- For any security concerns about your app or device, contact Trezor Support.

**5. Address confirm screen** 
Current: receive address confirmed on Trezor
New: Receive address has been confirmed on your Trezor.

### LINKED ISSUE #10059: Dashboards
**Dashboard:**
**Empty dashboard (rozcestník)**
Current: I’ve got my Trezor
New: Connect my Trezor

Current: Connect to manage your assets
New: Manage your coins with your Trezor connected.

Current: Connect Trezor
New: Connect

Current: Sync coins without your Trezor
New: Track my coins

Current: Track your favorite cons anytime, anywhere, even when your Trezor isn’t connected.
New: Sync your favorite coins and track balances with portfolio tracker.

Current: Sync my coins
New: Sync & Track

**Empty wallet**
Current: We haven’t discovered any coins in your wallet. 
New: Your wallet is empty

Current: Get started by receiving coins
New: You need to get some coins first in Trezor Suite Desktop or Web version.

**Loading assets:**
Current: Still working
New: Retrieving balances

**Portfolio tracker empty dashboard**
Current: This requires your Trezor hardware wallet and access to Trezor Suite.
New: This requires access to Trezor Suite coin addresses.

### LINKED ISSUE #10060: Device info + Unsupported device connected
**Device info page:**
Current:: Get accessories @ Trezor Shop
New: Get swag for your device @ Trezor Shop

**Unsupported Trezor connected**
Error message - unsupported FW: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4064%3A24657&mode=design&t=vhogq6wFQ1Gcu0jX-1 
Error message - no FW installed: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=4068%3A24715&mode=design&t=vhogq6wFQ1Gcu0jX-1

### PR DESCRIPTION
**Pull request by PeKne**
## Description
Copy polishment of new screens related to connected device.

## Related Issue

Resolve #10005
Resolve #10039
Resolve #10056
Resolve #10057
Resolve #10058
Resolve #10059
Resolve #10060

### CODE REVIEW

File: suite-native/device/src/hooks/useDeviceConnect.tsx [hunk 1]
```diff
@@ -31,24 +31,32 @@ import { selectIsOnboardingFinished } from '@suite-native/module-settings';
...
+                </Text>
+                <Text color="textSubdued">
+                    <Translation id="moduleDevice.installFirmware.lines.2" />
+                </Text>
+                <Text color="textSubdued">
+                    {isConnectedDeviceUninitialized ? (
+                        <Translation id="moduleDevice.installFirmware.lines.3.update" />
+                    ) : (
+                        <Translation id="moduleDevice.installFirmware.lines.3.setUp" />
+                    )}
```
Comment (juriczech) [inline suite-native/device/src/hooks/useDeviceConnect.tsx]: nit: You could use the ternary operator only for the ID inside the prop param

**Review by juriczech — APPROVED** [review]

File: suite-native/device/src/hooks/useDeviceConnect.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/device/src/hooks/useDeviceConnect.tsx]: fixed
