### PR TITLE
fix(suite-sync): ignore allowance if quota manager is disabled

### LINKED ISSUE #24360: Labels not loaded after app restart
**Describe the bug**
I don't see previously added labels when I restart the Suite - develop.

**How to reproduce**

1. Add labels to remembered wallet
1. Restart Suite
1. See no labels

**Expected behavior**
- Suite should remember the keys and display the labels even when the Trezor is disconnected
- Btw it should work off-line as well.

### PR DESCRIPTION
**Pull request by juriczech**
## Description

This is a hotfix for cases when quota manager is disabled. If it's disabled, the allowance is checked when retrieving suite sync keys and it breaks suite sync. This is a temporary workaround that will be removed after we separate the concerns of quota manager and suite sync key retrieval. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/24360

https://github.com/user-attachments/assets/22710e2c-0985-4c5e-a204-e5d5abb65794

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/disconnected-device-with-quota-manager-disabled&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/disconnected-device-with-quota-manager-disabled&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/disconnected-device-with-quota-manager-disabled&lookback=7)

### CODE REVIEW

File: suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts [hunk 1]
```diff
@@ -37,3 +29,18 @@ export const selectOwnersAllowance = (state: WithSuiteSyncQuotaManagerState) =>
 
 export const selectIsQuotaManagerEnabled = (state: WithSuiteSyncQuotaManagerState) =>
     state.suiteSyncQuotaManager.enabled;
+
+// If device has an owner, is registered in quota manager and the owner
+// already has an allowance, there's nothing to refresh — return success.
```
Comment (peter-sanderson) [inline suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts]: nit (was already there I know): this comments seems unnecessary to me

File: suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts [hunk 2]
```diff
@@ -37,3 +29,18 @@ export const selectOwnersAllowance = (state: WithSuiteSyncQuotaManagerState) =>
...
+export const selectHasDeviceAllowance = (
```
Comment (peter-sanderson) [inline suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts]:
```suggestion
export const selectIsAllowanceRegistrationNeeded = (
```

Something like this would be better name IMO. WDYT @OriginalEveres

Comment (peter-sanderson) [reply suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts]: (that would reverse the condition obviously)

**Review by peter-sanderson — APPROVED** [review]

File: suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts (hunk 2 above)
Comment (juriczech) [reply suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts]: I would keep the change as minimal as possible ideally. We can rename this when we separate the concerns of `refreshSuiteSyncKeys` and do some refactor there. 👍 ?

File: suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts (hunk 1 above)
Comment (juriczech) [reply suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts]: Removed

Comment (OriginalEveres) [reply suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts]: I agree, thx @juriczech for addresing

File: suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts (hunk 2 above)
Comment (OriginalEveres) [reply suite-common/suite-sync-quota-manager/src/quotaManagerSelectors.ts]: Lets leave the renaming for later, but please mark this selector as obsolete
