### PR TITLE
fix(suite-native): Pending transactions

### LINKED ISSUE #6533: Pending transactions do not appear when asset transaction list is open
Asset transaction list screen fails to update when an incoming our outgoing pending transaction appears.

* iOS the app needs to be closed and re-opened.
* Android navigating back to my assets and reopening the asset successfully renders the pending transaction.

### PR DESCRIPTION
**Pull request by juriczech**
## Description
This is a follow up for pending transactions UI implementation. Previously, pending transactions were only working for BTC, because we weren't reconnecting to blockchain to get fiat rates for all enabled networks. This PR resolves that and allows for displaying pending transactions (viz video recording).

## Related Issue

Resolve [Pending transactions do not appear when asset transaction list is open#6533](https://github.com/trezor/trezor-suite/issues/6533)

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/36101761/196615078-032b78c2-cdd7-4a8d-a900-81ad3ceab759.mov

### CODE REVIEW

File: suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx [hunk 1]
```diff
@@ -65,7 +65,10 @@ const submitButtonStyle = prepareNativeStyle(utils => ({
 const DEFAULT_CURRENCY_SYMBOL = 'btc';
 // Slip 0014 - https://github.com/satoshilabs/slips/blob/master/slip-0014.md#bitcoin-segwit--p2wpkh--bip84
 const BTC_HARD_CODED_XPUB =
-    'xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy';
+    'zpub6rjNNddoAVvuYaD6WPdxiqFEToQHgrERjWMg7kM9gGGk6rhPMWNEmL5X745FGqBq8Wp136LfA3A7UjRGEYdJrf8dUfshzNrb5rvaryNfVJf';
```
Comment (Nodonisko) [inline suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx]: Why do we change this xpub in nearly every PR? :D

File: suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx [hunk 2]
```diff
@@ -65,7 +65,10 @@ const submitButtonStyle = prepareNativeStyle(utils => ({
...
+
+const TESTNET_HARD_CODED_XPUB =
```
Comment (Nodonisko) [inline suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx]: Can you please make this some kind of object `Record<NetworkSymbol, Xpub>` then later you can do `devXpubs[selectedNetworkSymbol]`

File: suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx]: This Xpub is from @sime and actually has some some btc so it will be good for testing. It's some company testing xpub apparently.

Comment (sime) [reply suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx]: I don't think this needs to be in the repo, but if it's convenient, go for it.

File: suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx]: [8ea4764](https://github.com/trezor/trezor-suite/pull/6593/commits/8ea47644d7cd6de42e64047c41dce684fe2fc18d)

**Review by Nodonisko — APPROVED** [review]
