### PR TITLE
fix(suite-native): use 16px padding as default for screen components

### LINKED ISSUE #15553: Set 16px padding as default for Screen components
Currently, 8px are used as default but it is overridden on many screens already.

All `Screen*` components shall be revised and updated accordingly.

### PR DESCRIPTION
**Pull request by yanascz**
- 16px padding set as default
- some screens adapted accordingly

## Related Issue

Resolve #15553

## Screenshots:

image
image
image

### CODE REVIEW

File: suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx [hunk 1]
```diff
@@ -39,12 +39,13 @@ export const HomeScreen = () => {
 
     return (
         <Screen
-            screenHeader={<DeviceManagerScreenHeader hasBottomPadding />}
+            screenHeader={<DeviceManagerScreenHeader />}
             refreshControl={refreshControl}
             customHorizontalPadding={0}
+            customTopPadding={0}
```
Comment (PeKne) [inline suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx]: One question... Why is the customTopPadding needed everywhere? Could not it be set as a default value of the `Screen` component? Like that we would not have to pass it everywhere manually in so many places.

File: suite-native/module-send/src/components/SendScreenSubHeader.tsx [hunk 2]
```diff
@@ -24,10 +23,6 @@ type AccountBalanceScreenHeaderProps = {
     tokenContract?: TokenAddress;
 };
 
-export const SendScreenSubHeader = (props: ScreenSubHeaderProps) => (
-    <ScreenSubHeader {...props} customHorizontalPadding={nativeSpacings.sp16} />
-);
-
 export const AccountBalanceScreenHeader = ({
```
Comment (PeKne) [inline suite-native/module-send/src/components/SendScreenSubHeader.tsx:26]: please rename this file so it does reflect the component name `AccountBalanceScreenHeader.tsx`. I should have done it like that originally.

**Review by PeKne — APPROVED** [review]
LGTM

File: suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx (hunk 1 above)
Comment (yanascz) [reply suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx]: Because the default is 16px, not zero. But there are some use cases where zero is needed. I'd reduce it to a boolean flag in the future if possible, we'll be looking into it again with @shenkys.

File: suite-native/module-send/src/components/SendScreenSubHeader.tsx (hunk 2 above)
Comment (yanascz) [reply suite-native/module-send/src/components/SendScreenSubHeader.tsx:26]: Fixed.

**Review by Nodonisko — APPROVED** [review]
I have some hardcoded sp8 in FirmwareUpgradeInProgress screen, we should not forget to fix that one too

File: suite-native/navigation/src/components/Screen.tsx [hunk 3]
```diff
@@ -115,19 +115,22 @@ export const Screen = ({
...
 }: ScreenProps) => {
     const {
         applyStyle,
-        utils: { colors, isDarkColor },
+        utils: { colors, isDarkColor, spacings },
     } = useNativeStyles();
 
-    const hasPaddingBottom = !useContext(BottomTabBarHeightContext) && hasBottomInset;
     const insets = useOfflineBannerAwareSafeAreaInsets();
+    const customTopPadding = noTopPadding ? 0 : spacings.sp16;
```
Comment (PeKne) [inline suite-native/navigation/src/components/Screen.tsx]: super nit: I would maybe rename these values to not include `custom...` because it is not customizable anymore.

But feel free to resolve this.

**Review by PeKne — APPROVED** [review]
Both the app and code looks significantly better now. Thanks for fixing this 🙏

File: suite-native/navigation/src/components/Screen.tsx (hunk 3 above)
Comment (yanascz) [reply suite-native/navigation/src/components/Screen.tsx]: Fixed.
