### PR TITLE
fix(suite): fixed unintentional approval refresh

### LINKED ISSUE #19768: Trading - don't refresh approval after tx has been processed
## Description

After approve/revoke transaction has been processed, the approval timer refreshes the state once again after a few seconds. This can lead to a side effect in the receive address step that it automatically redirects the user to the send transaction step.

## Screenshots

After a few seconds after tx has been processed, it refreshes.

https://github.com/user-attachments/assets/0be68ece-1604-4aae-8fb0-cc3c53c393d4

If we go to swap before it refreshes, the step changes from receive address to send transaction.

https://github.com/user-attachments/assets/8028d688-a0a2-4537-a3d0-5a510ad1c1c6

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

After approve/revoke transaction has been processed, the approval is refreshed instantly and does not cause unintentional delayed refresh which caused issues in receive address step.

## Related Issue

Resolve #19768 

## Screenshots:

https://github.com/user-attachments/assets/a0b1ab67-18a6-435f-9c58-2800aa821ad8

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/approval-refresh&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/approval-refresh&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/approval-refresh&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts [hunk 1]
```diff
@@ -543,6 +543,8 @@ export const useTradingExchangeForm = ({
 
     const watchTradeApproval = useCallback(
         async (refreshCount: number) => {
+            await dispatch(fetchAndUpdateAccountThunk({ accountKey: account.key }));
+
```
Comment (TomasBoda) [inline packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts:547]: Moved this `dispatch` to the top of `watchTradeApproval` and removed it from `watchTradeApprovalThunk`, which causes instant refresh of approval instead of a delayed one. This ensures that the approval is freshly fetched on status change as well as there is no delayed fetch after the transaction has been approved/revoked.

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ApproveModal.tsx [hunk 2]
```diff
@@ -81,8 +75,9 @@ export const ApproveModal = ({
     const { exchange, dexTx } = selectedQuote;
     if (!exchange || !dexTx) return null;
 
-    const providerName =
-        exchangeInfo?.providerInfos[exchange]?.companyName || selectedQuote.exchange;
+    const quoteExchange = preselectedQuote?.exchange ?? exchange;
+
+    const providerName = exchangeInfo?.providerInfos[quoteExchange]?.companyName || quoteExchange;
```
Comment (TomasBoda) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ApproveModal.tsx:80]: This has nothing to do with this issue, but it fixes a bug that when the user selects a different offer from `Select all offers`, the correct exchange name is displayed in the approval modal.

**Review by tomasklim — APPROVED** [review]

**Review by adderpositive — COMMENTED** [review]
Good!
