### PR TITLE
native send form can pre-fill invalid feePerUnit decimals

### LINKED ISSUE #20734: Its possible to have 3 decimals in fee when only 2 is allowed
**Describe the bug**
Sometimes fee can be automatically set to 3 decimals instead of 2 and user can't proceed with sending the transactions.

**How to reproduce**

Don't have any 100% steps unfortunately.

**Screenshots**

https://github.com/user-attachments/assets/794c10e5-a108-4e4b-ba56-6c41b3caaf78

### PR DESCRIPTION
**Pull request by vytick**
We didn't previously make sure we pre-fill fee data with correct max amount of decimals than what we later validate. It caused issues at least with Litecoin, where we pre-filed 3 decimals, but fee form validation rejected this because 2 decimals were expected. Unless user set custom fee with less decimals, he then wasn't allowed to send LTC

This fix introduces sanitising for the form before we insert pre-filed data. 

https://github.com/user-attachments/assets/0f355802-a47e-4a72-b8b5-6d8de28e9bfe

Resolve #20734

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/send-fees-form-decimal-validation&lookback=7)

### CODE REVIEW

File: suite-native/module-send/src/utils.ts [hunk 1]
```diff
@@ -40,3 +42,65 @@ export const constructFormDraft = ({
...
+        default:
+            return null;
+    }
+};
+
+const getValueAsString = (value: string | BigNumber) =>
+    typeof value === 'string' ? value : value.toString();
+
+const getValueAsBigNumber = (value: string | BigNumber) =>
+    typeof typeof value === 'string' ? new BigNumber(value) : (value as BigNumber);
```
Comment (PeKne) [inline suite-native/module-send/src/utils.ts]: duplicated typeof

Comment (PeKne) [reply suite-native/module-send/src/utils.ts]: Also why is the `as BigNumber` needed? could not we just call BigNumber(value) and remove this util function completely?

File: suite-native/module-send/src/utils.ts [hunk 2]
```diff
@@ -40,3 +42,65 @@ export const constructFormDraft = ({
 
 export const isSameUtxo = (utxo1: Utxo, utxo2: Utxo): boolean =>
     utxo1.txid === utxo2.txid && utxo1.vout === utxo2.vout;
+
+export const getFeeDecimals = ({ symbol }: { symbol: NetworkSymbol }) => {
+    const network = getNetwork(symbol);
+
+    switch (network.networkType) {
+        case 'ethereum': {
+            return hasNetworkSettlementLayer(symbol) ? 4 : 2;
```
Comment (PeKne) [inline suite-native/module-send/src/utils.ts]: there was `9` originally. Is it intentional change?

File: suite-native/module-send/src/sendFeesFormSchema.ts [hunk 3]
```diff
@@ -30,17 +31,19 @@ export const sendFeesFormValidationSchema = yup.object({
...
 
-                let maxDecimals = 0;
-                if (networkType === 'bitcoin') {
-                    maxDecimals = 2;
-                } else if (networkType === 'ethereum') {
-                    maxDecimals = 9;
-                }
+                const maxDecimals = getFeeDecimals({ symbol });
+
+                if (!maxDecimals) return true;
```
Comment (PeKne) [inline suite-native/module-send/src/sendFeesFormSchema.ts]: nit: this if statement should be never true, few lines above there is a check that ensures that

``` 
if (networkType !== 'bitcoin' && networkType !== 'ethereum') return true;

```

Feel free to resolve this comment without further change.

File: suite-native/module-send/src/utils.ts [hunk 4]
```diff
@@ -40,3 +42,65 @@ export const constructFormDraft = ({
...
+            const multiplier = Math.pow(10, decimals);
+            const value = Math.ceil(Number(feeRate) * multiplier) / multiplier;
+
+            return value.toFixed(decimals);
+        }
+
+        case 'bitcoin': {
+            const feeBn = getValueAsBigNumber(feeRate);
+
+            return feeBn.toFixed(decimals);
```
Comment (PeKne) [inline suite-native/module-send/src/utils.ts]:
```suggestion
            return String(feeRate)
```
should be enough.

File: suite-native/module-send/src/utils.ts [hunk 5]
```diff
@@ -40,3 +42,65 @@ export const constructFormDraft = ({
...
+            return 2;
+        }
+
+        default:
+            return null;
+    }
+};
+
+const getValueAsString = (value: string | BigNumber) =>
+    typeof value === 'string' ? value : value.toString();
```
Comment (PeKne) [inline suite-native/module-send/src/utils.ts]: this util is IMO unnecessary. String(value) should do the trick.

**Review by PeKne — APPROVED** [review]
Minor code style issues.

File: suite-native/module-send/src/utils.ts (hunk 2 above)
Comment (vytick) [reply suite-native/module-send/src/utils.ts]: This is what they have in desktop and I took from [here](https://github.com/trezor/trezor-suite/tree/develop/packages/product-components/src/components/FeeRate/FeeRate.tsx#L18)

File: suite-native/module-send/src/utils.ts (hunk 4 above)
Comment (vytick) [reply suite-native/module-send/src/utils.ts]: String() does  not trim decimals

File: suite-native/module-send/src/utils.ts (hunk 2 above)
Comment (vytick) [reply suite-native/module-send/src/utils.ts]: Looking into it once more and 2 and 4 digits are used for normal fees, not for custom fees. Reverting back to 9. Good call 👍

Comment (vytick) [reply suite-native/module-send/src/utils.ts]: updated in 729c7b60bb

File: suite-native/module-send/src/sendFeesFormSchema.ts (hunk 3 above)
Comment (vytick) [reply suite-native/module-send/src/sendFeesFormSchema.ts]: changed in 729c7b60bb

File: suite-native/module-send/src/utils.ts (hunk 4 above)
Comment (vytick) [reply suite-native/module-send/src/utils.ts]: 729c7b60bb

File: suite-native/module-send/src/utils.ts (hunk 5 above)
Comment (vytick) [reply suite-native/module-send/src/utils.ts]: simplified in 729c7b60bb

File: suite-native/module-send/src/utils.ts (hunk 1 above)
Comment (vytick) [reply suite-native/module-send/src/utils.ts]: simplified in 729c7b60bb

**Review by PeKne — APPROVED** [review]

**Comment by STew790** [comment]
**QA OK**
I am not able to reproduce this.

**Info**
25.8.1 (⁠[5be07bb](https://github.com/trezor/trezor-suite/commit/5be07bba057d4088e46bde3dc773019537ce3461))
