### PR TITLE
fix(suite): fix graph tooltip z-index

### LINKED ISSUE #4227: Graph tooltip
Bug: Tooltip folds beneath the header area. 

Screen Shot 2021-09-03 at 15 36 23

### PR DESCRIPTION
**Pull request by dimasivan**
fix #4227

### CODE REVIEW

File: packages/suite/src/components/suite/TransactionsGraph/index.tsx [hunk 1]
```diff
@@ -142,6 +142,7 @@ const TransactionsGraph = React.memo((props: Props) => {
                             />
                             <Tooltip
                                 position={{ y: 0, x: 0 }}
+                                wrapperStyle={{ 'z-index': '3' }}
```
Comment (tomasklim) [inline packages/suite/src/components/suite/TransactionsGraph/index.tsx:145]: Probably too low

https://user-images.githubusercontent.com/33235762/133738599-9ab2c874-85d4-499e-910f-03305ae8eafd.mov

**Review by tomasklim — DISMISSED** [review]

File: packages/suite/src/components/suite/TransactionsGraph/index.tsx (hunk 1 above)
Comment (dimasivan) [reply packages/suite/src/components/suite/TransactionsGraph/index.tsx:145]: > Probably too low
> Screen.Recording.2021-09-17.at.8.55.07.mov

@tomasklim imo its ok that sticky header covers another element on page as its navigation has higher priority? maybe lets discuss it with UI team to be sure?

Comment (matejkriz) [reply packages/suite/src/components/suite/TransactionsGraph/index.tsx:145]: https://github.com/trezor/trezor-suite/issues/4227#issuecomment-933321948

**Review by matejkriz — APPROVED** [review]
