### PR TITLE
fix(suite-native): prevent biometrics throttling

### LINKED ISSUE #11380: Biometrics not working
Biometrics seems to be broken on latest build. 

https://github.com/trezor/trezor-suite/assets/36101761/6de80cd8-fd6d-47f7-bd62-933f7a4c27cb

### PR DESCRIPTION
**Pull request by vytick**
The app currently is throttled by biometrics authorisation requests. This PR prevents it.

Resolve https://github.com/trezor/trezor-suite/issues/11380

### CODE REVIEW

File: suite-native/biometrics/src/useBiometrics.tsx [hunk 1]
```diff
@@ -79,7 +77,9 @@ export const useBiometrics = () => {
         if (!isBiometricsAuthenticationCanceled) {
             handleAuthentication();
         }
-    }, [handleAuthentication, isBiometricsAuthenticationCanceled]);
+        // only run on change of isBiometricsAuthenticationCanceled
```
Comment (matejkriz) [inline suite-native/biometrics/src/useBiometrics.tsx]: Why? Wouldn't that call handleAuthentication with wrong params memoized?

File: suite-native/biometrics/src/isBiometricsFeatureAvailable.ts [hunk 2]
```diff
@@ -3,5 +3,5 @@ import { getEnrolledLevelAsync, SecurityLevel } from 'expo-local-authentication'
 export const getIsBiometricsFeatureAvailable = async () => {
     const enrolledLevelAsync = await getEnrolledLevelAsync();
 
-    return enrolledLevelAsync !== SecurityLevel.NONE;
+    return enrolledLevelAsync === SecurityLevel.BIOMETRIC;
```
Comment (juriczech) [inline suite-native/biometrics/src/isBiometricsFeatureAvailable.ts]: Why is this change necessary? I thought the issue was caused by `useEffect` in the hook?

Comment (juriczech) [reply suite-native/biometrics/src/isBiometricsFeatureAvailable.ts]: I guess it won't work for touch id with this change, have you tested that?

Comment (vytick) [reply suite-native/biometrics/src/isBiometricsFeatureAvailable.ts]: I've simplified how things work once more and reverted this part.
17d04cf14b

File: suite-native/biometrics/src/useBiometrics.tsx (hunk 1 above)
Comment (vytick) [reply suite-native/biometrics/src/useBiometrics.tsx]: I've simplified how things work once more and deleted this part.
https://github.com/trezor/trezor-suite/commit/17d04cf14b6d2df4d0852553892b3736b442e4c6

File: suite-native/biometrics/src/useBiometrics.tsx [hunk 3]
```diff
@@ -122,18 +114,20 @@ export const useBiometrics = () => {
...
-        const auth = async () => {
-            await handleAuthentication();
-        };
-
         // Ask for authentication only if the app is in active opened state.
-        if (appStateVisible === 'active') auth();
+        if (appStateVisible === 'active') handleAuthentication();
 
         // Only run once on app start from killed state
         // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (juriczech) [inline suite-native/biometrics/src/useBiometrics.tsx]: I believe this is not necessary anymore. Can we remove it? `handleAuthentication` is properly memoized so it could be added to the dependency list here and it won't affect rerenders, right?

Comment (vytick) [reply suite-native/biometrics/src/useBiometrics.tsx]: I’ll test and remove if true 👍

Comment (vytick) [reply suite-native/biometrics/src/useBiometrics.tsx]: 236f4747bc

**Review by juriczech — APPROVED** [review]

**Review by matejkriz — APPROVED** [review]
