### PR TITLE
fix(suite): fee display and calculation in day headers

### LINKED ISSUE #7907: The fee of transaction is calculated in day header, regardless of ownership of the transaction
**Describe the bug**
Not initiated transactions' fee is counted in day header

**Info:**
-   Suite Version: 22.2.0

**How to reproduce**
1. ETH acc
1. Phishing tx
1. Check day header

**Expected behavior**
I spent 0 ETH, so it should not be counted

**Screenshot**
Screenshot 2023-03-22 at 18 12 09

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- at least one vin should be `vin.isOwn` then tx is signed by me
- shows token/internal transfers in case of `tx.type` is `self`
- show fee if zero, extremely rare case, looks like a bug in Suite when sent tx has no fee

## Related Issue

closes #7907

## Screenshots:
not mine tx has no fee
Screenshot 2023-04-27 at 16 37 29

mine tx with zero fee has fee
Screenshot 2023-05-02 at 15 15 51

### CODE REVIEW

File: packages/suite/src/components/wallet/TransactionItem/index.tsx [hunk 1]
```diff
@@ -124,20 +124,15 @@ const TransactionItem = React.memo(
...
             | { type: 'internal'; payload: (typeof internalTransfers)[number] }
             | { type: 'target'; payload: WalletAccountTransaction['targets'][number] }
-        )[] =
-            transaction.type === 'self'
-                ? [...targets.map(t => ({ type: 'target' as const, payload: t }))]
-                : [
-                      ...targets.map(t => ({ type: 'target' as const, payload: t })),
-                      ...internalTransfers.map(t => ({ type: 'internal' as const, payload: t })),
-                      ...tokens.map(t => ({ type: 'token' as const, payload: t })),
-                  ];
```
Comment (komret) [inline packages/suite/src/components/wallet/TransactionItem/index.tsx:140]: I don't understand this change. How is it related?

Comment (tomasklim) [reply packages/suite/src/components/wallet/TransactionItem/index.tsx:140]: it's not, but it's some forgotten nonsense, which can cause bugs

**Review by matejkriz — APPROVED** [review]
LGTM
