### PR TITLE
fix(suite): Change BackupStatus to inProgress

### LINKED ISSUE #14655: Changing device during onboarding does not reset backup state
**Describe the bug**
Onboarding state does not reset properly when changing device during unfinished onboarding,

**Info:**

 - Suite version: desktop 24.10.0 (ac53d354cc8538700fb9e93de2dc7f6b6c6a37f4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteLocal/24.10.0 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**How to reproduce**

1. Connect an empty device
1. Create new wallet
2. Create backup
3. Verify backup
1. Do not continue with onboarding, disconnect device
5. Connect new device
1. Create new wallet
2. Start creating backup...
3. ...but onboarding indicates that backup is already finished :x:
4. And you can continue without backup, in onboarding it seems backup was done
5. but after onboarding it indicates backup has not been done :x:

**Expected behavior**
Onboarding state should be scoped per device, or fully reset

### PR DESCRIPTION
**Pull request by 5K1PY**
Now we construct BackupState also from device features.

## Description

Changed BackupState to contain `inProgress` instead of `backupStatus`. Then we construct `backupStatus` from BackupState and DeviceState:
- If BackupState has error set, status is `error`
- If `inProgress`, status is `in-progress`
- If `backup_availability` from DeviceState is `Required`, then we don't have backup => `initial`
- `finished` otherwise

## Related Issue

Resolve #14655

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/backup-state&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/backup-state&lookback=7)

### CODE REVIEW

File: packages/suite/src/reducers/backup/backupReducer.ts [hunk 1]
```diff
@@ -52,5 +54,12 @@ const backup = (state: BackupState = initialState, action: Action) =>
     });
 
 export const selectBackup = (state: BackupRootState) => state.backup;
+export const selectBackupStatus = (state: BackupRootState & DeviceRootState): BackupStatus => {
+    if (state.backup.error !== undefined) return 'error';
+    else if (state.backup.inProgress) return 'in-progress';
+    else if (state.device.selectedDevice?.features?.backup_availability === 'Required')
+        return 'initial';
+    else return 'finished';
```
Comment (peter-sanderson) [inline packages/suite/src/reducers/backup/backupReducer.ts]: nit: `else` not needed anywhere as it always returns.

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/reducers/backup/backupReducer.ts [hunk 2]
```diff
@@ -52,5 +54,12 @@ const backup = (state: BackupState = initialState, action: Action) =>
     });
 
 export const selectBackup = (state: BackupRootState) => state.backup;
+export const selectBackupStatus = (state: BackupRootState & DeviceRootState): BackupStatus => {
+    if (state.backup.error !== undefined) return 'error';
```
Comment (peter-sanderson) [inline packages/suite/src/reducers/backup/backupReducer.ts]: `if(state.device.selectedDevice?.features?.backup_availability === "Done") return "finished"`

Comment (peter-sanderson) [reply packages/suite/src/reducers/backup/backupReducer.ts]: as first line

somhowe restructure the conditions to make state from device the most important

**Review by peter-sanderson — APPROVED** [review]
