### PR TITLE
Mobile Trade: Allow user to reinitialize sell flow from preview

### LINKED ISSUE #23600: [Mobile] Sell - User is stuck in limbo after exiting early from partner site in mobile sell flow
**Describe the bug**
If a user visits a partner site via mobile sell and exits the process prematurely, they can become stuck (in a limbo state). The user cannot proceed forward or return to the partner flow, and is unable to get back to the site or resume the selling process.

**Info:**
Build: https://github.com/trezor/trezor-suite/commit/5acc56850f2987662780db4f7322b5d491cecca7
Android 15

**How to reproduce**

1.  Launch Mobile Suite and start a sell using a partner site
2. Exit the partner flow before successfully completing the process
3. Try to continue or restart the process
4.  Observe that you are stuck and cannot return to the partner or proceed with the sell

**Expected behavior**
There should always be a way for the user to resume the partner flow after leaving it early. Users should not become stuck and should be able to continue, retry, or return.

**Screenshots**

https://github.com/user-attachments/assets/2135d597-0d84-4d5f-9e6f-98ea8754aa1c

# Solution
- if user bails provider webview manually, show him this waiting state during which we will wait for provider sends us confirmation and address, in case the user completed all steps on their site before he closed the site manually
- [Figma with whole flow and all states](https://www.figma.com/design/OIXEah1s7HaSIsI8A8ws9T/-Mob--Trade?node-id=9607-17028&t=EFLgpEbqCUTCilRF-4)

Image

Image

### PR DESCRIPTION
**Pull request by jbazant**
## Description

Display continue button for quote in state `submitted`.

## Related Issue

Resolve #23600

## Screenshots:

Simulator Screenshot - iPhone 16e - 2025-12-08 at 16 58 32

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=23600-mobile-sell-user-is-stuck-after-exiting-early-from-partner-site&lookback=7)

### CODE REVIEW

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/module-trading/src/components/sell/SellPreview/SellPreviewSubmittedNextStepButton.tsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+export type SellPreviewSubmittedNextStepButtonProps = {
+    onPress: () => Promise<void>;
+};
+
+export const SellPreviewSubmittedNextStepButton = ({
+    onPress,
+}: SellPreviewSubmittedNextStepButtonProps) => {
+    const selectedQuote = useSelector(selectTradingSellSelectedQuote);
+
+    if (selectedQuote?.status !== 'SUBMITTED') {
```
Comment (vytick) [inline suite-native/module-trading/src/components/sell/SellPreview/SellPreviewSubmittedNextStepButton.tsx]: I would check the state in `TradingSellPreviewScreen`, where we already have `selectedQuote` and also a `trade` in case of selectedQuote missing - this probably still can happen sometimes (hard to be sure in this). 

If you do that, maybe this component is not needed and `AsyncButton` can be used in `TradingSellPreviewScreen`


wdyt?

**Review by vytick — APPROVED** [review]
👌
