### PR TITLE
fix(suite-native): fix Android Text's spacing

### LINKED ISSUE #19320: Text does not match design
**Describe the bug**

The font styles in the app do not fully match the design. Specifically, the `letter spacing `and `letter height` appear different from design. 

Investigate the root of the problem and, if possible, fix it.

**Info:**

- Mobile Suite Version: version/commit
- OS: iOS, Android

**Expected behavior**
Fonts should match the design

**Screenshots**
@shenkys , please attach screenshots of the specific occurrences, thank you.

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

- fix spacing issues when fontScale is set to small 
- screenshot copies serve solely as comparison, the app content remain unchaged

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19320

## Before

b2
b

## After

lab
la

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/text&lookback=7)

### CODE REVIEW

File: suite-native/app/e2e/pageObjects/tradingBuyActions.ts [hunk 1]
```diff
@@ -131,8 +131,10 @@ class TradingBuyActions {
 
     async confirmBuyForm() {
         await element(by.id('@trading/buy/continue-button')).tap();
-        await waitForElementByIdToBeVisible('@trading/buy/confirm-button');
-        await element(by.id('@trading/buy/confirm-button')).tap();
+        const confirmButton = element(by.id('@trading/buy/confirm-button'));
+        const bottomSheetScrollView = element(by.id('@bottom-sheet/scroll-view'));
+        await bottomSheetScrollView.scroll(300, 'down');
```
Comment (juriczech) [inline suite-native/app/e2e/pageObjects/tradingBuyActions.ts]: Shouldn't you be able to pass the scrollView id and use the `scrollUntilVisible`?

Comment (BrantalikP) [reply suite-native/app/e2e/pageObjects/tradingBuyActions.ts]: for some reason, that did not work for me... :/

Comment (juriczech) [reply suite-native/app/e2e/pageObjects/tradingBuyActions.ts]: Aaaagh, this `scrollUntilVisible` stuff is starting to hurt us a little bit I feel. How is this test related to changing text spacings anyway?

Comment (juriczech) [reply suite-native/app/e2e/pageObjects/tradingBuyActions.ts]: I don't like that the value is hardcoded and feel like can be broken on different devices. Like if we switch to tablet for testing or something like that, this would not work. 

Apart from that this PR is legitimate so if you can't find working solution, I guess we can go with it, even if it's suboptimal...

Comment (BrantalikP) [reply suite-native/app/e2e/pageObjects/tradingBuyActions.ts]: > Aaaagh, this `scrollUntilVisible` stuff is starting to hurt us a little bit I feel. How is this test related to changing text spacings anyway?

Due to the spacing, the text naturally takes up more space, which slightly pushes the button off the screen. That’s why scrolling is required..  I just need to scroll to the bottom a bit 😬. Maybe there’s a better solution. Thanks!

Comment (BrantalikP) [reply suite-native/app/e2e/pageObjects/tradingBuyActions.ts]: https://github.com/trezor/trezor-suite/pull/20152/commits/ece41f31fcf4c7b0027d1980744e27cbef8ad782

**Review by juriczech — APPROVED** [review]
