### PR TITLE
Fix sign verfy and Add Elevation Provider

### LINKED ISSUE #10140: Add Elevation Context
### Issue

Some color tokens have different _elevation variants_. What does that mean? It means that a certain color token has different values when it's displayed on different elevations, aka elevation values of color tokens of a background. Those exist to make sure that the contrast ratio is the best across different surfaces.

Currently we have hardcoded elevation values, e.g. `Button` backgrounds always have elevation 0. It leads to buttons being incorrectly displayed on surfaces with elevation 1 – white surfaces, e.g. `Card` and `Modal`. There is no background visible on the screenshot:

image

With the correct elevation value it looks like this:

image

### Proposal

Creat `ElevationContext` and a `useElevation` hook to read that context. The hook will be aware of the elevation value of a closest parent and interpolate it into the color token or use a default one — `0`. 

Container components should define their elevation context, like `Modal` and `Card`, and components which are displayed and using an elevatoin variant should use the `useElevation` hook, like `Button` or `Input`.

### temporary solution

Use `onElevation1` as the default, since it does not lead to components beling the same color as containers with `elevation1` as shown on the first screenshot.

### LINKED ISSUE #10616: Review: sign and verify page issues
Found some bugs in verify page that are related to the new redesign changes.

1. Alignment is not center if there is error message
7C07644C-0684-4984-951E-DC4596DA4D18
2. Issue with the transition from transparent to white (or transparent to black to white when dark mode is enabled). 
555E51FA-9950-411A-868B-14506638BE3C
3. Message input has the same background and the block it is in
F6F9FF54-82CB-43F5-B5A2-5D74EEA8A100

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

Addresses some style issues in sign and verify form

## Related Issue

- Resolve https://github.com/trezor/trezor-suite/issues/10616
- Resolve https://github.com/trezor/trezor-suite/issues/10140
- Resolve https://github.com/trezor/trezor-suite/issues/10697

### CODE REVIEW

File: packages/components/src/components/Card/Card.tsx [hunk 1]
```diff
@@ -1,16 +1,24 @@
...
     flex-direction: column;
     padding: ${({ $paddingSize }) => $paddingSize}px;
-    background: ${({ theme }) => theme.backgroundSurfaceElevation1};
+    background: ${({ theme, $elevation }) => theme[mapElevationToBackground[$elevation]]};
     border-radius: ${borders.radii.md};
-    box-shadow: ${({ $elevation, theme }) =>
-        $elevation && theme[`boxShadowElevation${$elevation === 3 ? 3 : 1}`]};
+    box-shadow: ${({ theme, $elevation }) => {
+        if ($elevation === 1) {
+            const boxShadow = mapElevationToBoxShadow[$elevation];
```
Comment (jvaclavik) [inline packages/components/src/components/Card/Card.tsx]: So we have box shadow only on elevation 1? Is it temporary solution or not?

File: packages/components/src/components/Card/Card.tsx [hunk 2]
```diff
@@ -27,28 +35,37 @@ const getPaddingSize = (paddingType?: PaddingType) => {
...
-    elevation?: Elevation;
     paddingType?: PaddingType;
     onMouseEnter?: () => void;
     onMouseLeave?: () => void;
+    onClick?: () => void;
 
     children?: ReactNode;
     className?: string;
+
+    resetElevation?: Elevation;
```
Comment (jvaclavik) [inline packages/components/src/components/Card/Card.tsx]: For me this naming is a bit confusing - `resetElevation` sounds like some callback function to reset elevation. 
If I understand it correctly, it's more like forced elevation. Btw what is the reason for it?

File: packages/components/src/components/skeletons/types.ts [hunk 3]
```diff
@@ -1,3 +1,6 @@
+/**
+ * @deprecated use ElevationContext
```
Comment (jvaclavik) [inline packages/components/src/components/skeletons/types.ts]: Don't you want to also change it? Otherwise we will need prepare PR for it :D

File: packages/suite/src/components/suite/AppNavigationPanel.tsx [hunk 4]
```diff
@@ -121,7 +121,7 @@ export const AppNavigationPanel = ({
                 </Content>
             </Wrapper>
             {isValidElement(navigation) && cloneElement(navigation, { inView })}
-            <Delimeter />
+            <Delimiter />
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/AppNavigationPanel.tsx:124]: TIL 😀

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx [hunk 5]
```diff
@@ -11,55 +11,44 @@ import {
...
 const MarginContainer = styled.div`
     padding: ${spacingsPx.md} ${spacingsPx.sm} ${spacingsPx.sm} ${spacingsPx.md};
     flex: 1;
 `;
 
-const Card = styled.div`
-    border-radius: ${borders.radii.md};
-    box-shadow: ${({ theme }) => theme.boxShadowElevation1};
-
+const StyledCard = styled(Card)`
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx:24]: There are some design inconsitencies:

**before:**
image


**after:**
image

File: packages/components/src/components/modals/Modal/Modal.tsx [hunk 6]
```diff
@@ -231,8 +233,9 @@ const Modal = ({
     const areStepsShown =
         totalProgressBarSteps !== undefined && currentProgressBarStep !== undefined;
 
+    // Model has intentionally always Elevation = 1 (it resets the elevation)
     return (
-        <>
+        <ElevationContext baseElevation={1}>
```
Comment (jvaclavik) [inline packages/components/src/components/modals/Modal/Modal.tsx:238]: just quick note - probably not related to this PR: 

background + shadow on darkmode is weird and hardly visible

image


lightmode is fine:
image

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx [hunk 7]
```diff
@@ -11,55 +11,44 @@ import {
...
+import { Card, H2, Icon, SkeletonRectangle, variables } from '@trezor/components';
 import { useDispatch } from 'react-redux';
 import { useAccountSearch, useLoadingSkeleton } from 'src/hooks/suite';
 import { goto } from 'src/actions/suite/routerActions';
 import { ArrowIcon, AssetInfo, AssetInfoSkeleton } from './AssetInfo';
 import { AssetFiatBalance } from '@suite-common/assets';
 import { FiatHeader } from '../../FiatHeader';
 
-const BuyContainer = styled.div`
+const BuyContainerCard = styled(Card)`
```
Comment (jvaclavik) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx]: I think it shouldn't be a `Card`. Just follow elevation background, but margins/paddings/border-radiuses are different.

**Review by jvaclavik — COMMENTED** [review]
Good job! I really like the idea of elevation context. It's really simple idea and it works.

Added few comments

File: packages/components/src/components/Card/Card.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx]: This is something @dahaca wanted and there are some rules around it. I think its just custom for the card.

File: packages/components/src/components/Card/Card.tsx (hunk 2 above)
Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx]: renamed

Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx]: the reason for this is the ability to enforce different elevation

BackupSeedCard is one example

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx (hunk 5 above)
Comment (jvaclavik) [reply packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx:24]: Diffs: 

Screenshot 2024-01-17 at 13 54 33

Comment (peter-sanderson) [reply packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx:24]: fixed, thx

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx (hunk 7 above)
Comment (peter-sanderson) [reply packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx]: fixed on call

File: packages/components/src/components/modals/Modal/Modal.tsx (hunk 6 above)
Comment (peter-sanderson) [reply packages/components/src/components/modals/Modal/Modal.tsx:238]: leo will talk about this with the designer

File: packages/components/src/components/skeletons/types.ts (hunk 3 above)
Comment (peter-sanderson) [reply packages/components/src/components/skeletons/types.ts]: done

**Review by jvaclavik — APPROVED** [review]
💪

File: packages/components/src/components/Card/Card.tsx [hunk 8]
```diff
@@ -1,16 +1,24 @@
...
-        $elevation && theme[`boxShadowElevation${$elevation === 3 ? 3 : 1}`]};
+    box-shadow: ${({ theme, $elevation }) => {
+        if ($elevation === 1) {
+            const boxShadow = mapElevationToBoxShadow[$elevation];
 
+            return boxShadow !== undefined ? theme[boxShadow] : undefined;
+        }
+
+        return undefined;
+    }};
```
Comment (dahaca) [inline packages/components/src/components/Card/Card.tsx]: Only cards on elevation 1 should have a shadow. A card inside of a modal or a card should be shadow-less.

i have already asked david to rename the shadow tokens in the DS and I believe we can do in ourselves too. 

`elevation1` => `shadowBase`
`elevation3` => `shadowElevated`

I believe that would resolve a lot of confusion!

File: packages/components/src/components/Card/Card.tsx [hunk 9]
```diff
@@ -27,28 +35,37 @@ const getPaddingSize = (paddingType?: PaddingType) => {
...
-        >
-            {children}
-        </Wrapper>
-    ),
+    ({ paddingType = 'normal', children, forceElevation, ...rest }, ref) => {
+        const { elevation } = useElevation();
+
+        const adjustedElevation =
+            // eslint-disable-next-line no-nested-ternary
+            forceElevation !== undefined ? forceElevation : elevation !== null ? elevation : 0;
```
Comment (dahaca) [inline packages/components/src/components/Card/Card.tsx]: I believe this should be handled by the hook? And hook's param would be `forceElevation` as well? Because this logic is not Card's but belongs to the elevation context

File: packages/components/src/components/Dropdown/menuStyle.ts [hunk 10]
```diff
@@ -13,15 +14,19 @@ export const DROPDOWN_MENU = keyframes`
...
     min-width: 140px;
     border-radius: ${borders.radii.md};
-    background: ${({ theme }) => theme.backgroundSurfaceElevation1};
-    box-shadow: ${({ theme }) => theme.boxShadowElevation3};
+    background: ${({ theme, elevation }) => theme[mapElevationToBackground[elevation]]};
+    box-shadow: ${({ theme, elevation }) => {
+        const boxShadow = mapElevationToBoxShadow[elevation];
+
+        return boxShadow !== undefined ? theme[boxShadow] : undefined;
+    }};
```
Comment (dahaca) [inline packages/components/src/components/Dropdown/menuStyle.ts]: box shadow should be fixed to `elevation3` + another reason to rename the shadows.

File: packages/components/src/components/Card/Card.tsx [hunk 11]
```diff
@@ -1,16 +1,24 @@
...
+import { borders, mapElevationToBoxShadow, spacings } from '@trezor/theme';
+import { ElevationContext, useElevation } from '../ElevationContext/ElevationContext';
+import { Elevation, mapElevationToBackground } from '@trezor/theme/src/elevation';
 
 const Wrapper = styled.div<{ $elevation: Elevation; $paddingSize: number }>`
     display: flex;
     flex-direction: column;
     padding: ${({ $paddingSize }) => $paddingSize}px;
-    background: ${({ theme }) => theme.backgroundSurfaceElevation1};
+    background: ${({ theme, $elevation }) => theme[mapElevationToBackground[$elevation]]};
```
Comment (dahaca) [inline packages/components/src/components/Card/Card.tsx:11]: How about creating this pluggable thingy to not repeat the same code?

```
const backgroundElevation = css<{ $elevation: Elevation }>`
    background: ${({ theme, $elevation }) => theme[mapElevationToBackground[$elevation]]};
`;
```

and then do this whenever needed:

```suggestion
    background: ${backgroundElevation};
```

File: packages/components/src/components/form/Select/Select.tsx
Comment (dahaca) [inline packages/components/src/components/form/Select/Select.tsx:1]: waiting for an answer from David regarding the Select and Dropdown elevaiton logic 🫡 Not entirely sure it should be like that but it very well might, I don't hate it actually!

image

File: packages/components/src/components/form/InputStyles.ts [hunk 12]
```diff
@@ -36,14 +37,18 @@ export const getInputStateBorderColor = (state: InputState | undefined, theme: D
...
 
-export const getInputStateBgColor = (state: InputState | undefined, theme: DefaultTheme) => {
+export const getInputStateBgColor = (
+    state: InputState | undefined,
+    theme: DefaultTheme,
+    elevation: Elevation,
+) => {
     switch (state) {
         case 'warning':
             return theme.backgroundAlertYellowSubtleOnElevation1;
```
Comment (dahaca) [inline packages/components/src/components/form/InputStyles.ts:47]: you are waiting for an answer from David regarding those, right?

File: packages/components/src/components/form/InputStyles.ts [hunk 13]
```diff
@@ -53,12 +58,14 @@ export interface BaseInputProps {
     inputState?: InputState;
     disabled?: boolean;
     isWithLabel?: boolean;
+    elevation: Elevation;
 }
 
 export const baseInputStyle = css<BaseInputProps>`
```
Comment (dahaca) [inline packages/components/src/components/form/InputStyles.ts:64]: Please, use the elevation for borders in the `:focus` style as well. Let's use `borderOnElevation0` for elevation 2 for now and `borderOnElevation1` for 3

File: packages/suite/src/components/suite/graph/GraphSkeleton.tsx [hunk 14]
```diff
@@ -67,14 +75,19 @@ export const GraphSkeleton = ({ animate, ...rest }: GraphSkeletonProps) => {
...
-                <SkeletonRectangle height="10px" animate={false} />
-                <SkeletonRectangle height="10px" animate={false} />
-                <SkeletonRectangle height="10px" animate={false} />
-                <SkeletonRectangle height="10px" animate={false} />
+                <SkeletonRectangle height="10px" animate={false} elevation={elevation} />
+                <SkeletonRectangle height="10px" animate={false} elevation={elevation} />
+                <SkeletonRectangle height="10px" animate={false} elevation={elevation} />
+                <SkeletonRectangle height="10px" animate={false} elevation={elevation} />
+                <SkeletonRectangle height="10px" animate={false} elevation={elevation} />
+                <SkeletonRectangle height="10px" animate={false} elevation={elevation} />
```
Comment (dahaca) [inline packages/suite/src/components/suite/graph/GraphSkeleton.tsx]: Using elevation context explicitly would be handy here to not pass the prop 6 times

File: packages/theme/src/colors.ts [hunk 15]
```diff
@@ -6,10 +6,10 @@ export const colorVariants = {
     standard: {
         transparent: '#00000000',
         backgroundSurfaceElevationNegative: '#eeeeeeff',
-        backgroundSurfaceElevation0: '#f6f6f6ff',
-        backgroundSurfaceElevation1: '#ffffffff',
-        backgroundSurfaceElevation2: '#f6f6f6ff',
-        backgroundSurfaceElevation3: '#ffffffff',
+        backgroundSurfaceElevation0: '#f6f6f6ff', // Never use directly, use ElevationContext.
```
Comment (dahaca) [inline packages/theme/src/colors.ts:9]: same goes for all the colors with an elevation postfix, right?

File: packages/theme/src/boxShadows.ts [hunk 16]
```diff
@@ -16,11 +17,11 @@ export const boxShadows = {
...
 
-export type Elevation = 0 | 1 | 3;
-
 export const mapElevationToBoxShadow: Record<Elevation, BoxShadow | undefined> = {
+    '-1': undefined,
     '0': undefined,
     '1': 'boxShadowElevation1',
+    '2': 'boxShadowElevation1', // Todo: ...
     '3': 'boxShadowElevation3',
 };
```
Comment (dahaca) [inline packages/theme/src/boxShadows.ts]: no need, rename the shadows, they exist separately from elevation

File: packages/suite/src/views/wallet/transactions/components/InfoCard.tsx [hunk 17]
```diff
@@ -78,7 +80,7 @@ export const InfoCard = (props: InfoCardProps) => {
         <Wrapper>
             <InfoCardContent>
                 <Title>{props.title}</Title>
-                {props.isLoading && <SkeletonRectangle width="160px" />}
+                {props.isLoading && <SkeletonRectangle width="160px" elevation={elevation} />}
```
Comment (dahaca) [inline packages/suite/src/views/wallet/transactions/components/InfoCard.tsx]: it's already a child of a Card, no?

File: packages/suite/src/views/wallet/transactions/TransactionList/SkeletonTransactionItem.tsx [hunk 18]
```diff
@@ -1,15 +1,19 @@
...
+export const SkeletonTransactionItem = () => {
+    const { elevation } = useElevation();
+
+    return (
+        <SkeletonStack col childMargin="0px 0px 8px 0px">
+            <SkeletonSpread>
+                <SkeletonRectangle width="120px" height="18px" elevation={elevation} />
+                <SkeletonRectangle width="80px" height="18px" elevation={elevation} />
+            </SkeletonSpread>
+            <SkeletonRectangle width="100%" height="70px" animate elevation={elevation} />
```
Comment (dahaca) [inline packages/suite/src/views/wallet/transactions/TransactionList/SkeletonTransactionItem.tsx]: I believe the skeletons should just use the hook?

File: packages/suite/src/views/wallet/sign-verify/index.tsx [hunk 19]
```diff
@@ -109,6 +109,10 @@ const tooltipContent = (
     />
 );
 
+const MultilineRow = styled(Row)`
+    align-items: start;
+`;
+
```
Comment (dahaca) [inline packages/suite/src/views/wallet/sign-verify/index.tsx:116]: i believe it's better to remove the top margin [here](https://github.com/trezor/trezor-suite/blob/642239ca4441c36d60284254e2aff79a1079f398/packages/suite/src/views/wallet/sign-verify/index.tsx#L78), as it's a leftover measure for the previous version of the `SelectBar`

File: packages/suite/src/views/wallet/sign-verify/index.tsx [hunk 20]
```diff
@@ -65,17 +65,17 @@ const StyledSelectBar = styled(SelectBar)`
...
     @media (min-width: ${variables.SCREEN_SIZE.SM}) {
         width: 320px;
-        margin: 0 0 0 20px;
+        margin: 6px 0 0 20px;
     }
 
     @media (min-width: ${variables.SCREEN_SIZE.MD}) and (max-width: ${variables.SCREEN_SIZE.LG}) {
         width: 100%;
-        margin: 12px 0 20px;
+        margin: 6px 0 20px;
```
Comment (dahaca) [inline packages/suite/src/views/wallet/sign-verify/index.tsx]: it looked less crowded with `12px` and the distance between the two inputs above is `12px` too. 

image

File: packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/AssetsView/components/AssetCard.tsx:1]: 🥇

**Review by dahaca — CHANGES_REQUESTED** [review]
Please remove the placeholders as well, it should work with the context now! 🙌 
image

File: packages/suite/src/views/wallet/transactions/TransactionList/SkeletonTransactionItem.tsx (hunk 18 above)
Comment (peter-sanderson) [reply packages/suite/src/views/wallet/transactions/TransactionList/SkeletonTransactionItem.tsx]: `SkeletonRectangle` is a styled `export const SkeletonRectangle = styled.div<SkeletonRectangleProps>` stuff

or is it possible to use hook there?

File: packages/components/src/components/Card/Card.tsx (hunk 8 above)
Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx]: :heavy_check_mark:

File: packages/components/src/components/Card/Card.tsx (hunk 9 above)
Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx]: :heavy_check_mark: good point

File: packages/components/src/components/Dropdown/menuStyle.ts (hunk 10 above)
Comment (peter-sanderson) [reply packages/components/src/components/Dropdown/menuStyle.ts]: :heavy_check_mark:

File: suite-native/atoms/src/Button/Button.tsx [hunk 21]
```diff
@@ -13,8 +13,6 @@ import { useButtonPressAnimatedStyle } from './useButtonPressAnimatedStyle';
 import { TestProps } from '../types';
 import { HStack } from '../Stack';
 
-export type ButtonBackgroundElevation = '0' | '1';
```
Comment (juriczech) [inline suite-native/atoms/src/Button/Button.tsx:16]: 👍

File: packages/components/src/components/Card/Card.tsx (hunk 11 above)
Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx:11]: Thats good idea!

but where to put it? `theme` would be good but it has no dependency on styled components

File: packages/components/src/components/Card/Card.tsx (hunk 9 above)
Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx]: :heavy_check_mark:

File: packages/components/src/components/Dropdown/menuStyle.ts (hunk 10 above)
Comment (peter-sanderson) [reply packages/components/src/components/Dropdown/menuStyle.ts]: :heavy_check_mark:

File: packages/components/src/components/Card/Card.tsx (hunk 11 above)
Comment (peter-sanderson) [reply packages/components/src/components/Card/Card.tsx:11]: agrred to not include this

File: packages/theme/src/colors.ts (hunk 15 above)
Comment (peter-sanderson) [reply packages/theme/src/colors.ts:9]: :heavy_check_mark:

Comment (peter-sanderson) [reply packages/theme/src/colors.ts:9]: https://github.com/trezor/trezor-suite/issues/10721

File: packages/theme/src/boxShadows.ts (hunk 16 above)
Comment (peter-sanderson) [reply packages/theme/src/boxShadows.ts]: :heavy_check_mark:

**Review by dahaca — APPROVED** [review]
Huge thatnks for addressing all my wishes at once! It's trully an important foundation for Suite going forward 🧑‍🎨
