### PR TITLE
fix(suite): Fix FeeCard responsiveness + refactoring

### LINKED ISSUE #17996: Fee setting breaks too soon when resizing the window.
**Describe the bug**
In the Send form, the breakpoint is set too soon therefore it happens to change the layout of the fee settings (Low/Normal/High) in a moment, where it ends up being wide long noodles.

**Info:**

-   Suite Version: 25.3

**How to reproduce**

1. Go to send form
2. Watch fee settings
3. Try resizing the window wildly
4. Observe fee settings becoming long noodles

**Expected behavior**
Min-width would be much smaller for fee settings to stay horizontal.

**Screenshots**
Image

https://github.com/user-attachments/assets/1ecfcf91-5593-49f4-8610-950f97008fe6

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve #17996

## Screenshots:

before

https://github.com/user-attachments/assets/a8973540-e333-4877-88cc-6fc4fcffbd4a

after

https://github.com/user-attachments/assets/d877b6af-a588-48ef-b73a-02b99342f4ad

### CODE REVIEW

**Comment by jvaclavik** [comment]
@STew790 @bosomt I removed quite a bit of code in this PR that I believe isn’t needed anymore. That said, it would be good to double-check that I didn’t accidentally break anything. I clicked through the app and it seems fine, but I can’t say with 100% certainty.

File: packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx [hunk 1]
```diff
@@ -14,122 +14,112 @@ import { FeeOptionType, getFeeLevelTranslationId } from '../Fees';
...
+                            <FeeRate
+                                feeRate={isEip1559(fee) ? fee.maxFeePerGas : fee.feePerUnit}
+                                networkType={networkType}
+                                symbol={symbol}
+                            />
+                        }
+                        tooltipContent={
+                            isDebug && isEip1559(fee) ? (
+                                <Grid columns={2} gap={spacings.xs}>
+                                    <Row>
```
Comment (seibei-iguchi) [inline packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx]: useless Row?

File: packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx [hunk 2]
```diff
@@ -14,122 +14,112 @@ import { FeeOptionType, getFeeLevelTranslationId } from '../Fees';
...
+                                        <Badge variant="warning" size="small">
+                                            <Translation id="TR_DEBUG_ONLY" />
+                                        </Badge>
+                                    </Row>
+                                    <span />
```
Comment (seibei-iguchi) [inline packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx]: ?

File: packages/suite/src/components/wallet/Fees/StandardFee/MiscFeeCards.tsx [hunk 3]
```diff
@@ -21,7 +21,7 @@ export const MiscFeeCards = forwardRef<HTMLDivElement, StandardFeeProps>(
         const feeAmount = isSolanaNetwork ? fee.feePerTx : fee.feePerUnit;
 
         return (
-            <FeeCardsWrapper $columns={columns ?? 1} ref={ref} data-testid="@wallet/fee-details">
+            <FeeCardsWrapper ref={ref} data-testid="@wallet/fee-details">
```
Comment (seibei-iguchi) [inline packages/suite/src/components/wallet/Fees/StandardFee/MiscFeeCards.tsx]: Why is the ref forwarding kept here and removed on the other ones?

File: packages/suite/src/components/wallet/Fees/StandardFee/StandardFee.tsx [hunk 4]
```diff
@@ -25,69 +23,28 @@ export type StandardFeeProps = {
...
-        const { inlineSize: elementWidth } = borderBoxSize;
-
-        const minWidth = (FEE_CARD_MIN_WIDTH + spacings.xs) * feeOptions.length;
-
-        const columns = elementWidth > minWidth ? feeOptions.length : 1;
-
-        setColumns(columns);
-    });
-
 export const StandardFee = (props: StandardFeeProps) => {
```
Comment (seibei-iguchi) [inline packages/suite/src/components/wallet/Fees/StandardFee/StandardFee.tsx:38]: Use switch instead of ifs

Comment (jvaclavik) [reply packages/suite/src/components/wallet/Fees/StandardFee/StandardFee.tsx:38]: Done

File: packages/suite/src/components/wallet/Fees/StandardFee/MiscFeeCards.tsx (hunk 3 above)
Comment (jvaclavik) [reply packages/suite/src/components/wallet/Fees/StandardFee/MiscFeeCards.tsx]: Deleted

File: packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx (hunk 2 above)
Comment (jvaclavik) [reply packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx]: Deleted

File: packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx (hunk 1 above)
Comment (jvaclavik) [reply packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx]: Deleted

**Review by seibei-iguchi — APPROVED** [review]

File: packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx [hunk 5]
```diff
@@ -14,122 +14,109 @@ import { FeeOptionType, getFeeLevelTranslationId } from '../Fees';
...
-                            }
-                            tooltipContent={
-                                isDebug && isEip1559(fee) ? (
-                                    <Grid columns={2} gap={spacings.xs}>
-                                        <Row>
-                                            <Badge variant="warning" size="small">
-                                                <Translation id="TR_DEBUG_ONLY" />
-                                            </Badge>
-                                        </Row>
-                                        <span />
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/Fees/StandardFee/EthereumFeeCards.tsx:98]: Removing this caused this

Screenshot 2025-04-05 at 11 04 14

**Review by tomasklim — COMMENTED** [review]
@jvaclavik please

**Comment by STew790** [comment]
**QA NOK**
As stated above
image

**Info:**
 - Suite version: web 25.5.0 (444b158d014407c47c873fe32df04173255a14c6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: WebUsbTransport

**Comment by jvaclavik** [comment]
> **QA NOK** As stated above image
> 
> **Info:**
> 
> * Suite version: web 25.5.0 ([444b158](https://github.com/trezor/trezor-suite/commit/444b158d014407c47c873fe32df04173255a14c6))
> * Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
> * OS: MacIntel
> * Screen: 1920x1080
> * Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
> * Transport: WebUsbTransport

Where is this tooltip? I can't find it.

image

**Comment by jvaclavik** [comment]
> **QA NOK** As stated above image
> 
> **Info:**
> 
> * Suite version: web 25.5.0 ([444b158](https://github.com/trezor/trezor-suite/commit/444b158d014407c47c873fe32df04173255a14c6))
> * Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
> * OS: MacIntel
> * Screen: 1920x1080
> * Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
> * Transport: WebUsbTransport

not related to this PR but fixed: https://github.com/trezor/trezor-suite/pull/18195

**Comment by STew790** [comment]
**QA OK**
Ah, didn't know, then it is ok.
