### PR TITLE
fix(suite): remove translatable network title

### LINKED ISSUE #16193: Introduce name of displaySymbol
We introduced that networks use `displaySymbol` 

Base network -> ETH symbol
However, on some places in codebase we need to tell the user the name of this `displaySymbol`

Image
Image
Image

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- in some places we used "translatable" network name and in some not. So I removed it completely
- introduced `displaySymbolName`

## Related Issue

Resolve [#16193](https://github.com/trezor/trezor-suite/issues/16193)

## Screenshots:

Screenshot 2025-01-07 at 11 44 54
Screenshot 2025-01-07 at 11 44 22
Screenshot 2025-01-07 at 11 44 19

### CODE REVIEW

File: suite-common/wallet-config/src/utils.ts [hunk 1]
```diff
@@ -89,3 +89,9 @@ export const getNetworkByCoingeckoNativeId = (coingeckoId: string) =>
     networksCollection.find(n => n.coingeckoNativeId === coingeckoId);
 
 export const getNetworkDisplaySymbol = (symbol: NetworkSymbol) => getNetwork(symbol).displaySymbol;
+
+export const getNetworkDisplaySymbolName = (symbol: NetworkSymbol) => {
+    const network = getNetwork(symbol);
+
+    return network.displaySymbolName || network.name;
```
Comment (adderpositive) [inline suite-common/wallet-config/src/utils.ts:96]: nitpick

```suggestion
    return network.displaySymbolName ?? network.name;
```

**Review by adderpositive — APPROVED** [review]
