### PR TITLE
fix(add wallet tooltip): show tooltip if device disconnected

### LINKED ISSUE #3847: Toooltip ask you to connect device even when connected
**Describe the bug**
Tooltip ask you to connect device even when connected.
Im not sure if this is correct/expected behaviour, but i rather point it out.
It's present in web version 21.5.1 too /dark mode screenshot/

**Steps to reproduce:**
1. Connect your device/devices
2. Open Wallets modal
3. hover over `+ add hidden wallet`

**Info:**
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3_1) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model One 1.10.1 regular

**Screenshots:**

obrazek

obrazek

obrazek

### PR DESCRIPTION
**Pull request by dimasivan**
fix #3847 

show tooltip if device is locked / disconnected

### CODE REVIEW

File: packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx [hunk 1]
```diff
@@ -65,11 +65,30 @@ const AddWalletButton = ({ device, instances, addDeviceInstance, selectDeviceIns
...
+        children,
+    }) => (isLocked ? wrapper(children) : children);
+
     return (
         <AddWallet>
-            <StyledTooltip
-                content={<Translation id="TR_TO_ACCESS_OTHER_WALLETS" />}
-                cursor="pointer"
+            <IsLockedDeviceWrapper
+                isLocked={isLocked}
```
Comment (marekrjpolak) [inline packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx]: Nitpick: When you click on the button, the device become locked so the tooltip appears for a moment.

File: packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx [hunk 2]
```diff
@@ -65,11 +65,30 @@ const AddWalletButton = ({ device, instances, addDeviceInstance, selectDeviceIns
         });
     };
 
+    type IsLockedDeviceWrapperProps = {
+        children: React.ReactElement;
+        isLocked: boolean;
+        wrapper: (children: React.ReactElement) => JSX.Element;
+    };
+
+    const IsLockedDeviceWrapper: React.FC<IsLockedDeviceWrapperProps> = ({
```
Comment (marekrjpolak) [inline packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx]: Is there any reason not to use TooltipConditional instead of a new single-purpose component?

**Review by marekrjpolak — CHANGES_REQUESTED** [review]

**Review by marekrjpolak — APPROVED** [review]
LGTM.
