### PR TITLE
Fix and refactor selectors for empty device states

### LINKED ISSUE #12524: Switch to portfolio tracker sent user to empty dashboard instead of sync coin
1. Open the app
3. Connect device
4. Enable view-only
5. Disconnect device
6. Try to switch from disconnected device to portfolio tracker
7. You are redirected to "empty dashboard"

Video: 
https://github.com/trezor/trezor-suite/assets/84183817/5f081569-4731-4b4f-a45e-316a7fca7cc1

Version: 24.5.0, Last commit hash: 5e5d8a3

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

The root cause of the bug was in `selectIsNoPhysicalDeviceConnected` that has been changed in https://github.com/trezor/trezor-suite/pull/12479/commits/3b0a4ca969faf970aef52f3b3c6d7a0041c8fa1b to do what the name says and fix bug with connecting trezor while there is already something remembered.

We discussed the names thoroughly with @vytick  and this is the best we could come up with.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12524

### CODE REVIEW

File: suite-native/device/src/hooks/useDetectDeviceError.tsx [hunk 1]
```diff
@@ -151,11 +149,4 @@ export const useDetectDeviceError = () => {
         showAlert,
         handleDisconnect,
     ]);
-
```
Comment (matejkriz) [inline suite-native/device/src/hooks/useDetectDeviceError.tsx:154]: fixme

**Review by juriczech — APPROVED** [review]
LGTM. Mucho readable IMO. GG
