### PR TITLE
fix(suite-native): align welcome screen with design

### LINKED ISSUE #13257: Fix UI of Welcome Screen for dark mode
Borders and backgrounds in onboarding are broken (and it is first screen every new user see), fix it by [FIGMA](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=689-9271&t=UKVccuAiW7tl0r0H-11)
image

### PR DESCRIPTION
**Pull request by yanascz**
Fixed border and footer text colour.

## Related Issue

Resolve #13257

## Screenshots:
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 40 54
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 40 57
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 41 00
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 41 02
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 41 05
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 43 46
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 43 49
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 43 53
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 43 57
Simulator Screenshot - iPhone 15 Pro Max - 2024-08-30 at 14 44 03

### CODE REVIEW

**Review by PeKne — APPROVED** [review]

File: suite-native/atoms/src/StepsProgressBar.tsx [hunk 1]
```diff
@@ -29,10 +29,10 @@ const progressBarItemStyle = prepareNativeStyle<{ isActive: boolean }>((utils, {
     borderRadius: utils.borders.radii.small / 4,
     borderWidth: utils.borders.widths.medium,
     borderColor: isActive
-        ? utils.colors.backgroundPrimaryDefault
+        ? utils.colors.backgroundSecondaryDefault
         : utils.colors.backgroundNeutralSubdued,
     backgroundColor: isActive
-        ? utils.colors.backgroundPrimaryDefault
+        ? utils.colors.backgroundSecondaryDefault
         : utils.colors.backgroundNeutralSubdued,
```
Comment (jvaclavik) [inline suite-native/atoms/src/StepsProgressBar.tsx]: btw I think you don't use icons semantically according their designation. You should use `borderElevation0` etc.

**Review by jvaclavik — APPROVED** [review]

File: suite-native/atoms/src/StepsProgressBar.tsx (hunk 1 above)
Comment (yanascz) [reply suite-native/atoms/src/StepsProgressBar.tsx]: Here the border is not supposed to be at all. However, the border color in `progressBarWrapperStyle` was wrong. Fixed.

File: suite-native/module-onboarding/src/screens/WelcomeScreen.tsx [hunk 2]
```diff
@@ -91,12 +92,11 @@ export const WelcomeScreen = () => {
                 style={applyStyle(imageContainerStyle)}
             />
             <Screen backgroundColor="transparent">
-                <LinearGradient
+                <Box
```
Comment (yanascz) [inline suite-native/module-onboarding/src/screens/WelcomeScreen.tsx]: We agreed with @shenkys to ditch the gradient and unify the backgrounds for all screens. However, the blur seems to be problematic since it may only be applied to an image and the image covers a bigger area. Solved by transparency instead since onboarding is to be reworked.

Comment (vytick) [reply suite-native/module-onboarding/src/screens/WelcomeScreen.tsx]: In case we wont be using linear gradient, I think this can be simplified using `OnboardingScreen` similar to other onboarding screens

Comment (yanascz) [reply suite-native/module-onboarding/src/screens/WelcomeScreen.tsx]: I don't think so because `OnboardingScreen` has a header with stepper. 😕

File: suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx [hunk 3]
```diff
@@ -64,7 +64,7 @@ export const TrackBalancesScreen = () => {
         <OnboardingScreen
             title={<Translation id={content.title} />}
             subtitle={<Translation id={content.subtitle} />}
-            activeStep={3}
```
Comment (yanascz) [inline suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx:67]: This lead to incorrect progress bar rendering on iOS.

**Comment by Nodonisko** [comment]
Since you are looking into this, can you please replace that big SVGs with PNG/WebM? It was mistake to use them because SVGs are much slower to render if they are complicated and big which these are.

File: suite-native/module-onboarding/src/screens/WelcomeScreen.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/module-onboarding/src/screens/WelcomeScreen.tsx]: Can the header be optional and then reusable?

Comment (yanascz) [reply suite-native/module-onboarding/src/screens/WelcomeScreen.tsx]: OK, now I understand what you meant! I gave it a try and I guess it looks a bit better. 😎

**Review by vytick — APPROVED** [review]
Looks good! 🚀
