### PR TITLE
Fix hanging bridge spinner and display recommendation on bridge updating for desktop users

### LINKED ISSUE #2875: Desktop app: update bridge forever loading
**Describe the bug**
I've just run desktop app on some old setup which has trezor bridge v 2.0.12 installed (quite outdated) 
desktop app notifies me about outdated bridge (correctly) but when i click on "update bridge" button it ends up with "forever loading" state

**Info:**
 - Suite Version: desktop app
 - OS: windows 10
 - Installed Bridge Version: 2.0.12 (outdated)

**Expected result:**
Not sure :) should i download new bridge and install it, or remove pre-installed bridge and start using bundled one?

**Screenshots:**

forever-loading

### PR DESCRIPTION
**Pull request by keraf**
Fixes #2875 and also adds a recommendation on what to do if the bridge is outdated on desktop (please review the copy, I wasn't very inspired :smile: )

### CODE REVIEW

**Comment by szymonlesisz** [comment]
it doesn't fix the issue completely
i'm still able to kill `trezord` subprocess and it will never be started again (third comment in the issue)

**Review by glacierbits — APPROVED** [review]

**Comment by keraf** [comment]
Restarting the process will be addressed in a separate PR (coming soon). I didn't include it in this change because it I don't think it's really critical (but nice to have for sure). If the process crashes, the user can just restart Suite.

**Review by tomexx — APPROVED** [review]

File: packages/suite/src/views/suite/bridge/index.tsx [hunk 1]
```diff
@@ -148,6 +153,11 @@ const InstallBridge = (props: Props) => {
                         id="TR_CURRENTLY_INSTALLED_TREZOR"
                         values={{ version: data.currentVersion }}
                     />
+                    {isDesktop() && (
+                        <BridgeDesktopNote>
```
Comment (szymonlesisz) [inline packages/suite/src/views/suite/bridge/index.tsx:157]: i think this message should be displayed instead of "gathering information loader" (line 164) because now they are visible both
so this component should have 3 conditional views:
- desktop info (only in desktop)
- loading (web only)
- bridge download (web only)

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/suite/bridge/index.tsx (hunk 1 above)
Comment (keraf) [reply packages/suite/src/views/suite/bridge/index.tsx:157]: Displaying loading and downloads links on desktop is correct imo. As the text hints that updating bridge is an option, providing the links to do so is correct. Loading might happen if the bridge gets killed. So it would be good to have an indicator of some sort.

**Comment by keraf** [comment]
@szymonlesisz Auto-restart addressed in #2922

**Comment by tsusanka** [comment]
@szymonlesisz @keraf let's finish this one? :)

File: packages/suite/src/views/suite/bridge/index.tsx (hunk 1 above)
Comment (szymonlesisz) [reply packages/suite/src/views/suite/bridge/index.tsx:157]: ah right, it makes sense

**Review by szymonlesisz — APPROVED** [review]
