### PR TITLE
Fix CoinLogo colors depending on the color scheme

### LINKED ISSUE #16884: Sidebar coin icons ignore Color scheme changed in app
**Describe the bug**
Sidebar coin icons ignore Color scheme changed in app 

**Steps to reproduce:**
1. Load multiple coins
2. Change app color scheme multiple times
3. Observe icons behavior

**Info:**
 - Suite version: desktop 25.2.1 (0f361faefc9ed1ed203658a47ee048833113771b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.2.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.8 regular (revision bbcb920213b0ab847a2fedf825eac70652e33279)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/9f5de4ab-60dd-4934-982f-4235062a3a68

### PR DESCRIPTION
**Pull request by izmy**
## Description

The new CoinLogo type **network** uses a black and white variant and switches colors in dark/light mode.

## Screenshots:

image

### CODE REVIEW

File: packages/theme/src/colors.ts [hunk 1]
```diff
@@ -161,6 +161,8 @@ const light = {
     textPrimaryPressed: palette.lightPrimaryForest900,
     textSecondaryHighlight: palette.lightSecondaryEmerald800,
     textSubdued: palette.lightGray700,
+    logoBg: palette.lightGray900,
+    logoFg: palette.lightGray100,
```
Comment (jvaclavik) [inline packages/theme/src/colors.ts:165]: Couldn't we use existing token? Can you ask David Kotik about it? He is the master of colors

File: packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx [hunk 2]
```diff
@@ -37,5 +37,11 @@ export const CoinLogo: StoryObj<CoinLogoProps> = {
                 type: 'select',
             },
         },
+        type: {
+            options: ['coin', 'network', 'badge'],
```
Comment (tomasklim) [inline packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx]:
```suggestion
            options: ['token', 'network', 'tokenNetworkBadge'],
```
I would improve naming. I am not sure with this though `tokenNetworkBadge` any ideas?

File: packages/product-components/src/components/CoinLogo/CoinLogo.tsx [hunk 3]
```diff
@@ -68,9 +78,14 @@ export const CoinLogo = ({
...
     } else {
         // TODO: should be changed, this is hacky way
-        const networkSymbol = getNetworkDisplaySymbol(
-            symbol as NetworkSymbol,
-        )?.toLowerCase() as NetworkSymbol;
+        let networkSymbol;
+        try {
+            networkSymbol = getNetworkDisplaySymbol(
+                symbol as NetworkSymbol,
+            )?.toLowerCase() as NetworkSymbol;
```
Comment (tomasklim) [inline packages/product-components/src/components/CoinLogo/CoinLogo.tsx]: does it fail with `?`

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/product-components/src/components/CoinLogo/CoinLogo.tsx (hunk 3 above)
Comment (izmy) [reply packages/product-components/src/components/CoinLogo/CoinLogo.tsx]: I found a problem in Storybook when I was trying symbols that were missing in the networks used in `getNetwork` method.

```
export const getNetwork = (symbol: NetworkSymbol): Network => networks[symbol];
const getNetworkDisplaySymbol = (symbol: NetworkSymbol) => getNetwork(symbol).displaySymbol;
```

Comment (tomasklim) [reply packages/product-components/src/components/CoinLogo/CoinLogo.tsx]: ah makes sense

Comment (tomasklim) [reply packages/product-components/src/components/CoinLogo/CoinLogo.tsx]: so maybe we can remove also the `?` so that it does not stay as undefined?

File: packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx (hunk 2 above)
Comment (izmy) [reply packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx]: What about `layerNetworkBadge`?

Comment (tomasklim) [reply packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx]: I dont know
tokenWithNetworkBadge? 😀

Comment (tomasklim) [reply packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx]: `tokenWithNetwork` ship-it

File: packages/theme/src/colors.ts (hunk 1 above)
Comment (izmy) [reply packages/theme/src/colors.ts:165]: I thought it was better to have semantically correct naming, also `palette.lightGray900` is not used yet. Anyway, I wrote to David so we will see.

File: packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx (hunk 2 above)
Comment (izmy) [reply packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx]: done

**Comment by bosomt** [comment]
created issue https://github.com/trezor/trezor-suite/issues/16884

File: packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx (hunk 2 above)
Comment (tomasklim) [inline packages/product-components/src/components/CoinLogo/CoinLogo.stories.tsx]:
```suggestion
            options: ['token', 'network', 'tokenWithNetwork'],
```

**Review by tomasklim — APPROVED** [review]
