### PR TITLE
Device busy view

### LINKED ISSUE #20942: Add views for device-busy state
Sometimes, when paired over bluetooth, device is in a busy state and cannot be interacted with until some action is taken on the device. Suite does not recognize this state and thinks that the device is used in another window and offers a button to use device here, which won't work. Adjust the messaging so that it is clear user should focus on the device.

https://github.com/user-attachments/assets/c756a905-d163-47f3-b84e-c54b5ff35d56

0:13 I refresh Suite when Trezor is in bootloader mode (blue screen on Trezor) - this state is not handled, Suite thinks it is used in another window but in fact it is in the busy state and cannot be communicated with at all, the button doesn't help. Instead of the current message, show "Trezor detected in incorrect state, restart it to reconnect." and remove the button. 

- Implement this also in the mobile app.
- See if there are other ways how you can get to this state than the one shown in the video.

### PR DESCRIPTION
**Pull request by komret**
WIP from @szymonlesisz to be completed.

Resolve https://github.com/trezor/trezor-suite/issues/20942

## What's done here
- added device-busy state to the "Connect" initial screen - displays hint that device may be in bootloader mode and requests restart
- added Hint to the "device selector banner"  that also displays hint to restart the device when busy
- adds a modal to the update process in onboarding that pops up when you need to click "Connect to host"
- same modal to the update when done through settings

## What this does
Adds the modal to when the device says during FW update `Connect to host` this pops a modal that prompts user to focus on the device.

## Questions
- is the copy correct?
- shoudn't the modals be more specific and tell the user what exactly he should click in what state the device is?

## TODO:
- is the hack around modal in onboarding okayish?
- update the modals texts?

cc @komret 

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/device-busy-view&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/device-busy-view&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/device-busy-view&lookback=7)

### CODE REVIEW

**Comment by szymonlesisz** [comment]
also should resolve https://github.com/trezor/trezor-suite/issues/21117

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx [hunk 1]
```diff
@@ -30,6 +30,12 @@ export const FirmwareProgressBar = () => {
         completed: 'TR_FIRMWARE_STATUS_INSTALLATION_COMPLETED',
     };
 
+    if (uiEvent?.type === 'ui-firmware_reconnect') {
```
Comment (vojtatranta) [inline packages/suite/src/components/firmware/FirmwareProgressBar.tsx:35]: I think this should also be removed , I am not sure what supposed to happen here, maybe @szymonlesisz could advice?

File: packages/suite/src/views/onboarding/steps/FirmwareInstallation.tsx [hunk 2]
```diff
@@ -32,52 +34,115 @@ interface FirmwareInstallationProps {
...
-                </SelectDevice>
-            );
-        }
-        if (status === 'done') {
-            return (
-                <Button
-                    variant="primary"
-                    onClick={onSuccess}
-                    data-testid="@firmware/continue-button"
+                <div
```
Comment (vojtatranta) [inline packages/suite/src/views/onboarding/steps/FirmwareInstallation.tsx]: this is nasty but somewhat working @seibei-iguchi advice how to do it better?

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx (hunk 1 above)
Comment (komret) [reply packages/suite/src/components/firmware/FirmwareProgressBar.tsx:35]: I believe the intention was to hide progress bar at the start of the process before installation has begun. This is good unless it causes some issue later during installation.

File: packages/suite/src/views/onboarding/steps/FirmwareInstallation.tsx [hunk 3]
```diff
@@ -32,52 +33,84 @@ interface FirmwareInstallationProps {
...
+                    position: 'fixed',
+                    top: 0,
+                    left: 0,
+                    right: 0,
+                    zIndex: 1000,
+                    width: '100vw',
+                    height: '100vh',
+                }}
+            >
+                <ConfirmActionModal device={originalDevice} />
```
Comment (vojtatranta) [inline packages/suite/src/views/onboarding/steps/FirmwareInstallation.tsx]: I'd create here a specific modals that would tell the user what should they exactly see on screen and what to click, not these general modals like "Follow instructions on the device"

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx (hunk 1 above)
Comment (vojtatranta) [reply packages/suite/src/components/firmware/FirmwareProgressBar.tsx:35]: seems okay

**Comment by vojtatranta** [comment]
@szymonlesisz I have pushed a version that displays the modal during the FW update phasen when  device shows 'Connect to host device'.

As we talked, this change makes sense.

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx [hunk 4]
```diff
@@ -142,12 +147,12 @@ export const ReconnectDevicePrompt = ({ onClose, onSuccess }: ReconnectDevicePro
...
         <Modal.Backdrop onClick={isAbortable ? onClose : undefined}>
-            {!isManualRebootRequired && !isRebootDone && (
+            {showConfirmOnDevice && (
                 <ConfirmOnDevice
                     title={<Translation id="TR_CONFIRM_ON_TREZOR" />}
-                    deviceModelInternal={deviceModelInternal}
-                    deviceUnitColor={device?.features?.unit_color}
-                    isConfirmed={!buttonEvent}
+                    deviceModelInternal={eventDevice?.features?.internal_model}
+                    deviceUnitColor={eventDevice?.features?.unit_color}
```
Comment (komret) [inline packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx:154]: Changing these because `device` is `undefined` while `deviceIsWaitingForConfirmationToConnectToHost`, so we need to use what Connect is sending in the event.

**Comment by vojtatranta** [comment]
looking good, approving

**Review by vojtatranta — APPROVED** [review]
