### PR TITLE
Trading: Apply minimum validation to fiat input

### LINKED ISSUE #14822: Trading - minimum is applied only to token, not to fiat
**Describe the bug**

Suite version: 24.10.1

Minimum BNB to trade is +-150$
Screenshot 2024-10-14 at 12 58 02

But I can trade 0.01$
Screenshot 2024-10-11 at 10 40 50

### PR DESCRIPTION
**Pull request by izmy**
## Description

- Added minimum amount validation for fiat input and display of errors in selected fiat currencies
- Synced fiat and crypto amounts: when a value is entered in one input, it’s recalculated for the other when switching

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14822

## Screenshots:

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-fiat-minimum-validation&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-fiat-minimum-validation&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingCurrencySwitcher.ts [hunk 1]
```diff
@@ -42,33 +46,51 @@ interface TradingUseCurrencySwitcherProps<T extends TradingAllFormProps> {
...
+    const fiatInputValue = useWatch({ control, name: inputNames.fiatInput });
     const sendCryptoSelect = getValues(TRADING_FORM_SEND_CRYPTO_CURRENCY_SELECT);
+    const currencySelect = getValues(TRADING_FORM_OUTPUT_CURRENCY);
     const networkDecimals = getTradingNetworkDecimals({
         sendCryptoSelect,
         network,
     });
+    const fiatRateKey = getFiatRateKey(
+        account.symbol,
+        currencySelect?.value ? currencySelect.value : 'usd',
```
Comment (TomasBoda) [inline packages/suite/src/hooks/wallet/trading/form/common/useTradingCurrencySwitcher.ts]: Can we use some global fallback constant instead of `usd`? for instance `buySelectors.ts` and `sellSelectors.ts` have `DEFAULT_FIAT_CURRENCY_FALLBACK = 'USD'` defined, I guess it would make sense to define this somewhere as well.

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingCurrencySwitcher.ts [hunk 2]
```diff
@@ -42,33 +46,51 @@ interface TradingUseCurrencySwitcherProps<T extends TradingAllFormProps> {
...
+    );
+    const rate = rates && rates[fiatRateKey] ? rates[fiatRateKey].rate : undefined;
+    const { fiatAmount } = useFiatFromCryptoValue({
+        amount: cryptoInputValue ?? '',
+        symbol: account.symbol,
+    });
+
+    const cryptoAmount =
+        fiatInputValue != null
```
Comment (TomasBoda) [inline packages/suite/src/hooks/wallet/trading/form/common/useTradingCurrencySwitcher.ts]: Nitpick: `fiatInputValue` is of type `string | undefined`, I'd omit the `!= null`.

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiat.tsx [hunk 3]
```diff
@@ -60,6 +69,38 @@ export const TradingFormInputFiat = <TFieldValues extends TradingAllFormProps>({
...
+                                  currencySelect?.value ? currencySelect.value : 'usd',
+                              );
+                              const rate =
+                                  rates && rates[fiatRateKey] ? rates[fiatRateKey].rate : undefined;
+                              const minFiat = toFiatCurrency({
+                                  amount: context.amountLimits.minCrypto,
+                                  rate,
+                              })?.toString();
+
+                              if (minFiat != null) {
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiat.tsx]: Nitpick:
```suggestion
                              if (minFiat) {
```

**Review by TomasBoda — CHANGES_REQUESTED** [review]
When switching to the fiat currency, first, there is `EUR`, but when I change the currency, it applies the full name, e.g. `EUR - Euro` and the whole label does not fit into the label container and is cut off.

Moreover, changing the fiat currency leaves the amount in fiat value unchanged. That would be okay I guess but the rates are not recalculated and the `You get` crypto amount stays the same.

I don't know if it is a part of this PR but should definitely be fixed.

https://github.com/user-attachments/assets/4e48e2ae-6b3b-4883-923c-da749c4ea177

**Review by matusbalascak — APPROVED** [review]
LGTM

**Comment by izmy** [comment]
> When switching to the fiat currency, first, there is `EUR`, but when I change the currency, it applies the full name, e.g. `EUR - Euro` and the whole label does not fit into the label container and is cut off.
> 
> Moreover, changing the fiat currency leaves the amount in fiat value unchanged. That would be okay I guess but the rates are not recalculated and the `You get` crypto amount stays the same.
> 
> I don't know if it is a part of this PR but should definitely be fixed.

I also noticed this. It wasn’t part of the original issue, but I’ve fixed it here as well ✅

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingCurrencySwitcher.ts (hunk 1 above)
Comment (izmy) [reply packages/suite/src/hooks/wallet/trading/form/common/useTradingCurrencySwitcher.ts]: done

**Review by TomasBoda — COMMENTED** [review]
I guess this number is incorrect. Maybe a conversion issue?

Image

Because minimum `USDC` is `5`ish.

Screenshot 2025-10-02 at 16 52 28

**Review by TomasBoda — COMMENTED** [review]
The issue with changing the fiat currency still persists. Swapping `10 EUR` and `10 CZK` should give a different amount of received `BTC`.

https://github.com/user-attachments/assets/35883cf6-d3d7-43b1-b478-97b82f7fdd21

**Comment by izmy** [comment]
@TomasBoda I finally fixed these bugs! Please check again.

**Review by TomasBoda — APPROVED** [review]
LGTM.
Some minor (non-related) issues persist, but works much better than before.
