### PR TITLE
fix(suite-native): correct assets for selling in trade sell flow

### LINKED ISSUE #20508: Mobile Sell: MyAssetSheet use exchange specific data and not universal
When picking asset to sell in MyAssets should also be used for sell but there is exchange related selector

### PR DESCRIPTION
**Pull request by vytick**
MyAssets seemed to be tradeType agnostic, but it used exchange supported assets for sell. Now it returns correct sell cryptoIds for sell and nothing for buy.

## Related Issue

Resolve #20508

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=20508-mobile-sell-myassetsheet-use-exchange-specific-data-and-not-universal&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=20508-mobile-sell-myassetsheet-use-exchange-specific-data-and-not-universal&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=20508-mobile-sell-myassetsheet-use-exchange-specific-data-and-not-universal&lookback=7)

### CODE REVIEW

File: suite-common/trading/src/selectors/tradingSelectors.ts [hunk 1]
```diff
@@ -470,6 +470,20 @@ const createExchangeCryptoIdsSelector = (key: 'buyCryptoIds' | 'sellCryptoIds')
 export const selectTradingExchangeSellCryptoIds = createExchangeCryptoIdsSelector('sellCryptoIds');
 export const selectTradingExchangeBuyCryptoIds = createExchangeCryptoIdsSelector('buyCryptoIds');
 
+export const selectTradingSellSellCryptoIds = createMemoizedSelector(
```
Comment (jbazant) [inline suite-common/trading/src/selectors/tradingSelectors.ts:473]: **issue:** Please add test‏

**Review by jbazant — APPROVED** [review]
LGTM

File: suite-common/trading/src/selectors/tradingSelectors.ts (hunk 1 above)
Comment (vytick) [reply suite-common/trading/src/selectors/tradingSelectors.ts:473]: updated in e449b5833cefc44cdf6210f5029b9a03a88c5a32
