### PR TITLE
23592 turn on suite sync with a hotfix

### LINKED ISSUE #23641: Trezor Suite Sync: Turn On is incomplete, there is a bug when the sync is turned on again
**Describe the bug**

We [started to implement](https://github.com/trezor/trezor-suite/pull/23624) the Turn On feature for Trezor Sync. It supposed to start over sync completely once it's turned off. However, there is apparently a problem in Evolu, where the instance isn't destroyed completely. So there is still some state hanging, and a restart of Evolu sees empty DB tables. 

This issue is tracked i Evolu Repo: https://github.com/evoluhq/evolu/issues/614#issuecomment-3613721491

Repro:
1. At this PR: https://github.com/trezor/trezor-suite/pull/23624
2. start app, start sync - you see it working
3. go to genera settings, turn off the trezor sync
4. you see "no labels" - default ones
5. turn on the Suite Sync again, you see errors in the console and when you try to edit the label, it throws an eror as well 

**Expected behavior**
You should be able to set different labels

### PR DESCRIPTION
**Pull request by vojtatranta**
## Description

~‼️ BLOCKED BY EVOLU ‼️~ we will do a "refresh" workaround

## Notes for QA

- technically hard to test
- you could test if the suite sync works properly when you turn it off and then turn it on again
- turning of should be done through Debug settings (disabled flag) and from Settings - just select different labeling
- when oyu turn off the labeling on mobil / desktop, the app should refresh / restart to make sure that evolus resources are cleared and no error will be displayed

## Related Issue

Resolve (temporary)  https://github.com/trezor/trezor-suite/issues/23641

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=23592-turn-on-suite-sync&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=23592-turn-on-suite-sync&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=23592-turn-on-suite-sync&lookback=7)

### CODE REVIEW

**Comment by vojtatranta** [comment]
I have an problem when I re-enable suite sync in general settings, it throws an error. But I really don't know why.

Repro:
- start up a wiped device
- turn on Trezor Sync
- edit some wallet label (all good for now)
- go to general settings, turn off the Trezor Sync
- in wallet switcher, you see No label (default text - standard wallet)
- activate Trezor Sync in General settigns again (you see your new label of wallet in the wallet switcher)
- try to edit the wallet label again - fails with error below

I have an issue here. For some reason I get hthis SQLite error:

```
"type":"SqliteError","error":{"type":"TransferableError","error":{"stack":"SQLite3Error: SQLITE_ERROR: sqlite3 result code 1: no such table: evolu_usage\n    at toss3 (webpack-internal:///../../node_modules/@evolu/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:9687:17)\n    at checkSqlite3Rc (webpack-internal:///../../node_modules/@evolu/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:9706:13)\n    at DB.checkRc (webpack-internal:///../../node_modules/@evolu/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:10112:42)\n    at OpfsSAHPoolDb.exec (webpack-internal:///../../node_modules/@evolu/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-bundler-friendly.mjs:10246:20)\n    at Object.exec (webpack-internal:///../../node_modules/@evolu/web/dist/src/WasmSqliteDriver.js:73:29)\n    at eval (webpack-internal:///../../node_modules/@evolu/common/dist/src/Sqlite.js:54:81)\n    at maybeLogSqliteQueryExecutionTime (webpack-internal:///../../node_modules/@evolu/common/dist/src/Sqlite.js:121:16)\n    at type (webpack-internal:///../../node_modules/@evolu/common/dist/src/Sqlite.js:54:28)\n    at trySync (webpack-internal:///../../node_modules/@evolu/common/dist/src/Result.js:105:19)\n    at Object.exec (webpack-internal:///../../node_modules/@evolu/common/dist/src/Sqlite.js:52:77)","message":"SQLITE_ERROR: sqlite3 result code 1: no such table: evolu_usage","resultCode":1,"name":"SQLite3Error"}}}
```

File: packages/suite-desktop-core/src/app.ts [hunk 1]
```diff
@@ -321,6 +321,12 @@ const init = async () => {
         store,
     });
 
+    ipcMain.handle('browser-window/reload', ipcEvent => {
```
Comment (vojtatranta) [inline packages/suite-desktop-core/src/app.ts:324]: note: the `window.location.reload()` is basically forbidde by our security policies, it won't do anything. I guess it could be misused to request some other url? I didn't want to add ther exception for "expected url".

Hence I put a special reload method that will reload only the current window in the main process.

Comment (vojtatranta) [reply packages/suite-desktop-core/src/app.ts:324]: cc @Lemonexe

File: suite-common/suite-sync-types/src/storageFlusher.ts [hunk 2]
```diff
@@ -0,0 +1,5 @@
+export type StorageFlusher = () => void;
+
+export type StorageFlusherDep = {
```
Comment (peter-sanderson) [inline suite-common/suite-sync-types/src/storageFlusher.ts]: I simply LOVE the naming. :toilet:

Comment (vojtatranta) [reply suite-common/suite-sync-types/src/storageFlusher.ts]: :D yeah

File: packages/suite/src/reducers/store.ts [hunk 3]
```diff
@@ -124,9 +125,13 @@ type RootReducerShape = typeof rootReducer;
 type PreloadedState = Partial<AppState>;
 type InferredAction = Parameters<RootReducerShape>[1];
 
-export const initStore = <E extends Partial<ExtraDependencies>>(
-    preloadStoreAction?: PreloadStoreAction,
-    options: { statePatch?: Record<string, any>; additionalExtraDeps?: E } = {},
+export const initStore = <
+    E extends Partial<Omit<ExtraDependencies, 'services'>> & {
```
Comment (peter-sanderson) [inline packages/suite/src/reducers/store.ts]: witf is this?

File: packages/suite/src/actions/wallet/__tests__/publicKeyActions.test.ts [hunk 4]
```diff
@@ -104,7 +104,7 @@ describe('PublicKeyActions', () => {
             setTrezorConnectFixtures(f.mocks);
             const store = initStore(f.initialState);
             await store.dispatch(connectInitThunk());
-            await store.dispatch(f.action());
+            await store.dispatch(f.action() as ThunkAction<any, any, any, any>);
```
Comment (peter-sanderson) [inline packages/suite/src/actions/wallet/__tests__/publicKeyActions.test.ts]: this shall not be needed, somehting is broken if you need this

Happened to me as well sometime. Deleting `.nx` cached helped me I think

File: packages/suite/src/reducers/store.ts (hunk 3 above)
Comment (vojtatranta) [reply packages/suite/src/reducers/store.ts]: Idea: you can override any Extra deps, plus any key of the `extra.services` which you specify here. Without `Omit` it requires all keys in `services`.

Comment (peter-sanderson) [reply packages/suite/src/reducers/store.ts]: image

File: suite-common/suite-sync-types/src/storageFlusher.ts (hunk 2 above)
Comment (vojtatranta) [reply suite-common/suite-sync-types/src/storageFlusher.ts]: but it shoudl be `FlushSuiteSyncStorage`

File: packages/suite/src/reducers/store.ts [hunk 5]
```diff
@@ -146,7 +151,12 @@ export const initStore = <E extends Partial<ExtraDependencies>>(
     const extraFactory = (api: MiddlewareAPI) => ({
         ...extraDependencies,
         ...(options.additionalExtraDeps || {}),
-        services: createSuiteCompositionRoot(api),
+        services: {
+            ...createSuiteCompositionRoot({
+                ...api,
+                ...options.additionalExtraDeps.services,
```
Comment (peter-sanderson) [inline packages/suite/src/reducers/store.ts]: This is baaaaaad. We need separate Web/Desktop composition root.

Comment (vojtatranta) [reply packages/suite/src/reducers/store.ts]: no jo furt :D

File: packages/suite-desktop-core/src/app.ts (hunk 1 above)
Comment (Lemonexe) [reply packages/suite-desktop-core/src/app.ts:324]: Yes, using mainWindowProxy instance sounds good to me 👍 

We don't alow other electron window instances than the main one with our Trezor Suite renderer process, but we can't rely on it, so it's good to limit the API only to main window instance.

File: packages/suite/src/actions/wallet/__tests__/publicKeyActions.test.ts (hunk 4 above)
Comment (vojtatranta) [reply packages/suite/src/actions/wallet/__tests__/publicKeyActions.test.ts]: okay, will try

**Comment by vojtatranta** [comment]
Tested:
- desktop
- web
- native

Refreshes

File: packages/suite/src/support/extraDependencies.ts [hunk 6]
```diff
@@ -94,10 +95,12 @@ export const createSuiteRouterHistory = ({
         ),
 });
 
-type SuiteAppDeps = {
+export type StoreAPIDep = {
     getState: () => any;
-    dispatch: any;
-} & HistoryDep;
+    dispatch: (arg1: any) => any;
```
Comment (peter-sanderson) [inline packages/suite/src/support/extraDependencies.ts]: why arg1? can be just `_`?

Comment (peter-sanderson) [reply packages/suite/src/support/extraDependencies.ts]: or `param` ow whatever?

**Review by peter-sanderson — APPROVED** [review]
just nits, but please address that weird `<any, any...> in tests

File: packages/suite/src/support/extraDependencies.ts (hunk 6 above)
Comment (vojtatranta) [reply packages/suite/src/support/extraDependencies.ts]: fxd

**Comment by vojtatranta** [comment]
> just nits, but please address that weird `<any, any...> in tests

fxd NX kokotina
