### PR TITLE
fix(suite): cardano update provider staking in a nutshell modal

### LINKED ISSUE #22749: Cardano staking - change text of staking in nutshell for update provider
When user sees this screen during "update provider" flow change texts for him according to this [spec](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Staking--Final-?node-id=3272-41894&t=SeOE0CIX7ygYBOV3-4).

Change `Staking in nutshell` modal (when opened from Update provider) and also `Update provider` modal

# Now
Image

Image

# Proposal

Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Changed text in Cardano Staking in a nutshell modal for update provider flow. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22749

## Screenshots:
image
image

### CODE REVIEW

File: packages/suite/src/components/suite/StakingProcess/StakingInfo.tsx [hunk 1]
```diff
@@ -108,10 +133,12 @@ export const StakingInfo = ({ isExpanded }: StakingInfoProps) => {
     if (!account) return null;
 
     const daysToAddToPoolInitial = getDaysToAddToPoolInitial(validatorsQueue);
+    const isCardanoUpdateProviderFlow = isUpdateProviderFlow(account);
     const infoRowsData = getInfoRowsData(
         account.networkType,
         account.symbol,
         daysToAddToPoolInitial,
+        isCardanoUpdateProviderFlow,
```
Comment (tomasklim) [inline packages/suite/src/components/suite/StakingProcess/StakingInfo.tsx]: pass account and resolve `isUpdateProviderFlow` inside

File: suite-common/wallet-utils/src/cardanoStakingUtils.ts [hunk 2]
```diff
@@ -26,6 +26,14 @@ export const isCardanoStakedWithEverstake = (account: Account) => {
     return account?.misc.staking.poolId === CARDANO_EVERSTAKE_STAKING_POOL.bech32;
 };
 
+export const isUpdateProviderFlow = (account?: Account) => {
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/cardanoStakingUtils.ts]:
```suggestion
export const isCardanoUpdateProviderFlow = (account?: Account) => {
```

File: packages/suite/src/components/suite/StakingProcess/StakingInfo.tsx (hunk 1 above)
Comment (dev-pvl) [reply packages/suite/src/components/suite/StakingProcess/StakingInfo.tsx]: done, https://github.com/trezor/trezor-suite/pull/22801/commits/6984d270350d7eb4c5f2fee5bebe37387c5f3943

File: suite-common/wallet-utils/src/cardanoStakingUtils.ts (hunk 2 above)
Comment (dev-pvl) [reply suite-common/wallet-utils/src/cardanoStakingUtils.ts]: https://github.com/trezor/trezor-suite/pull/22801/commits/6984d270350d7eb4c5f2fee5bebe37387c5f3943

**Review by tomasklim — APPROVED** [review]
👍 Please rebase and squash
