### PR TITLE
fix(suite): use correct btc unit in trade

### LINKED ISSUE #20743: Wrong BTC units in trade
**Describe the bug**
When stepping back in trading settings, the Bitcoin unit reverts to BTC even if it was previously set to sats.

https://github.com/user-attachments/assets/251dac26-c4a7-4cb8-814d-7838e2b1dfa1

**Info:**
 - Suite version: web 25.9.0 (8b8f5634218edbc692f6978d64bde132d759bb08)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.10 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

This PR fixes an issue where Bitcoin unit would be changed to `BTC` even when set to `sats` in settings.

The root cause was the `shouldUseTradingAccountKey` value, it didn't correctly work when going between swap <-> offers

## Related Issue

Resolve #20743

## Screenshots:
| Before | After |
| ------ | ----- |
| <video src="https://github.com/user-attachments/assets/6dfb590c-c7e0-4b27-a5d3-b8b8a211b5bc" width="300" controls></video> | <video src="https://github.com/user-attachments/assets/329ff38e-dc57-4969-b691-0fe7baabfeb7" width="300" controls></video> |

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/wrong-btc-units-in-trade&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/wrong-btc-units-in-trade&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ export const useTradingExchangeForm = ({
     pageType = 'form',
 }: UseTradingFormProps): TradingExchangeFormContextProps => {
     const type = 'exchange';
-    const isNotFormPage = pageType !== 'form';
+    const isFormPage = pageType === 'form';
```
Comment (adderpositive) [inline packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts:79]: :face_with_spiral_eyes:

**Review by adderpositive — APPROVED** [review]

**Review by izmy — APPROVED** [review]
