### PR TITLE
fix(suite): device connected tooltip appearing when it shouldn't

### LINKED ISSUE #22302: Device connected tooltip
**Describe the bug**
"trezor connected" tooltip opens when it shouldn't:
- first device connected and automatically selected
- a device connected that corresponds to the selected remembered wallet

**How to reproduce**

1. open fresh suite
2. connect a device
3. tooltip opens

**Expected behavior**
The tooltip should appear **only** if you connect a device **other** than the one you have selected, if there's any selected.

**Screenshots**

Image

**Additional context**

Copying here the history if this issue for context:

Note that if we remove this tooltip completely, we get a problem: you have rememberd wallet open, you connect a device other than the selected wallet, and nothing happens, you still see the irrelevant remembered wallet which is confusing to users (we actually got some user reports in 25.7.x)
Connecting a device via cable is an act of will by the user, and Suite should somehow reflect it, as per [#20158](https://github.com/trezor/trezor-suite/issues/20158):
- Selecting it automatically is (probably) too aggresive
  - mobile does this though
- Opening device switcher is also quite intrusive
  - I did that [#20556](https://github.com/trezor/trezor-suite/pull/20556) for 25.8.x
  - but it causes a truckload of bugs in BT / THP, so instead we did:
- Showing an interactive tooltip as per issue [#20742](https://github.com/trezor/trezor-suite/issues/20742)
  - I did that in [#20997](https://github.com/trezor/trezor-suite/pull/20997) for 25.9.x

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Do not show tooltip for a connecting device if it's the first device (selectedDevice undefined), or a physical device matching a currently selected remembered wallet

## Related Issue

Resolve #22302

## Screenshots

[Before: new device.webm](https://github.com/user-attachments/assets/6a965f7f-f9b3-42d0-bdd7-e0cbb68007a8)
[Before: reconnect remembered.webm](https://github.com/user-attachments/assets/04fdc62d-80cc-464a-8bb6-9019044a3005)
[After: : new device.webm](https://github.com/user-attachments/assets/774a4a05-78d4-4f43-9849-0accf2e4fcf6)
[After: reconnect remembered + connect a different one.webm](https://github.com/user-attachments/assets/6e5d5e05-c633-4ae3-ad6d-1266f560bfb9)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/device-connected-tooltip&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/device-connected-tooltip&lookback=7)

### CODE REVIEW

**Comment by Lemonexe** [comment]
Will merge despite failing `onboarding/t1b1/t1b1-create-wallet.test.ts` which [is confirmed broken](https://satoshilabs.slack.com/archives/CKYFBT2C9/p1759920907960019?thread_ts=1759758958.652489&cid=CKYFBT2C9)

File: packages/suite/src/actions/wallet/markDeviceAsRecentlyConnectedThunk.ts [hunk 1]
```diff
@@ -12,6 +12,13 @@ const RECENTLY_CONNECTED_DEVICE_TIMEOUT = 5_000;
 export const markDeviceAsRecentlyConnectedThunk = createThunk<void, Device, void>(
     `${DEVICE_MODULE_PREFIX}/handleDeviceConnect`,
     (device, { dispatch, getState }) => {
+        const selectedDevice = selectSelectedDevice(getState());
+
+        // Do not show tooltip if it's the first device (selectedDevice undefined), or a physical device matching a currently selected remembered wallet
+        if (device.path === selectedDevice?.path || device.id === selectedDevice?.id) {
```
Comment (peter-sanderson) [inline packages/suite/src/actions/wallet/markDeviceAsRecentlyConnectedThunk.ts]: `markDeviceAsRecentlyConnectedThunk` has a testfile, :pray: add a test case for this

Comment (Lemonexe) [reply packages/suite/src/actions/wallet/markDeviceAsRecentlyConnectedThunk.ts]: ah, thanks. I assumed they were there because I originally wrote them, but I see that 533dcd3f1dec8c77089a095ace0124e0cbb9dae5 split the thunk functionality into different thunks, so the test cases diseappeared.
I readded it :heavy_check_mark:

Comment (Lemonexe) [reply packages/suite/src/actions/wallet/markDeviceAsRecentlyConnectedThunk.ts]: And also the test that I relied on, but wasn't there, caught the missing `=== undefined` so thanks a lot :pray:

**Review by peter-sanderson — APPROVED** [review]
