### PR TITLE
fix(transactions): search optimization and incorrect pagination display for coin

### LINKED ISSUE #3376: Transaction history - Typing into the search input during discovery crashes render (aka White Screen of Death)
**Describe the bug**
Typing into the Transaction history search input crashes the render process; I am unable to determine what exactly does it. Also, none of the typed characters are displayed.

**Info:**
 - Suite Version: app 21.2.1 20f555fc
 - OS: macOS Big Sur 11.2
 - Firmware Version: model T 2.3.5 ffa96205f

**Steps to reproduce:**
1. Add a hidden wallet with a long tx history,
2. Navigate to an account's transaction history aka Overview screen,
3. Start immediately typing a long string of characters into the search input **during discovery,**
4. Observe.

**Expected result:**
Terminal displayes a Render process gone (reason: crashed) error and the Suite windows goes completely white.

**Actual result:**
Search input behaves as intended.

**Logs:**
[macos_log_search-crash.txt](https://github.com/trezor/trezor-suite/files/5958085/macos_log_search-crash.txt)
[macos_log_search-crash2.txt](https://github.com/trezor/trezor-suite/files/5958086/macos_log_search-crash2.txt)

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by keraf**
This addresses #3376 by reworking on the fetch all logic when searching. And it also fixes an issue with the wrong pagination being displayed.

### CODE REVIEW

File: packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx [hunk 1]
```diff
@@ -116,6 +116,8 @@ const TransactionList = ({ transactions, isLoading, account, ...props }: Props)
     const isRipple = account.networkType === 'ripple';
     const showPagination = isRipple ? shouldShowRipplePagination : total > 1;
 
+    console.log(showPagination, isRipple, size, total);
```
Comment (tomexx) [inline packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx]: remove log

Comment (keraf) [reply packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx]: Ugh, keep forgetting these logs :sweat_smile: We should probably add that to our linting rules.

**Review by tomexx — APPROVED** [review]

File: packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx (hunk 1 above)
Comment (keraf) [reply packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx]: Addressed (& squashed) in 5338b4a
