### PR TITLE
fix(suite-native): discovery after killing coin enabling init

### LINKED ISSUE #22180: Stuck on loading dashboard after killing coin enabling init
**How to reproduce**

1. Go through TS7 connection and THP after wiping app
2. On coin enabling init, kill the app and reopen
3. You are now stuck on loading dashboard without coin enabling being offered again

**Expected behavior**
Coin enabling will be offered again, either after estabilishing THP connection or straight away.

### PR DESCRIPTION
**Pull request by juriczech**
## Description
- If user kills the app on coin enabling init before submitting the form, the connected device is remembered so we don't do the connection navigation, however coin enabling is not finished 🤷 😮 

This is an edge case, but in this case, we actually want to trigger the connection navigation, so we can run discovery. 

Resolve https://github.com/trezor/trezor-suite/issues/22180

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/broken-discovery-after-killing-app-on-coin-enabling&lookback=7)

### CODE REVIEW

**Comment by juriczech** [comment]
Ad: The dashboard will still show the loading while acquiring the device (estabilishing thp connection), but that is not scope of this bug fix and there's an [issue](https://github.com/trezor/trezor-suite/issues/21812) for it already. The fix only unblocks the user automatically while still not being perfect solution.

File: suite-native/device/src/middlewares/deviceConnectionMiddleware.ts [hunk 1]
```diff
@@ -161,7 +161,7 @@ deviceConnectionMiddleware.startListening({
         const isDeviceRemembered =
             !!device.features && selectDevices(getOriginalState()).some(d => d.id === device.id);
 
-        if (isDeviceRemembered) return;
+        if (isDeviceRemembered && selectIsCoinEnablingInitFinished(getState())) return;
```
Comment (yanascz) [inline suite-native/device/src/middlewares/deviceConnectionMiddleware.ts]: Please extract `selectIsCoinEnablingInitFinished(getState())` into a constant, it's also used on line 168.

Comment (juriczech) [reply suite-native/device/src/middlewares/deviceConnectionMiddleware.ts]: Fixed

**Review by yanascz — APPROVED** [review]

**Comment by juriczech** [comment]
Failing test passing locally. Merging.
