### PR TITLE
fix(suite): add legacy labeling disabled tooltip

### LINKED ISSUE #26497: Add tooltip to disabled Legacy labeling option in Settings
## Summary
In Settings > Application > Labeling, the "Legacy" variant option is disabled when no Trezor device is connected. There is no indication to the user why it's disabled or how to enable it. A tooltip should be added to guide the user.

## Expected Behavior
When hovering over the disabled "Legacy" option, a tooltip should appear with the text:
> Connect your Trezor to switch to Legacy labeling

Image

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/26497

image

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=tooltip-disabled-labeling&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=tooltip-disabled-labeling&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 13 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-14T13:52:31.794Z • 13 test(s) total_

<details><summary>Trezor Suite (desktop) — 12 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Global receive and send,Global receive" | 🙋 manual |
| Bridge > App acquired device, EXTERNAL bridge is restarted, app reconnects | 🤖 auto |
| Bridge > App spawns bundled bridge and stops it after app quit | 🤖 auto |
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Onboarding - create wallet > Success (basic) | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-14T13:49:57.371Z • 12 test(s) total_

### CODE REVIEW

File: packages/components/src/components/form/Select/customComponents.tsx [hunk 1]
```diff
@@ -190,23 +192,29 @@ export const Option = ({
...
-                    typographyStyle={mapSizeToTypographyStyle(size)}
-                    isDisabled={props.isDisabled}
+                <Box
+                    borderRadius={8}
+                    backgroundColor={
+                        props.isFocused && !props.isDisabled ? 'elementFillGhostHovered' : undefined
+                    }
+                    cursor={props.isDisabled ? 'default' : 'pointer'}
+                    padding={{ vertical: 6, horizontal: 8 }}
                 >
```
Comment (jvaclavik) [inline packages/components/src/components/form/Select/customComponents.tsx]: This looks hacky, why do you need to change background etc.?

Comment (matejkriz) [reply packages/components/src/components/form/Select/customComponents.tsx]: that is not a new change, the only new code is the tooltip component

**Review by matejkriz — APPROVED** [review]
Works just fine :shipit:

File: packages/components/src/components/form/Select/customComponents.tsx (hunk 1 above)
Comment (jvaclavik) [reply packages/components/src/components/form/Select/customComponents.tsx]: I missed that, thanks

**Comment by jvaclavik** [comment]
I tested it and I suggest to add icon with question mark (and help cursor) next to the "Legacy" and add tooltip directly on the icon.

**Review by seibei-iguchi — APPROVED** [review]
