### PR TITLE
fix(metadata): optimize loading

### LINKED ISSUE #2671: Action @metadata/account-loaded fired too often
It seems that every time I add a new account I see bunch of `@metadata/account-loaded` actions fired.
bug?

Screenshot 2020-10-19 at 16 47 41
Screenshot 2020-10-19 at 16 50 07

### PR DESCRIPTION
**Pull request by mroz22**
Idea to optimize excessive http requests for metadata and close #2671
The first commit (3bec66805c55b95c0ee37e2c9a67893bc656f815) contains some tests documenting how many requests were fired. The other one (e0f405455ee4a2362f03b8f1f4ac381a081729a9) contains fix.

Intentionally left one todo in there to initiate discussion :]

### CODE REVIEW

File: packages/suite/src/middlewares/suite/metadataMiddleware.ts [hunk 1]
```diff
@@ -15,11 +15,20 @@ const metadata = (api: MiddlewareAPI<Dispatch, AppState>) => (next: Dispatch) =>
     next(action);
 
     switch (action.type) {
-        case DISCOVERY.COMPLETE:
-            if (api.getState().metadata.enabled) {
+        case DISCOVERY.UPDATE: {
```
Comment (mroz22) [inline packages/suite/src/middlewares/suite/metadataMiddleware.ts]: Ideas discussed

**Comment by mroz22** [comment]
reworked as discussed with szymon some time ago

File: packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts [hunk 2]
```diff
@@ -5,8 +5,8 @@ import { rerouteMetadataToMockProvider, stubOpen } from '../../stubs/metadata';
 
 // fixture contains number of request that given provider needs go through this test scenario
 const fixtures = [
-    { provider: 'dropbox', numberOfRequests: 24 },
-    { provider: 'google', numberOfRequests: 10},
+    { provider: 'dropbox', numberOfRequests: [24, 25] },
+    { provider: 'google', numberOfRequests: [10, 12] },
```
Comment (keraf) [inline packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts:9]: What are the indexes in the `numberOfRequests` array for? A comment describing it would be helpful.

**Review by keraf — APPROVED** [review]
Looks good. Just one comment regarding test documentation.

File: packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts (hunk 2 above)
Comment (tomexx) [reply packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts:9]: or change it to an object so it self descriptive (if possible)

**Review by tomexx — CHANGES_REQUESTED** [review]

File: packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts (hunk 2 above)
Comment (mroz22) [reply packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts:9]: these are number of requests to be asserted at a certain point of time during the test. If I was able to come up with a proper name for these two points I would have certainly done it that way.

Comment (mroz22) [reply packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts:9]: and there is a comment on line 6

**Review by tomexx — APPROVED** [review]

File: packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts (hunk 2 above)
Comment (keraf) [reply packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts:9]: The comment between L96 to L99 gave me a bit more context. As @tomexx said, an object would be a bit more descriptive than an array. But that's just a nitpick.
