### PR TITLE
fix(discovery): recover discovery when connection is re-established

### LINKED ISSUE #17524: Interrupted discovery never finishes
**Describe the bug**
If you go offline during the discovery, it never finishes even if you go back online and even if you replug Trezor.

**Info:**

-   Mobile Suite Version: 25.2.1
-   OS: Android

**How to reproduce**

1. Connect Trezor to the app
1. Before discovery is finalized, go offline (flight mode)
1. Turn the internet back again
1. See error

**Expected behavior**
The discovery should continue if you go back online.

**Additional context**
The result for the user is similar to [this issue](https://github.com/trezor/trezor-suite/issues/13854), but it's a completely different problem

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

- Resuming Discovery when the internet connection is re-established

note: The fix is build upon https://github.com/trezor/trezor-suite/pull/17903 by @marekrjpolak 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17524

### Before
https://github.com/user-attachments/assets/e84355d3-fc28-4f1b-bfd7-32ba78d38135

### After
https://github.com/user-attachments/assets/046a15b2-b58b-437e-9aeb-a700239b1f49

### CODE REVIEW

**Review by marekrjpolak — APPROVED** [review]
Approve for Connect part. I haven't tested the native discovery part, but the change looks reasonable.

File: suite-native/discovery/src/discoveryThunks.ts [hunk 1]
```diff
@@ -525,9 +527,11 @@ const discoverNetworkBatchThunk = createThunk(
                     deviceState,
                     network,
                     accountType,
-                    round: round + 1,
+                    // Retry current round if discoverAccountsByDescriptorThunk fails
+                    round: error ? round : round + 1,
                 }),
             );
+            console.warn(error);
```
Comment (PeKne) [inline suite-native/discovery/src/discoveryThunks.ts:534]: Does this have any other purpose than debugging? If not, please remove it

**Review by PeKne — APPROVED** [review]
Looks good :ok_hand:

File: suite-native/discovery/src/discoveryThunks.ts (hunk 1 above)
Comment (BrantalikP) [reply suite-native/discovery/src/discoveryThunks.ts:534]: Its intentional👌

**Review by matejkriz — APPROVED** [review]
Seems to works nice 👍
