### PR TITLE
Display network name instead of symbol on tooltip

### LINKED ISSUE #16166: Change filter tooltip from network symbol to network name
**Describe the bug**

Users can be confused what does `BSC`, `OP`, `ARB` mean. Let's use network symbol on hover or nothing?

Screenshot 2025-01-04 at 13 01 09

### PR DESCRIPTION
**Pull request by enjojoy**
## Description

Refactor variables names for more precise naming and display network name instead of symbol

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16166

## Screenshots:
Screenshot 2025-01-06 at 14 37 21
Screenshot 2025-01-06 at 14 37 48
Screenshot 2025-01-06 at 14 38 14

### CODE REVIEW

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx [hunk 1]
```diff
@@ -46,13 +47,15 @@ export const CoinsFilter = () => {
     const enabledNetworks = useSelector(selectEnabledNetworks);
     const { supportedMainnets, supportedTestnets } = useNetworkSupport();
 
-    const supportedNetworks = [...supportedMainnets, ...supportedTestnets].map(
+    const supportedNetworksSymbols = [...supportedMainnets, ...supportedTestnets].map(
         network => network.symbol,
     );
 
-    const availableNetworks = enabledNetworks.filter(symbol => supportedNetworks.includes(symbol));
+    const availableNetworksSymbols = enabledNetworks.filter(symbol =>
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx]: nit:
```suggestion
    const availableNetworkSymbols = enabledNetworks.filter(symbol =>
```

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx [hunk 2]
```diff
@@ -83,27 +86,27 @@ export const CoinsFilter = () => {
             }}
         >
             <AnimatePresence initial={false}>
-                {availableNetworks.map(network => {
-                    const isSelected = coinFilter === network;
+                {availableNetworksSymbols.map(symbol => {
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx]: nit:
```suggestion
                {availableNetworksSymbols.map(networkSymbol => {
```

**Review by tomasklim — APPROVED** [review]
