### PR TITLE
fix(coinmarket): anonymize amounts in DCA

### LINKED ISSUE #6964: DCA - amounts not anonymized
Please anonymize all amounts (in BTC and FIAT)

Screenshot 2022-11-20 at 17 40 28

### PR DESCRIPTION
**Pull request by LukasRada**
## Description

The change consist in usage of `HiddenPlaceholder` component on right places.

## Related Issue

Fixes #6964

## Screenshots:
Correct:
image

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ const Right = styled.div`
     flex-direction: column;
 `;
 
-const Fiat = styled.div`
+const Fiat = styled(HiddenPlaceholder)`
```
Comment (dahaca) [inline packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: how about just using the `FiatValue` component here instead?

Comment (LukasRada) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: Would like to but `FiatValue` uses default `FiatAmountFormatter` without posibillity to override `maximumFractionDigits` and `minimumFractionDigits`. Suggestions?

Comment (dahaca) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: Isn't it used [here](https://github.com/trezor/trezor-suite/pull/7017/files#diff-d6e657270272496547a315b71f9183f9c261f13cb554c4557d8192505c4d325eR59) anyways? 🤔

Comment (LukasRada) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: Component `FiatValue` is not used in mentioned [changes](https://github.com/trezor/trezor-suite/pull/7017/files#diff-d6e657270272496547a315b71f9183f9c261f13cb554c4557d8192505c4d325eR59).

Comment (LukasRada) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: Or what do you mean by "it"?

Comment (dahaca) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: I mean the `FiatAmountFormatter`

Comment (LukasRada) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: The fix to resolve this issue is to use such component which hides/anonymizes the amount. It is OK to use `FiatValue` to solve this issue, but since there is a need to use custom `FiatAmountFormatter` the added value of using `FiatValue` is gone because `FiatValue`does not render `HiddenPlaceholder` when there is need to render children components.

Yes, there is solution like this:

```
                                <FiatValue
                                    amount={savingsTrade.fiatStringAmount || '0'}
                                    symbol={symbol}
                                    fiatCurrency={savingsTrade.fiatCurrency?.toLowerCase()}
                                >
                                    {() => (
                                        <FiatPaymentWrapper>
                                            <FiatAmountFormatter
                                                value={savingsTrade.fiatStringAmount || '0'}
                                                currency={savingsTrade.fiatCurrency}
                                                maximumFractionDigits={2}
                                                minimumFractionDigits={0}
                                            />
                                        </FiatPaymentWrapper>
                                    )}
                                </FiatValue>
```
Where `FiatPaymentWrapper` is actually styled `HiddenPlaceholder`. Do we really want this? I really do not see the solution while using `FiatValue` and `FiatAmountFormatter` and `HiddenPlaceholder` together. Please advise. We can also arrange call. (Looks like my React skills are poorer as I did not implement a thing in React in weeks [😅](https://emojipedia.org/grinning-face-with-sweat/))

Comment (dahaca) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: I realized I had an incorrect link in my previous comment. I mean that the plain `FiatAmountFormatter` is used in this [Summary component](https://github.com/trezor/trezor-suite/blob/fc002ae043dd16eae7988e7e3302728b54842182/packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx#L59). I am not sure where a _custom formatter_ is used, maybe I am missing something? And I think that `FiatValue` does [render](https://github.com/trezor/trezor-suite/blob/fc002ae043dd16eae7988e7e3302728b54842182/packages/suite/src/components/suite/FiatValue.tsx#L85) the `HiddenPlaceholder` unless it's explicitly disabled.

Comment (LukasRada) [reply packages/suite/src/views/wallet/coinmarket/savings/setup/components/Summary/index.tsx]: All clear after our call, thanks :)

File: packages/suite/src/views/wallet/coinmarket/savings/overview/index.tsx [hunk 2]
```diff
@@ -18,7 +22,7 @@ import {
 import type { PaymentFrequency, SavingsKYCStatus, SavingsTrade } from 'invity-api';
 import { WaitingForFirstPayment } from './components/WaitingForFirstPayment';
 import { darken } from 'polished';
-import { NetworkSymbol } from '@wallet-types';
+import type { Account, NetworkSymbol } from '@wallet-types';
```
Comment (dahaca) [inline packages/suite/src/views/wallet/coinmarket/savings/overview/index.tsx:25]: nit: out team agreed that `type` is not necessary anymore. you can read about it in our [style guide](https://www.notion.so/satoshilabs/Imports-exports-83240c38173e4ace82c84ee9668814c1)

File: packages/suite/src/views/wallet/coinmarket/savings/overview/index.tsx [hunk 3]
```diff
@@ -162,9 +165,11 @@ function renderSavingsStatus(
...
                     <Fiat>
                         ≈&nbsp;
-                        <FiatAmountFormatter
-                            currency={savingsTrade.fiatCurrency}
-                            value={savingsFiatSum}
+                        <FiatValue
+                            shouldConvert={false}
+                            fiatCurrency={savingsTrade.fiatCurrency?.toLowerCase()}
+                            amount={savingsFiatSum}
+                            symbol={symbol}
```
Comment (dahaca) [inline packages/suite/src/views/wallet/coinmarket/savings/overview/index.tsx:172]: if `shouldConvert={false}` then you don't need the `symbol` do you?

Comment (dahaca) [reply packages/suite/src/views/wallet/coinmarket/savings/overview/index.tsx:172]: I see, it's required in props and I could come up with a simple solution to make it non-required based on `shouldConvert` :\

**Review by dahaca — APPROVED** [review]
