### PR TITLE
fix(ipc-proxy): IPC response handling when rendered was destroyed

### LINKED ISSUE #19670: Error: Render frame was disposed before WebFrameMain could be accessed
## Description

This issue is occuring on desktop, probably when a user is closing Suite.

## Sentry details

Sentry Issue: [TREZOR-SUITE-122G](https://satoshilabs.sentry.io/issues/6249152375/?referrer=github_integration)

Duplicated Sentry Issue:  [TREZOR-SUITE-13BW](https://satoshilabs.sentry.io/issues/6532292593/events/96b05f50329d43d4b066099563adb3ee/?project=5193825)

```
Error: Render frame was disposed before WebFrameMain could be accessed
  File "@trezor/suite-desktop-core/../ipc-proxy/src/proxy-handler.ts", line 105, in emit
    reply(ipcEventName, payload);
  File "@trezor/suite-desktop-core/../connect/src/index.ts", line 88, in onCoreEvent
    eventEmitter.emit(event, message);
  File "@trezor/suite-desktop-core/../connect/src/core/index.ts", line 1064, in Core.sendCoreMessage
    this.emit(CORE_EVENT, message);
  File "@trezor/suite-desktop-core/../connect/src/backend/Blockchain.ts", line 223, in f.?
    this.postMessage(
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Lemonexe**
https://github.com/electron/electron/blob/3536d49/docs/api/structures/ipc-main-event.md
https://github.com/electron/electron/blob/3536d49/docs/breaking-changes.md#behavior-changed-frame-properties-may-retrieve-detached-webframemain-instances-or-none-at-all

## Related Issue

Resolve #19670

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/ipc-when-rendered-destroyed&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/ipc-when-rendered-destroyed&lookback=7)

### CODE REVIEW

File: packages/ipc-proxy/src/proxy-handler.ts [hunk 1]
```diff
@@ -102,6 +102,12 @@ export const createIpcProxyHandler = <Api extends EventEmitterApi>(
                     debug?.info(SERVICE_NAME, `Adding listener ${realEventName}`);
                     onAddListener(realEventName, (...payload: any[]) => {
                         debug?.info(SERVICE_NAME, `Emit ${realEventName} as ${ipcEventName}`);
+
+                        // prevents 'Render frame was disposed before WebFrameMain could be accessed', occurring when renderer process is closed during responding
```
Comment (Lemonexe) [inline packages/ipc-proxy/src/proxy-handler.ts:106]: well, hopefully :upside_down_face: 
I understand the issue, but not if this is the right place to fix, because of the complexity of `ipc-proxy`
Ideas?

**Review by komret — APPROVED** [review]
