### PR TITLE
fix(suite-native): redirect unacquired devices with THP correctly

### LINKED ISSUE #21690: App fails to detect initialized Trezor over BT
**Info:**
- Suite Version: `6bc05ed`
- System: iOS
- Model: iPhone SE (2nd generation)
- Firmware Version: 2.9.2.5

**How to reproduce**

1. Grab initialized Trezor
2. Connect it via BT to mobile
3. 🔴 See screen with option to `create` or `recover` wallet → App should recognize that Trezor already has a seed
4. 🔴 Than I have to cancel this setup and manually activate passphrase
5. 🔴 Discovery doesn't work → I get screen with `Your wallet is empty` (_I have to add coins manually_)

Video in [Slack](https://satoshilabs.slack.com/archives/C082Q0Y6WP3/p1758284254001609?thread_ts=1758284236.742099&cid=C082Q0Y6WP3)

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21690

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/prevent-onboarding-redirect-for-initialized-trezor&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/prevent-onboarding-redirect-for-initialized-trezor&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/prevent-onboarding-redirect-for-initialized-trezor&lookback=7)

### CODE REVIEW

File: suite-common/suite-utils/src/device.ts [hunk 1]
```diff
@@ -463,3 +471,15 @@ export const getDeviceColorVariant = (
...
 ): device is T & { thp: ThpStateSerialized } => device.thp !== undefined;
+
+export const getIsDeviceInitialized = ({
+    deviceMode,
+    deviceFeatures,
+}: {
+    deviceMode?: DeviceMode | null;
+    deviceFeatures?: PROTO.Features;
+}) => {
+    if (deviceMode === 'initialize' || deviceMode === 'seedless') return false;
```
Comment (matejkriz) [inline suite-common/suite-utils/src/device.ts]: FYI `seedless` is initialized but doesn't matter much, I guess it's not really used

Comment (juriczech) [reply suite-common/suite-utils/src/device.ts]: Would you like me to change it? I kept it to maintain same API and reduce workload for testing etc. as we need to move with this quickly. But if it's something QA can test easily, I'm happy to fix the condition.

File: suite-common/suite-utils/src/device.ts [hunk 2]
```diff
@@ -459,3 +467,23 @@ export const getDeviceInternalModel = (
 export const isThpDevice = <T extends Device | TrezorDevice>(
     device: T,
 ): device is T & { thp: ThpStateSerialized } => device.thp !== undefined;
+
+export const getIsDeviceInitialized = ({
+    deviceMode,
+    deviceFeatures,
+}: {
```
Comment (peter-sanderson) [inline suite-common/suite-utils/src/device.ts:474]: nit: export to type (I kinda feel, we are doing that everywhere, probably not rule, but kind of a habit)

File: suite-common/suite-utils/src/device.ts [hunk 3]
```diff
@@ -459,3 +467,23 @@ export const getDeviceInternalModel = (
...
+    deviceMode?: DeviceMode | null;
+    deviceFeatures?: PROTO.Features;
+}) => {
+    if (deviceMode === 'initialize' || deviceMode === 'seedless') return false;
+
+    return !!deviceFeatures?.initialized;
```
Comment (peter-sanderson) [inline suite-common/suite-utils/src/device.ts]: nit

```suggestion
    return deviceMode !== 'initialize' && deviceMode !== 'seedless' && deviceFeatures?.initialized === true
```

File: suite-native/device/src/utils.ts [hunk 4]
```diff
@@ -42,7 +38,9 @@ export const isDeviceEventAction = <T extends DeviceEvent['type']>(
     actionType: T,
 ): action is { type: T; payload: Device } => action.type === actionType;
 
-export const isDeviceSetupSupported = (model: DeviceModelInternal) => {
+export const getIsDeviceSetupSupported = (model: DeviceModelInternal | null) => {
+    if (G.isNullable(model)) return false;
+
```
Comment (yanascz) [inline suite-native/device/src/utils.ts]: I believe this may be reverted as `getDeviceInternalModel` has `DeviceModelInternal.UNKNOWN` as fallback.

And `model ?? DeviceModelInternal.UNKNOWN` can be used in `selectIsDeviceSetupSupported`.

The reason is that it's better to pass non-null values around.

File: suite-common/suite-utils/src/device.ts (hunk 2 above)
Comment (juriczech) [reply suite-common/suite-utils/src/device.ts:474]: I feel like sometimes it makes sense, mainly if its more than 2, but I wouldn't make it a hard rule maybe? In this case, I don't mind it here. In the end, every function would have a type above and then you have to structure it in a types file etc. Sometimes makes sense and I used to hate this too, but I am fine with this and think it depends on personal preference. Maybe others can chip in with their opinions if it makes sense to extract type 🤔

File: suite-common/suite-utils/src/device.ts (hunk 3 above)
Comment (juriczech) [reply suite-common/suite-utils/src/device.ts]: https://github.com/trezor/trezor-suite/pull/21697/commits/a70dd20e99b609e2b1e8f1f1dd071e631baa2cce

File: suite-native/device/src/utils.ts (hunk 4 above)
Comment (juriczech) [reply suite-native/device/src/utils.ts]: https://github.com/trezor/trezor-suite/pull/21697/commits/a70dd20e99b609e2b1e8f1f1dd071e631baa2cce

File: suite-native/device/src/utils.ts [hunk 5]
```diff
@@ -42,7 +38,7 @@ export const isDeviceEventAction = <T extends DeviceEvent['type']>(
     actionType: T,
 ): action is { type: T; payload: Device } => action.type === actionType;
 
-export const isDeviceSetupSupported = (model: DeviceModelInternal) => {
+export const getIsDeviceSetupSupported = (model: DeviceModelInternal) => {
```
Comment (yanascz) [inline suite-native/device/src/utils.ts:41]: I'd keep the original name if possible to stay consistent with other functions in this file.
```suggestion
export const isDeviceSetupSupported = (model: DeviceModelInternal) => {
```

**Review by yanascz — APPROVED** [review]
One nit but otherwise I like! 🚢🇮🇹

File: suite-native/device/src/utils.ts (hunk 5 above)
Comment (juriczech) [reply suite-native/device/src/utils.ts:41]: I'd actually prefer to prefix functions with `getSomething` in general. Most functions in common are prefixed this way so we don't have a repository consistency sadly so if you don't have a strong opinion on this, I'd prefer to keep this.

File: suite-common/suite-utils/src/device.ts (hunk 1 above)
Comment (matejkriz) [reply suite-common/suite-utils/src/device.ts]: It was really just FYI, no need to change it now of course.
