### PR TITLE
fix(staking): zero amounts when bumping fee

### LINKED ISSUE #13397: Deduplicate data info during bumping fee in review tx modal
When bumping fee on staking/unstaking/claiming, the info about action is shown twice and it should not

Something should probably be modified in `TransactionReviewOutput.tsx`

Image

Image

### LINKED ISSUE #13752: Zero amounts when bumping fee of unstaking and claiming txs
**Description**
- the amount of unstaking and claiming is indeed zero but let's fix it

**Current**
Image

**Desired state**
- please check how it is done for regular unstaking/claiming tx that the amount is there. Maybe it is somehow hacked.
- I am thinking about parsing it from data in tx review modal in case it is staking type tx
- If you introduce this parsing from data. It would be nice to do it also for regular unstaking/claiming and remove hacky current solution.

Unstake:
Image

Bump unstake:
Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description
- no satoshi methods for non-bitcoin
- resolves zero amount issue when bumping fee during the unstake flow (proving amount)
- resolves zero amount issue when bumping fee during the claim flow (hiding amount)
- hide double label when bumping staking txs
- hide 0 amount in left panel in tx review modal. Applies for claim bump and approve token swap tx

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13752
Resolve [#13397](https://github.com/trezor/trezor-suite/issues/13397)

## Screenshots:
bump-fee-zero-amount
Screenshot 2024-11-03 at 16 07 12
Screenshot 2024-11-03 at 16 06 06

### CODE REVIEW

**Review by tomasklim — APPROVED** [review]

**Review by tomasklim — CHANGES_REQUESTED** [review]
Removing approve as in claiming tx, the amount is still `0`

**Comment by dev-pvl** [comment]
this fixup https://github.com/trezor/trezor-suite/pull/15030/commits/20908786802b9649329fd971259fff5f36ae3f79 hides zero amount for bump txs when claiming as was agreed

**Comment by omykhailovskyi** [comment]
Hey, @tomasklim 
Any update on that?

**Comment by tomasklim** [comment]
@omykhailovskyi don't worry, the last commit is quite a big change and I wanted to go through really carefully

**Review by tomasklim — APPROVED** [review]
Approving but waiting for also approve from somebody else as most of the commit are mine

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 1]
```diff
@@ -362,7 +362,7 @@ export const formatAmount = (amount: BigNumberValue, decimals: number) => {
     }
 };
 
-export const amountToSatoshi = (amount: BigNumberValue, decimals: number) => {
+export const formatAmountWithDecimals = (amount: BigNumberValue, decimals: number) => {
```
Comment (martykan) [inline suite-common/wallet-utils/src/accountUtils.ts]: Just a nitpick, but I think the new name makes it unclear what this function does. 
It's named confusingly similarly to `formatAmount` function, but it does the opposite thing.
So maybe `amountToSmallestUnit` or `normalizeAmount`?

Comment (tomasklim) [reply suite-common/wallet-utils/src/accountUtils.ts]: It is clear for me, but I will rename it. np
