### PR TITLE
fix(suite-native): skip validation of irrelevant fields in fee form

### LINKED ISSUE #25244: Selecting "low" fee when sending ETH does not allow to actually send ETH on mobile
**Describe the bug**
When I want to send some ETH and select "low" fee, the app won't let me continue.

**Steps to reproduce:**
1. Connect a device
2. Navigate to ETH account
3. Try to send some ETH
4. Select the "low" fee option
5. I can click on the button but app won't let me continue in the send flow

Interestingly enough, if I click on "custom fee" and immediately quit it, it lets me continue after that.

**Info:**
 - Suite version: mobile 26.2.1 (de77445)
 - OS: Android 16

**Screenshots:**

https://github.com/user-attachments/assets/e323de32-9897-429f-a422-55afafbaac71

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

- customFeePerUnit validation check should be skipped for priority fees

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/25244

## Screenshots:

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/low-fee-eth-issue&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/low-fee-eth-issue&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/low-fee-eth-issue&lookback=7)

## 🔍 Currents Test Results

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/low-fee-eth-issue&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 2 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-09T10:32:16.907Z • 2 test(s) total_

### CODE REVIEW

File: suite-native/transaction-management/src/components/fees/CustomFee/CustomFeeInputs.tsx [hunk 1]
```diff
@@ -23,6 +27,8 @@ export const CustomFeeInputs = ({ symbol }: CustomFeeInputsProps) => {
     const feeInfo = useSelector((state: FeesRootState) =>
         selectConvertedNetworkFeeInfo(state, symbol),
     );
+
+    const isEip1559Fee = useSelector((state: FeesRootState) => selectIsEip1559Fee(state, symbol));
```
Comment (tomasklim) [inline suite-native/transaction-management/src/components/fees/CustomFee/CustomFeeInputs.tsx:31]: I think it should be enough to use `isEip1559` util. imo it is not required to check if `networkType` is `ethereum`

**Review by tomasklim — DISMISSED** [review]

File: suite-native/transaction-management/src/components/fees/CustomFee/CustomFeeInputs.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/transaction-management/src/components/fees/CustomFee/CustomFeeInputs.tsx:31]: Hmm, ok, but I would still keep the selector (the utils is used there) as we don't need to access fee levels everywhere. WDYT?

 Regarding `networkType` I can remove it from the selector since `isEip1559` already checks for `maxFeePerGas`, which should only exist on EVM anyway right?.

Comment (BrantalikP) [reply suite-native/transaction-management/src/components/fees/CustomFee/CustomFeeInputs.tsx:31]: oh, I accidentally amended the commit, but the `networkType` check is removed now :D
  https://github.com/trezor/trezor-suite/pull/25256/changes/b58c84ef030827e85da7d3ee4f9eaa427587b884#diff-ee13ffa270653f62e3d35336114e6656decb18d58554a1e715f775cfac17d656R90

Comment (tomasklim) [reply suite-native/transaction-management/src/components/fees/CustomFee/CustomFeeInputs.tsx:31]: I think access to fee levels is in each file you modified except `useCustomFee` but is it needed there?

Comment (BrantalikP) [reply suite-native/transaction-management/src/components/fees/CustomFee/CustomFeeInputs.tsx:31]: uh, sorry I forgot about this PR...
yes I need it specifically for this condition

```
  if ((!isEip1559Fee && !customFeePerUnit) || !formState) {
            console.warn('Cannot calculate custom fee because of missing values');
```

without it it would trigger the warning console log although it's not needed 🫠

**Review by matusbalascak — APPROVED** [review]
