### PR TITLE
fix(wallet-core): filter failed accounts when they are not relevant

### LINKED ISSUE #19473: non BTC coins enabled even when using BTConly device
**Describe the bug**
non BTC coins enabled even when using BTConly device.
```
Account discovery error
We were unable to discover your accounts.
```

**Steps to reproduce:**
1. Enable multiple coins
2. Connect BTC only device
3. Observe discovery errors on unsupported coins

**Info:**
 - Suite version: desktop 25.7.0 (aec67e5c3eceb5acbf7d78cc12347b524b31b8ba)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.7.0 Chrome/136.0.7103.49 Electron/36.2.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.10 bitcoin-only (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: NodeUsbTransport

**Screenshots:**

Image

Image

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Reorder the operations in `selectAllAccountsToList`:
**first** merge failed accounts into ok accounts, **then** filter all of them and sort

Previously: filter ok accounts, merge failed (which were **not** filtered) and then sort
(failed accounts not filtered by enabled && supported)

## Related Issue

Resolve #19473 (that was 95% solved by #19571, this is like the last 5% of this issue :joy:  )

## Screenshots:

Since this is the edgiest of edgecases, I reproduced the bug only "in-vitro": discover BTC and ETH [with artifically failed ETH#3 discovery](https://github.com/user-attachments/assets/bc8e90fa-1b92-417a-8962-07952230a702) and then suddenly declare that device does not support ETH.

In the wild, outside "laboratory conditions", you'd probably have to discover with universal FW and having some of them fail, remember the wallet, disconnect, at **another** Suite switch the device to BTC-only and reconnect to the remembered wallet, but idk, for me it was only sometimes reproducible :upside_down_face:   

Before: ETH#3 remains visible
in vitro reproduction

After: no ETH visible 
in vitro fix

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/filter-failed-account-by-btc-only&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/filter-failed-account-by-btc-only&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/selectors.ts [hunk 1]
```diff
@@ -33,28 +33,35 @@ const createMemoizedSelector = createWeakMapSelector.withTypes<
...
 >();
 
-export const selectDeviceAccountsVisibleEnabledAndSupported = createMemoizedSelector(
-    [selectVisibleDeviceAccounts, selectSelectedDevice, selectEnabledNetworks],
-    (accounts, device, enabledNetworks) => {
-        const deviceNetworks = selectSupportedNetworkByDevice(device);
+/**
+ * This means "all potentially visible accounts", because for accounts that failed to be discovered
+ * we don't know if they would have been visible or not (depends on discovery account.empty result).
+ */
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/selectors.ts:39]: there are countless possibilities how we could split and compose these selectors.
I decided for these two selectors as they have a sensible meaning, kind of.
Would FP fix this? No not really.

File: suite-common/wallet-core/src/selectors.ts [hunk 2]
```diff
@@ -33,28 +33,35 @@ const createMemoizedSelector = createWeakMapSelector.withTypes<
...
+
+        return returnStableArrayIfEmpty(allAccounts);
     },
 );
 
+/**
+ * Listable accounts are visible, enabled in settings, supported by the device and conventionally sorted.
+ * Edge cases: accounts failed to be discovered, or remembered accounts no longer supported by the device.
+ */
 export const selectAllAccountsToList = createMemoizedSelector(
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/selectors.ts:56]: nit: would be great to have test for this :pray:

**Review by peter-sanderson — APPROVED** [review]

File: suite-common/wallet-core/src/selectors.ts (hunk 2 above)
Comment (Lemonexe) [reply suite-common/wallet-core/src/selectors.ts:56]: it'd be great to have a test for a lot of `wallet-core`. Idk when will I be able to get to it :disappointed:
