### PR TITLE
fix(trading): prevent cross-network address contamination in swap form

### LINKED ISSUE #23875: Swap form uses wrong destination address after reconnecting device
**Describe the bug**
When preparing a swap/trade in Suite desktop (e.g., WBTC→ETH), after pre-filling the form and disconnecting then reconnecting the device, the form incorrectly inputs another address (such as BTC address) into the Ethereum "To" field.

This issue is similar to https://github.com/trezor/trezor-suite/issues/23670, but now occurs on the swap (trade) screen.

**Info:**
 - Suite version: desktop 26.1.0 (f8eb070add39e602431cf135418807604582cc35)
 - Browser: Trezor Suite 26.1.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3W1 2.9.6 universal (revision dbb7b00ce10fb7eab33fa2021c4096c623b0b146)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**How to reproduce**
1. Open Suite desktop, go to Swap (trade)
2. Pre-fill the trade form (choose e.g. WBTC→ETH, enter recipient and amounts)
3. Disconnect the hardware device
4. Reconnect the device
5. Observe: The destination address is replaced in trade data

**Expected behavior**
After reconnecting, the swap form should preserve the correct original destination address for the selected asset. Cross-asset address autofill should never occur.

**Screenshots**
Swap form with invalid address error

**Additional context**
- Related to previous bug in sending forms for DOGE/ETH (#23670)

### PR DESCRIPTION
**Pull request by sherpaPSX**
Resolves #23875

## Description
Fixes the issue where the swap form uses wrong destination address after reconnecting device. When preparing a swap/trade in Suite desktop (e.g., WBTC→ETH), after pre-filling the form and disconnecting then reconnecting the device, the form incorrectly inputs another address (such as BTC address) into the Ethereum 'To' field.

## Notes for QA
- Open the desktop app and go to Swap (trade)
- Pre-fill a trade form (e.g., WBTC→ETH with a recipient address)
- Disconnect the hardware device
- Reconnect the device
- Verify: The destination address should be preserved correctly and match the selected asset
- Cross-asset address autofill should never occur

## Related Issue
Resolves #23875

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-swap-form-destination-address&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-swap-form-destination-address&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 6 test(s)</summary>

| Test | Type |
|------|------|
| Analytics Events > Analytics captures important events when started enabled by default | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-26T07:26:54.075Z • 6 test(s) total_

<details><summary>Trezor Suite (desktop) — 6 test(s)</summary>

| Test | Type |
|------|------|
| Staking - Cardano > Stake Cardano | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |
| Firmware not ready | 🙋 manual |

</details>

_Updated: 2026-03-24T09:41:05.153Z • 6 test(s) total_

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts [hunk 1]
```diff
@@ -140,10 +141,13 @@ export const useTradingReceiveAddress = ({
...
         setSelectedAccount(undefined);
         setHasSelectionInitialized(false);
-    }, [symbol]);
+        methods.setValue('address', '', { shouldValidate: false });
+        methods.setValue('extraField', '', { shouldValidate: false });
+    }, [symbol, methods]);
 
     useEffect(() => {
         if (!sendAccountKey) return;
+        if (hasSelectionInitialized) return; // Don't override user selection
```
Comment (vytick) [inline packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts]: __nit:__ 

```suggestion
        if (!sendAccountKey || hasSelectionInitialized) {
            return; // Don't override user selection
        }
```

**Comment by vytick** [comment]
@coderabbitai review

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts [hunk 2]
```diff
@@ -161,16 +165,23 @@ export const useTradingReceiveAddress = ({
...
 
     useEffect(() => {
         if (!symbol) return;
         if (hasSelectionInitialized) return;
 
-        if (isPreviousRouteFromTradeSection && persistedReceiveAccountKey) {
+        if (persistedReceiveAccountKey) {
             const matchingAccount = suiteReceiveAccounts?.find(
-                account => account.key === persistedReceiveAccountKey,
+                account => account.key === persistedReceiveAccountKey && account.symbol === symbol,
```
Comment (vytick) [inline packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts]: Q: If the account.key is the same it should mean that even the symbol is the same, isnt it? So checking symbol should not be necessary

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts [hunk 3]
```diff
@@ -161,16 +165,23 @@ export const useTradingReceiveAddress = ({
...
+        hasSelectionInitialized,
+        type,
+        selectSuiteAccount,
+    ]);
 
     useEffect(() => {
         if (!symbol) return;
         if (hasSelectionInitialized) return;
 
-        if (isPreviousRouteFromTradeSection && persistedReceiveAccountKey) {
```
Comment (vytick) [inline packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts:178]: q: why do we ignore here `isPreviousRouteFromTradeSection` (and also elsewhere in this file)

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts [hunk 4]
```diff
@@ -180,10 +191,17 @@ export const useTradingReceiveAddress = ({
...
+                persistedReceiveAddress,
+                symbol,
+            );
 
-            return;
+            if (isValidForCurrentSymbol) {
+                selectNonSuiteAddress(persistedReceiveAddress);
+
+                return;
+            }
```
[the remark this answers is not in the document]
Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts:203]: Yes, but the `isAddressValid` fails cause on `keccak`

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts (hunk 3 above)
Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts:178]: Previously persisted receive address restoration was blocked by `isPreviousRouteFromTradeSection`, which could be false after device reconnect or navigation changes even when the persisted state was valid. Now we always consider persisted state, but we validate it with `addressValidator.validate(address, symbol)`  to prevent cross-network contamination (e.g., BTC address being used for ETH receive).

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts (hunk 2 above)
Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts]: You are right. Removed redundant condition

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts (hunk 1 above)
Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts]: Thanks, good point

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts (hunk 3 above)
Comment (vytick) [reply packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts:178]: makes sense

**Review by vytick — APPROVED** [review]
lgtm
