### PR TITLE
Restrict Select menu to use portal in modals only

### LINKED ISSUE #8907: Trading - Select/Modal z-index clash in Exchange Offers
Screenshot 2023-07-12 at 9 58 50

How to reproduce:
You need to have some amount of mainnet coins in your account or change source code so that youu are able to get to the screen. Go to Trade > Exchange > Compare offers > Get deal > Create a new account. Reported [here](https://satoshilabs.slack.com/archives/C031LD98L9K/p1688568630994659?thread_ts=1688480384.320529&cid=C031LD98L9K).

### LINKED ISSUE #8909: Select does not open when there is not enough space for menu
All Selects are broken like this. Reduce the window size or open devtools:

https://github.com/trezor/trezor-suite/assets/42465546/3ce08f0c-a642-47e3-9f40-43a674112ff3

How it works when you remove `menuPortalTarget` and `closeMenuOnScroll` from `Select`:

https://github.com/trezor/trezor-suite/assets/42465546/5fcbe975-82fa-4d45-9990-6d4008c65fdf

### PR DESCRIPTION
**Pull request by komret**
## Description

Probably better solution than #8901, plus it also fixes #8909. There is some small performance impact due to the loop, however an extra render only happens for a `Select` inside a `Modal`. Using a `RefCallback` instead of `useEffect` would also work, but it causes an extra render, so I opted for the effect.

I also removed the `closeMenuOnScroll` because it was immediately closing the menu in case the `Select` was on the bottom of the page, as demonstrated in #8909.

I changed portal `z-index` from `GUIDE_BUTTON` to `MODAL` for clarity.

## Related Issue

Resolve #8909
Resolve #8907

### CODE REVIEW

File: packages/components/src/components/Modal/index.tsx [hunk 1]
```diff
@@ -318,6 +319,7 @@ Modal.Description = Description;
 Modal.Content = Content;
 Modal.BottomBar = BottomBar;
 Modal.closeIconWidth = CLOSE_ICON_SIDE + CLOSE_ICON_PADDING;
+Modal.contentId = CONTENT_ID;
```
Comment (dahaca) [inline packages/components/src/components/Modal/index.tsx]: i'd export just `CONTENT_ID`, no need to import the whole `Modal` just for the id

File: packages/components/src/components/form/Select/index.tsx [hunk 2]
```diff
@@ -362,6 +358,27 @@ export const Select = ({
...
 
+    // Check if the select is within a modal. If so, render it inside a portal so that it can overflow the modal.
+    // The inputRef is deeply nested so we iterate with while loop until wee reach the parentElement or max depth.
+    // The depth has a limit so that it does not iterate over the entire DOM.
+    // The depth limit has a buffer of 2 iterations in case the select is wrapped. (Minimum depth is 4.)
+    useEffect(() => {
+        let parent = selectRef.current?.inputRef?.parentElement;
+        let count = 0;
+        while (parent) {
+            console.log(count);
```
Comment (dahaca) [inline packages/components/src/components/form/Select/index.tsx]: rogue `log`

File: packages/components/src/components/form/Select/index.tsx [hunk 3]
```diff
@@ -304,11 +305,6 @@ export const Select = ({
         }
     }, []);
 
-    const closeMenuOnScroll = useCallback(
```
Comment (dahaca) [inline packages/components/src/components/form/Select/index.tsx:307]: Does that mean that the dropdowns stay open when scrolling?

File: packages/components/src/components/form/Select/index.tsx (hunk 2 above)
Comment (komret) [reply packages/components/src/components/form/Select/index.tsx]: c557d28d9fc5cca7127700f6e340990cc28d8282

File: packages/components/src/components/Modal/index.tsx (hunk 1 above)
Comment (komret) [reply packages/components/src/components/Modal/index.tsx]: c557d28d9fc5cca7127700f6e340990cc28d8282

File: packages/components/src/components/form/Select/index.tsx (hunk 3 above)
Comment (komret) [reply packages/components/src/components/form/Select/index.tsx:307]: Yes... I think we are not losing much if we omit it. It will not immediately close selects near the bottom of a page which was annoying.

Comment (dahaca) [reply packages/components/src/components/form/Select/index.tsx:307]: I think I found a solution. I'd add the close on scroll back and and use `menuPosition="fixed"` instead. Works even better than before :)

Comment (komret) [reply packages/components/src/components/form/Select/index.tsx:307]: Nice! A bit annoying that `closeMenuOnScroll` doesn't work with a boolean. It should, according to [docs](https://react-select.com/props). b508348f336a46657a3bfed1ac52453a7d866eb7

**Review by dahaca — APPROVED** [review]
