### PR TITLE
Analytics and desktop app improvements

### LINKED ISSUE #5848: Analytics event 'suite-ready' is sometimes missing in the data
**Describe the bug**

Some of the analytics sessions are missing `suite-ready` and `device-connect` events. It is probably caused by network which is not properly working on the launch of the app.

### PR DESCRIPTION
**Pull request by tomasklim**
closes #5848

This PR contains code to make it easier to debug missing `suite-ready` analytics events (There are some minor desktop app improvements though) and a fix to report analytics event again if the previous report fails

- removed `disable-csp` flag which was there to be able to open devTools on production
- removed some params from creating `BrowserWindow` as they were same as default settings
- add `--open-devtools` flag to be able to open production app with DevTools open (required to see all networks events after launch of the app), open devtool when electron app starts, do not wait for `dom-ready` event, which resulted into missing first network records
- added `F12` shortcut to open devtools (to be consistent with browsers), close devtools by pressing dev tools shortcut when devtools is open
- refactored reloading app shortcut logic and added to documentation
- added hard reloading app shortcut logic to be able to reload app ignoring cache
- postponed `suite-ready` event a little bit which is now fired on `SUITE.READY` instead of `ANALYTICS.INIT`
- skipped `router-location-change` init event which does not need to be reported 
- unify restart app logic to be able to do ⬇️ 
- add shortcut to restart app without resetting app to make debugging easier
- removed Linux restart app fix which stopped working in Electron v18 and it should also that fix command line arguments were not propagated to restarted app
- and finally, try to send analytics events once again if the reporting fails

### CODE REVIEW

**Comment by tomasklim** [comment]
Followup: 
Find 
``console.error(`Analytics report failed. Reporting '${type}' was unsuccessful. ${err}`);``
``console.error(`Analytics report failed. Reporting '${type}' again. ${err}`);``
errors in Sentry and remove filtering.

File: packages/suite-desktop/src-electron/modules/shortcuts.ts [hunk 1]
```diff
@@ -25,6 +25,14 @@ const init: Module = ({ mainWindow }) => {
             mainWindow.webContents.reload();
         });
     });
+
+    const hardReloadAppShortcuts = ['Shift+F5', 'CommandOrControl+Shift+R'];
+    hardReloadAppShortcuts.forEach(shortcut => {
+        electronLocalshortcut.register(mainWindow, shortcut, () => {
+            logger.info('shortcuts', `${shortcut} pressed to hard reload app`);
+            mainWindow.webContents.reload();
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/modules/shortcuts.ts]: I can't see the difference in this hard reload from "regular" reload - both call `mainWindow.webContents.reload()`

File: packages/suite/src/middlewares/suite/analyticsMiddleware.ts [hunk 2]
```diff
@@ -114,14 +114,16 @@ const analyticsMiddleware =
...
             case ROUTER.LOCATION_CHANGE:
-                analytics.report({
-                    type: EventType.RouterLocationChange,
-                    payload: {
-                        prevRouterUrl,
-                        nextRouterUrl: action.payload.url,
-                        anchor: redactTransactionIdFromAnchor(action.payload.anchor),
-                    },
-                });
+                if (state.suite.lifecycle.status === 'ready') {
```
Comment (matejkriz) [inline packages/suite/src/middlewares/suite/analyticsMiddleware.ts]: I'm not sure, I haven't examined it in detail, but exclude only `initial` status looks safer to me - maybe there are some relevant location changes possible in error statuses
```suggestion
                if (state.suite.lifecycle.status !== 'initial') {
```

File: packages/suite-desktop/src-electron/modules/shortcuts.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite-desktop/src-electron/modules/shortcuts.ts]: 🤯 
0b02675d6c7e4da938ebaae8d1485bce75abf59c

File: packages/suite-desktop/src-electron/libs/menu.ts [hunk 3]
```diff
@@ -69,6 +73,11 @@ if (!isDev) {
     mainMenuTemplate[2].submenu.splice(2, 1);
 }
 
+if (isDev) {
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/libs/menu.ts]: Why to remove it for dev mode? Perhaps you wanted the opposite condition?

File: packages/suite-desktop/src-electron/libs/menu.ts [hunk 4]
```diff
@@ -17,7 +18,10 @@ const mainMenuTemplate: MenuItem[] = [
     // { role: 'fileMenu' }
     {
         label: 'File',
-        submenu: [isMac ? { role: 'close' } : { role: 'quit' }],
+        submenu: [
+            { label: 'Restart', click: restartApp },
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/libs/menu.ts:22]: I guess it belongs more to `View` menu than `File`?

Comment (tomasklim) [reply packages/suite-desktop/src-electron/libs/menu.ts:22]: I think `Restart` is more similar to `Close` than to `Reload`

File: packages/suite-desktop/src-electron/libs/menu.ts (hunk 3 above)
Comment (tomasklim) [reply packages/suite-desktop/src-electron/libs/menu.ts]: ~~During development, if you restart app, you get electron window without renderer~~

Okay, not true anymore. It was probably fixed by a4b1798ab2491da828f3debb92afe3708304ed8b

Okay, I would leave it in both development and production if you are not strictly against it.

Comment (tomasklim) [reply packages/suite-desktop/src-electron/libs/menu.ts]: 6a3dc0726e6acb9c21ebfa746a6c0c9dc10558b9

File: packages/suite/src/middlewares/suite/analyticsMiddleware.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/middlewares/suite/analyticsMiddleware.ts]: I am excluding `initial` and `loading`
b1aacb4700a36ea410483bf65dbc079dcc88adff

File: packages/suite-desktop/src-electron/libs/app-utils.ts [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+
+    const options: RelaunchOptions = {};
+
+    options.args = process.argv.slice(1).concat(['--relaunch']);
+
+    if (isLinux && process.env.APPIMAGE) {
+        options.execPath = process.env.APPIMAGE;
+        options.args.unshift('--appimage-extract-and-run');
+    } else if (isLinux) {
+        options.execPath = process.execPath;
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/libs/app-utils.ts]: are you sure that this is needed (or even reachable)  for the linux?

File: packages/suite-desktop/src-electron/libs/app-utils.ts [hunk 6]
```diff
@@ -0,0 +1,22 @@
...
+const isLinux = process.platform === 'linux';
+
+export const restartApp = () => {
+    const { logger } = global;
+
+    const options: RelaunchOptions = {};
+
+    options.args = process.argv.slice(1).concat(['--relaunch']);
+
+    if (isLinux && process.env.APPIMAGE) {
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/libs/app-utils.ts]: nit: `isLinux` condition is kind of extra here?
```suggestion
    if (process.env.APPIMAGE) {
```

File: packages/suite-desktop/src-electron/libs/app-utils.ts (hunk 5 above)
Comment (tomasklim) [reply packages/suite-desktop/src-electron/libs/app-utils.ts]: Good point. Probably this `else if` is not required. I will check that. It is true that this "restart" fix was done because it was not working only on some specific Linux distributions. Probably only ones with set `process.env.APPIMAGE`.

File: packages/suite-desktop/src-electron/libs/app-utils.ts (hunk 6 above)
Comment (tomasklim) [reply packages/suite-desktop/src-electron/libs/app-utils.ts]: I will check that together with ⬆️

File: packages/suite-desktop/src-electron/libs/menu.ts (hunk 4 above)
Comment (matejkriz) [reply packages/suite-desktop/src-electron/libs/menu.ts:22]: 🤷

**Comment by matejkriz** [comment]
> Followup:
> Find
> `` console.error(`Analytics report failed. Reporting '${type}' was unsuccessful. ${err}`); ``
> `` console.error(`Analytics report failed. Reporting '${type}' again. ${err}`); ``
> errors in Sentry and remove filtering.

I'm afraid this way we are not able to keep filtering for FAILED TO FETCH and stop filtering this if the `err` is FAILED TO FETCH...

We would need to change FAILED TO FETCH here or in `beforeSend` to something else like `FAILED TO ANALYTICS FETCH`

File: packages/suite-desktop/src-electron/modules/shortcuts.ts [hunk 7]
```diff
@@ -1,27 +1,48 @@
 import electronLocalshortcut from 'electron-localshortcut';
-import { APP_SRC } from '../libs/constants';
+
+import { restartApp } from '@desktop-electron/libs/app-utils';
+import { isDev } from '@suite-utils/build';
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/modules/shortcuts.ts]: used no more

**Review by matejkriz — COMMENTED** [review]
Please add notes for QA (checking app restart on all platforms) and describe what changed from the user/tester perspective (menu item, shortcuts, cli flags...)

**Comment by tomasklim** [comment]
> Please add notes for QA (checking app restart on all platforms) and describe what changed from the user/tester perspective (menu item, shortcuts, cli flags...)

Yes, sure. It is planned.

File: packages/analytics/src/utils.ts [hunk 8]
```diff
@@ -40,3 +40,21 @@ export const encodeDataToQueryString = <T extends Event>(
 
     return params.toString();
 };
+
+export const reportEventWithRetry = async (
```
Comment (matejkriz) [inline packages/analytics/src/utils.ts]: nit: I would prefer passing more params to function as an object to make the parameters "named" (`retry: false` instead of just `false`)
```javascript
interface ReportEventProps {
    type: Event['type'];
    url: string;
    options: RequestInit;
    retry: boolean;
}

export const reportEvent = async ({ type, url, options, retry = true }: ReportEventProps) => {
    try {
        await fetch(url, options);
    } catch (err) {
        if (!retry) {
            console.error(`Analytics report failed. Reporting '${type}' was unsuccessful. ${err}`);
            return;
        }
        console.error(`Analytics report failed. Reporting '${type}' again. ${err}`);
        reportEvent({ type, url, options, retry: false });
    }
};
```

File: packages/suite-desktop/src-electron/modules/shortcuts.ts (hunk 7 above)
Comment (tomasklim) [reply packages/suite-desktop/src-electron/modules/shortcuts.ts]: 525fd5243311905002265bbaacbc761856738aae

File: packages/analytics/src/utils.ts (hunk 8 above)
Comment (tomasklim) [reply packages/analytics/src/utils.ts]: something like this? 3dbaa8c8e6267c6c26096c7fa63bd0838a3a3fba together with error change

File: packages/suite-desktop/src-electron/libs/app-utils.ts (hunk 5 above)
Comment (tomasklim) [reply packages/suite-desktop/src-electron/libs/app-utils.ts]: @matejkriz I will probably delete this whole restart fixing logic for Linux (Ubuntu, Mint)..., because after testing yesterday with @STew790, it looks like that on Electron v18 it stopped working and we need to find another fix. I will try to find out more on Monday

File: packages/analytics/src/utils.ts [hunk 9]
```diff
@@ -40,3 +40,46 @@ export const encodeDataToQueryString = <T extends Event>(
...
+
+export const reportEvent = async ({ type, url, options, retry }: ReportEventProps) => {
+    try {
+        await fetch(url, options);
+    } catch (err) {
+        reportEventError(type, retry, err);
+
+        if (retry) {
+            reportEvent({ type, url, options, retry: false });
+        }
```
Comment (0ex-d) [inline packages/analytics/src/utils.ts]: I was thinking we can put a `setTimeout` here, let me know what you think

**Review by 0ex-d — COMMENTED** [review]
Looks good

File: packages/analytics/src/utils.ts (hunk 9 above)
Comment (tomasklim) [reply packages/analytics/src/utils.ts]: I was thinking about it. 
Probably it does not help with a fetch timeout. However, it can help if user is offline.

What delay do you suggest?

Comment (tomasklim) [reply packages/analytics/src/utils.ts]: Added 1s

File: packages/suite-desktop/src-electron/libs/app-utils.ts (hunk 5 above)
Comment (tomasklim) [reply packages/suite-desktop/src-electron/libs/app-utils.ts]: removed and squashed

**Comment by tomasklim** [comment]
@trezor/qa 
Please test on all platforms.

- Restart app
  - ~`Cmd+Option+R` `Ctrl+Alt+R`~ `Shift+Option+R` `Shift+Alt+R` should restart app (I think you will like it)
  - it should work on non-Linux (except NixOS) oses
  - on shortcut, reset app and hang-detect (not sure how to get it)
  - if some flags were used to open the previous session, it should use it in the new session, e.g. `--log-write` or `--open-devtools`
- `--open-devtools` should open app with DevTools
  - `F12` should open devtools, if devtools opened it should close devtools, same applies to old shortcuts
- `Cmd+R` should reload app, `Shift+Cmd+R` should reload the app while ignoring cache (not sure how to check it)
- `suite-ready` analytics event should ALWAYS be in networks
  - sometimes it can fail if tor is enabled. If it fails, it should be sent again (applies for all events) (you can turn off wifi, and it should sent each event twice)
- `router/location-change` event should be tracked on navigation within the app
- analytics should work
  
See `docs/packages/suite-desktop.md` for shortcuts

**Review by 0ex-d — APPROVED** [review]

File: packages/analytics/src/utils.ts [hunk 10]
```diff
@@ -40,3 +40,50 @@ export const encodeDataToQueryString = <T extends Event>(
...
+    let errorMessage = err?.error?.message || err?.message;
+
+    if (typeof errorMessage !== 'string') {
+        // this should never happen
+        errorMessage = 'Unknown error.';
+    }
+
+    // to circumvent sentry inbound filter
+    if (errorMessage.includes('Failed to fetch')) {
+        errorMessage = 'Failed to analytics fetch.';
```
Comment (0ex-d) [inline packages/analytics/src/utils.ts:58]:
```suggestion
        errorMessage = 'Failed to fetch analytics.';
```

Comment (tomasklim) [reply packages/analytics/src/utils.ts:58]: It is like that to circumvent sentry inbound filter

Comment (matejkriz) [reply packages/analytics/src/utils.ts:58]: The message must not contain "Failed to fetch" so we could distinguish from other "Failed to fetch" errors in sentry.

**Review by matejkriz — APPROVED** [review]

**Comment by STew790** [comment]
**QA NOK**
The shortcut `Cmd+control+R` doesn't work on Mac OS, the app is will not reset. The same applies for Windows, `Ctrl+Alt+R` shortcut doesn't do anything. Also, the shortcut is not shown in the log as it is with the `Cmd+R` or `Ctrl+R` for reload.

**QA OK**
Other shortcuts works just fine. Flags used with the previous session are also correctly applied after the "manual" reset of the app. `F12` opens and closes the devtools correctly as well.
Also, I could find the `suite-ready` analytics in all my sessions so far.

 **Info:**
 - Suite version: desktop 22.8.1 (503b472935dec8a9c07aac5eef5ba43f86780a38)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.1 Universal (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by matejkriz** [comment]
> **QA NOK** The shortcut `Cmd+control+R` doesn't work on Mac OS, the app is will not reset. The same applies for Windows, `Ctrl+Alt+R` shortcut doesn't do anything. Also, the shortcut is not shown in the log as it is with the `Cmd+R` or `Ctrl+R` for reload.

@STew790 it's probably only confusion from comments/description, there are no `Cmd+control+R` or `Ctrl+Alt+R`  shortcuts. Please see this table for the available shortcuts:
https://github.com/trezor/trezor-suite/blob/e922b4621866892b64be0e560240267edbdfd450/docs/packages/suite-desktop.md#shortcuts

**Comment by STew790** [comment]
**QA OK**
I see, my bad. The shortcuts available in the table you provided works just fine for both Mac and Windows OS!
