### PR TITLE
fix traffic light offset wrapper

### LINKED ISSUE #20850: Mac desktop 25.8.2 scrolling issue
**Describe the bug**
Slider on desktop Mac 25.8.2 is scrolling everything, not only accounts, works normally on Windows

**Info:**
 - Suite version: desktop 25.8.2 (8ff922d36b55816d4e87de2d0bc7a41bd99123ac)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.8.2 Chrome/138.0.7204.97 Electron/37.2.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3T1 2.8.10 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: BridgeTransport 3.1.0

**Screenshots:**

https://github.com/user-attachments/assets/e35c2760-712a-447d-a773-da738f1d1e00

### PR DESCRIPTION
**Pull request by OriginalEveres**
Improvement fix for https://github.com/trezor/trezor-suite/pull/20779 since it broke sidebar.

## Screenshots:
BEFORE
Screenshot 2025-08-19 at 13 55 42
AFTER
Screenshot 2025-08-19 at 13 56 00

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trafficlight-offset-expand-prop&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trafficlight-offset-expand-prop&lookback=7)

### CODE REVIEW

**Review by Lemonexe — APPROVED** [review]
Codewise LGTM, but I can only attest that this PR does not break linux sidebar & switch-device.
Someone with macOS @jvaclavik has to test this **on desktop**  because only then is `TrafficLightOffset` effective.

**Comment by jvaclavik** [comment]
Tested on mac, it works 👍

File: packages/suite/src/components/suite/TrafficLightOffset.tsx [hunk 1]
```diff
@@ -38,11 +44,20 @@ export const TrafficLightDraggableWindowHeader = ({ children, isVisible = true }
 };
 
 // on Mac in desktop app we don't use window bar and close/maximize/minimize icons are positioned directly in the app
-export const TrafficLightOffset = ({ children, offset = 35, isVisible = true }: Props) => {
+export const TrafficLightOffset = ({
+    children,
+    offset = 35,
+    isVisible = true,
+    expand = true,
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/TrafficLightOffset.tsx:51]: suggest to use `isExpanded` since we have `isVisible` here

**Review by jvaclavik — APPROVED** [review]
One comment to consider, otherwise LGTM, approving.
