### PR TITLE
fix(suite): use deeplink when navigating from sell/swap provider on desktop

### LINKED ISSUE #23069: Trading - callback using app scheme instead of localhost for SELL and UK SWAP
Follow-up of #23064

[Slack](https://satoshilabs.slack.com/archives/C015Y0VSKB7/p1761141063362749?thread_ts=1760973537.526289&channel=C015Y0VSKB7&message_ts=1761141063.362749)

### PR DESCRIPTION
**Pull request by matusbalascak**
## Notes for QA

`return_url` param when navigating to sell/swap provider should not include 127.0.0.1:21335 but rather deeplink `trezorsuite://`. The functionality should remain unchanged. The changes should only affect desktop app.

## Related Issue

Resolve #23069

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/deeplink-redirect-for-swap-sell-on-desktop&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/deeplink-redirect-for-swap-sell-on-desktop&lookback=7)

### CODE REVIEW

**Review by cermakjiri — APPROVED** [review]

**Comment by cermakjiri** [comment]
All the routes would be nice to have in some const object / enum I know it's out-of-scope of this PR.

File: packages/suite-desktop-core/src/modules/http-receiver.ts [hunk 1]
```diff
@@ -61,7 +61,13 @@ export const initBackground: ModuleInitBackground = ({
         ipcMain.handle('server/request-address', (ipcEvent, pathname) => {
             validateIpcMessage({ ipcEvent });
             try {
-                if (pathname === '/buy-redirect') {
+                // For trading redirect routes, return deeplink URL instead of localhost
+                const tradingRedirectRoutes = [
```
Comment (izmy) [inline packages/suite-desktop-core/src/modules/http-receiver.ts]: Wouldn't it be better to have a global variable for it, wdyt?

```
export const TRADING_REDIRECT_PATHS = [
    '/buy-redirect',
    '/sell-redirect',
    '/exchange-redirect',
] as const;
```

**Review by izmy — APPROVED** [review]
