### PR TITLE
Fix/fee levels and min values

### LINKED ISSUE #21654: Make high level default fee 2sat/vb and economy be based of 6 blocks
target:
- High level should have min of 2 sat/vb
- Economy should be calculated based on latest 6 blocks

https://satoshilabs.slack.com/archives/C09DADBQXJN/p1756975585353899

### PR DESCRIPTION
**Pull request by OriginalEveres**
## Description

**Changes**:
- calculate Economy level based of 6 latest blocks
- set min 2sat/vb for high level

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21654

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/fee-levels-and-min-values&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/fee-levels-and-min-values&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/fee-levels-and-min-values&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/fees/feesUtils.ts [hunk 1]
```diff
@@ -91,10 +93,9 @@ export const getNewFeeInfo = async ({
     if (network.symbol === 'btc') {
         const feeOverride = NETWORK_FEE_OVERRIDES.bitcoin;
         result.payload.levels.forEach(level => {
-            if (feeOverride.overrideLevels.includes(level.label)) {
-                level.feePerUnit = new BigNumber(level.feePerUnit).lte(feeOverride.minFeePerUnit)
-                    ? feeOverride.minFeePerUnit
-                    : level.feePerUnit;
+            const minFee = feeOverride.minFeePerUnit[level.label];
+            if (minFee && new BigNumber(level.feePerUnit).lte(minFee)) {
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/fees/feesUtils.ts]: tiny nit: `minFee !== undefined`

**Review by Lemonexe — APPROVED** [review]

File: suite-common/wallet-core/src/fees/feesUtils.ts (hunk 1 above)
Comment (OriginalEveres) [reply suite-common/wallet-core/src/fees/feesUtils.ts]: jój, muscle memory kills me
