### PR TITLE
fix(suite): do not show THP modals in onboarding

### LINKED ISSUE #21379: No focus in THP pairing code fields
**Describe the bug**
I need to click into the THP pairing code fields in order to type into them, the focus should be by default.

**Steps to reproduce:**
1. Connect a device
2. Pair it using BLE
3. Install FW
4. After FW installation, there should be the THP pairing
5. There is no focus in the fields for the code

**Info:**
 - Suite version: desktop 25.10.0 (14cd5905346a39f2aebb98866faa2cddec739fcf)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.10.0 Chrome/140.0.7339.41 Electron/38.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1800x1169
 - Device: 
 - Transport: BridgeTransport 3.1.0, BluetoothTransport

### PR DESCRIPTION
**Pull request by OriginalEveres**
Onboarding had a duplicated THP flow modals, this PR adds a prop to not have them duplicated.

**Changes**:
- added `showThpModals` prop tot `ConnectionGlobalModal`
  - passed false in onboarding flow

Resolve https://github.com/trezor/trezor-suite/issues/21379

## Screenshots:
**BEFORE:**
487835954-39ebfab7-e430-40f4-a620-7982c480e442

**AFTER:**
Screenshot 2025-09-12 at 14 31 32

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/onboarding-thp-autofocus&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/onboarding-thp-autofocus&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/onboarding-thp-autofocus&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/onboarding/OnboardingLayout.tsx [hunk 1]
```diff
@@ -184,7 +184,7 @@ export const OnboardingLayout = ({ children }: OnboardingLayoutProps) => {
 
     return (
         <>
-            <ConnectionGlobalModal />
+            <ConnectionGlobalModal showThpModals={false} />
```
Comment (peter-sanderson) [inline packages/suite/src/components/onboarding/OnboardingLayout.tsx:187]: I fucking hate that Onboarding Fullscrean App madness :(

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/components/connection/ConnectionGlobalModal.tsx [hunk 2]
```diff
@@ -13,7 +13,11 @@ import { ThpConnectionModal } from './thp/ThpConnectionModal';
 import { ThpPairingFailedModal } from './thp/ThpPairingFailedModal';
 import { ThpPairingPinEntryModal } from '../suite/modals/ReduxModal/DeviceContextModal/ThpPairingPinEntryModal';
 
-export const ConnectionGlobalModal = () => {
+type ConnectionGlobalModalProps = {
+    showThpModals?: boolean;
```
Comment (peter-sanderson) [inline packages/suite/src/components/connection/ConnectionGlobalModal.tsx:18]: Maybe lets add `@deprecated` comment that exmplaing this shall be removed once we get rid of the Onboarding Fullcreen app logic

Comment (OriginalEveres) [reply packages/suite/src/components/connection/ConnectionGlobalModal.tsx:18]: good idea!

**Comment by martykan** [comment]
This doesn't work for certain edge cases, for example if you disconnect/reconnect during onboarding. 
(yes, this is ugly)

Screenshot 2025-09-12 at 14 54 53

**Comment by OriginalEveres** [comment]
> This doesn't work for certain edge cases, for example if you disconnect/reconnect during onboarding. (yes, this is ugly)
> 
> Screenshot 2025-09-12 at 14 54 53

but, thats not what this PR solves.

The connection modal should be there for BT devices. (I think you added it :D)

but the THP ones should not be there since there are other components that handles the flow inside the onboarding flow.

**Comment by OriginalEveres** [comment]
UPDATE: I'll tackle the onboarding THP flow in this PR as well, so we don't have any bugs with the THP modals

File: packages/suite/src/views/onboarding/index.tsx [hunk 3]
```diff
@@ -20,7 +23,19 @@ import { DeviceTutorial } from './steps/DeviceTutorial';
...
 
 export const Onboarding = () => {
+    const dispatch = useDispatch();
+
     const { activeStepId, goToNextStep } = useOnboarding();
+    const device = useSelector(selectSelectedDevice);
+    const thpStep = useSelector(selectThpStep);
+
+    // This is a temporary hack until we refactor onboarding
+    // we cant include THP modals in the onboarding flow, so in a this specific edge we redirect user to the dashboard
```
Comment (peter-sanderson) [inline packages/suite/src/views/onboarding/index.tsx]:
```suggestion
    // we cant include THP modals in the onboarding flow, so in a this specific edge we redirect user to the dashboard where onboarding starts over and picks up where it ended
```

**Review by peter-sanderson — APPROVED** [review]
