### PR TITLE
fix: ensure that the suite sync is turned on even when titles are updated

### LINKED ISSUE #23921: Labels not loaded after keys are provided for writing
1. Enable Suite Sync in Suite but do not confirm on Trezor. (0:03)
2. Edit a label and this time confirm on Trezor. (0:13)
3. The one label changes but I would expect all of them to load at this point. (0:19)

In the video, all labels load after I refresh the window.

https://github.com/user-attachments/assets/f86037fc-1d42-44a3-bec0-0e960c2eab1a

### PR DESCRIPTION
**Pull request by vojtatranta**
…t updated

## Description

Ensuring that when some property in Suite Sync is edited, it also turns on the suite sync when needed.

## Notes for QA

This should fix the error outlined in the issue without any caveats.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23921

## Screenshots:

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=23921-fix-evolu-not-subscribed-on-edit&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=23921-fix-evolu-not-subscribed-on-edit&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=23921-fix-evolu-not-subscribed-on-edit&lookback=7)

### CODE REVIEW

File: suite-common/suite-sync/src/data/labeling/createUpdateAccountLabel.ts [hunk 1]
```diff
@@ -14,6 +15,14 @@ export const createUpdateAccountLabel =
             return storageResult;
         }
 
+        const ensureWalletSuiteSyncOnResult = await deps.ensureWalletSuiteSyncOn({
```
Comment (vojtatranta) [inline suite-common/suite-sync/src/data/labeling/createUpdateAccountLabel.ts]: Maybe we could remove that `ensureStorage` above, this will have to do the same thing

File: suite-common/suite-sync/src/storage/createSubscriptionStorage.ts [hunk 2]
```diff
@@ -18,5 +20,7 @@ export const createSubscriptionStorage = (): SubscriptionStorage => {
             storage[storageId]?.();
             delete storage[storageId];
         },
+        has: deviceStaticSessionId =>
```
Comment (vojtatranta) [inline suite-common/suite-sync/src/storage/createSubscriptionStorage.ts]: I. think this is needed in order to not attempt the subscribe again, am I right? @peter-sanderson

File: suite-common/suite-sync/tests/utils.ts [hunk 3]
```diff
@@ -1,4 +1,60 @@
...
+    SuiteSyncStorage,
+    WalletTable,
+} from '@suite-common/suite-sync-storage';
+
 export const mockNotExpected = <T extends (...args: any[]) => any>(key: string) =>
     jest.fn<ReturnType<T>, Parameters<T>>().mockImplementation(() => {
         throw new Error(`Method ${key} was not expected to be called`);
     });
+
+type CreateSuiteSyncStorageMockParams = {
```
Comment (vojtatranta) [inline suite-common/suite-sync/tests/utils.ts]: maybe we could start writing mocks, but IDK

File: suite-common/suite-sync/src/data/labeling/tests/createUpdateAccountLabel.test.ts [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+
+import { createSuiteSyncStorageMock, mockNotExpected } from '../../../../tests/utils';
+import { RefreshSuiteKeysUnavailable } from '../../../createRefreshSuiteSyncKeys';
+import { createEnsureWalletSuiteSyncOnMock } from '../../../storage/createEnsureWalletSuiteSyncOn.mock';
+import type { UpdateAccountLabelDeps } from '../createUpdateAccountLabel';
+import { createUpdateAccountLabel } from '../createUpdateAccountLabel';
+
+const deviceStaticSessionId: StaticSessionId = '1@2:3';
+
+describe(createUpdateAccountLabel.name, () => {
```
Comment (vojtatranta) [inline suite-common/suite-sync/src/data/labeling/tests/createUpdateAccountLabel.test.ts:13]: AI slop NGL, but those tests are more "condensed" as @peter-sanderson wanted.

At least we have som tests :)

File: suite-common/test-utils/src/extraDependenciesMock.ts [hunk 5]
```diff
@@ -71,7 +71,7 @@ export const mockReducer = (name: string) => (state: any, action: any) => {
 
 const suiteSyncMock: SuiteSync = {
     changeRelayUrl: () => Promise.resolve(),
-    turnOnSuiteSyncForWallet: () => Promise.resolve(ok()),
+    ensureWalletSuiteSyncOn: () => Promise.resolve(ok()),
```
Comment (peter-sanderson) [inline suite-common/test-utils/src/extraDependenciesMock.ts]: :clap:

File: suite-common/suite-sync/src/data/labeling/createUpdateAccountLabel.ts (hunk 1 above)
Comment (peter-sanderson) [reply suite-common/suite-sync/src/data/labeling/createUpdateAccountLabel.ts]: I agree, lets make `ensureWalletSuiteSyncOn` return `SuiteSyncStorage` directly It wil simplify code a lot

File: suite-common/suite-sync/src/storage/createSubscriptionStorage.ts (hunk 2 above)
Comment (peter-sanderson) [reply suite-common/suite-sync/src/storage/createSubscriptionStorage.ts]: I think  `SubscribeSuiteSyncData` is idempotent, if storage already exists it will return it so I think this may not be needed

Comment (peter-sanderson) [reply suite-common/suite-sync/src/storage/createSubscriptionStorage.ts]: I see its not. But it shall be

Comment (peter-sanderson) [reply suite-common/suite-sync/src/storage/createSubscriptionStorage.ts]: => another `ensure`? :D `ensureSuiteSyncDataSubscription`

File: suite-common/suite-sync/tests/utils.ts (hunk 3 above)
Comment (peter-sanderson) [reply suite-common/suite-sync/tests/utils.ts]: IDK, I really hate jest, I think if we cannot do it without it, we have bad code

Comment (vojtatranta) [reply suite-common/suite-sync/tests/utils.ts]: Well, you have to mock it somehow. Yes, it is possible without jest. But like jest doest mocking well.

File: suite-common/suite-sync/src/data/labeling/tests/createUpdateAccountLabel.test.ts (hunk 4 above)
Comment (peter-sanderson) [reply suite-common/suite-sync/src/data/labeling/tests/createUpdateAccountLabel.test.ts:13]: I rewrote the slop. U owe me ;)

File: suite-common/suite-sync/src/storage/createEnsureWalletSuiteSyncOn.ts [hunk 6]
```diff
@@ -1,33 +1,35 @@
...
+    (deps: EnsureWalletSuiteSyncOnDeps): EnsureWalletSuiteSyncOn =>
     async ({ deviceStaticSessionId }) => {
         const device = selectDeviceByStaticSessionId(deps.getState(), deviceStaticSessionId);
 
         const canTurnOnSuiteSync =
             device && isTrezorDeviceWithState(device) && isSuiteSyncSupportedByDevice(device);
 
         if (!canTurnOnSuiteSync) {
-            return ok();
+            return err({ type: 'SuiteSyncTurnOnNotAvailableError' });
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/storage/createEnsureWalletSuiteSyncOn.ts]: use `RefreshSuiteKeysUnavailable` + rename if needed

**Review by peter-sanderson — APPROVED** [review]
