### PR TITLE
fix(suite-native): fix app freeze in earn section when selecting btc-only fw

### LINKED ISSUE #24704: Mobile: App freezes after switching from Earn tab to device with BTC-only firmware
When I am in the Earn tab and switch to a device with BTC-only firmware, Trezor Suite correctly redirects me to the Home tab. However, at that moment the whole application freezes (the buttons are not clickable).

https://github.com/user-attachments/assets/c058fe5d-a7c9-4d82-8981-1d04cd9d4c28

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

When changing to bitcoin-only firmware in Earn section, the Home section freezed and app became unusable. This PR fixes this bug.

## Notes for QA

1. connect both universal and bitcoin-only firmware to mobile app
2. select the universal firmware and navigate to Earn section
3. select the bitcoin-only firmware (which navigates the app to Home section)
4. the app should not freeze any longer

## Related Issue

Resolve #24704 

## Screenshots:

https://github.com/user-attachments/assets/3216076b-10ff-42d8-867a-4f1bf02ba619

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/mobile-earn-btc-fw&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/mobile-earn-btc-fw&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/mobile-earn-btc-fw&lookback=7)

### CODE REVIEW

File: suite-native/navigation/src/components/TabBar.tsx [hunk 1]
```diff
@@ -44,6 +48,25 @@ export const TabBar = ({ state, navigation, tabItemOptions }: TabBarProps) => {
     const { applyStyle } = useNativeStyles();
     const insets = useSafeAreaInsets();
 
+    const isBtcOnly = useSelector(selectHasBitcoinOnlyFirmware);
```
Comment (tomasklim) [inline suite-native/navigation/src/components/TabBar.tsx]:
```suggestion
    const isBitcoinOnlyFirmware = useSelector(selectHasBitcoinOnlyFirmware);
```

File: suite-native/navigation/src/components/TabBar.tsx [hunk 2]
```diff
@@ -44,6 +48,25 @@ export const TabBar = ({ state, navigation, tabItemOptions }: TabBarProps) => {
...
+    const shouldHideEarnTab = isBtcOnly || !isEarnEnabled;
+
+    // handle navigation to home stack when earn tab becomes hidden
+    // e.g. when BTC-only firmware is selected
+    useEffect(() => {
+        if (!shouldHideEarnTab) {
+            return;
+        }
+
+        const currentRoute = state.routes[state.index];
```
Comment (tomasklim) [inline suite-native/navigation/src/components/TabBar.tsx]: `getActiveRouteName` util would be better?

File: suite-native/navigation/src/components/TabBar.tsx [hunk 3]
```diff
@@ -44,6 +48,25 @@ export const TabBar = ({ state, navigation, tabItemOptions }: TabBarProps) => {
     const { applyStyle } = useNativeStyles();
     const insets = useSafeAreaInsets();
 
+    const isBtcOnly = useSelector(selectHasBitcoinOnlyFirmware);
+    const isEarnEnabled = useFeatureFlag(FeatureFlag.IsEarnEnabled);
+
+    const shouldHideEarnTab = isBtcOnly || !isEarnEnabled;
+
+    // handle navigation to home stack when earn tab becomes hidden
+    // e.g. when BTC-only firmware is selected
```
Comment (juriczech) [inline suite-native/navigation/src/components/TabBar.tsx]:
```suggestion
    // When user selects BTC only device in device switcher, redirect to homescreen out of the earn section.
```

File: suite-native/navigation/src/components/TabBar.tsx [hunk 4]
```diff
@@ -44,6 +48,25 @@ export const TabBar = ({ state, navigation, tabItemOptions }: TabBarProps) => {
...
+        if (!shouldHideEarnTab) {
+            return;
+        }
+
+        const currentRoute = state.routes[state.index];
+
+        if (currentRoute?.name === AppTabsRoutes.EarnStack) {
+            navigation.navigate(AppTabsRoutes.HomeStack);
+        }
+    }, [navigation, shouldHideEarnTab, state.index, state.routes]);
```
Comment (juriczech) [inline suite-native/navigation/src/components/TabBar.tsx]: Is this effect really necessary? Wouldn't it be possible to call this navigation on lines 79-81 before rendering `null`?

Comment (TomasBoda) [reply suite-native/navigation/src/components/TabBar.tsx]: I believe it's good practice to keep rendering code pure (no side effects, state changes, navigation, ...). If we do this, we are risking infinite rendering loops and other potential problems. The `useEffect` simply reacts to state asynchronously, which I believe is much better.

File: suite-native/navigation/src/components/TabBar.tsx (hunk 3 above)
Comment (TomasBoda) [reply suite-native/navigation/src/components/TabBar.tsx]: done

File: suite-native/navigation/src/components/TabBar.tsx (hunk 2 above)
Comment (TomasBoda) [reply suite-native/navigation/src/components/TabBar.tsx]: yes, done

File: suite-native/navigation/src/components/TabBar.tsx (hunk 1 above)
Comment (TomasBoda) [reply suite-native/navigation/src/components/TabBar.tsx]: done

**Review by tomasklim — APPROVED** [review]

File: suite-native/navigation/src/components/TabBar.tsx (hunk 4 above)
Comment (juriczech) [reply suite-native/navigation/src/components/TabBar.tsx]: Good point. I believe the `useEffect` is not well suited here though. I believe that if you need to handle specific case which is only triggered by device switcher, then probably handle it there with the same condition instead of `useEffect` please.

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx [hunk 5]
```diff
@@ -71,6 +85,18 @@ export const DeviceManagerContent = () => {
     const insets = useSafeAreaInsets();
 
     const handleSelectDevice = (selectedDevice: TrezorDevice) => {
+        const currentRoute = getActiveRouteName(navigation.getState() as AppNavigationState);
```
Comment (juriczech) [inline suite-native/device-manager/src/components/DeviceManagerContent.tsx]: Please, use `useRoute` - https://reactnavigation.org/docs/use-route/

Then you don't need to use type-casting.

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx [hunk 6]
```diff
@@ -71,6 +85,18 @@ export const DeviceManagerContent = () => {
...
+        const isOnEarnScreen = currentRoute === EarnStackRoutes.Earn;
+        const isBitcoinOnlyFirmware = selectedDevice.firmwareType === 'bitcoin-only';
```
Comment (juriczech) [inline suite-native/device-manager/src/components/DeviceManagerContent.tsx]: `selectHasBitcoinOnlyFirmware`

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx [hunk 7]
```diff
@@ -71,6 +85,18 @@ export const DeviceManagerContent = () => {
     const insets = useSafeAreaInsets();
 
     const handleSelectDevice = (selectedDevice: TrezorDevice) => {
+        const currentRoute = getActiveRouteName(navigation.getState() as AppNavigationState);
+        const isOnEarnScreen = currentRoute === EarnStackRoutes.Earn;
```
Comment (juriczech) [inline suite-native/device-manager/src/components/DeviceManagerContent.tsx]: `checkIsRouteAnyOf`

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx [hunk 8]
```diff
@@ -71,6 +85,18 @@ export const DeviceManagerContent = () => {
...
+        const isBitcoinOnlyFirmware = selectedDevice.firmwareType === 'bitcoin-only';
+
+        // When user selects BTC only device in device switcher, redirect to homescreen out of the earn section.
+        if (isOnEarnScreen && isBitcoinOnlyFirmware) {
+            navigation.navigate({
```
Comment (juriczech) [inline suite-native/device-manager/src/components/DeviceManagerContent.tsx]: Please use `navigation.popTo`. If you simply navigate, on android you would still be able to navigate back using the hardware button to go back which would bring you to the frozen screen, reinventing the bug.

Comment (juriczech) [reply suite-native/device-manager/src/components/DeviceManagerContent.tsx]: To use `navigation.popTo` you need to fix typing of navigation prop:
```
type NavigationProp = StackToStackCompositeNavigationProps<
    HomeStackParamList,
    HomeStackRoutes,
    RootStackParamList
>;
```

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx (hunk 5 above)
Comment (TomasBoda) [reply suite-native/device-manager/src/components/DeviceManagerContent.tsx]: done

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx (hunk 7 above)
Comment (TomasBoda) [reply suite-native/device-manager/src/components/DeviceManagerContent.tsx]: done

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx (hunk 8 above)
Comment (TomasBoda) [reply suite-native/device-manager/src/components/DeviceManagerContent.tsx]: used `.reset`

**Review by juriczech — APPROVED** [review]
LGTM, haven't tested it
