### PR TITLE
Proper timeouts in blockchain-link websockets

### LINKED ISSUE #10460: Suite doesn't recognize custom backend requests timeout
**Describe the bug**
Suite doesn’t recognize that the server requests times out and acts as if everything is “normal” and the backend is connected. That is, until you go into send form and try to send a transaction. You can set everything up but it doesn’t calculate the fees and the “Review and Send” button is greyed out.

**Info:**
 - Suite version: desktop 24.1.0 (ed53f9f5caf12b7fce24bc17b74043e4c1e6d448)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.1.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
Suite correctly detects server timeout.

**Actual result:**
Suite doesn't recognize that server times out.

**Note(s):**
https://satoshilabs.slack.com/archives/CKYFBT2C9/p1702397330668799

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

In `blockchain-link`'s `baseWebsocket` class (Blockbook & Blockfrost APIs), response timeouts were always (re)calculated from the last message sent, meaning that no timeout was ever thrown until new requests were being sent.

- https://github.com/trezor/trezor-suite/pull/10787/commits/cf300f0e40a1d43758430368cb4a599deae986ae - implemented  `createPromiseManager` util, which handles uniquely identified deferred promises and their potential timeouts; will be reused in  #10363
- https://github.com/trezor/trezor-suite/pull/10787/commits/a69f8e9b1d3fe67e828381f0b9443c4707b9ed40 - `createPromiseManager` used in baseWebsocket
  - initial connection timeout separated from ordinary message timeout, meaning that `onTimeout` method is now used only for messages and its part regarding initial connection moved to `connect` method
  - `connectionTimeout` is now set and cleared only locally; there was no reason to store it as a class field

## Related Issue

Could resolve #10460

## QA

Apart from resolving the linked issue, please make sure that the backend connection works well in general; the changes could be more significant than they look like.

### CODE REVIEW

File: packages/utils/src/createPromiseManager.ts [hunk 1]
```diff
@@ -0,0 +1,106 @@
+import { createDeferred, Deferred } from './createDeferred';
+
+type ManagedPromise = Deferred<any, number> & { deadline: number };
```
Comment (mroz22) [inline packages/utils/src/createPromiseManager.ts]: note for me: shoudln't it accept first type argument instead of passing any?

File: packages/utils/src/createPromiseManager.ts [hunk 2]
```diff
@@ -0,0 +1,106 @@
+import { createDeferred, Deferred } from './createDeferred';
```
Comment (mroz22) [inline packages/utils/src/createPromiseManager.ts]: total nitpick, if I was naming it, i would name it `createDeferredManager` 
image

feel free to ignore

File: packages/utils/src/createPromiseManager.ts [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+
+    const length = () => promises.length;
+
+    const nextId = () => ID;
+
+    const replanTimeout = () => {
+        const now = Date.now();
+        const nearestDeadline = promises.reduce(
+            (prev, { deadline }) => (prev && deadline ? Math.min : Math.max)(prev, deadline),
+            0,
```
Comment (mroz22) [inline packages/utils/src/createPromiseManager.ts]: i didn't think much about that but does it make sense to have nearestDeadline lower than now? I would expect setting accumulator to now here

**Review by mroz22 — APPROVED** [review]
it looks ok, just some 3 random comments to prove that I read it!

File: packages/utils/src/createPromiseManager.ts (hunk 3 above)
Comment (marekrjpolak) [reply packages/utils/src/createPromiseManager.ts]: I'm not sure I understand correctly. It probably shouldn't happen now, but even if `nearestDeadline` is sooner than now, I clamp the timer to zero a few lines below. Also, if `nearestDeadline` is zero (which is accumulator's initial value), it means that there's no promise with unsignalled deadline so I don't have to set the timer at all.

Edit: `nearestDeadline` sooner than now could happen in the future, when we decide to set the min safe interval from TODO below. The idea is that when you have multiple promises with deadlines very close to each other, it may make sense to set the timer after all of them (e.g. clamped to minimum of 100 ms or something) and signal them all at once.

File: packages/utils/src/createPromiseManager.ts (hunk 1 above)
Comment (marekrjpolak) [reply packages/utils/src/createPromiseManager.ts]: I'm again not sure what you mean. There is unfortunately no way how to correctly type every deferred promise inside the manager. Do you mean to type the manager as a whole with the union of every possible promise value? It could actually make sense.

File: packages/utils/src/createPromiseManager.ts (hunk 2 above)
Comment (marekrjpolak) [reply packages/utils/src/createPromiseManager.ts]: I like it.
https://github.com/trezor/trezor-suite/pull/10787/commits/8f4beaefb133c644d55cb6c683904ec2fcb88eaa & https://github.com/trezor/trezor-suite/pull/10787/commits/b74c0227689aad4d2941bd1be68f53535ce83b7e

File: packages/utils/src/createPromiseManager.ts (hunk 1 above)
Comment (marekrjpolak) [reply packages/utils/src/createPromiseManager.ts]: Like this? https://github.com/trezor/trezor-suite/pull/10787/commits/913f7bc2207c9c5c6e4c49437d1f1f1427c55a13

Comment (mroz22) [reply packages/utils/src/createPromiseManager.ts]: I just got my lizard brain triggered by any without any specific idea what to do about it
this could be useful 👍

**Review by mroz22 — APPROVED** [review]
