### PR TITLE
Memoize CJ prison selector

### LINKED ISSUE #11950: Canceling/stopping Coinjoin freezes Suite
**Describe the bug**
When I start Coinjoin and then I stop it and try to go to "Send" of the same Coinjoin account for example, the Suite freezes completely. In the console I can see:
`2024-04-10T08:56:48.310Z - WARN(content): Unresponsive`
And I have to force quit the app.
My console was also flooded with this after quitting the app:
image

It is not present in the production app.

**Steps to reproduce:**
1. Start Suite
2. Add Coinjoin account
3. Start Coinjoin
4. Go to "Send" form of the Coinjoin account for example
5. Suite freezes

**Info:**
 - Suite version: desktop 24.4.1 (979558244707a3d9d577cf9afff6a860c48b137d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.4.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.32

**Expected result:**
I can stop the Coinjoin process.

**Actual result:**
Suite freezes after stopping the Coinjoin process.

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

After changes in https://github.com/trezor/trezor-suite/commit/02b15b43db9d2ffa063cba80199c00b949a34dd6, accessing send form from CJ account sometimes results in endless loop of `getSendFormDraftThunk`. By memoizing `selectRegisteredUtxosByAccountKey` output instead of returning new object every time, this should be fixed.

## Related Issue

Should resolve #11950

### CODE REVIEW

File: packages/suite/src/reducers/wallet/coinjoinReducer.ts [hunk 1]
```diff
@@ -665,6 +666,27 @@ export const selectCurrentCoinjoinBalanceBreakdown = (state: CoinjoinRootState)
...
+            ) {
+                result[key] = inmate;
+            }
+
+            return result;
+        }, {});
+    },
+);
+
 export const selectRegisteredUtxosByAccountKey = (
```
Comment (PeKne) [inline packages/suite/src/reducers/wallet/coinjoinReducer.ts]: why not memoizing the whole `selectRegisteredUtxosByAccountKey` selector? 
```suggestion
export const selectRegisteredUtxosByAccountKey = memoizeWithArgs(...
```

**Review by PeKne — COMMENTED** [review]
Thanks for fixing this 🙏

File: packages/suite/src/reducers/wallet/coinjoinReducer.ts (hunk 1 above)
Comment (marekrjpolak) [reply packages/suite/src/reducers/wallet/coinjoinReducer.ts]: Because I'm extremely conservative and I didn't know how clever `proxy-memoize` is. I'll change it, test it and push a fixup.

**Review by PeKne — APPROVED** [review]
