### PR TITLE
Fix/suite import tx

### LINKED ISSUE #5787: csv import in Send form not validating file content
**Describe the bug**
csv import in Send form is not validating file content.
See screenshots. When you import empty file transaction amount and address fields disappear.
When you import invalid file send form is filled out with rubbish data.

**Steps to reproduce:**
1. Navigate to Send form
2. Import invalid or empty .csv file.
3. Observe Send form behavior.

**Info:**
 - Suite version: desktop 22.7.1 (20ef59a8d1050bd3843cf86066dce9e8819bf0dc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.31

**Screenshots:**
_Empty file_
Screenshot 2022-07-14 at 14 32 54
_Invalid file_
Screenshot 2022-07-14 at 15 00 41

### LINKED ISSUE #7263: Imported send data are calculated for bitcoin but not for sats
**Steps to reproduce:**
1. Switch to sats (_click on the amount in the top of your account_ )
2. Import csv with transaction information
3. See that calculated bitcoin value is expressed in BTC not in sats (_using decimals_)

**Info:**
 - Suite version: desktop 22.12.1 (ddaacdb2245d7a909b3d2abfe918cff34d2e1609)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Expected result:**
Calculated the bitcoin value in sats (_integers_)

**Actual result:**
Received amounts in BTC

**Video:**

https://user-images.githubusercontent.com/26002916/209912060-9ca16c6d-5e1a-4f52-8be3-7b4261839fa1.mov

**csv example with random data**
```
"bc1qp66agjq5tmf8cuneq26mj4sg9zmxfzh0cxrmv7,210,EUR,157250"
"bc1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxswvvzej,68.90,USD,154838"
```

### LINKED ISSUE #7966: Example text in Import tx overflows
Taproot account -> Send -> Import

The example text overflows. (It will be related to all addresses that are as long as Taproot addresses)

image

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description
Some fixes regarding import tx in send form

- imported values are formatted to btc or satoshi units
- validation after import working correctly
- fixed word breaking in import modal component

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/7263
Resolve https://github.com/trezor/trezor-suite/issues/5787
Resolve https://github.com/trezor/trezor-suite/issues/7966

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 1]
```diff
@@ -41,12 +51,22 @@ export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRa
 
                 if (currency === network.symbol) {
                     // csv amount in crypto currency
-                    output.amount = item.amount || '';
+                    const cryptoValue = item.amount || '';
+                    if (!isInteger(cryptoValue) && shouldSendInSats) {
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]: Why check for integer here? What if I want to send 1 BTC?

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 2]
```diff
@@ -41,12 +51,22 @@ export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRa
...
+
                     // calculate Fiat from Amount
                     if (fiatRates && fiatRates.current) {
+                        const fiatAmount = shouldSendInSats
+                            ? formatAmount(output.amount, network.decimals)
+                            : output.amount;
                         output.fiat =
                             toFiatCurrency(
-                                output.amount,
+                                fiatAmount,
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]: I think the naming is off here (the value represents crypto amount) and perhaps it can be simplified:

Comment (komret) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]: I think the naming is off here (the value represents crypto amount) and perhaps it can be simplified just by using `cryptoValue` as the first argument of `toFiatCurrency`).

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 3]
```diff
@@ -227,10 +227,12 @@ export const useSendForm = (props: UseSendFormProps): SendContextValues => {
         // keepDefaultValues will set `isDirty` flag to true
         reset(values, { keepDefaultValues: true });
         setLoading(false);
-        const valid = await trigger();
-        if (valid) {
-            composeRequest();
-        }
+        validateImportedTransaction(async () => {
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendForm.ts:237]: 😬 It works but... I wish there was a simpler way, without `useEffect`.

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 1 above)
Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: if you are using sats (shoudSendInSats) and value **is not** an integer (float) then value should be transformed to sats.

see issue https://github.com/trezor/trezor-suite/issues/7263

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 2 above)
Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: ~~nope, it represents fiat amount, you can fill csv data using either crypto or fiat currency (see example in upload form)~~

File: packages/suite/src/hooks/wallet/useSendForm.ts (hunk 3 above)
Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendForm.ts:237]: #metoo, and we are not the only one :) 

https://github.com/orgs/react-hook-form/discussions/3700

https://codesandbox.io/p/sandbox/reack-hook-form-initial-validation-forked-9zmqt?file=%2Fsrc%2Findex.tsx

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 2 above)
Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: well, `cryptoValue` (crypto input) could be represented  either in bitcoin or satoshi units while `toFiatCurrency` always requires bitcoin units, this is why it needs to be conditionally transformed

Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: i was confused by `output.fiat`, `fiatAmount` is actually `cyptoAmountInBitcoinUnits` (exaplined in comment below)

i've slightly renamed it https://github.com/trezor/trezor-suite/pull/10327/commits/aaf41b6535a8c186c09fcb3be01521d0b44250e4

**Comment by szymonlesisz** [comment]
idk what kind of black magic is that. commit before the fixup had `38.82 %` of branch coverage, when i run test locally i have the same value but in fixup commit is throws:
```
Jest: "global" coverage threshold for branches (38.8%) not met: 38.77%
```

I've decided to [completely exclude](https://github.com/trezor/trezor-suite/pull/10327/commits/49aa23417d52d7f35e7380bf18919ed7493aa198) all coinmarket hooks from the coverage. 
there is 27 files without single unit test :( cc @LukasRada 

new values are a little bit higher now
| % Stmts | % Branch | % Funcs | % Lines |
|---------|----------|---------|---------|
|   59.14 |    45.74 |      56 |   60.42 |

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 1 above)
Comment (komret) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: Ok I get it. The condition could be improved, possibly checking for dust limit instead of integer, and doing the conversion for either all or none of the outputs. But super low priority, you can leave it as it is...

Trying to send 1 BTC:

https://github.com/trezor/trezor-suite/assets/42465546/2acc6732-6329-4df9-bfd8-ae110a7990c5

**Review by komret — APPROVED** [review]

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 1 above)
Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: not sure how do you want to improve it.

if suite is set to **using sats** and data file says `amount=1` how suite should know that in fact  you are requesting 1 btc (100000000 sats) ? or another example if data file says `amount=746` how suite should decide that you are requesting 746 sats or 746 btc?

this condition covers **only the opposite case**: if amount **is not** an integer (let say 1.1 btc) then automatically converts it into sats otherwise assume that this integer represents sats

Comment (komret) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: If it used dust limit instead of `isInteger` in the condition, then `1` would be interpreted as BTC - Suite does not let you send 1 sat anyway. `746`, on the other hand, is above dust limit, so this would be interpreted as sats - one does not usually send more than 500 BTC, at least I don't do it often.

But it is probably not worth implementing, importing a transaction of 1 BTC is not likely either.

Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: well, you are right. 
since its confusing why decimal amounts are converted and integer amounts are not im removing this condition (tbh i dont exactly remember why i did it like this) 
now **all amounts** will be converted to satoshis :+1: 

[8ff322f](https://github.com/trezor/trezor-suite/pull/10327/commits/8ff322fbc9f21870cfa51485397fdcd68c9f10c3)

Comment (komret) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: Ok but this means that the amount in the CSV must always be in BTC and we don't state it anywhere I think 😬

Comment (szymonlesisz) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: we do state it in `Show CSV example`:

```
address,amount,currency
tb1qp4v7ajc36ehssrqq2thhslp4apxegsp030f9kt,0.31337,BTC
tb1qqdmj0nuavjmr5f7huu8n9rh6wke4c2r4ykrj50,0.1,USD
```

you can either use BTC or FIAT currency, in fact there is no mention that you can use SAT currency in csv - which will be new feature

issue #7263 is about missing calculation from imported BTC to SAT

Comment (komret) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: Ok, let's merge it.
