### PR TITLE
fix(suite-native): earn - insufficient page + component update

### LINKED ISSUE #26190: Create Insufficient Balance Screen and update routing
- [ ]  create Insufficient Balance Screen for Staking https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=5104-30388&t=uoAHKxqZqaxBp0gb-1

- [ ] update routing for [earn section staking items](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=5104-25265&t=uoAHKxqZqaxBp0gb-1)
a) not staked yet, but sufficient balance for staking -> [figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=5104-30243&t=uoAHKxqZqaxBp0gb-1)
b) already staking -> [figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=5635-13183&t=uoAHKxqZqaxBp0gb-1)
c) insufficient balance -> [figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=5104-30388&t=uoAHKxqZqaxBp0gb-1)

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

- update staking routing based on the account status
- create insufficient page
- made stake acc bottom sheet selector

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/26190

## Screenshots:

https://github.com/user-attachments/assets/cd8064c0-8580-4932-9ed9-953317c8684a

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/native/insufficient-staking&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/native/insufficient-staking&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/native/insufficient-staking&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Account metadata,google - watches files over time" | 🙋 manual |
| Quarantine test: "Account metadata,dropbox - watches files over time" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-02T12:53:12.059Z • 7 test(s) total_

<details><summary>Trezor Suite (desktop) — 3 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-02T12:51:28.308Z • 3 test(s) total_

### CODE REVIEW

File: suite-native/module-earn/src/components/ChooseAccountItem.tsx [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+}: ChooseAccountItemProps) => {
+    const formattedAccountType = useSelector((state: AccountsRootState) =>
+        selectFormattedAccountType(state, account.key),
+    );
+
+    const handlePress = useCallback(() => {
+        onPress(account);
+    }, [account, onPress]);
+
+    const icon = useMemo(() => <CryptoIcon symbol={account.symbol} />, [account.symbol]);
```
Comment (TomasBoda) [inline suite-native/module-earn/src/components/ChooseAccountItem.tsx]: I don't see a reason for this variable + `useMemo`. I'd rather just render the icon component directly in the `icon={...}` prop. WDYT?

File: suite-native/module-earn/src/components/EarnAccountCard.tsx [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+    const { applyStyle } = useNativeStyles();
+    const isStakingItem = item.type === 'staking';
+    const isStablecoinYieldItem = item.type === 'stablecoin-yield';
+
+    const stakingApy = useStakingSelector(state =>
+        isStakingItem ? selectAPYByAccountKey(state, item.accountKey) : null,
+    );
+
+    const apyValue = isStakingItem ? (stakingApy ?? item.apy) : item.apy;
+    const hasApy = apyValue != null;
```
Comment (TomasBoda) [inline suite-native/module-earn/src/components/EarnAccountCard.tsx]: Nitpick: generally, I don't like creating such variables if:
1. they are used only once
2. do not need complex logic (many `&&` or `||`)

I'd rather just use `!!apyValue` where the `hasApy` is used.

File: suite-native/module-earn/src/hooks/useStakingPromoNavigation.ts [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+
+    const { bottomSheetRef: infoSheetRef, openModal: openInfoModal } = useBottomSheetModal();
+
+    const {
+        bottomSheetRef: chooseAccountSheetRef,
+        openModal: openChooseAccountModal,
+        closeModal: closeChooseAccountModal,
+    } = useBottomSheetModal();
+
+    const [chooseAccounts, setChooseAccounts] = useState<Account[]>([]);
```
Comment (TomasBoda) [inline suite-native/module-earn/src/hooks/useStakingPromoNavigation.ts]:
```suggestion
    const [chosenAccounts, setChosenAccounts] = useState<Account[]>([]);
```

File: suite-native/module-earn/src/components/EarnAccountCard.tsx (hunk 2 above)
Comment (BrantalikP) [reply suite-native/module-earn/src/components/EarnAccountCard.tsx]: Yeah, I see your point, but since it was agreed that we should follow these conventions in our (code-style folder), I wanted to stick to

File: suite-native/module-earn/src/hooks/useStakingPromoNavigation.ts (hunk 3 above)
Comment (BrantalikP) [reply suite-native/module-earn/src/hooks/useStakingPromoNavigation.ts]: https://github.com/trezor/trezor-suite/pull/26363/changes/95483b65b1331026df62c14cad249876b3f9d77b

File: suite-native/module-earn/src/components/EarnAccountCard.tsx (hunk 2 above)
Comment (BrantalikP) [reply suite-native/module-earn/src/components/EarnAccountCard.tsx]: hmm what about something in the middle? :D https://github.com/trezor/trezor-suite/pull/26363/changes/95483b65b1331026df62c14cad249876b3f9d77b

File: suite-native/module-earn/src/components/ChooseAccountItem.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/module-earn/src/components/ChooseAccountItem.tsx]: https://github.com/trezor/trezor-suite/pull/26363/changes/95483b65b1331026df62c14cad249876b3f9d77b

File: suite-native/module-earn/src/components/EarnAccountCard.tsx (hunk 2 above)
Comment (TomasBoda) [reply suite-native/module-earn/src/components/EarnAccountCard.tsx]: yes, this is exactly what I meant, thanks. btw, is there really a code style convention for not using `!!` and prioritizing `!= null` instead? just wondering, I could not find it

**Review by TomasBoda — COMMENTED** [review]
@BrantalikP When clicking on the `Get ETH` button when the account has insufficient balance, the app redirects to swap form. Doesn't it make more sense to redirect to buy form instead?

**Review by TomasBoda — APPROVED** [review]
LGTM
