### PR TITLE
Fix/fee box layout fix

### LINKED ISSUE #2360: Fee box layout distorted
Broken layout 

Screen Shot 2020-09-16 at 15 26 40

### PR DESCRIPTION
**Pull request by robertbrada**
Fix https://github.com/trezor/trezor-suite/issues/2360

### CODE REVIEW

File: packages/suite/src/views/wallet/send/components/Fees/index.tsx [hunk 1]
```diff
@@ -70,10 +70,13 @@ const EstimatedMiningTimeWrapper = styled.span`
 const Row = styled.div`
     display: flex;
 
-    & + & {
-        margin-top: 15px;
+    /* set fixed min-height for the first Row, so that the form doesn't change its height while the fee is being calculated 
+    (happens when typing fee value in the input box) */
+    &:first-child {
+        min-height: 55px;
```
Comment (slowbackspace) [inline packages/suite/src/views/wallet/send/components/Fees/index.tsx]: ehhh that's hacky, approved! 😀

Comment (slowbackspace) [reply packages/suite/src/views/wallet/send/components/Fees/index.tsx]: hmm maybe if would be a bit nicer if the crypto/fiat amount acted as a second column (first column being fee selector including text and input for custom fee below), HI-RES DESIGN ATTACHED (red rectangles are representing columns) (I think I just discovered my new favorite wireframes tool)

Screenshot 2020-09-23 at 17 26 11

Comment (robertbrada) [reply packages/suite/src/views/wallet/send/components/Fees/index.tsx]: Nice design! I agree the layout logic could probably be redesigned compared to the current state. I will take a look at it

File: packages/suite/src/views/wallet/send/components/Fees/index.tsx [hunk 2]
```diff
@@ -10,28 +10,26 @@ import CustomFee from './components/CustomFee';
 import { useSendFormContext } from '@wallet-hooks';
 
 const StyledCard = styled(Card)`
-    display: flex;
-    justify-items: space-between;
     margin-bottom: 25px;
     padding: 32px 42px;
-
-    @media all and (max-width: ${variables.SCREEN_SIZE.SM}) {
```
Comment (slowbackspace) [inline packages/suite/src/views/wallet/send/components/Fees/index.tsx:18]: Some wrapping is still needed as the new layout won't work on smaller screens as the fee selector is taking too much space 
Screenshot 2020-09-24 at 14 06 07


I would expect amounts move under a fee selector just like it used to be. Imo there is no need for grid as it should be easy job for flexbox, but feel free to use use what you are most comfortable with.
Screenshot 2020-09-24 at 14 10 00

**Review by slowbackspace — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/send/components/Fees/index.tsx (hunk 2 above)
Comment (slowbackspace) [reply packages/suite/src/views/wallet/send/components/Fees/index.tsx:18]: you can even render different layout for large and small screens and you don't have to rely just on media queries. There is useLayoutSize hook that will return a boolean if the mobile layout is active 
` const { isMobileLayout } = useLayoutSize();`. So you can conditionally render different components (or just pass some prop to it) to do necessary layout adjustments.

But ofc it would be super nice if all this could be done as simple as possible.
edit: idea - for mobile layout you can move the whole column with amounts to the same container as the fee estimation message is in.

File: packages/suite/src/views/wallet/send/components/Fees/index.tsx [hunk 3]
```diff
@@ -104,20 +126,42 @@ const Fees = () => {
...
+                </CoinAmount>
+                <FiatAmount>
+                    <FiatValue
+                        amount={formatNetworkAmount(transactionInfo.fee, symbol)}
+                        symbol={symbol}
+                    />
+                </FiatAmount>
+            </FeeAmount>
+        ) : (
+            <></>
```
Comment (slowbackspace) [inline packages/suite/src/views/wallet/send/components/Fees/index.tsx]: nitpick, just return null instead `... : null`

**Review by slowbackspace — APPROVED** [review]
that will work! (at least in most cases 😅)

**Comment by szymonlesisz** [comment]
i think properly written `display: grid` will solve this "folding/overflowing" issue eventually :)
but for now it's better than it was :)
