### PR TITLE
Fix/import transaction

### LINKED ISSUE #18495: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
Sentry Issue: [TREZOR-SUITE-11WF](https://satoshilabs.sentry.io/issues/6226750394/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
  at currencies (@trezor/suite-build/../suite/src/hooks/wallet/useSendFormImport.ts:44:57)
  at <object>.importTransaction (@trezor/suite-build/../suite/src/hooks/wallet/useSendFormImport.ts:44:35)
  at <object>.loadTransaction (@trezor/suite-build/../suite/src/hooks/wallet/useSendForm.ts:234:15)
```

### PR DESCRIPTION
**Pull request by komret**
## Description

Commits 1 & 2: render CSV example as `pre` so that when it is copied, it retains line-breaks
Commit 3: add toast to notify the user that the CSV input could not be parsed
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/18495

#### Before:
Example was copied as one line and couldn't be parsed - confusing:

https://github.com/user-attachments/assets/f0c6adfa-7348-4f63-acfd-69bf99b11782

Failed to parse, yet no error shown - confusing and also created an unhandled error that got to Sentry:

https://github.com/user-attachments/assets/82531af8-a099-438a-ba68-da6b4c331236

#### After:

https://github.com/user-attachments/assets/f5ea9e46-a91c-4155-81fa-362fc3b278c1

https://github.com/user-attachments/assets/98734672-67d6-4008-b6a7-d3eacddeecf5

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/import-transaction&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/import-transaction&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/import-transaction&lookback=7)

### CODE REVIEW

File: packages/components/src/components/typography/Paragraph/Paragraph.tsx [hunk 1]
```diff
@@ -2,8 +2,8 @@ import React from 'react';
 
 import { Text, TextProps } from '../Text/Text';
 
-export const Paragraph = ({ children, ...rest }: TextProps) => (
-    <Text {...rest} as="p">
+export const Paragraph = ({ children, ...rest }: Omit<TextProps, 'as'>) => (
+    <Text {...(rest as TextProps) /* type-casting to prevent weird TS error */} as="p">
```
Comment (komret) [inline packages/components/src/components/typography/Paragraph/Paragraph.tsx]: Any idea what is happening here?

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 2]
```diff
@@ -140,9 +149,7 @@ export const useSendFormImport = ({
                 }
 
                 if (!output.amount || !output.fiat) {
-                    // TODO: display Toast notification with invalid currency error?
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts:143]: A five-year old todo :D

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 3]
```diff
@@ -41,7 +42,15 @@ export const useSendFormImport = ({
...
-        const currencies = result.map(it => it.currency.toLowerCase());
+
+        let currencies;
+        try {
+            currencies = result.map(it => it.currency.toLowerCase());
+        } catch {
+            dispatch(notificationsActions.addToast({ type: 'could-not-parse-csv' }));
+
+            return;
+        }
```
Comment (Lemonexe) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]: `let` must have type declaration, otherwise it implicitly types as `any` But that's besides the point..
The try catch seems very weird. How could .map + .toLowerCase() throw error?
I see that at this point, `result` is typed as `{ [p: string]: string }[]`
So it may contain any properties →  `it.currency` may be undefined, and that's the only way where I would see this code throwing (can't access undefined.toLowerCase).
So let's look at that explicitly, instead of try catch:
```suggestion

        if (result.some(it => !Object.prototype.hasOwnProperty.call(it, 'currency'))) {
            dispatch(notificationsActions.addToast({ type: 'could-not-parse-csv' }));

            return;
        }
        const currencies = result.map(it => it.currency.toLowerCase());
```

File: packages/components/src/components/typography/Paragraph/Paragraph.tsx (hunk 1 above)
Comment (Lemonexe) [reply packages/components/src/components/typography/Paragraph/Paragraph.tsx]: Yes, use `Without` instead of `Omit` :slightly_smiling_face: 
This is a known limitation, and AFAIK we have Without [exactly for that purpose](https://github.com/trezor/trezor-suite/blob/fbe8426fb8ac16c4b951367a9802708b05b81491/packages/type-utils/src/utils.ts#L35)

Comment (komret) [reply packages/components/src/components/typography/Paragraph/Paragraph.tsx]: image

I added a small tweak in ecda1ce01c742e42d555fdb6ceca625338bb3ce1 for `Without` to only allow known properties of `T`.

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 3 above)
Comment (komret) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: I didn't want to iterate twice but I have to agree that being explicit is better. 2c1ca42618cd3b0b5fcf3a01960c5824ab50dd37

File: packages/components/src/components/typography/Paragraph/Paragraph.tsx (hunk 1 above)
Comment (Lemonexe) [reply packages/components/src/components/typography/Paragraph/Paragraph.tsx]: thanks for noticing that. Seems that previously, you could have used `Without<TextProps, 'asdf nonsense'>` without any warning, which is now not possible :+1: :+1:

**Review by Lemonexe — APPROVED** [review]
Codewise LGTM.
Works correctly with the example on BTC mainnet :heavy_check_mark:

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 25.5.0 (6faf4d3002d80e8453a19b108a08dc8027e508f8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.5.0 Chrome/134.0.6998.178 Electron/35.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 2.0.33
