### PR TITLE
Fix device acquire in suite

### LINKED ISSUE #19461: new discovery - device becomes acquried from unacquired
fix by @szymonlesisz 
https://github.com/trezor/trezor-suite/commit/ff12764ec7706e7591de96d30777ac2bf3e5870b

Image

### PR DESCRIPTION
**Pull request by mroz22**
resolve #19461

on develop, even with coins enabled 
Screenshot 2025-06-25 at 13 02 49

clicking this
Screenshot 2025-06-25 at 13 03 26
got me here

Screenshot 2025-06-25 at 13 02 24

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-device-acquire-in-suite&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-device-acquire-in-suite&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix-device-acquire-in-suite&lookback=7)

### CODE REVIEW

**Comment by mroz22** [comment]
also tagging @Lemonexe who has been into this kind of issues lately..

File: packages/suite/src/actions/wallet/selectedAccountActions.ts [hunk 1]
```diff
@@ -39,18 +39,18 @@ const getAccountState = (state: AppState): SelectedAccountStatus => {
...
             loader: 'auth',
         };
     }
 
+    const accounts = selectDeviceAccounts(state);
+
     // account cannot exist since there are no discovered accounts (maybe no networks enabled)
-    if (accounts.length === 0) {
+    const enabledNetworks = selectEnabledNetworks(state);
+    if (accounts.length === 0 && enabledNetworks.length === 0) {
```
Comment (mroz22) [inline packages/suite/src/actions/wallet/selectedAccountActions.ts:53]: stricter condition so that [this](https://private-user-images.githubusercontent.com/30367552/458846655-afe1a4a0-03a2-4b9d-b001-0dfdee782a28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTEwMTgxODgsIm5iZiI6MTc1MTAxNzg4OCwicGF0aCI6Ii8zMDM2NzU1Mi80NTg4NDY2NTUtYWZlMWE0YTAtMDNhMi00YjlkLWIwMDEtMGRmZGVlNzgyYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjI3VDA5NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYzYyZjc3Y2IzYTFlNmVkN2M5OTI5ZTllMjljN2I1OTcxNzc5YjNkNjhmMWYzZmM3N2VhOGIyMzNlY2NhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AU6IxZ_C6_dqZKodrKKqgNERvWLwceiPhNQvubR-XNM) won't get displayed when it does not make sense

**Review by Lemonexe — APPROVED** [review]
Good catch
