### PR TITLE
suite updates and fixes

### LINKED ISSUE #22430: Device detected in incorrect state visible when pairing THP
When you connect a THP device and are not paired yet, you see this screen:

Image

### PR DESCRIPTION
**Pull request by mroz22**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22430

## Screenshots:

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=nitpicks-3&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=nitpicks-3&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=nitpicks-3&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx [hunk 1]
```diff
@@ -65,24 +65,33 @@ const DeviceImage = ({ selectedDevice }: { selectedDevice: TrezorDevice | undefi
 
 export const PrerequisitesGuide = ({ showDeviceImage = true }: PrerequisitesGuideProps) => {
     const device = useSelector(selectSelectedDevice);
-    const [prerequisite, setPrerequisite] = useState<ReturnType<typeof selectPrerequisite>>(
-        useSelector(selectPrerequisite),
-    );
-    const [deviceStatus, setDeviceStatus] = useState<ReturnType<typeof getStatus> | null>(
-        (device && getStatus(device)) ?? null,
-    );
```
Comment (mroz22) [inline packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx:73]: not sure if this was your intention but this causes that after the initial mount of this component it does not react to any further device changes. Or am I wrong? cc @vojtatranta

Comment (vojtatranta) [reply packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx:73]: heh, you are right, @jvaclavik put it here, that's wrong obvoiusly, we screwed up, I wanted to make this debug thing done diffetently

Comment (vojtatranta) [reply packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx:73]: Id' remove the whole debug thing to be certain.

Comment (vojtatranta) [reply packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx:73]: coz getStatsu and prequisites should both be reactive

Damn, I should have noticed that. I was against adding the debug like this, but then I allowed it. My bad.

**Review by vojtatranta — CHANGES_REQUESTED** [review]
Let's remove that debugging thing completely to be sure. We'll do the debugging of the UI differently as I suggested in the PR where this was added. SO that it wouldn't touch the source code.

**Comment by mroz22** [comment]
removed misleading troubleshooting tips for thp-locked 

image

**Comment by mroz22** [comment]
@vojtatranta ack [67ead2d](https://github.com/trezor/trezor-suite/pull/22426/commits/67ead2df60cc431bead90613aaa3f42bc356f7f5)

File: packages/suite/src/components/suite/troubleshooting/TroubleshootingTips.tsx [hunk 2]
```diff
@@ -149,12 +150,15 @@ export const TroubleshootingTipsWithSections = <K extends string, T extends K>({
...
-            <TroubleshootingButton />
+            {cta && <ActionBanner />}
+            {/* > 1 because there is some empty default passed from parent component */}
+            {/* @ts-expect-error */}
+            {items['default']['items'].length > 1 && <TroubleshootingButton />}
         </Column>
     ) : (
         <Box margin={{ top: 80 }}>
-            <TroubleshootingButton />
+            {/* @ts-expect-error */}
```
Comment (vojtatranta) [inline packages/suite/src/components/suite/troubleshooting/TroubleshootingTips.tsx]: Just a note: couldn't we pass the items to the button from here? To prevent these TS comments?

Don't bother with that I am looking into this component and it is weird altogether.

**Review by vojtatranta — APPROVED** [review]
Awesome, the screen reacts, the troubleshootings look good.

Brilliantly caught, well done, thanks from the engmnt team. If you need other bugs to fix, let us know we can make some anytime!

Let's fix that commit message, merge it and I guess pick it

File: packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx (hunk 1 above)
Comment (Lemonexe) [reply packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx:73]: Yes it seems to me like overkill. I [already created issue](https://github.com/trezor/trezor-suite/issues/22430) for it because it was reported and I was just debugging it. with the very same intent to fix it.
I'll link the issue in PR..

Comment (vojtatranta) [reply packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx:73]: I shouldn't have approved it :( my bad

**Comment by vojtatranta** [comment]
I notified @pavelmario that this should be definitely cherry-picked

File: packages/suite/src/components/suite/troubleshooting/TroubleshootingTips.tsx (hunk 2 above)
Comment (Lemonexe) [reply packages/suite/src/components/suite/troubleshooting/TroubleshootingTips.tsx]: Yes, we no longer need multiple sections.
`TroubleshootingTipsWithSections` was done to support more than one section, see `git grep -n "TroubleshootingTipsWithSections" f0284203` but that is no longer used.
To deduplicate code, `TroubleshootingTips` was created to offer the same interface as before, but now with multiple sections it created the "default" one.

@mroz22 is already working to simplify it back, because designs no longer have multiple sections.

**Comment by vojtatranta** [comment]
> I notified @pavelmario that this should be definitely cherry-picked

okay, so the buggy code isn't in the release branch, so it's okay

**Review by Lemonexe — APPROVED** [review]
LGTM

**Review by Lemonexe — APPROVED** [review]
