### PR TITLE
fix: copy fix for wipe-device vs. factory-reset in settings

### LINKED ISSUE #9626: Separate copy for wipe device in bootloader mode from normal mode
If you click Factory reset in device settings with device in normal mode, it wipes only the seed and PIN. If you click the same button in bootloader mode, it wipes also firmware. Would be nice to have separate copy for those two variants.

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/9626

image
image

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsDevice/WipeDevice.tsx [hunk 1]
```diff
@@ -9,15 +11,30 @@ interface WipeDeviceProps {
...
 
 export const WipeDevice = ({ isDeviceLocked }: WipeDeviceProps) => {
+    const { device } = useDevice();
     const dispatch = useDispatch();
 
+    const isBootloaderMode = isDeviceInBootloaderMode(device);
+
     const handleClick = () => dispatch(openModal({ type: 'wipe-device' }));
 
+    const headingTranslation = isBootloaderMode
```
Comment (komret) [inline packages/suite/src/views/settings/SettingsDevice/WipeDevice.tsx:21]: It should be the other way round: Factory reset in bootloader, wipe in normal. Otherwise OK.

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/settings/SettingsDevice/WipeDevice.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/views/settings/SettingsDevice/WipeDevice.tsx:21]: :man_facepalming: Fixed. Thanks for catching it.

**Review by komret — APPROVED** [review]

**Comment by peter-sanderson** [comment]
We also have a modal copy
image

**Comment by STew790** [comment]
Questions here https://github.com/trezor/trezor-suite/issues/9626#issuecomment-2575706799
