### PR TITLE
metadata functional improvements

### LINKED ISSUE #3207: Trezor Suite does not apply labelling correctly when switching to standard wallet
**Describe the bug**
After switching from a passphrase protected wallet to the standard wallet (empty passphrase) labels are not applied within the standard wallet.

**Info:**
 - Suite Version: 20.12.1
 - OS: Ubuntu 20.10

**Steps to reproduce:**
This only happens if you open with the standard wallet first: 
1. open standard wallet (no passphrase) and confirm "enable labeling"
2. switch to passphrase protected wallet and again confirm "enable labeling"
3. switch back to standard wallet -> labels are gone

**Expected result:**
Labels should still be applied.

**Actual result:**
Default labels are shown instead, e.g. acccount "Bitcoin #1", etc. instead of custom labels.

**Note(s):**
Not sure if suite should ask again to enable labeling when switching back to standard wallet? Suite does not ask a second time to enable labeling when switching back to standard wallet.

### PR DESCRIPTION
**Pull request by mroz22**
As szymon [pointed out](https://github.com/trezor/trezor-suite/pull/3027), dfd.reject is being called even on sucessful authorization flow. It actually did work but to make it more future proof I updated error handling in metadata provider modal.

should probably resolve #3207

### CODE REVIEW

File: packages/suite/src/services/suite/metadata/GoogleProvider.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ class GoogleProvider extends AbstractMetadataProvider {
             this.connected = true;
             return true;
         } catch (error) {
-            return false;
+            return error.message as string;
```
Comment (szymonlesisz) [inline packages/suite/src/services/suite/metadata/GoogleProvider.ts]:
```suggestion
            return error.toString();
```
what if message is not a string or there is no message?

File: packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx [hunk 2]
```diff
@@ -57,11 +57,18 @@ const MetadataProvider = (props: Props) => {
...
         const result = await connectProvider(type);
-        if (!result) {
+        // window close indicates user action, user knows what happened, no need to show an error message
+        if (result === 'window closed') {
             setIsLoading('');
-            // TODO: error state, try again
+            // stop here, user might have changed his decision and wants to use another provider
             return;
         }
+        // TODO: we could show error in the UI
```
Comment (szymonlesisz) [inline packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx]: i would rather implement this "display error", at least we got some feedback if it happens and we know where to look.
its always better to receive a issue with "it's showing Error: some error" than "it isn't working, nothing happens" :)

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx (hunk 2 above)
Comment (mroz22) [reply packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx]: oook, I just don't know how it should look like. I may try something and if design people don't like it, they will come with something

Comment (mroz22) [reply packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx:66]: Indeed it looks like it does not break anything and lets me remove this eslint ignore, but lets wait for tests..

Comment (mroz22) [reply packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx]: Maybe something like this will do for now
image

Comment (mroz22) [reply packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx]: But I am wondering whether this text should be displayed to user at all :face_with_head_bandage: It clerly seems to be addressing me rather than user :no_good:

**Comment by mroz22** [comment]
Ok, while addressing review comments I found few more issues worth refactoring. So I did but I need to read my work tomorrow when I am fresh

**Comment by mroz22** [comment]
Reworked it a bit: 
- fixed problem with not unregistering event listeners 
- unified error handling from abstractProvider.connect method
- and probably more

**Review by keraf — APPROVED** [review]

File: packages/suite/src/utils/suite/oauth.ts [hunk 3]
```diff
@@ -38,70 +38,125 @@ const openWindowOnAnotherDomain = (
...
-        }
-        if (!message) return;
+// keep handler function instance in top level scope
+let desktopHandlerInstance: (message: { [key: string]: string }) => void;
+let webHandlerInstance: (e: MessageEvent) => void;
 
-        const { code, access_token, state } = message;
+const getDesktopHandlerInstance = (
+    dfd: Deferred<Credentials>,
+    originalParams: { [key: string]: string },
```
Comment (tomexx) [inline packages/suite/src/utils/suite/oauth.ts:93]: let's maybe add type as it is used in multiple places

**Review by tomexx — CHANGES_REQUESTED** [review]

File: packages/suite/src/utils/suite/oauth.ts (hunk 3 above)
Comment (mroz22) [reply packages/suite/src/utils/suite/oauth.ts:93]: well, why not. It has 13 occurrences in total across the project. What would be the name for this utility type?

Comment (keraf) [reply packages/suite/src/utils/suite/oauth.ts:93]: `KeyValueString`?

Comment (tomexx) [reply packages/suite/src/utils/suite/oauth.ts:93]: cache invalidation and naming stuff are the hardest things in software development 😅  anyway I'd go with @keraf 's suggestion

Comment (mroz22) [reply packages/suite/src/utils/suite/oauth.ts:93]: And you would expect me to put it into types/utils/index.ts? I am still struggling to see added value of this. If I see `{[key:string]:string}` I immediately know what is going on, I see this one as a common idiom, nearly the same as `number` or `boolean`. When I see `KeyValueString` I really have no idea what to expect. It does not appear to be a good deal to have less typing 14 (KeyValueString) vs 21 ({[key:string]:string}) in exchange of added mental overhead. I'd support your idea in case it was more complicated type, where we could say that it might be edited in future. Here I don't see any chance how it could ever be edited.

File: packages/suite-desktop/scripts/dev.js [hunk 4]
```diff
@@ -14,7 +14,8 @@ next.prepare().then(() => {
     const requestHandler = next.getRequestHandler();
     const server = createServer(requestHandler).listen(8000, () => {
         if (!launchElectron) {
-            return;
+            console.error('process.env.LAUNCH_ELECTRON not set to true')
```
Comment (mroz22) [inline packages/suite-desktop/scripts/dev.js:17]: Not connected with anything in this PR. I was just tinkering with env vars and bumbed into case when launchElectron was false and I ended up waiting forever

File: packages/suite/src/services/suite/metadata/GoogleProvider.ts (hunk 1 above)
Comment (mroz22) [reply packages/suite/src/services/suite/metadata/GoogleProvider.ts]: resolved with instanceof Error check

File: packages/suite/src/utils/suite/oauth.ts [hunk 5]
```diff
@@ -40,72 +40,125 @@ const openWindowOnAnotherDomain = (
...
         }
+        if (!e.data.search && !e.data.hash) return;
 
-        if (code || access_token) {
-            dfd.resolve(({ code, access_token } as unknown) as Credentials);
-        } else {
-            dfd.reject(new Error('Cancelled'));
-        }
-        window.removeEventListener('message', onMessageWeb);
+        return handleResponse(
```
Comment (szymonlesisz) [inline packages/suite/src/utils/suite/oauth.ts]: unnecessary return

File: packages/suite/src/utils/suite/oauth.ts [hunk 6]
```diff
@@ -40,72 +40,125 @@ const openWindowOnAnotherDomain = (
...
+let desktopHandlerInstance: (message: { [key: string]: string }) => void;
+let webHandlerInstance: (e: MessageEvent) => void;
 
-        const { code, access_token, state } = message;
+const getDesktopHandlerInstance = (
+    dfd: Deferred<Credentials>,
+    originalParams: { [key: string]: string },
+) => {
+    desktopHandlerInstance = message => {
+        return handleResponse(
```
Comment (szymonlesisz) [inline packages/suite/src/utils/suite/oauth.ts]: unnecessary return

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite-desktop/src-electron/preload.ts [hunk 7]
```diff
@@ -51,12 +51,17 @@ contextBridge.exposeInMainWorld('desktopApi', {
...
     off: (channel: string, func: (...args: any[]) => any) => {
+        ipcRenderer.removeListener(channel, func);
         if (validChannels.includes(channel)) {
             ipcRenderer.off(channel, (_, ...args) => func(...args));
         }
     },
-
+    removeAllListeners: (channel: string) => {
+        ipcRenderer.removeAllListeners(channel);
+    },
```
Comment (szymonlesisz) [inline packages/suite-desktop/src-electron/preload.ts]: implement this:
https://github.com/trezor/trezor-suite/pull/3175/files#diff-7a95c75c77571983a267b8413959e765e96268f9506d139a165c1253669818d7

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

**Review by szymonlesisz — APPROVED** [review]
