### PR TITLE
Phishing Detectors

### LINKED ISSUE #13474: False positives on user token transfers
**Describe the bug**
Prevent marking legitimate user transactions as phishing when they involve non-legit or unknown tokens. This avoids unnecessary false positives for user-sent/stake tokens.

Screenshot 2024-07-23 at 14 19 49
Screenshot 2024-07-23 at 14 21 54

### LINKED ISSUE #14697: Non-EVM Chain Phishing Detection
Extend phishing detection to non-EVM blockchains, ensuring that scam transactions are flagged across a wider range of networks.

### LINKED ISSUE #14698: Transaction phishing detection
### Missing features/bugs

- [x] #24658

### What is implemented now:
- if EVM
  - amount of native token is zero and all tokens have zero value
  - we have token definitions and user has them downloaded
    - amount of native token is zero
    - there are tokens/nfts available
    - all tokens/nfts are scam if they are unrecognised or hidden by user, tokens which were unrecognised but are marked as legit by user are not scam anymore

### Implementation:    
https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-utils/src/antiFraud.ts

### LINKED ISSUE #14699: Small non-zero native token detection
Update the logic to flag phishing attempts even when small amounts of native tokens (non-zero) are involved, covering cases where scammers send minimal amounts to bypass zero-value checks.

### LINKED ISSUE #20846: XLM: introduce tx phishing detection/filter
There is extremely lot of spam in Suite

Image

Image

https://stellar.expert/explorer/public/tx/2dfcf2eb80bee9175b6844fa9910e64944c4270da06a88dfea4fbfa7c54407ea

### LINKED ISSUE #24658: Introduce Tron tx phishing detection
- native token dust
- scam tokens
- ???

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

This PR adds new tx phishing detectors or enhances existing detectors:

- refactor phishing detection code
- add phishing detection for more networks
- added dust amount detection (`< 0.005 USD` for total tx amount)
- added unknown tx detection for `Stellar`
- added ability to mark tx as not scam (and undo it)
- implement for mobile as well

## Related Issue

Resolve #14699 
Resolve #14697 
Resolve #13474 
Resolve #24658
Resolve #20846 
Resolve https://github.com/trezor/trezor-suite/issues/14698

## Instructions for QA

QA, please test that marked transactions are dropped for non-remembered wallets/ejected wallets.

Check the below detectors ⬇️ 

<table>
<thead>
<tr>
<th>Network</th>
<th>Zero Amount</th>
<th>Dust Amount</th>
<th>Fake Token</th>
<th>Unknown Tx</th>
</tr>
</thead>
<tbody>

<tr>
<td>Ethereum</td>
<td>✅</td>
<td>✅</td>
<td>✅</td>
<td>❌</td>
</tr>

<tr>
<td>Ripple</td>
<td>❌</td>
<td>✅</td>
<td>❌</td>
<td>❌</td>
</tr>

<tr>
<td>Cardano</td>
<td>❌</td>
<td>✅</td>
<td>✅</td>
<td>❌</td>
</tr>

<tr>
<td>Solana</td>
<td>❌</td>
<td>✅</td>
<td>✅</td>
<td>❌</td>
</tr>

<tr>
<td>Stellar</td>
<td>❌</td>
<td>✅</td>
<td>✅</td>
<td>✅</td>
</tr>

<tr>
<td>Tron</td>
<td>❌</td>
<td>✅</td>
<td>✅</td>
<td>❌</td>
</tr>

</tbody>
</table>

Also try to ban fetching token definitions in network. Check what happens. All token txs should be invalid.

## Screenshots

Copies on the screenshots are outdated. These are the new copies:

:warning:
**Banner** - This transaction looks suspicious. Learn more
**Button** - Mark as safe

:white_check_mark:
**Banner** - You’ve confirmed this transaction is safe.
**Button** - Mark as suspicious

Screenshot 2026-02-25 at 12 45 28

Screenshot 2026-02-25 at 12 45 32

<table>
<tr>
<td>
simulator_screenshot_AF7D792A-D479-4E07-814E-DDC6AFDE1DA5
</td>
<td>
simulator_screenshot_C5186921-6EEB-43E7-A8C4-1E28E654786E
</td>
</tr>
</table>

<table>
<tr>
<td>
simulator_screenshot_7C0EB611-8110-41C7-B4F9-D054EA7F9D25
</td>
<td>
simulator_screenshot_6B6254B2-D4A7-4628-B738-68047842583D
</td>
</tr>
</table>

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/tx-phishing-detectors&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/tx-phishing-detectors&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/tx-phishing-detectors&lookback=7)

## 🔍 Currents Test Results

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/tx-phishing-detectors&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/tx-phishing-detectors&lookback=7)

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/tx-phishing-detectors&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (desktop) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-03-12T10:29:32.517Z • 7 test(s) total_

<details><summary>Trezor Suite (web) — 9 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Labeling migration > Migration from Dropbox | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-12T12:25:42.650Z • 9 test(s) total_

### CODE REVIEW

File: suite-common/wallet-types/src/transaction.ts [hunk 1]
```diff
@@ -243,6 +243,7 @@ export interface WalletAccountTransaction extends AccountTransaction {
      * prepending txs have deadline (blockHeight) when they should be removed from UI
      */
     deadline?: number;
+    overrideFraudDetection?: boolean;
```
Comment (tomasklim) [inline suite-common/wallet-types/src/transaction.ts]: I would keep this separately from tx object. Some array with tx ids in redux so that it can be synced with mobile.

e.g.
`wallet.transactions.phishing.[account].show/hide`

Comment (tomasklim) [reply suite-common/wallet-types/src/transaction.ts]: Image

this is how we do tokens

File: suite-common/token-definitions/src/__fixtures__/antiFraud.ts [hunk 2]
```diff
@@ -1,7 +1,68 @@
 import type { WalletAccountTransaction } from '@suite-common/wallet-types';
+import { asAmountUnit, unitsToSubunits } from '@suite-common/wallet-utils';
 import type { TokenTransfer } from '@trezor/blockchain-link';
+import { BigNumber } from '@trezor/utils';
 
+import { DUST_PHISHING_THRESHOLD } from '../antiFraud';
 import type { TokenDefinitions } from '../tokenDefinitionsTypes';
+
+const BELOW_DUST = unitsToSubunits({
+    value: asAmountUnit(new BigNumber(DUST_PHISHING_THRESHOLD).dividedBy(2)),
```
Comment (tomasklim) [inline suite-common/token-definitions/src/__fixtures__/antiFraud.ts]: it is better to use boundary values decreased/increased by one 1 unit instead of divide/multiply

File: suite-common/token-definitions/src/__fixtures__/antiFraud.ts [hunk 3]
```diff
@@ -1,7 +1,68 @@
...
+    symbol: 'eth',
+}).toString();
+
```
Comment (tomasklim) [inline suite-common/token-definitions/src/__fixtures__/antiFraud.ts:10]: exact amount test is missing

File: suite-common/token-definitions/src/antiFraud.ts [hunk 4]
```diff
@@ -39,16 +64,42 @@ export const getIsFakeTokenPhishing = (
...
+type NetworkPhishingDetectors = Map<NetworkType, PhishingDetectorFn[]>;
+
+const phishingDetectors: NetworkPhishingDetectors = new Map([
+    ['bitcoin', [detectors.dustValue]],
+    ['ethereum', [detectors.dustValue, detectors.zeroValue, detectors.fakeToken]],
+    ['ripple', [detectors.dustValue]],
+    ['cardano', [detectors.dustValue]],
+    ['solana', [detectors.dustValue]],
+    ['stellar', [detectors.dustValue]],
+    ['tron', [detectors.dustValue]],
```
Comment (tomasklim) [inline suite-common/token-definitions/src/antiFraud.ts]: add fake token here too

File: suite-common/token-definitions/src/antiFraud.ts [hunk 5]
```diff
@@ -39,16 +64,42 @@ export const getIsFakeTokenPhishing = (
...
+const detectors = {
+    dustValue: getIsDustValuePhishing,
+    zeroValue: getIsZeroValuePhishing,
+    fakeToken: getIsFakeTokenPhishing,
+} as const;
+
+type NetworkPhishingDetectors = Map<NetworkType, PhishingDetectorFn[]>;
+
+const phishingDetectors: NetworkPhishingDetectors = new Map([
+    ['bitcoin', [detectors.dustValue]],
```
Comment (tomasklim) [inline suite-common/token-definitions/src/antiFraud.ts]: please ask @hynek-jina if there can be valid tx with 0 amount on bitcoin, e.g. op return

**Review by tomasklim — DISMISSED** [review]

File: suite-common/token-definitions/src/antiFraud.ts [hunk 6]
```diff
@@ -1,22 +1,47 @@
...
+    const amountInUnits = subunitsToUnits({
+        value: asAmountSubunit(new BigNumber(transaction.amount)),
+        symbol: transaction.symbol,
+    });
+
+    const isTxAmountBelowDust = new BigNumber(amountInUnits)
+        .multipliedBy(historicFiatRate)
+        .isLessThanOrEqualTo(DUST_PHISHING_THRESHOLD);
+
+    return isTxAmountBelowDust && D.isEmpty(transaction.tokens);
```
Comment (tomasklim) [inline suite-common/token-definitions/src/antiFraud.ts]: I think `transaction.internalTransfers` has to be also empty

Comment (tomasklim) [inline suite-common/token-definitions/src/antiFraud.ts]: there can also be token dust value attack

File: suite-common/token-definitions/src/antiFraud.ts (hunk 5 above)
Comment (hynek-jina) [reply suite-common/token-definitions/src/antiFraud.ts]: OP_RETURN is valid and by design without amount, but otherwise nodes doesn't relay transaction with output amounts below dust.

I believe this is generally not an issue in bitcoin.

File: suite-common/wallet-types/src/transaction.ts (hunk 1 above)
Comment (TomasBoda) [reply suite-common/wallet-types/src/transaction.ts]: done: added `wallet.transactions.phishing` that is a map with `accountKey` as key and array of overriden txids as value

File: suite-common/token-definitions/src/__fixtures__/antiFraud.ts (hunk 2 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/__fixtures__/antiFraud.ts]: done

File: suite-common/token-definitions/src/__fixtures__/antiFraud.ts (hunk 3 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/__fixtures__/antiFraud.ts:10]: done

File: suite-common/token-definitions/src/antiFraud.ts (hunk 4 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/antiFraud.ts]: done

File: suite-common/token-definitions/src/antiFraud.ts (hunk 5 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/antiFraud.ts]: thanks, skipping bitcoin dust detector

File: suite-common/token-definitions/src/antiFraud.ts (hunk 6 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/antiFraud.ts]: done: refactored the dust detector to handle also internal transfers

Comment (TomasBoda) [reply suite-common/token-definitions/src/antiFraud.ts]: done

File: suite/intl/src/messages.ts [hunk 7]
```diff
@@ -8589,6 +8589,18 @@ export const messages = defineMessages({
         defaultMessage:
             'Proceed with caution. This may be a fraudulent transaction. <a>Learn more</a>',
     },
+    TR_MARK_AS_NOT_SCAM: {
+        id: 'TR_MARK_AS_NOT_SCAM',
+        defaultMessage: 'Mark as not scam',
```
Comment (tomasklim) [inline suite/intl/src/messages.ts]: imo it makes sense to mark it only if wallet is remembered, if not remembered, we should disable button and show something like `To enable marking this transaction as not a scam, please remember wallet`. Please ask @cavigneron for better strings 🙏

File: suite-common/wallet-core/src/transactions/transactionsReducer.ts [hunk 8]
```diff
@@ -127,9 +138,20 @@ export const prepareTransactionsReducer = createReducerWithExtraDeps(
                     }
                 });
             })
+            .addCase(transactionsActions.markTransactionAsNotScam, (state, { payload }) => {
+                const { key, txid, isMarkedAsNotScam } = payload;
+                const txList = state.phishing[key] || [];
```
Comment (tomasklim) [inline suite-common/wallet-core/src/transactions/transactionsReducer.ts]:
```suggestion
                const transactionIdList = state.phishing[key] || [];
```

File: suite-common/wallet-core/src/transactions/transactionsReducer.ts [hunk 9]
```diff
@@ -127,9 +138,20 @@ export const prepareTransactionsReducer = createReducerWithExtraDeps(
...
+
+                if (isMarkedAsNotScam && !txList.includes(txid)) {
+                    state.phishing[key] = [...txList, txid];
+                } else if (!isMarkedAsNotScam && txList.includes(txid)) {
+                    state.phishing[key] = txList.filter(t => t !== txid);
```
Comment (tomasklim) [inline suite-common/wallet-core/src/transactions/transactionsReducer.ts]:
```suggestion
                    state.phishing[key] = transactionIdList.filter(transactionId => transactionId !== txid);
```

File: suite-common/wallet-core/src/transactions/transactionsReducer.ts (hunk 8 above)
Comment (TomasBoda) [reply suite-common/wallet-core/src/transactions/transactionsReducer.ts]: done

File: suite-common/wallet-core/src/transactions/transactionsReducer.ts (hunk 9 above)
Comment (TomasBoda) [reply suite-common/wallet-core/src/transactions/transactionsReducer.ts]: done

File: suite/intl/src/messages.ts (hunk 7 above)
Comment (TomasBoda) [reply suite/intl/src/messages.ts]: added disabled buttons and tooltips, but needs to be updated by copywriters

**Comment by tomasklim** [comment]
Please try to ban fetching token definitions in network. Check what happens. All token txs should be valid but maybe it shows everything invalid 😀

**Comment by STew790** [comment]
**QA note**
Found this scam airdrop that might be worth checking/testing it on:
image
https://etherscan.io/tx/0x910c5a6e39719f9a7e277b8d7cbd1bd91e5f68f9378a838f2be104b458c0ecf7

**Comment by TomasBoda** [comment]
> **QA note** Found this scam airdrop that might be worth checking/testing it on: ...

@STew790 this transaction consists of two tokens:
- `ERC1155` which is fraudulent
- `ERC20` which is valid and above the dust threshold

Due to this `ERC20` token it was not marked as scam. I increased the dust threshold from `0.001 USD` to `0.005 USD` to capture more dust transactions that are potential scams (including this one which had value around `0.0038 USD`).

**Comment by TomasBoda** [comment]
> Please try to ban fetching token definitions in network. Check what happens. All token txs should be valid but maybe it shows everything invalid 😀

In this case all token transactions are marked as potential scam. We agreed that this is correct and expected behavior.

**Comment by cavigneron** [comment]
@tomasklim What does the UI look like (including the copy) for when the user can confirm recognition of the transaction? 

Also I'd suggest to use "Show suspicious transaction" or similar rather than "Unhide"....

File: packages/suite/src/components/wallet/Pagination.tsx [hunk 10]
```diff
@@ -69,8 +69,12 @@ export interface GetPagesProps {
 export type Page = number | '...';
 
 export const getPages = ({ currentPage: page, totalPages: total }: GetPagesProps): Page[] => {
+    if (total <= 0) {
+        return [];
+    }
+
     if (total <= 7) {
-        return [...Array(total)].map((_, i) => i + 1);
+        return [...Array.from({ length: total })].map((_, i) => i + 1);
```
Comment (cermakjiri) [inline packages/suite/src/components/wallet/Pagination.tsx]: There's no need for the coping over the array. The `map` returns always new array. 

Btw I'm just curious, why did you change this? The `new Array(length)` / `Array(length)` works just fine, doesn't it?

File: packages/suite/src/views/wallet/transactions/TransactionList/useFetchTransactions.ts [hunk 11]
```diff
@@ -173,22 +171,24 @@ export const useVisibleTransactions = ({
...
         () =>
-            tokenDefinitions && enableFiltering
+            enableFiltering
                 ? allTransactions.filter(
                       transaction =>
-                          // NOTE: due to some weirdness, the transaction here can be `undefined`!
-                          transaction
-                              ? !getIsPhishingTransaction(transaction, tokenDefinitions)
-                              : false, // NOTE: when transaction is falsy, hide it
+                          !getIsPhishingTransaction({
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/transactions/TransactionList/useFetchTransactions.ts]: super nit: since you expect `boolean` the `get` prefix seems redundant: `getIsPhishingTransaction` -> `isPhishingTransaction`?

File: suite-common/token-definitions/src/antiFraud.ts [hunk 12]
```diff
@@ -1,22 +1,91 @@
...
+
+type PhishingDetectorFnProps = {
+    transaction: TransactionWithFiatAmount;
+    tokenDefinitions?: TokenDefinitions;
+};
+
+type PhishingDetectorFn = (props: PhishingDetectorFnProps) => boolean;
+
+// dust threshold in USD
+export const DUST_PHISHING_THRESHOLD = '0.005';
```
Comment (cermakjiri) [inline suite-common/token-definitions/src/antiFraud.ts:51]: is it based on something? It so, could you provide the context in the comment?

File: suite-common/token-definitions/src/antiFraud.ts [hunk 13]
```diff
@@ -39,16 +108,144 @@ export const getIsFakeTokenPhishing = (
...
+type NetworkPhishingDetectors = Map<NetworkType, PhishingDetectorFn[]>;
+
+const phishingDetectors: NetworkPhishingDetectors = new Map([
+    ['ethereum', [detectors.dustValue, detectors.zeroValue, detectors.fakeToken]],
+    ['ripple', [detectors.dustValue]],
+    ['cardano', [detectors.dustValue, detectors.fakeToken]],
+    ['solana', [detectors.dustValue, detectors.fakeToken]],
+    ['stellar', [detectors.dustValue, detectors.fakeToken, detectors.unknownTx]],
+    ['tron', [detectors.dustValue, detectors.fakeToken]],
+]);
```
Comment (cermakjiri) [inline suite-common/token-definitions/src/antiFraud.ts:137]: Nice flexible and clear composition 👍

File: suite-common/token-definitions/src/antiFraud.ts [hunk 14]
```diff
@@ -39,16 +108,144 @@ export const getIsFakeTokenPhishing = (
...
-// NOTE: This function determins, for which symbols there are filters in the UI to hide / display spam transactions
+export const getIsUnknownTxPhishing: PhishingDetectorFn = ({ transaction }) =>
+    transaction.type === 'unknown';
+
+const detectors = {
+    dustValue: getIsDustValuePhishing,
+    zeroValue: getIsZeroValuePhishing,
+    fakeToken: getIsFakeTokenPhishing,
+    unknownTx: getIsUnknownTxPhishing,
+} as const;
```
Comment (cermakjiri) [inline suite-common/token-definitions/src/antiFraud.ts]:
```suggestion
} as const satisfies Record<string, PhishingDetectorFn>;
```

File: suite-common/token-definitions/src/antiFraud.ts [hunk 15]
```diff
@@ -39,16 +108,144 @@ export const getIsFakeTokenPhishing = (
...
+const getTransactionAmountInFiat = ({
+    transaction,
+    amount,
+    contractAddress,
+    decimals,
+    historicRates,
+}: GetTransactionAmountInFiatProps) => {
+    if (amount === '') return '0';
+
+    const fiatRateKey = getFiatRateKey(transaction.symbol, 'usd', contractAddress);
```
Comment (cermakjiri) [inline suite-common/token-definitions/src/antiFraud.ts]: If these utils are fixed only to the `usd` currency, could you please add it to some constant / config so it's easy to adjust if needed?

Comment (cermakjiri) [reply suite-common/token-definitions/src/antiFraud.ts]: Might be a good idea to put it together with https://github.com/trezor/trezor-suite/pull/25263/changes#r2916924634

File: scripts/circular-dependencies/madge-snapshot.txt [hunk 16]
```diff
@@ -62,5 +62,6 @@ packages/suite/src/views/dashboard/AssetsView/AssetTable/AssetTable.tsx > packag
...
-suite-common/wallet-core/src/transactions/transactionsSelectors.ts > suite-common/wallet-core/src/transactions/transactionsReducer.ts > suite-common/wallet-core/src/transactions/transactionsThunks.ts
-suite-common/wallet-core/src/transactions/transactionsSelectors.ts > suite-common/wallet-core/src/transactions/transactionsReducer.ts > suite-common/wallet-core/src/transactions/transactionsThunks.ts > suite-common/wallet-core/src/send/sendFormEthereumThunks.ts
+suite-common/wallet-core/src/transactions/transactionsSelectors.ts > suite-common/wallet-core/src/fiat-rates/fiatRatesSelectors.ts
+suite-common/wallet-core/src/transactions/transactionsSelectors.ts > suite-common/wallet-core/src/fiat-rates/fiatRatesSelectors.ts > suite-common/wallet-core/src/transactions/transactionsReducer.ts > suite-common/wallet-core/src/transactions/transactionsThunks.ts
+suite-common/wallet-core/src/transactions/transactionsSelectors.ts > suite-common/wallet-core/src/fiat-rates/fiatRatesSelectors.ts > suite-common/wallet-core/src/transactions/transactionsReducer.ts > suite-common/wallet-core/src/transactions/transactionsThunks.ts > suite-common/wallet-core/src/send/sendFormEthereumThunks.ts
```
Comment (cermakjiri) [inline scripts/circular-dependencies/madge-snapshot.txt]: I don't mind type cir. ref., there should be fine but ESM cir. dep. are hell and will come back to us if we ignore them in form unexpected bugs (i.e. undefined ESM imports) or memory leak. Let's please take a while to fix it. 

From what I can see:
- `fiatRatesSelectors` <--> `transactionsSelectors` are interconnected  
- If you move the `selectTransactionsWithMissingRates` from `fiatRatesSelectors` to `transactionsSelectors`, you cancel the dependency of `fiatRatesSelectors` on `transactionsSelectors`. That should be it, right?

File: suite-common/wallet-core/src/transactions/transactionsSelectors.ts [hunk 17]
```diff
@@ -135,20 +138,54 @@ export const selectTransactionConfirmations = (
...
+        selectPhishingTransactionsContext(state, accountKey, transaction.symbol);
 
-    return getIsPhishingTransaction(transaction, tokenDefinitions);
+    return getIsPhishingTransaction({
+        transaction,
+        tokenDefinitions,
+        historicRates,
+        txsMarkedAsNotScam,
+    });
 };
```
Comment (cermakjiri) [inline suite-common/wallet-core/src/transactions/transactionsSelectors.ts:201]: memo (`createMemoizedSelector`) might be a good idea here, the result will be a quite stable, right (i.e. given tx is phishing tx or not)?

File: packages/suite/src/components/wallet/Pagination.tsx (hunk 10 above)
Comment (TomasBoda) [reply packages/suite/src/components/wallet/Pagination.tsx]: I was playing with this component because it made the app crash when no transactions were present. However, I fixed it a few code lines above and this is just a redundancy. Changed it back to `Array(total)`, it works fine

File: packages/suite/src/views/wallet/transactions/TransactionList/useFetchTransactions.ts (hunk 11 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/transactions/TransactionList/useFetchTransactions.ts]: done: changed to `isPhishingTransactions` as well as changed all `getIs...` functions in the `antiFraud.ts` file to `is...`

File: suite-common/token-definitions/src/antiFraud.ts (hunk 12 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/antiFraud.ts:51]: done: added some more context

File: suite-common/token-definitions/src/antiFraud.ts (hunk 14 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/antiFraud.ts]: done

File: suite-common/token-definitions/src/antiFraud.ts (hunk 15 above)
Comment (TomasBoda) [reply suite-common/token-definitions/src/antiFraud.ts]: done

File: scripts/circular-dependencies/madge-snapshot.txt (hunk 16 above)
Comment (TomasBoda) [reply scripts/circular-dependencies/madge-snapshot.txt]: done

File: suite-common/wallet-core/src/transactions/transactionsSelectors.ts (hunk 17 above)
Comment (TomasBoda) [reply suite-common/wallet-core/src/transactions/transactionsSelectors.ts:201]: I've been trying to make it work but with little success. I'll investigate further

Comment (cermakjiri) [reply suite-common/wallet-core/src/transactions/transactionsSelectors.ts:201]: I guess you might struggle with the args, right? It's quite unintuitive:

(Some random example with the passing the args):
```ts
export const selectPersistentDeviceDataById = createMemoizedSelector(
    [selectPersistentDeviceData, (_state, deviceId: TrezorDevice['id']) => deviceId],
    (persistentDeviceData, deviceId) =>
        persistentDeviceData.find(data => data.device_id === deviceId),
);
```

**Review by cermakjiri — APPROVED** [review]
Code-wise LGTM 👍

File: suite-common/wallet-core/src/transactions/transactionsSelectors.ts (hunk 17 above)
Comment (TomasBoda) [reply suite-common/wallet-core/src/transactions/transactionsSelectors.ts:201]: we decided to leave this as is for now
