### PR TITLE
Message system testing

### LINKED ISSUE #8493: Simplify testing of messaging system update
Currently it is not reliable and it takes time to properly test message updates.

Ideas:
- always fetch also local config (right now we fetch local only if remote config fetch failed) and compare what has higher `currentSequence` number (so developer don't need to block remote fetch in order to get the local one) ❌ 
- for same `currentSequence` number as current one, compare also `config.timestamp` (so developer don't need to bump sequence for testing, just the timestamp) ❌ 
- add easy possibility to remove current config from state – button in debug menu? Or just document deleting from storage?
- describe nicely in documentation how to test it locally and how to test it on builds from CI

### PR DESCRIPTION
**Pull request by izmy**
## Description

- Added a toggle to switch between remote and local message system config
- Introduced tooling for manual message injection and preview

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/8493

## Screenshots:

image

image

image

## Videos:

https://github.com/user-attachments/assets/15187765-bddf-4fe1-936c-99a9610e61ab

https://github.com/user-attachments/assets/33870737-7d7a-43df-ade6-e6fb93ef5cdf

https://github.com/user-attachments/assets/25e3dff1-e7f5-438e-b995-e7fb9d2292f3

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/message-system-testing&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/message-system-testing&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/message-system-testing&lookback=7)

### CODE REVIEW

File: suite-common/message-system/src/messageSystemUtils.ts [hunk 1]
```diff
@@ -327,3 +330,121 @@ export const resolveMessageContent = (localizedMessages: Localization, language:
...
+        case 'transport':
+            return { bridge: '*', webusbplugin: '*' };
+
+        case 'settings':
+            return [{ tor: false }];
+
+        case 'devices':
+            return [
+                {
+                    model: 'T',
```
Comment (tomasklim) [inline suite-common/message-system/src/messageSystemUtils.ts]:
```suggestion
                    model: 'T3T1',
```

File: suite-common/message-system/src/messageSystemUtils.ts [hunk 2]
```diff
@@ -327,3 +330,121 @@ export const resolveMessageContent = (localizedMessages: Localization, language:
...
+                    firmwareRevision: '',
+                    firmware: '*',
+                    bootloader: '*',
+                    variant: '*',
+                    vendor: 'trezor.io',
+                },
+            ];
+
+        case 'countryCodes':
+            return ['US'];
```
Comment (tomasklim) [inline suite-common/message-system/src/messageSystemUtils.ts]:
```suggestion
            return ['CZ'];
```

so that it works without change on our VPN

File: suite-common/message-system/src/messageSystemUtils.ts (hunk 1 above)
Comment (tomasklim) [reply suite-common/message-system/src/messageSystemUtils.ts]: please change to internal model in tests

File: suite-common/message-system/src/messageSystemThunks.ts [hunk 3]
```diff
@@ -17,17 +18,16 @@ import {
...
+    selectMessageSystemConfigSource,
     selectMessageSystemCurrentSequence,
     selectMessageSystemTimestamp,
 } from './messageSystemSelectors';
 import { jws as configJwsLocal } from '../files/config.v1';
 
-// Enable this for local development purposes:
-// set to true to always fetch local JWS
-const FORCE_LOCAL_JWS = false;
+export const messageSystemPolling = createPollingController();
```
Comment (tomasklim) [inline suite-common/message-system/src/messageSystemThunks.ts]: What is this good for?

**Review by tomasklim — COMMENTED** [review]
Epic! Please update message system readme

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemInfo.tsx [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+        },
+        {
+            field: 'category',
+            required: <Icon name="checkCircleFilled" variant="primary" />,
+            description: 'Where the message will appear',
+            allowed: (
+                <>
+                    <Badge variant="tertiary">banner</Badge>
+                    <Badge variant="tertiary">context</Badge>
+                    <Badge variant="tertiary">modal</Badge>
```
Comment (tomasklim) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemInfo.tsx:42]: not yet implemented

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemInfo.tsx [hunk 5]
```diff
@@ -0,0 +1,194 @@
...
+                </>
+            ),
+        },
+        {
+            field: 'category',
+            required: <Icon name="checkCircleFilled" variant="primary" />,
+            description: 'Where the message will appear',
+            allowed: (
+                <>
+                    <Badge variant="tertiary">banner</Badge>
```
Comment (tomasklim) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemInfo.tsx:40]: can you use somehow validate the values by types from `messageSystem.ts`? so that it yells in case of changes

File: suite-common/suite-utils/src/pollingController.ts [hunk 6]
```diff
@@ -0,0 +1,35 @@
+type PollingCallback = () => void;
+
+export const createPollingController = () => {
+    let intervalId: ReturnType<typeof setInterval> | null = null;
+    let callback: PollingCallback | null = null;
```
Comment (matusbalascak) [inline suite-common/suite-utils/src/pollingController.ts]: It doesn't seem like this variable is necessary, it is just assigned in `start`, but never used.

File: suite-common/message-system/src/messageSystemTypes.ts [hunk 7]
```diff
@@ -58,6 +61,14 @@ export const Feature = {
     dashboardPromoBanner: 'dashboard.promoBanner',
 } as const;
 
+export const FEATURE_LIST = Object.values(Feature)
```
Comment (matusbalascak) [inline suite-common/message-system/src/messageSystemTypes.ts]: It would be more fitting to put `FEATURE_LIST` and `CONTEXT_PATTERNS` into `messageSystemConstants.ts` instead of `messageSystemTypes.ts`.

File: suite-common/message-system/src/messageSystemTypes.ts [hunk 8]
```diff
@@ -58,6 +61,14 @@ export const Feature = {
...
+    .flatMap(value =>
```
Comment (matusbalascak) [inline suite-common/message-system/src/messageSystemTypes.ts]: It'd be better to use `.flatMap<string>` instead of `as string[]` type cast after `sort`.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm.tsx [hunk 9]
```diff
@@ -0,0 +1,251 @@
...
+
+export const MessageSystemForm = () => {
+    const popoverRef = useRef<PopoverRef>(null);
+    const [showForm, setShowForm] = useState(false);
+    const [formData, setFormData] = useState<string>(DEFAULT_ACTION);
+    const [parsedData, setParsedData] = useState<Action | null>(null);
+    const [jsonError, setJsonError] = useState<string | null>(null);
+    const dispatch = useDispatch();
+
+    useEffect(() => {
```
Comment (matusbalascak) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm.tsx]: Nitpick, but I think it would be nice to limit effects usage where not needed. You can instead create a function `handleFormData` where you would put this logic and also call `setFormData` there. You can then use this function instead of calling `setFormData` directly.

**Comment by tomasklim** [comment]
@coderabbitai review

**Comment by pavelmario** [comment]
@izmy , I have tested this improvement and it looks really cool. However, it does not seem to be working correctly while changing the languages as the message always stays in English.

The message:

`{
  "conditions": [
    {
      "browser": {
        "firefox": "*",
        "chrome": "*",
        "chromium": "*"
      }
    }
  ],
  "message": {
    "id": "5bbbeb12-4492-4842-bcaf-7385ed9d02cf",
    "priority": 100,
    "dismissible": true,
    "variant": "critical",
    "category": "banner",
    "content": {
      "en": "EN Critical",
      "cs": "CS Critical",
      "es": "ES Critical",
      "de": "DE Critical",
      "fr": "FR Critical",
      "pt": "PT Critical"
    }
  }
}`

Screenshots:

03_cs
02_es
01_en

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemInfo.tsx (hunk 5 above)
Comment (izmy) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemInfo.tsx:40]: done... I did a complex validation using yup

File: suite-common/suite-utils/src/pollingController.ts (hunk 6 above)
Comment (izmy) [reply suite-common/suite-utils/src/pollingController.ts]: true... removed

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm.tsx (hunk 9 above)
Comment (izmy) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm.tsx]: I reworked the entire `useEffect` for validation, so now I think it's necessary to use it without moving the logic into a function

**Comment by izmy** [comment]
> @izmy , I have tested this improvement and it looks really cool. However, it does not seem to be working correctly while changing the languages as the message always stays in English.
> 
> The message:
> 
> `{ "conditions": [ { "browser": { "firefox": "*", "chrome": "*", "chromium": "*" } } ], "message": { "id": "5bbbeb12-4492-4842-bcaf-7385ed9d02cf", "priority": 100, "dismissible": true, "variant": "critical", "category": "banner", "content": { "en": "EN Critical", "cs": "CS Critical", "es": "ES Critical", "de": "DE Critical", "fr": "FR Critical", "pt": "PT Critical" } } }`
> 

It was a different bug unrelated to my PR: https://github.com/trezor/trezor-suite/pull/20875

File: suite-common/message-system/src/messageSystemThunks.ts (hunk 3 above)
Comment (izmy) [reply suite-common/message-system/src/messageSystemThunks.ts]: It’s a tiny wrapper around setInterval that gives us safe control over polling
- Ensures only one timer runs (no duplicate intervals after re-init).
- Provides start/stop/restart; restart does an immediate fetch before scheduling.

File: suite-common/message-system/src/messageSystemValidation.ts [hunk 10]
```diff
@@ -0,0 +1,229 @@
+import type {
```
Comment (tomasklim) [inline suite-common/message-system/src/messageSystemValidation.ts:1]: nice!

**Review by tomasklim — COMMENTED** [review]
Please add info about this great tool into `docs/features/message-system.md`

File: packages/suite/package.json [hunk 11]
```diff
@@ -124,6 +124,7 @@
         "redux-thunk": "^3.1.0",
         "semver": "^7.7.1",
         "styled-components": "^6.1.19",
+        "uuid": "^11.1.0",
```
Comment (Lemonexe) [inline packages/suite/package.json:127]: :memo: [10kB](https://bundlephobia.com/package/uuid@11.1.0), that's ok (just noting)

File: suite-common/suite-utils/src/pollingController.ts [hunk 12]
```diff
@@ -0,0 +1,39 @@
+type PollingCallback = () => Promise<void> | void;
+
+export const createPollingController = () => {
+    let intervalId: ReturnType<typeof setInterval> | null = null;
```
Comment (Lemonexe) [inline suite-common/suite-utils/src/pollingController.ts]: nit: use [this type](https://github.com/trezor/trezor-suite/blob/3f34981e5d2536fda9afc8616bb5647702d74898/packages/type-utils/src/timeout.ts) for consistency

File: suite-common/suite-utils/src/pollingController.ts [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+    let running = false;
+
+    const start = (cb: PollingCallback, intervalMs: number) => {
```
Comment (Lemonexe) [inline suite-common/suite-utils/src/pollingController.ts]: don't use unnecessary abbreviations please :pray: 
```suggestion
    const start = (callback: PollingCallback, intervalMs: number) => {
```

File: suite-common/suite-utils/src/pollingController.ts [hunk 14]
```diff
@@ -0,0 +1,39 @@
...
+        start(cb, intervalMs);
+    };
+
+    return {
+        start,
+        stop,
+        restart,
+        isRunning: () => intervalId !== null,
+    };
+};
```
Comment (Lemonexe) [inline suite-common/suite-utils/src/pollingController.ts]: overall: why is this not a class, instantiated with `new PollingController`?

Ok, it works to use just the function scope to  hold the state `intervalId` and `running`, but it's my opinion that using class (or constructor) would make it clearer that this is a factory for a bunch of stateful function. The object returned from this factory does not hold the state itself, so the fact that it relies on fn scope is a bit obscured.

(for examle `setInterval` itself is also a plain fn, but it returns handle, does not hold the state itself)

File: suite-common/suite-utils/src/pollingController.ts [hunk 15]
```diff
@@ -0,0 +1,39 @@
...
+    let running = false;
+
+    const start = (cb: PollingCallback, intervalMs: number) => {
+        if (intervalId) return;
+        intervalId = setInterval(async () => {
+            if (running) return;
+            running = true;
+            try {
+                await cb();
+            } finally {
```
Comment (Lemonexe) [inline suite-common/suite-utils/src/pollingController.ts:19]: Currently it silences errors. For debugging purposes, how about this? 
```suggestion
            } catch(err) { console.error(err); } finally {
```

File: suite-common/suite-utils/src/pollingController.ts [hunk 16]
```diff
@@ -0,0 +1,39 @@
...
+    const stop = () => {
+        if (intervalId) {
+            clearInterval(intervalId);
+            intervalId = null;
+        }
+    };
+
+    const restart = async (cb: PollingCallback, intervalMs: number) => {
+        stop();
+        await cb();
```
Comment (Lemonexe) [inline suite-common/suite-utils/src/pollingController.ts]: nit: stop & restart do not care if it might be `running` right now, but no need to implement it, it would be overkill

File: packages/suite/src/views/settings/SettingsDebug/MessageSystemConfigSourceSelect.tsx [hunk 17]
```diff
@@ -0,0 +1,60 @@
...
+    const onChange = useCallback(
+        (value: MessageSystemConfigSource) => {
+            dispatch(messageSystemActions.setConfigSource(value));
+            dispatch(initMessageSystemThunk());
+        },
+        [dispatch],
+    );
+
+    return (
+        <SettingsSectionItem anchorId={SettingsAnchor.AddressDisplay}>
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystemConfigSourceSelect.tsx]: this is not the right anchor. In debug settings I think we don't need anchors, please remove.

File: suite-common/message-system/src/messageSystemUtils.ts [hunk 18]
```diff
@@ -327,3 +330,121 @@ export const resolveMessageContent = (localizedMessages: Localization, language:
...
+                    feature: [
+                        {
+                            domain: '',
+                            flag: true,
+                        },
+                    ],
+                };
+            case 'banner':
+            default:
+                return {};
```
Comment (Lemonexe) [inline suite-common/message-system/src/messageSystemUtils.ts]: this is not type exhaustive, please `return exhaustive(type)`.

:point_right:  But even better yet, you can rewrite the function with switch case to a POJO, and make it exhaustive simply by typing as `Record<Category, Partial<Message>>` :slightly_smiling_face:

File: suite-common/message-system/src/messageSystemUtils.ts [hunk 19]
```diff
@@ -327,3 +330,121 @@ export const resolveMessageContent = (localizedMessages: Localization, language:
...
+    return {
+        message: {
+            ...baseMessage,
+            ...extraFields,
+        },
+        conditions: [{}],
+    };
+};
+
+export const getDefaultConditionValue = (key: string) => {
```
Comment (Lemonexe) [inline suite-common/message-system/src/messageSystemUtils.ts]: Declarative typing would be appreciated :pray: I believe this would be appropriate?
```suggestion
export const getDefaultConditionValue = (key: keyof Condition): Condition[keyof Condition] => {
```

File: suite-common/message-system/src/messageSystemUtils.ts [hunk 20]
```diff
@@ -327,3 +330,121 @@ export const resolveMessageContent = (localizedMessages: Localization, language:
...
+                    variant: '*',
+                    vendor: '*',
+                },
+            ];
+
+        case 'countryCodes':
+            return ['CZ'];
+
+        default:
+            return {};
```
Comment (Lemonexe) [inline suite-common/message-system/src/messageSystemUtils.ts]: Once the fn is typed as I suggested above, `exhaustive(key)` would again be better, at which point I realized that this whole function can also be rewritten as object typed
as `Record<keyof Condition, Condition[keyof Condition]>`

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 21]
```diff
@@ -0,0 +1,492 @@
...
+                        <Column flex="1" gap={spacings.md}>
+                            <MessageDetail message={message} />
+                            <Divider color="backgroundNeutralBold" />
+                            <MessageConditions conditions={conditions} />
+                        </Column>
+                        <Column gap={spacings.xs}>
+                            <MessageInfo
+                                message={message}
+                                allValidMessages={allValidMessages}
+                                isInApp={allInAppIds[message.id]}
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: nit: teeechnicaly this isn't type safe due to TS limitations.
`allInAppIds` is `Record<string, boolean>` but accessing allInAppIds[string] is not guaranteed to yield boolean, it can be undefined.
It'd be cleaner to simply use `!!`.

There will be no problem though as it's only tested for truthiness, so it's a smol nit.

File: suite-common/message-system/src/messageSystemSelectors.ts [hunk 22]
```diff
@@ -137,6 +140,11 @@ export const selectIsFeatureDisabled = (
     return featureFlag !== undefined ? !featureFlag : (defaultValue ?? false);
 };
 
+export const selectAllMessages = (state: MessageSystemRootState) =>
+    state.messageSystem.config?.actions.map(a => a.message) ?? [];
```
Comment (Lemonexe) [inline suite-common/message-system/src/messageSystemSelectors.ts]: this is unused, remove pls

File: suite-common/message-system/src/messageSystemReducer.ts [hunk 23]
```diff
@@ -52,9 +56,18 @@ export const prepareMessageSystemReducer = createReducerWithExtraDeps(
...
                 state.currentSequence = config.sequence;
+
+                const prevInAppActions =
+                    state.config?.actions?.filter(a => !!state.inAppIds[a.message.id]) ?? [];
+                const incomingFileActions = config.actions ?? [];
+
+                state.config = {
+                    ...config,
+                    actions: [...prevInAppActions, ...incomingFileActions],
+                };
```
Comment (Lemonexe) [inline suite-common/message-system/src/messageSystemReducer.ts:81]: shouldn't you also update `state.inAppIds` with `incomingFileActions`?

File: suite-common/message-system/src/messageSystemReducer.ts [hunk 24]
```diff
@@ -19,6 +19,10 @@ const initialState: MessageSystemState = {
     dismissedMessages: {},
 
     validExperiments: [],
+
+    configSource: 'remote',
+
+    inAppIds: {},
```
Comment (Lemonexe) [inline suite-common/message-system/src/messageSystemReducer.ts]: name is not clear to me until I delve into the code implementation.
I'd suggest something like `loadedMessageIds`.

But really, does this have to be its own state variable? It's not a unique data, it's directly derived from messages.
IIUC it's only "caching", which could be solved easily by memoizedSelector from messages.
If you decide to go this way, ignore all my other comments pertaining `inAppIds`

:thought_balloon:  Also, performance is not really important in debug settings, is it?

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 25]
```diff
@@ -0,0 +1,492 @@
...
+                ))}
+            </Column>
+        </Modal>
+    );
+};
+
+export const MessageSystemDebugInfo = () => {
+    const config = useSelector(selectMessageSystemConfig);
+    const allValidMessages = useSelector(selectAllValidMessages);
+    const allInAppIds = useSelector(selectAllInAppIds);
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: it's useless to select both of these here, only to pass them via props to `MessageModal`.
Select them in `MessageModal` instead.

**Review by Lemonexe — COMMENTED** [review]
CR WIP, just dumping some comments.

File: suite-common/message-system/src/messageSystemReducer.ts (hunk 23 above)
Comment (Lemonexe) [reply suite-common/message-system/src/messageSystemReducer.ts:81]: Note: practically this means that you cannot locally delete messages that are loaded from your selected source.
You can only Remove those you added locally yourself.
When I load app, `state.inAppIds = {}`

EDIT:
now I see it [was probably intentional.](https://github.com/trezor/trezor-suite/blob/8c6f96b1920dfac0a8dc0bfddd2f9c7e3706ea66/packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx#L300) then the naming ([my other comment](https://github.com/trezor/trezor-suite/pull/20457#discussion_r2304086731)) should be different, like `manuallyAddedMessageIds`, but I'm not 100% sure what is the intention here.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 26]
```diff
@@ -0,0 +1,492 @@
...
+    onCategoryChange,
+}: MessageFiltersProps) => (
+    <Row alignItems="center" justifyContent="space-between" gap={spacings.sm}>
+        <SelectBar
+            selectedOption={selectedCategory}
+            options={[...CATEGORY_FILTER_OPTIONS]}
+            size="small"
+            onChange={value => {
+                onCategoryChange(value);
+            }}
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: nit: simplify
```suggestion
            onChange={onCategoryChange}
```

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 27]
```diff
@@ -0,0 +1,492 @@
...
+            bottomContent={<MessageSystemForm />}
+        >
+            <Column gap={spacings.sm}>
+                <MessageFilters
+                    showActive={showActive}
+                    onToggleActive={() => setIsActive(prev => !prev)}
+                    selectedCategory={selectedCategory}
+                    onCategoryChange={category => {
+                        setSelectedCategory(category);
+                    }}
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: nit: simplify
```suggestion
                    onCategoryChange={setSelectedCategory}
```

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 28]
```diff
@@ -0,0 +1,492 @@
...
+                iconName="translate"
+            >
+                <div>
+                    {Object.entries(messages)
+                        .filter(([lang]) => lang === 'en')
+                        .map(([lang, text]) => (
+                            <div key={lang}>
+                                <strong>{lang}:</strong> {text}
+                            </div>
+                        ))}
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: I think this can be simplified with `.find`, which will make it clear that we only expect one of them.
`filter` and `map` sound like there will be more of them, but that is impossible, JS does not allow duplicate keys in an object.
:thought_balloon:  JSON does allow it, but parsing the JSON only keeps the last key.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 29]
```diff
@@ -0,0 +1,492 @@
...
+    return conditions.map(({ environment, os, devices, settings, countryCodes }, index) => (
+        <Column key={index} gap={spacings.sm}>
+            <Row gap={spacings.sm} alignItems="flex-start">
+                <InfoItem label="Environment" iconName="devices" variant="default">
+                    {environment ? (
+                        <ul>
+                            {Object.entries(environment).map(([key, value]) => (
+                                <InfoItem
+                                    key={key}
+                                    label={key.charAt(0).toUpperCase() + key.slice(1)}
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: nit: `import { capitalizeFirstLetter } from '@trezor/utils';`

Same for the two subsequent blocks.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 30]
```diff
@@ -0,0 +1,492 @@
...
+                                    direction="row"
+                                >
+                                    {String(value)}
+                                </InfoItem>
+                            ))}
+                        </ul>
+                    ) : (
+                        '-'
+                    )}
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: This block is almost identical to the previous Environment section, and the subsequent Setting section.
Opportunity to extract component `MessageConditionsPerCategory`, which will only need `os` as prop.

The only difference I notice between these blocks is that Settings are not wrapped in `<ul>`, but I think they can be too for consistency.

You could include the line 238 too `<InfoItem label="Operating System" iconName="browsers" variant="default">` but it would need more props, so not such a useful abstraction.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 31]
```diff
@@ -0,0 +1,492 @@
...
+                <MessageModal
+                    actions={config.actions}
+                    allValidMessages={allValidMessages}
+                    allInAppIds={allInAppIds}
+                    onCloseModal={handleCloseValidMessages}
+                />
+            )}
+        </>
+    );
+};
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx:44]: Please split the subcomponents into separate files for easier navigation :pray:

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 32]
```diff
@@ -0,0 +1,492 @@
...
+    if (!devices || devices.length === 0) {
+        return (
+            <InfoItem label="Devices" iconName="devices" variant="default">
+                -
+            </InfoItem>
+        );
+    }
+
+    const firstDevice = devices[0];
+    const restDevices = devices.slice(1);
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: I don't see the need to display `firstDevice` outside of the collapsible.
It makes sense for languages where `en` is default, but the listed device condition are equally important; this begets the question "why is this device condition more important than others?" but it isn't, so it's mildly confusing.
It's just my opinion that it will be clearer to list them equally in Collapsible. Plus it simplifies the code.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 33]
```diff
@@ -0,0 +1,492 @@
...
+                <div>
+                    <strong>{firstDevice.model}</strong> (firmware: {firstDevice.firmware},
+                    bootloader: {firstDevice.bootloader})
+                </div>
+
+                <Collapsible.Content>
+                    {restDevices.map((d, i) => (
+                        <div key={i}>
+                            <strong>{d.model}</strong> (firmware: {d.firmware}, bootloader:{' '}
+                            {d.bootloader})
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: the condition has other properties, which are not listed here. I don't if it's important, but there is a lot of space so why not list them?
image

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx [hunk 34]
```diff
@@ -0,0 +1,492 @@
...
+                          )
+                        : '-'}
+                </InfoItem>
+
+                <InfoItem label="Country codes" iconName="globe" variant="default">
+                    {countryCodes ? countryCodes.join(', ') : '-'}
+                </InfoItem>
+            </Row>
+            <MessageDevices devices={devices} />
+        </Column>
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: Some conditions are missing here: duration, browser, transport, settings
They are not used so often, so maybe there is no need to have them here, but at least write a TODO

File: packages/suite/src/actions/suite/storageActions.ts [hunk 35]
```diff
@@ -503,14 +503,17 @@ export const forgetDeviceMetadataError =
...
+        getState().messageSystem;
 
     db.addItem(
         'messageSystem',
         {
             config,
             currentSequence,
             dismissedMessages,
+            configSource,
+            inAppIds,
```
Comment (Lemonexe) [inline packages/suite/src/actions/suite/storageActions.ts]: what value is there in persisting `inAppIds` if the messages themselves are not persisted?

File: suite-common/message-system/schema/config.schema.v1.json [hunk 36]
```diff
@@ -130,6 +131,9 @@
                                         },
                                         "flag": {
                                             "type": "boolean"
+                                        },
+                                        "visibleBanner": {
+                                            "type": "string"
```
Comment (Lemonexe) [inline suite-common/message-system/schema/config.schema.v1.json:136]: please don't define this in schema, it makes it look like a generic property available for all feature flags.
But feature flags can have [an arbitrary payload](https://github.com/trezor/trezor-suite/blob/8c6f96b1920dfac0a8dc0bfddd2f9c7e3706ea66/suite-common/suite-types/src/messageSystem.ts#L409), which is typed as unknown, and has to be processed as such in  the consuming code: [DashboardPromoBanner](https://github.com/trezor/trezor-suite/blob/d2e036284e9cbc1c8ae4994346a177665b673f74/packages/suite/src/views/dashboard/DashboardPromoBanner/DashboardPromoBanner.tsx#L21).
But these are ad-hoc properties relevant only to specific feature flag domain , and it's responsibility of the consuming code to handle it.

File: packages/react-utils/src/hooks/useTextareaCursorPosition.ts [hunk 37]
```diff
@@ -0,0 +1,64 @@
...
+
+        cleanupRef.current = () => {
+            document.removeEventListener('selectionchange', onSelectionChange);
+        };
+    }, []);
+
+    useEffect(() => () => cleanupRef.current?.(), []);
+
+    return { textareaRef, position };
+};
```
Comment (Lemonexe) [inline packages/react-utils/src/hooks/useTextareaCursorPosition.ts:64]: very nice :+1:

File: suite-common/message-system/src/messageSystemConstants.ts [hunk 38]
```diff
@@ -27,3 +41,62 @@ export const CONFIG_URL_REMOTE = {
     stable: `${CONFIG_URL_REMOTE_BASE}/stable/${JWS_CONFIG_FILENAME_REMOTE}`,
     develop: `${CONFIG_URL_REMOTE_BASE}/develop/${JWS_CONFIG_FILENAME_REMOTE}`,
 };
+
+export const FEATURE_LIST = Object.values(Feature)
+    .flatMap<string>(value =>
+        typeof value === 'string'
+            ? value
+            : Object.values(value).flatMap(v => (typeof v === 'string' ? v : Object.values(v))),
```
Comment (Lemonexe) [inline suite-common/message-system/src/messageSystemConstants.ts]: this is hardcoded level 2 recursion.
The reason why we need two levels is incidental – as that's how 
But there isn't any rule anywhere saying it can't be deeper, so writing recursive function would be better.

My main reason is that the code should convey clear meaning at first glance – why does it do what it does.

**Review by Lemonexe — COMMENTED** [review]
Dumping more comments.
So far I have reviewed everything except `MessageSystemForm + validation`.
Overall looks good, but I have a lot of codestyle, naming comments. Only a few doubts about functionality.

Anyway I'll finish the CR later, need to do other stuff RN.

File: suite-common/suite-utils/src/pollingController.ts (hunk 14 above)
Comment (izmy) [reply suite-common/suite-utils/src/pollingController.ts]: Good point. I chose a closure for simplicity, but making the state explicit is clearer. I’ve refactored it to a class (new PollingController()), keeping the same API and behavior.

File: suite-common/suite-utils/src/pollingController.ts (hunk 16 above)
Comment (izmy) [reply suite-common/suite-utils/src/pollingController.ts]: Noted. I’ll keep stop/restart simple and not handle in-flight ticks... we can add a wait-for-idle later if needed.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx (hunk 32 above)
Comment (izmy) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: Good point.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx (hunk 33 above)
Comment (izmy) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: Yea, you are right, I added other properties.

File: suite-common/message-system/schema/config.schema.v1.json (hunk 36 above)
Comment (izmy) [reply suite-common/message-system/schema/config.schema.v1.json:136]: Well, I’d like to keep this in the schema, because:

- Treat the schema as a contract, not just docs. Explicit optional props improve DX, codegen, and CI validation.
- It prevents drift/typos (unknown payload bags tend to accumulate ad-hoc keys).
- `visibleBanner` is optional, so it doesn’t force other flags to use it.
- If it were up to me, I would set `additionalProperties: false` 😀
- and I also discussed it with @jvaclavik - we agreed that a stricter scheme is better.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx (hunk 28 above)
Comment (izmy) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: heh, "en" is actually required, so I'll access it directly

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx (hunk 30 above)
Comment (izmy) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: Good catch!

File: suite-common/message-system/src/messageSystemReducer.ts (hunk 24 above)
Comment (izmy) [reply suite-common/message-system/src/messageSystemReducer.ts]: I changed it to `manuallyAddedMessageIds`.

File: suite-common/message-system/src/messageSystemReducer.ts (hunk 23 above)
Comment (izmy) [reply suite-common/message-system/src/messageSystemReducer.ts:81]: I keep `inAppIds`/`manuallyAddedMessageIds` because the message system polls new data and I need to persist it regularly, and I also want test messages to survive an app refresh.

File: packages/suite/src/actions/suite/storageActions.ts (hunk 35 above)
Comment (izmy) [reply packages/suite/src/actions/suite/storageActions.ts]: Messages are inside the config.

**Review by tomasklim — APPROVED** [review]

**Comment by jvaclavik** [comment]
This is awesome 😍 good job!

File: suite-common/message-system/src/messageSystemReducer.ts (hunk 23 above)
Comment (Lemonexe) [reply suite-common/message-system/src/messageSystemReducer.ts:81]: Right that makes sense! Thank you for renaming, this is much clearer :ok_hand:

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx (hunk 28 above)
Comment (Lemonexe) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemDebugInfo.tsx]: Even better :slightly_smiling_face:

File: suite-common/message-system/schema/config.schema.v1.json (hunk 36 above)
Comment (Lemonexe) [reply suite-common/message-system/schema/config.schema.v1.json:136]: Ok, my point was that it creates false expectation that `visibleBanner` is a property available for all feature flags, while the handling for it is specific only for `dashboardPromoBanner`.
In TS this would be easily solvable with a union of types per each feature flag, but JSON schema cannot do that. 
But I don't have a strong opinion about this.

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm/MessageSystemForm.tsx [hunk 39]
```diff
@@ -0,0 +1,177 @@
...
+    const formatJSON = useCallback(() => {
+        setFormData(JSON.stringify(parsedData, null, 2));
+    }, [parsedData]);
+
+    const availableConditionOptions = useMemo(() => {
+        if (!Array.isArray(parsedData?.conditions) || !parsedData.conditions[0]) {
+            return CONDITION_OPTIONS;
+        }
+
+        const bucket = parsedData.conditions[0] as Record<keyof Condition, unknown>;
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm/MessageSystemForm.tsx:96]: why is this called `bucket`? :bucket: what does that mean?

**Review by Lemonexe — COMMENTED** [review]
Finished CR ex-post, but have no more comments; the form was not as complex as I thought. It's great that you implemented all these features with only yup & JSON :slightly_smiling_face: 
Looking perfect :rocket:

File: packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm/MessageSystemForm.tsx (hunk 39 above)
Comment (izmy) [reply packages/suite/src/views/settings/SettingsDebug/MessageSystem/MessageSystemForm/MessageSystemForm.tsx:96]: That's probably AI noise 😄 I will rename it to `conditions` (because conditions in the message system is the array with an object and we (almost) always use only the first item from the array)
