### PR TITLE
Labeling bugs

### LINKED ISSUE #16069: Address label not showing in the coin control section
**Describe the bug**
In the "Receive" section I can add label to specific addresses. But is the coin control section these labels are not shown. I can see only addresses and labels belonging to specific UTXO

**Info:**

-   Suite Version: app 24.11.3
-   OS: Windows 10

**How to reproduce**

1. Select Bitcoin
2. Click on 'Receive'
3. Add label to any used address
4. Go back
5. Click on 'Send'
6. Activate Coin control
7. Label is not displayed. Only the address

**Expected behavior**
Instead or better next to the address the label should be displayed

### PR DESCRIPTION
**Pull request by komret**
#### 1st commit:
Fixes alignment.

before:
Screenshot 2025-02-28 at 17 51 57
after:
Screenshot 2025-02-28 at 17 51 47

#### 2nd commit:
Code cleanup, also was necessary after the first commit.
#### 3rd commit:
Resolve https://github.com/trezor/trezor-suite/issues/16069
#### 4th commit:
before:
Screenshot 2025-02-28 at 16 28 47
after:
Screenshot 2025-02-28 at 16 28 29

#### 5th commit:
Click doesn't propagate and checkbox is not checked.

before:

https://github.com/user-attachments/assets/27a5cc3d-3b9f-41ad-bc21-e7a830531ac1

after:

https://github.com/user-attachments/assets/79d21baa-cd95-4a60-b754-ff1edf100004

### CODE REVIEW

File: packages/suite/src/views/wallet/send/Options/BitcoinOptions/CoinControl/UtxoSelectionList/UtxoSelection/UtxoSelection.tsx [hunk 1]
```diff
@@ -34,15 +34,15 @@ const ROW_GAP = spacings.xxs;
 const LabelPart = styled.div`
     display: flex;
     align-items: center;
-    gap: ${ROW_GAP};
+    gap: ${ROW_GAP}px;
```
Comment (peter-sanderson) [inline packages/suite/src/views/wallet/send/Options/BitcoinOptions/CoinControl/UtxoSelectionList/UtxoSelection/UtxoSelection.tsx:37]: Not sure what is better but this can be also fixed by using `spacingsPx.xxs` for:

```ts:
const ROW_GAP = spacingsPx.xxs;`
```

Comment (peter-sanderson) [reply packages/suite/src/views/wallet/send/Options/BitcoinOptions/CoinControl/UtxoSelectionList/UtxoSelection/UtxoSelection.tsx:37]: I see it cannot, its used in contexteds wihtout Px (gap in Row , tec...)

**Review by peter-sanderson — APPROVED** [review]
