### PR TITLE
fix(trading): add option to disable hidden placeholder in TradingFiatAmount component

### LINKED ISSUE #23861: Transaction details, hiding balances not working completely
**Describe the bug**
Trade history details showing amount despite Hide balance feature ON 

**Info:**

- Remembered Wallet: yes
- Suite Version: desktop app, 25.11.3
- Browser: n/a
- Browser Installation Method: n/a
- OS: Ventura, 13.17.4
- Bridge: ?
- Firmware Version: T3, 2.9.4

**How to reproduce**

1. Go to Account (e.g., Bitcoin)
2. Click on Buy&Sell > Trade history 
3. Click on View details (one of the transactions)

**Expected behavior**
I would expect the amount (e.g., EUR) under _You pay_ would also be blurred.

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by sherpaPSX**
…

## Description
Implemented HiddenPlaceholder in the TradingFiatAmount component

## Notes for QA
Check if Fiat amount is hidden with Hidden balance feature on

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23861

## Screenshots:

image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/transactions-details&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/transactions-details&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingCryptoAmount.tsx [hunk 1]
```diff
@@ -52,7 +52,6 @@ export const TradingCryptoAmount = ({
                     value={amount}
                     symbol={coinSymbol}
                     contractAddress={contractAddress}
-                    disableHiddenPlaceholder
```
Comment (vytick) [inline packages/suite/src/views/wallet/trading/common/TradingCryptoAmount.tsx:55]: does this work correctly when blurring is disabled?

**Review by vytick — APPROVED** [review]
lgtm
