### PR TITLE
fix electron shortcuts

### LINKED ISSUE #634: Suite refreshed instead of Google Chrome
When I open Suite for Linux and go to chrome and refresh any page by pressing F5, Suite is refreshed instead of the browser. 

Google Chrome
Version 77.0.3865.90 (Official Build) (64-bit)

Suite build:
https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/310856504

Linux Mint 19.1 Cinnamon

### PR DESCRIPTION
**Pull request by slowbackspace**
fix https://github.com/trezor/trezor-suite/issues/634

tldr: `GlobalShorcuts` are really global, meaning Suite was capturing the cmd+R/F5 shortcuts even in case where Suite window was not focused (minimized, hidden under other windows, etc). I ended up using https://github.com/beakerbrowser/electron-localshortcut

### CODE REVIEW

File: packages/suite-desktop/src/electron.js [hunk 1]
```diff
@@ -80,12 +73,15 @@ const init = async () => {
             callback({ path: url });
         });
 
-        globalShortcut.register('f5', () => {
+        electronLocalshortcut.register(mainWindow, 'R', () => {
```
Comment (szymonlesisz) [inline packages/suite-desktop/src/electron.js]: cmd+R

Comment (szymonlesisz) [reply packages/suite-desktop/src/electron.js]: add shortcut for `win.openDevTools()`

**Review by vladimirvolek — APPROVED** [review]
