### PR TITLE
fix(wallet-utils): allow tokens without symbol and valid balance

### LINKED ISSUE #13322: Suite does not display tokens without symbol
From [slack conversation](https://satoshilabs.slack.com/archives/C03SRP8PSS2/p1720429988564829)

image

Test token:
`0xa1Ac2d8a57b70ff9637521F76D5733260c6F0f5a`

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- do not filter out any tokens
- use formatter which is used also for solana and cardano in case there is missing symbol
- ignore nonsense `toLowerCase`, there is another issue for that. Symbols can be mixed case

## Related Issue

Resolve  #13322

## Screenshots:
Screenshot 2024-07-14 at 20 30 54

### CODE REVIEW

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 1]
```diff
@@ -451,14 +452,16 @@ export const countUniqueCoins = (accounts: Account[]) => {
...
+        const symbol = formatTokenSymbol(t.symbol || t.contract);
+
+        return {
             ...t,
-            name: t.name || t.symbol,
-            symbol: t.symbol!.toLowerCase(),
-            balance: formatAmount(t.balance!, t.decimals),
-        }));
+            name: t.name || symbol,
+            symbol: symbol.toLowerCase(),
```
Comment (jvaclavik) [inline suite-common/wallet-utils/src/accountUtils.ts:461]: nitpick:

You have this in the description:
```
ignore nonsense toLowerCase, there is another issue for that. Symbols can be mixed case
```

So why do you use `toLowerCase` here or am I missing something?

**Review by jvaclavik — APPROVED** [review]
One comment but approving 👍

File: suite-common/wallet-utils/src/accountUtils.ts (hunk 1 above)
Comment (tomasklim) [reply suite-common/wallet-utils/src/accountUtils.ts:461]: I expressed myself poorly. 

The lowercase does not make sense but I am keeping it there just to be sure that it does not break anything, but it will be removed soon
