### PR TITLE
fix(suite-native): Date ordering

### LINKED ISSUE #7500: List of transaction: Order by date is not working
Items in transaction list should be ordered by date. The items in the month groups do not match with the group month.
E.g. Transactions from January are marked as December group - check the printscreen

Image

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/7500

## Screenshots:
image

### CODE REVIEW

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 1]
```diff
@@ -42,19 +42,17 @@ const generateTransactionDateKey = (d: Date) =>
...
 /* Convert date to string in YYYY-MM format */
 const generateTransactionMonthKey = (d: Date) => `${d.getFullYear()}-${d.getMonth() + 1}`;
 
-/** Parse Date object from a string in YYYY-MM format */
-export const parseTransactionMonthKey = (key: string) => {
-    const parts = key.split('-');
-    const d = new Date(Number(parts[0]), Number(parts[1]) - 1);
-    return d;
+/** Parse Date object from a string in YYYY-MM format to return localized month name */
+export const parseTransactionMonthKey = (key: string): string => {
```
Comment (Nodonisko) [inline suite-common/wallet-utils/src/transactionUtils.ts]: This should return only date object and that should be passed into formatter.

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-common/wallet-utils/src/__tests__/transactionUtils.test.ts [hunk 2]
```diff
@@ -24,7 +24,7 @@ describe('transaction utils', () => {
     });
 
     it('parseTransactionMonthKey', () => {
-        expect(parseTransactionMonthKey('2023-01')).toEqual(new Date(2023, 0));
+        expect(parseTransactionMonthKey('2023-00')).toEqual('January');
```
Comment (PeKne) [inline suite-common/wallet-utils/src/__tests__/transactionUtils.test.ts]: `January` should be equal to `2023-01`.

`function const generateTransactionMonthKey = (d: Date) => ${d.getFullYear()}-${d.getMonth() + 1}`
is adding +1 to the month value. You should subtract -1 inside the `parseTransactionMonthKey` function as it was. Then the test will pass without modification.

Now, all months are incorrectly shifted by one.

**Review by PeKne — CHANGES_REQUESTED** [review]

File: suite-common/wallet-utils/src/__tests__/transactionUtils.test.ts (hunk 2 above)
Comment (Nodonisko) [reply suite-common/wallet-utils/src/__tests__/transactionUtils.test.ts]: Good catch.

Comment (juriczech) [reply suite-common/wallet-utils/src/__tests__/transactionUtils.test.ts]: Yes. Problem is you didn't add month in localisation function which resulted in different month in the UI as discussed during pair programming. 

So again for @Nodonisko, I created formatter which returns month name and in that formatter I'm doing month addition so UI reflects real data.

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 3]
```diff
@@ -42,20 +43,16 @@ const generateTransactionDateKey = (d: Date) =>
...
+    const [year, month, day] = key.split('-');
+    return new Date(Number(year), Number(month) - 1, Number(day));
 };
 
-/* Convert date to string in YYYY-MM format */
-const generateTransactionMonthKey = (d: Date) => `${d.getFullYear()}-${d.getMonth() + 1}`;
+export type MonthKey = string & { __type: 'MonthKey' };
+const generateTransactionMonthKey = (d: Date): MonthKey =>
+    // Adding days because of time zones of UTC
+    addDays(startOfMonth(d), 1).toUTCString() as MonthKey;
```
Comment (PeKne) [inline suite-common/wallet-utils/src/transactionUtils.ts:53]: If `generateTransactionMonthKey` generates a string in a format like `2023-01-01T00:00:00.000Z`, do we even need it? Maybe we can just reuse the `generateTransactionDateKey` which returns similar output `2023-01-01`.

Comment (PeKne) [reply suite-common/wallet-utils/src/transactionUtils.ts:53]: Or maybe just rename `generateTransactionMonthKey` to something like `generateTransactionDateTimeKey`. This naming is confusing.

Comment (juriczech) [reply suite-common/wallet-utils/src/transactionUtils.ts:53]: No, because we need to have it in UTC format. If it's not in UTC, there will still be bug which was there when months were shifted by one. 

I can rename it but it's more confusing then before, because now there will be two functions with very similar name which makes it unclear why we're doing it. I think it was better name before, because it was generating month keys for ordering, but here's a fixup commit and let's see what others think. 

https://github.com/trezor/trezor-suite/pull/7506/commits/f03a8634cf9db18c1edd7a932eaca80f518dbd36

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 4]
```diff
@@ -42,20 +43,16 @@ const generateTransactionDateKey = (d: Date) =>
...
+    // Adding days because of time zones of UTC
+    addDays(startOfMonth(d), 1).toUTCString() as DatetimeKey;
 
-/** Parse Date object from a string in YYYY-MM format */
-export const parseTransactionMonthKey = (key: string) => {
-    const parts = key.split('-');
-    const d = new Date(Number(parts[0]), Number(parts[1]) - 1);
-    return d;
-};
+export const parseTransactionDateTimeKey = (key: DatetimeKey): Date => new Date(key);
```
Comment (Nodonisko) [inline suite-common/wallet-utils/src/transactionUtils.ts]: Please rename it back. It doesn't make sense now, it's still just `MonthKey` and you do not care if it uses datetime under-the-hood.

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-common/wallet-utils/src/transactionUtils.ts (hunk 4 above)
Comment (juriczech) [reply suite-common/wallet-utils/src/transactionUtils.ts]: Yeah, it didn't make sense to me either. Here's a fixup https://github.com/trezor/trezor-suite/pull/7506/commits/b351ac9637764d81724d8bd561357b2883db0ea0

**Review by PeKne — APPROVED** [review]

**Review by Nodonisko — APPROVED** [review]
Looks good now

**Review by Nodonisko — APPROVED** [review]
