### PR TITLE
Fix/device ready image

### LINKED ISSUE #9523: Fw installation - Device ready image
**Describe the bug**
- when you want to update fw, there is an image to switch to bootloader
- when you switch to bootloader, device is now ready but the image "switch to bootloader" is still there

**Info:**

-   Suite Version: 23.10.0

**How to reproduce**

1. Update fw

**Expected behavior**
I would expect different image or not image

**Screenshots**

Screenshot 2023-09-21 at 15 22 28

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Removed animation when user is able to install firmware.

Also did a small fix to spacing for light bulb inside modal that appears on smaller screen.

## Related Issue

Resolve #9523

## Screenshots:

Removed animation:
B6615A70-3540-4EA7-9988-4DC4DBCDFF39_4_5005_c

Light bulb before:
B7CABF12-440C-4F3E-8D96-2AB9129BD726_4_5005_c

Light bulb after:
B872B883-C4E7-43CA-AA4A-CB35364E60A9_4_5005_c

### CODE REVIEW

File: packages/suite/src/components/suite/modals/Modal/DefaultRenderer.tsx [hunk 1]
```diff
@@ -5,6 +5,11 @@ import { useGuide } from 'src/hooks/guide';
 import { useLayoutSize } from 'src/hooks/suite/useLayoutSize';
 import { useModalTarget } from 'src/support/suite/ModalContext';
 import { ModalEnvironment } from '../ModalEnvironment';
+import styled from 'styled-components';
+
+const StyledIcon = styled(Icon)`
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/Modal/DefaultRenderer.tsx]: it is broken on other places now 
Screenshot 2023-11-14 at 14 55 59

Comment (tomasklim) [reply packages/suite/src/components/suite/modals/Modal/DefaultRenderer.tsx]: Screenshot 2023-11-14 at 14 57 18
it looks like this bulb is and was broken in all headerless modals

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx [hunk 2]
```diff
@@ -41,15 +41,22 @@ const Wrapper = styled.div`
...
-        margin-left: 0;
-    }
+    ${({ isCentered }) =>
+        isCentered
+            ? css`
+                  margin: 0 auto;
+              `
+            : css`
+                  ${variables.SCREEN_QUERY.MOBILE} {
+                      margin-left: 0;
```
Comment (tomasklim) [inline packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: I would flip this. ABOVE_MOBILE add margin-left: 24px, otherwise no margin-left.

Or better:
Maybe we can just use `justify-content: space-around;` on the wrapper and we will not need those margins at all, I guess

Comment (AdamSchinzel) [reply packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: 0041d13bc91ffbff202dc1fdbc6e26c09c8c12ac

File: packages/suite/src/components/suite/modals/Modal/DefaultRenderer.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/Modal/DefaultRenderer.tsx]: I thought it will be a quick fix but probably not, created an issue for this - #9947

Comment (dahaca) [reply packages/suite/src/components/suite/modals/Modal/DefaultRenderer.tsx]: It will be misaligned in modals without a Header, so the ones which are not closable or with a `AbortButton`

**Review by tomasklim — APPROVED** [review]
