### PR TITLE
fix(suite-native): allow portfolio to sync accounts of connected device

### LINKED ISSUE #10255: It is not possible to sync coin from connected Trezor
Steps to reproduce:
1. Open App
2. Portfolio tracker is empty (no coins are synced)
3. Connect Trezor
4. Wait for discovery to finish
5. Pick some coin and copy the public address
6. Open the portfolio tracker and insert the address in syncing flow
7. App says that the coin is already synced

Expected behaviour: Coin from connected Trezor can be add to Portfolio tracker while the Trezor is connected

### PR DESCRIPTION
**Pull request by vytick**
allow syncing coins into portfolio from connected device

Resolves #10255

### CODE REVIEW

File: suite-common/wallet-core/src/accounts/accountsReducer.ts [hunk 1]
```diff
@@ -169,6 +169,21 @@ export const selectDeviceMainnetAccounts = memoize((state: AccountsRootState & D
     ),
 );
 
+export const selectDeviceAccountByDescriptorAndNetworkSymbol = (
```
Comment (juriczech) [inline suite-common/wallet-core/src/accounts/accountsReducer.ts]: This selector already exists, please remove and reuse the other one

**Review by juriczech — CHANGES_REQUESTED** [review]

**Comment by juriczech** [comment]
Can you please explain how is this pull request fixing the issue? As far as I know, functionality remains same, you just added duplication of selectors, no? 😅

**Review by juriczech — APPROVED** [review]
