### PR TITLE
fix(connect): handle malformed EIP-712 data

### LINKED ISSUE #5099: Stuck Trezor after sending malformed EIP712 input via Connect
**Describe the bug**
Sending an invalid EIP712 payload to Trezor will result in a frozen screen. 

**Info:**

-   Remembered Wallet: no
-   Suite Version: n/a
-   Browser: Firefox 97
-   OS: OSX
-   Bridge: 2.0.31
-   Firmware Version: TT 2.4.4 (unreleased)

**How to reproduce**

1. Unzip [ethtypedsign.html.gz](https://github.com/trezor/trezor-suite/files/8232775/ethtypedsign.html.gz)
2. Open
3. Click on 'Sign EIP 712'
4. Press first green arrow
5. Press second green arrow

**Expected behavior**
Go back to homescreen

**Screenshots**

https://user-images.githubusercontent.com/216917/157889764-883d0e67-ac51-4590-89ce-654c1f9870ab.mp4

**Additional context**

Putting the dirty payload into [connect explorer](https://suite.corp.sldev.cz/connect-explorer/extend-connect-explorer/#/method/ethereumSignTypedData) never touched the Trezor, potentially do to some validation?

<details>
<summary>Payload that doesn't error</summary>

```json
{
    "types": {
        "Coin": [
            {
                "name": "denom",
                "type": "string"
            },
            {
                "name": "amount",
                "type": "string"
            }
        ],
        "EIP712Domain": [
            {
                "name": "name",
                "type": "string"
            },
            {
                "name": "version",
                "type": "string"
            },
            {
                "name": "chainId",
                "type": "uint256"
            },
            {
                "name": "verifyingContract",
                "type": "string"
            },
            {
                "name": "salt",
                "type": "string"
            }
        ],
        "Fee": [
            {
                "name": "amount",
                "type": "Coin[]"
            },
            {
                "name": "gas",
                "type": "string"
            }
        ],
        "Msg": [
            {
                "name": "type",
                "type": "string"
            },
            {
                "name": "value",
                "type": "MsgValue"
            }
        ],
        "MsgValue": [
            {
                "name": "delegator_address",
                "type": "string"
            },
            {
                "name": "validator_address",
                "type": "string"
            },
            {
                "name": "amount",
                "type": "TypeAmount"
            }
        ],
        "Tx": [
            {
                "name": "account_number",
                "type": "string"
            },
            {
                "name": "chain_id",
                "type": "string"
            },
            {
                "name": "fee",
                "type": "Fee"
            },
            {
                "name": "memo",
                "type": "string"
            },
            {
                "name": "msgs",
                "type": "Msg[]"
            },
            {
                "name": "sequence",
                "type": "string"
            },
            {
                "name": "timeout_height",
                "type": "string"
            }
        ],
        "TypeAmount": [
            {
                "name": "denom",
                "type": "string"
            },
            {
                "name": "amount",
                "type": "string"
            }
        ]
    },
    "primaryType": "Tx",
    "domain": {
        "name": "Injective Web3",
        "version": "1.0.0",
        "chainId": 1,
        "verifyingContract": "cosmos",
        "salt": "1646906878039"
    },
    "message": {
        "account_number": "5712",
        "chain_id": "injective-1",
        "fee": {
            "amount": [
                {
                    "amount": "200000000000000",
                    "denom": "inj"
                }
            ],
            "gas": "400000"
        },
        "memo": "",
        "msgs": [
            {
                "type": "cosmos-sdk/MsgDelegate",
                "value": {
                    "amount": {
                        "amount": "100000000000000000",
                        "denom": "inj"
                    },
                    "delegator_address": "inj17vy49gw9xnx700z8zwqqv4exl2rgdhanv75c4r",
                    "validator_address": "injvaloper1w3psm8a9td2qz06s46cxss03mz5umxaxegvhhs"
                }
            }
        ],
        "sequence": "0",
        "timeout_height": "8545415"
    }
}
```

</details>

<details>
<summary>Payload which throws error</summary>

```json
{
  "types": {
      "Coin": [
          {
              "name": "denom",
              "type": "string"
          },
          {
              "name": "amount",
              "type": "string"
          }
      ],
      "EIP712Domain": [
          {
              "name": "name",
              "type": "string"
          },
          {
              "name": "version",
              "type": "string"
          },
          {
              "name": "chainId",
              "type": "uint256"
          },
          {
              "name": "verifyingContract",
              "type": "string"
          },
          {
              "name": "salt",
              "type": "string"
          }
      ],
      "Fee": [
          {
              "name": "gas",
              "type": "string"
          }
      ],
      "Msg": [
          {
              "name": "type",
              "type": "string"
          },
          {
              "name": "value",
              "type": "MsgValue"
          }
      ],
      "MsgValue": [
          {
              "name": "delegator_address",
              "type": "string"
          },
          {
              "name": "validator_address",
              "type": "string"
          },
          {
              "name": "amount",
              "type": "TypeAmount"
          }
      ],
      "Tx": [
          {
              "name": "account_number",
              "type": "string"
          },
          {
              "name": "chain_id",
              "type": "string"
          },
          {
              "name": "fee",
              "type": "Fee"
          },
          {
              "name": "memo",
              "type": "string"
          },
          {
              "name": "msgs",
              "type": "Msg[]"
          },
          {
              "name": "sequence",
              "type": "string"
          },
          {
              "name": "timeout_height",
              "type": "string"
          }
      ],
      "TypeAmount": [
          {
              "name": "denom",
              "type": "string"
          },
          {
              "name": "amount",
              "type": "string"
          }
      ]
  },
  "primaryType": "Tx",
  "sequence": "0",
  "timeout_height": "8535057",
  "domain": {
      "name": "Injective Web3",
      "version": "1.0.0",
      "chainId": 1,
      "verifyingContract": "cosmos",
      "salt": "1646876620490"
  },
  "message": {
      "account_number": "5712",
      "chain_id": "injective-1",
      "fee": {
          "gas": "400000"
      },
      "memo": "",
      "msgs": [
          {
          "type": "cosmos-sdk/MsgDelegate",
          "value": {
              "amount": {
                  "amount": "100000000000000000",
                  "denom": "inj"
              },
              "delegator_address": "inj17vy49gw9xnx700z8zwqqv4exl2rgdhanv75c4r",
              "validator_address": "injvaloper1w3psm8a9td2qz06s46cxss03mz5umxaxegvhhs"
              }
          }
      ]
  }}
```
</details>

### PR DESCRIPTION
**Pull request by martykan**
## Description

If an error is encountered when retreiving EIP-712 data, cancel the call and throw an error. 

## Related Issue

Resolve #5099

### CODE REVIEW

File: packages/connect/src/api/ethereum/api/ethereumSignTypedData.ts [hunk 1]
```diff
@@ -226,8 +226,14 @@ export default class EthereumSignTypedData extends AbstractMethod<'ethereumSignT
                     const memberTypeDefinition = types[memberTypeName][index];
                     memberTypeName = memberTypeDefinition.type;
                     memberData = memberData[memberTypeDefinition.name as keyof typeof memberData];
-                } else {
-                    // TODO: what to do when the value is missing (for example in recursive types)?
+                }
+                if (memberData === null || memberData === undefined) {
+                    // Cancel the request so the device isn't left hanging
+                    cmd.typedCall('Cancel', 'Success');
```
Comment (mroz22) [inline packages/connect/src/api/ethereum/api/ethereumSignTypedData.ts:232]: hmm I just wonder - shoudln't this be handled somewhere in a general manner? I would even say there are some attempts to have it covered. Unfortunately they are a mess.
 https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/device/DeviceCommands.ts#L101
https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/device/DeviceCommands.ts#L456

and this is something @marekrjpolak is now looking into

Comment (mroz22) [reply packages/connect/src/api/ethereum/api/ethereumSignTypedData.ts:232]: ok, we probably don't want to introduce ethereum specific to where general logic is handled so this is probably the fastest way to do it now.

**Review by mroz22 — APPROVED** [review]
