### PR TITLE
fix(suite, native): fix the issue of inconsistency between the review flow and hardware display (T1B1). 

### LINKED ISSUE #18706: XLM: align handling in Trezor Suite with the Trezor device when activating a new account
**Describe the bug**
When you send Lumens to an empty address and want to activate it, the sending flow is completely different between the device and Trezor Suite.

**Info:**
 - Suite version: web 25.5.0 (bb28264b87ee6e45934a58c3e0947fa4748cb87c) 
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.10 regular (revision 41b786353e09390b64b107e64e1cfe3020514ad5)
 - Transport: WebUsbTransport

**Screenshots:**

Image

### LINKED ISSUE #19014: XLM: Align Trezor Suite with T1B1
**Describe the bug**  
Currently, Trezor Suite displays a generic "Follow instructions" message instead of the proper send flow, which only appears after confirming on the Trezor device.

**Info:**  
- Suite version: web 25.6.0 (f57a9e24a5c77183ff4c892c05c932772931d69a)  
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36  
- OS: Linux x86_64  
- Screen: 2880x1800  
- Device: Trezor T1B1 1.13.1 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)  
- Transport: WebUsbTransport  

**Screenshots:**  
Image

### PR DESCRIPTION
**Pull request by overcat**
## Description
This is the follow-up PR for #19201, which includes improvements for T1B1.

## Related Issue

Resolve #19014
Resolve #18706

## Screenshots:
image

image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DeviceContextModal.tsx [hunk 1]
```diff
@@ -28,6 +29,7 @@ export const DeviceContextModal = ({
 }: ReduxModalProps<typeof MODAL.CONTEXT_DEVICE>) => {
     const device = useSelector(selectSelectedDevice);
     const intl = useIntl();
+    const { account } = useSelector((state: CoinjoinRootState) => state.wallet.selectedAccount);
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DeviceContextModal.tsx]:
```suggestion
    const selectedAccount = useSelector(selectSelectedAccount);
```

File: suite-common/wallet-core/src/send/sendFormSelectors.ts [hunk 2]
```diff
@@ -58,7 +58,9 @@ export const selectSendFormReviewButtonRequestsCount = (
             code === 'ButtonRequest_SignTx' ||
             isCardano ||
             (isEthereum && code === 'ButtonRequest_Other') ||
-            (isStellar && code === 'ButtonRequest_Other'),
+            // This is a special case for T1B1 devices (Stellar).
+            // See https://github.com/trezor/trezor-firmware/issues/5120
+            (isStellar && (code === 'ButtonRequest_Other' || code === 'ButtonRequest_ProtectCall')),
```
Comment (tomasklim) [inline suite-common/wallet-core/src/send/sendFormSelectors.ts:63]: with this code, I am getting passphrase window before signing on non-passphrase wallet


https://github.com/user-attachments/assets/a323a8fe-df3b-4ea3-b284-9bca0d9bae65

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: suite-common/wallet-core/src/send/sendFormSelectors.ts (hunk 2 above)
Comment (overcat) [reply suite-common/wallet-core/src/send/sendFormSelectors.ts:63]: This issue doesn't seem to have been introduced in this PR; let me debug and see where the root cause is.

Comment (overcat) [reply suite-common/wallet-core/src/send/sendFormSelectors.ts:63]: Fixed in c555d57ca7943a12a2d16fc484720a004956dca7

🥲 I overlooked something, which led to this problem.

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DeviceContextModal.tsx (hunk 1 above)
Comment (overcat) [reply packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/DeviceContextModal.tsx]: 351f14484f74ab399c64157d6e8125f83cabe2de

File: suite-common/wallet-core/src/send/sendFormSelectors.ts (hunk 2 above)
Comment (overcat) [reply suite-common/wallet-core/src/send/sendFormSelectors.ts:63]: Hi @tomasklim, I tested Model One and Model T on Desktop and Android, and it works well.

**Review by tomasklim — APPROVED** [review]
LGTM, tested

Screenshot 2025-06-03 at 12 13 35

**Comment by overcat** [comment]
Thank you for your quick response. 🙏
