### PR TITLE
fix(suite-native): keep fiat value as null before loaded so skeleton is visible instead of zero

### LINKED ISSUE #20884: Assets show 0 instead of skeleton before rates load
**What**
When we load assets, we should be loading a skeleton to indicate the value loading is in progress. But now it shows zero instead of loader and then updates once we have a value to be shown.

**Info:**

- Mobile Suite Version: 25.8.1
- OS: android

**Steps to reproduce:**
1. Connect device and load assets
2. Disconnect 
3. Close and reopen the app
4. Assets will show 0 before loading rates and then changing value (should be skeleton instead)

**Expected behavior**
We should show the loading skeleton until we're certain that zero  is the correct value 

Image

https://github.com/user-attachments/assets/cd792cee-6fc2-4fff-884e-5927a32721f5

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

To be honest, I don’t know how it used to work before, but this change is relatively isolated and makes sense to me, so hopefully it didn’t break something else in an unexpected place 🙈 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20884

## Screenshots:
Screenshot_2025-08-20-12-56-49-217_io trezor suite debug

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/null-fiat-value-skeleton&lookback=7)

### CODE REVIEW

**Review by juriczech — APPROVED** [review]
LGTM

**Comment by juriczech** [comment]
Quickly tested on android device, seems to be fixed 💪

File: suite-native/assets/src/assetsSelectors.ts [hunk 1]
```diff
@@ -138,18 +138,22 @@ const selectDeviceAssetsWithBalances = createMemoizedSelector(
                 (sum, { cryptoValue }) => sum.plus(new BigNumber(cryptoValue)),
                 new BigNumber(0),
             );
-            const fiatBalance = networkAccounts.reduce(
-                (sum, { fiatValue }) => (fiatValue ? sum.plus(fiatValue) : sum),
-                new BigNumber(0),
-            );
+            const fiatBalance = networkAccounts.reduce<BigNumber | null>((sum, { fiatValue }) => {
+                if (sum === null) return null;
```
Comment (peter-sanderson) [inline suite-native/assets/src/assetsSelectors.ts:144]: Do I understand that in case there is **at least one** account with `null` data, we want to make totalSum `null` as well as we assume that all accounts are not not loaded yet?

I would maybe add a comment here to explain.

**Review by peter-sanderson — APPROVED** [review]

File: suite-native/assets/src/assetsSelectors.ts (hunk 1 above)
Comment (matejkriz) [reply suite-native/assets/src/assetsSelectors.ts:144]: Yes, we don't want to present partial value to the user, we should present loading state until we have the final number. I'll add a comment that it is intentional.

Comment (matejkriz) [reply suite-native/assets/src/assetsSelectors.ts:144]: [`15546b9` (#20895)](https://github.com/trezor/trezor-suite/pull/20895/commits/15546b9825076f9795d11bf7c65370fdb9dd517b#diff-1c8311e2d32ab0d88991a27b03c2e10cf05a7e684b127fe3f3691172d3154f85R142-R143)
