### PR TITLE
fix(suite-native): clipboard toast message shown only on ios

### LINKED ISSUE #7331: Wrapper for expo-cliboard
We should wrap expo-clipboard to some hook like `useClipboard` which will also show some Toast with text `Copied to clipboard` everytime when called. As quick temporary solution we can use https://github.com/magicismight/react-native-root-toast which is very easy to use and later we will migrate to our notification solution (which will rely on redux to adding notifications, that's reason why should we make it hook right now, to avoid changes to "public api" later).

We will have to create new package named `@suite-native/helpers` - I want to avoid having `utils` package, which will collect all kind of garbage in the end and I hope different name will at least little bit prevent people to do that.

### PR DESCRIPTION
**Pull request by PeKne**
Clipboard toast message displayed only on iOS.
Since Android shows toast message on copy-to-clipobord by default, our custom message will be hidden.

fixes #7331

### CODE REVIEW

File: suite-native/helpers/src/hooks/useCopyToClipboard.tsx [hunk 1]
```diff
@@ -7,8 +8,10 @@ export function useCopyToClipboard() {
     const copyToClipboard = useCallback(async (value: string, toastMessage?: string) => {
         await Clipboard.setStringAsync(value);
 
-        // TODO: Replace with our own notification UI when ready.
-        Toast.show(toastMessage ?? 'Copied to clipboard.');
+        if (Platform.OS === 'ios') {
```
Comment (Nodonisko) [inline suite-native/helpers/src/hooks/useCopyToClipboard.tsx:11]: would be nice to have comment like "Android is showing native toast when copying text" or smthing like that.

**Review by Nodonisko — APPROVED** [review]

File: suite-native/helpers/src/hooks/useCopyToClipboard.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/helpers/src/hooks/useCopyToClipboard.tsx:11]: fixed
