### PR TITLE
fix(suite-native): Mobile Trade: Display selected coin balance

### LINKED ISSUE #19634: Mobile Trade: Showing native coin balance instead of selected asset balance
**Describe the bug**
When selecting token to buy, balance for account should show balance of token not a native coin.

**How to reproduce**

1. select any token to buy
2. select account for that token
3. it shows native token balance instead of token balance

**Expected behavior**
When buying some asset, the balance on account should show asset balance. The same should apply for swap as well

**Screenshots now**

Image

**Expected (see USDC)**

Image

### PR DESCRIPTION
**Pull request by jbazant**
## Description

- Now account balance should always display unit and balance according to selected asset

## Related Issue

Resolve #19634

## Screenshots:

Simulator Screenshot - iPhone 16 Plus - 2025-06-19 at 14 32 46
Simulator Screenshot - iPhone 16 Plus - 2025-06-19 at 14 32 56
Simulator Screenshot - iPhone 16 Plus - 2025-06-19 at 14 33 04

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=19634-mobile-trade-show-token-balance&lookback=7)

### CODE REVIEW

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/module-trading/src/components/general/TradeableAssetAccountBalance.tsx [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+    );
+};
+
+const AssetBalance = ({ account, asset, testID }: AssetBalanceProps) => {
+    const { cryptoId, symbol } = asset;
+    const { key: accountKey, formattedBalance } = account;
+
+    const tokenAddress = isSendingEvmNativeToken(cryptoId)
+        ? undefined
+        : parseCryptoId(cryptoId).contractAddress;
```
Comment (vytick) [inline suite-native/module-trading/src/components/general/TradeableAssetAccountBalance.tsx]:
```suggestion
        : asset.contractAddress;
```

File: suite-native/module-trading/src/components/general/TradeableAssetAccountBalance.tsx [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+
+    return (
+        <DiscreetTextTrigger>
+            {tokenAddress ? (
+                <TokenBalance
+                    symbol={symbol}
+                    accountKey={accountKey}
+                    tokenAddress={tokenAddress as TokenAddress}
```
Comment (vytick) [inline suite-native/module-trading/src/components/general/TradeableAssetAccountBalance.tsx]: if asset.contractAddress is used, this is not needed anymore

```suggestion
                    tokenAddress={tokenAddress}
```

**Review by vytick — APPROVED** [review]
Nice improvement 💪. I have 2 nits, but overall it works and looks nicely 🚢 🇮🇹

**Review by vytick — APPROVED** [review]
