### PR TITLE
fix(trading): fix switching between coin and fiat

### LINKED ISSUE #19345: Trading – switching between fiat and coin is unavailable.
**Describe the bug**
Switching between fiat and coin is unavailable until you enter an amount and receive the first trade offers.

Image

**Info:**
 - Suite version: desktop 25.6.1 (d14eb885016cefe147b2e6532ba04412230aaee0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.6.1 Chrome/136.0.7103.49 Electron/36.2.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.10 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: BridgeTransport 3.0.0-bundled.25.6.1

### PR DESCRIPTION
**Pull request by meedoox**
## Description
Fixes switching between coin and fiat

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/19345

### Before
451387091-3b27325d-b0e0-46a4-b1bd-8f2eb152a0b8

### After
https://github.com/user-attachments/assets/9ba9d627-00be-4f79-8d24-7080cc419026

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-switch-between-coin-and-fiat-unavailable&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-switch-between-coin-and-fiat-unavailable&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiatCrypto.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ export const TradingFormInputFiatCrypto = <
         labelRight: showLabel ? (
             <TradingFormSwitcherCryptoFiat
                 currency={!amountInCrypto ? displaySymbol : (currencySelectLabel ?? '')}
-                isDisabled={isFormLoading}
+                isDisabled={methods.formState.isLoading}
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiatCrypto.tsx]: `methods.formState.isLoading` is not used anywhere else in codebase and it is always `false` so i guess if there is no reason to disable the switcher, let's remove `isDisabled` completely?

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Review by tomasklim — APPROVED** [review]
