### PR TITLE
fix(connect): caching firmware type

### LINKED ISSUE #22616: Switching from BTC only FW to Universal firmware not possible on T3T1
**Describe the bug**
Switching from BTC only FW to Universal firmware is not possible on T3T1. I am offered the BTC only firmware again.

```typescript
Core onCallFirmwareUpdate waiting for device to reconnect in bootloader mode
@trezor/connect handleMessage ui-firmware_reconnect
@trezor/transport BridgeTransport unexpected error:  session not found
2025-10-22T14:00:12.344Z - INFO(request-filter): https://o117836.ingest.sentry.io/api/5193825/envelope/?sentry_version=7&sentry_key=6d91ca6e6a5d4de7b47989455858b5f6&sentry_client=sentry.javascript.electron%2F5.12.0 was allowed because o117836.ingest.sentry.io is in the exception list
2025-10-22T14:00:12.346Z - INFO(request-filter): https://data.trezor.io/suite/log/desktop/develop.log?c_v=25.11.0&c_type=device-disconnect&c_commit=e23faf16dbe93befaea3deec4ddd4a3eff52a401&c_instance_id=rFoKKVUIyj&c_session_id=ZJtagdVCmY&c_timestamp=1761141612342&c_message_id=khHAsJ9Zni was allowed because data.trezor.io is in the exception list
2025-10-22T14:00:12.358Z - DEBUG(csp): Header applied to https://data.trezor.io/suite/log/desktop/develop.log?c_v=25.11.0&c_type=device-disconnect&c_commit=e23faf16dbe93befaea3deec4ddd4a3eff52a401&c_instance_id=rFoKKVUIyj&c_session_id=ZJtagdVCmY&c_timestamp=1761141612342&c_message_id=khHAsJ9Zni
2025-10-22T14:00:12.364Z - DEBUG(csp): Header applied to https://o117836.ingest.sentry.io/api/5193825/envelope/?sentry_version=7&sentry_key=6d91ca6e6a5d4de7b47989455858b5f6&sentry_client=sentry.javascript.electron%2F5.12.0
Core onCallFirmwareUpdate ...still waiting for device to reconnect 1
@trezor/connect handleMessage ui-firmware_reconnect
Device handshake Cancel start
Device handshake Cancel sent
Device handshake Cancel read attempt 0
Device handshake Cancel read success: Failure
DeviceCommands Sending GetFeatures {}
DeviceCommands Received Features (redacted...)
2025-10-22T14:00:16.052Z - DEBUG(request-interceptor): http.request - data.trezor.io/firmware/t3t1/bitcoinonly/t3t1-2.1.10-bitcoinonly.json with agent false
2025-10-22T14:00:16.053Z - DEBUG(request-interceptor): tls.connect - data.trezor.io
2025-10-22T14:00:16.053Z - DEBUG(request-interceptor): net.Socket.connect - data.trezor.io:443
Core onCallFirmwareUpdate ...still waiting for device to reconnect 2
@trezor/connect handleMessage ui-firmware_reconnect
@trezor/connect handleMessage device-connect
2025-10-22T14:00:16.100Z - DEBUG(request-interceptor): request to data.trezor.io took 47ms and responded with status code 404
2025-10-22T14:00:16.556Z - INFO(request-filter): https://data.trezor.io/suite/log/desktop/develop.log?c_v=25.11.0&c_type=device-connect&c_commit=e23faf16dbe93befaea3deec4ddd4a3eff52a401&c_instance_id=rFoKKVUIyj&c_session_id=ZJtagdVCmY&c_timestamp=1761141616556&c_message_id=TTaNXRVUpQ&mode=bootloader&firmware=2.9.1&bootloader=2.1.10&firmwareSource=NA+-+bootloader was allowed because data.trezor.io is in the exception list
2025-10-22T14:00:16.569Z - DEBUG(csp): Header applied to https://data.trezor.io/suite/log/desktop/develop.log?c_v=25.11.0&c_type=device-connect&c_commit=e23faf16dbe93befaea3deec4ddd4a3eff52a401&c_instance_id=rFoKKVUIyj&c_session_id=ZJtagdVCmY&c_timestamp=1761141616556&c_message_id=TTaNXRVUpQ&mode=bootloader&firmware=2.9.1&bootloader=2.1.10&firmwareSource=NA+-+bootloader
Core onCallFirmwareUpdate ...still waiting for device to reconnect 3
DeviceCommands Sending Initialize { derive_cardano: false }
@trezor/connect handleMessage device-changed
DeviceCommands Received Features (redacted...)
Core handleMessage popup-handshake
DeviceCommands Sending FirmwareErase { length: 1184768 }
@trezor/connect handleMessage button
@trezor/connect handleMessage ui-button
DeviceCommands Received FirmwareRequest { offset: 0, length: 16384 }
DeviceCommands Sending FirmwareUpload {
  payload: <Buffer 54 52 5a 56 00 04 00 00 00 00 00 00 00 00 02 03 7f 01 54 33 54 31 00 00 00 00 00 00 00 00 00 00 38 d9 a8 7f d9 f1 31 36 75 42 c9 f7 27 30 8d 4f fe d4 ... 16334 more bytes>
}
2025-10-22T14:00:18.363Z - DEBUG(request-interceptor): http.request - data.trezor.io/firmware/t3t1/bitcoinonly/t3t1-2.1.10-bitcoinonly.json with agent false
2025-10-22T14:00:18.375Z - DEBUG(request-interceptor): request to data.trezor.io took 12ms and responded with status code 404
2025-10-22T14:00:22.676Z - DEBUG(window-control): Blur
``` 

**Steps to reproduce:**
1. Connect device with BTC only firmware
2. Navigate to device settings
3. Switch to Universal firmware
4. Suite will reinstall BTC only firmware

**Info:**
 - Suite version: desktop 25.11.0 (e23faf16dbe93befaea3deec4ddd4a3eff52a401)
 - Browser: Trezor Suite 25.11.0
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: T3T1
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by karliatto**
## Description

There was an issue when caching firmware in Desktop when changing firmware type. The issue was that it was stored as the current firmware type but it was actually the other FW type, so if you changed FW type 2 types then you were not able to change it until you wiped desktop data. 

This issue is probably not happening often since most likely users are not changing firmware type more tan 1 time per new FW version.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22616

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/caching-firmware-type-changing&lookback=7)

### CODE REVIEW

File: packages/connect/src/core/onCallFirmwareUpdate.ts [hunk 1]
```diff
@@ -285,6 +285,7 @@ const getBinaryHelper = async ({
             binary: params.binary,
             binaryVersion: parseFirmwareHeaders(Buffer.from(params.binary)).version,
             releaseVersion: undefined,
```
Comment (marekrjpolak) [inline packages/connect/src/core/onCallFirmwareUpdate.ts]: This `releaseVersion` is obsolete now, right?

**Review by marekrjpolak — CHANGES_REQUESTED** [review]
There is a type error in `getBinaryOptional` and also in `onCallFirmwareUpdate`.

File: packages/connect/src/core/onCallFirmwareUpdate.ts (hunk 1 above)
Comment (karliatto) [reply packages/connect/src/core/onCallFirmwareUpdate.ts]: Yes, here I fixed the missing ones https://github.com/trezor/trezor-suite/pull/22700/commits/6c2c9c8fc82232843da51ee7fd5c2fd998597bcb

**Review by marekrjpolak — APPROVED** [review]

**Comment by vojtatranta** [comment]
I have just got here a production unit of TS7 and unfortunately, I stil have this bug here :(.

**Comment by evgenysl** [comment]
Checked with TS5 and TS7

QA OK

**Comment by vojtatranta** [comment]
> I have just got here a production unit of TS7 and unfortunately, I stil have this bug here :(.

Had to completely wipe the app, and clear the cache, now it works.

Sorry for the alarm. Thanks @karliatto
