### PR TITLE
Fix/23928 to field asset picker

### LINKED ISSUE #23928: TO picker in trading form - ui bugs
UI bugs found in `TO` asset picker ([url](https://dev.suite.sldev.cz/suite-web/feat/22838-swap-to-asset-picker/web)).

<details>
<summary> 1. Top 5 assets should user their ticker, not the ticker of the network </summary>

Image

### Figma

Image

</details>

<details>
<summary> 2. Network filter should be aligned more to right and the number of all networks in the bracket is unnecessary</summary>

Image

### Figma

Image

</details>

<details>
<summary> 3. Top 5 assets should have a strong border around them </summary>

Image

### Figma

Image

</details>

4. The whole modal should be narrower (currently 600px, Figma has 480px)

5. If `Your assets` section isn't present, because user does not have any funds, hide `All assets` headline

<details>
<summary> 6. Improve instructions on empty search results page </summary>

Image

### Figma

Image

</details>

<details>
<summary> 7. Make network popover slightly wider, so all network names fit on one line </summary>

We didn't have c-chain there when i was designing this.

Image

</details>

<details>
<summary> 8. Add `...` for too long token names and add the full name to tooltip </summary>

Image

</details>

### LINKED ISSUE #24142: Remove selected asset from TO picker in SWAP
If asset is selected in FROM field in SWAP form, remove the asset from TO picker.

E.g. I selected that I want to trade from ETH and I am being offer to trade to ETH. This shouldn't happen.

Note: This behaviour was present in old `TO` picker

Image

# The result
- This shows up if I select to trade from ETH to ETH

Image

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

* Make top five assets static again (it's going to be soon removed and replaced with more sophisticated logic -  [slack thread](https://satoshilabs.slack.com/archives/C08PA8C0370/p1767607026274459?thread_ts=1765879742.531959&cid=C08PA8C0370)).
* Exclude cryptoId of `From` field in `To` field asset picker. (Yes, it's not excluded from the static top five assets. This is expected. It's only being excluded from `Your assets` and `All assets`)
* Hide `All assets` if `Your assets` is empty.

## Related Issue

- Resolve #23928
- Resolve #24142

## Screenshots:

Snímek obrazovky 2026-01-05 v 14 38 21

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/23928-to-field-asset-picker&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/23928-to-field-asset-picker&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/23928-to-field-asset-picker&lookback=7)

### CODE REVIEW

File: suite-common/trading/src/utils.ts [hunk 1]
```diff
@@ -66,6 +69,22 @@ export function composeCryptoId(coingeckoId: string, contractAddress?: string |
     ) as CryptoId;
 }
 
+/**
+ * Get the crypto id for an account or token
+ */
+export function getCryptoId(account: Account, token?: TokenInfo): CryptoId {
+    const network = networks[account.symbol];
```
Comment (izmy) [inline suite-common/trading/src/utils.ts]: I think it would be better if the helper function received `networks` as a parameter instead of relying on the outer scope.

File: suite-common/trading/src/utils.ts [hunk 2]
```diff
@@ -66,6 +69,22 @@ export function composeCryptoId(coingeckoId: string, contractAddress?: string |
...
+
+    if (token) {
+        return composeCryptoId(
+            network.coingeckoId!,
```
Comment (izmy) [inline suite-common/trading/src/utils.ts:79]: Since this is a helper function, wouldn't it be better to avoid using a non-null assertion here?

**Review by izmy — APPROVED** [review]

File: suite-common/trading/src/utils.ts (hunk 1 above)
Comment (cermakjiri) [reply suite-common/trading/src/utils.ts]: Thanks for feedback. There're several other utils in this file using the `networks` too. The only diff. they use `getNetwork` and other network utils. The `networks` is global constant. You could argue with the same logic to pass `CRYPTO_PLATFORM_SEPARATOR` in `parseCryptoId` and `composeCryptoId` or `CONTRACT_ADDRESS_FOR_NATIVE_TOKEN` in `isCryptoIdForNativeToken` as arguments.

I'll use the `getNetwork` util.

File: suite-common/trading/src/utils.ts (hunk 2 above)
Comment (cermakjiri) [reply suite-common/trading/src/utils.ts:79]: The `coingeckoId` is undefined for testnets only. Let me add a comment there saying the util is only for non-testnets networks.
