### PR TITLE
fix(suite): force yield transaction polling

### LINKED ISSUE #25647: Confirmation burst for approve/supply/withdraw tx
To save requests to our backends, we limit account update to XY seconds. (At least for Solana,... not sure if we limit it also for EVM)

To have seamless experience we need info that tx was mined ASAP so that we can continue to next flow ASAP. Please check if we need to lift some restrictions and if we need to use update account methods after tx was broadcasted. (many times until it is confirmed [ofc with some rate limitter])

There is similar thing in Trading but in trading we have info from trading backend, not from Blockbook so that's why it works

Check https://github.com/trezor/trezor-suite/pull/19929/changes and `prepareAccountsMiddleware`

### PR DESCRIPTION
**Pull request by izmy**
## Description

Adds a forced transaction refresh path for yield pending transaction polling to keep approve, revoke, supply and withdraw status updates responsive.

## Related Issue

Resolve #25647

## 🔍 Currents Test Results

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/yield-transaction-polling&lookback=7)

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/yield-transaction-polling&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/yield-transaction-polling&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 13 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-15T11:33:26.393Z • 13 test(s) total_

<details><summary>Trezor Suite (desktop) — 14 test(s)</summary>

| Test | Type |
|------|------|
| Analytics Events - Staking Navigate > Should log the event staking/navigate - ADA from account menu | 🤖 auto |
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Global receive and send,Global receive" | 🙋 manual |
| Bridge > App acquired device, EXTERNAL bridge is restarted, app reconnects | 🤖 auto |
| Bridge > App spawns bundled bridge and stops it after app quit | 🤖 auto |
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Onboarding - create wallet > Success (basic) | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-15T11:31:33.873Z • 14 test(s) total_

### CODE REVIEW

File: packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts [hunk 1]
```diff
@@ -31,12 +36,35 @@ export const useYieldPendingTransactionTracking = ({
...
+    useEffect(() => {
+        if (!isCurrentlyPending) {
+            return;
+        }
+
+        const interval = setInterval(() => {
+            dispatch(
+                fetchAndUpdateAccountThunk({
+                    accountKey: account.key,
+                    forceTransactions: true,
```
Comment (tomasklim) [inline packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts]:
```suggestion
                    forceUpdate: true,
```

Comment (izmy) [reply packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts]: done

File: packages/suite/src/components/earn/yield/common/YieldActionStepWarning.tsx
Comment (seibei-iguchi) [inline packages/suite/src/components/earn/yield/common/YieldActionStepWarning.tsx]: Use rightContent and Banner.Button

**Comment by seibei-iguchi** [comment]
Just a general note. This PR seems to be huge and I see no screenshots or Figma link

**Comment by izmy** [comment]
> Just a general note. This PR seems to be huge and I see no screenshots or Figma link

This is because the PR depends on another branch where I did a rebase. For now, I changed it to a draft.

File: suite-common/wallet-core/src/accounts/accountsThunks.ts [hunk 2]
```diff
@@ -102,7 +105,7 @@ export const fetchAndUpdateAccountThunk = createThunk(
 
         // stop here if account is not outdated and there are no pending transactions
 
-        if (!accountOutdated && !accountTxs.find(isPending)) {
+        if (!forceUpdate && !accountOutdated && !accountTxs.find(isPending)) {
```
Comment (tomasklim) [inline suite-common/wallet-core/src/accounts/accountsThunks.ts]: do you need to add `forceUpdate`? there should be pending tx on the account

File: packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+    pendingTransaction,
+}: UseYieldPendingTransactionTrackingProps) => {
+    const dispatch = useDispatch();
+    const trackedPendingTransaction = useSelector(state =>
+        pendingTransaction
+            ? selectTransactionByAccountKeyAndTxid(state, account.key, pendingTransaction.txid)
+            : null,
+    );
+
+    // Keep polling even before the tx appears in wallet.transactions.
```
Comment (tomasklim) [inline packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts:48]: it should appear there everytime because we have `addFakePendingEvmTxThunk`

File: packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+import {
+    fetchAndUpdateAccountThunk,
+    selectTransactionByAccountKeyAndTxid,
+} from '@suite-common/wallet-core';
+import { type Account } from '@suite-common/wallet-types';
+import { isPending } from '@suite-common/wallet-utils';
+
+import { useDispatch, useSelector } from 'src/hooks/suite';
+
+const PENDING_TX_POLL_INTERVAL_MS = 3_000;
```
Comment (tomasklim) [inline packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts]: We should have `blockTime` for every network. It is used somewhere for evm fees.

I would suggest using something like `Math.max(blocktime / 2, 2)` min 2 seconds, half time of block

File: packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts (hunk 3 above)
Comment (izmy) [reply packages/suite/src/components/earn/yield/hooks/useYieldPendingTransactionTracking.ts:48]: yes, you are right

**Review by tomasklim — APPROVED** [review]
