### PR TITLE
fix(suite): clear state after connect popup call

### LINKED ISSUE #26018: Can't enter passphrase in Trezor Suite - Confirm button is greyed out
**Describe the bug**
Can't enter passphrase in Trezor Suite - Confirm button is greyed out.
Both for New and Previously used passphrase.

Image

**Info:**
 - Suite version: desktop 26.4.0 (98554a0d2865b52c71868e272d42fdaeca1fcc30)
 - Browser: Trezor Suite 26.4.0
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.8.10 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: BluetoothTransport, BridgeTransport 3.2.1

### PR DESCRIPTION
**Pull request by martykan**
## Description

Clear state after connect popup call. Without this, we apply logic to close modals intended to clean up after the popup call, but it would continue afterwards, which was not intended. 
This was previously causing issues with passphrase flow and potentially certain other flows that check modal state. 

## Notes for QA

See linked issue, check both connect popup and passphrase behaves normally.

## Related Issue

Resolve #26018

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/connect-popup-clear-state&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/connect-popup-clear-state&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/connect-popup-clear-state&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 19 test(s)</summary>

| Test | Type |
|------|------|
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| TrezorConnect popup web > TrezorConnect.getAddress | 🤖 auto |
| TrezorConnect popup web > call cancellation | 🤖 auto |
| TrezorConnect popup web > closing popup window returns Method_Interrupted error | 🤖 auto |
| TrezorConnect popup web > call cancelled from calling application | 🤖 auto |
| TrezorConnect popup web > second call after popup was closed by user should work | 🤖 auto |
| TrezorConnect popup web > focuses existing popup if already open | 🤖 auto |
| Quarantine test: "Account metadata,google - watches files over time" | 🙋 manual |
| Quarantine test: "Account metadata,dropbox - watches files over time" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-09T12:14:51.381Z • 19 test(s) total_

<details><summary>Trezor Suite (desktop) — 11 test(s)</summary>

| Test | Type |
|------|------|
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Analytics Events - Staking Navigate > Should log the event staking/navigate - ADA from account menu | 🤖 auto |
| Onboarding - create wallet > Success (basic) | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-09T09:14:25.838Z • 11 test(s) total_

### CODE REVIEW

**Comment by evgenysl** [comment]
Testing on branch, doesn't seem to be fully fixed.

Called Connect method, tried to entered passphrase and button became active after some delay only:


https://github.com/user-attachments/assets/409edfb4-2ab2-45df-a300-3eac27ccbb0e

**Comment by martykan** [comment]
@evgenysl This looks normal to me, it's communicating with device

**Comment by evgenysl** [comment]
Agree, it looks like I have this (or shorter) delay even after Suite restart (and not using popup).

File: packages/suite/src/support/suite/useConnectPopupModals.tsx [hunk 1]
```diff
@@ -132,6 +136,10 @@ export const useConnectPopupModals = () => {
                     dispatch(removePreserveModal());
                     dispatch(cancelModal());
                 }
+                // Clear state after allowing everything to update
+                setTimeout(() => {
+                    dispatch(connectPopupActions.clearCall());
+                }, 100);
```
Comment (mroz22) [inline packages/suite/src/support/suite/useConnectPopupModals.tsx:142]: sounds sensible to me to set acitveCall to undefined, but what is the meaning of this timeout?

**Review by mroz22 — APPROVED** [review]

File: packages/suite/src/support/suite/useConnectPopupModals.tsx (hunk 1 above)
Comment (martykan) [reply packages/suite/src/support/suite/useConnectPopupModals.tsx:142]: There are also other hooks/events that react to the finished state, this gives everything time to process...
