### PR TITLE
Fix for THP re-pairing modal

### LINKED ISSUE #21374: Endless loading in THP pairing
Related to https://github.com/trezor/trezor-suite/issues/21375

1. Device is connected but THP not yet paired
2. Cancel THP pairing in Suite
3. Click the button to pair again
4. Endless loading

https://github.com/user-attachments/assets/1dfc8266-cc74-4186-aacc-efc40ab2f3a4

The pill is broken here but that should be fixed with the final renders.

### PR DESCRIPTION
**Pull request by OriginalEveres**
This PR removes a duplicated Trezor cancel call that causes THP pairing issue.

**Changes**:
- removed duplicated `TrezorConnect.cancel()` call

NOTE: this fixes it in BT mode, I'm still working on fix for devices connected via cable

## Related Issue

Resolves https://github.com/trezor/trezor-suite/issues/21374 & https://github.com/trezor/trezor-suite/issues/21375

## Screenshots:

https://github.com/user-attachments/assets/719541a0-6d29-45c1-b99d-dfbf8014581c

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/thp-endless-loading&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/thp-endless-loading&lookback=7)

### CODE REVIEW

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/components/connection/thp/ThpConnectionModal.tsx [hunk 1]
```diff
@@ -14,7 +13,6 @@ export const ThpConnectionModal = ({ device }: ThpConnectionModalProps) => {
     const dispatch = useDispatch();
 
     const onCancel = () => {
-        TrezorConnect.cancel();
```
Comment (komret) [inline packages/suite/src/components/connection/thp/ThpConnectionModal.tsx:17]: Sorry I don't get this and would appreciate some explanation.  How does `dispatch(thpActions.finishThpFlow())` close the modal? All I see in the reducer is:
```
.addMatcher(isAnyOf(thpActions.finishThpFlow, thpActions.cancelThpFlow), state => {
                state.step = null;
            })

Comment (OriginalEveres) [reply packages/suite/src/components/connection/thp/ThpConnectionModal.tsx:17]: Modal is rendered in switch based of the THP steps in `ConnectionGlobalModal.tsx` - this approach was basically introduced by @peter-sanderson and I like it tbh.

Since ours `UserContextModal` are not great we've decided to keep modals domain specific instead, thus not including them in the huuuuge redux state for all modals - it's cleaner and more intuitive.

Regarding the `TrezorConnect.cancel()` - it was called twice and when the connect received 2 cancel calls - the next request to the device just did not fullfill or reject the promise. This is a bug and it was reported to @martykan.

But, this `onCancel` had unnecessary `TrezorConnect.cancel()` anyways since it's called by default in the `ConfirmActionModal.tsx` that this component wrapps.

Comment (komret) [reply packages/suite/src/components/connection/thp/ThpConnectionModal.tsx:17]: Thanks!

**Review by komret — APPROVED** [review]
