### PR TITLE
fix(suite): browser icons on non-supported browser fallback page

### LINKED ISSUE #3383: Browser icons broken on https://suite.trezor.io/web/version/ with Unsupported Browser
When I visit https://suite.trezor.io/web/version/ with Unsupported browser (i.e. Safari), the browser icons (Firefox/Chrome) are broken, because they are fetched from https://suite.trezor.io/web/version/static/browser-detection/browser-chrome.png (note the `version` in the URL)

https://suite.trezor.io/web/ looks fine, because the icon is fetch from https://suite.trezor.io/web/static/browser-detection/browser-chrome.png

### PR DESCRIPTION
**Pull request by tomexx**
fixes #3383

- static JS file is now created from TS file as a build step
- browser icons images are inlined as base64 (we don't need to solve problems using relative paths under different URLs + a little benefit is also that the icons now doesn't blink on first render)

### CODE REVIEW

**Comment by szymonlesisz** [comment]
i think absolute path should not be used at all
in production files are stored in [/web/static](https://suite.trezor.io/web/static/browser-detection/browser-chrome.png)
in sldev they are stored in `[bnachname]/web/static`

File: packages/suite-data/src/browser-detection/index.ts [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+            name: 'Chromium',
+            version: 69,
+            mobile: true,
+        },
+        {
+            name: 'Firefox',
+            version: 62,
+            mobile: false, // no webusb support
+        },
+    ];
```
Comment (keraf) [inline packages/suite-data/src/browser-detection/index.ts:115]: Can we get this from the browserlist file somehow? Maybe it can be read at build time and passed here using the Define Plugin.

File: packages/suite-data/src/browser-detection/index.ts [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+
+    const noWebUSB =
+        '<div style="position:absolute;left:0;right:0;top:0;bottom:0;background:#fff;z-index:99999;text-align:center;padding-top:150px"><h1 style="text-rendering:optimizeLegibility;color:#494949;font-weight:bold;margin:0;padding:0;font-size:2rem;padding-bottom:10px">No WebUSB support</h1><p style="font-size:1rem;line-height:1.8;color:#757575;padding:0;margin:0">Only Chrome for Android has WebUSB support.</p></div>';
```
Comment (keraf) [inline packages/suite-data/src/browser-detection/index.ts]: These look to be fairly similar, maybe it would be worth making a template?

**Review by keraf — CHANGES_REQUESTED** [review]

File: packages/suite-data/src/browser-detection/index.ts (hunk 1 above)
Comment (tomexx) [reply packages/suite-data/src/browser-detection/index.ts:115]: I've created a new task for that #3479 so this is not blocked. This is code is actually just moved from `packages/suite-data/files/browser-detection/index.js`

File: packages/suite-data/src/browser-detection/index.ts (hunk 2 above)
Comment (tomexx) [reply packages/suite-data/src/browser-detection/index.ts]: Please check updated version

**Comment by tsusanka** [comment]
@keraf please check again

**Review by keraf — APPROVED** [review]
