### PR TITLE
fix(suite-native): xlm outputs review

### LINKED ISSUE #19993: XLM - native - the send flow pre-fills all checkmarks.
**Describe the bug**
In the send flow of XLM, the checkmarks are prefilled as completed even though you are just starting the process.

Image

https://github.com/user-attachments/assets/59b0c5ed-4d9e-4700-ab50-063a669d7b5b

**Info:**

- Mobile Suite Version: 0b0bfa25
- OS: Android 15

### LINKED ISSUE #19995: "Confirm on device" overlapping with the send flow checks for XLM
**Describe the bug**
The "Confirm on device" picture overlapping with the send flow checks for XLM.

**Info:**

- Mobile Suite Version: 25.7.1 e335c7e
- OS: Android

**How to reproduce**

1. Connect device with XLM
2. Enable XLM in the dev utils
3. Go to Send
4. Send some XLM from one account to another
5. Observe the checks in the send flow after confirming everything on the device

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by vytick**
Make Send flow work correctly for Stellar.

## Related Issue

Resolve #19993
Resolve #19995

## Screenshots:

BEFORE:

https://github.com/user-attachments/assets/8d47f56f-6662-4a00-a522-4c374ef9ce2e

AFTER:

https://github.com/user-attachments/assets/87dfba76-114d-4dd0-9f41-cc9ae588b03b

For reference
after BTC:
https://github.com/user-attachments/assets/d642e61b-7284-4399-9acc-97da74c6039b

after ETH:
https://github.com/user-attachments/assets/fd27e627-dbbf-4150-b348-d2a21aaaf712

after XRP:
https://github.com/user-attachments/assets/81eeb315-5109-4537-88ba-528ca87eff96

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=19993-xlm---native---the-send-flow-pre-fills-all-checkmarks&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=19993-xlm---native---the-send-flow-pre-fills-all-checkmarks&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=19993-xlm---native---the-send-flow-pre-fills-all-checkmarks&lookback=7)

### CODE REVIEW

File: suite-native/module-send/src/components/ReviewOutputItem.tsx [hunk 1]
```diff
@@ -28,7 +30,8 @@ const isTranslationDefined = (
 ): type is keyof typeof outputLabelTranslationMap => type in outputLabelTranslationMap;
 
 export const ReviewOutputItem = ({ reviewOutput, onLayout }: ReviewOutputItemProps) => {
-    const { state = 'success', type, value } = reviewOutput;
+    const isTxSigned = !!useSelector((state: SendRootState) => selectSendSignedTx(state));
+    const { state = isTxSigned ? 'success' : undefined, type, value } = reviewOutput;
```
Comment (PeKne) [inline suite-native/module-send/src/components/ReviewOutputItem.tsx]: This could be handled already in `selectTransactionReviewOutputs` so it has not to be recalculated in every item component. The state based on the value of `isTxSigned ` will be already computed there? 

EDIT: Wait... it is already handled there, no? Remove it from here then

File: suite-native/module-send/src/components/ReviewOutputItem.tsx [hunk 2]
```diff
@@ -28,7 +30,8 @@ const isTranslationDefined = (
 ): type is keyof typeof outputLabelTranslationMap => type in outputLabelTranslationMap;
 
 export const ReviewOutputItem = ({ reviewOutput, onLayout }: ReviewOutputItemProps) => {
-    const { state = 'success', type, value } = reviewOutput;
+    const isTxSigned = !!useSelector((state: SendRootState) => selectSendSignedTx(state));
```
Comment (PeKne) [inline suite-native/module-send/src/components/ReviewOutputItem.tsx]: there is  `selectIsTransactionAlreadySigned` selector. Use it please

File: suite-common/wallet-utils/src/reviewTransactionUtils.ts [hunk 3]
```diff
@@ -22,7 +22,10 @@ export const getTransactionReviewOutputState = (
     index: number,
     buttonRequestsCount: number,
 ): ReviewOutputState => {
+    if (index === 0 && buttonRequestsCount === 0) return 'active';
```
Comment (PeKne) [inline suite-common/wallet-utils/src/reviewTransactionUtils.ts]: please add some comment :pray:. I can imagine we could be confused about this in few months again. :D

File: suite-native/module-send/src/components/ReviewOutputItemList.tsx [hunk 4]
```diff
@@ -57,26 +62,36 @@ export const ReviewOutputItemList = ({ accountKey, tokenContract }: ReviewOutput
...
+                    {reviewOutputs
+                        ?.filter((_, index) => shouldShowAllOutputs || index === 0)
+                        .map((output, index) => (
+                            <ReviewOutputItem
+                                key={`${output.type}-${output.value}`}
+                                reviewOutput={output}
+                                onLayout={event => handleReadListItemHeight(event, index)}
+                            />
+                        ))}
+                    {shouldShowAllOutputs && (
```
Comment (PeKne) [inline suite-native/module-send/src/components/ReviewOutputItemList.tsx]: What is the benefit of hiding the last summary item? IMO it should be always part of the list.

File: suite-native/module-send/src/components/ReviewOutputItemList.tsx [hunk 5]
```diff
@@ -57,26 +62,36 @@ export const ReviewOutputItemList = ({ accountKey, tokenContract }: ReviewOutput
...
+                            }
                         />
-                    ))}
-                    <ReviewOutputSummaryItem
-                        accountKey={accountKey}
-                        symbol={account.symbol}
-                        tokenContract={tokenContract}
-                        onLayout={event => handleReadListItemHeight(event, reviewOutputs.length)}
-                    />
+                    )}
```
Comment (PeKne) [inline suite-native/module-send/src/components/ReviewOutputItemList.tsx]: I am wondering... Would it make sense to not render anything until `shouldShowAllOutputs` is true? filtering the list and conditionally displaying the last element seems quite hacky to me. 

e.g.

```suggestion
                    
                    {shouldRenderItems ? (
                        reviewOutputs
                        .map((output, index) => (
                            <ReviewOutputItem
                                key={`${output.type}-${output.value}`}
                                reviewOutput={output}
                                onLayout={event => handleReadListItemHeight(event, index)}
                            />
                        ))
                        <ReviewOutputSummaryItem
                            accountKey={accountKey}
                            symbol={account.symbol}
                            tokenContract={tokenContract}
                            onLayout={event =>
                                handleReadListItemHeight(event, reviewOutputs.length)
                            }
                        />
                    ) : <Spinner/>
                    }
                    
```

WDYT?

File: suite-native/module-send/src/components/ReviewOutputItemList.tsx [hunk 6]
```diff
@@ -57,26 +62,36 @@ export const ReviewOutputItemList = ({ accountKey, tokenContract }: ReviewOutput
 
     if (!account) return <ErrorMessage errorMessage="Account not found." />;
 
+    const shouldShowAllOutputs = buttonRequestCount > 0 || isTransactionAlreadySigned;
+    const shouldShowFooter =
+        !isTransactionAlreadySigned && buttonRequestCount > 0 && (reviewOutputs?.length ?? 0) > 0;
```
Comment (PeKne) [inline suite-native/module-send/src/components/ReviewOutputItemList.tsx]: `(reviewOutputs?.length ?? 0) > 0` will be reviewOutputs ever empty/undefined? If yes, please add comments to these complicated conditions. It might get tricky to understand over time.

File: suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx [hunk 7]
```diff
@@ -65,10 +93,18 @@ export const SendOutputsReviewScreen = ({
                     closeActionType="close"
                 />
             }
+            /* TODO: improve the illustration: https://github.com/trezor/trezor-suite/issues/13965 */
+            footer={showConfirmOnDevice ? <SendConfirmOnDeviceImage /> : undefined}
```
Comment (PeKne) [inline suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx]:
```suggestion
            footer={showConfirmOnDevice && <SendConfirmOnDeviceImage />}
```

File: suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx [hunk 8]
```diff
@@ -65,10 +93,18 @@ export const SendOutputsReviewScreen = ({
...
         >
             <VStack flex={1} spacing="sp16" justifyContent="space-between">
                 <ReviewOutputItemList accountKey={accountKey} tokenContract={tokenContract} />
-                <OutputsReviewFooter accountKey={accountKey} tokenContract={tokenContract} />
+                {showConfirmOnDevice ? (
+                    // to add space in case there are more than 2 steps
+                    // otherwise it can be overlapped by the SendConfirmOnDeviceImage
+                    activeStep > 1 && <Box style={applyStyle(spacerStyle)} />
```
Comment (PeKne) [inline suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx]: Why not to render the spacer always? What is the benefit of rendering it conditionally?

Comment (PeKne) [reply suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx]: I seems it not did the trick :/

This is how it looks when I run your branch locally:
Screenshot 2025-07-08 at 9 00 33 AM

**Review by PeKne — CHANGES_REQUESTED** [review]

File: suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx (hunk 7 above)
Comment (vytick) [reply suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx]: good spot I forgot to changed this along the way

File: suite-native/module-send/src/components/SendFeesForm.tsx [hunk 9]
```diff
@@ -129,6 +141,22 @@ export const SendFeesForm = ({ accountKey, tokenContract }: SendFormProps) => {
...
+            });
+            setWaitingForButtonRequestsToNavigateToOutputsReview(false);
+        }
+    }, [
+        buttonRequestCount,
+        navigation,
+        accountKey,
+        tokenContract,
+        waitingForButtonRequestsToNavigateToOutputsReview,
+    ]);
```
Comment (juriczech) [inline suite-native/module-send/src/components/SendFeesForm.tsx]: This feels like a code smell to me 🤔 Are you doing this because you're trying to delay the redirect until button request arrives? Can you elaborate on what the issue is and why is it done this way please?

Comment (juriczech) [reply suite-native/module-send/src/components/SendFeesForm.tsx]:
```
            // We need to wait for device button requests before navigating to the review screen.
```
Obviously I see this comment, that's apparent, but why do you need to wait for it?

Comment (juriczech) [reply suite-native/module-send/src/components/SendFeesForm.tsx]: Maybe this could be abstracted only to `useHandleOnDeviceTransactionReview `?

Comment (vytick) [reply suite-native/module-send/src/components/SendFeesForm.tsx]: 👍  I'll make it into separate hook. I dont want to mix it with logic of useHandleOnDeviceTransactionReview that is used on 2 other places.

File: suite-common/wallet-utils/src/reviewTransactionUtils.ts (hunk 3 above)
Comment (vytick) [reply suite-common/wallet-utils/src/reviewTransactionUtils.ts]: refactored

File: suite-native/module-send/src/components/ReviewOutputItemList.tsx (hunk 4 above)
Comment (vytick) [reply suite-native/module-send/src/components/ReviewOutputItemList.tsx]: refactored

File: suite-native/module-send/src/components/ReviewOutputItemList.tsx (hunk 6 above)
Comment (vytick) [reply suite-native/module-send/src/components/ReviewOutputItemList.tsx]: refactored

File: suite-native/module-send/src/components/ReviewOutputItem.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/module-send/src/components/ReviewOutputItem.tsx]: refactored

File: suite-native/module-send/src/components/ReviewOutputItem.tsx (hunk 1 above)
Comment (vytick) [reply suite-native/module-send/src/components/ReviewOutputItem.tsx]: refactored

File: suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx (hunk 7 above)
Comment (vytick) [reply suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx]: refactored

File: suite-native/module-send/src/components/SendFeesForm.tsx (hunk 9 above)
Comment (vytick) [reply suite-native/module-send/src/components/SendFeesForm.tsx]: 0f0fccf13b

File: suite-native/module-send/src/components/SendFeesForm.tsx [hunk 10]
```diff
@@ -129,6 +131,11 @@ export const SendFeesForm = ({ accountKey, tokenContract }: SendFormProps) => {
         transaction: selectedFeeLevelTransaction,
     });
 
+    const requestDelayedNavigationToOutputsReview = useDelayedNavigationToOutputsReview({
```
Comment (PeKne) [inline suite-native/module-send/src/components/SendFeesForm.tsx]: nit: the hook name should be same as the returned value
```suggestion
    const requestDelayedNavigationToOutputsReview = useRequestDelayedNavigationToOutputsReview({
```

**Review by PeKne — APPROVED** [review]
