### PR TITLE
fix(trade): fix selecting fixed-rate quotes

### LINKED ISSUE #24755: Cannot switch from preselected float rate to any fixed rate provider in Swap
**Describe the bug**
When attempting to switch from the preselected floating rate provider to any fixed rate provider in the Swap interface, the selection does not persist. The previously selected floating rate provider is automatically reselected, so you cannot switch away from it. This prevents users from choosing a fixed rate provider after a float rate provider is selected.

**Info:**
 - Suite version: desktop 26.2.0 (5059d79d716b64340b79b683dd39be1fd0db9812)
 - Browser: Trezor Suite 26.2.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3W1 2.10.0 universal (revision de4b70e2e89a64f3894dba2124f6ec56e5cbd088)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**Screenshots**
Swap provider selection bug UI

https://github.com/user-attachments/assets/3dcab5cd-846b-4eb2-9948-07e095175ba4

### PR DESCRIPTION
**Pull request by sherpaPSX**
## Description

Previously implemented getPreferredCexQuotes filter caused TradingForm to stop receiving fixed-rate quotes, so it always picked the first floating-rate quote.

## Notes for QA

Please verify that best offer is preselected in the TradingForm

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/24755

## Screenshots:
image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/fixed-rate-quote&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/fixed-rate-quote&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/fixed-rate-quote&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingExchangeQuotesFilter.ts [hunk 1]
```diff
@@ -22,14 +21,10 @@ interface TradingExchangeQuotesFilterProps {
...
     quotes,
-    exchangeInfo,
     setValue,
 }: TradingExchangeQuotesFilterProps) => {
     const dexQuotes = useMemo(() => quotes.filter(quote => quote.isDex), [quotes]);
-    const cexQuotes = useMemo(
-        () => exchangeUtils.getPreferredCexQuotes(quotes, exchangeInfo),
-        [quotes, exchangeInfo],
-    );
+    const cexQuotes = useMemo(() => quotes.filter(quote => !quote.isDex), [quotes]);
```
Comment (vytick) [inline packages/suite/src/hooks/wallet/trading/form/common/useTradingExchangeQuotesFilter.ts]: It seems, that `getPreferredCexQuotes` is no longer used and therefore `fixedRateCexQuotes` and `floatRateCexQuotes` are not used as well

Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/common/useTradingExchangeQuotesFilter.ts]: deleted

Comment (vytick) [inline packages/suite/src/hooks/wallet/trading/form/common/useTradingExchangeQuotesFilter.ts]: now i realised, we can use `arrayPartition` to populate `cexQuotes` and `dexQuotes`

Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/common/useTradingExchangeQuotesFilter.ts]: done

**Review by vytick — APPROVED** [review]
lgtm 👌

**Review by izmy — APPROVED** [review]
