### PR TITLE
fix(native-suite): device setting actions refactor

### LINKED ISSUE #17648: Unexpected PIN Change Prompt
**Describe the bug**
There is an edge case where a Trezor device unexpectedly offers a PIN change

**Info:**

-   Mobile Suite Version: 25.3.2/6fdcff3bac
-   OS: Android

**How to reproduce**

1.	Have a disconnected, remembered (view-only) Trezor.
2.	Go to Device Settings.
3.	Open Change PIN, then close it.
4.	Open Firmware Update.
5.	Connect the Trezor.
6.	The Trezor unexpectedly prompts for a PIN change.

**Expected behavior**
The Trezor should not trigger a PIN change prompt unless explicitly requested by the user.

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

Prevent triggering device setting actions unintentionally.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17648

### Before

https://github.com/user-attachments/assets/72a63b5f-952e-4e56-9050-a20f9bfe1adf

https://github.com/user-attachments/assets/f15ff190-8ac4-4610-8a77-5773e02e52a0

### After

https://github.com/user-attachments/assets/876bc091-70d6-4900-84da-32f94a2605d5

https://github.com/user-attachments/assets/4ce28e10-9042-4a12-97d0-d9a7edd3ad5a

### CODE REVIEW

File: suite-native/module-device-settings/src/hooks/usePinAction.tsx [hunk 1]
```diff
@@ -0,0 +1,144 @@
...
+import { useToast } from '@suite-native/toasts';
+import TrezorConnect from '@trezor/connect';
+
+type NavigationProp = StackNavigationProps<
+    DeviceSettingsStackParamList,
+    DeviceStackRoutes.DevicePinProtection
+>;
+
+type ActionConfig = {
+    param: boolean | undefined;
```
Comment (matejkriz) [inline suite-native/module-device-settings/src/hooks/usePinAction.tsx]: nitpick, feel free to ignore it because it was there before and I know it's not something you changed, but the name of the param `param` is cryptic and it would be nice to rename it to something like `remove` or make it generic same as on desktop by passing all params with type from Connect `Parameters<typeof TrezorConnect.changePin>[0]`

File: suite-native/module-device-settings/src/components/DeviceInteractionScreenWrapper.tsx [hunk 2]
```diff
@@ -18,6 +19,7 @@ export const DeviceInteractionScreenWrapper = ({
     const device = useSelector(selectSelectedDevice);
 
     const closeAction = useCallback(() => {
+        TrezorConnect.cancel();
```
Comment (matejkriz) [inline suite-native/module-device-settings/src/components/DeviceInteractionScreenWrapper.tsx]: This was removed in the previous commit and the second commit put it back, which I believe is correct.

File: suite-native/module-device-settings/src/hooks/useDeviceChangedCheck.ts [hunk 3]
```diff
@@ -35,6 +36,7 @@ export const useDeviceChangedCheck = () => {
 
         // Check for device mismatch only after initial device ID is set
         if (initialDeviceIdRef.current && device?.id && initialDeviceIdRef.current !== device.id) {
+            TrezorConnect.cancel();
```
Comment (matejkriz) [inline suite-native/module-device-settings/src/hooks/useDeviceChangedCheck.ts:39]: I'm not sure this is safe if we don't know what is it canceling.

File: suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+                navigation.navigate(DeviceAuthenticityStackRoutes.AuthenticitySummary, {
+                    checkResult: 'compromised',
+                });
+                reportCheckResult('failed');
+            }
+        }
+    }, [device, navigation, reportCheckResult]);
+
+    useEffect(() => {
+        if (isDeviceConnected) void checkAuthenticity();
```
Comment (matejkriz) [inline suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts]: First time I see someone using void like this. What is the benefit? Should we use it everywhere? If there is no benefit I would remove it for consistency.

File: suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+
+        // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (matejkriz) [inline suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts:80]: Is that really necessary here? Why don't you just add `checkAuthenticity` to dependencies?

**Review by matejkriz — COMMENTED** [review]
Few nits so far, I would like to test and think about the TrezorConnect.cancel() placement.

File: suite-native/module-device-settings/src/components/DeviceInteractionScreenWrapper.tsx (hunk 2 above)
Comment (BrantalikP) [reply suite-native/module-device-settings/src/components/DeviceInteractionScreenWrapper.tsx]: Yeah, the initial idea was to call `TrezorConnect.cancel `in `useEffect` on a specific screen when the user leaves the page.

```
useEffect(() => () => {
  if (deviceConnected) TrezorConnect.cancel();
}, []);
```

or something similar. But then, I realized two reasons why this wouldn’t be a good idea:

1. @yanascz  mentioned that he wants to reuse the `ContinueOnTrezor` page for his Bluetooth implementation as well, so I didn’t want to create obstacles for his implementation.

2.	If T`rezorConnect.cancel` were called twice (once in `useEffect` and once by pressing the `close` button), it caused issues where, if you tried to change the PIN or trigger another device setting action right after, it wouldn’t get triggered.

File: suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts (hunk 4 above)
Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts]: It’s just explicitly stating that there’s no need to wait for this async function to finish. I’m not sure if there was an `ESLint` warning or if it’s just something I’m used to doing. It makes it clear that I have not forgot to put `await` prefix  before the function

File: suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts (hunk 5 above)
Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts:80]: Because the `checkAuthenticity` has `device` as dependencies therefore IMHO it could trigger the `useEffect`, unintentionally?

File: suite-native/module-device-settings/src/hooks/useDeviceChangedCheck.ts (hunk 3 above)
Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/useDeviceChangedCheck.ts:39]: Yeah, you have more knowledge about it, but I assumed, based on its usage in the `ContinueOnTrezor` page, that it’s just canceling any ongoing action on `Trezor`. It’s more like a `cleanup` before leaving the page and as I know it used solely for handling incorrect device that has been connected on Device Setting screen, tbh not sure if there might be other scenariosu where it can caused issues

But if there are any concerns, I’m happy to change it. Thanks!

File: suite-native/module-device-settings/src/hooks/usePinAction.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/usePinAction.tsx]: https://github.com/trezor/trezor-suite/pull/17689/commits/3d5164a30ec1bcf5f8517850406b222fe2619319 as the latter option would require changes also in the `actionConfigMap` I opted for the first one.

File: suite-native/module-device-settings/src/hooks/useDeviceChangedCheck.ts (hunk 3 above)
Comment (matejkriz) [reply suite-native/module-device-settings/src/hooks/useDeviceChangedCheck.ts:39]: From my testing, it seems to work fine 👌

File: suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts (hunk 4 above)
Comment (matejkriz) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts]: We don't have any eslint warning for that, so I would strongly prefer to remove it to stay consistent. If you find that rule useful, let's discuss with a whole team if we can add it 🙏

Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts]: image

Oh ok this I tried to solve. IMHO using `void` is the cleanest way. Or do you have any other prefered solution. 

I would want to try to avoid something like this ﻿ ` if (isDeviceConnected) (async () => await checkAuthenticity())();` 😅

File: suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts (hunk 5 above)
Comment (matejkriz) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts:80]: You are right, if you add checkAuthenticity as a dependency, this effect is triggered multiple times. Would be great to mention the reason in a comment here (and for handlePinAction too).

Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts:80]: https://github.com/trezor/trezor-suite/pull/17689/commits/7656c2de293a5f1973d86971be07f66001493f9f  https://github.com/trezor/trezor-suite/pull/17689/commits/fe43c74f8f3f07ab20abebf942d1f87dba5bf9db

File: suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts (hunk 4 above)
Comment (matejkriz) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts]: Is that coming from your local eslint config? I don't see that warning if I run `yarn run lint:js`

Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts]: you might be right. new IDE new issues. Going to disable it in favor of the project setup (once I find it ). I push fixups. Thanks!

Comment (BrantalikP) [reply suite-native/module-device-settings/src/hooks/useDeviceAuthenticityAction.ts]: IDE warning suppressed https://github.com/trezor/trezor-suite/pull/17689/commits/29f47ee0a4c4489b44eca3076a09d5b8e5ad3dcd https://github.com/trezor/trezor-suite/pull/17689/commits/de73286a153e50890e061db8124ddc1926d21cb3

**Review by matejkriz — APPROVED** [review]
Great job, works smooth for me 🎉

**Comment by matejkriz** [comment]
android E2E is failing on the same thing as on develop https://github.com/trezor/trezor-suite/actions/runs/13981866909/job/39148822012
