### PR TITLE
fix(suite-native): app crashes on graph

### LINKED ISSUE #11448: App crashes on graph
Steps to reproduce:
- Load wallet with Cardano and get fiat rates error (try different time scopes if it doesn't fail)
- Click somewhere in graph area
- See app crash

Suite Lite 24.1.1 Android

**Expected behavior:**
- App does not crash 
- Try again button do try again
(fixing fetching fiat rates is not part of scope of this issue)

image

https://satoshilabs.sentry.io/issues/5037970051/?project=4504214699245568&query=release:io.trezor.suite@24.3.1+45

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11448

### CODE REVIEW

File: suite-native/graph/src/components/GraphError.tsx [hunk 1]
```diff
@@ -36,23 +38,26 @@ const ErrorIcon = () => {
...
     return (
         <VStack spacing="small" alignItems="center" paddingHorizontal="medium">
             <ErrorIcon />
             <Animated.View entering={FadeInDown} exiting={FadeOutUp}>
                 <Text variant="hint" color="textSubdued" textAlign="center">
-                    There are some troubles with loading graph points: {error}
+                    {translate('graph.errorMessage')}
+                    {error}
                 </Text>
-                <Text.Pressable
```
Comment (Nodonisko) [inline suite-native/graph/src/components/GraphError.tsx:47]: What's wrong with this pressable?

File: suite-native/react-native-graph/src/AnimatedLineGraph.tsx [hunk 2]
```diff
@@ -355,11 +355,18 @@ export function AnimatedLineGraph<TEventPayload extends object>({
         (fingerX: number) => {
             const fingerXInRange = Math.max(fingerX - horizontalPadding, 0);
 
+            const date = pointsInRange[pointsInRange.length - 1];
```
Comment (Nodonisko) [inline suite-native/react-native-graph/src/AnimatedLineGraph.tsx]: name should be something like `lastDate`

File: suite-native/react-native-graph/src/AnimatedLineGraph.tsx [hunk 3]
```diff
@@ -355,11 +355,18 @@ export function AnimatedLineGraph<TEventPayload extends object>({
...
+            if (!date) {
+                return;
+            }
+
             const index = Math.round(
                 (fingerXInRange /
                     getXInRange(
                         drawingWidth,
-                        pointsInRange[pointsInRange.length - 1]!.date,
+                        pointsInRange[pointsInRange.length - 1].date,
```
Comment (Nodonisko) [inline suite-native/react-native-graph/src/AnimatedLineGraph.tsx]: You can use `lastDate` const here

File: suite-native/graph/src/components/Graph.tsx [hunk 4]
```diff
@@ -127,7 +127,7 @@ export const Graph = <TGraphPoint extends FiatGraphPoint>({
                 style={applyStyle(graphStyle, { loading, error })}
                 points={points}
                 color={colors.borderSecondary}
-                animated={animated}
+                animated={animated && !error}
```
Comment (Nodonisko) [inline suite-native/graph/src/components/Graph.tsx]: why?

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/graph/src/components/GraphError.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/graph/src/components/GraphError.tsx:47]: It's not propagating the event and the `onPress` is not working somehow. I don't have a clue why, but it's the only usage so I guess wrapping with `Pressable` is pretty good, since the `Text` is still going to be performant, just wrapped.

File: suite-native/graph/src/components/Graph.tsx (hunk 4 above)
Comment (juriczech) [reply suite-native/graph/src/components/Graph.tsx]: I guess no animation is needed when there is error in graph? This doesn't effect the bug that was there, but seemed pointless to do animation below graph error. I can revert it if you think it's better.

File: suite-native/react-native-graph/src/AnimatedLineGraph.tsx (hunk 3 above)
Comment (juriczech) [reply suite-native/react-native-graph/src/AnimatedLineGraph.tsx]: Yeah, that's the whole point of why I created the const :D Then I forgot, good catch 
https://github.com/trezor/trezor-suite/pull/11495/commits/b2a360134ec65b9942c730967614b04651b13c9b

File: suite-native/react-native-graph/src/AnimatedLineGraph.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/react-native-graph/src/AnimatedLineGraph.tsx]: https://github.com/trezor/trezor-suite/pull/11495/commits/b2a360134ec65b9942c730967614b04651b13c9b

File: suite-native/graph/src/components/GraphError.tsx (hunk 1 above)
Comment (Nodonisko) [reply suite-native/graph/src/components/GraphError.tsx:47]: If it's not working we should remove that Text.Pressable completely

File: suite-native/graph/src/components/Graph.tsx (hunk 4 above)
Comment (Nodonisko) [reply suite-native/graph/src/components/Graph.tsx]: I woudn't mess with this there might be some edge cases when we will want this.

File: suite-native/graph/src/components/GraphError.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/graph/src/components/GraphError.tsx:47]: https://github.com/trezor/trezor-suite/pull/11495/commits/a35c02f7b15e79085b5910adb9628e61425302ce

File: suite-native/graph/src/components/Graph.tsx (hunk 4 above)
Comment (juriczech) [reply suite-native/graph/src/components/Graph.tsx]: I reverted it here, but might be worth discussing this sometimes to improve the functionality in error state. 
https://github.com/trezor/trezor-suite/pull/11495/commits/364301f34a652fb2940e09fbaf313bb33a3d15c4

File: suite-native/atoms/src/Text.tsx [hunk 5]
```diff
@@ -21,23 +21,13 @@ const DefaultTextComponent: typeof RNText = Platform.select({
...
 
-// NativeText does not support all the props that are supported by the standard `react-native` Text.
-type UnsupportedNativeTextProps =
-    | 'pressRetentionOffset'
-    | 'onLongPress'
-    | 'onPress'
-    | 'onPressIn'
-    | 'onPressOut';
-
-export type TextProps = Omit<PressableTextProps, UnsupportedNativeTextProps>;
```
Comment (Nodonisko) [inline suite-native/atoms/src/Text.tsx:39]: This is necessary these props are not supported in Text so they shoudn't be availeble in TS

Comment (juriczech) [reply suite-native/atoms/src/Text.tsx:39]: Fixed

**Review by Nodonisko — APPROVED** [review]
