### PR TITLE
Fix/Missing FIAT amounts in tx-detail modal

### LINKED ISSUE #2638: Missing FIAT ammount in Transaction Detail modal
**Info:**
 - OS: Nixos + Windows
 - Browser: Chromium 85
 - Wallet Version: app + web, commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 - Firmware Version: 2.3.4 + 1.8.3
 
**Describe the bug**
There is one value missing in Transaction Detail, amount of sent coins in FIAT value.
Please see screenshot

**Steps to reproduce:**
1. load suite.trezor.io
2. load any accounts from device 
3. check Transaction Detail modal, it's missing one value

**Expected result:**
You will see current FIAT value of sent coins

**Actual result:**
You don't see current FIAT value of sent coins

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by robertbrada**
fix https://github.com/trezor/trezor-suite/issues/2638

The problem was that we compared **UPPERCASE** value with **lowercase** value

### CODE REVIEW

**Review by slowbackspace — APPROVED** [review]

**Review by keraf — APPROVED** [review]

File: packages/suite/src/components/suite/FiatValue/index.tsx [hunk 1]
```diff
@@ -37,7 +37,10 @@ const FiatValue = ({
     ...props
 }: Props) => {
     const targetCurrency = fiatCurrency ?? props.settings.localCurrency;
-    const currentFiatRates = props.fiat.coins.find(f => f.symbol === symbol)?.current;
```
Comment (szymonlesisz) [inline packages/suite/src/components/suite/FiatValue/index.tsx:40]: since we know where the issue is maybe it should be fixed in the source (connect? blockchain-link?)
which symbol was in upperCase here?

Comment (robertbrada) [reply packages/suite/src/components/suite/FiatValue/index.tsx:40]: `symbol`  was in upperCase in case of token transfer (because of lines 61:63 in `AmountDetails` in the old version).

If I just remove the unnecessary `toUpperCase()` from `AmountDetails`, the code works ok for now. 

I used `toLowerCase()` here in  `FiatValue` just to double-check this kind of error won't happen again.
