### PR TITLE
style: fix huge values overflowing in token list

### LINKED ISSUE #2555: Tokens: Unnecessary overflow
Let's aling `Balance – USDT` in one line. 

Screenshot 2020-10-08 at 15 06 00

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/2555

### CODE REVIEW

File: packages/suite/src/components/suite/FormattedCryptoAmount/index.tsx [hunk 1]
```diff
@@ -18,7 +20,7 @@ const FormattedCryptoAmount = ({ value, symbol, disableHiddenPlaceholder, classN
     const content = (
         <>
             <Value>{value}</Value>
-            {symbol && <Symbol>{` ${symbol.toUpperCase()}`}</Symbol>}
```
Comment (szymonlesisz) [inline packages/suite/src/components/suite/FormattedCryptoAmount/index.tsx]: are we using `&nbsp;` now? i thought i saw your discussion with @keraf where you convinced him that it's better to use `{' '}` instead?
anyway, i already did a little change in this component here so we may have a conflict 
https://github.com/trezor/trezor-suite/pull/2626/commits/2e5a65eadd15ca55d7f4385861af00a70d71544e

File: packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx [hunk 2]
```diff
@@ -97,18 +114,15 @@ const TokenList = ({ tokens, explorerUrl, isTestnet }: Props) => {
                     return (
                         <Fragment key={t.address}>
                             <Col isTestnet={isTestnet}>
-                                <TokenName>
+                                <TokenNameWrapper>
                                     <TokenSymbol>{t.symbol?.toUpperCase()}</TokenSymbol>
-                                    {` - ${t.name}`}
-                                </TokenName>
+                                    <TokenName> - {t.name}</TokenName>
```
Comment (szymonlesisz) [inline packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx:120]: space before `-` will not work anymore is it intended?

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/FormattedCryptoAmount/index.tsx (hunk 1 above)
Comment (slowbackspace) [reply packages/suite/src/components/suite/FormattedCryptoAmount/index.tsx]: `&nbsp;` has its use, it is literally non-breaking space. It is good to know that it is not 1:1 replacement for a space (if you would use nbsp everywhere instead of regular space, you could end up with funky line breaking behaviour).

I used it here, cause it seems that nothing else really works if the parent of `FormattedCryptoAmount` is flex container (and I need it in token list to properly truncate crypto amounts). I assume that there won't be a case where we would want to have `Value` and `Symbol` break over 2 lines so nbsp seems okay here.

File: packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx (hunk 2 above)
Comment (slowbackspace) [reply packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx:120]: yup, I think it didn't even worked before, there is margin-right on `TokenSymbol`
