### PR TITLE
fix(suite-native): prevent occasional data losses

### LINKED ISSUE #16746: Occasional data loss
Several people reported data loss after updating the iOS app. They had to re-import all accounts. This Sentry issue might be related (but it's not confirmed yet)

There were also some reports from Android. There is probably different cause with the same result.

Sentry Issue: [SUITE-NATIVE-MT](https://satoshilabs.sentry.io/issues/5118977032/?referrer=github_integration)

```
Error: Calling the 'setValueWithKeyAsync' function has failed
→ Caused by: User interaction is not allowed.
  at _callSuper (app:///main.jsbundle:6:38)
...
(2 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

From Sentry reports it seems that on iOS it happens mostly on the background without user interaction (hypothesis is that after automatic app update iOS starts the app).

On Android, it might happen during app start from time to time, not sure why and when.

When the reading from the secure store fails, we used to immediately reset the key and make all user data inaccessible. Now we will always ask the user to either try to restart the app or reset the storage if it doesn't help.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16746

## Screenshots:
image
image

### CODE REVIEW

File: suite-native/storage/src/storage.ts [hunk 1]
```diff
@@ -39,33 +53,37 @@ export const clearStorage = () => {
     RNRestart.restart();
 };
 
-// Ideally it should never happen but we need to be sure that at least some message is displayed.
-// If someone will mess with encryptionKey it can corrupt storage and app will crash on startup.
-// Then app will hang on splashscreen indefinitely so we at least want to show some error message.
+const alertUser = () => {
+    SplashScreen.hideAsync();
+    Alert.alert(
+        'We couldn’t load your data',
```
Comment (matejkriz) [inline suite-native/storage/src/storage.ts]: Not translatable so far and it can be a small challenge here - we will probably need to store the selected language in some other storage without SecureStore to make it available here. Or we might rely on system default language here. But let's solve this together with other localization issues later.

Comment (PeKne) [reply suite-native/storage/src/storage.ts]: Relying on the system language seems reasonable to me 👍

**Review by PeKne — APPROVED** [review]
I don't know how to test it, but the code looks good to me.

File: suite-native/storage/src/storage.ts [hunk 2]
```diff
@@ -16,18 +16,32 @@ export const ENCRYPTED_STORAGE_ID = 'trezorSuite-app-storage';
...
-        // Some users are facing an error when they uninstall the app and then reinstall it,
-        // see https://github.com/expo/expo/issues/23426
-        await SecureStore.deleteItemAsync(ENCRYPTION_KEY);
-        captureException(error);
+        // If there is an error, report it and try to read one more time.
+        captureException(error, { tags: { attempt: 1 } });
+        try {
+            // There were some trouble reading from the SecureStore,
+            // let's wait a bit to make sure it wasn't just temporary error.
+            await new Promise(resolve => setTimeout(resolve, 100));
```
Comment (Nodonisko) [inline suite-native/storage/src/storage.ts:28]: I not sure about this, I would try this only if anything else helped, otherwise this will always delay app startup time for 100ms which is quite a lot

File: suite-native/storage/src/storage.ts (hunk 1 above)
Comment (matejkriz) [reply suite-native/storage/src/storage.ts]: But it's not ideal if you have a default language that we don't support, but you prefer some other supported language than English...

File: suite-native/storage/src/storage.ts [hunk 3]
```diff
@@ -16,18 +16,32 @@ export const ENCRYPTED_STORAGE_ID = 'trezorSuite-app-storage';
...
+            secureKey = await SecureStore.getItemAsync(ENCRYPTION_KEY);
+        } catch (error) {
+            captureException(error, { tags: { attempt: 2 } });
```
Comment (Nodonisko) [inline suite-native/storage/src/storage.ts:31]: How is second attempt triggered? I don't see any invokation of this function again

**Review by Nodonisko — APPROVED** [review]

File: suite-native/state/src/StoreProvider.tsx [hunk 4]
```diff
@@ -14,23 +15,37 @@ type StoreProviderProps = {
...
+        if (!initStoreCalledRef.current && AppState.currentState === 'active') {
+            initStoreAsync();
+            subscription.remove();
+        }
 
-        initStoreAsync();
+        return () => {
+            subscription.remove();
+        };
     }, []);
```
[the remark this answers is not in the document]
Comment (matejkriz) [reply suite-native/state/src/StoreProvider.tsx:49]: It is intentional, there is no need to listen to app state change if store is already initialized.

File: suite-native/storage/src/storage.ts (hunk 2 above)
Comment (matejkriz) [reply suite-native/storage/src/storage.ts:28]: This is called only if it failed once - it is inside the catch block. For the first try, there is no artificial delay.

File: suite-native/storage/src/storage.ts (hunk 3 above)
Comment (matejkriz) [reply suite-native/storage/src/storage.ts:31]: The second attempt is triggered by the first attempt firing any error.

File: suite-native/storage/src/storage.ts [hunk 5]
```diff
@@ -39,33 +53,37 @@ export const clearStorage = () => {
     RNRestart.restart();
 };
 
-// Ideally it should never happen but we need to be sure that at least some message is displayed.
-// If someone will mess with encryptionKey it can corrupt storage and app will crash on startup.
-// Then app will hang on splashscreen indefinitely so we at least want to show some error message.
+const alertUser = () => {
+    SplashScreen.hideAsync();
```
Comment (Nodonisko) [inline suite-native/storage/src/storage.ts:59]: 🐰 is partially correct here, it's not clear why there duplication of hiding splashscreen, please add comment why

File: suite-native/storage/src/storage.ts (hunk 1 above)
Comment (Nodonisko) [reply suite-native/storage/src/storage.ts]: I would not bother with this here at all, ideally no one should see this

File: suite-native/storage/src/storage.ts (hunk 2 above)
Comment (Nodonisko) [reply suite-native/storage/src/storage.ts:28]: I did read it wrong, so it's fine

File: suite-native/storage/src/storage.ts [hunk 6]
```diff
@@ -39,33 +53,37 @@ export const clearStorage = () => {
...
+    Alert.alert(
+        'We couldn’t load your data',
+        'Try restarting the app first. If the problem persists, you’ll need to wipe this app’s storage.',
+        [
+            {
+                text: 'Reset Storage',
+                onPress: clearStorage,
```
Comment (Nodonisko) [inline suite-native/storage/src/storage.ts:66]: We should probably track in Sentry if user decides to click this as error, because it is :D

File: suite-native/storage/src/storage.ts (hunk 5 above)
Comment (matejkriz) [reply suite-native/storage/src/storage.ts:59]: comment added, does it makes better sense? https://github.com/trezor/trezor-suite/pull/16819/commits/ea99dc780716c8dcfc56aea1db8b0664f64646e0

File: suite-native/storage/src/storage.ts [hunk 7]
```diff
@@ -39,33 +53,37 @@ export const clearStorage = () => {
...
+                text: 'Restart app',
+                onPress: () => {
+                    RNRestart.restart();
+                },
+                isPreferred: true,
+                style: 'default',
+            },
+        ],
+    );
+};
```
[the remark this answers is not in the document]
Comment (matejkriz) [reply suite-native/storage/src/storage.ts]: There is no problem in calling SplashScreen.hideAsync() multiple times and it can't happen here - if there is any issue with loading storage, app can't start and splash screen is never hidden from the App.tsx. Explanation comment added.

File: suite-native/storage/src/storage.ts (hunk 6 above)
Comment (matejkriz) [reply suite-native/storage/src/storage.ts:66]: Good idea, added here [`b181a9d` (#16819)](https://github.com/trezor/trezor-suite/pull/16819/commits/b181a9d16fd7fd729fe1aa88186699a5dab110c5)

Example report https://satoshilabs.sentry.io/issues/6272721810/events/08b444862bb1487ba01a70a5cdb1d37a/
