### PR TITLE
fix(graph): Btc test break portfolio graph

### LINKED ISSUE #6808: suite-native: Fix undefined balances for BTC TEST in graph
There was the problem _"Cannot convert undefined value to object"_

Image

...with these assets imported in the mobile app:

- BTC account from our "use dev xpub" button
- BTC test xpub: vpub5ZJFnFjoejaE2GUxf2nhq7Mgv5fzcg3v5CUrKdH7guiZeUhp55s41x6gyjRBU8j4NRVJzAFCVDy491Xgp9yATB42Bp1DEUyBoTnhKvfLXJT
- BTC test xpub 2: vpub5ZJFnFjoejaE6GCRq8aJjqQmZkqVcLZFYHoAoxFJntktMEvaFkreJUz47XMr3vym1Lb681PhHunzgdUetnyHSQTE9PuUmzXXE9ZB7ZPD7M9

The problem with "undefined" value comes from here https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-graph/src/graphUtils.ts#L555 so I have already started with fixing it here in this PR:

- https://github.com/trezor/trezor-suite/pull/6807

PR is in progress and the "undefined" problem described above is fixed there.

...now there is another problem for Portfolio graph. It is not an error but something is wrong with the summation of the balance for various different currencies together. See that BTC balance is **$97.39** but graph says "Zero balance in this range".

Image

Note: it works correctly in single account view, graph is shown (account detail) so I think the problem above is connected with planned issue https://github.com/trezor/trezor-suite/issues/6686

### PR DESCRIPTION
**Pull request by bouchja1**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/6808

### CODE REVIEW

File: suite-common/wallet-graph/src/graphThunks.ts [hunk 1]
```diff
@@ -64,6 +66,7 @@ const getSingleAccountTimeFrameItems = async (
     fiatCurrency: FiatCurrencyCode,
     timeFrame: LineGraphTimeFrameValues,
 ) => {
+    let zeroFiatRatesFallback = null;
```
Comment (juriczech) [inline suite-common/wallet-graph/src/graphThunks.ts:69]: I think this should be typed. If we assign anything to this var, it will use type inference because we're not saying what type it is.

Comment (juriczech) [inline suite-common/wallet-graph/src/graphThunks.ts:69]:
```suggestion
    let zeroFiatRatesFallback: FiatRates | null = null;
```

File: suite-common/wallet-graph/src/graphUtils.ts [hunk 2]
```diff
@@ -449,31 +450,45 @@ export const calcFakeGraphDataForTimestamps = (
...
+    // we can cache the result because currency symbols should be always same
+    if (zeroFiatRatesCache) return zeroFiatRatesCache;
+
+    // pass arbitrary coin to get supported fiat currency rates - we need this to get currency symbols
+    const anyFiatRates = await getFiatRatesForTimestamps(
+        { symbol: 'btc' },
+        timestampDatesInTimeFrame,
+    );
+
+    const fiatRates = (await anyFiatRates)?.tickers?.[0]?.rates;
```
Comment (juriczech) [inline suite-common/wallet-graph/src/graphUtils.ts:469]: nit: I don't like this wrapping of awaited function too much. I'm kind of used to storing the result into a variable to then use it for better readability.

File: suite-common/wallet-graph/src/graphUtils.ts [hunk 3]
```diff
@@ -759,6 +772,17 @@ export const fetchAccountBalanceHistoryWithBalanceBefore = async (
...
     );
+
+    const { symbol } = account;
+
+    // cannot find ticker config for symbol, e.g. BTC TEST - fallback to 0
+    if (!getTickerConfig({ symbol }) && zeroFiatRatesFallback) {
+        return balanceHistory.map(balanceHistoryPoint => ({
+            ...balanceHistoryPoint,
+            rates: zeroFiatRatesFallback,
+        }));
```
Comment (juriczech) [inline suite-common/wallet-graph/src/graphUtils.ts:783]: Q: Why use D.map above and not here? Is there a pattern or why did you not use it here?

File: suite-common/wallet-graph/src/graphThunks.ts (hunk 1 above)
Comment (Nodonisko) [reply suite-common/wallet-graph/src/graphThunks.ts:69]: It doesn't need to be, let the inference do the work. It you assign anything alse than should be here if it will throw in place of usage.

File: suite-common/wallet-graph/src/graphUtils.ts (hunk 3 above)
Comment (Nodonisko) [reply suite-common/wallet-graph/src/graphUtils.ts:783]: This is mapping over array

File: suite-common/wallet-graph/src/graphUtils.ts (hunk 2 above)
Comment (Nodonisko) [reply suite-common/wallet-graph/src/graphUtils.ts:469]: I would probably keep it this way, IMHO it's better like this instead of another name including zeroRates in it, just because I want to use it on next line

**Review by juriczech — APPROVED** [review]

File: suite-common/wallet-graph/src/graphThunks.ts (hunk 1 above)
Comment (Nodonisko) [reply suite-common/wallet-graph/src/graphThunks.ts:69]: Overtyping is anti pattern, it doesn't help type safety and then it makes problem during refactoring. You should let inheritance as much work as possible.

In modern type langues you are defining very few types only and rest is inherited
