### PR TITLE
fix(suite-native): use correct explorer

### LINKED ISSUE #21937: Wrong ETH and EVM explorers used on mobile
we should use the "scans" like on dekstop

https://github.com/user-attachments/assets/9157715e-c14e-4354-a44f-c7bc26a9577b

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Use correct explorer URLs on mobile.

## Related Issue

Resolve #21937 

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/explorer&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/explorer&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/explorer&lookback=7)

### CODE REVIEW

**Review by matusbalascak — APPROVED** [review]

File: suite-native/transactions/src/screens/TransactionDetailScreen.tsx [hunk 1]
```diff
@@ -40,8 +41,8 @@ export const TransactionDetailScreen = ({
     const transaction = useSelector((state: TransactionsRootState) =>
         selectTransactionByAccountKeyAndTxid(state, accountKey, txid),
     ) as WalletAccountTransaction;
-    const blockchainExplorer = useSelector((state: BlockchainRootState) =>
-        selectBlockchainExplorerBySymbol(state, transaction?.symbol),
```
Comment (vytick) [inline suite-native/transactions/src/screens/TransactionDetailScreen.tsx:44]: after removing it, `selectBlockchainExplorerBySymbol` is not used at all.

File: suite-native/transactions/src/screens/TransactionDetailScreen.tsx [hunk 2]
```diff
@@ -72,7 +73,8 @@ export const TransactionDetailScreen = ({
     const handleOpenBlockchain = () => {
         if (!blockchainExplorer) return;
         analytics.report({ type: EventType.TransactionDetailExploreInBlockchain });
-        openLink(`${blockchainExplorer.tx}${transaction.txid}`);
```
Comment (vytick) [inline suite-native/transactions/src/screens/TransactionDetailScreen.tsx:75]: Actually why do we have `wallet.explorer` and `wallet.blockchain.explorer`? Is the `wallet.blockchain.explorer` now used at all? From a brief search it seems to me that it is not and we can delete it from `wallet.blockchain`

Comment (vytick) [reply suite-native/transactions/src/screens/TransactionDetailScreen.tsx:75]: We agreed, it will be refactored in #22141

File: suite-native/transactions/src/screens/TransactionDetailScreen.tsx (hunk 1 above)
Comment (TomasBoda) [reply suite-native/transactions/src/screens/TransactionDetailScreen.tsx:44]: removed

**Review by vytick — APPROVED** [review]
