### PR TITLE
fix(dark-mode): dont reset theme on db error

### LINKED ISSUE #2738: Dark mode 🌃
Design: [Zeplin](https://zpl.io/beZg7nN)

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/2738#issuecomment-729516722

tested by our dear QA

I think for the next release I am gonna move the logic for auto selecting the correct theme from ThemeProvider to one time action triggered on inital run or something. Should be less complex to deal with.

### CODE REVIEW

File: packages/suite/src/support/suite/ThemeProvider.tsx [hunk 1]
```diff
@@ -52,13 +54,13 @@ const ThemeProvider: React.FC = ({ children }) => {
         }
 
         // set active theme OS based theme only if there are no saved settings
-        if (storedTheme === null) {
+        if (storedTheme === null && !error) {
```
Comment (mroz22) [inline packages/suite/src/support/suite/ThemeProvider.tsx:57]: do I understand correctly that you don't want this condition evaluate to `true` if there is error set on line 48? Shouldn't there be `return` after `setError` then?

Comment (slowbackspace) [reply packages/suite/src/support/suite/ThemeProvider.tsx:57]: Yup, you do get that right. I don't see how the return would help though, setError is in separate async function and I don't work with its return value.
