### PR TITLE
fix(coinmarket): fix crypto formatter for unknown network

### LINKED ISSUE #9332: TypeError: Cannot destructure property 'decimals' of 'r.QW[n]' as it is undefined.
Sentry Issue: [TREZOR-SUITE-V08](https://satoshilabs.sentry.io/issues/4413266795/?referrer=github_integration)

```
TypeError: Cannot destructure property 'decimals' of 'r.QW[n]' as it is undefined.
  at None (/web/js/32143.4292b3f3.js:1:1629065)
  at n.format (/web/js/32143.4292b3f3.js:1:1628355)
  at Object.limits (/web/js/32143.4292b3f3.js:1:1481051)
  at lt (/web/js/59589.42bcc9b6.js:2:3124667)
  at async z (/web/js/59589.42bcc9b6.js:2:3132921)
...
(3 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by FreeWall**
## Description

Default 0 decimals for unknown network

## Related Issue

Resolve #9332

### CODE REVIEW

File: suite-common/formatters/src/formatters/prepareCryptoAmountFormatter.ts [hunk 1]
```diff
@@ -49,8 +49,7 @@ export const prepareCryptoAmountFormatter = (config: FormatterConfig) =>
         ) => {
             const { bitcoinAmountUnit } = config;
 
-            // TS thinks that symbol is undefined, but it's required in type CryptoAmountFormatterDataContext so it's safe to use "!"
-            const { decimals } = networks[symbol!];
+            const { decimals } = symbol && networks[symbol] ? networks[symbol] : { decimals: 0 };
```
Comment (dahaca) [inline suite-common/formatters/src/formatters/prepareCryptoAmountFormatter.ts]:
```suggestion
            const decimals = networks[symbol!]?.decimals || 0;
```

Comment (FreeWall) [reply suite-common/formatters/src/formatters/prepareCryptoAmountFormatter.ts]: fixed https://github.com/trezor/trezor-suite/pull/10083/commits/636b082e83437fd14b35e09eb8bbc0e8085719f9

**Review by dahaca — APPROVED** [review]
