### PR TITLE
Fix/cardano

### LINKED ISSUE #11539: Short symbol name unrecognised tokens include '...' in its name in send form
**Describe the bug**
Screenshot 2024-03-11 at 13 01 12

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- there was endless loading for cardano tokens when coingecko fiat fetch failed
- there was loading state when fiat rate had error
- solana and cardano had different logic for missing symbol name, unified
- remove using custom cardano componens for select. Now it is same for EVM. Solana and Cardano.
  - I guess we will have to improve it anyway in the future to show contract address somehow, maybe on hover..

## Related Issue

Fix [#11539](https://github.com/trezor/trezor-suite/issues/11539)

## Screenshots:

Screenshot 2024-05-08 at 16 51 23
Screenshot 2024-05-08 at 16 51 12
Screenshot 2024-05-08 at 16 51 05
Screenshot 2024-05-08 at 16 49 46
Screenshot 2024-05-08 at 16 49 30
Screenshot 2024-05-08 at 16 49 20

### CODE REVIEW

**Review by marekrjpolak — APPROVED** [review]
Haven't reviewed UI part, the rest seems good.

File: suite-common/fiat-services/src/rates.ts [hunk 1]
```diff
@@ -82,6 +82,10 @@ export const fetchCurrentFiatRates = async ({
 
     const coingeckoResponse = await coingeckoService.fetchCurrentFiatRates(ticker);
 
+    if (!coingeckoResponse) {
+        return null;
+    }
+
```
Comment (AdamSchinzel) [inline suite-common/fiat-services/src/rates.ts:88]: It would be good to add this also to `fetchLastWeekFiatRates` and `getFiatRatesForTimestamps` functions

**Review by AdamSchinzel — CHANGES_REQUESTED** [review]

File: suite-common/fiat-services/src/rates.ts (hunk 1 above)
Comment (tomasklim) [reply suite-common/fiat-services/src/rates.ts:88]: 1e868530ef7b26a641d67d257f6b07531de5faf9

**Review by AdamSchinzel — APPROVED** [review]
LGTM

**Comment by MiroslavProchazka** [comment]
Please adjust the commit messages and squash it to preferably one commit. Thx!

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.5.2 (1ca8b8063fd7028d1fe242db41caa31c0a1f7d5a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
