### PR TITLE
fix(coinmarket): quotes fixes

### LINKED ISSUE #14132: Coinmarket - Featured offers wrong receive amount
**Describe the bug**
Featured offers show wrong receive amount

**How to reproduce**

1. Go to Bitcoin trade section
1. Fill out 100 EUR to buy
1. Wait till featured offers load
1. See wrong amount in featured offers

**Expected behavior**
Featured offers show wrong receive amount

**Screenshots**
image

### LINKED ISSUE #14142: Coinmarket - sllipage tolerance not changable
## Issue
It is not possible to change _Slippage tolerance_ and errors are in the console

## Expected behavior
To change _Slippage tolerance_ without console errors

## How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some `ETH` token to get DEX offers
3. Select DEX on the right side
4. Click on Exchange
image

##  Screenshots 
image
image

### LINKED ISSUE #14144: Coinmarket - incomplete list in the exchange comparator
## Describe the bug
Floating quotes and DEX are separated.

## Expected behavior
There should be only two lists of quotes at all - **fixed** and **floating** list of quotes. Fixed quotes will remain unchanged, while floating quotes will be unified with the DEX.

## How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some `ETH` token to get DEX offers
3. Select __Compare all offers__
image

## Design after (quotes after - first quote DEX and then other floating quotes)
image

### LINKED ISSUE #14146: Coinmarket - design for no offers available
## Describe the bug
Small font size and separate text on two lines

## Design before
image

## Design after
image

### LINKED ISSUE #14147: Coinmarket - missing cryptocurrency
## Design before
image

## Design after
image

### LINKED ISSUE #14151: Coinmarket - timer is below 0s in Exchange
## Describe the bug
[Screencast from 2024-09-05 12-59-31.webm](https://github.com/user-attachments/assets/adb1f670-fbe2-4b84-8a10-5d7dc683af93)

## How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some ETH token to get DEX offers
3. Select Compare all offers

### PR DESCRIPTION
**Pull request by adderpositive**
### It should be `€50.00 -> 0.00093833 BTC`  not `€50.00 -> 50 BTC`  
image

## 2. Issue
It is not possible to change _Slippage tolerance_ and errors are in the console

### Expected behavior
To change _Slippage tolerance_ without console errors

### How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some `ETH` token to get DEX offers
3. Select DEX on the right side
4. Click on Exchange
image

###  Screenshots 
image
image

## 3. Issue
Floating quotes and DEX are separated.

### Expected behavior
There should be only two lists of quotes at all - **fixed** and **floating** list of quotes. Fixed quotes will remain unchanged, while floating quotes will be unified with the DEX.

### How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some `ETH` token to get DEX offers
3. Select __Compare all offers__
image

### Design after (quotes after - first quote DEX and then other floating quotes)
image

## 4. Issue
Small font size and separate text on two lines

### Design before
image

### Design after
image

### Design before
image

### Design after
image

### Describe the bug
[Screencast from 2024-09-05 12-59-31.webm](https://github.com/user-attachments/assets/adb1f670-fbe2-4b84-8a10-5d7dc683af93)

### How to reproduce
1. Go to Trade - Exchange
2. Choose `From` ETH and `To` some ETH token to get DEX offers
3. Select Compare all offers

## Related Issue
1. Resolve https://github.com/trezor/trezor-suite/issues/14132
2. Resolve https://github.com/trezor/trezor-suite/issues/14142
3. Resolve https://github.com/trezor/trezor-suite/issues/14144
4. Resolve https://github.com/trezor/trezor-suite/issues/14146
5. Resolve https://github.com/trezor/trezor-suite/issues/14147
6. Resolve https://github.com/trezor/trezor-suite/issues/14151

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendSwap.tsx [hunk 1]
```diff
@@ -158,39 +159,44 @@ export const CoinmarketOfferExchangeSendSwap = () => {
     const { account, callInProgress, selectedQuote, exchangeInfo, confirmTrade, sendTransaction } =
         useCoinmarketFormContext<CoinmarketTradeExchangeType>();
     const [slippageSettings, setSlippageSettings] = useState(false);
-    const [slippage, setSlippage] = useState(selectedQuote?.swapSlippage || '1');
+    const selectedQuoteHelper = { ...selectedQuote };
```
Comment (Lemonexe) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendSwap.tsx:162]: What is the reason to create a copy?
As far as I can see, the object is not mutated anywhere, so why can't you use the original?

**Review by Lemonexe — APPROVED** [review]
LGTM :rocket: 
I've checked all of the issues and they seem to be working fine now :heavy_check_mark:

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendSwap.tsx (hunk 1 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendSwap.tsx:162]: There is an object mutation in the code below. This is necessary because it comes from a Redux state, which is read-only.

```
selectedQuoteHelper.swapSlippage = customSlippage;
selectedQuoteHelper.approvalType = undefined;
```

A better approach would be to refactor the code to avoid mutating the object and use `dispatch` instead.

Comment (Lemonexe) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendSwap.tsx:162]: Right, I did not notice where the mutation happens, nvm.
