### PR TITLE
Fix firmware progress bar

### LINKED ISSUE #21393: Firmware progress mess
This happens on TS7 irrespective of BT/cable:

https://github.com/user-attachments/assets/6b1907e7-84b9-4e99-82e5-5d4c675e61fa

Related: https://github.com/trezor/trezor-suite/pull/20941

- Firmware progress should not be shown until installation starts.
- It should not go from 100% to 0% at the start
- It should show the check mark for Done when it hasn't started yet.

### PR DESCRIPTION
**Pull request by 5K1PY**
Don't show wrong percentage in firmware progress bar in certain circumstances.

## Related Issue

Resolve #21393

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/firmware-progress&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/firmware-progress&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/firmware-progress&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx [hunk 1]
```diff
@@ -30,6 +30,12 @@ export const FirmwareProgressBar = () => {
         completed: 'TR_FIRMWARE_STATUS_INSTALLATION_COMPLETED',
     };
 
+    if (uiEvent?.type === 'ui-firmware_reconnect') {
+        console.warn('RECONNECT!!!', operation);
```
Comment (OriginalEveres) [inline packages/suite/src/components/firmware/FirmwareProgressBar.tsx]: maybe leftover?

**Review by OriginalEveres — APPROVED** [review]
LGTM, it fixes the non-BT FW install. I could not test the BT install due to FW issue.

Feel free to merge for now, we'll check it once the FW is fixed.

Just please double-check the failing tests.

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx (hunk 1 above)
Comment (OriginalEveres) [reply packages/suite/src/components/firmware/FirmwareProgressBar.tsx]: consider this console.warn and remove it if we don't need it

Comment (OriginalEveres) [reply packages/suite/src/components/firmware/FirmwareProgressBar.tsx]: I've removed the console log
