### PR TITLE
fix: trezord kill on app exit

### LINKED ISSUE #4904: After closing Suite window on Linux, trezor-suite, trezord and bindmount are not closed
**Describe the bug**
After closing Suite window, `trezor-suite`, `trezord` processes and tmpfs bindmount are not closed.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: Trezor-Suite-22.1.1-linux-x86_64.AppImage
 - Browser: used the AppImage version
 - OS: Ubuntu 20.04 LTS with KDE/Plasma desktop environment
 - Bridge: bundled
 - Firmware Version: 2.4.3 TT
 - Used Tor bridge that comes from torproject.org PPA (preinstalled)

**How to reproduce**
1. Open Suite
2. Click on an account, wait them to load
3. Exit Suite by closing window
4. Processes `trezor-suite`, `trezord` processes and tmpfs bindmount are not closed.

**Expected behavior**
Processes and tmpfs bindmount should be closed. I don't see any tray icon or anything, google doesn't think there is tray icon implemented, so I guess processes and mount along with bridge should've been closed.

**Additional context**

These processes remain after closing of suite.

```
 145504 ?        Ssl    0:01  \_ ./Trezor-Suite-22.1.1-linux-x86_64.AppImage
 145508 pts/22   S      0:00  \_ /tmp/.mount_TrezorPCzAze/trezor-suite --type=zygote --no-zygote-sandbox
 145509 pts/22   S      0:00  \_ /tmp/.mount_TrezorPCzAze/trezor-suite --type=zygote
 145512 pts/22   S      0:00  |   \_ /tmp/.mount_TrezorPCzAze/trezor-suite --type=zygote
 145579 pts/22   Sl     0:11  \_ /tmp/.mount_TrezorPCzAze/resources/bin/bridge/trezord

```

### PR DESCRIPTION
**Pull request by mroz22**
Found that there were 2 places stopping `before-quit` events from executing. 

-  when calling `mainWindow.getBounds()` inside `before-quite` event. Doing this feels wrong in general as this event is fired after `window-all-closed` so doing something with browserWindow instance which maybe (I am not sure yet, did not check that yet) does not exist anymore doesn't feel right. 
-  to my dismay, also calling `electronLocalshortcut.unregisterAll(mainWindow);` in `before-quit` stops further `before-quit` events from executing. I don't know why yet, but my first question is whether it is needed to unregister some event listeners for key presses when app is going to stop after few miliseconds anyway? 

As it is now, it should be fixing #4904 and also it fixes a bug (not sure if there is an issue) that window size is not saved and therefore can't be restored on next application run.

### CODE REVIEW

File: packages/suite-desktop/src-electron/app.ts [hunk 1]
```diff
@@ -83,6 +83,17 @@ const init = async () => {
...
+    mainWindow.on('resize', () => {
+        if (resizeDebounce) return;
+        resizeDebounce = setTimeout(() => {
+            resizeDebounce = null;
+            const winBound = mainWindow.getBounds() as WinBounds;
+            store.setWinBounds(winBound);
+            logger.debug('app', 'new winBounds saved');
+        }, 1000);
+    });
+
```
Comment (mroz22) [inline packages/suite-desktop/src-electron/app.ts:102]: not sure if debounce is necessary. `resize` event does not fire so often. but maybe it is "better" to do some debouncing here.

File: packages/suite-desktop/src-electron/modules/shortcuts.ts [hunk 2]
```diff
@@ -23,9 +22,11 @@ const init = ({ mainWindow, src }: Dependencies) => {
         mainWindow.loadURL(src);
     });
 
-    app.on('before-quit', () => {
-        electronLocalshortcut.unregisterAll(mainWindow);
-    });
+    // todo: calling electronLocalshortcut.unregisterAll(mainWindow) has unpleasant side-effect
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/modules/shortcuts.ts]: I believe that all local shortcuts should be unregistered at that point already by `electron-localshortcut` itself

File: packages/suite-desktop/src-electron/app.ts (hunk 1 above)
Comment (matejkriz) [reply packages/suite-desktop/src-electron/app.ts:102]: I believe debounce is a good idea here, but you have to check if `mainWindow` is still defined before trying to getBounds() and would be nice to clear that timeout on `closed`

Comment (mroz22) [reply packages/suite-desktop/src-electron/app.ts:102]: added [ca43b7a](https://github.com/trezor/trezor-suite/pull/4931/commits/ca43b7ad5e56f29b157ed50c7e0b3da7f72082e9)

File: packages/suite-desktop/src-electron/modules/shortcuts.ts (hunk 2 above)
Comment (mroz22) [reply packages/suite-desktop/src-electron/modules/shortcuts.ts]: removed commented code in [12baf63](https://github.com/trezor/trezor-suite/pull/4931/commits/12baf635bfab1e99ce895baf5c4b9f3d968e627d)

**Review by matejkriz — APPROVED** [review]
works for me (arm mac) 👌

**Comment by mroz22** [comment]
squashed, rebased and waiting for QA to aproved this before merging. 
So far I believe these have been tested and work:
- [x] linux  
- [x] mac
- [x] windows

**Comment by wendys-cats** [comment]
QA OK - tested on Win10 and macOS (intel).

Could not replicate the issue.
