### PR TITLE
fix(suite-native): Alert Sheet fix

### LINKED ISSUE #17838: AlertSheet component behaves incorrectly on low-end Android devices
**Describe the bug**
On slower or older Android devices, the `AlertSheet` component does not animate correctly. It either start at wrong position or it is triggered multiple times

**Info:**

-   Mobile Suite Version: 25.3.2/85538688bc
-   OS: Galaxy S8+, Android 9

**How to reproduce**

1. Use a low-end Android device (older or slower model).
2. Trigger the Alert Sheet Modal
3. Observe

**Expected behavior**
The AlertSheet should slide in from the bottom of the screen with no glitches

**Screenshots**
https://github.com/user-attachments/assets/2a75cbfe-57a9-4698-8fa4-aa9050c40431

### PR DESCRIPTION
**Pull request by BrantalikP**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17838

### CODE REVIEW

File: suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx [hunk 1]
```diff
@@ -45,6 +49,23 @@ export const HomeScreen = () => {
             refreshControl={refreshControl}
             noHorizontalPadding
         >
```
Comment (BrantalikP) [inline suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx]: Note: This file has been changed solely for testing purposes, once the fix is validated, it will be removed via `git ammend`

File: suite-native/alerts/src/components/AlertSheet.tsx [hunk 2]
```diff
@@ -46,6 +46,7 @@ const sheetOverlayStyle = prepareNativeStyle(_ => ({
     flex: 1,
 }));
 
+const ReanimatedPressable = Animated.createAnimatedComponent(Pressable);
```
Comment (yanascz) [inline suite-native/alerts/src/components/AlertSheet.tsx:49]: Could we please separate by a blank line from the following const?

Comment (yanascz) [inline suite-native/alerts/src/components/AlertSheet.tsx]: This is already used on four different places. Would it make sense to extract a component called `AnimatedPressable` into `atoms`?

Comment (BrantalikP) [reply suite-native/alerts/src/components/AlertSheet.tsx]: Thank you for the comment! 

IMO, it should not be in `Atoms`, although I understand the argument that we could benefit from making it reusable (following DRY). However, based on what I’ve observed and from an architectural point of view `Atoms` should solely serve as **components/primitives** coupled to our **Design System** (or at least related to the app’s UI in some way), either connected to some `business logig`(e.g `Skeleton`) or the `theme` itself (e.g Box).
`ReanimatedPressable` doesn’t follow either of these. It serves only as a consumer of the `animated style`. It’s similar to re-exporting `Animated.View` just to avoid copy-pasting. in this case, I think it’s completely fine to duplicate and adjust the component to meet the specific needs of the component. Happy to discuss this further if you’d like  :)

File: suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx]: removed by https://github.com/trezor/trezor-suite/pull/18302/commits/df36195c890072467ad77c1e8420984750b05d65

File: suite-native/alerts/src/components/AlertSheet.tsx (hunk 2 above)
Comment (yanascz) [reply suite-native/alerts/src/components/AlertSheet.tsx]: Well, we've already got `AnimatedHStack`, `AnimatedBox`, `AnimatedCard`, ... But it's true, they're tied to a corresponding design system component. So let's leave it here. 👍 

Could we at least stay consistent with the naming and call it `AnimatedPressable`?

File: suite-native/alerts/src/components/AlertSheet.tsx [hunk 3]
```diff
@@ -21,6 +22,9 @@ type AlertSheetProps = {
     alert: Alert;
 };
 
+const screenWidth = getScreenWidth();
+const screenHeight = getScreenHeight();
```
Comment (yanascz) [inline suite-native/alerts/src/components/AlertSheet.tsx]: I'd go with the same naming as in other files:
```suggestion
const SCREEN_WIDTH = getScreenWidth();
const SCREEN_HEIGHT = getScreenHeight();
```

**Review by yanascz — APPROVED** [review]
Works like a charm! 🪄
