### PR TITLE
Fix/reconnect to normal

### LINKED ISSUE #14260: `AbortButton` broken layout
This is the only remaining place `AbortButton` is used, maybe it can be replaced with a simpler icon?

**How to reproduce**

- Go to update firmware on TT with FW version < 2.6.0 (or T1 < 1.10.0).
- Observe broken button

**Screenshots**
Screenshot 2024-09-10 at 16 43 40

### PR DESCRIPTION
**Pull request by komret**
## Description

Use correct animation when rebooting to normal mode during intermediary firmware update. Previously, the animation depicted reboot to bootloader with the left button clicked.

QA: You'll need a devkit to test this and possibly old Bridge for Suite to be able to communicate with the device.

Note: `AbortButton` should be fixed [elsewhere](https://github.com/trezor/trezor-suite/issues/14260).

## Screenshots:
Screenshot 2024-09-11 at 15 11 11

### CODE REVIEW

**Comment by jvaclavik** [comment]
> ## Description
> Use correct animation when rebooting to normal mode during intermediary firmware update. Previously, the animation depicted reboot to bootloader with the left button clicked.
> 
> QA: You'll need a devkit to test this and possibly old Bridge for Suite to be able to communicate with the device.
> 
> Note: `AbortButton` should be fixed [elsewhere](https://github.com/trezor/trezor-suite/issues/14260).
> 
> ## Screenshots:
> Screenshot 2024-09-11 at 15 11 11

what about the close button on the screenshot? Is it state after or not?

**Comment by komret** [comment]
> what about the close button on the screenshot? Is it state after or not?

No no, it is broken, see https://github.com/trezor/trezor-suite/issues/14260.

File: packages/components/src/components/animations/DeviceAnimation.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ export const DeviceAnimation = forwardRef<HTMLVideoElement, DeviceAnimationProps
                     >
                         <source
                             src={resolveStaticPath(
-                                `videos/device/trezor_${DeviceModelInternal.T1B1.toLowerCase()}_${type.toLowerCase()}${theme}.webm`,
+                                `videos/device/trezor_${DeviceModelInternal.T1B1.toLowerCase()}_${type.toLowerCase()}${themeSuffix}.webm`,
```
Comment (Lemonexe) [inline packages/components/src/components/animations/DeviceAnimation.tsx:108]: Ack. This could be caught by eslint rule `no-base-to-string`, I'll try playing around with that.

**Review by Lemonexe — APPROVED** [review]
Did not QA, codewise LGTM.

I did see what the animations look like, so `NORMAL` is indeed without buttons pressed :upside_down_face:

**Comment by bosomt** [comment]
**QA NOK**


https://github.com/user-attachments/assets/aeae9b56-3106-4a18-8b7d-d19ef349732a



**Info:**
 - Suite version: web 24.10.0 (0cb09ab127e1213a55f4fce24243c674884c436a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.4.0 regular (revision ea3596ad8)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.0

**Comment by komret** [comment]
@bosomt There is another issue for that. It was not caused by these chages. https://github.com/trezor/trezor-suite/issues/14260

**Comment by bosomt** [comment]
**QA OK**

tested on devkit with 1.3.2 fw/BL

image


**Info:**
 - Suite version: desktop 24.10.0 (265028df5e34d075abd34f2ee338e6392d3613c1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.10.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 undefined (revision null)
 - Transport: BridgeTransport 2.0.33
