### PR TITLE
fix(suite): long device name PIN modal

### LINKED ISSUE #8606: PIN modal has broken layout with longer device names
**Describe the bug**
If you have longer device name, PIN entry modal is broken

**Info:**
-  Trezor 1 

**How to reproduce**

1. Give your Model 1 trezor longer name
1. Set PIN for the device
1. Connect the device
1. See error

**Expected behavior**
Longer device label should not break the layout. How to resolve? To be defined. I would expect ellipsis...

**Screenshots**
Device_name-PIN_distorted

### PR DESCRIPTION
**Pull request by AdamSchinzel**
Long device name caused that the UI of modal was a bit broken.

## Description

Moved the device name from modal's heading to modal's description. Also bolded the device name (as per a discussion in #8789)

Will be updating translations in Crowdin for `TR_ENTER_PIN_ON_DEVICE_LABEL` and `TR_THE_PIN_LAYOUT_IS_DISPLAYED`. Will use almost everything that I already translated and wrote to the translations files in the old PR (#8789) just this time will focus on putting the device name at the beginning or in the middle of the sentence ([suggestion](https://github.com/trezor/trezor-suite/pull/8789#issuecomment-1609504732) from @tomasklim). 

## Related Issue

Resolve #8606

### CODE REVIEW

**Comment by AdamSchinzel** [comment]
Translations in Crowdin are updated

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -3356,7 +3356,7 @@ export default defineMessages({
         id: 'TR_TESTNET_COINS_LABEL',
     },
     TR_THE_PIN_LAYOUT_IS_DISPLAYED: {
-        defaultMessage: 'Check your Trezor screen for the keypad layout.',
+        defaultMessage: 'Check your <b>{deviceLabel}</b> screen for the keypad layout.',
```
Comment (matejkriz) [inline packages/suite/src/support/messages.ts:3355]: it's not an HTML, I think `<b>`  would not work out of the box, you have to add something like:
`b: text => <b>{text}</b>` to values for TR_THE_PIN_LAYOUT_IS_DISPLAYED Translation component next to deviceLabel...

File: packages/suite/src/components/suite/modals/Pin.tsx [hunk 2]
```diff
@@ -41,13 +41,13 @@ export const Pin = ({ device, ...rest }: PinProps) => {
 
     return (
         <StyledModal
-            heading={
+            heading={<Translation id="TR_ENTER_PIN_ON_DEVICE_LABEL" />}
```
Comment (komret) [inline packages/suite/src/components/suite/modals/Pin.tsx]: This is equivalanet to `TR_ENTER_PIN`. You can use that message, just change its description.

File: packages/suite/src/support/messages.ts (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/support/messages.ts:3355]: Thanks, I was looking to other translations that use `<b>` but just how they're handled in the `messages.ts` file.

File: packages/suite/src/components/suite/modals/Pin.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/Pin.tsx]: Ok, also deleted `TR_ENTER_PIN_ON_DEVICE_LABEL` because it's no longer needed.

Also when I delete some translation key, how is that handled in Crowdin? Didn't find a button for proposing deletion

Comment (matejkriz) [reply packages/suite/src/components/suite/modals/Pin.tsx]: will be deleted by next sync 👌

**Review by komret — APPROVED** [review]

**Comment by matejkriz** [comment]
👍 nice, I will just suggest in crowdin removing the word "your" from the copy because it looks kinda weird with the default device name that is "My Trezor"

image
