### PR TITLE
fix(trading): clear preselectedQuote after loading into buy form

### LINKED ISSUE #24383: Changing payment method does not clear provider if unsupported
**Describe the bug**
When changing the payment method in the Buy & sell flow, the selected provider is not cleared even if the provider does not support the newly selected payment method. For example, when switching from PayPal to Revolut Pay (which MoonPay may not support), MoonPay remains selected as the provider.

**Info:**
 - Suite version: desktop 26.1.1 (72ba67df1a5d11a69ea2ee1cf4d04b1563d78eba)
 - Browser: Trezor Suite 26.1.1
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3W1 2.10.0 universal (revision de4b70e2e89a64f3894dba2124f6ec56e5cbd088)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**How to reproduce**

1. Go to Buy & sell section
2. Select a payment method (e.g., PayPal)
3. Note the provider that is selected (e.g., MoonPay)
4. Change payment method to one not supported by selected provider (e.g., Revolut Pay)
5. Observe that provider (MoonPay) remains selected

**Expected behavior**
After changing the payment method to one not supported by the current provider, the provider should be cleared or replaced with one that supports the new method.

**Screenshots**
image3
image2
image1

### PR DESCRIPTION
**Pull request by vytick**
When user selects trade via list of trades, it is saved into `preselectedQuote`, but this one is not cleared when user changes payment method. This PR changes the way how preselectedQuote is treated on going back to form. Provider and payment method (buy and sell) are set to the form and used to identify selected quote. For exchange, it is provider and isDex parameter. After this, `preselectedQuote` is cleared. These parameters (if present) are then used to identify selected trade in the form.

Note: This is just an attempt to fix issue with stalled preselected trade. The flow would use complete rework on how trades are selected. This will be part of an initiative (probably) later this year.

## Notes for QA

After this, user should be able to change quote after it is selected via list of trades by changing the payment method.

## Related Issue

Resolve #24383

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading/form-updating&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading/form-updating&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/trading/form-updating&lookback=7)

### CODE REVIEW

**Comment by vytick** [comment]
@coderabbitai review

File: packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts [hunk 1]
```diff
@@ -307,6 +310,38 @@ export const useTradingBuyForm = ({
...
+            return;
+        }
+
+        const preselectedProvider = preselectedQuote.exchange;
+        const preselectedPaymentMethod = preselectedQuote.paymentMethod;
+        const shouldUpdateProvider = !!preselectedProvider && preselectedProvider !== provider;
+        const shouldUpdatePaymentMethod =
+            !!preselectedPaymentMethod && paymentMethod?.value !== preselectedPaymentMethod;
+
+        dispatch(tradingBuyActions.savePreselectedQuote(undefined));
```
Comment (jbazant) [inline packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts:324]: **question:** This clears `preselectedQuote` even when no provider or method is updated. Is that intended?‏

File: packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts [hunk 2]
```diff
@@ -307,6 +310,38 @@ export const useTradingBuyForm = ({
         // eslint-disable-next-line react-hooks/exhaustive-deps
     }, [receiveAddress]);
 
+    useEffect(() => {
```
Comment (jbazant) [inline packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts:313]: **nitpick (non-blocking):** Seems like this effect is duplicated on multiple places. Can't we generalize it?‏

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 3]
```diff
@@ -54,19 +53,46 @@ import { useIsContentBelowBreakpoint } from '../../../../../support/suite/Conten
...
-        return bestScoredQuote;
+        const { provider, paymentMethod } = context.getValues();
+
+        const q = getQuotesFilteredByProviderAndPaymentMethod(
+            context.quotes,
+            provider,
+            paymentMethod?.value,
+        )?.[0];
+
+        return q;
```
Comment (jbazant) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: **nitpick (non-blocking):** I believe we can find better name for this. Or better return it right away without local const.‏

**Review by jbazant — APPROVED** [review]
LGTM

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx (hunk 3 above)
Comment (vytick) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: good find. this is leftover after logging. will change

File: packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts (hunk 1 above)
Comment (vytick) [reply packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts:324]: intended

File: packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts (hunk 2 above)
Comment (vytick) [reply packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.ts:313]: I would do this in followup or rewrite a lot of this functionality in general

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 4]
```diff
@@ -54,19 +53,46 @@ import { useIsContentBelowBreakpoint } from '../../../../../support/suite/Conten
...
+    const isDex = exchangeType === TRADING_EXCHANGE_FORM_DEX;
 
-    const selectedQuote = isDex ? context.dexQuotes?.[0] : context.cexQuotes?.[0];
+    const quotes = isDex ? context.dexQuotes : context.cexQuotes;
+    const selectedQuote =
+        quotes.filter(quote => quote.exchange === provider)?.[0] ?? context.cexQuotes?.[0];
 
-    return selectedQuote ?? bestScoredQuote;
+    return selectedQuote;
 };
```
[the remark this answers is not in the document]
Comment (vytick) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx:93]: applied

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 5]
```diff
@@ -54,19 +53,46 @@ import { useIsContentBelowBreakpoint } from '../../../../../support/suite/Conten
...
+
+const getQuotesFilteredByProviderAndPaymentMethod = (
+    quotes: BuyTrade[] | SellFiatTrade[],
+    provider: string | undefined,
+    paymentMethod: string | undefined,
+) =>
+    getQuotesFilteredByPaymentMethod(quotes, paymentMethod).filter(quote =>
+        provider ? (quote as BuyTrade | SellFiatTrade).exchange === provider : true,
+    );
+
```
[the remark this answers is not in the document]
Comment (vytick) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx:71]: applied

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx (hunk 3 above)
Comment (vytick) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: updated
