### PR TITLE
fix(suite-native): device selectors naming

### LINKED ISSUE #10311: Refactors selectors to reflect selected device
There is lot of selectors and some of them is using `selectAccounts` and some of them `selectDeviceAccounts`. Rename them to reflect that in name. For example:
```ts
export const selectAccountsByNetworkSymbol = memoizeWithArgs(
    (state: AccountsRootState & DeviceRootState, networkSymbol: NetworkSymbol | null) => {
        if (G.isNull(networkSymbol)) return [];

        const accounts = selectDeviceAccounts(state);

        return A.filter(accounts, account => account.symbol === networkSymbol);
    },
    {
        size: Object.keys(networks).length,
    },
);
```
Is using `selectDeviceAccounts` so it should be named `selectDeviceAccountsByNetworkSymbol`

etc.

### PR DESCRIPTION
**Pull request by PeKne**
- anything that is related to the `device.selectedDevice` state (accounts, discoveries, device features, etc.) starts with the `selectDevice...` prefix
- selectors that select some device or its features based on a parameter (e.g. `deviceState`) follow the structure `selectDevice...ByState`
- a few other selectors were renamed to reflect better their functionality

Closes #10311

### CODE REVIEW

**Review by Nodonisko — APPROVED** [review]
Really nice, bad naming of device selector bite me into ass more than once

File: suite-common/test-utils/src/extraDependenciesMock.ts [hunk 1]
```diff
@@ -78,7 +78,7 @@ export const extraDependenciesMock: ExtraDependencies = {
         selectDevice: mockSelector('selectDevice', {
             ...testMocks.getSuiteDevice(),
         }),
-        selectDiscoveryForDevice: mockSelector('selectDiscoveryForDevice', undefined),
+        selectDeviceDiscovery: mockSelector('selectDeviceDiscovery', undefined),
```
Comment (juriczech) [inline suite-common/test-utils/src/extraDependenciesMock.ts:81]: nit: No need for this mock since it's already included in extraDependencies

**Review by juriczech — APPROVED** [review]
