### PR TITLE
fix(suite): discovery buttons tooltip

### LINKED ISSUE #10791: Add a Tooltip for disabled Buttons during discovery
**Description**
* there already exists a tooltip notifying that an element is disabled dues to a device being disconnected
* we need to add a new one for when a device is connected but a discovery is in process
* there's also an opportunity to create a shared component for the buttons in Settings which would be handling both the tooltip and `isDisabled` state.
* additionally there is an opportunity to create one more abstraction for a button which is disabled due to a device bein disconnected. I believe we have a bunch of those and they are not anyhow connected.

**Additional context**
More info here: https://github.com/trezor/trezor-suite/pull/10524#discussion_r1465201709

### PR DESCRIPTION
**Pull request by jvaclavik**
needs copy

## Related Issue

Resolve #10791

## Screenshots:
image

### CODE REVIEW

File: packages/suite/src/components/suite/CoinList/CoinList.tsx [hunk 1]
```diff
@@ -26,6 +26,12 @@ interface CoinListProps {
     onToggle: (symbol: Network['symbol'], toggled: boolean) => void;
 }
 
+const getTooltip = (isDiscoveryRunning?: boolean) => {
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/CoinList/CoinList.tsx]:
```suggestion
const getTooltip = (isDiscoveryRunning?: boolean) => isDiscoveryRunning ?  'TR_LOADING_ACCOUNTS' : 'TR_DISABLED_SWITCH_TOOLTIP'
```

**Review by peter-sanderson — APPROVED** [review]
:ship: :it:
