### PR TITLE
`AddAccountModal` redesign

### LINKED ISSUE #6461: Add account: Improvements Pt.2
**Follow up for https://github.com/trezor/trezor-suite/issues/4067**

- [x] Animate coins container expansion i na way that doesn't move the content inside

- [ ] Disable coin bubble when empty account already created (as oppose to telling the user in 2 steps by disabling the primary button) › move that tooltip to the coin bubble

image

### LINKED ISSUE #9910: Updade the Create Account modal
**Design:** [Figma](https://www.figma.com/file/pewjlOfequOKYVC6h3v0YL/%5BEmpower-%231%5D-UI-Library-%26-Global-Navigation?type=design&node-id=3276-177999&mode=dev)

**Spec:** 
* refresh the look
* show all coins from the start (bye-bye ugly expand animation)
* keep the test coins hidden
* make sure all the other steps for coin activation _(including CJ)_ are not broken

### PR DESCRIPTION
**Pull request by komret**
## Description

The _Learn more_ button is too big IMO, should be smaller than the main button. Or should I keep it inline as before?

## Related Issue

Resolve #9910
Resolve #6461

## Screenshots:
`spacingsPx` before:
Screenshot 2023-11-23 at 15 57 20

`spacingsPx` now:
Screenshot 2023-11-23 at 15 57 35

First step:
Screenshot 2023-11-29 at 14 23 04

Second step:
Screenshot 2023-11-29 at 14 22 24

Minor fix in Coins settings: when an unsupported network is enabled and all supported ones are disabled, the settings icon should not be visible. This is how it looked like before fixing (mobile-only):

https://github.com/trezor/trezor-suite/assets/42465546/4912d294-6a4b-4d10-8faf-fc566c16084d

### CODE REVIEW

File: packages/theme/src/spacings.ts [hunk 1]
```diff
@@ -14,12 +14,11 @@ export const spacings = {
...
 export const spacingsPx = (Object.keys(spacings) as Array<SpacingSize>).reduce(
-    (result: Record<SpacingSize, string>, key) => {
-        result[key] = `${spacings[key]}px`;
-
+    (result, key) => {
+        (result as Record<SpacingSize, string>)[key] = `${spacings[key]}px`;
         return result;
     },
-    {} as Record<SpacingSize, string>,
+    {} as { [K in SpacingSize]: `${(typeof spacings)[K]}px` },
```
Comment (dahaca) [inline packages/theme/src/spacings.ts:21]: Awesome! 🧠

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx [hunk 2]
```diff
@@ -16,63 +18,61 @@ import { selectIsPublic } from 'src/reducers/wallet/coinjoinReducer';
 import { useEnabledNetworks } from 'src/hooks/settings/useEnabledNetworks';
 import { AccountTypeSelect } from './AccountTypeSelect/AccountTypeSelect';
 import { SelectNetwork } from './SelectNetwork';
-import { EnableNetwork } from './EnableNetwork/EnableNetwork';
 import { AddAccountButton } from './AddAccountButton/AddAccountButton';
 
 const StyledModal = styled(Modal)`
     width: 560px;
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx]: `max-width: 480px;`
 
 From Figma and it looks nice!

File: packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx [hunk 3]
```diff
@@ -17,7 +17,6 @@ const animationVariants = {
 };
 
 const Wrapper = styled.div<Pick<CollapsibleBoxProps, 'variant'>>`
-    margin-bottom: 20px;
```
Comment (dahaca) [inline packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx:20]: I guess I was afraid to ruin some styles but you chopped it and not even blinked – that's the way 😎  _(pretty sure nothing had been ruined)_

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx [hunk 4]
```diff
@@ -16,63 +18,61 @@ import { selectIsPublic } from 'src/reducers/wallet/coinjoinReducer';
...
     text-align: left;
 `;
 
-const Expander = styled.div`
+const NetworksWrapper = styled.div`
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx:28]: how about `margin-bottom: ${spacingsPx.md};`?

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx [hunk 5]
```diff
@@ -16,63 +18,61 @@ import { selectIsPublic } from 'src/reducers/wallet/coinjoinReducer';
...
+
 interface AddAccountProps {
     device: TrezorDevice;
     onCancel: () => void;
-    symbol?: Account['symbol'];
+    symbol?: NetworkSymbol;
     noRedirect?: boolean;
 }
 
 export const AddAccountModal = ({ device, onCancel, symbol, noRedirect }: AddAccountProps) => {
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx:50]: Maybe it's worth separating into 2 modals? 🤔

**Review by dahaca — COMMENTED** [review]
Never realized you can have `HighlightedText` in commit messages – cool! :D

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx (hunk 2 above)
Comment (komret) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx]: 1f39ed13ef6187bde694ffc57695bf68514b321d

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx (hunk 4 above)
Comment (komret) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx:28]: 1f39ed13ef6187bde694ffc57695bf68514b321d but added as `margin-top` to the `CollapsibleBox` because it is rendered conditionally.

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx (hunk 5 above)
Comment (komret) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx:50]: 3462a8c0708b73fdb070d6684b02371d662b904e How about this? Is it better than before? A little bit better IMO.

Comment (dahaca) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx:50]: It's for sure cleaner!! 

One last nitpick – I'd simply spread the config `{...getStepConfig()}` ;) Aproving anyways tho!

**Review by dahaca — APPROVED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx (hunk 5 above)
Comment (komret) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx:50]: 🧠 37dce14e1bfbb5dcd56884806c43f1ad21c2eba4
