### PR TITLE
fix(coinmarket): coinmarket amount wrapper

### LINKED ISSUE #14206: Coinmarket - Misplaced token icon in You get section during exchange
**Describe the bug**
`You get` section on latest develop has misplaced token icon

**Info:**
 - Suite version: web 24.10.0 (f27b837e5934625c5aae63c08d39ed4b1b2ea9fa)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: WebUsbTransport

**Screenshots:**
Screenshot 2024-09-09 at 11 51 41
Screenshot 2024-09-09 at 11 44 46

### LINKED ISSUE #14306: Coinmarket - Numbers are cropped in you buy/you pay
**Describe the bug**
Numbers are cropped in you buy /You pay section in default zoom

**Steps to reproduce:**
1. Navigate to Trade / Buy
2. Wait for default buy is loaded
3. Observe `You pay` digits

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**

image

image

### PR DESCRIPTION
**Pull request by adderpositive**
## Describe the bug
`You get` section on latest develop has a misplaced token icon. Also fixed cropped amount.

## Before
Screenshot 2024-09-09 at 11 51 41
Screenshot 2024-09-09 at 11 44 46

image

## After
image
obrazek

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/14206
Resolve https://github.com/trezor/trezor-suite/issues/14306

### CODE REVIEW

**Review by jvaclavik — APPROVED** [review]

**Comment by adderpositive** [comment]
@jvaclavik I have added also https://github.com/trezor/trezor-suite/issues/14306. This PR solved a similar problem.

**Review by Hermez-cz — APPROVED** [review]

File: packages/suite/src/views/wallet/coinmarket/index.tsx [hunk 1]
```diff
@@ -254,6 +254,7 @@ export const CoinmarketAmountWrapperText = styled.div`
     font-variant-numeric: tabular-nums;
     overflow: hidden;
     text-overflow: ellipsis;
+    line-height: 1;
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/index.tsx:257]: Couldn't we do it without explicitly setting line-height? 🙏

Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/index.tsx:257]: There is a problem with Icon centering and this solution helps. Strange bug  🤷‍♂️
