### PR TITLE
fix(suite-native): add ContinueOnTrezor screen autoconnect

### LINKED ISSUE #21620: Broken navigation when changing THP auto-connect from device settings
### Steps to reproduce
1. Connect via BT and confirm THP pairing.
2. Go to _Device settings_ and tap on _Turn on Auto-connect._
3. Once you confirm the action on device, you're redirected to _Home._

### Expected result
You shall stay in _Device settings_ after confirming the action on device.

### PR DESCRIPTION
**Pull request by juriczech**
## Description
- improve response from start auto connect thunk
- improve navigation of auto connect so it's more consistent with rest of device settings
- fix incorrect copy of autoconnect card

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21620

## Screenshots:
- tested turn off autoconnect, cancel in app, cancel on trezor, success on trezor

https://github.com/user-attachments/assets/d86d0085-4851-4b2b-94e9-ff700da73ef2

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/autoconnect-settings-ux&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/autoconnect-settings-ux&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/autoconnect-settings-ux&lookback=7)

### CODE REVIEW

File: suite-common/thp/src/startThpAutoconnectThunk.ts [hunk 1]
```diff
@@ -6,24 +6,29 @@ import TrezorConnect from '@trezor/connect';
...
+            return;
         } else {
             dispatch(
                 notificationsActions.addToast({ type: 'error', error: response.payload.error }),
             );
+            dispatch(finishThpAutoconnectThunk());
+
+            return rejectWithValue(response.payload.error);
         }
-        dispatch(finishThpAutoconnectThunk());
```
Comment (juriczech) [inline suite-common/thp/src/startThpAutoconnectThunk.ts]: Based on the usage, this shouldn't affect anything on desktop side as the response is not subscribed anywhere.

**Review by yanascz — APPROVED** [review]
LGTM. Haven't tested it, though.
