### PR TITLE
fix(suite): do not show staking banner in acc when staking is active

### LINKED ISSUE #21333: Hide staking banner when staking active in the account
If staking is already active on the account, don't show this banner on the account detail that promotes staking.

Image

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- promo to stake is not shown in case user already stakes
- promo to stake shows correct text based on user's balance

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21333

## Screenshots:
Already staked
Screenshot 2025-09-08 at 9 40 13
Not staked, enough balance
Screenshot 2025-09-08 at 9 40 18
Not staked, not enough balance
Screenshot 2025-09-08 at 9 40 23
No balance
Screenshot 2025-09-08 at 9 40 28

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/banner-staking&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/banner-staking&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/banner-staking&lookback=7)

### CODE REVIEW

**Review by matusbalascak — APPROVED** [review]

**Review by izmy — APPROVED** [review]

File: suite-common/wallet-utils/src/stakingUtils.ts [hunk 1]
```diff
@@ -56,16 +56,15 @@ export const getStakingLimitsByNetworkSymbol = (symbol: NetworkSymbol) => {
...
             return {
                 MIN_AMOUNT_FOR_STAKING: MIN_SOL_AMOUNT_FOR_STAKING,
                 MAX_AMOUNT_FOR_STAKING: MAX_SOL_AMOUNT_FOR_STAKING,
                 MIN_FOR_WITHDRAWALS: MIN_SOL_FOR_WITHDRAWALS,
                 MIN_BALANCE_FOR_STAKING: MIN_SOL_BALANCE_FOR_STAKING,
             };
-        }
         default:
-            throw new Error(`Unsupported network symbol: ${symbol}`);
+            return null;
```
Comment (izmy) [inline suite-common/wallet-utils/src/stakingUtils.ts:69]: I think `throw` has its place here, as it can make future bugs easier to catch - at least keep a `console.warn`.

```suggestion
            console.warn(`Unsupported or missing network symbol: ${symbol}`);

            return null;
```

**Review by izmy — APPROVED** [review]
