### PR TITLE
fix: reconnect from foreground proxy to keep service worker active when there is a connection

### LINKED ISSUE #10471: connect-webextension keepalive serviceworker
chrome might kill serviceworker after some time of inactivity https://satoshilabs.slack.com/archives/C056RKRV478/p1704213040532319?thread_ts=1702495559.394199&cid=C056RKRV478

### PR DESCRIPTION
**Pull request by karliatto**
## Description
Adding reconnection to keep service woker up when using foreground proxy in webextension.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10471

### CODE REVIEW

**Comment by martykan** [comment]
It's not working for me yet, looking into it...

**Comment by martykan** [comment]
This is more related to #12021, not really this PR per se. 

The problematic scenario is when I open the extension, wait 30s without doing anything and then try calling a method.
In that case `extendLifetime` doesn't get called so the service worker is alseep already. 

In the webextension proxy, `init` doesn't actually get called when receiving the init event, that only saves the settings and it's properly initialized before each method call. 
So for this I would propose calling `extendLifetime` [here when receiving the init event](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-webextension/src/index.ts#L231) as well.

**Comment by karliatto** [comment]
> This is more related to #12021, not really this PR per se.
> 
> The problematic scenario is when I open the extension, wait 30s without doing anything and then try calling a method. In that case `extendLifetime` doesn't get called so the service worker is alseep already.
> 
> In the webextension proxy, `init` doesn't actually get called when receiving the init event, that only saves the settings and it's properly initialized before each method call. So for this I would propose calling `extendLifetime` [here when receiving the init event](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-webextension/src/index.ts#L231) as well.

I see, ok, something like this: https://github.com/trezor/trezor-suite/pull/12071/commits/2f403e3d48228b60576ab26fd77128cd18eaf421 ?


For the fore-ground proxy I am trying to think about other solution, because in that situation we can do something to wake-up the service worker if it is sleep.


I am investigating if it would be possible/nice to solve it at the level of WindowServiceWorkerChannel for the proxy and others uses of that service.
If it possible to see that service worker is inactive maybe it is possible to wake it up and continue.

File: packages/connect-webextension/src/proxy/index.ts [hunk 1]
```diff
@@ -59,6 +59,16 @@ const init = (settings: Partial<ConnectSettings> = {}): Promise<void> => {
...
+    const reconnect = () => {
+        // By connecting again we keep the service worker active.
+        cancel();
+        _channel = null;
+        init(settings);
+    };
+
+    _channel.port.onDisconnect.removeListener(reconnect);
+    _channel.port.onDisconnect.addListener(reconnect);
+
```
Comment (karliatto) [inline packages/connect-webextension/src/proxy/index.ts:71]: I am still thinking in a different ways of using this way but for now this works for me.

Comment (karliatto) [reply packages/connect-webextension/src/proxy/index.ts:71]: @martykan Let me know if this works on your machine.

Comment (martykan) [reply packages/connect-webextension/src/proxy/index.ts:71]: Yes, this looks very good! 👍

Comment (karliatto) [reply packages/connect-webextension/src/proxy/index.ts:71]: @martykan what do you think should we proceed with this like it is?
I was thinking in other approaches but don't want to over complicate it.

Comment (martykan) [reply packages/connect-webextension/src/proxy/index.ts:71]: It seems to work and doesn't require any extra configuration so this is probably the best

Comment (karliatto) [reply packages/connect-webextension/src/proxy/index.ts:71]: :+1:  Let's approve and merge it then!

**Review by martykan — APPROVED** [review]
