### PR TITLE
fix(coinmarket): send and verify modals

### LINKED ISSUE #14218: Coinmarket - An incorrect account is selected in the Send modal form
## Describe the bug
Instead of the currently selected Trezor account, the account from the exchange form should be selected.

## Expected behavior
You should be able to interact with an ETH account, not a Polygon account in the send modal.

## How to reproduce
1. Choose Polygon account
2. Go to Trade-Exchange
3. Choose `From` ETH
4. Choose `To` USDT and some `Amount` to proceed with the trade
5. Continue to `Confirm on Trezor & send` in the trade

## Screenshot
image (1)
image (2)

## Correct behavior 
image

### LINKED ISSUE #14231: Coinmarket - An incorrectly selected account in the verify step
## Describe the bug
Incorrect account selected in the Verify step – this can be recognized by the presence of 'Including tokens' when buying BTC.

## Expected behavior
There should be selected correct account, should not be visible `Including tokens` subheading.

## How to reproduce
1. Choose an ETH account
2. Go to Trade-Buy
3. Choose `You buy` BTC
4. Select `Buy`
5. Click on `Confirm on Trezor` (verify)

## Buggy
image

## Expected behavior
image

### PR DESCRIPTION
**Pull request by adderpositive**
# 1. An incorrectly selected account in the verify step
## Describe the bug
Instead of the currently selected Trezor account, the account from the exchange form should be selected.

## Expected behavior
You should be able to interact with an ETH account, not a Polygon account in the send modal.

## How to reproduce
1. Choose Polygon account
2. Go to Trade-Exchange
3. Choose `From` ETH
4. Choose `To` USDT and some `Amount` to proceed with the trade
5. Continue to `Confirm on Trezor & send` in the trade

## Screenshot
image (1)
image (2)

## Correct behavior
image

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/14218

# 2. An incorrect account is selected in the Send modal form
## Describe the bug
Incorrect account selected in the Verify step – this can be recognized by the presence of 'Including tokens' when buying BTC.

## Expected behavior
There should be selected the correct account and should not be visible `Including tokens` subheading.

## How to reproduce
1. Choose an ETH account
2. Go to Trade-Buy
3. Choose `You buy` BTC
4. Select `Buy`
5. Click on `Confirm on Trezor` (verify)

## Buggy
image

## Expected behavior
image

## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/14231

# Other info
Please also check if the Send form is not affected.

### CODE REVIEW

**Comment by jvaclavik** [comment]
Screenshot 2024-09-10 at 09 01 53

Could you please delete this border? 🙏  (it shouldn't be white)

**Review by jvaclavik — CHANGES_REQUESTED** [review]
Don't understand the logic in detail, but I didn't spot any issues except the border color. Since you fix it I'm approving

**Review by jvaclavik — APPROVED** [review]

**Review by LukasRada — APPROVED** [review]

File: packages/suite/src/reducers/wallet/selectedAccountReducer.ts [hunk 1]
```diff
@@ -50,4 +57,19 @@ export const selectSelectedAccountHasSufficientEthForStaking = (
 export const selectIsSelectedAccountLoaded = (state: SelectedAccountRootState) =>
     state.wallet.selectedAccount.status === 'loaded';
 
+/**
+ * Mainly used for common modals, also used in the Coinmarket section.
+ * @returns account from coinmarket if it's set, otherwise account from the store
+ */
+export const selectAccountIncludedChosenInCoinmarket = (
```
Comment (komret) [inline packages/suite/src/reducers/wallet/selectedAccountReducer.ts]:
```suggestion
export const selectAccountIncludingChosenInCoinmarket = (
```

File: packages/suite/src/reducers/wallet/selectedAccountReducer.ts [hunk 2]
```diff
@@ -50,4 +57,19 @@ export const selectSelectedAccountHasSufficientEthForStaking = (
...
+    state: SelectedAccountRootStateWithCoinmarket,
+) => {
+    const { coinmarket, selectedAccount } = state.wallet;
+    const storeAccount = selectedAccount.status === 'loaded' ? selectedAccount.account : undefined;
```
Comment (komret) [inline packages/suite/src/reducers/wallet/selectedAccountReducer.ts]: This is some additional logic that is not present in the originally used `selectSelectedAccount`, why did you add it?

Perhaps this selector could be simplified and return earlier:

```
    const { modalAccount } = state.wallet.coinmarket;

    if (modalAccount) {
        return modalAccount;
    }

    const selectedAccount = selectSelectedAccount(state);

    return selectedAccount;
```

File: packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketAccount.ts [hunk 3]
```diff
@@ -48,5 +51,15 @@ export const useCoinmarketAccount = ({
         return selectedAccount.account;
     });
 
+    // clean coinmarketAccounts if is form page
+    useEffect(() => {
```
Comment (komret) [inline packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketAccount.ts]: Why is this necessary? Maybe it could be done with middleware?

File: packages/suite/src/hooks/wallet/coinmarket/offers/useCoinmarketCommonOffers.ts [hunk 4]
```diff
@@ -69,6 +71,12 @@ export const useCoinmarketCommonOffers = ({
 
     useServerEnvironment();
 
+    useEffect(() => {
```
Comment (komret) [inline packages/suite/src/hooks/wallet/coinmarket/offers/useCoinmarketCommonOffers.ts]: This would perhaps be safer to do in middleware when the modal closes?

**Review by komret — CHANGES_REQUESTED** [review]
I'd prefer to do this without the useEffects, if possible. They are not linked to the modals closely enough and I am afraid that it could lead to future bugs where we expect the reducer value to be cleared while it is not. Perhaps the same result could be achived with props or middlewares.

**Comment by komret** [comment]
Great improvements and added unit tests 👏 

But note that some unit tests are failing.

**Comment by adderpositive** [comment]
I have found one more bug. It should be ETH account, not BTC in exchange. 
obrazek

**Comment by adderpositive** [comment]
> I have found one more bug. It should be ETH account, not BTC in exchange. obrazek

should be fixed

**Review by komret — APPROVED** [review]

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0
