### PR TITLE
fix: Post-freeze bugs

### LINKED ISSUE #5328: Hex format switch triggers Verify button in Verify dialogue
**Describe the bug**
Hex format switch triggers Sign button in Verify dialogue and does not switch message format.
I was not able to reproduce it on production.
I was able to reproduce it in web and in app version of Staging Suite version
See first video with issue , second video with production version of Suite behaves as expected.

**Steps to reproduce:**
1. Navigate to verify dialogue in Sign/Verfi function
2. Fill out fields.
3. Try to switch to `Hex format`
4. Observe Suite behavior.

**Info:**
 - Suite version: web 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Screenshots:**

22.5.1

https://user-images.githubusercontent.com/31506317/166711049-faf59c2e-7126-472a-88ff-4fe7e7420170.mov

22.4.3

https://user-images.githubusercontent.com/31506317/166711073-7c3a940a-e135-41a8-be40-7a25157d0dd0.mov

### LINKED ISSUE #5330: Green outlining of send form boxes is missing
**Describe the bug**
Green outline of the boxes in send form and also in sign and verify and OP_RETURN, that signalize the user filled out the boxes correctly, are not present in the new staging version of Suite. Wrong input is correctly shown as red.
I am not really sure if this is because of https://github.com/trezor/trezor-suite/issues/4632 but my guess it's very probable.

**Steps to reproduce:**
1. Go to Accounts and select an account (doesn't matter which coin, for example BTC)
2. Click on "Send"
3. Fill out any relevant BTC address
4. The text box for address doesn't turn green.

**Info:**
 - Suite version: desktop 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Expected result:**
Text boxes turn green when correctly filled out.

**Actual result:**
Text boxes doesn't turn green when correctly filled out.

**Screenshots:**
image

**Note(s):**

### LINKED ISSUE #5339: Back button in T1 recovery is blurred
**Describe the bug**
Button for "Back" in one step of T1 recovery is blurred out.

**Steps to reproduce:**
1. Connect device with no seed
2. Select "Recovery" option
3. Select number of words
4. Select "Standard" recovery
5. Now you are prompted to continue on the device and the "Back" button in Suite is blurred out

**Info:**
 - Suite version: desktop 22.5.1 (06b93c51d07e8dfbd153c3e1569911884caf97a2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.5.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.5 regular (revision 3f12742669bd782cac374a1750d517f4fd88c43b)
 - Transport: bridge 2.0.31

**Expected result:**
"Back" button is normally visible

**Actual result:**
"Back" button is blurred out.

**Screenshots:**
image

**Note(s):**

### PR DESCRIPTION
**Pull request by dahaca**
closes #5328
closes #5339
closes #5330

### CODE REVIEW

File: packages/suite/src/components/onboarding/OnboardingStepBox/index.tsx [hunk 1]
```diff
@@ -29,17 +31,18 @@ const StyledBackdrop = styled(Backdrop)<{ show: boolean }>`
     z-index: 0;
```
Comment (tomasklim) [inline packages/suite/src/components/onboarding/OnboardingStepBox/index.tsx]: z-index twice

**Review by tomasklim — CHANGES_REQUESTED** [review]
Next time, I would omit refactoring changes in "post-freeze" bug fix PRs

File: packages/suite/src/components/onboarding/OnboardingStepBox/index.tsx (hunk 1 above)
Comment (dahaca) [reply packages/suite/src/components/onboarding/OnboardingStepBox/index.tsx]: Done. Ok, noted!

**Review by tomasklim — APPROVED** [review]
