### PR TITLE
fix(suite): add missing accounts to the trading buy, sell and exchange box

### LINKED ISSUE #15900: Trading - Missing network and account info in the last step of trade
**Describe the bug**
Missing network and account info when swapping POL
Other networks works as expected, see screenshots.

**Steps to reproduce:**
1. Navigate to Swap section
2. Try to swap POL tokens
3. Observe info when confirming trade (last step)

**Info:**
 - Suite version: desktop 24.12.1 (ec8321d0d17529ca77d8916e70158cecc469f863)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.12.1 Chrome/128.0.6613.186 Electron/32.2.6 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image
image
image

Image

### PR DESCRIPTION
**Pull request by izmy**
## Description

Adds missing account information to the trading box for buy, sell, and exchange flows.

**UI update:**
Display sendAccount and receiveAccount in the transaction detail for:

- **Buy** - shows `receiveAccount`
- **Sell** - shows `sendAccount`
- **Exchange** - shows both `sendAccount` and `receiveAccount`

**Migration:**
Updates existing transactions in IndexedDB to include:

- `sendAccount` for **sell** and **exchange**
- `receiveAccount` for **buy** and **exchange**

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/15900

## Screenshots:

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-exchange-missing-accounts&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-exchange-missing-accounts&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/trading-exchange-missing-accounts&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx [hunk 1]
```diff
@@ -16,11 +21,36 @@ import { TradingDetailExchangePaymentSuccessful } from 'src/views/wallet/trading
...
+    accounts: Account[],
+    address: string | undefined,
+    cryptoId: CryptoId | undefined,
+): Account | undefined => {
+    if (address == null || cryptoId == null) {
+        return undefined;
+    }
+
+    return accounts.find(account => {
+        const contractAddresses = [
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx]: `contractAddresses` is incorrect name, use `cryptoIds`.
`contractAddress` is only one part of `cryptoId`

File: packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx [hunk 2]
```diff
@@ -16,11 +21,36 @@ import { TradingDetailExchangePaymentSuccessful } from 'src/views/wallet/trading
...
+            ...(account.tokens?.flatMap(token =>
+                toTokenCryptoId(
+                    account.symbol,
+                    getContractAddressForNetworkSymbol(account.symbol, token.contract),
+                ),
+            ) ?? []),
+            getNetwork(account.symbol).tradeCryptoId,
+        ].filter(Boolean) as CryptoId[];
+
+        return account.descriptor === address && contractAddresses.includes(cryptoId);
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx]: `account.descriptor === address` may not be correct. If you use Bitcoin for trading on one account, the descriptor stays the same, but the addresses will change with each trade if I’m not mistaken. 

What about using `account.addresses` and searching for a specific address? Will it work for other currencies?

**Review by adderpositive — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx (hunk 2 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx]: If we could find an address in `addresses` (still not sure it is possible), then at the end we could just search for the address.

File: packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx [hunk 3]
```diff
@@ -16,11 +21,36 @@ import { TradingDetailExchangePaymentSuccessful } from 'src/views/wallet/trading
 import { TradingSelectedOfferInfo } from 'src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo';
 import { TradingWrapper } from 'src/views/wallet/trading/common/TradingWrapper';
 
+const findAccountForTrade = (
+    accounts: Account[],
+    address: string | undefined,
+    cryptoId: CryptoId | undefined,
+): Account | undefined => {
+    if (address == null || cryptoId == null) {
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx]: Nit: 

```suggestion
    if (!address || !cryptoId) {
```

File: packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx (hunk 2 above)
Comment (izmy) [reply packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx]: I completely changed the logic and added addresses checking

File: packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx [hunk 4]
```diff
@@ -63,6 +65,9 @@ export const TradingDetailExchange = () => {
         receiveCurrency: trade?.data?.receive,
     };
 
+    const sendAccount = accounts.find(a => a.key === trade.sendAccountKey);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx]:
```suggestion
    const sendAccount = accounts.find(account => a.key === trade.sendAccountKey);
```

**Review by tomasklim — APPROVED** [review]
LGTM

**Comment by tomasklim** [comment]
Please resolve conflicts and would be nice to solve this also for buy and sell in another issue/pr

**Comment by adderpositive** [comment]
> Please resolve conflicts and would be nice to solve this also for buy and sell in another issue/pr

If it will to be solved in the next PR, it is ok by me. We also discussed with @izmy we could delete `account` from trades, FYI @tomasklim

**Review by adderpositive — APPROVED** [review]

File: packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx (hunk 4 above)
Comment (izmy) [reply packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx]: done

**Comment by izmy** [comment]
> Please resolve conflicts and would be nice to solve this also for buy and sell in another issue/pr

I also did it for buy and sell.


> If it will to be solved in the next PR, it is ok by me. We also discussed with @izmy we could delete `account` from trades, FYI @tomasklim

I created a follow-up issue https://github.com/trezor/trezor-suite/issues/18527

**Review by tomasklim — CHANGES_REQUESTED** [review]
I can't test it but LGTM. There is failing CI

**Review by tomasklim — APPROVED** [review]
Sorry, I wanted to approve it

**Review by adderpositive — APPROVED** [review]

File: packages/suite/src/storage/migrations/index.ts [hunk 5]
```diff
@@ -1276,4 +1280,88 @@ export const migrate: OnUpgradeFunc<SuiteDBSchema> = async (
     if (oldVersion < 54) {
         db.createObjectStore('connect');
     }
+
+    if (oldVersion < 55) {
+        const findAccountForTrade = (
```
Comment (adderpositive) [inline packages/suite/src/storage/migrations/index.ts]: nit: I would create migration in separate file. It is also mentioned in the TODO in the file above.

Comment (izmy) [reply packages/suite/src/storage/migrations/index.ts]: done
