### PR TITLE
fix(suite-native): fee rate formatter

### LINKED ISSUE #10070: Transaction fee rates does not match desktop and blockbook fee rates
**Describe the bug**
Transaction fee rates does not match desktop and blockbook fee rates.
I was able to reproduce it on production 23.11.2 and develop 23.11.1 versions.

**Info:**

-   Mobile Suite Version: 23.11.2 production and 23.11.1 develop 
-   OS: iOS and Android 

**Screenshots**
image
telegram-cloud-photo-size-4-5992421466567720734-y
image
image

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- if the fee rate is already present in the TX object, use it.

## Related Issue

Resolve #10070

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/b6ddccf5-a8e3-4288-9bbf-b605f328f660

### CODE REVIEW

**Review by juriczech — APPROVED** [review]

File: suite-native/formatters/src/components/FeeFormatter.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const FeeFormatter = ({ transaction }: FeeFormatterProps) => {
         () =>
             networkType === 'ethereum'
                 ? fromWei(transaction.ethereumSpecific?.gasPrice ?? '0', 'gwei')
-                : getFeeRate(transaction),
+                : transaction.feeRate || getFeeRate(transaction),
```
Comment (matejkriz) [inline suite-native/formatters/src/components/FeeFormatter.tsx:21]: I believe you can completely remove the legacy way using getFeeRate, check this comment https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/BasicTxDetails.tsx/#L276

Comment (PeKne) [reply suite-native/formatters/src/components/FeeFormatter.tsx:21]: oh, nice. I will prepare fixup then. 👍
