### PR TITLE
fix(mobile): do not show xpub when firmware is compromised

### LINKED ISSUE #19550: Disable xpub generation when device is compromised
Do the same as  #14941 in Suite Lite

### PR DESCRIPTION
**Pull request by OriginalEveres**
Disables option to generate xpub on mobile when firmware is compromised.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19550

## Screenshots:
BEFORE
Screenshot 2025-07-02 at 0 40 27
AFTER
Screenshot 2025-07-07 at 7 02 16

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/disable-xpub-generation-when-device-is-compromised-mobile&lookback=7)

### CODE REVIEW

**Review by PeKne — APPROVED** [review]
The code looks good, approved. But I'm wondering... should not we display some informative message to the user why is the button disabled 🤔? Maybe some simple alert or toast?

File: suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx [hunk 1]
```diff
@@ -13,6 +14,8 @@ export const AccountSettingsShowXpubButton = ({ accountKey }: { accountKey: stri
         selectAccountByKey(state, accountKey),
     );
 
+    const isAuthenticityCheckFailed = useSelector(selectHasFirmwareAuthenticityCheckHardFailed);
```
Comment (matejkriz) [inline suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: nitpick: I know it's a long name, but descriptive. And I like the convention of naming the result of selector by the selector itself. It's like that in all the other places where selectHasFirmwareAuthenticityCheckHardFailed is used.
```suggestion
    const hasFirmwareAuthenticityCheckHardFailed = useSelector(selectHasFirmwareAuthenticityCheckHardFailed);
```

**Comment by OriginalEveres** [comment]
> The code looks good, approved. But I§m wondering. should not we display some informative message to the user why is the button disabled 🤔? Maybe some simple alert or toast?

Sure, we have a tooltip on desktop and we definitely want to have some message on mobile, I want to raise this on our sync today to discuss the form and message content

**Comment by OriginalEveres** [comment]
@PeKne & @matejkriz I've discussed the flow and updated it to show alert with the device compromised copy.

File: suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx (hunk 1 above)
Comment (OriginalEveres) [reply suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx]: good nitpick! I've updated it.

**Review by PeKne — APPROVED** [review]
