### PR TITLE
Various improvements regarding RBF

### LINKED ISSUE #6944: Not able to bump or finalize transaction sent between CJ accounts
**Describe the bug**
Not able to bump or finalize transaction sent between CJ accounts

**Steps to reproduce:**
1. Create/load two wallets and add CJ accounts
2. Send transaction between accounts
3. Try to bump or finalize transaction. 

**Info:**
 - Suite version: desktop 22.12.0 (8564941f51e20658d0286dc26e14858d8ee0d300)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Screenshots:**
[trezor-suite-log-1668771090576.txt.zip](https://github.com/trezor/trezor-suite/files/10040987/trezor-suite-log-1668771090576.txt.zip)

image
image

### LINKED ISSUE #7101: TypeError: Cannot read properties of undefined (reading 'type')
Sentry Issue: [TREZOR-SUITE-Q80](https://sentry.io/organizations/satoshilabs/issues/3774265776/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'type')
  at h (webpack://@trezor/suite-build/../suite/src/hooks/wallet/useRbfForm.ts:203:16)
  at fk (webpack://@trezor/suite-build/../../node_modules/react-dom/cjs/react-dom.production.min.js:262:359)
  at exports.unstable_runWithPriority (webpack://@trezor/suite-build/../../node_modules/scheduler/cjs/scheduler.production.min.js:18:343)
  at gg (webpack://@trezor/suite-build/../../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at Oj (webpack://@trezor/suite-build/../../node_modules/react-dom/cjs/react-dom.production.min.js:261:308)
...
(9 additional frame(s) were not displayed)
```

### LINKED ISSUE #7184: Reuse UTXO exclusion algorithms from send form in RBF
If you bump fee so high that you need to add more UTXO, algorithm for UTXO exclusion has to be applied to not break your anonymity.

### LINKED ISSUE #7339: Can't bump fee when sending BTC from Taproot account
**Describe the bug**
I can't bump fee of a transaction sent from Taproot BTC account in Suite. Trezor freezes when creating the tx and Suite shows error. Both can be seen in screenshots section. Trezor device is fine after reconnecting. This issue is in Suite from 22.7.3 version (as shown in the info part of this issue).

**Steps to reproduce:**
1. Go to your Taproot account
2. Sent few sats to yourself from the Taproot account
3. Try to bump the fee of this transaction
4. An error will appear and Trezor will freeze

**Info:**
 - Suite version: desktop 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 regular (revision ff35c77bad82c7acac1df6245940ebe0d6454642)
 - Transport: bridge 2.0.32

**Expected result:**
I can bump a fee of a Taproot transaction.

**Actual result:**
I can't bump a fee of a Taproot transaction and the Trezor freezes and has to be reconnected. 

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

Multiple fixes, improvements and refactors of replace-by-fee functionality.

https://github.com/trezor/trezor-suite/pull/7378/commits/8c507cb296c5e866f59a3cfa95b29d61d306ef19 - `skipUtxoSelection` param in utxo-lib coin selection wasn't used anywhere, so it's been removed (including unit tests)

https://github.com/trezor/trezor-suite/pull/7378/commits/e84c56f884aaf6b630fa33f0ec989a4c653901ed - When trying to bump transaction on coinjoin account, it's needed to filter the potentially added utxos by their privacy levels in the same way as in send form. Therefore, `excludedUtxos` are set in `useRbfForm` (in the same way as in `useSendForm` hook) and the filtering in `sendFormBitcoinActions` was enhanced so it always preserve required utxos (because when we change the required privacy level between original and bumped tx, we still want to use all the previously used utxos)

https://github.com/trezor/trezor-suite/pull/7378/commits/78412024b1aa628cc61c56ffc29597b6bc1ff22a - RBF on taproot accounts didn't work, because the `origTxs` needed by device hadn't been fetched (they were ignored together with `refTxs` which are NOT needed for taproot txs). Now the `refTxs` and `origTxs` are fetched separately when needed (and refactored a bit)

https://github.com/trezor/trezor-suite/pull/7378/commits/1270e9972c0b2b92d317e272d81bf49c6e7539dd - The validity check for `refTxs` param (when explicitly sent to TrezorConnect.signTransaction, which wasn't used in Suite anyway) was adjusted to the previous commit (= it's now valid to send only the orig txs and not ref txs for taproot accounts)

https://github.com/trezor/trezor-suite/pull/7378/commits/98ed9ff06644c8f7e8b84c477c0c095d12fe8f75 - Added Connect test for bumping taproot transaction so it won't happen again

https://github.com/trezor/trezor-suite/pull/7378/commits/6c033d102ad5afff9ffb5cdf9f67ccfd766b044c - Most of RBF features in Suite totally ignored missing `rbf` flag in network features:
- `selectedAccount.network` was in general the first network for the corresponding coin irrespective of the real `accountType` (therefore it was usually `normal`). Fixed.
- `TransactionItem` and `TransactionDetail` components were showing RBF features regardless of the `rbf` flag. Fixed.
- This also disabled the RBF for coinjoin accounts which we agreed on because of the potential privacy leak. (see followup issue #7380)

https://github.com/trezor/trezor-suite/pull/7378/commits/9a07d0c8d14990b2d181ebf688f784710228e724 - <strike>`Fees` select bar is now disabled until the `composedLevels` are present which should resolve a crash - when `custom` level was manually selected before the composed transactions, no tx was added for this level.</strike> This solution disallowed to change the fee level before filling all the other parameters in the send form, so I've just added null conditional operator instead.

## Related Issue

https://github.com/trezor/trezor-suite/pull/7378/commits/e84c56f884aaf6b630fa33f0ec989a4c653901ed resolve #7184
https://github.com/trezor/trezor-suite/pull/7378/commits/78412024b1aa628cc61c56ffc29597b6bc1ff22a resolve #7339
https://github.com/trezor/trezor-suite/pull/7378/commits/9a07d0c8d14990b2d181ebf688f784710228e724 may resolve #7101 (at least one case)

## What to test

Mostly that replace-by-fee works for taproot accounts (as well as for the legacy and segwit accounts and other coins where it was working before) and that it's disabled in coinjoin account.

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 1]
```diff
@@ -118,10 +119,20 @@ const useRbfState = ({ tx, finalize, chainedTxs }: Props, currentState: boolean)
         baseFee,
     };
 
+    // find coinjoin account related to current account
+    const coinjoinAccount = coinjoinAccounts.find(a => a.key === selectedAccount.account.key);
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useRbfForm.ts:121]:
```suggestion
    const coinjoinAccount = useSelector(state => selectCoinjoinAccountByKey(state, accountKey));
```

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 2]
```diff
@@ -57,19 +57,20 @@ const getFeeInfo = (
 };
 
 const useRbfState = ({ tx, finalize, chainedTxs }: Props, currentState: boolean) => {
-    const state = useSelector(state => ({
+    const { selectedAccount, fees, coinjoinAccounts } = useSelector(state => ({
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useRbfForm.ts]: This could as well be refactored into separate selectors as suggested in [style guide](https://www.notion.so/satoshilabs/Redux-b0a4c3b7e71b499a8d592fb44cd794fe#4f4936ae00f84140bc433300ae2b7d88).

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 3]
```diff
@@ -352,6 +352,12 @@ export const getAllAccounts = (deviceState: string | typeof undefined, accounts:
 export const getNetwork = (symbol: string): Network | null =>
     NETWORKS.find(c => c.symbol === symbol) || null;
 
+export const getAccountNetwork = ({
```
Comment (komret) [inline suite-common/wallet-utils/src/accountUtils.ts:355]: Nice to have: incorporate this into `getNetwork` and refactor code which does the same without using the util.

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 4]
```diff
@@ -199,7 +210,7 @@ export const useRbf = (props: Props) => {
         if (ctxState.account?.networkType !== 'bitcoin' || !composedLevels) return;
         const { selectedFee, setMaxOutputId, outputs } = getValues();
         const tx = composedLevels[selectedFee || 'normal'];
-        if (tx.type === 'error' && tx.error === 'NOT-ENOUGH-FUNDS') {
+        if (tx?.type === 'error' && tx.error === 'NOT-ENOUGH-FUNDS') {
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useRbfForm.ts:212]: Some comment explaining the need for optional chaining might be handy in the future.

**Review by komret — APPROVED** [review]
RBF is disabled on CoinJoin account, I did not test it on other accounts. Code looks good, I only have some nice-to-have suggestions. Good job!

**Review by mroz22 — APPROVED** [review]
nice

File: packages/suite/src/hooks/wallet/useRbfForm.ts (hunk 1 above)
Comment (marekrjpolak) [reply packages/suite/src/hooks/wallet/useRbfForm.ts:121]: I get your point, but
a) it's not possible to use a hook here as there is a `return` on line 69 and
b) it's not possible to use it before this `return` as there we even don't have an `accountKey` to use (as the `selectedAccount.status` may not be `loaded`).

But I can try to refactor it even more to do it like this, if you want.

File: packages/suite/src/hooks/wallet/useRbfForm.ts (hunk 2 above)
Comment (marekrjpolak) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: https://github.com/trezor/trezor-suite/pull/7378/commits/c992b9692d5f15063fa3d00d7cb7cc1a7b11d812

File: packages/suite/src/hooks/wallet/useRbfForm.ts (hunk 4 above)
Comment (marekrjpolak) [reply packages/suite/src/hooks/wallet/useRbfForm.ts:212]: https://github.com/trezor/trezor-suite/pull/7378/commits/1a974cb4ef4acb227405854e57337244c6719afe

File: suite-common/wallet-utils/src/accountUtils.ts (hunk 3 above)
Comment (marekrjpolak) [reply suite-common/wallet-utils/src/accountUtils.ts:355]: I've done something like this as a separate draft PR #7418 (only the last commit), because I didn't want to pollute this PR.
