### PR TITLE
fix(suite): enable labeling for fresh receive address

### LINKED ISSUE #26172: Allow labeling a new address directly in the Receive section
## Summary
For labeling the receive address user is forced to display it first. And label is not visible in Receive until it is used.

## Expected Behavior
Apply the same user interaction of labeling on new receive address as with other labeling fields

Image

### PR DESCRIPTION
**Pull request by hynek-jina**
- enable inline labeling for the fresh receive address in Receive
- keep the fresh address formatting consistent with the used-address list, including chunking by 4 characters

https://github.com/user-attachments/assets/24cd895b-394d-491c-bcca-404fe2e80284

Resolve https://github.com/trezor/trezor-suite/issues/26172

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/label-new-receive-address&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/label-new-receive-address&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Analytics Events > Analytics captures important events when started enabled by default | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Firmware - check readiness > Suite detects that firmware is ready | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-25T19:00:07.928Z • 7 test(s) total_

<details><summary>Trezor Suite (desktop) — 4 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |
| Firmware not ready | 🙋 manual |

</details>

_Updated: 2026-03-25T18:58:46.668Z • 4 test(s) total_

### CODE REVIEW

**Comment by hynek-jina** [comment]
Screenshot 2026-03-25 at 16 50 56
Screenshot 2026-03-25 at 16 50 50

Chunked address is not correctly displayed...

**Review by OriginalEveres — APPROVED** [review]
LGTM! tested and it works. Good job!

File: packages/suite/src/views/wallet/receive/components/FreshAddress.tsx [hunk 1]
```diff
@@ -132,6 +139,10 @@ export const FreshAddress = ({
         minWidth: 220,
         size: 'large',
     };
+    const firstFreshAddressLabel = firstFreshAddress?.address
+        ? (suiteSyncAddressLabels.find(it => it.address === firstFreshAddress.address)?.label ??
```
Comment (peter-sanderson) [inline packages/suite/src/views/wallet/receive/components/FreshAddress.tsx:143]: This pisses me off. I know its my own tech dept, but I with we have some Address component that already solves the labeling inside. So we do not need to repeat this over and over again. 

The culprit will be that different places may have slightly different designs so the component needs to be a bit versatile. 

But I bet its one prompt away.... :)

**Review by peter-sanderson — APPROVED** [review]

**Comment by tomasklim** [comment]
Have you considered to somehow indicate that labeling is used? I can put label `bc1q twtd ... 48pv` and it will look exactly the same 😀 
Screenshot 2026-03-26 at 9 12 20

**Comment by hynek-jina** [comment]
> Have you considered to somehow indicate that labeling is used? I can put label `bc1q twtd ... 48pv` and it will look exactly the same 😀 

It's out of scope 😀
_Meaning.. why would anyone do that? And is it anyhow dangerous?_

**Comment by hynek-jina** [comment]
@tomasklim Btw. adding new label  Doesn't show `delete` button..
Screenshot 2026-03-26 at 9 52 31


Screenshot 2026-03-26 at 9 52 20

So technically you can distiguish that :-)
