### PR TITLE
fix: Sentry in Desktop renderer

### LINKED ISSUE #23149: Sentry not working in Desktop renderer
**Describe the bug**

Sentry error is not sent from Desktop renderer.

Works in Web, and in Desktop main.
Affects production 25.11.1 prerelease and develop.
Works on current production `Trezor-Suite-25.10.2-linux-x86_64.AppImage`

**Info:**

- Suite Version: `Trezor-Suite-25.11.1-linux-x86_64.AppImage`
- OS: Linux Ubuntu 22.04

**How to reproduce**

1. Go to Debug settings
2. Click on Throw testing error
1. ~See~ "TESTING ERROR" in sentry 

**Expected behavior**
See "TESTING ERROR" in sentry

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Fix Sentry in Desktop rendered, which was broken by me in a fixup in https://github.com/trezor/trezor-suite/pull/22817

- align versions of `@sentry/core`, which are mismatched between electron & react-native SDKs
  - see comment [here](https://github.com/trezor/trezor-suite/pull/22817#discussion_r2486345723) in the bump PR but I did not act on it then. Now I thought it might be the problem. Turns out it did not fix it, but let's do it anyway since I have it ready.
- **the fix**: default integrations dropped by accident from `suite-desktop-ui`
  - (only this shall be cherrypicked)

## Notes for QA

Sentry testing error must work on Desktop, Web and Native.
I tested that in dev environments and Desktop build :heavy_check_mark: 

## Related Issue

Resolve #23149

## Screenshots:

[Testing error thrown from desktop](https://satoshilabs.sentry.io/issues/7027640356/?project=5193825&query=TESTING&referrer=issue-stream)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/sentry-desktop&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/sentry-desktop&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/sentry-desktop&lookback=7)

### CODE REVIEW

File: packages/suite-desktop-ui/src/sentry.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { SENTRY_CONFIG } from '@suite-common/sentry';
 const ELECTRON_RENDERER_SENTRY_CONFIG = {
     ...SENTRY_CONFIG,
     // BrowserSession is not present in Electron renderer process so we don't have to remove it
-    integrations: () => [captureConsoleIntegration({ levels: ['error'] })],
+    integrations: defaults => [...defaults, captureConsoleIntegration({ levels: ['error'] })],
```
Comment (Lemonexe) [inline packages/suite-desktop-ui/src/sentry.ts:8]: this is the fix 🙈

**Review by matejkriz — APPROVED** [review]
LGTM

**Review by OriginalEveres — APPROVED** [review]
LGTM
