### PR TITLE
fix(connect-popup): analytics for core in popup

### LINKED ISSUE #14983: Connect analytics calls in popup mode
Currently the AppReady event is only being sent from `connect-iframe`, not `connect-popup`. 
This means that data in popup coreMode is not reported correctly.

### PR DESCRIPTION
**Pull request by martykan**
## Description

Add AppReady event handling to core in popup flow.

## Related Issue

Resolve #14983

### CODE REVIEW

File: packages/connect-popup/src/index.tsx [hunk 1]
```diff
@@ -320,6 +320,22 @@ const handleMessageInCoreMode = (
                 info: method.info,
             });
             reactEventBus.dispatch({ type: 'state-update', payload: getState() });
+
+            const { settings } = getState();
+            const transport = core.getTransportInfo();
+            analytics.report({
+                type: EventType.AppReady,
```
Comment (mroz22) [inline packages/connect-popup/src/index.tsx:327]: IFRAME.CALL sounds weird but it makes sense, there is, right now, one iframe.call per popup open, so probably good enough 🤷‍♂️

**Review by mroz22 — APPROVED** [review]
