### PR TITLE
fix(suite): display correct native token for external EVMs

### LINKED ISSUE #23398: Transaction review amount is in ETH for unsupported EVMs
If I'm doing transactions via Connect on unsupported EVMs (in this example Monad), the amounts are incorrectly shown in ETH instead of the actual native token. 

Image

### PR DESCRIPTION
**Pull request by martykan**
## Description

Added new `nativeToken` field to PrecomposedTransaction, which can be used to override the network's native token. 
This is to display correct native token for EVMs that are used via Connect, but not natively supported in Suite

## Notes for QA

Import an unsupported chain into Metamask etc. and do a transaction via Connect. 

## Related Issue

Resolve #23398

## Screenshots:

With Monad chain (MON native token)

|Before|After|
|-|-|
|Screenshot 2025-11-28 at 16 06 17|Screenshot 2025-11-28 at 16 05 31|

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/suite-unsupported-evms-native-token&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/suite-unsupported-evms-native-token&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/suite-unsupported-evms-native-token&lookback=7)

### CODE REVIEW

File: packages/connect/src/api/ethereum/api/ethereumSignTransaction.ts [hunk 1]
```diff
@@ -202,6 +202,17 @@ export default class EthereumSignTransaction extends AbstractMethod<
...
+                    ? {
+                          type: 'NATIVE',
+                          standard: 'NATIVE',
+                          contract: '',
+                          name: this.params.network.name,
+                          symbol: this.params.network.shortcut,
+                          decimals: this.params.network.decimals,
+                      }
+                    : undefined,
+                network: this.params.network,
```
Comment (marekrjpolak) [inline packages/connect/src/api/ethereum/api/ethereumSignTransaction.ts:215]: Nit: why is there this `network` param? I haven't found a place where it is used.

**Review by marekrjpolak — APPROVED** [review]
Haven't tested, but I believe it's safe.

File: packages/connect/src/api/ethereum/api/ethereumSignTransaction.ts (hunk 1 above)
Comment (martykan) [reply packages/connect/src/api/ethereum/api/ethereumSignTransaction.ts:215]: For now it's not used, but I plan to show it in the UI later on
