### PR TITLE
Fix/bch lowercase button

### LINKED ISSUE #5151: Add convert to lowercase button for BCH send dialogue
**Describe the bug**
Found this issue during new firmware change in QR code rendering
` Do not convert bech32 addresses to upper-case for QR code #1751 `
QR code generated from Trezor is not accepted by Trezor Suite

**Steps to reproduce:**
1. generate BCH Receive address
2. Scan QR code
3. Use it as receive address in Suite

**Info:**
 - Suite version: web 22.3.2 (563be1e28ad75ddd4e38c2002e6032b0743511d2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**
Screenshot 2022-03-18 at 13 52 42
Screenshot 2022-03-18 at 13 53 20
Screenshot 2022-03-18 at 13 54 33
Screenshot 2022-03-18 at 13 54 38

### PR DESCRIPTION
**Pull request by komret**
## Description
1. Add case-sensitive validation BCH addresses
2. Add validation for BCH address prefix
3. Recompose transaction when address field is manipulated by the button

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/5151

#### before:
Uppercase address creates compose error, no field validation message is shown:

https://github.com/user-attachments/assets/7976fd89-d908-4cdb-8c45-3e48b81e3209

Prefix-less address not detected by validation, fails when signing:

https://github.com/user-attachments/assets/38c24d03-fdb8-48d0-ad7b-d0b1c7703fce
#### after:

https://github.com/user-attachments/assets/f56e1fa6-52a4-46ab-98da-9563858cf827

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/bch-lowercase-button&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/bch-lowercase-button&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/bch-lowercase-button&lookback=7)

### CODE REVIEW

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -5497,6 +5497,10 @@ export default defineMessages({
         defaultMessage: 'Convert to lowercase',
         id: 'TR_CONVERT_TO_LOWERCASE',
     },
+    TR_ADD_BITCOINCASH_PREFIX: {
+        defaultMessage: 'Add bitcoincash: prefix',
```
Comment (peter-sanderson) [inline packages/suite/src/support/messages.ts]: Is this copy correct? Seems to me as some placeholder

Comment (komret) [reply packages/suite/src/support/messages.ts]: Will look better with quotes: 83d946a0814423ba701df286442cf9e5529c9fa6

File: packages/suite/src/views/wallet/send/Outputs/Address.tsx [hunk 2]
```diff
@@ -240,6 +256,14 @@ export const Address = ({ output, outputId, outputsCount }: AddressProps) => {
                     return translationString('TR_UNSUPPORTED_ADDRESS_FORMAT');
                 }
             },
+            uppercase: (value: string) => {
+                if (
+                    (symbol === 'bch' && isCashAddressUppercase(value)) ||
+                    (networkType === 'bitcoin' && isBech32AddressUppercase(value))
```
Comment (peter-sanderson) [inline packages/suite/src/views/wallet/send/Outputs/Address.tsx]: The comment `// bech32 addresses are valid as uppercase but are not accepted by Trezor` was dropped intentionally

To me it makes sense

File: suite-common/wallet-utils/src/__tests__/validation.test.ts [hunk 3]
```diff
@@ -164,6 +166,32 @@ describe('validation', () => {
         ).toEqual(true);
     });
 
+    it('hasCashAddressPrefix', () => {
+        expect(hasCashAddressPrefix('')).toBe(false);
```
Comment (peter-sanderson) [inline suite-common/wallet-utils/src/__tests__/validation.test.ts]: optional: dataProvider or jest `each`  https://jestjs.io/docs/api#testeachtablename-fn-timeout

File: suite-common/wallet-utils/src/validationUtils.ts [hunk 4]
```diff
@@ -62,8 +62,14 @@ export const isTaprootAddress = (address: string, symbol: Account['symbol']) =>
     );
 };
 
+export const hasCashAddressPrefix = (address: string) =>
```
Comment (peter-sanderson) [inline suite-common/wallet-utils/src/validationUtils.ts]: is there a reason we call it just `cash` and not `bitcoincash`?

File: suite-common/wallet-utils/src/validationUtils.ts [hunk 5]
```diff
@@ -62,8 +62,14 @@ export const isTaprootAddress = (address: string, symbol: Account['symbol']) =>
...
+    /^bitcoincash:/.test(address.toLowerCase());
+
+export const isCashAddressUppercase = (address: string) =>
```
Comment (peter-sanderson) [inline suite-common/wallet-utils/src/validationUtils.ts]: same here -> https://github.com/trezor/trezor-suite/pull/18519/files#r2056288851

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/views/wallet/send/Outputs/Address.tsx (hunk 2 above)
Comment (komret) [reply packages/suite/src/views/wallet/send/Outputs/Address.tsx]: 4bad5f0cecdfd7d9673a7fb8f07f8962afa83e6f

File: suite-common/wallet-utils/src/validationUtils.ts (hunk 5 above)
Comment (komret) [reply suite-common/wallet-utils/src/validationUtils.ts]: f58867a7753bafbae6b3879c813bf812c59eb3a7

File: suite-common/wallet-utils/src/validationUtils.ts (hunk 4 above)
Comment (komret) [reply suite-common/wallet-utils/src/validationUtils.ts]: f58867a7753bafbae6b3879c813bf812c59eb3a7

File: suite-common/wallet-utils/src/__tests__/validation.test.ts (hunk 3 above)
Comment (komret) [reply suite-common/wallet-utils/src/__tests__/validation.test.ts]: f58867a7753bafbae6b3879c813bf812c59eb3a7
