### PR TITLE
Fix/device redirect fixes

### LINKED ISSUE #9993: Device switcher issues Android
Empty dashboard:

- [x] #9995
- [x] #9996

UI bugs:

- [x] #9997
- [x] #9998
- [x] #9999
- [x] #10000
- [x] #10001
- [x] #10010 

Connected Trezor switcher

- [x] #10002
- [x] #10003
- [x] #10062

### LINKED ISSUE #9995: In empty dashboard (signpost) user should not see "Portfolio tracker" in switcher - there should be "Hello there" - look at the designs.
Empty dashboard switcher should have not be in the state of Portfolio tracker. There should be "Hello there"

Screenshot 2023-11-17 at 11 15 16

### LINKED ISSUE #9996: Content of switcher does not have the items according to design > if user clicks on the switcher - there should be possibility to click only on "Connect the Trezor" - look at the designs
In empty state of the dashboard, user should see only option to Connect Trezor in opened Swticher - look at the designs:
Screenshot 2023-11-17 at 11 16 10

### LINKED ISSUE #10002: If user switch to Portfolio tracker - he should land on empty "portfolio tracker dashboard"
When user switch to portfolio tracker via switcher and the portfolio tracker is empty, user should land in "empty portfolio tracker dashboard"
Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=3804%3A12800&mode=design&t=NHHH5wsJTwIQX02T-1

### LINKED ISSUE #10003: Each switch back to Connected Trezor shows the screen "Connecting"

### LINKED ISSUE #10062: When user is in Portfolio tracker and the device is connected, there should not be the option to connect another device.
Screenshot_20231125-124627

### PR DESCRIPTION
**Pull request by PeKne**
Batch of device manager and related redirects fixes.

## Description

- 2a06aea619171181d9b1fa047becae04b3aa3295 - the connecting loader screen is triggered only on device connection, not on the selection of the device from the device manager any more.  
  - fixes #10003
- bb0db8c0b6283471c8fc780c29910b8442c29255 - the connect/import crossroad is displayed only if there is no physical device connected and portfolio tracker does not contain any account 
  - fixes #10002
- ccb1ec69ce5396cd1203e454f7d85e03c5cfabbb - while the crossroads is displayed, the device manager header contains `Hi there!` and trezor company logo 
  - fixes #9995, fixes #9996
- 79f68acc4e4ee99141b0e32faceac2e3eff933b3 - if user ejects device by clicking on eject button, device manager is closed
- b95f3dba74 - connect button is displayed only if there is no physical device connected 
  - fixes #10062
 
## Related Issue

Closes #9993 (the Android device manager bugs epic)

### CODE REVIEW

File: suite-common/wallet-core/src/device/deviceReducer.ts [hunk 1]
```diff
@@ -684,3 +684,8 @@ export const selectPersistedDevicesStates = (state: DeviceRootState) => {
     const devices = selectDevices(state);
     return [...devices.map(d => d.id), PORTFOLIO_TRACKER_DEVICE_STATE];
 };
+
+export const selectIsNoPhysicalDeviceConnected = (state: DeviceRootState) => {
+    const devices = selectDevices(state);
+    return devices.length === 1 && devices[0].id === PORTFOLIO_TRACKER_DEVICE_ID;
```
Comment (Nodonisko) [inline suite-common/wallet-core/src/device/deviceReducer.ts:690]: nit: could be simplified to just `devices?.[0].id ===  PORTFOLIO_TRACKER_DEVICE_ID`

**Review by Nodonisko — APPROVED** [review]

File: suite-common/wallet-core/src/device/deviceReducer.ts (hunk 1 above)
Comment (PeKne) [reply suite-common/wallet-core/src/device/deviceReducer.ts:690]: I think the device on the index 0 is alway the Portfolio tracker, because it is always created already during the app init. So IMO if I would remove the check for the `devices.length`, it would not work as expected.
