### PR TITLE
recovery fixes

### LINKED ISSUE #1329: Recovery mode
Needs design: How should suite behave when user connects / selects device in recovery mode.

### PR DESCRIPTION
**Pull request by mroz22**
- [x] change padding around success and error image in recovery 
- [x] add illustration to recovery mode modal
- [x] fix progress bar (https://github.com/trezor/trezor-suite/pull/1447/commits/43b0794f065b79e7d9aa57be65e94243d768eb1f)
- [x] prevent stuck in recovery in onboarding bug (go to onboarding, select recovery, start recovery, disconnect, reconnect, finish recovery on device without touching UI, get stuck io recovery step in onboarding)

### Initialized device
common steps: check seed -> start -> confirm  on device:

- [x] reload window -> click continue -> finish on device
- [x] reload window -> finish on device without clicking continue -> click continue

Here comes a little unhappy case I can not do much about. Maybe close seed check modal, but where do I display error? In application state modal indicating that device is in recovery mode? @matejzak 

- [ ] reconnect device -> error state appears -> finish on device with success -> error state still visible -> click close -> see device-is-in-recovery mode -> click continue.

 
### No seed device
common steps: onboarding -> recovery -> start -> confirm on device 
- [x] reload window -> click continue -> finish on device
- [x] reload window -> finish on device without clicking continue -> click on continue
- [x] reconnect -> error appears -> click retry -> finish on device
- [x] reconnect -> error appears -> finish without clicking retry -> ??? 

___

resolves #1329

### CODE REVIEW

File: packages/suite/src/views/suite/device-recovery-mode/index.tsx [hunk 1]
```diff
@@ -11,42 +11,49 @@ const Wrapper = styled.div`
...
-                        <Button onClick={() => checkSeed()}>
-                            <Translation id="TR_CONTINUE" />
-                        </Button>
-                    )}
-                </Buttons>
-            </>
-        )}
-    </Wrapper>
-);
+const Index = ({ device }: Props) => {
```
Comment (mroz22) [inline packages/suite/src/views/suite/device-recovery-mode/index.tsx]: since I am now handling recovery-mode automatically, it probably makes sense to replace this component with simple <Loading />

File: packages/suite/src/actions/recovery/recoveryActions.ts [hunk 2]
```diff
@@ -68,22 +68,14 @@ const checkSeed = () => async (dispatch: Dispatch, getState: GetState) => {
...
-
     dispatch(setStatus('finished'));
 };
 
 const recoverDevice = () => async (dispatch: Dispatch, getState: GetState) => {
     const { advancedRecovery, wordsCount } = getState().recovery;
     const { device } = getState().suite;
     if (!device || !device.features) return;
-
+    dispatch(setError(''));
```
Comment (szymonlesisz) [inline packages/suite/src/actions/recovery/recoveryActions.ts:78]: why?

Comment (mroz22) [reply packages/suite/src/actions/recovery/recoveryActions.ts:78]: starting new call erases previous error and results either in finished state which may or may not add new error.
