### PR TITLE
fix: empower bugs

### LINKED ISSUE #10909: Inactive dropdown selector in Trade/Sell section
**Describe the bug**
Inactive dropdown selector in Trade/Sell section.
See comparison with current production version

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
Screenshot 2024-01-30 at 13 33 40
Screenshot 2024-01-30 at 13 33 32

### LINKED ISSUE #10937: Empower/Coinjoin loading account toggle missaligned
Plese align it to the right side of the screen
image

Like this 
image

### LINKED ISSUE #10938: Empower/Spacing of coinjoin state and time seems a bit off
image

### LINKED ISSUE #10956: Empower/Fake tx warning - text spacing
image

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Second wave of multiple fixes to empower.

## Related Issue

Resolve #10956
Resolve #10909
Resolve #10937
Resolve #10938

## Screenshots:
Screenshot 2024-02-01 at 10 52 03 AM
EA9DA5A7-47A5-4F2B-B918-B2C0E6187562_4_5005_c

### CODE REVIEW

File: packages/components/src/components/form/Select/Select.tsx [hunk 1]
```diff
@@ -260,6 +264,7 @@ export const Select = ({
     onChange,
     placeholder,
     isDisabled,
+    isWithIndicator = true,
```
Comment (dahaca) [inline packages/components/src/components/form/Select/Select.tsx]: What is it supposed to represent? To me this is basically `isDisabled`, and in both places it's used together with it. Perhaps the disables state should not have an indicator, simply 💭  Will discuss with David!

File: packages/suite/src/components/wallet/WalletLayout/CoinjoinAccountDiscovery/RememberWallet.tsx [hunk 2]
```diff
@@ -21,26 +22,31 @@ const Middle = styled.div`
     gap: ${spacingsPx.xxs};
 `;
 
+const Left = styled.div`
+    display: flex;
```
Comment (dahaca) [inline packages/suite/src/components/wallet/WalletLayout/CoinjoinAccountDiscovery/RememberWallet.tsx]: nit: IMO having `margin-left: auto` on the switch is an easier solution? Would not need to `justify-content` as well!

File: packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx [hunk 3]
```diff
@@ -9,13 +9,17 @@ import {
     selectCurrentCoinjoinWheelStates,
     selectCurrentSessionDeadlineInfo,
 } from 'src/reducers/wallet/coinjoinReducer';
+import { spacingsPx } from '@trezor/theme';
 
 const Cointainer = styled.div`
-    height: 30px;
```
Comment (dahaca) [inline packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx:14]: i believe this was here to fix the height of that section and prevent the layout from jumping 🤔 Might be wrong though, will run it later!

File: packages/components/src/components/form/Select/Select.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/components/src/components/form/Select/Select.tsx]: Ok, ask please, I think it makes sense to have it like this, in 99% of situations you want to show disabled indicator but just here for the trade section it doesn't make much sense

File: packages/suite/src/components/wallet/WalletLayout/CoinjoinAccountDiscovery/RememberWallet.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/CoinjoinAccountDiscovery/RememberWallet.tsx]: 4b027de8e70c21638e0e7b71eee706c7cca9ba86

File: packages/components/src/components/form/Select/Select.tsx (hunk 1 above)
Comment (dahaca) [reply packages/components/src/components/form/Select/Select.tsx]: Yes, then let's remove `isWithIndicator` and nor render the indication when `isDisabled`! If David will say otherwise later, I will fix 🙌

File: packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx (hunk 3 above)
Comment (dahaca) [reply packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx:14]: As suspected :) 

image

File: packages/components/src/components/form/Select/Select.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/components/src/components/form/Select/Select.tsx]: Done

File: packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx (hunk 3 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx:14]: Please check it 🙏 - 06c567a5d687610b0bbf0a895ec174afad47dc5e (don't have Coinjoin active anywhere)

**Comment by jvaclavik** [comment]
@AdamSchinzel FYI I'm taking this PR on my own 👍

File: packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx (hunk 3 above)
Comment (jvaclavik) [reply packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinStatusWheel/CoinjoinStatusMessage.tsx:14]: Fixed now: image

File: packages/components/src/components/form/Select/Select.tsx [hunk 4]
```diff
@@ -123,6 +123,7 @@ const Wrapper = styled.div<WrapperProps>`
         padding: 0;
         transition: transform 0.2s cubic-bezier(0.68, -0.02, 0.21, 1.1);
         cursor: pointer;
+        display: ${({ isDisabled }) => isDisabled && 'none'};
```
Comment (peter-sanderson) [inline packages/components/src/components/form/Select/Select.tsx:126]: nit: i would prefer ternar operator here, this is a bit unintuitive

**Review by peter-sanderson — APPROVED** [review]
