### PR TITLE
Trading - Approval States + Revoke Modal

### LINKED ISSUE #19220: Trading DEX – handle USDT and other similar token allowances properly.
- cover two special cases for when the approval was done for too low amount
  - direct user to approval flow to increase the limit if possible and communicate him this by changing the text on the button ([Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4236-5496&t=fsNTebgxEYdgeCr2-4))
  - direct user to revoke flow first if required (e.g. USDT) ([Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4236-5989&t=fsNTebgxEYdgeCr2-4))

Image

# Info by QA

**Bug Summary**  
Some tokens like USDT do not support direct increases to allowances. As a result, when Trezor Suite tries to update the allowance for such tokens, the transaction fails and the DEX trade cannot be completed. You can view an example of a failed transaction here:  
https://etherscan.io/tx/0x88e97d1bc6314a4fdaf0257d742bde1b411d6ce830a972b68845a9244f08f32e  

**Expected Behavior**  
USDT and similar tokens require that the current allowance be set to zero before assigning a new amount. 
```
    /**
    * @dev Approve the passed address to spend the specified amount of tokens on behalf of msg.sender.
    * @param _spender The address which will spend the funds.
    * @param _value The amount of tokens to be spent.
    */
    function approve(address _spender, uint _value) public onlyPayloadSize(2 * 32) {

        // To change the approve amount you first have to reduce the addresses`
        //  allowance to zero by calling `approve(_spender, 0)` if it is not
        //  already 0 to mitigate the race condition described here:
        //  https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729
        require(!((_value != 0) && (allowed[msg.sender][_spender] != 0)));

        allowed[msg.sender][_spender] = _value;
        Approval(msg.sender, _spender, _value);
    }
```

This behavior is enforced by the USDT smart contract, as shown in the code snippet.  

**How to replicate**
1. Swap amount X of ETH USDT to something
2. Make approval for this amount
3. Repeat, Swap amount bigger than X of ETH USDT
4. Make approval for this amount (fail + fee estimation error because simulation fails)

**Info:**
 - Suite version: web 25.6.0 (e7f7fcd5bd7019a4c292a4bbb9ae414544bc778e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2880x1800
 - Device: Trezor T3T1 2.8.10 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport

**Screenshot for Reference**  

https://github.com/user-attachments/assets/0e7596d7-a44e-4ce2-94ea-bbf225722aaa

This case for ETH USDT always fails
Image

### LINKED ISSUE #20385: Trading - approval states
Please adjust and simplify ALL approval states handling in the SWAP flow according to [Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4236-8452&t=fsNTebgxEYdgeCr2-4).

Changes
- remove this box from all states
Image

- change text on notification (standard in top right corner) once approval or revoke is complete to provide feedback to user, detail described in Figma

Note 1:  new approval modal has its own task -> #20272 

# Proposal (just one of the states for illustation, check figma)

Image

# Current

Image

### LINKED ISSUE #20386: Trading - add revoke modal
Currently approval revoking happens without any modal and user only confirms in on Trezor.

Introduce this modal to better communicate what is happening and to enable user to select Fee.

[Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4230-1842&t=fsNTebgxEYdgeCr2-4)

# Proposal

Image

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

- updated approval states according to [Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4236-8452&t=fsNTebgxEYdgeCr2-4)
- added a new revoke modal
- for USDT tokens, the user cannot increase approval and must revoke the pre-approved amount first
- for other tokens, the user can either increase current approval or revoke previous approval

## Related Issue

Resolve #20385 
Resolve #20386 
Resolve #19220

## Screenshots:

01-approve

02-confirming-approval

Token is pre-approved but the user wants to swap a higher amount.

03-increase-approval

For USDT tokens, user cannot increase approval and must revoke pre-approved amount first.

06-revoke-approval

07-revoke-modal

05-revoking-approval

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/approval-states&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/approval-states&lookback=7)

### CODE REVIEW

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts [hunk 1]
```diff
@@ -392,3 +392,22 @@ export const getTradeTypeByRoute = (
...
+
+export const isUsdtToken = (contractAddress?: string) => {
+    const usdtContractAddresses = [
+        '0xdAC17F958D2ee523a2206206994597C13D831ec7', // ethereum
+        '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9', // arbitrum one
+        '0x55d398326f99059fF775485246999027B3197955', // binance smart chain
+        '0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7 ', // avalanche
+        '0xc2132D05D31c914a87C6611C10748AEb04B58e8F', // polygon
+        '0x94b008aa00579c1307b0ef2c499ad98a8ce58e58', // optimism
+    ];
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]: https://github.com/trezor/trezor-suite/issues/19220 this should not be hardcoded, the best scenario is to get some flag from trading backend

Comment (tomasklim) [reply packages/suite/src/utils/wallet/trading/tradingUtils.ts]: Moreover it looks that it is implemented only for mainnet

Comment (tomasklim) [reply packages/suite/src/utils/wallet/trading/tradingUtils.ts]: maybe if we know only about this one token, we can have it in suite but I would not call it `usdt` specific but more generic

Comment (TomasBoda) [reply packages/suite/src/utils/wallet/trading/tradingUtils.ts]: I changed the naming to be more general

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx [hunk 2]
```diff
@@ -0,0 +1,229 @@
...
+                {!isIncreasingAllowanceSupported && (
+                    <Banner variant="info" icon="info">
+                        <Translation
+                            id="TR_EXCHANGE_APPROVAL_MODAL_REVOKE_BANNER"
+                            values={{ displaySymbol }}
+                        />
+                    </Banner>
+                )}
+
+                <Box borderWidth={borders.widths.large} padding={spacings.sm} borderRadius="12px">
```
Comment (izmy) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]:
```suggestion
                <Box borderWidth={borders.widths.large} padding={spacings.sm} borderRadius={borders.radii.sm}>
```

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx [hunk 3]
```diff
@@ -0,0 +1,229 @@
...
+        onCancel();
+    };
+
+    const { coinSymbol, contractAddress } = cryptoIdToSymbolAndContractAddress(selectedQuote.send);
+    const displaySymbol = coinSymbol && getDisplaySymbol(coinSymbol, contractAddress);
+    const isIncreasingAllowanceSupported = tokenSupportsIncreasingAllowance(contractAddress);
+
+    const providers = getProvidersInfoProps(context);
+    const provider =
+        selectedQuote && selectedQuote.exchange && providers
```
Comment (izmy) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx:90]: You can use the `exchange` that you already destructured above.

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx [hunk 4]
```diff
@@ -0,0 +1,229 @@
...
+                    <Column gap={spacings.sm}>
+                        <Column gap={spacings.sm}>
+                            <Text>
+                                <Translation id="TR_EXCHANGE_APPROVAL_PROVIDER" />
+                            </Text>
+                            <Row gap={spacings.xs}>
+                                {provider?.logo && (
+                                    <CustomIcon
+                                        src={invityAPI.getProviderLogoUrl(provider.logo)}
+                                        alt=""
```
Comment (izmy) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]:
```suggestion
                                        alt={provider.logo}
```

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx [hunk 5]
```diff
@@ -0,0 +1,229 @@
...
+                                    </Row>
+                                }
+                            >
+                                <BreakableValue>{dexTx.data}</BreakableValue>
+                            </CollapsibleBox>
+                        ) : null}
+                    </Column>
+                </Box>
+
+                <Box padding={spacings.sm} borderWidth={borders.widths.large} borderRadius="12px">
```
Comment (izmy) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]:
```suggestion
                <Box padding={spacings.sm} borderWidth={borders.widths.large} borderRadius={borders.radii.sm}>
```

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx [hunk 6]
```diff
@@ -0,0 +1,229 @@
...
+
+    const [isConfirmButtonLoading, setIsConfirmButtonLoading] = useState<boolean>(false);
+
+    if (!selectedQuote) return null;
+
+    const { exchange, dexTx } = selectedQuote;
+    if (!exchange || !dexTx) return null;
+
+    if (!selectedQuote.send) return null;
+
```
Comment (izmy) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: You can merge the three consecutive `if (!selectedQuote...)` checks into a single condition using optional chaining for better readability:

```
if (!selectedQuote?.exchange || !selectedQuote?.dexTx || !selectedQuote?.send) {
    return null;
}
```

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx [hunk 7]
```diff
@@ -44,34 +36,17 @@ const loadingAnimation = keyframes`
...
-
-const IconCircle = ({ variant }: IconProps) => (
-    <Icon name="circle" size="mediumLarge" variant={variant} />
-);
-
-const IconError = ({ variant }: IconProps) => (
-    <Icon name="xCircle" size="mediumLarge" variant={variant} />
-);
-
 const ApprovalStep = ({ label, icon }: { label: ReactNode; icon: ReactNode }) => (
```
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx]: There is the same name for the component and the type... yea, TS can handle it, but it could be confusing, so I suggest renaming the component to `ApprovalStepRow`? I also don't see any use for this code, so you can delete it.

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx [hunk 8]
```diff
@@ -292,124 +270,85 @@ export const TradingFormApproval = ({
...
+                                    </Button>
+
+                                    <TextButton
+                                        onClick={() =>
+                                            isRevokeButtonDisabled ||
+                                            isRevokeButtonLoading ||
+                                            isApproveButtonDisabled ||
+                                            isApproveButtonDisabled
+                                                ? null
+                                                : onRevokeApprovalClick()
```
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx]:
```suggestion
                                        onClick={() =>
                                            isRevokeButtonDisabled ||
                                            isRevokeButtonLoading ||
                                            isApproveButtonDisabled
                                                ? null
                                                : onRevokeApprovalClick()
```

**Review by izmy — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx [hunk 9]
```diff
@@ -0,0 +1,229 @@
...
+                                    <Text typographyStyle="hint" variant="tertiary">
+                                        {contractAddress}
+                                    </Text>
+                                </Column>
+                            </Row>
+                        </Column>
+
+                        <Divider margin={{ top: 0, bottom: 0 }} />
+
+                        <Row alignItems="center" gap={spacings.xxxxl}>
```
Comment (matusbalascak) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: It would look nicer if you used `alignItems="start"` here, wrap the arrow `Icon` below with flex container and set its `alignSelf` to `center`

So instead of this:
image


You get nicely aligned revoke token info even when token amount breaks to the next line
image

**Review by matusbalascak — DISMISSED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx (hunk 2 above)
Comment (TomasBoda) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: done

Comment (TomasBoda) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: also in `ApproveModal`

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx (hunk 3 above)
Comment (TomasBoda) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx:90]: done

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx (hunk 4 above)
Comment (TomasBoda) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: done

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx (hunk 5 above)
Comment (TomasBoda) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: done

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx (hunk 6 above)
Comment (TomasBoda) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: done

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx (hunk 7 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx]: removed

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx (hunk 8 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormApproval.tsx]: that was a misspelling, I intended to use `isApproveButtonLoading` instead of duplicate `isApproveButtonDisabled`, fixed

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx (hunk 9 above)
Comment (TomasBoda) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/RevokeModal.tsx]: good suggestion, done

**Review by izmy — APPROVED** [review]

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts [hunk 10]
```diff
@@ -392,3 +392,22 @@ export const getTradeTypeByRoute = (
...
+
+    const isUsdt =
+        contractAddress &&
+        usdtContractAddresses
+            .map(usdtContractAddress => usdtContractAddress.toLowerCase())
+            .includes(contractAddress.toLowerCase());
+
+    return !isUsdt;
+};
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]: Only applies to Ethereum chain. Other chains are fine and revoke should not be needed

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Review by tomasklim — CHANGES_REQUESTED** [review]
It looks like that now when you do revoke/approve, quote can refresh and wants revoke/approve again. This did not happen before (on develop)

**Comment by tomasklim** [comment]
@coderabbitai review

**Review by tomasklim — APPROVED** [review]
LGTM, works good now. Refresh of quotes is not replicable anymore. However, I do not see really a change in code. In case of any troubles, we still have 1 week to fix it
