### PR TITLE
fix(suite): transaction search with token name, symbol or contract

### LINKED ISSUE #3544: Transaction history - ERC20 tokens not included in search
**Describe the bug**
When you look in Ethereum transaction history ERC20 tokens are not included in search.  

**Steps to reproduce:**
1. Load account that includes ERC20 token transactions 
2. Search for those transaction via search field
3. Observe

**Info:**
 - Suite version: web 21.4.0 (1da73bf5c45ed462662a4b3f12b10993625b9999)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
When you look in Ethereum transaction history ERC20 tokens are included in search.  

**Actual result:**
When you look in Ethereum transaction history ERC20 tokens are not included in search.  

**Screenshots:**
image

image

image

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Enable search by token symbol, name or contract address inside transactions.

## Related Issue

Resolve #3544

## Screenshots:
Screenshot 2024-07-18 at 10 08 52 AM

### CODE REVIEW

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 1]
```diff
@@ -920,6 +920,24 @@ export const simpleSearchTransactions = (
...
 
+    // Find by token name, symbol or contract
+    const foundTxsForToken = transactions.flatMap(t => {
+        const hasMatchingToken = t.tokens.some(token => {
+            return (
+                token.symbol?.toLowerCase().includes(search) ||
+                token.name?.toLowerCase().includes(search) ||
+                token.contract?.toLowerCase().includes(search)
+            );
+        });
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts]: can you reuse logic from tokens tab?

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 2]
```diff
@@ -920,6 +920,24 @@ export const simpleSearchTransactions = (
     });
     txsToSearch.push(...foundTxsForAddress);
 
+    // Find by token name, symbol or contract
+    const foundTxsForToken = transactions.flatMap(t => {
+        const hasMatchingToken = t.tokens.some(token => {
+            return (
+                token.symbol?.toLowerCase().includes(search) ||
+                token.name?.toLowerCase().includes(search) ||
+                token.contract?.toLowerCase().includes(search)
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts]: please for cardano also add fingerprint and policyId

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 3]
```diff
@@ -920,6 +920,24 @@ export const simpleSearchTransactions = (
     });
     txsToSearch.push(...foundTxsForAddress);
 
+    // Find by token name, symbol or contract
+    const foundTxsForToken = transactions.flatMap(t => {
+        const hasMatchingToken = t.tokens.some(token => {
+            return (
+                token.symbol?.toLowerCase().includes(search) ||
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts]: does not work in case I do not insert symbol/name/contract lowercased

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 4]
```diff
@@ -920,6 +920,24 @@ export const simpleSearchTransactions = (
     });
     txsToSearch.push(...foundTxsForAddress);
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts:922]: Tip

`Tip: You can search for transaction IDs, addresses, labels, amounts and dates.` 

not updated

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 5]
```diff
@@ -1053,3 +1054,13 @@ export const isAddressBasedNetwork = (networkType: NetworkType) => {
 
     return !!exhaustiveCheck;
 };
+
+export const tokenMatchesSearch = (token: TokenInfo, search: string) => {
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]:
```suggestion
export const isTokenMatchesSearch = (token: TokenInfo, search: string) => {
```

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 6]
```diff
@@ -920,6 +920,20 @@ export const simpleSearchTransactions = (
...
 
+    // Find by token name, symbol or contract
+    const foundTxsForToken = transactions.flatMap(t => {
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts]:
```suggestion
    const foundTxsForToken = transactions.flatMap(transaction => {
```

File: packages/suite/src/support/messages.ts [hunk 7]
```diff
@@ -6964,7 +6964,7 @@ export default defineMessages({
     TR_TRANSACTIONS_SEARCH_TIP_1: {
         id: 'TR_TRANSACTIONS_SEARCH_TIP_1',
         defaultMessage:
-            'Tip: You can search for transaction IDs, addresses, labels, amounts and dates.',
+            'Tip: You can search for transaction IDs, addresses, tokens, labels, amounts and dates.',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts:6967]: Note: added to crowdin, please next time 🙏

**Review by tomasklim — APPROVED** [review]
