### PR TITLE
fix(staking): error duplication in unstake modal

### LINKED ISSUE #13753: Deduplicate errors in unstake modal when using other amount
**Description**
- error is duplicated right under input and then in warning. Please show it just once. Under input in case it is related to it. In warning otherwise.

Image

Image

Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Fixed an issue where the error message was duplicated in unstake modal. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13753

## Screenshots:
image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeEthForm/UnstakeEthForm.tsx [hunk 1]
```diff
@@ -91,14 +91,6 @@ export const UnstakeEthForm = () => {
 
             <Options symbol={symbol} />
 
-            <WarningsWrapper>
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeEthForm/UnstakeEthForm.tsx:94]: By this change, this banner will be gone for all options :( 
Screenshot 2024-08-19 at 17 42 57

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeEthForm/UnstakeEthForm.tsx (hunk 1 above)
Comment (dev-pvl) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeEthForm/UnstakeEthForm.tsx:94]: this should work https://github.com/trezor/trezor-suite/pull/13873/commits/7b88b68de0fe801bb4535e9a8a29de66075619be

Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeEthForm/UnstakeEthForm.tsx:94]: looks good

**Review by tomasklim — APPROVED** [review]
LGTM 
Screenshot 2024-08-21 at 14 43 36
Screenshot 2024-08-21 at 14 43 28
Screenshot 2024-08-21 at 14 43 24
