### PR TITLE
Staking Dashboard fixes

### LINKED ISSUE #21989: Staking on dashboard - bugs
Please fixing following issues on STAKING section on DASHBOARD SCREEN ([original Figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Staking--Final-?node-id=2409-7160&t=qUiygiAiQdhYEuwH-4)):

Changes to apply across whole desktop Suite for all tables:
- Decrease font size in table header (should be 14px, is 16px)
- Add border around the whole white part of the table

Staking specific bug:
- If user has some available balance to stake, but it is enough for min. stake (<0.01 SOL, <0.1ETH), prompt him to "buy" more coins instead "stake more" as he won't be able to do that ([screen](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Staking--Final-?node-id=3047-21761&t=qUiygiAiQdhYEuwH-4))

Image

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

This PR fixes three things:

- adds borders around ALL TABLES
- reduces table header font size to `14px` for ALL TABLES
- if an account has staked, but has insufficient funds for staking more, prompt the user to buy more

## Related Issue

Resolve #21989 

## Screenshots:

Screenshot 2025-10-30 at 10 54 09

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/staking-dashboard&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/staking-dashboard&lookback=7)

### CODE REVIEW

File: packages/components/src/components/Table/TableCell.tsx
Comment (cermakjiri) [inline packages/components/src/components/Table/TableCell.tsx]:
```suggestion
    const { hasBorders, typographyStyle = 'body' } = useTable();
```

File: packages/components/src/components/Table/TableCell.tsx [hunk 1]
```diff
@@ -83,7 +83,7 @@ export const TableCell = ({
         horizontal: spacings.lg,
     };
 
-    const defaultTypographyStyle = isHeader ? 'hint' : 'body';
+    const defaultTypographyStyle = 'body';
```
Comment (cermakjiri) [inline packages/components/src/components/Table/TableCell.tsx]:
```suggestion
```

File: packages/components/src/components/Table/TableCell.tsx [hunk 2]
```diff
@@ -97,7 +97,7 @@ export const TableCell = ({
         >
             <Text
                 as="div"
-                typographyStyle={typographyStyle ?? defaultTypographyStyle}
+                typographyStyle={isHeader ? 'hint' : (typographyStyle ?? defaultTypographyStyle)}
```
Comment (cermakjiri) [inline packages/components/src/components/Table/TableCell.tsx]:
```suggestion
                typographyStyle={isHeader ? 'hint' : typographyStyle}
```

**Review by cermakjiri — APPROVED** [review]
