### PR TITLE
fix(trading): update swap receive address when asset changes

### LINKED ISSUE #26457: Receive address not updated when changing asset in Swap
**Describe the bug**

When changing the receive asset in Swap, the address field keeps the address of the previously selected account if it is a valid address for the new network.

**Info:**
 - Suite version: desktop 26.4.0 (347b89846e50900a5fe0eebcc0f304a7e5b20e77)
 - Browser: Trezor Suite 26.4.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.11.1 universal (revision ef73d69c06a0496a06ca849ed4f84d9beafe5c2c)
 - Transport: BluetoothTransport, BridgeTransport 3.2.1

**Steps to reproduce**

1. Go to Swap tab
2. Select a "From" and "To" pair
3. Change the receive asset ("To" network)
4. Observe the receive account not updating

**Expected behavior**

The receive account should always change to match the selected asset

**Screenshots**

Swap bug address not updated

https://github.com/user-attachments/assets/519499d9-dce7-45cb-929d-cd3ef4526c84

### PR DESCRIPTION
**Pull request by sherpaPSX**
## Description

- Reinitialize swap receive address selection when the receive asset changes by resetting state on cryptoId changes.
- Avoid carrying over stale receive addresses when no matching Suite receive account exists for the newly selected asset.
- Handle receive address validator exceptions so invalid network/address combinations consistently fail validation.

## Notes for QA

- In Wallet -> Trading -> Swap, choose a From/To pair, then change the To asset to a different network and confirm the receive address is updated/reset instead of staying on the previous asset address.
- Open the receive address modal, paste an address from a different network, and confirm you get an invalid receiving address validation error.
- Switch back to an asset where a previously used valid non-suite receive address exists and confirm it can still be selected.

## Related Issue

Resolve #26457

## Screenshots:

N/A

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/26457-swap-receive-address-update&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/26457-swap-receive-address-update&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 13 test(s)</summary>

| Test | Type |
|------|------|
| TrezorConnect popup web > TrezorConnect.getAddress | 🤖 auto |
| TrezorConnect popup web > call cancellation | 🤖 auto |
| TrezorConnect popup web > closing popup window returns Method_Interrupted error | 🤖 auto |
| TrezorConnect popup web > call cancelled from calling application | 🤖 auto |
| TrezorConnect popup web > second call after popup was closed by user should work | 🤖 auto |
| TrezorConnect popup web > focuses existing popup if already open | 🤖 auto |
| Quarantine test: "Account metadata,google - watches files over time" | 🙋 manual |
| Quarantine test: "Account metadata,dropbox - watches files over time" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-08T08:13:20.988Z • 13 test(s) total_

<details><summary>Trezor Suite (desktop) — 4 test(s)</summary>

| Test | Type |
|------|------|
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-08T08:11:47.470Z • 4 test(s) total_

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts [hunk 1]
```diff
@@ -110,6 +110,7 @@ export const useTradingReceiveAddress = ({
 
     const canAddSuiteAccount = !!(device?.connected && isSupportedNetwork);
     const canUseNonSuiteAccount = nonSuiteAccount;
+    const hasSuiteReceiveAccount = (suiteReceiveAccounts?.length ?? 0) > 0;
```
Comment (vytick) [inline packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts]:
```suggestion
    const hasSuiteReceiveAccount = !!suiteReceiveAccounts?.length;
```

**Review by vytick — APPROVED** [review]
just one nit, otherwise it seems to work correctly

File: packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts (hunk 1 above)
Comment (sherpaPSX) [reply packages/suite/src/hooks/wallet/trading/form/useTradingReceiveAddress.ts]: good hint. Done
