### PR TITLE
fix(suite): make sure that there is loading state when loading all tr…

### LINKED ISSUE #19623: Searching for a transaction on Solana does not load.
**Describe the bug**
Searching for a transaction on Solana does not load for pages that have not been previously loaded, meaning existing transactions cannot be found.

Image

**Info:**
 - Suite version: web 25.7.0 (3dae014934f7d785c6203f8b1e4bf7a020d24e7f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.10 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by vojtatranta**
…ansactions for the query search

## Description

There was no loading state when the search was active. The search triggers loading of all pages so there is a good chance, that the searched transaction is among pages that haven't been yet loaded.

So, I display the loading state when search is active and not all pages were yet loaded.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19623

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=19623-solana-tx-search-doesn-work&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=19623-solana-tx-search-doesn-work&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/transactions/TransactionList/TransactionList.tsx [hunk 1]
```diff
@@ -164,7 +166,8 @@ export const TransactionList = ({
             )}
 
             {/* TODO: show this skeleton also while searching in txs */}
-            {isLoading ? (
+            {isLoading ||
```
Comment (vojtatranta) [inline packages/suite/src/views/wallet/transactions/TransactionList/TransactionList.tsx:169]: Above is this condition:
`const areTransactionsAvailable = transactions.length > 0 && searchedTransactions.length === 0;`

This says that there are actually ready transactions whne there are some pages loaded and there is no search result among them.

But search naturally requests load of all pages in order to search in them. So there is a good chance, that the searched result is among pages that weren't yet loaded.

Hence I changed this logic, to show the loading state when searching is active, not all transactions are loaded and there are yet no found transactions.

**Review by seibei-iguchi — APPROVED** [review]

**Review by jvaclavik — APPROVED** [review]

**Comment by Ondra-Zik** [comment]
https://github.com/trezor/trezor-suite/issues/19623#issuecomment-3126027697
