### PR TITLE
fix(suite): polish send details

### LINKED ISSUE #10904: Empower minor issues p 1
**Describe the bug**

1. ~Press send max in `Send` dialogue before entering receive address and amount will overflow field name~ https://github.com/trezor/trezor-suite/issues/10681
2. Check explorer link icon in `Transaction list` transaction detail `Inputs, Outputs`
3. Check explorer link in transaction detail link `TX ID` section
4. in `Send transaction` dialogue "wallet" icon is not properly aligned with account name text
5. ~Not sure but it looks like circles around coin selectors in left panel looks unaligned~ Fixed

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

2.
Screenshot 2024-01-30 at 11 52 00

3.
image

4.
Screenshot 2024-01-30 at 11 50 27

### PR DESCRIPTION
**Pull request by dahaca**
## Description

* polish send details + tx details

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10904

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewSummary.tsx [hunk 1]
```diff
@@ -117,35 +116,27 @@ const RateInfo = styled.div`
...
     display: flex;
     align-items: center;
     justify-content: space-between;
-    font-size: 10px;
-    color: ${({ theme }) => theme.TYPE_LIGHT_GREY};
-    transition: background 0.1s;
-    background: ${({ theme, detailsOpen }) =>
-        detailsOpen && darken(theme.HOVER_DARKEN_FILTER, theme.STROKE_LIGHT_GREY)};
+    border-radius: ${borders.radii.xs};
+    padding: 4px 4px 4px 8px;
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewSummary.tsx]: nit: use `spacingsPx` please

**Review by peter-sanderson — APPROVED** [review]
