### PR TITLE
fix(trade): last transactions design

### LINKED ISSUE #15501: Trade - Last transactions design bugs
## Description
- an alignment of payment status
- an alignment of payment methods and provider
- a transaction margin

## Screenshots
image

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
- fix alignment of payment status
- fix alignment of payment methods and provider
- fix transaction margin

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/15501

### Before
image

### After 
image

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketPaymentType.tsx [hunk 1]
```diff
@@ -12,7 +12,13 @@ interface CoinmarketPaymentTypeProps {
 
 export const CoinmarketPaymentType = ({ method, methodName }: CoinmarketPaymentTypeProps) => (
     <Row gap={spacings.xs}>
-        {method && <img width="24px" src={invityAPI.getPaymentMethodUrl(method)} alt="" />}
+        {method && (
+            <Image
+                imageSrc={invityAPI.getPaymentMethodUrl(method)}
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketPaymentType.tsx]: Would it be hard to introduce something that it would also look good in darkmode?

Comment (tomasklim) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketPaymentType.tsx]: Venmo and credit card is almost invisible.

Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketPaymentType.tsx]: Added a white box.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketProviderInfo.tsx [hunk 2]
```diff
@@ -19,19 +21,18 @@ export const CoinmarketProviderInfo = ({ exchange, providers }: CoinmarketProvid
...
-                            src={invityAPI.getProviderLogoUrl(provider.logo)}
-                            alt=""
-                        />
+                        <CoinmarketIcon iconUrl={invityAPI.getProviderLogoUrl(provider.logo)} />
                     )}
-                    {provider.brandName || provider.companyName}
+                    {provider.brandName ?? provider.companyName}
                 </>
+            ) : (
+                <Row margin={{ left: spacings.xl }}>
```
Comment (seibei-iguchi) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketProviderInfo.tsx]: Why the margins on both Row and Text? Why not use the gap on the parent Row?

Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketProviderInfo.tsx]: This margin is the same as the width of a missing icon. With a gap, it would not work. I guess.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+    border-radius: ${borders.radii.xxs};
+`;
+
+interface CoinmarketIconProps {
+    iconUrl: string;
+}
+
+export const CoinmarketIcon = ({ iconUrl }: CoinmarketIconProps) => {
+    const currentTheme = useSelector(state => state.suite.settings.theme.variant);
+    const iconWrapperSize = iconSizes.mediumLarge + 4;
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx]: what is this magical number 4? :D Maybe it's easier to set iconWrapperSize manually like: 

```
const ICON_WRAPPER_SIZE = 123
```

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx [hunk 4]
```diff
@@ -0,0 +1,33 @@
+import styled from 'styled-components';
+
+import { iconSizes, Image, Row } from '@trezor/components';
+import { borders } from '@trezor/theme';
+
+import { useSelector } from 'src/hooks/suite';
+
+const CoinmarketIconWrapper = styled.div<{ $isDark: boolean }>`
+    ${({ $isDark }) => $isDark && `background-color: #fff;`}
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx:9]: It's just my opinion, but I would suggest to overlay colors of all these transparent pngs. It would be much more consistent with Suite design.

Something like:

```css
img {
  filter: brightness(0) invert(1);
}
```

or another solution like this one: https://bdwm.be/css-change-a-transparent-png-to-any-color-you-want/

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionContainer.tsx [hunk 5]
```diff
@@ -16,10 +16,10 @@ export const CoinmarketTransactionContainer = ({
     const isMobile = useMediaQuery(`(max-width: ${variables.SCREEN_SIZE.SM})`);
 
     return (
-        <Card fillType="none">
+        <Card fillType="none" margin={{ bottom: spacings.lg }}>
             <Row flexWrap={isBelowDesktop ? 'wrap' : undefined}>
                 <Column
-                    alignItems="flex-start"
+                    alignItems="stretch"
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionContainer.tsx]: You can delete `alignItems` here. Yesterday we switched `Column` default value to `normal` which is basically the same like `stretch`.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx [hunk 6]
```diff
@@ -27,8 +27,10 @@ export const CoinmarketTransactionInfo = ({ trade }: CoinmarketTransactionInfoPr
 
     return (
         <Text margin={{ top: spacings.xs }} variant="tertiary" typographyStyle="label" as="div">
-            {tradeType} • <FormattedDate value={date} date time /> •{' '}
-            <CoinmarketTransactionStatus trade={trade} />
+            <Row alignItems="center" flexWrap="wrap">
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx]: `alignItems="center"` for `Row` is the default value, so you can delete this prop

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx [hunk 7]
```diff
@@ -27,8 +27,10 @@ export const CoinmarketTransactionInfo = ({ trade }: CoinmarketTransactionInfoPr
...
+                {tradeType} • <FormattedDate value={date} date time /> •{' '}
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx]: Please use new `InfoPair` component here 🙏

See here: https://dev.suite.sldev.cz/components/develop/?path=/story/infopair--info-pair

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx (hunk 4 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx:9]: We do not want to change the partner's logos.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx (hunk 3 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx]: It is total padding in the wrapper. (2px left - `mediumLarge` size of image - 2px right)

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketProviderInfo.tsx (hunk 2 above)
Comment (jvaclavik) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketProviderInfo.tsx]: And why not have it in `Text` without `Row`?

Like:

```tsx
<Text margin={{ left: spacings.xxl }}>{exchange}</Text>
```

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx (hunk 3 above)
Comment (jvaclavik) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx]: OK, then I suggest to use it this way:

```ts
const iconWrapperSize = iconSizes.mediumLarge + 2 * SIDE_PADDING;
```

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx (hunk 7 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx]: It would be lovely to have it dynamic, not only to the left and right parts. :) But it is nice anyway.

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketProviderInfo.tsx (hunk 2 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketProviderInfo.tsx]: Yes, that's possible!

**Comment by adderpositive** [comment]
@jvaclavik fixes are in this commit [5138fd1](https://github.com/trezor/trezor-suite/pull/15502/commits/5138fd11ea7b67beab2fd5bdf528b25ea24de6cf). I needed to rebase to use features according to your feedback. Thanks for your review

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx (hunk 7 above)
Comment (jvaclavik) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx]: We hear you :D 

Please wait for merging [this](https://github.com/trezor/trezor-suite/pull/15627) (should be soon) and refactor it to `InfoSegments`

Comment (jvaclavik) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx]: It's merged

Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactions/CoinmarketTransaction/CoinmarketTransactionInfo.tsx]: Updated

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+`;
+
+interface CoinmarketIconProps {
+    iconUrl: string;
+}
+
+export const CoinmarketIcon = ({ iconUrl }: CoinmarketIconProps) => {
+    const currentTheme = useSelector(state => state.suite.settings.theme.variant);
+    const SIDE_PADDING = 2;
+    const iconWrapperSize = iconSizes.mediumLarge + 2 * SIDE_PADDING;
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx]: Ideally these two could be extracted to top level. not to have it directly in `CoinmarketIcon` component (it's rerendering)

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+
+    return (
+        <CoinmarketIconWrapper $isDark={currentTheme === 'dark'}>
+            <Row
```
Comment (jvaclavik) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx]: Why do you need `Row` here if there is only one element?

You can use new component `Box` for this use case. It's an universal building block with many styling props.

**Review by jvaclavik — COMMENTED** [review]
Two last comments and ready to merge 💪

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx (hunk 9 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketIcon.tsx]: 😁 updated in [83d97a7](https://github.com/trezor/trezor-suite/pull/15502/commits/83d97a7bd066127d942f72cfece93d1838599412)

**Review by tomasklim — APPROVED** [review]
