### PR TITLE
fix(suite): remove sticky positioning from transaction headers

### LINKED ISSUE #23073: Transaction history UI overlapping in several cases
**Describe the bug**
Transaction history UI elements overlap in several situations, making the transaction list unclear or unreadable. 

**Screenshots**
Transaction history overlap 1
Transaction history overlap 2

### PR DESCRIPTION
**Pull request by seibei-iguchi**
🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/transaction-header&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/transaction-header&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/transactions/TransactionList/TransactionsGroup/TransactionsGroup.tsx [hunk 1]
```diff
@@ -14,24 +14,14 @@ import {
...
-
-    & + & {
-        margin-top: 36px;
-    }
-
-    > * + * {
-        margin-top: 8px;
-    }
-`;
+const TransactionsGroupWrapper = styled.div``;
```
Comment (Lemonexe) [inline packages/suite/src/views/wallet/transactions/TransactionList/TransactionsGroup/TransactionsGroup.tsx:24]: redundant, div can be used directly. Or maybe rather `Box`, whatever you prefer

**Comment by Lemonexe** [comment]
So this is the bug you're solving?
image

**Review by Lemonexe — APPROVED** [review]
LGTM, bug mentioned above ↑
seems to be fixed

Image
