### PR TITLE
fix(suite): Update breakpoint for welcome screen

### LINKED ISSUE #17531: Improve welcome screen break point to match the new layout well
Please change the breakpoint so it breaks only if the contents don't fit the right frame anymore (now it breaks earlier than that unnecessarily).

Image

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/17531

## Screenshots:

before
Image

after

https://github.com/user-attachments/assets/05753979-8697-4743-96b4-5b0b9cdc6037

### CODE REVIEW

File: packages/suite/src/components/suite/SecurityCheck/SecurityCheckLayout.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ const Wrapper = styled.div`
     gap: 24px;
     width: 100%;
 
-    @media only screen and (max-width: ${variables.SCREEN_SIZE.XL}) {
+    @media only screen and (max-width: ${variables.SCREEN_SIZE.MD}) {
```
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/SecurityCheck/SecurityCheckLayout.tsx]: Is it possible to use non legacy breakpoint?

Comment (jvaclavik) [reply packages/suite/src/components/suite/SecurityCheck/SecurityCheckLayout.tsx]: Done

**Review by seibei-iguchi — APPROVED** [review]

**Review by vojtatranta — APPROVED** [review]
magnifique

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 25.4.0 (e5ccc0c45bf1c935d6c0c030e02452d2cacf234a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3B1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: WebUsbTransport
