### PR TITLE
fix(suite): include ADA staking balance check in active staking analytics

### LINKED ISSUE #21908: Data analytics: add staking info into existing events
We're currently tracking amounts of discovered networks as a part of [accounts/non-zero-balance](https://www.notion.so/satoshilabs/accounts-non-zero-balance-a5f533a3b2dd415ba066988a8630e2c3) and [accounts/status](https://www.notion.so/satoshilabs/accounts-status-de19c2a833cb49eeb195cf14cff96ba6) events.
Since we're currently offering staking on some assets, it would be beneficial to know accounts which have anything staked. Due to this fact this issue is about proposing to add a new event along those two existing ones.

**Event name**: `accounts/active-staking`
**Triggered when**: Discovery of all accounts is completed.
**Attribute**: `{token}_{networkSymbol}_{accountType}: number`

### PR DESCRIPTION
**Pull request by izmy**
## Description

Added missing staking balance check for Cardano accounts in accounts/active-staking analytics.
Now ADA staking accounts are correctly included in the event payload.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21908

## Screenshots:

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/data-analytics-active-staking-cardano&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/data-analytics-active-staking-cardano&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/data-analytics-active-staking-cardano&lookback=7)

### CODE REVIEW

**Review by matusbalascak — APPROVED** [review]

File: suite-common/wallet-utils/src/stakingUtils.ts [hunk 1]
```diff
@@ -41,6 +44,8 @@ export const getAccountTotalStakingBalance = (account: Account) => {
             return getEthAccountTotalStakingBalance(account);
         case 'solana':
             return getSolAccountTotalStakingBalance(account);
+        case 'cardano':
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/stakingUtils.ts:47]: @izmy can we reuse some staking type which says that there is staking on specific network? so that we do not miss it next time? Thanks

Comment (tomasklim) [reply suite-common/wallet-utils/src/stakingUtils.ts:47]: Maybe StakingNetworkSymbol but extend it by cardano 😀

Comment (tomasklim) [reply suite-common/wallet-utils/src/stakingUtils.ts:47]: Quickly check other staking methods if they should have same typecheck. Thank you (e.g. getStakingDataForNetwork)

Comment (izmy) [reply suite-common/wallet-utils/src/stakingUtils.ts:47]: https://github.com/trezor/trezor-suite/pull/22734
