### PR TITLE
EVM NFT section 

### LINKED ISSUE #8004: NFTs section
Screenshot 2024-06-11 at 17 15 36

**Describe the bug**
- ERC721, ERC1155 are filtered out so they do not arrive to Suite UI (not sure where)

**Expected behavior**
I will see NFTs in Suite. I want to be able to filter by ERC721 and ERC1155. Rabby does not distinguish
Screenshot 2024-05-02 at 12 24 06

**What we get from BlockBook:**

**ERC1155**
```
{
  "type": "ERC1155",
  "name": "Airdrop at linkredeem.io",
  "contract": "0x43721eF8de94FD33E23eE267546d67CeFdB1968C",
  "transfers": 1,
  "symbol": "NFT",
  "decimals": 18,
  "multiTokenValues": [
    {
      "id": "1",
      "value": "1"
    }
  ]
}
```
Link to BlockBook: `https://matic1.trezor.io/nft/0x43721eF8de94FD33E23eE267546d67CeFdB1968C/1`

What is interesting for us?
`type` (ERC-1155)
`name` (Collection)
`symbol`
`contract address`
`ID` (id of NFT, number)
`amount` (how many of specific NFT with specific ID I have)
`number of transfers`

**ERC721:**
```
{
  "type": "ERC721",
  "name": "AstronomiaMeta",
  "contract": "0x23A864B6bB94518B0FA41d17f8f52ea38A826457",
  "transfers": 1,
  "symbol": "AstronomiaMeta",
  "decimals": 18,
  "ids": [
    "95729"
  ]
}
```
Link to BlockBook: `https://eth1.trezor.io/nft/0x8506540784ec25A19aB750741A4AB1b6D8790e2c/1`

What is interesting for us?
`type` (ERC-720)
`name` (Collection)
`symbol`
`contract address`
`ID` (id of NFT, number, there is always just 1 unique)
`number of transfers`

Icon for recognised NFTs can be fetched from coingecko. It is not circle but square
Screenshot 2024-05-02 at 12 22 27

User can have more NFTs from same collection. Do we want to put collections together or just have it as a new token?
`type` (ERC-720)
`name` (Collection)
`symbol`
`contract address`
`number of transfers`
+ icon

is for collection.

`ID` (id of NFT, number)
`amount` (how many of specific NFT with specific ID I have)

for item

### LINKED ISSUE #12165: EVM tokens
[Design](https://www.figma.com/design/o6eb4wUMjSu5xMb34423vh/Tokens?node-id=4084%3A8416&t=xXUHelGSSoAKr65m-1)

```[tasklist]
### Release 24.12
- [ ] #15939
- [ ] https://github.com/trezor/trezor-suite/issues/8004
- [x] https://github.com/trezor/trezor-suite/issues/8036
- [x] https://github.com/trezor/trezor-suite/issues/13749
```

```[tasklist]
### Release 24.11
- [x] #14611
- [x] https://github.com/trezor/trezor-suite/issues/14985
- [x] https://github.com/trezor/trezor-suite/issues/13142
- [x] #14456
- [x] https://github.com/trezor/trezor-suite/issues/13152
```

```[tasklist]
### Release 24.10
- [x] https://github.com/trezor/trezor-suite/issues/12822
```

```[tasklist]
### Release 24.9
- [x] https://github.com/trezor/trezor-suite/issues/13503
- [x] https://github.com/trezor/trezor-suite/issues/12825
```

```[tasklist]
### Release 24.8
- [x] https://github.com/trezor/trezor-suite/issues/13528
- [x] https://github.com/trezor/trezor-suite/issues/13338
- [x] https://github.com/trezor/trezor-suite/issues/13322
- [x] https://github.com/trezor/trezor-suite/issues/3544
- [x] #13336
- [x] #13337
- [x] https://github.com/trezor/trezor-suite/issues/13039
```

```[tasklist]
### Release 24.7
- [x] https://github.com/trezor/trezor-suite/issues/12810
- [x] https://github.com/trezor/trezor-suite/issues/12811
- [x] https://github.com/trezor/trezor-suite/issues/12812
- [x] https://github.com/trezor/trezor-suite/issues/12841
- [x] https://github.com/trezor/trezor-suite/issues/12823
- [x] https://github.com/trezor/trezor-suite/issues/12845
- [x] https://github.com/trezor/trezor-suite/issues/12860
- [x] https://github.com/trezor/trezor-suite/issues/12905
- [x] https://github.com/trezor/trezor-suite/issues/12906
- [x] https://github.com/trezor/trezor-suite/issues/12908
- [x] https://github.com/trezor/trezor-suite/issues/12909
- [x] https://github.com/trezor/trezor-suite/issues/12842
- [x] https://github.com/trezor/trezor-suite/issues/12846
- [x] https://github.com/trezor/trezor-suite/issues/12907
- [x] https://github.com/trezor/trezor-suite/issues/12820
- [x] https://github.com/trezor/trezor-suite/issues/12826
- [x] https://github.com/trezor/trezor-suite/issues/12862
- [x] https://github.com/trezor/trezor-suite/issues/12910
- [x] https://github.com/trezor/trezor-suite/issues/12840
- [x] https://github.com/trezor/trezor-suite/issues/12864
```

### PR DESCRIPTION
**Pull request by enjojoy**
## Description
NFT section is introduced for EVM based chains, enabled through experimental features. Supportes NFTs are ERC721 and ERC1155.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/8004
Resolve  #12165 (last issue)

## Screenshots:

In experimental features:

image

Screenshot 2024-12-16 at 13 58 36

Screenshot 2024-12-16 at 13 59 57
Screenshot 2024-12-16 at 14 00 18
Screenshot 2024-12-16 at 14 00 41
Screenshot 2024-12-19 at 18 49 35
Screenshot 2024-12-19 at 18 50 08
Screenshot 2024-12-19 at 18 50 39
Screenshot 2024-12-19 at 18 51 01

### CODE REVIEW

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+                                <Translation id="TR_COLLECTION" />
+                            </Table.Cell>
+                            {type === 'ERC1155' && (
+                                <>
+                                    <Table.Cell colSpan={1}>
+                                        <Translation id="TR_ID" />
+                                    </Table.Cell>
+
+                                    <Table.Cell colSpan={1}>
+                                        <Translation id="AMOUNT" />
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: Quantity would be better imo

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+                <Table>
+                    <Table.Header>
+                        <Table.Row>
+                            <Table.Cell colSpan={1}>
+                                <Translation id="TR_COLLECTION" />
+                            </Table.Cell>
+                            {type === 'ERC1155' && (
+                                <>
+                                    <Table.Cell colSpan={1}>
+                                        <Translation id="TR_ID" />
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: Token ID

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+                                    </Table.Cell>
+
+                                    <Table.Cell colSpan={1}>
+                                        <Translation id="AMOUNT" />
+                                    </Table.Cell>
+                                </>
+                            )}
+                            {type === 'ERC721' && (
+                                <Table.Cell colSpan={9}>
+                                    <Translation id="TR_TOKENS" />
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: This is also Token ID right?

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+
+    return (
+        <Column width="100%" alignItems="start" gap={12}>
+            <H3>{type}</H3>
+            <Card paddingType="none" overflow="hidden">
+                <Table>
+                    <Table.Header>
+                        <Table.Row>
+                            <Table.Cell colSpan={1}>
+                                <Translation id="TR_COLLECTION" />
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: Collection name

I would not shorten name of Collection + please use BlurUrls
Screenshot 2024-11-23 at 18 09 38

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+
+import NftsRow from './NftsRow';
+import { filterNftTokens } from '@suite-common/wallet-utils';
+import { Token } from '@trezor/blockchain-link-types/src/blockbook-api';
+import { getNetwork } from '@suite-common/wallet-config';
+
+type NftsTableProps = {
+    selectedAccount: SelectedAccountLoaded;
+    searchQuery: string;
+    type: 'ERC721' | 'ERC1155';
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: Please try to reuse `TokenStandard` if possible or introduce some subset

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+        }
+
+        return verified ? nfts.hiddenVerified : nfts.hiddenUnverified;
+    };
+
+    const nftsToShow = getNftsToShow();
+    const filteredNfts = filterNftsByType(nftsToShow);
+
+    if (filteredNfts.length === 0) {
+        return null;
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: There should be some empty state component as there is for Tokens

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 7]
```diff
@@ -29,6 +30,7 @@ import { FiatCurrencyCode } from '@suite-common/suite-config';
 import { formatAmount, formatNetworkAmount, isTokenMatchesSearch } from './accountUtils';
 import { toFiatCurrency } from '../src/fiatConverterUtils';
 import { getFiatRateKey, roundTimestampToNearestPastHour } from './fiatRatesUtils';
+import { Token } from '@trezor/blockchain-link-types/src/blockbook-api';
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts]: This is not correct import. However, TokenInfo should be enough or not?

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 8]
```diff
@@ -1177,3 +1178,15 @@ export const isTokenMatchesSearch = (token: TokenInfo, search: string) => {
         token.policyId?.toLowerCase().includes(search)
     );
 };
+
+export const isNftMatchesSearch = (token: Token, search: string) => {
+    return (
+        token.symbol?.toLowerCase().includes(search) ||
+        token.name?.toLowerCase().includes(search) ||
+        token.contract?.toLowerCase().includes(search) ||
+        token.ids
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: not sure if it makes sense?

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 9]
```diff
@@ -1177,3 +1178,15 @@ export const isTokenMatchesSearch = (token: TokenInfo, search: string) => {
         token.policyId?.toLowerCase().includes(search)
     );
 };
+
+export const isNftMatchesSearch = (token: Token, search: string) => {
+    return (
+        token.symbol?.toLowerCase().includes(search) ||
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts:1196]: TODO note for myself: our symbol is kinda handicaped by shortening in blockchain-link, we should check that, it breaks searching because there are `...`

File: packages/suite/src/views/wallet/nfts/index.tsx [hunk 10]
```diff
@@ -0,0 +1,51 @@
...
+    const [searchQuery, setSearchQuery] = useState('');
+
+    const { selectedAccount } = useSelector(state => state.wallet);
+
+    const dispatch = useDispatch();
+
+    useEffect(() => {
+        if (
+            selectedAccount.status === 'loaded' &&
+            !selectedAccount.network?.features.includes('tokens')
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/index.tsx]: you should introduce `nfts` in networksConfig into features

File: packages/suite/src/views/wallet/nfts/ShownNfts.tsx [hunk 11]
```diff
@@ -0,0 +1,32 @@
...
+                searchQuery={searchQuery}
+                type="ERC1155"
+                shown={true}
+                verified
+            />
+        </Column>
+    );
+};
+
+export default ShownNfts;
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/ShownNfts.tsx]: we dont use `default` exports in the project

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 12]
```diff
@@ -0,0 +1,227 @@
...
+            <Table.Cell colSpan={1}>
+                <TruncateWithTooltip>{name}</TruncateWithTooltip>
+            </Table.Cell>
+            {type === 'ERC1155' && (
+                <>
+                    <Table.Cell colSpan={1}>
+                        <Column alignItems="flex-start">
+                            {nft.multiTokenValues?.map(value => (
+                                <Row key={value.id?.toString()}>
+                                    <Link
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: TODO: Please check if we can use `<Link...` in Suite, it ignores tor I think. I guess `<TrezorLink...` should be used everywhere

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 13]
```diff
@@ -0,0 +1,227 @@
...
+                                        {value.id?.toString()}
+                                    </Link>
+                                </Row>
+                            ))}
+                        </Column>
+                    </Table.Cell>
+                    <Table.Cell colSpan={1}>
+                        <Column alignItems="flex-start">
+                            {nft.multiTokenValues?.map(value => (
+                                <Row key={value.value?.toString()}>{value.value?.toString()}</Row>
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: hidden placeholders missing for ID and quantity

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 14]
```diff
@@ -0,0 +1,227 @@
...
+    margin-left: ${spacingsPx.xxs};
+`;
+
+const NftsRow = ({ nft, type, network, shown }: NftsRowProps) => {
+    const dispatch = useDispatch();
+
+    const { translationString } = useTranslation();
+    const shouldShowCopyAddressModal = useSelector(selectIsCopyAddressModalShown);
+
+    const getNftContractExplorerUrl = (network: Network, nft: Token) => {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: does this differ from `getTokenExplorerUrl`?

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 15]
```diff
@@ -0,0 +1,227 @@
...
+        const explorerUrl = network.explorer.account;
+        const contractAddress = nft.contract;
+        const queryString = network.explorer.queryString ?? '';
+
+        return `${explorerUrl}${contractAddress}${queryString}`;
+    };
+
+    const getNftExplorerUrl = (network: Network, nft: Token, id?: string) => {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: move to `wallet-utils`

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 16]
```diff
@@ -0,0 +1,227 @@
...
+                                                getNftContractExplorerUrl(network, nft),
+                                                '_blank',
+                                            );
+                                        },
+                                    },
+                                ],
+                            },
+                            {
+                                key: 'contract-address',
+                                label: translationString('TR_CONTRACT_ADDRESS'),
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: why `translationString`

File: packages/suite/src/views/wallet/nfts/ShownNfts.tsx [hunk 17]
```diff
@@ -0,0 +1,32 @@
...
+};
+
+const ShownNfts = ({ selectedAccount, searchQuery }: ShownNftsProps) => {
+    return (
+        <Column gap={24}>
+            <NftsTable
+                selectedAccount={selectedAccount}
+                searchQuery={searchQuery}
+                type="ERC721"
+                shown={true}
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/ShownNfts.tsx]:
```suggestion
                isShown={true}
```
Maybe also something like `isVerifiedTokenSection`, `isShownTokenSection` would be more understandable

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 18]
```diff
@@ -0,0 +1,227 @@
...
+    word-break: break-all;
+    white-space: wrap;
+`;
+
+const IconWrapper = styled.div`
+    display: inline-block;
+    margin-left: ${spacingsPx.xxs};
+`;
+
+const NftsRow = ({ nft, type, network, shown }: NftsRowProps) => {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Most of the logic is copy/paste of TokenRow, would it be possible to unify it?

File: packages/suite/src/views/wallet/nfts/NftsNavigation.tsx [hunk 19]
```diff
@@ -0,0 +1,87 @@
...
+import { SearchAction } from 'src/components/wallet/SearchAction';
+import { filterNftTokens } from '@suite-common/wallet-utils';
+
+interface NftsNavigationProps {
+    selectedAccount: SelectedAccountLoaded;
+    searchQuery: string;
+    setSearchQuery: Dispatch<SetStateAction<string>>;
+}
+
+export const NftsNavigation = ({
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/NftsNavigation.tsx]: Most of the logic is copy/paste of TokensNavigation, would it be possible to unify it?

File: packages/suite/src/utils/wallet/nftUtils.ts [hunk 20]
```diff
@@ -0,0 +1,60 @@
...
+type GetNfts = {
+    tokens: Token[];
+    symbol: NetworkSymbol;
+    nftDefinitions?: TokenDefinition;
+    searchQuery?: string;
+};
+
+export type NftType = 'ERC721' | 'ERC1155';
+
+export const getNfts = ({ tokens, symbol, nftDefinitions, searchQuery }: GetNfts) => {
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/nftUtils.ts]: Looks like getTokens, would it be possible to unify it?

File: packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx [hunk 21]
```diff
@@ -54,6 +56,16 @@ export const AccountNavigation = () => {
             activeRoutes: ['wallet-tokens', 'wallet-tokens-hidden'],
             'data-testid': '@wallet/menu/wallet-tokens',
         },
+        {
+            id: 'wallet-nfts',
+            callback: () => {
+                goToWithAnalytics('wallet-nfts', { preserveParams: true });
+            },
+            title: <Translation id="TR_NAV_NFTS" />,
+            isHidden: !['ethereum'].includes(networkType),
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx]: would make sense to use `getNetworkFeatures(symbol).includes('nft-definitions');`

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Review by tomasklim — DISMISSED** [review]
I understand that this is just a PR draft, but I would like to avoid duplicating code and making additional changes later.

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx (hunk 1 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: Amount is used in txs overview, why would it be different here? I think Amount makes sense and it means the same thing as quantity. Also the word quantity has never been used in suite, I would leave it as amount.

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 14 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Yes it's different

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 16 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Looks like no reason, will use a normal translation component

File: packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx (hunk 21 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx]: yes but now there is be "nft" in features, will use that

**Comment by enjojoy** [comment]
> I understand that this is just a PR draft, but I would like to avoid duplicating code and making additional changes later.

I appreciate this approach

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 18 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: I agree that some logic is similar, I'm not sure if it should be unified, I will think about it. 

The table has a completely different structure and I can imagine that in the future we might want to change it to display pictures etc... For now I would leave it separate to not bloat a component with logic and to not compromise on readability, but I will keep thinking about it

File: packages/suite/src/views/wallet/nfts/NftsNavigation.tsx (hunk 19 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsNavigation.tsx]: Yes,  I agree, I unified it

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: > Also the word quantity has never been used in suite, I would leave it as amount.

because we did not have NFTs before 😀 

The difference between amount and quantity (how I feel it)
Amount is something divisible, you can have 1.5 ETH, you can have fractions,..
Quantity for me represents discrete, countable units. I have 3x NFT of ID 5. I cant have 2.5 NFT

btw etherscan:
https://etherscan.io/nft/0x177af8c5c96373cb727b8636b331785f49ba24e2/17
Screenshot 2024-12-03 at 19 47 30

Comment (tomasklim) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: > Amount is used in txs overview, why would it be different here?

Nobody ever cared about doing NFTs in tx overview nice. Now we start to care, so I think it is not good argument

Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsTable.tsx]: Ok, makes sense

File: suite-common/wallet-config/src/networksConfig.ts [hunk 22]
```diff
@@ -177,7 +178,7 @@ export const networks = {
             nft: 'https://op1.trezor.io/nft/',
             address: 'https://op1.trezor.io/address/',
         },
-        features: ['rbf', 'sign-verify', 'tokens', 'coin-definitions', 'nft-definitions'],
+        features: ['rbf', 'sign-verify', 'tokens', 'nft', 'coin-definitions', 'nft-definitions'],
```
Comment (tomasklim) [inline suite-common/wallet-config/src/networksConfig.ts]: plus sepolia and holesky

Comment (tomasklim) [reply suite-common/wallet-config/src/networksConfig.ts]: not sure about etc, please check

File: packages/suite/src/utils/wallet/nftUtils.ts (hunk 20 above)
Comment (enjojoy) [reply packages/suite/src/utils/wallet/nftUtils.ts]: unified

File: packages/blockchain-link-types/src/common.ts [hunk 23]
```diff
@@ -188,6 +189,10 @@ export interface TokenInfo {
     accounts?: TokenAccount[]; // token accounts for solana
     policyId?: string; // Cardano policy id
     fingerprint?: string; // Cardano starting with "asset"
+    multiTokenValues?: MultiTokenValue[];
+    ids?: string[];
+    totalReceived?: string;
+    totalSent?: string;
```
Comment (tomasklim) [inline packages/blockchain-link-types/src/common.ts]: this is never used, so please remove it

File: packages/blockchain-link-types/src/common.ts [hunk 24]
```diff
@@ -188,6 +189,10 @@ export interface TokenInfo {
     accounts?: TokenAccount[]; // token accounts for solana
     policyId?: string; // Cardano policy id
     fingerprint?: string; // Cardano starting with "asset"
+    multiTokenValues?: MultiTokenValue[];
```
Comment (tomasklim) [inline packages/blockchain-link-types/src/common.ts]: Can you instead do 

```
 & Optional<Pick<BlockbookToken, 'multiTokenValues' | 'ids'>>;
```

File: suite-common/wallet-utils/src/tokenUtils.ts [hunk 25]
```diff
@@ -35,3 +35,10 @@ export const getTokenExplorerUrl = (
 
     return `${explorerUrl}${contractAddress}${queryString}`;
 };
+
+export const getNftExplorerUrl = (network: Network, nft: TokenInfo, id?: string) => {
+    const explorerUrl = network.explorer.nft;
+    const contractAddressWithId = nft.contract + `/${id}`;
+
+    return `${explorerUrl}${contractAddressWithId}`;
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/tokenUtils.ts]:
```suggestion
    return `${explorerUrl}${contractAddressWithId}${queryString}`;
```

just in case we add solana one day

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 26]
```diff
@@ -1182,3 +1182,16 @@ export const isTokenMatchesSearch = (token: TokenInfo, search: string) => {
         token.policyId?.toLowerCase().includes(search)
     );
 };
+
+export const isNftMatchesSearch = (token: TokenInfo, search: string) => {
+    return (
+        token.symbol?.toLowerCase().includes(search) ||
+        token.name?.toLowerCase().includes(search) ||
+        token.contract?.toLowerCase().includes(search) ||
+        token.ids
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: I would not search using IDs and multitokenvalues

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx [hunk 27]
```diff
@@ -19,28 +19,33 @@ interface TokensNavigationProps {
...
 export const TokensNavigation = ({
     selectedAccount,
     searchQuery,
     setSearchQuery,
+    isNft = false,
 }: TokensNavigationProps) => {
     const { account } = selectedAccount;
     const [isExpanded, setExpanded] = useState(false);
     const routeName = useSelector(selectRouteName);
     const coinDefinitions = useSelector(state =>
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: but now it is not `coinDefinitions` anymore

just use `tokenDefinitions` and its ok

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx [hunk 28]
```diff
@@ -65,17 +70,25 @@ export const TokensNavigation = ({
...
                 <SubTabs.Item
-                    id="wallet-tokens"
+                    id={isNft ? 'wallet-nfts' : 'wallet-tokens'}
                     iconName="tokens"
-                    onClick={goToRoute('wallet-tokens')}
-                    count={tokens.shownWithBalance.length}
+                    onClick={goToRoute(isNft ? 'wallet-nfts' : 'wallet-tokens')}
+                    count={
+                        isNft
+                            ? tokens.shownWithBalance.length + tokens.shownWithoutBalance.length
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: why both?

Comment (tomasklim) [reply packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: how does it behave when you send nft out of account? is it in data with quantity 0?

you can use rabby to send nft away

File: packages/suite/src/views/wallet/send/Outputs/TokenSelect/TokenSelect.tsx [hunk 29]
```diff
@@ -86,7 +86,11 @@ const buildTokenOptions = (
     }
 
     if (accountTokens) {
-        const tokens = getTokens(accountTokens, symbol, coinDefinitions);
+        const tokens = getTokens({
+            tokens: accountTokens,
+            symbol,
+            tokenDefinitions: coinDefinitions,
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/Outputs/TokenSelect/TokenSelect.tsx:92]: rename to tokenDefintiions

File: packages/suite/src/views/wallet/nfts/index.tsx [hunk 30]
```diff
@@ -0,0 +1,59 @@
...
+import { useDispatch, useSelector } from 'src/hooks/suite';
+import { goto } from 'src/actions/suite/routerActions';
+
+import { TokensNavigation } from '../tokens/TokensNavigation';
+import { NftsTablesSection } from './NftsTablesSection';
+
+export const Nfts = () => {
+    const [searchQuery, setSearchQuery] = useState('');
+
+    const { selectedAccount } = useSelector(state => state.wallet);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/nfts/index.tsx]:
```suggestion
    const selectedAccount = useSelector(state => state.wallet.selectedAccount);
```

optimisation?

File: packages/suite/src/support/messages.ts [hunk 31]
```diff
@@ -5294,18 +5324,42 @@ export default defineMessages({
         id: 'TR_TOKENS',
         defaultMessage: 'Tokens',
     },
+    TR_COLLECTION_NAME: {
+        id: 'TR_COLLECTION_NAME',
+        defaultMessage: 'Collection name',
+    },
+    TR_ID: {
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: is used?

File: packages/suite/src/support/messages.ts [hunk 32]
```diff
@@ -5294,18 +5324,42 @@ export default defineMessages({
...
+        id: 'TR_ID',
+        defaultMessage: 'ID',
+    },
+    TR_NFT: {
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: is used? should be used?

File: packages/suite/src/views/wallet/nfts/index.tsx (hunk 30 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/index.tsx]: that's a great  catch

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx (hunk 28 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: this was caused by a mistake in getTokens, fixed now

File: packages/blockchain-link-types/src/common.ts (hunk 24 above)
Comment (enjojoy) [reply packages/blockchain-link-types/src/common.ts]: A lil different, but yes it's a nice idea

export interface TokenInfo extends Partial<Pick<Token, 'multiTokenValues' | 'ids'>> {

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx [hunk 33]
```diff
@@ -65,17 +70,21 @@ export const TokensNavigation = ({
...
+                    )}
                 </SubTabs.Item>
                 <SubTabs.Item
-                    id="wallet-tokens-hidden"
+                    id={isNft ? 'wallet-nfts-hidden' : 'wallet-tokens-hidden'}
                     iconName="hide"
-                    onClick={goToRoute('wallet-tokens-hidden')}
+                    onClick={goToRoute(isNft ? 'wallet-nfts-hidden' : 'wallet-tokens-hidden')}
                     count={tokens.hiddenWithBalance.length}
                 >
```
Comment (izmy) [inline packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: There are a lot of conditions... how about something like this?

```
    const nftSubTabs = (
        <SubTabs activeItemId={routeName} size="medium">
            <SubTabs.Item
                id="wallet-nfts"
                iconName="pictureFrame"
                onClick={goToRoute('wallet-nfts')}
                count={tokens.shownWithBalance.length}
            >
                <Translation id="TR_NAV_COLLECTIONS" />
            </SubTabs.Item>
            <SubTabs.Item
                id="wallet-nfts-hidden"
                iconName="hide"
                onClick={goToRoute('wallet-nfts-hidden')}
                count={tokens.hiddenWithBalance.length}
            >
                <Translation id="TR_HIDDEN" />
            </SubTabs.Item>
        </SubTabs>
    );

    const tokenSubTabs = (
        <SubTabs activeItemId={routeName} size="medium">
            <SubTabs.Item
                id="wallet-tokens"
                iconName="tokens"
                onClick={goToRoute('wallet-tokens')}
                count={tokens.shownWithBalance.length}
            >
                <Translation id="TR_NAV_TOKENS" />
            </SubTabs.Item>
            <SubTabs.Item
                id="wallet-tokens-hidden"
                iconName="hide"
                onClick={goToRoute('wallet-tokens-hidden')}
                count={tokens.hiddenWithBalance.length}
            >
                <Translation id="TR_HIDDEN" />
            </SubTabs.Item>
        </SubTabs>
    );

...

return (
        <Row alignItems="center" justifyContent="space-between">
            {isNft ? nftSubTabs : tokenSubTabs}
```

File: suite-common/wallet-utils/src/tokenUtils.ts [hunk 34]
```diff
@@ -35,3 +35,11 @@ export const getTokenExplorerUrl = (
 
     return `${explorerUrl}${contractAddress}${queryString}`;
 };
+
+export const getNftExplorerUrl = (network: Network, nft: TokenInfo, id?: string) => {
+    const explorerUrl = network.explorer.nft;
+    const contractAddressWithId = nft.contract + `/${id}`;
```
Comment (izmy) [inline suite-common/wallet-utils/src/tokenUtils.ts:41]: if `id` is undefined, you can get string **"/undefined"**, so maybe set some default id or throw an exception

File: packages/suite/src/utils/wallet/tokenUtils.ts [hunk 35]
```diff
@@ -65,16 +70,37 @@ export const formatTokenSymbol = (symbol: string) => {
...
 
-export const getTokens = (
-    tokens: EnhancedTokenInfo[] | TokenInfo[],
-    symbol: NetworkSymbol,
-    coinDefinitions?: TokenDefinition,
-    searchQuery?: string,
-) => {
-    // filter out NFT tokens until we implement them
-    const tokensWithoutNFTs = tokens.filter(token => !isNftToken(token));
+type GetTokens = {
```
Comment (izmy) [inline packages/suite/src/utils/wallet/tokenUtils.ts:73]: I think it is not a good practice to name types after verbs, so I suggest renaming it to something like **TokenCollection**?

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 36]
```diff
@@ -0,0 +1,296 @@
...
+}: NftsRowProps) => {
+    const dispatch = useDispatch();
+    const { elevation } = useElevation();
+
+    const [isCollectionOpen, setIsCollectionOpen] = useState(false);
+
+    const shouldShowCopyAddressModal = useSelector(selectIsCopyAddressModalShown);
+    const { account } = selectedAccount;
+
+    const getNftContractExplorerUrl = (network: Network, nft: EnhancedTokenInfo) => {
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: this function doesn't use any props (only parameters), so you can move it from the component to the outer scope (saving unnecessary renders)

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 37]
```diff
@@ -0,0 +1,296 @@
...
+                                                onClick: () =>
+                                                    dispatch(
+                                                        tokenDefinitionsActions.setTokenStatus({
+                                                            symbol: network.symbol,
+                                                            contractAddress: nft.contract || '',
+                                                            status: TokenManagementAction.HIDE,
+                                                            type: DefinitionType.NFT,
+                                                        }),
+                                                    ),
+                                                isHidden: isShown === false,
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: 💅
```suggestion
                                                isHidden: !isShown,
```

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 38]
```diff
@@ -0,0 +1,296 @@
...
+                                                                  nft.contract || '',
+                                                                  'contract',
+                                                              )
+                                                            : copyAddressToClipboard(nft.contract),
+                                                    );
+                                                },
+                                            },
+                                        ],
+                                    },
+                                ].filter(category => category) as GroupedMenuItems[]
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: What does this filter do?

File: packages/suite/src/views/wallet/tokens/DropdownRow.tsx [hunk 39]
```diff
@@ -0,0 +1,64 @@
...
+    user-select: none;
+`;
+
+type DropdownRowProps = {
+    isActive: boolean;
+    text?: TranslationKey;
+    typographyStyle?: TypographyStyle;
+    variant?: TextVariant;
+    shouldDisplayIcon?: boolean;
+    NftName?: ReactNode;
```
Comment (izmy) [inline packages/suite/src/views/wallet/tokens/DropdownRow.tsx]: 💅
```suggestion
    nftName?: ReactNode;
```

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 40]
```diff
@@ -0,0 +1,296 @@
...
+                                <Translation id="TR_UNHIDE" />
+                            </Button>
+                        )}
+                    </Row>
+                </Table.Cell>
+            </Table.Row>
+            {nft.type === 'ERC721' &&
+                nft.ids?.map((id, index) => (
+                    <Table.Row
+                        key={id + index}
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: I would expect the ID to be unique.

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 41]
```diff
@@ -0,0 +1,296 @@
...
+                        isCollapsed={!isCollectionOpen}
+                        isHighlightedOnHover={false}
+                    >
+                        <Table.Cell colSpan={2}>
+                            <Text typographyStyle="hint">
+                                <HiddenPlaceholder>
+                                    <Row gap={spacings.xs}>
+                                        {pictureIcon}
+                                        <Text textWrap="nowrap">{NftName}</Text>
+                                        #<RedactNumericalValue value={id.toString()} />
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Isn't **id** string?

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 42]
```diff
@@ -0,0 +1,296 @@
...
+                                        <Badge size="small">
+                                            <RedactNumericalValue value="1x" />
+                                        </Badge>
+                                        <TrezorLink
+                                            typographyStyle="label"
+                                            variant="nostyle"
+                                            href={getNftExplorerUrl(network, nft, id.toString())}
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Isn't **id** string?

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 43]
```diff
@@ -0,0 +1,296 @@
...
+                        isCollapsed={!isCollectionOpen}
+                        isHighlightedOnHover={false}
+                    >
+                        <Table.Cell colSpan={2}>
+                            <Text typographyStyle="hint">
+                                <HiddenPlaceholder>
+                                    <Row gap={spacings.xs}>
+                                        {pictureIcon}
+                                        <Text textWrap="nowrap">{NftName}</Text>
+                                        #<RedactNumericalValue value={value.id?.toString() || ''} />
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Isn't **value.id** string?

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 44]
```diff
@@ -0,0 +1,296 @@
...
+                                    </Row>
+                                </HiddenPlaceholder>
+                            </Text>
+                        </Table.Cell>
+                    </Table.Row>
+                ))}
+            {nft.type === 'ERC1155' &&
+                nft.multiTokenValues?.map((value, index) => (
+                    <Table.Row
+                        key={nft.contract + index}
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: If `nft.contract` is not unique I prefer to use string interpolation

```suggestion
                        key={`${nft.contract}-${index}`}
```

If `nft.contract` is unique, I prefer not to use `index`

File: packages/suite/src/views/wallet/nfts/NftsTablesSection.tsx [hunk 45]
```diff
@@ -0,0 +1,95 @@
...
+        return (
+            <NftsTable selectedAccount={selectedAccount} isShown={isShown} verified nfts={nfts} />
+        );
+    } else {
+        if (areNoHiddenNfts && areNoUnverifiedNfts) {
+            return <NoTokens isNft={true} title={<Translation id="TR_HIDDEN_NFT_EMPTY" />} />;
+        }
+
+        return hiddenEvmNfts;
+    }
```
Comment (izmy) [inline packages/suite/src/views/wallet/nfts/NftsTablesSection.tsx]:
```suggestion
const getNoTokensTitle = () => {
    const hasHiddenOrUnverified =
        nfts?.hiddenWithBalance.length ||
        nfts?.hiddenWithoutBalance.length ||
        nfts?.unverifiedWithBalance.length ||
        nfts?.unverifiedWithoutBalance.length;

    return hasHiddenOrUnverified ? 'TR_NFT_EMPTY_CHECK_HIDDEN' : 'TR_NFT_EMPTY';
};

if (isShown) {
    return areNoShownNfts ? (
        <NoTokens isNft={true} title={<Translation id={getNoTokensTitle()} />} />
    ) : (
        <NftsTable selectedAccount={selectedAccount} isShown={isShown} verified nfts={nfts} />
    );
}

if (areNoHiddenNfts && areNoUnverifiedNfts) {
    return <NoTokens isNft={true} title={<Translation id="TR_HIDDEN_NFT_EMPTY" />} />;
}

return hiddenEvmNfts;
```

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 44 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: In this case it's no unique

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 40 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Theoretically, yes. In fact it doesn't have to be unique, anyone can create a contract and make an id not unique. There's no checker onchain that would ensure uniqueness of an ID. 

Example:
Screenshot 2024-12-17 at 13 57 19

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 38 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: This was needed in case of TokenRow (where I copied it from), I think there it was checking wether the array doesn't include falcy values, because there were some conditional items. Here I don't have any conditional items so it's not necessary, can be dropped

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 36 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: It actually should be in utils, so I'll move it there

File: suite-common/wallet-utils/src/tokenUtils.ts (hunk 34 above)
Comment (enjojoy) [reply suite-common/wallet-utils/src/tokenUtils.ts:41]: It actually shouldn't be undefined, I'll handle it outside of the function

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx (hunk 33 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: I'm not a fan of duplicating the style components, I'll rather take out the conditions outside so it looks cleaner

**Review by izmy — APPROVED** [review]

File: packages/suite/src/views/wallet/nfts/NftsTablesSection.tsx [hunk 46]
```diff
@@ -0,0 +1,87 @@
...
+
+    const areNoShownNfts = !nfts?.shownWithBalance.length && !nfts?.shownWithoutBalance.length;
+
+    const areNoHiddenNfts = !nfts?.hiddenWithBalance.length && !nfts?.hiddenWithoutBalance.length;
+
+    const areNoUnverifiedNfts =
+        !nfts?.unverifiedWithBalance.length && !nfts?.unverifiedWithoutBalance.length;
+
+    const hiddenEvmNfts = (
+        <Column gap={24} alignItems="stretch">
```
Comment (seibei-iguchi) [inline packages/suite/src/views/wallet/nfts/NftsTablesSection.tsx]: Use spacings for gap. The align is not needed, I think.

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx [hunk 47]
```diff
@@ -0,0 +1,268 @@
...
+    nft: EnhancedTokenInfo;
+    network: Network;
+    selectedAccount: SelectedAccountStatus;
+    isShown?: boolean;
+    isEmptyCollection?: boolean;
+    setIsEmptyCollectionsOpen?: (open: boolean) => void;
+    isEmptyCollectionsOpen?: boolean;
+};
+
+const PictureIconWrapper = styled.div<{ $elevation: Elevation }>`
```
Comment (seibei-iguchi) [inline packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Try using IconCircle with hasBorder=false, paddingType=small (or medium, perhaps), size={32}, variant=tertiary instead of custom styles.

**Review by seibei-iguchi — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx (hunk 47 above)
Comment (enjojoy) [reply packages/suite/src/views/wallet/nfts/NftsTable/NftsRow.tsx]: Thank you, I was wondering if there's a component like that. It's perfect

**Review by seibei-iguchi — APPROVED** [review]

File: packages/suite/src/utils/wallet/tokenUtils.ts [hunk 48]
```diff
@@ -83,16 +109,23 @@ export const getTokens = (
...
+        const isHidden = tokenDefinitions?.hide.includes(token.contract);
+        const isShown = tokenDefinitions?.show.includes(token.contract);
 
         const query = searchQuery ? searchQuery.trim().toLowerCase() : '';
 
-        if (searchQuery && !isTokenMatchesSearch(token, query)) return;
+        if (
+            searchQuery &&
+            (!isTokenMatchesSearch(token, query) ||
+                (isNft && isNftMatchesSearch(token as TokenInfo, query)))
```
Comment (martykan) [inline packages/suite/src/utils/wallet/tokenUtils.ts]: This is a bit ugly and actually doesn't work, I would rewrite it like this:
```suggestion
            !(isNft ? isNftMatchesSearch(token, query) : isTokenMatchesSearch(token, query))
```

File: packages/suite/src/views/wallet/tokens/TokensNavigation.tsx [hunk 49]
```diff
@@ -1,46 +1,75 @@
...
+type SubTabConfig = {
+    isNft: boolean;
+    tokens: GetTokensOutputType;
+    goToRoute: (route: Route['name']) => () => void;
+};
+
+const getSubTabConfig = ({ isNft, tokens, goToRoute }: SubTabConfig) => [
+    {
+        id: isNft ? 'wallet-nfts' : 'wallet-tokens',
+        iconName: isNft ? 'pictureFrame' : ('tokens' as IconName),
```
Comment (martykan) [inline packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: This looks odd, the type cast is only applied to one part of the conditional? 
Also I recommend `satisfies` instead of `as`, because then TS actually checks the type conformity.

Comment (enjojoy) [reply packages/suite/src/views/wallet/tokens/TokensNavigation.tsx]: That's weird indeed, good catch 

I did it this way


```
type SubTabItem = {
    id: string;
    iconName: IconName;
    onClick: () => void;
    count: number;
    labelId: TranslationKey;
};

const getSubTabConfig = ({ isNft, tokens, goToRoute }: SubTabConfig) =>
    [
        {
            id: isNft ? 'wallet-nfts' : 'wallet-tokens',
            iconName: isNft ? 'pictureFrame' : 'tokens',
            onClick: goToRoute(isNft ? 'wallet-nfts' : 'wallet-tokens'),
            count: tokens.shownWithBalance.length,
            labelId: isNft ? 'TR_NAV_COLLECTIONS' : 'TR_NAV_TOKENS',
        },
        {
            id: isNft ? 'wallet-nfts-hidden' : 'wallet-tokens-hidden',
            iconName: 'hide',
            onClick: goToRoute(isNft ? 'wallet-nfts-hidden' : 'wallet-tokens-hidden'),
            count: tokens.hiddenWithBalance.length,
            labelId: 'TR_HIDDEN',
        },
    ] satisfies SubTabItem[];
```

File: packages/suite/src/utils/wallet/tokenUtils.ts (hunk 48 above)
Comment (enjojoy) [reply packages/suite/src/utils/wallet/tokenUtils.ts]: Thank you, implemented

**Review by martykan — APPROVED** [review]

**Review by tomasklim — CHANGES_REQUESTED** [review]
~Getting this error when navigating to settings~
Screenshot 2024-12-19 at 15 49 18

Sorry, I had database from L2 branch

**Comment by tomasklim** [comment]
There is bigger gap in NTFs between tabs and table than in Tokens

https://github.com/user-attachments/assets/01f5eae9-f49e-4506-b0b4-45798af42d6f

**Comment by enjojoy** [comment]
> There is bigger gap in NTFs between tabs and table than in Tokens
> 
>  Screen.Recording.2024-12-19.at.15.57.46.mov

fixed by a recent commit

**Review by tomasklim — CHANGES_REQUESTED** [review]
I've sent our legit NFT (using Rabby) from ETH 1 to ETH 2 and this happened:

https://github.com/user-attachments/assets/e2097d5f-b2ab-41dd-be33-630d28494bac

Missing legit NFT section 
Missing hidden "no balance" nft collection in Hidden

**Comment by tomasklim** [comment]
nit:
In debug mode we can add token by contract address. It is available in `Tokens` but not in `NFTs` 
You can add NFT in tokens sections so it is possible to debug it, but maybe it should be unified and available in both sections under debug mode?
Screenshot 2024-12-19 at 16 22 22

**Comment by tomasklim** [comment]
It is not possible to seach empty collection

Screenshot 2024-12-19 at 16 23 50
Screenshot 2024-12-19 at 16 23 46

**Comment by tomasklim** [comment]
Probably there should be `Search NFTs` or `Search collections` 
Screenshot 2024-12-19 at 16 25 32

**Comment by enjojoy** [comment]
> I've sent our legit NFT (using Rabby) from ETH 1 to ETH 2 and this happened:
> 
>  Screen.Recording.2024-12-19.at.16.17.07.mov 
> Missing legit NFT section Missing hidden "no balance" nft collection in Hidden

Fixed 
Screenshot 2024-12-19 at 15 30 52

**Comment by enjojoy** [comment]
> I've sent our legit NFT (using Rabby) from ETH 1 to ETH 2 and this happened:
> 
>  Screen.Recording.2024-12-19.at.16.17.07.mov 
> Missing legit NFT section Missing hidden "no balance" nft collection in Hidden

Fixed 

https://github.com/user-attachments/assets/77aa7406-135a-4936-b7d7-d21a5285f204

**Comment by tomasklim** [comment]
Tokens table shows this when no result found
Screenshot 2024-12-19 at 16 43 55

(only in legit tab, in hidden it does not work same as for nfts)

NFT:
Screenshot 2024-12-19 at 16 43 59

**Comment by enjojoy** [comment]
> Tokens table shows this when no result found Screenshot 2024-12-19 at 16 43 55
> 
> (only in legit tab, in hidden it does not work same as for nfts)
> 
> NFT: Screenshot 2024-12-19 at 16 43 59

fixed this, and for hidden tokens too

**Review by tomasklim — CHANGES_REQUESTED** [review]
Screenshot 2024-12-19 at 21 33 26
now it really does not work

**Review by tomasklim — APPROVED** [review]
LGTM 🚀

**Comment by enjojoy** [comment]
@trezor/qa 

NFT section is introduced as an experimental feature. You have to turn it on in the settings. Only for EVM based chains. 

### Standards
It works with 2 types of NFT standards:

ERC-721 (Non-Fungible Token Standard):
	Each token has a unique ID (tokenId) that distinguishes it from others. (although it's possible that there can be NFTs with same IDs, especially in scam collections). But in the usual case there should be only one item of each ID. 
	
ERC-1155 (Multi-Token Standard):
	Each token can be represented multiple times. 
	
In the table you can't tell which is which, you can check it in the explorer. 

### Empty collections
If a collection has been present in the account before, but now it's empty (because user sent all the nfts away using a third party wallet), it will be displayed in the "Empty collections" on the last row of the table. 

### Recognized/unrecognized collections
A collection can be recognized (based on information from coingecko), and unrecognized, in that case it's displayed in the hidden part. (It's similar as in tokens)


### Tips for testing 
For testing I recommend you to buy some cheap recognized collection, on BSC or Polygon to avoid high gas fees. You don't have to worry about unrecognized collections because there's a ton of spam collections on QA seed. (on Polygon for sure)

https://www.coingecko.com/en/nft/chains/binance-smart-chain you can check out the collections there and filter it by the lowest floor price. 

Then you can find it either on OpenSea or MagicEden (or another NFT marketplace of your choice). You'll have to connect using a third party wallet (can be Metamask or Rabby)

I want to ask you to really take your time and test every possible scenario with recognized/unrecognized collections, with each standard as well as empty and hidden collections. Maybe on the L2s in debug mode as well.

This is a big feature and as you can see in the amount of comments, it's easy to overlook something. 

May you have any questions, feel free to reach out to me

File: suite-common/wallet-config/src/networksConfig.ts [hunk 50]
```diff
@@ -545,7 +546,7 @@ export const networks = {
         decimals: 18,
         testnet: true,
         explorer: getExplorerUrls('https://holesky1.trezor.io', 'ethereum'),
-        features: ['rbf', 'sign-verify', 'tokens', 'staking'],
+        features: ['rbf', 'sign-verify', 'tokens', 'nfts', 'nft-definitions'],
```
Comment (tomasklim) [inline suite-common/wallet-config/src/networksConfig.ts:549]: removed `staking` from ethereum holesky :(

Comment (enjojoy) [reply suite-common/wallet-config/src/networksConfig.ts:549]: fixing here https://github.com/trezor/trezor-suite/pull/16129

thank you for the catch

**Comment by bosomt** [comment]
**QA OK**

- enable/disable ✅ 
- empty/not empty/multi collection ✅ 
- hide/unhide ✅ 
- view all transactions filter ✅ 
- view in explorer ✅ 
- ERC1155 NFT on Arbitrum ✅ 
- ERC721 NFT on Polygon ✅ 
- explorer link ✅ 
- lots of hidden NFTs :) 


**Info:**
 - Suite version: web 25.1.0 (8f3ea38f83226eaf6ed5053b925c945a57a5292e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision f2aeea159f1fde98d4fc5575350a8c9fc4478367)
 - Transport: WebUsbTransport
