### PR TITLE
fix/firmware update

### LINKED ISSUE #21062: Fix TS7 firmware update UI
https://github.com/user-attachments/assets/136334ce-6268-4d6a-b0a7-b06b0f5466db

0:10: There should be a "Confirm on Trezor" pill on top of the modal - seems to be broken on other models, too.
0:17: Device switcher should not flicker.
0:39: Installation progress should be visible.

### PR DESCRIPTION
**Pull request by OriginalEveres**
**Changes:**
- enabled `Confirm on device` pill when the user should confirm on device
- fixed wrong update UI state at the end of the installation

**Tested on**:
- ✅ T3W1
- ✅ T3T1

### Note
I could not reproduce `0:17: Device switcher should not flicker`

## Related Issue

Resolve https://github.com/orgs/trezor/projects/113/views/1?pane=issue&itemId=126151986&issue=trezor%7Ctrezor-suite%7C21062

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/firmware-update&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/firmware-update&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/firmware-update&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/firmware/FirmwareInitial.tsx [hunk 1]
```diff
@@ -343,7 +343,7 @@ export const FirmwareInitial = ({
         };
     }
 
-    if (content) {
+    if (content) {
```
Comment (vojtatranta) [inline packages/suite/src/components/firmware/FirmwareInitial.tsx]: huh

File: suite-common/firmware/src/hooks/useFirmwareInstallation.ts [hunk 2]
```diff
@@ -148,7 +148,9 @@ export const useFirmwareInstallation = (
 
     const showConfirmationPill =
         (!showReconnectPrompt && progressEvent?.operation === 'downloading') ||
-        isThpConfirmationRequested;
+        isThpConfirmationRequested ||
```
Comment (vojtatranta) [inline suite-common/firmware/src/hooks/useFirmwareInstallation.ts:151]: Just a NIT: can we put it to some util function up there which's name would explain the state in which this has to be.

**Review by vojtatranta — APPROVED** [review]
I tested it out, and the cases mentioned in the video seem to be fixed.
