### PR TITLE
fix(suite-native): device manager UI bugs

### LINKED ISSUE #9997: There should not be grey circles around the icon "close"
Close icon should not have circled background - look at the designs comparison:
Screenshot 2023-11-17 at 11 16 10

### LINKED ISSUE #9998: Icons are missing in opened switcher
Opened switcher misses the related icon, look at the design comparison:

Screenshot 2023-11-17 at 11 22 22

### LINKED ISSUE #9999: When the device is connected, icon should have "green" mark around it
Screenshot 2023-11-17 at 11 22 22

### LINKED ISSUE #10000: Subtitle in item should have different font size / colour
Screenshot 2023-11-17 at 11 22 22

### LINKED ISSUE #10001: Background of opened switcher should be white

### LINKED ISSUE #10010: Arrows in switcher should disappear when the switcher is opened
Image

### PR DESCRIPTION
**Pull request by PeKne**
## Description 

- [feat(suite-native): icon can use svg source colors](https://github.com/trezor/trezor-suite/pull/10020/commits/ca41d40eac538b8f655d665999b172825ca664cf):  makes svg accept `svgSource` color variant to use the svg source file original colors
- [refactor(suite-native): device selector naming unified](https://github.com/trezor/trezor-suite/pull/10020/commits/682da24e62b0607462e1d6fc57e5043d7702ad6f): unifies naming of the device selectors, now everything that just starts by prefix `selectDevice...` queries for `selectedDevice` (active device) state. On the other hand anything the follows`selectDevice...ById` makes query based on argument provided deviceId 
- [fix(suite-native): minor device manager UI bugs](https://github.com/trezor/trezor-suite/pull/10020/commits/e3ce2037942ed80343253276623227b33e0c71fd): Fixed minor UI bigs described by #9993:

> Screenshot 2023-11-22 at 9 28 43

## Related issues
Fixes #9997
Fixes #9998
Fixes #9999 
Fixes #10000
Fixes #10001
Fixes #10010

## Screenshot

https://github.com/trezor/trezor-suite/assets/26143964/55136cd1-bee5-4cba-ba47-33f18e4b6b38

### CODE REVIEW

File: suite-common/icons/src/components/Icon.tsx [hunk 1]
```diff
@@ -43,6 +48,10 @@ export const Icon = ({ name, customSize, size = 'large', color = 'iconDefault' }
 
     // Paint has to be Reanimated derived value, to allow color transition animation on the UI thread.
     const paint = useDerivedValue(() => {
+        // if the color is `undefined`, the `paint` is ignored and the svg source file
+        //  colors are used. This is useful for using multicolor icons.
+        if (areSvgColorsUsed || !color) return undefined;
```
Comment (Nodonisko) [inline suite-common/icons/src/components/Icon.tsx]: missing in deps

Comment (PeKne) [reply suite-common/icons/src/components/Icon.tsx]: the `svgSource` color prop used instead in the end.

File: suite-native/device-manager/src/components/DeviceItemContent.tsx [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+        selectDeviceNameById(state, deviceId),
+    );
+    const deviceLabel = useSelector((state: DeviceRootState) =>
+        selectDeviceLabelById(state, deviceId),
+    );
+
+    const isPortfolioTrackerDevice = deviceId === PORTFOLIO_TRACKER_DEVICE_ID;
+
+    // TODO: when we enable remember mode, icon representing disconnected device have to be handled.
+    const trezorDeviceIcon: IconName =
```
Comment (Nodonisko) [inline suite-native/device-manager/src/components/DeviceItemContent.tsx:40]: Can you again make some exhaustive check here?

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx [hunk 3]
```diff
@@ -45,26 +46,27 @@ export const DeviceManagerContent = () => {
         });
     };
 
+    const listedDevice = devices.filter(device => device.id !== selectedDeviceId);
```
Comment (Nodonisko) [inline suite-native/device-manager/src/components/DeviceManagerContent.tsx]: useMemo

File: suite-native/device-manager/src/components/DeviceItem.tsx [hunk 4]
```diff
@@ -24,44 +23,33 @@ const deviceItemWrapperStyle = prepareNativeStyle(utils => ({
...
-
     const { setIsDeviceManagerVisible } = useDeviceManager();
 
-    if (!deviceLabel) return null;
-
     const handleSelectDevice = () => {
         setIsDeviceManagerVisible(false);
 
-        if (device?.id === currentDevice?.id) return;
+        if (id === currentDevice?.id) return;
```
Comment (Nodonisko) [inline suite-native/device-manager/src/components/DeviceItem.tsx]: Can you name `id` little bit more specific? I kind of confused here `id` vs `currentDevice.id` vs `device.id`. You don't need to change prop name just override it somehow like `{ id: deviceItemId }` or smthing like that

**Review by Nodonisko — APPROVED** [review]
few nits

File: suite-native/device-manager/src/components/DeviceItemContent.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/device-manager/src/components/DeviceItemContent.tsx:40]: I've checked with designer, and there will be the same Icon for all the possible trezor models. So IMO there is no need for exhaustive check here.

File: suite-native/device-manager/src/components/DeviceManagerContent.tsx (hunk 3 above)
Comment (PeKne) [reply suite-native/device-manager/src/components/DeviceManagerContent.tsx]: memo applied in [4092740](https://github.com/trezor/trezor-suite/pull/10020/commits/4092740700d31090573c5fbf379279c641a91726)

File: suite-native/device-manager/src/components/DeviceItem.tsx (hunk 4 above)
Comment (PeKne) [reply suite-native/device-manager/src/components/DeviceItem.tsx]: naming improved as `deviceItemId` and `selectedDeviceId` in [4092740](https://github.com/trezor/trezor-suite/pull/10020/commits/4092740700d31090573c5fbf379279c641a91726)
