### PR TITLE
fix(suite): Make Install firmware buttons more rensposive

### LINKED ISSUE #13261: Polish Welcome screen
1. Check main button color - should be `variant="primary"`

2. There are multiple responsive issues:

image

image

3. Verify design with Ondra

### PR DESCRIPTION
**Pull request by hstastna**
## Description

Also adjust `Button` component to normal wrap instead of nowrap and use `spacingsPx` for some css padding/margin values instead, where possible.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13261

## Videos:
**Before:**

https://github.com/user-attachments/assets/e1726b17-cb52-400b-9e9f-ee6423ed5681

**After:**

https://github.com/user-attachments/assets/53ee3a94-96bc-411f-9c7b-dd43a19207ba

### CODE REVIEW

File: packages/suite/src/components/firmware/Buttons/FirmwareInstallButton.tsx [hunk 1]
```diff
@@ -1,19 +1,13 @@
-import styled from 'styled-components';
-
 import { Button, ButtonProps, Tooltip } from '@trezor/components';
 import { Translation } from 'src/components/suite';
 import { useTranslation } from 'src/hooks/suite';
 
-const StyledButton = styled(Button)`
-    min-width: 180px;
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/Buttons/FirmwareInstallButton.tsx:8]: :clap:

**Review by peter-sanderson — APPROVED** [review]

**Review by jvaclavik — APPROVED** [review]
LGTM!
