### PR TITLE
Fix/sendform is integer

### LINKED ISSUE #1857: Change wording when sending ERC20 tokens
Please change wording when sending ERC20 tokens.
Something more explanatory.
Like Maximum decimals allowed for this token is ..
I have no idea why I can't send 1.1 of this token.

image (1)

### PR DESCRIPTION
**Pull request by szymonlesisz**
fix: #1857
and exclude leading zeros

### CODE REVIEW

File: packages/suite/src/views/wallet/send/components/Fees/components/CustomFee/index.tsx [hunk 1]
```diff
@@ -63,12 +63,10 @@ const CustomFee = () => {
                             return 'CUSTOM_FEE_IS_NOT_NUMBER';
                         }
                         // allow decimals in ETH since GWEI is not a satoshi
-                        if (
-                            network.networkType !== 'ethereum' &&
-                            (!feeBig.isInteger() || value.includes('.'))
-                        ) {
+                        if (network.networkType !== 'ethereum' && !isInteger(value)) {
```
Comment (keraf) [inline packages/suite/src/views/wallet/send/components/Fees/components/CustomFee/index.tsx:66]: Not sure if we have the network types in a constant file but I'd be useful to create one in the near future.

**Review by keraf — APPROVED** [review]

File: packages/suite/src/views/wallet/send/components/Fees/components/CustomFee/index.tsx (hunk 1 above)
Comment (szymonlesisz) [reply packages/suite/src/views/wallet/send/components/Fees/components/CustomFee/index.tsx:66]: we do have it since early beginnings:
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/config/wallet/networks.ts
