### PR TITLE
fix(suite): update cardano unstake tx view in history

### LINKED ISSUE #24527: Cardano unstake tx in tx history
Fix and unify view of 1 unstaking tx with auto-claimed rewards

Deposit should be `+` in tx history
Image
Withdrawal should be `+` in tx detail
Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Fixes Cardano unstake transaction display in history.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/24527

## Screenshots:
image
image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/AmountDetails.tsx [hunk 1]
```diff
@@ -270,7 +258,7 @@ export const AmountDetails = ({ tx, isTestnet }: AmountDetailsProps) => {
                                 <FormattedCryptoAmount
                                     value={cardanoWithdrawal}
                                     symbol={tx.symbol}
-                                    signValue="negative"
+                                    signValue="positive"
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/AmountDetails.tsx]: can `getCardanoStakingDepositSignValue` be used also here?

Would make sense to call it `getCardanoStakingSignValue`?

Comment (dev-pvl) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/AmountDetails.tsx]: fixed and rebased

**Review by tomasklim — APPROVED** [review]
LGTM 🚀
