### PR TITLE
fix(suite): fix padding for InnerActions

### LINKED ISSUE #10905: Empower minor issues p 2
**Describe the bug**
6.`Close` button not properly aligned in `Update firmware complete` modal
7. Send and receive buttons are active even account not properly loaded, buttons disappear after you click them 
8. Account name is rendered as context help sometimes /probably due that it didnt fit to left panel before when ARS fiat value enabled/

**Info:**
 - Suite version: desktop 24.2.0 (906dcd476ef2e5919147b4f86e299b6e3b607d96)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
6.
image

7.
image

8.

https://github.com/trezor/trezor-suite/assets/31506317/2e73b3aa-a64a-4f13-87a3-94ff7884b0a8

https://github.com/trezor/trezor-suite/assets/31506317/0327cf57-0717-4784-aa01-7eec5c737e0c

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10905

## Screenshots:

image
image

image

### CODE REVIEW

File: packages/suite/src/components/onboarding/OnboardingStepBox.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ const InnerActions = styled.div`
     justify-content: center;
     align-items: center;
     margin-top: 32px;
+    margin-bottom: 32px;
```
Comment (jvaclavik) [inline packages/suite/src/components/onboarding/OnboardingStepBox.tsx]: spacingPx would be nice, but OK

**Review by jvaclavik — APPROVED** [review]

File: packages/suite/src/components/onboarding/OnboardingStepBox.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/components/onboarding/OnboardingStepBox.tsx]: done
