### PR TITLE
fix(suite): display receive address in swap instead of account label

### LINKED ISSUE #21681: Trading - show receive custom address on confirmation step
When user selects receive account that is outside the Trezor Suite, show him the beginning of the address instead of the account name on the confirmation step of SWAP.

Trading -> Swap -> Address outside Trezor Suite -> profit
Trading -> Buy -> Address outside Trezor Suite -> profit

Image

Contact person: @matusbalascak

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

Display receive address (if it's external) in swap/buy instead of account label.

## Related Issue

Resolve #21681

## Screenshots:
Snímek obrazovky 2025-09-29 v 9 16 33
Snímek obrazovky 2025-09-29 v 9 17 44
Snímek obrazovky 2025-09-29 v 9 17 56
Snímek obrazovky 2025-09-29 v 9 18 04
Snímek obrazovky 2025-09-29 v 9 25 29

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/21681-swap-receive-address&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/21681-swap-receive-address&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx [hunk 1]
```diff
@@ -49,6 +49,10 @@ export const TradingSelectedOfferInfo = ({
             currency={quoteAmounts?.receiveCurrency}
             amount={quoteAmounts?.receiveAmount}
             formStep={formStep}
+            receiveAddress={
+                // A better solution would be to add type (e.g. `exchange` to `ExchangeTrade`) to each union item in `TradingTradeType` so it's easy to narrow down the type.
+                type === 'exchange' ? (selectedQuote as ExchangeTrade).receiveAddress : undefined
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: should be available also for type `buy`

**Review by tomasklim — DISMISSED** [review]
it should be shown only in case 

> When user selects receive account that is outside the Trezor Suite

Screenshot 2025-09-26 at 15 15 43

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx [hunk 2]
```diff
@@ -59,11 +63,17 @@ export const TradingInfoItem = ({
...
                             {accountLabelPrefix}&nbsp;
-                            <AccountLabel
-                                account={account}
-                                showAccountTypeBadge
-                                accountTypeBadgeSize="small"
-                            />
+                            {type === 'exchange' && receiveAddress ? (
+                                <Tooltip content={receiveAddress} hasArrow>
+                                    <StyledReceiveAddress>{receiveAddress}</StyledReceiveAddress>
+                                </Tooltip>
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]:
```suggestion
                              <TokenAddressRow
                                    tokenContractAddress={receiveAddress}
                                    shouldAllowCopy={true}
                                    onCopy={() => copyAddressToClipboard(receiveAddress)}
                                    typographyStyle="hint"
                                    variant="tertiary"
                                />
```

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx [hunk 3]
```diff
@@ -59,11 +63,17 @@ export const TradingInfoItem = ({
                     <Text variant="tertiary" typographyStyle="hint" as="div">
                         <Row>
                             {accountLabelPrefix}&nbsp;
-                            <AccountLabel
-                                account={account}
-                                showAccountTypeBadge
-                                accountTypeBadgeSize="small"
-                            />
+                            {type === 'exchange' && receiveAddress ? (
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx:66]:
```suggestion
                            {!account && receiveAddress ? (
```

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: Screenshot 2025-09-26 at 15 17 29

Comment (tomasklim) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: sync with @TomasBoda, he is going to use this component too, maybe he will rename it/modify it

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: Nice, that's better component for it, thanks. Alright, we'll sync.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx (hunk 1 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: ✅

**Comment by cermakjiri** [comment]
> it should be shown only in case
> 
> > When user selects receive account that is outside the Trezor Suite
> 
> Screenshot 2025-09-26 at 15 15 43

✅

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx [hunk 4]
```diff
@@ -39,31 +42,45 @@ export const TradingInfoItem = ({
...
+    receiveAddress,
 }: TradingInfoItemProps) => {
     const { translationString } = useTranslation();
     const currencyInfo = currency && cryptoIdToNetworkSymbolAndContractAddress(currency);
     const accountLabelPrefix = translationString(isReceive ? 'TR_TO' : 'TR_FROM').toLowerCase();
 
-    const shouldShowAccountLabel =
-        ((formStep && ['SEND_TRANSACTION', 'SIGN_DATA'].includes(formStep)) || !isReceive) &&
+    const showAccountLabel =
+        (['SEND_TRANSACTION', 'SIGN_DATA'].find(f => f === formStep) || !isReceive) &&
```
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: For me, using `includes` is more straightforward here than `find`, since you only need a boolean for the condition.

Comment (izmy) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: I also suggest creating a static const, e.g.
`const FORM_STEPS_WITH_LABEL = new Set(['SEND_TRANSACTION', 'SIGN_DATA'] as const);`
and then using
`FORM_STEPS_WITH_LABEL.has(formStep))`

**Review by izmy — APPROVED** [review]

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx (hunk 4 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: I agree using `includes` makes more sense, however in the case of static/const array, there will be a TS error. So a solution is to use casting or type enforcement. 
E.g. `['SEND_TRANSACTION', 'SIGN_DATA'].includes(formStep!)` or `['SEND_TRANSACTION', 'SIGN_DATA'].includes(formStep as string)`. The solution with `find` doesn't require any type enforcement or casting though.

Using `Set#has` gives us O(1) instead of Array#includes with O(n), however that's a micro optimization. 

I'll add pure function called `isFormStepWithAccountLabel`, use the type enforcement and preserve the Array data structure.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx [hunk 5]
```diff
@@ -49,6 +50,12 @@ export const TradingSelectedOfferInfo = ({
             currency={quoteAmounts?.receiveCurrency}
             amount={quoteAmounts?.receiveAmount}
             formStep={formStep}
+            receiveAddress={
+                // A better solution would be to add type (e.g. `exchange` to `ExchangeTrade`) to each union item in `TradingTradeType` so it's easy to narrow down the type.
+                (['exchange', 'buy'] satisfies TradingType[]).find(t => t === type)
+                    ? (selectedQuote as ExchangeTrade | BuyTrade).receiveAddress
+                    : undefined
+            }
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: nitpick: can we move this logic above to `useMemo` for better readability?

**Review by TomasBoda — APPROVED** [review]
LGTM

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx (hunk 5 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: I agree, the code readability could be improved. But I won't use `useMemo`, that would be a micro optimization (i.e. the initialization of the hook can be actually more costly than omitting it). What about moving it to `getReceiveAddress` pure function like this?

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: https://github.com/trezor/trezor-suite/pull/21936/commits/cfc24331a67ffd8cd1c9642f69ae871271375317

Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: agreed

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx (hunk 4 above)
Comment (matusbalascak) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: I believe using `['SEND_TRANSACTION', 'SIGN_DATA'].some(step => step === formStep)` would be the best solution here that doesn't require non-null assertion.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx [hunk 6]
```diff
@@ -39,31 +55,42 @@ export const TradingInfoItem = ({
...
     const currencyInfo = currency && cryptoIdToNetworkSymbolAndContractAddress(currency);
     const accountLabelPrefix = translationString(isReceive ? 'TR_TO' : 'TR_FROM').toLowerCase();
 
-    const shouldShowAccountLabel =
-        ((formStep && ['SEND_TRANSACTION', 'SIGN_DATA'].includes(formStep)) || !isReceive) &&
-        account &&
-        type !== 'sell';
+    const showAccountLabel = isFormStepWithAccountLabel({ formStep, isReceive, account, type });
+
+    // `account` is undefined for external addresses
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx:66]: Is this comment really needed here?

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx (hunk 4 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: Yea, that's basically the `find` but ok :D

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx]: ✅

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx [hunk 7]
```diff
@@ -13,6 +14,16 @@ import { TradingInfoProvider } from 'src/views/wallet/trading/common/TradingSele
 import { TradingTransactionId } from 'src/views/wallet/trading/common/TradingTransactionId';
 import { TradingUtilsKyc } from 'src/views/wallet/trading/common/TradingUtils/TradingUtilsKyc';
 
+function getReceiveAddress(type: TradingType, selectedQuote: TradingTradeType) {
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]:
```suggestion
function getReceiveAddress(type: TradingType, selectedQuote: TradingTradeType) {
    if (!isExchangeTrade(selectedQuote) && !isBuyTrade(selectedQuote)) return;

    const isExchangeOrBuy = ['exchange', 'buy'].some(t => t === type);

    if (!isExchangeOrBuy) {
        return undefined;
    }

    return selectedQuote.receiveAddress

```

**Review by matusbalascak — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx (hunk 6 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx:66]: It wasn't obvious to me that `account` is undefined in this case as a someone new in the codebase. 🤷‍♂️

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx (hunk 7 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: Nice, I didn't know about these guard fns. Thanks

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: Or even better:
```ts
function getReceiveAddress(selectedQuote: TradingTradeType) {
    if (!isExchangeTrade(selectedQuote) && !isBuyTrade(selectedQuote)) {
        return undefined;
    }

    return selectedQuote.receiveAddress;
}
```

Comment (matusbalascak) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: Yes, good point! 👌

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingSelectedOfferInfo.tsx]: ✅

**Review by matusbalascak — APPROVED** [review]
Looks nice, good job! ✅
