### PR TITLE
refactor(product-components): extract notification subcomponents and fix Storybook fonts

### LINKED ISSUE #25129: Transaction and Exchange Notifications Refactoring
Complete the ongoing refactor of transaction and exchange notifications by moving presentational logic into product-components, keeping Suite-specific concerns in renderers, and finalizing stable Storybook variants for all relevant notification types.

### PR DESCRIPTION
**Pull request by izmy**
## Description

This PR refactors notification rendering so that `@trezor/product-components` owns more UI logic, and fixes font rendering in the' product-components' Storybook.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/25129

## Screenshots:

image

image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/refactor-notification-components&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/refactor-notification-components&lookback=7)

### CODE REVIEW

**Review by jvaclavik — APPROVED** [review]

File: packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+    receive: ExchangeInfoAsset;
+    renderAmount?: (amount: ReactNode, side: ExchangeInfoAmountSide) => ReactNode;
+};
+
+type AssetWithFallbackProps = {
+    asset: ExchangeInfoAsset;
+};
+
+const AssetWithFallback = ({ asset }: AssetWithFallbackProps) => {
+    const resolvedDisplaySymbol = getDisplaySymbol(asset.displaySymbol || asset.symbol);
```
Comment (matusbalascak) [inline packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx]:
```suggestion
    const resolvedDisplaySymbol = asset.displaySymbol ?? getDisplaySymbol(asset.symbol);
```

This seems more correct, wdyt?

File: packages/product-components/src/components/Notifications/TransactionNotification.tsx [hunk 2]
```diff
@@ -0,0 +1,154 @@
...
+
+const TransactionIcon = ({
+    icon,
+    notificationType,
+    symbol,
+    accountSymbol,
+    token,
+}: TransactionIconProps) => {
+    if (icon) {
+        return <>{icon}</>;
```
Comment (matusbalascak) [inline packages/product-components/src/components/Notifications/TransactionNotification.tsx]: `return icon` should be sufficient

File: packages/product-components/src/components/Notifications/TransactionNotification.tsx [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+    }
+
+    const isApprovalType = notificationType === 'tx-approved' || notificationType === 'tx-revoked';
+    const isTransferTokenType =
+        (notificationType === 'tx-sent' || notificationType === 'tx-received') && token;
+
+    if ((isApprovalType || isTransferTokenType) && token) {
```
Comment (matusbalascak) [inline packages/product-components/src/components/Notifications/TransactionNotification.tsx]: I'd add those check to some helper function (i.e. `shouldDisplayAssetLogo`)

File: packages/product-components/src/components/Notifications/TransactionNotification.tsx [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+    const amountContent = shouldRenderApprovalAmountWithSymbol ? (
+        <Row display="inline-flex" gap={4} alignItems="baseline">
+            {resolvedAmountValue}
+            <span>{resolvedTokenDisplaySymbol}</span>
+        </Row>
+    ) : (
+        resolvedAmountValue
+    );
+
+    return <>{renderAmount ? renderAmount(amountContent) : amountContent}</>;
```
Comment (matusbalascak) [inline packages/product-components/src/components/Notifications/TransactionNotification.tsx]: no need for fragment here

File: packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+
+type AmountWithSymbolProps = {
+    amount: ReactNode;
+    asset: ExchangeInfoAsset;
+};
+
+const AmountWithSymbol = ({ amount, asset }: AmountWithSymbolProps) => (
+    <Row gap={4} alignItems="baseline">
+        {amount}
+        <Text>{getDisplaySymbol(asset.displaySymbol || asset.symbol)}</Text>
```
Comment (matusbalascak) [inline packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx]: same as above, if `asset.displaySymbol` exists we probably don't have to call getDisplaySymbol with it again no?

File: packages/product-components/src/components/Notifications/TransactionNotification.tsx
Comment (matusbalascak) [inline packages/product-components/src/components/Notifications/TransactionNotification.tsx:1]: I think this should be multiple files, I'd keep it as a component per file.

File: packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx (hunk 1 above)
Comment (izmy) [reply packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx]: Sure, I fixed it.

File: packages/product-components/src/components/Notifications/TransactionNotification.tsx
Comment (izmy) [reply packages/product-components/src/components/Notifications/TransactionNotification.tsx:1]: You are right, I changed it.

File: packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx (hunk 5 above)
Comment (izmy) [reply packages/product-components/src/components/Notifications/ExchangeInfoNotification.tsx]: changed

File: packages/product-components/src/components/Notifications/TransactionNotification.tsx (hunk 3 above)
Comment (izmy) [reply packages/product-components/src/components/Notifications/TransactionNotification.tsx]: I reorganized the components, and now it is no longer needed.

**Review by matusbalascak — APPROVED** [review]

**Review by TomasBoda — APPROVED** [review]
