### PR TITLE
fix(connect): FW revision check for unknown models

### LINKED ISSUE #17226: Fix FW revision check for unknown models
Using Trezor Suite with unknown device model, such as T3W1 or T9999, results in `other-error`, but should be `firmware-version-unknown`.

Note: two different cases can happen:
- `T3W1` - `releases.json` is found locally, but does not contain this version. Online file is fetched, gets 404 
- `T999nonsense` - nothing is found locally, online file is fetched, gets 404
But both lead to the same result (`other-error`)

## QA instructions

- connect a T3W1 device
- should display [DeviceCompromised modal](https://github.com/user-attachments/assets/befa4476-011c-4146-88ff-ee4868a85997)
- **not** a warning banner on top saying `Couldn't perform firmware authenticity check.`

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Detect 404 when fetching online `releases.json` during FW revision check, and mark it as `firmware-version-unknown`.

:thought_balloon: this could also happen if the files get deleted on our servers by accident. But IMHO that's negligible; it's much more likely that the servers will be unavailable (leading to either `other-error` or `cannot-perform-check-offline`, depending on response status)

## Related Issue

Resolve #17226

## Screenshots

Display :ghost: modal but that's nothing new.
image

### CODE REVIEW

File: packages/connect/src/utils/assets-browser.ts [hunk 1]
```diff
@@ -2,6 +2,16 @@ import fetch from 'cross-fetch';
 
 import { HttpRequestOptions, HttpRequestReturnType, HttpRequestType } from './assetsTypes';
 
+export class HttpRequestError extends Error {
+    response: Response;
+
+    constructor(response: Response) {
+        const message = `${response.status} while fetching ${response.url}`;
```
Comment (Lemonexe) [inline packages/connect/src/utils/assets-browser.ts:9]: example for `HttpRequestError.message`:
```
Error: 404 while fetching https://data.trezor.io/firmware/t999/releases.json
``` 

example for `HttpRequestError.toString()` (from prototype):
```
HttpRequestError: 404 while fetching https://data.trezor.io/firmware/t999/releases.json
    at httpRequest (assets-browser.ts:31:9)
    at async downloadReleasesMetadata (downloadReleasesMetadata.ts:12:20)
    at async getOnlineReleaseMetadata (checkFirmwareRevision.ts:30:26)
    at async checkFirmwareRevision (checkFirmwareRevision.ts:65:29)
    at async Device.checkFirmwareRevision (Device.ts:692:48)
    at async Device.checkFirmwareRevisionWithRetries (Device.ts:677:7)
    at async Device._runInner (Device.ts:449:7)
```

**Review by peter-sanderson — APPROVED** [review]

**Comment by Lemonexe** [comment]
connect-popup e2e [is currently broken](https://github.com/trezor/trezor-suite/actions/workflows/test-connect-popup.yml), merging despite it
