### PR TITLE
fix(trading): catch json parsing errors

### LINKED ISSUE #11691: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
Sentry Issue: [TREZOR-SUITE-XJM](https://satoshilabs.sentry.io/issues/5034383398/?referrer=github_integration)

```
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
- add catching of JSON parsing errors

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11691

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/trading-catching-request-error&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/trading-catching-request-error&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/trading-catching-request-error&lookback=7)

### CODE REVIEW

**Comment by Lemonexe** [comment]
Unit tests are failing:
```
@suite-common/trading:   ● InvityAPI › getBuyTradeForm › should get buy trade form
"error": "TypeError: response.json(...).then is not a function",
```

File: suite-common/trading/src/invityAPI.ts [hunk 1]
```diff
@@ -164,15 +164,25 @@ class InvityAPI {
 
         return await fetch(finalUrl, opts).then(response => {
             if (response.ok) {
-                return response.json();
+                return response
+                    .json()
+                    .then(json => json)
```
Comment (Lemonexe) [inline suite-common/trading/src/invityAPI.ts:169]: Looks like `response.json()` does not always return a promise  when response is not json-like..
I'd expect that it always return a promise, and it may `reject` it.
So I believe you will have to wrap it with `try {} catch {}` block instead of `.catch` on the promise

Comment (adderpositive) [reply suite-common/trading/src/invityAPI.ts:169]: I have updated tests, a fetch doesnt mocked `json` method correctly.

Comment (Lemonexe) [reply suite-common/trading/src/invityAPI.ts:169]: Ah, so I was overthinking it without studying the code, it is expected to return a Promise after all :smile:

**Review by Lemonexe — APPROVED** [review]
Thanks, I'll rebase & merge after CI passes
