### PR TITLE
fix(suite-native): FW rev check abort error as offline

### LINKED ISSUE #22653: Firmware revision check other-error because Error: Aborted
Sentry Issue: [SUITE-NATIVE-2SR](https://satoshilabs.sentry.io/issues/6852178500/?referrer=github_integration)

```
reportCheckFail: Firmware revision check failed! {"model":"T2B1","revision":"acd56d0113a547e9b5983510b0ce9de079e30e05","version":"2.9.1","vendor":"Trezor","errorType":"other-error"}
  at withSentryScope$argument_0 (/suite-native/sentry/src/reportSecurityCheck.ts:18:45)
  at reportSecurityCheck (/suite-native/sentry/src/reportSecurityCheck.ts:15:20)
  at createThunk$argument_1 (/suite-common/firmware-authenticity/src/reportSecurityCheckThunk.ts:12:40)
  at tryCallTwo (app:///index.android.bundle:1:1223)
  at doResolve (app:///index.android.bundle:1:2542)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Continuing the game of whack-a-mole to catch all kinds of offline errors on all environments.

## Related Issue

Resolve #22653

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/FW-rev-check-other-error&lookback=7)

### CODE REVIEW

File: packages/connect/src/device/checkFirmwareRevision.ts [hunk 1]
```diff
@@ -14,6 +14,7 @@ const isNodeJSOfflineError = (e: Error) => ['FetchError', 'AbortError'].includes
 const isReactNativeOfflineError = (e: Error) =>
     e.name === 'TypeError' && e.message.includes('Network request failed');
 const isAbortControllerTimeout = (e: Error) =>
+    e.message.includes('Aborted') ||
```
Comment (Lemonexe) [inline packages/connect/src/device/checkFirmwareRevision.ts:17]: See https://satoshilabs.sentry.io/issues/6852178500/?project=4504214699245568&referrer=github_integration

**Review by OriginalEveres — APPROVED** [review]
LGTM
