### PR TITLE
fix(suite): layout header rendering

### LINKED ISSUE #15637: Tokens tab re-renders on each click
https://github.com/user-attachments/assets/6b7b56cb-ee7e-4cc2-a005-5b2b4e8cf402

### PR DESCRIPTION
**Pull request by seibei-iguchi**
Fixes https://satoshilabs.slack.com/archives/C07CPLU4SE8/p1732875180964159?thread_ts=1732874938.526209&cid=C07CPLU4SE8

### CODE REVIEW

**Review by jvaclavik — APPROVED** [review]

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayoutHeader.tsx [hunk 1]
```diff
@@ -1,17 +1,53 @@
...
+    fallbackTitle: TranslationKey;
+    currentRouteName?: string;
+    goBack: () => void;
+};
+
+const CoinmarketPageHeader = ({
+    fallbackTitle,
+    currentRouteName,
+    goBack,
+}: CoinmarketPageHeaderProps) => {
```
Comment (peter-sanderson) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayoutHeader.tsx:26]: ultra nit: I prefer inline function without {} and return but its an absolute nit nititity nit :D

File: packages/suite/src/support/suite/LayoutContext.ts [hunk 2]
```diff
@@ -1,12 +1,12 @@
...
+import React, { createContext } from 'react';
 
 export type SideMenuProps = {
     isMenuInline?: boolean;
 };
 
 export type LayoutContextPayload = {
     title?: string;
-    TopMenu?: ComponentType;
+    layoutHeader?: React.ReactNode;
```
Comment (peter-sanderson) [inline packages/suite/src/support/suite/LayoutContext.ts:9]: :clap: :heart_eyes:
