### PR TITLE
fix(trading): update trading currency based on currency from settings

### LINKED ISSUE #14925: Trading - wrong currency in trade section
Trade section offers me offers in different currency than I have set in Suite

https://github.com/user-attachments/assets/b42e011f-0dbb-4c1a-9285-f5bc17a8dea4

### PR DESCRIPTION
**Pull request by meedoox**
## Related Issue
Resolve https://github.com/trezor/trezor-suite/issues/14925

### Before
https://github.com/user-attachments/assets/7830764e-ebd2-46f1-9387-fa239c5d941b

### After 
https://github.com/user-attachments/assets/9d886f21-b7ca-4618-ad41-6f757a6c511b

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/wrong-currency-in-trade-section&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/wrong-currency-in-trade-section&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/wrong-currency-in-trade-section&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputCurrency.tsx [hunk 1]
```diff
@@ -56,10 +56,14 @@ export const TradingFormInputCurrency = ({
         }
     };
 
+    useEffect(() => {
+        (resetField as any)(name, { defaultValue: buildFiatOption(localCurrencyOption.value) });
+    }, [localCurrencyOption.value, name, resetField]);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputCurrency.tsx]: It is really hard to read this and understand it. Please make it cleaner

**Review by tomasklim — APPROVED** [review]
LGTM

**Comment by tomasklim** [comment]
@meedoox please resolve conflicts and rebase

File: suite-common/trading/src/types.ts [hunk 2]
```diff
@@ -156,7 +156,7 @@ export interface TradingInfoProps {
 }
 
 export type TradingFiatCurrencyOption = {
-    value: FiatCurrencyCode;
+    value: 'btc' | 'xag' | 'xau' | 'bhd' | 'bmd' | 'mmk' | 'pkr' | 'vef' | FiatCurrencyCode;
```
Comment (tomasklim) [inline suite-common/trading/src/types.ts]: If invity api does not know `btc`, `xag`,... it should probably not be selected and should fallback to `usd`

**Review by tomasklim — CHANGES_REQUESTED** [review]
We should not choose currency which is not known by invity api

File: packages/suite/src/types/trading/tradingForm.ts [hunk 3]
```diff
@@ -196,6 +198,7 @@ export interface TradingExchangeFormContextProps
 
     exchangeInfo?: TradingExchangeInfoSelector;
     defaultCurrency: TradingFiatCurrencyOption;
+    localCurrencyOption: { label: string; value: FiatCurrencyCode | BaseCurrencyCode };
```
Comment (tomasklim) [inline packages/suite/src/types/trading/tradingForm.ts]: there is `defaultCurrency` in types, is it required to introduce new attribute?

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts [hunk 4]
```diff
@@ -78,6 +79,14 @@ export const buildTradingFiatOption = (currency: FiatCurrencyCode) => ({
     label: currency.toUpperCase(),
 });
 
+export const getLocalCurrencyOption = (localCurrency: string) => {
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]:
```suggestion
export const getLocalCurrencyOption = (localCurrency: BaseCurrencyCode) => {
```

File: packages/suite/src/utils/wallet/trading/tradingUtils.ts [hunk 5]
```diff
@@ -78,6 +79,14 @@ export const buildTradingFiatOption = (currency: FiatCurrencyCode) => ({
...
+    const validCurrency = isArrayMember(localCurrency, typedObjectValues(enabledTradingCurrencies))
+        ? (localCurrency as FiatCurrencyCode)
+        : 'usd';
+
+    return buildTradingFiatOption(validCurrency);
+};
+
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/trading/tradingUtils.ts]: This is cleaner
```
export const getLocalCurrencyOption = (localCurrency: BaseCurrencyCode) => {
    const isValid = localCurrency in enabledTradingCurrencies;

    const validCurrency = isValid
        ? (localCurrency as Extract<BaseCurrencyCode, FiatCurrencyCode>)
        : 'usd';

    return buildTradingFiatOption(validCurrency);
};
```

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputCurrency.tsx [hunk 6]
```diff
@@ -65,10 +68,18 @@ export const TradingFormInputCurrency = ({
         }
     };
 
+    useEffect(() => {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputCurrency.tsx]: this should not be needed if `defaultCurrency` is set correctly right away (if possible, i dont know)

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Review by tomasklim — CHANGES_REQUESTED** [review]
Missing for exchange

**Review by tomasklim — APPROVED** [review]
Ah it is already implemented. Thanks. LGTM
