### PR TITLE
Fix/little things before freeze

### LINKED ISSUE #5400: Missing bottom gap under "Complete setup" button in final onboarding step
**Info:**
-   Suite Version: app, 22.5.2

**How to reproduce**

1. Go to final onboarding step and have small window

**Screenshots**
Screenshot 2022-05-17 at 11 06 23

### PR DESCRIPTION
**Pull request by tomasklim**
- close #5400 extremely annoying 😀
- error on 
Screenshot 2022-05-30 at 10 12 35

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/BasicSettings/index.tsx [hunk 1]
```diff
@@ -16,9 +16,7 @@ const BasicSettings = () => {
                 <AdvancedSetup>
                     <OnboardingButtonCta
                         data-test="@onboarding/coins/continue-button"
-                        onClick={() => {
-                            goToNextStep();
-                        }}
+                        onClick={goToNextStep}
```
Comment (matejkriz) [inline packages/suite/src/views/onboarding/steps/BasicSettings/index.tsx]: Be careful with that, it's not the same. See `goToNextStep` implementation: https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/actions/onboarding/onboardingActions.ts/#L60

It receives one param called `stepId` and checking `if (stepId)`. And by this refactor it will receives event as the param.

**Review by matejkriz — APPROVED** [review]
