### PR TITLE
fix(suite-native): scan for Bluetooth devices only when the app is active

### LINKED ISSUE #22844: Capture: Cannot start scanning operation
Add background handling to stopScanning similarly how it's done in `useBluetoothAdapter.ts`

Sentry Issue: [SUITE-NATIVE-2S5](https://satoshilabs.sentry.io/issues/6844865846/?referrer=github_integration)

```
BleError: Cannot start scanning operation
  at construct (native)
  at apply (native)
  at _construct (/node_modules/@babel/runtime/helpers/construct.js:4:65)
  at Wrapper (/node_modules/@babel/runtime/helpers/wrapNativeSuper.js:15:14)
  at construct (native)
...
(14 additional frame(s) were not displayed)
```

### Notes for QA

Not sure how to reliably reproduce/verify. Might be possible to leave the issue open and check Sentry again later.

### PR DESCRIPTION
**Pull request by yanascz**
Resolve #22844.

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/use-bluetooth-manager&lookback=7)

### CODE REVIEW

**Review by juriczech — APPROVED** [review]

File: suite-native/bluetooth/src/hooks/useBluetoothScanner.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+            }
+        });
+
+        return () => {
+            subscription.remove();
+            bluetoothManager.stopDeviceScan();
+        };
+    }, []);
+
+    return { startDeviceScan };
```
Comment (juriczech) [inline suite-native/bluetooth/src/hooks/useBluetoothScanner.ts:24]: What about this name? 
```suggestion
    return { startAndSubscribeDeviceScan };
```

Comment (yanascz) [reply suite-native/bluetooth/src/hooks/useBluetoothScanner.ts:24]: I don't understand the motivation... Subscribe to what? Ain't that implementation detail?

**Review by juriczech — APPROVED** [review]
LGTM

File: suite-native/bluetooth/src/hooks/useBluetoothScanner.ts (hunk 1 above)
Comment (juriczech) [reply suite-native/bluetooth/src/hooks/useBluetoothScanner.ts:24]: Yeah, it's probably redundant, just trying to make it more explicit but `startDeviceScan` is probably good enough.
