### PR TITLE
fix(suite): eth send flow

### LINKED ISSUE #9567: ETH send modal does not correspond with FW
### Problem statement
(look below for solution)

image

In FW (2.6.2) there are currently only 2 screens: 
image

In Suite, there are 5 points.

I'd expect only 2 bullets:
- Receipient
- Amount | Maximum fee

In tokens there is additional Contract address screen:
image

+ when I press the back arrow in fw, bullets keeps checking one by one. I'd expect the bullet to uncheck when I go back in fw. (not sure if this is possible; are we differentiating between "confirm" and "back" message in fw? @mmilata)

### Solution

Please update the Ethereum and Ethereum tokens send flow for T2B1 (all FWs) and T2T1 (only with FW 2.6.3 and later) as follows and align with the FW team to synchronize the FW<->Suite actions.

Reduce the steps in Ethereum send flow modal window from current 5 steps to only 3:

1. Recipient address match? ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=205%3A777&mode=design&t=01EikyoHUBtnEPV9-1))
2. Amount & Maximum fee matching? ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=205%3A1022&mode=design&t=01EikyoHUBtnEPV9-1))
3. All confirmed, send ([Figma design](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=205%3A1145&mode=design&t=01EikyoHUBtnEPV9-1))

Important: The example in the Suite design in Figma above is including the Spaced address checking and in the design corresponding to T2T1. Please make sure to have the black frame contents in the format and design matching the device type, its firmware version and Spaced/Continuous address view setup in settings as described in [T2B1 Segmented Address Checking#31](https://github.com/trezor/trezor-suite-private/issues/31)

For Ethereum tokens, there's one extra step in the Send modal (and FW ofc) before all the other steps. Otherwise it should behave same as the Ethereum send flow described above.

- [Figma design Ethereum token send modal first step](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=209%3A1387&mode=design&t=01EikyoHUBtnEPV9-1)
- [Figma design Ethereum token send modal last step](https://www.figma.com/file/T0DBX3enk49MAbGx7JjPpd/Suite-Desktop-PO-Workspace?type=design&node-id=207%3A1274&mode=design&t=01EikyoHUBtnEPV9-1)

Please note that all data in the design might be sort of gibberish, use real data, labels etc. as we did until now).

Nice to have: if the user would return a step in FW, the modal should ideally return as well to help users checking the contents in the best focus.

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Align steps in send flow for Ethereum in Suite with steps on the actual device.

Also fixed that for ERC-20 we display only token address if there are no definitions for the particular token.

## Related Issue

Resolve #9567

# Notes for @trezor/qa 

- Please check send flow for all coins, not only ETH!
- Check it on all models T2T1/T2B1/T1B1
- Check latest FW first, but please verify that 2.6.0 and 2.5.3 are not more broken after those changes than on the production
- Cardano send flow is broken, but should not be broken more than on production. @AdamSchinzel promised an issue for that

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx [hunk 1]
```diff
@@ -185,16 +185,14 @@ export const TransactionReviewOutputList = ({
...
-                            <TransactionReviewTotalOutput
-                                ref={totalRef}
-                                account={account}
-                                signedTx={signedTx}
-                                outputs={outputs}
-                                buttonRequestsCount={buttonRequestsCount}
-                                precomposedTx={precomposedTx}
-                            />
-                        )}
+                        <TransactionReviewTotalOutput
```
Comment (matejkriz) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx:188]: why removing the `!precomposedTx.token` condition?

Comment (matejkriz) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx:188]: I see now...

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 2]
```diff
@@ -1,6 +1,7 @@
 import BigNumber from 'bignumber.js';
 
 import TrezorConnect, { PROTO, SignedTransaction } from '@trezor/connect';
+import { getEthereumDefinitions } from '@trezor/connect/src/api/ethereum/ethereumDefinitions';
```
Comment (tomasklim) [inline packages/suite/src/actions/wallet/sendFormActions.ts:4]: nit:
reexport `getEthereumDefinitions` in `connect/src/api/index.ts` and use `TrezorConnect.getEthereumDefinitions`

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputElement.tsx [hunk 3]
```diff
@@ -187,11 +187,16 @@ export const TransactionReviewOutputElement = forwardRef<
                                             <FormattedCryptoAmount
                                                 disableHiddenPlaceholder
                                                 value={line.value}
-                                                symbol={cryptoSymbol}
+                                                symbol={
+                                                    line.id !== 'fee' && token
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputElement.tsx:192]: nit: 
I don't like this condition much.
Maybe add at least a comment? Something like
`// tx fee is always paid in network native coin`

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx [hunk 4]
```diff
@@ -28,6 +34,64 @@ type TransactionReviewTotalOutputProps = Omit<
...
 >;
 
+const getLines = (
+    device: TrezorDevice,
+    networkType: TransactionReviewOutputListProps['account']['networkType'],
+    symbol: TransactionReviewOutputListProps['account']['symbol'],
+    precomposedTx: TransactionReviewOutputListProps['precomposedTx'],
+): Array<OutputElementLine> => {
+    const isUpdatedSendFlow = getIsUpdatedSendFlow(device);
+    const isWithUpdatedEthereumSendFlow = getIsUpdatedEthereumSendFlow(device, networkType);
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx]:
```suggestion
    const isUpdatedEthereumSendFlow = getIsUpdatedEthereumSendFlow(device, networkType);
```

File: packages/suite/src/utils/wallet/reviewTransactionUtils.ts [hunk 5]
```diff
@@ -23,6 +23,19 @@ export const getIsUpdatedSendFlow = (device: TrezorDevice) => {
...
 
+export const getIsUpdatedEthereumSendFlow = (
+    device: TrezorDevice,
+    network: Account['networkType'],
+) => {
+    if (network !== 'ethereum') return false;
+
+    const firmwareVersion = getFirmwareVersion(device);
+
+    const isWithUpdatedEthereumSendFlow = versionUtils.isNewerOrEqual(firmwareVersion, '2.6.1');
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/reviewTransactionUtils.ts]:
```suggestion
    // publicly introduced in 2.6.3, versions 2.6.1 and 2.6.2 we just internal
    const isWithUpdatedEthereumSendFlow = versionUtils.isNewer(firmwareVersion, '2.6.0');
```

File: packages/suite/src/utils/wallet/reviewTransactionUtils.ts [hunk 6]
```diff
@@ -175,11 +188,13 @@ const constructNewFlow = ({
...
     account,
     precomposedForm,
-}: Omit<ConstructOutputsParams, 'device'>) => {
+    device,
+}: ConstructOutputsParams) => {
     const outputs: ReviewOutput[] = [];
 
     const isCardano = isCardanoTx(account, precomposedTx);
     const { networkType } = account;
+    const isWithUpdatedEthereumSendFlow = getIsUpdatedEthereumSendFlow(device, networkType);
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/reviewTransactionUtils.ts]:
```suggestion
    const isUpdatedEthereumSendFlow = getIsUpdatedEthereumSendFlow(device, networkType);
```

The previous version is called `isUpdatedSendFlow` is our codebase

File: packages/suite/src/utils/wallet/reviewTransactionUtils.ts [hunk 7]
```diff
@@ -281,7 +299,9 @@ const constructNewFlow = ({
 export const constructOutputs = ({ device, ...params }: ConstructOutputsParams) => {
     const isWithUpdatedSendFlow = getIsUpdatedSendFlow(device);
 
-    const outputs = isWithUpdatedSendFlow ? constructNewFlow(params) : constructOldFlow(params);
+    const outputs = isWithUpdatedSendFlow
+        ? constructNewFlow({ device, ...params })
+        : constructOldFlow(params);
 
     return outputs;
```
Comment (tomasklim) [inline packages/suite/src/utils/wallet/reviewTransactionUtils.ts]: nit: 
I would prefer something like this, but it is your chose

```
export const constructOutputs = ({ device, ...params }: ConstructOutputsParams) => {
    const isUpdatedSendFlow = getIsUpdatedSendFlow(device); // >= 2.6.0
    const isUpdatedEthereumSendFlow = getIsEthereumUpdatedSendFlow(device); // > 2.6.0

    if (isUpdatedSendFlow) {
        return constructNewFlow({...params, isUpdatedEthereumSendFlow})
    }
    
    return constructOldFlow(params);
```

**Review by tomasklim — CHANGES_REQUESTED** [review]
just nits, going to check how it actually works

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputElement.tsx [hunk 8]
```diff
@@ -187,11 +187,16 @@ export const TransactionReviewOutputElement = forwardRef<
...
+                                                        ? token.symbol
+                                                        : cryptoSymbol
+                                                }
                                             />
                                         )}
                                     </OutputValueWrapper>
-                                    {fiatVisible && (
+                                    {/* temporary solution until fiat value for ERC20 tokens will be fixed  */}
+                                    {fiatVisible && !(line.id !== 'fee' && token) && (
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputElement.tsx:200]: Hide it instead of showing `0.00` (or add sign `<0.01`. Probably for another issue, it also depends on currency)
Screenshot 2023-10-31 at 10 31 18

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 2 above)
Comment (matejkriz) [reply packages/suite/src/actions/wallet/sendFormActions.ts:4]: we don't want to do that, right @mroz22? It's not meant to be part of public connect API...

**Review by tomasklim — APPROVED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputElement.tsx (hunk 8 above)
Comment (matejkriz) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputElement.tsx:200]: let's not touch this, it's not in the lates flow anymore

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 2 above)
Comment (mroz22) [reply packages/suite/src/actions/wallet/sendFormActions.ts:4]: not public but suite is not public so imho ok until we find a better way

**Comment by bosomt** [comment]
https://www.notion.so/satoshilabs/eth-send-flow-7e8280cb08e548b79d72ad70b7ea5d9d?pvs=4

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/actions/wallet/sendFormActions.ts:4]: @matejkriz because of this, we are bundling part of connect to the main app including protobuf
Screenshot 2023-11-22 at 17 08 53
