### PR TITLE
Fix: Tor notifications improvements

### LINKED ISSUE #7436: Multiple tor notifications displayed in the same time
image

### PR DESCRIPTION
**Pull request by karliatto**
## Description
* a35d7affab4c9080832ae6cff092058e297e5fb9 - creates new action for notifications that close notification if there is one with same type visible.
* dd09cbe3bb30c9d2242cc8f75c804a2890f59f71 - use addToastOnce when Tor gets notification that it is slow. So the UI does not display many Toast messages with the same information at once.

Closes https://github.com/trezor/trezor-suite/issues/7436

### CODE REVIEW

File: suite-common/toast-notifications/src/notificationsActions.ts [hunk 1]
```diff
@@ -37,6 +43,15 @@ export const addToast = createActionWithExtraDeps(
     }),
 );
 
+// Adds a Toast if there is not one of same type visible.
```
Comment (matejkriz) [inline suite-common/toast-notifications/src/notificationsActions.ts:41]: The comment is misleading, it adds the toast and just close all with the same type. I don't think it's the desired behaviour, check the video where I simulated `tor-is-slow` once per second:

https://user-images.githubusercontent.com/3729633/213138548-26d66412-1d03-41fb-a65b-c5cd5b709bfb.mov

Comment (karliatto) [reply suite-common/toast-notifications/src/notificationsActions.ts:41]: Ahh yes, the comment is from the first approach I took, it is wrong.
But then I thought that it is probably better to show a new popup when Tor is still being misbehaving. The idea was to have only one but to keep it there while it is misbehaving. 

But I am not really sure what the behavior should be.

Comment (sime) [reply suite-common/toast-notifications/src/notificationsActions.ts:41]: I have come into a situation that replicates the above video.

When a notification is open, do not display another.

Comment (karliatto) [reply suite-common/toast-notifications/src/notificationsActions.ts:41]: @matejkriz done https://github.com/trezor/trezor-suite/pull/7397/commits/8ac2d0638bfc2807405d3d3c5451c3dcd48a5893

**Review by matejkriz — APPROVED** [review]

**Comment by matejkriz** [comment]
@karliatto There are some conflicts during rebase, please rebase manually 🙏 Next step for the rebasing bot would be to add comment if failed...
