### PR TITLE
fix: prevent coinjoin account from starting discovery if Tor is disable

### LINKED ISSUE #7485: Noisy coinjoin notification for remember wallet with no Tor connection
**Describe the bug**
Noisy notification about `Coinjoin client not enabled`

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Version 23.2.0 (23.2.0.25186)
-   OS: name, OSX

**How to reproduce**
1. Enable coinjoin account
2. Disable Tor
3. Restart suite

**Expected behavior**
Fail silently.

**Screenshots**
Screenshot 2023-01-30 at 9 57 06

### PR DESCRIPTION
**Pull request by karliatto**
## Description
When starting app with remember coinjoin account and Tor disable, the discovery is going to start with a Noisy coinjoin notification. This PR prevents coinjoin account discovery from starting if Tor is not enable.

* 20a8390d50bd233a5a52fda50b6a77e4c4cd70c8 - new selector that allow select Tor is disable for coinjoin without account.
* b96e81290b09049fbd9c8b6d960b416c94b5ce99 - preventing coinjoin discovery start when Tor is disable for coinjoin.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/7485

### CODE REVIEW

File: packages/suite/src/reducers/wallet/coinjoinReducer.ts [hunk 1]
```diff
@@ -498,7 +498,17 @@ export const selectCurrentTargetAnonymity = memoize((state: CoinjoinRootState) =
...
+    const { isTorEnabled } = selectTorState(state);
+
+    if (state.wallet.coinjoin.debug?.coinjoinAllowNoTor) {
+        return false;
+    }
+
+    return !isTorEnabled;
+});
+
+export const selectIsCoinjoinSelectedAccountBlockedByTor = memoize((state: CoinjoinRootState) => {
```
Comment (komret) [inline packages/suite/src/reducers/wallet/coinjoinReducer.ts:511]: Good. FYI, I am taking this a step further in https://github.com/trezor/trezor-suite/pull/7587/commits/e3da67785aac6dcdfb4f632cf3220a1d1780b691 and remove the selector for selected account.

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts [hunk 2]
```diff
@@ -119,22 +119,30 @@ export const coinjoinMiddleware =
...
-                coinjoinAccounts.forEach(a =>
-                    api.dispatch(coinjoinAccountActions.fetchAndUpdateAccount(a)),
+            const state = api.getState();
+            const isCoinjoinGloballyBlockedByTor = selectIsCoinjoinGloballyBlockedByTor(state);
+            if (!isCoinjoinGloballyBlockedByTor) {
+                // find all coinjoin accounts
+                const coinjoinAccounts = state.wallet.accounts.filter(
+                    a => a.accountType === 'coinjoin',
                 );
+                if (coinjoinAccounts.length > 0) {
```
Comment (komret) [inline packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: This line is redundant.

File: packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts [hunk 3]
```diff
@@ -143,16 +151,20 @@ export const coinjoinMiddleware =
...
+            const state = api.getState();
+            const { symbol } = action.payload;
+            const isCoinjoinGloballyBlockedByTor = selectIsCoinjoinGloballyBlockedByTor(state);
+            if (!isCoinjoinGloballyBlockedByTor) {
+                const { accounts } = state.wallet;
+                // find all coinjoin accounts for network
+                const coinjoinAccounts = accounts.filter(
+                    a => a.accountType === 'coinjoin' && a.symbol === symbol,
                 );
+                if (coinjoinAccounts.length > 0) {
```
Comment (komret) [inline packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts]: Redundant as above.

**Review by komret — APPROVED** [review]

**Review by komret — APPROVED** [review]
I added a test suite for `coinjoinMiddleware` in #7587, you might want to add some tests once it is merged.
