### PR TITLE
fix(coinmarket): Fix fetching all contract txs for solana

### LINKED ISSUE #11418: It is not possible to do exchange from USDT@MATIC to USDT@ETH
**Describe the bug**
It seems that the detection of the same symbol in the from and to does not respect different platforms.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by FreeWall**
Trade section uses contract address to estimate fees more precisely. That doesn't work for solana - it tries to fetch all txs of the contract, see [getSignaturesForAddress](https://github.com/trezor/trezor-suite/blob/develop/packages/blockchain-link/src/workers/solana/index.ts#L51)

## Related Issue

Resolve #11418

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx [hunk 1]
```diff
@@ -62,18 +62,20 @@ const SendCryptoSelect = () => {
                         setAmountLimits(undefined);
                         setValue(CRYPTO_INPUT, '');
                         setValue(FIAT_INPUT, '');
+                        setValue('outputs.0.address', account.descriptor);
                         const token = selected.value;
                         const invitySymbol = invityApiSymbolToSymbol(token).toLowerCase();
                         const tokenData = tokens?.find(t => t.symbol === invitySymbol);
                         if (ethereumTypeNetworkSymbols.includes(token)) {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx:68]: Please create another fork for solana networks, this solution makes it even more complicated than it is.

Remove setValue added on line 65 and do
If (ethereum)
else if (solana)
else

Comment (FreeWall) [reply packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx:68]: https://github.com/trezor/trezor-suite/pull/11602/commits/0f5e6114ac1d80b9aa50e4977158bbaaabbb1f18

**Review by tomasklim — APPROVED** [review]

**Review by tomasklim — APPROVED** [review]
