### PR TITLE
Fix/device bt connection

### LINKED ISSUE #22393: Device not connected after successful BT pairing
Seems to happen randomly on desktop, observed on Mac and WIN. Trezor shows "Connected", Suite does not see it.

[Video](https://www.notion.so/satoshilabs/287dc526060680f0b938d7d884fc3c42)

### PR DESCRIPTION
**Pull request by OriginalEveres**
In some cases a device in `connecting` state does not update regularly (and sometimes does).

Because of that, we do not filter unresponsive devices in connecting state.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22393

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/device-bt-connection&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/device-bt-connection&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/device-bt-connection&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/connection/hook/useBluetoothConnection.tsx [hunk 1]
```diff
@@ -40,12 +40,12 @@ export const useBluetoothConnection = ({
...
 
     const notConnectedKnownDevices = useMemo(
-        () => knownDevices.filter(device => device.connectionStatus.type === 'disconnected'),
+        () => knownDevices.filter(device => !device.connected),
         [knownDevices],
     );
 
     const notConnectedNearbyDevices = useMemo(
-        () => devices.filter(device => device.connectionStatus.type === 'disconnected'),
+        () => devices.filter(device => !device.connected),
```
Comment (Lemonexe) [inline packages/suite/src/components/connection/hook/useBluetoothConnection.tsx]: I don't understand how this can fix anything.
`connected` should be equivalent to 'paired', 'pairing', 'connecting', 'connected'
So `!connected` is only 'disconnected' and 'pairing-error'
This only covers the error additionally..

Which led me to this small fix btw:
https://github.com/trezor/trezor-suite/pull/22427

**Review by Lemonexe — APPROVED** [review]
Looks good to me, but I don't know if it will fix anything. Also review from @komret needed.

File: packages/suite/src/actions/bluetooth/filterOutNonResponsiveDevices.ts [hunk 2]
```diff
@@ -1,9 +1,17 @@
...
+import type {
+    BluetoothDeviceCommon,
+    DeviceBluetoothConnectionStatusType,
+} from '@suite-common/bluetooth/src/types';
 import { isLinux } from '@trezor/env-utils';
 
 export const NEARBY_DEVICES_LAST_UPDATED_LIMIT = 3_000;
 export const NEARBY_DEVICES_LAST_UPDATED_LIMIT_LINUX = 5_000;
 
+const CONNECTION_STATUES_TO_KEEP: DeviceBluetoothConnectionStatusType[] = [
```
Comment (komret) [inline packages/suite/src/actions/bluetooth/filterOutNonResponsiveDevices.ts]: typo

Comment (Lemonexe) [reply packages/suite/src/actions/bluetooth/filterOutNonResponsiveDevices.ts]: :statue_of_liberty: :moyai:

File: packages/suite/src/components/connection/hook/useBluetoothConnection.tsx (hunk 1 above)
Comment (OriginalEveres) [reply packages/suite/src/components/connection/hook/useBluetoothConnection.tsx]: these changes were dropped fyi

**Review by Lemonexe — APPROVED** [review]

**Comment by komret** [comment]
@OriginalEveres squash the commits please because the second is just undoing a change from the first.
