### PR TITLE
fix: skip PIN onboarding step when it is not needed

### LINKED ISSUE #24468: Skip "Set a PIN" in onboarding if PIN is already set
Background - Following issue reported by TEX:
- "We’ve noticed in several TS7 TEX sessions that some users set their PIN directly on the device instead of following the PIN prompt in Trezor Suite. When they then continue through Suite’s onboarding flow, the device prompts them to change the PIN they have just set, which leads to user confusion." 
- The above only applies when connecting via cable. It is already handled with Bluetooth, where the whole step is skipped if PIN is already set. 

Requirements
- During onboarding check if PIN is already set and if yes then skip the "Set a Pin" step in the onboarding flow
- Align the behavior for across cable and bluetooth
- We should check what happens if you go to that step and set PIN before pressing the button.

### PR DESCRIPTION
**Pull request by vojtatranta**
## Description

For THP devices, it makes sure that onboarding skips the PIN step when the PIN is alreyd set on the device.

For **cable USB** connection, it doesnt skip the PIN, because at that moment, there isn't such update event comming.

## Notes for QA

When you create a wallet in onboarding and then you set the PIN on the device, after going through / skipping backup, you should go right to the COIN selection

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/24468#issuecomment-3835035713

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=24468-skip-pin-onboarding-when-not-needed&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=24468-skip-pin-onboarding-when-not-needed&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=24468-skip-pin-onboarding-when-not-needed&lookback=7)

### CODE REVIEW

File: packages/suite/src/utils/onboarding/steps.ts [hunk 1]
```diff
@@ -36,6 +41,16 @@ export const isStepUsed = (step: Step, props: IsStepUsedProps): boolean => {
...
     const firmwareVersion = getFirmwareVersion(device);
 
+    if (step.id === ID_SET_PIN_STEP) {
+        // Skip PIN setup step if device already has PIN protection enabled
+        return !device?.features?.pin_protection;
+    }
+
+    if (step.id === ID_BACKUP_STEP) {
+        // Skip backup step if device doesn't need backup (already backed up)
+        return !isDeviceBackupRequired(device);
```
Comment (vojtatranta) [inline packages/suite/src/utils/onboarding/steps.ts]: I have consulted with @marekrjpolak that to make it wor for all connection (including USB cabel) we would have to call `connect.getFeatures()` which is an async call. 

This kinda sucks because I'd have to make some calls async and going to the onboarding screens wouldn't be smooth.

File: packages/suite/src/utils/onboarding/steps.ts [hunk 2]
```diff
@@ -36,6 +41,16 @@ export const isStepUsed = (step: Step, props: IsStepUsedProps): boolean => {
     const deviceModelInternal = device?.features?.internal_model;
     const firmwareVersion = getFirmwareVersion(device);
 
+    if (step.id === ID_SET_PIN_STEP) {
+        // Skip PIN setup step if device already has PIN protection enabled
+        return !device?.features?.pin_protection;
```
Comment (vojtatranta) [inline packages/suite/src/utils/onboarding/steps.ts]: We skip PIN setup when the `pin_protection=true`

File: packages/suite/src/utils/onboarding/steps.ts [hunk 3]
```diff
@@ -36,6 +41,16 @@ export const isStepUsed = (step: Step, props: IsStepUsedProps): boolean => {
...
+    }
+
+    if (step.id === ID_BACKUP_STEP) {
```
Comment (vojtatranta) [inline packages/suite/src/utils/onboarding/steps.ts]: We skip the `BACKUP` step if backup IS NOT required

File: packages/suite/src/components/onboarding/SkipStepConfirmation.tsx [hunk 4]
```diff
@@ -32,7 +32,6 @@ const getModalContent = (activeStepId: AnyStepId): SkipModalContent => {
                 heading: <Translation id="TR_SKIP_BACKUP" />,
                 secondaryButtonText: <Translation id="TR_SKIP_BACKUP" />,
                 body: <Translation id="TR_SKIP_BACKUP_DESCRIPTION" />,
-                nextStep: STEP.ID_SET_PIN_STEP,
```
Comment (vojtatranta) [inline packages/suite/src/components/onboarding/SkipStepConfirmation.tsx:35]: This was hardcoced and had to be deleted to let the onboarding process decide on its own.

**Comment by vojtatranta** [comment]
@trezor/suite-growth pls test

File: packages/suite/src/utils/onboarding/steps.ts [hunk 5]
```diff
@@ -87,13 +92,53 @@ export const isStepUsed = (step: Step, props: IsStepUsedProps): boolean => {
...
+    }
+
+    if (nextStep.id === ID_SET_PIN_STEP && device) {
+        // Skip PIN setup step only if device has PIN protection explicitly enabled
+        if (device?.features?.pin_protection === true) {
+            return getAccessibleStep(steps[currentIndex + 1]?.id, steps, device);
+        }
+    }
+
+    if (nextStep.id === ID_BACKUP_STEP && device) {
```
Comment (vojtatranta) [inline packages/suite/src/utils/onboarding/steps.ts]: I believe that this is basically useless, this may no occur ever.

File: packages/suite/src/utils/onboarding/steps.ts [hunk 6]
```diff
@@ -87,13 +92,53 @@ export const isStepUsed = (step: Step, props: IsStepUsedProps): boolean => {
...
+) => {
     const currentIndex = steps.findIndex((step: Step) => step.id === currentStepId);
-    if (!steps[currentIndex + 1]) {
+
+    if (currentIndex === -1) {
         return null;
     }
 
-    return steps[currentIndex + 1];
+    return getAccessibleStep(steps[currentIndex + 1]?.id ?? null, steps, device);
```
Comment (Lemonexe) [inline packages/suite/src/utils/onboarding/steps.ts]: nit: pls extract `const nextStepId = steps[currentIndex + 1]?.id ?? null` for better readability of this line

File: packages/suite/src/actions/onboarding/onboardingActions.ts [hunk 7]
```diff
@@ -176,6 +183,15 @@ const beginOnboardingTutorial = () => async (dispatch: Dispatch, getState: GetSt
     dispatch(goToNextStep());
 };
 
+const getSkippedStepId =
```
Comment (Lemonexe) [inline packages/suite/src/actions/onboarding/onboardingActions.ts]: this shouldn't be named skipped step, if it returns accessible step, it's flipped around.

File: packages/suite/src/actions/onboarding/onboardingActions.ts [hunk 8]
```diff
@@ -176,6 +183,15 @@ const beginOnboardingTutorial = () => async (dispatch: Dispatch, getState: GetSt
...
+    (skippedToStepId: AnyStepId) => (_dispatch: Dispatch, getState: GetState) => {
+        const device = selectSelectedDevice(getState());
+        const stepsInPath = getAllStepsInPath(getState);
+        const skippedStep = getAccessibleStep(skippedToStepId, stepsInPath, device ?? null);
```
Comment (Lemonexe) [inline packages/suite/src/actions/onboarding/onboardingActions.ts]: same here

File: packages/suite/src/utils/onboarding/steps.ts [hunk 9]
```diff
@@ -87,13 +92,53 @@ export const isStepUsed = (step: Step, props: IsStepUsedProps): boolean => {
...
+        // Skip backup step if device doesn't need backup (already backed up)
+        if (!isDeviceBackupRequired(device)) {
+            return getAccessibleStep(steps[currentIndex + 1]?.id, steps, device);
+        }
+    }
+
+    return nextStep;
+};
+
+export const findNextStep = (
```
Comment (Lemonexe) [inline packages/suite/src/utils/onboarding/steps.ts:120]:
```suggestion
// Calculates the next step given the current step Id
export const findNextStep = (
```

File: packages/suite/src/utils/onboarding/steps.ts [hunk 10]
```diff
@@ -87,13 +92,53 @@ export const isStepUsed = (step: Step, props: IsStepUsedProps): boolean => {
 export const isStepCategoryUsed = (stepCategory: StepCategory, props: IsStepUsedProps): boolean =>
     stepCategory.steps.some(step => isStepUsed(step, props));
 
-export const findNextStep = (currentStepId: AnyStepId, steps: Step[]): Step | null => {
+export const getAccessibleStep = (
```
Comment (Lemonexe) [inline packages/suite/src/utils/onboarding/steps.ts]: I'd rename and add comment.
It's difficult to name it, but `resolve` is good I think
(like resolving url or path – it validates it, or returns what should be)
```suggestion
// Validates if Id of the next step is available, or returns the earliest next available step
export const resolveNextAvailableStep = (
```

**Review by Lemonexe — APPROVED** [review]
LGTM.
It complicates things a bit, there might be a way to include this logic in `isStepUsed` instead, but I don't see how, given that this changes dynamically.
Current planning of steps is done ahead, statically 🤔 

Some nits to rename

File: packages/suite/src/utils/onboarding/steps.ts (hunk 5 above)
Comment (vojtatranta) [reply packages/suite/src/utils/onboarding/steps.ts]: yes it is useless

**Comment by vojtatranta** [comment]
fingers crossed, merging kindy asking QA , thanks

**Comment by zako05** [comment]
QA OK ✅

* T7(THP) onboarding - wallet recovery - enter PIN skipped ✅
* T7(THP) onboarding - create wallet - backup  - enter PIN skipped ❌
  * after finishing wallet backup, the button 'continue to PIN' appears, and after click the button, user is navigate to the COIN page
  * there shouldn't be any button, and user should be navigate straight to the COIN page

https://github.com/user-attachments/assets/ec41f7ad-1dba-4d58-9ad2-a29812df9814

* T7(THP) onboarding - [create wallet - backup skipped - enter PIN skipped ](https://github.com/user-attachments/assets/c7f949bd-a2c9-44a7-8a80-2b710017c886) ✅
* T7(Cabel) onboarding - wallet recovery - enter PIN ✅
  * [set PIN - on device appears 'Change PIN?': skip / continue](https://github.com/user-attachments/assets/eedae7ff-6a95-4932-a5ee-d980d71a0d3b)
  * [skip - continue on the COIN page](https://github.com/user-attachments/assets/0dc85dcd-70d8-4830-b8a4-31174ccd7db4)
* T7(Cabel) onboarding - wallet recovery skipped ✅
