### PR TITLE
fix(suite-native): Trading: Fix preview screen footer

### LINKED ISSUE #24759: Trading mobile: Wrong trading footer on preview step
**Describe the bug**
Footer on trading preview screen does not explicitly mention provider.

**Info:**

- Mobile Suite Version: version/commit
- OS: name, version

**How to reproduce**

1. Go to trading sell / exchange
1. Fill form and confirm
1. On preview screen check footer/

**Current behavior**
Footer 

**Expected behavior**
Footer should contain "It's governed by XXX's Terms and Conditions"

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by jbazant**
## Description

Fixes the footer on preview screen. Instead of general one, footer with selected provider is displayed.

## Related Issue

Resolve #24759 
### Before
Simulator Screenshot - iPhone 16e - 2026-01-28 at 11 48 04

### After
Simulator Screenshot - iPhone 16e - 2026-01-28 at 14 12 39

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=24759-trading-mobile-wrong-trading-footer-on-preview-step&lookback=7)

### CODE REVIEW

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/module-trading/src/hooks/general/form/useProviderMetadataChangeEffect.ts [hunk 1]
```diff
@@ -16,17 +18,24 @@ export const useProviderMetadataChangeEffect = (
...
 
     const providerMetadata = useSelector((state: TradingRootState) =>
         selectTradingProviderByNameAndTradeType(state, exchange, tradingType),
     );
     const currentProviderMetadata = useSelector(selectTradingProviderMetadata);
 
     useEffect(() => {
-        if (providerMetadata !== currentProviderMetadata) {
-            dispatch(tradingActions.setCurrentProviderMetadata(providerMetadata));
+        if (!isFocused) {
```
Comment (vytick) [inline suite-native/module-trading/src/hooks/general/form/useProviderMetadataChangeEffect.ts:32]: I don't get it. Can you add comment why is this here?

**Review by vytick — APPROVED** [review]
lgtm
