### PR TITLE
fix: incorrect PIN message for ininitialized device during onboarding FW install

### LINKED ISSUE #16771: Dont ask for Restarting Trezor. Enter PIN if prompted. during onboarding of fresh device
**Describe the bug**
Dont ask for `Restarting Trezor. Enter PIN if prompted.` during onboarding of fresh device

**Steps to reproduce:**
1. Connect new/empty device
2. Proceed with onboarding 
3. Check `Enter PIN if prompted.` during restart of device before PIn setup

**Info:**
 - Suite version: web 25.2.0 (e948e70ab2052662e7244da234e5416bed64ba46)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.8 regular (revision bbcb920213b0ab847a2fedf825eac70652e33279)
 - Transport: WebUsbTransport

**Screenshots:**

Image

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolve: https://github.com/trezor/trezor-suite/issues/16771

image

@coderabbitai ignore

### CODE REVIEW

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 1]
```diff
@@ -25,12 +25,13 @@ interface FirmwareInstallationProps {
     cachedDevice?: TrezorDevice;
     // This component is shared between Onboarding flow and standalone fw update modal with few minor UI changes
     // If it is set to true, then you know it is being rendered in standalone fw update modal
-    standaloneFwUpdate?: boolean;
+    standaloneFwUpdate?: boolean; // Todo: The above is no longer TRUE!!! ask Komar many of above is not used anymore
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx]: @komret lets discuss this more :point_up:

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 2]
```diff
@@ -22,23 +21,15 @@ const SelectDevice = styled.div`
 `;
 
 interface FirmwareInstallationProps {
-    cachedDevice?: TrezorDevice;
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx:25]: unused

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 3]
```diff
@@ -22,23 +21,15 @@ const SelectDevice = styled.div`
...
-    // This component is shared between Onboarding flow and standalone fw update modal with few minor UI changes
-    // If it is set to true, then you know it is being rendered in standalone fw update modal
-    standaloneFwUpdate?: boolean;
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx:28]: unused

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 4]
```diff
@@ -22,23 +21,15 @@ const SelectDevice = styled.div`
...
-    // If true, information about new version is not shown, because we don't know anything about it
-    customFirmware?: boolean;
     install: () => void;
-    onPromptClose?: () => void;
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx:32]: unused

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 5]
```diff
@@ -22,23 +21,15 @@ const SelectDevice = styled.div`
 `;
 
 interface FirmwareInstallationProps {
-    cachedDevice?: TrezorDevice;
-    // This component is shared between Onboarding flow and standalone fw update modal with few minor UI changes
-    // If it is set to true, then you know it is being rendered in standalone fw update modal
-    standaloneFwUpdate?: boolean;
-    // If true, information about new version is not shown, because we don't know anything about it
-    customFirmware?: boolean;
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx:30]: unused

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 6]
```diff
@@ -72,27 +61,25 @@ export const FirmwareInstallation = ({
                     onClick={onSuccess}
                     data-testid="@firmware/continue-button"
                 >
-                    <Translation id={standaloneFwUpdate ? 'TR_CLOSE' : 'TR_CONTINUE'} />
+                    <Translation id="TR_CLOSE" />
```
Comment (komret) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx]: This is used in onboarding (i.e. not standalone), so the button should say "Continue", not "Close".

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 7]
```diff
@@ -72,27 +61,25 @@ export const FirmwareInstallation = ({
...
             <OnboardingStepBox
                 image="FIRMWARE"
                 heading={<Translation id="TR_INSTALL_FIRMWARE" />}
                 device={undefined}
                 isActionAbortable={isActionAbortable}
                 innerActions={getInnerActionComponent()}
-                nested={!!standaloneFwUpdate}
-                disableConfirmWrapper={!!standaloneFwUpdate}
+                nested={false}
+                disableConfirmWrapper={false}
```
Comment (komret) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx]: These could be just omitted, they are nullable.

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx [hunk 8]
```diff
@@ -72,27 +61,25 @@ export const FirmwareInstallation = ({
...
             >
-                <FirmwareOffer isCustomFirmware={customFirmware} targetFirmwareType={targetType} />
+                <FirmwareOffer isCustomFirmware={false} targetFirmwareType={targetType} />
```
Comment (komret) [inline packages/suite/src/components/firmware/FirmwareInstallation.tsx:75]: `isCustomFirmware` could also be omitted.

File: packages/suite/src/views/onboarding/steps/FirmwareStep.tsx [hunk 9]
```diff
@@ -113,7 +113,11 @@ export const FirmwareStep = () => {
         case 'started': // called from firmwareUpdate()
         case 'done':
             return (
-                <FirmwareInstallation install={install} onSuccess={goToNextStepAndResetReducer} />
+                <FirmwareInstallation
+                    install={install}
+                    onSuccess={goToNextStepAndResetReducer}
+                    isFirstInstallation={true}
```
Comment (komret) [inline packages/suite/src/views/onboarding/steps/FirmwareStep.tsx]: This is always true here, so it can be declared inside `FirmwareInstallation`.

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx (hunk 1 above)
Comment (komret) [reply packages/suite/src/components/firmware/FirmwareInstallation.tsx]: This was forgotten here in https://github.com/trezor/trezor-suite/pull/17359.

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx [hunk 10]
```diff
@@ -12,27 +12,34 @@ const Percentage = styled.div`
...
-    NonNullable<FirmwareOperationStatus['operation']>,
-    TranslationKey
-> = {
-    installing: 'TR_INSTALLING',
-    validating: 'TR_VALIDATION',
-    restarting: 'TR_WAIT_FOR_REBOOT',
-    completed: 'TR_FIRMWARE_STATUS_INSTALLATION_COMPLETED',
+type FirmwareProgressBarProps = {
+    // In onboarding, the device is not initialized (no seed) yet, for example: there is no PIN during restart
+    isFirstInstallation: boolean;
```
Comment (komret) [inline packages/suite/src/components/firmware/FirmwareProgressBar.tsx]: I think it would be better for this component to check `onboarding.isActive` rather than accept a prop.

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx (hunk 8 above)
Comment (peter-sanderson) [reply packages/suite/src/components/firmware/FirmwareInstallation.tsx:75]: Todo: rname to `FirmwareInstallationOnboarding` and move to the onboarding code next to FirmwareStep into onboarding code)

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx (hunk 6 above)
Comment (peter-sanderson) [reply packages/suite/src/components/firmware/FirmwareInstallation.tsx]: done :+1:

File: packages/suite/src/components/firmware/FirmwareProgressBar.tsx (hunk 10 above)
Comment (peter-sanderson) [reply packages/suite/src/components/firmware/FirmwareProgressBar.tsx]: Done

File: packages/suite/src/views/onboarding/steps/FirmwareStep.tsx (hunk 9 above)
Comment (peter-sanderson) [reply packages/suite/src/views/onboarding/steps/FirmwareStep.tsx]: done

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx (hunk 8 above)
Comment (peter-sanderson) [reply packages/suite/src/components/firmware/FirmwareInstallation.tsx:75]: done

File: packages/suite/src/components/firmware/FirmwareInstallation.tsx (hunk 7 above)
Comment (peter-sanderson) [reply packages/suite/src/components/firmware/FirmwareInstallation.tsx]: done

**Review by komret — APPROVED** [review]
Please use fixups next time 🙏
