### PR TITLE
Fix 1 min timeout for fetching new token info 

### LINKED ISSUE #15493: It takes up to 1 minute to fetch rates for newly received token
**Describe the bug**

When you receive a token which was not have on an account before, it takes up to 1 minute to have fiat rates and 7d change ready

Related to #16127

**Info:**

-   Suite Version: 24.11.2

**Screenshots**
Screenshot 2024-11-21 at 8 35 45

### PR DESCRIPTION
**Pull request by enjojoy**
## Description

- Now the newly received token data is being fetched instantly, instead of waiting for the 1 min 
timeout

- Token added through "Add token" also fetches last week rates to display the change 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/15493

## Screenshots:
Receive new token Before:

https://github.com/user-attachments/assets/46455a99-ef29-43aa-a6b3-139c9d1eca4c

Receive new token After:

https://github.com/user-attachments/assets/49b8d9cd-6ff5-47d3-83a4-4563de40bfaf

Add token Before:

https://github.com/user-attachments/assets/e793194b-9177-4862-82ee-1c6bd6b582d8

Add token After:

https://github.com/user-attachments/assets/58857c4e-5c8e-45be-a8cc-22c293431f10

### CODE REVIEW

**Review by izmy — APPROVED** [review]

File: packages/suite/src/actions/wallet/tokenActions.ts [hunk 1]
```diff
@@ -33,6 +33,21 @@ export const addToken =
             }),
         );
 
+        dispatch(
```
Comment (tomasklim) [inline packages/suite/src/actions/wallet/tokenActions.ts]: does this need to be here? You update account on line 14, so it should be caught by your modification in `accountUtils`

**Review by tomasklim — CHANGES_REQUESTED** [review]
Tested again and it works, weird.

However, you do not need to fix add token, it will start working automatically by your fix

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 2]
```diff
@@ -734,6 +734,7 @@ export const isAccountOutdated = (account: Account, freshInfo: AccountInfo) => {
             return (
                 freshInfo.misc!.nonce !== account.misc.nonce ||
                 freshInfo.balance !== account.balance || // balance can change because of beacon chain txs (staking) |
+                freshInfo.tokens !== account.tokens ||
                 JSON.stringify(freshInfo?.misc?.stakingPools) !==
                     JSON.stringify(account?.misc?.stakingPools)
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: probably it would be better to compare string instead of object, maybe that's why it sometimes work and sometimes not.

Please get inspired by lines for staking

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 3]
```diff
@@ -734,6 +734,7 @@ export const isAccountOutdated = (account: Account, freshInfo: AccountInfo) => {
             return (
                 freshInfo.misc!.nonce !== account.misc.nonce ||
                 freshInfo.balance !== account.balance || // balance can change because of beacon chain txs (staking) |
+                freshInfo.tokens !== account.tokens ||
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: Please fix it for all token networks. This fix is only for EVM

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 4]
```diff
@@ -744,11 +753,14 @@ export const isAccountOutdated = (account: Account, freshInfo: AccountInfo) => {
...
                 // changed stake pool
-                freshInfo.misc!.staking?.poolId !== account.misc.staking.poolId
+                freshInfo.misc!.staking?.poolId !== account.misc.staking.poolId ||
+                areDifferentTokens()
             );
         case 'solana':
             // compare last transaction signature since the total number of txs may not be fetched fully
-            return freshInfo.history.txids?.[0] !== account.history.txids?.[0];
+            return (
+                freshInfo.history.txids?.[0] !== account.history.txids?.[0] || areDifferentTokens()
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: I am thinking now, maybe it is not required for Solana and Cardano :( can you try to remove it and test it?

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 5]
```diff
@@ -708,6 +708,14 @@ export const getTotalFiatBalance = ({
 export const isTestnet = (symbol: NetworkSymbol) => networks[symbol].testnet;
 
 export const isAccountOutdated = (account: Account, freshInfo: AccountInfo) => {
+    const isDifferentBalance = () => {
+        return account.balance !== freshInfo.balance;
+    };
+
+    const areDifferentTokens = () => {
+        return JSON.stringify(account.tokens) !== JSON.stringify(freshInfo.tokens);
```
Comment (Nodonisko) [inline suite-common/wallet-utils/src/accountUtils.ts]: JSON operation are very expensive and this function could run very often and I think `tokens` could be really huge if account has lot of tokens. I am pretty sure it will have negative perf impact on mobile for bigger accounts.

What about using just `account.tokens.length !== freshInfo.tokens.length` ?

Comment (tomasklim) [reply suite-common/wallet-utils/src/accountUtils.ts]: it's possible for networks using blockbook, not for non-blockbook

File: suite-common/wallet-utils/src/accountUtils.ts (hunk 4 above)
Comment (tomasklim) [reply suite-common/wallet-utils/src/accountUtils.ts]: Screenshot 2025-01-09 at 16 27 53
ok I am not sure, please test it before you decide if it should or should not be there

File: suite-common/wallet-utils/src/accountUtils.ts (hunk 5 above)
Comment (Nodonisko) [reply suite-common/wallet-utils/src/accountUtils.ts]: How could token disappear from account? Anyway as I said I would prefer something more efficient like this (credit to chatGPT):

```
function areTheyDifferent(
  oldArr: TokenInfo[],
  freshArr: TokenInfo[]
): boolean {
  // Quick check: if lengths differ, they definitely have different items
  if (oldArr.length !== freshArr.length) {
    return true;
  }

  const oldIds = new Set(oldArr.map(item => item.contract));
  const freshIds = new Set(freshArr.map(item => item.contract));

  // If the sizes differ, there's a new/missing contractId
  if (oldIds.size !== freshIds.size) {
    return true;
  }

  // Check if every ID in old exists in fresh (and vice versa, since sizes are the same)
  for (const id of oldIds) {
    if (!freshIds.has(id)) {
      return true;
    }
  }

  // If we get here, the sets of contractIds are the same
  return false;
}
```

Comment (tomasklim) [reply suite-common/wallet-utils/src/accountUtils.ts]: You swap one token for another.

1 token dissapear and the other appear. Length is same

File: packages/suite/src/actions/wallet/tokenActions.ts (hunk 1 above)
Comment (enjojoy) [reply packages/suite/src/actions/wallet/tokenActions.ts]: This was not working indeed and it was needed, now I figured out why  (big thanks to @Nodonisko), the problem was in middleware and now it's fixed and fiat rate updates are instant

Fixed here https://github.com/trezor/trezor-suite/pull/16226/commits/6d3a6d0cc0e1faed6a6548a292fc0edfe90cd4f9

File: suite-common/wallet-utils/src/accountUtils.ts (hunk 5 above)
Comment (Nodonisko) [reply suite-common/wallet-utils/src/accountUtils.ts]: Unresolving this as my comment about performance of this solution still stands.

Comment (enjojoy) [reply suite-common/wallet-utils/src/accountUtils.ts]: yes, I remember about it, will get to it soon

Comment (tomasklim) [reply suite-common/wallet-utils/src/accountUtils.ts]: I am not sure if we need to do any changes in this file at all

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 6]
```diff
@@ -726,16 +734,17 @@ export const isAccountOutdated = (account: Account, freshInfo: AccountInfo) => {
...
             );
         case 'ethereum':
             return (
+                isDifferentBalance() ||
                 freshInfo.misc!.nonce !== account.misc.nonce ||
-                freshInfo.balance !== account.balance || // balance can change because of beacon chain txs (staking) |
                 JSON.stringify(freshInfo?.misc?.stakingPools) !==
-                    JSON.stringify(account?.misc?.stakingPools)
+                    JSON.stringify(account?.misc?.stakingPools) ||
+                areDifferentTokens()
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: total amount of txs changes when you receive tokens so no changes here are needed. The tokens appeared before, the only problem was update of fiat rates

File: suite-common/wallet-utils/src/accountUtils.ts [hunk 7]
```diff
@@ -744,11 +753,14 @@ export const isAccountOutdated = (account: Account, freshInfo: AccountInfo) => {
                 // changed rewards amount (rewards are distributed every epoch (5 days))
                 freshInfo.misc!.staking?.rewards !== account.misc.staking.rewards ||
                 // changed stake pool
-                freshInfo.misc!.staking?.poolId !== account.misc.staking.poolId
+                freshInfo.misc!.staking?.poolId !== account.misc.staking.poolId ||
+                areDifferentTokens()
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: Cardano works same as blockbook so probable same as for Ethereum -> total amount of txs changes when you receive tokens so no changes here are needed

File: suite-common/wallet-utils/src/accountUtils.ts (hunk 4 above)
Comment (tomasklim) [inline suite-common/wallet-utils/src/accountUtils.ts]: Solana works different but when something in the account changes, there has to be new tx (incoming or outcoming) so no changes here are needed

**Review by tomasklim — APPROVED** [review]
