### PR TITLE
Fix/message system renderer

### LINKED ISSUE #9970: Bug: Message Banners - renders over the content.
Banners currently render over the content. But according to [design](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=20531-323421&mode=design&t=WvwHtK8yBUL4NrY2-4), it should render differently

I suggest to use this branch for testing purposes:
https://github.com/trezor/trezor-suite/tree/native-test-banners

current state:
Screenshot 2023-11-16 at 14 57 42

### PR DESCRIPTION
**Pull request by juriczech**
## Description
- separate `MessageSystemRenderer` and `FeatureMessageScreen`. Makes more sense to have them separate so that we don't have to use weird hacks, using `Screen` component etc
- `MessageSystemRenderer` is now rendered as a sibling to the `RootStackNavigator`
- `FeatureMessageScreen` is rendered as last element inside JSX of `App.tsx` so it's utilizing higher `zIndex` value (rather is layered on top of the app)
- Dismiss button inside `FeatureMessageScreen` now has a correct color scheme to be according to design

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/9970

### CODE REVIEW

File: suite-native/app/src/App.tsx [hunk 1]
```diff
@@ -55,25 +55,28 @@ const AppComponent = () => {
...
+            <FormatterProvider config={formattersConfig}>
+                <ScreenshotProvider>
+                    <AuthenticatorProvider>
+                        <AlertRenderer>
                             {/* Notifications are disabled until the problem with after-import notifications flooding is solved. */}
                             {/* More here: https://github.com/trezor/trezor-suite/issues/7721  */}
                             {/* <NotificationRenderer> */}
                             <ToastRenderer>
                                 <ScreenshotCapturer>
+                                    <MessageSystemRenderer />
```
Comment (PeKne) [inline suite-native/app/src/App.tsx]: nit: I would rename this to `MessageSystemBannerRenderer` since it is rendering only the banners messages.

**Review by PeKne — APPROVED** [review]
