### PR TITLE
fix(suite): handle loading missing stores gracefully

### LINKED ISSUE #21782: Handle missing IDB stores
This is relevant mainly for developers and QA on develop, rarely in case of customers on production.

In [preloadStore.ts](https://github.com/trezor/trezor-suite/blob/dd8466a6492dc551d4e419d4ac9e5f352fd444df/packages/suite/src/support/suite/preloadStore.ts), we don't gracefully handle missing stores.

Example of bug occurrence:
- I open `develop` Suite 25.10.0
  - IDB version gets bumped to 25.10.0
- someone merges a 25.10.0 migration
- I pull `develop` and reopen Suite 25.10.0
  - migration 25.10.0 does not run, because version is already satisfied
- inconsistent IDB → Suite preload crashes
- infinite loader displayed

We cannot:
- load undefined, it just defers the crash (crashes when trying to modify the store) 
- backfill a missing store
- downgrade database version manually (ditto)

👉 need to display a modal to offer resetting DB

ℹ️ the above described bug occurrence is completely normal on develop environment. But there were unfortunately many cases of Sentry errors on production, because of improperly written migrations 😞 
So this is a valuable precaution for customers as well.

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Handle errors during `preloadStore` → display a modal to let you reset suite.

IMO it's better than resetting it right away, because the user would be confused (why is my data missing), this lets you know there is a problem and you're control of the solution (well, you have no other option than to accept, because Suite is broken at this point, no way to continue gracefully without resetting). 

The UI is not beautiful but this is an rare edge case, mostly for internal Trezor people, see the Issue.

## Related Issue

Resolve #21782

## Screenshots:

[database corrupted.webm](https://github.com/user-attachments/assets/1cae3639-edfd-453c-b6fe-13ef59d454d4)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/preload-missing-stores&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/preload-missing-stores&lookback=7)

### CODE REVIEW

File: packages/suite/src/support/suite/preloadStore.ts [hunk 1]
```diff
@@ -24,88 +24,97 @@ export const preloadStore = async () => {
...
+            },
+        } as const;
+    } catch (error) {
+        console.error(error); // Report the error to sentry instead of silently failing
+
+        return {
+            type: STORAGE.CORRUPTED,
+            payload: error,
+        } as const;
+    }
```
Comment (Lemonexe) [inline packages/suite/src/support/suite/preloadStore.ts:117]: only this is the new code, the above is just wrapped in `try`

File: packages/suite/src/components/suite/Preloader/__tests__/Preloader.test.tsx [hunk 2]
```diff
@@ -1,3 +1,5 @@
+import '@suite-common/test-utils/src/globalOverrides';
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/Preloader/__tests__/Preloader.test.tsx:1]: funny thing:
this was not necessary before, and now it's  because of imports hierarchy.

Preloader → DatabaseCorruptedModal → resetSuiteAppThunk → storageActions → crashes because of missing indexedDB.

I believe this is not a mistake, the mock is a proper one and it's just dumb luck that this was **not** needed before.
 
Other tests ↓ have the same line because they also render Preloader

**Review by peter-sanderson — APPROVED** [review]

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/support/suite/preloadStore.ts [hunk 3]
```diff
@@ -24,88 +24,97 @@ export const preloadStore = async () => {
...
+            formDrafts,
             coinjoinAccounts,
             coinjoinDebugSettings,
             tokenManagement,
             persistentDeviceData,
-            bioAuth,
             connect,
             explorer,
+            bioAuth,
             firmware,
```
Comment (Lemonexe) [inline packages/suite/src/support/suite/preloadStore.ts:53]: this diff is misleading because of identation, git tries to diff two different sections of code against each other.
