### PR TITLE
fix(suite-desktop): handle auto updater errors

### LINKED ISSUE #2595: Checking.. button in settings is stuck
As reported in https://github.com/trezor/trezor-suite/issues/649#issuecomment-706794717. I am creating a new issue to make sure it does not get lost. The update probably errors out and does not reset the state of the button.

### PR DESCRIPTION
**Pull request by keraf**
Fixes #2595 and displays error messages in a toast notification.

### CODE REVIEW

File: packages/suite-desktop/src/support/DesktopUpdater.tsx [hunk 1]
```diff
@@ -191,18 +193,13 @@ const DesktopUpdater = () => {
         window.desktopApi!.on('update/downloading', (progress: UpdateProgress) =>
             downloading(progress),
         );
+        window.desktopApi!.on('update/error', (err: Error) => error(err));
```
Comment (szymonlesisz) [inline packages/suite-desktop/src/support/DesktopUpdater.tsx]: unnecessary function wrapping, you can use it like:
`window.desktopApi!.on('update/error', error);`

in fact all `window.desktopApi` listeners could be reduced like this (i didnt notice that before)

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

File: packages/suite-desktop/src/support/DesktopUpdater.tsx (hunk 1 above)
Comment (keraf) [reply packages/suite-desktop/src/support/DesktopUpdater.tsx]: Indeed! Force of habit :smile:

**Review by szymonlesisz — APPROVED** [review]
