### PR TITLE
fix(suite-native): do not include solana staking in balance

### LINKED ISSUE #16564: Solana some balances include stake balance and some not
**Describe the bug**
There is inconsistency on whether balance includes stake fiat balance or not. Some places have it, some not

**How to reproduce**

1. Go to Portfolio tracker
2. Import dev Solana account that has staking
3. See discrepancy between balances on dashboard

**Expected behavior**
Numbers are the same and do not include staking where not allowed

**Screenshots**

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- Solana staking is not included in the account balances

## Related Issue

Resolve #16564 

## Screenshots:

https://github.com/user-attachments/assets/3b48fb2a-08fc-4950-851a-636ed874cc77

### CODE REVIEW

File: suite-native/device/src/selectors.ts [hunk 1]
```diff
@@ -71,30 +74,41 @@ export const selectDeviceError = (
...
+    rates?: RatesByKey;
+}) => {
+    let instanceBalance = new BigNumber(0);
+    deviceAccounts.forEach(a => {
+        const accountFiatBalance =
+            getAccountFiatBalance({
+                account: a,
+                localCurrency,
+                rates,
+                shouldIncludeStaking: a.networkType !== 'solana',
```
Comment (vytick) [inline suite-native/device/src/selectors.ts]: please, lets use `doesCoinSupportStaking ` from staking `package`

File: suite-native/device/src/selectors.ts [hunk 2]
```diff
@@ -71,30 +74,41 @@ export const selectDeviceError = (
     return device?.error;
 };
 
+// FIXME: this function can be removed and substitued with @suite-common/wallet-utils/getTotalFiatBalance when Solana supports staking on mobile.
+const getTotalFiatBalance = ({
```
Comment (vytick) [inline suite-native/device/src/selectors.ts]: nit: something like ```suggestion
const getNativeTotalFiatBalance = ({
```

**Review by vytick — CHANGES_REQUESTED** [review]

File: suite-native/device/src/selectors.ts (hunk 1 above)
Comment (PeKne) [reply suite-native/device/src/selectors.ts]: fixed 0546e9d3ff

File: suite-native/device/src/selectors.ts (hunk 2 above)
Comment (PeKne) [reply suite-native/device/src/selectors.ts]: fix 0546e9d3ff

**Review by vytick — APPROVED** [review]
I tested it rn and it looks good. Great job 👍
