### PR TITLE
fix(blockchain-link): prevent multiple workers initialization

### LINKED ISSUE #9646: Discovery 9. - optimize redux logic
There are some unnecessary redux calls during the discovery process on mobile. E.g the createAccount action is called individually for each found account, which triggers too many unnecessary calls for fetching fiat rates from backed.

TODO:
- examine the redux logic of the discovery process and optimize it so there are no redundant calls present

### PR DESCRIPTION
**Pull request by Nodonisko**
Added check if there is worker initialization in progress and if yes, return that instance instead of creating new one.

## Description

This problem occurs when worker is not initialized yet and suddenly there is multiple parallel calls and every one of them will init new worker, because they are not aware there is intialization in progress. Check that I added should prevent this.

## Related Issue

Resolve #9646

### CODE REVIEW

File: packages/blockchain-link/src/index.ts [hunk 1]
```diff
@@ -70,6 +70,9 @@ class BlockchainLink extends TypedEmitter<Events> {
 
     private throttler: Throttler;
 
+    // worker promise is used to prevent multiple workers initialization when multiple methods are called at called parallel before worker is initialized
```
Comment (PeKne) [inline packages/blockchain-link/src/index.ts:73]:
```suggestion
    // worker promise is used to prevent multiple workers initialization when multiple methods are called at parallel before worker is initialized
```

Just a typo. Otherwise looks good 🚀

**Review by marekrjpolak — APPROVED** [review]
While I was initially not convinced that this fix is enough, now I think it's fine.

The thing is, this ensures that only one instance of worker is created, but not that `connect` is called on it only once in parallel. Luckily [it was already handled](https://github.com/trezor/trezor-suite/commit/85a412b02aa5a3dd243a097e17058d5bf38a35a8) in the same manner by me, which I forgot about.

LGTM
