### PR TITLE
fix(suite-native): apply letterSpacing workaround on Connecting title

### LINKED ISSUE #14729: Extra line wrap with custom letter spacing
Screenshot_20241004_112428_Trezor Suite Lite Develop

Samsung s22

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

Apply a workaround on another place where an unexpected line break was reported.

## Related Issue

Resolve [#14729](https://github.com/trezor/trezor-suite/issues/14729)

## Screenshots:
It's hard to reproduce the bug, but with the workaround, it looks almost the same.
image

### CODE REVIEW

File: suite-native/atoms/src/resetLetterSpacingOnAndroid.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { isAndroid } from '@trezor/env-utils';
+import { prepareNativeStyle } from '@trezor/styles';
+
+export const resetLetterSpacingOnAndroid = prepareNativeStyle(_ => ({
```
Comment (Nodonisko) [inline suite-native/atoms/src/resetLetterSpacingOnAndroid.ts]: nit: I would suffix it style

**Review by Nodonisko — APPROVED** [review]

File: suite-native/atoms/src/resetLetterSpacingOnAndroid.ts (hunk 1 above)
Comment (matejkriz) [reply suite-native/atoms/src/resetLetterSpacingOnAndroid.ts]: good idea, changed
