### PR TITLE
fix(connect-popup): when connect-src not same as host popup display u…

### LINKED ISSUE #10156: Unknown url reported on Connect staging
**Describe the bug**

Unknown url reported on Connect staging when trezor-connect-src not specified.

NOT OK https://staging-connect.trezor.io/9/#/method/getPublicKey
OK         https://staging-connect.trezor.io/9/?trezor-connect-src=https://staging-connect.trezor.io/9/#/method/getPublicKey

**Screenshots**

https://github.com/trezor/trezor-suite/assets/31506317/52c4a0cb-aa67-47a3-b058-5f9c14fa5fe9

### PR DESCRIPTION
**Pull request by karliatto**
## Description

When running connect with different source as host popup was displaying unknown origin.

I think this might have a better solution in the origin of the event but still not sure.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10156

### CODE REVIEW

File: packages/connect-popup/src/index.tsx [hunk 1]
```diff
@@ -454,7 +454,10 @@ const handshake = (handshake: PopupHandshake, origin: string) => {
 
     // when this message comes from iframe, settings is already validated.
     // when there is no iframe, we must validate it here
-    const trustedSettings = parseConnectSettings(payload.settings, origin);
+    const trustedSettings = parseConnectSettings(
+        payload.settings,
+        origin || payload.settings.origin || '',
```
Comment (mroz22) [inline packages/connect-popup/src/index.tsx]: hmm there shouldn't really be cases when `origin` is undefined. it should come from `event.origin`. And should not be empty, if it is, there is something weird going on. Are you sure origin param in handshake method is nullable? I would say it is not and the problem is maybe that we overwrite it later on somewhere?

Comment (karliatto) [reply packages/connect-popup/src/index.tsx]: In the case I tested `event.origin` is not undefined, it is empty string which is falsy. But yest I am investigating the root of it now that I know how to reproduce it locally.

Comment (mroz22) [reply packages/connect-popup/src/index.tsx]: and it happens only when injecting trezor-connect-src right?

Comment (karliatto) [reply packages/connect-popup/src/index.tsx]: It happens only when host and connect source are different. For example here https://staging-connect.trezor.io/9/#/method/getPublicKey it does not use `trezor-connect-src` but it happens becuse it uses https://suite.corp.sldev.cz/connect/release/connect/9.1.6/popup.html as connect source.

Comment (karliatto) [reply packages/connect-popup/src/index.tsx]: After digging deep I think the root cause of it might be related to the use of BroadcastChannel that has same API as  postMessage but it looks like some arguments are not included and one of those is origin, that takes it's default value that is empty string - https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/MessageEvent#origin

https://github.com/trezor/trezor-suite/blob/develop/packages/connect-iframe/src/index.ts#L235

https://stackoverflow.com/questions/63143886/is-there-a-way-to-reply-to-only-the-sender-after-receiving-a-broadcastchannel-m
image

https://html.spec.whatwg.org/multipage/web-messaging.html#broadcasting-to-other-browsing-contexts

I am still investigating.  :mag_right:

Comment (karliatto) [reply packages/connect-popup/src/index.tsx]: But I am not sure, because according to mdn message event from a BroadcastChannel CAN have origin https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/message_event

So maybe we have to set it because it is optional.

**Comment by karliatto** [comment]
@mroz22 I updated the code to work the same but more clear and added some comments.

**Review by mroz22 — APPROVED** [review]
its probably ok. I am still a bit unsure. was it always like this?

**Comment by karliatto** [comment]
> its probably ok. I am still a bit unsure. was it always like this?

The argument `origin` was recently added to the `handshake` function. https://github.com/trezor/trezor-suite/commit/ecb13e82081395aa184d38b65e2e4667f8108e6f#diff-39f16e786cb0eac481161e3a249c4ade088cc38cf0bdd8adc74ac7b7bac99172R292
