### PR TITLE
fix(transactions): search on multiple outputs

### LINKED ISSUE #3493: Transaction history - Search only finds first output
**Describe the bug**
Search only finds first output. When you search for other output search won't find them.

**Info:**
 - Remembered Wallet: no
 - Suite Version: web, commit
 - Browser: , version
 - OS: system, build
 - Bridge: build version
 - Firmware Version: model , revision 

**Steps to reproduce:**
1. Send transaction with multiple outputs
2. Search in transaction history for second or third output
3. Observe

**Screenshots:**
image

image

image

### PR DESCRIPTION
**Pull request by keraf**
Fixes #3493

### CODE REVIEW

File: packages/suite/src/utils/wallet/transactionUtils.ts [hunk 1]
```diff
@@ -586,36 +586,37 @@ const numberSearchFilter = (
...
 ) => {
-    const targetAmount =
-        transaction.targets[0] !== undefined
-            ? getTargetAmount(transaction.targets[0], transaction)
-            : transaction.amount;
-
-    if (!targetAmount) {
-        return false;
-    }
+    const targetAmounts =
```
Comment (tomexx) [inline packages/suite/src/utils/wallet/transactionUtils.ts]: it feels like this fn could be reused for searching without operator as well.

**Review by tomexx — CHANGES_REQUESTED** [review]
elegant 👍 
but pls check comment

File: packages/suite/src/utils/wallet/transactionUtils.ts (hunk 1 above)
Comment (keraf) [reply packages/suite/src/utils/wallet/transactionUtils.ts]: Addressed in 3153634

**Review by tomexx — APPROVED** [review]
