### PR TITLE
fix(suite-native): graph event extremes offset

### LINKED ISSUE #9050: First dot is out on multiple graphs
**Describe the bug**
first dot is out on multiple graphs.

**Info:**

- b501fa1 - [develop] - feat(suite-native): persistent graph timeframe storage (#8948)
- Android 13 - Samsung A13

**Screenshots**

image

### PR DESCRIPTION
**Pull request by PeKne**
The extreme graph events date (x-axis of the graph) is normalized to make the events always fully visible and centered right on the graph line.

Closes #9050

### CODE REVIEW

File: suite-common/graph/src/hooks.ts [hunk 1]
```diff
@@ -36,6 +36,31 @@ type CommonUseGraphReturnType = {
 // if start date is null we are fetching all data till first account movement
 type StartOfTimeFrameDate = Date | null;
 
+const MINIMAL_PROPORTIONAL_EDGE_OFFSET = 0.02;
```
Comment (juriczech) [inline suite-common/graph/src/hooks.ts]: How is this number determined? Trial and error or is there a reason for this? Could you please attach a comment if there is any logic behind it?

Comment (PeKne) [reply suite-common/graph/src/hooks.ts]: comment added in cb5b45438

**Review by juriczech — APPROVED** [review]
