### PR TITLE
fix(suite-native): prohibit swiping back from authorize device screens

### LINKED ISSUE #15237: It's possible to swipe back from the Connecting screen
It's possible to swipe back from the Connecting screen and the PIN matrix remains shown on the device.

**Info:**

-   Mobile Suite Version: develop
-   OS: any

**Steps to reproduce**

1. Connect a Trezor Model One.
1. Wait for the Connecting screen to appear.
1. Swipe back as soon as the Connecting screen appears.
1. You end up on Home screen and PIN matrix remains shown on the device.

**Expected behavior**
It's either not possible to swipe back, or the PIN matrix is cleared from the device.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by yanascz**
## Related Issue

Resolve #15237

### CODE REVIEW

File: suite-native/app/src/navigation/RootStackNavigator.tsx [hunk 1]
```diff
@@ -109,6 +109,7 @@ export const RootStackNavigator = () => {
                 options={{
                     ...stackNavigationOptionsConfig,
                     animation: 'slide_from_bottom',
+                    gestureEnabled: false,
```
Comment (matejkriz) [inline suite-native/app/src/navigation/RootStackNavigator.tsx:112]: This does not fix it on android, only iOS.

Comment (matejkriz) [reply suite-native/app/src/navigation/RootStackNavigator.tsx:112]: And I'm not sure we want to disable the back gesture in whole AuthorizeDeviceStackNavigator. Maybe yes, just not sure what else it affects (passphrase flow, I guess)

Comment (PeKne) [reply suite-native/app/src/navigation/RootStackNavigator.tsx:112]: Agree with @matejkriz. Please change the `gestureEnabled` for the specific screen only.

Comment (PeKne) [reply suite-native/app/src/navigation/RootStackNavigator.tsx:112]: What about overriding the goBack event listener for this screen so it does not do anything? It should fix the issue for both platforms and will work with Android back button. We already have something like that used here: https://github.com/trezor/trezor-suite/blob/010eca96cc3e4e8439cb6391d200919d1ab0aa52/suite-native/module-send/src/hooks/useHandleOnDeviceTransactionReview.tsx#L56

Comment (yanascz) [reply suite-native/app/src/navigation/RootStackNavigator.tsx:112]: From what I tested, the fix works on both platforms. Tapping the back button on Android does the same thing as tapping the close button which is expected from my point of view.

I'm pretty confident we want to avoid swiping back on all the screens. In fact, I had to override the property even in `AuthorizeDeviceStack.Navigator` for it to work correctly for locked devices.

If you can think of a use case that is broken by this fix, please let me know. I couldn't find one.

**Review by PeKne — APPROVED** [review]
Seems to work as expected now 🥳

File: suite-native/app/src/navigation/RootStackNavigator.tsx (hunk 1 above)
Comment (yanascz) [reply suite-native/app/src/navigation/RootStackNavigator.tsx:112]: In the end, I had to add and use `useHandleHardwareBackNavigation`. Now all the scenarios seem to work as expected.
