### PR TITLE
fix(suite): Fix metadata provide icons + refactoring component

### LINKED ISSUE #14325: Grey label provider icons
**Describe the bug**
The icons for providers for labels are grey.

**Steps to reproduce:**
1. Connect a device
2. Go to settings
3. Click on "Labeling"
4. When choosing provider see grey icons of the providers

**Info:**
 - Suite version: desktop 24.9.1 (e2177b22af8251cd1e81e2fec0a0019e664e053a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 3.0.0

**Expected result:**
Icons are colored

**Actual result:**
Icons are grey

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve #14325

## Screenshots:

before
image

after
image

Screenshot 2024-09-19 at 13 43 12

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal/MetadataProviderModal.tsx [hunk 1]
```diff
@@ -84,56 +50,60 @@ export const MetadataProviderModal = ({ onCancel, decision }: MetadataProviderMo
...
         >
-            <StyledP typographyStyle="hint">
+            <Paragraph typographyStyle="hint">
                 <Translation id="METADATA_MODAL_DESCRIPTION" />
-            </StyledP>
-            {error && <Error>{error}</Error>}
-        </StyledModal>
+            </Paragraph>
+            {error && (
+                <Text variant="destructive" typographyStyle="label" margin={{ top: spacings.xs }}>
```
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal/MetadataProviderModal.tsx]: Paragraph?

File: packages/components/src/components/buttons/Button/Button.tsx [hunk 2]
```diff
@@ -145,13 +145,22 @@ export const Button = ({
...
-    const IconComponent = icon ? (
-        <Icon
-            name={icon}
-            size={iconSize || getIconSize(size)}
-            color={getIconColor({ variant, isDisabled, theme, isSubtle })}
-        />
-    ) : null;
+    const getIcon = () => {
+        if (!icon) return null;
+        if (typeof icon === 'string') {
```
Comment (seibei-iguchi) [inline packages/components/src/components/buttons/Button/Button.tsx]: IconName?:)

**Review by seibei-iguchi — APPROVED** [review]
