### PR TITLE
fix: proper wording of the connection states

### LINKED ISSUE #23956: Incorrect header 'Connect your Trezor' shown during device pairing (should indicate 'Confirm pairing')
**Describe the bug**
The header in the modal during device pairing incorrectly says "Connect your Trezor". The text should be something like "Confirm pairing" or similar, as the current header is misleading during the pairing confirmation step.

**Info:**
 - Suite version: desktop 25.12.2 (5374584e0a3ff72421e8bedf84e930b67cd49f58)
 - Browser: Trezor Suite 25.12.2
 - OS: Win32
 - Screen: 2514x1335
 - Device: 
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**How to reproduce**
1. Start the device pairing process in Trezor Suite Desktop
1. Observe the modal displayed for device selection and pairing
1. Notice the header reads "Connect your Trezor" instead of something like "Confirm pairing"

**Expected behavior**
The modal header should clearly indicate the pairing confirmation step, e.g., "Confirm pairing", to avoid confusion for the user.

**Screenshots**
Pairing modal with incorrect header

### PR DESCRIPTION
**Pull request by vojtatranta**
## Notes for QA

Changed the wording on the heading of the model in the device pairing state 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23956

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=23956-confirm-pairing-copy&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=23956-confirm-pairing-copy&lookback=7)

### CODE REVIEW

File: suite/intl/src/messages.ts [hunk 1]
```diff
@@ -7356,6 +7360,10 @@ export const messages = defineMessages({
         id: 'TR_CONNECT_YOUR_TREZOR_DESCRIPTION',
         defaultMessage: 'Select a device to connect.',
     },
+    TR_CONFIRM_PAIRING_TREZOR_DESCRIPTION: {
+        id: 'TR_CONFIRM_PAIRING_TREZOR_DESCRIPTION',
+        defaultMessage: 'Confirm the pairing with your Trezor device.',
```
Comment (jvaclavik) [inline suite/intl/src/messages.ts]: What about `Confirm pairing using your Trezor device`?

**Review by jvaclavik — APPROVED** [review]

File: suite/intl/src/messages.ts (hunk 1 above)
Comment (vojtatranta) [reply suite/intl/src/messages.ts]: chaging

**Comment by zako05** [comment]
QA OK ✅ https://github.com/trezor/trezor-suite/issues/23956#issuecomment-3823514284
