### PR TITLE
Invity buy improvements

### LINKED ISSUE #2705: INVITY  invity.io link not clickable in Learn more modal
**Info:**
 - OS: Nixos
 - Browser: Chromium and Firefox, current versions
 - Wallet Version: web, commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
 - Firmware Version: 2.3.4 model T  
 
**Describe the bug**

`invity.io `link not clickable in `Learn more` modal in Coinmarket section.
It behaves as link / cursor changes as you hover over it but https://invity.io/ is not opened

**Steps to reproduce:**
1. Load suite with Coinmarket feature and navigate to `Trade` section
2. Click on `Learn more` in right down corner of Suite
3. Click on `invity.io` button in modal  and observe

**Expected result:**
`invity.io` button is clickable 
 
**Actual result:**
Click on invity.io doesn't behave properly, behaves as button but no url is opened after is clicked.

**Screenshots:**

image

Peek 2020-10-21 17-19

### PR DESCRIPTION
**Pull request by vladimirvolek**
This PR closes https://github.com/trezor/trezor-suite/issues/2705.

- Removed borders from transactions (Remove border from the focus on the particular transaction
 https://github.com/trezor/trezor-suite/issues/2732)
- Added space in the transaction failed detail (Spacing around the transaction ID https://github.com/trezor/trezor-suite/issues/2732)

### CODE REVIEW

**Review by keraf — APPROVED** [review]

File: packages/suite/src/components/wallet/CoinmarketFooter/index.tsx [hunk 1]
```diff
@@ -116,7 +116,9 @@ const CoinmarketFooter = () => {
                                 </Link>
                             </BoxLeft>
                             <BoxRight>
-                                <Button variant="tertiary">invity.io</Button>
+                                <Link href="https://invity.io/" target="_blank">
```
Comment (szymonlesisz) [inline packages/suite/src/components/wallet/CoinmarketFooter/index.tsx:119]: i think this url should be added here:
https://github.com/trezor/trezor-suite/blob/develop/packages/suite-desktop/src-electron/config.ts#L6
otherwise it will be blocked by desktop app

and maybe you could use `ExternalLink` component instead to be easier to track it in the future?

**Review by szymonlesisz — CHANGES_REQUESTED** [review]
rebase this branch pls

File: packages/suite/src/components/wallet/CoinmarketFooter/index.tsx (hunk 1 above)
Comment (vladimirvolek) [reply packages/suite/src/components/wallet/CoinmarketFooter/index.tsx:119]: We don't want to have the icons from ExternalLink component.

image

**Review by szymonlesisz — APPROVED** [review]
conditionally approved, in the future pls use fixup! commits and more meaningful commit messages because currently i need to squash it into one
https://docs.trezor.io/trezor-suite/misc/review.html
