### PR TITLE
fix(suite-desktop): add dropbox to allowed origins

### LINKED ISSUE #5759: Labeling on Dropbox and Safari combination not working
**Describe the bug**
When I enable labeling and try to connect Dropbox to Suite via Safari, it doesn't work. The process gets stuck on the very last step where the site should just tell you to close your window and go back to Suite but the page is just forever loading without showing anything. This is not a regression, I tried with Suite 22.6.5 and it isn't working as well. You need to have Safari as a default browser, of course. Console log is provided below.

**Steps to reproduce:**
1. Go to settings
2. Enable labeling
3. Connect to Dropbox
4. Go through the allowing of connecting Suite to Dropbox
5. The very last step, where you should just close your window is stuck on forever loading and Dropbox never connects.

**Info:**
 - Suite version: desktop 22.7.1 (b82987dd15049a1578bbeb4705d32b6f1edb7893)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.7.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Expected result:**
Suite connects to Dropbox and labeling works as expected.

**Actual result:**
Dropbox doesn't connect to Suite and it gets stuck on forever loading.

**Screenshots:**
Screenshot 2022-07-11 at 16 53 45

### PR DESCRIPTION
**Pull request by komret**
Fixes redirect from Dropbox OAuth as described in #5759. I don't really know why Dropbox adds a `referer` header only in Safari, but that's why it didn't work.

### CODE REVIEW

File: packages/suite-desktop/src-electron/libs/http-receiver.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export class HttpReceiver extends EventEmitter {
             {
                 pathname: '/oauth',
                 handler: this.oauthHandler,
-                origins: ['', '127.0.0.1'], // No referer is sent by Google and Dropbox
+                origins: ['', '127.0.0.1', 'https://www.dropbox.com'], // No referer is sent by Google, Dropbox sends referer when using Safari
```
Comment (matejkriz) [inline packages/suite-desktop/src-electron/libs/http-receiver.ts]: `https://` is extra here, we check if origin includes `new URL(referer).hostname`

```suggestion
                origins: ['', '127.0.0.1', 'www.dropbox.com'], // No referer is sent by Google, Dropbox sends referer when using Safari
```

Comment (komret) [reply packages/suite-desktop/src-electron/libs/http-receiver.ts]: Done in e6cd6d8e0a0f99eb54f011d1e4fc40f376529c08.

**Review by matejkriz — APPROVED** [review]
👍  squash fixup & merge please
