### PR TITLE
Show error alert when trade confirmation fails

### LINKED ISSUE #21882: Mobile Swap: Improve error on failed confirmTrade
Followup to #21693 

When `confirmTrade` fails, it does not show any error to user. If it fails, show [__bottom sheet__](https://www.figma.com/design/OIXEah1s7HaSIsI8A8ws9T/-Mob--Trade?node-id=7318-491415&t=LZARDVPw26Lw3bua-0) with text:

`title`: `Failed to confirm offer.`
`description` if user is offline: `moduleTrading.error.deviceOfflineDescription`
no `description` otherwise.

actions:
- `Try again` - trigger `handleConfirmTrade`
- `Cancel` - goes back to exchange form.

### PR DESCRIPTION
**Pull request by vytick**
- Error alert with retry button when trade confirmation fails
- Small refactor of useFeesFetching
- Solana address in trade review is not chunked

## Related Issue

Resolve #21882 

## Screenshots:

https://github.com/user-attachments/assets/f4904726-de89-4680-9504-d01baca531d2

https://github.com/user-attachments/assets/b41c9dcd-fa9b-4d4f-9e42-4ce4e1538247

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=21882-mobile-swap-improve-error-on-failed-confirmtrade&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=21882-mobile-swap-improve-error-on-failed-confirmtrade&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=21882-mobile-swap-improve-error-on-failed-confirmtrade&lookback=7)

### CODE REVIEW

**Comment by vytick** [comment]
@coderabbitai review

File: suite-native/module-trading/src/components/general/ProviderReceiveAddress.tsx [hunk 1]
```diff
@@ -42,12 +43,13 @@ export const ProviderReceiveAddress = ({ trade }: { trade: ExchangeTrade | SellF
             ? (trade as ExchangeTrade).sendAddress
             : (trade as SellFiatTrade).destinationAddress;
 
-    if (!receiveAddress) {
+    if (!receiveAddress || !networkSymbol) {
         return null;
     }
 
+    const { networkType } = getNetwork(networkSymbol);
```
Comment (jbazant) [inline suite-native/module-trading/src/components/general/ProviderReceiveAddress.tsx]: **nitpick (non-blocking):** We can select `selectAccountNetworkType` directly instead.‏

File: suite-native/transaction-management/src/hooks/fees/__tests__/useFeesFetching.test.ts [hunk 2]
```diff
@@ -44,16 +45,19 @@ describe('useFeesFetching', () => {
...
         isRefetchDisabled?: boolean;
     }) =>
-        renderHookWithStoreProviderAsync(() => useFeesFetching({ accountKey, isRefetchDisabled }), {
-            store,
-        });
+        renderHookWithStoreProviderAsync(
+            () => useFeesFetching({ networkSymbol, isRefetchDisabled }),
+            {
+                store,
+            },
```
Comment (jbazant) [inline suite-native/transaction-management/src/hooks/fees/__tests__/useFeesFetching.test.ts]: WTF prettier did here? Can you update it to simple
```ts
{ store },
```
please?

File: suite-native/transaction-management/src/hooks/fees/__tests__/useFeesFetching.test.ts [hunk 3]
```diff
@@ -81,21 +85,21 @@ describe('useFeesFetching', () => {
...
 
         expect(result.current.areFeesLoading).toBe(false);
-        expect(mockUseFetchFeesOnce).toHaveBeenCalledWith({ networkSymbol: undefined });
+        expect(mockUseFetchFeesOnce).toHaveBeenCalledWith({ networkSymbol: 'btc' });
         expect(mockUseRefetchFees).toHaveBeenCalledWith({
-            networkSymbol: undefined,
+            networkSymbol: 'btc',
             isDisabled: false,
         });
     });
```
Comment (jbazant) [inline suite-native/transaction-management/src/hooks/fees/__tests__/useFeesFetching.test.ts]: **issue:** This test does not test anything anymore, does it?

This functionality is IMO already tested by `'should select account by key from state'`.
‏

**Review by jbazant — APPROVED** [review]
LGTM! Really nice test coverage. Seem to work flawlessly. At least to me 🤷

File: suite-native/module-trading/src/components/general/ProviderReceiveAddress.tsx (hunk 1 above)
Comment (vytick) [reply suite-native/module-trading/src/components/general/ProviderReceiveAddress.tsx]: good spot!

File: suite-native/transaction-management/src/hooks/fees/__tests__/useFeesFetching.test.ts (hunk 3 above)
Comment (vytick) [reply suite-native/transaction-management/src/hooks/fees/__tests__/useFeesFetching.test.ts]: Good spot. I forgot to delete this one after not using account
