### PR TITLE
14x Cardano staking fix

### LINKED ISSUE #23152: Cardano staking - estimated rewards calculation
- It would be good to inform users that the calculated estimated rewards are based on interest applied to their total account amount minus the 2 ADA deposit.
- we have missing deposit in staking in nutshell

Image
Image
Image

Here is missing the deposit in staking process. It is for stake but not for unstake

Image

Maybe we should tell during update provider, that deposit is already paid and will not be paid again

Image

### LINKED ISSUE #23153: Staking - staking/tx progress bar
TODO: cover all cases

Cardano staking bar is shown when rewards are 0 (after claim)

Image

Cardano staking bar is shown when staking with somebody else and all rewards are claimed

Image

### LINKED ISSUE #23323: Cardano staking - why people stake twice
**Describe the bug**
There must be some problem with updating account because some people update provider twice 

Image

### LINKED ISSUE #23484: Cardano staking - show pool id and staking key at least in debug mode
Show pool id and staking key for debug purposes. Investigate if any of those would help our users too

### LINKED ISSUE #23506: Staking dashboard says inactive when cardano staking is active but 0 balance
The `Inactive` button on this screenshot is because staking/account balance is zero. Edge case Screenshot 2025-11-29 at 21 05 04

_Originally posted by @tomasklim in https://github.com/trezor/trezor-suite/issues/23502#issuecomment-3591907236_

### PR DESCRIPTION
**Pull request by tomasklim**
## Description + Notes for QA

- if user has stake with FiveBinaries, Update provider banner is pushy
Non-FiveBinaries
Screenshot 2025-12-01 at 11 54 29
FiveBinaries
Screenshot 2025-12-01 at 11 54 56

_______________

- dashboard staking indicator says outdated provider only if user stakes with FiveBinaries 

Non-Fivebinaries
Screenshot 2025-12-01 at 11 56 57

FiveBinaries
Screenshot 2025-12-01 at 11 55 34

_______________

- Update provider in staking dashboard on dashboard now do not open staking in nutshell modal but takes user to staking dashboard in account
- Also analytics was updated so we know on what user clicked (notion updated)

______________

- fake pending cardano txs were in suite for 2 blocks, increased to 10 blocks so that it does not dissapear before it is mined
- probably fixes double stakes

_____________

- tx history in cardano staking tab + fixes staking tx headers (some staking txs were not correctly identified)

Screenshot 2025-12-01 at 11 59 51

_____________

- update provider banner is only in staking tab, not in account overview if it is not FiveBinaries

Screenshot 2025-12-01 at 12 01 02

____________

- pushy fivebinaries banner can be turned off by message system
- there was sometimes `0` instead of staking progress bar
___________

- progress staking bar (activation period) is not visible when not staked with Everstake

Screenshot 2025-12-01 at 12 02 30

__________

- no progress bar after rewards are claimed
Screenshot 2025-11-30 at 20 16 59

__________

- debug info for cardano

Screenshot 2025-12-01 at 12 03 08

___________

- custom drep visible in stake/update provider modal (if set)

Screenshot 2025-12-01 at 12 04 03

__________

- no solana/cardano staking promo for T1B1

Screenshot 2025-12-01 at 11 15 24

__________

- text improvements from #23152

## Notes for QA

🔝  + Test that also staking on other networks is still ok

## Related Issue

Resolve #23323
Resolve #23152 (updated also in crowdin)
Resolve #23506
Resolve #23153
Resolve #23484

Not all bugs have issue.

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/cardano-staking-3&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/cardano-staking-3&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/cardano-staking-3&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx [hunk 1]
```diff
@@ -32,11 +37,25 @@ export const NewCardanoStakingDashboard = ({
...
+    useEffect(() => {
+        if (accountKey) {
+            dispatch(
+                fetchAllTransactionsForAccountThunk({
+                    accountKey,
+                    noLoading: true,
+                }),
+            );
+        }
+    }, [account, accountKey, dispatch]);
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx]: Are you sure you want to refetch it when the account object changes? Isn't accountKey enought?

File: packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx [hunk 2]
```diff
@@ -75,15 +94,18 @@ export const NewCardanoStakingDashboard = ({
                                     </Flex>
                                 </Grid>
                                 <StakingCard
+                                    account={account}
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx:97]: It'd be nice to create some context pro currently select account to prevent the prop drilling but I guess that's a work for another day.

**Review by cermakjiri — APPROVED** [review]

File: packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/views/wallet/staking/components/CardanoStakingDashboard/NewCardanoStakingDashboard.tsx]: tru, I copy pasted it from ethStakingDashboard. I will remove it from both places
