### PR TITLE
fix(suite-native): axil label overflow

### LINKED ISSUE #8571: Larger amounts cropped on graph
**Describe the bug**

Higher amounts get cropped on the right side of the screen. 

**Info:**
-   Suite Version: 23.5.1 (13) commit 6902cc4
-   OS: iPhone 13, iOS 16.4.1 (20E252)

**How to reproduce**

1. Launch app 
1. Get dough
1. Set to CZK
1. Observe

**Screenshots**
image

### PR DESCRIPTION
**Pull request by PeKne**
The axis label was overflowing the Graph. This commit fixes it.

Fixes #8571 

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/c37b246c-52cd-4bc8-a9e9-3dd6ff4b7d9b

### CODE REVIEW

File: suite-native/graph/src/components/AxisLabel.tsx [hunk 1]
```diff
@@ -10,34 +10,53 @@ type AxisLabelProps = {
...
-const axisLabelStyle = prepareNativeStyle<Pick<AxisLabelProps, 'x'>>((_, { x }) => ({
+const axisLabelStyle = prepareNativeStyle<AxisLabelStyleProps>((_, { x, isOverflowing }) => ({
     position: 'absolute',
     left: `${x}%`,
+    extend: {
+        // Position the axis label from the right if it's overflowing the screen width.
+        condition: isOverflowing,
+        style: {
+            left: undefined,
+            right: 0,
```
Comment (juriczech) [inline suite-native/graph/src/components/AxisLabel.tsx:30]: Should be handled for left side as well. You could just use `right: 0` if it's max value and `left: 0` if it's min value

**Review by juriczech — CHANGES_REQUESTED** [review]

File: suite-native/graph/src/components/AxisLabel.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/graph/src/components/AxisLabel.tsx:30]: why for the left side? The `x` prop will be never lower than 0.

File: suite-native/graph/src/components/AxisLabel.tsx [hunk 2]
```diff
@@ -10,34 +10,53 @@ type AxisLabelProps = {
...
-        if (x !== MAX_CLAMP_VALUE || !textWidth) return x;
-        const textWidthPercentage = (textWidth / Dimensions.get('window').width) * 100;
-        return x - textWidthPercentage;
-    }, [textWidth, x]);
+    const viewRef = useRef<View>(null);
+    const [isOverflowing, setIsOverflowing] = useState(false);
 
     if (isDiscreetMode) return null;
 
+    const handleLayoutOverflow = () => {
```
Comment (Nodonisko) [inline suite-native/graph/src/components/AxisLabel.tsx]: useCallback just in case would be nice

**Review by Nodonisko — APPROVED** [review]

**Review by juriczech — APPROVED** [review]

File: suite-native/graph/src/components/AxisLabel.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/graph/src/components/AxisLabel.tsx]: ✅
