### PR TITLE
Fix/fixes 2451

### LINKED ISSUE #2240: CTA on backup failed notification
Change the CTA on backup failed notification to "Continue" as a terciary button with link to Settings > Device.

Screen Shot 2020-08-21 at 17 41 19

### LINKED ISSUE #2467: Trezor Suite - hidden wallet - number missing
image

image

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/2240
fix https://github.com/trezor/trezor-suite/issues/2467#issuecomment-704167312 (wallet name (standard wallet/ hidden wallet #N) is assigned only when there is device.state)
separate intl for "Continue" and "Continue setup"

### CODE REVIEW

File: packages/suite/src/components/suite/Labeling/components/Wallet/index.tsx [hunk 1]
```diff
@@ -10,17 +10,19 @@ interface Props {
...
+                  ...messages.TR_PASSPHRASE_WALLET,
+                  values: {
+                      id: device.instance,
+                  },
+              };
+    }
 
-    const label =
-        typeof walletLabel === 'string' ? <>{walletLabel}</> : <Translation {...walletLabel} />;
+    const label = walletLabel ? <Translation {...walletLabel} /> : null;
```
Comment (szymonlesisz) [inline packages/suite/src/components/suite/Labeling/components/Wallet/index.tsx]: it will be cleaner to use only one variable:
```
let label: JSX.Element | undefined;
if (device.state) {
        label = (
            <Translation
                {...(device.useEmptyPassphrase
                    ? { id: 'TR_NO_PASSPHRASE_WALLET' }
                    : { id: 'TR_PASSPHRASE_WALLET', values: { id: device.instance } })}
            />
        );
    }
```
pros: you don't have to import whole messages module and ExtendedMessageDescriptor type + elimination of the second condition (if walletLabel ...)

**Review by szymonlesisz — CHANGES_REQUESTED** [review]

**Review by szymonlesisz — APPROVED** [review]
