### PR TITLE
Send max an NumberInput

### LINKED ISSUE #7967: Amount not displayed in Send dialogue
**Describe the bug**
See screen and video.
I was able to reproduce this issue in Google Chrome and Mozilla Firefox.
Tested with ETH and BTC , same results.
Same results with coin control on/off.

Noticed when you leave Send dialogue and come back amount is rendered as expected.

**Steps to reproduce:**
1. Navigate to Send dialogue
2. Select send all or input fiat amount
3. Check Amount in coin field

**Info:**
 - Suite version: web 23.4.0 (f169f0f32c939b2dea222e818a69038ba63ff8be)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
 - OS: MacIntel
 - Screen: 1824x1140
 - Device: model T 2.5.4 Universal (revision 305b7fe84d802db7f0826d07a222a886f73732f0)
 - Transport: BridgeTransport 2.0.32

**Expected result:**

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**
Screenshot 2023-03-31 at 15 20 05

image

https://user-images.githubusercontent.com/31506317/229131361-74216b39-ff42-4a97-a800-86bf53f30f70.mov

### PR DESCRIPTION
**Pull request by komret**
## Description

8898e543cbe37a5d977d979d497564823ff921eb: Remove condition to enable formatting `displayValue` when previous `value` was falsy. Remove ref dependences which are unnecessary IMO. There is no bug in coinjoin-specific send form (as I originally thought) - if there are no anonymous coins, send-max does not fill any value and warning is shown.
d1283457059a538fdd604a65df51c6d3c7ecf413 - while testing the above, I noticed a redundant memoization which caused incorrect distribution into categories in CoinControl after `targetAnonymity` was adjusted in coinjoin setup. Memoization has been removed.

## Related Issue

Resolve #7967

### CODE REVIEW

File: packages/suite/src/reducers/wallet/coinjoinReducer.ts [hunk 1]
```diff
@@ -599,14 +599,14 @@ export const selectCurrentCoinjoinSession = memoize((state: CoinjoinRootState) =
     return session;
 });
 
-export const selectCurrentTargetAnonymity = memoize((state: CoinjoinRootState) => {
+export const selectCurrentTargetAnonymity = (state: CoinjoinRootState) => {
```
Comment (dahaca) [inline packages/suite/src/reducers/wallet/coinjoinReducer.ts:602]: oh, not again :(

**Review by dahaca — APPROVED** [review]
