### PR TITLE
fix(suite-native): network symbol formatter units optional

### LINKED ISSUE #9057: Sats used to identify Bitcoin during account import
**Describe the bug**
Sats used to identify Bitcoin during account import when Satoshis enabled as default Bitcoin unit via settings

**Info:**

-  1b4cd62 - [develop] - fix(suite-native): use base jest config instead of native in assets pkg

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- NetworkSymbolFormatter extended by optional parameter `areAmountUnitsEnabled`
- Import asset screen uses this parameter co correctly format the bitcoin symbol to `BTC` instead of `sats`

## Related Issue

Resolve #9057 
## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/3e94e778-149f-428e-b158-37c72f00f068

### CODE REVIEW

File: suite-native/module-accounts-import/src/components/SelectableNetworkItem.tsx [hunk 1]
```diff
@@ -48,7 +51,7 @@ export const SelectableNetworkItem = ({ symbol, onPress }: SelectableAssetItemPr
                         <Text variant="body">{networkName}</Text>
                         <HStack alignItems="center" justifyContent="center">
                             <Text variant="hint" color="textSubdued">
-                                <NetworkSymbolFormatter value={symbol} />
+                                {formattedNetworkSymbol}
```
Comment (Nodonisko) [inline suite-native/module-accounts-import/src/components/SelectableNetworkItem.tsx]: Why you didn't used component? You can pass params as props too.

Comment (PeKne) [reply suite-native/module-accounts-import/src/components/SelectableNetworkItem.tsx]: awesome, fixed by a653fd8b81

**Review by juriczech — APPROVED** [review]
