### PR TITLE
fix(suite): unsubscribe disabled coins

### LINKED ISSUE #12904: When coin is disabled, app is still subscribed to new blocks
**Describe the bug**
When I disable coin after start, I am still getting new block info

**How to reproduce**
1. Activate whatever coin (best is polygon (fast blocks))
1. Restart Suite
1. Load accounts
2. Disable coin
3. Check console that `blockchain-block` for disabled coin is still getting updated

**Screenshots**
Screenshot 2024-06-16 at 18 52 07

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

When a coin is disabled, it should be unsubscribed from blockchain backend.

## Related Issue

Resolve #12904 

## Screenshots:

Polygon is selected and is subscribed to blockchain backend.
subscribed

Polygon is deselected and is no longer subscribed to blockchain backend.
unsubscribed

### CODE REVIEW

File: suite-common/wallet-core/src/blockchain/blockchainThunks.ts [hunk 1]
```diff
@@ -315,6 +315,8 @@ export const unsubscribeBlockchainThunk = createThunk(
                         blocks: false,
                         accounts: accountIdentities[identity] ?? [],
                     }));
+
+                return [...transformedRemovedAccounts, { symbol, blocks: true, accounts: [] }];
```
Comment (TomasBoda) [inline suite-common/wallet-core/src/blockchain/blockchainThunks.ts:319]: Added an account with no identity to removed accounts to unsubscribe both web sockets

**Review by martykan — APPROVED** [review]
