### PR TITLE
fix(suite): Wipe-code copy and bootloader appearance

### LINKED ISSUE #11069: Incorrect copy on Wipe-code modal for T1
**Describe the bug**
Wipe-code modal is using copy from PIN setup.
This is probably not only about copy in Crowdin. I've reused the PIN modal. So there probably needs to be added another one for wipe-code flow. 

image-1

### LINKED ISSUE #11121: Set up wipe code available in bootloader mode
**Describe the bug**
Set up wipe code available in bootloader mode
After you try to set it up you will get `Error: ui-device_bootloader_mode` error

**Steps to reproduce:**
1. Connect device in bootloader mode
2. Navigate to `Settings/device`
3. Press `Set up wipe code`
4. Observe error

**Info:**
 - Suite version: desktop 24.2.1 (fd5d1fa8475b78659e80f19bada6933ca804fab3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T1B1 1.12.1 undefined (revision null)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
Screenshot 2024-02-09 at 9 08 22

### PR DESCRIPTION
**Pull request by hynek-jina**
Resolve
- #11069 
- #11121

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsDevice/SettingsDevice.tsx [hunk 1]
```diff
@@ -151,7 +151,7 @@ export const SettingsDevice = () => {
 
             <SettingsSection title={<Translation id="TR_ADVANCED" />} icon="GHOST">
                 <WipeDevice isDeviceLocked={isDeviceLocked} />
-                <WipeCode isDeviceLocked={isDeviceLocked} />
+                {!bootloaderMode && !initializeMode && <WipeCode isDeviceLocked={isDeviceLocked} />}
```
Comment (komret) [inline packages/suite/src/views/settings/SettingsDevice/SettingsDevice.tsx]: This condition is used three times, maybe let's abstract it to some variable.

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -2546,7 +2546,7 @@ export default defineMessages({
     TR_ENTER_WIPECODE: {
         defaultMessage: 'Enter Wipe Code',
         description: 'Text for Header and Button when submitting wipe code',
-        id: 'TR_ENTER_PIN',
+        id: 'TR_ENTER_WIPECODE',
```
Comment (komret) [inline packages/suite/src/support/messages.ts:2549]: Please squash this with the first commit.

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/PinMatrix/PinInput/PinInput.tsx [hunk 3]
```diff
@@ -51,6 +52,16 @@ interface PinInputProps {
 
 export const PinInput = ({ isSubmitting, onPinSubmit }: PinInputProps) => {
     const [pin, setPin] = useState('');
+    const { isWipeCode } = usePin();
+    const getTranslationId = () => {
+        if (isSubmitting) {
+            return 'TR_VERIFYING_PIN';
+        } else if (isWipeCode) {
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/PinMatrix/PinInput/PinInput.tsx]: both `else`s are unnecessary, return will terminate the flow

File: packages/suite/src/hooks/suite/usePinModal.ts [hunk 4]
```diff
@@ -0,0 +1,28 @@
+import { selectDeviceButtonRequests } from '@suite-common/wallet-core';
+import { useSelector } from 'src/hooks/suite';
+
+export const usePin = () => {
+    const buttonRequests = useSelector(selectDeviceButtonRequests);
+
+    const pinRequestType = buttonRequests[buttonRequests.length - 1];
+    const invalidCounter = buttonRequests.filter(r => r.code === 'ui-invalid_pin').length || 0;
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/suite/usePinModal.ts:13]: it would be great to have this logic of this function covered with tests

File: packages/suite/src/hooks/suite/usePinModal.ts [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+
+    const isExtended =
+        (pinRequestType?.code &&
+            ['PinMatrixRequestType_NewFirst', 'PinMatrixRequestType_NewSecond'].includes(
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/suite/usePinModal.ts]: this array can be extracted as constant and named properly to explain by code why those two codes are important together

Comment (peter-sanderson) [reply packages/suite/src/hooks/suite/usePinModal.ts]: for example something like: `NEW_PIN_REQUEST_TYPES`

File: packages/suite/src/hooks/suite/usePinModal.ts [hunk 6]
```diff
@@ -0,0 +1,28 @@
+import { selectDeviceButtonRequests } from '@suite-common/wallet-core';
+import { useSelector } from 'src/hooks/suite';
+
+export const usePin = () => {
+    const buttonRequests = useSelector(selectDeviceButtonRequests);
+
+    const pinRequestType = buttonRequests[buttonRequests.length - 1];
+    const invalidCounter = buttonRequests.filter(r => r.code === 'ui-invalid_pin').length || 0;
+
+    const isExtended =
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/suite/usePinModal.ts]: why  `isExtended`? would be better to name: `isRequestingNewPinCode`?

File: packages/suite/src/hooks/suite/usePinModal.ts [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+        (pinRequestType?.code &&
+            ['PinMatrixRequestType_NewFirst', 'PinMatrixRequestType_NewSecond'].includes(
+                pinRequestType.code,
+            )) ||
+        invalidCounter > 0;
+
+    const isWipeCode =
+        pinRequestType?.code &&
+        ['PinMatrixRequestType_WipeCodeFirst', 'PinMatrixRequestType_WipeCodeSecond'].includes(
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/suite/usePinModal.ts]: for example something like: `WIPE_CODE_REQUEST_TYPES`

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PinModal.tsx [hunk 8]
```diff
@@ -37,16 +31,10 @@ export const PinModal = ({ device, ...rest }: PinModalProps) => {
     // 3 cases when we want to show left column
     // 1) and 2) - Setting a new pin: 1 entry, 2nd (confirmation) entry
     // 3) Invalid pin (It doesn't seem to work anymore) instead separate PinMismatchModal is shown
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PinModal.tsx]: I am not sure if I understand what this comment is here for, but I assume its relevant to the code you have extracted.

Maybe this comment shall be removed (that would be idea, if code is self-documenting), rephrased or moved to the `usePin` hook you have created

File: packages/suite/src/hooks/suite/usePinModal.ts (hunk 7 above)
Comment (hynek-jina) [reply packages/suite/src/hooks/suite/usePinModal.ts]: I will use `newWipeCodeRequestTypes`

File: packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PinModal.tsx (hunk 8 above)
Comment (hynek-jina) [reply packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PinModal.tsx]: Ok, I've migrated it to `usePinModal.ts`

File: packages/suite/src/hooks/suite/usePinModal.ts (hunk 6 above)
Comment (komret) [reply packages/suite/src/hooks/suite/usePinModal.ts]: See the comment:

```
// 3 cases when we want to show left column
// 1) and 2) - Setting a new pin: 1 entry, 2nd (confirmation) entry
// 3) Invalid pin (It doesn't seem to work anymore) instead separate PinMismatchModal is shown
```

Point 3 applies to an existing PIN, so the original naming is actually more apt. Could be changed to `isModalExtended` or something for extra clarity.

Comment (peter-sanderson) [reply packages/suite/src/hooks/suite/usePinModal.ts]: Thanks, good point! Now I also understand the comment. 

So suggest to do this them:
```ts
const isRequestingNewPinCode = (pinRequestType?.code && newPinRequestTypes.includes(pinRequestType.code))

const isPinInvalid = invalidCounter > 0; // maybee better naming, I still dont understand when is pin invalid in the settings (too short, too weak? is it this type of validation?

const isModalExtended = isRequestingNewPinCode || isPinInvalid
```


And we can delete the comments. Best code is self-explanatory code.

File: packages/suite/src/hooks/suite/usePinModal.ts [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+        isWipeCode,
+        isRequestingNewPinCode,
+        isPinInvalid,
+        isModalExtended,
+    };
+};
+
+export const usePin = () => {
+    return usePinWithoutSelector(useSelector(selectDeviceButtonRequests));
+};
```
Comment (komret) [inline packages/suite/src/hooks/suite/usePinModal.ts:32]: I don't love this but...okay. I guess it is here because of the test and @peter-sanderson suggested it?

**Review by komret — APPROVED** [review]

File: packages/suite/src/hooks/suite/usePinModal.ts (hunk 9 above)
Comment (peter-sanderson) [reply packages/suite/src/hooks/suite/usePinModal.ts:32]: This is here to separate state logic from the logic that is separated into pure function.

I wanted to spare @hynek-jina of the mocking of the state for selectors
