### PR TITLE
fix(suite): fix exchange currency

### LINKED ISSUE #11927: Trezor suite - exchange currency bug
#  Wrong cryptocurrency symbol

## Behaviour
**Current result**: in modal window there is `BTC receive address`
**Expected result**: in modal window there should be `LTC receive address`
image-20231208-124244
image-20231208-113942

## Info:
Steps to reproduce (macOS, Trezor Suite - desktop version 23.12.1):

## Steps to reproduce the behavior:
1. Open trade section in Trezor suite 
2. Go to exchange section
3. Choose BTC x LTC pair and fill out desired BTC amount to exchange and choose offer
4. Here after clicking on “Confirm on Trezor” button in modal window there is mentioned, that its BTC, not LTC address
**Expected behavior**

### PR DESCRIPTION
**Pull request by adderpositive**
#  Wrong cryptocurrency symbol

## Behaviour
**Current result**: in modal window there is `BTC receive address`
**Expected result**: in modal window there should be `LTC receive address`
image-20231208-124244
image-20231208-113942

## Info:
Steps to reproduce (macOS, Trezor Suite - desktop version 23.12.1):

## Steps to reproduce the behavior:
1. Open trade section in Trezor suite 
2. Go to exchange section
3. Choose BTC x LTC pair and fill out desired BTC amount to exchange and choose offer
4. Here after clicking on “Confirm on Trezor” button in modal window there is mentioned, that its BTC, not LTC address
**Expected behavior**

resolves #11927

### CODE REVIEW

**Review by tomasklim — APPROVED** [review]
LGTM, not tested

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx [hunk 1]
```diff
@@ -5,13 +5,20 @@ import { Translation } from 'src/components/suite';
 import { useDisplayMode, useSelector } from 'src/hooks/suite';
 import { selectSelectedAccount } from 'src/reducers/wallet/selectedAccountReducer';
 import { ConfirmValueModal, ConfirmValueModalProps } from './ConfirmValueModal/ConfirmValueModal';
+import { CryptoSymbol } from 'invity-api';
 
 interface ConfirmAddressModalProps
     extends Pick<ConfirmValueModalProps, 'isConfirmed' | 'onCancel' | 'value'> {
     addressPath: string;
+    receiveSymbol?: CryptoSymbol;
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx]: I am not sure with `CryptoSymbol` here as we use symbols only from `NetworkSymbol` in Trezor Suite.

CryptoSymbol value should always be available in NetworkSymbol. In case there is different symbol, then Trezor cannot show valid address

I would change it to `NetworkSymbol` if possible

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx (hunk 1 above)
Comment (adderpositive) [reply packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx]: Done.

After a discussion with @tomasklim I have made two updates:
- `useSelector` was moved to the children component
- for cryptocurrencies as `USDT@ETH` was added better translation - `USDT receive address on ETH network`

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx [hunk 2]
```diff
@@ -22,15 +25,48 @@ export const ConfirmAddressModal = ({ addressPath, value, ...props }: ConfirmAdd
 
     if (!account) return null;
 
-    return (
-        <ConfirmValueModal
-            account={account}
-            heading={
+    const getHeading = () => {
+        const receiveSymbolArray = receiveSymbol ? receiveSymbol.toUpperCase().split('@') : [];
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx]: could you please create util in `cryptoSymbolUtils.ts` (if it does not already exist)

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx (hunk 2 above)
Comment (adderpositive) [reply packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx]: Done. I used functions from `cryptoSymbolUtils.ts`.

**Review by tomasklim — APPROVED** [review]
LGTM

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 24.5.0 (1a7ff332d4b1d3c128487964794663604502e1d7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
We've discovered this issue that seems to be connected to this PR - cc @adderpositive take a look at it
https://github.com/trezor/trezor-suite/issues/11927

Looks like the problem could be caused by this -    const receiveSymbol = useSelector(
        state => state.wallet.coinmarket.exchange.quotesRequest?.receive,
    );
