### PR TITLE
Fix same labels for all evm accounts

### LINKED ISSUE #15546: Ethereum like networks share same labels
**Describe the bug**
Ethereum like networks share same labels

**Steps to reproduce:**
1. Create label for Eth n.1 account
2. Add Polygon and BNB accounts/networks coins
3. Observe labels of those accounts

**Info:**
 - Suite version: desktop 24.11.3 (71f9b21d21c9b033e34fc8c6d33ffd8223ffda73)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.3 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
Screenshot 2024-11-25 at 9 41 36
Screenshot 2024-11-25 at 9 41 32
Screenshot 2024-11-25 at 9 40 53

### PR DESCRIPTION
**Pull request by enjojoy**
## Description
Now the keys generated for non-mainnet evm accounts will be different than the ones generated for miannnet, so the files on the storage will be different and labels will not duplicate for each network.

Ethereum mainnet labels should stay the same and the others networks will be replaced by the new files.

To rewrite metadata keys it's needed to rediscover accounts 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/15546

## Screenshots:

Screenshot 2025-01-02 at 13 27 53
Screenshot 2025-01-02 at 13 28 17

### CODE REVIEW

**Comment by enjojoy** [comment]
Initially I thought about completely replacing account.metadata.key with account.key, for cleaner code and consistency, but that would overwrite all already existing labels, so I added some logic only for evm non-mainnet accounts. Maybe we should  also add some informational banner that the user now can set unique labels for all evm accounts. @tomasklim what do you think?

File: packages/suite/src/actions/suite/metadataLabelingActions.ts [hunk 1]
```diff
@@ -111,7 +111,12 @@ export const setAccountMetadataKey =
             return account;
         }
         try {
-            const metaKey = metadataUtils.deriveMetadataKey(deviceMetaKey, account.metadata.key);
+            const isNonEthEvm = account.networkType === 'ethereum' && account.symbol !== 'eth';
+
+            const metaKey = metadataUtils.deriveMetadataKey(
+                deviceMetaKey,
+                isNonEthEvm ? account.key : account.metadata.key,
```
Comment (tomasklim) [inline packages/suite/src/actions/suite/metadataLabelingActions.ts]: `key` will not work, it changes (same seed, two devices)

Comment (enjojoy) [reply packages/suite/src/actions/suite/metadataLabelingActions.ts]: changed to metadata key + network symbol

Comment (tomasklim) [reply packages/suite/src/actions/suite/metadataLabelingActions.ts]: can we use chain id, chain id will probably never change but network symbol can (matic -> pol)

Comment (tomasklim) [reply packages/suite/src/actions/suite/metadataLabelingActions.ts]: can you modify metadata key at the source? you are already introducing bug as you are modifying it just on 1 place out of 2

Comment (enjojoy) [reply packages/suite/src/actions/suite/metadataLabelingActions.ts]: Yes, now it's modifying at the source, tbh it was tricky to find where it's updated. 

But this also affects mobile sice it's in suite common, i hope it wont break anything

**Review by tomasklim — APPROVED** [review]
