### PR TITLE
fix(suite): hide progress bar on eth unstake

### LINKED ISSUE #24520: When unstaking ETH, staking progress bar is shown
Hide the progress bar when unstaking. 

If you want, please check and refactor the `useProgress...` component as it is kinda mess.

Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Hide the staking progress bar on Ethereum unstake. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/24520

### CODE REVIEW

File: packages/suite/src/views/wallet/staking/components/StakingDashboard/hooks/useProgressLabelsData.tsx [hunk 1]
```diff
@@ -16,256 +17,314 @@ import { Column, Paragraph } from '@trezor/components';
...
-    stakeTxs: WalletAccountTransaction[];
-    isStakedWithEverstake: boolean;
-};
+    isDaysToAddToPoolShown: boolean;
+    daysToAddToPool?: number;
+}): ProgressLabelData[] => [
+    {
+        id: 0,
+        'data-testid': '@staking/transaction-status',
+        progressState: (() => (isStakeConfirming ? 'active' : 'done'))(),
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/staking/components/StakingDashboard/hooks/useProgressLabelsData.tsx]:
```suggestion
        progressState: isStakeConfirming ? 'active' : 'done'
```

**Review by tomasklim — APPROVED** [review]
LGTM, one small change

File: packages/suite/src/views/wallet/staking/components/StakingDashboard/hooks/useProgressLabelsData.tsx (hunk 1 above)
Comment (dev-pvl) [reply packages/suite/src/views/wallet/staking/components/StakingDashboard/hooks/useProgressLabelsData.tsx]: fixed and rebased
