### PR TITLE
fix(suite): add graph updater that reats to the transactions

### LINKED ISSUE #20342: Graph on dashboard not updating when device in "view-only" mode
**Describe the bug**
Graph on the dashboard is not updating when the device is in view only mode.

**Steps to reproduce:**
1. Connect a device
2. Enable "view-only"
3. Send a transaction
4. The dashboard graph is not updated with this transaction

**Info:**
 - Suite version: web 25.8.0 (b8ad5148686b524d6d8f60c90d55a05b0b47b3f3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1800x1169
 - Device: Trezor T3B1 2.8.10 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: BridgeTransport 3.0.0-bundled.25.6.3

### PR DESCRIPTION
**Pull request by vojtatranta**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20342

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=20342-transactions-not-proagated-graph&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=20342-transactions-not-proagated-graph&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx [hunk 1]
```diff
@@ -90,6 +91,76 @@ export interface FiatGraphProps extends CommonProps {
 
 export type TransactionsGraphProps = CryptoGraphProps | FiatGraphProps;
 
+const emptyList: ReturnType<typeof selectAccountTransactionsWithNulls>[] = [];
+const useGraphUpdater = ({
```
Comment (vojtatranta) [inline packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: this is like MVP fix.

THe reason why I put it here is that there isn't any unified way of linke "queeing" some requests. So at least, it is scoped to the a rendereed component.

There is a code that refreshsed the graf data when an account is switched (`graphMiddleware`).
But that has a flag `newAccountsOnly` which only loads balances if there arent any data for that interval.
So I guess that was why it wasn't updated properly.

Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: Nevertheless, IMHO the graph should react to the transactions rather than like url itself.

Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: Yeah, so checking the current implementation. When you go back and forth on the account, it only loads the additional data tu it - so only loads data for new accounts.

I can't tell if there is some other logic that would periodically refresh graf.

Or like , if there is some hidden logic, that would refresh regardless of the if the account is new or not.

Yeah, it runs the update when discovery finishes. That's weird. Maybe intentional?

Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: Hm and the discovery isn't run for view-only devices on app startup... SO it is hardly no way to update the graph

Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: So my currentl conclusion is that in the current implementaion (develop) the graph won't ever update under normal circumstances.

So a solution I proposed up here is viable. Or similar solution can be nice.

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx [hunk 2]
```diff
@@ -90,6 +91,76 @@ export interface FiatGraphProps extends CommonProps {
...
+        .filter((tx): tx is WalletAccountTransaction =>
+            Boolean(Boolean(tx) && tx && !isPending(tx)),
+        );
+
+    const txIds = newestTransactions.map(tx => tx.txid);
+
+    const promiseId = txIds.join('-');
+
+    useEffect(() => {
+        if (promiseId !== currentPromise?.promiseId && account) {
```
Comment (vojtatranta) [inline packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx:122]: It is sad that I cannot omit the graph update when `currentPromise` is null (on mount). Coz in that case, there is still no code that would update the graph data.

I like this , coz the refresh of the graph data and the graph itself are colocated.

File: packages/suite/src/actions/wallet/graphActions.ts [hunk 3]
```diff
@@ -136,20 +140,28 @@ export const fetchAccountGraphData =
         }
     };
 
-export const updateGraphData =
-    (
-        accounts: Account[],
-        options?: {
-            newAccountsOnly?: boolean;
+export const updateGraphData = createThunk<
```
Comment (vojtatranta) [inline packages/suite/src/actions/wallet/graphActions.ts:143]: this dispatch-based retrieval is just so bad...

File: packages/suite/src/actions/wallet/graphActions.ts [hunk 4]
```diff
@@ -159,15 +171,30 @@ export const updateGraphData =
...
-    };
+            abortSignal?.throwIfAborted();
+
+            dispatch({
+                type: AGGREGATED_GRAPH_SUCCESS,
+            });
+
+            return;
+        } catch (error) {
+            if (error.name.toLowerCase().includes('aborterror')) {
```
Comment (Lemonexe) [inline packages/suite/src/actions/wallet/graphActions.ts]: nit: a more idiomatic way
```suggestion
            if (error.name === 'AbortError') {
```

**Comment by vojtatranta** [comment]
@evgenysl also checked it and said it works nice

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx [hunk 5]
```diff
@@ -90,6 +91,76 @@ export interface FiatGraphProps extends CommonProps {
...
+        abortController: AbortController;
+    } | null>(null);
+
+    const allTransactions = useSelector(state =>
+        account ? selectAccountTransactionsWithNulls(state, account.key) : emptyList,
+    );
+
+    const newestTransactions = allTransactions
+        .slice(0, 3)
+        .flatMap(tx => tx)
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: or what is the purpsoe of flatmap here?
```suggestion
        .flat()
```

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx [hunk 6]
```diff
@@ -90,6 +91,76 @@ export interface FiatGraphProps extends CommonProps {
...
+const useGraphUpdater = ({
+    shouldUpdateGraph,
+    account,
+}: {
+    shouldUpdateGraph: (abortController: AbortController) => Promise<any> | undefined;
+    account: Account | undefined;
+}) => {
+    const [currentPromise, setCurrentPromise] = useState<{
+        promiseId: string;
+        txIds: string[];
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: why is txIds in state? Not used.
PromiseId is sufficient, isn't it?

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx [hunk 7]
```diff
@@ -90,6 +91,76 @@ export interface FiatGraphProps extends CommonProps {
 
 export type TransactionsGraphProps = CryptoGraphProps | FiatGraphProps;
 
+const emptyList: ReturnType<typeof selectAccountTransactionsWithNulls>[] = [];
+const useGraphUpdater = ({
+    shouldUpdateGraph,
+    account,
+}: {
+    shouldUpdateGraph: (abortController: AbortController) => Promise<any> | undefined;
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: pls rename, `should` usually means boolean, this is callback that I'd name `onUpdateGraph`

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx [hunk 8]
```diff
@@ -90,6 +91,76 @@ export interface FiatGraphProps extends CommonProps {
...
+                        currentPromise?.promise?.then(
+                            result => result,
+                            error => {
+                                console.warn(
+                                    'useGraphUpdater: Previous graph update promise failed',
+                                    error,
+                                );
+                            },
+                        ),
+                    )
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: this is just for debugging?

Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: like the logging? yes, I probably delete it

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx (hunk 7 above)
Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: `onRequestGraphUpdate`

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx (hunk 6 above)
Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: yeah, I thought Like I am gona compare the transactions. Likely useless. I want to request the graph data for the latest TXs

File: packages/suite/src/actions/wallet/graphActions.ts (hunk 4 above)
Comment (vojtatranta) [reply packages/suite/src/actions/wallet/graphActions.ts]: I am not yet sure about what does it throws... So I'll check

Comment (Lemonexe) [reply packages/suite/src/actions/wallet/graphActions.ts]: yeah it's this, I was dealing with it recently.
```
a = new AbortController(); a.abort(); try{a.signal.throwIfAborted() }catch(e){console.log(e.name)}
```

File: packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx (hunk 8 above)
Comment (vojtatranta) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: but like I still want to "swallow" this error here and keep going to the next promise

Comment (Lemonexe) [reply packages/suite/src/components/suite/graph/TransactionsGraph/TransactionsGraph.tsx]: ok then

**Review by Lemonexe — APPROVED** [review]
LGTM and works properly, I tested on regtext: incoming Tx directly, and mining a block with incoming pending tx
