### PR TITLE
fix(suite): Fix QR code background in dark mode

### LINKED ISSUE #13083: QR code is inverted in dark mode
**Describe the bug**
When the app is in dark mode, the QR code is shown with inverted colors.
This is non-standard and while _some_ QR scanners can deal, not all of them, because they expect dark-on-light scheme.

**Info:**

-   Suite Version: web 24.6.2

**How to reproduce**

1. enable dark mode
2. go to a Receive tab
3. show an address + QR code

**Expected behavior**
Dark-mode QR code should not be inverted. It should be the same as light-mode QR code, surrounded by at least one cell wide white border.

**Screenshots**
image image

**Additional context**
reported on the forum: https://forum.trezor.io/t/qr-code-cannot-be-scanned-in-dark-mode-both-trezor-suite-desktop-and-web-based-are-affected/18111/2

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

There are two occurrences of `QrCode` component in suite:
- `PromoBanner` uses default `QrCode` colors, works as intended
- `ConfirmValueModal` used colors from theme to override `QrCode`, will use constant colors instead

## Related Issue

Resolve #13083

## Screenshots:

Dark mode before & after:

### ConfirmValueModal _unconfirmed_
image
image

### ConfirmValueModal _confirmed_
image
image

### PromoBanner
image
image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmValueModal/ConfirmValueModal.tsx [hunk 1]
```diff
@@ -135,6 +133,9 @@ export const ConfirmValueModal = ({
         }
     }, [canConfirmOnDevice, dispatch, isConfirmed, modalContext, validateOnDevice]);
 
+    // light theme colors are used always for QR code
+    const qrCodeFgColor = addressConfirmed ? colorVariants.standard.iconDefault : colorVariants.standard.iconSubdued
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/ReduxModal/ConfirmValueModal/ConfirmValueModal.tsx]: what about using color from `palette` directly? 

e.g.`palette.darkGray1000`?

Comment (Lemonexe) [reply packages/suite/src/components/suite/modals/ReduxModal/ConfirmValueModal/ConfirmValueModal.tsx]: Done (though `lightGray1000` is the appropriate one)

**Review by jvaclavik — APPROVED** [review]
image

**Review by MiroslavProchazka — APPROVED** [review]
Ship it
