### PR TITLE
fix(suite): fix label drop for RBF transactions

### LINKED ISSUE #10047: Replacing transaction wipes its label
When replacing a transaction via Bump fee or Finalize transaction, its label is wiper if there's one already.

Suite version: 23.11.5 app (Apple Silicon)
Device: T2B1 FW 2.6.3
OS: MacOS 14.1.1

How to reproduce:

1. Go to send a transaction (I've tried Bitcoin testnet)
2. Label the transaction in the send form or in transaction history right after approving the transaction
3. Bump fee or finalize transaction
4. Observe if the label is gone

Expected behavior: The label should stay the same, replacing transaction shouldn't change it in any way as for the user it's the same transaction no matter if the txid has changed.

Video:

https://github.com/trezor/trezor-suite/assets/88533514/b9fe95cc-feb7-4ef0-ba29-e08bcb3ba377

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

This PR fixies the issue of replacing the transaction (RBF for example) drops the label for it.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10047

### CODE REVIEW

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 1]
```diff
@@ -250,7 +251,41 @@ const pushTransaction =
...
+            const isRbf = precomposedTx.prevTxid !== undefined;
+
+            if (isRbf) {
+                const accountMetadata = selectLabelingDataForAccount(getState(), account.key);
+                const oldLabeling = accountMetadata?.outputLabels?.[precomposedTx.prevTxid];
+
+                const synchronize = getSynchronize();
+
+                Object.entries(oldLabeling).forEach(([outputIndex, value]) => {
+                    synchronize(() =>
```
Comment (peter-sanderson) [inline packages/suite/src/actions/wallet/sendFormActions.ts:263]: Synchronize to prevent race condition on write.

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 2]
```diff
@@ -340,7 +377,10 @@ const pushTransaction =
                     // propagate metadata to reducers and persistent storage
                     .forEach((output, index, arr) => {
                         const isLast = index === arr.length - 1;
-                        dispatch(metadataActions.addAccountMetadata(output, isLast));
+
+                        synchronize(() =>
```
Comment (peter-sanderson) [inline packages/suite/src/actions/wallet/sendFormActions.ts:362]: Synchronize to prevent race condition on write added here as well.

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 3]
```diff
@@ -250,7 +251,41 @@ const pushTransaction =
...
+                                txid: precomposedTx.prevTxid, // delete original label
+                                outputIndex: Number(outputIndex),
+                                defaultValue: '',
+                                value: '',
+                            }),
+                        ),
+                    );
+                    synchronize(() =>
+                        dispatch(
+                            metadataActions.addMetadata({
```
Comment (peter-sanderson) [inline packages/suite/src/actions/wallet/sendFormActions.ts:277]: Maybe it would be good to handle labeling in the `replaceTransactionThunk` but this is insuite-common/wallet-core` and labling code is not available there.

Maybe it would be good to extract labeling from the suite and make it separate so it can be used in mobile one day as well.

File: packages/suite/src/actions/suite/metadataActions.ts [hunk 4]
```diff
@@ -102,8 +103,8 @@ const createProviderInstance = (
             return new GoogleProvider(tokens, environment);
         case 'fileSystem':
             return new FileSystemProvider();
-        default:
```
Comment (peter-sanderson) [inline packages/suite/src/actions/suite/metadataActions.ts:106]: This is an example of having default behavior (in this case throwing).

With strict mapping it is not possible to not handle all cases (all providers)

File: packages/suite/src/actions/suite/metadataActions.ts [hunk 5]
```diff
@@ -643,11 +646,6 @@ const encryptAndSaveMetadata =
             getProviderInstance({ clientId: provider.clientId, dataType: 'labels' }),
         );
 
-        if (!providerInstance) {
```
Comment (peter-sanderson) [inline packages/suite/src/actions/suite/metadataActions.ts:646]: With strict mapping this is no longer possible and this default handler can be removed.

File: suite-common/metadata-types/src/metadataTypes.ts [hunk 6]
```diff
@@ -50,7 +50,7 @@ export type MetadataAddPayload =
 // }
 export type MetadataItem = string;
 
-export type MetadataProviderType = 'dropbox' | 'google' | 'fileSystem' | 'sdCard';
+export type MetadataProviderType = 'dropbox' | 'google' | 'fileSystem' | 'inMemoryTest'; // Todo: | 'sdCard'
```
Comment (peter-sanderson) [inline suite-common/metadata-types/src/metadataTypes.ts:53]: Intentionally dropping the `sdCard` option as it is not implemented yet

File: packages/suite/src/actions/suite/metadataActions.ts [hunk 7]
```diff
@@ -78,20 +80,19 @@ export type MetadataAction =
...
+
 const fetchIntervals: { [deviceState: string]: any } = {}; // any because of native at the moment, otherwise number | undefined
 
 const createProviderInstance = (
     type: MetadataProvider['type'],
     tokens: Tokens = {},
     environment: OAuthServerEnvironment = 'production',
     clientId?: string,
-) => {
+): DropboxProvider | GoogleProvider | FileSystemProvider | InMemoryTestProvider => {
```
Comment (peter-sanderson) [inline packages/suite/src/actions/suite/metadataActions.ts:94]: This needs to be exhaustive because `clientId`  property is not part of the parent AbstractClass. 

Shall be refactored in the future probably.

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts
Comment (dahaca) [inline packages/suite/src/actions/wallet/moveLabelsForRbf.ts:1]: `moveLabelsForRbfActions`

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+}: FindLabelsToBeMovedOrDeletedParams): LabelsToBeMovedOrDeleted => {
+    const result: LabelsToBeMovedOrDeleted = {};
+
+    const accountTransactions = findTransactions(
+        prevTxid,
+        getState().wallet.transactions.transactions,
+    );
+
+    // eslint-disable-next-line no-restricted-syntax
+    for (const accountTransaction of accountTransactions) {
```
Comment (dahaca) [inline packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: Why not `map`? It's used everywhere for those cases + you won't have to turn the linter off ;D

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 9]
```diff
@@ -213,6 +214,15 @@ const pushTransaction =
         const device = selectDevice(getState());
         if (!signedTx || !precomposedTx || !account) return;
 
+        const isRbf = precomposedTx.prevTxid !== undefined;
+
+        const toBeMovedOrDeletedList = isRbf
+            ? findLabelsToBeMovedOrDeleted({
```
Comment (dahaca) [inline packages/suite/src/actions/wallet/sendFormActions.ts]: why not put it inside of `moveLabelsForRbf`?

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 10]
```diff
@@ -250,7 +260,16 @@ const pushTransaction =
                 }),
             );
 
-            if (precomposedTx.prevTxid) {
+            if (isRbf) {
+                if (toBeMovedOrDeletedList !== undefined) {
```
Comment (dahaca) [inline packages/suite/src/actions/wallet/sendFormActions.ts:261]: if `isRbf`, then `toBeMovedOrDeletedList` is never `undefined` I think?

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts [hunk 11]
```diff
@@ -0,0 +1,154 @@
...
+
+                const deleteParams: DeleteAllOutputLabelsParams = {
+                    accountKey,
+                    dispatch,
+                    labels: accountOutputLabelsToBeDeleted,
+                    txid: transactionToDrop.txid,
+                };
+
+                // eslint-disable-next-line no-await-in-loop
+                await deleteAllOutputLabels(deleteParams);
```
Comment (dahaca) [inline packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: nit: consider renaming the action, that action is deleting unused labels, "all output" sounds too extreme :D

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts [hunk 12]
```diff
@@ -0,0 +1,154 @@
...
+        // eslint-disable-next-line no-restricted-syntax
+        for (const toBeMovedOrDeleted of Object.entries(toBeMovedOrDeletedList)) {
+            const [accountKey, data] = toBeMovedOrDeleted;
+
+            const accountMetadata = selectLabelingDataForAccount(getState(), accountKey);
+            const accountOutputLabelsToBeMoved: AccountOutputLabels =
+                accountMetadata?.outputLabels?.[data.toBeMoved.txid] ?? {};
+
+            // eslint-disable-next-line no-await-in-loop
+            await moveLabelToNewTransaction({
```
Comment (dahaca) [inline packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: nit: consider renaming the action. Move sounds like the old ones are deleted as a part of this action

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts [hunk 13]
```diff
@@ -0,0 +1,154 @@
...
+    AccountKey,
+    {
+        toBeMoved: WalletAccountTransaction;
+        toBeDeleted: WalletAccountTransaction[];
+    }
+>;
+
+export const findLabelsToBeMovedOrDeleted = ({
+    prevTxid,
+    getState,
```
Comment (dahaca) [inline packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: if written as a thunk, the get state is available without passing. I would rewrite 🙏

**Review by dahaca — COMMENTED** [review]
Ideally @mroz22 should take a look as well ;)

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts (hunk 8 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: Good point! thanks! it a leftover from previous version when I had asynchronous code there

Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: :heavy_check_mark:

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts:1]: :heavy_check_mark:

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 9 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/sendFormActions.ts]: This needs to happen before the `pushTransaction`, after this (`pushTransaction`) is called the state is changed (transactions are discarded) and I wont find some transactions and therefore there will be danging labels.

File: packages/suite/src/actions/wallet/sendFormActions.ts (hunk 10 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/sendFormActions.ts:261]: Yes it is, but Typescript doesn't know that.

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts (hunk 11 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: :heavy_check_mark:

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts (hunk 12 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: :heavy_check_mark:

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts (hunk 13 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts]: :+1:

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts
Comment (dahaca) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts:1]: could you change it to plural please? 😓

**Review by dahaca — APPROVED** [review]
All good! ✅

File: packages/suite/src/actions/wallet/moveLabelsForRbf.ts
Comment (peter-sanderson) [reply packages/suite/src/actions/wallet/moveLabelsForRbf.ts:1]: :+1:

**Comment by bosomt** [comment]
**QA NOK**

sent two transactions with label,
bumped - no label present, 
transaction confirmed - no label present

image

image

**Info:**
 - Suite version: desktop 24.2.0 (81d011d6dc01c0135cb38b989270cec8b9f74a57)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Comment by peter-sanderson** [comment]
@bosomt (hopefully) finally fixed in: https://github.com/trezor/trezor-suite/pull/19807
