### PR TITLE
Fix: changelog for is required

### LINKED ISSUE #22028: Runtime typedCall: Device not initialized when calling GetPublicKey. call Initialize first
Account discovery runs even for outdated firmware requiring update.

Sentry Issue: [TREZOR-SUITE-16R4](https://satoshilabs.sentry.io/issues/6854313058/?referrer=github_integration)

```
Runtime typedCall: Device not initialized when calling GetPublicKey. call Initialize first
```

### PR DESCRIPTION
**Pull request by karliatto**
## Description
* Adding missing `"required": true,` since when we change to the format of releases JSON, we used data.trezor.io as source of truth, but some of those `required` were only changed in the copy of those releases.json files in Suite.
* Returning `getChangelog` and `isRequired` function to firmware info so if there is `"required": true` in any release between the current one and the last one it is marked as required and therefore the Device is not allowed to be used in Suite until it is properly updated.
* I had to update the tests and I add couple of improvements as well that I could not stop my self from doing.

Resolves https://github.com/trezor/trezor-suite/issues/22028

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/changelog-for-is-required&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/changelog-for-is-required&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/changelog-for-is-required&lookback=7)

### CODE REVIEW

File: packages/connect/src/data/firmwareInfo.ts [hunk 1]
```diff
@@ -560,11 +612,16 @@ export const getFirmwareReleaseConfigInfo = (features: Features, firmwareType: F
         versionContext.version &&
         versionUtils.isNewerOrEqual(versionContext.version, release[versionContext.minVersionKey]);
 
+    const releasesOfDevice = getReleasesAssetByDeviceModelAndFirmwareType(
+        features.internal_model,
+        firmwareType,
+    );
+
```
Comment (mroz22) [inline packages/connect/src/data/firmwareInfo.ts:625]: so this fn existed before but was unused 🤔

Comment (karliatto) [reply packages/connect/src/data/firmwareInfo.ts:625]: No, it was used in `findBestCompatibleRelease` just few lines below.
Now it is using it for other purpose as well so I extracted.

**Comment by karliatto** [comment]
@MiroslavProchazka there is an unexpected force-push, did you rebase or what was the reason?

image

There are now unrelated lines that I am sure I did not add there like:


```
const bridgeTransport = new BridgeTransport({ messages, port: 21325, sessionOwnerId: 'bridge' });
```

File: packages/connect/src/data/firmwareInfo.ts (hunk 1 above)
Comment (mroz22) [reply packages/connect/src/data/firmwareInfo.ts:625]: btw where do these releases come from? is it any of these requests? 
image

File: suite-native/state/src/extraDependencies.ts [hunk 2]
```diff
@@ -20,7 +20,7 @@ import { mergeDeepObject } from '@trezor/utils';
 
 const deviceType = Device.isDevice ? 'device' : 'emulator';
 
-const bridgeTransport = new BridgeTransport({ messages, port: 21325, id: 'bridge' });
+const bridgeTransport = new BridgeTransport({ messages, port: 21325, sessionOwnerId: 'bridge' });
```
Comment (mroz22) [inline suite-native/state/src/extraDependencies.ts]: ups, sry, I accidentally commited my local change, fixup incoming

File: packages/connect/src/data/firmwareInfo.ts (hunk 1 above)
Comment (mroz22) [reply packages/connect/src/data/firmwareInfo.ts:625]: aha, I see, it is javascript baked-in here https://github.com/trezor/trezor-suite/blob/fix/changelog-for-is-required/packages/connect-common/src/map-releases.ts#L10

Comment (karliatto) [reply packages/connect/src/data/firmwareInfo.ts:625]: Right, there is the baked in, but if the remote releases.v1 contains a higher sequence than the baked one the in gets the releases that are defined in that `releases.v1` remote.

**Review by mroz22 — APPROVED** [review]

**Comment by mroz22** [comment]
@MiroslavProchazka all good from my POV, lets leave it to @karliatto to merge
