### PR TITLE
fix(suite): pin and passphrase modal cancellable

### LINKED ISSUE #6643: Quit keyboard shortcut unavailable in app when T1 PIN dialogue open
**Describe the bug**
It's not possible to quit Trezor Suite app  via keyboard shortcut /Alt+F4 in Windows and Command+q in macOS/ when there is Trezor model One PIN dialogue modal open.

**Steps to reproduce:**
1. Connect model One device with PIN enabled
2. Start app
3. When asked for PIN try to quit app via keyboard.

**Info:**
 - Suite version: desktop 22.10.3 (540db5426ce88c33bdda2fdae0ceb50f6cbc4a23)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.10.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: 
 - Transport: bridge 2.0.31

**Screenshots:**
image

### LINKED ISSUE #6941: Ability to cancel actions
When user clicks on `Add (hidden) wallet` in `Wallets` he cannot cancel `Select wallet type` action.
image

Same behaviour is under `Enter passphrase on Trezor` and `Enter PIN` popup for T1.

image
image

Put a canceling cross on these tabs as in `Wallets`:
image

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- cancellable pin
- cancellable wallet and hidden wallet
- closable app when pin modal opened

## Related Issue

closes #6941
closes #6643 (confirm on device abort is skipped for now, it's too generic)

## Screenshots:
Screenshot 2023-04-26 at 9 38 57
Screenshot 2023-04-26 at 9 39 46
Screenshot 2023-04-26 at 9 40 20
Screenshot 2023-04-26 at 9 41 11
Screenshot 2023-04-26 at 13 24 41
Screenshot 2023-04-26 at 13 24 56
Screenshot 2023-04-26 at 13 25 57
Screenshot 2023-04-26 at 13 43 17

### CODE REVIEW

**Comment by mroz22** [comment]
just please check bridge 27

**Comment by tomasklim** [comment]
@mroz22 It's okay

File: packages/suite/src/views/dashboard/components/AssetsCard/index.tsx [hunk 1]
```diff
@@ -193,6 +193,7 @@ const AssetsCard = () => {
                                 color={theme.TYPE_RED}
                                 size={14}
                             />
+                            &nbsp;
```
Comment (komret) [inline packages/suite/src/views/dashboard/components/AssetsCard/index.tsx]: Please style the `Icon` instead. It should be styled with CSS instead of the `style` property which is not read anyway.

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/dashboard/components/AssetsCard/index.tsx (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/views/dashboard/components/AssetsCard/index.tsx]: 😨 1599f9c398e028a2e171dfa8716a5e24abfac528

**Review by komret — APPROVED** [review]
Nice improvements. I wish opening the passphrase modal did not redirect immediately - this way you could stay on the current route if you close it which is much more convenient than an unloaded account.

**Comment by bosomt** [comment]
**QA OK**

tested with 2.0.27, 2.0.33 and webUSB 

**Info:**
 - Suite version: desktop 23.5.0 (0e2010aa3ca28fd407107948cb608de5c36a02b8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.5.0 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model 1 1.12.0 Bitcoin-only (revision a97dfd3a4f4a709a08e125946f6e1c96a0cc7ec0)
 - Transport: BridgeTransport 2.0.33
