### PR TITLE
fix(suite-native): fix navigating from Connect and Unlock screen when device is connected

### LINKED ISSUE #13198: Connect device stuck when physical device that's also view-only is connected & unlocked
Connect device stuck when physical device that's also view-only is connected & unlocked 

**Info:**

-   Mobile Suite Version: 24.6.0., commit: 0af43838cf5d13a9566619b2dea......
-   OS: ios 17.5

**How to reproduce**

When I go to app -> wallet switcher -> change -> connect another device and connect the device that's also view-only, the connect screen does nothing and stays there. When X clicked

**Expected behavior**
No matter if the device is view-only or not, when in connect screen & unlocking device successfully, I should be moved to dashboard with correct device open

**Screenshots**
image

**Additional context**
None

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

Navigate out of Connect & Unlock screen if selected device is connected.
Also hide the button to Connect & Unlock screen if selected device is already connected to prevent immediate navigation back...

I use `goBack` instead of navigating to dashboard to keep it more general and allow to go back to settings, where the Device Switcher is also available.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13198

## Screenshots:

https://github.com/user-attachments/assets/59c8f380-bb0f-4222-bac7-941a3fcb8e93

### CODE REVIEW

File: suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx [hunk 1]
```diff
@@ -50,6 +53,15 @@ export const ConnectAndUnlockDeviceScreen = () => {
         }
     }, [isDeviceAuthorized, device, dispatch, isFocused]);
 
+    useEffect(() => {
+        if (isFocused && isDeviceConnected) {
+            // When selected device become connected, we need to navigate out of this screen.
+            if (navigation.canGoBack()) {
+                navigation.goBack();
```
Comment (vytick) [inline suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: Wont this make previous useEffect irrelevant?  

``` if (isFocused && device && !isDeviceAuthorized) {```

Comment (matejkriz) [reply suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: Yes! Thanks for the catch 👍

Comment (matejkriz) [reply suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: 7b95a242ce99463f8145434b837f96ecfe336838

**Review by vytick — APPROVED** [review]
looks good! 💪
