### PR TITLE
Prevent jumping of bottomsheet with input behind the keyboard

### LINKED ISSUE #23673: Keyboard aware input for account name edit jump behind the keyboard
**Describe the bug**
If I try to edit existing account label having Suite Sync turned on, it happen from time to time that the input jumps to the bottom of the screen below the keyboard.

**Info:**

- Mobile Suite Version: develop
- OS: ios

**How to reproduce**

1. Go to Account detail, Account Settings, Edit name
1. Delete the existing label in the input
1. Type any single letter of a new label
1. See error

**Expected behavior**
Input should be always visible above the keyboard.

**Screenshots**

Image

https://github.com/user-attachments/assets/9721a7dd-ebc8-4e9b-895a-82465fda6da8

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

- The only workaround that seems to help is prolonging the timeout before autofocus happens. If autofocus happens too early, the bottom sheet position is miscalculated, and that could lead to unexpected behavior. 
For the ultimate solution, we would need to change the design, I'm afraid.

There are 2 more small changes in this PR:
- Forcing validation on text change, because it happened to me many times, that I didn't see the "Field is mandatory" error for empty input. (I thought that it was related to the main bug, but I don't think so anymore)
- Deleting custom hint for input length and use default hint feature of the text input field.

## Notes for QA

Try it many times, please.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23673

## Screenshots:

https://github.com/user-attachments/assets/8b3d778f-0cd3-40ef-b32b-9aa99e9ef2e6

https://github.com/user-attachments/assets/7b871cf3-edba-4bd2-9a0b-51b86b62d0df

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/bottomsheet-inputs&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/bottomsheet-inputs&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/bottomsheet-inputs&lookback=7)

### CODE REVIEW

File: suite-native/module-accounts-management/src/components/AccountRenameForm.tsx [hunk 1]
```diff
@@ -48,8 +48,13 @@ export const AccountRenameForm = ({ accountKey, onSubmit }: AccountRenameFormPro
         handleSubmit,
         formState: { isValid },
         control,
+        trigger,
     } = form;
 
+    const accountLabelLength = useWatch({ control, name: 'accountLabel' })?.length ?? 0;
+
+    const forceValidation = useCallback(() => trigger('accountLabel'), [trigger]);
```
Comment (PeKne) [inline suite-native/module-accounts-management/src/components/AccountRenameForm.tsx]: Should not this be done by setting `mode: onChange` argument to the useForm (useAccountLabelForm) hook?

https://react-hook-form.com/docs/useform#mode

**Review by PeKne — APPROVED** [review]
One nit found, otherwise works as expected.

File: suite-native/module-accounts-management/src/components/AccountRenameForm.tsx (hunk 1 above)
Comment (matejkriz) [reply suite-native/module-accounts-management/src/components/AccountRenameForm.tsx]: You are right, mode: onChange would be better, but the whole solution was wrong and adding unstandard behavior. So I've changed that to only hide hint if there is error visible, so keep the hint visible before submit.

Comment (matejkriz) [reply suite-native/module-accounts-management/src/components/AccountRenameForm.tsx]: dc7c9937f15aa8643e54f98e323a52de0a48fb6c
