### PR TITLE
Make the native backup flow work the same

### LINKED ISSUE #24511: TS7 – Backup failure scenarios
In all cases, the device is connected **via cable**. 

**Case 1**
The user starts the wallet backup process using Shamir Backup, and the words are generated. The device is then disconnected from the computer and the user continues writing down the words. At the end of the first share, the device asks to verify that three words are correct. After entering and confirming them, the process moves to the next share — at this point, the device reports an error _"Your Trezor is having trouble communicating with your connected device"_ and the backup fails.

https://github.com/user-attachments/assets/1f02eb08-81ac-44d7-98a9-fbd5f74e778d

**Case 2**
The user disconnects the device from the computer while writing down his words and immediately reconnects it — the backup fails.

**Case 3**
If a THP device is wiped within Trezor Suite (Settings → Device → Wipe), there is a risk that when creating a backup afterward, the backup will fail immediately after generation (before the device displays the words). Trezor Suite shows a “backup failed” message, but the device does not display this information.

Image

**Info:**
 - Suite version: desktop 26.2.0 (8630040eec666a008752b5b910cffcb65b15a28d)
 - Browser: Trezor Suite 26.2.0
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: 
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by vojtatranta**
## Description

We are making the desktop wallet creation + backup work the same as the mobile one. (merging the wallet creation + backup together). So when the backup is anyhow interrupted (unplug, BT disconnect) the wallet creation fails and device is wiped. Before, the device stayed in the state like "backup failed, wipe the device"
‼️ @vojtatranta add this https://satoshilabs.slack.com/archives/C07CPLU4SE8/p1773749532622599?thread_ts=1770222748.019379&cid=C07CPLU4SE8

## Notes for QA

This PR aligns the create wallet + backup flow on desktop with native. Meaning, the wallet creation and backup guide is made as a "one step" on the device. Not as in the past, where on the desktop user first created a wallet, then he clicked in the Suite Onboarding to continue to backup.

Reason for change: if backup fails (eg. disconnecting the device, BT connection drops) the device isn't "bricked" in the state state "backup failed".

I am kindly asking you to test **all the devices** and go through the onboarding while trying to disconnect the device. At that case ,device should just appear to be wiped and ready to be set-up.

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/24511 https://github.com/trezor/trezor-suite/issues/25009

## Screenshots:
Added / Edited screens
Screenshot 2026-03-26 at 3 01 38 PM
Screenshot 2026-03-26 at 3 01 03 PM
Screenshot 2026-03-26 at 3 00 58 PM

Screenshot 2026-04-01 at 11 04 26 AM

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=25009-backup-create-onboarding-alignment&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=25009-backup-create-onboarding-alignment&lookback=7)

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=25009-backup-create-onboarding-alignment&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=25009-backup-create-onboarding-alignment&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Analytics Events > Analytics captures important events when started enabled by default | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-27T09:08:57.102Z • 7 test(s) total_

<details><summary>Trezor Suite (desktop) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Staking - Cardano > Stake Cardano | 🤖 auto |
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |
| Firmware not ready | 🙋 manual |

</details>

_Updated: 2026-03-23T13:45:27.046Z • 7 test(s) total_

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/SecurityStep.tsx [hunk 1]
```diff
@@ -1,46 +1,109 @@
...
+
+    const getResetDeviceParams = useCallback(() => {
+        switch (backupType) {
+            case 'shamir-single':
+            case 'shamir-advanced':
+                return { backup_type: 1 as const, skip_backup: false };
+            case '12-words':
+                return { backup_type: 0 as const, strength: 128, skip_backup: false };
+            case '24-words':
+                return { backup_type: 0 as const, strength: 256, skip_backup: false };
```
Comment (peter-sanderson) [inline packages/suite/src/views/onboarding/steps/SecurityStep.tsx]: missing exhustive here I guess

**Comment by vojtatranta** [comment]
Mihovil's comment https://satoshilabs.slack.com/archives/C07CPLU4SE8/p1770993880835639?thread_ts=1770736388.346959&cid=C07CPLU4SE8

**Comment by vojtatranta** [comment]
@STew790 says, that there is a problem:
- if a users goes to the phase where he reads the backup seed from the device and at that moment BT is disconnected, Suite will after reconnect wipe the device
- Roman Zeyde says that guys can fix it in the FW

So it doesn't seem to be a blocker for this PR.

**Comment by STew790** [comment]
**QA OK**
All scenarios looks good to me. I was able to start over again every time when I interrupted the flow. The only issue is with TS7 where you should be able to continue with the backup words showing on device even with Suite killed (or refreshed or BLE connection lost, or etc.) but that will be handled on FW side https://github.com/trezor/trezor-firmware/issues/6348

File: packages/suite/src/components/backup/BackupSeedCards.tsx [hunk 2]
```diff
@@ -31,31 +31,28 @@ export const BackupSeedCards = () => {
...
-            >
+            <Paragraph typographyStyle="body-sm" align="center">
                 <Translation id="TR_ONBOARDING_CLICK_TO_CONFIRM" />
             </Paragraph>
             <Grid gap={16} columns={isBelowTablet ? 1 : 3}>
                 {items.map(item => (
                     <Card
-                        paddingType="large"
+                        paddingType="normal"
+                        height="100%"
```
Comment (vojtatranta) [inline packages/suite/src/components/backup/BackupSeedCards.tsx:41]: @seibei-iguchi kill me, how to do it better pls?

Comment (seibei-iguchi) [reply packages/suite/src/components/backup/BackupSeedCards.tsx:41]: Why change the seed cards?

Comment (vojtatranta) [reply packages/suite/src/components/backup/BackupSeedCards.tsx:41]: Mihovil ordered differetn alignment https://www.figma.com/design/GCOLpIOfFiMW4CnWlUOKwG/Wallet?node-id=6219-9559&t=Di8xicw9oy5Ik3Qn-0

Comment (seibei-iguchi) [reply packages/suite/src/components/backup/BackupSeedCards.tsx:41]: I think it's fine the way you did it. I'm not sure if the height="100%" is needed though, since it's grid so all the Card should the same height, but whatever:)

**Review by seibei-iguchi — APPROVED** [review]

**Comment by vojtatranta** [comment]
ON HOLD @arthurzablocki-trezor is talijng with the C level

**Comment by vojtatranta** [comment]
@vojtatranta add this https://satoshilabs.slack.com/archives/C07CPLU4SE8/p1773749532622599?thread_ts=1770222748.019379&cid=C07CPLU4SE8

**Comment by vojtatranta** [comment]
@arthurzablocki-trezor said: |Can we still deploy your fix while keeping the Skip Backup for the users?

And yes, it it possible, will do it here

**Comment by zako05** [comment]
QA OK ✅

- The "Happy Path": Select "Standard Seed" -> Security Step -> Start Backup -> Complete the full word verification on the device -> Success. ✅


https://github.com/user-attachments/assets/030bcb70-24ae-4686-a975-3331666785b5


https://github.com/user-attachments/assets/56edc8fc-572a-439c-8fe7-e6f6731381b6


https://github.com/user-attachments/assets/b66bae41-6756-4ae7-8aa2-2eb50c84bf5f


https://github.com/user-attachments/assets/06bd0526-4355-4d00-a375-b2206a4d28cd


https://github.com/user-attachments/assets/31c47ec8-f9db-4a0b-89d3-19375daba6df


https://github.com/user-attachments/assets/59937d49-a3de-43dc-8c79-7bd3d7243b4b

**- Abort on Device: Create wallet backup:**
  - **Cancel "wallet creation" on the device** (TC: create new wallet -> select "wallet backup type" & continue -> create wallet backup -> on the device: **burger menu -> cancel**) ✅
  - **Cancel "wallet backup" on the device** (TC: create new wallet -> select "wallet backup type & continue ->  create wallet backup -> on the device: "hold to continue" in wallet creation -> "wallet created" continue -> backup: **burger menu -> skip backup**) ✅
  - **Expectation**: Device should wipe itself and Suite should return to the initial onboarding state. 

https://github.com/user-attachments/assets/b6a0fbb9-25f0-4f2a-a508-f9e38b9c0a04

https://github.com/user-attachments/assets/e402e949-df1b-4331-af52-d7a8f7345285

https://github.com/user-attachments/assets/8fca3bd7-ed49-419d-aa22-17c4fac14896

https://github.com/user-attachments/assets/99ff0dab-36da-43c2-aa0e-9b828bb75607

**- Abort on Device: Skip wallet backup:**
  - ** Cancel wallet creation" on the device** (TC: skip wallet backup -> "skip wallet backup" confirmation -> on the device: **burger menu -> cancel**) ✅
  -  Expectation: A confirmation modal appears. Confirming it should create the wallet on the device without entering the backup flows

**- Device Disconnection**: Unplug the device while it's showing seed words during the atomic flow.
  - **Disconnect BT:** (TC: Disconnect the device during "create wallet backup) ✅
  - **Disconnect USB:** (TC: Unplug USB from device during "create wallet backup) ✅
  - **Expectation**: Upon reconnection, the device should be in a wiped/uninitialized state.

**Comment by zako05** [comment]
**Scenario 1**: Confirming "Create Wallet" in Suite, then Canceling on Device
    **Action**: I confirm "Create Wallet" in Trezor Suite but then cancel the prompt on the Trezor Safe 7 (TS7).
    **Result**: The UI moves to: "Device connected—complete setup to continue."

**Scenario 2**: Skipping "Wallet Backup" in Suite, then Canceling on Device
    **Action**: I select "Skip Wallet Backup" in Trezor Suite but then cancel the "Create Wallet" prompt on the TS7.
    **Result**: The UI returns to: "Create Wallet Backup."

**Feedback**
In both scenarios, the cancellation happens on the device during the same stage, yet the user ends up on different screens in Suite.
In the first case, the user is directed to the "Complete setup" screen, whereas in the second, they are sent back to "Create Wallet Backup." I’m not necessarily saying this is a bug, but it feels inconsistent from a UX perspective since the device-side action is identical in both instances.

cc @vojtatranta @mvargovic

**Comment by mvargovic** [comment]
@zako05 Good catch. Both cases actually cancels the first part which is Wallet creation. So, it make sense to show the same screen. User should land on this screen in both cases: 
Screenshot 2026-04-08 at 13 30 24

cc @vojtatranta

**Comment by vojtatranta** [comment]
> @zako05 Good catch. Both cases actually cancels the first part which is Wallet creation. So, it make sense to show the same screen. User should land on this screen in both cases: Screenshot 2026-04-08 at 13 30 24
> 
> cc @vojtatranta

roger

**Comment by vojtatranta** [comment]
> @zako05 Good catch. Both cases actually cancels the first part which is Wallet creation. So, it make sense to show the same screen. User should land on this screen in both cases: Screenshot 2026-04-08 at 13 30 24
> 
> cc @vojtatranta

fixed, merging

**Comment by obrusvit** [comment]
As of Firmware, this issue https://github.com/trezor/trezor-firmware/issues/6348 tracks our effort to make the backup flow "sticky".

Once the user gets to the point where they see the words, the flow cannot be manually aborted (there are no "Cancel" options on the device). This way, we want to prevent a scenario where a user writing down the backup loses all progress when Suite dies or gets somehow disconnected. This was especially troublesome when a user opted for multi-share backup and started punching words on Keep Metal.
