### PR TITLE
test(request-manager): manually test Tor identities

### LINKED ISSUE #6838: Investigate dying tor circuits
It seems tor circuits are dying too quick and it often prevent coinjoin from finishing - see part of the logs from CoinJoin and the `Proxy connection timed out` error:

<details>
  <summary>partial coinjoin log</summary>
  
 ```json
{
    "time": 1667477153387,
    "value": "Confirmation interval with error request to http://dev-coinjoin-testnet.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion/WabiSabi/connection-confirmation failed, reason: Proxy connection timed out"
  },
  {
    "time": 1667477123375,
    "value": "Confirming add038dd...02000000 to fdfd7540...6a64e13f with delay 0ms"
  },
  {
    "time": 1667477094875,
    "value": "Registration 30103ae2...01000000 to fdfd7540...6a64e13f failed: request to http://dev-coinjoin-testnet.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion/WabiSabi/input-registration failed, reason: Proxy connection timed out"
  },
  {
    "time": 1667477092057,
    "value": "Registration f6b96278...00000000 to fdfd7540...6a64e13f failed: request to http://dev-coinjoin-testnet.trezoriovpjcahpzkrewelclulmszwbqpzmzgub37gbcjlvluxtruqad.onion/WabiSabi/input-registration failed, reason: Proxy connection timed out"
  },
```
</details>

@szymonlesisz mentioned it's happening even after two minutes or so. 

To replicate and isolate the issue would be nice to write a simple test outside CoinJoin context - just open multiple tor circuits, try to use them in time for some request and observe when they start to fail.

Then we could try extend circuits lifespan to prevent too often recreation of new tor circuit that take some time. Also if there is any configurable limit for number of circuits we should check that. Those are just ideas, to find out what the problem really is the test script is probably needed.

### PR DESCRIPTION
**Pull request by karliatto**
## Description
I created this script to allow testing Tor identities by trying to stress them in a similar way that CoinJoin is doing. Many identities each sending a request during a period of time.

The testing is being done for 3 different interval requests of 1, 20 and 35 minutes, during a period of time of 2  hours. 
The were 0 errors during testing process. 
For interval requests of 1 minute the identities where keeping the same IP which probably means it was same circuit, instead for interval requests of 35 minutes the IPs of the same identity (username and password) where changing which makes sense since the lasting time of the circuits by configuration is 30 minutes.

I do not really think that testing this way makes much sense to find issues that would lead to improvements. But the script to test Tor manually has become already useful for me in other features so I can run Tor and do some quick tests, so  I think it is nice to have it as a testing script.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/6838

### CODE REVIEW

File: packages/request-manager/e2e/identities-stress.ts [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+const INTERCEPTOR = {
+    handler: () => {},
+    getIsTorEnabled: () => true,
+};
+
+const testGetUrlHttps = 'https://check.torproject.org/';
+
+const amountOfIdentities = 20;
+const intervalBetweenRequests = 1000 * 20;
```
Comment (mroz22) [inline packages/request-manager/e2e/identities-stress.ts:27]: maybe would be useful to change these in the course of the test - increase amountOfIdentities and decrease intervalBetweenRequests. But on the other hand, this would create a spamming machine :thinking: this is not what we want. How do we stress test without spamming? :thinking:

**Review by mroz22 — APPROVED** [review]
Has been running for a while on my machine without any errors.

File: packages/request-manager/e2e/identities-stress.ts [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+            return {
+                ip,
+            };
+        });
+        return Promise.all(requests);
+    };
+
+    try {
+        const ips = await makeRequests(identities);
+        console.log('ips', ips);
```
Comment (mroz22) [inline packages/request-manager/e2e/identities-stress.ts:82]: maybe it could be useful to add a check that all ips are different

Comment (mroz22) [reply packages/request-manager/e2e/identities-stress.ts:82]: but is this guaranteed? probably it is not, 2 different identities could  yield  the same ip I guess?

File: packages/request-manager/e2e/identities-stress.ts (hunk 1 above)
Comment (karliatto) [reply packages/request-manager/e2e/identities-stress.ts:27]: By spamming do you mean sending too many nonsense request to a server? If so we could call different URLs so we are not sending all the requests to the same one. But then we would be testing also the different servers because each one is going to be responding differently.

Yes I think changing the interval dynamically during the test could be interesting but I don't think the results would change.

I think the main idea was to test the  stability of many identities during a period of time, and I think it is done with this simple test. Of course the network is complex and it will have different outputs with different connections.

File: packages/request-manager/e2e/identities-stress.ts (hunk 2 above)
Comment (karliatto) [reply packages/request-manager/e2e/identities-stress.ts:82]: Yes, 2 different identities could have same output IP address, it is not guarantee.
