### PR TITLE
Fix/minor fixes 123

### LINKED ISSUE #1230: Change PIN
If PIN protection enabled, option to change PIN is to appear. 

**[Zeplin](https://zpl.io/VOnyj71)**

### LINKED ISSUE #1479: Add account hint misplaced
When you load accounts or add them there is hovering hint.
You don't see it when accounts are loaded.

Hint is misplaced, see video

https://www.youtube.com/watch?v=EJp4ZPlp53A&feature=youtu.be

### LINKED ISSUE #1480: Change second device settings behavior
Please change second device settings behavior or remove it.
It's causing confusion.
When you click on Device settings of second device it will take you to First device settings page.
 
image

### LINKED ISSUE #1485: formatCoinBalance bug
availableBalance: "10"
formattedBalance: "0.0000001"

Screenshot 2020-04-08 at 11 45 21

### LINKED ISSUE #1495: Weird size in some components (Fresh address card, price panel card)
Screenshot 2020-04-09 at 10 18 51
Screenshot 2020-04-09 at 10 19 02

### PR DESCRIPTION
**Pull request by slowbackspace**
close https://github.com/trezor/trezor-suite/issues/1230#issuecomment-610791641
close https://github.com/trezor/trezor-suite/issues/1485
close https://github.com/trezor/trezor-suite/issues/1479
close https://github.com/trezor/trezor-suite/issues/1495
close https://github.com/trezor/trezor-suite/issues/1480

- removed upload image button from QR scanner modal
- fix add account tooltip msg on disabled btn
- removed description from receive

Screenshot 2020-04-09 at 10 02 35

### CODE REVIEW

File: packages/suite/src/components/wallet/Menu/index.tsx [hunk 1]
```diff
@@ -174,6 +175,11 @@ const Menu = ({
                     })
                 }
                 disabled={!!addAccountDisabled}
+                tooltipMessage={
+                    !device.connected ? (
```
Comment (szymonlesisz) [inline packages/suite/src/components/wallet/Menu/index.tsx]: not sure about this, there are multiple reasons why "add account" is disabled
i think this tooltip (and its Tranlsation) should be dynamically defined inside AddAccount button

Comment (szymonlesisz) [reply packages/suite/src/components/wallet/Menu/index.tsx]: and maybe `useDeviceActionLocks` should be added too?
maybe whole logic of `addAccountDisabled` should be moved into AddAccount ?

Comment (slowbackspace) [reply packages/suite/src/components/wallet/Menu/index.tsx]: yup, I agree there are more reasons why the button could be disabled. Feel free to expand it in another PR, It seemed a bit out of scope for this PR. I just wanted to fix broken tooltip position and noticed there was some nonsense message in tooltip.
So this only fixes the position and adds correct message for the disconnected device case (for other cases tooltip simply won't show for now.)

Comment (szymonlesisz) [reply packages/suite/src/components/wallet/Menu/index.tsx]: since you already adding some logic add it properly. 
instead of sending `tooltipMessage` into AddAccount component, send whole `device` and do the if (device.connected) condition and Transaltion delaration inside `<AddAccount>`
