### PR TITLE
fix(suite): csv import

### LINKED ISSUE #11908: Fiat rates are not calculated properly on CSV import
1. Launch Suite 24.3.4
2. Connect your trezor
3. Set Application currency to USD 
4. Go to BTC account 
5. Open send dialog
6. Hit Import addresses form CSV
7. Import CSV file with different currencies 
8. Observe that the re-calculation to btc is correct on strings that contain same currency as the application default (in this case USD), and is not correct on any different currencies (for example CZK)

image

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Fixed fiat rates in CSV imports (and also fiat calculation on currency change).

## Related Issue

Resolve #11908

## Screenshots:
Screenshot 2024-04-24 at 7 21 41 PM

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 1]
```diff
@@ -32,6 +27,29 @@ export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRa
...
+                }),
+            );
+
+            if (updateFiatRatesResult.meta.requestStatus === 'fulfilled') {
+                const rate = updateFiatRatesResult.payload as fiatRatesResult;
+
+                currentRates.push({ currency, rate: rate.rate });
+            }
+        }
+
```
Comment (AdamSchinzel) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts:75]: Not ideal approach but accessing it with selector seems to not be possible since it doesn't update itself (state is updated but value from selector not)

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx [hunk 2]
```diff
@@ -74,7 +74,7 @@ export const Fiat = ({ output, outputId, labelHoverRight, labelRight }: FiatProp
 
     const currencyValue = watch(currencyInputName);
 
-    const recalculateFiat = (rate: number) => {
+    const recalculateFiat = (rate?: number) => {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx:77]: change name of param so that it is not used as `rate.rate` 😀

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx [hunk 3]
```diff
@@ -204,9 +204,9 @@ export const Fiat = ({ output, outputId, labelHoverRight, labelRight }: FiatProp
                 );
 
                 if (updateFiatRatesResult.meta.requestStatus === 'fulfilled') {
-                    const rate = updateFiatRatesResult.payload as number;
+                    const rate = updateFiatRatesResult.payload as fiatRatesResult;
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]: change name of variable so that it is not used as `rate.rate` or do `const { rate } = updateF...`

File: suite-common/wallet-types/src/fiatRates.ts [hunk 4]
```diff
@@ -40,4 +40,9 @@ export type Rate = {
     ticker: TickerId;
 };
 
+export type fiatRatesResult = {
+    rate: number | undefined;
```
Comment (tomasklim) [inline suite-common/wallet-types/src/fiatRates.ts]: rate?: number

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx (hunk 2 above)
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]: I would leave `rate: number` 

and just make check before this method is called (it is called just on 1 place)

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 5]
```diff
@@ -32,6 +27,29 @@ export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRa
...
+                    localCurrency: currency as FiatCurrencyCode,
+                    rateType: 'current',
+                    fetchAttemptTimestamp: Date.now() as Timestamp,
+                }),
+            );
+
+            if (updateFiatRatesResult.meta.requestStatus === 'fulfilled') {
+                const rate = updateFiatRatesResult.payload as fiatRatesResult;
+
+                currentRates.push({ currency, rate: rate.rate });
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]: no `rate.rate`

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts:52]: Why it is not updated?

Comment (tomasklim) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts:75]: Can you just fetch what is not yet available in the store?

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 6]
```diff
@@ -60,38 +80,28 @@ export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRa
...
+                        );
+                        const fiatValueBigNumber = formattedAmount.multipliedBy(rate);
+
+                        output.fiat = fiatValueBigNumber.toFixed(2) || '';
                     }
-                } else if (
-                    Object.keys(fiatCurrencies).find(c => c === currency) &&
-                    fiatRate?.rate
-                ) {
+                } else if (Object.keys(fiatCurrencies).find(c => c === currency) && rate) {
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]:
```suggestion
                } else if (Object.keys(fiatCurrencies).find(currency => currency === itemCurrency) && rate) {
```
or `outputCurrency`

you have to rename `currency` at the top

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 7]
```diff
@@ -60,38 +80,28 @@ export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRa
...
-                    const cryptoValue = fromFiatCurrency(
-                        output.fiat,
-                        currency,
-                        fiatRate,
-                        network.decimals,
-                        false,
-                    );
+                    const formattedLocalAmount = output.fiat.replace(',', '.');
+                    const amount = new BigNumber(formattedLocalAmount).div(rate);
+                    const amountStr = amount.toFixed(network.decimals);
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]:
```suggestion
                    const amount = new BigNumber(formattedLocalAmount).div(rate).toFixed(network.decimals);
```
or better naming for both

**Comment by tomasklim** [comment]
@MiroslavProchazka @AdamSchinzel Could you provide CSV to test this?

**Review by tomasklim — CHANGES_REQUESTED** [review]
When importing BTC, fiat is incorrect
`bc1qawvkrlq73sv4a56uatfvewvq7nxlw4dgt8835p,0.01337,BTC`
Screenshot 2024-04-25 at 16 48 58

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts:52]: Sure, will reuse `selectShouldUpdateFiatRate` in `updateFiatRatesThunk`

**Comment by AdamSchinzel** [comment]
> When importing BTC, fiat is incorrect `bc1qawvkrlq73sv4a56uatfvewvq7nxlw4dgt8835p,0.01337,BTC` Screenshot 2024-04-25 at 16 48 58

Fixed thanks for reporting

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts:75]: a1718ae7de5e8b020f8b1c9b763eee8039cc6bd1

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx (hunk 3 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]: a1718ae7de5e8b020f8b1c9b763eee8039cc6bd1

File: suite-common/wallet-types/src/fiatRates.ts (hunk 4 above)
Comment (AdamSchinzel) [reply suite-common/wallet-types/src/fiatRates.ts]: a1718ae7de5e8b020f8b1c9b763eee8039cc6bd1

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]: a1718ae7de5e8b020f8b1c9b763eee8039cc6bd1

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 5 above)
Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: a1718ae7de5e8b020f8b1c9b763eee8039cc6bd1

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 6 above)
Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: a1718ae7de5e8b020f8b1c9b763eee8039cc6bd1

File: packages/suite/src/hooks/wallet/useSendFormImport.ts (hunk 7 above)
Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useSendFormImport.ts]: a1718ae7de5e8b020f8b1c9b763eee8039cc6bd1

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 8]
```diff
@@ -4,26 +4,36 @@ import { importSendFormRequestThunk } from 'src/actions/wallet/send/sendFormThun
...
 // This hook should be used only as a sub-hook of `useSendForm`
-
-export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRate }: Props) => {
+export const useSendFormImport = ({
+    network,
+    tokens,
+    localCurrencyOption,
+    fiatRate,
+    currentRates,
+}: Props) => {
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]:
```suggestion
}: useSendFormImportProps) => {
```

File: packages/suite/src/hooks/wallet/useSendFormImport.ts [hunk 9]
```diff
@@ -32,6 +42,36 @@ export const useSendFormImport = ({ network, tokens, localCurrencyOption, fiatRa
...
+        const uniqueCurrencies = [...new Set(currencies)];
+
+        for (const currency of uniqueCurrencies) {
+            const fiatRateKey = getFiatRateKey(network.symbol, currency as FiatCurrencyCode);
+            const fiatRate = currentRates?.[fiatRateKey];
+
+            if (fiatRate) {
+                rates.push({ currency, rate: fiatRate?.rate });
+            } else {
+                const updateFiatRatesResult = await dispatch(
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendFormImport.ts]: I would put a comment here

**Review by tomasklim — APPROVED** [review]
LGTM
