### PR TITLE
fix: fetch fiat rates for custom token

### LINKED ISSUE #10771: Adding token does not trigger fiat rate fetch
**Describe the bug**
When I add ERC-20 token in ETH account, it does not trigger fiat rate fetch automatically. However, in max 1 minute it is fetched correctly if available

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: 2024.1.2

Screenshot 2024-01-24 at 9 59 40
After max 1 minute
Screenshot 2024-01-24 at 9 57 44

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Fixed an issue that when adding a token it didn't trigger fiat rates fetch right after this action.

Also did some copy changes, see attached screen

## Related Issue

Resolve #10771 

## Screenshots:

8D9AD254-92C2-48F2-BB84-F8B3EBDD4F66

### CODE REVIEW

File: packages/suite/src/actions/wallet/tokenActions.ts [hunk 1]
```diff
@@ -3,19 +3,36 @@ import { Account } from 'src/types/wallet';
...
+import { FiatCurrencyCode } from '@suite-common/suite-config';
 
-export const addToken = (account: Account, tokenInfo: TokenInfo[]) => (dispatch: Dispatch) => {
-    dispatch(
-        accountsActions.updateAccount({
-            ...account,
-            tokens: (account.tokens || []).concat(accountUtils.enhanceTokens(tokenInfo)),
-        }),
-    );
+export const addToken =
```
Comment (tomasklim) [inline packages/suite/src/actions/wallet/tokenActions.ts:10]: By updating account, new token definition should be fetched.
I am thinking if is is necessary to add `isCustomToken` attribute here. (if yes, I would use something like `forceFetchToken`)

I know that the token definition will not be ready in the time when `updateFiatRatesThunk` is called. 
However, we should maybe somehow guarantee that fiat rates for tokens are not called earlier than token definitions are fetched.
3rd bullet https://github.com/trezor/trezor-suite/pull/11120
What do you think?

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -5437,11 +5437,16 @@ export default defineMessages({
     },
     TR_ADD_TOKEN_TITLE: {
         id: 'TR_ADD_TOKEN_TITLE',
-        defaultMessage: 'Add ERC20 token',
+        defaultMessage: 'Add token',
+    },
+    TR_ADD_TOKEN_DESCRIPTION: {
+        id: 'TR_ADD_TOKEN_TITLE',
+        defaultMessage:
+            "Enter a contract address of a token you wish to add to your wallet. This is typically a 42-character alphanumeric string starting with '0x'.",
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts:5445]: Please find out if we can enable it also for Solana and Cardano

File: packages/suite/src/actions/wallet/tokenActions.ts (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/actions/wallet/tokenActions.ts:10]: Was not trying it before you PR was merged, already rebased on develop so will try again

File: packages/suite/src/support/messages.ts (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/support/messages.ts:5445]: Unfortunately we can't just enable it for Solana and Cardano now since it's not working out of the box. Created an issue for it https://github.com/trezor/trezor-suite/issues/11141

File: packages/suite/src/actions/wallet/tokenActions.ts (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/actions/wallet/tokenActions.ts:10]: It really needs to be there if we don't want to do the 3rd bullet that you mentioned. Imho other than for this use case it will be always fetched before so let's not care about it to much.

But better naming is good point, changed it to what you are suggesting - d022ac2aca7704564e38be1cbfd53247d587bff8

**Comment by AdamSchinzel** [comment]
Updated translation strings for  `TR_ADD_TOKEN_TITLE` and `TR_ADD_TOKEN_LABEL` for official languages plus czech in Crowdin

**Review by tomasklim — CHANGES_REQUESTED** [review]
CI is failing `[ { value: 'TR_ADD_TOKEN_TITLE', occurrences: 2 } ]`

**Review by tomasklim — APPROVED** [review]
