### PR TITLE
fix(suite): Abort button fix

### LINKED ISSUE #10518: Review: Trezor Modal abort button is not well aligned
Screenshot 2024-01-05 at 12 34 09

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve #10518

## Screenshots:

Before:
image

After:
image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/AbortButton.tsx [hunk 1]
```diff
@@ -25,19 +26,19 @@ const expandedStyle = css`
 const AbortContainer = styled.div`
     position: relative;
     height: 32px;
-    border-radius: 20px;
-    background: ${({ theme }) => theme.STROKE_GREY};
-    color: ${({ theme }) => theme.TYPE_LIGHT_GREY};
+    border-radius: ${borders.radii.lg};
+    background: ${({ theme }) => theme.backgroundTertiaryDefaultOnElevation0};
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/AbortButton.tsx]: Modal background is considered like `elevation: 0`, right @dahaca?

Comment (dahaca) [reply packages/suite/src/components/suite/modals/AbortButton.tsx]: Modal is on top of the app, so it's 1 :)

**Review by dahaca — APPROVED** [review]
