### PR TITLE
fix(onboarding): huge icon when backup fails

### LINKED ISSUE #3910: Huge icon during onboarding
**Describe the bug**
Huge icons are back and it appeared in newly designed onboarding.
I tested new onboarding multiple times but saw it for first time /at least in recent time/
I was able to replica it and record it. See video link.

**Steps to reproduce:**
1. Start suite that includes new onboarding
2. Disconnect device during seed backup
3. Reconnect it and observe

**Info:**
 - Suite version: desktop 21.7.0 (6796f451738b4cd59ecd9efb3257743bbe8398a1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.4.0 regular

**Screenshots:**

**https://youtu.be/cKRmzC0GJM0**

obrazek

### PR DESCRIPTION
**Pull request by tomasklim**
closes #3910

Screenshot 2021-06-22 at 8 52 35

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/Backup/index.tsx [hunk 1]
```diff
@@ -139,7 +139,7 @@ const BackupStep = () => {
                         </OnboardingButtonCta>
                     }
                 >
-                    <OptionsWrapper>
+                    <OptionsWrapper fullWidth={false}>
```
Comment (matejkriz) [inline packages/suite/src/views/onboarding/steps/Backup/index.tsx:142]: replacing `flex: 1` with `margin:auto` on StyledImage would do the same thing, but probably it doesn't matter (I just always trying to avoid those configuration props as fullWidth, but here it's already defined...)

**Review by matejkriz — APPROVED** [review]
