### PR TITLE
fix(mobile): fix account detail crash

### LINKED ISSUE #7086: App quits when clicking on certain asset or transaction
Sometimes the app crashed when clicking on asset or transaction. 

Examples:
LTC (I will provide XPUB separately via slack)
Video:
https://user-images.githubusercontent.com/84183817/205053807-6f8021d7-de9b-464e-9de3-a60a824293bf.mov

BTC Testnet (XPUB in slack)
Video: 
https://user-images.githubusercontent.com/84183817/205054265-7a7209c4-5955-42d7-aa7e-8e6d4f0968ae.mov

ETH Test Goerli (XPUB in Slack)
Video:
https://user-images.githubusercontent.com/84183817/205054690-9d6036bb-b335-4532-8fad-facca696cc9e.MP4

### PR DESCRIPTION
**Pull request by Nodonisko**
should fix #7086

### CODE REVIEW

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 1]
```diff
@@ -55,9 +55,9 @@ export const parseDateKey = (key: string) => {
 export const groupTransactionsByDate = (transactions: WalletAccountTransaction[]) =>
     // Note: We should use ts-belt for sorting this array but currently, there can be undefined inside
     // Built-in sort doesn't include undefined elements but ts-belt does so there will be some refactoring involved.
-    // Spread ([...arr]) is not used, because it maintains undefined in the array while .slice() removes them so it's needed to do it like this for sorting.
-    transactions
-        .slice()
+    [...transactions]
```
Comment (juriczech) [inline suite-common/wallet-utils/src/transactionUtils.ts:58]: I think this is how it was done previously and doing spread introduced a bug in desktop

**Review by juriczech — APPROVED** [review]
