### PR TITLE
fix: review modal for erc20 tokens

### LINKED ISSUE #3337: Send - Erc20 send dialogue looks like Eth transaction
**Describe the bug**
Please see screenshot, sending of ERC20 token is identified as ETH transaction

**Steps to reproduce:**
1. generate ERC20 transaction
2. check 'Send' modal description

**Info:**
 - Suite version: desktop 21.2.1 (c2448b3a66c2850c2a99acc8574edadf5771d565)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.1 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular

**Expected result:**
ERC20 token is identified as ERC20 transaction

**Actual result:**
ERC20 token is identified as ETH transaction

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by tomexx**
- show custom token symbol when available
- handle send amount of custom tokens correctly

fixes #3337

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx [hunk 1]
```diff
@@ -168,7 +168,12 @@ const Summary = ({
     const theme = useTheme();
     const { symbol } = account;
 
-    const amount = new BigNumber(tx.totalSpent).minus(tx.fee).toString();
+    let amount;
+    if (tx.token) {
```
Comment (tomexx) [inline packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx:171]: not sure if I can leave it like this, but the point is erc20 tokens have `totalSpent` without fees, but I'll gladly do a better fix if you point me to the right direction. Thx

**Review by slowbackspace — APPROVED** [review]

File: packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx (hunk 1 above)
Comment (slowbackspace) [reply packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx:171]: lgtm, but maybe @szymonlesisz will have some idea

**Comment by tsusanka** [comment]
@szymonlesisz please have a look at this "post-mortem" on Monday, I am merging now because we want to pass it to QA as soon as possible.
