### PR TITLE
Fix/23928 asset picker to field

### LINKED ISSUE #23928: TO picker in trading form - ui bugs
UI bugs found in `TO` asset picker ([url](https://dev.suite.sldev.cz/suite-web/feat/22838-swap-to-asset-picker/web)).

<details>
<summary> 1. Top 5 assets should user their ticker, not the ticker of the network </summary>

Image

### Figma

Image

</details>

<details>
<summary> 2. Network filter should be aligned more to right and the number of all networks in the bracket is unnecessary</summary>

Image

### Figma

Image

</details>

<details>
<summary> 3. Top 5 assets should have a strong border around them </summary>

Image

### Figma

Image

</details>

4. The whole modal should be narrower (currently 600px, Figma has 480px)

5. If `Your assets` section isn't present, because user does not have any funds, hide `All assets` headline

<details>
<summary> 6. Improve instructions on empty search results page </summary>

Image

### Figma

Image

</details>

<details>
<summary> 7. Make network popover slightly wider, so all network names fit on one line </summary>

We didn't have c-chain there when i was designing this.

Image

</details>

<details>
<summary> 8. Add `...` for too long token names and add the full name to tooltip </summary>

Image

</details>

### LINKED ISSUE #24196: Cannot Filter To-Network When Swapping From Native Network Coin
**Describe the bug**
When attempting to swap coins in the "to" form, filtering by a particular network (such as Solana, Ethereum, Optimism, etc.) is not possible if the selected "from" coin is the native coin of the same network. For example, when swapping from SOL on the Solana network, Solana does not appear as a filter option in the "to" network dropdown. This behavior is also observed with other networks like ETH (Ethereum), OP (Optimism), etc.

**Info:**
 - Suite version: web 26.1.0 (b9e7b558322fea83dd97a27bc07aae5bf80fb5ff)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2880x1800
 - Device: Trezor T3B1 2.10.0 universal (revision 25b05677cad6b1c3e17dc32576be8c14a064ad17)
 - Transport: WebUsbTransport
 
**How to reproduce**
1. Go to the Swap form in Trezor Suite (desktop/web).
2. Select a native coin for a supported network in the "from" field (e.g., SOL for Solana, ETH for Ethereum).
3. Attempt to filter the available networks in the "to" dropdown to the same network as the selected native coin (e.g., Solana, Ethereum, Optimism).
4. Notice that the network cannot be selected or filtered. 

**Expected behavior**
You should be able to filter and select the same network in the "to" dropdown, even when the "from" coin is the native of that network.

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

* fix: exclude tokens match in search in asset picker of To field
     Before:
     Snímek obrazovky 2026-01-08 v 9 21 00
     After:
    Snímek obrazovky 2026-01-08 v 9 23 28
* fix: select correctly networks options for To field asset picker in trading ([context](https://satoshilabs.slack.com/archives/C08PA8C0370/p1767784825284049))
* refactor: update all networks translation (Crowdin has been updated ✔️ )
      Snímek obrazovky 2026-01-08 v 9 29 27
* refactor: remove unused `NetworkTabs` component and related translation

## Related Issue

Resolve #23928
Resolve #24196

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/23928-asset-picker-to-field&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/23928-asset-picker-to-field&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/23928-asset-picker-to-field&lookback=7)

### CODE REVIEW

**Comment by jvaclavik** [comment]
isn't this bug? 
image

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/hooks/useBuildTradingAssetOptions.ts [hunk 1]
```diff
@@ -88,6 +88,22 @@ function createTopFiveAssets(disabledCryptoIds: Set<CryptoId> = new Set()) {
...
 }
 
+type GetOrderNetworksProps = {
+    topFiveAssets: TradingAssetOption[];
+    assets: TradingAssetOption[];
+    accountsWithTokens: AggregatedAccountWithTokens[];
+};
+
+function getOrderNetworks({ topFiveAssets, assets, accountsWithTokens }: GetOrderNetworksProps) {
+    const networks: Set<NetworkSymbol> = new Set();
```
Comment (seibei-iguchi) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/hooks/useBuildTradingAssetOptions.ts:98]: What about
```
const networks = new Set([
        ...topFiveAssets.map(asset => asset.networkSymbol),
        ...assets.map(asset => asset.networkSymbol),
        ...accountsWithTokens.map(item => item.account.symbol),
    ]);
```

**Review by seibei-iguchi — APPROVED** [review]

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/hooks/useBuildTradingAssetOptions.ts (hunk 1 above)
Comment (seibei-iguchi) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/hooks/useBuildTradingAssetOptions.ts:98]: Or even more declarative:)
```
const networks = new Set(
        [topFiveAssets, assets, accountsWithTokens].flat().map(item =>
            'networkSymbol' in item ? item.networkSymbol : item.account.symbol,
        ),
    );
```

**Review by izmy — APPROVED** [review]

**Comment by cermakjiri** [comment]
> isn't this bug? image

I've updated it in Crowdin and in the `messages.ts` but I didn't change `en.json` and other lang specific json files. So it appears to be broken but will be fixed after doing Crowdin sync.

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/AssetPickerModal.tsx [hunk 2]
```diff
@@ -34,10 +36,13 @@ export const AssetPickerModal = memo(function AssetPickerModalInner({
     onAssetSelect,
     dataTestId,
 }: AssetPickerModalProps) {
-    const { networks } = useAssetsContext();
-
     const { search, throttledSearch, setSearch } = useSearchFilter();
-    const [networkFilter, setNetworkFilter] = useState<NetworkSymbol | undefined>(undefined);
+    const [networkSymbol, setNetworkSymbol] = useState<NetworkSymbol | undefined>(undefined);
+
+    const { listItems, networks } = useBuildTradingAssetOptions({
```
Comment (BrantalikP) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/AssetPickerModal.tsx:42]: We might want to trim the searched value. For example, if you insert “usdc ”, the USDC result disappears. WDYT?

Screenshot 2026-01-08 at 10 16 28

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/AssetPickerModal.tsx:42]: I guess trimming it on blur event should be harmless

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/AssetPickerModal.tsx:42]: ✔️

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/hooks/useBuildTradingAssetOptions.ts (hunk 1 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/hooks/useBuildTradingAssetOptions.ts:98]: Thanks for feedback and you're right it's possible to express it differently. However, it seems it's quite the same to me (I know your's written in more functional way). And the 2nd seems harder to read at first glance IMO. 😀

Comment (seibei-iguchi) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputBuyAsset/AssetPickerModal/hooks/useBuildTradingAssetOptions.ts:98]: If it works, fine with me, it's just that forEach is always like a red flag for me and I have the urgent need to replace it:) The second one is a bit convoluted, you're right. But the first one saves one line!:D
