### PR TITLE
fix(suite): handle missing account when trying to add more

### LINKED ISSUE #6424: Cannot add Regtest account when not connected to the network
**Describe the bug**
The app breaks when attempting to add an account while not connected to the network.

**How to reproduce**
1. Enable Regtest in Settings without connecting to a network.
2. Try to add a Regtest account.

**Expected behavior**
The solution before #6276 was merged was to stop the _Add account_ button in the modal from rendering. Disabling the button and adding a tooltip would be nice.

**Screenshots**
chrome-capture-2022-8-29

### PR DESCRIPTION
**Pull request by matejkriz**
- Also disable button and provide tooltip if there are no empty accounts.

## Description
Here I moved `verifyAvailability` check before `emptyAccounts.length === 0` condition:
https://github.com/trezor/trezor-suite/pull/6276/commits/81f46e522f8fe7185bb43ff815d6a37bf4a40efa#diff-d38593712315afa9d7a2059044445bc79cf206d97b71ad5bf5d70c17e7e948efL83
and it caused this error.

Now I moved the check directly in `verifyAvailability` so we show error message in tooltip on disabled button instead of not rendering the button at all.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/6424

## Screenshots (if appropriate):
image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx [hunk 1]
```diff
@@ -13,6 +13,13 @@ const verifyAvailability = ({
     emptyAccounts: Account[];
     account: Account;
 }) => {
+    if (!account) {
```
Comment (Nodonisko) [inline packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx:16]: This is bad you cannot conditionally use hooks (useCallback) here. Please move ifs after that.

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx (hunk 1 above)
Comment (matejkriz) [reply packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx:16]: here is no conditionally used hook, or I (and eslint) can't see it. This is separate `verifyAvailability` function, not render fuction of `AddDefaultAccountButton`...

Comment (Nodonisko) [reply packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx:16]: I see, it looked like that because of github diff... sorry for bothering

**Review by Nodonisko — APPROVED** [review]
