### PR TITLE
Disable label edit on desktop if Suite Sync is on but missing keys and Trezor disconnected

### LINKED ISSUE #26651: Edit label is available on desktop but not working if keys are missing and device is not connected
**Describe the bug**

If Suite Sync is turned on with trezor disconnected, user can edit labels but it's not working (keys are missing)

**Info:**

- Platform: desktop/web
- Browser: all
- Suite Version: 26.4.1 (release candidate and develop)
- Firmware Version: latest
- OS: doesn't matter

**Steps to reproduce**

1. fresh Suite
1. connect onboarded trezor, wait for discovery
1. do not edit any label, Suite Sync is disabled
1. disconnect trezor
1. turn on Suite Sync

Suite Sync is visually ON in the Settings. User can see "Connect your Trezor and Allow Suite Sync to view and edit your labels, wallet names, and account names" banner, but user also see the option to edit labels (but it is not working, labels can't be saved).

**Expected behavior**
Suite Sync is visually ON in the Settings. User can see "Connect your Trezor and Allow Suite Sync to view and edit your labels, wallet names, and account names" banner. User should NOT see any Edit label buttons until he connect the Trezor and allow Suite **Sync.**

**Screenshots**

**Additional context**
https://satoshilabs.slack.com/archives/C07D260JB4H/p1776093834668379

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

- We would like to make Edit label visible always and guide user to connect the Trezor if click on it to unify that with mobile flow, but as a followup. Handling device authorization during device action is not trivial. So this is most probably only temporary solution until we unify it with the mobile flow.

- There is one more fix in this PR as second commit: Do not initiate Suite Sync if Trezor is not connected. Originally we try to initialize Suite Sync even with Trezor disconnected, and it leads to DeviceError. On mobile that error is simply [ignored (not showned to user) ](https://github.com/trezor/trezor-suite/blob/2e6b8257a1ab95a9023623a63595d560e92b4584/suite-native/labeling/src/hooks/useSuiteSyncLabelErrorHandler.ts#L34). But it will not be possible to successfully initialize Suite Sync without Trezor connected. We will delete the keys on turning Suite Sync off, see https://github.com/trezor/trezor-suite/issues/26466

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/26651

## 🔍 Currents Test Results

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/suite-sync-disconnected-trezor-without-keys&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/suite-sync-disconnected-trezor-without-keys&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 13 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-14T07:28:33.193Z • 13 test(s) total_

### CODE REVIEW

**Review by juriczech — APPROVED** [review]
LGTM

**Review by peter-sanderson — APPROVED** [review]

File: suite-common/suite-sync/src/createTurnOnSuiteSync.ts [hunk 1]
```diff
@@ -7,17 +7,22 @@ import {
...
-} & EnsureWalletSuiteSyncOnDep;
+} & EnsureWalletSuiteSyncOnDep &
+    GetDeviceForStaticSessionIdDep;
 
 export const createTurnOnSuiteSync =
     (deps: CreateTurnOnSuiteSyncDeps): TurnOnSuiteSync =>
     async ({ deviceStaticSessionId }) => {
         const isSuiteSyncEnabled = deps.getIsSuiteSyncEnabled();
+        const isDeviceConnected = deviceStaticSessionId
+            ? deps.getDeviceForStaticSessionId(deviceStaticSessionId)?.connected === true
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/createTurnOnSuiteSync.ts:24]: nit: `deps.getIsDeviceConnected(...)`

Comment (matejkriz) [reply suite-common/suite-sync/src/createTurnOnSuiteSync.ts:24]: Discussed and I'll not do it now.
