### PR TITLE
Solana tx timer

### LINKED ISSUE #10906: Solana sign tx modal improvements
**Describe the bug**

On Solana, when signing tx, blockhash has to be provided. This blockhash is valid only 150 blocks which is ~60 seconds.

[Design](https://www.figma.com/design/nLpKN2kFcbjZFvyqZ51zgL/Confirm-on-device?node-id=4325-13073&t=xk8BQKxfACUtCQUy-1)

**Expected behavior**
Allow me to send tx, if it fails because of blockhash, I get `retry` button and I can see approximate time I have to confirm the transaction. I want to have there also `retry` button during the signing process in case I know I am slow.

```[tasklist]
### Tasks
- [ ] When opening sign tx modal, fetch new blockhash
- [ ] Introduce timer
- [ ] Introduce retry button which should fetch new blockhash, cancel current device flow and start again
- [ ] Decode/rewrite Solana tx fail notification
- [ ] Introduce retry button if it fails only because of time! not because of something else
- [ ] Update error messages to some human readable text (not "Solana 32000 error")
```

**Screenshots**
In case it takes me too long to confirm transaction on device and I hit `Send`
Image

I get into this state with loading. In case I was fast enough and tx is confirmed. Modal is closed and tx is confirmed. Otherwise,...
Image

I get this error
#15434 
Image

### LINKED ISSUE #15434: Solana Transaction signing error: TransactionExpiredBlockheightExceededError
**Describe the bug**
When sending a solana token I frequently get this error: Transaction signing error: TransactionExpiredBlockheightExceededError
I read somewhere that this can be related to not sending fast enough. However I doing the transaction as fast as possible

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app
-   OS: name, windows
-   Firmware Version: 24.10.1

### PR DESCRIPTION
**Pull request by izmy**
## Description

A countdown timer has been added to show the remaining time for transaction confirmation. If the blockhash expires, a retry button will be displayed.

- enabled only for:
	- send
	- stake/unstake/claim
- trading is not available
- the timer is set to 45 seconds
- knowns issues: remembered wallet -> passphrase input takes time

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10906
Resolve [#15434](https://github.com/trezor/trezor-suite/issues/15434)

## Screenshots:
Screenshot 2025-02-24 at 19 15 54
Screenshot 2025-02-24 at 19 14 37
Screenshot 2025-02-24 at 19 16 51

### CODE REVIEW

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -9180,6 +9180,28 @@ export default defineMessages({
...
         defaultMessage: 'Confirmation of transaction may take up to <nowrap>1 minute</nowrap>',
     },
+    TR_SOLANA_TX_SEND_FAILED_TITLE: {
+        id: 'TR_SOLANA_TX_SEND_FAILED_TITLE',
+        defaultMessage: 'Send transaction failed',
+    },
+    TR_SOLANA_TX_SEND_FAILED_DESCRIPTION: {
+        id: 'TR_SOLANA_TX_SEND_FAILED_DESCRIPTION',
+        defaultMessage:
+            'The time to sign a Solana transaction is limited. It could no longer be submitted because it timed out and is no longer valid.',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]:
```suggestion
            'The time to sign a {networkName} transaction is limited. It could no longer be submitted because it timed out and is no longer valid.',
```

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -9180,6 +9180,28 @@ export default defineMessages({
...
+        defaultMessage: '{remainingTime} seconds left',
+    },
+    TR_SOLANA_TX_CONFIRMATION_TIMER_SHORT: {
+        id: 'TR_SOLANA_TX_CONFIRMATION_TIMER_SHORT',
+        defaultMessage: '<strong>{remainingTime}s</strong> left to confirm',
+    },
+    TR_SOLANA_TX_CONFIRMATION_TIMER_DESCRIPTION: {
+        id: 'TR_SOLANA_TX_CONFIRMATION_TIMER_DESCRIPTION',
+        defaultMessage:
+            'Due to Solana constraints, you have ~1 minute to check everything before your transaction times out.',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]:
```suggestion
            'Due to Solana constraints, you have ~1 minute to check everything before your transaction times out.',
```

@vytick let's do it 45 seconds? There needs to be buffer for fetching hash, broadcast and confirmation

Comment (tomasklim) [reply packages/suite/src/support/messages.ts]: or let's do 1 minute and speed up timer to 1 second === 0.75 second? 😀

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/ExpiredBlockhash.tsx [hunk 3]
```diff
@@ -0,0 +1,25 @@
+import { Box, Card, Column, IconCircle, Text } from '@trezor/components';
+import { spacings } from '@trezor/theme';
+import { HELP_CENTER_SOL_SEND } from '@trezor/urls';
+
+import { Translation } from '../../../../Translation';
+import { TrezorLink } from '../../../../TrezorLink';
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/ExpiredBlockhash.tsx]:
```suggestion
import { Translation } from 'src/components/suite/Translation';
...
```

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 4]
```diff
@@ -70,6 +76,9 @@ export const TransactionReviewModalContent = ({
     const [isSending, setIsSending] = useState(false);
     const [areDetailsVisible, setAreDetailsVisible] = useState(false);
 
+    const timer = useTimer();
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: Invity had a problem with slow time 
Please check that your 1 minute is real 1 minute.

https://github.com/trezor/trezor-suite/commit/c9e9759e2e6285c103717796c32cd910b838716c

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 5]
```diff
@@ -33,10 +35,14 @@ import { getTransactionReviewModalActionText } from 'src/utils/suite/transaction
 
 import { TransactionReviewDetails } from './TransactionReviewDetails';
 import { TransactionReviewOutputList } from './TransactionReviewOutputList/TransactionReviewOutputList';
+import { TransactionReviewOutputTimer } from './TransactionReviewOutputList/TransactionReviewOutputTimer';
 import { TransactionReviewSummary } from './TransactionReviewSummary';
 import { ConfirmActionModal } from '../DeviceContextModal/ConfirmActionModal';
+import { ExpiredBlockhash } from '../UserContextModal/TxDetailModal/ExpiredBlockhash';
 import { ReplaceByFeeFailedOriginalTxConfirmed } from '../UserContextModal/TxDetailModal/ReplaceByFeeFailedOriginalTxConfirmed';
 
+const SOLANA_TIMEOUT = 10;
```
Comment (martykan) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: This is for testing I assume?

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 4 above)
Comment (martykan) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: Also it seems the timer resets after confirming but before sending

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 5 above)
Comment (izmy) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: > This is for testing I assume?

yes

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 4 above)
Comment (izmy) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: yes, I found some problem with the timer in this place, so I plan to change it

File: packages/blockchain-link/src/workers/solana/index.ts [hunk 6]
```diff
@@ -197,9 +197,15 @@ const pushTransaction = async (request: Request<MessageTypes.PushTransaction>) =
             );
         }
         if (isSolanaError(error)) {
-            throw new Error(
-                `Solana error code: ${error.context.__code}. Please try again or contact support.`,
-            );
+            if (error.context.__code === -32002) {
```
Comment (martykan) [inline packages/blockchain-link/src/workers/solana/index.ts]: This situation is a bit more complicated, since there can be different causes behind the preflight error, eg. compute limit, not enough funds, instruction problems...

I think this would be the correct condition: 
```
isSolanaError(error,  SOLANA_ERROR__JSON_RPC__SERVER_ERROR_SEND_TRANSACTION_PREFLIGHT_FAILURE) &&
isSolanaError(error.cause, SOLANA_ERROR__TRANSACTION_ERROR__BLOCKHASH_NOT_FOUND)
```

File: packages/suite/src/support/messages.ts (hunk 2 above)
Comment (izmy) [reply packages/suite/src/support/messages.ts]: So? 😄

File: packages/suite/src/support/messages.ts (hunk 1 above)
Comment (izmy) [reply packages/suite/src/support/messages.ts]: done

File: packages/blockchain-link/src/workers/solana/index.ts (hunk 6 above)
Comment (izmy) [reply packages/blockchain-link/src/workers/solana/index.ts]: done

File: suite-common/wallet-core/src/send/sendFormReducer.ts [hunk 7]
```diff
@@ -33,13 +33,15 @@ export type SendState = {
     precomposedForm?: FormState; // Used to pass the form state to the review modal. Holds similar data as drafts, but drafts are not used in RBF form.
     signedTx?: BlockbookTransaction;
     serializedTx?: SerializedTx; // Hexadecimal representation of signed transaction (payload for TrezorConnect.pushTransaction).
+    timestamp?: number;
```
Comment (PeKne) [inline suite-common/wallet-core/src/send/sendFormReducer.ts]: please name it more specifically. It is not clear at all what time does this timestamp represent without digging deeper in context of other files. With this name it could be time of anything. Time of transaction composition, time of storing draft, time of signing.... etc.

Please clarify this by changing the name of this attribute.

**Review by PeKne — CHANGES_REQUESTED** [review]

**Review by PeKne — APPROVED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/StakeModal/StakeEthForm/ConfirmStakeEthModal.tsx [hunk 8]
```diff
@@ -80,19 +80,17 @@ export const ConfirmStakeEthModal = ({
                         }}
                     />
                 </Banner>
-                <Banner icon="hand">
+                <Banner
```
Comment (martykan) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/StakeModal/StakeEthForm/ConfirmStakeEthModal.tsx:83]: Not sure if this should be a part of this PR, at least a separate commit would definitely be better

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModal.tsx [hunk 9]
```diff
@@ -19,21 +29,48 @@ type TransactionReviewModalProps =
 export const TransactionReviewModal = ({ type, decision }: TransactionReviewModalProps) => {
     const send = useSelector(state => state.wallet.send);
     const stake = useSelector(selectStake);
+    const selectedAccount = useSelector(state => state.wallet.selectedAccount);
```
Comment (martykan) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModal.tsx:32]: Why not use `selectSelectedAccount` selector?

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 10]
```diff
@@ -51,25 +96,29 @@ const mapRbfTypeToReporting: Record<
...
+    timestamp = 0,
     decision,
     txInfoState,
+    tryAgainSignTx,
     cancelSignTx,
     isRbfConfirmedError,
 }: TransactionReviewModalContentProps) => {
     const dispatch = useDispatch();
     const account = useSelector(selectAccountIncludingChosenInTrading);
+    const accounts = useSelector(state => state.wallet.accounts);
```
Comment (martykan) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: `selectAccounts` selector?

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 11]
```diff
@@ -80,6 +129,30 @@ export const TransactionReviewModalContent = ({
     );
 
     const isTradingAction = !!precomposedForm?.isTrading;
+
+    const deadline = timestamp + SOLANA_TX_TIMEOUT_MS;
+
+    // check if transaction is still valid
+    useEffect(() => {
+        if (isTradingAction) {
```
Comment (martykan) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: Shouldn't this depend on showSolanaTimer? This would now run for all networks, unless I'm missing something?

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/StakeModal/StakeEthForm/ConfirmStakeEthModal.tsx (hunk 8 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/StakeModal/StakeEthForm/ConfirmStakeEthModal.tsx:83]: let's ignore it, i do not want to preparate it from jardas commit

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 12]
```diff
@@ -118,7 +199,7 @@ export const TransactionReviewModalContent = ({
               .find(type => type) || null;
 
     const onCancel = () => {
-        if (isRbfConfirmedError) {
+        if (isRbfConfirmedError || networkType === 'solana') {
```
Comment (martykan) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: Seems like it would be better to refer to `shouldCheckTxTimeValidity`

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 13]
```diff
@@ -33,10 +46,47 @@ import { getTransactionReviewModalActionText } from 'src/utils/suite/transaction
...
 import { TransactionReviewOutputList } from './TransactionReviewOutputList/TransactionReviewOutputList';
+import { TransactionReviewOutputTimer } from './TransactionReviewOutputList/TransactionReviewOutputTimer';
 import { TransactionReviewSummary } from './TransactionReviewSummary';
 import { ConfirmActionModal } from '../DeviceContextModal/ConfirmActionModal';
+import { ExpiredTxValidity } from '../UserContextModal/TxDetailModal/ExpiredTxValidity';
 import { ReplaceByFeeFailedOriginalTxConfirmed } from '../UserContextModal/TxDetailModal/ReplaceByFeeFailedOriginalTxConfirmed';
 
+const getTxValidityTimeoutInMs = (networkType?: NetworkType) => {
+    if (networkType === 'solana') {
+        return 40 * 1000; // 40 seconds
```
Comment (vytick) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: Please add the reason why 40s for the future

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 14]
```diff
@@ -79,7 +131,36 @@ export const TransactionReviewModalContent = ({
...
+    useEffect(() => {
+        if (!shouldCheckTxTimeValidity) {
+            return;
+        }
+
+        const now = Date.now();
+        const timeLeft = Math.max(deadline - now, 0);
+        let mounted = true;
+
+        console.log(timeLeft);
```
Comment (vytick) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: This probably should not be here?

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 15]
```diff
@@ -33,10 +46,47 @@ import { getTransactionReviewModalActionText } from 'src/utils/suite/transaction
...
+
+    const firstOutput = outputs[0];
+    const isInternalTransfer =
+        firstOutput?.type === 'address' &&
+        findAccountsByAddress(symbol, firstOutput.value, accounts).length > 0;
+
+    const isFirstStep = buttonRequestsCount <= 1;
+    const isStaking = stakeType && !serializedTx;
+
+    return isInternalTransfer || !isFirstStep || serializedTx || isStaking;
```
Comment (vytick) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx:88]: should this return true for any other symbol than sol and dsol?

Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx:88]: it will not, there is condition at the beginning of this fn

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 14 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: removed

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 12 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: changed

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 13 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: done

**Review by martykan — APPROVED** [review]
LGTM
