### PR TITLE
fix: handle estimated fee error

### LINKED ISSUE #3283: ETH: catch error from blockbook/geth in estimateFee
**Describe the bug**
handle and parse errors from `TrezorConnect.blockchainEstimateFee` in ethereum composeTransaction process.
Prevent from sending if invalid smart contract/ other error detected

Currently, a user can pay a fee even for an invalid transaction.

handle [errors](https://github.com/ethereum/go-ethereum/blob/c503f98f6d5e80e079c1d8a3601d188af2a899da/core/error.go) returned by `estimateFee` [method ](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts#L123)

### PR DESCRIPTION
**Pull request by enjojoy**
The error coming from geth and returned the value of the error with a notification. 

I have a couple of questions as I'm not sure what the expected outcome is, I'd be happy to discuss it and get some help. 

- Should I handle every incoming error differently and provide a differently interpreted message or returning the initial error value is sufficient? 
- I'm not sure how to test in this case, I couldn't seem to find any examples on how/where the function is used.

Closes #3283

### CODE REVIEW

File: packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts [hunk 1]
```diff
@@ -149,6 +149,13 @@ export const composeTransaction =
             }
         } else {
             // TODO: catch error from blockbook/geth (invalid contract, not enough balance...)
+            if (estimatedFee.payload.error) return;
+            dispatch(
+                notificationsActions.addToast({
+                    type: 'metadata-unexpected-error',
+                    error: estimatedFee.payload.error,
+                }),
+            );
```
Comment (mroz22) [inline packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts]: this does not add up. if you return when `estimatedFee.payload.error` is present, you can't disaptch it on line 156. or am I missing something?

**Comment by tomasklim** [comment]
related to https://github.com/trezor/trezor-suite/issues/3283

File: packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts [hunk 2]
```diff
@@ -149,6 +149,13 @@ export const composeTransaction =
             }
         } else {
             // TODO: catch error from blockbook/geth (invalid contract, not enough balance...)
```
Comment (AdamSchinzel) [inline packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts]: Please remove this comment

File: packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts [hunk 3]
```diff
@@ -149,6 +149,13 @@ export const composeTransaction =
...
+            if (estimatedFee.payload.error) return;
```
Comment (AdamSchinzel) [inline packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts]: This is as @mroz22 said not needed. If response was not successful then we always want to show this toast message.

File: packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts [hunk 4]
```diff
@@ -149,6 +149,13 @@ export const composeTransaction =
...
+            dispatch(
+                notificationsActions.addToast({
+                    type: 'metadata-unexpected-error',
```
Comment (AdamSchinzel) [inline packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts]: Please create a new type something like `estimated-fee-error` and provide a general message saying that it failed.

**Review by AdamSchinzel — CHANGES_REQUESTED** [review]
And also please rebase, there were bigger changes to this file.

**Comment by enjojoy** [comment]
> And also please rebase, there were bigger changes to this file.

I believe it's up to date with the develop branch, I tried to rebase it and got no conflicts whatsoever, could you please check?

File: packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts (hunk 1 above)
Comment (enjojoy) [reply packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts]: You're right, fixed this in the new commits

File: packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts (hunk 2 above)
Comment (enjojoy) [reply packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts]: done

**Comment by MiroslavProchazka** [comment]
> > And also please rebase, there were bigger changes to this file.
> 
> I believe it's up to date with the develop branch, I tried to rebase it and got no conflicts whatsoever, could you please check?

It seems that there are some conflicts in `packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts`

File: suite-common/toast-notifications/src/types.ts [hunk 5]
```diff
@@ -132,6 +132,10 @@ export type ToastPayload = (
           type: 'cardano-withdrawal-error';
           error: string;
       }
+    | {
+          type: 'estimated-fee-error';
```
Comment (AdamSchinzel) [inline suite-common/toast-notifications/src/types.ts]: No need for the whole object to be introduced as a new type. You can use the object starting on line 84 and just extend the type there.

Also I see this is the same case also for `cardano-delegate-error` and `cardano-withdrawal-error`. You can move them up together with your type and remove the objects

**Review by AdamSchinzel — CHANGES_REQUESTED** [review]
Just some nitpics

**Comment by AdamSchinzel** [comment]
Also please reword your commits so they are like fix(suite):..., feat(suite): ... etc.

**Review by AdamSchinzel — APPROVED** [review]
Nice good job!

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts [hunk 6]
```diff
@@ -151,7 +151,14 @@ export const composeEthereumSendFormTransactionThunk = createThunk(
...
 
-            // TODO: catch error from blockbook/geth (invalid contract, not enough balance...)
+            dispatch(
+                notificationsActions.addToast({
+                    type: 'estimated-fee-error',
+                    error: estimatedFee.payload.error,
+                }),
+            );
+
+            return;
```
Comment (AdamSchinzel) [inline suite-common/wallet-core/src/send/sendFormEthereumThunks.ts]: Hmm now I'm thinking about it (because of the failed tests) we should not put a return here. We need the function to continue. If it fails the only thing that will be different is that it will use the backup value and show toast message.

I would suggest one thing for the toast. Let's not even show the error. It can be just a copy with e. g. "Failed to estimate fee from the network. Using backup value.".

Please update it like this. When you will be in the `suite-common/toast-notifications/src/types.ts` you can also do the same type of refactoring for objects with just type property (put them together with your type).

**Review by AdamSchinzel — CHANGES_REQUESTED** [review]

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts (hunk 6 above)
Comment (tomasklim) [reply suite-common/wallet-core/src/send/sendFormEthereumThunks.ts]: Yes, the return should not be there. Fallback of gas limit is set on line 152.

Unit test is failing because of it

**Comment by tomasklim** [comment]
Screenshot 2024-05-10 at 21 45 17
Screenshot 2024-05-10 at 21 54 18

**Review by tomasklim — COMMENTED** [review]
@Hermez-cz User gets `Estimated fee error` + reason of error. However, we set gas limit for him to some big number hardcoded in codebase.

I think user can be quite confused that he got an error but he is still able to continue. I guess we should improve the message to inform that we also set some default for him.

**Review by AdamSchinzel — APPROVED** [review]
LGTM
