### PR TITLE
Account label clearence (suite sync)

### LINKED ISSUE #24615: Unsynced account label on mobile
This happens because account is accessed via `account.accountLabel`.

Related: https://github.com/trezor/trezor-suite/issues/24620

1. Go to account, label is applied:
Image

2. Go back to account list, label not applied:
Image

### LINKED ISSUE #24620: Deprecate accountLabel
- Mark `account.accountLabel` as deprecated.
- Replace all of its usages on desktop with account label from labelling (see `AccountLabel` component).
- On mobile, do not display it and do not allow editing it when Suite Sync is on.
- Inform other devs that it should not be used anymore.

It will be removed eventually.

### LINKED ISSUE #24754: Receive address screen shows old account label with enabled Suite Sync
If you change account label with Suite Sync OFF, Receive address screen still uses the old label with Suite Sync ON.

Image

**Info:**

- Mobile Suite Version: develop-26.1.2, commit 5059d79d716b64340b79b683dd39be1fd0db9812
- OS: Android 15

**How to reproduce**

1. With Suite Sync OFF - rename any account (ex. "Legacy label")
1. Suite Sync ON - rename the account again (ex. "Suite Sync label")
2. Go to the same account and click Receive
1. See that the "Legacy label" is still shown on the top

Might be related to https://github.com/trezor/trezor-suite/issues/24615 ?

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolve: https://github.com/trezor/trezor-suite/issues/24615
Resolve: https://github.com/trezor/trezor-suite/issues/24620
Resolve: https://github.com/trezor/trezor-suite/issues/24754

In this PR:

1. Deprecation with laud warnings for `account.accountLabel`
2. Remove as many usages of it as possible
3. Where too hard, TODO added and issue created for it
4. This fixes the issue that on BNB (and similar) the labels were not correctly shown
5. Introduced `AccountLabel` component for mobile to unify usage
6. Some small accidental code improvements

## Notes for QA
This touches a bit more places

- Desktop: Account display on Trading/Staking
- Bip329 export 
- Mobile: Account labels in all places

**:pray: I like to ask to especially check the labeling in Trading & Staking**

___

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=account-label&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=account-label&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=account-label&lookback=7)

### CODE REVIEW

File: suite-native/accounts/src/components/AccountSectionTitle.tsx [hunk 1]
```diff
@@ -36,7 +37,9 @@ export const AccountSectionTitle: React.FC<AccountSectionTitleProps> = ({
 
     return (
         <HStack alignItems="center" justifyContent="space-between" marginBottom="sp16">
-            <Text variant="highlight">{account.accountLabel}</Text>
```
Comment (peter-sanderson) [inline suite-native/accounts/src/components/AccountSectionTitle.tsx:39]: THIS was the root of all evil 👿

File: suite-native/labeling/src/components/AccountLabel.tsx [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+const normalizeProps = (props: AccountLabelPropsWithAccount): AccountLabelProps => 'account' in props
+        ? {
+              deviceStaticSessionId: props.account.deviceState,
+              networkSymbol: props.account.symbol,
+              accountDescriptor: props.account.descriptor,
+          }
+        : props;
+
+export const AccountLabel = (props: AccountLabelPropsWithAccount) => {
```
Comment (peter-sanderson) [inline suite-native/labeling/src/components/AccountLabel.tsx:27]: I am trying to prepare components to work with non-object props, so it does not need to be re-rendered. 

However, all places already have  `account` as object. So this end up as a future-proving effort. But I think we shall do it more, so I am leaving it,

File: suite-native/labeling/src/components/AddressLabelEditable.tsx [hunk 3]
```diff
@@ -27,19 +29,36 @@ export const AddressLabelEditable = ({
...
+
+        if (!result.success) {
+            const { type } = result.error;
+            switch (type) {
+                case 'SuiteSyncUnavailableOnDeviceError':
+                case 'SuiteSyncFirmwareUpgradeNeededDeviceErrorType':
+                case 'DeviceCancelled':
+                case 'DeviceError':
+                case 'SuiteSyncUpdateError':
+                    showToast({ variant: 'error', icon: 'warning', message: type });
```
Comment (peter-sanderson) [inline suite-native/labeling/src/components/AddressLabelEditable.tsx:55]: Not ideal, but currently, the error-handling was completely missing.

We shall add some ESLint to check for non-awaited promises and raise it as error

File: suite-native/trading-state/src/selectors/commonSelectors.ts [hunk 4]
```diff
@@ -295,6 +295,7 @@ export const selectAccountsWithTokensToSellSectionListByTradingType =
 
                     return {
                         key: `section_${account.key}`,
+                        // Todo: this is wrong, correct label is determined by `selectAccountLabel` selector
```
Comment (juriczech) [inline suite-native/trading-state/src/selectors/commonSelectors.ts:303]: Forgotten TODO. This is meant to be part of follow up, or in this PR?

File: suite-native/module-trading/src/components/general/ReceiveAccount/ReceiveAccountPicker.tsx [hunk 5]
```diff
@@ -111,14 +113,22 @@ export const ReceiveAccountPicker = ({
     const { translate } = useTranslate();
     const navigation = useNavigation<NavigationProps>();
 
+    const account = receiveAccount?.account;
+
+    const accountLabel =
+        useSelector((state: CombinedLabelingState) =>
+            account !== undefined
```
Comment (juriczech) [inline suite-native/module-trading/src/components/general/ReceiveAccount/ReceiveAccountPicker.tsx]: I think this should be part of the selector.

File: suite-native/module-accounts-management/src/components/AccountDetailScreenHeader.tsx [hunk 6]
```diff
@@ -25,28 +23,14 @@ type AccountDetailNavigationProps = StackToStackCompositeNavigationProps<
...
-    );
-};
+const AccountDetailScreenHeaderContent = ({ account }: AccountDetailScreenHeaderProps) => (
+    <HStack alignItems="center">
+        <CryptoIconWithNetwork symbol={account.symbol} size="small" />
+        <Text variant="highlight" adjustsFontSizeToFit numberOfLines={1}>
+            <AccountLabel account={account} />
+        </Text>
+    </HStack>
+);
```
Comment (juriczech) [inline suite-native/module-accounts-management/src/components/AccountDetailScreenHeader.tsx:33]: Noice! ❤️

File: suite-native/labeling/src/components/AddressLabelEditable.tsx (hunk 3 above)
Comment (juriczech) [reply suite-native/labeling/src/components/AddressLabelEditable.tsx:55]: I'm touching this in my branch, probably will look into this.

File: suite-common/test-utils/src/mocks.ts [hunk 7]
```diff
@@ -8,58 +8,114 @@ import {
...
     asDeviceUniquePath,
 } from '@trezor/connect';
 import { DeviceModelInternal } from '@trezor/device-utils';
 
-/**
- * Generate wallet account
- * @param {Partial<Account>} [account]
- * @returns {Features}
- */
-// @ts-expect-error - related to backendType and status
```
Comment (peter-sanderson) [inline suite-common/test-utils/src/mocks.ts]: Finally we can get rid of this! :point_up: :tada:

File: suite-native/trading-state/src/selectors/commonSelectors.ts (hunk 4 above)
Comment (peter-sanderson) [reply suite-native/trading-state/src/selectors/commonSelectors.ts:303]: There is follow  up issue for those

File: suite-native/module-trading/src/components/general/ReceiveAccount/ReceiveAccountPicker.tsx (hunk 5 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/general/ReceiveAccount/ReceiveAccountPicker.tsx]: this would be kinda complicated as `selectAccountLabel`

have 3 parameters all of which would need to be nullable => that would lead to very ugly if in it.

Is it worth it?

image

Comment (juriczech) [reply suite-native/module-trading/src/components/general/ReceiveAccount/ReceiveAccountPicker.tsx]: I believe it's the selectors job to retrieve the info for you based on the parameters provided. It might be useful elsewhere in the future. Feel free to ignore. It's just future proofing and not necessary, if you feel like it would be redundant and ugly.

**Review by matejkriz — APPROVED** [review]
It would be nicer to have it split into multiple PRs (at least 39e2fe9d943465784d9d98a951b38686172d3a50), but there's no point in redoing it now. 

Everything seems clear to me, and it works both on the desktop with legacy labeling and Suite Sync, as well as on mobile when switching between legacy account labeling and Suite Sync. 👏

File: suite-native/trading-fixtures/src/__fixtures__/account.ts [hunk 8]
```diff
@@ -1,8 +1,14 @@
-import { Account } from '@suite-common/wallet-types';
+import { Account, AccountKey } from '@suite-common/wallet-types';
 
-export const getBtcAccount = (key = 'btc-account-1', overrides: Partial<Account> = {}) =>
+/**
+ * @deprecated use `mockWalletAccount`, to keep AccountKey in sync with Descriptor, etc...
```
Comment (peter-sanderson) [inline suite-native/trading-fixtures/src/__fixtures__/account.ts:4]: @vytick @jbazant :pray: If you have some resources in your team, this mock is real pain.

I suggest to replace this with the mocks from `suite-native/trading-fixtures/src/__fixtures__/accounts.ts` (plural)

File: suite-native/module-trading/src/components/general/ReceiveAccount/__tests__/ReceiveAccountPicker.comp.test.tsx [hunk 9]
```diff
@@ -110,22 +128,10 @@ describe('ReceiveAccountPicker', () => {
             expect(getByTestId('TEST_ID/not-selected')).toHaveTextContent('Not selected');
         });
 
-        it('should render correctly with empty string as receiveAccount label', () => {
-            const { getByTestId } = renderReceiveAccountPicker({
-                receiveAccount: {
-                    account: { ...getBtcAccount(), accountLabel: '' },
```
Comment (peter-sanderson) [inline suite-native/module-trading/src/components/general/ReceiveAccount/__tests__/ReceiveAccountPicker.comp.test.tsx:116]: This test is no longer relevant, account is always taken by selector from the state.

File: suite-native/module-trading/src/components/general/ReceiveAccount/ReceiveAccountPicker.tsx [hunk 10]
```diff
@@ -111,14 +113,20 @@ export const ReceiveAccountPicker = ({
     const { translate } = useTranslate();
     const navigation = useNavigation<NavigationProps>();
 
+    const account = receiveAccount?.account;
+
+    const accountLabel = useSelector((state: CombinedLabelingState) => account !== undefined
+            ? (selectAccountLabel(state, account.deviceState, account.descriptor, account.symbol) ??
+                  '') // important to be `''` there is logic that relays on it
```
Comment (peter-sanderson) [inline suite-native/module-trading/src/components/general/ReceiveAccount/ReceiveAccountPicker.tsx]: There is a component that has weird logic based on the label value. That's weird I would expect to use `selectedAcountKey` to do the logic, not the stringy label that may not be very stable.

File: suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangeFromAccountTradePreviewCard.comp.test.tsx [hunk 11]
```diff
@@ -40,7 +40,8 @@ describe('ExchangeFromAccountTradePreviewCard', () => {
         expect(toJSON()).toBeNull();
     });
 
-    it('should render TradeSideCard otherwise', async () => {
+    // Todo: I was not able to fix it, probably the AccountKey inconsistency in `getBtcAccount`
+    it.skip('should render TradeSideCard otherwise', async () => {
```
Comment (peter-sanderson) [inline suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangeFromAccountTradePreviewCard.comp.test.tsx:44]: :pray: @jbazant if you know what to do here. I was not able to make it work.

File: suite-native/module-trading/src/components/buy/__tests__/BuyReceiveAccountPicker.comp.test.tsx [hunk 12]
```diff
@@ -87,7 +86,7 @@ describe('BuyReceiveAccountPicker', () => {
             }),
         });
 
-        expect(getByText(btcAccountName1)).toBeTruthy();
+        expect(getByText('Receive account')).toBeTruthy();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/buy/__tests__/BuyReceiveAccountPicker.comp.test.tsx]: **issue:** ‏This is IMO wrong. This test should test that account is displayed. With your changes, account name is not displayed at all.
Switching the expectations just hides the problem.

Probably just problem with the mock as it looks good in app.

Image

I suggest to revert this change, skip the test for now and create issue to fix it.

File: suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx [hunk 13]
```diff
@@ -21,8 +21,8 @@ describe('ExchangePreviewView', () => {
     it('should render all sections except alert', async () => {
         const { getByText } = await renderExchangePreviewView({});
 
-        expect(getByText('BTC Account #1')).toBeOnTheScreen();
-        expect(getByText('Ethereum #1')).toBeOnTheScreen();
+        expect(getByText('Bitcoin')).toBeOnTheScreen();
+        expect(getByText('Ethereum')).toBeOnTheScreen();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx]: **issue:** Same here. Revert, skip, resolve in separate issue.

File: suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx [hunk 14]
```diff
@@ -31,8 +31,8 @@ describe('ExchangePreviewView', () => {
             txnErrorString: 'txnErrorString',
         });
 
-        expect(getByText('BTC Account #1')).toBeOnTheScreen();
-        expect(getByText('Ethereum #1')).toBeOnTheScreen();
+        expect(getByText('Bitcoin')).toBeOnTheScreen();
+        expect(getByText('Ethereum')).toBeOnTheScreen();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx]: **issue:** Same here. Revert, skip, resolve in separate issue.

File: suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangeToAccountTradePreviewCard.comp.test.tsx [hunk 15]
```diff
@@ -44,7 +44,7 @@ describe('ExchangeToAccountTradePreviewCard', () => {
         });
 
         expect(getByText('Account')).toBeOnTheScreen();
-        expect(getByText('BTC Account #1')).toBeOnTheScreen();
+        expect(getByText('Bitcoin')).toBeOnTheScreen();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangeToAccountTradePreviewCard.comp.test.tsx]: **issue:** Same here. Revert, skip, resolve in separate issue.

File: suite-native/module-trading/src/components/exchange/receive/__tests__/ExchangeReceiveAccountPicker.comp.test.tsx [hunk 16]
```diff
@@ -87,7 +86,7 @@ describe('ExchangeReceiveAccountPicker', () => {
             }),
         });
 
-        expect(getByText(btcAccountName1)).toBeTruthy();
+        expect(getByText('1BTC')).toBeTruthy();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/exchange/receive/__tests__/ExchangeReceiveAccountPicker.comp.test.tsx]: **issue:** Same here. Revert, skip, resolve in separate issue.

File: suite-native/module-trading/src/components/general/ReceiveAccount/__tests__/ReceiveAccountPicker.comp.test.tsx [hunk 17]
```diff
@@ -88,16 +108,14 @@ describe('ReceiveAccountPicker', () => {
...
             receiveAccount: {
-                account: btcAccount,
-                address: btcAccount.addresses!.used[0],
+                account: btc1NormalAccount,
+                address: btc1NormalAccount.addresses!.used[0],
             },
         });
 
         expect(getByText('BTC Account #1')).toBeTruthy();
-        expect(getByText('1BTC')).toBeTruthy();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/general/ReceiveAccount/__tests__/ReceiveAccountPicker.comp.test.tsx:100]: **issue:** Same here. Revert, skip, resolve in separate issue. (just this one line, not the whole test)

File: suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx [hunk 18]
```diff
@@ -59,7 +59,7 @@ describe('TradeDetailTransactionInfo', () => {
 
         expect(getByText('$1,234.00')).toBeTruthy();
         expect(getByText('0.462586 ETH')).toBeTruthy();
-        expect(getByText('ETH Account #1')).toBeTruthy();
+        expect(getByText('Ethereum')).toBeTruthy();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx]: **issue:** Same here. Revert, skip, resolve in separate issue.

File: suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx [hunk 19]
```diff
@@ -74,7 +74,7 @@ describe('TradeDetailTransactionInfo', () => {
         expect(getByText('10.1232 JTO')).toBeTruthy();
         expect(getByText('0.462586 SOL')).toBeTruthy();
         // For exchange trades, both from and to accounts are displayed and they are the same account
-        expect(getAllByText('SOL Account #1')).toHaveLength(2);
+        expect(getAllByText('Solana')).toHaveLength(2);
```
Comment (jbazant) [inline suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx]: **issue:** Same here. Revert, skip, resolve in separate issue.

File: suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx [hunk 20]
```diff
@@ -114,7 +114,7 @@ describe('TradeDetailTransactionInfo', () => {
 
         expect(getByText('1.22 BTC')).toBeTruthy();
         expect(getByText('$100.00')).toBeTruthy();
-        expect(getByText('BTC Account #1')).toBeTruthy();
+        expect(getByText('Bitcoin')).toBeTruthy();
```
Comment (jbazant) [inline suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx]: **issue:** Same here. Revert, skip, resolve in separate issue.

**Review by jbazant — APPROVED** [review]
Changes in tests are not correct. I would suggest to skip them and mark them with `// TODO XXXX` where XXX is a number of corresponding ticket. I will try to fix them someday.

It seems that trading work appropriately in mobile app.

File: suite-native/module-trading/src/components/buy/__tests__/BuyReceiveAccountPicker.comp.test.tsx (hunk 12 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/buy/__tests__/BuyReceiveAccountPicker.comp.test.tsx]: done

File: suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx (hunk 13 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx]: done

File: suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx (hunk 14 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangePreviewView.comp.test.tsx]: done

File: suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangeToAccountTradePreviewCard.comp.test.tsx (hunk 15 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/exchange/ExchangePreview/__tests__/ExchangeToAccountTradePreviewCard.comp.test.tsx]: done

File: suite-native/module-trading/src/components/exchange/receive/__tests__/ExchangeReceiveAccountPicker.comp.test.tsx (hunk 16 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/exchange/receive/__tests__/ExchangeReceiveAccountPicker.comp.test.tsx]: done

File: suite-native/module-trading/src/components/general/ReceiveAccount/__tests__/ReceiveAccountPicker.comp.test.tsx (hunk 17 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/general/ReceiveAccount/__tests__/ReceiveAccountPicker.comp.test.tsx:100]: done

File: suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx (hunk 19 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx]: done

File: suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx (hunk 18 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx]: done

File: suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx (hunk 20 above)
Comment (peter-sanderson) [reply suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailTransactionInfo.comp.test.tsx]: done
