### PR TITLE
fix(mobile): fix wallet mobile transform

### LINKED ISSUE #13119: [suite-native] TypeError: Cannot convert undefined value to object
Sentry Issue: [SUITE-NATIVE-R8](https://satoshilabs.sentry.io/issues/5559611503/?referrer=github_integration)

```
TypeError: Cannot convert undefined value to object
  at filterObjectKeys (/home/expo/workingdir/build/suite-native/storage/src/transforms/utils.ts:15:11)
  at createTransform$argument_0 (/home/expo/workingdir/build/suite-native/storage/src/transforms/walletTransforms.ts:43:62)
...
(12 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Nodonisko**
## Description

When state is loaded from persistent storage there could be missing `fetchStatusDetail` since it's new.

I also refactored little bit.

## Related Issue

Resolve #13119

### CODE REVIEW

**Review by PeKne — APPROVED** [review]

File: suite-native/storage/src/transforms/utils.ts [hunk 1]
```diff
@@ -8,15 +8,11 @@ export const selectDeviceStatesNotRemembered = (state: DeviceRootState) => {
     );
 };
 
-export const filterObjectKeys = <O extends Record<string, any>>(
+export const filterKeysByPartialMatch = <O extends Record<string, unknown>>(
```
Comment (matejkriz) [inline suite-native/storage/src/transforms/utils.ts:11]: Looks much better 👍 but please update the unit test.

Comment (Nodonisko) [reply suite-native/storage/src/transforms/utils.ts:11]: done
