### PR TITLE
fix: small UI bugs

### LINKED ISSUE #10501: Review: Badge shouldn't have opacity on hover
It's visible in the accounts menu for coin with tokens.

**No interaction:**
image

**On hover interaction:**
Screenshot 2024-01-05 at 9 55 52

Solution: We should use color without alpha.

Design doesn't say anything about on hover state for badge

### LINKED ISSUE #10503: Review: Highlighting is without spacing
**Current state:**
Screenshot 2024-01-05 at 10 09 38

Design is not defined

### LINKED ISSUE #10520: Review: Show placeholder when there are no accounts
There should be placeholder text when there are no accounts. Font should be the same as when there is no search result but text should be "No accounts"

Screenshot 2024-01-05 at 13 59 17

Example from search:
image

### LINKED ISSUE #10521: Review: Fix button size while installing custom firmware
Screenshot 2024-01-05 at 14 20 37

### LINKED ISSUE #10530: Review: App version button polishing
- delete tooltip
- delete underline in button
- check link 
- (not important): check if we can use `Badge` instead of `Button`

Screenshot 2024-01-05 at 14 19 54

### LINKED ISSUE #10532: Review: Fix rename device
Screenshot 2024-01-05 at 17 13 49

### LINKED ISSUE #10535: Review: Fix token badges
Put the token count below the coin icon for accounts with tokens, as the current version is not flexible when it comes to non 1-digit numbers. 

image

### LINKED ISSUE #10541: Review: Fix icon alignment in "Setup complete" screen
Screenshot 2024-01-08 at 14 40 29

### LINKED ISSUE #10559: Review: Line from footer overflows on some resolutions
Dashboard:

Screenshot 2024-01-09 at 13 17 27

### LINKED ISSUE #10560: Review: Polish Labeling providers modal
Remove fixed with and margin from the provider buttons.

Screenshot 2024-01-09 at 13 20 19

Also we should use translation for this text:

image

Maybe we already have this translation? `TR_CONNECTED_TO_PROVIDER_LOCALLY`

### LINKED ISSUE #10577: Review: No search when there is no account
(low priority)

When no accounts, search should be invisible and add button should be full size with label

Screenshot 2024-01-09 at 15 04 25

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Addresses several issues with current design. Some are reported and some I found and fixed on the spot. See screensshots.

## Related Issue

Resolve #10541 
Resolve #10535 
Resolve #10532 
Resolve #10530 
Resolve #10503 
Resolve #10501 
Resolve #10520 
Resolve #10521 
Resolve #10577
Resolve #10560
Resolve #10559

## Screenshots:
4CD3DA1F-B04A-40CD-8A57-41AE674A6DFF_4_5005_c
93D93A69-7123-48B1-8ECA-67FB62A116E6_4_5005_c
7A407912-4645-45E2-A572-CA2A68509912
6E1B63AE-2AAE-4227-9A51-C6DAD0B8331F_4_5005_c
7A20C2C4-9223-40BE-A2CB-0CE5825DA067_4_5005_c
0740F380-7EFF-40A5-AF2D-E6CF5A797D80
1422CC49-261F-4F94-870B-32284244346D_4_5005_c
86BEA6E2-F72C-428E-A032-E6405849158B
36A8B6F7-FA32-4BA8-A923-C3B023F358B4
9F9DAFAF-8644-40A8-8D40-4AC5DB7E2BF7_4_5005_c
A664A2A6-4A10-4B47-9EF8-B2740343BEB4
AB2CF5D4-1CF8-4FD2-B401-BECC5A6F44D8
8C839C2E-734F-49BD-B28B-9552A7B823C4
A08AEBA7-C87A-454F-9A4C-7CDE6CCA5090_4_5005_c

### CODE REVIEW

File: packages/suite/src/components/suite/troubleshooting/tips.tsx [hunk 1]
```diff
@@ -13,30 +21,38 @@ const UdevDescription = () => {
...
+
+const BridgeStatus = () => (
+    <Wrapper>
         <Translation
-            id="TR_TROUBLESHOOTING_TIP_UDEV_INSTALL_DESCRIPTION"
+            id="TR_TROUBLESHOOTING_TIP_BRIDGE_STATUS_DESCRIPTION"
             values={{
                 a: chunks => (
-                    <TrezorLink variant="underline" onClick={handleClick} data-test="@goto/udev">
+                    <TrezorLink variant="underline" href="http://127.0.0.1:21325/status/">
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/troubleshooting/tips.tsx:49]: Is this hardcoded URL correct?

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx [hunk 2]
```diff
@@ -129,7 +129,11 @@ export const AccountsList = ({ onItemClick }: AccountListProps) => {
 
     return (
         <NoResults>
-            <Translation id="TR_ACCOUNT_SEARCH_NO_RESULTS" />
+            {!searchString ? (
```
Comment (peter-sanderson) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx:132]:
```suggestion
            {!searchString ? (
```

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx [hunk 3]
```diff
@@ -129,7 +129,11 @@ export const AccountsList = ({ onItemClick }: AccountListProps) => {
...
+                <Translation id="TR_ACCOUNT_NO_ACCOUNTS" />
```
Comment (peter-sanderson) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx]:
```suggestion
                <Translation id={!searchString ? "TR_ACCOUNT_NO_ACCOUNTS" :  "TR_ACCOUNT_SEARCH_NO_RESULTS"}/>
```

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx [hunk 4]
```diff
@@ -85,6 +90,20 @@ export const AccountsMenu = () => {
...
 
+    if (!device || !discovery) {
+        return null;
+    }
+
+    const failed = getFailedAccounts(discovery);
+
+    const list = sortByCoin(accounts.filter(a => a.deviceState === device.state).concat(failed));
+    const filteredAccounts =
+        searchString || coinFilter
```
Comment (peter-sanderson) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx]: Maybe something like: 

`searchString.trim() !== ""`

File: packages/suite/src/components/suite/troubleshooting/tips.tsx (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/troubleshooting/tips.tsx:49]: yes it is

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx (hunk 4 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx]: I think it is not really necessary

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx [hunk 5]
```diff
@@ -111,8 +130,12 @@ export const AccountsMenu = () => {
         <Wrapper>
             <MenuHeader>
                 <Row>
-                    <AccountSearchBox />
-                    <AddAccountButton data-test="@account-menu/add-account" device={device} />
+                    {!isEmpty && <AccountSearchBox />}
```
Comment (peter-sanderson) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx:121]: With this way of getting isEmpty: `const isEmpty = filteredAccounts.length === 0;`

this seems to me that the `AccountSearchBox`  will be hidden when search result is empty. Is that right?

It seems to me that isEmpty shall be `const isEmpty = list.length === 0;` instead. But maybe I am missing something.

Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx:121]: Yes you are correct, missed this, thanks

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx (hunk 4 above)
Comment (peter-sanderson) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx]: I see that `accountSearchFn` does the trim itself 

ok

File: packages/components/src/components/Badge/Badge.tsx [hunk 6]
```diff
@@ -91,12 +91,7 @@ const Container = styled.button<BadgeContainerProps>`
     ${({ onClick }) =>
         onClick &&
         css`
-            transition: opacity 0.1s ease-out;
```
Comment (dahaca) [inline packages/components/src/components/Badge/Badge.tsx:94]: Since the designers are still unsure with clickable labels, let's cut that functionality from the component entirely :) We have 0 clickable labels right now anyways.

File: packages/components/src/components/Badge/Badge.tsx [hunk 7]
```diff
@@ -91,12 +91,7 @@ const Container = styled.button<BadgeContainerProps>`
...
             cursor: pointer;
-
-            :hover {
-                opacity: 0.8;
-            }
```
Comment (jvaclavik) [inline packages/components/src/components/Badge/Badge.tsx]: Does it have any interaction on hover now?

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx [hunk 8]
```diff
@@ -11,6 +11,12 @@ import { isFeatureFlagEnabled } from '@suite-common/suite-utils';
 
 const { FONT_SIZE, FONT_WEIGHT, SCREEN_SIZE } = variables;
 
+const Wrapper = styled.div`
+    display: flex;
+    flex-wrap: wrap;
+    gap: 12px;
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx]: `gap: ${spacingsPx.sm}`

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx [hunk 9]
```diff
@@ -1,11 +1,9 @@
 import { MouseEventHandler } from 'react';
-import styled from 'styled-components';
 import { Badge } from '@trezor/components';
+import styled from 'styled-components';
 
 const StyledBadge = styled(Badge)`
-    position: absolute;
-    right: -9px;
-    bottom: -1px;
+    margin-top: 2px;
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx]: `margin-top: ${spacingsPx.xxxs}`

File: packages/suite/src/views/onboarding/steps/Final.tsx [hunk 10]
```diff
@@ -48,6 +48,7 @@ const StyledIcon = styled(Icon)`
     display: flex;
     justify-content: center;
     align-items: center;
+    margin: auto 16px auto 0;
```
Comment (jvaclavik) [inline packages/suite/src/views/onboarding/steps/Final.tsx]: margin: auto ${spacings.md} auto 0;

**Review by jvaclavik — APPROVED** [review]
👍

File: packages/components/src/components/Badge/Badge.tsx (hunk 7 above)
Comment (AdamSchinzel) [reply packages/components/src/components/Badge/Badge.tsx]: Currently no, will add something since design doesn't say anything about this

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx (hunk 8 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx]: 3dc0f17fdba7fa84790dd54dcbfdccf31e0f02f4

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx (hunk 9 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx]: 901c1e8fccc358beb45df7c7268354a7c66bf688

File: packages/suite/src/views/onboarding/steps/Final.tsx (hunk 10 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/onboarding/steps/Final.tsx]: fa97e4c28370ad5f9aec54efb2465a6bcb806b09

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx [hunk 11]
```diff
@@ -15,6 +15,11 @@ const Container = styled.div<{ isVertical?: boolean }>`
     flex-direction: ${({ isVertical }) => (isVertical ? 'column' : 'row')};
     align-items: center;
     gap: ${spacingsPx.sm};
+    ${({ isVertical }) =>
+        isVertical &&
+        css`
+            min-width: 200px;
+        `}
```
Comment (dahaca) [inline packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: nit: for better readability consider:

min-width:   ${({ isVertical }) => isVertical && '200px'};

File: packages/suite/src/utils/suite/anchor.ts [hunk 12]
```diff
@@ -29,11 +29,11 @@ export const anchorOutlineStyles = css<{ shouldHighlight?: boolean }>`
     transition: all 0.3s;
     transition-delay: 0.3s;
     outline: solid 3px transparent;
-    outline-offset: -3px;
+    padding: 10px;
```
Comment (dahaca) [inline packages/suite/src/utils/suite/anchor.ts:33]: Please also add `borders.radii.xs`

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx [hunk 13]
```diff
@@ -1,11 +1,9 @@
 import { MouseEventHandler } from 'react';
-import styled from 'styled-components';
 import { Badge } from '@trezor/components';
+import styled from 'styled-components';
 
 const StyledBadge = styled(Badge)`
```
Comment (dahaca) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx]: I believe there is no need for the Badge here. Because of its paddings the layout shift a bit with 2-3 digit numbers :( I should have been more precise in the issue description. Simply render a number for now

image

File: packages/components/src/components/form/Radio/Radio.tsx [hunk 14]
```diff
@@ -41,6 +41,7 @@ const radioVariantStyles: Record<CheckboxVariant, VariantStyles> = {
 const RadioIcon = styled(CheckContainer)`
     position: relative;
     border-radius: ${borders.radii.full};
+    min-width: 24px;
```
Comment (dahaca) [inline packages/components/src/components/form/Radio/Radio.tsx]: It would be nice to add this and `min-height` to the [`CheckContainer`](https://github.com/trezor/trezor-suite/blob/b576231512fa69917b7ff232afd18b8236c937b8/packages/components/src/components/form/Checkbox/Checkbox.tsx#L70) to solve any possible future issues for both components. And please use the tokens 🙏

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx
Comment (dahaca) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx:1]: Now when there are no accounts in the list, the `QuickAction` component jumps to the top.

image

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx:1]: As stated in the [issue](https://github.com/trezor/trezor-suite/issues/10560), simply remove the fixed width and margins, no ned to wrap and it would look much cleaner ;)

image

**Review by dahaca — CHANGES_REQUESTED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx:1]: eb6e0a6b9a3c6f767edbbc598289309594da44f2

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx:1]: e941fb3235045cc7272ec90ff3cbe3868dc9f627

File: packages/components/src/components/form/Radio/Radio.tsx (hunk 14 above)
Comment (AdamSchinzel) [reply packages/components/src/components/form/Radio/Radio.tsx]: 3f84b6aee12f169c28c7d6d4b89a353492707bb1

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx (hunk 13 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx]: be85f368770e3457bcc006a3270dbce858540e34

File: packages/suite/src/utils/suite/anchor.ts (hunk 12 above)
Comment (AdamSchinzel) [reply packages/suite/src/utils/suite/anchor.ts:33]: 018f3ebd271c5cba9c230eee353d29603829bbf2

File: packages/suite/src/components/suite/ChangeDeviceLabel.tsx (hunk 11 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/ChangeDeviceLabel.tsx]: e24d9bc25129e0630f82e556a4699b6929a1b4ae

File: packages/components/src/components/Badge/Badge.tsx (hunk 6 above)
Comment (AdamSchinzel) [reply packages/components/src/components/Badge/Badge.tsx:94]: be85f368770e3457bcc006a3270dbce858540e34

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx
Comment (dahaca) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx:1]: this is still present when just starting up

image

**Review by dahaca — APPROVED** [review]
