### PR TITLE
Fix/dropbox web

### LINKED ISSUE #24901: Legacy labels won't connect to provider on Suite web
**Describe the bug**
There is an issue on production web with legacy labels, the provider just won't connect and the popup window only stays blank (for Dropbox, Google asks for permissions but doesn't work anyway after confirming) and quits after a couple of seconds. Labels aren't turned on after that.

**Steps to reproduce:**
1. Connect a device to Suite web
2. Enable legacy labels
3. Choose either of the providers
4. Popup window shows for a couple of seconds and quits
5. No connection is made to providers and labels aren't turned ON

**Info:**
 - Suite version: web 26.1.2 (3ecd5f234e68c4198511fd6b49e3ea6ca60b0d65)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1800x1169
 - Device: Trezor T2T1 2.9.1 bitcoin-only (revision acd56d0113a547e9b5983510b0ce9de079e30e05)
 - Transport: WebUsbTransport

**Actual result:**
I can connect to a provider and see my labels.

### PR DESCRIPTION
**Pull request by juriczech**
## Summary
  - Dropbox and Google Drive OAuth on web was broken — after authorizing in the popup, the modal stayed loading
  - Root cause: `window.opener` is `null` on the OAuth receiver page after the cross-origin redirect chain (due to COOP headers), so `window.opener.postMessage()` never fires
  - Additionally, COOP makes `popup.closed` return `true` immediately for cross-origin popups, preventing reliable popup-closed detection
  - Replaced popup-to-parent communication with `BroadcastChannel` — same-origin, in-memory, no dependency on `window.opener`
  - Fixed a bug where `handleResponseError()` returned an `Error` but the return value was silently ignored
  - Removed broken `openWindowOnAnotherDomain` helper (was checking `!win` instead of `win.closed`)

  ## How it works now
  1. Main app opens OAuth popup and listens on `BroadcastChannel('trezor-oauth')`
  2. Popup completes OAuth, lands on `oauth_receiver.html`
  3. Receiver sends payload via `BroadcastChannel`, then closes itself
  4. Main app receives the code, validates state, exchanges for token, done
  5. If no response arrives within 20s, the flow times out and rejects

  ## Known limitations
  - COOP prevents detecting popup closure via `popup.closed`, so if the user manually closes the popup mid-flow, the modal with providers is hanging, but it can just be closed and the flow restarted. Better UX could be implemented here, but it's out of scope for this PR and up for discussion whether it's necessary.
  
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/24901

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/dropbox-web&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/dropbox-web&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 7 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Analytics Events > Analytics captures important events when started enabled by default | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-27T12:46:00.786Z • 7 test(s) total_

<details><summary>Trezor Suite (desktop) — 4 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |
| Firmware not ready | 🙋 manual |

</details>

_Updated: 2026-03-27T09:42:18.466Z • 4 test(s) total_

### CODE REVIEW

File: packages/suite-data/files/oauth/oauthReceiver.js [hunk 1]
```diff
@@ -5,15 +5,14 @@
...
-}
+const OAUTH_CHANNEL_NAME = 'trezor-oauth';
+
+const channel = new BroadcastChannel(OAUTH_CHANNEL_NAME);
+channel.postMessage({
+    key: OAUTH_CHANNEL_NAME,
+    hash: window.location.hash,
+    search: window.location.search,
+});
+channel.close();
```
Comment (cermakjiri) [inline packages/suite-data/files/oauth/oauthReceiver.js:16]: an elegant solution with the broadcast channel 👍

**Review by cermakjiri — APPROVED** [review]
