### PR TITLE
fix: tooltips above guide on mobile

### LINKED ISSUE #4739: Guide on mobile and small screens
Find and implement a solution for Suite Guide on small screens  (<= 992px).
 

**Spec:**
- the width of the Guide remains fixed ([350px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L13))
- guide is opened from right side (same for all screen sizes)
- screen width above [992 px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L7) remains unchanged.
- screen width [992 px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L7) and below:
  - Guide is displayed OVER modals with overlay. Modal won't move, or better yet, it will be aligned to the left side of the screen so it's easier to see what it contains (nice to have).
  image
- screen width [768 px](https://github.com/trezor/trezor-suite/blob/develop/packages/components/src/config/variables.ts/#L6) and below:
  - Guide is displayed even over navigation bar.
  image
  - Suite Guide should be now accessible from mobile menu (We call it Suite Guide no more Learn & Discover 
  image
  - Suite Guite button (lightbulb at the bottom right corner) should be shown
  image
 
  - Suide Guide button could be hidden if there is an opened modal or (nice to have) displayed as a new button next to close X button:
  image
  - Make sure links to guide from tooltips start working as expected  
  image

____
Current state: 
- There is no guide on mobile and small screens (screen width <= 768px)
- Guide breaks layout on some places on small screens (screen between 768px and 992px) 

Why:
- we do not want to have broken layout
- we want to be able to show guide as it is the only place how to find a link to contact support (there are some other places e.g. in onboarding, but I think we should remove it)

### PR DESCRIPTION
**Pull request by dahaca**
Fixes https://github.com/trezor/trezor-suite/issues/4739#issuecomment-1095153000

Now tooltip hides when the guide anchor is used. Allows to keep the z-index and use tooltips in guide too.

### CODE REVIEW

File: packages/components/src/components/Tooltip/index.tsx [hunk 1]
```diff
@@ -123,10 +123,12 @@ const Tooltip = ({
     offset = 10,
     cursor = 'help',
     content,
-    openGuide,
+    guideAnchor,
     title,
     ...rest
-}: Props) => {
+}: TooltipProps) => {
+    const [isShown, setIsShown] = useState(false);
```
Comment (Nodonisko) [inline packages/components/src/components/Tooltip/index.tsx:130]: nit: maybe isVisible is little bit more convenient

resolve if think it's good enough

**Review by Nodonisko — APPROVED** [review]

File: packages/components/src/components/Tooltip/index.tsx (hunk 1 above)
Comment (dahaca) [reply packages/components/src/components/Tooltip/index.tsx:130]: It also triggers onShow so I think it's more consistent that way c:

**Comment by STew790** [comment]
**QA OK**

Tooltip now correctly hides when Suite guide is opened.

**Info:**
 - Suite version: web 22.5.0 (bf0e4020dc1344c179501fcb5f57d9c4039c8bf0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model 1 1.10.4 regular (revision 595b14254c1abb2be3f69e42c7932f1eca8cf1b1)
 - Transport: bridge 2.0.31
