### PR TITLE
fix(suite): bump fee to current eth gas price

### LINKED ISSUE #8672: ETH bump fee does not offer current gas price
**Describe the bug**

Let's say I send ETH tx to someone with gas price `10`. However, the current gas price in the network is `100`. Tx obviously stays pending, but I need to send it now. I use `Bump Fee` feature. I do not check network fee and just use the suggested fee by Trezor Suite. However, the suggested fee is `11`, so it stays pending again 🙃

**Info:**

-   Suite Version: since the dawn of time

**How to reproduce**

1. Send tx with small gas price
2. Try to bump fee

**Expected behavior**
It offers current gas price of network.

**Screenshots**
Screenshot 2023-06-12 at 13 54 01
Send form current gas price suggestion
Screenshot 2023-06-12 at 13 54 15

**Additional context**
`useRbfForm` file. Introduced here https://github.com/trezor/trezor-suite/pull/3429
`current.plus(1);`
Screenshot 2023-06-12 at 13 52 56

### PR DESCRIPTION
**Pull request by AdamSchinzel**
When user sets gas price too low on ETH tx and wants to replace it he now gets current gas price.

## Description

I removed the `const minFee = current.plus(1)` and instead from the info param I used the selected level to get the current gas price and transformed it from Wei to Gwei.

## Related Issue

Resolve #8672 

## Screenshots:

https://github.com/trezor/trezor-suite/assets/66002635/22266e66-09fe-4e84-9396-f5a8c69f02d3

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 1]
```diff
@@ -34,16 +35,18 @@ const getBitcoinFeeInfo = (info: FeeInfo, feeRate: string) => {
 
 const getEthereumFeeInfo = (info: FeeInfo, gasPrice: string) => {
     const current = new BigNumber(gasPrice);
-    const minFee = current.plus(1);
+    const minFee = new BigNumber(fromWei(info.levels[0].feePerUnit, 'gwei'));
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useRbfForm.ts]: I see 3 use cases.

1. User created tx with low fee because he wanted to save some money but now he wants to speed tx up. 
gas price of tx 1GWEI, current is 12 GWEI, ok ✅ 
Screenshot 2023-06-27 at 12 04 38
2. User used normal fee rate, our recommended. However, gas price increased in the next block. ok (same as 🔝 ) ✅ 
3. User used normal fee rate, our recommended. However, for some reason we recommended wrong gas price. E.g. tx created with 12 GWEI gas price, I want to bump it, we still think that 12 GWEI is gas price. We offer to use 12 GWEI again. ❌ 
Screenshot 2023-06-27 at 12 00 36
Screenshot 2023-06-27 at 14 44 31

So I would add something like - if current gas price is same as gas price of tx, increase it by one.

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/hooks/wallet/useRbfForm.ts (hunk 1 above)
Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: Done

Comment (tomasklim) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: `console.log(new BigNumber(fromWei(info.levels[0].feePerUnit, 'gwei')).toString());`

Screenshot 2023-06-28 at 10 30 08
Screenshot 2023-06-28 at 10 30 11

offered gas price is now `0`

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: When did that happen? Works on my device for Ethereum mainnet and also Goerli testnet.

Screenshot 2023-06-28 at 12 10 35 PM

Screenshot 2023-06-28 at 12 12 11 PM

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: When did that happen? Works on my device for Ethereum Mainnet and also Goerli Testnet.

Screenshot 2023-06-28 at 12 20 01 PM

Screenshot 2023-06-28 at 12 19 49 PM

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: Can't reproduce your bug. When did that happen? Works on my device for Ethereum Mainnet and also Goerli Testnet.

Screenshot 2023-06-28 at 12 31 41 PM

Comment (tomasklim) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: When I tested it, current gas price reported from Blockbook was `0.7983... gwei` as can be seen in console. 

```
const minFeeFromNetwork = new BigNumber(fromWei(info.levels[0].feePerUnit, 'gwei'),).integerValue(BigNumber.ROUND_FLOOR);
```

That means that because of `BigNumber.ROUND_FLOOR` the `minFeeFromNetwork` was `0`

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: Hmm so maybe another check that if gas price is 0 from the network then also do plus(1)? Or what should be the gas price if it is 0?

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: Not sure if this is even handled when you create the tx? If not then maybe fix that there too?

Comment (tomasklim) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-utils/src/sendFormUtils.ts#L179
```// blockbook/geth may return 0 in feePerUnit. if this happens set at least minFee```

Right now, when I check fee levels for goerli in Suite, it is `1544` wei so less than `1 gwei`

So `minFeeFromNetwork` is equal to `0`
`getMinFee` returns `0` 

I am kinda confused from the logic, I cannot give you an advice without deep diving into the logic. However, `minFee` is modified to `0` and `feePerUnit` in fee `levels` too.
So the result is  ⬇️ 
Screenshot 2023-06-29 at 11 21 37

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useRbfForm.ts]: I see. I fixed the logic based on that. Can you try it? I think it should be fine now.

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 2]
```diff
@@ -34,16 +35,26 @@ const getBitcoinFeeInfo = (info: FeeInfo, feeRate: string) => {
 
 const getEthereumFeeInfo = (info: FeeInfo, gasPrice: string) => {
     const current = new BigNumber(gasPrice);
-    const minFee = current.plus(1);
+    const minFeeFromNetwork = new BigNumber(
+        fromWei(info.levels[0].feePerUnit, 'gwei'),
+    ).integerValue(BigNumber.ROUND_FLOOR);
+
+    const getMinFee = () => {
+        if (minFeeFromNetwork.toNumber() <= current.toNumber()) {
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useRbfForm.ts]:
```suggestion
        if (minFeeFromNetwork.lte(current)) {
```

I believe this is better and it should be equivalent

**Review by tomasklim — CHANGES_REQUESTED** [review]
Looks good

File: packages/suite/src/hooks/wallet/useRbfForm.ts [hunk 3]
```diff
@@ -34,16 +35,26 @@ const getBitcoinFeeInfo = (info: FeeInfo, feeRate: string) => {
...
+            return current.plus(1);
+        }
+        return minFeeFromNetwork;
+    };
+
     // increase FeeLevel only if it's lower than predefined
     const levels = getFeeLevels('ethereum', info).map(l => ({
         ...l,
-        feePerUnit: current.lte(gasPrice) ? minFee.toString() : gasPrice,
+        feePerUnit: getMinFee().toString(),
```
Comment (szymonlesisz) [inline packages/suite/src/hooks/wallet/useRbfForm.ts]: nitpick:
why call `getMinFee()` twice? 
more effective would be if you calculate it and assign once
```
const minFee = getMinFee();

// and used later
feePerUnit: minFee.toString()
...
minFee: minFee.toNumber()

```

**Review by tomasklim — APPROVED** [review]

**Comment by tomasklim** [comment]
@AdamSchinzel squash also this one please 🙏
