### PR TITLE
Suite Desktop: return valid HTML and content-type header in HttpReceiver

### LINKED ISSUE #2958: Desktop - Buy - Payment gateway redirect opens a local file
**Describe the bug**
Payment gateway redirect to text editor and not to browse in Kubuntu.
tested in Mint Linux with KDE and it works fine.

**Info:**
 - Suite Version: app, commit 36c7716bd5c2a01de4b8981a2ac680f80c79164c
 - OS:  Kubuntu 20.04
 - Firmware Version: 2.3.4

**Steps to reproduce:**
1. Start Suite app in Kubuntu
2. Proceed with Buy feature
3. Hit Go to payment button

**Expected result:**
Payment will proceed in browser

**Actual result:**
Buy provider is open in `Kate - Advanced Text Editor`

**Screenshots:**
Peek 2020-11-12 12-57

image

### PR DESCRIPTION
**Pull request by keraf**
Fixes #2958 (tested by @bosomt)

### CODE REVIEW

File: packages/suite-desktop/src-electron/http-receiver.ts [hunk 1]
```diff
@@ -121,11 +125,29 @@ export class HttpReceiver extends EventEmitter {
 
         const route = this.routes.find(r => r.pathname === pathname);
         if (route) {
+            response.setHeader('Content-Type', 'text/html; charset=UTF-8');
             // original type has url as optional, Request alias makes it required.
             return route.handler(request as Request, response);
         }
     };
 
+    // TODO: add option to auto-close after X seconds. Possible?
```
Comment (mroz22) [inline packages/suite-desktop/src-electron/http-receiver.ts:134]: would be great. But I did not find a way how to do it. Maybe we could add at least a button with xdg-redirect back to Suite

Comment (keraf) [reply packages/suite-desktop/src-electron/http-receiver.ts:134]: I think it was your comment originally that I deleted because I tried to implement the auto-close, just to then realize it's not possible. Put the comment back in case we find out a way some day :smile: Custom protocol isn't implemented yet, so we can't really redirect back to Suite just now.

**Review by szymonlesisz — APPROVED** [review]
