### PR TITLE
Fix/native/remove passphrase device on pin cancel

### LINKED ISSUE #13192: Close after locked device in passphrase leads to wrong selected device
If device is locked and user goes to passphrase flow and cancels during pin screen - it gets closed but acquired (newly created instance) is still selected. It should forget this instance and select different device.
https://github.com/trezor/trezor-suite/assets/36101761/acb59d8b-dafe-4f1e-8155-974bc13135bb

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- on PIN cancel while adding Passphrase device, the newly created device instance is correctly removed.
## Related Issue

Resolve #13192 

## Screenshots:

https://github.com/user-attachments/assets/ad9e033e-e443-4679-839d-acdfe8432f40

### CODE REVIEW

File: suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx [hunk 1]
```diff
@@ -17,6 +17,10 @@ import { Translation } from '@suite-native/intl';
 import { selectIsDeviceDiscoveryActive } from '@suite-common/wallet-core';
 
 import { ConnectingTrezorHelp } from './ConnectingTrezorHelp';
```
Comment (vytick) [inline suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx]: there are some lint and formatting errors

File: suite-native/module-authorize-device/src/components/connect/PinOnDevice.tsx [hunk 2]
```diff
@@ -41,17 +44,25 @@ type PinOnDeviceProps = {
...
+
+        // If the device asks for a passphrase after unlocking the PIN, we ignore this and let the passphrase flow handle the success / failure.
+        if (navigation.canGoBack() && isNotPassphraseFlowActive) {
+            // Remove unauthorized passphrase device if it was created before prompting the PIN in case of PIN flow exit.
+            if (isCreatingNewWalletInstance)
+                dispatch(cancelPassphraseAndSelectStandardDeviceThunk());
+
             navigation.goBack();
         }
     }, [hasDeviceRequestedPassphrase, navigation]);
```
Comment (vytick) [inline suite-native/module-authorize-device/src/components/connect/PinOnDevice.tsx]: linting/formatting

File: suite-native/module-authorize-device/src/screens/connect/ConnectingDeviceScreen.tsx [hunk 3]
```diff
@@ -6,7 +6,7 @@ import { useNativeStyles, prepareNativeStyle } from '@trezor/styles';
 import { useDelayedNavigation } from '@suite-native/device';
 import { Translation } from '@suite-native/intl';
 
-import { ConnectDeviceSreenView } from '../../components/connect/ConnectDeviceSreenView';
+import { ConnectDeviceScreenView } from '../../components/connect/ConnectDeviceScreenView';
```
Comment (vytick) [inline suite-native/module-authorize-device/src/screens/connect/ConnectingDeviceScreen.tsx:9]: noice 👏 !

**Review by vytick — APPROVED** [review]
LGTM 👍 

There are a few lint/formatting issues though.

**Review by vytick — CHANGES_REQUESTED** [review]
formatting might be worth fixing

File: suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx]: 1b6ac2759d

File: suite-native/module-authorize-device/src/components/connect/PinOnDevice.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/module-authorize-device/src/components/connect/PinOnDevice.tsx]: 1b6ac2759d

**Review by juriczech — APPROVED** [review]

**Review by vytick — APPROVED** [review]
👌
