### PR TITLE
fix/learn more button elevation in staking footer

### LINKED ISSUE #14598: Learn more button elevation in Staking dashboard
image

### PR DESCRIPTION
**Pull request by MiroslavProchazka**
Resolves: https://github.com/trezor/trezor-suite/issues/14598

Before
image

AFTER
Dark mode
image

Light mode
image

### CODE REVIEW

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/EverstakeFooter.tsx [hunk 1]
```diff
@@ -33,9 +33,12 @@ export const EverstakeFooter = () => {
                 <EverstakeLogo color={isDarkMode ? '#fff' : '#000'} />
             </Left>
 
-            <TrezorLink href={HELP_CENTER_ETH_STAKING} target="_blank">
+            <ActionButton
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/EverstakeFooter.tsx]: We use this logic 

```
            <Link href={link} target="_blank">
                <ActionButton>
                    <Translation id="id" />
                </ActionButton>
            </Link>
```

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/EverstakeFooter.tsx (hunk 1 above)
Comment (MiroslavProchazka) [reply packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/EverstakeFooter.tsx]: Resolved in 19271b6f202293c7adc4fb1b10a1177dea997dd3

Comment (MiroslavProchazka) [reply packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/EverstakeFooter.tsx]: Fixed some additional things in 89cfcfd7696429388e01e318a9ef5ab3699ebe6a

**Review by seibei-iguchi — APPROVED** [review]

**Review by tomasklim — APPROVED** [review]
