### PR TITLE
Fix app quit on MacOS

### LINKED ISSUE #2630: Desktop: Not able to quit the app on macos
**Info:**
 - OS: MacOs
 - Electron
 - Wallet Version: 20.10.1, 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 - Firmware Version: any 
 
**Describe the bug**
sometimes (i didnt find a pattern yet) i'm not able to quit the app using "right click > quit" it ends up with an error message and it's not killing the electron window. In need to kill the app manually using Task manager.

**Screenshots:**
Screenshot 2020-10-14 at 15 30 13

**Note(s):**
it's happening randomly

### PR DESCRIPTION
**Pull request by keraf**
Fixes #2630

### CODE REVIEW

File: packages/suite-desktop/src-electron/electron.ts [hunk 1]
```diff
@@ -75,7 +76,7 @@ const init = async () => {
         // do nothing
     }
 
-    if (isDev) {
+    if (isDev && !(await isPortUsed(8000))) {
```
Comment (prusnak) [inline packages/suite-desktop/src-electron/electron.ts]: I have not idea why this is required, can you please add add a comment explaining why the test is added?

File: packages/suite-desktop/src-electron/electron.ts [hunk 2]
```diff
@@ -300,11 +292,14 @@ const init = async () => {
...
-    app.quit();
-    // @ts-ignore
-    mainWindow = undefined;
+    // On macOS it is common for applications and their menu bar
+    // to stay active until the user quits explicitly with Cmd + Q
+    if (process.platform !== 'darwin') {
+        app.quit();
+    } else {
+        mainWindow = null;
+    }
```
Comment (prusnak) [inline packages/suite-desktop/src-electron/electron.ts]: Are we sure we want to keep this? It would be so much cleaner to just `app.quit()` for macOS as well (closing the bridge and tor we started).

**Review by prusnak — CHANGES_REQUESTED** [review]

File: packages/suite-desktop/src-electron/electron.ts (hunk 1 above)
Comment (keraf) [reply packages/suite-desktop/src-electron/electron.ts]: This was added to check if the Next dev server is running. We use `electron-next` which only provides a method to run the Next dev server but none for shutting it down or checking if it's up. Because the app is not killed on Mac when you close it, the server stays alive. I'll add a comment to clarify this.

File: packages/suite-desktop/src-electron/electron.ts (hunk 2 above)
Comment (keraf) [reply packages/suite-desktop/src-electron/electron.ts]: From what I observed on other applications and my understanding of the Electron docs in regards to Mac, the expected behaviour is to destroy the window but keep the app running in the tray. I don't think it makes any sense but I'm not a Mac user :shrug:

Comment (prusnak) [reply packages/suite-desktop/src-electron/electron.ts]: Ah, OK, I get it now. Let's keep this then :-/

File: packages/suite-desktop/src-electron/electron.ts (hunk 1 above)
Comment (keraf) [reply packages/suite-desktop/src-electron/electron.ts]: I changed the code to use a boolean to check if `init` was already run or not. I kept the port checking code function in the utils file for some future work.

**Review by szymonlesisz — APPROVED** [review]
