### PR TITLE
fix(suite): display testnet base currency in account detail

### LINKED ISSUE #25325: Testnet accounts balance not visible on overview
**Describe the bug**
When viewing testnet accounts, the amount of testnet coins is not visible.

The balance only appears after the user scrolls slightly down the page.

**Info:**
 - Suite version: web 26.3.0 (ce71b08bb284955b47f143b49510562d4861714f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: Trezor T3T1 2.10.0 universal (revision de4b70e2e89a64f3894dba2124f6ec56e5cbd088)
 - Transport: BridgeTransport 3.2.0

**Screenshots:**

Image

Image

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

If the account is a testnet:

- display crypto amount in the header
- hide fiat amount in the header

## Related Issue

Resolve #25325 

## Screenshots:

Screenshot 2026-02-24 at 09 50 37

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/show-testnet-base-currency&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/show-testnet-base-currency&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/show-testnet-base-currency&lookback=7)

### CODE REVIEW

**Review by tomasklim — COMMENTED** [review]
It should not display fiat in the header

**Comment by TomasBoda** [comment]
> It should not display fiat in the header

Done: testnets now only display amount in crypto. E2E tests are updated as well

**Review by BrantalikP — APPROVED** [review]

File: packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountTopPanel.tsx [hunk 1]
```diff
@@ -82,13 +84,15 @@ export const AccountTopPanel = () => {
...
                     )}
                 </AmountUnitSwitchWrapper>
-                <FiatHeader
-                    symbol={account.symbol}
-                    amount={account.formattedBalance}
-                    size="large"
-                    localCurrency={baseCurrency}
-                    data-testid="@wallet/account-top-panel/fiat-amount"
-                />
+                {!isAccountTestnet && (
```
Comment (izmy) [inline packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountTopPanel.tsx]: nit: Mainnet is the default case, `!isAccountTestnet` feels a bit inverted. Could we use a positive flag like `shouldShowFiatHeader` or `isMainnetAccount`? wdyt?

**Review by izmy — APPROVED** [review]

**Review by Vere-Grey — APPROVED** [review]
from test pow

File: packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountTopPanel.tsx (hunk 1 above)
Comment (TomasBoda) [reply packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountTopPanel.tsx]: done: changed to `isMainnet`
