### PR TITLE
fix: closing the FW upgrade / custom install modal

### LINKED ISSUE #17991: Nota able to close `Switch firmware type` modal after canceling process on device
**Describe the bug**
Nota able to close `Switch firmware type` modal after canceling process on device.

**Steps to reproduce:**
1. Start process of Switch firmware in `Settings/Device` section
2. When asked to reboot to bootloader cancel it on device
3. Try to close modal 

**Info:**
 - Suite version: web 25.4.0 (f028420356093e1b1ff5065ad4486f88d72a897e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: WebUsbTransport
**Expected result:**

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**

https://github.com/user-attachments/assets/c15f2b84-bc33-4035-ba01-dbdd19d7e915

### PR DESCRIPTION
**Pull request by peter-sanderson**
See explanation here: https://github.com/trezor/trezor-suite/pull/18576/files#r2060059924

Resolves: https://github.com/trezor/trezor-suite/issues/17991

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-fw-modal-close&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-fw-modal-close&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/firmware/FirmwareModal.tsx [hunk 1]
```diff
@@ -62,6 +63,7 @@ export const FirmwareModal = ({
         if (device?.status !== 'available') {
             dispatch(acquireDevice(device));
         }
+        dispatch(modalActions.onCancel());
```
Comment (peter-sanderson) [inline packages/suite/src/views/firmware/FirmwareModal.tsx:66]: 1) There is modal state that shall be cleared I guess. Without it, the modal never closes.
2) There is an router unlocking in the `closeModalApp` but, if modal state is present the `onLocationChange` early returns and does not leave the foreground app modal (see `onBeforePopState` method in the `packages/suite/src/actions/suite/routerActions.ts`. 

So => by calling `dispatch(modalActions.onCancel());` we "fix" two places
1. We unblock the  flow in the `onLocationChange`
2. We actually reset the modal state so no modal is rendered based on that.

**Review by Lemonexe — APPROVED** [review]
