### PR TITLE
fix(suite): Make whole coinjoin status clickable

### LINKED ISSUE #7852: Make whole coinjoin state clickable
**Context**
Suite displays in top bar state of running coinjoin. If user navigates to different account this bar works as a shortcut to running coinjoin page. There might be more of them in the same time but it is quite edge case. 
Proposal here is to only make whole bar clickable (not only small `view` button) and change the backgrounds on hover.

**Design:**
image

**Figma**
[Exploring coinjoin](https://www.figma.com/file/PrfGpe3axW0BBgf0UCzFyO/Exploring-CoinJoin?node-id=1287%3A19315&t=HOuQYdJJVFjaP9R6-1)

### PR DESCRIPTION
**Pull request by jvaclavik**
## Description

- whole status bar is clickable while coinjoin is in progress. It reacts on hover with different background color and cursor change. Also former View button is preserved, because it could confuse current users.
- works also in light mode

## Related Issue

Resolve #7852 

## Screenshots:

Before:

https://github.com/trezor/trezor-suite/assets/858321/4514e5d4-c636-4052-958b-a3f97da0c3f9

After:

https://github.com/trezor/trezor-suite/assets/858321/e938fec2-97bd-4de8-9cd7-d712ffe8be62

### CODE REVIEW

**Review by komret — APPROVED** [review]

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx [hunk 1]
```diff
@@ -36,6 +36,13 @@ const Container = styled.div`
     border-bottom: 1px solid ${({ theme }) => theme.STROKE_LIGHT_GREY};
     font-size: ${variables.FONT_SIZE.TINY};
     font-weight: ${variables.FONT_WEIGHT.MEDIUM};
+    ${({ isClickable, theme }) =>
+        isClickable &&
+        `
+        cursor: pointer;
+        &:hover {
+            background: ${theme.BG_WHITE_ALT_HOVER};
```
Comment (dahaca) [inline packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: nit: `BG_LIGHT_GREY` looks better imo :)

**Review by dahaca — CHANGES_REQUESTED** [review]
I would remove the `View` button and leave just text there + underline on status bar hover, since that button is misleading after your changes.

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx (hunk 1 above)
Comment (jvaclavik) [reply packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: I think it's very hard to see the background with `BG_LIGHT_GREY `, and it will be even worse on bad-quality monitors:

https://github.com/trezor/trezor-suite/assets/858321/6ada8fbe-c463-4f27-b1e2-26411925d0eb

Comment (dahaca) [reply packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: yeah, you are right, watching this from a bad quality monitor.... x)

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx [hunk 2]
```diff
@@ -54,8 +62,7 @@ const Separator = styled.span`
     margin: 0 ${SPACING / 2}px;
 `;
 
-const ViewButton = styled(Button)`
-    height: 20px;
+const ViewText = styled.div`
     margin-left: auto;
```
Comment (dahaca) [inline packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: color: ${({ theme }) => theme.TYPE_LIGHT_GREY};

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx [hunk 3]
```diff
@@ -27,15 +27,23 @@ import { Translation } from './Translation';
 
 const SPACING = 6;
 
-const Container = styled.div`
+const Container = styled.div<{ isClickable: boolean }>`
     display: flex;
+    justify-content: space-between;
```
Comment (dahaca) [inline packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: this is not needed, everything spreados out when `View` is not rendered because of this 🙏

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx [hunk 4]
```diff
@@ -27,15 +27,23 @@ import { Translation } from './Translation';
...
     background: ${({ theme }) => theme.BG_WHITE};
     border-bottom: 1px solid ${({ theme }) => theme.STROKE_LIGHT_GREY};
     font-size: ${variables.FONT_SIZE.TINY};
     font-weight: ${variables.FONT_WEIGHT.MEDIUM};
+    ${({ isClickable, theme }) =>
+        isClickable &&
+        `
+        cursor: pointer;
+        &:hover {
+            background: ${theme.BG_WHITE_ALT_HOVER};
```
Comment (dahaca) [inline packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: How about 

```
${ViewText} {
    text-decoration: underline;
    transform: translateX(-4px);
}
```

and `transition: transform 0.15s ease-in-out;` in `ViewText`?

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx [hunk 5]
```diff
@@ -27,15 +27,23 @@ import { Translation } from './Translation';
...
+const Container = styled.div<{ isClickable: boolean }>`
     display: flex;
+    justify-content: space-between;
     align-items: center;
     height: 28px;
     padding: 0 ${SPACING}px;
     background: ${({ theme }) => theme.BG_WHITE};
     border-bottom: 1px solid ${({ theme }) => theme.STROKE_LIGHT_GREY};
     font-size: ${variables.FONT_SIZE.TINY};
     font-weight: ${variables.FONT_WEIGHT.MEDIUM};
```
Comment (dahaca) [inline packages/suite/src/components/suite/CoinjoinStatusBar.tsx:44]: `transition: background 0.15s;`

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx [hunk 6]
```diff
@@ -27,15 +27,23 @@ import { Translation } from './Translation';
...
+    ${({ isClickable, theme }) =>
+        isClickable &&
+        `
```
Comment (dahaca) [inline packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: This is the [recommended](https://styled-components.com/docs/api#css) way to interpolate + [code highlight](https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components) starts working :)

```suggestion
       css`
```

File: packages/suite/src/components/suite/CoinjoinStatusBar.tsx (hunk 4 above)
Comment (jvaclavik) [reply packages/suite/src/components/suite/CoinjoinStatusBar.tsx]: That looks pretty cool!

**Review by dahaca — APPROVED** [review]
🫡
