### PR TITLE
fix(suite): display the app banner on the welcome screen in the right…

### LINKED ISSUE #17412: Incorrect align of banner in new welcome screen
**Describe the bug**
Incorrect align of banner in new welcome screen.
Attached web and app version screenshots

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 25.3.1 (e5b4203432360b831bb87d2bbfb2e0131e8aeae0)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.3.1 Chrome/132.0.6834.194 Electron/34.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2B1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

Image

Image

### PR DESCRIPTION
**Pull request by vojtatranta**
… column

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17412

## Screenshots:

Before: https://github.com/trezor/trezor-suite/issues/17412

After:

Screenshot 2025-03-13 at 11 49 40 AM

Screenshot 2025-03-13 at 11 53 33 AM

### CODE REVIEW

**Comment by vojtatranta** [comment]
@jvaclavik I think it needs a lot of QA...

**Comment by vojtatranta** [comment]
But another freeze is far away.

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx [hunk 1]
```diff
@@ -83,7 +80,20 @@ export const WelcomeLayout = ({ children }: WelcomeLayoutProps) => {
                         <LoggedOutSidebar />
                     </ElevationDown>
 
-                    <Right>{children}</Right>
+                    <Right
+                        bannerSlot={
+                            <>
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx]: is fragment necessary?

**Review by jvaclavik — APPROVED** [review]

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx (hunk 1 above)
Comment (vojtatranta) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx]: I guess no, will delete

**Comment by bosomt** [comment]
**QA OK**

image


**Info:**
 - Suite version: desktop 25.4.0 (e5ccc0c45bf1c935d6c0c030e02452d2cacf234a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.4.0 Chrome/134.0.6998.44 Electron/35.0.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3B1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 2.0.33
