### PR TITLE
fix(suite): Fix eject button background

### LINKED ISSUE #12467: Fix eject icon background on dark mode (view-only)
Screenshot 2024-05-17 at 15 41 35

https://www.figma.com/design/wGshbwWuR7shAA1i1UBqR8/branch/1O5PSi8KzMpeVyFMrEMZeA/Remember-Mode?node-id=2354-40396&t=03r75bJYrFjp9AqS-0

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve #12467

### CODE REVIEW

File: packages/suite/src/views/suite/SwitchDevice/DeviceItem/EjectButton.tsx [hunk 1]
```diff
@@ -1,15 +1,15 @@
...
+import { Elevation, borders, mapElevationToBackground, spacingsPx } from '@trezor/theme';
 import { ContentType } from '../types';
 
-const EjectContainer = styled.div`
+const EjectContainer = styled.div<{ $elevation: Elevation }>`
     position: absolute;
     right: ${spacingsPx.xs};
     top: ${spacingsPx.xs};
-    background-color: white;
+    background-color: ${mapElevationToBackground};
```
Comment (peter-sanderson) [inline packages/suite/src/views/suite/SwitchDevice/DeviceItem/EjectButton.tsx:12]: :clap:

**Review by peter-sanderson — APPROVED** [review]
