### PR TITLE
fix(suite-native): avoid building flipper for release build

### LINKED ISSUE #36060: Cannot resolve symbol 'ReactNativeFlipper' - When building release build variant
### New Version

0.71.1

### Old Version

0.70.6

### Build Target(s)

Android - Release Build Variant

### Output of `react-native info`

```
✗ react-native info
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 40.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.3.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^10.0.0 => 10.1.3 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.1 => 0.71.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Issue and Reproduction Steps

When I change Build Variant to Release, it builds successfully but this error comes up when clicking Run 'app'. And hovering over 'ReactNativeFlipper' shows `Cannot resolve symbol 'ReactNativeFlipper'`. 

  ```
.../MainApplication.java:61: error: cannot find symbol
        ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
        ^
symbol:   variable ReactNativeFlipper
location: class MainApplication
```

Everything works fine on `debug`

### PR DESCRIPTION
**Pull request by juriczech**
## Description
Failing action for release build on android https://github.com/trezor/trezor-suite/actions/runs/4468384664/jobs/7849061275

Screenshot 2023-03-20 at 16 29 42

Issue with proposed fix: https://github.com/facebook/react-native/issues/36060

It's possible that this will fail as well because of duplicated class ReactNativeFlipper as mentioned in the issue comment. In that case we'd need to remove `stag/` directory as well. 

## Related Issue

Resolve

### CODE REVIEW

**Review by Nodonisko — APPROVED** [review]

File: suite-native/app/android/app/src/release/io/trezor/suite/ReactNativeFlipper.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+/**
+ * Class responsible of loading Flipper inside your React Native application. This is the release
+ * flavor of it so it's empty as we don't want to load Flipper.
+ */
+public class ReactNativeFlipper {
+  public static void initializeFlipper(Context context, ReactInstanceManager reactInstanceManager) {
+    // Do nothing as we don't want to initialize Flipper on Release.
+  }
+}
+suite-native/app/android/app/src/release/java/io/trezor/suite/ReactNativeFlipper.java
```
Comment (Nodonisko) [inline suite-native/app/android/app/src/release/io/trezor/suite/ReactNativeFlipper.java:21]: are you sure this line. should be here?
