### PR TITLE
Remove redux from send form

### LINKED ISSUE #1457: BTC only Send max button is not working when address is not valid
Send max button is not working in send dialogue when address is not valid.

See video. Very low priority.

https://youtu.be/kWlhMWL4yTQ

### LINKED ISSUE #1716: Suite doesn't remember fee settings
Go to transaction.
Set transaction fee to **low**.
Send transaction.

Try to send another transaction.
You don't even need to leave send dialogue.
Fee is back to **Normal**

In current fees it means that if you want send 2$ in BTC you will pay 5$ fee.

### LINKED ISSUE #1771: SendForm: changing device state (disconnected > connected) resets draft tx
1. discover account
2. remember wallet
3. disconnect device
4. prepare transaction (address, amount)
5. connect device (whole tx is gone)

### LINKED ISSUE #1826: Send: ETH custom fee is missing in select
inconsistent form with BTC-like and XRP:

BTC-like: "custom" level reveals additional field "sat/B"
XRP: "custom" level reveals additional field "drops"
ETH-like: there is no "custom" level in select and "gas limit/gas price" fields are always visible!

Screenshot 2020-05-19 at 11 12 20

### LINKED ISSUE #1853: Send: refactor error handling
for example output error is [generated as string](https://github.com/trezor/trezor-suite/blob/83e352986502dcad94d7faf8fca2171079cd5072/packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts#L55) to be translated as a [VALIDATION_ERRORS constant](https://github.com/trezor/trezor-suite/blob/83e352986502dcad94d7faf8fca2171079cd5072/packages/suite/src/reducers/wallet/sendFormReducer.ts#L375) to finally be translated to [Translation id](https://github.com/trezor/trezor-suite/blob/83e352986502dcad94d7faf8fca2171079cd5072/packages/suite/src/views/wallet/send/components/Amount/index.tsx#L77)

### LINKED ISSUE #1889: Cannot delete last char in amount

### LINKED ISSUE #1936: UX: Bouncing elements when "Send max" clicked
send-max-loading

### LINKED ISSUE #2022: Incorrect FIAT value in Confirm transaction modal + GAS price in tokens and not in coin value
**Info:**
 - OS: nixos
 - Browser: , Firefox 76.0.1 (64-bit)
 - Wallet Version: web staging , commit 33caf3bc8934385835ad554571380d0c30278775
 - Firmware Version: 1.9.1 0xc6b2580cd245ee924507f45e9675f857a3d78768,
 
**Describe the bug**
There is something incorrect in dialogue logic.
In other places price is correct

**Steps to reproduce:**
Go to suite
Try to send ERC20 token
Check Send transaction modal

**Expected result:**
You will see real Etoken wallue and GAS price  will be in coin value

**Actual result:**
Crazy high price in modal 
GAS price is in token too

**Screenshots:**
insert here
image
image

image

### LINKED ISSUE #2023: Custom fees are ignored in send dialogue
**Info:**
 - OS: nixos
 - Browser: , FireFox  76.0.1 (64-bit)
 - Wallet Version: staging web, commit 33caf3bc8934385835ad554571380d0c30278775
 - Firmware Version: 1.9.1 , revision 0xc6b2580cd245ee924507f45e9675f857a3d78768
 
**Describe the bug**

Custom fee is ignored and transaction is sent with last selected fee /normal, high, low.../
See screenshots, even when you set fee to 1 it will be sent with much higher fee compared to wallet.

0.00000229 DOGE vs 3 DOGE
0.00000x vs 0.0000x BTC

https://doge1.trezor.io/tx/78f75c802f17ad3871534df30819d9d77c1c9e4f9dfa23434be96ce166030c99

same for BTC and probably all coins.

**Steps to reproduce:**
1. prepare transaction in send dialogue
2. try to send it with high fee check fee
3. try to send it with custom fee check fee

**Expected result:**
Send dialogue will use custom fee from custom fee field

**Actual result:**
Send dialogue will use last selected fee from fee selector

**Screenshots:**

doge
doge4

doge2
doge3

### LINKED ISSUE #2054: Custom fee price too high in new send dialogue branch
**Info:**
 - OS: latest nixOS
 - Browser: Chromium | 83.0.4103.106 (Developer Build) (64-bit)
 - Wallet Version: web, commit 968c83ecfa5bbecfc202ab9ac13fdbce0e515754
 - Firmware Version: TT  , revision 0xc6b2580cd245ee924507f45e9675f857a3d78768,
 
**Describe the bug**
Price of fee is too high in FIAT and it doesn't match real FIAT price

**Steps to reproduce:**
1. go to send-new-version branch
2. choose BTC/send dialogue
3. change fee selector to custom
4. observe

**Expected result:**
fee in FIAT will match develop branch

**Actual result:**
new send branch shows crazy high price in FIAT

**Screenshots:**

image

image

### PR DESCRIPTION
**Pull request by vladimirvolek**
- Use lib https://react-hook-form.com/ instead of the redux lib

Remove error constants resolves: https://github.com/trezor/trezor-suite/issues/1853
Fix last char in amount resolves: https://github.com/trezor/trezor-suite/issues/1889  
UX: Add custom fee to eth select resolves: https://github.com/trezor/trezor-suite/issues/1826
Fix bouncing error messages resolves: https://github.com/trezor/trezor-suite/issues/1936
Fix custom fee in dialog resolves: https://github.com/trezor/trezor-suite/issues/2023
Fix composing tx without address resolves: https://github.com/trezor/trezor-suite/issues/1457
Fix fiat fee values resolves: https://github.com/trezor/trezor-suite/issues/2054
Removed amount tooltip resolves: https://github.com/trezor/trezor-suite/issues/2065
resolves: https://github.com/trezor/trezor-suite/issues/2154
resolves: https://github.com/trezor/trezor-suite/issues/2063
resolves: https://github.com/trezor/trezor-suite/issues/1889
resolves: https://github.com/trezor/trezor-suite/issues/1771
resolves: https://github.com/trezor/trezor-suite/issues/2061
resolves: https://github.com/trezor/trezor-suite/issues/2022
resolves: https://github.com/trezor/trezor-suite/issues/1716

### CODE REVIEW

**Comment by szymonlesisz** [comment]
- amount change should "composeTx"? imho at least in BTC-like. Currently i can add invalid amount, greater than set-max but lower than max allowed balance (not enough coins to cover fee, this tx could not be accepted by the network).

- send-max button calls "composeTx" action twice, any reason for that?

- "composeTx" unnecessary calls LOCK.DEVICE, is it needed?

- persistent state to reducer

- feature: instead of setting initial fee to "normal", which not always fits your balance you can try to precompose multiple levels at once find greatest possible (old-wallet and connect does that)
https://github.com/trezor/connect/blob/31d4bb595bed72ef666f0d5c8aacb85f0e55588a/src/js/core/methods/tx/TransactionComposer.js#L68

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 1]
```diff
@@ -0,0 +1,258 @@
...
+    );
+
+    // update custom values
+    const updateContext = useCallback(
+        (value: Partial<UseSendFormState>) => {
+            setState({
+                ...state,
+                ...value,
+            });
+            console.warn('updateContext', value, state);
```
Comment (szymonlesisz) [inline packages/suite/src/hooks/wallet/useSendForm.ts:127]: rm

**Review by slowbackspace — APPROVED** [review]
