### PR TITLE
fix(suite): don't show hidden token balance in portfolio balance

### LINKED ISSUE #15199: Hiding token doesn't hide it from the Portfolio balance
**Describe the bug**
When I hide a token, the tokens fiat value is not hidden in the Portfolio balance BUT it is actually hidden in the tokens balance (in the left coins menu) so there's some inconsistency. Not sure if it should be shown in Portfolio or not but it should be at least consistent.

**Steps to reproduce:**
1. Go to for example ETH coin
2. Go to tokens
3. Hide one of the tokens
4. Observe the fiat value of the tokens on the left side changed
5. Go back to dashboard
6. The fiat value of Portfolio hasn't changed

**Info:**
 - Suite version: web 24.11.0 (05d128a974d81cb841314a86ed3c97e11cdb6ec4)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

When a token is hidden, don't show its balance in the total portfolio balance in the dashboard.

## Related Issue

Resolve #15199 

## Screenshots:

Initial portfolio balance.

Screenshot 2024-12-19 at 11 42 37

I hid this token with large balance.

Screenshot 2024-12-19 at 11 42 55

I go back to the dashboard and the token's balance is no longer a part of the total portfolio balance.

Screenshot 2024-12-19 at 11 43 17

### CODE REVIEW

File: packages/suite/src/views/dashboard/PortfolioCard/PortfolioCard.tsx [hunk 1]
```diff
@@ -47,9 +49,17 @@ export const PortfolioCard = memo(() => {
     const dispatch = useDispatch();
     const { device } = useDevice();
 
+    const tokenDefinitions = useSelector(state => state.tokenDefinitions);
+    const deviceAccounts: Account[] = accounts.map(account => {
+        const coinDefinitions = tokenDefinitions?.[account.symbol]?.coin;
```
Comment (tomasklim) [inline packages/suite/src/views/dashboard/PortfolioCard/PortfolioCard.tsx:54]: use can use `selectCoinDefinitions` selector

**Review by tomasklim — APPROVED** [review]
LGTM! good job

**Review by enjojoy — APPROVED** [review]
LGTM 

P.S. I was checking out tokenDefinitions in the repo and found a place where a selector was used in a bad practice way, so I added a commit to fix it. We're trying to eliminate the usage of this bad practice throughout the repo.
