### PR TITLE
fix: empower bugs

### LINKED ISSUE #10613: App promo in dark mode
Cleared up the issue because a lot of dark-mode things have been solved by #10140 

I think I would be better to do some lighter dark color.

1DB61EBC-2108-4ED1-98C9-FF2E7B3DCA2E

### LINKED ISSUE #10848: Empower/Bottom promo padding too tight
Let’s make it the same as padding between sections (Portfolio : Assets : Security)

image

### LINKED ISSUE #10849: Empower/Wrong top+bot in some modal content paddings
Viz. [[components in figma](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31645&mode=design&t=dDDckCeQTSS0DgJh-1)](https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A31645&mode=design&t=dDDckCeQTSS0DgJh-1)

Found in:

- Satety checks
- Add token
- Select labeling source
image

### LINKED ISSUE #10852: Empower/Device & Coins tabs disable active state on Settings (in left nav)
Application tab keeps the left nav item active as expected.

image
image

### LINKED ISSUE #10882: Make cards the default portfolio display option
image

### LINKED ISSUE #10883: Margin in the Select Wallet modal is too large
image

### LINKED ISSUE #10894: Padding between “Portfolio” header and box
Should be same as for Assets & Security

### LINKED ISSUE #10895: Padding between Portfolio value + TS3 promo
Kinda just floats there, should be either:

- 16px between the graph (so it fits with the container paddings)
- or same as between sections (Portfolio : Assets : Security)

### LINKED ISSUE #10896: trade/exchange → tootlip color and font problem
Jan 25 Screenshot from Notion

### LINKED ISSUE #10897: Settings - disconnected trezor banner is missing some space around
At least one wallet needs to be remembered to achieve this state
Jan 29 Screenshot from Notion

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

First batch of fixes for new version of Suite.

## Related Issue

Resolve #10613
Resolve #10848
Resolve #10849
Resolve #10852
Resolve #10882
Resolve #10883
Resolve #10897
Resolve #10895
Resolve #10894
Resolve #10896

## Screenshots:
7411444C-9C7F-4EDA-B5D7-44B59B53FA62_4_5005_c
73057F9D-F709-4203-92C9-41CDC91C9CC2_4_5005_c
Screenshot 2024-01-29 at 4 01 04 PM
Screenshot 2024-01-29 at 4 01 28 PM
BB4D0C31-510F-482A-A1B3-5C2D9E5ABA35_4_5005_c
85D3C526-AA96-489E-BE4E-5C227D504986_4_5005_c
D3F874E9-DC9F-466E-ABE3-43D16ECEF440_4_5005_c
6103AAEA-7B0F-45F6-B2D9-CB9ECBB42E5B

### CODE REVIEW

File: packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/NavigationItem.tsx [hunk 1]
```diff
@@ -89,18 +91,18 @@ export const NavigationItem = ({
     const handleClick = (e: MouseEvent) => {
         e.stopPropagation();
 
-        if (route) {
-            dispatch(goto(route, preserveParams === true ? { preserveParams } : undefined));
+        if (goToRoute) {
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/NavigationItem.tsx]: nit
```suggestion
        if (goToRoute !== undefined) {
```

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/views/dashboard/components/T2B1PromoBanner.tsx [hunk 2]
```diff
@@ -242,7 +241,7 @@ export const T2B1PromoBanner = () => {
         });
 
     const promoBannerAnimationConfig = {
-        initial: { opacity: 1, transform: 'scale(1)', marginBottom: -18 },
+        initial: { opacity: 1, transform: 'scale(1)' },
```
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/T2B1PromoBanner.tsx:244]: the layout is jumping now, that's why it was there. I believe framer has a better solution for it as well 

https://github.com/trezor/trezor-suite/assets/45338719/ff5fbecd-a2db-4d6d-9942-7a02489351b7

File: packages/suite/src/views/dashboard/components/PromoBanner.tsx [hunk 3]
```diff
@@ -140,13 +141,17 @@ const StoreBadge = ({
...
+    const currentTheme = useSelector(state => state.suite.settings.theme.variant);
 
     return (
         <StyledTooltip
             disabled={isMobileLayout}
             content={
                 <div>
-                    <StoreTitle image={`${image}_TITLE`} height={26} />
+                    <StoreTitle
+                        image={`${image}_TITLE_${currentTheme === 'dark' ? 'BLACK' : 'WHITE'}`}
```
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/PromoBanner.tsx:152]: Could simply be done via an inverse css filter ;) No need to have 2 filed for that.

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx [hunk 4]
```diff
@@ -37,7 +37,6 @@ const StyledButton = styled(Button)`
 // todo: typography shall be unified and these ad hoc styles removed..
 const StyledP = styled(Paragraph)`
     color: ${({ theme }) => theme.TYPE_DARK_GREY};
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx:39]: This is not needed as well + not sure why it's `type="hint"` 🤔  

Basically can just leave `Paragraph` imo.

File: packages/suite/src/components/suite/Preloader/SuiteLayout/SuiteLayout.tsx [hunk 5]
```diff
@@ -73,7 +73,7 @@ export const ContentWrapper = styled.div`
     flex: 1;
     width: 100%;
     max-width: ${MAX_CONTENT_WIDTH};
-    padding: ${spacingsPx.lg} ${HORIZONTAL_LAYOUT_PADDINGS} 90px ${HORIZONTAL_LAYOUT_PADDINGS};
+    padding: ${spacingsPx.lg} ${HORIZONTAL_LAYOUT_PADDINGS} 134px ${HORIZONTAL_LAYOUT_PADDINGS};
```
Comment (dahaca) [inline packages/suite/src/components/suite/Preloader/SuiteLayout/SuiteLayout.tsx:76]: I believe this should have been a change scoped to the Dashboard, since the Layout padding itself is OK

File: packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/Navigation.tsx [hunk 6]
```diff
@@ -25,7 +26,8 @@ const navItems: Array<NavigationItemProps & { CustomComponent?: FC<NavigationIte
     {
         nameId: 'TR_SETTINGS',
         icon: 'settings',
-        route: 'settings-index',
+        goToRoute: 'settings-index',
+        routes: ['settings-index', 'settings-device', 'settings-coins', 'settings-debug'],
```
Comment (dahaca) [inline packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/Navigation.tsx:30]: How about having typed logic based on a prefix?

```
type Routes = 'dashboard' | 'settings';

type Config = {
    route: Routes;
};

const config: Array<Config> = [
    {
        route: 'dashboard',
    },
    {
        route: 'settings',
    },
];

type SubPageName<T extends Routes> = `${T}-${string}`;

const activeRoute: SubPageName<'dashboard'> = 'dashboard-one-dashboard';

const isSubRoute = (activeRoute: string, route: Routes): activeRoute is SubPageName<Routes> =>
    config.some(item => item.route === route);

const isActiveRoute = activeRoute === route || isSubRoute(activeRoute, route);

```

File: packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx [hunk 7]
```diff
@@ -27,6 +27,11 @@ const Body = styled.div`
     flex: 1;
 `;
 
+const StyledDropdown = styled(Dropdown)`
+    display: flex;
+    height: 38px;
```
Comment (dahaca) [inline packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx:32]: this is an issue of the `DashboardSection` component, I checked 🙏

File: packages/suite/src/views/dashboard/components/PromoBanner.tsx (hunk 3 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/PromoBanner.tsx:152]: I tried but wasn't able to do it with this, if you find a better solution I would be glad

File: packages/suite/src/components/suite/Preloader/SuiteLayout/SuiteLayout.tsx (hunk 5 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/Preloader/SuiteLayout/SuiteLayout.tsx:76]: But it works so this is also a way no?

File: packages/suite/src/views/dashboard/components/T2B1PromoBanner.tsx (hunk 2 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/T2B1PromoBanner.tsx:244]: Hmm okey will fix it differently

File: packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/Navigation.tsx (hunk 6 above)
Comment (AdamSchinzel) [reply packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/Navigation.tsx:30]: I think we can leave it as it is for now

File: packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx (hunk 7 above)
Comment (AdamSchinzel) [reply packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx:32]: Okey, can you fix it in some of your next PRs then please

File: packages/suite/src/views/dashboard/components/PromoBanner.tsx (hunk 3 above)
Comment (dahaca) [reply packages/suite/src/views/dashboard/components/PromoBanner.tsx:152]: `filter: invert(1);` on the Image ;) Tried and it works!

File: packages/suite/src/components/suite/Preloader/SuiteLayout/SuiteLayout.tsx (hunk 5 above)
Comment (dahaca) [reply packages/suite/src/components/suite/Preloader/SuiteLayout/SuiteLayout.tsx:76]: It does! But the issue is not caused by the `SuiteLayout`'s incorrect paddings, it is caused by the `PromoBanner`'s `absolute` positioning making the bottom layout padding look smaller ;) 

Let's say the padding was even taller and you increase the global layout bottom padding even more to have room for it on the Dashboard. Then it might so happen that the bottom padding become too large in other places, causing another bug.

 It is not the case now but it's an explanation of why I decided to leave the original comment 🙏
