### PR TITLE
fix(suite-native): eject wallets: display only authorized wallets

### LINKED ISSUE #22080: Non-initialized Trezor shown as "Passphrase wallet" in the "Eject wallet" settings
**Describe the bug**
When I connect Trezor that has no seed nor firmware, I can go out of the onboarding and into the Settings, specifically "Eject wallets" settings, where I can see that the device connected is shown with passphrase wallet (which is not true obviously).

**Info:**

- Mobile Suite Version: 25.9.1
- OS: name, version

**How to reproduce**

1. Wipe device
2. Connect it to app
3. Quit out the onboarding
4. Go into the Settings
5. Into "Eject wallets"
6. See that the device has there already a passphrase wallet

**Screenshot**

Image

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

 - Prevent unauthorized wallets from appearing in the eject wallets list.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22080

## Screenshots:
Simulator Screenshot - iPhone 16 - 2025-10-07 at 15 48 32

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/eject-wallets-list&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/eject-wallets-list&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/eject-wallets-list&lookback=7)

### CODE REVIEW

**Comment by BrantalikP** [comment]
The fix is straightforward, but regarding the UX.  do we want to hide the entire group (e.g., Trezor device) in the list, or is it fine to just hide the invalid (the screenshot in the description) wallet? What do you think @shenkys @STew790

File: suite-native/module-settings/src/components/EjectWallets/WalletRow.tsx [hunk 1]
```diff
@@ -24,7 +24,8 @@ export const WalletRow = ({ device }: WalletRowProps) => {
     const { applyStyle } = useNativeStyles();
     const hasDiscovery = useSelector(selectHasRunningDiscovery);
 
-    // todo: only makes sense if device is already authorized (has state)
+    if (!device.state) return null;
```
Comment (juriczech) [inline suite-native/module-settings/src/components/EjectWallets/WalletRow.tsx]: `selectIsDeviceAuthorized` 🙏

Comment (matejkriz) [reply suite-native/module-settings/src/components/EjectWallets/WalletRow.tsx]: It can't be used here, you don't want to check selected device here...

**Review by matejkriz — APPROVED** [review]

File: suite-native/module-settings/src/components/EjectWallets/WalletRow.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/module-settings/src/components/EjectWallets/WalletRow.tsx]: But that one would check it only for connected/selected device no? I think we should validate the whole list

Comment (juriczech) [reply suite-native/module-settings/src/components/EjectWallets/WalletRow.tsx]: You're of course right 🤦‍♂️

**Review by juriczech — APPROVED** [review]

**Comment by juriczech** [comment]
Tested with uninitialized TS7 and works as expected. 👏

**Review by juriczech — APPROVED** [review]
Works as expected after changing the behavior. Thanks for fixing this! 🫶

**Comment by MiroslavProchazka** [comment]
Please enable auto-merge so we do not have to wait for all tests to finish

File: suite-common/wallet-utils/src/deviceUtils.ts [hunk 2]
```diff
@@ -13,11 +13,11 @@ export const parseDeviceStaticSessionId = (deviceStaticSessionId: StaticSessionI
 };
 
 export const shouldDeviceBeRemembered = ({
-    isDeviceAutoEjectEnabled,
     device,
+    isDeviceAutoEjectEnabled = true,
```
Comment (matejkriz) [inline suite-common/wallet-utils/src/deviceUtils.ts]: I don't think this is correct. `shouldDeviceBeRemembered` would return false by default then.

**Comment by BrantalikP** [comment]
@MiroslavProchazka @matejkriz guys let's proceed with freeze without this PR, its not that urgent as its more edge-case and it has failing tests. Thanks

**Comment by MiroslavProchazka** [comment]
@BrantalikP fyi I've cancelled the on-going runs to steal the runner capacity to other PRs 🙏

File: suite-common/wallet-utils/src/deviceUtils.ts (hunk 2 above)
Comment (juriczech) [reply suite-common/wallet-utils/src/deviceUtils.ts]: @BrantalikP I suggest we do it as we discussed earlier and cut out the part that we want to share please 🙏

Comment (juriczech) [reply suite-common/wallet-utils/src/deviceUtils.ts]: @matejkriz I think it will work correctly in device reducer, where it's used, as it will only set the default value if you don't pass the `isDeviceAutoEjectEnabled` at all. Which doesn't happen in deviceReducer. It would not break any already existing code that does pass this parameter. But I do agree that it's super confusing and unnecessary if we cut out the important part to reuse in settings and not rape this util function.

Comment (BrantalikP) [reply suite-common/wallet-utils/src/deviceUtils.ts]: No, I think @juriczech it’s related only to my case, where it’s not actually passed, and we didn’t test the scenario where the device is authorized with  `shouldDeviceBeRemembered` applied . It’s related to my initial mistake... I misread it as a feature flag and forgot to change it back. 🤦‍♂️ Changing the default to false should do the trick. `isDeviceAutoEjectEnabled = false`

Comment (juriczech) [reply suite-common/wallet-utils/src/deviceUtils.ts]: Another 🤦‍♂️

Comment (BrantalikP) [reply suite-common/wallet-utils/src/deviceUtils.ts]: fixed but rebased before I managed to share the fixxup link
