### PR TITLE
fix(suite): show confirmation pill on fw install

### LINKED ISSUE #21627: Missing confirmation pill in THP pairing after firmware update
After firmware is updated in settings, THP pairing is required. This must be confirmed on Trezor, but there is no indication in Suite that user should switch their attention to the device.

https://github.com/user-attachments/assets/eb1b36fc-8776-4e98-9a39-2b8134e1b4a0

In 0:23, user should see this above the modal:
Image

### PR DESCRIPTION
**Pull request by OriginalEveres**
**Changes**:
- show confirmation pill also for `ConfirmOnlyConnection`

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/21627

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/confirm-on-device-pill-fw-install&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/confirm-on-device-pill-fw-install&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/confirm-on-device-pill-fw-install&lookback=7)

### CODE REVIEW

File: suite-common/firmware/src/hooks/useFirmwareInstallation.ts [hunk 1]
```diff
@@ -119,11 +120,12 @@ export const useFirmwareInstallation = (
...
-        'thp_pairing_request',
-        'thp_connection_request',
-        'thp_autoconnect_credential_request',
-    ].includes(firmware.status);
+    const isThpConfirmationRequested =
+        [
+            'thp_pairing_request',
+            'thp_connection_request',
+            'thp_autoconnect_credential_request',
+        ].includes(firmware.status) || thpStep === 'ConfirmOnlyConnection';
```
Comment (peter-sanderson) [inline suite-common/firmware/src/hooks/useFirmwareInstallation.ts]: This is weird. Normally, the `ConfirmOnlyConnection` is the result of the `thp_connection_request` UI.REQUEST_BUTTON (see `thpReducer`) 

So I am not sure why this extra check is needed.

Comment (OriginalEveres) [reply suite-common/firmware/src/hooks/useFirmwareInstallation.ts]: 🤔 it does not apply for one step in FW install in settings.

**Comment by 5K1PY** [comment]
image

Should "Confirm on trezor" really appear in this step?

**Comment by OriginalEveres** [comment]
> image
> Should "Confirm on trezor" really appear in this step?

according to the video and description in the issue, yes. cc @komret

File: suite-common/firmware/src/hooks/useFirmwareInstallation.ts (hunk 1 above)
Comment (komret) [reply suite-common/firmware/src/hooks/useFirmwareInstallation.ts]: I confirm that it works as expected. But perhaps we should update `firmware.status` instead, as @peter-sanderson suggests?

**Comment by komret** [comment]
> Should "Confirm on trezor" really appear in this step?

@5K1PY it should not, only after you press Continue in Suite. However, it works correctly when I test it - how did you get to this state?

**Comment by OriginalEveres** [comment]
> > Should "Confirm on trezor" really appear in this step?
> 
> @5K1PY it should not, only after you press Continue in Suite. However, it works correctly when I test it - how did you get to this state?

ah, I did not notice that you were in the step where you need to confirm in suite. Yes, that should not be there. 

But I have turned this PR into draft, since I need to find a different way to solve it now. (my current solution is more of a hack)

File: suite-common/firmware/src/hooks/useFirmwareInstallation.ts (hunk 1 above)
Comment (OriginalEveres) [reply suite-common/firmware/src/hooks/useFirmwareInstallation.ts]: `firmware.status` was incorrectly used here. I've updated the code

**Review by peter-sanderson — APPROVED** [review]
