### PR TITLE
Switch device/wallets redesign and fixes

### LINKED ISSUE #1299: Webusb +check for devices button missing in "switch device" modal
**[Zeplin](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5e2eb789b530e498136335cd)**

Screen Shot 2020-03-19 at 15 40 13

### LINKED ISSUE #1380: Style Add hidden Wallet button as disabled
Terciary button **_+ Add hidden Wallet_** needs to be disabled when Device disconnected.

In such case, please add tooltip on hover saying "Connect your Trezor to add hidden wallet"

Screen Shot 2020-03-25 at 12 33 35

### PR DESCRIPTION
**Pull request by slowbackspace**
- close https://github.com/trezor/trezor-suite/issues/1299
- part of https://github.com/trezor/trezor-suite/issues/1371 (new design is incomplete and can't be properly implemented as of now)
  - I am not gonna implement the ugly new trezor icon
- close https://github.com/trezor/trezor-suite/issues/1380
- fixed webusb button (now we are positioning only the iframe, not whole button)

Screenshot 2020-03-26 at 09 58 24

### CODE REVIEW

File: packages/components/src/components/buttons/Button/index.tsx [hunk 1]
```diff
@@ -182,55 +182,63 @@ interface Props extends React.ButtonHTMLAttributes<HTMLButtonElement> {
...
-        >
-            {!isLoading && alignIcon === 'left' && IconComponent}
-            {isLoading && alignIcon === 'left' && Loader}
-            {children}
-            {!isLoading && alignIcon === 'right' && IconComponent}
-            {isLoading && alignIcon === 'right' && Loader}
-        </Wrapper>
-    );
-};
+const Button = React.forwardRef(
```
Comment (slowbackspace) [inline packages/components/src/components/buttons/Button/index.tsx:185]: just added forwardRef and passed ref to the wrapper/button component. otherwise it is completely the same.

**Comment by mroz22** [comment]
looks nice!

**Review by vladimirvolek — APPROVED** [review]
