### PR TITLE
Trading - Fees for Approval Modal

### LINKED ISSUE #18060: Trading - Fee estimation from network failed. Using backup value.
**Describe the bug**  
When you try to trade many ERC20 tokens (e.g. EURT), you are constantly spammed by the notification:  
`Fee estimation from network failed. Using backup value.`

Since we now use sensible backups, the notification might not be necessary anymore.

**Info:**
 - Suite version: web 25.5.0 (e2c9eec19bb352d9e48e24061fcb5d6e675608f5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 3.0.0-bundled.25.4.1

**Screenshots:**

Image

**Note(s):**
https://satoshilabs.slack.com/archives/C04DD84P4A1/p1739451913097169

### LINKED ISSUE #19913: Trading DEX - fees in approval modal
This issue is only about the fees part. The fees should consider only approval data.

Design:
https://www.figma.com/design/bETHMSdkxMyt2sOyQORjXe/Trends-hotfixes?node-id=508-4417&p=f&t=iCSEH0wJ1LrmcNsl-0

Now:
Image

After:
Image

Prerequisite to resolve this #14838

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Introduce fees to approval modal.

## Related Issue

Resolve #19913 
Resolve #18060 it should occur way less often

## Screenshots

Screenshot 2025-07-21 at 11 23 34

Screenshot 2025-07-21 at 11 23 43

Screenshot 2025-07-21 at 11 23 51

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/approval-fees&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/approval-fees&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/approval-fees&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts [hunk 1]
```diff
@@ -147,7 +148,19 @@ export const composeEthereumTransactionFeeLevelsThunk = createThunk<
         const { account, network, feeInfo } = composeContext;
         const { ethereumDataHex } = formState;
 
-        const composedOutput = getExternalComposeOutput(formState, account, network);
+        const isApproveTx = ethereumDataHex?.startsWith('0x095ea7b3');
```
Comment (tomasklim) [inline suite-common/wallet-core/src/send/sendFormEthereumThunks.ts]: reuse `getEvmTransactionTextSignature` ('approval' | 'revoke')

Comment (TomasBoda) [reply suite-common/wallet-core/src/send/sendFormEthereumThunks.ts]: done

**Comment by tomasklim** [comment]
Getting this error on old fw. 2.9.0 is fine

Screenshot 2025-07-19 at 11 32 55

On `Confirm` button
Screenshot 2025-07-19 at 11 32 51

I get
Screenshot 2025-07-19 at 11 32 47

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts [hunk 2]
```diff
@@ -143,11 +147,28 @@ export const composeEthereumTransactionFeeLevelsThunk = createThunk<
...
-    async ({ formState, composeContext }, { dispatch, rejectWithValue }) => {
+    async ({ formState, composeContext }, { dispatch, rejectWithValue, getState }) => {
+        const device = selectSelectedDevice(getState());
+
         const { account, network, feeInfo } = composeContext;
         const { ethereumDataHex } = formState;
 
-        const composedOutput = getExternalComposeOutput(formState, account, network);
+        const txType = getEvmTransactionTextSignature(ethereumDataHex);
+        const isApproveTx = txType === 'approval' || txType === 'revoke';
```
Comment (tomasklim) [inline suite-common/wallet-core/src/send/sendFormEthereumThunks.ts]:
```suggestion
        const isApproveTx = isEvmApprovalTx(ethereumDataHex);
```

Comment (TomasBoda) [reply suite-common/wallet-core/src/send/sendFormEthereumThunks.ts]: done

**Review by tomasklim — APPROVED** [review]
