### PR TITLE
fix(suite): add translation strings and use locales for time

### LINKED ISSUE #4338: Missing Czech translations
**Describe the bug**
Found some English sentences that are not translated.

**Info:**
 - Suite version: desktop 21.10.1 (ea82dd4a00ad06e3c36a267be1c08ade554dac58)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**

1) Enter passphrase on device

obrazek

2) new wallet is called new wallet in notifications even wallet name is in Czech language

obrazek

3) Graph 

obrazek

obrazek

4) Creating new wallet 

obrazek

5) Working in Settings/Crypto sounds strange

`Nastavení mincí také definuje, která síť bude objevena po připojení vašeho Trezoru.`

### PR DESCRIPTION
**Pull request by tomasklim**
Fixes bugs from #4338 which are fixable in code. (to the date of PR) https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937695677

Not translated are https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936940300 https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936998783 as they are strings from `connect` and we need to decide if we translate it in `suite` or `connect`. @szymonlesisz 

I am not 100% sure with `useLocales` hook, so please check if you think, that it is correct solution.

### CODE REVIEW

File: packages/suite/src/hooks/suite/useLocales.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import { useEffect, useState } from 'react';
+
+import type { Locale } from 'date-fns';
+
+import { useSelector } from '@suite-hooks';
+
+export const useLocales = () => {
```
Comment (matejkriz) [inline packages/suite/src/hooks/suite/useLocales.ts:7]: The downside of this hook is, that it is called on every usage, so the dynamic import is called multiple times. What about to put it in redux state instead? What do you think, @marekrjpolak?

Comment (matejkriz) [reply packages/suite/src/hooks/suite/useLocales.ts:7]: I would prefer to put it in `fetchLocale` action

Comment (matejkriz) [reply packages/suite/src/hooks/suite/useLocales.ts:7]: That was a bad proposal, sorry, it's not serializable to string so redux state is wrong place for it. In the end, I think it's ok the way it is.

**Review by matejkriz — APPROVED** [review]
