### PR TITLE
fix(suite): save bitcoin calculations

### LINKED ISSUE #10695: Save Bitcoin - invalid calculation
**Describe the bug**
The "Save Bitcoin" feature has a summary that shows how much you'll save up in a year, however the calculation does not work. 

**Info:**

 - Suite version: desktop 24.1.2 (b529bd13d2d6d77c065a09828ef0bbfa206ef7d8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.2 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
-   Remembered Wallet: yes

**How to reproduce**

1. Go to BTC -> Trade -> Save Bitcoin
1. Select any frequency/amount
1. See the incorrect sum of 0.00 BTC / 0.00€

**Expected behavior**
See the correct calculation in BTC and fiat

**Screenshots**
Screenshot 2024-01-17 at 13 28 58

### PR DESCRIPTION
**Pull request by AdamSchinzel**
## Description

Calculations for bitcoin save were broken. This should fix it.

## Related Issue

Resolve #10695 

## Screenshots:

Screenshot 2024-02-21 at 10 32 08 AM

### CODE REVIEW

**Review by tomasklim — CHANGES_REQUESTED** [review]
discussed

File: packages/suite/src/hooks/wallet/useCoinmarketSavingsSetup.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ export const useSavingsSetup = ({
     ]);
 
     // NOTE: There is only one fiat currency per provider.
-    const fiatCurrency = selectedProvider?.tradedFiatCurrencies[0];
+    const fiatCurrency = selectedProvider?.tradedFiatCurrencies[0].toLocaleLowerCase();
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useCoinmarketSavingsSetup.ts]:
```suggestion
    const fiatCurrency = selectedProvider?.tradedFiatCurrencies[0].toLowerCase();
```

Why `Locale`
Are you sure it does not break invity api? I am not sure but if they return `USD`, they would probably expect `USD` and not `usd` but no idea

Comment (AdamSchinzel) [reply packages/suite/src/hooks/wallet/useCoinmarketSavingsSetup.ts]: Hmm good point, will do it just for our selectors to be sure we don't break anything.

**Review by tomasklim — APPROVED** [review]
