### PR TITLE
fix(coinmarket): app crashing

### LINKED ISSUE #14172: Coinmarket - app crashing
## Description
https://github.com/user-attachments/assets/c04737f5-77f6-455c-b791-99d2b7a0c748

### 1. Prerequisite
1. Reset the app for clean storage
2. Discovery at least two different accounts (BTC, ETH for DEX)
### 2. Select BTC account
1. Select **BTC** account
2. Go to **Trade** section
3. Go to **Exchange**
4. Select `From` some ETH token
5. Select `To` ETH
6. Click on **Exchange**
7. Click on **Confirm on Trezor**
8. Click on **Finish transaction** -> will work

### 3. Select ETH account
1. Select **ETH** account
2. Go to **Trade** section
3. Go to **Exchange**
4. Select `From` some ETH token
5. Select `To` ETH
6. Click on **Exchange**
7. Click on **Confirm on Trezor**
8. Click on **Finish transaction**  -> `app will crash`

## Additional related issues
- also issue with double request after **Finish transaction**
image

- overriding the redux object will trigger errors in the console
image

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
https://github.com/user-attachments/assets/c04737f5-77f6-455c-b791-99d2b7a0c748

### 1. Prerequisite
1. Reset the app for clean storage
2. Discovery at least two different accounts (BTC, ETH for DEX)
### 2. Select BTC account
1. Select **BTC** account
2. Go to **Trade** section
3. Go to **Exchange**
4. Select `From` some ETH token
5. Select `To` ETH
6. Click on **Exchange**
7. Click on **Confirm on Trezor**
8. Click on **Finish transaction** -> will work

### 3. Select ETH account
1. Select **ETH** account
2. Go to **Trade** section
3. Go to **Exchange**
4. Select `From` some ETH token
5. Select `To` ETH
6. Click on **Exchange**
7. Click on **Confirm on Trezor**
8. Click on **Finish transaction**  -> `app will crash`

## Additional related issues
- also issue with double request after **Finish transaction**
image

- overriding the redux object will trigger errors in the console
image

## Other
Resolve https://github.com/trezor/trezor-suite/issues/14172

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendApproval.tsx [hunk 1]
```diff
@@ -87,14 +87,15 @@ export const CoinmarketOfferExchangeSendApproval = () => {
         sendTransaction,
         setExchangeStep,
     } = useCoinmarketFormContext<CoinmarketTradeExchangeType>();
+    const selectQuoteHelper = useMemo(() => ({ ...selectedQuote }), [selectedQuote]);
```
Comment (komret) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendApproval.tsx]: This looks very fragile. The memoization here shouldn't really do anything because the memoized object changes every time a dependency changes. I can see that it gets rid of the linter error, but probably that's all it is doing. Is there a way to improve this? Removing the `useEffect`, if possible...

**Review by komret — CHANGES_REQUESTED** [review]

**Review by komret — APPROVED** [review]
