### PR TITLE
fix(trading): delete suite-analytics

### LINKED ISSUE #17049: Trading - code improvements
## Description
- [x] `tradingThunks` vs `tradingThunk.test`. Same for `buyThunks` vs `buyThunk.test`
- [x] improve test description according convention (https://github.com/trezor/trezor-suite/pull/16913#pullrequestreview-2614459178)
- [x] Consider to rewrite loadInvityData as a thunk.
- [x] refactor to `createSlice`
- [x] process feedback https://github.com/trezor/trezor-suite/pull/16866
- [x] `should call processResponseData with response and save trade` is flaky (mocked date)

## Related
Follow up https://github.com/trezor/trezor-suite/issues/16518

### PR DESCRIPTION
**Pull request by adderpositive**
## Description

Deleted _suite-analytics_ from trading - not compatible with _suite-native_

### CODE REVIEW

File: suite-common/trading/src/thunks/buy/confirmTradeThunk.ts [hunk 1]
```diff
@@ -16,13 +15,20 @@ export type ConfirmTradeThunkProps = {
...
 
 export const confirmTradeThunk = createThunk(
     `${BUY_THUNK_COMMON_PREFIX}/confirmTrade`,
     async (
-        { returnUrl, address, account, processResponseData }: ConfirmTradeThunkProps,
+        {
+            returnUrl,
+            address,
+            account,
+            analyticsTriggerConfirm,
```
Comment (vytick) [inline suite-common/trading/src/thunks/buy/confirmTradeThunk.ts]: nit: I would use something starting with verb

```suggestion
            triggerAnalyticsTradeConfirmation,
```

**Review by vytick — APPROVED** [review]
👌  Looks good and mobile app builds again. Good job. Just a one tiny nit

File: suite-common/trading/src/thunks/buy/confirmTradeThunk.ts (hunk 1 above)
Comment (adderpositive) [reply suite-common/trading/src/thunks/buy/confirmTradeThunk.ts]: fixed
