### PR TITLE
fix(suite): update of btc-only fw to btc-only fw

### LINKED ISSUE #3790: Update of bitcoin-only fw
**Describe the bug**
When I update bitcoin-only firmware, I get the regular fw.

**Steps to reproduce:**
1. Have device with old bitcoin-only fw
2. Update fw
3. Check new version

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: model T 2.3.5 Bitcoin only

**Expected result:**
Bitcoin-only fw updates to bitcoin-only fw.

**Actual result:**
Bitcoin-only fw updates to regular fw.

### PR DESCRIPTION
**Pull request by tomasklim**
Right now, if you update device with btc-only fw. It is updated to device with regular fw.

Problem is that we cannot detect if device fw is btc-only or not, if device is in bootloader mode. For this reason, we have to store data about previously connected device in non-bootloader mode. Moreover, we want to store data about previous device only in firmware update modal.

### CODE REVIEW

File: packages/suite/src/middlewares/firmware/firmwareMiddleware.ts [hunk 1]
```diff
@@ -11,12 +11,13 @@ import { FIRMWARE } from '@suite/actions/firmware/constants';
...
     action: Action,
 ): Action => {
-    const prevApp = api.getState().router.app;
+    const { app: prevApp } = api.getState().router;
 
     // pass action
     next(action);
 
     const { status } = api.getState().firmware;
+    const { app } = api.getState().router;
```
Comment (matejkriz) [inline packages/suite/src/middlewares/firmware/firmwareMiddleware.ts]: I'm not sure here, but execution of the `action` is async, right? So this `getState()` call could be executed even before the `action` is processed so the `app` could be the same as `prevApp`, right? 

In that case if it is ok, then you probably don't need to define it twice and if it's not ok, then we need to handle it differently.

File: packages/suite/src/middlewares/firmware/firmwareMiddleware.ts [hunk 2]
```diff
@@ -87,6 +88,11 @@ const firmware = (api: MiddlewareAPI<Dispatch, AppState>) => (next: Dispatch) =>
             // entering firmware update context is not handled here. In onboarding device may not be connected
             // in the beginning, so remember happens after firmware.status is changed to check-seed or waiting-for-bootloader, see^^
 
+            break;
+        case DEVICE.DISCONNECT:
+            if (app === 'firmware' && action.payload.mode !== 'bootloader') {
```
Comment (matejkriz) [inline packages/suite/src/middlewares/firmware/firmwareMiddleware.ts]: minor: would be nice to put here comment explaining why this condition is used (same explanation as in PR description would be sufficient)

File: packages/suite/src/middlewares/firmware/firmwareMiddleware.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/middlewares/firmware/firmwareMiddleware.ts]: Yes, you are definitely right. 

I need only "previous" `app` here because when you have firmware modal open and you disconnect your device, it opens another modal (device disconnected), so the `firmware` one is the "previous one".

File: packages/suite/src/middlewares/firmware/firmwareMiddleware.ts (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/middlewares/firmware/firmwareMiddleware.ts]: comments improved

Comment (matejkriz) [reply packages/suite/src/middlewares/firmware/firmwareMiddleware.ts]: nice, thanks!

**Review by goodhoko — APPROVED** [review]
Went through found nothing wrong. However I'm not that familiar with this part of code to put my stamp on this. Optimally seek at least one more reviewer.

**Review by tomexx — APPROVED** [review]
lgtm, but I didn't test it
