### PR TITLE
fix(suite-native): entropy check transport error false positives

### LINKED ISSUE #23661: Entropy check device-disconnected leads to false positive
**Describe the bug**
When you get one of the [ignored entropy check errors](https://github.com/trezor/trezor-suite/blob/90458ae6b21d2e74fd6f75f67bd2e8630542ce4e/suite-common/wallet-core/src/device/deviceThunks.ts#L572-L577) while creating a wallet, you get Device compromised screen, with "Revision check" subtitle (making it even more confusing).

**Info:**

- Mobile Suite Version: develop
- OS: android emu

**How to reproduce**
Reproduced in laboratory conditions, unfeasible to do in the wild.

**Expected behavior**
Should either retry or cancel, but definitely not display the device compromised modal.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

When the entropy check results in a transport error, display a toast and **retry** the process.

## Notes for QA

Test the happy path – that creating wallet is successful.

## Related Issue

Resolve #23661

## Screenshots:

With `device disconnected` error mocked locally: 

native device-disconnected

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/entropy-check-mobile-false-positive&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/entropy-check-mobile-false-positive&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/entropy-check-mobile-false-positive&lookback=7)

### CODE REVIEW

File: suite-native/module-device-onboarding/src/screens/WalletCreationScreen.tsx [hunk 1]
```diff
@@ -60,20 +63,24 @@ export const WalletCreationScreen = () => {
...
+            // handle entropy check failure, otherwise continue with the flow
+            if (isEntropyCheckEnabled && code === 'Failure_EntropyCheck') {
+                navigation.navigate(RootStackRoutes.DeviceCompromisedModal);
+            }
         }
-        // repeat the attempt if error was not one of the DEFINITIVE_ERRORS
-        // This code is OK, but the eslint plugin crashes on recursive calls
-        // eslint-disable-next-line react-hooks/immutability
-        handleCreateAndBackupWallet();
-    }, [dispatch, walletBackupType, navigation, isEntropyCheckEnabled]);
```
Comment (Lemonexe) [inline suite-native/module-device-onboarding/src/screens/WalletCreationScreen.tsx:76]: I inverted the condition, idk, it looks more intuitive to me now.

File: suite-common/wallet-core/src/device/deviceUtils.ts [hunk 2]
```diff
@@ -17,3 +17,17 @@ export const DeviceError = (message: string): DeviceError => ({
     type: 'DeviceError' as const,
     message,
 });
+
+// Check if error is an entropy check failure, but not one of the temporarily skipped errors (to be investigated)
+export const isIgnoredEntropyCheckError = (error: string) => {
```
Comment (juriczech) [inline suite-common/wallet-core/src/device/deviceUtils.ts]: Since it's a function, I'd prefer to reflect that in the name.
```suggestion
export const getIsIgnoredEntropyCheckError = (error: string) => {
```

**Review by juriczech — APPROVED** [review]
The changes LGTM, but I think it's getting a bit complex and some of the logic that's in this component should be the thunks responsibility as well as the error handling could be improved (not fulfilled when failed, etc.)

I don't want to block this PR. I think creating additional tests for this case is the way to go and we could refactor this soon-ish.

I haven't tested this.

File: suite-common/wallet-core/src/device/deviceUtils.ts (hunk 2 above)
Comment (Lemonexe) [reply suite-common/wallet-core/src/device/deviceUtils.ts]: Good idea, done
