### PR TITLE
Unify send form input logic

### LINKED ISSUE #15227: Suite doesn't calculate crypto value correctly in send form after deleting and writing again the fiat input
**Describe the bug**
Suite doesn't calculate crypto value correctly in send form after deleting and writing again the fiat input. It works best with only single digit number but I managed to replicate it sometimes with even 2 digits.

**Steps to reproduce:**
1. Navigate to send form of any coin
2. Write any fiat value and delete it
3. Write a single digit fiat value again
4. The crypto value isn't calculated at all or incorrectly

**Info:**
 - Suite version: web 24.11.0 (b7afbd05152736013d619dfd9dc9f10143fbd216)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/user-attachments/assets/9c454141-f11f-4a27-ad6e-f4c62ce9bc71

### PR DESCRIPTION
**Pull request by komret**
Resolve https://github.com/trezor/trezor-suite/issues/15227

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 1]
```diff
@@ -181,6 +182,13 @@ export const useSendForm = (props: UseSendFormProps): SendContextValues => {
         setAmount: sendFormUtils.setAmount,
     });
 
+    const changeHandlers = useSendFormChangeHandlers({
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendForm.ts:185]: I added this "hook" because I needed to call `composeRequest` which is not available in `useSendFormFields` and cannot be added there because it is returned from `useSendFormCompose` which relies on `useSendFormFields` via `setAmount`.

File: packages/suite/src/hooks/wallet/useSendFormChangeHandlers.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    setValue: SendContextValues['setValue'];
+};
+
+export const useSendFormChangeHandlers = ({
+    calculateAmountFromFiat,
+    calculateFiatFromAmount,
+    composeRequest,
+    setValue,
+}: UseSendFormChangeHandlersParams) => {
+    const handleAmountOrFiatChange = ({
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendFormChangeHandlers.ts]: I moved the change handlers here because there was duplicate code in `Amount` and `FiatInput`. This is certainly more lines, but avoiding repetition is worth it in my opinion.

File: packages/suite/src/hooks/wallet/useSendFormFields.ts [hunk 3]
```diff
@@ -11,86 +17,147 @@ import { SendContextValues, UseSendFormState } from 'src/types/wallet/sendForm';
...
-}: Props) => {
+}: UseSendFormFieldsParams) => {
     const { shouldSendInSats } = useBitcoinAmountUnit(network.symbol);
     const currentRates = useSelector(selectCurrentFiatRates);
 
-    const calculateFiat = useCallback(
-        (outputIndex: number, amount?: string) => {
-            const outputError = errors.outputs ? errors.outputs[outputIndex] : undefined;
-            const error = outputError ? outputError.amount : undefined;
+    const getCurrentFiatRate = useCallback(
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendFormFields.ts:42]: Moved here to avoid repetition between the hook and components.

File: packages/suite/src/hooks/wallet/useSendFormFields.ts [hunk 4]
```diff
@@ -11,86 +17,147 @@ import { SendContextValues, UseSendFormState } from 'src/types/wallet/sendForm';
...
+            const targetValue = output[target];
+            if (target === 'fiat' && typeof targetValue !== 'string') {
+                return; // fiat input not registered (testnet or fiat not available)
+            }
+            const targetInputName = `outputs.${outputId}.${target}` as const;
+            const outputError = errors.outputs ? errors.outputs[outputId] : undefined;
+            const error = outputError
+                ? outputError[target === 'fiat' ? 'amount' : 'fiat']
+                : undefined;
+            if (error || !value) {
```
Comment (komret) [inline packages/suite/src/hooks/wallet/useSendFormFields.ts:79]: Here's what fixes the bug. In `FiatInput`, `error` was read from context where it was not yet updated at the time of triggering the change handler. Thus, this behaviour was delayed by one keyboard stroke.
Accessing `error` directly from `useForm` solves the issue. `Amount` did not have this problem, so I just unified the approach between the two inputs.

File: packages/suite/src/views/wallet/send/Outputs/Amount/FiatInput.tsx [hunk 5]
```diff
@@ -236,29 +167,27 @@ export const FiatInput = ({
     );
 
     return (
-        <Wrapper>
```
Comment (komret) [inline packages/suite/src/views/wallet/send/Outputs/Amount/FiatInput.tsx:239]: Useless wrapper, it looks the same without it.

File: packages/suite/src/hooks/wallet/useSendFormChangeHandlers.ts (hunk 2 above)
Comment (Lemonexe) [reply packages/suite/src/hooks/wallet/useSendFormChangeHandlers.ts]: That sounds good to centralize change handlers here, but are you sure about the `handleAmountOrFiatChange` and `calculateTheOtherValue`?
This layer of abstraction add complexity, I think it'd just fine if there were too functions `handleAmountChange` and `handleFiatChange` with some boilerplate. But ok :shrug:

File: packages/suite/src/hooks/wallet/useSendFormFields.ts [hunk 6]
```diff
@@ -11,86 +17,147 @@ import { SendContextValues, UseSendFormState } from 'src/types/wallet/sendForm';
...
+                value: amount,
+            });
+        },
+        [calculateFiatFromAmountOrViceVersa, shouldSendInSats, network.symbol],
+    );
+
+    const calculateAmountFromFiat = useCallback(
+        (outputId: number, fiat: string) => {
+            const calculateFormattedAmountValue = (fiat: string, fiatRate: number) => {
+                const amount = fromFiatCurrency(fiat, network.decimals, fiatRate);
```
Comment (Lemonexe) [inline packages/suite/src/hooks/wallet/useSendFormFields.ts]: the original implementation used `token.decimals || network.decimals` ..?

File: packages/suite/src/hooks/wallet/useSendFormChangeHandlers.ts (hunk 2 above)
Comment (komret) [reply packages/suite/src/hooks/wallet/useSendFormChangeHandlers.ts]: I agree that was a bit wild. What about 7200dfcd4a8970a766a1ec936c719f515a3d8cac?

**Review by Lemonexe — APPROVED** [review]
Great refactoring! It's quite complex, so it took me a while to follow all the changes, as I was not familiar with original code. It seems to me it replicates the original behavior, but if I missed something, idk. I think the depth of abstraction is ok.

Tested and works well :heavy_check_mark:

File: packages/suite/src/hooks/wallet/useSendFormFields.ts (hunk 6 above)
Comment (komret) [reply packages/suite/src/hooks/wallet/useSendFormFields.ts]: Nice catch! c49af7248472705a6f9e90cdabaecce8d08fd2a4
