### PR TITLE
fix(suite): make sure that we are not stuck on blank screen after pint

### LINKED ISSUE #19372: Discovery refactor - TS3 pin blank screen
**Describe the bug**
If you connect a pin locked TS3 device and enter the pin - **first wrongly and then correctly** the app ends in a blank screen state.

https://github.com/user-attachments/assets/be3d843b-bd67-4674-b82f-c75ca2a9c6da

### PR DESCRIPTION
**Pull request by vojtatranta**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19372

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=19372-fix-go-back-black-pin&lookback=7)

### CODE REVIEW

File: suite-native/module-authorize-device/src/screens/connect/PinScreen.tsx [hunk 1]
```diff
@@ -1,37 +1,22 @@
...
-
 export const PinScreen = () => {
-    const navigation = useNavigation<NavigationProp>();
+    const navigateToInitialScreen = useNavigateToInitialScreen();
 
     const deviceModel = useSelector(selectDeviceModel);
 
     const onSuccess = useCallback(() => {
-        if (navigation.canGoBack()) {
-            navigation.goBack();
```
Comment (vojtatranta) [inline suite-native/module-authorize-device/src/screens/connect/PinScreen.tsx:32]: go back in AuthorizeStack only meant goint to empty screen coz the passphrase stack is on top there (I am not enterily sure if thats' correct but this works pretty well)

**Review by Lemonexe — APPROVED** [review]
Looks LGTM to me, thanks!
