### PR TITLE
Use total stake pending and remaining entry period in staking

### LINKED ISSUE #26548: Incorrect remaining entry period for ETH pending stake
The displayed remaining entry period is incorrect and does not match the real remaining duration.

Image

Image

### PR DESCRIPTION
**Pull request by myasiura-stack**
## Description

Fixes pending-stake UI on native Earn: use total stake pending for amounts and remaining entry-period days (from stake txs + validator queue) instead of pool pending deposit and unstaking-period days. 

## Related Issue

Resolve #26548

## Screenshots:
Simulator Screenshot - iPhone 16 Plus - 2026-04-13 at 11 54 26

### CODE REVIEW

File: suite-native/module-earn/src/screens/StakingManagementScreen.tsx [hunk 1]
```diff
@@ -18,6 +20,11 @@ export const StakingManagementScreen = () => {
     const route = useRoute<RouteProp<RootStackParamList, RootStackRoutes.StakingManagement>>();
     const { accountKey } = route.params;
     const { networkSymbol } = parseAccountKey(accountKey);
+    const dispatch = useDispatch();
+
+    useEffect(() => {
```
Comment (BrantalikP) [inline suite-native/module-earn/src/screens/StakingManagementScreen.tsx:25]: is this related to the issue?

File: suite-native/module-earn/src/components/StakingManagementPendingStakeModal.tsx [hunk 2]
```diff
@@ -57,11 +57,12 @@ export const StakingManagementPendingStakeModal = ({
...
-    const pendingDepositedBalance = useSelector((state: NativeStakingRootState) =>
-        selectPendingDepositedBalanceByAccountKey(state, accountKey),
-    );
-    const unstakingPeriodInDays = useSelector((state: NativeStakingRootState) =>
-        selectUnstakingPeriodInDaysByAccountKey(state, accountKey),
+    const totalStakePending =
+        useSelector((state: NativeStakingRootState) =>
+            selectTotalStakePendingByAccountKey(state, accountKey),
+        ) ?? '0';
+    const entryPeriodRemainingInDays = useSelector((state: NativeStakingRootState) =>
```
Comment (BrantalikP) [inline suite-native/module-earn/src/components/StakingManagementPendingStakeModal.tsx]: Hey, I tried the same approach as on [desktop](https://github.com/trezor/trezor-suite/blob/22eceff1851a6b63ed2259036477d6393e1c5ce3/packages/suite/src/views/wallet/staking/components/EthStakingDashboard/EthStakingDashboard.tsx#L56) that sends lastTxBlockTime as a param to get `validatorQueue` data [query](https://github.com/trezor/trezor-suite/blob/develop/suite-common/earn-staking-api/src/staking/hooks/useEthereumValidatorsQueue.ts) hook. Please validate if it works for you. cc: @tomasklim 



```suggestion
    const account = useSelector(state => selectAccountByKey(state, accountKey));
    const stakeTxs = useSelector(state => selectAccountStakeTransactions(state, accountKey));
    const lastTxBlockTime = stakeTxs[0]?.blockTime;
    const timestamp =
        account && hasStakeInPendingDepositedState(account) ? lastTxBlockTime : undefined;
    const { data: validatorQueueData } = useEthereumValidatorsQueue({
        account: account!,
        timestamp,
    });
    const entryPeriodRemainingInDays = getDaysToAddToPool(stakeTxs, validatorQueueData);


```

**Review by BrantalikP — CHANGES_REQUESTED** [review]

File: suite-native/module-earn/src/components/StakingManagementPendingStakeModal.tsx [hunk 3]
```diff
@@ -57,12 +64,24 @@ export const StakingManagementPendingStakeModal = ({
...
     );
-    const unstakingPeriodInDays = useSelector((state: NativeStakingRootState) =>
-        selectUnstakingPeriodInDaysByAccountKey(state, accountKey),
+    const stakeTxs = useSelector((state: NativeStakingRootState) =>
+        selectAccountStakeTransactions(state, accountKey),
     );
+    const lastTxBlockTime = stakeTxs[0]?.blockTime;
+    const timestamp =
+        account && hasStakeInPendingDepositedState(account) ? lastTxBlockTime : undefined;
+    const { data: validatorQueueData } = useEthereumValidatorsQueue({
```
Comment (BrantalikP) [inline suite-native/module-earn/src/components/StakingManagementPendingStakeModal.tsx:81]: as there are a few points of failures where it can fail. I think we should add some sort of protection in case the `entryPeriodRemainingInDays` is `undefined` please

**Review by BrantalikP — APPROVED** [review]
