### PR TITLE
fix(suite): cardano staking dashboard balance

### LINKED ISSUE #22701: Cardano Staking - Confusing display of Cardano staking and account balances in Suite
**Describe the bug**
Currently, the Cardano staking screen seems to show two separate balances: one for the account and one for the active stake. However, for Cardano, the entire account balance is always staked—there should not appear to be two balances. This may confuse users into thinking only a portion is staked.

**Screenshots**
**Current**
Cardano staking screen showing two balances

**Proposed**
[Figma](https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Staking--Final-?node-id=3285-25583&t=eC7PcjYRg3FbSjHN-0)

Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Updated Cardano staking dashboard to show full balance instead of separate active and pending balances.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22701

## Screenshots:
image

### CODE REVIEW

File: packages/suite/src/views/wallet/staking/components/StakingDashboard/components/StakingCard.tsx [hunk 1]
```diff
@@ -233,22 +245,34 @@ export const StakingCard = ({
...
+                            }
+                            data-testid="@account/staking/full-balance"
+                        />
+                    ) : (
+                        <Item
+                            label={<Translation id="TR_STAKE_STAKE" />}
+                            iconName="lock"
+                            symbol={selectedAccount?.symbol}
+                            cryptoAmount={depositedBalance || '0'}
+                            fiatAmount={depositedBalance || '0'}
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/staking/components/StakingDashboard/components/StakingCard.tsx]: pass formatted crypto amount and base currency value here using title and description

Comment (dev-pvl) [reply packages/suite/src/views/wallet/staking/components/StakingDashboard/components/StakingCard.tsx]: done, https://github.com/trezor/trezor-suite/pull/22811/commits/655b5564b1f2f165cc1cb74da73d3ea236102c0c

**Review by tomasklim — APPROVED** [review]
Please rebase and squash
