### PR TITLE
fix(suite): onboarding last step with BTC-only

### LINKED ISSUE #22506: Cannot complete onboarding with BTC-only FW
**Describe the bug**
In BTC-only FW onboarding you can't skip PIN, and after setting the PIN, the page crashes,

**Info:**

- Suite Version: Web `develop` as of ea7ddf42
- Browser: Brave
- Bridge: node-bridge as of ea7ddf42
- Firmware Version:
  - T3B1 production 2.9.1,
  - T3W1 test-signed 2.9.3

**How to reproduce**

1. Start onboarding
1. Create/recoer wallet
1. Try to skip pin, the button on modal is frozen
1. Set pin
2. next
3. crashes instead of final screen (coin selection screen is skipped with BTC-only)

**Expected behavior**
Get to onboarding final screen and be able to finish onboarding

**Screenshots**

- [Try to skip pin](https://github.com/user-attachments/assets/c80b2334-4eb0-49d8-8588-ac48a7741a9d)
- [So I set PIN, continue and then this](https://github.com/user-attachments/assets/93121403-a3e6-44dc-99d7-1d3bc0814d3c)

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

When `goToNextStep`, and there is no more step, then `goToSuite` instead of crashing.

This also cleans up the code a bit :slightly_smiling_face: 

I tested:
- onboarding BTC only skipping PIN (goes to suite)
- onboarding BTC only setting PIN (goes to suite)
- onboarding universal (goes to suite from coin selection screen no matter what you do with PIN)

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22506

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/onboarding-BTC-only&lookback=7)

### CODE REVIEW

File: packages/suite/src/actions/onboarding/onboardingActions.ts [hunk 1]
```diff
@@ -67,15 +71,6 @@ const getAllStepsInPath = (getState: GetState) => {
...
 };
 
-const goToNextStep = (stepId?: AnyStepId) => (dispatch: Dispatch, getState: GetState) => {
-    if (stepId) {
-        return dispatch(goToStep(stepId));
-    }
-    const stepsInPath = getAllStepsInPath(getState);
-    const nextStep = findNextStep(getState().onboarding.activeStepId, stepsInPath);
-    dispatch(goToStep(nextStep.id));
-};
```
Comment (Lemonexe) [inline packages/suite/src/actions/onboarding/onboardingActions.ts:77]: moved below because `no use before define`, but added `null` handling corresponding to the `findNextStep` change from throw to null.

File: packages/suite/src/actions/onboarding/onboardingActions.ts [hunk 2]
```diff
@@ -102,6 +97,50 @@ const resetOnboarding = (): OnboardingAction => ({
...
+        };
+        delete payload.startTime;
+
+        analytics.report({
+            type: EventType.DeviceSetupCompleted,
+            payload,
+        });
+    };
+    reportAnalytics();
+};
```
Comment (Lemonexe) [inline packages/suite/src/actions/onboarding/onboardingActions.ts:127]: I unified all code from `useOnboarding` + `CoinsStep/index.tsx‎` into one thunk.
This is may also fix other potential issues, because at [SecurityCheck](https://github.com/trezor/trezor-suite/blob/cdc1078ba6470727f8c48927c2038090f38aac7a/packages/suite/src/views/onboarding/steps/DeviceAuthenticityStep/SecurityCheck.tsx) there is `goToSuite` called, but so far it did only one part.

File: packages/suite/src/hooks/suite/useOnboarding.ts [hunk 3]
```diff
@@ -36,21 +34,11 @@ export const useOnboarding = () => {
...
 
-    const goToSuite = (initialRedirection = false) => {
-        dispatch(suiteActions.initialRunCompleted());
-        dispatch(onboardingActions.resetOnboarding());
-        dispatch(routerActions.closeModalApp(true));
-
-        // fixes a bug that user ends up in settings after initialization of a new device because he navigated to settings before
-        if (initialRedirection) {
-            dispatch(routerActions.goto('suite-index'));
-        }
```
Comment (Lemonexe) [inline packages/suite/src/hooks/suite/useOnboarding.ts:51]: `initialRedirection` paramter was never used so I removed this if branch

**Review by seibei-iguchi — APPROVED** [review]
Amazing!

**Comment by Lemonexe** [comment]
Merging, failing desktop E2E `settings/without-device.test.ts` [confirmed to be broken](https://satoshilabs.slack.com/archives/CKYFBT2C9/p1760541970992649?thread_ts=1760528936.424339&cid=CKYFBT2C9)
