### PR TITLE
fix(trading): fixed trading fee layout unwanted resize

### LINKED ISSUE #17098: Fee is moving with trading layout
**Describe the bug**

https://github.com/user-attachments/assets/c699eeda-93e9-4c81-ad56-891807fa531f

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Fixed trading layout resize upon clicking on the Advanced fee.

## Related Issue

Resolve #17098 

## Screenshots:

https://github.com/user-attachments/assets/292fa944-2a9e-424e-95cf-a1cacdcb8223

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingWrapper.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { spacingsPx } from '@trezor/theme';
 export const TradingWrapper = `
     gap: ${spacingsPx.md};
     display: grid;
-    grid-template-columns: minmax(500px, auto) minmax(340px, 420px);
+    grid-template-columns: 1fr 420px;
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingWrapper.tsx:7]: Kinda hacky but I decided that I don't see a great benefit in having the right card resizable in such a small range.

Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingWrapper.tsx:7]: Kinda hacky but I decided that I don't see a great benefit in having the right card resizable in such a small range.

Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingWrapper.tsx:7]: And of course it fixes the current issue

**Review by tomasklim — APPROVED** [review]
LGTM
