### PR TITLE
Display gas price for token transaction when not enough Eth balance 

### LINKED ISSUE #15219: Show how much fee is needed to send token tx
**Describe the bug**
Based on [Slack](https://satoshilabs.slack.com/archives/C016ACNF1BN/p1730561896489939)
Related to https://github.com/trezor/trezor-suite/issues/13756

User is missing info what is enough ETH to cover token tx fee 
Screenshot 2024-11-05 at 10 59 28

**Info:**

-   Suite Version: 24.11.0

**Expected behavior**
We can also add it into error message `With current network fees (5 gas price), enough amount of ETH is 0.001`
Screenshot 2024-11-05 at 10 58 22

### PR DESCRIPTION
**Pull request by enjojoy**
## Description

Now users can see ow much Eth they need for a token transaction, when they don't have enough 

## Related Issue 

Resolve https://github.com/trezor/trezor-suite/issues/15219

## Screenshots:
Before:
Screenshot 2024-12-19 at 15 30 52

After:
Screenshot 2024-12-19 at 15 26 04
Screenshot 2024-12-19 at 15 29 30

### CODE REVIEW

**Review by Lemonexe — APPROVED** [review]
Codewise LGTM, works as expected :heavy_check_mark: 

:thought_balloon: Though wouldn't it make sense to introduce a similar message for all coins as well, not just tokens? Just a thought :thinking:

**Review by izmy — APPROVED** [review]

**Comment by enjojoy** [comment]
> Codewise LGTM, works as expected ✔️
> 
> 💭 Though wouldn't it make sense to introduce a similar message for all coins as well, not just tokens? Just a thought 🤔

I think that would be good, yes. 

On mainnet now it just says "not enough funds" if you enter too much. But you also can do "send max" and it will set the max that is possible to send considering the gas, so it's easier to navigate then on tokens.

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts [hunk 1]
```diff
@@ -46,31 +46,43 @@ const calculate = (
...
-        const error = token ? 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE' : 'AMOUNT_IS_NOT_ENOUGH';
+        if (token) {
+            return {
+                type: 'error',
+                error: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT',
+                errorMessage: {
+                    id: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT',
+                    values: {
+                        symbol: 'ETH',
+                        feeAmount: `(${fromWei(feeInGwei, 'ether')} ETH)`,
```
Comment (tomasklim) [inline suite-common/wallet-core/src/send/sendFormEthereumThunks.ts:75]: This method is for all EVMs, why `ETH` is hardcoded?
Screenshot 2024-12-20 at 20 15 02

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -5426,6 +5426,11 @@ export default defineMessages({
         defaultMessage: 'Not enough {symbol} to cover transaction fee',
         id: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE',
     },
+
+    AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT: {
+        defaultMessage: 'Not enough {symbol} to cover transaction fee {feeAmount}',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts:5431]: How about
`Not enough {symbol} to cover transaction fee ({feeAmount} {symbol)',`

I dont like hardcoded symbol and ( ) in code, we try to keep the most of logic in crowdin. This will get broken in some languages

**Comment by tomasklim** [comment]
> 💭 Though wouldn't it make sense to introduce a similar message for all coins as well, not just tokens? Just a thought 🤔

I don't know about coins, but it should be available for all networks with tokens at least

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts (hunk 1 above)
Comment (tomasklim) [inline suite-common/wallet-core/src/send/sendFormEthereumThunks.ts:75]: it would make sense to just return `feeAmount` as a number here. Symbol is not needed

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts [hunk 3]
```diff
@@ -227,10 +239,16 @@ export const composeEthereumTransactionFeeLevelsThunk = createThunk<
...
+            if (
+                tx.type === 'error' &&
+                tx.error === 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT'
+            ) {
                 tx.errorMessage = {
-                    id: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE',
-                    values: { symbol: network.symbol.toUpperCase() },
+                    id: 'AMOUNT_NOT_ENOUGH_CURRENCY_FEE_WITH_ETH_AMOUNT',
+                    values: {
+                        symbol: tx.errorMessage?.values?.symbol || 'ETH',
```
Comment (tomasklim) [inline suite-common/wallet-core/src/send/sendFormEthereumThunks.ts:249]: use `symbol` from account or `network.symbol`, never hardcode symbols in generic evm code

File: suite-common/wallet-utils/src/sendFormUtils.ts [hunk 4]
```diff
@@ -75,21 +75,31 @@ export const calculateMax = (availableBalance: string, fee: string): string => {
...
+/**
+ * Calculate the Ethereum fee from gas price and gas limit.
+ * @param {string} [gasPrice] - The gas price in wei.
+ * @param {string} [gasLimit] - The gas limit.
+ * @returns {string} The calculated fee in wei, or '0' if inputs are invalid.
  */
 export const calculateEthFee = (gasPrice?: string, gasLimit?: string): string => {
     if (!gasPrice || !gasLimit) {
         return '0';
     }
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/sendFormUtils.ts:87]: maybe we can remove this? it looks duplicated with BN logic

File: suite-common/wallet-utils/src/sendFormUtils.ts [hunk 5]
```diff
@@ -75,21 +75,31 @@ export const calculateMax = (availableBalance: string, fee: string): string => {
...
+
+    if (gasPriceBN.isNaN() || gasLimitBN.isNaN()) {
         return '0';
     }
+
+    const fee = gasPriceBN.times(gasLimitBN);
+
+    if (fee.isNaN()) {
+        return '0';
+    }
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/sendFormUtils.ts:100]: if both are numbers, can this ever happen?

File: suite-common/wallet-utils/src/sendFormUtils.ts [hunk 6]
```diff
@@ -75,21 +75,31 @@ export const calculateMax = (availableBalance: string, fee: string): string => {
...
+    const gasLimitBN = new BigNumber(gasLimit);
+
+    if (gasPriceBN.isNaN() || gasLimitBN.isNaN()) {
         return '0';
     }
+
+    const fee = gasPriceBN.times(gasLimitBN);
+
+    if (fee.isNaN()) {
+        return '0';
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/sendFormUtils.ts:99]: Maybe it would make sense to throw error. There is some backup logic, and 0 fees are not valid

File: packages/suite/src/support/messages.ts (hunk 2 above)
Comment (adderpositive) [reply packages/suite/src/support/messages.ts:5431]: If it is ok, I made a little refactoring. Commit: https://github.com/trezor/trezor-suite/pull/15993/commits/0d79d6dff1cd5b390161fc528e10e65153248453 More information is in the related PR. Please give me your code review! :)

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts (hunk 1 above)
Comment (adderpositive) [reply suite-common/wallet-core/src/send/sendFormEthereumThunks.ts:75]: https://github.com/trezor/trezor-suite/pull/15993/commits/0d79d6dff1cd5b390161fc528e10e65153248453

File: suite-common/wallet-core/src/send/sendFormEthereumThunks.ts (hunk 3 above)
Comment (adderpositive) [reply suite-common/wallet-core/src/send/sendFormEthereumThunks.ts:249]: https://github.com/trezor/trezor-suite/pull/15993/commits/0d79d6dff1cd5b390161fc528e10e65153248453

**Comment by enjojoy** [comment]
@tomasklim  I'll create a followup PR to implement your comments
