### PR TITLE
Sort receive accounts in swap section

### LINKED ISSUE #14879: Trading - when swapping receive accounts list is not organised by account number
**Describe the bug**
See video or screenshot.
When swapping accounts list is not organised by account type or number.

**Steps to reproduce:**
1. Perform swap to coin that have multiple used accounts in wallet
2. Observe how accounts are sorted

**Info:**
 - Suite version: desktop 24.11.0 (9a8687546678796c7ff1a8b151044d9a58c4b3cc)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision d71d9e9c343ad04a7f28d6b02f8d3f8945af30d6)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

image

https://github.com/user-attachments/assets/51aa630f-2b46-4241-9919-865ee00dfb96

### PR DESCRIPTION
**Pull request by enjojoy**
## Description
Sort accounts by account type and account index

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14879

## Screenshots:
Screenshot 2025-01-08 at 14 46 56
Screenshot 2025-01-08 at 14 59 52

### CODE REVIEW

**Review by izmy — APPROVED** [review]

File: suite-common/wallet-utils/src/filterReceiveAccounts.ts [hunk 1]
```diff
@@ -15,6 +15,16 @@ export const isDebugOnlyAccountType = (
...
 
+const accountTypeOrder: Record<AccountType, number> = {
+    normal: 0,
+    ledger: 1,
+    legacy: 2,
+    imported: 3,
+    segwit: 4,
+    coinjoin: 5,
+    taproot: 6,
+};
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/filterReceiveAccounts.ts]: I guess Bitcoiners will not be happy to have `legacy` accounts before `segwit` and `taproot`

I would expect something like:

1. normal (BTC, ETH, SOL,...)
2. taproot (BTC)
3. segwit (BTC)
4. coinjoin (BTC)
5. ledger (ETH, SOL)
6. legacy (BTC, ETH)
7. imported (??? mobile)

Please someone confirm @hynek-jina @marekrjpolak

Comment (tomasklim) [reply suite-common/wallet-utils/src/filterReceiveAccounts.ts]: I think we already have to have some ordering in Suite because it logically orders accounts in sidebar

Comment (tomasklim) [reply suite-common/wallet-utils/src/filterReceiveAccounts.ts]: I would stick to that and reuse it
Screenshot 2025-01-14 at 15 41 39

**Review by tomasklim — APPROVED** [review]

File: suite-common/wallet-utils/src/filterReceiveAccounts.ts (hunk 1 above)
Comment (tomasklim) [reply suite-common/wallet-utils/src/filterReceiveAccounts.ts]: resolved
