### PR TITLE
18698 mobile trade visual fixes

### LINKED ISSUE #18698: Mobile Trade: Visual fixes
- [x] when scrolled tradeable asset list has changed filter, it should scroll back to top (now the scroll offset remains the same)
- [x] Currency picker button should have height the same as small button (40pts)
- [x] Currency picker should have no bg gradient
- [x] Tradeable asset button should have border in dominant color with 16% alpha
- [x] At the moment user can pick network account, the color of `Not selected` should be active color (it has disabled color now)
- [x] Search input field should have right edge lined with the content under that

### PR DESCRIPTION
**Pull request by jbazant**
## Related Issue

Resolve #18698

## Screenshots:
Screenshot 2025-05-05 at 11 06 36
Screenshot 2025-05-05 at 11 06 19
Screenshot 2025-05-05 at 11 05 47

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=18698-Mobile-Trade-Visual-fixes&lookback=7)

### CODE REVIEW

File: suite-native/module-trading/src/components/buy/AssetNetworkInfo.tsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ export const AssetNetworkInfo = () => {
     const shouldShowNetwork = showForNativeToken || contractAddress;
 
     if (!shouldShowNetwork) {
-        return null;
+        return <Box />;
```
Comment (vytick) [inline suite-native/module-trading/src/components/buy/AssetNetworkInfo.tsx:29]: Please, add comment, why to have Box here.

File: suite-native/module-trading/src/components/general/TradeableAssetButton.tsx [hunk 2]
```diff
@@ -25,19 +25,23 @@ export type TradeableAssetButtonProps = {
...
-    padding: 6,
+const buttonStyle = prepareNativeStyle(({ boxShadows, spacings }) => ({
+    height: spacings.sp40,
+    paddingHorizontal: spacings.sp8,
+    gap: spacings.sp8,
     flexDirection: 'row',
     justifyContent: 'center',
     alignItems: 'center',
-    gap: spacings.sp8,
+    ...boxShadows.small,
```
Comment (vytick) [inline suite-native/module-trading/src/components/general/TradeableAssetButton.tsx]: Lets not add shadow anywhere to be consistent.

**Review by vytick — APPROVED** [review]

**Review by vytick — APPROVED** [review]
Looks good 👍 👌.

Just two small nits

File: suite-native/module-trading/src/components/general/TradeableAssetButton.tsx (hunk 2 above)
Comment (jbazant) [reply suite-native/module-trading/src/components/general/TradeableAssetButton.tsx]: My mistake. (This in fact had no effect)

Fixed.

**Comment by jbazant** [comment]
@coderabbitai full review

File: suite-native/module-trading/src/components/general/TradeableAssetButton.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/module-trading/src/components/general/TradeableAssetButton.tsx]: Yes, I could not see it, but it is better not to have it there. Thanks!

**Review by vytick — APPROVED** [review]
