### PR TITLE
Upload android native sourcemaps to sentry

### LINKED ISSUE #10080: Sentry JS source maps in mobile app
It seems that sourcemaps for JS doesn't work both on Android and iOS. This is really unfortunate for debugging.

### PR DESCRIPTION
**Pull request by vytick**
- Only wrap app for Sentry when we init sentry.
- track performance only for 50% of events
- add fastlane action to upload sourcemaps for android after the build

Resolves #10080

### CODE REVIEW

File: suite-native/app/android/fastlane/Fastfile [hunk 1]
```diff
@@ -79,6 +79,17 @@ platform :android do
...
+    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
+    sentry_upload_sourcemap(
+      auth_token: ENV["SENTRY_AUTH_TOKEN"],
+      org_slug: 'satoshilabs',
+      project_slug: 'suite-native',
+      version: ENV["VERSION"],
+      app_identifier: package_name, 
+      build: ENV["BUILD_NUMBER"]
+      sourcemap: ['index.android.bundle', 'index.android.bundle.map'],
+      rewrite: true
```
Comment (matejkriz) [inline suite-native/app/android/fastlane/Fastfile:91]: what does this parameter do?

File: suite-native/app/src/App.tsx [hunk 2]
```diff
@@ -128,4 +129,4 @@ const PureApp = () => (
     </GestureHandlerRootView>
 );
 
-export const App = Sentry.wrap(PureApp);
+export const App = isDebugEnv() ? Sentry.wrap(PureApp) : PureApp;
```
Comment (matejkriz) [inline suite-native/app/src/App.tsx]: This seems inverted to me. And it won't stop Sentry.wrap from being called before Sentry.init, will it?

File: suite-native/app/android/fastlane/Fastfile (hunk 1 above)
Comment (vytick) [reply suite-native/app/android/fastlane/Fastfile:91]: Hard to say from the code. I would say it rewrites the sourcemap for the version and build. Even though we bump the build number, I suggest to keep it there just for sure.

File: suite-native/app/src/App.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/app/src/App.tsx]: Hmm, Sentry.init is being called in the useEffect, so you are probably right. But at least it wont bother us on debug while developing the app.

Comment (vytick) [reply suite-native/app/src/App.tsx]: Also I inverted the check as you suggested
a9999ff173

File: suite-native/app/src/App.tsx [hunk 3]
```diff
@@ -128,4 +129,4 @@ const PureApp = () => (
     </GestureHandlerRootView>
 );
 
-export const App = Sentry.wrap(PureApp);
+export const App = isDebugEnv() ? PureApp : Sentry.wrap(PureApp);
```
Comment (Nodonisko) [inline suite-native/app/src/App.tsx:132]: I not sure if this will solve issue, in other envs than debug it will use Sentry.wrap even if Sentry is disabled. Maybe that is not issue because it won't do anything if Sentry is disabled but I am not sure.

Comment (vytick) [reply suite-native/app/src/App.tsx:132]: I agree. I didnt realise init is called in useEffect. But I would say it will work the same as it worked until now and the warning wont bother us while developing: https://github.com/trezor/trezor-suite/pull/10555#discussion_r1446273799

Comment (Nodonisko) [reply suite-native/app/src/App.tsx:132]: Ok, seems reasonable.

**Review by vdovhanych — APPROVED** [review]
