### PR TITLE
fix(connect-init): add getAccountInfo to wrapping blacklist

### LINKED ISSUE #19590: Device gets locked every second and lot of  buttons becomes inactive
**Describe the bug**

Device gets locked every second and device or coin settings become inactive
See video and log @suite/lock-device is triggered every second.

**Steps to reproduce:**

Load develop web version and connect device
Navigate to Settings/device
Observe buttons

Image

https://github.com/user-attachments/assets/086d1cb0-d5d2-4c2b-bb9b-bd407648032d

**Info:**
 - Suite version: web 25.6.1 (d812d7abea8f95084cc384513efe74da168ca5e7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 5120x1440
 - Device: Trezor T1B1 1.13.1 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Do not wrap `getAccountInfo` which was introduced in #19833 because it is often called in a way that does not require device, and locks the suite excessively.

Neither is entirely correct, because some flows of `getAccountInfo` do use device, and some don't.
:thought_balloon:  It'd be best to wrap it only when Suite knows that device will be used, but that'd require to duplicate the Connect code in `connectInitThunks`.
Does anyone have a better idea? If so, please make a PR instead of this one, but this is at least a hotfix that restores original behavior for today's freeze :slightly_smiling_face:  

## Related Issue

Resolve #19590

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/lock-device-too-often&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/lock-device-too-often&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/lock-device-too-often&lookback=7)

### CODE REVIEW

**Comment by mroz22** [comment]
oh yeah, sry. I remember getAccountInfo was the troublemaker

File: suite-common/connect-init/src/blacklist.ts [hunk 1]
```diff
@@ -26,4 +26,8 @@ export const blacklist: ConnectKey[] = [
     'getCoinInfo',
     'dispose',
     'cancel',
+    // this API may use device or not, depending on parameters. The flow that doesn't use device is called very often,
+    // so locking device must be avoided (blocks a lot of Suite features needlessly)
+    // TODO find a better solution to wrap this method only when device is used
```
Comment (mroz22) [inline suite-common/connect-init/src/blacklist.ts:31]: better solution is to use the __info: true dry run param and let connect tell you whether the method will or will not need device. This way we should be able to get rid of this blacklisting completely

**Review by mroz22 — APPROVED** [review]

File: suite-common/connect-init/src/blacklist.ts (hunk 1 above)
Comment (Lemonexe) [reply suite-common/connect-init/src/blacklist.ts:31]: Cool, I didn't know that is possible! Yes, that sounds like the "better idea" I was asking for :+1:
But I guess I'll merge this PR for freeze, because using the dry run sounds like deep refactoring with potential new bugs.

**Review by martykan — APPROVED** [review]
