### PR TITLE
fix(suite-native): make sure that requeesting passphrase on device fl…

### LINKED ISSUE #19352: Discovery refactor - passphrase retry
When I choose to enter the passphrase on the device and cancel it, then try to do it again, it doesn’t trigger the action on the device again.”

### PR DESCRIPTION
**Pull request by vojtatranta**
…ag is switched off frist before discovery is cancelled due to useEffect in useHandleDeviceRequestPassprase navigation hook

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19352

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=19352-cant-input-passphrase-device-after-cancel-on-device&lookback=7)

### CODE REVIEW

File: suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnterOnTrezorScreen.tsx [hunk 1]
```diff
@@ -65,12 +65,12 @@ export const PassphraseEnterOnTrezorScreen = () => {
     }, [isDeviceAuthorizationDone, navigation]);
 
     const handleCancel = () => {
+        dispatch(setInputPassphraseOnDevice(false));
```
Comment (vojtatranta) [inline suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnterOnTrezorScreen.tsx:68]: problem:
in `useHandleDeviceRequestedPassphrase` hook, there is a useEffect. When first was called "cancel" on the discovery is removed, and this trigges use effect. Since `addingHiddenWallet` is false there, it triggers navigation to the `passphrase unlock feature` screen, which is incorrect.

**Review by Lemonexe — APPROVED** [review]
Makes sense.
Tested and it works correclty :+1:
