### PR TITLE
fix(suite-native): Mobile Trade: fix buy form known issues

### LINKED ISSUE #17927: Mobile Trade: Fetch quotes and fill the buy form
When user has selected all off (or later changed): 
- tradeable asset
- amount of fiat/crypto 
- fiat currency

Fetch quotes from API and set the rest of the form:
- get all possible payment methods from all quotes
- if possible select Credit Card as payment method, if not pick the first one
- select first quote that has selected payment method
- write out provider of this selected quote

### PR DESCRIPTION
**Pull request by jbazant**
## Description

Various fixes, refactors and tests for mobile trade.

## Related Issue

Resolve #17927

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/mobile-trade-buy-form&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/mobile-trade-buy-form&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/mobile-trade-buy-form&lookback=7)

### CODE REVIEW

File: suite-native/module-trading/src/components/general/TradingAmountInput.tsx [hunk 1]
```diff
@@ -13,6 +13,7 @@ export type TradingAmountInputProps = {
 export const INPUT_MIN_WIDTH = 60;
 export const INPUT_HEIGHT = 42;
 
+// TODO test coverage for color
```
Comment (vytick) [inline suite-native/module-trading/src/components/general/TradingAmountInput.tsx]: Tests seem to be added now?

File: suite-native/module-trading/src/hooks/useQuotes.ts [hunk 2]
```diff
@@ -82,12 +84,64 @@ const useShouldFetchQuotes = (form: TradingBuyForm): ShouldFetchQuotes => {
...
+            quotesPromiseRef.current.abort('Invalidating quotes');
+        }
+    }, [shouldAbortQuotesRequest, quotesPromiseRef, debounce]);
+
+    // make sure no stale quotes are present when form is invalid
+    useEffect(() => {
+        if (shouldInvalidateQuotes) {
+            dispatch(clearQuotesAndQuotesRequest());
+        }
+    }, [shouldInvalidateQuotes, dispatch]);
```
Comment (vytick) [inline suite-native/module-trading/src/hooks/useQuotes.ts:119]: **thought**:  What do you think about having only one these three useEffects above depending on `isFormValid`, `isLoading` and `quotes.length`. All those should... booleans can be then inside and we will know in which order and when exactly those clearings will happen. It feels it would be easier to read in that case

File: suite-native/module-trading/src/hooks/useTradingBuyForm.ts [hunk 3]
```diff
@@ -41,49 +41,50 @@ const useAmountAndCurrencyFieldsChangeEffect = (form: TradingBuyForm) => {
...
-                    if (focusedValue === 'fiatValue') {
-                        form.setValue('cryptoValue', undefined);
-                        form.setValue('amountInCrypto', false);
-                        form.trigger('cryptoValue');
+        const { unsubscribe } = form.watch(
+            ({ focusedValue, asset, amountInCrypto }, { name, type }) => {
+                switch (name) {
+                    case 'fiatValue':
+                        if (focusedValue === 'fiatValue' && type === 'change') {
+                            form.setValue('cryptoValue', undefined, { shouldValidate: true });
```
Comment (vytick) [inline suite-native/module-trading/src/hooks/useTradingBuyForm.ts:47]: **question:** Would it make sense to clear form 'quote' here (and in cryptoValue and fiatCurrency branch) as well?

**Review by vytick — COMMENTED** [review]
Great improvement 💪. I have a few questions, but otherwise it works really nice

File: suite-native/module-trading/src/hooks/useTradingBuyForm.ts (hunk 3 above)
Comment (jbazant) [reply suite-native/module-trading/src/hooks/useTradingBuyForm.ts:47]: I spent some time considering this and decided not to do it here. Current flow is:
1. Form becomes "invalid" because of some change. No matter what exactly changed.
1. Quotes are currently fully managed by `useQuotes` hook. If form becomes "invalid" quotes ar cleared.
3. `useQuotesChangeEffect` reacts to `quotes` changes and clears / selects best quote.

There is IMO no need to add another complexity to this process.

After reviewing `useQuotesChangeEffect` I decided to add early return to corresponding effect when no quotes are  available (It should not change behavior, just make the process more straightforward).

Also I found out that `useQuoteChangeEffect` can be simplified (and also correctly named). Please take a closer look to make sure I did not introduce new flaw.

File: suite-native/module-trading/src/components/general/TradingAmountInput.tsx (hunk 1 above)
Comment (jbazant) [reply suite-native/module-trading/src/components/general/TradingAmountInput.tsx]: Yes. Forgot to remove the comment. Fixed

File: suite-native/module-trading/src/hooks/useQuotes.ts (hunk 2 above)
Comment (jbazant) [reply suite-native/module-trading/src/hooks/useQuotes.ts:119]: The problem with your proposal is that we either need to add `prevShouldClearDebounceCallback`, etc. and check for changes or those clearings may run more often than necessary. Although I am not sure whether it can actually cause any problem. 🤔

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts [hunk 4]
```diff
@@ -108,14 +108,19 @@ export const handleRequestThunk = createThunk(
...
         }
 
         if (!Array.isArray(allQuotes) || allQuotes.length === 0) {
             timer.stop();
-            dispatch(tradingBuyActions.saveQuotes([]));
 
-            return;
+            const quotesSuccess: BuyTrade[] = [];
+            dispatch(tradingBuyActions.setAmountLimits(undefined));
+            dispatch(tradingBuyActions.saveQuotes(quotesSuccess));
```
Comment (adderpositive) [inline suite-common/trading/src/thunks/buy/handleRequestThunk.ts:119]:
```suggestion
            dispatch(tradingBuyActions.saveQuotes([]));
```

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts [hunk 5]
```diff
@@ -97,7 +97,7 @@ export const handleRequestThunk = createThunk(
         if (!requestData) {
             timer.stop();
 
-            return;
+            throw rejectWithValue('Invalid request data');
```
Comment (adderpositive) [inline suite-common/trading/src/thunks/buy/handleRequestThunk.ts:100]:
```suggestion
            return rejectWithValue('Invalid request data');
```

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts [hunk 6]
```diff
@@ -108,14 +108,19 @@ export const handleRequestThunk = createThunk(
         if (signal.aborted) {
             timer.reset();
 
-            return;
+            throw rejectWithValue('Request was aborted');
```
Comment (adderpositive) [inline suite-common/trading/src/thunks/buy/handleRequestThunk.ts:111]:
```suggestion
            return rejectWithValue('Request was aborted');
```

**Review by adderpositive — APPROVED** [review]
I have only some nitpicks, fine by me.

**Comment by adderpositive** [comment]
I have tested the timer and it works well on the desktop. Nice improvement.

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts (hunk 5 above)
Comment (vytick) [reply suite-common/trading/src/thunks/buy/handleRequestThunk.ts:100]: I see that you changed it from return to throw. What is the reason?

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts [hunk 7]
```diff
@@ -108,14 +108,19 @@ export const handleRequestThunk = createThunk(
...
-            dispatch(tradingBuyActions.saveQuotes([]));
 
-            return;
+            const quotesSuccess: BuyTrade[] = [];
+            dispatch(tradingBuyActions.setAmountLimits(undefined));
+            dispatch(tradingBuyActions.saveQuotes(quotesSuccess));
+            dispatch(tradingBuyActions.saveQuoteRequest(requestData));
+            dispatch(tradingActions.savePaymentMethods([]));
+
+            return fulfillWithValue(quotesSuccess);
```
Comment (vytick) [inline suite-common/trading/src/thunks/buy/handleRequestThunk.ts:123]: It might make sense not to use `quotesSuccess` here at all?

**Review by vytick — APPROVED** [review]
Looks and works nicely 👌. Great improvement 🚀 

One question regarding  that `throw` same as @adderpositive  has

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts (hunk 4 above)
Comment (jbazant) [reply suite-common/trading/src/thunks/buy/handleRequestThunk.ts:119]: I use `quotesSuccess` defined on line 117 by purpose. I want the array returned from thunk and array saved to quotes to be the same one. (Not two different empty arrays) Maybe I am just overthinking it 🤔

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts (hunk 5 above)
Comment (jbazant) [reply suite-common/trading/src/thunks/buy/handleRequestThunk.ts:100]: The reason is that if you try to `return rejectWithValue('Invalid request data');` return signature of thunk for some reason changes and typescript start screaming in `packages/suite/src/hooks/wallet/trading/form/common/useTradingBuyHandleChange.ts`.

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts (hunk 7 above)
Comment (jbazant) [reply suite-common/trading/src/thunks/buy/handleRequestThunk.ts:123]: This branch saves empty array to quotes it makes sense to me to return that array as well.

Or do you mean to rename the constant to `emptyQuotes` or similar?

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts (hunk 5 above)
Comment (vytick) [reply suite-common/trading/src/thunks/buy/handleRequestThunk.ts:100]: wtf. I see it now. 👍

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts (hunk 4 above)
Comment (adderpositive) [reply suite-common/trading/src/thunks/buy/handleRequestThunk.ts:119]: Ooh, sorry, I have overlooked the return value

File: suite-common/trading/src/thunks/buy/handleRequestThunk.ts (hunk 5 above)
Comment (adderpositive) [reply suite-common/trading/src/thunks/buy/handleRequestThunk.ts:100]: Strange behavior, but valid argument! :)
