### PR TITLE
fix(suite-native): input top padding

### LINKED ISSUE #9472: Overlap of text in enter xpub via text field
**Describe the bug**
See screenshot.
When you enter xpub manually placeholder text is not deleted and both text overlaps.

**Info:**

-   Mobile Suite Version: ccabcec - [develop] - chore(suite-common): device middleware (#9445)
-   OS: iOS + Android

**How to reproduce**

**Screenshots**
Screenshot 2023-09-18 at 15 55 50

### PR DESCRIPTION
**Pull request by PeKne**
## Description

- fixes conditonal top padding, the padding should be always the same independent of `isFocused` state

## Related issue

Closes #9472

## Screenshots:

https://github.com/trezor/trezor-suite/assets/26143964/66525716-4dfa-45ce-9824-11a92c8fa450

### CODE REVIEW

File: suite-native/atoms/src/Input/Input.tsx [hunk 1]
```diff
@@ -113,7 +113,7 @@ const inputStyle = prepareNativeStyle<InputStyleProps>((utils, { isIconDisplayed
     borderWidth: 0,
     flex: 1,
     // Make the text input uniform on both platforms (https://stackoverflow.com/a/68458803/1281305)
-    paddingTop: isFocused ? utils.spacings.large : 0,
+    paddingTop: utils.spacings.large,
```
Comment (juriczech) [inline suite-native/atoms/src/Input/Input.tsx:115]: `isFocused` is not used anymore so please remove it from style prop types and its usage

**Review by juriczech — CHANGES_REQUESTED** [review]

**Review by Nodonisko — COMMENTED** [review]
Can you make padding larger? It seems that there is very small gap between label and input text

File: suite-native/atoms/src/Input/Input.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/atoms/src/Input/Input.tsx:115]: fixed by 04ff390c6d

**Comment by PeKne** [comment]
@Nodonisko I just realized that I've uploaded wrong (not final) demo video 🙈. Actually with this version of code the input top padding looks like this. It is according to the design, so no change needed. 
Screenshot 2024-02-07 at 8 02 26

**Review by juriczech — APPROVED** [review]
