### PR TITLE
fix(staking): gas limit when bumping fee

### LINKED ISSUE #12183: Use reserve for bumping fee of un/staking, claiming tx
**Describe the bug**
Fee reserve is not applied for bumping staking, unstaking and claiming tx

**How to reproduce**
1. Stake with low gas price
1. Bump fee and observe

**Screenshots**

Screenshot 2024-04-29 at 10 31 43

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

Increase gas limit for bump fee of staking txs

Discussion here https://satoshilabs.slack.com/archives/C0543DJBK0C/p1719409880504649?thread_ts=1719403259.875369&cid=C0543DJBK0C

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12183

## Screenshots:
Unstake:
Screenshot 2024-07-12 at 15 15 29

Bump unstake:
Screenshot 2024-07-12 at 15 15 42
ignore zero amount and information twice, issues are linked in comment below
Screenshot 2024-07-12 at 15 15 53

### CODE REVIEW

**Comment by tomasklim** [comment]
Identified two new bugs: 
issues
https://github.com/orgs/trezor/projects/75/views/3?pane=issue&itemId=70759189
https://github.com/orgs/trezor/projects/75/views/3?pane=issue&itemId=70759227

File: suite-common/wallet-core/src/stake/stakeTypes.ts [hunk 1]
```diff
@@ -14,6 +14,12 @@ import { FeeLevel } from '@trezor/connect';
 // Used when Everstake pool stats are not available from the API.
 export const BACKUP_ETH_APY = 4.13;
 
+// Slack discussion https://satoshilabs.slack.com/archives/C0543DJBK0C/p1719409880504649?thread_ts=1719403259.875369&cid=C0543DJBK0C
+// increasing gas limit as tx can consume more than it was estimated due to edge cases
+// stake/unstake method usually consumes 97k-425k but can take up to 1M
+// claim method 97k-300k
+export const STAKE_GAS_LIMIT_RESERVE = 220_000;
```
Comment (jvaclavik) [inline suite-common/wallet-core/src/stake/stakeTypes.ts:21]: wooow :D I didn't know that I can use _ in number

**Review by jvaclavik — APPROVED** [review]
