### PR TITLE
fix(suite): Make Welcome screen more responsible for smaller screens

### LINKED ISSUE #13261: Polish Welcome screen
1. Check main button color - should be `variant="primary"`

2. There are multiple responsive issues:

image

image

3. Verify design with Ondra

### PR DESCRIPTION
**Pull request by hstastna**
## Description

Make "Download desktop app" and "trezor.io" buttons/links more nicely visible also for smaller screens. Use `flex-flow: row wrap;` css style for it.

Additionally, use `spacingsPx` for margin sizes of the related components where possible instead of hardcoded values.

TODO:
more screens need the similar polishing. For more info see the related issue.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13261

## Screenshots:
**Before:**

https://github.com/user-attachments/assets/4d48af61-58fc-45c9-bd17-498c44262b81

**After:**

https://github.com/user-attachments/assets/d5e3fe9c-201c-499d-a732-9a27f9f90eb3

### CODE REVIEW

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ const Expander = styled.div`
     justify-content: center;
     align-items: center;
     flex: 1;
+    margin-top: calc(${spacingsPx.xxxxl} * 2);
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx]: Not sure maybe just place `96px`? If its not semantic. (WDYT @jvaclavik ?)

Comment (jvaclavik) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx]: I agree with using just `96px`

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx [hunk 2]
```diff
@@ -69,18 +70,20 @@ const MotionWelcome = styled(motion.div)`
...
 
 const LinksContainer = styled.div`
-    position: absolute;
     bottom: 0;
     display: flex;
-    margin: 24px 0;
+    margin: ${spacingsPx.xl};
+    align-items: center;
+    flex-flow: row wrap;
+    gap: 14px;
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx]: Maybe could we use `spacingsPx.md` here? Does it look good?

Comment (hstastna) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx]: Very little visual change of the gap, IMHO both options are ok, see 14px vs 16 px (difference almost unseen):
gap
I think we can safely use `spacingsPx.md` here.

**Review by jvaclavik — APPROVED** [review]
