### PR TITLE
Remove initial cancel call for BT devices

### LINKED ISSUE #21820: Trezor is already in use
Trying to reconnect T3W1 results in the message "Trezor is already in use" and an "Acquire error: Device is used in another window."

seems to happen mostly on Linux but I have also seen instances on windows

**Info:**
 - Suite version: desktop 25.10.0 (0c38f599d12923ffe53305b8575b1f7cf9b944dc)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.10.0 Chrome/140.0.7339.41 Electron/38.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 5120x1440
 - Device: Trezor T3W1 2.9.2 universal (revision 1e7f36abc0de9f87c8ae2b4c5900291040053c0b)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

When connected over BT, we don't need to call `Cancel` first in order to detect v2 protocol as it's always v2. This resolves some issues, e.g. when the device is suspended so the Cancel call times out which kinda breaks the handshake.

## Related issues
At least in some cases resolves #21820

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/initial-cancel-wake&lookback=7)

### CODE REVIEW

File: packages/connect/src/device/Device.ts [hunk 1]
```diff
@@ -197,6 +197,12 @@ export class Device extends TypedEmitter<DeviceEvents> {
         return (this.descriptorType ?? 0) <= 2;
     }
 
+    public get isTS7() {
```
Comment (martykan) [inline packages/connect/src/device/Device.ts]: I think a more generic name like `isProtocolV2` would be more suitable, also future-proof for any devices afterwards

Comment (marekrjpolak) [reply packages/connect/src/device/Device.ts]: Renamed to `isProtocolV2Device` as it still can have `device.protocol === protocolV1` at that time.

**Review by martykan — APPROVED** [review]
