### PR TITLE
connect: check possible device duplicates before the handshake 

### LINKED ISSUE #21700: Cannot install FW via cable after pairing via BT
**Describe the bug**

When device is paired via BT, and user is prompted to install FW via cable because of battery below 50%, after connecting via cable it throws `Error: Firmware update allowed with only 1 device connected`. I guess Suite is counting the BT and cable connection as 2 separate devices.

**Info:**
 - Suite version: desktop 25.10.0 (1160cfd53e2405511eea0ac122886d0bc19cf3ce)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/25.10.0 Chrome/140.0.7339.41 Electron/38.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3W1  universal (revision null)
 - Transport: BridgeTransport 3.1.0, BluetoothTransport

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description
Addressing two issues:

- allow FW installation when device is connected over BT and USB at the same time. should fix https://github.com/trezor/trezor-suite/issues/21700
- freshly connected device handshake is optional. It is skipped when connected device probably exists on different transport and is currently in use. Such device is created as unacquired. This should prevent from taking over currently running workflows.
      Conditions:
      1. if USBDevice `serialNumber` (aka device.descriptor.id) match known device features `device_id`
      1. if DescriptorApiLevel model match known device.descriptor.model
      1. and `device.isUsed() === true` -> device transport is having a session
  
#### How to test case 1 (suite-desktop):
Following the steps from  https://github.com/trezor/trezor-suite/issues/21700

- connect via BLUETOOTH
- go to Settings/Device click on FW update
- before installation imagine that you are requested to charge Trezor battery and connect it via USB
- start installation

Expected result: installation should be allowed and FW is uploaded over USB transport (faster)

#### How to test case 2 (suite-desktop):
- connect via BLUETOOTH
- go to Account/Receive and show address on Trezor
- connect via USB while address is displayed

Expected result: GetAddress workflow should not be interrupted

  

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/connect-device-model-descriptor&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/connect-device-model-descriptor&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/connect-device-model-descriptor&lookback=7)

### CODE REVIEW

File: packages/device-utils/src/deviceModelInternalUtils.ts [hunk 1]
```diff
@@ -9,3 +9,46 @@ export const getNarrowedDeviceModelInternal = <T extends DeviceModelInternal>(
...
+            case 'Trezor Safe 5':
+                return DeviceModelInternal.T3T1;
+            case 'Trezor Safe 7':
+                return DeviceModelInternal.T3W1;
+            default:
+                return DeviceModelInternal.UNKNOWN;
+        }
+    }
+
+    return DeviceModelInternal.UNKNOWN;
```
Comment (szymonlesisz) [inline packages/device-utils/src/deviceModelInternalUtils.ts]: unknown or undefined?

File: packages/device-utils/src/deviceModelInternalUtils.ts [hunk 2]
```diff
@@ -9,3 +9,46 @@ export const getNarrowedDeviceModelInternal = <T extends DeviceModelInternal>(
...
+    if (device.deviceVersionMajor === 1) {
+        return DeviceModelInternal.T1B1;
+    }
+
+    if (device.deviceVersionMajor === 2) {
+        switch (device.productName) {
+            case 'TREZOR':
+                return DeviceModelInternal.T2T1;
+            case 'Trezor Safe 3':
+                return DeviceModelInternal.T3B1; // TODO: could be T2B1 as well?, should be UNKNOWN?
```
Comment (szymonlesisz) [inline packages/device-utils/src/deviceModelInternalUtils.ts]: this

File: packages/transport/src/api/usb.ts [hunk 3]
```diff
@@ -1,3 +1,4 @@
+import { getUSBDeviceModelInternal } from '@trezor/device-utils';
```
Comment (martykan) [inline packages/transport/src/api/usb.ts]: Just a detail, but `@trezor/device-utils` should be added to `@trezor/transport` dependencies in package.json

File: packages/react-native-usb/src/index.ts [hunk 4]
```diff
@@ -94,7 +94,7 @@ const createWebUSBDevice = (device: NativeDevice): WebUSBDevice => ({
     usbVersionMajor: 2,
     usbVersionMinor: 0,
     usbVersionSubminor: 0,
-    deviceVersionMajor: 1,
+    deviceVersionMajor: 1, // TODO
```
Comment (martykan) [inline packages/react-native-usb/src/index.ts]: Maybe it would be better to hardcode `deviceVersionMajor: 2` for now? 
Since the way we use it is relevant to TS7

File: packages/device-utils/src/deviceModelInternalUtils.ts (hunk 2 above)
Comment (martykan) [reply packages/device-utils/src/deviceModelInternalUtils.ts]: I guess for our current purposes it doesn't really matter right?

**Review by martykan — COMMENTED** [review]
Works pretty well in most cases. 
It's not directly related to your fix, but with FW install I'm stuck in `rebooting` state if I'm connected over USB. 
It seems that Suite doesn't reconnect to Bluetooth because of [this condition](https://github.com/trezor/trezor-suite/blob/5378585ded10c7f7d7a458502c7ba0e051142efd/packages/suite/src/actions/bluetooth/initBluetoothThunk.ts#L83)

Screenshot 2026-01-26 at 11 06 53

File: packages/transport/src/api/usb.ts (hunk 3 above)
Comment (szymonlesisz) [reply packages/transport/src/api/usb.ts]: i've dropped this dependency in favor of new utility in `@trezor/transport` package

File: packages/react-native-usb/src/index.ts (hunk 4 above)
Comment (szymonlesisz) [reply packages/react-native-usb/src/index.ts]: remove, currently irrelevant. i think mobile doesnt have multitransport support

**Review by martykan — APPROVED** [review]
