### PR TITLE
Display all tokens in a multitoken tx

### LINKED ISSUE #8036: Tx with ERC-1155 shows only first NFT available, without # of units
**Describe the bug**

Right now, we show only first ERC-1155 within a transaction without units.
https://github.com/trezor/trezor-suite/blob/develop/suite-common/wallet-utils/src/transactionUtils.ts#L413
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/components/suite/FormattedNftAmount.tsx#L48

**Info:**

-   Suite Version: 23.4.0

**How to reproduce**
https://ethereum.org/en/developers/docs/standards/tokens/erc-1155/

Example tx:
https://etherscan.io/tx/0xa3074c72e058a29f077f5c478e86dd600623c562939e5ce0a3a3cb65b7a4a706
https://eth1.trezor.io/api/v2/tx/0xa3074c72e058a29f077f5c478e86dd600623c562939e5ce0a3a3cb65b7a4a706

Example address with NFTs:
https://eth1.trezor.io/address/0x958B69371e5750Ca8e6436f122322d68b395f781
https://etherscan.io/token/0x05baf9f1961e1ed1dac222a1f97c479441b31b34?a=81#inventory

**Expected behavior**
- shows all NFTs of tx
- shows value of NFT

Screenshot 2023-04-07 at 21 51 54

### PR DESCRIPTION
**Pull request by enjojoy**
## Description

Fixed display of multitoken values for ERC-1155

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/8036

## Screenshots:

Before: 
image
After:
image

Before:
image
After:
image

Before:
image
After:
image

Before:
image
After:
image

### CODE REVIEW

**Comment by enjojoy** [comment]
@qa  there are ERC-1155 transactions with multitokens on academic seed "v" passphrase on polygon and Ethereum Sepolia

File: packages/suite/src/components/FormattedMultitokenAmount.tsx [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+    display: flex;
+    font-size: ${variables.FONT_SIZE.TINY};
+    line-height: initial;
+    align-items: center;
+`;
+
+export interface FormattedMultitokenAmountProps {
+    tokens: TokenTransfer['multiTokenValues'];
+    signValue?: SignValue;
+    className?: string;
```
Comment (jvaclavik) [inline packages/suite/src/components/FormattedMultitokenAmount.tsx]: Can we do it wihtout className? I think you don't use it anywhere

File: packages/suite/src/components/FormattedMultitokenAmount.tsx [hunk 2]
```diff
@@ -0,0 +1,74 @@
+import styled from 'styled-components';
+
+import { SignValue } from '@suite-common/suite-types';
+import { TokenTransfer } from '@trezor/connect';
+import { Column, Row, variables } from '@trezor/components';
+
+import { HiddenPlaceholder, Sign, TrezorLink } from 'src/components/suite';
+import { useSelector } from 'src/hooks/suite';
+
+const Id = styled.div`
```
Comment (jvaclavik) [inline packages/suite/src/components/FormattedMultitokenAmount.tsx]: Couldn't we use `Text` component with related props? 🤔

Comment (jvaclavik) [inline packages/suite/src/components/FormattedMultitokenAmount.tsx]: Couldn't we use `Text` component with related props? 🤔

File: packages/suite/src/components/FormattedMultitokenAmount.tsx [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+`;
+
+const StyledTrezorLink = styled(TrezorLink)`
+    color: ${({ theme }) => theme.legacy.TYPE_GREEN};
+    text-decoration: underline;
+    display: flex;
+    font-size: ${variables.FONT_SIZE.TINY};
+    line-height: initial;
+    align-items: center;
+`;
```
Comment (jvaclavik) [inline packages/suite/src/components/FormattedMultitokenAmount.tsx]: I'm not fan of duplicating this component again. Also we should use new non-legacy tokens (font and color). And maybe we could use wrapper not to override TrezorLink at all.

File: packages/suite/src/components/wallet/getAmountComponent.tsx [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    withLink?: boolean;
+    contract?: string;
+};
+
+export const getAmountComponent = ({
+    transfer,
+    useStyled = false,
+    withLink = false,
+    contract,
+}: GetAmountComponentProps) => {
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/getAmountComponent.tsx]: Logic in this function seems to me a bit complicated. Couldn't we improve it somehow?

**Review by tomasklim — CHANGES_REQUESTED** [review]
Why `+` and `-` disappeared? 
Screenshot 2024-11-22 at 20 50 51

Why is `Id:` also underlined? 
Screenshot 2024-11-22 at 20 51 01

File: packages/suite/src/components/FormattedMultitokenAmount.tsx [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+                        <Row>
+                            {SignValueComponent}
+                            {token.value}x
+                        </Row>
+                        <Row gap={4}>
+                            {withLink && network?.networkType === 'ethereum' && contract ? (
+                                <StyledTrezorLink
+                                    href={`${network?.explorer.nft}/${contract}/${token.id}`}
+                                >
+                                    ID:
```
Comment (tomasklim) [inline packages/suite/src/components/FormattedMultitokenAmount.tsx]: I would make `ID` translatable even though it will probably be same in all languages, it will be easier to change it in case somebody decides so

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 6]
```diff
@@ -476,7 +476,9 @@ export const getTxOperation = (
 };
 
 export const isNftTokenTransfer = (transfer: TokenTransfer) =>
-    ['ERC1155', 'ERC721'].includes(transfer.standard || '');
+    ['ERC1155', 'ERC721'].includes(transfer?.standard || '');
+
+export const isMultitoken = (transfer: TokenTransfer) => !!transfer?.multiTokenValues;
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts]:
```suggestion
export const IsNftMultitokenTransfer = (transfer: TokenTransfer) => !!transfer?.multiTokenValues;
```

and btw it return `true` when multitokens array is defined but empty

File: packages/suite/src/components/FormattedMultitokenAmount.tsx [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+}: FormattedMultitokenAmountProps) => {
+    const SignValueComponent = signValue ? <Sign value={signValue} /> : null;
+    const { selectedAccount } = useSelector(state => state.wallet);
+    const { network } = selectedAccount;
+
+    return (
+        <HiddenPlaceholder>
+            <Column className={className} alignItems="flex-start">
+                {tokens?.map(token => (
+                    <Row key={`${token.id}-${token.value}`} gap={4}>
```
Comment (tomasklim) [inline packages/suite/src/components/FormattedMultitokenAmount.tsx]: does `token.value` make sense in the `key`?

File: packages/suite/src/components/FormattedMultitokenAmount.tsx [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+                        <Row>
+                            {SignValueComponent}
+                            {token.value}x
```
Comment (tomasklim) [inline packages/suite/src/components/FormattedMultitokenAmount.tsx]: We use `+` and `-` icons for positive, negative values. Maybe it would make sense to have it also for `x`? @jvaclavik @adamhavel 
Screenshot 2024-11-23 at 9 59 44

and btw etherscan has `x` before the amount
Screenshot 2024-11-23 at 10 00 10

File: packages/suite/src/components/FormattedMultitokenAmount.tsx (hunk 5 above)
Comment (tomasklim) [reply packages/suite/src/components/FormattedMultitokenAmount.tsx]: etherscan btw uses Token ID, maybe that is better

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Comment by tomasklim** [comment]
Btw for nft names, it would be great to use `BlurUrls` component. We should implement it into `FormattedNftAmount`. I agree with @jvaclavik that we should not duplicate this component and we should not create `FormattedMultitokenAmount`

File: packages/suite/src/components/FormattedMultitokenAmount.tsx (hunk 5 above)
Comment (enjojoy) [reply packages/suite/src/components/FormattedMultitokenAmount.tsx]: Can be Token ID, then I will rename it for every NFT case, not only multitoken

File: packages/suite/src/components/FormattedMultitokenAmount.tsx (hunk 1 above)
Comment (enjojoy) [reply packages/suite/src/components/FormattedMultitokenAmount.tsx]: yes, removed

File: packages/suite/src/components/FormattedMultitokenAmount.tsx (hunk 2 above)
Comment (enjojoy) [reply packages/suite/src/components/FormattedMultitokenAmount.tsx]: Yes, it's gone

File: packages/suite/src/components/FormattedMultitokenAmount.tsx (hunk 3 above)
Comment (enjojoy) [reply packages/suite/src/components/FormattedMultitokenAmount.tsx]: I deleted this component and used the non-legacy variables where needed

File: packages/suite/src/components/wallet/getAmountComponent.tsx (hunk 4 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/getAmountComponent.tsx]: Now it's much simpler without all the styled components

File: suite-common/wallet-utils/src/transactionUtils.ts (hunk 6 above)
Comment (enjojoy) [reply suite-common/wallet-utils/src/transactionUtils.ts]: I'm not sure it's a problem in this case, can this even be a case? I mean can a transfer have multitoken value defined but have transaction amount outside of it? I'm not so sure, will have to test it out

File: packages/suite/src/components/FormattedMultitokenAmount.tsx (hunk 7 above)
Comment (enjojoy) [reply packages/suite/src/components/FormattedMultitokenAmount.tsx]: yeah I used an index instead, apparently id can be same in some cases

**Comment by enjojoy** [comment]
It would be nice to remake GraphTooltipAccount component, it's full of custom styles, I was playing around with it but decided to leave it for later to not make this PR too big

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx [hunk 9]
```diff
@@ -97,23 +95,25 @@ export const FormattedCryptoAmount = ({
     }
 
     const content = (
-        <Container className={className}>
-            {!!signValue && <Sign value={signValue} />}
-            <Value data-testid={dataTest}>
-                <RedactNumericalValue value={formattedValue} />
-            </Value>
+        <Row width="100%" flexWrap="nowrap" justifyContent={justifyContent} gap={4}>
```
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/FormattedCryptoAmount.tsx]: No need for flexWrap, use spacings for gap.

File: packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx [hunk 10]
```diff
@@ -254,7 +243,7 @@ export const TransactionItem = memo(
                     </TxTypeIconWrapper>
 
                     <Content>
-                        <Description>
+                        <Row justifyContent="space-between" overflow="hidden" flexWrap="nowrap">
```
Comment (seibei-iguchi) [inline packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx]: No need for flexWrap

**Comment by seibei-iguchi** [comment]
I've made lot of changes to the IODetails component since you made this branch, so you will have to do a painful rebase - sorry about that!

**Comment by enjojoy** [comment]
> I've made lot of changes to the IODetails component since you made this branch, so you will have to do a painful rebase - sorry about that!

It's oki, thank you for letting me know

File: packages/suite/src/components/suite/CoinBalance.tsx [hunk 11]
```diff
@@ -4,13 +4,15 @@ import { FormattedCryptoAmount } from 'src/components/suite';
 interface CoinBalanceProps {
     value: string;
     symbol: Account['symbol'] | (string & {});
+    justifyContent?: 'flex-end' | 'flex-start';
```
Comment (tomasklim) [inline packages/suite/src/components/suite/CoinBalance.tsx]: `FlexJustifyContent` would maybe make more sense here? but maybe not, you can just pick those from this type

Comment (enjojoy) [reply packages/suite/src/components/suite/CoinBalance.tsx]: Well I don't need other options in this component

Comment (tomasklim) [reply packages/suite/src/components/suite/CoinBalance.tsx]: so you can pick those two from `FlexJustifyContent`?

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx [hunk 12]
```diff
@@ -97,23 +97,25 @@ export const FormattedCryptoAmount = ({
...
+                {!!signValue && <Sign value={signValue} />}
+                <Value data-testid={dataTest}>
+                    <RedactNumericalValue value={formattedValue} />
+                </Value>
+            </Row>
             {formattedSymbol && (
                 <>
                     {' '}
-                    <BlurUrls text={formattedSymbol} />
+                    <BlurUrls text={formattedSymbol} />{' '}
```
Comment (tomasklim) [inline packages/suite/src/components/suite/FormattedCryptoAmount.tsx]: should the {' '} be here?

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx [hunk 13]
```diff
@@ -35,6 +34,7 @@ export interface FormattedCryptoAmountProps {
     disableHiddenPlaceholder?: boolean;
     isRawString?: boolean;
     'data-testid'?: string;
+    justifyContent?: 'flex-end' | 'flex-start';
     className?: string;
```
Comment (tomasklim) [inline packages/suite/src/components/suite/FormattedCryptoAmount.tsx]: not used anymore

File: packages/suite/src/components/suite/CoinBalance.tsx (hunk 11 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/CoinBalance.tsx]: sure

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx [hunk 14]
```diff
@@ -45,8 +45,8 @@ export const FormattedCryptoAmount = ({
     signValue,
     disableHiddenPlaceholder,
     isRawString,
+    justifyContent = 'flex-end',
     'data-testid': dataTest,
-    className,
```
Comment (tomasklim) [inline packages/suite/src/components/suite/FormattedCryptoAmount.tsx:49]: all the occurences of `styled(FormattedCryptoAmount)` will stop working

File: suite-common/wallet-utils/src/transactionUtils.ts [hunk 15]
```diff
@@ -477,7 +477,9 @@ export const getTxOperation = (
 };
 
 export const isNftTokenTransfer = (transfer: TokenTransfer) =>
-    ['ERC1155', 'ERC721'].includes(transfer.standard || '');
+    ['ERC1155', 'ERC721'].includes(transfer?.standard || '');
+
+export const isNftMultitokenTransfer = (transfer: TokenTransfer) => !!transfer?.multiTokenValues;
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/transactionUtils.ts]: are the `?` needed?

File: packages/suite/src/support/messages.ts [hunk 16]
```diff
@@ -5688,6 +5692,10 @@ const messages = defineMessagesWithTypeCheck({
         defaultMessage: '{amount} selected',
         description: 'Number of list items selected',
     },
+    TR_OF: {
+        id: 'TR_OF',
+        defaultMessage: 'of',
+    },
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: We do not do that, can you add whole structure here?

It should be something like `{sign} {tokenValue}x ID token {id}: of {name}`, right? (it is just wild guess)

File: packages/suite/src/components/wallet/getAmountComponent.tsx [hunk 17]
```diff
@@ -0,0 +1,46 @@
...
+type GetAmountComponentProps = {
+    transfer: TokenTransfer;
+    useStyled?: boolean;
+    withLink?: boolean;
+    withSign?: boolean;
+    contract?: string;
+    alignMultitoken?: 'flex-end' | 'flex-start';
+};
+
+export const getAmountComponent = ({
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/getAmountComponent.tsx]: we discussed yesterday that it should not be `get...`

File: packages/suite/src/components/wallet/getAmountComponent.tsx [hunk 18]
```diff
@@ -0,0 +1,46 @@
+import { isNftTokenTransfer, formatAmount, getTxOperation } from '@suite-common/wallet-utils';
+import { TokenTransfer } from '@trezor/connect';
+
+import { FormattedNftAmount } from 'src/components/suite/FormattedNftAmount';
+import { FormattedCryptoAmount } from 'src/components/suite/FormattedCryptoAmount';
+
+type GetAmountComponentProps = {
+    transfer: TokenTransfer;
+    useStyled?: boolean;
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/getAmountComponent.tsx]: where is this used?

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 13 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx]: Looks like it was updated 8 hours ago lol, oki will remove that

File: packages/suite/src/components/wallet/TransactionItem/CommonComponents.tsx [hunk 19]
```diff
@@ -40,44 +41,19 @@ export const Content = styled.div`
...
-`;
-
-export const StyledFormattedCryptoAmount = styled(FormattedCryptoAmount)`
-    ${amountStyle}
-`;
-
-export const StyledFormattedNftAmount = styled(FormattedNftAmount)`
-    ${amountStyle}
-`;
+export const Id = ({ id }: { id?: string }) => {
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/TransactionItem/CommonComponents.tsx]: Does it belong here?

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 14 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx:49]: 😳

File: packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx [hunk 20]
```diff
@@ -79,9 +82,11 @@ export const TransactionHeader = ({ transaction, isPending }: TransactionHeaderP
     const symbol = getTxHeaderSymbol(transaction)?.toUpperCase();
 
     return (
-        <Translation
-            id={getTransactionMessageId({ transaction, isPending })}
-            values={{ symbol, multiple: isMultiTokenTransaction }}
+        <BlurUrls
+            text={translationString(getTransactionMessageId({ transaction, isPending }), {
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx:86]: why `translationString` and not `Translation` component?

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx [hunk 21]
```diff
@@ -200,8 +194,7 @@ export const GraphTooltipBase = (props: GraphTooltipBaseProps) => {
                     {props.balance && (
                         <Row>
                             <Value>
-                                <Sign $color="transparent">+</Sign>
-                                {props.balance}
+                                <Row $noBottomMargin>{props.balance}</Row>
```
Comment (tomasklim) [inline packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx:197]: Screenshot 2024-11-27 at 16 20 30
🤯

File: suite-common/wallet-utils/src/transactionUtils.ts (hunk 15 above)
Comment (enjojoy) [reply suite-common/wallet-utils/src/transactionUtils.ts]: nope

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx (hunk 21 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx:197]: Is there some request to remove those signs?

File: packages/suite/src/support/messages.ts (hunk 16 above)
Comment (enjojoy) [reply packages/suite/src/support/messages.ts]: I wouldn't add a sign there since it's a component, but I agree about the rest of the text

Comment (enjojoy) [reply packages/suite/src/support/messages.ts]: https://arc.net/l/quote/sbhhastt

File: suite-common/wallet-utils/src/transactionUtils.ts (hunk 15 above)
Comment (tomasklim) [reply suite-common/wallet-utils/src/transactionUtils.ts]: but it is still there...

File: packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx (hunk 20 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx:86]: Because BlurUrls accepts a string not a component or child 
image

File: packages/suite/src/components/wallet/getAmountComponent.tsx (hunk 18 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/getAmountComponent.tsx]: It's not there anymore

File: packages/suite/src/components/wallet/getAmountComponent.tsx (hunk 17 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/getAmountComponent.tsx]: Fixed

File: packages/suite/src/components/wallet/TransactionItem/CommonComponents.tsx (hunk 19 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/CommonComponents.tsx]: No, since it was used only in one component I moved it there https://github.com/trezor/trezor-suite/pull/15457/commits/8e054ee8acbd20b773f34b3e0b4134c64b39f7c0

File: packages/suite/src/support/messages.ts (hunk 16 above)
Comment (enjojoy) [reply packages/suite/src/support/messages.ts]: This is fixed https://arc.net/l/quote/capnkscz

File: suite-common/wallet-utils/src/transactionUtils.ts (hunk 15 above)
Comment (enjojoy) [reply suite-common/wallet-utils/src/transactionUtils.ts]: weird, I was pretty sure I pushed it, here it is https://github.com/trezor/trezor-suite/pull/15457/commits/5a7283911c014c77fb8ebe47f29fe43f80752792

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 14 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx:49]: It's back

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 12 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx]: Probably no need

File: packages/suite/src/components/suite/CoinBalance.tsx (hunk 11 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/CoinBalance.tsx]: This is not there anymore

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 22]
```diff
@@ -1,89 +1,127 @@
...
-                    </StyledTrezorLink>
+                    <TrezorLink
+                        href={explorerUrl}
+                        color={theme.textSecondaryHighlight}
+                        variant="underline"
+                        typographyStyle="label"
+                        gap="zero"
+                    >
+                        <Id id={id} />
+                        &nbsp; {symbolComponent}
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: This seems to me weird. You set gap to zero and then you use `&nbsp;` probably for having a gap. Why?

Btw I noticed that you use &nbsp; 5x in this PR, not sure if it's not overused.

File: packages/components/src/components/typography/Link/Link.tsx [hunk 23]
```diff
@@ -99,6 +105,8 @@ const Link = ({
             $variant={variant}
             className={className}
             {...textProps}
+            $color={color}
+            $gap={gap}
```
Comment (jvaclavik) [inline packages/components/src/components/typography/Link/Link.tsx]: I think it doesn't belong here, couldn't you use Row inside of the link?

something like:

```
<Link>
  <Row as="span" gap={spacings.xs}>
    <A/>
    <B/>
  </Row>
</Link>

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx [hunk 24]
```diff
@@ -97,23 +95,25 @@ export const FormattedCryptoAmount = ({
...
                     <BlurUrls text={formattedSymbol} />
                 </>
             )}
-        </Container>
+        </Row>
     );
 
     if (disableHiddenPlaceholder) {
-        return content;
+        return <>{content}</>;
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/FormattedCryptoAmount.tsx]: Why do you need it?

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 25]
```diff
@@ -1,89 +1,127 @@
-import styled from 'styled-components';
+import { useTheme } from 'styled-components';
 
 import { SignValue } from '@suite-common/suite-types';
-import { getNftTokenId } from '@suite-common/wallet-utils';
+import { getNftTokenId, isNftMultitokenTransfer } from '@suite-common/wallet-utils';
 import { TokenTransfer } from '@trezor/connect';
-import { variables } from '@trezor/components';
+import { Column, Flex, Row, Text } from '@trezor/components';
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: Please do not use `Flex`, but `Row` or `Column` 🙏

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 26]
```diff
@@ -1,89 +1,127 @@
...
-
-const Id = styled.div`
-    white-space: nowrap;
-    overflow: hidden;
-    text-overflow: ellipsis;
-    max-width: 145px;
-`;
+export const Id = ({ id }: { id?: string }) => {
+    return id ? (
+        <Text maxWidth="145px" ellipsisLineCount={1} textWrap="nowrap">
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: nitpick: it's just my personal preference but if we use px we can use number.

Like:
```
maxWidth={145}
```

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 27]
```diff
@@ -1,89 +1,127 @@
...
+                                        })}
+                                    />
+                                ) : (
+                                    <>
+                                        {token.value}x&nbsp;
+                                        <Translation id="TR_TOKEN_ID" />:
+                                    </>
+                                )}
+                            </Row>
+                            <Row>
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: Do you need Row here? There is only one element

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx [hunk 28]
```diff
@@ -26,14 +22,16 @@ const formatAmount = (
...
-        <>
+        <Row>
             {amount && (
-                <StyledCryptoAmount
-                    value={amount}
-                    symbol={symbol}
-                    signValue={sign}
-                    disableHiddenPlaceholder
-                />
+                <Row margin={{ right: 4 }}>
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx]: please use `spacings`

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 29]
```diff
@@ -1,89 +1,127 @@
...
+                        typographyStyle="label"
+                        gap="zero"
+                    >
+                        <Id id={id} />
+                        &nbsp; {symbolComponent}
+                    </TrezorLink>
                 ) : (
-                    <NoLink>
-                        {idComponent}
+                    <Row gap={4}>
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: please use `spacings.xxs`

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx (hunk 21 above)
Comment (jvaclavik) [inline packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx]: I suggest to use `Row` component from DS here

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx [hunk 30]
```diff
@@ -65,10 +65,13 @@ const IOItem = ({ anonymitySet, address, symbol, amount, isPhishingTransaction }
                     {anonymity && <UtxoAnonymity anonymity={anonymity} />}
                     {amount &&
                         (typeof amount === 'string' && symbol ? (
-                            <FormattedCryptoAmount
-                                value={formatNetworkAmount(amount, symbol)}
-                                symbol={symbol}
-                            />
+                            <Column>
+                                <br />
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx]: why not to use margin top or something else instead of `<br />`?

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx [hunk 31]
```diff
@@ -211,18 +214,37 @@ const EthereumSpecificBalanceDetailsRow = ({
...
+                                    ] as IODetails[]
+                                }
+                                outputs={
+                                    [
+                                        {
+                                            addresses: [transfer.to],
+                                            value: value as ReactNode,
+                                        },
+                                    ] as IODetails[]
+                                }
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx]: nitpick: I would suggest extract these arrays to consts above. It's easier to read

File: packages/suite/src/components/wallet/AmountComponent.tsx [hunk 32]
```diff
@@ -0,0 +1,46 @@
+import { isNftTokenTransfer, formatAmount, getTxOperation } from '@suite-common/wallet-utils';
+import { TokenTransfer } from '@trezor/connect';
+
+import { FormattedNftAmount } from 'src/components/suite/FormattedNftAmount';
+import { FormattedCryptoAmount } from 'src/components/suite/FormattedCryptoAmount';
+
+type AmountComponentProps = {
+    transfer: TokenTransfer;
+    useStyled?: boolean;
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/AmountComponent.tsx]: What does this mean? I don't understand the naming and think you don't use it at all.

Comment (jvaclavik) [reply packages/suite/src/components/wallet/AmountComponent.tsx]: And the same for contract - it's also not used

File: packages/suite/src/components/wallet/AmountComponent.tsx [hunk 33]
```diff
@@ -0,0 +1,46 @@
...
+        return (
+            <FormattedCryptoAmount
+                value={formatAmount(transfer.amount, transfer.decimals)}
+                symbol={transfer.symbol}
+                signValue={operation}
+            />
+        );
+    }
+
+    return <>{formatAmount(transfer.amount, transfer.decimals)}</>;
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/AmountComponent.tsx]: Can you do it without the fragment?

File: packages/suite/src/components/wallet/TransactionItem/CoinjoinBatchItem.tsx [hunk 34]
```diff
@@ -141,11 +133,11 @@ export const CoinjoinBatchItem = ({
                                 signValue={amount}
                             />
                         </Description>
-                        <NextRow>
+                        <Row flex="1" alignItems="flex-start" margin={{ bottom: spacings.xxs }}>
                             <TimestampWrapper>
                                 <TransactionTimestamp transaction={lastTx} />
                             </TimestampWrapper>
-                            <TargetsWrapper>
+                            <Column flex="1" overflow="hidden">
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/TransactionItem/CoinjoinBatchItem.tsx]: Please use `Box` component here

File: packages/suite/src/components/wallet/TransactionItem/TransactionHeading.tsx [hunk 35]
```diff
@@ -168,12 +163,12 @@ export const TransactionHeading = ({
                         />
                     )}
                     <BlurWrapper $isBlurred={isPhishingTransaction}>
-                        <HeaderWrapper>
+                        <Row gap={spacings.xxs}>
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/TransactionItem/TransactionHeading.tsx:166]: Please use `Box` here. Row is considered for multiple children, and Box is universal building block for cases like this one.

File: packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx [hunk 36]
```diff
@@ -244,7 +233,7 @@ export const TransactionItem = memo(
                 $isPhishingTransaction={isPhishingTransaction}
                 className={className}
             >
-                <Body>
+                <Flex width="100%">
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx]: Please use `Row` component

File: packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx [hunk 37]
```diff
@@ -254,7 +243,7 @@ export const TransactionItem = memo(
                     </TxTypeIconWrapper>
 
                     <Content>
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx]: It would be nice to separate some of the components in this return to make it more readable. But I understand it was here before, so it's up to you.

File: packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx [hunk 38]
```diff
@@ -1,6 +1,7 @@
 import styled, { css } from 'styled-components';
 
 export const BlurWrapper = styled.span<{ $isBlurred: boolean }>`
+    width: 100%;
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx]: does it do something with non-block element like `span`?

File: packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx (hunk 37 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx]: I will leave it as is for now, I need this PR to be merged to work on NFT section that is higher priority

File: packages/components/src/components/typography/Link/Link.tsx [hunk 39]
```diff
@@ -22,17 +22,19 @@ type AllowedLinkTextProps = Pick<TextPropsCommon, (typeof allowedLinkTextProps)[
...
     text-decoration: none;
     cursor: pointer;
-    color: ${({ theme }) => theme.textDefault};
+    color: ${({ $color, theme }) => $color || theme.textDefault};
     font-weight: 500;
     display: inline-flex;
     align-items: center;
 
-    gap: ${spacingsPx.xxs};
+    gap: ${({ $gap }) => ($gap ? spacingsPx[$gap] : spacingsPx.xxs)};
```
Comment (seibei-iguchi) [inline packages/components/src/components/typography/Link/Link.tsx]: I think default should be set on the gap prop, not in the css, and it should be typed to SpacingValues.

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 26 above)
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: Use number for maxWidth

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 40]
```diff
@@ -1,89 +1,127 @@
...
     const { network } = selectedAccount;
     const explorerUrl =
         network?.networkType === 'ethereum'
             ? `${network?.explorer.nft}/${transfer.contract}/${id}`
             : undefined;
 
-    const idComponent = <Id>{id}</Id>;
-    const symbolComponent = transfer.symbol ? <Symbol>&nbsp;{transfer.symbol}</Symbol> : null;
+    const symbolComponent = transfer.symbol ? (
+        <Text maxWidth="120px" ellipsisLineCount={1} textWrap="nowrap">
```
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: Use number for maxWidth. The nowrap is, I think, redundant, it is already set by the ellipsis prop

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 41]
```diff
@@ -1,89 +1,127 @@
...
+    const isMultitoken = isNftMultitokenTransfer(transfer);
+
+    if (isMultitoken) {
+        const tokens = transfer.multiTokenValues;
+
+        return (
+            <HiddenPlaceholder>
+                <Column alignItems={alignMultitoken}>
+                    {tokens?.map((token, index) => (
+                        <Row key={`${token.id}-${index}`} gap={4}>
```
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: Use spacings for gap

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 29 above)
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: Use spacings

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx (hunk 28 above)
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx]: Use spacings

**Review by seibei-iguchi — CHANGES_REQUESTED** [review]

File: packages/suite/src/support/messages.ts [hunk 42]
```diff
@@ -5696,6 +5700,10 @@ const messages = defineMessagesWithTypeCheck({
         defaultMessage: '{amount} selected',
         description: 'Number of list items selected',
     },
+    TR_COLLECTION_NAME_OF_TOKEN_ID: {
+        id: 'TR_COLLECTION_NAME_OF_TOKEN_ID',
+        defaultMessage: '{tokenValue}x {collectionName} of Token ID: ',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: Can we add also id here?

File: packages/suite/src/support/messages.ts [hunk 43]
```diff
@@ -3314,6 +3314,10 @@ const messages = defineMessagesWithTypeCheck({
         defaultMessage: 'Details',
         id: 'TR_TRANSACTION_DETAILS',
     },
+    TR_TOKEN_ID: {
+        defaultMessage: 'Token ID',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: the `TR_COLLECTION_NAME_OF_TOKEN_ID` contains `:`. Can we unify it please 🙏

File: packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx (hunk 38 above)
Comment (tomasklim) [reply packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx]: line below there is `display: block;`

File: suite-common/wallet-utils/src/transactionUtils.ts (hunk 6 above)
Comment (tomasklim) [reply suite-common/wallet-utils/src/transactionUtils.ts]: I have no idea but we should be ready for weird cases :D

File: packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx (hunk 20 above)
Comment (tomasklim) [reply packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx:86]: ah oki

File: suite-common/wallet-utils/src/transactionUtils.ts (hunk 6 above)
Comment (enjojoy) [reply suite-common/wallet-utils/src/transactionUtils.ts]: I added a check for length there just in case, I don't think it's possible, maybe only in a very weird nonsense contract

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 22 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: In this case it has to be there, to preserve the underline between these components, otherwise it's being removed and there's a weird gap that is not underlined, even tho the link is the same

I didn't come up with a less hacky solution 😅

File: packages/components/src/components/typography/Link/Link.tsx (hunk 23 above)
Comment (enjojoy) [reply packages/components/src/components/typography/Link/Link.tsx]: Again it's here because I must remove the gap and add a space to preserve the underline

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 24 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx]: No need, it's removed now

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 25 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: Used

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 26 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: Done

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 27 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: Removed

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx (hunk 28 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx]: Used

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 29 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: Used

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx (hunk 21 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipBase.tsx]: used

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx (hunk 30 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx]: Sure, used a margin

File: packages/suite/src/components/wallet/AmountComponent.tsx (hunk 32 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/AmountComponent.tsx]: Yes, it was forgotten there, will remove it now, thanks

File: packages/suite/src/components/wallet/AmountComponent.tsx (hunk 33 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/AmountComponent.tsx]: removed

File: packages/suite/src/components/wallet/TransactionItem/CoinjoinBatchItem.tsx (hunk 34 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/CoinjoinBatchItem.tsx]: used

File: packages/suite/src/components/wallet/TransactionItem/TransactionHeading.tsx (hunk 35 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/TransactionHeading.tsx:166]: In this case there can be more children depending on a condition, but I'll note that for other cases

File: packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx (hunk 36 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx]: Used

File: packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx (hunk 38 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx]: Yes, I added that

File: packages/components/src/components/typography/Link/Link.tsx (hunk 39 above)
Comment (enjojoy) [reply packages/components/src/components/typography/Link/Link.tsx]: Thanks, did this

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 26 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: used

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 40 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: yes, you are right, fixed this, thank you

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 41 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: done

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 29 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: done

File: packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx (hunk 28 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipAccount.tsx]: done

File: packages/suite/src/support/messages.ts (hunk 42 above)
Comment (enjojoy) [reply packages/suite/src/support/messages.ts]: No, because I need this to be a string to feed it to BlurUrls  that only accepts strings, and ID must be wrapped into a TrezorLink component, so here I won't use it. I think it's ok like that

File: packages/suite/src/support/messages.ts (hunk 43 above)
Comment (enjojoy) [reply packages/suite/src/support/messages.ts]: yes, unified

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx [hunk 44]
```diff
@@ -97,23 +95,25 @@ export const FormattedCryptoAmount = ({
     }
 
     const content = (
-        <Container className={className}>
-            {!!signValue && <Sign value={signValue} />}
-            <Value data-testid={dataTest}>
-                <RedactNumericalValue value={formattedValue} />
-            </Value>
+        <Row width="100%" gap={spacings.xxs} className={className}>
```
Comment (tomasklim) [inline packages/suite/src/components/suite/FormattedCryptoAmount.tsx:98]: I think it broke this 
Screenshot 2024-11-29 at 17 15 01

File: packages/suite/src/components/wallet/AmountComponent.tsx [hunk 45]
```diff
@@ -0,0 +1,44 @@
...
+    if (withSign) {
+        return (
+            <FormattedCryptoAmount
+                value={formatAmount(transfer.amount, transfer.decimals)}
+                symbol={transfer.symbol}
+                signValue={operation}
+            />
+        );
+    }
+
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/AmountComponent.tsx:46]: It misses symbol without sign, is it intended? 

Screenshot 2024-11-29 at 17 20 57
There should be USDC

Screenshot 2024-11-29 at 17 21 13

File: packages/suite/src/support/messages.ts (hunk 42 above)
Comment (tomasklim) [reply packages/suite/src/support/messages.ts]: Okay, then please remove the space after Token ID: for both strings. I am scared that the translation agency would remove it anyway and it would be broken in some languages

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx [hunk 46]
```diff
@@ -65,10 +65,12 @@ const IOItem = ({ anonymitySet, address, symbol, amount, isPhishingTransaction }
                     {anonymity && <UtxoAnonymity anonymity={anonymity} />}
                     {amount &&
                         (typeof amount === 'string' && symbol ? (
-                            <FormattedCryptoAmount
-                                value={formatNetworkAmount(amount, symbol)}
-                                symbol={symbol}
-                            />
+                            <Column margin={{ top: spacings.md }}>
```
Comment (seibei-iguchi) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx]: Why the margin?

Comment (enjojoy) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx]: Oh I think there was a break before, but I guess with the resent changes it's not there anymore, will remove

Comment (enjojoy) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx]: removed

File: packages/suite/src/components/wallet/AmountComponent.tsx [hunk 47]
```diff
@@ -0,0 +1,44 @@
...
+    transfer,
+    withLink = false,
+    withSign = false,
+    alignMultitoken,
+}: AmountComponentProps): React.ReactNode => {
+    const operation = getTxOperation(transfer.type);
+
+    if (isNftTokenTransfer(transfer)) {
+        return (
+            <FormattedNftAmount
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/AmountComponent.tsx:27]: I am not sure how the hidden placeholder works but for normal amounts, it replaces the amount by XXX, for nfts, it does not do that. Probably it was there before so just create issue in case it is hard to fix
Screenshot 2024-11-29 at 17 35 08

File: packages/suite/src/components/wallet/AmountComponent.tsx [hunk 48]
```diff
@@ -0,0 +1,44 @@
...
+    alignMultitoken?: 'flex-end' | 'flex-start';
+};
+
+export const AmountComponent = ({
+    transfer,
+    withLink = false,
+    withSign = false,
+    alignMultitoken,
+}: AmountComponentProps): React.ReactNode => {
+    const operation = getTxOperation(transfer.type);
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/AmountComponent.tsx:23]: this can be inside the `if (withSign) {` condition

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 49]
```diff
@@ -1,89 +1,127 @@
...
+                        }
+                        color={theme.textSecondaryHighlight}
+                        variant="underline"
+                        typographyStyle="label"
+                        gap={spacings.zero}
+                    >
+                        <Text maxWidth={145} ellipsisLineCount={1}>
+                            {transfer.amount}
+                        </Text>
+                        &nbsp; {symbolComponent}
```
Comment (tomasklim) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: does it still need the space between `&nbsp;` `{symbolComponent}`?

File: packages/suite/src/components/suite/FormattedNftAmount.tsx [hunk 50]
```diff
@@ -1,89 +1,127 @@
...
+                                        <Translation id="TR_TOKEN_ID" />
+                                    </Row>
+                                )}
+                            </Row>
+                            {isWithLink && network?.networkType === 'ethereum' ? (
+                                <TrezorLink
+                                    href={`${network?.explorer.nft}/${transfer.contract}/${token.id}`}
+                                    color={theme.textSecondaryHighlight}
+                                    variant="underline"
+                                    typographyStyle="label"
```
Comment (tomasklim) [inline packages/suite/src/components/suite/FormattedNftAmount.tsx]: It now does not have same font size in review tx modal 
Screenshot 2024-11-29 at 17 48 11

**Review by tomasklim — CHANGES_REQUESTED** [review]
Just minted beautiful nft for qa on eth n.1 😀 for testing

Screenshot 2024-11-29 at 17 49 35

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 44 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx:98]: How? I can't duplicate this. Do you have the recent changed pulled?

File: packages/suite/src/components/wallet/AmountComponent.tsx (hunk 45 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/AmountComponent.tsx:46]: It's not intended, I will rather bring back the way that component worked before

File: packages/suite/src/components/wallet/AmountComponent.tsx (hunk 47 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/AmountComponent.tsx:27]: I will create an issue, now there's only a method to redact a raw string or numebr, but we have a component because of BlurUrls in the name

Comment (enjojoy) [reply packages/suite/src/components/wallet/AmountComponent.tsx:27]: Issue created

File: packages/suite/src/components/wallet/AmountComponent.tsx (hunk 48 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/AmountComponent.tsx:23]: No because it's also used before the condition in if(isNftTokenTransfer(transfer))

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 44 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx:98]: Yes, I am always doing review on latest changes 😀 

https://dev.suite.sldev.cz/suite-web/feat/display-multitoken-tx/web/accounts#/eth/0/normal

qa seed, eth 1, 22th november, 1470px width
Screenshot 2024-12-01 at 15 15 57

File: packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx (hunk 38 above)
Comment (tomasklim) [reply packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx]: What does it do?

File: packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TransactionTarget.tsx [hunk 51]
```diff
@@ -68,15 +70,12 @@ export const TokenTransfer = ({
...
-                isNft ? (
-                    <StyledFormattedNftAmount transfer={transfer} signValue={operation} />
-                ) : (
-                    <StyledFormattedCryptoAmount
-                        value={formatAmount(transfer.amount, transfer.decimals)}
-                        symbol={transfer.symbol}
-                        signValue={operation}
-                    />
-                )
+                <AmountComponent
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TransactionTarget.tsx:73]: Develop:
Screenshot 2024-12-01 at 15 53 01

Your branch:
Screenshot 2024-12-01 at 15 46 16

Check how the address behaves. There was `...` before

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 49 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: I think not needed

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 44 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx:98]: Ok, very interesting, I don't think I've touched that part of the code. Anyway fixed https://github.com/trezor/trezor-suite/pull/15457/commits/72b21d1332ddd817867d1601b8ac47216654e08e

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 49 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: It is needed, without it there will be a space in the underline of the link, as the gap is not considered a normal space and breaks the underline

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 50 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: It's not the same on develop either

image

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 49 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: I am talking about 
```
&nbsp;`HERE`{symbolComponent}
```

Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: Oh yean, that is not needed indeed

File: packages/suite/src/components/suite/FormattedCryptoAmount.tsx (hunk 44 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx:98]: You modified `FormattedCryptoAmount` which is used in the DayHeader so you basically touched it

Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedCryptoAmount.tsx:98]: True

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 50 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: I also noticed that the color of amounts in the tx modal on develop is different, will adjust that

File: packages/components/src/components/typography/Link/Link.tsx (hunk 23 above)
Comment (enjojoy) [reply packages/components/src/components/typography/Link/Link.tsx]: I realized I can do the same thing without modifying gap in the link component
  image

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx (hunk 31 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx]: I actually returned it to the way it was before

File: packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx (hunk 38 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/TransactionItemBlurWrapper.tsx]: now seems like it does nothing, not sure why I added it before as well as width, seems to be ok without it so i removed it

File: packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TransactionTarget.tsx (hunk 51 above)
Comment (enjojoy) [reply packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TransactionTarget.tsx:73]: This should be fixed as I removed the added styles on BlurWrapper

File: packages/suite/src/components/suite/FormattedNftAmount.tsx (hunk 22 above)
Comment (enjojoy) [reply packages/suite/src/components/suite/FormattedNftAmount.tsx]: > I realized I can do the same thing without modifying gap in the link component image

re

**Review by seibei-iguchi — APPROVED** [review]

**Review by tomasklim — APPROVED** [review]
