### PR TITLE
fix(9618): Refactor Paragraph with typography

### LINKED ISSUE #9618: Get rid of typography components in the components package
Begin getting rid of the headings and `Paragraph` in favour of `@trezor/theme/typography`. 
If no props are passed to `P`, should be safe to just substitute for `<p></p>`, if there are some, find the right value of `typography` and interpolate it in the component style, like [here](https://github.com/trezor/trezor-suite/blob/072337a3e237adda7c04fa3aa3bc2763ece0d158/packages/components/src/components/Tooltip/Tooltip.tsx#L38).

### PR DESCRIPTION
**Pull request by jvaclavik**
## Description

Paragraph component is refactored to allow use only type (`TypographyStyle`) prop

## Related Issue

Resolve #9618

### CODE REVIEW

File: packages/components/src/components/typography/Paragraph/Paragraph.tsx [hunk 1]
```diff
@@ -1,72 +1,16 @@
...
-    line-height: ${props => getLineHeight(props.size)};
-    color: ${({ size, theme }) => (size === 'tiny' ? theme.TYPE_LIGHT_GREY : theme.TYPE_DARK_GREY)};
-    padding: 0;
-    font-weight: ${({ weight }) => getWeight(weight)};
-    ${props =>
-        props.textAlign &&
-        css`
-            text-align: ${props.textAlign};
-        `}
+const Paragraph = styled.div<{ type: TypographyStyle }>`
```
Comment (dahaca) [inline packages/components/src/components/typography/Paragraph/Paragraph.tsx:10]:
```suggestion
const Paragraph = styled.p<{ type: TypographyStyle }>`
```

Comment (dahaca) [reply packages/components/src/components/typography/Paragraph/Paragraph.tsx:10]: Perhaps makes sense to make a prop to render `Paragraph` as `span`? I never liked the `P` naming as well, now when I think of it, it's tied to html and it should not be – `Paragraph` is better IMO. `<p>` can be the simply default element for wrapping the text, with an option to make it something else. Thoughts, @komret  @matejkriz ?

File: packages/components/src/components/typography/typography.stories.tsx [hunk 2]
```diff
@@ -12,48 +12,70 @@ storiesOf('Typography/All', module).add(
             </StoryColumn>
             <StoryColumn>
                 <P data-test="paragraph-default">
-                    size="default" <br />
+                    size=undefined <br />
```
Comment (dahaca) [inline packages/components/src/components/typography/typography.stories.tsx]:
```suggestion
                    default
```

File: packages/components/src/components/typography/typography.stories.tsx [hunk 3]
```diff
@@ -12,48 +12,70 @@ storiesOf('Typography/All', module).add(
...
+                    type="titleMedium" <br />
                     Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a ante quis
                     lectus eleifend rutrum. Aenean tincidunt odio vel fermentum ultricies. Sed
                     suscipit interdum eros, eget placerat lorem pulvinar in. Ut elit orci, rhoncus
                     eu porta vel, feugiat vel mi.
                 </P>
-                <P weight="bold" data-test="paragraph-bold">
-                    weight="bold" <br />
+                <P type="titleSmall" data-test="paragraph-titleSmall">
+                    weight="titleSmall" <br />
```
Comment (dahaca) [inline packages/components/src/components/typography/typography.stories.tsx]:
```suggestion
                    type ="titleSmall" <br />
```

File: packages/components/src/components/typography/Paragraph/Paragraph.tsx (hunk 1 above)
Comment (jvaclavik) [reply packages/components/src/components/typography/Paragraph/Paragraph.tsx:10]: Agree that `Paragraph` is better than `P`. Even for searchability in the code this is much better. There can be some use cases when we want to render it as a span, but in this case `<div>` is closer to `<p>` than `<span>`. We can add new prop for it, something like:

```jsx
<Paragraph type="callout" as="span">...</Paragraph>
```

Comment (komret) [reply packages/components/src/components/typography/Paragraph/Paragraph.tsx:10]: While it makes more sense semantically, it shouldn't be a `p` tag IMO because then you run into console warnings of "`div` cannot be child of `p`" when you use a `Tooltip` in the text. `span` applies `display: inline` by default and we don't usually want that, so I'd keep it as a `div`. If we keep it as is, we don't need the option to change element type.

Comment (dahaca) [reply packages/components/src/components/typography/Paragraph/Paragraph.tsx:10]: Yes, agree somewhat regarding tooltips. I am not the biggest fan of text in `divs` but it's true we have those messages popping up from time to time... 😪  Still, for styling text within a paragraph `as="span"` would be beneficial precisely for `display: inline`

**Review by dahaca — APPROVED** [review]
Don't forget to rename to `Paragraph` 🙏
