### PR TITLE
fix(send): clear "compose" errors when switching between FeeLevels

### LINKED ISSUE #2536: Fee level won't update
ezgif-6-063cee6b6d51

### PR DESCRIPTION
**Pull request by szymonlesisz**
fix #2536

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ const getStateFromProps = (props: UseSendFormProps) => {
 // Mounted in top level index: @wallet-views/send
 // return SendContextValues used by SendFormContext in all nested children components of @wallet-views/send
 // SendContextValues is a combination of `react-hook-form` methods with custom callbacks and utils
-// see: ./packages/suite/send/ARCHITECTURE.md
+// see: ./packages/suite/docs/send/ARCHITECTURE.md
```
Comment (keraf) [inline packages/suite/src/hooks/wallet/useSendForm.ts:60]: Unrelated to this change, but we could move the documentation into the root of the project (where all the other docs have been moved).

**Review by keraf — APPROVED** [review]
