### PR TITLE
Fix fiat input in send form

### LINKED ISSUE #10545: Fiat value not properly used when using different currency than the one set in settings
**Describe the bug**
noticed that 
- when i tried to send tx with different than $ value transaction amount is never calculated
- when i change it from $ to different fiat transaction is sent in $
- replicated on multiple computer and with multiple coins

**Steps to reproduce:**
1. Navigate to Send dialogue
2. Try to send tx and use CZK fiat
3. Try to change USD to CZK in Fiat amount

**Info:**
 - Suite version: desktop 24.1.1 (cd3946024cb2233e2e80788ea25784b83daa0a06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.1.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

The problem is, that before we had `symbol`'s fiat rate for all currencies. Currently, we are getting it just for the currency set it settings.

- [chore(suite): move fiatRates from sendForm state](https://github.com/trezor/trezor-suite/pull/10552/commits/5b14699637d95661458ca5b76d986884416cc0e7)
  - this commit ensures that `fiatRates` are always up-to-date
  - another solution could be to use `updateContext` to update `state` on `fiatRates`. However, it sounds stupid
- [chore(suite): rename fiat input name](https://github.com/trezor/trezor-suite/pull/10552/commits/0f69301f53623263cd92493b5110894c86c4b399)
  - just a name refactor, not nice for hotfix, but it is small 
- [fix(suite): fetch fiat rates for locally selected currency in sendform](https://github.com/trezor/trezor-suite/pull/10552/commits/8e8d6b49d7347ad67626ea1905386a6bcc11ea89)
  - it fetches current `symbol`'s fiat rate for locally selected currency 

## Related Issue

Resolves #10545

## Screenshots

https://github.com/trezor/trezor-suite/assets/33235762/2d0b0f32-f194-4a46-b443-15cf8df36e53

### CODE REVIEW

**Comment by komret** [comment]
Have you tried using `updateContext` to change `fiatRates` in `state`?

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx [hunk 1]
```diff
@@ -162,46 +191,22 @@ export const Fiat = ({ output, outputId }: FiatProps) => {
...
-                        shouldSendInSats
-                            ? formatAmount(amountValue, network.decimals)
-                            : amountValue,
+                    dispatch(
+                        updateFiatRatesThunk({
+                            ticker: { symbol: network.symbol as NetworkSymbol },
+                            localCurrency: selected.value as FiatCurrencyCode,
+                            rateType: 'current',
+                            // TODO: would be nice to update rates regularly, what timestamp should i put here?
+                            lastSuccessfulFetchTimestamp: 0,
```
Comment (matejkriz) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]: why not to put Date.now() here?

Comment (tomasklim) [reply packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx]: e2bfe2357385caf2414cbd377a59129e6259efad

**Review by matejkriz — COMMENTED** [review]
I've tried looking for some other solution, but I haven't come up with a better one yet.

Maybe prefetch current fiat conversion rates between fiat currencies to be used here? They are not changing as often as cryptocurrencies rates....

**Comment by tomasklim** [comment]
> Have you tried using `updateContext` to change `fiatRates` in `state`?

That's definitely an option, but I do not see a reason to add `useEffect` and check if `fiatRates` did not change so I removed it from state and it works great now.

**Comment by komret** [comment]
I noticed a change in behaviour - the input adds two fixed decimals (unlike on develop). When you type a two-digit number (such as 10) not fast enough, the cursor jumps to the end and you type "1.000" instead of "10".


https://github.com/trezor/trezor-suite/assets/42465546/497db835-c94f-4c9b-8efd-2fa0daa37824

**Comment by komret** [comment]
There is also a difference between filling the fiat value into clear/dirty form. See the video. On the second attempt, the decimals and crypto amount are missing.

https://github.com/trezor/trezor-suite/assets/42465546/60f03b7f-4773-4edd-a9b7-2adaa92ce437

**Comment by tomasklim** [comment]
@komret sorry fixed, I did one change before pushing and broke everything for you
Screenshot 2024-01-09 at 10 23 04

The `useEffect` has to be called only when user interacts with currency selector

`sats` are irrelevant for fiat
`value` to fiat is handled on different place

**Comment by komret** [comment]
1. Looks like the second reported bug is on production as well, so let's not worry about it now.
2. Probably unrelated, but I noticed some "currencies" like XAU and XAG not working, not even on production. The value does not change when currency changes. Could be disregarded for now.
3.  Unit tests still failing.
4. We should be able to do this without `useEffect`, no? I don't think any value should change when `fiatRates` change, it should only react to change of the currency which can be handled in the `onChange` handler. I tried something and it seems to work. Pls check the commit and feel free to drop it, it is certainly not polished. I used the default `useDispatch` because there was an issue with types.

File: packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx [hunk 2]
```diff
@@ -150,58 +176,37 @@ export const Fiat = ({ output, outputId }: FiatProps) => {
...
+                        rateType: 'current',
+                        lastSuccessfulFetchTimestamp: Date.now() as Timestamp,
+                    }),
+                );
+
+                if (updateFiatRatesResult.meta.requestStatus === 'fulfilled') {
+                    const rate = updateFiatRatesResult.payload as number;
+
+                    recalculateFiat(rate);
+                }
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx:207]: I've added check that it was successfully fetched @komret

**Comment by tomasklim** [comment]
2. `XDR` and `XAG` is working for me
3. not anymore
4. looks good, i like it. I added check to call it only if fetch is successful

**Review by AdamSchinzel — APPROVED** [review]
Works nice

**Review by komret — APPROVED** [review]
