### PR TITLE
fix(suite): app crash on firmware update

### LINKED ISSUE #3757: Link to changelog missing in firmware update modal
**Describe the bug**
Link to changelog says TODO in firmware update modal #3757 
Present in 21.5.1 and 21.6.0 dev master

**Steps to reproduce:**
1. connect T1 device with outdated firmware
2. Click update now
3. Click on `Learn more` for 1.10.0 firmware 

**Info:**
 - Suite version: desktop 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.8.3 regular

**Screenshots:**
image

image

### LINKED ISSUE #3767: Unable to update firmware
**Describe the bug**
After merging [#3629](https://github.com/trezor/trezor-suite/pull/3629), I am unable to update firmware on my device because app crashes. The reason is that revision is not obtained in bootloader mode.

**Steps to reproduce:**
1. Update firmware in settings
2. Connect device in bootloader

**Info:**
 - Suite version: web 21.6.0 (9d8cea584b1f655f0964d80f863b02b1523e2cad)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: model T 2.1.5 Bitcoin only

**Screenshots:**
Screenshot 2021-05-18 at 9 01 02

### PR DESCRIPTION
**Pull request by tomasklim**
After merging [#3629](https://github.com/trezor/trezor-suite/pull/3629):

- app crashed on FW update when device was connected in Bootloader mode
- link to GitHub worked only on TT

### CODE REVIEW

**Comment by tomasklim** [comment]
@szymonlesisz should the revision encoding fix be available in Suite or Connect?

**Comment by tomasklim** [comment]
After discussion with @szymonlesisz, we decided, that we will move the "fix" logic into connect. 
This includes, that Suite will get revision attribute in UTF-8 and will not require to use `Buffer.from("xxxx", "hex").toString()` logic.

I will modify this pull request code and do appropriate changes in connect.

**Comment by goodhoko** [comment]
> I will modify this pull request code and do appropriate changes in connect.

@tomasklim What's the status of this PR? Shall I review it or are you still working on it? .)

**Comment by tomasklim** [comment]
@goodhoko you can review it. It should not crash anymore. However, you cannot check correct revision encoding unless you point Suite to trezor-connect with additional changes. It requires [trezor-connect #819](https://github.com/trezor/connect/pull/819) and  [trezor-connect #820](https://github.com/trezor/connect/pull/820) to be merged and probably a new version of connect to be released. (as it is not only types, but also code, so patch is probably not a good option @szymonlesisz?)

File: packages/suite/src/utils/suite/device.ts [hunk 1]
```diff
@@ -121,8 +121,11 @@ export const getFwVersion = (device: AcquiredDevice) => {
     return `${features.major_version}.${features.minor_version}.${features.patch_version}`;
 };
 
-export const getFwRevision = (device: AcquiredDevice) =>
-    Buffer.from(device.features.revision, 'hex').toString();
+/**
+ * @param {Features} features of device
+ * @returns {string | undefined} revision in ASCII format or undefined if device is in bootloader mode
+ */
+export const getFwRevision = (features: Features) => features.revision;
```
Comment (goodhoko) [inline packages/suite/src/utils/suite/device.ts]: Do we need a function that is barely a getter of a single property? .)

**Review by goodhoko — COMMENTED** [review]
LGTM, except one small remark. .)

**Comment by tsusanka** [comment]
Also closes https://github.com/trezor/trezor-suite/issues/3757.

**Comment by tomasklim** [comment]
This PR fixes crash of app on FW update and updates version of connect.

Problem with inconsistency of revisions was fixed in [connect #820](https://github.com/trezor/connect/pull/820).

This PR also contains changes related to [connect #818](https://github.com/trezor/connect/pull/818).
I had to fix few conditions as all Features attributes are now required (and they were before, only there was wrong typing). So instead of the possibility to be `undefined`, they can be `null`.

File: packages/suite/src/views/settings/device/index.tsx [hunk 2]
```diff
@@ -204,8 +203,8 @@ const Settings = () => {
                                 }}
                                 isDisabled={
```
Comment (tomexx) [inline packages/suite/src/views/settings/device/index.tsx:204]: Just a nitpick - I'd maybe put these kind of conditions into a helper fn - it might become more readable

**Review by tomexx — APPROVED** [review]
lgtm

**Review by keraf — APPROVED** [review]

File: packages/suite/src/views/settings/device/index.tsx (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/views/settings/device/index.tsx:204]: Probably better to leave it for some refactoring task. Conditions like this are all over the project.

File: packages/suite/src/utils/suite/device.ts (hunk 1 above)
Comment (goodhoko) [reply packages/suite/src/utils/suite/device.ts]: thanks. Resolving.
