### PR TITLE
Mobile Trade: Clear amount limits on asset / fiat currency change

### LINKED ISSUE #19172: Mobile Buy: Minimum purchase error persists after switching crypto
**Describe the bug**
When I enter less than the minimum purchase amount for one cryptocurrency in the app and then switch to a different cryptocurrency, the app still remembers and displays the previous minimum amount error from the first one, even though each cryptocurrency has its own minimum.

For example, if I try to buy an amount below the minimum for ADA, I get an error as expected. But when I switch to BTC and start typing the amount I want to buy, the app still shows the minimum amount from ADA if the new amount is less than the minimum Ada required. Once I finish entering the new BTC amount, the app loads for a moment and then confirms it’s okay — but until then, it keeps displaying the old ADA minimum error, which no longer applies.

**Expected behavior**
When changed fiat or crypto currency, error should clear

**Screenshots**

https://github.com/user-attachments/assets/f10114bc-c18f-4c03-8547-770fa8deec91

### PR DESCRIPTION
**Pull request by jbazant**
## Description

- Invalidates amount limits when selected fiat currency changes
- Invalidates amount limits when selected asset changes

## Related Issue

Resolve #19172

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=19172-mobile-trade-errors-clear&lookback=7)

### CODE REVIEW

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/module-trading/src/tradingSlice.ts [hunk 1]
```diff
@@ -81,6 +81,13 @@ export const tradingSlice = createSliceWithExtraDeps({
         clearTradeOrderIdToBeOpened: state => {
             state.tradeOrderIdToBeOpened = undefined;
         },
+        buyAssetChanged: state => {
+            state.buy.selectedReceiveAccount = undefined;
+            state.buy.amountLimits = undefined;
```
Comment (vytick) [inline suite-native/module-trading/src/tradingSlice.ts:87]: Clearing amountLimits in this case triggers showing error for no quotes. I think it should not be shown in this case

https://github.com/user-attachments/assets/af9ad62f-5bda-4fbe-8818-39fcd44f9ad0

**Review by vytick — CHANGES_REQUESTED** [review]

File: suite-native/module-trading/src/tradingSlice.ts (hunk 1 above)
Comment (tomasjakl) [inline suite-native/module-trading/src/tradingSlice.ts:87]: You should also reset quotesRequest, otherwise you'll get a "No offers available..." error message after changing currencies.
```suggestion
            state.buy.amountLimits = undefined;
            state.buy.quotesRequest = undefined;
```

**Review by tomasjakl — CHANGES_REQUESTED** [review]

File: suite-native/module-trading/src/tradingSlice.ts (hunk 1 above)
Comment (jbazant) [reply suite-native/module-trading/src/tradingSlice.ts:87]: Fixed.

Comment (jbazant) [reply suite-native/module-trading/src/tradingSlice.ts:87]: Fixed.

**Review by vytick — APPROVED** [review]
works nicely now, good job 👍

**Review by tomasjakl — APPROVED** [review]
Looks good 👍
