### PR TITLE
fix(trading): use Concierge wording in OTC CTAs

### LINKED ISSUE #26697: Bug: Provider name placeholder shown in buy flow
**Describe the bug**
Provider name placeholder {providerName} is displayed instead of the real provider name in the buy screen.

**Steps to reproduce**
1. Go to the buy flow
2. buy for over 50000USD
3. Look at the OTC partner provider button

**Expected behavior**
Provider name is displayed correctly (not as a placeholder).

**Screenshots**
Provider name bug

### PR DESCRIPTION
**Pull request by sherpaPSX**
## Description

- Replace OTC CTA translation copy to use fixed Concierge wording instead of injecting providerName.
- Remove now-unused providerName interpolation from the OTC offer banner CTA.
- Set the Concierge form Continue button to large size for consistent CTA prominence.

## Notes for QA

1. Open wallet trading OTC flow and verify the CTA text reads Buy with Concierge or Sell with Concierge (never provider-specific name).
2. Open the Concierge form and verify the Continue button is visibly larger than before and links to the selected provider URL.
3. Confirm no regressions in OTC banner rendering for both buy and sell offer types.

## Related Issue

Resolve #26697

## Screenshots:
image

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/26697/otc-cta&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/26697/otc-cta&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 13 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-15T09:16:55.804Z • 13 test(s) total_

<details><summary>Trezor Suite (desktop) — 14 test(s)</summary>

| Test | Type |
|------|------|
| Analytics Events - Staking Navigate > Should log the event staking/navigate - ADA from account menu | 🤖 auto |
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Global receive and send,Global receive" | 🙋 manual |
| Bridge > App acquired device, EXTERNAL bridge is restarted, app reconnects | 🤖 auto |
| Bridge > App spawns bundled bridge and stops it after app quit | 🤖 auto |
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Onboarding - create wallet > Success (basic) | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-15T09:16:27.161Z • 14 test(s) total_

### CODE REVIEW

File: suite/intl/src/messages.ts [hunk 1]
```diff
@@ -1251,11 +1251,11 @@ export const messages = defineMessages({
         id: 'TR_TRADING_OTC_INFO_SELL',
     },
     TR_TRADING_OTC_LINK_BUY: {
-        defaultMessage: 'Buy with {providerName}',
+        defaultMessage: 'Buy with Concierge',
```
Comment (vytick) [inline suite/intl/src/messages.ts:1254]: ⚠️  we need to update this in Crowdin, otherwise it gets lost

**Review by vytick — APPROVED** [review]
lgtm

__BUT make sure texts are updated in crowdin!__
