### PR TITLE
CLONE: fix(suite): order of network filter #15289

### LINKED ISSUE #9165: Accounts tab - order of network filter is different than accounts order
**Describe the bug**
The order of networks in the sidebar network filter is now based on the order in which the networks were enabled.

**Info:**

-   Suite Version: 24.8.1

**How to reproduce**

1. Disable all networks in `Settings` in `Coins` section
2. Enable `Litecoin`, `Polygon`, `Dogecoin`, `Bitcoin`
3. Check sidebar order of networks in filter vs order of accounts 
4. `Litecoin`, `Polygon`, `Dogecoin`, `Bitcoin` vs `Bitcoin`, `Polygon`, `Litecoin`, `Dogecoin`

**Expected behavior**
Networks filter should have same order as networks in Settings / accounts tab

**Screenshots**
Screenshot 2024-10-21 at 11 59 35
Screenshot 2024-10-21 at 12 00 07

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- clone of #15289 with added migration

Fixed order of network filter. The order is now the same as the account order.

## Related Issue

Resolve #9165

### CODE REVIEW

File: packages/suite/src/reducers/wallet/settingsReducer.ts [hunk 1]
```diff
@@ -36,7 +37,10 @@ const settingsReducer = (state: State = initialState, action: Action): State =>
 
             case walletSettingsActions.changeNetworks.type: {
                 if (walletSettingsActions.changeNetworks.match(action)) {
-                    draft.enabledNetworks = action.payload;
+                    draft.enabledNetworks = [...action.payload].sort(
```
Comment (Lemonexe) [inline packages/suite/src/reducers/wallet/settingsReducer.ts:40]: Nit: `toSorted` is exactly for this purpose, [see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) :slightly_smiling_face: 
```suggestion
                    draft.enabledNetworks = action.payload.toSorted(
```

File: packages/suite/src/storage/index.ts [hunk 2]
```diff
@@ -5,7 +5,7 @@ import { reloadApp } from 'src/utils/suite/reload';
 import { migrate } from './migrations';
 import type { SuiteDBSchema } from './definitions';
 
-const VERSION = 48; // don't forget to add migration and CHANGELOG when changing versions!
+const VERSION = 49; // don't forget to add migration and CHANGELOG when changing versions!
```
Comment (Lemonexe) [inline packages/suite/src/storage/index.ts:8]: [changelog](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/storage/CHANGELOG.md) is missing?

**Review by Lemonexe — APPROVED** [review]
LGTM!
