### PR TITLE
fix(trading): fixed swap inputs validation and styling

### LINKED ISSUE #16954: Trading - memo is not nice
**Describe the bug**

Image
Image

And when you are in it, please fix that it does not yell that address is empty even without touching it

### LINKED ISSUE #17071: Remove hover background color change in the toggle component circle
**Describe the bug**

Background color of the toggle circle changes on hover. There should be no hover change, the color should stay the same.

**Screenshots**

https://github.com/user-attachments/assets/b8804860-5f19-4ac3-b68b-05e71548e625

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

- the receive address input and the extra field inputs are displayed only after the user selects whether to create a new account or to use an account that isn't in Suite
- the receive address input shows errors only after the user has interacted with it
- the extra field inputs (memo, destination tag, ...) have better styling for readability

## Related Issue

Resolve #16954 
Resolve #17071 

## Screenshots:

https://github.com/user-attachments/assets/4c33643c-ecf6-407f-b415-b0fcb80534c9

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx [hunk 1]
```diff
@@ -143,33 +144,42 @@ export const TradingVerify = ({ tradingVerifyAccount, cryptoId }: TradingVerifyP
...
-                        {...networkField}
-                    />
-                )}
+                {selectedAccountOption &&
+                    selectedAccountOption?.account?.networkType !== 'bitcoin' && (
+                        <Input
+                            data-testid="@trading/form/verify/address"
+                            readOnly={selectedAccountOption?.type !== 'NON_SUITE'}
+                            inputState={
+                                form.formState.touchedFields.address &&
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx:153]: show errors only after the address field has been "touched"

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx [hunk 2]
```diff
@@ -226,7 +236,7 @@ export const TradingVerify = ({ tradingVerifyAccount, cryptoId }: TradingVerifyP
                                     confirmTrade(address, extraField);
                                 }
                             }}
-                            isDisabled={!form.formState.isValid || callInProgress}
+                            isDisabled={!form.formState.isValid || address === '' || callInProgress}
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx]: disable the button if the input field has not been touched but it is empty

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx [hunk 3]
```diff
@@ -143,33 +144,42 @@ export const TradingVerify = ({ tradingVerifyAccount, cryptoId }: TradingVerifyP
...
+                    selectedAccountOption?.account?.networkType !== 'bitcoin' && (
+                        <Input
+                            data-testid="@trading/form/verify/address"
+                            readOnly={selectedAccountOption?.type !== 'NON_SUITE'}
+                            inputState={
+                                form.formState.touchedFields.address &&
+                                form.formState.errors.address
+                                    ? 'error'
+                                    : undefined
+                            }
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx]: show errors only after the address field has been "touched"

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx [hunk 4]
```diff
@@ -143,33 +144,42 @@ export const TradingVerify = ({ tradingVerifyAccount, cryptoId }: TradingVerifyP
...
+                                    content={<Translation id={addressTooltipTranslationId} />}
+                                >
+                                    <Translation id="TR_EXCHANGE_RECEIVING_ADDRESS" />
+                                </Tooltip>
+                            }
+                            bottomText={
+                                (form.formState.touchedFields.address &&
+                                    form.formState.errors.address?.message) ||
+                                null
+                            }
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx]: show error text only after the address field has been "touched"

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx [hunk 5]
```diff
@@ -124,7 +124,8 @@ export const TradingVerify = ({ tradingVerifyAccount, cryptoId }: TradingVerifyP
                     </Tooltip>
                 }
             />
-            <Column gap={spacings.xxs}>
+
+            <Column gap={spacings.sm}>
                 {selectedAccountOption?.type === 'SUITE' &&
                     selectedAccountOption?.account?.networkType === 'bitcoin' && (
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx:131]: changed spacing for better look

File: packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.tsx [hunk 6]
```diff
@@ -73,7 +73,7 @@ const useTradingVerifyAccount = ({
     const { supportedMainnets, supportedTestnets } = useNetworkSupport();
 
     const methods = useForm<TradingVerifyFormProps>({
-        mode: 'onChange',
+        mode: 'onTouched',
     });
```
Comment (TomasBoda) [inline packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.tsx]: trigger form errors only after the form has been touched

**Comment by tomasklim** [comment]
This is extremely confusing, can we hide memo when buying to your own acc? @adderpositive
Screenshot 2025-02-18 at 11 00 05

**Comment by tomasklim** [comment]
This is how our send form now looks like for Ripple
Screenshot 2025-02-18 at 11 06 22

I am thinking that we should replicate it here with by default disabled `Add Memo/Destination tag` and probably without `i` or with different text.

What do you think @jirih-stsh?

File: packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.tsx (hunk 6 above)
Comment (tomasklim) [reply packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.tsx]: why does `onChange` trigger at all? The value did not change, or did it?

**Comment by jirih-stsh** [comment]
> I am thinking that we should replicate it here with by default disabled `Add Memo/Destination tag` and probably without `i` or with different text.
> 
> What do you think @jirih-stsh?

@tomasklim Yeah I agree. Lets copy the Ui from send, but keep the toggle disabled. Just be aware that currently in send, if you disable the toggle it will inject a warning banner instead bellow the input. Not sure if that will good look in swap.

**Comment by tomasklim** [comment]
Let's do it without banner and without `i`. `What is this?` can cover it

File: packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.tsx (hunk 6 above)
Comment (TomasBoda) [reply packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.tsx]: Found out where the issue was. The `useTradingVerifyHook` triggered validation on form creation. Fixed it in a fixup commit, so now we don't have to check for `formState.touchedValues.address`

**Comment by adderpositive** [comment]
> This is extremely confusing, can we hide memo when buying to your own acc? @adderpositive Screenshot 2025-02-18 at 11 00 05

I don't know. Will there still be a possibility to fill the memo?

**Comment by TomasBoda** [comment]
> Let's do it without banner and without `i`. `What is this?` can cover it

@tomasklim Done

https://github.com/user-attachments/assets/fde392a5-83e7-4aeb-a751-d3e465057aa1

**Comment by TomasBoda** [comment]
I also fixed #17071 as discussed with @jvaclavik

**Review by tomasklim — APPROVED** [review]

**Review by tomasklim — CHANGES_REQUESTED** [review]
It should not be under
Screenshot 2025-02-18 at 13 33 31

**Comment by TomasBoda** [comment]
> It should not be under Screenshot 2025-02-18 at 13 33 31

done

File: packages/components/src/components/form/Switch/Switch.tsx [hunk 7]
```diff
@@ -63,7 +63,7 @@ const Container = styled.div<{
                     : theme.backgroundNeutralDisabled};
             }
 
-            :hover {
+            &:hover {
```
Comment (jvaclavik) [inline packages/components/src/components/form/Switch/Switch.tsx:66]: 👏

**Review by jvaclavik — APPROVED** [review]
LGTM

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+    onToggle?: (toggled: boolean) => void;
+}
+
+export const TradingVerifyDestinationTag = ({
+    inputComponent,
+    onToggle,
+}: TradingVerifyDestinationTagProps) => {
+    const { openNodeById } = useGuideOpenNode();
+
+    const [enabled, setEnabled] = useState<boolean>(false);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx]: It looks like that sometimes it can be required so take data from 

Screenshot 2025-02-20 at 10 06 26

**Review by tomasklim — DISMISSED** [review]
I cannot continue without turning switch on and off

https://github.com/user-attachments/assets/138317b3-a1b7-4f4d-bd2e-0405be38de31

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx (hunk 8 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyDestinationTag.tsx]: done
