### PR TITLE
fix(suite): update t1b1 eth staking flow

### LINKED ISSUE #18707: ETH - Stake/Unstake/Claim – align the Trezor Suite with the updated flow for T1B1.
**Describe the bug**
In light of https://github.com/trezor/trezor-firmware/pull/4930, we need to update the flows for Stake, Unstake, and Claim to match the device.

**Info:**
 - Suite version: web 25.5.0 (5cecbac437c6e9d75afb7e621896c7818c7d4530)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.10 regular (revision 41b786353e09390b64b107e64e1cfe3020514ad5)
 - Transport: WebUsbTransport

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Aligns Ethereum Stake/Unstake/Claim flow with the updated T1B1 behavior in Trezor Suite.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/18707

## Screenshots:

Regular:
image
image
image

RBF:
image
image
image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutput.tsx [hunk 1]
```diff
@@ -193,7 +193,9 @@ const getOutputLines = (
                     {
                         id: 'data',
                         type: 'default',
-                        value,
+                        value: translationString(displayModeStringsMap[stakeType].value, {
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutput.tsx]: this case can be moved under 

```
  case 'address':
  case 'data':
```

line 170

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx [hunk 2]
```diff
@@ -47,7 +49,7 @@ const getLines = (
         .minus(precomposedTx.fee)
         .toString();
 
-    if (isUpdatedEthereumSendFlow) {
+    if (isUpdatedEthereumSendFlow || isStakeType) {
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx]:
```suggestion
    if (isUpdatedEthereumSendFlow || stakeType) {
```

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx [hunk 3]
```diff
@@ -209,6 +209,8 @@ export const TransactionReviewModalContent = ({
               .map(output => getTxStakeNameByDataHex(output?.value))
               .find(type => type) || null;
 
+    const txOutputs = !stakeType ? outputs : outputs.filter(output => output.type !== 'fee'); // The `fee` output is already included in the final transaction summary output.
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: Why the fee line is there? Please fix it on the place where the fee line is added. Probably here
```return isUnknownStakingClaimValue ? [feeLine] : [amountLine, feeLine];```

but maybe it is somewhere else but I do not like filtering it because the line should not be there

**Review by tomasklim — CHANGES_REQUESTED** [review]
Please add images of 

- stake, unstake, claim
- rbf stake, rbf unstake, rbf claim

if not claim is available, I believe you can fake it in the data

Because of the current changes, please confirm that solana staking and ethereum staking on non-T1B1 is still working. Thanks

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx (hunk 2 above)
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx]: By introducing this change, solana staking will use this?

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutput.tsx (hunk 1 above)
Comment (dev-pvl) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutput.tsx]: done, https://github.com/trezor/trezor-suite/pull/19547/commits/8877ef8d52ad930b15ac669b062d5f5172c55654

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx (hunk 2 above)
Comment (dev-pvl) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx]: fixed, https://github.com/trezor/trezor-suite/pull/19547/commits/8877ef8d52ad930b15ac669b062d5f5172c55654

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx (hunk 3 above)
Comment (dev-pvl) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx]: This fee line was added in constructOldFlow function. Fixed it without filtering https://github.com/trezor/trezor-suite/commit/8877ef8d52ad930b15ac669b062d5f5172c55654

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx (hunk 2 above)
Comment (dev-pvl) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx]: Yes, and it worked fine even with this change. But anyway, added additional check here to avoid confusion https://github.com/trezor/trezor-suite/commit/8877ef8d52ad930b15ac669b062d5f5172c55654

**Comment by dev-pvl** [comment]
Added required screenshots. I assume the missing amount on the rbf claim is expected behaviour. Also, checked staking on non-T1B1, and it seems to be working fine.

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx (hunk 2 above)
Comment (tomasklim) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewTotalOutput.tsx]: ah yes, we dont have solana for T1B1

**Comment by tomasklim** [comment]
@dev-pvl missing RBF claim value is expected. Now I am thinking, can we hide it also for unstaking instead of showing `0`?

**Review by tomasklim — APPROVED** [review]

**Comment by tomasklim** [comment]
Unstake RBF amount is now hidden instead of showing 0 

Screenshot 2025-06-13 at 17 16 28
