### PR TITLE
tiny ui fixes - unauthorized device

### LINKED ISSUE #16106: enable labeling switch - missing tooltip
there are cases when enable labeling switch is disabled (device not authorized yet). there is a tooltip explaining the reason but under some conditions the tooltip does not appear

no tooltip 
image

tooltip
image

steps to reproduce: 
1. go directly to http://localhost:8000/settings
2. try to enable labeling, the switch is disabled without any tooltip 

Image

### PR DESCRIPTION
**Pull request by mroz22**
resolves #16106

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsGeneral/Labeling.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ export const Labeling = () => {
     // - Labeling enabled without any device connected
     // - Labeling enabled with the device connected inside Settings
     // The initialization of Labeling then start when user select a Wallet.
-    const isDisabled = isLocked() || device?.mode !== 'normal';
+    const isDisabled = isLocked() || device?.mode !== 'normal' || !device?.state?.sessionId;
```
Comment (mroz22) [inline packages/suite/src/views/settings/SettingsGeneral/Labeling.tsx]: hmm do I need to ask specifically fro sessionId or is it enough to check for state only?

Comment (komret) [reply packages/suite/src/views/settings/SettingsGeneral/Labeling.tsx]: Looks like `state` is enough.

File: packages/suite/src/components/suite/labeling/WalletLabeling.tsx [hunk 2]
```diff
@@ -21,6 +21,7 @@ export const useWalletLabeling = () => {
 
     const defaultAccountLabelString = useCallback(
         ({ device }: { device: TrezorDevice }) => {
+            if (!device.state) return undefined;
```
Comment (komret) [inline packages/suite/src/components/suite/labeling/WalletLabeling.tsx]:
```suggestion
            if (!device.state) return undefined; // wallet not loaded yet
```

**Review by komret — CHANGES_REQUESTED** [review]
nits

**Review by komret — APPROVED** [review]
