### PR TITLE
fix(invity): Sell/Exchange with zero balance

### LINKED ISSUE #3762: Sell/Exchange with zero balance
**Describe the bug**
Three different error messages appear when I fill zero into Exchange/Sell inputs while having zero balance.

**Steps to reproduce:**
1. Accounts>Trade on coin with zero balance
2. Sell/Exchange tab
3. Click on 1/4, 1/2,.. or fill 0 to input

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: model T 2.3.6 regular

**Expected result:**
Screenshot 2021-05-17 at 10 31 24
I would expect that those buttons will be disabled when I have no balance.

**Screenshots:**
Screen Recording 2021-05-13 at 10 34 06 (1)

### PR DESCRIPTION
**Pull request by LukasRada**
fixes #3762

### CODE REVIEW

File: packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/Buttons/index.tsx [hunk 1]
```diff
@@ -27,15 +27,28 @@ const Left = styled.div`
     display: flex;
 `;
 
-const Button = styled.div`
+const Button = styled.div<{ isDisabled?: boolean }>`
```
Comment (tomexx) [inline packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/Buttons/index.tsx]: I know it was already in place but I think we should use semantic tags `button` in this case. It might be worth to use existing `button` component from `@trezor/components`

**Review by tomexx — COMMENTED** [review]
Please check the in-code comment. 

+ Not sure if you want to have the **ExchangeForm** and **SellForm** strictly separated but it seems the code could be simplified with some refactoring as there are a lot of duplicities.

**Comment by LukasRada** [comment]
Thanks for the review!
Sure, let's discuss the **ExchangeForm** and **SellForm** in a separate issue. And also maybe engage @martinboehm into the discussion.

Nevertheless, I refactored the fraction buttons also (not just the button).

**Review by tomexx — APPROVED** [review]
cool, thank you

File: packages/suite/src/components/wallet/CoinMarketFractionButtons/index.tsx [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+            </SmallButton>
+            <SmallButton isDisabled={disabled} onClick={() => !disabled && onFractionClick(3)}>
+                1/3
+            </SmallButton>
+            <SmallButton isDisabled={disabled} onClick={() => !disabled && onFractionClick(4)}>
+                1/4
+            </SmallButton>
+            <SmallButton isDisabled={disabled} onClick={() => !disabled && onAllClick()}>
+                <Translation id="TR_FRACTION_BUTTONS_ALL" />
+            </SmallButton>
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/CoinMarketFractionButtons/index.tsx]:
```suggestion
            <SmallButton isDisabled={disabled} onClick={() => onFractionClick(2)}>
                1/2
            </SmallButton>
            <SmallButton isDisabled={disabled} onClick={() => onFractionClick(3)}>
                1/3
            </SmallButton>
            <SmallButton isDisabled={disabled} onClick={() => onFractionClick(4)}>
                1/4
            </SmallButton>
            <SmallButton isDisabled={disabled} onClick={() => onAllClick()}>
                <Translation id="TR_FRACTION_BUTTONS_ALL" />
            </SmallButton>
```

Probably you do not need to check `disabled` in the onClick handler again as the button is disabled so unclickable by HTML itself.

**Review by tomasklim — APPROVED** [review]
LGTM. I agree with @tomexx that it would be nice to refactor and merge ExchangeForm and SellForm files.

File: packages/suite/src/components/wallet/CoinMarketFractionButtons/index.tsx (hunk 2 above)
Comment (LukasRada) [reply packages/suite/src/components/wallet/CoinMarketFractionButtons/index.tsx]: Good catch! Forgot to remove these conditions since the elements are buttons now. Fixed.
