### PR TITLE
Device compomised layout refactoring to show modal switcher all the time

### LINKED ISSUE #21855: Missing wallet switcher in some views
I don't see any point in hiding wallet switcher ever. Even though you get into an unexpected state on one device, you may still need to switch to another device, right?

In the video, user failed entropy check on a remembered T1. When they connect another device, they cannot switch to it until they reset Suite storage. Not only you cannot see wallet switcher on dashboard, but clicking it from settings takes you to dashboard instead of opening it.

https://github.com/user-attachments/assets/94661dc7-97f5-4cd4-ae1d-9d896ab45c93

How to fail entropy check:
Change this condition in `verifyEntropy.ts`:
`!trezorEntropy || !commitment || !strength || Object.keys(xpubs).length < 1`
to:
`!trezorEntropy || !commitment || !strength || Object.keys(xpubs).length < 10`

This behaviour probably applies to some other views as well, not just failed checks. Please investigate.

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/21855

image
image
image
image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=device-compomised-layout&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=device-compomised-layout&lookback=7)

### CODE REVIEW

**Comment by peter-sanderson** [comment]
image

File: packages/suite/src/components/suite/Preloader/selectShouldDisplayDeviceCompromisedOnRoute.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+export const selectShouldDisplayDeviceCompromisedOnRoute = (state: AppState): boolean => {
+    const { router } = state;
+
+    const shouldDisplayDeviceCompromised = selectShouldDisplayDeviceCompromised(state);
+
+    const displayOnRoute =
+        router.route?.app === undefined ||
+        !ROUTES_TO_SKIP_FIRMWARE_CHECK.includes(router.route?.app);
+
+    return displayOnRoute && shouldDisplayDeviceCompromised;
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/Preloader/selectShouldDisplayDeviceCompromisedOnRoute.ts:22]: 👌

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx [hunk 2]
```diff
@@ -3,10 +3,12 @@ import {
     WelcomeLayoutWithoutModalSwitcherProps,
 } from './WelcomeLayoutWithoutModalSwitcher';
 import { ModalSwitcher } from '../../modals/ModalSwitcher/ModalSwitcher';
+import { PassphraseFlow } from '../SuiteLayout/PassphraseFlow';
 
 export const WelcomeLayout = ({ children, ...rest }: WelcomeLayoutWithoutModalSwitcherProps) => (
     <WelcomeLayoutWithoutModalSwitcher {...rest}>
         <ModalSwitcher />
+        <PassphraseFlow />
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx:11]: I assume this is because device switcher is now available, and with device switcher you can start passphrase, which needs this component to work, right?

**Review by Lemonexe — COMMENTED** [review]
Visual issues:

WelcomeLayout trezor logo has 0 padding:
[Before](https://github.com/user-attachments/assets/8a1105c8-841e-4787-82fb-14a390f578a7)
[After](https://github.com/user-attachments/assets/768968e6-9d1e-4663-a311-f61b3a89c19c)

Trezor logo should be minified to icon when collapsed, but it's full and overflowing:
[Before](https://github.com/user-attachments/assets/d64d8ac5-5051-45ae-b1f8-4a8a9f8adc11)
[After](https://github.com/user-attachments/assets/b3ed47ca-0a0b-46bf-9a3a-ad476221b3c5)

EDIT: it's fixed

File: packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx [hunk 3]
```diff
@@ -72,6 +98,12 @@ export const Sidebar = () => {
         (updateStatusSuite !== 'up-to-date' && !closedNotificationSuite) ||
         (!['up-to-date', 'disconnected'].includes(updateStatusDevice) && !closedNotificationDevice);
 
+    const showAccountsWithExtra =
+        !shouldDisplayDeviceCompromised &&
+        selectedDevice !== undefined &&
+        selectedDevice.mode !== 'normal' && // bootloader, etc...
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx]: I think you meant this?
```suggestion
        selectedDevice.mode === 'normal' && // bootloader, etc...
```

File: packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx [hunk 4]
```diff
@@ -72,6 +98,12 @@ export const Sidebar = () => {
         (updateStatusSuite !== 'up-to-date' && !closedNotificationSuite) ||
         (!['up-to-date', 'disconnected'].includes(updateStatusDevice) && !closedNotificationDevice);
 
+    const showAccountsWithExtra =
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx]: what does it mean `WithExtra`?
If you meant "with extra conditions" than that's description of code structure instead of purpose, I'd suggest
`showAccountsAndIsDeviceReady`

File: packages/suite/src/components/suite/layouts/LoggedOutSidebar.tsx [hunk 5]
```diff
@@ -1,99 +0,0 @@
...
-                        <NavigationColumn>
-                            {!isSidebarCollapsed && (
-                                <TrezorLogoWrapper>
-                                    <TrezorLogo width="107px" type="horizontal" />
-                                </TrezorLogoWrapper>
-                            )}
-                            <Navigation margin={spacingsPx.zero}>
-                                {isSidebarCollapsed && (
-                                    <Icon name="trezorLogo" size="large" pointerEvents="none" />
-                                )}
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/LoggedOutSidebar.tsx:87]: ↑ the TrezorLogo 107 px || Icon decision should be in `Sidebar` I think

**Comment by vojtatranta** [comment]
Context: About a month I had a similar PR that completely removes the `/start` route and all the layouts around it.
Simultaneoulsy, @OriginalEveres made a PR that reskinned the "welcome layout" for the TS7 purposes. 

So at the moment we decided to keep the reskinned version because this would not break any interaction for certain. But complete removal of the /start and onborading might have caused troubles.

Your approach is somewhat in the middle, you mantain the route but unify the components. This is good.
I'd be affraid of that device switcher as it has a lot of interaction that may not be available during "onboarding" phase. And it may behave weirdly during it. Needs quite a lot for testing.

**Comment by peter-sanderson** [comment]
@vojtatranta thanks, I retest onboarding. I think the Onboarding layout dos not render `Sidebar` AT ALL. so it shall not be a problem, but I retest

File: packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx [hunk 6]
```diff
@@ -88,11 +120,19 @@ export const Sidebar = () => {
                 <Container $elevation={elevation}>
                     <TrafficLightOffset>
                         <Content>
-                            <DeviceSelector />
+                            {showDeviceSwitcher && selectedDevice !== undefined ? (
+                                <DeviceSelector />
+                            ) : (
+                                <Box margin={{ left: 20, right: 12, top: 12, bottom: 12 }}>
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx]: strange, all margins are declared, but in element inspector only the left one is applied 🤔 
Idk why.. But try `padding`, IMO padding is always better practice unless you know that you need to work with margin collapse (or margin auto).

**Review by Lemonexe — COMMENTED** [review]
Codewise LGTM, generally looks good but pls fix the visual issues 🙏

**Comment by Lemonexe** [comment]
~Oh and bigger problem: now I can't see accounts list anytime, [this is dashboard with all checks passed](https://github.com/user-attachments/assets/761bf33e-b010-46e1-9e3f-8e515f5cbcac).~

EDIT: now it's fixed

**Comment by peter-sanderson** [comment]
@Lemonexe WelcomeLayout collapsed aligment fixed

WelcomeLayout non-collabes (works on my machine, are you sure you have tested correct version (maybe sldev was behind?)

File: packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx (hunk 2 above)
Comment (peter-sanderson) [reply packages/suite/src/components/suite/layouts/WelcomeLayout/WelcomeLayout.tsx:11]: yes

File: packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx (hunk 3 above)
Comment (peter-sanderson) [reply packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx]: yes, its there? and it was there `===` yesterday.. it seems I have maybe forget co push or something :cry:

File: packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx (hunk 4 above)
Comment (peter-sanderson) [reply packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx]: fixed

File: packages/suite/src/components/suite/layouts/LoggedOutSidebar.tsx (hunk 5 above)
Comment (peter-sanderson) [reply packages/suite/src/components/suite/layouts/LoggedOutSidebar.tsx:87]: fixed

**Review by Lemonexe — APPROVED** [review]
Looks good now, visually I don't see any issues 🙂 
Needs to be QA'd in all kinds of app onboarding / device onboarding flows

File: packages/suite/src/views/suite/SwitchDevice/NeedsAttentionBanner.tsx [hunk 7]
```diff
@@ -4,9 +4,10 @@ import { acquireDevice, selectDeviceThunk } from '@suite-common/wallet-core';
 import { Banner, BannerVariant, Icon, IconName, Row } from '@trezor/components';
 import { exhaustive } from '@trezor/type-utils';
 
+import { Translation } from 'src/components/suite/Translation';
+
 import { goto } from '../../../actions/suite/routerActions';
 import { redirectAfterWalletSelectedThunk } from '../../../actions/wallet/addWalletThunk';
-import { Translation } from '../../../components/suite';
```
Comment (peter-sanderson) [inline packages/suite/src/views/suite/SwitchDevice/NeedsAttentionBanner.tsx:9]: this fixies on circular :tada:

**Review by OriginalEveres — APPROVED** [review]
LGTM codewise, did not test tho. But I think this should be properly tested by QA

**Comment by peter-sanderson** [comment]
I just re-run all the e2e test again to make sure it works
