### PR TITLE
Revert/display rotation source

### LINKED ISSUE #12915: Display rotation for device that does not support it.
**Describe the bug**
Display rotation for device that does not support it.
See screenshot with TS3 connected.
It allows you to change it and it has success notification `Settings changed successfully`

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image

image

### PR DESCRIPTION
**Pull request by komret**
## Description

Revert 25133322a340da10942a3be4afe7a3414c15157c: this solution didn't work with T2B1 where the default value for `display_rotation` is `0`.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12915

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx [hunk 1]
```diff
@@ -21,12 +22,20 @@ interface DisplayRotationProps {
 export const DisplayRotation = ({ isDeviceLocked }: DisplayRotationProps) => {
     const dispatch = useDispatch();
     const { device } = useDevice();
-    const currentRotation = device?.features?.display_rotation;
 
-    if (typeof currentRotation !== 'number') {
+    // features.display_rotation cannot be used to determine support because can be defined for devices not supporting rotation (e.g. T2B1).
+    const isSupported =
+        device?.features != undefined &&
```
Comment (tomasklim) [inline packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx]:
```suggestion
        device?.features != undefined &&
```
Can it also be `null` that you use `!=`? or is it just mistype?

Comment (komret) [reply packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx]: No, this is intentionally explicit so that @peter-sanderson doesn't bully me for this.

**Comment by komret** [comment]
Approve please 🙏  @tomasklim @peter-sanderson

File: packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx]: Shall it be `!==`? (one `=` is probably missing.

File: packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx [hunk 2]
```diff
@@ -21,12 +22,20 @@ interface DisplayRotationProps {
 export const DisplayRotation = ({ isDeviceLocked }: DisplayRotationProps) => {
     const dispatch = useDispatch();
     const { device } = useDevice();
-    const currentRotation = device?.features?.display_rotation;
 
-    if (typeof currentRotation !== 'number') {
+    // features.display_rotation cannot be used to determine support because can be defined for devices not supporting rotation (e.g. T2B1).
```
Comment (peter-sanderson) [inline packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx]: I assume we don't have this in `Capabilities` right? Is there issue or something where this is covered in FW?

File: packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx [hunk 3]
```diff
@@ -21,12 +22,20 @@ interface DisplayRotationProps {
...
+    const isSupported =
+        device?.features != undefined &&
+        [DeviceModelInternal.T2T1, DeviceModelInternal.T3T1].includes(
```
Comment (peter-sanderson) [inline packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx]: nit: `const DEVICES_SUPPORTING_DISPLAY_ROTATION = [DeviceModelInternal.T2T1, DeviceModelInternal.T3T1]` at the beginning of the file

File: packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx (hunk 1 above)
Comment (komret) [reply packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx]: 👀 82be73c648e4cf9ef7bdafb8b16c7d82c9ca4d74

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx (hunk 3 above)
Comment (komret) [reply packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx]: 5d50504df3cd18ff649a169961a0c0190a6821dd
