### PR TITLE
fix: remove pin-followup on backup device (doesn make sense), also prevent modal closure without confirming seed action

### LINKED ISSUE #16156: Remove Pin next-steps in Backup action as it doesn't make much sense + prevent closure of the modal
When you create backup in settings (because you skipped it during onboarding), this is the final screen. Is it intentional that we show the Create/Skip PIN buttons? Looks like a bug.

image

Also, the modal should not be cancellable unless all checkboxes are checked.

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolve https://github.com/trezor/trezor-suite/issues/16156

- Also refactoring and code-splitting was done (see first commit)

-------------------

Before: 

image

After: 

image
image

### CODE REVIEW

File: packages/suite/src/utils/backup/index.ts [hunk 1]
```diff
@@ -1,13 +1,5 @@
 import { ConfirmKey } from 'src/actions/backup/backupActions';
 
-/**
- * Utility function used to disable backup start button
- */
-export const canStart = (userConfirmed: ConfirmKey[], isDeviceLocked: boolean) =>
```
Comment (peter-sanderson) [inline packages/suite/src/utils/backup/index.ts:6]: this has usage only on one place so I moved it there

File: packages/suite/src/views/backup/BackupStep1Initial.tsx [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+        userConfirmed.includes(e),
+    ) && !isDeviceLocked;
+
+export const BackupStep1Initial = ({
+    onCancel,
+    backup,
+}: {
+    onCancel: () => void;
+    backup: BackupState;
+}) => {
```
Comment (komret) [inline packages/suite/src/views/backup/BackupStep1Initial.tsx:25]: Nit: I'd rather see these abstracted into a type for consistency.

**Review by komret — APPROVED** [review]
I am still not sure if the behaviour was intentional or not... but it was confusing.
