### PR TITLE
TxDetail - XRP - Display destination tag

### LINKED ISSUE #3375: TxDetail - XRP - Display destination tag
**Describe the bug**
Transaction detail modal does not display its destination tag.

**Info:**
 - Suite Version: web  20f555f
 - Browser: Chromium 88.0.4324.150 
 - OS: NixOS 20.09
 - Firmware Version: model T 2.3.5 ffa96205f

**Steps to reproduce:**
1. Create and send an arbitrary XRP transaction with destination tag filled in,
2. Select and display the transaction detail,
3. Observe modal.

**Expected result:**
Modal displays the destination tag that was added.

**Actual result:**
Modal doesn't include destination tag.

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by izmy**
## Description

Add the destination tag into TxDetail.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/3375

## Screenshots:

image

### CODE REVIEW

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -5462,6 +5462,10 @@ export default defineMessages({
         defaultMessage: 'Destination tag',
         id: 'DESTINATION_TAG',
     },
+    DESTINATION_TAG_SHORT: {
+        defaultMessage: 'DT',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]:
```suggestion
        defaultMessage: 'Memo/Tag',
```
This would maybe be better? Please @jirih-stsh

Comment (izmy) [reply packages/suite/src/support/messages.ts]: It seems better to me, so I changed it.

**Review by tomasklim — APPROVED** [review]
