### PR TITLE
fix(mobile): balance mismatch

### LINKED ISSUE #12352: Balances mismatch
We have several reports from internal and support about following issues in the app:
1. Balance mismatch -The top value on the homepage is different than the value shown in the transactions list when I have only BTC for example
2. Amount doubled - Some users see exactly double the amount at the top value in homepage
3. Staking is not shown as part of the top value on the homepage

Proposal: 
1. **Partially decoupling the top value from the graph**. Meaning that when the user is not interacting with graph, we will show the total amount of assets, however, if the user interacts with the graph, this will display the value from the graph
3. **Include staking in top value and device switcher**, so it is only missing in the graph
4. Solana is included (already) in the top value, but not in the graph

- **After Discussion We are going for Solution Number 2**
    - Let’s try this partial decoupling
    - Include staking in top value and device switcher, so it is only missing in the graph
    - Solana is included (already) in the top value, but not in the graph
    - ~~Hide % if it is zero is in the graph view~~ % will not calculate agains first point of graph but agains first non-zero point of graph so now percentages kind of make sense even for "all" timeframe etc.
    - Show the current balance independently on the graph so even if there is an error in the graph, but we know the current value.

### PR DESCRIPTION
**Pull request by Nodonisko**
## Description

1. When user is not touching graph show same value as everywhere else
2. Reflect staking in device switcher

I was not able to hide percentages for when there is zero because there is lot of valid cases when there could be zero, so I decided to change it little bit so now it will not calculate agains first point of graph but agains first non-zero point of graph so now percentages kind of make sense even for "all" timeframe etc.

## Related Issue

Resolve #12352 

## Screenshots:

Simulator Screenshot - iPhone 16 Pro - 2025-01-17 at 19 15 59
Simulator Screenshot - iPhone 16 Pro - 2025-01-17 at 19 15 23

### CODE REVIEW

File: suite-native/accounts/src/selectors.ts [hunk 1]
```diff
@@ -81,23 +84,54 @@ export const selectIsAccountAlreadyDiscovered = (
...
+    [selectCurrentFiatRates, selectFiatCurrencyCode, selectAccountByKey, selectAccountTokenInfo],
+    (fiatRates, localCurrency, account, tokenInfo) => {
+        if (!account || !fiatRates || !tokenInfo) return '0';
+        const { contract, balance } = tokenInfo;
+        const fiatRateKey = getFiatRateKey(account.symbol, localCurrency, contract);
+        const rate = fiatRates[fiatRateKey]?.rate;
+
+        if (!rate || !balance) return '0';
+
+        return toFiatCurrency(balance, rate) ?? '0';
```
Comment (matejkriz) [inline suite-native/accounts/src/selectors.ts:133]: Where is the `decimals` value reflected in the calculation?

File: suite-native/graph/src/components/GraphFiatBalance.tsx [hunk 2]
```diff
@@ -34,7 +34,7 @@ const Skeleton = () => (
 
 const Balance = ({ selectedPointAtom }: BalanceProps) => {
     const point = useAtomValue(selectedPointAtom);
-    const fiatValue = String(point.value);
+    const fiatValue = point.valueLatestTotal ? point.valueLatestTotal : String(point.value);
```
Comment (matejkriz) [inline suite-native/graph/src/components/GraphFiatBalance.tsx]: nitpick:
same, but easier to read?
```suggestion
    const fiatValue = point.valueLatestTotal || String(point.value);
```

File: suite-native/device-manager/src/components/WalletItem.tsx [hunk 3]
```diff
@@ -15,11 +15,7 @@ type WalletItemProps = {
 export const WalletItem = ({ onPress, deviceState, isSelectable = true }: WalletItemProps) => {
     const device = useSelector((state: any) => selectDeviceByState(state, deviceState));
     const selectedDevice = useSelector(selectSelectedDevice);
-    const fiatBalance = useSelector((state: any) =>
-        device?.state?.staticSessionId
-            ? String(selectDeviceTotalFiatBalanceNative(state, device?.state?.staticSessionId))
-            : undefined,
-    );
+    const fiatBalance = useSelector(selectSelectedDeviceTotalFiatBalance);
```
Comment (matejkriz) [inline suite-native/device-manager/src/components/WalletItem.tsx]: This is wrong, you can't show the fiat balance of the selected device for all devices... You have to select it by the staticSessionId

**Review by matejkriz — CHANGES_REQUESTED** [review]

File: suite-native/graph/src/components/GraphFiatBalance.tsx [hunk 4]
```diff
@@ -34,7 +34,7 @@ const Skeleton = () => (
 
 const Balance = ({ selectedPointAtom }: BalanceProps) => {
```
Comment (matejkriz) [inline suite-native/graph/src/components/GraphFiatBalance.tsx]: Would it be possible to show the `valueLatestTotal` even while the graph is loading if we know the value already? It doesn't make sense to hide the current balance by switching graph time frame. And would be awesome to show it sooner even before the graph is loaded.

File: suite-native/accounts/src/selectors.ts (hunk 1 above)
Comment (Nodonisko) [reply suite-native/accounts/src/selectors.ts:133]: hopefully fixed

File: suite-native/device-manager/src/components/WalletItem.tsx (hunk 3 above)
Comment (Nodonisko) [reply suite-native/device-manager/src/components/WalletItem.tsx]: good catch, reverted

File: suite-native/graph/src/components/GraphFiatBalance.tsx (hunk 4 above)
Comment (Nodonisko) [reply suite-native/graph/src/components/GraphFiatBalance.tsx]: Yes, but it required me to rework this whole PR again :D

File: suite-native/accounts/src/selectors.ts [hunk 5]
```diff
@@ -82,25 +85,54 @@ export const selectIsAccountAlreadyDiscovered = (
...
+    [selectCurrentFiatRates, selectFiatCurrencyCode, selectAccountByKey, selectAccountTokenInfo],
+    (fiatRates, localCurrency, account, tokenInfo) => {
+        if (!account || !fiatRates || !tokenInfo) return '0';
+        const { contract, balance, decimals } = tokenInfo;
+        const fiatRateKey = getFiatRateKey(account.symbol, localCurrency, contract);
+        const rate = fiatRates[fiatRateKey]?.rate;
+
+        if (!rate || !balance) return '0';
+
+        return toFiatCurrency(balance, rate, decimals) ?? '0';
```
Comment (matejkriz) [inline suite-native/accounts/src/selectors.ts]: No, these are completely different decimals with different meaning! The toFiatCurrency utility has a decimals parameter, which specifies how many decimal places the number should be rounded to. However, the decimals from tokenInfo refer to how divisible a token can be, so how to get the base unit. As an example: BTC has decimals==8, because 1 BTC has 100 000 000 sats. We get the value in sats but fiat rate is in BTC. Same it is with tokens.

File: suite-native/graph/src/hooks.ts [hunk 6]
```diff
@@ -220,3 +222,68 @@ export const useGraphForAllDeviceAccounts = ({ fiatCurrency }: CommonUseGraphPar
...
+
+    const lastPoint: TGraphPoint | undefined = graphPoints[graphPoints.length - 1];
+    const referencePoint: TGraphPoint | undefined = useMemo(
+        () => graphPoints.find(point => point.value > 0) ?? graphPoints[0],
+        [graphPoints],
+    );
+
+    useEffect(
+        () => () => {
+            // we should reset everything to default on unmount otherwise it will broke loading state when navigating to same or another account
```
Comment (matejkriz) [inline suite-native/graph/src/hooks.ts:253]: Is it really unmounting if we navigate to another account?

Comment (Nodonisko) [reply suite-native/graph/src/hooks.ts:253]: yes, you leave screen so it will be unmounted and reseted but only for account detail not for dashboard but on dashboard we don't need it anyway... as I said I am not happy with current state because it's very glued up together but some major refactor would take few more days 😢

**Comment by matejkriz** [comment]
Instead of $0, the amount is hidden at the beginning of the graph, check the video
https://github.com/user-attachments/assets/4dd18ac2-4862-4d96-9b62-07dfdaba7247

**Comment by Nodonisko** [comment]
Good catch, that's interesting edge case, let me take a look

**Comment by Nodonisko** [comment]
@matejkriz Not showing zero issue solved in [`eebbc4c` (#16457)](https://github.com/trezor/trezor-suite/pull/16457/commits/eebbc4cad85e51cf014922541573c03bb6794a12)

File: suite-native/graph/src/hooks.ts (hunk 6 above)
Comment (matejkriz) [reply suite-native/graph/src/hooks.ts:253]: ok, thanks

File: suite-native/accounts/src/selectors.ts (hunk 5 above)
Comment (Nodonisko) [reply suite-native/accounts/src/selectors.ts]: I removed decimals here, and I tried implement `convertTokenValueToDecimal` which should do exactly what you say, but it will broke completely and all values will be like `0.000000000123`

Screenshot 2025-01-21 at 12 00 05

If do not handle it at all it seems to work without any issues

**Comment by Nodonisko** [comment]
Fixed issue where Solana tokens with 0 values showed inifite loading [`5b7dcee` (#16457)](https://github.com/trezor/trezor-suite/pull/16457/commits/5b7dceee589dcbcdd26275c6ad38920de3496e40)

File: suite-native/accounts/src/selectors.ts (hunk 5 above)
Comment (matejkriz) [reply suite-native/accounts/src/selectors.ts]: yes, confirmed, that the balance is already converted, I just still didn't find the place where it is converted...

Comment (matejkriz) [reply suite-native/accounts/src/selectors.ts]: I guess it's here https://github.com/trezor/trezor-suite/blob/fix/balance-mismatch/suite-common/wallet-utils/src/accountUtils.ts/#L474-L475

**Review by matejkriz — APPROVED** [review]
It is a bit dirty and could use some refactoring later, but it is a HUUUGE improvement from user perspective 🎉 🎖️ 😍
