### PR TITLE
fix(suite): restructure SettingsSection to properly display explanato…

### LINKED ISSUE #16610: Missing text in Supported on newer Trezor section
**Describe the bug**
Supported on newer Trezors in Supported on newer Trezor section overlayed by coin list.
When you copy it test is complete but not rendered correctly.

**Steps to reproduce:**
1. Connect model T1
2. Navigate to Settings/Coins 
3. Observe Supported on newer Trezors section

**Info:**
 - Suite version: web 25.2.0 (70b9fdde41173fb4730cad31c0e5592dabd8caa6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T1B1 1.13.0 regular (revision 7bf7d5fac2e897aca792dece98d6346df5e29bd2)
 - Transport: WebUsbTransport

**Screenshots:**

Image

### PR DESCRIPTION
**Pull request by vojtatranta**
…ry tooltips
TODO:
- [x] Level the tooltip icon with the rest of the text
- [x] test out properly that nothing else in the settings is broken SettingsSection is used just in settings

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/16610

## Screenshots:

BRF
406865411-609c1028-bc8c-4121-935b-e3dc6b5b4603

AFTR
Screenshot 2025-02-12 at 2 22 28 PM

### CODE REVIEW

File: packages/components/src/components/InfoItem/InfoItem.tsx [hunk 1]
```diff
@@ -94,7 +97,7 @@ export const InfoItem = ({
                         variant={variant}
                         typographyStyle={typographyStyle}
                         as="div"
-                        ellipsisLineCount={1}
+                        ellipsisLineCount={allowTextWrap ? undefined : 1}
```
Comment (vojtatranta) [inline packages/components/src/components/InfoItem/InfoItem.tsx]: ugly.. Better soution? Anyone?

File: packages/suite/src/components/settings/SettingsSection.tsx [hunk 2]
```diff
@@ -1,24 +1,44 @@
...
+            allowTextWrap
             direction={isBelowLaptop ? 'column' : 'row'}
             labelWidth={250}
             iconName={icon}
-            label={title}
+            label={
+                <>
+                    {title}
+                    {tooltipText && (
+                        <Tooltip isInline content={tooltipText}>
```
Comment (vojtatranta) [inline packages/suite/src/components/settings/SettingsSection.tsx]: here we need somehow add top margin to the tooltip, so it sits nicely in the line, maybe line height hack could center it vertically to the line. @jvaclavik

Comment (jvaclavik) [reply packages/suite/src/components/settings/SettingsSection.tsx]: shouldn't we add `margin` from `frameProps` to `Tooltip`?

**Comment by jvaclavik** [comment]
Screenshot 2025-02-12 at 14 10 32

File: packages/suite/src/components/settings/SettingsSection.tsx (hunk 2 above)
Comment (vojtatranta) [reply packages/suite/src/components/settings/SettingsSection.tsx]: as discussed: made with position: relative

**Comment by vojtatranta** [comment]
QA instruct: please, test out other languages / windows / all of the other settings sections if the styling is correct and texts are readable and tooltips are displayed properly with correct texts, thanks

File: packages/components/src/components/InfoItem/InfoItem.tsx [hunk 3]
```diff
@@ -44,6 +44,7 @@ const Container = styled.div<ContainerProps>`
 
 export type InfoItemProps = AllowedFrameProps &
     AllowedTextProps & {
+        allowTextWrap?: boolean;
```
Comment (jvaclavik) [inline packages/components/src/components/InfoItem/InfoItem.tsx]: What about do it with `textProps` using `ellipsisLineCount`? It's the same principle like `frameProps`

Check it here: `packages/components/src/components/typography/utils.tsx`

File: packages/components/src/components/Tooltip/Tooltip.tsx [hunk 4]
```diff
@@ -22,7 +22,7 @@ import { Icon } from '../Icon/Icon';
 
 export type TooltipInteraction = 'none' | 'hover';
 
-export const allowedTooltipFrameProps = ['cursor'] as const satisfies FramePropsKeys[];
+export const allowedTooltipFrameProps = ['cursor', 'margin'] as const satisfies FramePropsKeys[];
```
Comment (jvaclavik) [inline packages/components/src/components/Tooltip/Tooltip.tsx]: so do we need it? Actually not sure if this margin shouldn't be applied on the area when you hover

Comment (vojtatranta) [reply packages/components/src/components/Tooltip/Tooltip.tsx]: damn, didn't delete this, thanks

File: packages/components/src/components/InfoItem/InfoItem.tsx (hunk 3 above)
Comment (vojtatranta) [reply packages/components/src/components/InfoItem/InfoItem.tsx]: good idea

Comment (vojtatranta) [reply packages/components/src/components/InfoItem/InfoItem.tsx]: The it woul be liie `ellipsisLineCOunt={0}`, right?

Comment (jvaclavik) [reply packages/components/src/components/InfoItem/InfoItem.tsx]: Why 0? I think it's correct this way: `ellipsisLineCount ?? 1`

**Review by jvaclavik — APPROVED** [review]
Magnifigue!

**Comment by bosomt** [comment]
**QA OK**


https://github.com/user-attachments/assets/f34d6737-bd12-4738-abd0-899f64f8f809

**Info:**
 - Suite version: web 25.3.0 (8eddce5730fef3426425577e1e1a1f0491364c42)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T1B1 1.13.0 regular (revision null)
 - Transport: WebUsbTransport

File: packages/components/src/components/InfoItem/InfoItem.tsx (hunk 3 above)
Comment (vojtatranta) [reply packages/components/src/components/InfoItem/InfoItem.tsx]: As we discussed: you need to pass then to this compoennt `ellipsisLineCount={0}` to disable line breaking (the inner comopnent has check `ellipsisLineCount > 0` to enable text overflow and ellipsis.
