### PR TITLE
Make TS3 wipeable again!

### LINKED ISSUE #10245: Can't wipe TS3 in BL mode via Suite settings
**Describe the bug**
I can't wipe the TS3 in BL mode through Suite. Suite throws error:
image

and does not wipe the device. (This was introduced with 23.11.5, it works correctly in 23.10.1)

**Steps to reproduce:**
1. Connect TS3 to Trezor Suite in BL mode
2. Go to device settings
3. Try to "Factory reset" the device through the menu
4. Suite throws an error and doesn't wipe the device.

**Info:**
 - Suite version: desktop 23.11.5 (4566edae060459a5645f0ddabde574b998d53c53)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.11.5 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2B1 2.6.3 regular (revision null)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
I can wipe the FW of TS3 through Suite.

**Actual result:**
I can't wipe the FW of TS3 in Suite.

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- we dont know fw version of `T1B1` in bootloader mode so we cant fix `getVersion()` in `Device.ts` properly
=> disable check firmware range for bootloader mode for all device to have it unified

## Related Issue

closes #10245

## Screenshots:
image

### CODE REVIEW

File: packages/connect/src/core/AbstractMethod.ts [hunk 1]
```diff
@@ -255,7 +255,9 @@ export abstract class AbstractMethod<Name extends CallMethodPayload['method'], P
             return;
         }
         const { device } = this;
-        if (!device.features) return;
+
+        // do not do rfw ange check for devices in BL mode as we do not know fw version of some device models
```
Comment (mroz22) [inline packages/connect/src/core/AbstractMethod.ts]: what language is this?

Comment (mroz22) [reply packages/connect/src/core/AbstractMethod.ts]: please specify reason (descripbe model One behavior)

Comment (tomasklim) [reply packages/connect/src/core/AbstractMethod.ts]: updated

**Review by mroz22 — APPROVED** [review]
Yes, in my opinion, it makes sense. Since on model One, we don't know firware version in bootloader mode and vice-versa we have 2 options:
- define version requirements in connect not by firmware version but "by version of either bootloader or firwmare depending on in which state the feature is expected to be used". Here in this case, `wipeDevice` method does not have any specific requirement so it very likely ends up on defaults in AbstractMethod
```
export const DEFAULT_FIRMWARE_RANGE: FirmwareRange = {
    T1B1: { min: '1.0.0', max: '0' },
    T2T1: { min: '2.0.0', max: '0' },
    T2B1: { min: '2.6.1', max: '0' },
};
```
so one option would be to set T2B1 default to '2.0.0' to fix this but it does not feel systemic.
- or simply skip checking firmware version if device is in bootloader mode. sounds relatively ok, since this logic only lets us return some nicer error than we would yield from firmware itself and also there are very little calls to device carried out in bootloader mode.
