### PR TITLE
Fix `selectAllPendingTransactions` with undefined transactions

### LINKED ISSUE #12886: App sometimes crashes during coinjoin discovery
**Describe the bug**
App sometimes crashes during coinjoin discovery when you open transaction detail.
Managed to reproduce it on 24.6.1 and 24.5.4 version

**Steps to reproduce:**
1. Add BTC coinjoin account
2. During discovery navigate to TEST account with tx history and open tx detial
3. Repeat till app crashes, looks like when you hit at bad time app crashes

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: 
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image
https://youtu.be/Ez5l_qUDrLw

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

I haven't reproduced the issue #12886, but from it and minified Sentry stack trace, my interpretation is following:

- sometimes during CJ discovery, account is already removed (or not added yet) and transactions are being removed from it by `cleanPendingTransactions`
- therefore, `transactions` object transforms from `{ }` to `{ [accountKey]: undefined }` (first bug)
- meanwhile, `TxDetailModal` is opened on another account, calling `selectAllPendingTransactions`
- it doesn't expect undefined value for an `accountKey` in `transactions`, so it throws (second bug)

I made these two places a bit more defensive.

## Related Issue

Hopefully resolve #12886

### CODE REVIEW

**Comment by MiroslavProchazka** [comment]
@bosomt Can you try to reproduce the Reading filter issue on this PR?

File: suite-common/wallet-core/src/transactions/transactionsReducer.ts [hunk 1]
```diff
@@ -99,9 +99,11 @@ export const prepareTransactionsReducer = createReducerWithExtraDeps(
             .addCase(transactionsActions.removeTransaction, (state, { payload }) => {
                 const { account, txs } = payload;
                 const transactions = state.transactions[account.key];
-                state.transactions[account.key] = transactions?.filter(
-                    tx => !txs.some(t => t.txid === tx?.txid),
-                );
+                if (transactions) {
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/transactions/transactionsReducer.ts:110]: I see there is a test file for this, it may be worth to add a test-case for this fix :pray: 

`suite-common/wallet-core/src/transactions/__tests__/transactionsReducer.test.ts`

**Review by peter-sanderson — CHANGES_REQUESTED** [review]
We can discuss this more in general, but I am kinda starting to feel we need more unit test in general and this IMO shall be covered. 

I think that every fix shall have a test that covers what have been fixed so it wont happen again.

File: suite-common/wallet-core/src/transactions/transactionsReducer.ts (hunk 1 above)
Comment (marekrjpolak) [reply suite-common/wallet-core/src/transactions/transactionsReducer.ts:110]: https://github.com/trezor/trezor-suite/pull/12951/commits/44e26b5c44b549c7632e81d42ef42c045bc725ce

**Comment by bosomt** [comment]
i did not managed to crash this branch app


**Info:**
 - Suite version: desktop 24.7.0 (44e26b5c44b549c7632e81d42ef42c045bc725ce)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.7.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

File: suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts [hunk 2]
```diff
@@ -149,3 +149,30 @@ export const addTransaction = [
         result: { [ACCOUNT.key]: [testMocks.getWalletTransaction({ txid: '00' })] },
     },
 ];
+
+export const removeTransaction = [
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts]: Please lets type all fixtures declarativelly. Without it, its hard to debug failing test wen we add something to action payload

File: suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts [hunk 3]
```diff
@@ -149,3 +149,30 @@ export const addTransaction = [
...
+    {
+        description: 'ordinary remove',
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts]: I suggest writing test case description is a way that explaining what is the expected behavior and why we need this this way.

In this case something like: `it("removes the transaction from the existing account", ...`

File: suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts [hunk 4]
```diff
@@ -149,3 +149,30 @@ export const addTransaction = [
...
+            },
+        },
+        actionPayload: {
+            account: ACCOUNT,
+            txs: [testMocks.getWalletTransaction()],
+        },
+        result: { [ACCOUNT.key]: [] },
+    },
+    {
+        description: 'remove from nonexistent account',
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts]: In this case something like: `it("removing transaction from the non-existing account does nothing", ...`

File: suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts (hunk 2 above)
Comment (marekrjpolak) [reply suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts]: ok fascist

Comment (peter-sanderson) [reply suite-common/wallet-core/src/transactions/__fixtures__/transactionsReducer.ts]: image


At your service!

**Review by peter-sanderson — APPROVED** [review]
