### PR TITLE
fix(suite): fit spanish into QR code description

### LINKED ISSUE #10313: QR code with long text not fitting into container
Show receive address or XPUB with language set to Spanish:
Screenshot 2023-12-12 at 21 08 12

My suggestion is to remove absolute positioning and make the container scale with the text.

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

Adds a space for Spanish in the QR code description.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10313

## Screenshots:
image
image

-----
image
image

### CODE REVIEW

File: packages/suite/src/components/suite/QrCode.tsx [hunk 1]
```diff
@@ -55,12 +54,12 @@ export const QrCode = ({ value, className, bgColor, fgColor, showMessage }: QrCo
             style={{ width: '100%', height: '100%', objectFit: 'contain' }}
         />
         {showMessage && (
-            <MessageWrapper>
-                <Message>
+            <Message>
+                <span style={{ whiteSpace: 'normal' }}>
```
Comment (tomasklim) [inline packages/suite/src/components/suite/QrCode.tsx]: Please use `styled-components`

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Comment by tomasklim** [comment]
@Hermez-cz the info icon under QR code next to text looks like that there is some tooltip, but there is not. Should it be there? Or maybe it should be at the begging of the text and not at the end? Screenshot 2024-01-02 at 6 05 22

**Comment by Hermez-cz** [comment]
> @Hermez-cz the info icon under QR code next to text looks like that there is some tooltip, but there is not. Should it be there? Or maybe it should be at the begging of the text and not at the end? Screenshot 2024-01-02 at 6 05 22

We should add a tooltip explaining why you shouldn't do that. Something roughly like "Please confirm the receiving address on device first, as its trusted display can't be hacked unlike this one".

File: packages/suite/src/components/suite/QrCode.tsx (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/components/suite/QrCode.tsx]: :heavy_check_mark:

**Comment by peter-sanderson** [comment]
image
image
image
image

**Review by dahaca — APPROVED** [review]

**Review by tomasklim — APPROVED** [review]
