### PR TITLE
fix(suite-native): do not show view only alert during passphrase flow

### LINKED ISSUE #15979: View only modal overlaps "empty passphrase" when empty passphrase is entered
**Describe the bug**
When I enter an empty passphrase and I have "view only" still enabled, I get a view only modal that overlaps the empty passphrase wallet flow. This basically only applies for either wiped Suite or never disabled view only feature. See screenshot.

**Info:**

-   Mobile Suite Version: 24.11.2
-   OS: Android

**How to reproduce**

1. Start with wiped Suite lite
2. Go through onboardin and enable just BTC (for example)
3. Enable "view only" for standard wallet
4. Open passphrase wallet
5. Enter passphrase with no tx history (empty)
6. After the "discovery" you will see what's on screenshot

**Expected behavior**
I should be prompted for view only after I get to the dashboard.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by vytick**
After moving View only modal from bottomsheet to Alert we need to check whethere passphrase is not being added.

## Related Issue

Resolve #15979

### CODE REVIEW

**Review by yanascz — APPROVED** [review]
Works like a charm!

File: suite-native/module-home/src/screens/HomeScreen/useShowViewOnlyAlert.tsx [hunk 1]
```diff
@@ -109,6 +110,7 @@ export const useShowViewOnlyAlert = () => {
             !isPortfolioTrackerDevice &&
             !hasDiscovery &&
             !viewOnlyCancelationTimestamp &&
+            !isCreatingNewPassphraseWallet &&
```
Comment (matejkriz) [inline suite-native/module-home/src/screens/HomeScreen/useShowViewOnlyAlert.tsx:113]: I like how the canBeShowed condition is super short and simple 🤣

**Review by matejkriz — APPROVED** [review]

File: suite-native/module-home/src/screens/HomeScreen/useShowViewOnlyAlert.tsx (hunk 1 above)
Comment (vytick) [reply suite-native/module-home/src/screens/HomeScreen/useShowViewOnlyAlert.tsx:113]: I think we are getting closer to the moment we were talking about: having one decision tree for showing modals.
