### PR TITLE
fix: Send form "setMax" inconsistent behaviour

### LINKED ISSUE #2314: New send form - Send max button disabling Send Transaction button
**Info:**
 - OS: NIXOS
 - Browser: Chromium , version 84.0.4147.135
 - Wallet Version: web, commit cf1f18089c5ed75a68f2e720a5e08b6e3df79130
 - Firmware Version: model 2.3.3 , revision 0d5f00668
 
**Describe the bug**
Send max button disables Send Transaction button.
See video please
Same problem when sending to multiple recipients

**Steps to reproduce:**
1. go to send form and enter valid address
2. press send max button multiple times, watch Send button
3. observe Send transaction button

**Expected result:**
it's possible to send transaction everytime

**Actual result:**
You have to change transaction to reactivate Send transaction button 

**Screenshots:**

LOG: https://pastebin.com/PU4X9e6Q

see video: https://www.youtube.com/watch?v=tmYp46l9iG4&feature=youtu.be

console with warnings and errors:

image

### PR DESCRIPTION
**Pull request by szymonlesisz**
- Fix: #2314, #2327
- Fix DOGE custom fee calculation freeze
- Fix app crashing on "setMax" mad clicking
- Refactor of composeRequest
- Refactor and more unit tests

### CODE REVIEW

**Comment by sorooris** [comment]
**QA OK**

Suite Version: web,  374d68b (send-btc-compose-outputs branch)
OS: NixOS
Browser: Chromium 84.0.4147.125
Device 2.3.3 0d5f00668

File: packages/suite/src/utils/wallet/sendFormUtils.ts [hunk 1]
```diff
@@ -260,7 +262,9 @@ export const getBitcoinComposeOutputs = (values: Partial<FormState>, symbol: Acc
     // corner case for multiple outputs
     // one Output is valid and "final" but other has only address
     // to prevent composing "final" transaction switch it to not-final (noaddress)
-    const hasIncompleteOutput = values.outputs.find(o => o && o.address && !o.amount);
+    const hasIncompleteOutput = values.outputs.find(
+        (o, i) => setMaxOutputId !== i && o && o.address && !o.amount,
```
Comment (keraf) [inline packages/suite/src/utils/wallet/sendFormUtils.ts:266]: Minor thing here, could use optional chaining. And it's not very clear what the amount check is supposed to be. I believe amount is a number? Is it checking for a missing or 0 amount in this case?

Comment (szymonlesisz) [reply packages/suite/src/utils/wallet/sendFormUtils.ts:266]: amount is a string (all fields from the inputs are strings, [typed here](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/types/wallet/sendForm.ts#L19)) so in this case: amount === undefined (when input was not registered yet) or amount === '' (amount is empty)

**Review by keraf — APPROVED** [review]
