### PR TITLE
fix(trading): fix delay when selecting max value in swap

### LINKED ISSUE #16432: Trading - "Max" value displays with considerable delay in Swap
**Describe the bug**

In swapping, when selecting "Max" value, the input field is cleared and the value appears only after several seconds. However, it's equivalent fiat value is shown instantly.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: web 25.2.0-dev
-   Browser: Google Chrome, 131.0.6778.265
-   OS: macOS, 15.1.1
-   Firmware Version: Trezor Safe 5, 2.8.7

**How to reproduce**

1. Go to Dashboard
2. Click on Swap
3. Select "From" GST-SOL token for instance
4. Select "To" any token
5. Click on "Max" and see that the value is shown after several seconds

**Expected behavior**

The value of "Max" should appear instantly as with other percentage values.

**Screenshots**

https://github.com/user-attachments/assets/a341e246-1e18-47b7-9885-6f33c032a78d

### PR DESCRIPTION
**Pull request by meedoox**
## Description
Resolves delay after Max value to swap is selected

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16432

### Before
https://github.com/user-attachments/assets/03e634d1-66e9-4feb-9033-f4249479d704

### After
https://github.com/user-attachments/assets/b450a79d-4f86-430c-a5a0-d3803eea3b6e

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/swap-max-value-delay&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/swap-max-value-delay&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts [hunk 1]
```diff
@@ -215,9 +215,17 @@ export const useTradingFormActions = <T extends TradingSellExchangeFormProps>({
...
+            : new BigNumber(account.formattedBalance).decimalPlaces(networkDecimals).toString();
+
+        const cryptoInputValue = shouldSendInSats
+            ? convertAmountUnitsToSubunits(maxAmount, networkDecimals)
+            : maxAmount;
+
         setValue(TRADING_FORM_OUTPUT_MAX, 0, { shouldDirty: true });
         setValue(TRADING_FORM_OUTPUT_FIAT, '', { shouldDirty: true });
-        setValue(TRADING_FORM_OUTPUT_AMOUNT, '', { shouldDirty: true });
+        setValue(TRADING_FORM_OUTPUT_AMOUNT, cryptoInputValue, { shouldDirty: true });
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts]: this can be done for tokens, but not for native token as you need to wait for fee

**Review by tomasklim — CHANGES_REQUESTED** [review]
do it only for tokens and we are good 👌

**Review by tomasklim — APPROVED** [review]
LGTM!
