### PR TITLE
fix(utxo-lib): ltc deserialize without advanced marker

### LINKED ISSUE #7344: Cannot sign the transaction for Litecoin
**Describe the bug**

I am trying to send a Litecoin transaction from Trezor Suite from a legacy account to `MR…`. After the `review & send` click it gives me the error: `Transaction signing error: value out of range`

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app, Version 22.12.1 (22.12.1.24264)
-   Browser: Firefox (not relevant)
-   OS: macOS Ventura 13.1
-   Bridge: 2.0.27
-   Firmware Version: Trezor T, 2.5.1

**How to reproduce**

1. Connect Trezor T device
1. Open Trezor Suite app
1. Choose Litecoin
1. Make a new transfer from the legacy wallet
1. Click `Review & Send`
1. Error pop-in `Transaction signing error: value out of range`

**Expected behavior**

Transaction to the wallet you choose and sign the transaction.

**Screenshots**
Screenshot 2023-01-07 at 13 38 15

### LINKED ISSUE #7619: Transaction signing error: Cannot read slice out of bounds
I transferred Litecoin to my Trezor wallet yesterday. Now, I am trying to send it to my Exodus wallet connected to my trezor, but it says "Transaction signing error: Cannot read slice out of bounds". I tried to input smaller amounts but still had the same error. 
I also tried to send it to my binance wallet, but still had the same error. 

I also sent Litecoin to my exodus wallet from binance and send it back to binance and it worked. I am only having problems when sending litecoin from trezor to any wallet I have. 

Trezor suite updated to the latest version. The Firmware of the device Trezor One is updated to the latest version as well. 
Hoping for your help on this. First time encountered this problem. 

Error

### PR DESCRIPTION
**Pull request by mroz22**
with adding support for spending mweb peg-out outputs we unfortunately introduced a bug that caused misinterpretation of transaction hex. under some circumstances, it was possible for a transaction to be falsely marked as mweb which broke further decoding

resolve #7619 
resolve #7344

### CODE REVIEW

File: packages/utxo-lib/src/transaction/bitcoin.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ function toBuffer<S>(
         bufferWriter.writeUInt8(ADVANCED_TRANSACTION_MARKER);
         bufferWriter.writeUInt8(ADVANCED_TRANSACTION_FLAG);
     } else if (hasMweb) {
-        bufferWriter.writeUInt8(0);
+        bufferWriter.writeUInt8(ADVANCED_TRANSACTION_MARKER);
```
Comment (marekrjpolak) [inline packages/utxo-lib/src/transaction/bitcoin.ts:29]: Only cosmetic change, right?

File: packages/utxo-lib/src/transaction/bitcoin.ts [hunk 2]
```diff
@@ -74,13 +74,18 @@ export function fromBuffer(buffer: Buffer, options: TransactionOptions) {
...
-
     const marker = bufferReader.readUInt8();
     const flag = bufferReader.readUInt8();
 
-    const hasMweb = flag === MWEB_PEGOUT_TX_FLAG && isNetworkType('litecoin', tx.network);
-
     let hasWitnesses = false;
+    let hasMweb = false;
+
+    if (isNetworkType('litecoin', tx.network)) {
```
Comment (marekrjpolak) [inline packages/utxo-lib/src/transaction/bitcoin.ts:83]: If I understand it correctly, flag (either mw pegout or segwit) is there only when there is the advanced tx marker (zero byte) as well, but occasionally we interpreted some txin data as mw pegout flag in a pre-segwit transaction as we didn't check the marker first, right?

File: packages/utxo-lib/tests/__fixtures__/transaction/litecoin.ts [hunk 3]
```diff
@@ -31,6 +31,133 @@ export default {
             virtualSize: 125,
             weight: 500,
         },
+        {
+            description: 'Tx without advanced transaction marker and with mweb flag',
```
Comment (marekrjpolak) [inline packages/utxo-lib/tests/__fixtures__/transaction/litecoin.ts]: If I'm correct in the previous comment, the mweb flag isn't really a flag without the marker, but there is ofc no need to change the fixture description.

**Review by marekrjpolak — APPROVED** [review]
I've left some questions, but there's no reason not to approve :+1:

File: packages/utxo-lib/src/transaction/bitcoin.ts (hunk 1 above)
Comment (mroz22) [reply packages/utxo-lib/src/transaction/bitcoin.ts:29]: Exactly.

File: packages/utxo-lib/src/transaction/bitcoin.ts (hunk 2 above)
Comment (mroz22) [reply packages/utxo-lib/src/transaction/bitcoin.ts:83]: Thats how I understand it too

File: packages/utxo-lib/tests/__fixtures__/transaction/litecoin.ts (hunk 3 above)
Comment (mroz22) [reply packages/utxo-lib/tests/__fixtures__/transaction/litecoin.ts]: Good idea, changed fixture to "Tx without advanced transaction marker and with byte that could be misinterpreted as mweb flag"
