### PR TITLE
fix: do not call SuiteSync stuff on unsuported devices

### LINKED ISSUE #23188: Prevent `initEvoluKeysThunk` being called on unsupported firmwares
Image

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/23188

## QA: 
- Having SuiteSync ON on old FW shall not produce error
- See also: https://github.com/trezor/trezor-suite/issues/22922

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-do-not-subscribe-unsuported-evolu&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix-do-not-subscribe-unsuported-evolu&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-do-not-subscribe-unsuported-evolu&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/device/deviceSelectors.ts [hunk 1]
```diff
@@ -235,14 +235,6 @@ export const selectDeviceByStaticSessionId = createMemoizedSelector(
     (devices, staticSessionId) => devices.find(d => d.state?.staticSessionId === staticSessionId),
 );
 
-export const selectDeviceByBaseStaticSessionId = createMemoizedSelector(
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/device/deviceSelectors.ts:238]: unused, accidental change

File: suite-common/wallet-core/src/device/delegatedIdentityKey/retrieveDelegatedIdentityKeyThunk.ts
Comment (peter-sanderson) [inline suite-common/wallet-core/src/device/delegatedIdentityKey/retrieveDelegatedIdentityKeyThunk.ts:1]: I think this shall be in `wallet-core` and not in the `suite-sync`. DelegatedIdentityKey is property of device not necessarily tight to suite-sync

File: suite-common/wallet-core/src/index.ts [hunk 2]
```diff
@@ -1,49 +1,57 @@
-export * from './selectors';
```
Comment (peter-sanderson) [inline suite-common/wallet-core/src/index.ts:1]: alphabetical sort

File: packages/connect/src/types/device.ts [hunk 3]
```diff
@@ -118,7 +136,17 @@ export type BluetoothDeviceProps = {
 
 export type KnownDevice = BaseDevice & {
     type: 'acquired';
+
+    /**
+     * Identifier of the PHYSICAL device. It is par of the device.fetaures
```
Comment (OriginalEveres) [inline packages/connect/src/types/device.ts]: typo `It is par of the device.fetaures` -> `It is part of the device.fetaures`

**Review by OriginalEveres — APPROVED** [review]
lgtm, not tested tho.

File: packages/suite/src/middlewares/suite/suiteMiddleware.ts [hunk 4]
```diff
@@ -91,7 +92,9 @@ export const prepareSuiteMiddleware = createMiddlewareWithExtraDeps(
             const { device } = action.payload;
 
             dispatch(handleDeviceDisconnect(device));
-            dispatch(extra.thunks.unsubscribeAndDisposeLocalFirstStorage({ device }));
+            if (isTrezorDeviceWithState(device)) {
+                dispatch(extra.thunks.unsubscribeAndDisposeLocalFirstStorage({ device }));
```
Comment (vojtatranta) [inline packages/suite/src/middlewares/suite/suiteMiddleware.ts:96]: I wonder, if this shouldn't be like a general "singla" in the app. 

```ts
extra.thunks.signalDeviceForgotten(device)
```
And then it also shouldn't be here in the middleware at all, we just need to replace the `deviceActions.forgetDevice()` with `forgetDeviceThunk()` where this will be called.

Then, where we need to check for the forgotten device `beforeDeviceForget(device => isTrezorDeviceWithState(device)? neco() : null)`

Yes, it introduces event listeners, but at least we do not misuse the middleware so much.

On mobile,ther eis `deviceConnectionMiddleware` that solves it with the current tools with 
```ts
export const deviceConnectionMiddleware = createListenerMiddleware<NativeDeviceRootState>();
```

That's specically made for the effects. I am not sure about this particular API. But I think it is better than these middlewares.
