### PR TITLE
fix: after update notification only for the first run of the new version

### LINKED ISSUE #3308: Autoupdate - missing update result on next launch (update un/succesful message, modal)
**Describe the bug**
User is not informed about the result of an update after relaunch.

**Info:**
 - Suite Version: any, app only (tested 21.1.0, commit ?)
 - OS: any (tested macOS 11.1 Big Sur)
 - Firmware Version: any (tested model T 2.3.5)

**Steps to reproduce:**
Precondition - update is available
1. Launch Suite and confirm update,
2. Select either update on next launch or update immediately,
3. Let either Suite relaunch or relaunch manually.

**Expected result:**
Suite displays an information about the result of the update (success, error) in form of a modal similar to how update is displayed, before entering passphrase etc.; would expect ~"update to version X succesful".

**Actual result:**
No info about update result displayed, either device connection prompt or wallet select modal is displayed.

**Screenshots:**
N/A since is doesn't exist

### PR DESCRIPTION
**Pull request by mroz22**
this should fix https://github.com/trezor/trezor-suite/issues/3308#issuecomment-875678618

### CODE REVIEW

File: packages/suite-desktop/src-electron/index.d.ts [hunk 1]
```diff
@@ -69,7 +69,7 @@ declare type WinBounds = {
 
 declare type UpdateSettings = {
     skipVersion: string;
-    preUpdateVersion?: string;
+    savedCurrentVersion?: string;
```
Comment (goodhoko) [inline packages/suite-desktop/src-electron/index.d.ts:78]: This would be a good place for a comment explaining what does this field contains and hopefully preventing the confusion you described [here](https://github.com/trezor/trezor-suite/pull/3946#discussion_r664330242).

Something like
```suggestion
    /**
      * Duplicates and persists `app.getVersion()` most of the time except the first app start after an update.
      * In that case it's used to detect an update to display a success notification to the user.
      * Use `app.getVersion()` to get the current version of the app.
      */
    savedCurrentVersion?: string;
```

File: packages/suite-desktop/src-electron/modules/auto-updater.ts [hunk 2]
```diff
@@ -46,18 +46,28 @@ const init = ({ mainWindow, store }: Dependencies) => {
...
-            `version of application before this launch: ${preUpdateVersion}, current app version: ${currentVersion}`,
+            `version of application before this launch: ${savedCurrentVersion}, current app version: ${currentVersion}`,
         );
-        if (preUpdateVersion && preUpdateVersion !== currentVersion) {
+        if (savedCurrentVersion && savedCurrentVersion !== currentVersion) {
             mainWindow.webContents.send('update/new-version-first-run', currentVersion);
+            store.setUpdateSettings({
+                ...updateSettings,
+                savedCurrentVersion: currentVersion,
+            });
```
Comment (goodhoko) [inline packages/suite-desktop/src-electron/modules/auto-updater.ts]: There should be no need for this because the store is updated few lines below regardless of the condition of this if-block.

**Review by goodhoko — CHANGES_REQUESTED** [review]
My apologies for not spotting the bug in the original PR.

File: packages/suite-desktop/src-electron/modules/auto-updater.ts (hunk 2 above)
Comment (mroz22) [reply packages/suite-desktop/src-electron/modules/auto-updater.ts]: uf of course. thanks.

**Review by goodhoko — APPROVED** [review]
LGTM!
