### PR TITLE
fix(suite): swap fees

### LINKED ISSUE #14838: Trading DEX - swap fee does not reflect reality
**Describe the bug**

It counts fees for "send" type transaction and not for transaction with swap data.

https://github.com/user-attachments/assets/f9004ca0-4773-4e64-860e-07de4ac31eee

### LINKED ISSUE #18060: Trading - Fee estimation from network failed. Using backup value.
**Describe the bug**  
When you try to trade many ERC20 tokens (e.g. EURT), you are constantly spammed by the notification:  
`Fee estimation from network failed. Using backup value.`

Since we now use sensible backups, the notification might not be necessary anymore.

**Info:**
 - Suite version: web 25.5.0 (e2c9eec19bb352d9e48e24061fcb5d6e675608f5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 3.0.0-bundled.25.4.1

**Screenshots:**

Image

**Note(s):**
https://satoshilabs.slack.com/archives/C04DD84P4A1/p1739451913097169

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Improve fee estimation so that fees in swap form and during tx signing are identical.

- adjust gas limit by `1.25` in swap form (same as in tx signing)
- don't refetch fees when not in swap form (except during tx signing)
- fetch fees for `preselectedQuote` (if selected) instead of first `DEX` quote

Additionally fix a bug where `fromAddress` parameter has not been included in quotes request payload.

## Related Issue

Resolve #14838 
Resolve #18060 

## Screenshots

Screenshot 2025-10-08 at 11 05 34

Screenshot 2025-10-08 at 11 05 42

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/fees&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/fees&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/fees&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/fees/feesUtils.ts [hunk 1]
```diff
@@ -18,6 +18,8 @@ const NETWORK_FEE_OVERRIDES: Record<
     },
 } as const;
 
+export const ETHEREUM_ADJUST_GAS_LIMIT = '1.25';
```
Comment (cermakjiri) [inline suite-common/wallet-core/src/fees/feesUtils.ts:21]: I understand it's not part this PR but how can it be a static value? Or where does it come from?

**Review by cermakjiri — APPROVED** [review]

File: suite-common/wallet-core/src/fees/feesUtils.ts (hunk 1 above)
Comment (TomasBoda) [reply suite-common/wallet-core/src/fees/feesUtils.ts:21]: There is a comment in `suite-common/trading/src/thunks/exchange/sendDexTransactionThunk.ts` that explains it:

Screenshot 2025-10-09 at 09 26 14

**Review by izmy — APPROVED** [review]
