### PR TITLE
Fix/coins

### LINKED ISSUE #4992: Click on right side of inactive coin "badge" opens custom backend settings
**Describe the bug**
Click on right side of inactive coin "badge" opens custom backend settings instead of activating the coin.

**How to reproduce**

1. Go to Settings/Crypto
2. Click on the right side of the Coin "badge"

**Expected behavior**
Coin should be activated.

**Screenshots**

https://user-images.githubusercontent.com/3729633/155514367-ed6ff1fd-0dc9-418c-8bf0-816196a45a19.mov

### LINKED ISSUE #5001: Custom backend info is still visible after coin is disabled
**Describe the bug**
We show Electrum custom backend as disconnected even when the coin is turned off.

**Steps to reproduce:**
1. Set up Customer Electrum server
2. Disable bitcoin
3. Enable another coin

**Info:**
 - Suite version: desktop 22.3.0 (8fed4ff9336a4f9c7eef5d7ef29943c66208ad12)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.3.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: model T 2.4.4 regular

**Expected result:**
No custom backend is shown? Or maybe some other indication that the coin is turned of?
image

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by tomasklim**
closes #5001, #4992

**additional issue**
- user is on mobile
- user has custom backend set for coin available only for TT
- user is now on T1
   - user can now edit/delete custom backend 
   
**another issue**
- on touch device if you click on the right side of the active coin "badge" it will open the settings instead of deactivating the coin

### CODE REVIEW

File: packages/suite/src/components/suite/Coin/index.tsx [hunk 1]
```diff
@@ -27,6 +30,12 @@ const SettingsWrapper = styled.div<{ onClick: ((e: React.MouseEvent) => void) |
                 )};
             }
         `}
+
+    ${props =>
+        !props.toggled &&
+        css`
+            pointer-events: none;
```
Comment (matejkriz) [inline packages/suite/src/components/suite/Coin/index.tsx:37]: there is one more issue - on touch device if you click on the right side of the **active** coin "badge" it will open the settings instead of deactivating the coin

Comment (marekrjpolak) [reply packages/suite/src/components/suite/Coin/index.tsx:37]: Oh, you're right.

Comment (tomasklim) [reply packages/suite/src/components/suite/Coin/index.tsx:37]: on it

Comment (tomasklim) [reply packages/suite/src/components/suite/Coin/index.tsx:37]: a8cbcc66f1791e0907ebd56df69e999129302f4d ?

**Review by marekrjpolak — APPROVED** [review]
:+1:

File: packages/suite/src/components/suite/Coin/index.tsx (hunk 1 above)
Comment (matejkriz) [reply packages/suite/src/components/suite/Coin/index.tsx:37]: I'm not sure about the `and (pointer: coarse)` part, why not only `@media (hover: none)`?

Comment (marekrjpolak) [reply packages/suite/src/components/suite/Coin/index.tsx:37]: It's already done.

**Review by matejkriz — APPROVED** [review]
👍
