### PR TITLE
fix(suite): setting PIN during BTC-only onboarding

### LINKED ISSUE #22600: T2B1: cannot finish the onboarding when PIN is set on BTC only
Video here:
- wiped device with BTC only FW (tested T2B1, TS5)
- go to onboarding
- set pin
- back at the beginning of the onboarding

https://github.com/user-attachments/assets/c215a6c5-2823-480b-b9e8-ab10ce238f07

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Very strange bug, where after successful PIN setup, `@modal/context-device` (`ButtonRequest_Success`) is hanging for apx. 300 milliseconds, before Connect emits the `UI_REQUEST.CLOSE_UI_WINDOW` and Suite clears the modal context to `@modal/context-none`. But in the meantime, `goTo('suite-index')` has failed :grimacing: 

On Web, `UI_REQUEST.CLOSE_UI_WINDOW` is sent instantly so navigation is not blocked.

## Related Issue

Resolve #22600

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/btc-only-onboarding&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/btc-only-onboarding&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/PinStep.tsx [hunk 1]
```diff
@@ -46,12 +46,6 @@ export const PinStep = () => {
         setPin('');
     };
 
-    useEffect(() => {
-        if (status === 'success') {
-            goToNextStep();
-        }
-    }, [status, goToNextStep]);
```
Comment (Lemonexe) [inline packages/suite/src/views/onboarding/steps/PinStep.tsx:53]: just incidental cleanup

**Review by seibei-iguchi — APPROVED** [review]
