### PR TITLE
Fix Select scroll to selected option

### LINKED ISSUE #18749: Select - scroll to selected item
## Description

After selecting specific option from `Select` component, scroll to the selected option/option's group header.

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Important changes:
- network and token info for buy/sell/swap are loaded independently
- while the options are being loaded, select is disabled and loader is displayed
- selected option is persisted and scrolled to upon opening the select dropdown

## Related Issue

Resolve #18749 

## Screenshots:

https://github.com/user-attachments/assets/b03e089e-500f-4bcf-a19e-bde96994b7ba

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/select&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/select&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/select&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx [hunk 1]
```diff
@@ -37,6 +38,11 @@ export const TradingFormInputAccount = <
     } = useTradingFormContext<TradingTradeSellExchangeType>();
     const optionGroups = useTradingBuildAccountGroups(type);
 
+    const exchangeInfo = useSelector(state => state.wallet.tradingNew.exchange.exchangeInfo);
+    const sellInfo = useSelector(state => state.wallet.tradingNew.sell.sellInfo);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx]: there should be `isLoading` in `tradingNew`. Can it be used or not?

Comment (tomasklim) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx]: because in case fetch fails, it will be stuck in loading state

File: suite-common/trading/src/thunks/common/__tests__/loadInitialDataThunk.test.ts [hunk 2]
```diff
@@ -213,51 +181,6 @@ describe('loadInitialDataThunk', () => {
         await testUpdatedInfoData('outdated');
     });
 
-    it('should keep same version of data without update', async () => {
```
Comment (tomasklim) [inline suite-common/trading/src/thunks/common/__tests__/loadInitialDataThunk.test.ts]: are there test covering the logic after changes?

File: suite-common/trading/src/thunks/common/loadInitialDataThunk.ts [hunk 3]
```diff
@@ -42,7 +42,7 @@ export const loadInitialDataThunk = createThunk(
 
         dispatch(tradingActions.setTradingActiveSection(activeSection));
 
-        if (account && !isLoading && (isDifferentAccount || areDataOutdated)) {
+        if (account && !isLoading) {
```
Comment (adderpositive) [inline suite-common/trading/src/thunks/common/loadInitialDataThunk.ts]: `invityAPI.getInfo()` will be called every time, regardless of whether the data is outdated or is for a different account.

File: suite-common/trading/src/thunks/common/loadInitialDataThunk.ts [hunk 4]
```diff
@@ -58,19 +58,22 @@ export const loadInitialDataThunk = createThunk(
                 dispatch(tradingActions.saveInfo(info));
             }
 
-            if (isDifferentAccount || !buyInfo) {
+            if (activeSection === 'buy' && (isDifferentAccount || !buyInfo || areDataOutdated)) {
```
Comment (adderpositive) [inline suite-common/trading/src/thunks/common/loadInitialDataThunk.ts]: `activeSection === 'buy'` should not be here. I got your point, but it will not work for another part of the suite, when we need to get data regardless of the `activeSection`, for example, `TokenList` page - `Swap` will be unavailable unless you visit Swap in the trading before.

image

File: packages/components/src/components/form/Select/customComponents.tsx [hunk 5]
```diff
@@ -22,23 +25,37 @@ export const Control = ({ 'data-testid': dataTest, ...controlProps }: ControlCom
...
-                }`,
-            } as OptionProps<OptionType, boolean>['innerProps']
+export const Option = ({
+    selectedOption,
+    'data-testid': dataTest,
+    ...props
+}: OptionComponentProps) => {
+    const ref = useRef<HTMLDivElement>();
+
+    useEffect(() => {
```
Comment (adderpositive) [inline packages/components/src/components/form/Select/customComponents.tsx]: `useDeepCompareEffect` should solve the problem with creating a new `deepEqual` function.

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx (hunk 1 above)
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx]: For `exchangeInfo`, `sellInfo`, and `buyInfo` are prepared selectors, which transform values correctly.

`selectTradingExchangeInfo`
`selectTradingSellInfo`
`selectTradingBuyInfo`

Please use them if they are necessary.

Comment (adderpositive) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx]: For loading info from the API (common info, buyInfo, sellInfo, exchangeInfo) serves `isLoading` at the top of the trading root. 
You can use the `selectTradingLoadingAndTimestamp` selector for that.

There is also `isLoading` in the sub-reducers (buy, sell, exchange) used for loading quotes.

File: packages/components/src/components/form/Select/Select.tsx [hunk 6]
```diff
@@ -346,34 +314,14 @@ export const Select = ({
...
-                options: group.options.map((option: Option) => ({
-                    ...option,
-                    [OPTION_INDEX_NAME]: index,
-                })),
-            }));
-        }
 
-        return rest.options?.map((option, index) => ({ ...option, [OPTION_INDEX_NAME]: index }));
-    }, [rest.options, isGrouped]);
+    const [selectedOption, setSelectedOption] = useState<any>(rest.value);
```
Comment (adderpositive) [inline packages/components/src/components/form/Select/Select.tsx]: `any`? Can we use `Option | undefined` or something like that?

File: suite-common/trading/src/thunks/common/__tests__/loadInitialDataThunk.test.ts (hunk 2 above)
Comment (TomasBoda) [reply suite-common/trading/src/thunks/common/__tests__/loadInitialDataThunk.test.ts]: added tests for the separate loading of buy/sell/exchange sections

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx (hunk 1 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx]: yes it can, changed it

**Review by adderpositive — CHANGES_REQUESTED** [review]
1. UX - It would be nice to also see under what account it belongs to. What do you think? But I am not sure if there will be, for example, 20 coins under one account…
image

2. Sometimes the scrolling is jumping, check the video.
https://github.com/user-attachments/assets/83b2e468-3410-400c-9bc9-350f883203be

3. I don't understand changes in trading. 🤷‍♂️ Why the changes?

File: suite-common/trading/src/thunks/common/loadInitialDataThunk.ts (hunk 4 above)
Comment (TomasBoda) [reply suite-common/trading/src/thunks/common/loadInitialDataThunk.ts]: you're right, thanks for the catch. It doesn't make sense to load `activeSection` only then, I reverted it back to as it was before

File: packages/components/src/components/form/Select/customComponents.tsx (hunk 5 above)
Comment (TomasBoda) [reply packages/components/src/components/form/Select/customComponents.tsx]: It doesn't work, it scrolls to the very bottom of the dropdown everytime for some reason. I kept the `deepEqual`

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx (hunk 1 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx]: I am now using the `isLoading` state for this

File: packages/components/src/components/form/Select/Select.tsx (hunk 6 above)
Comment (TomasBoda) [reply packages/components/src/components/form/Select/Select.tsx]: done

**Comment by TomasBoda** [comment]
> 1. UX - It would be nice to also see under what account it belongs to. What do you think? But I am not sure if there will be, for example, 20 coins under one account…
>    image
> 2. Sometimes the scrolling is jumping, check the video.
>    https://github.com/user-attachments/assets/83b2e468-3410-400c-9bc9-350f883203be
> 3. I don't understand changes in trading. 🤷‍♂️ Why the changes?

1. This was my intention from the start, but as token info is loading for a few tens of seconds after the select is ready, it refreshes the options and makes it difficult to handle scrolling in the select. The current solution is the only one that works at least somehow consistently
2. I fixed the jumping to some extent
3. The changes were intended to load the sections separately, but as you pointed out, it causes problems, so I reverted it for the time being

File: suite-common/trading/src/thunks/common/__tests__/loadInitialDataThunk.test.ts (hunk 2 above)
Comment (TomasBoda) [reply suite-common/trading/src/thunks/common/__tests__/loadInitialDataThunk.test.ts]: I reverted the separate loading of sections, because it caused issues in other parts of Suite. Now the select works even though they are loaded all at once, so the tests stay the same as they were

File: packages/components/src/components/form/Select/customComponents.tsx (hunk 5 above)
Comment (adderpositive) [reply packages/components/src/components/form/Select/customComponents.tsx]: Maybe `useDeepCompareEffect` is for a bit different use case. Sorry for misleading.

File: packages/components/src/components/form/Select/customComponents.tsx [hunk 7]
```diff
@@ -22,23 +25,38 @@ export const Control = ({ 'data-testid': dataTest, ...controlProps }: ControlCom
...
```
Comment (adderpositive) [inline packages/components/src/components/form/Select/customComponents.tsx]: Replaced with `useDeepCompareEffect`, it should prevent jumping in the select list

**Review by adderpositive — CHANGES_REQUESTED** [review]
Thank you for the updates. Select list still jumps a bit.

**Review by adderpositive — APPROVED** [review]
