### PR TITLE
Fix multiple cardano isssues

### LINKED ISSUE #21043: Cardano: pending transaction should be called unconfirmed to avoid incorrect textation
When sending tokens, staking,... It says `Sending ADA`
Let's use `TR_UNCONFIRMED_TX_LONG` and improve `Amount` section

Image
Image
Image

### LINKED ISSUE #21047: Cardano: tokens are not mentioned in tx heading
For Cardano, when building the header. Check tokens first

Image

Image

Image

### LINKED ISSUE #21182: Cardano: tx page is horizontally scrollable
Probably caused by address component

https://github.com/user-attachments/assets/556fb165-e345-45e1-bb89-85f743222470

### LINKED ISSUE #21183: Cardano: tx detail sent to self amount
**Describe the bug**

- tx list `Sent to self` copies `FEE`. Hide it, remove it.
- tx detail `Amount` is zero but it copies fee and is positive.

Image

Image

### LINKED ISSUE #21189: Cardano: remove encoded name from token detail
Policy id is mentioned twice. Remove the longer one (first) as it is policy id + encoded name

Image

### PR DESCRIPTION
**Pull request by matusbalascak**
## Description

This PR fixes multiple issues connected to Cardano network.

## Related Issue

Resolve #21189
Resolve #21182
Resolve #21043 
Resolve #21047 
Resolve #21183

### #21043 
image
image

### #21047 
image

### #21189 
image

### #21183 
image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/cardano-issues&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/cardano-issues&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/cardano-issues&lookback=7)

### CODE REVIEW

**Review by TomasBoda — CHANGES_REQUESTED** [review]
I think we can use `Unconfirmed transaction` instead of `Sending ADA` in the pending transaction, as we use it for e.g. `Base`:

Screenshot 2025-09-23 at 10 01 34

Also in the tx detail modal:

Screenshot 2025-09-23 at 10 03 25

File: packages/suite/src/views/wallet/transactions/TransactionList/TransactionsGroup/PendingGroupHeader.tsx [hunk 1]
```diff
@@ -1,14 +1,21 @@
...
-        <InfoSegments>
-            <Translation id="TR_PENDING_TX_HEADING" values={{ count: txsCount }} />
-            {txsCount}
-        </InfoSegments>
-    </Text>
-);
+export const PendingGroupHeader = ({ txsCount, networkType }: PendingGroupHeaderProps) => {
+    const translationId = ['ethereum', 'cardano'].includes(networkType)
+        ? 'TR_UNCONFIRMED_TX_LONG'
+        : 'TR_PENDING_TX_HEADING';
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/transactions/TransactionList/TransactionsGroup/PendingGroupHeader.tsx]: I think we can use `TR_PENDING_TX_HEADING` as it was and add `TR_UNCONFIRMED_TX_LONG` to the `ADA` tx card.

**Review by TomasBoda — CHANGES_REQUESTED** [review]

File: packages/suite-desktop-core/e2e/support/pageObjects/stakingSection.ts [hunk 2]
```diff
@@ -20,6 +20,7 @@ export class StakingSection {
     readonly unstakeButton: Locator;
     readonly speedUpButton: Locator;
     readonly pendingTransactionText: Locator;
+    readonly unconfirmedTransactionText: Locator;
```
Comment (Vere-Grey) [inline packages/suite-desktop-core/e2e/support/pageObjects/stakingSection.ts]: Rather then adding another locator, we need to replace the original. And replace all its uses.
In tests we first check for visibility of the now unconfirmed transaction and later that is gone. 
I have noticed that you did update only the first part, that it is visible and the second on is falsely passing. Because it is rellying on the old locator which never was there in first place.
```suggestion
    readonly unconfirmedTransactionText: Locator;
````

File: packages/suite-desktop-core/e2e/support/pageObjects/stakingSection.ts [hunk 3]
```diff
@@ -66,6 +67,7 @@ export class StakingSection {
         this.unstakeButton = this.page.getByTestId('@modal/staking/unstake-button');
         this.speedUpButton = this.page.getByTestId('@transaction-item/bump-fee-button');
         this.pendingTransactionText = this.page.getByText('Pending transaction•1');
+        this.unconfirmedTransactionText = this.page.getByText('Unconfirmed transaction•1');
```
Comment (Vere-Grey) [inline packages/suite-desktop-core/e2e/support/pageObjects/stakingSection.ts]:
```suggestion
        this.unconfirmedTransactionText = this.page.getByText('Unconfirmed transaction•1');
```

File: packages/suite-desktop-core/e2e/tests/staking/initial-stake.test.ts [hunk 4]
```diff
@@ -143,7 +143,7 @@ test.describe('ETH staking', { tag: ['@group=staking'] }, () => {
             });
 
             await test.step('Verify pending transaction', async () => {
-                await expect(stakingSection.pendingTransactionText).toBeVisible();
```
Comment (Vere-Grey) [inline packages/suite-desktop-core/e2e/tests/staking/initial-stake.test.ts:146]: later in tests there is `                await expect(stakingSection.pendingTransactionText).toBeHidden();
` which need to use the same new locator you have added.

File: packages/suite-desktop-core/e2e/tests/staking/stake-more.test.ts [hunk 5]
```diff
@@ -136,7 +136,7 @@ test.describe('ETH staking', { tag: ['@group=staking'] }, () => {
             });
 
             await test.step('Verify pending transaction', async () => {
-                await expect(stakingSection.pendingTransactionText).toBeVisible();
+                await expect(stakingSection.unconfirmedTransactionText).toBeVisible();
```
Comment (Vere-Grey) [inline packages/suite-desktop-core/e2e/tests/staking/stake-more.test.ts]: later in tests there is `                await expect(stakingSection.pendingTransactionText).toBeHidden();
` which need to use the same new locator you have added.

File: packages/suite-desktop-core/e2e/tests/staking/unstake.test.ts [hunk 6]
```diff
@@ -104,7 +104,7 @@ test.describe('ETH unstaking and claim', { tag: ['@group=staking'] }, () => {
             });
 
             await test.step('Verify pending transaction', async () => {
-                await expect(stakingSection.pendingTransactionText).toBeVisible();
+                await expect(stakingSection.unconfirmedTransactionText).toBeVisible();
```
Comment (Vere-Grey) [inline packages/suite-desktop-core/e2e/tests/staking/unstake.test.ts]: later in tests there is `                await expect(stakingSection.pendingTransactionText).toBeHidden();
` which need to use the same new locator you have added.

**Review by Vere-Grey — DISMISSED** [review]
Please update 3 more asserts that would always pass. More in comments

File: packages/components/src/components/form/InputButton/InputButton.tsx [hunk 7]
```diff
@@ -26,6 +26,8 @@ const Wrapper = styled.div<{ $elevation: Elevation }>`
     border-radius: ${borders.radii.full};
     background: ${({ theme, $elevation }) =>
         mapElevationToButtonOnBackground({ elevation: $elevation, theme, state: 'normal' })};
+    overflow-x: hidden;
```
Comment (tomasklim) [inline packages/components/src/components/form/InputButton/InputButton.tsx:29]: @jvaclavik is this fix ok?

File: packages/suite/src/components/wallet/TransactionItem/TransactionHeading.tsx [hunk 8]
```diff
@@ -188,7 +188,7 @@ export const TransactionHeading = ({
                 </ChevronIconWrapper>
             </Wrapper>
 
-            {transaction.type !== 'failed' && amount}
+            {transaction.type !== 'failed' && transaction.type !== 'self' && amount}
```
Comment (tomasklim) [inline packages/suite/src/components/wallet/TransactionItem/TransactionHeading.tsx:191]: how about also token sent to self?

File: packages/components/src/components/form/InputButton/InputButton.tsx [hunk 9]
```diff
@@ -53,6 +55,9 @@ const Input = styled.input<{ $width: number }>`
 
 const InputWrapper = styled(motion.div)`
     overflow: hidden;
+    min-width: 0;
+    max-width: 100%;
```
Comment (jvaclavik) [inline packages/components/src/components/form/InputButton/InputButton.tsx]: why do you need this? I guess this should be standard behaviour 🤷‍♂️

File: packages/components/src/components/form/InputButton/InputButton.tsx (hunk 7 above)
Comment (jvaclavik) [reply packages/components/src/components/form/InputButton/InputButton.tsx:29]: I'm not sure, what was reason for this change @matusbalascak?

Comment (matusbalascak) [reply packages/components/src/components/form/InputButton/InputButton.tsx:29]: #21182 - it fixes this

The hidden placeholder was causing horizontal overflow in the collapsed state, which allowed the content to be scrolled sideways. Adding `overflow-x: hidden` on the wrapper prevents that.

File: packages/components/src/components/form/InputButton/InputButton.tsx (hunk 9 above)
Comment (matusbalascak) [reply packages/components/src/components/form/InputButton/InputButton.tsx]: You're right, we don't need that.

**Review by tomasklim — APPROVED** [review]
LGTM. One small bug which can be addressed in next issue. Maybe it is problem in data itself, not display logic

Screenshot 2025-09-25 at 12 27 14

Screenshot 2025-09-25 at 12 26 52

Screenshot 2025-09-25 at 12 24 34

**Review by TomasBoda — APPROVED** [review]
