### PR TITLE
fix(android): Fix Android text input

### LINKED ISSUE #6373: Account name field doesn't show text input
**Describe the bug**
Tapping on the account name field and entering text does not render any content

**Info:**
-   OS: Android
-   Version: 22.8.0 (119)

**How to reproduce**
1. Open app
2. Click 'Use dev xPub'
3. Tap 'Account label'
4. Start typing

**Expected behavior**
* Blinking cursor
* Content to appear after keyboard entry

**Screenshots**
https://user-images.githubusercontent.com/216917/191767967-df346521-e328-4a1b-8a9e-06c401f873d2.mp4

### PR DESCRIPTION
**Pull request by bouchja1**
## Description

Tapping on the account name field and entering text renders content now. It was broken on Android.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/6373

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/2227592/193010249-a5d0b29c-b168-4126-a650-5588c55d4404.mov

### CODE REVIEW

**Review by juriczech — APPROVED** [review]

File: suite-native/atoms/src/Input/Input.tsx [hunk 1]
```diff
@@ -73,12 +73,13 @@ const inputStyle = prepareNativeStyle(utils => ({
     ...utils.typography.body,
     alignItems: 'center',
     justifyContent: 'center',
-    height: INPUT_TEXT_HEIGHT + INPUT_WRAPPER_PADDING_VERTICAL,
+    height: INPUT_TEXT_HEIGHT,
     color: utils.colors.gray700,
-    lineHeight: 0,
     borderWidth: 0,
     flex: 1,
-    paddingTop: INPUT_WRAPPER_PADDING_VERTICAL,
```
Comment (Nodonisko) [inline suite-native/atoms/src/Input/Input.tsx:81]: I am not sure about this, I introduced this padding because I wanted input to fill all possible space, so if you click anywhere it will focus. Please add some temp border to it and check if it's filling whole space from top to bottom

Comment (bouchja1) [reply suite-native/atoms/src/Input/Input.tsx:81]: I would solve this with hitSlop so I increased top slop 34a49f8a5a9bdc0551381d2eb7664cc5caeb470d. Your solution worked on iOS but did not show any text on Android.

**Review by Nodonisko — APPROVED** [review]
