### PR TITLE
fix(suite): add scrolling to every tx-output that needs to be confirmed on the device

### LINKED ISSUE #9816: Send dialogue does not auto scroll when sending to multiple recipients.
**Describe the bug**
Send dialogue does not auto scroll when sending to multiple recipients.
It only scrolls to bottom after all recipients are confirmed,
See video.

Same results with 23.11.1  

**Steps to reproduce:**
1. Send one transaction to multiple recipients
2. Observe `Confirm on Trezor` behavior during confirming amounts and addresses of recipients 

**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.0 regular (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/b8636f80-1eab-4808-bd80-4a0a7ebfcedf

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

Adds scrolling  when sending to multiple recipients

## Related Issue 

Resolve https://github.com/trezor/trezor-suite/issues/9816

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx [hunk 1]
```diff
@@ -18,6 +18,7 @@ import type {
 import { getOutputState } from 'src/utils/wallet/reviewTransactionUtils';
 import { TransactionReviewTotalOutput } from './TransactionReviewTotalOutput';
 import { ReviewOutput } from 'src/types/wallet/transaction';
+import { log } from 'console';
```
Comment (prusnak) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx]: not needed - also the reason why CI fails

Comment (peter-sanderson) [reply packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutputList.tsx]: :heavy_check_mark:

File: packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutput.tsx [hunk 2]
```diff
@@ -32,172 +32,175 @@ export type TransactionReviewOutputProps = {
     account: Account;
 } & ReviewOutput;
 
-export const TransactionReviewOutput = (props: TransactionReviewOutputProps) => {
-    const { type, state, label, value, symbol, token, account } = props;
-    let outputLabel: ReactNode = label;
-    const { networkType } = account;
+export const TransactionReviewOutput = forwardRef<HTMLDivElement, TransactionReviewOutputProps>(
+    (props, ref) => {
```
Comment (dahaca) [inline packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewOutput.tsx:36]: nit:

```suggestion
    ({ type, state, label, value, symbol, token, account }, ref) => {
```

**Review by dahaca — APPROVED** [review]
