### PR TITLE
Fix(suite): THP modals

### LINKED ISSUE #19614: THP: Modal shall not have cancelable background
All THP modals have "cancelable background" enabled — meaning if you click on the background, the modal closes (and probably sends a cancel action — though I haven’t verified that). Either way, it's pretty undesirable. For example, when you're pairing a Bluetooth device, the BT settings open on top of Suite, and if you try to refocus on Suite by clicking into it, you end up canceling the whole process.

### LINKED ISSUE #20911: THP: Cannot cancel ThpConnectionModal
**Describe the bug**

Cannot cancel the modal "Securely connect with your Trezor" from suite side, it leaves it hanging and you have to reload suite 

**Info:**

- Remembered Wallet: no
- Suite Version: `feat/bt-thp` 1bbaf15f
- OS: Ubuntu 22.04 LTS
- Bridge: node bridge
- Firmware Version: TS7 2.9.0, revision ec4123667f852d52caae693e14235e48c9bbc29c

**How to reproduce**

1. start pairing THP device by cable
2.  cancel at this step:

Image

### LINKED ISSUE #20912: THP: Device image missing when THP pairing for the first time
**Describe the bug**

Device image is missing at `ThpConnectionModal` on cable when pairing for the first time, because this is _during_ device acquisition, it has no been acquired so it has no `features`, so Suite does not yet know `internal_model`.
 
👉 that's why we have [the unknown device image placeholder](https://github.com/trezor/trezor-suite/blob/e6c74f1ac3bbbaf9c2279038b6e428ad35f89651/packages/suite-data/files/images/svg/device_confirm_trezor_unknown.svg), so use it.

**Info:**

- Remembered Wallet: no
- Suite Version: `feat/bt-thp` 1bbaf15f
- OS: Ubuntu 22.04 LTS
- Bridge: node bridge
- Firmware Version: TS7 2.9.0, revision ec4123667f852d52caae693e14235e48c9bbc29c

**How to reproduce**

1. start pairing THP device by cable
2. see this modal, it's looking weird because there should be device image:

Image

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Small fixes for THP modals:
- make background **not** cancellable
- fix cancelling from suite-side on `ThpConnectionModal`
- fix `ThpConnectionModal` missing device image

## Related Issue

Resolve #19614
Resolve #20911
Resolve #20912

## Screenshots:

Concerning #20912:

Before:
Image

After:
Image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/thp-modals&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/thp-modals&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/DeviceConfirmImage.tsx [hunk 1]
```diff
@@ -1,17 +1,14 @@
...
     device: Pick<Device, 'features' | 'thp'>;
 };
 
 export const DeviceConfirmImage = ({ device }: DeviceConfirmImageProps) => {
-    const deviceModelInternal = getDeviceInternalModel(device);
-
-    if (!deviceModelInternal) {
-        return null;
-    }
+    const deviceModelInternal = getDeviceInternalModel(device) ?? DeviceModelInternal.UNKNOWN;
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/DeviceConfirmImage.tsx:11]: :clap:

**Review by peter-sanderson — APPROVED** [review]
