### PR TITLE
fix(suite): when switching the device, make sure that the correspondi…

### LINKED ISSUE #4465: Account does not exist often displayed in Suite
**Describe the bug**

`Account does not exist ` is often displayed in Trezor Suite.
So far i was not able to find reason how and why it's happening. But it occurs since i remember.
Of course reload/restart or reconnection of device helps. Attached log generated by Suite.

**Info:**
 - Suite version: desktop 21.11.0 (4a56ae794159091a4f2c4de847d237a47657dc1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**
Screenshot 2021-11-06 at 9 36 55

obrazek

[trezor-suite-log.txt](https://github.com/trezor/trezor-suite/files/7490110/trezor-suite-log.txt)

### PR DESCRIPTION
**Pull request by vojtatranta**
…ng account exists on the other device wallet

## Description

When you are in a device / wallet on /btc/4/ account and you switch to a different device / wallet that doesn't have /btc/4 but like just 1 btc account, it ended up in "Accout not found".

In this PR, I first check if that account existss

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/4465

### CODE REVIEW

File: packages/suite/src/views/suite/SwitchDevice/DeviceItem/WalletInstance.tsx [hunk 1]
```diff
@@ -78,8 +80,23 @@ export const WalletInstance = ({
...
               if (!editing) {
+                  const nextDeviceAccounts = instance.state
+                      ? getAccountsByDeviceState(accounts, instance.state)
+                      : [];
+
+                  // NOTE: attempt to determine, if the currently selected account
+                  // has a corresponding account in the next device accounts
+                  // if not, enforce switching URL to dashboard
+                  const nextAccount = nextDeviceAccounts.find(
+                      account =>
```
Comment (vojtatranta) [inline packages/suite/src/views/suite/SwitchDevice/DeviceItem/WalletInstance.tsx:91]: is this correct way of finding "correspoding" accout to switch to?

File: packages/suite/src/actions/wallet/addWalletThunk.ts [hunk 2]
```diff
@@ -16,10 +16,23 @@ import { getBackgroundRoute } from 'src/utils/suite/router';
...
 
-export const redirectAfterWalletSelectedThunk = createThunk<void, void, void>(
+export const redirectAfterWalletSelectedThunk = createThunk<
+    void,
+    { forceDeviceDashboard?: boolean },
+    void
+>(
     `${DEVICE_MODULE_PREFIX}/redirectAfterWalletSelectedThunk`,
-    async (_, { dispatch }) => {
+    async ({ forceDeviceDashboard }, { dispatch }) => {
```
Comment (vojtatranta) [inline packages/suite/src/actions/wallet/addWalletThunk.ts]: This thunk was written by @seibei-iguchi I am not sure what it was suppose to do though.

Comment (vojtatranta) [reply packages/suite/src/actions/wallet/addWalletThunk.ts]: Yeah, in some cases, it went to dashboard.

**Review by seibei-iguchi — APPROVED** [review]

**Comment by STew790** [comment]
**QA NOK**
Unfortunately, I can still see the issue.
Switching from taproot account in passphrase to standard wallet (where the taproot is not present)
image

**Info:**
 - Suite version: web 25.4.0 (f255b2a9ec8d60b29239e27934815c31874d7275)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T2T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: WebUsbTransport

**Comment by vojtatranta** [comment]
> **QA NOK** Unfortunately, I can still see the issue. Switching from taproot account in passphrase to standard wallet (where the taproot is not present) image
> 
> **Info:**
> 
> * Suite version: web 25.4.0 ([f255b2a](https://github.com/trezor/trezor-suite/commit/f255b2a9ec8d60b29239e27934815c31874d7275))
> * Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
> * OS: Linux x86_64
> * Screen: 3440x1440
> * Device: Trezor T2T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
> * Transport: WebUsbTransport

fix here https://github.com/trezor/trezor-suite/pull/17748

**Comment by bosomt** [comment]
**QA OK**

🎉 !!!

**Info:**
 - Suite version: web 25.4.0 (e5ccc0c45bf1c935d6c0c030e02452d2cacf234a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3B1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 2.0.33
