### PR TITLE
fix(suite): initialRun not completed by going to settings

### LINKED ISSUE #5861: Analytics is disabled in fresh app on navigating to Settings
**Describe the bug**
In the fresh app, if a user goes to settings before giving us consent to use analytics/sentry. The analytics consent step is skipped and analytics is not working.

**Info:**

- In 22.6.x it is disabled in settings
- In <22.6.x it looks enabled but it is not reporting

**How to reproduce**

1. Reset app
1. Go to settings
1. Connect device
1. You are in the app without giving us consent

**Why**
`@suite/set-flag` - `initialRun` is set to false on navigating to settings 

- [ ] Together with fix please create e2e test

### PR DESCRIPTION
**Pull request by tomasklim**
closes #5861

We should create a follow-up issue and refactor whole router and fullscreen/foreground apps logic.

If a user navigates to settings on the welcome page, he is navigated to Settings after exiting onboarding.

### CODE REVIEW

File: packages/suite/src/components/suite/SuiteLayout/index.tsx [hunk 1]
```diff
@@ -110,7 +111,7 @@ export const SuiteLayout = ({ children }: SuiteLayoutProps) => {
 
     // Setting screens are available even if the device is not connected in normal mode
     // but then we need to hide NavigationBar so user can't navigate to Dashboard and Accounts.
-    const isNavigationBarVisible = device?.mode === 'normal';
+    const isNavigationBarVisible = device?.mode === 'normal' && !initialRun;
```
Comment (matejkriz) [inline packages/suite/src/components/suite/SuiteLayout/index.tsx:114]: Why this change?

Comment (matejkriz) [reply packages/suite/src/components/suite/SuiteLayout/index.tsx:114]: Ahh, now I get it 👌

**Comment by matejkriz** [comment]
EDIT: resolved ✅ 

get stucked between Settings <-> Security check

https://user-images.githubusercontent.com/3729633/182358854-dde4d90c-b86a-49a3-a98f-c91c6d114da1.mov

**Review by matejkriz — APPROVED** [review]
🎉

**Comment by bosomt** [comment]
@tomasklim  found one behavior thats  probably not expected.
EDIT: its expected, this behavior is only when device is already initialized, when fresh device onboarding ends in dashboard.  


1. leave settings
2. initalRun is started again
3. after you finish "onboarding" you are navigated to `Settings`

please see video and confirm that its expected or we need another issue or you will change it.
https://youtu.be/EoRt0fZNJ9o

**Comment by matejkriz** [comment]
getting back preserving params on "redirection" back to Suite https://github.com/trezor/trezor-suite/pull/6146
