### PR TITLE
fix(suite): normalize the color of the unacquired device to 1 if unde…

### LINKED ISSUE #21394: Confirmation pill layout modal
Should be aligned properly.
Image

### PR DESCRIPTION
**Pull request by vojtatranta**
…fined as well as acquired device

## Description

The `faetures.unit_color` is normalized, but this is unavailable when the device  is unacquired. So this PR also normalizes the `thp.properties.model_variant`

## Related Issue

Resolve  https://github.com/trezor/trezor-suite/issues/21394#issuecomment-3306160274

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=normalize-thp-properties-model-variant&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=normalize-thp-properties-model-variant&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=normalize-thp-properties-model-variant&lookback=7)

### CODE REVIEW

**Comment by martykan** [comment]
I would say this should be handled in [getDeviceColorVariant](https://github.com/trezor/trezor-suite/blob/6ffac4a0291b39d1db3983a4f418fca8e01c7cef/suite-common/suite-utils/src/device.ts#L459), not THP logic in Connect

**Review by mroz22 — CHANGES_REQUESTED** [review]
agreed

**Comment by vojtatranta** [comment]
> I would say this should be handled in [getDeviceColorVariant](https://github.com/trezor/trezor-suite/blob/6ffac4a0291b39d1db3983a4f418fca8e01c7cef/suite-common/suite-utils/src/device.ts#L459), not THP logic in Connect

kk, AI wrongly adviced

**Comment by vojtatranta** [comment]
> I would say this should be handled in [getDeviceColorVariant](https://github.com/trezor/trezor-suite/blob/6ffac4a0291b39d1db3983a4f418fca8e01c7cef/suite-common/suite-utils/src/device.ts#L459), not THP logic in Connect

btw. are you aware of this https://github.com/trezor/trezor-suite/pull/21573/files#diff-ca03cc83fb0e3d98908b763de7901b240e15b59ba046942b514f98801f3a8afaR878

Which is similar "normlization" in done in connect and that seem to be okay, at least according to Marek?

**Comment by martykan** [comment]
Wasn't aware, I'd suggest getting rid of that as well.

**Comment by vojtatranta** [comment]
> Wasn't aware, I'd suggest getting rid of that as well.

I think the alternative then, is to call the util FN to get the normalize color at every instance of trying to get the color of the device, that IMHO, isn't great, don't you think?

I'd like to point out that my original suggestion of how to fix this was to simply created a new file with the image and video with corresponding name (with 0 as variant color) so that we wouldn't have to deal with these problems.

So you guys want to have the util be called everywhere, is that correct?

**Comment by vojtatranta** [comment]
> > Wasn't aware, I'd suggest getting rid of that as well.
> 
> I think the alternative then, is to call the util FN to get the normalize color at every instance of trying to get the color of the device, that IMHO, isn't great, don't you think?
> 
> I'd like to point out that my original suggestion of how to fix this was to simply created a new file with the image and video with corresponding name (with 0 as variant color) so that we wouldn't have to deal with these problems.
> 
> So you guys want to have the util be called everywhere, is that correct?

I agree it is cleaner, I know that the main problem is "rotating device" image. So hopefully, putting it there will solve it.

But again, I don't think it is that important, this bug is there only for the testing units.

**Comment by mroz22** [comment]
what about doing all the normalizations somewhere around here? https://github.com/trezor/trezor-suite/blob/feat/suite-start-bt-notif/packages/connect/src/device/Device.ts#L1023 🤔

**Comment by vojtatranta** [comment]
> what about doing all the normalizations somewhere around here? https://github.com/trezor/trezor-suite/blob/feat/suite-start-bt-notif/packages/connect/src/device/Device.ts#L1023 🤔

hmhm,
I am thinking of like if it is really "normalization". Like, let's assume that some random people use the connect as well, and they are surprise that the device without color looks always as if it has color 1.

IMHO, this normalization is for the purposes of the Suite.

So, I think ,if there was some modular way to normalize the device for the purpose of the Suite. So like somewhere like:
```ts
TrezorConnect.init({
   normalizeDevice: (rawDevice) => ({...rawDevice, ...myNormalizatStuff(raw)}) 
 })
```

But TrezorConnect doesn't operate like this, so I guess that's not possible to have such API. 

So I am thinking of like doing it in redux, but that won't work, coz sometime you work with device instance right from Connect as well...

**Comment by vojtatranta** [comment]
> what about doing all the normalizations somewhere around here? https://github.com/trezor/trezor-suite/blob/feat/suite-start-bt-notif/packages/connect/src/device/Device.ts#L1023 🤔

But I think we overengineer. Bear in mind , that this is only for the case when our testing units do not have color at all. In prod, it will be okay, so like "in place" normlaization is okay. It is broken somewhere, its just for testing units.

Nevertheless, some proper normalization API would be useful (since it is there already in `_updateProperties` within connect)

**Comment by vojtatranta** [comment]
This looks okayish, tested both public and private reposp, both problematic cases

File: suite-common/suite-utils/src/device.ts [hunk 1]
```diff
@@ -456,9 +456,13 @@ export const getDeviceInternalModel = (
     (device?.thp?.properties?.internal_model as DeviceModelInternal) ??
     DeviceModelInternal.UNKNOWN;
 
-export const getDeviceColorVariant = (
-    device: Pick<Device, 'features' | 'thp'>,
-): number | undefined => device.features?.unit_color ?? device.thp?.properties?.model_variant ?? 1;
+// NOTE: when a device eg. a testing unit, doesnt have a color variant (0 | null | undefined), we default to 1
```
Comment (peter-sanderson) [inline suite-common/suite-utils/src/device.ts]: :clap: thanks for extracting this to method, good to have it at one place for future changes

**Review by peter-sanderson — APPROVED** [review]

File: suite-common/suite-utils/src/device.ts (hunk 1 above)
Comment (vojtatranta) [reply suite-common/suite-utils/src/device.ts]: yeah, it is really not great at all

File: scripts/circular-dependencies/madge-snapshot.txt [hunk 2]
```diff
@@ -1,258 +1,3 @@
 
 
-packages/blockchain-link-types/src/blockbook.ts > packages/blockchain-link-types/src/common.ts
```
Comment (vojtatranta) [inline scripts/circular-dependencies/madge-snapshot.txt]: wtf is diz

**Comment by vojtatranta** [comment]
@peter-sanderson update the snapshot there were fewer circular deps, that's good

File: suite-common/suite-utils/src/device.ts [hunk 3]
```diff
@@ -456,9 +456,13 @@ export const getDeviceInternalModel = (
...
+export const normalizeDeviceColorVariant = (colorVariant?: number): number => colorVariant || 1;
+
+export const getDeviceColorVariant = (device: Pick<Device, 'features' | 'thp'>): number =>
+    normalizeDeviceColorVariant(
+        device.features?.unit_color ?? device.thp?.properties?.model_variant,
+    );
```
Comment (mroz22) [inline suite-common/suite-utils/src/device.ts]: this changes behavior from what was there previously that from now on `getDeviceColorVariant` never returns 0. Is it intended, right?

Comment (vojtatranta) [reply suite-common/suite-utils/src/device.ts]: Yep

File: packages/product-components/package.json [hunk 4]
```diff
@@ -19,6 +19,7 @@
     "dependencies": {
         "@suite-common/suite-constants": "workspace:*",
         "@suite-common/suite-types": "workspace:*",
+        "@suite-common/suite-utils": "workspace:*",
```
Comment (mroz22) [inline packages/product-components/package.json]: this is imho antipattern. whatever is nested in `packages` must not import from whatever is nested in `suite-common` 
see more detailed explanation in https://www.notion.so/satoshilabs/Code-improvements-9-breaking-the-monolith-528bf80c34ba4a6bba3f335e60ff29e8

**Review by mroz22 — CHANGES_REQUESTED** [review]
I would like to start getting rid of suite-common imports into packages, plz 😿

**Comment by vojtatranta** [comment]
> I would like to start getting rid of suite-common imports into packages, plz 😿

key key

**Review by mroz22 — APPROVED** [review]
