### PR TITLE
fix(trading): Fix the balance for addresses in DCA Modal

### LINKED ISSUE #17885: Update DCA landing page in Trezor Suite
We need update DCA page based on the new design with modals for selecting address

Figma: [https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=11704-126250&t=PEBGW9Zl3TuUWueX-4](https://www.figma.com/design/xSW1knAjH25SfOmqSdNioY/Trade?node-id=11704-126250&t=PEBGW9Zl3TuUWueX-4)

### PR DESCRIPTION
**Pull request by meedoox**
## Description

Resolves: https://github.com/trezor/trezor-suite/issues/17885#issuecomment-2766102819

## Screenshots:
Screenshot 2025-03-31 at 3 26 47 PM

### CODE REVIEW

**Review by izmy — APPROVED** [review]

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TradingDCAModal.tsx [hunk 1]
```diff
@@ -123,39 +124,55 @@ const AddressSelect = ({
...
-                    />
-                    {acountAddress.path}
-                </InfoSegments>
-            </Column>
-        )}
-    />
-);
+}: AddressSelectProps) => {
+    const networkDecimals = getTradingNetworkDecimals({
+        sendCryptoSelect: undefined,
```
Comment (adderpositive) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TradingDCAModal.tsx:129]: Nit: 

```suggestion
```

**Review by adderpositive — APPROVED** [review]
LGTM

**Comment by MiroslavProchazka** [comment]
@izmy can you merge this, in case you find it legitimate?

**Review by TomasBoda — APPROVED** [review]
