### PR TITLE
Fix/send-total-spent

### LINKED ISSUE #2403: ERC20 tokens Total sent
Optimizing token send with no fiat value (for now). As discussed in the office: 

Screen Shot 2020-09-22 at 16 48 41

### PR DESCRIPTION
**Pull request by szymonlesisz**
- fixed "clear button" visibility when loading draft ("isDirty")
- refactored/unified ETH + XRP composeTransaction methods
- fixed "totalSpent" field in ETH
- fix #2403, ERC20 values displayed in "TotalSent" component

### CODE REVIEW

File: packages/suite/src/views/wallet/send/components/TotalSent/index.tsx [hunk 1]
```diff
@@ -63,35 +63,52 @@ const TotalSentFiat = styled.div`
...
+                            />
+                        </TotalSentFiat>
+                    )}
+                    {tokenInfo && (
+                        <TotalSentFiat>
+                            <Translation id="FEE" />
+                            <Symbol>{formatNetworkAmount(transactionInfo.fee, symbol)}</Symbol>
+                            <Symbol>{symbol}</Symbol>
+                        </TotalSentFiat>
+                    )}
```
Comment (keraf) [inline packages/suite/src/views/wallet/send/components/TotalSent/index.tsx]: Nitpicking but this could be transformed into an if-else statement.
```
<TotalSentFiat>
    {tokenInfo ? (
        <>
            <Translation id="FEE" />
            <Symbol>{formatNetworkAmount(transactionInfo.fee, symbol)}</Symbol>
            <Symbol>{symbol}</Symbol>
        </>
    ) : (
        <FiatValue
            amount={formatNetworkAmount(transactionInfo.totalSpent, symbol)}
            symbol={symbol}
        />
    )}
</TotalSentFiat>
```

**Review by keraf — APPROVED** [review]
Love the last commit message :laughing: Looks all good!
