### PR TITLE
fix(suite-native): Mobile Trade: Legal BottomSheet scroll

### LINKED ISSUE #18818: Mobile Trade: Legal bottomsheet is scrollable with difficulties
**Describe the bug**
Legal bottomsheet is scrollable with difficulties and needs to be scrolled up before can be scrolled down.

https://github.com/user-attachments/assets/1ea0fe41-dea8-452e-88c0-ecdf90c3de56

**Info:**

- Mobile Suite Version: 776ec66
- OS: iOS, 18.1

### PR DESCRIPTION
**Pull request by jbazant**
## Related Issue

Resolve #18818

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=18818-Mobile-Trade-Legal-bottomsheet-fixes&lookback=7)

### CODE REVIEW

File: suite-native/module-trading/src/components/buy/LegalSheet.tsx [hunk 1]
```diff
@@ -24,63 +26,80 @@ const Info = ({ children }: { children: ReactNode }) => (
     </BulletListItem>
 );
 
-export const LegalSheet = ({ isVisible, onConsent, onClose, tradeProvider }: LegalSheetProps) => {
-    const providers = useSelector(selectTradingBuyProviders);
-    const { companyName } = providers?.[tradeProvider] ?? {};
+export const LegalSheet = memo(
```
Comment (jbazant) [inline suite-native/module-trading/src/components/buy/LegalSheet.tsx:29]: **note:** `Confirmation.tsx` uses `useTimer` which rerenders every second. No need to re-render this sheet as well.

File: suite-native/module-trading/src/components/buy/LegalSheet.tsx [hunk 2]
```diff
@@ -24,63 +26,80 @@ const Info = ({ children }: { children: ReactNode }) => (
...
+                            <Translation id="moduleTrading.legalSheet.subheaderLegal" />
+                        </Subheader>
+                        <Info>
+                            <Translation id="moduleTrading.legalSheet.infoLegal1" />
+                        </Info>
+                        <Info>
+                            <Translation id="moduleTrading.legalSheet.infoLegal2" />
+                        </Info>
+                    </VStack>
+                    {isVisible && (
```
Comment (jbazant) [inline suite-native/module-trading/src/components/buy/LegalSheet.tsx]: **note:** Nothing to see here, keep scrolling. (This is here because of tests and the way Gorhom bottom sheet is mocked)

File: suite-native/module-trading/src/hooks/useTradingBuyFlow.ts [hunk 3]
```diff
@@ -71,21 +71,24 @@ export const useTradingBuyFlow = (form: TradingBuyForm) => {
...
-            resolveConsent(false);
-            setIsConsentRequested(false);
-        },
-        request: async (_provider: string, _cryptoCurrency: string) => {
-            setIsConsentRequested(true);
-
-            return await waitForConsent();
-        },
-    };
+    const handleConsent = useMemo(
```
Comment (jbazant) [inline suite-native/module-trading/src/hooks/useTradingBuyFlow.ts:74]: **note:** This was unstable and thanks too `useTimer` re-rendered every second.

**Comment by jbazant** [comment]
@coderabbitai review

File: suite-native/module-trading/src/components/buy/LegalSheet.tsx (hunk 2 above)
Comment (vytick) [reply suite-native/module-trading/src/components/buy/LegalSheet.tsx]: can you add this as a comment, please?

**Review by vytick — APPROVED** [review]
Nice, you 🪨

File: suite-native/module-trading/src/components/buy/LegalSheet.tsx (hunk 2 above)
Comment (jbazant) [reply suite-native/module-trading/src/components/buy/LegalSheet.tsx]: Updated.
