### PR TITLE
fix(connect-ui): install bridge title align

### LINKED ISSUE #12673: connect-popup - install bridge page broken UI (misaligned header)
image

### PR DESCRIPTION
**Pull request by karliatto**
## Description

Fix install bridge title alignment.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12673

## Screenshots:

image

### CODE REVIEW

File: packages/connect-ui/src/views/Transport.tsx [hunk 1]
```diff
@@ -7,9 +8,16 @@ import imageSrc from '../images/man_with_laptop.svg';
 
 export type TransportEventProps = Extract<UiEvent, { type: 'ui-no_transport' }>;
 
+const Title = styled(H3)`
```
Comment (martykan) [inline packages/connect-ui/src/views/Transport.tsx]: Why not change this in the View component directly? I think we always want it centered

Comment (karliatto) [reply packages/connect-ui/src/views/Transport.tsx]: I was afraid of modifying something unexpectedly but you are right, actually before it was all centered, just it was broken by some changes in H3 component.

So there there is fixup 92d0ec0651c791e5c430b262a95766321d527dbe

**Review by martykan — APPROVED** [review]
👍
