### PR TITLE
Fix PostCSS line return parsing error

### LINKED ISSUE #7613: Dependencies: stylelint, stylelint-config-recommended
Update `stylelint`, `stylelint-config-recommended`

Issues:
- new rules 
- `yarn lint` problems 
Screenshot 2023-02-10 at 18 00 50

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- update storybook to get rid of `webpack4` storybook dependency which had old version of `postcss`
- remove `@storybook/core` as it was not used after migration to v7
- replace `stylelint-processor-styled-components` by `postcss-styled-syntax` which is not deprecated and is recommended by stylelint docs and also does not include old `postcss`
- update `stylelint` to latest version and update it's config
- fix all css problems in Suite package
- disable stylelint in components package https://github.com/trezor/trezor-suite/issues/9810
- use one `.stylelintrc` config from root
- add stylelint check to `suite-web`, `suite-desktop-ui`, `connect-explorer`, `connect-popup`, `connect-popup-ui`

## Related Issue

https://github.com/trezor/trezor-suite/security/dependabot/189
closes https://github.com/trezor/trezor-suite/issues/7613
https://github.com/trezor/trezor-suite/pull/8872

### CODE REVIEW

**Review by dahaca — APPROVED** [review]
Follow-up issue: https://github.com/trezor/trezor-suite/issues/9810

**Comment by tomasklim** [comment]
@SocketSecurity ignore @storybook/cli@7.5.2
@SocketSecurity ignore @storybook/manager@7.5.2
@SocketSecurity ignore stylelint@15.11.0
@SocketSecurity ignore stylelint-config-recommended@13.0.0
@SocketSecurity ignore write-file-atomic@5.0.1
@SocketSecurity ignore @storybook/components@7.5.2
@SocketSecurity ignore storybook@7.5.2
@SocketSecurity ignore @storybook/addon-actions@7.5.2
@SocketSecurity ignore @storybook/preview@7.5.2
@SocketSecurity ignore @storybook/core-webpack@7.5.2
@SocketSecurity ignore @types/unist@3.0.1
@SocketSecurity ignore @storybook/builder-webpack5@7.5.2
@SocketSecurity ignore @storybook/builder-manager@7.5.2
@SocketSecurity ignore @storybook/telemetry@7.5.2
@SocketSecurity ignore @storybook/docs-tools@7.5.2
@SocketSecurity ignore @storybook/node-logger@7.5.2
@SocketSecurity ignore @storybook/addon-links@7.5.2
@SocketSecurity ignore @storybook/csf-tools@7.5.2
@SocketSecurity ignore @storybook/react-dom-shim@7.5.2
@SocketSecurity ignore @storybook/react-webpack5@7.5.2
@SocketSecurity ignore @storybook/preset-react-webpack@7.5.2
@SocketSecurity ignore @storybook/codemod@7.5.2
@SocketSecurity ignore @storybook/react@7.5.2
@SocketSecurity ignore @storybook/blocks@7.5.2
@SocketSecurity ignore @storybook/core-common@7.5.2
@SocketSecurity ignore @storybook/addon-controls@7.5.2
@SocketSecurity ignore @storybook/core-server@7.5.2
@SocketSecurity ignore @storybook/core-client@7.5.2
@SocketSecurity ignore @storybook/addon-viewport@7.5.2
@SocketSecurity ignore typescript@5.1.6

File: packages/suite/src/views/wallet/send/components/TotalSent.tsx [hunk 1]
```diff
@@ -7,8 +7,7 @@ import { Card, Translation, FiatValue, FormattedCryptoAmount } from 'src/compone
 const StyledCard = styled(Card)`
     display: flex;
     flex-direction: row;
-    justify-items: space-between;
-    align-items: center;
+    place-items: center space-between;
```
Comment (matejkriz) [inline packages/suite/src/views/wallet/send/components/TotalSent.tsx:10]: @tomasklim This is not working at least on my machine:
image
