### PR TITLE
Fix/connect CoinInfo with FeeLevels

### LINKED ISSUE #5340: @trezor/connect improve coinInfo FeeLevels
non bitcoin like coins coinInfo defaultFees are not unified, because of that there are multiple workarounds in connect (blockchainEstimateFee) and suite (blockchainActions)

- [x] use FeeLevel type while parsing coinInfo
- [x] create separated module for know levels (ethereum, ada, xrp) which are not defined in `trezor-common`, or consider to add them to `trezor-common`
- [x] fallback for unknown levels/coins

### PR DESCRIPTION
**Pull request by szymonlesisz**
## Description

As usual i would like to do something else but i'm ending up with something unrelated (only at first glance) 🤯

I wanted to write missing test for [Fee estimation](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/api/bitcoin/Fees.ts) to be able to properly calculate [new feature](https://github.com/trezor/trezor-suite/pull/9109/commits/46cc3e2faaf8920135e48829832601e87afa9d0d) called `longTermFeeRate` which will be used to [estimate dustThreshold](https://github.com/trezor/trezor-suite/pull/9109) but i noticed some issues, TODOs and forgotten chores regarding CoinInfo + FeeLevels so i firstly want to resolve them as prerequisite.

First commit (blockchain-link) is here because dev mode of blockchain-link is failing
`yarn workspace @trezor/blockchain-link dev`

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/5340

### CODE REVIEW

File: packages/connect/src/data/defaultFeeLevels.ts [hunk 1]
```diff
@@ -0,0 +1,130 @@
+import { FeeLevel, FeeInfo } from '../types';
+
+// this is workaround for the lack of information from 'trezor-common'
+// we need to declare what does "high/normal/low" mean in block time (eg: normal BTC = 6 blocks = ~1 hour)
+// coins other than BTC usually got 2 levels maximum (high/low) and we should consider to remove other levels from 'trezor-common'
+const BLOCKS_FOR_FEE_LEVEL: Record<string, Record<string, number>> = {
```
Comment (mroz22) [inline packages/connect/src/data/defaultFeeLevels.ts:6]: not part of  this PR, just a general thought - this information (fees) could become part of the new config we are planning together with blockchain-link information and others that we don't want to use from trezor-common anymore.

File: packages/connect/src/api/blockchainEstimateFee.ts [hunk 2]
```diff
@@ -61,10 +61,10 @@ export default class BlockchainEstimateFee extends AbstractMethod<'blockchainEst
     async run() {
         const { coinInfo, request } = this.params;
         const feeInfo: MethodReturnType<typeof this.name> = {
-            blockTime: coinInfo.blocktime,
+            blockTime: coinInfo.blockTime,
             minFee: coinInfo.minFee,
             maxFee: coinInfo.maxFee,
-            dustLimit: coinInfo.type === 'bitcoin' ? coinInfo.dustLimit : undefined,
+            dustLimit: coinInfo.type === 'bitcoin' ? coinInfo.dustLimit : -1,
```
Comment (mroz22) [inline packages/connect/src/api/blockchainEstimateFee.ts]: runtime change right? I understand that non-utxo coins don't have dust limit (what about cardano?). why it did not make sense to use undefined here?

File: packages/connect/src/data/defaultFeeLevels.ts [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+            const label = level.toLowerCase() as FeeLevel['label']; // string !== 'high' | 'normal'....
+            return {
+                label,
+                feePerUnit: defaultFees[level].toString(),
+                blocks: getDefaultBlocksForFeeLevel(shortcut, label),
+            };
+        });
+
+    return {
+        blockTime: coin.blocktime_seconds / 60,
```
Comment (mroz22) [inline packages/connect/src/data/defaultFeeLevels.ts]: blocktime is blocktime in minutes?

I undrestand that doing Math.round (which was tehre before) was at least inaccurate since some very fast chains might have been rounded down to zero.

But wouldn't it make sense to round it to certain number of decimals here? probably not needed I guess. Just that I spotted a difference here.

**Review by mroz22 — APPROVED** [review]
looks good. nice refactoring of types. in general fees/default fees should be more readable now.

File: packages/connect/src/api/blockchainEstimateFee.ts (hunk 2 above)
Comment (szymonlesisz) [reply packages/connect/src/api/blockchainEstimateFee.ts]: you are right, it will be safer to return undefined [18ed620](https://github.com/trezor/trezor-suite/pull/9171/commits/18ed6204d689f69d4f4738545fbc411561043aff)

File: packages/connect/src/data/defaultFeeLevels.ts (hunk 3 above)
Comment (szymonlesisz) [reply packages/connect/src/data/defaultFeeLevels.ts]: again right, this value is used by suite send form:
```
formatDuration(feeInfo.blockTime * selectedLevel.blocks * 60)
```
it will be safer to return this value in minutes (int) - so now im rounding to 0 (as it was) but picking up Math.max between 1 and real value [ffc3f85](https://github.com/trezor/trezor-suite/pull/9171/commits/ffc3f85e559865e7801fa81151a0cf4c4086de42) + [6e533ef](https://github.com/trezor/trezor-suite/pull/9171/commits/6e533ef66894f0ae9e9acfa08e9368cc151d02bb)

Comment (szymonlesisz) [reply packages/connect/src/data/defaultFeeLevels.ts]: i think two last fixups will throw conflicts while squashing, so i need to suqash it manually and force push it

**Review by marekrjpolak — APPROVED** [review]
Definitely more understandable.
