### PR TITLE
fix(staking): fix inconsistent Solana staking amounts between UI and device

### LINKED ISSUE #17388: Solana Stake / Claim amount discrepancy due to rent fee
**Describe the bug**
- When staking or claiming, there is a discrepancy between the Stake/Claim amount displayed on the Suite TX confirmation screen and on the FW
- The discrepancy is caused by different handling of “Rent”
    - Suite includes Rent in transaction fees
    - Device includes Rent in the stake/claim amount
    
This issue needs to be aligned on TS level
**Info:**
 - Suite version: web 25.3.0 (e1f21be5da5a434b003c5823262e052d2678c0ca)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: WebUsbTransport

**Screenshots:**

Image

Image

### PR DESCRIPTION
**Pull request by izmy**
## Description

Fixes inconsistent Solana staking amount and fee values shown in Suite UI and on the device.

## Notes for QA

- try to stake, unstake and claim

## Related Issue

Resolve #17388

## Screenshots:

image

image

image

image

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/correct-staking-amount-calculation-and-formatting&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/correct-staking-amount-calculation-and-formatting&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/correct-staking-amount-calculation-and-formatting&lookback=7)

### CODE REVIEW

File: suite-common/staking-solana/src/utils/stakingUtils.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ const getStakingParams = (estimatedFee?: Fee[number]) => {
     }
 
     return {
-        сomputeUnitPrice: BigInt(estimatedFee.feePerUnit),
+        computeUnitPrice: BigInt(estimatedFee.feePerUnit),
```
Comment (izmy) [inline suite-common/staking-solana/src/utils/stakingUtils.ts:64]: Fix `computeUnitPrice` key using a Cyrillic character instead of Latin `c`. 💀

**Review by matusbalascak — APPROVED** [review]

**Review by tomasklim — APPROVED** [review]

**Comment by tomasklim** [comment]
e2e tests are failing

File: suite-common/staking-solana/src/utils/transactionUtils.ts [hunk 2]
```diff
@@ -160,6 +168,63 @@ const baseTx = async (
     return transactionMessage;
 };
 
+const SOLANA_BASE_FEE_LAMPORTS = 5000n;
```
Comment (vytick) [inline suite-common/staking-solana/src/utils/transactionUtils.ts]: nit: we already have `SOLANA_BASE_FEE` in the codebase. Imo it should be good to unify

Comment (izmy) [reply suite-common/staking-solana/src/utils/transactionUtils.ts]: Unfortunately, I can't import it from `@trezor/connect`, but I at least added consts into `wallet-constants`

**Comment by vytick** [comment]
@greptile

**Review by tomasklim — APPROVED** [review]
