### PR TITLE
Trading - Receive Address UI Fixes

### LINKED ISSUE #22593: Receive address in Trade - ui bugs
Please fix these small UI bugs:

1. If there is only one row of text (account is "Not selected" or external account in entered), increase top and bottom padding to 20px ([Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4811-24346&t=ba8sY7hlyCAmq7MM-4))

Image

2. In BUY form remove the bottom border. Receive account is last item in the card and since card has its own border, it results in weird "double border".

Image

3. Chevron should have some color as secondary text, not as primary text
Image

4. Show only one "New address" in receive address selector (Same as on mobile. Currently it shows 20 new addresses.) and increase space between New and Used addresses section. ([Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4811-12185&t=ba8sY7hlyCAmq7MM-4))

Image

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Minor receive address UI fixes:

- adjust padding for `Not selected` receive account
- don't show bottom border of the receive address picker in buy, since it is the last element in the card
- set chevron icon colors to tertiary
- show only one unused (new) address for UTXO-based networks in receive address modal

## Related Issue

Resolve #22593 

## Screenshots:

Account not selected padding:

Screenshot 2025-10-22 at 12 51 43

Bottom border omitted in buy:

Screenshot 2025-10-22 at 12 51 20

Chevron icon color tertiary:

Screenshot 2025-10-22 at 12 51 58

Show only one new unused address for UTXO-based networks:

Screenshot 2025-10-22 at 12 52 10

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/receive-address&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/receive-address&lookback=7)

### CODE REVIEW

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -1570,9 +1570,9 @@ export default defineMessages({
         defaultMessage: "Enter {networkName} address that isn't in Trezor Suite.",
         id: 'TR_TRADING_RECEIVE_ADDRESS_ENTER_TEXT',
     },
-    TR_TRADING_RECEIVE_ADDRESS_NEW_ADDRESSES: {
-        defaultMessage: 'New addresses',
-        id: 'TR_TRADING_RECEIVE_ADDRESS_NEW_ADDRESSES',
+    TR_TRADING_RECEIVE_ADDRESS_NEW_ADDRESS: {
+        defaultMessage: 'New addresse',
```
Comment (tomasklim) [inline packages/suite/src/support/messages.ts]: typo

**Review by tomasklim — APPROVED** [review]
When typo fixed, LGTM

File: packages/suite/src/support/messages.ts (hunk 1 above)
Comment (TomasBoda) [reply packages/suite/src/support/messages.ts]: done
