### PR TITLE
fix: do not send host_static_public_key as it is not needed

### LINKED ISSUE #23268: Remove `host_static_public_key` from the `EvoluGetDelegatedIdentityKey`
> the host_static_public_key field will be removed from EvoluGetDelegatedIdentityKey message for security reasons. The credential (used to obtain delegated identity) will be validated using the host_static_public_key stored in the channel's cache. 

[Once FW update is done](https://github.com/trezor/trezor-firmware/issues/6171)

- update probubuf
- change relevant code, see: `retrieveDelegatedIdentityKeyThunk.ts`
- lock the required version of the Firmware for Evolu to higher version if needed (maybe not needed, depends how its tracked in the firmware lifecycle)

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/23268

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=remove-delegated-identity-host&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=remove-delegated-identity-host&lookback=7)

## 🔍 Currents Test Results

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=remove-delegated-identity-host&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 8 test(s)</summary>

| Test | Type |
|------|------|
| Analytics Events > Analytics captures important events when started enabled by default | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Firmware - check readiness > Suite detects that firmware is ready | 🤖 auto |
| Staking - Cardano > Stake Cardano | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-24T16:20:14.519Z • 8 test(s) total_

### CODE REVIEW

**Review by komret — APPROVED** [review]

File: packages/connect/src/api/evoluGetDelegatedIdentityKey.ts [hunk 1]
```diff
@@ -22,11 +23,18 @@ export default class EvoluGetDelegatedIdentityKey extends AbstractMethod<
...
         const thpState = this.device.getThpState();
+        const version = this.device.getVersion();
+
         if (thpState) {
             this.params = {
                 thp_credential: thpState.pairingCredentials[0].credential,
-                host_static_public_key:
-                    thpState.handshakeCredentials?.hostStaticPublicKey.toString('hex'),
+
+                ...(version !== undefined && versionUtils.isNewer(version, [2, 10, 0])
```
Comment (szymonlesisz) [inline packages/connect/src/api/evoluGetDelegatedIdentityKey.ts]: is it really worth to keep since it was never officially released?

Comment (peter-sanderson) [reply packages/connect/src/api/evoluGetDelegatedIdentityKey.ts]: I thought as well, but then I tested it and it fails with some `firmware error` so I thought lets keep it for a while as many of us have `2.10.0` FW and this change is for FW that has not been released yet. 

With this change, all devs & internal testers would need to run custom fw to work on Suite Sync.

We may also delay merge of this + also we shall increase minimal version for Suite Sync I guess..

Comment (peter-sanderson) [reply packages/connect/src/api/evoluGetDelegatedIdentityKey.ts]: I added a commit https://github.com/trezor/trezor-suite/pull/24744/commits/15ea4322c1a6a6a7ffa704660040f5b38d947ef2 that increases required version to `2.10.1` and removes the `host_static_public_key` completely.

However I would wait with merging this, until the 2.10.1 is released. 

(Or whatever new version it will be)

**Review by szymonlesisz — APPROVED** [review]

**Comment by peter-sanderson** [comment]
This https://github.com/trezor/trezor-suite/pull/26089 needs to be merged first
