### PR TITLE
Fix/suite multiple calls to reboot

### LINKED ISSUE #9577: Error: ui-device_firmware_old error when installing custom firmware image
**Describe the bug**
Error: `ui-device_firmware_old` error when installing custom firmware image.
I was not able to reproduce it with stock 2.6.0 W or with fw type change.

**Steps to reproduce:**
1. Install custom firmware
2. observe errors

**Info:**
 - Suite version: web 23.10.0 (7869fabefa29e7a86b9ca4a3998e42e9ae36d638)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/118.0
 - OS: MacIntel
 - Screen: 2160x1350
 - Device: Trezor T2T1 2.6.3 undefined (revision null)
 - Transport: BridgeTransport 2.0.32

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/46084b23-7805-433d-973f-5f958610d05d

### PR DESCRIPTION
**Pull request by mroz22**
quick fix #9577

rebootToBootloader should probably set device lock anyway. 
second commit are just logs, feel free to throw it away. I thought it might be useful if somebody wanted to dig in it a little more

### CODE REVIEW

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx [hunk 1]
```diff
@@ -255,6 +255,7 @@ export const ReconnectDevicePrompt = ({
 }: ReconnectDevicePromptProps) => {
     const { device } = useDevice();
     const { isWebUSB } = useFirmware();
+    console.log('render ReconnectDevicePrompt');
```
Comment (mroz22) [inline packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: although hook params in `useRebootRequest.ts` do not change, this hooks is called twice because this component rerenders.

File: packages/suite/src/hooks/firmware/useRebootRequest.ts [hunk 2]
```diff
@@ -65,7 +79,7 @@ export const useRebootRequest = (
                     });
             }
         }
-    }, [device, dispatch, phase, method, requestedMode]);
+    }, [connected, mode, dispatch, phase, method, requestedMode, isLocked]);
```
Comment (mroz22) [inline packages/suite/src/hooks/firmware/useRebootRequest.ts:75]: quickiest fix is to have something that changes after the first call to connect is issued.

**Review by matejkriz — APPROVED** [review]
looks good to me, works fine in custom FW installation, haven't tested yet in regular installation flow

**Comment by mroz22** [comment]
dropped the tmp commit and forcepushed
