### PR TITLE
fix(suite): change isOfficialFw to firmwareSource

### LINKED ISSUE #14893: Data Analytics: Custom Firmware Install
Add attribute indicating custom/normal firmware to events [device-update-firmware](https://www.notion.so/satoshilabs/device-update-firmware-862ec5e97f0c41c98dc035412be83721?pvs=4) and [device-connected](https://www.notion.so/satoshilabs/device-connect-4f6b6f058fad42878410fd3b56ad7077?pvs=4). Could be named customFw with boolean value.

### PR DESCRIPTION
**Pull request by izmy**
## Description

`isOfficialFw` property in device-update-firmware events now accepts a string value `NA - bootloader` to represent devices in bootloader mode, where official firmware verification is not possible.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/14893

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/data-analytics-customFw&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/data-analytics-customFw&lookback=7)

### CODE REVIEW

File: packages/suite-analytics/src/types/events.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ export type SuiteAnalyticsEvent =
           payload: {
               mode: 'normal' | 'bootloader' | 'initialize' | 'seedless';
               firmware: string;
-              isOfficialFw: boolean;
+              isOfficialFw: OfficialFirmwareStatus;
```
Comment (adderpositive) [inline packages/suite-analytics/src/types/events.ts]: Renaming `isOfficialFw` to something else would be nice. It is not `boolean` anymore, but it could be a problem with analytics, just for consideration.

**Review by adderpositive — APPROVED** [review]
lgtm

**Review by TomasBoda — APPROVED** [review]

File: packages/suite-analytics/src/types/events.ts (hunk 1 above)
Comment (izmy) [reply packages/suite-analytics/src/types/events.ts]: You are right, so I renamed property `isOfficialFw` to `firmwareSource`

**Review by adderpositive — APPROVED** [review]
