### PR TITLE
fix(native): show xpub at correct moment

### LINKED ISSUE #20959: Account XPUB is displayed too soon
If the user goes to the Account Details screen and want to display the XPUB, Trezor device starts the flow before the action is confirmed in the app UI.

## SCREENSHOTS

https://github.com/user-attachments/assets/58a4aca1-a857-4bc5-a3e4-7599d7968500

### PR DESCRIPTION
**Pull request by OriginalEveres**
## Description
Xpub prompt was shown at device at incorrect moment.

**changes**:
- call trezor get pub keys when user clicks on the button
- cancel in progress call when user closes the bottom sheet

## Notes for QA

- XPUB should be shown once user clicks `Show public key` button

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20959

## Screenshots:

https://github.com/user-attachments/assets/2bc39cdf-ccfb-48a1-a5c2-c8c51d9228e1

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/xpub-shown-early&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/xpub-shown-early&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/xpub-shown-early&lookback=7)

### CODE REVIEW

File: suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx [hunk 1]
```diff
@@ -70,7 +103,12 @@ export const XpubQRCodeBottomSheet = ({
     };
 
     return (
-        <BottomSheetModal ref={ref} isCloseDisplayed title={sheetTitle}>
+        <BottomSheetModal
+            ref={ref}
+            isCloseDisplayed
+            title={sheetTitle}
+            onClose={handleCancelConfirmation}
```
[the remark this answers is not in the document]
Comment (OriginalEveres) [reply suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx:109]: not really. Its closed via ref

File: suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx [hunk 2]
```diff
@@ -60,8 +78,23 @@ export const XpubQRCodeBottomSheet = ({
...
+        if (!device || !account) return;
+
+        setConfirmationInProgress(true);
+        const xpub = await showXpubOnDevice(device, account);
+
+        if (xpub.success) {
+            setConfirmationInProgress(false);
+            setIsXpubShown(true);
+        }
     };
```
[the remark this answers is not in the document]
Comment (OriginalEveres) [reply suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx:97]: not relevant anymore

File: suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx [hunk 3]
```diff
@@ -60,8 +78,25 @@ export const XpubQRCodeBottomSheet = ({
...
+
+        setConfirmationInProgress(false);
+        TrezorConnect.cancel();
+    };
+
+    const handleShowXpub = async () => {
+        if (!device || !account) return;
+
+        setConfirmationInProgress(true);
+        const xpub = await showXpubOnDevice(device, account);
```
Comment (Lemonexe) [inline suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx]: Nit: rename to `xpubResponse`, it's not the `xpub`.

File: suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx [hunk 4]
```diff
@@ -60,8 +78,25 @@ export const XpubQRCodeBottomSheet = ({
...
+
+        if (xpub.success) {
+            setConfirmationInProgress(false);
+            setIsXpubShown(true);
+        } else {
+            onClose();
```
Comment (Lemonexe) [inline suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx:93]: does the React component unmount?
I see that the onClose comes from  `useBottomSheetModal()` but I don't how that library works.
If it doesn't umnount, then unsuccessful call would mean that you can never show xpub again because `confirmationInProgress`

**Review by Lemonexe — APPROVED** [review]
LGTM, but pls look into the two small comments

**Review by juriczech — COMMENTED** [review]
I fear that this is not working well with passphrase prompt. If you press on `show xpub` on passphrase wallet that has been reconnected, the device shows passphrase prompt, it's registered by the app on opens the passphrase prompt, but it's "below" the modal. 

Edit: It was like this for months on production builds too, so it's not a PR blocker. Would be nice to fix though, or create an issue 🙏 

Image

**Comment by OriginalEveres** [comment]
> I fear that this is not working well with passphrase prompt. If you press on `show xpub` on passphrase wallet that has been reconnected, the device shows passphrase prompt, it's registered by the app on opens the passphrase prompt, but it's "below" the modal.
> 
> Edit: It was like this for months on production builds too, so it's not a PR blocker. Would be nice to fix though, or create an issue 🙏
> 
> Image

yes. I want to tackle this in a separate issue. It was there for long time and this PR fixes something different. IMHO the passphrase might turn this into a separate screen, so we have to talk to design.

File: suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx (hunk 4 above)
Comment (OriginalEveres) [reply suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx:93]: AFAIK it does unmount, but I moved the `setConfirmationInProgress` after the if statement, so it fires in both cases.
