### PR TITLE
fix: change relay now correctly updates Evolu instances

### LINKED ISSUE #22990: Relay URL change on Desktop requried Refrest to take place
Changing the Relay URL shall recreate the Evolu instance with new Transport URL. 

See `suite-common/local-first-storage/src/storage/LocalFirstStorageProvider.ts` there is some commented code in `deleteStorage` this may be relevant

### LINKED ISSUE #23084: Change of relay wont refresh Evolu transports
The `evolu.useOwner(...)` needs to be used 

## QA:

changing evolu relay (in debug) shall stop retrying the old URL

Steps:
- set non-existing URL (for example: `http://smazak-s-hranlkama.org`
- observe retries in console/network
- set correct url (default)
- observe that it connects to it (relay) and stops retries on the previous (non-existing)

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/23084
Resolves: https://github.com/trezor/trezor-suite/issues/22990

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-evolu-relay-change&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-evolu-relay-change&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix-evolu-relay-change&lookback=7)

### CODE REVIEW

File: suite-common/local-first-storage/src/storage.ts [hunk 1]
```diff
@@ -22,4 +28,25 @@ export class LocalFirstStorage {
...
+            transports: [createOwnerWebSocketTransport({ url, ownerId: owner.id })],
+        };
+
+        this.#evolu.useOwner(syncOwner);
+    }
+
+    async dispose() {
+        // Todo: reload prevets app from reloading. Evolu has this tab-reload
+        //       to clear state as proper dispose is not yet implemented.
+        //       However we cannot effort the tab-reload.
```
Comment (Lemonexe) [inline suite-common/local-first-storage/src/storage.ts:48]: I don't understand this sentence

**Review by Lemonexe — APPROVED** [review]
Codewise LGTM but have not tested and I do not understand the topic very much, ask @OriginalEveres if you want proper review.
