### PR TITLE
fix(connect): respect useEmptyPassphrase param in cipherKeyValue method

### LINKED ISSUE #8250: Can't enable labeling on remembered hidden wallet
**Describe the bug**
Can't enable labeling on remembered hidden wallet.

**Info:**

-   Remembered Wallet: yes
-   Suite Version: 23.5.0-dev
-   OS: macOS
-   Firmware Version: TT 2.6.0

**How to reproduce**

1. Enter a hidden wallet
2. Remember it
3. Reconnect the device
4. Try to enable labeling in the Sessions
5. Observe a loader being displayed on device and nothing happening afterwards.

**Expected behavior**
Suite should ask to provide a passphrase and then prompt to enable labeling on device.

### PR DESCRIPTION
**Pull request by dahaca**
## Description

* fix inability to enable labeling from a hidden wallet

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/8250

### CODE REVIEW

File: packages/connect/src/api/cipherKeyValue.ts [hunk 1]
```diff
@@ -15,15 +15,18 @@ export default class CipherKeyValue extends AbstractMethod<
     init() {
         this.requiredPermissions = ['read', 'write'];
         this.firmwareRange = getFirmwareRange(this.name, null, this.firmwareRange);
-        this.info = 'Cypher key value';
-        this.useEmptyPassphrase = true;
+        this.info = 'Cipher key value';
+        // this.useEmptyPassphrase = true;
```
Comment (szymonlesisz) [inline packages/connect/src/api/cipherKeyValue.ts]: nit: this could be removed

**Review by szymonlesisz — APPROVED** [review]
