### PR TITLE
fix(suite): link to the issue

### LINKED ISSUE #3886: Link to given support page section at "device not recognized" instead of the support mainpage
**Current state**
When the device is not recognized by Suite (see screen below) the support link links to main support page

**Suggested solution**
In such case it would be more Suitable to link directly to "device not recognized by wallet" section at https://trezor.io/support/technical/i-cannot-access-the-wallet/ 

image

### PR DESCRIPTION
**Pull request by dimasivan**
fix #3886

### CODE REVIEW

**Review by goodhoko — APPROVED** [review]
LGTM

File: packages/suite/src/constants/suite/urls.ts [hunk 1]
```diff
@@ -4,6 +4,8 @@ export const CHANGELOG_MARKDOWN_URL =
 export const TREZOR_URL = 'https://trezor.io';
 export const TREZOR_COINS_URL = 'https://trezor.io/coins/';
 export const SUPPORT_URL = 'https://trezor.io/support/';
+export const CANNOT_ACCESS_WALLET =
+    'https://trezor.io/support/technical/i-cannot-access-the-wallet/';
```
Comment (tomasklim) [inline packages/suite/src/constants/suite/urls.ts]:
```suggestion
export const WALLET_ACCESS_URL =
    'https://trezor.io/support/technical/i-cannot-access-the-wallet/';
```
All other variables have `URL` in its name. I would keep it consistent

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Review by tomasklim — APPROVED** [review]
LGTM, please squash it
