### PR TITLE
fix(connect-common): check FW revision only new format

### LINKED ISSUE #22202: Fix `check-firmware-revisions.json`
The `IS_LEGACY` parameter does not make sense for Suite, please revert.

## For QA
No need to test, just cleanup for scripts.

### PR DESCRIPTION
**Pull request by karliatto**
## Description

Removing checking for legacy releases JSONs in Suite since they are not there, so there was nothing to validate anymore. This removes that unnecessary check and simplifies the script.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22202

### CODE REVIEW

File: packages/connect-common/scripts/check-firmware-revisions.sh [hunk 1]
```diff
@@ -1,15 +1,20 @@
 #!/usr/bin/env bash
 
+# There is a similar script like this in trezor/data
+# https://github.com/trezor/data/blob/master/scripts/check-firmware-revisions.sh
+#
+# The difference is tha in here we only have to check for new release JSONs but
```
Comment (peter-sanderson) [inline packages/connect-common/scripts/check-firmware-revisions.sh]:
```suggestion
# The difference is that in here we only have to check for new release JSONs but
```

**Review by peter-sanderson — APPROVED** [review]

**Comment by STew790** [comment]
Same as here https://github.com/trezor/trezor-suite/issues/22202#issuecomment-3490062383
