### PR TITLE
fix(coinmarket): fix crypto ticker in receive dropdown

### LINKED ISSUE #14182: Coinmarket - Unexpected text when exchanging to coin that is not currently enabled
**Describe the bug**
Unexpected text when exchanging to coin that is not currently enabled 

**Steps to reproduce:**
1. Navigate to exchange section 
2. Select funded account as input
3. Select disabled coin as output
4. Observe text

**Info:**
 - Suite version: web 24.10.0 (a85f6b6ce96920a8e4cb66ccffb36dba6e25a606)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
 - OS: MacIntel
 - Screen: 1663x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by FreeWall**
## Description

We don't have symbols for all networks outside suite, instead we'll use a network name.

## Related Issue

Resolve #14182

### Before
image

### After
image
image
image

### CODE REVIEW

**Review by adderpositive — DISMISSED** [review]

**Review by adderpositive — APPROVED** [review]

**Review by Hermez-cz — APPROVED** [review]

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptions.tsx [hunk 1]
```diff
@@ -12,23 +14,40 @@ export const CoinmarketVerifyOptions = ({
...
-            />
-        }
-    />
-);
+}: CoinmarketVerifyOptionsProps) => {
+    const { cryptoIdToPlatformName, cryptoIdToCoinName } = useCoinmarketInfo();
+
+    if (!receiveNetwork) {
+        return null;
+    }
```
Comment (Lemonexe) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptions.tsx]: I'd make `receiveNetwork` prop non-nullable and remove this `if`.
`CoinmarketVerifyOptions` is called from two places, and `receiveNetwork` is non-nullable at both, so there seems to be no reason to keep it nullable (and potentially cause problems in future).

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptionsItem.tsx [hunk 2]
```diff
@@ -56,6 +59,16 @@ export const CoinmarketVerifyOptionsItem = ({
             </Row>
         );
     }
+
+    if (!receiveNetwork) {
+        return null;
+    }
```
Comment (Lemonexe) [inline packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptionsItem.tsx]: Same as above in `CoinmarketVerifyOptions.tsx`

**Review by Lemonexe — APPROVED** [review]
Looks fine, works as supposed to, but please adress the two comments about maintainability before merging :slightly_smiling_face:

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptionsItem.tsx (hunk 2 above)
Comment (FreeWall) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptionsItem.tsx]: fixed in https://github.com/trezor/trezor-suite/pull/14294/commits/8835cb5273c4bb999ec1a3e73a4c86241fdfa730

File: packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptions.tsx (hunk 1 above)
Comment (FreeWall) [reply packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptions.tsx]: fixed in https://github.com/trezor/trezor-suite/pull/14294/commits/8835cb5273c4bb999ec1a3e73a4c86241fdfa730

**Review by Lemonexe — APPROVED** [review]

**Review by tomasklim — CHANGES_REQUESTED** [review]
Does not work for me when device is remembered, not connected. Is it expected?

https://github.com/user-attachments/assets/7d825c63-74ed-427a-81b0-e0683cf62dba

**Comment by adderpositive** [comment]
@tomasklim it is allowed only for **Buy**. For **Swap**, it does not make sense, because you need to sign your transaction.

**Review by tomasklim — APPROVED** [review]
