### PR TITLE
fix: Clear Suite Sync keys when Suite Sync is disabled

### LINKED ISSUE #26466: Clear Suite Sync keys when Suite Sync is disabled
When a user disables Suite Sync in settings, we should delete `delegatedIdentityKey` and `suiteSyncOwners`. Local database data should remain stored, but it will stay encrypted and unreadable until the user enables Suite Sync again and approves issuing new keys on the Trezor.

The same behavior should apply when Suite Sync is disabled remotely through message-system: keep the database, but delete the keys as well.

Feel free to split this issue into multiple issues (mobile, desktop, message system...)

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/26466

### Testing

After turning off suite sync, the encrypted owner data are not present in the app state

After turning suite sync off => 
image

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=clear-suite-sync-keys&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=clear-suite-sync-keys&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=clear-suite-sync-keys&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 13 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-14T09:22:45.637Z • 13 test(s) total_

<details><summary>Trezor Suite (desktop) — 12 test(s)</summary>

| Test | Type |
|------|------|
| Quarantine test: "Receive transaction,Receive a ETH transaction" | 🙋 manual |
| Quarantine test: "Global receive and send,Global receive" | 🙋 manual |
| Bridge > App acquired device, EXTERNAL bridge is restarted, app reconnects | 🤖 auto |
| Bridge > App spawns bundled bridge and stops it after app quit | 🤖 auto |
| Bridge > App in daemon mode spawns node-bridge | 🤖 auto |
| Onboarding - create wallet > Success (basic) | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-04-14T09:20:55.615Z • 12 test(s) total_

### CODE REVIEW

File: suite-common/suite-sync/src/storage/createTurnOffSuiteSyncForWallet.ts [hunk 1]
```diff
@@ -16,4 +19,5 @@ export const createTurnOffSuiteSyncForWallet =
 
         deps.subscriptionStorage.dispose(storageId);
         await deps.suiteSyncStorageRepository.delete(storageId);
+        deps.dispatch(setSuiteSyncOwner({ deviceStaticId: deviceStaticSessionId, owner: null }));
```
Comment (OriginalEveres) [inline suite-common/suite-sync/src/storage/createTurnOffSuiteSyncForWallet.ts]: I'm not sure - can `await deps.suiteSyncStorageRepository.delete(storageId)` fail / throw with unexpected state?

If so, than the clearance of SS keys won't be done. From defensive point of view I would maybe call it before the await, since there is the call for dispose function inside. WDYT?

File: suite-common/suite-sync/src/storage/tests/createTurnOffSuiteSyncForWallet.test.ts [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+import { createMockDeps, mock } from '@suite-common/dependency-injection';
+import { type StaticSessionId } from '@trezor/connect';
+
+import { setSuiteSyncOwner } from '../../suiteSyncSlice';
+import { createStorageIdFromDeviceStaticSessionId } from '../createStorageIdFromDeviceStaticSessionId';
+import { createSubscriptionStorageMock } from '../createSubscriptionStorage.mock';
+import {
+    type CreateTurnOnSuiteSyncForWalletDeps,
+    createTurnOffSuiteSyncForWallet,
+} from '../createTurnOffSuiteSyncForWallet';
```
Comment (OriginalEveres) [inline suite-common/suite-sync/src/storage/tests/createTurnOffSuiteSyncForWallet.test.ts:12]: importing `CreateTurnOnSuiteSyncForWalletDeps` from `createTurnOffSuiteSyncForWallet`? I'm confused by this a little bit

Comment (OriginalEveres) [reply suite-common/suite-sync/src/storage/tests/createTurnOffSuiteSyncForWallet.test.ts:12]: 👍 fixed, resolving conversation

File: suite-common/suite-sync/src/storage/createTurnOffSuiteSyncForWallet.ts [hunk 3]
```diff
@@ -1,19 +1,29 @@
...
     async ({ deviceStaticSessionId }) => {
         const storageId = createStorageIdFromDeviceStaticSessionId(deviceStaticSessionId);
 
-        deps.subscriptionStorage.dispose(storageId);
-        await deps.suiteSyncStorageRepository.delete(storageId);
+        try {
+            deps.subscriptionStorage.dispose(storageId);
+            await deps.suiteSyncStorageRepository.delete(storageId);
+        } finally {
+            // Defensively always delete keys
```
Comment (OriginalEveres) [inline suite-common/suite-sync/src/storage/createTurnOffSuiteSyncForWallet.ts:24]: 👍

File: suite-common/suite-sync/src/storage/tests/createTurnOffSuiteSyncForWallet.test.ts [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+
+        expect(deps.subscriptionStorage.dispose).toHaveBeenCalledWith(storageId);
+        expect(deps.suiteSyncStorageRepository.delete).toHaveBeenCalledWith(storageId);
+        expect(deps.dispatch).toHaveBeenCalledWith(
+            setSuiteSyncOwner({
+                deviceStaticId: DEVICE_STATIC_SESSION_ID_123,
+                owner: null,
+            }),
+        );
+    });
```
Comment (OriginalEveres) [inline suite-common/suite-sync/src/storage/tests/createTurnOffSuiteSyncForWallet.test.ts:42]: nit: maybe add a case when the dispose fails

**Review by OriginalEveres — APPROVED** [review]
LGTM!
