### PR TITLE
fix(suite): navigate to correct network when clicking stake on dashboard

### LINKED ISSUE #25995: Clicking staking button on dashboard opens staking for a different cryptocurrency
**Describe the bug**
When clicking the staking button on the dashboard, the app opens the staking section for a different cryptocurrency than the one selected.

**Info:**
 - Suite version: desktop 26.4.0 (1cf032552e07dfcad8a932ff743c51c04d6735e6)
 - Browser: Trezor Suite 26.4.0
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: Trezor T3T1 2.11.0 universal (revision 725c0c01879329900f08fc453d8fd0fcb4d86090)
 - Transport: BridgeTransport 3.2.1, BluetoothTransport

**Video:**

https://github.com/user-attachments/assets/75443ec9-669d-45c1-a466-9a31aff0592e

### PR DESCRIPTION
**Pull request by izmy**
## Description

When clicking the staking button on the dashboard, the app was navigating to `wallet-staking` without explicit route params, which caused the staking page to open for the last active account instead of the selected cryptocurrency.

Fix passes explicit `symbol`, `accountIndex`, and `accountType` params when navigating to `wallet-staking` from `TradingButton`.

Also:
- Restricts `routeName` prop to a `TradingButtonRoute` union type (`wallet-staking | wallet-trading-buy`) for type safety
- Replaces deprecated `spacings.*` token usage with literal values in `AssetRow` and `AssetsView`

## Notes for QA

On the dashboard, click the Stake button for a cryptocurrency that is **not** the currently active account. Verify the staking page opens for the correct cryptocurrency.

## Related Issue

Resolve #25995

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/dashboard-staking-button-wrong-network&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/dashboard-staking-button-wrong-network&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 9 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Labeling migration > Migration from Dropbox | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-17T17:08:55.613Z • 9 test(s) total_

<details><summary>Trezor Suite (desktop) — 8 test(s)</summary>

| Test | Type |
|------|------|
| Account transactions overview > Check graph span and search a transaction by BTC address | 🤖 auto |
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-03-17T17:07:00.428Z • 8 test(s) total_

### CODE REVIEW

File: packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx
Comment (tomasklim) [inline packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx]: Uff TradingButton used for staking

File: packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx [hunk 1]
```diff
@@ -43,7 +45,19 @@ export const TradingButton = ({
             );
         }
 
-        dispatch(goto({ routeName }));
+        dispatch(
```
Comment (tomasklim) [inline packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx]: moving it to `if (account)` would make more sense

File: packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx
Comment (izmy) [reply packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx]: Yes, this naming is semantically wrong... so I renamed it to `AssetActionButton`

File: packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx (hunk 1 above)
Comment (izmy) [reply packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx]: Staking should always navigate, even without an account (using defaults). Splitting by route makes this clearer.

**Review by tomasklim — APPROVED** [review]
