### PR TITLE
fix(suite-native): fix fees selector ui

### LINKED ISSUE #26798: Network fee component - fixes
1. Network fee component has too big inner spacing. It should be 12px. [Figma](https://www.figma.com/design/g9LLS8q9IpUY8UTTBvQAJF/Send--Final-?node-id=2726-7499&t=Znj5bIhe3SWnlK7H-4)

Image

2. When network fees are being calculated already show the component to the user with the skeleton, so that the user knows that something is happening. Nowadays it looks like he is stuck.

Image

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

change card's padding
display loader if fees are not loaded yet instead of hiding the selector

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/26798

## Screenshots:

https://github.com/user-attachments/assets/a427a915-29ea-4303-bb48-7f31cb0fa193

## 🔍 Currents Test Results

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/fees-loader&lookback=7)

### CODE REVIEW

File: suite-native/transaction-management/src/components/fees/FeeSelector.tsx [hunk 1]
```diff
@@ -115,7 +115,7 @@ export const FeeSelector = ({
                 />
             ) : (
                 <FeeSummaryCard
-                    fee={fee}
+                    fee={fee ?? ''}
```
Comment (cermakjiri) [inline suite-native/transaction-management/src/components/fees/FeeSelector.tsx]: isn't better to accept `undefined` fee too rather than making it pseudo valid?

**Review by cermakjiri — APPROVED** [review]

File: suite-native/transaction-management/src/components/fees/FeeSelector.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/transaction-management/src/components/fees/FeeSelector.tsx]: very good point, thank you
