### PR TITLE
fix(suite-native): Update Earn Tiles

### LINKED ISSUE #26187: Earn: Update Earn List Item UI
update Earn Items values according to:

Stablecoin Yield: https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=5104-25222&t=uoAHKxqZqaxBp0gb-1

Staking: https://www.figma.com/design/XvZrwAtaxvOID7BqR1PIes/Earn--Final-?node-id=5104-25166&t=uoAHKxqZqaxBp0gb-1

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

Updated Earn Tiles UI 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/26187

## Screenshots:

Screenshot 2026-03-27 at 14 10 10
Screenshot 2026-03-27 at 14 10 05

## 🔍 Currents Test Results

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/earn-change&lookback=7)

### CODE REVIEW

File: suite-native/module-earn/src/components/EarnActiveItemsBottomSheet.tsx [hunk 1]
```diff
@@ -71,18 +70,19 @@ const formatActiveItemBalance = (item: EarnDepositsCardActiveItem) => {
...
     const isStakingItem = item.type === 'staking';
+    const isStablecoinYieldItem = item.type === 'stablecoin-yield';
 
     const stakingApy = useStakingSelector(state =>
         isStakingItem ? selectAPYByAccountKey(state, item.accountKey) : null,
     );
 
     const apyValue = isStakingItem ? (stakingApy ?? item.apy) : item.apy;
-    const apyText = apyValue === null ? null : `${apyValue}% APY`;
+    const apyText = apyValue ? `${apyValue}% APY` : null;
```
Comment (izmy) [inline suite-native/module-earn/src/components/EarnActiveItemsBottomSheet.tsx]: Wouldn't it be better to have a helper for this? Or maybe extend somehow ApyValue?

**Review by izmy — APPROVED** [review]

File: suite-native/module-earn/src/components/EarnActiveItemsBottomSheet.tsx (hunk 1 above)
Comment (BrantalikP) [reply suite-native/module-earn/src/components/EarnActiveItemsBottomSheet.tsx]: I would not overcomplicate the ApyValue com, but here is the localized text at least :) https://github.com/trezor/trezor-suite/pull/26259/changes/f019d7a2f82ac75f2ea36bf17cafa69d2f5ce068
