### PR TITLE
fix(suite): fix sats appearing for unsupported networks in toasts

### LINKED ISSUE #6520: sat LTC in notification instead of LTC
**Describe the bug**
We are not using smaller units on LTC. However if user switch to Satoshis on Bitcoin account it erroneously starts showing up in notifications of LTC transactions `sat LTC`. It should stick to `LTC`.

image

### PR DESCRIPTION
**Pull request by dahaca**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/6520

## Screenshots:
image

### CODE REVIEW

File: suite-common/wallet-utils/src/settingsUtils.ts [hunk 1]
```diff
@@ -1,9 +1,19 @@
...
     value: localCurrency,
     label: localCurrency.toUpperCase(),
 });
 
-export const getAreSatoshisUsed = (bitcoinAmountUnit: PROTO.AmountUnit) =>
-    bitcoinAmountUnit === PROTO.AmountUnit.SATOSHI;
+export const getAreSatoshisUsed = (bitcoinAmountUnit: PROTO.AmountUnit, symbol: NetworkSymbol) => {
+    const areSatsDisplayed = bitcoinAmountUnit === PROTO.AmountUnit.SATOSHI;
+
+    const areUnitsSupportedByNetwork =
```
Comment (matejkriz) [inline suite-common/wallet-utils/src/settingsUtils.ts]: consider to use `hasNetworkFeatures` util for it, this ignores settings for account types

File: suite-common/wallet-utils/src/settingsUtils.ts [hunk 2]
```diff
@@ -1,9 +1,19 @@
...
+        symbol &&
+        NETWORKS.find(({ symbol: networkSymbol }) => networkSymbol === symbol)?.features?.includes(
+            'amount-unit',
+        );
+
+    return areSatsDisplayed && areUnitsSupportedByNetwork;
```
Comment (matejkriz) [inline suite-common/wallet-utils/src/settingsUtils.ts:16]: check for device support is not relevant here? https://github.com/trezor/trezor-suite/blob/fix/send-toast-units/packages/suite/src/hooks/wallet/useBitcoinAmountUnit.ts/#L33

Comment (dahaca) [reply suite-common/wallet-utils/src/settingsUtils.ts:16]: Nope, that one is for knowing if it's possible to send. I actually wanted to rename the `areSatsUsed` flag to `areSatsSendable` since it's only used in that context.

File: suite-common/wallet-utils/src/settingsUtils.ts (hunk 1 above)
Comment (dahaca) [reply suite-common/wallet-utils/src/settingsUtils.ts]: b35cfaa5c8581471bffc234228a1bffa4b1fc3fb

File: suite-common/wallet-utils/src/settingsUtils.ts (hunk 2 above)
Comment (dahaca) [reply suite-common/wallet-utils/src/settingsUtils.ts:16]: f78be0db9acc6428e7c0442fe4bfed17369f5b24

**Review by matejkriz — APPROVED** [review]
looks good, works fine for me 👍 please squash&merge
