### PR TITLE
fix(suite-native): pin matrix screen oveflow

### LINKED ISSUE #17035: PIN entry for T1 on mobile is out of view for some phones or displays
**Describe the bug**
On some phones or displays, the PIN matrix for T1 entry can be out of view, see screenshot.

**Info:**

-   Mobile Suite Version: 25.1.3 production
-   OS: Android

**How to reproduce**

1. It is better to make text/icons larger in usability settings firts (more apparent)
2. Connect T1 with PIN protection enabled
3. Either the whole bottom row or just confirm button is not in the view (and cant be scrolled to view)

**Screenshots**

Image

Image

With enlarged usability settings:

Image

### PR DESCRIPTION
**Pull request by PeKne**
- hides the image on pin matrix screen if the screen is too small to render everything

## Related Issue

Resolve #17035 

### with regular font size

https://github.com/user-attachments/assets/ea1416fb-0236-40d6-99f9-a79f91252369

### With enlarged fonts

https://github.com/user-attachments/assets/2a640ec0-b89a-4629-ade5-8c74b1232bc5

### CODE REVIEW

File: suite-native/module-authorize-device/src/components/connect/PinOnKeypad.tsx [hunk 1]
```diff
@@ -74,41 +86,67 @@ export const PinOnKeypad = ({ variant, onSuccess }: PinOnKeypadProps) => {
...
     const translations = translationsMap[variant];
 
+    // Hide image if the screen is too small to fit both the image and the pin matrix.
+    const handlePinMatrixLayoutEvent = (event: LayoutChangeEvent) => {
+        if (event.nativeEvent.layout.height > 0.5 * SCREEN_HEIGHT) {
+            setIsImageDisplayed(false);
+
+            return;
+        }
+        setIsImageDisplayed(true);
```
Comment (yanascz) [inline suite-native/module-authorize-device/src/components/connect/PinOnKeypad.tsx]: What about this?
```suggestion
        setIsImageDisplayed(event.nativeEvent.layout.height <= 0.5 * SCREEN_HEIGHT);
```

Comment (PeKne) [reply suite-native/module-authorize-device/src/components/connect/PinOnKeypad.tsx]: good idea, fixed 11453ba0d5

File: suite-native/module-authorize-device/src/components/connect/PinOnKeypad.tsx [hunk 2]
```diff
@@ -74,14 +79,28 @@ export const PinOnKeypad = ({ variant, onSuccess }: PinOnKeypadProps) => {
...
+    useEffect(() => {
+        const { height, scale, fontScale } = windowDimensions;
+
+        // If user has too small device or uses accessibility settings for screen content enlargement,
+        // the image is hidden to make sure the the content fits in the screen.
+        if (height < 720 || fontScale > 1 || scale > 3) {
+            setIsImageDisplayed(false);
+        } else {
+            setIsImageDisplayed(true);
+        }
```
Comment (yanascz) [inline suite-native/module-authorize-device/src/components/connect/PinOnKeypad.tsx:93]: I'd prefer to show what conditions need to be met to **show** the image (i.e. to focus on the positive outcome rather than the negative one) and then simplify like this:
```suggestion
        setIsImageDisplayed(height >= 720 && fontScale <= 1 && scale <= 3);
```

**Review by yanascz — APPROVED** [review]
Nice and clean solution after all the iterations! 👏
