### PR TITLE
fix(suite): labels for transaction proper spacing

### LINKED ISSUE #11032: Send dialogue minor issues
**Describe the bug**
See screenshot
- [x] amount is not properly rendered when you enter fiat value first **(edit: fix by fixed by #11061)**
- [x] when using coin control and there is input with long label its not rendered/shortened properly  **(edit fix here: https://github.com/trezor/trezor-suite/pull/11063)

**Info:**
 - Suite version: desktop 24.2.0 (d3a7b23a070f251e1ef5cfd9064a2b1d3d779026)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.2.0 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
Screenshot 2024-02-05 at 12 43 02

### PR DESCRIPTION
**Pull request by peter-sanderson**
## Description

- Fixes overflow for buttons in general
- fixes size of Label buttons

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11032

## Screenshots:

image

image

image

### CODE REVIEW

**Review by jvaclavik — APPROVED** [review]

**Review by jvaclavik — APPROVED** [review]
Looks good, but I will check the app in half an hour if nothing is broken by that button change.

**Review by jvaclavik — APPROVED** [review]

File: packages/suite/src/components/suite/NotificationCard.tsx [hunk 1]
```diff
@@ -98,9 +107,11 @@ const Body = styled.div`
 
 const CardButton = ({ href, ...props }: ButtonType) => {
     if (href) {
-        <TrezorLink variant="nostyle" href={href}>
```
Comment (peter-sanderson) [inline packages/suite/src/components/suite/NotificationCard.tsx:101]: Missing return here. Lol.

**Review by jvaclavik — APPROVED** [review]
