### PR TITLE
Fix send form when sending ERC-20

### LINKED ISSUE #8099: Erc20 tokens interpreted as Ethereum in confirm modal of send dialogue.
**Describe the bug**
Erc20 tokens interpreted as Ethereum in confirm modal of send dialogue.
You are sending token but Suite reports amount and value in Ethereum

**Steps to reproduce:**
1. Navigate to Send section
2. Try to send ERC20 token
3. Observe confirm modal during tx signing

**Info:**
 - Suite version: desktop 23.4.1 (cff9e3ab255d4a7feebe7fb81ff3170146ee3537)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.1 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.27

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by tomasklim**
## Description

- add contract to send form
- fix token symbol

## Related Issue

closes #8099

## Screenshots:
Screenshot 2023-04-14 at 12 30 56

### CODE REVIEW

**Comment by matejkriz** [comment]
Looks good to me, but @dahaca please check it too 👀

**Comment by tomasklim** [comment]
QA, please test in RELEASE. There will be change during cherrypick from attribute `contract` to `address`

File: packages/suite/src/components/suite/modals/ReviewTransaction/constructOutputs.ts [hunk 1]
```diff
@@ -215,10 +215,14 @@ const constructNewFlow = ({
     } else {
         precomposedTx.transaction.outputs.forEach(o => {
             if (typeof o.address === 'string') {
+                if (precomposedTx.token) {
+                    outputs.push({ type: 'contract', value: precomposedTx.token.contract });
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReviewTransaction/constructOutputs.ts:219]:
```suggestion
                    outputs.push({ type: 'contract', value: precomposedTx.token.address });
```
@komret for release branch

**Review by dahaca — APPROVED** [review]
