### PR TITLE
Coinmarket: Allow multiple slashes in `formDraftKey`

### LINKED ISSUE #12927: Error: Invalid formDraftKey
Sentry Issue: [TREZOR-SUITE-ZKD](https://satoshilabs.sentry.io/issues/5495941693/?referrer=github_integration)

```
Error: Invalid formDraftKey
  at None (/js/main.efd63902.js:1:1074538)
  at None (/js/main.efd63902.js:1:1074569)
  at None (/js/main.efd63902.js:1:1074457)
  at None (/js/vendors.d7aa5cb3.js:2:3739451)
  at Object.dispatch (/js/vendors.d7aa5cb3.js:2:3742783)
...
(36 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by marekrjpolak**
## Description

There are slashes in taproot account keys, so `parseFormDraftKey` sometimes failed on `formDraftKey.split('/').length === 2` check. This PR should fix it by using everything after first slash as an account key.

## Related Issue

Resolve #12927

## QA

- go to Taproot account
- go to Trade section
- type something into the form, creating a form draft
- go directly into application settings
- switch from BTC to sats or vice versa
  - before the fix, an error log should appear in the console
  - after the fix, error log should be gone

### CODE REVIEW

File: suite-common/wallet-utils/src/formDraftUtils.ts [hunk 1]
```diff
@@ -5,9 +5,12 @@ export const getFormDraftKey = (prefix: FormDraftKeyPrefix, key: string) => `${p
 export const parseFormDraftKey = (
     formDraftKey: string,
 ): [prefix: FormDraftKeyPrefix, key: string] => {
-    const strings = formDraftKey.split('/');
-    if (strings.length === 2) {
-        return strings as [prefix: FormDraftKeyPrefix, key: string];
+    const delimiter = formDraftKey.indexOf('/');
```
Comment (yanascz) [inline suite-common/wallet-utils/src/formDraftUtils.ts]: Just a nitpick... I'd go with `delimiterIndex` or similar since it's not a delimiter in fact.

**Review by yanascz — COMMENTED** [review]
Seems fine, just one naming nitpick.

File: suite-common/wallet-utils/src/formDraftUtils.ts (hunk 1 above)
Comment (marekrjpolak) [reply suite-common/wallet-utils/src/formDraftUtils.ts]: https://github.com/trezor/trezor-suite/pull/12929/commits/223eefde583e92fc248361df94fc5d665613cf8a

**Review by yanascz — APPROVED** [review]
