### PR TITLE
fix(suite-data): update Firefox min version

### LINKED ISSUE #11026: Minimum Firefox version reported as 78 in placeholder even 102 is minimum version
**Describe the bug**

Minimum Firefox version reported as 78 in placeholder even 102 is minimum version
https://github.com/trezor/trezor-suite/blob/b0d4b11876eb1b49ef80691c4db2b6f60f416cee/packages/suite-build/browserslist#L2

**Steps to reproduce:**
1. Navigate to https://suite.trezor.io/web with Firefox older 102

**Info:**
 - Suite version: web 24.1.3 (240373658ecb4b9ea1e6b09e06e657722ae6c2f1)
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: 
 - Transport: N/A

**Expected result:**

**Actual result:**
A clear and concise description of what actually happens.

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by karliatto**
## Description
Min Firefox supported version is 102 (https://github.com/trezor/trezor-suite/blob/b0d4b11876eb1b49ef80691c4db2b6f60f416cee/packages/suite-build/browserslist#L2) but we display 78+ in UI.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/11026

## Screenshots:
image

### CODE REVIEW

File: packages/suite-data/src/browser-detection/index.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ window.addEventListener('load', () => {
     };
 
     const firefox = {
-        name: 'Firefox 78+',
+        name: 'Firefox 102+',
```
Comment (tomasklim) [inline packages/suite-data/src/browser-detection/index.ts:101]: It would be nice to use version from `supportedBrowsers` const to avoid those errors

**Review by tomasklim — APPROVED** [review]
