### PR TITLE
fix(suite): Adjust IO dropdowns style for Coinjoin transaction detail

### LINKED ISSUE #13098: Drop-down selector size changes after opening.
**Describe the bug**
Drop-down selector size changes after opening.
See videos from transaction detail and onboarding 

https://satoshilabs.slack.com/archives/G019WLX2P7B/p1719738173339079

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: web 24.7.0 (c00e0472d7b36073dc95265d90b83900c4f5d299)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision 2e10618876be8a09a9d985098429f3016baf348e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

https://github.com/trezor/trezor-suite/assets/31506317/216f4e40-e08a-4463-984b-cbfe7473c31b

https://github.com/trezor/trezor-suite/assets/31506317/68350718-10ef-4b28-a0b6-ae76d564bed6

### PR DESCRIPTION
**Pull request by hstastna**
## Description

Drop-down selector size in Coinjoin transaction detail window was unexpectedly changing after opening or while hovering. After removing unnecessary css of related `StyledCollapsibleBox`, adding proper and missing `Divider` component instead of achieving the same using css and after adjusting related padding values, we achieve the expected look.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13098

## Videos:
**Before:**

https://github.com/trezor/trezor-suite/assets/13417815/5341f914-55c8-45f8-8401-fc78a291ceaa

**After:**

https://github.com/trezor/trezor-suite/assets/13417815/0d376437-1c80-4a0f-ba4a-dfed1763c81f

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx [hunk 1]
```diff
@@ -34,38 +27,15 @@ const Wrapper = styled.div`
 `;
 
 const StyledCollapsibleBox = styled(CollapsibleBox)<{ $elevation: Elevation }>`
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:29]: Can you use it without `StyledCollapsibleBox`, just using `CollapsibleBox`?

Also I think you don't need `$elevation` here and I think also other props are not necessary.

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx [hunk 2]
```diff
@@ -476,7 +446,8 @@ const CollapsibleIOSection = ({
             $elevation={elevation}
             heading={heading}
             defaultIsOpen={opened}
-            paddingType="large"
+            paddingType="none"
+            fillType="none"
         >
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:452]: Also `hasDivider={false}` should be here

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx (hunk 1 above)
Comment (hstastna) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:29]: We don't need elevation here, right. But adjusting `CollapsibleBox.Header` and `CollapsibleBox.Content` is needed to achieve a nice and consistent look in different window sizes and zoom levels. Not sure I can adjust those sub-components the other way if we don't export them too

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx (hunk 2 above)
Comment (hstastna) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:452]: So finally I think this is really good to add this prop here. Thanks!

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx (hunk 1 above)
Comment (hstastna) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:29]: I've asked the designer on his opinion about CollapsibleBox look in the various places, will update the PR accordingly.

Comment (hstastna) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx:29]: Update: From what I've found from the designer, we want the existing padding for CollapsibleBox there, so as I've implemented, and there is some update already prepared. I'd suggest to bring newer CollapsibleBox style in followup PRs, not to mix it here. This PR's aim was just to fix what got broken to display the related drop down for coinjoin transaction the nicer way.

**Review by jvaclavik — APPROVED** [review]
