### PR TITLE
fix(suite, native): fix the issue of inconsistency between the review flow and hardware display.

### LINKED ISSUE #19014: XLM: Align Trezor Suite with T1B1
**Describe the bug**  
Currently, Trezor Suite displays a generic "Follow instructions" message instead of the proper send flow, which only appears after confirming on the Trezor device.

**Info:**  
- Suite version: web 25.6.0 (f57a9e24a5c77183ff4c892c05c932772931d69a)  
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36  
- OS: Linux x86_64  
- Screen: 2880x1800  
- Device: Trezor T1B1 1.13.1 regular (revision 2a65d18200580005dc419b9569ed97fae440806a)  
- Transport: WebUsbTransport  

**Screenshots:**  
Image

### PR DESCRIPTION
**Pull request by overcat**
## Description

The review interface of Stellar transactions has discrepancies with the hardware display (Safe 3 / Safe 5 and Model T), and this PR fixes that issue.

For transactions related to creating new accounts, there will still be a slight deviation, but I do not intend to fix it in the suite; instead, I will modify the firmware. See https://github.com/trezor/trezor-suite/issues/18706#issuecomment-2911030570

For Model One, its flow is quite different from the other three devices, and I will modify it in another PR.

## Related Issue
#19014 and #18706

## Screenshots:
desktop
native

### CODE REVIEW

**Review by vytick — COMMENTED** [review]
Mobile signing flow doesnt really follow what is on trezor screen. 

For example there is no confirmation of memo compared to what is there for ripple memo and it starts showing confirmed data only after a few steps are confirmed on trezor.

**Comment by overcat** [comment]
> Mobile signing flow doesnt really follow what is on trezor screen.
> 
> For example there is no confirmation of memo compared to what is there for ripple memo and it starts showing confirmed data only after a few steps are confirmed on trezor.

Hi @vytick, which wallet device are you using?

**Comment by vytick** [comment]
Trezor Safe 5 (I hope that I havent missed latest updates on the code)

**Comment by overcat** [comment]
Hi @vytick, maybe you can try running `yarn build:libs` first? I just tested it on Safe 3 and Model T, and it worked as expected.

In addition, I did not design a separate page for memo; it only appears in the review entries and does not have any special design compared to other entries.

**Comment by vytick** [comment]
I cleaned everything and tried once more and it works since then 🤷‍♂️. So there was probably something bad at my machine after I checked out this branch.

**Review by tomasklim — APPROVED** [review]
Desktop approved, checked on model T

**Comment by tomasklim** [comment]
> ... and I will modify it in another PR.

I think we can also get rid of `Signing on testnet network` 
+ ignoring timebounds in case they are not set

Let's leave it in suite until it is changed in fw

**Comment by overcat** [comment]
> I think we can also get rid of Signing on testnet network

I think it still makes sense to keep it, but we could consider merging it with other content and placing it on the last page.

File: suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx [hunk 1]
```diff
@@ -35,6 +38,27 @@ export const SendOutputsReviewScreen = ({
...
+        (state: AccountsRootState & DeviceRootState & SendRootState) =>
+            selectIsTransactionReviewInProgress(state, accountKey, tokenContract),
+    );
+
+    const handleOnDeviceTransactionReview = useHandleOnDeviceTransactionReview();
+
+    useFocusEffect(
+        useCallback(() => {
+            if (!isTransactionReviewInProgress && !hasReviewAlreadyStarted) {
+                handleOnDeviceTransactionReview();
```
Comment (PeKne) [inline suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx]: What about calling the `handleOnDeviceTransactionReview()` already at line 136 of the `SendAddressReviewScreen` file inside of the `if (networkType === 'stellar')` code block?

I would like it more because this file is now more complicated than it needs to be by stellar-specific code even though the keyword stellar is not mentioned anywhere in this file. Might bring some confusion during later development. If you move the call there, you can remove all the changes of this file added in this PR.

File: suite-native/module-send/src/components/SendFeesForm.tsx [hunk 2]
```diff
@@ -132,6 +132,13 @@ export const SendFeesForm = ({ accountKey, tokenContract }: SendFormProps) => {
                 tokenContract,
                 transaction: selectedFeeLevelTransaction,
             });
+        } else if (networkType === 'stellar') {
+            // The first review entry of Stellar is neither a destination address nor a destination tag.
```
Comment (PeKne) [inline suite-native/module-send/src/components/SendFeesForm.tsx:143]:
```suggestion
            // The first review entry of Stellar is neither a destination address nor a destination tag.
            handleOnDeviceTransactionReview();
```

Comment (overcat) [reply suite-native/module-send/src/components/SendFeesForm.tsx:143]: Hi @PeKne, I think we can't simply use this method because `handleOnDeviceTransactionReview` internally uses [`const { transaction } = route.params;`](https://github.com/trezor/trezor-suite/blob/6093a076fbff8b693ce596464cad0d2bf3ea4ee7/suite-native/module-send/src/hooks/useHandleOnDeviceTransactionReview.tsx#L42
), and this tx is generated on [line L101](https://github.com/trezor/trezor-suite/blob/6093a076fbff8b693ce596464cad0d2bf3ea4ee7/suite-native/module-send/src/components/SendFeesForm.tsx#L101
), but we haven't placed it into `route.params` yet.

File: suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx (hunk 1 above)
Comment (overcat) [reply suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx]: In fact, it is not only applicable to Stellar but also to all transactions that do not use the destination address/memo as the first review item. However, among the chains we currently support, only Stellar meets this condition, so it appears to be specific to Stellar.

File: suite-native/module-send/src/components/SendFeesForm.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/module-send/src/components/SendFeesForm.tsx:143]: Then you would have it pass it as a prop to the `usHandleOnDeviceTransactionReview` hook instead of reading it directly from the navigation. But if you don't like it I propose another solution:

1. You keep all the code that was added to `SendOutputsReviewScreen` there, but you will extract it to some Stellar-specific hook. e.g. `useHandleStellarOnDeviceTransactionReview`.
2. this hook triggers strictly for the Stellar network only

What I am trying to achieve is separation of concern. In the desktop suite, there is everything happening in one single complicated hook and there is always running a lot of network-specific code that would not have to be executed most of the time. It is very non-transparent and bug-prone. We would like to avoid this in mobile (native) code.

What do you think?

Comment (overcat) [reply suite-native/module-send/src/components/SendFeesForm.tsx:143]: Hi @PeKne, thanks for the hit! See 6c1734f91e57fd267169c21563abc2b4f2007784

**Review by PeKne — APPROVED** [review]

**Comment by overcat** [comment]
Hi, if you need me to rebase and squash, please let me know.

**Comment by tomasklim** [comment]
@overcat yes please

File: suite-common/wallet-core/src/send/sendFormSelectors.ts [hunk 3]
```diff
@@ -50,13 +50,15 @@ export const selectSendFormReviewButtonRequestsCount = (
 
     const isCardano = networkType === 'cardano';
     const isEthereum = networkType === 'ethereum';
+    const isStellar = networkType === 'stellar';
```
Comment (overcat) [inline suite-common/wallet-core/src/send/sendFormSelectors.ts:53]: Hi @tomasklim, finished. 

P.S. This new change is due to the relocation of the relevant code, which is consistent with the previous changes.
