### PR TITLE
fix(blockchain-link): use connect variant available in react-native-tcp-socket

### LINKED ISSUE #25820: Unable to connect to non-secure custom electrum server
**Describe the bug**

I tried to configure a custom non-secure electrum connection, but the app is unable to connect. 

**Info:**

- Platform: mobile
- Suite Version: 26.2.2
- OS: Android, 13

**Steps to reproduce**

1. set custom non secure electrum server.
2. try to connect.

**Expected behavior**

should connect successfully.

**Screenshots**

Image

**Additional context**

I'm connecting over WG tunnel, but this server is working for other wallets on the same device. So this is not the problem.

### PR DESCRIPTION
**Pull request by yanascz**
As described in the [react-native-tcp-socket](https://github.com/Rapsssito/react-native-tcp-socket?tab=readme-ov-file#net) repo, only `connect(options[, callback])` is supported.

## Related Issue

Resolve #25820

## Screenshots:

| iOS | Android |
| --- | --- |
| image | Screenshot_20260317_165322 |

## 🔍 Currents Test Results

🔍 **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/blockchain-link/electrum-native-tcp-connection&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/blockchain-link/electrum-native-tcp-connection&lookback=7)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 9 test(s)</summary>

| Test | Type |
|------|------|
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Labeling migration > Migration from Dropbox | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-03-17T16:08:02.316Z • 9 test(s) total_

<details><summary>Trezor Suite (desktop) — 8 test(s)</summary>

| Test | Type |
|------|------|
| Account transactions overview > Check graph span and search a transaction by BTC address | 🤖 auto |
| Suite Sync - Labelling > Sync labels from server | 🤖 auto |
| Suite Sync - Labelling > Create new labels | 🤖 auto |
| Suite Sync - Remove Labels > Remove labels syncs null to relay | 🤖 auto |
| Suite Sync - Passphrase wallets > Labels on multiple wallets | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Send Base,User can perform ethereum sending on base network" | 🙋 manual |
| Quarantine CANARY test: "Use regtest to test pending transactions,Send couple of pending txs and check that they are pending until mined" | 🙋 manual |

</details>

_Updated: 2026-03-17T16:04:37.289Z • 8 test(s) total_

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]
ok

File: packages/blockchain-link/src/workers/electrum/sockets/tcp.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ export class TcpSocket extends SocketBase {
         return new Promise<TCPSocket>((resolve, reject) => {
             const errorHandler = (err: Error) => reject(err);
             socket.on('error', errorHandler);
-            socket.connect(this.port, this.host, () => {
+            socket.connect({ host: this.host, port: this.port }, () => {
```
Comment (mroz22) [inline packages/blockchain-link/src/workers/electrum/sockets/tcp.ts:16]: maybe a comment to avoid unexpected future changes could be useful

Comment (yanascz) [reply packages/blockchain-link/src/workers/electrum/sockets/tcp.ts:16]: Makes sense, added.
