### PR TITLE
fix(suite): display symbols

### LINKED ISSUE #16121: Fix network display symbol
**Describe the bug**

- in some places in the app, the display symbol is not used

- [x] Trade section - account dropdown and balance
Screenshot 2024-12-29 at 17 11 50

- [x] Trade section - trade summary (You pay, you get)

Screenshot 2024-12-29 at 17 14 00

- [x] Trade section - confirm receive address

Screenshot 2024-12-29 at 17 14 17

- [x] CSV import - should use `NetworkSymbol` and not `DisplaySymbol` (it is ok in UI but logic does not parse it)

Screenshot 2024-12-29 at 17 17 10
Screenshot 2024-12-29 at 17 17 25

- [x] Export - Uses `NetworkSymbol` and not `DisplaySymbol`. The symbol next to network name is ok but not in the data.

Screenshot 2024-12-29 at 17 21 09

- [x] Display symbol in notifications is uppercased 

Screenshot 2024-12-29 at 17 30 51 (2)

### PR DESCRIPTION
**Pull request by adderpositive**
## Description
Fix display symbols. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16121

### Before
Screenshot 2024-12-29 at 17 11 50
Screenshot 2024-12-29 at 17 14 00
Screenshot 2024-12-29 at 17 14 17
Screenshot 2024-12-29 at 17 17 10
Screenshot 2024-12-29 at 17 17 25
Screenshot 2024-12-29 at 17 21 09
Screenshot 2024-12-29 at 17 30 51 (2)

### After
image

image (this is only testing case, `TEST` symbol is correct)

image
(this is only testing case, `TEST` symbol is correct)

image

image
(this is only testing case, `TEST` symbol is correct)

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx [hunk 1]
```diff
@@ -39,16 +39,16 @@ export const ConfirmAddressModal = ({ addressPath, value, ...props }: ConfirmAdd
...
 
             if (symbol && coinSymbol !== symbol) {
                 return (
                     <Translation
                         id="TR_ADDRESS_MODAL_TITLE_EXCHANGE"
                         values={{
-                            networkSymbol: symbol,
-                            networkCurrencyName: coinSymbol,
+                            networkSymbol: getNetworkDisplaySymbol(symbol),
+                            networkCurrencyName: coinSymbol?.toUpperCase(),
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx:51]: Because of L2s, there should be `on BSC network` or `on BNB Smart Chain network` so use network name or network symbol. Probably name is better?
Screenshot 2025-01-03 at 12 44 00

**Review by tomasklim — APPROVED** [review]
