### PR TITLE
fix(suite-native): wallet creation design qa fixes

### LINKED ISSUE #18687: Onboarding - create wallet design QA review
Fix the UI/UX problems described in this Figma file: 

https://www.figma.com/design/UdQpTfz2RhsoZzqLp9L8fU/Onboarding?node-id=5627-15727&m=dev

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- flaws discovered during the wallet creation design QA were fixed (see the related issue)

## Related Issue

Resolve #18687 

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/wallet-creation-design-qa&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/wallet-creation-design-qa&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/wallet-creation-design-qa&lookback=7)

### CODE REVIEW

File: suite-native/atoms/src/Sheet/BottomSheet.tsx [hunk 1]
```diff
@@ -131,6 +136,7 @@ export const BottomSheet = forwardRef<BottomSheetHandle, BottomSheetProps>(
                                     animatedSheetWrapperStyle,
                                     applyStyle(sheetWrapperStyle, {
                                         insetBottom,
+                                        maxHeight,
```
Comment (BrantalikP) [inline suite-native/atoms/src/Sheet/BottomSheet.tsx:139]: Super nit: We could allow passing an arbitrary `wrapperStyle` to the bottom sheet, in case the developer wants to override the styles without extending the props e.g., to custome background, padding, etc.

File: suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx [hunk 2]
```diff
@@ -244,7 +243,7 @@ export const FirmwareInstallationScreenContent = ({
                 <VStack
                     spacing="sp12"
                     style={applyStyle(bottomButtonsContainerStyle, {
-                        bottom: bottomButtonOffset,
+                        isConfirmOnDeviceShown: showConfirmOnDevice,
```
Comment (BrantalikP) [inline suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx]: nit: we could create a separate variable and use it everywhere

e.g 

```
const buttonContainerStyle = applyStyle(bottomButtonsContainerStyle, {
                        isConfirmOnDeviceShown: showConfirmOnDevice,
 })
```

**Review by BrantalikP — APPROVED** [review]
looks neat! 💅

File: suite-native/atoms/src/Sheet/BottomSheet.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/atoms/src/Sheet/BottomSheet.tsx:139]: Good thinking, but let's add it later if needed.

File: suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx (hunk 2 above)
Comment (PeKne) [reply suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx]: fixed and squashed
