### PR TITLE
fix(suite): rewrite settings DAC modal to actually use the thunk result

### LINKED ISSUE #22644: DAC in device settings cancelled → false positive
**Describe the bug**
After https://github.com/trezor/trezor-suite/pull/22171 Suite Desktop DAC in Device settings produces false positive device compromised screen if you cancel on device.

**How to reproduce**

1. Go to Device > Settings > Security
1. Click on Device check
1. Cancel device
1. See device compromised screen

**Expected behavior**

Should just close modal and display toast, see [release/25.10](https://dev.suite.sldev.cz/suite-web/release/25.10/web/settings/device).

## Screenshots

[bad develop](https://github.com/user-attachments/assets/53e9b64b-3dad-435d-bfe3-9e3be417ddb6)

[good release 25.10](https://github.com/user-attachments/assets/e4a4a368-d1a0-48d1-b8ab-0989678ef480)

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Fix small bug in DAC settings modal – see issue – but while doing that I realized that the modal is quite wrong to live in global state, so I rewrote it to local state.

Cause =  in #22171 `checkDeviceAuthenticityThunk` was enhanced to properly use `fulfillWithValue` & `rejectWithValue`.
But this modal wrongly relied on thunk rejection as clear proof of device compromised, but that's not so, because now all flows but check success are thunk rejection.

## Notes for QA

Modal is no longer global, so it will not overwrite other modals.  You can see that previously, the "Confirm on device" modal _replaced_ the authenticity check, but now, it _overlays_ it.

Also, I have intentionally made a UI change: when check does not complete (e.g. cancelled, transport error, but not device compromised), I will not close the modal, but let it open so you can retry. I believe that makes sense.

## Related Issue

Resolve #22644

## Screenshots:

Modal local state: can be opened and closed
[closin modal.webm](https://github.com/user-attachments/assets/2ec5df69-3e2d-49e3-bd93-4258261f0604)

Device authenticity check: compromised, cancelled, success.
[DAC.webm](https://github.com/user-attachments/assets/62d403ec-9f32-41d0-a0bb-8e9da89826de)

[Bootloader unlocked = compromised](https://github.com/user-attachments/assets/a43adc2b-82aa-46ef-b031-6c9cc51876a9), no matter the settings. The settings only affect onboarding. 

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/DAC-cancel-in-settings-false-positive&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/DAC-cancel-in-settings-false-positive&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/DAC-cancel-in-settings-false-positive&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceInititalStep.tsx
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceInititalStep.tsx:1]: JSX only extracted from `AuthenticateDeviceModal.tsx‎`

File: packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceFailStep.tsx
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceFailStep.tsx:1]: mostly moved from `AuthenticateDeviceFailModal.tsx`, closing the modal is now different

File: packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceModal.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    const isCheckFailed = result?.valid === false;
+
+    const handleClick = async () => {
+        setIsLoading(true);
+        const result = await dispatch(
+            checkDeviceAuthenticityThunk({ allowDebugKeys: isDebugModeActive }),
+        );
+        if (result.payload?.valid === true) {
+            return handleClose();
+        }
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceModal.tsx:34]: Here I have intentionally made a UI change: when check does not complete (e.g. cancelled, transport error, but not device compromised), I will not close the modal, but let it open so you can retry. I believe that makes sense.

When device compromised → show the failed step.
Only when success → close the modal (only toast is displayed)

File: packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceInititalStep.tsx
Comment (komret) [reply packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceInititalStep.tsx:1]: Please rename the file to `AuthenticateDeviceInititalStep` or something more contextual.

File: packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceFailStep.tsx
Comment (komret) [reply packages/suite/src/views/settings/SettingsDevice/AuthenticateDevice/AuthenticateDeviceFailStep.tsx:1]: nit: I'd rename the file to `AuthenticateDeviceFailStep`.

**Review by komret — APPROVED** [review]
