### PR TITLE
Reset amount, Send max and draft on token change 

### LINKED ISSUE #13494: Amount in Send form not reseted after you change token or from/to Eth
**Describe the bug**
Amount in send form not reseted after you change token or from/to Eth

**Steps to reproduce:**
1. Navigate  to send form of account that contain Eth and some Erc20 tokens
2. Click on send max after selecting token or enter amount higher than Eth amount in account
3. Change to different token with lower amount or to Eth or to token with different decimals
4. Observe error

**Info:**
 - Suite version: web 24.8.0 (6cffcc1b53fcb83d0b8b6a89c62788d248199e56)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
image
image

https://github.com/user-attachments/assets/66948242-8f63-42eb-8fb0-dd79869290fb

### PR DESCRIPTION
**Pull request by enjojoy**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/13494

## Screenshots:

https://github.com/user-attachments/assets/5deb8e4c-b98b-416a-af73-237a4beeae6b

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 1]
```diff
@@ -226,6 +226,10 @@ export const useSendForm = (props: UseSendFormProps): SendContextValues => {
         setState(getStateFromProps(props)); // resetting state will trigger "loadDraft" useEffect block, which will reset FormState to default
     }, [dispatch, props, setComposedLevels]);
 
+    const resetDraft = useCallback(() => {
+        dispatch(removeSendFormDraftThunk()); // reset draft;
```
Comment (izmy) [inline packages/suite/src/hooks/wallet/useSendForm.ts]: unnecessary comment

```suggestion
        dispatch(removeSendFormDraftThunk());
```

**Review by izmy — APPROVED** [review]
