### PR TITLE
fix(suite): fix firmware version & changelog UI

### LINKED ISSUE #4074: Installing firmware onto new device shows wrong changelog information on hover
**Describe the bug**
When you are trying to update from older firmwares or installing a new firmware onto new devices (out of the box) the changelog, on hover, states wrong version and wrong changelog info. See screenshots.

**Info:**
 - Remembered Wallet: yes/no
 - Suite Version: web/app 21.7.1
 - Browser: Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
 - OS: Win32
 - Bridge: 2.0.27
 - Firmware Version: model 1

**Steps to reproduce:**
1. Connect a new device or a device with an older (older than 1.6.3) firmware
2. Follow the instructions Suite gives you until you get to firmware install or firmware update and hover over the 1.10.2 version
3. It shows info about 1.6.3 version (as can be seen on screenshot)

**Expected result:**
When installing new firmware or updating to a new firmware the hover info shows the correct firmware version and info.

**Actual result:**
When installing new firmware or updating to a new firmware the hover info shows wrong firmware version and info.

**Screenshots:**

image

image

### PR DESCRIPTION
**Pull request by dimasivan**
fix #4074 

parse firmware changelog from `firmwareReleases.latest` for devices with intermediary firmware support.

### CODE REVIEW

File: packages/suite/src/utils/suite/device.ts [hunk 1]
```diff
@@ -355,9 +355,15 @@ export const getPhysicalDeviceCount = (devices: Device[]) => {
     return uniqueIds.size;
 };
 
-export const parseFirmwareChangelog = (firmwareRelease: TrezorDevice['firmwareRelease']) => {
+export const parseFirmwareChangelog = (
+    features: TrezorDevice['features'],
+    firmwareRelease: TrezorDevice['firmwareRelease'],
+) => {
+    const supportIntermediary = features?.major_version === 1;
```
Comment (matejkriz) [inline packages/suite/src/utils/suite/device.ts]: would be nice to create separate function for it and use it here and in `getFwUpdateVersion` to not repeat yourself (to prevent bugs in future refactoring)

```
const supportIntermediary = (features: TrezorDevice['features']) => features?.major_version === 1;
```

File: packages/suite/src/utils/suite/device.ts [hunk 2]
```diff
@@ -355,9 +355,15 @@ export const getPhysicalDeviceCount = (devices: Device[]) => {
...
     if (!firmwareRelease?.changelog || firmwareRelease?.changelog?.length === 0) return null;
-    const changelogs = firmwareRelease.changelog;
+    // Generate latest FW changelog if device has intermediary support
+    const latestChangelog = [firmwareRelease.latest];
+    const changelogs = supportIntermediary ? latestChangelog : firmwareRelease.changelog;
 
     // Default changelog format is just a long string where individual changes are separated by "*" symbol.
```
Comment (matejkriz) [inline packages/suite/src/utils/suite/device.ts]: It could be easily simplified by returning only object of changelog for desired version instead of an array with changelogs for all versions laying between because then in FirmwareOffer `parsedChangelog.slice(0, 1)` is called and only the first item is actually used 

```suggestion
    const release = firmwareRelease[supportIntermediary ? 'latest' : 'release'];

    // Default changelog format is just a long string where individual changes are separated by "*" symbol.

    const changelog = release.changelog
        .trim()
        .split('*')
        .map(l => l.trim())
        .filter(l => l.length);

    const { url, notes } = release;

    // Get firmware version, convert to string and use it as a key in custom object
    const versionString = release.version.join('.'); // e.g. [1,9,8] => "1.9.8"
    return {
        url,
        notes,
        changelog,
        versionString,
    };
```

so no more need for `.map` over all changelogs and then slicing only the first one...

Comment (dimasivan) [reply packages/suite/src/utils/suite/device.ts]: changed in e410946b8e1f2bedae5af3f407396cd634661a78
also changed parsing in `FirmwareOptions` component

File: packages/suite/src/utils/suite/device.ts (hunk 1 above)
Comment (dimasivan) [reply packages/suite/src/utils/suite/device.ts]: f86af02

Comment (matejkriz) [reply packages/suite/src/utils/suite/device.ts]: cool, just address the linter issue `'supportIntermediary' was used before it was defined` and rebase fixups and we could merge

Comment (matejkriz) [reply packages/suite/src/utils/suite/device.ts]: and fix also unit tests please

**Review by matejkriz — APPROVED** [review]
