### PR TITLE
Minor Solana fixes from Sentry

### LINKED ISSUE #16534: Could not simulate transaction: BlockhashNotFound
Sentry Issue: [TREZOR-SUITE-11S3](https://satoshilabs.sentry.io/issues/6204309293/?referrer=github_integration)

```
Could not simulate transaction: BlockhashNotFound
```

### LINKED ISSUE #16537: TypeError: Cannot destructure property 'solStakingAccounts' of 'e.misc' as it is undefined.
Sentry Issue: [TREZOR-SUITE-11XZ](https://satoshilabs.sentry.io/issues/6235460712/?referrer=github_integration)

```
TypeError: Cannot destructure property 'solStakingAccounts' of 'e.misc' as it is undefined.
  at getSolAccountTotalStakingBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/solanaStakingUtils.ts:78:13)
  at getAccountTotalStakingBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/stakingUtils.ts:32:20)
  at stakingBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/accountUtils.ts:630:21)
  at getAccountFiatBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/accountUtils.ts:672:32)
  at forEach (@trezor/suite-build/../../suite-common/wallet-utils/src/accountUtils.ts:695:13)
...
(13 additional frame(s) were not displayed)
```

### LINKED ISSUE #16538: TypeError: Cannot read properties of undefined (reading 'solStakingAccounts')
Sentry Issue: [TREZOR-SUITE-11V5](https://satoshilabs.sentry.io/issues/6221755273/?referrer=github_integration)

```
TypeError: Cannot read properties of undefined (reading 'solStakingAccounts')
  at selectSolAccountHasStaked (@trezor/suite-build/../../suite-common/wallet-core/src/accounts/accountsReducer.ts:485:27)
  at isSolStakingEnabled (@trezor/suite-build/../suite/src/components/wallet/WalletLayout/AccountsMenu/AccountSection.tsx:40:47)
  at useSelector (@trezor/suite-build/../suite/src/hooks/suite/useSelector.ts:12:5)
  at AccountSection (@trezor/suite-build/../suite/src/components/wallet/WalletLayout/AccountsMenu/AccountSection.tsx:40:26)
...
(18 additional frame(s) were not displayed)
```

### LINKED ISSUE #16539: SolanaError: Solana error #8190003; Decode this error by running `npx @solana/errors decode -- 8190003`
Sentry Issue: [TREZOR-SUITE-11Y4](https://satoshilabs.sentry.io/issues/6236465515/?referrer=github_integration)

```
SolanaError: Solana error #8190003; Decode this error by running `npx @solana/errors decode -- 8190003`
  at WebSocket.e (/web/js/201.js:116:171760)
```

### LINKED ISSUE #16559: TypeError: Cannot destructure property 'solStakingAccounts' of 'e.misc' as it is undefined.
Sentry Issue: [TREZOR-SUITE-11V6](https://satoshilabs.sentry.io/issues/6221755279/?referrer=github_integration)

```
TypeError: Cannot destructure property 'solStakingAccounts' of 'e.misc' as it is undefined.
  at getSolAccountTotalStakingBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/solanaStakingUtils.ts:78:13)
  at getAccountTotalStakingBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/stakingUtils.ts:32:20)
  at stakingBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/accountUtils.ts:630:21)
  at getAccountFiatBalance (@trezor/suite-build/../../suite-common/wallet-utils/src/accountUtils.ts:672:32)
  at forEach (@trezor/suite-build/../../suite-common/wallet-utils/src/accountUtils.ts:695:13)
...
(16 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by martykan**
## Description

Multiple fixes for Solana issues from Sentry.

1. Subscribe to Solana blocks in coinmarket form (resolves #16534)

2. Solana account.misc may be undefined - when still loading or on backend issues (resolves #16538, resolves #16537)

3. Don't log error when solana RPC channel closed (resolves #16539)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts [hunk 1]
```diff
@@ -681,6 +682,9 @@ export const useCoinmarketExchangeForm = ({
         };
     }, []);
 
+    // Subscribe to blocks for Solana, since they are not fetched globally
+    useSolanaSubscribeBlocks(account);
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts:686]: Coinmarket uses it's own duplicate of account. I am not sure if this will work 100% https://github.com/trezor/trezor-suite/issues/16524

Comment (martykan) [reply packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts:686]: TS didn't complain and when I tested it, it was fetching new blocks

Comment (tomasklim) [reply packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts:686]: @adderpositive summon

File: packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts [hunk 2]
```diff
@@ -62,6 +62,7 @@ import { useCoinmarketExchangeQuotesFilter } from 'src/hooks/wallet/coinmarket/f
 import { useCoinmarketPreviousRoute } from 'src/hooks/wallet/coinmarket/form/common/useCoinmarketPreviousRoute';
 
 import { useCoinmarketInitializer } from './common/useCoinmarketInitializer';
+import { useSolanaSubscribeBlocks } from '../../form/useSolanaSubscribeBlocks';
```
Comment (adderpositive) [inline packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts]: Nit: absolute path

File: packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts (hunk 1 above)
Comment (adderpositive) [reply packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts:686]: It should be good. The property `account` should be the selected one at this level.

**Review by adderpositive — CHANGES_REQUESTED** [review]
According to these fixes, I believe  `useSolanaSubscribeBlocks(account);` should be added to the _useCoinmarketSellForm_. We work with `account` as well. @martykan could you verify it, please?

**Comment by martykan** [comment]
Yes, good point, just added it

**Review by adderpositive — APPROVED** [review]
