### PR TITLE
Move ReconnectDevicePrompt to FirmwareInstallation

### LINKED ISSUE #12528: Firmware upgrade from 2.1.1 never starts
**Describe the bug**
- im not able to onboard old device with 2.0.5 firmware /before storage upgrade/
- upgrade **2.0.5 > 2.1.1** works as expected  ✅ 
- but **2.1.1 > 2.7.0** never starts even after i try to reconnect device in BL mode even im not asked. ❌ 
- f you start with device in bootloader mode you can upgrade to 2.7.0 see screenshot

**Steps to reproduce:**
1. Connect device with 2.1.1 firmware and no seed
2. Try to upgrade to current 2.7.0
3. Observe that installation never starts

**Info:**
 - Suite version: desktop 24.6.0 (f48ce5b81db91a7a2ce25e23554292b5eaee44cd)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.6.0 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.1.1 undefined (revision null)
 - Transport: BridgeTransport 3.0.0

**Screenshots:**
https://youtu.be/3rupJrS0pIQ

image

### PR DESCRIPTION
**Pull request by komret**
## Description

I created this bug in https://github.com/trezor/trezor-suite/pull/11300 by omitting `ReconnectDevicePrompt` from `FirmwareInitial`. The idea to have it in one place was good, but it must be in a component shared between Settings and Onboarding so that it can be displayed in both flows.

`ReconnectDevicePrompt` was missing in onboarding, so user didn't know they had to reconnect their device to upgrade FW.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/12528

## Screenshots:
Screenshot 2024-06-10 at 14 48 39

### CODE REVIEW

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx [hunk 1]
```diff
@@ -195,7 +195,7 @@ export const ReconnectDevicePrompt = ({ onClose, onSuccess }: ReconnectDevicePro
     const rebootPhase = getRebootPhase();
     const isRebootDone = rebootPhase === 'done';
     const deviceModelInternal = device?.features?.internal_model;
-    const isAbortable = isManualRebootRequired && rebootPhase == 'waiting-for-reboot';
+    const isAbortable = onClose && isManualRebootRequired && rebootPhase == 'waiting-for-reboot';
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: nit: `onClose !== undefined`

Comment (komret) [reply packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: 6ee79d50e9dda58748594a79ae2112eeb6e49e2d

**Review by peter-sanderson — APPROVED** [review]
