### PR TITLE
fix(suite): switch device during connect getAddress call

### LINKED ISSUE #20583: Connect - Passphrase is closing automatically in wallet switcher
Can't enter Passphrase because window is closing automatically.
Reproducible with Nu.fi
  
https://github.com/user-attachments/assets/2f2f0243-a4b7-469c-8eb7-d5a4613ec935

_Originally posted by @evgenysl in https://github.com/trezor/trezor-suite/issues/20225#issuecomment-3155151855_

### PR DESCRIPTION
**Pull request by martykan**
## Description

There was an issue when switching to new passphrase during Connect calls.

Add extra checks to wait for discovery to finish when handling the device switching flow. 
Also remove device lock before permission check. 

## Related Issue

Resolve #20583

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/connect-switch-getaddress&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/connect-switch-getaddress&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/connect-switch-getaddress&lookback=7)

### CODE REVIEW

File: packages/suite/src/support/suite/useConnectPopupModals.tsx [hunk 1]
```diff
@@ -13,6 +14,12 @@ import { selectRouteName } from 'src/reducers/suite/routerReducer';
 export const useConnectPopupModals = () => {
     const dispatch = useDispatch();
     const popupCall = useSelector(selectConnectPopupCall);
+    const discovery = useSelector(selectDiscoveryForSelectedDevice);
+    const isInDiscoveryFlow =
+        discovery &&
+        discovery.status !== 'failed' &&
+        discovery.status !== 'complete' &&
+        discovery.status !== 'cancelled';
```
Comment (Lemonexe) [inline packages/suite/src/support/suite/useConnectPopupModals.tsx:22]: I think there is some util for this condition, but nvm, can be done later

**Review by Lemonexe — APPROVED** [review]
Have not tested, but this condition SGTM

**Review by karliatto — APPROVED** [review]
Haven't tested but looks legit.
