### PR TITLE
Fix: remove account announcement for LTC and BCH

### LINKED ISSUE #2306: LTC change address: Remove notification
Discussed with FW and Support. The information is no longer (as) relevant. Format of the address has changed some 3 years ago and the notification is way too prominent. Tooltip will with simple _Learn more_ will do for now.

- [ ] Remove the context notification

- [ ] Create custom error message in Send upon recognition of "3" (old) address

- [ ] Add tooltip to header in Receive tab with learn more link

Screen Shot 2020-09-04 at 14 01 19

### PR DESCRIPTION
**Pull request by szymonlesisz**
fix: https://github.com/trezor/trezor-suite/issues/2306

- added validation for LTC and BCH deprecated address
- added tooltip in Receive for LTC and BCH
- remove global announcement in LTC and BTC accounts
- added common component: ReadMoreLink, which should be used in multiple places (currently used in 2, i don't want to spam this PR, there will be another PR with implementation)
- refactor of QuestionTooltip component

### CODE REVIEW

File: packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx [hunk 1]
```diff
@@ -92,7 +114,7 @@ const FreshAddress = ({
             {addressPath && <AddressPath>{addressPath}</AddressPath>}
             <AddressContainer>
                 <StyledInput
-                    label={<Translation id={addressLabel} />}
+                    label={<InputLabel isBitcoin symbol={account.symbol} />}
```
Comment (keraf) [inline packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx]: `isBitcoin` here will always be true. Not sure but I guess you want to pass the value declared higher up?

**Review by keraf — CHANGES_REQUESTED** [review]

File: packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx (hunk 1 above)
Comment (szymonlesisz) [reply packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx]: good catch, fixed

**Review by keraf — APPROVED** [review]
