### PR TITLE
fix(suite): correct amounts and token selection

### LINKED ISSUE #23877: Send form - amount issues
**Describe the bug**
- When inputing custom value in fiat, the crypto value does not calculate properly
- The Send Max option does not populate the maximum sendable amount in fiat

Edit: If you go to the Send form and manually enter a fiat amount, for example 5 USD, then switch to a different asset at the top, the fiat amount of 5 USD remains, but the crypto amount is never calculated. After that, for all assets you switch to, you can enter any values into both fields, and TS accepts it.

**This affects all accounts that hold multiple assets.**

Image

**Info:**
 - Suite version: desktop 25.12.2 (a82293e8a33dd8cbd897c3e5631e445944e9b6e9)
 - Browser: Trezor Suite 25.12.2
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: Trezor T1B1 1.13.1 universal (revision 2a65d18200580005dc419b9569ed97fae440806a)
 - Transport: BridgeTransport 3.1.0, BluetoothTransport

**Video:**

https://github.com/user-attachments/assets/a3424dbb-a553-4014-9ef2-2b316f434eaf

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Correctly handle changing token, amount (crypto/fiat) and send max to prevent mismatched amounts bugs.

## Related Issue

Resolve #23877 

## Screenshots:

https://github.com/user-attachments/assets/67fe29ec-eb0b-4c1c-bafc-17ed0eaf1cd7

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/send-form-amounts&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/send-form-amounts&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/wallet/send/Outputs/TokenSelect/SelectTokenAssetModal/SelectTokenAssetModal.tsx [hunk 1]
```diff
@@ -77,12 +78,15 @@ export function SelectTokenAssetModal({
 
         resetDraft();
 
-        setValue(tokenInputName, newlySelectedToken?.contract || account.symbol, {
+        setValue(tokenInputName, newlySelectedToken?.contract ?? null, {
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/send/Outputs/TokenSelect/SelectTokenAssetModal/SelectTokenAssetModal.tsx]: If the token is the native token (no contract address), setting it to `account.symbol` may cause weird behavior, we need to set it to `null` instead.

File: packages/suite/src/views/wallet/send/Outputs/TokenSelect/SelectTokenAssetModal/SelectTokenAssetModal.tsx [hunk 2]
```diff
@@ -77,12 +78,15 @@ export function SelectTokenAssetModal({
...
             shouldDirty: true,
         });
         setValue(amountInputName, '', {
             shouldDirty: true,
         });
+        setValue(fiatInputName, '', {
+            shouldDirty: true,
+        });
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/send/Outputs/TokenSelect/SelectTokenAssetModal/SelectTokenAssetModal.tsx:89]: Clear both the crypto and fiat amount when changing token to prevent bugs.

File: packages/suite/src/views/wallet/send/Outputs/TokenSelect/SelectTokenAssetModal/SelectTokenAssetModal.tsx (hunk 1 above)
Comment (BrantalikP) [reply packages/suite/src/views/wallet/send/Outputs/TokenSelect/SelectTokenAssetModal/SelectTokenAssetModal.tsx]: I would keep the || operator here. It also handles cases like an empty string. With the nullish coalescing operator (??), only undefined and null are handled, if this is the case we can keep it as `setValue(tokenInputName, newlySelectedToken?.contract, { ..... )`

Comment (TomasBoda) [reply packages/suite/src/views/wallet/send/Outputs/TokenSelect/SelectTokenAssetModal/SelectTokenAssetModal.tsx]: good point, thanks, changed to `newlySelectedToken?.contract || null`. The `|| null` needs to be there because TypeScript doesn't like it without it 😄

**Review by matusbalascak — APPROVED** [review]

**Review by izmy — APPROVED** [review]

**Review by cermakjiri — APPROVED** [review]
