### PR TITLE
XRP - dynamic reserve error message

### LINKED ISSUE #15894: Send XRP - hardcoded reserve error messages
The error messages validating if a user is failing the XRP reserve policy while sending the coins are hardcoded now.  (see #15893)

It is not ideal, because the Ripple network can dynamically change the reserve and then the mobile Suite would display outdated information.

To fix this, a way to inject dynamic data into the yup validation schema error messages needs to be designed and implemented. This refactor should ideally be done together with internationalizing all the yup messages because they are currently hardcoded as English.

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

In send form validation, provide dynamic XRP reserve message to the user. The reserve is taken from `account.misc.reserve` is injected into the schema validation.

> [!IMPORTANT]
> This PR does NOT handle translations for yup schema validation, as a separate issue exists for this. (https://github.com/trezor/trezor-suite/issues/11004)

## Related Issue

Resolve #15894 

## Screenshots:

<table>
<tr>
<td>
simulator_screenshot_A64A2AD0-8A86-43A3-A4B4-FDF93781B0BE
</td>
<td>
simulator_screenshot_AEEF704A-ADA4-4665-BE04-7FC231798C05
</td>
</tr>
</table>

## 🔍 Currents Test Results

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/xrp-dynamic-reserve-message&lookback=7)

### CODE REVIEW

File: suite-native/module-send/src/hooks/useSendForm.ts [hunk 1]
```diff
@@ -119,6 +138,8 @@ export const useSendForm = (accountKey: AccountKey, tokenContract?: TokenAddress
           })
         : undefined;
 
+    const rippleReserve = account ? getRippleReserve(account) : undefined;
```
Comment (izmy) [inline suite-native/module-send/src/hooks/useSendForm.ts]: The `getRippleReserve` helper looks good. However, I’m wondering if we should avoid Ripple-specific logic directly in the hook. I was thinking about adding Ripple to `getNetworkReserve`, wdyt?

Comment (TomasBoda) [reply suite-native/module-send/src/hooks/useSendForm.ts]: The network reserve for `Ripple` and `Stellar` are handled differently as for other networks (`Ethereum`, `Base`, `Arbitrum`, etc.). For these other networks, it is Suite-specific and defined in `networksConfig.ts`, whereas for `Ripple` and `Stellar` it is dynamic based on the blockchain and stored in `account.misc.reserve`. Hence we need to handle the logic separately.

File: suite-native/module-send/src/hooks/useSendForm.ts [hunk 2]
```diff
@@ -64,6 +68,21 @@ const getDefaultValues = ({
         ],
     }) as const;
 
+const getRippleReserve = (account: Account) => {
+    const networkType = getNetworkType(account.symbol);
+
+    if (networkType !== 'ripple') return undefined;
+
+    const reserve =
+        account.misc && 'reserve' in account.misc && account.misc.reserve
```
Comment (BrantalikP) [inline suite-native/module-send/src/hooks/useSendForm.ts:73]: What about this?

```
const getRippleReserve = (account: Account) => {
    const networkType = getNetworkType(account.symbol);

    const reserve = account.misc && 'reserve' in account.misc ? account.misc.reserve : undefined;
    if (networkType !== 'ripple' || !reserve) return undefined;

    return formatNetworkAmount(reserve, account.symbol);
};

```

File: suite-native/module-send/src/hooks/useSendForm.ts (hunk 1 above)
Comment (BrantalikP) [inline suite-native/module-send/src/hooks/useSendForm.ts]: nit: we already know the `networkType` here as well, there is no need to checking for it again in the `getRippleReserve`

**Review by BrantalikP — CHANGES_REQUESTED** [review]

File: suite-native/module-send/src/hooks/useSendForm.ts (hunk 1 above)
Comment (izmy) [reply suite-native/module-send/src/hooks/useSendForm.ts]: I see the sources are different, but I still think it could be nice to hide that behind a single abstraction/unified interface. But it's just an idea, you don't have to do it :)

Comment (TomasBoda) [reply suite-native/module-send/src/hooks/useSendForm.ts]: that's a good point. we can create an issue for it. but as the `getNetworkReserve` function is used non-trivially on other places in Suite as well, I think it's out of scope of this PR. let's discuss it for future refactoring

File: suite-native/module-send/src/hooks/useSendForm.ts (hunk 2 above)
Comment (TomasBoda) [reply suite-native/module-send/src/hooks/useSendForm.ts:73]: done

File: suite-native/module-send/src/hooks/useSendForm.ts (hunk 1 above)
Comment (TomasBoda) [reply suite-native/module-send/src/hooks/useSendForm.ts]: done

**Review by izmy — APPROVED** [review]

**Review by BrantalikP — APPROVED** [review]
