### PR TITLE
fix(suite): Fix TransactionGraph tooltip overflow

### LINKED ISSUE #17279: Tootlip in transaction history graph cutout
**Describe the bug**
Tootlip in transaction history graph cutout
**Steps to reproduce:**
1. Load wallet with history
2. Open account and hover over graph
3. Sometimes graph hover info is cutout /had to reduce window size to reproduce/

**Info:**
 - Suite version: desktop 25.3.0 (21292fda4b99364182a872b4eefbc9986a6da622)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/25.3.0 Chrome/132.0.6834.194 Electron/34.1.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T2B1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: BridgeTransport 3.0.0-bundled.25.3.0

**Screenshots:**

https://github.com/user-attachments/assets/d9a07af5-9582-4d3c-bd50-c54f5e71c2bf

### PR DESCRIPTION
**Pull request by jvaclavik**
## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17279

## Screenshots:

before

Screenshot 2025-03-12 at 19 14 36

after

Screenshot 2025-03-12 at 19 14 25

### CODE REVIEW

File: packages/components/src/components/Card/Card.tsx [hunk 1]
```diff
@@ -79,8 +82,6 @@ const CardContainer = styled.div<CardContainerProps>`
     ${({ theme, $variant }) =>
         $variant &&
         css`
-            overflow: hidden;
```
Comment (jvaclavik) [inline packages/components/src/components/Card/Card.tsx:82]: looks like there was a duplicity

File: packages/components/src/components/Card/Card.tsx [hunk 2]
```diff
@@ -63,13 +65,14 @@ type CardContainerProps = {
...
     $variant?: CardVariant;
     $hasLabel: boolean;
+    $overflow: TransientAllowedFrameProps['$overflow'];
 };
 
 const CardContainer = styled.div<CardContainerProps>`
     position: relative;
     border-radius: ${borders.radii.md};
     cursor: ${({ $isClickable }) => ($isClickable ? 'pointer' : 'default')};
-    overflow: hidden;
```
Comment (jvaclavik) [inline packages/components/src/components/Card/Card.tsx:72]: actually I think it couldn't work before

Comment (vojtatranta) [reply packages/components/src/components/Card/Card.tsx:72]: Well, for card container `overflow:hidden` make sense glboaly.. I'd say that graph card should be an exception with `overflow: visible`.

So, I'd think about ti before we change it globally.

**Review by vojtatranta — APPROVED** [review]
I'd think about this comment and if boss concludes it's okay, merge it: https://github.com/trezor/trezor-suite/pull/17623#discussion_r1993086914

File: packages/components/src/components/Card/Card.tsx (hunk 2 above)
Comment (jvaclavik) [reply packages/components/src/components/Card/Card.tsx:72]: Yes, I agree with you. And it should be like that after my changes. If you don't fill `overflow` prop component will use `overflow: hidden`, but at least now it's possible to change it.

Comment (vojtatranta) [reply packages/components/src/components/Card/Card.tsx:72]: magnifique

**Comment by bosomt** [comment]
**QA OK**


https://github.com/user-attachments/assets/d2336083-56ff-4463-8085-ad327712bc2a

**Info:**
 - Suite version: web 25.4.0 (8e4903e2baf236fe0d5c55028ee338d69bb4310e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: WebUsbTransport
