### PR TITLE
coins.json - eth stop using eth records, decode them from defs instead

### LINKED ISSUE #7415: trezor-common - ethereum testnet (tGOR) record outdated
ethereum testnet is not up-to-date in trezor-common. When we regenerate coins.json, we get some outdated results which break suite.

### LINKED ISSUE #8213: Ropsten network name with signing a Goerli TX
**Describe the bug**
Connect shows Ropsten network name when signing a TX on the Goerli network

**Info:**
Connect v9

**How to reproduce**
Sign a TX on Goerli

**Expected behavior**
Show Goerli network name

**Screenshots**

Screenshot 2023-04-21 at 13 58 33

### LINKED ISSUE #8440: connect - ethereumSignTx legacy (2.2.0) tests
Failing test: https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/4272273088#L3033

because of this https://github.com/trezor/trezor-suite/blob/develop/packages/connect-common/files/coins.json#L2236
now all other eth chains are treated as goerli chain. since eth definitions are not going to be maintained anymore in firmware repo, my suggestion is to alter coinInfo.ts is as follows:

```

// todo: this should stop using coins.json, remain sync, and return only ethereum mainnet, or ethereum testnet
export const getEthereumNetwork = (pathOrName: number[] | string) => {
    const networks = cloneCoinInfo(ethereumNetworks);
    if (typeof pathOrName === 'string') {
        const name = pathOrName.toLowerCase();
        return networks.find(
            n => n.name.toLowerCase() === name || n.shortcut.toLowerCase() === name,
        );
    }
    const slip44 = fromHardened(pathOrName[1]);
    return networks.find(n => n.slip44 === slip44);
};

// this should be called in case getEthereumNetwork is not enough
// returned data is protobuf and can be decoded.
export const getEthereumNetworkDefinition = (path: string, chain_id:number) => {

}

```

rough idea is that whenever slip44 is 1, the network will be treated as generic ethereum testned. and only in case we successfully decode definition dowloaded by chain_id, we display also more specific network info.

decoding was kicked off by @tomasklim here https://github.com/trezor/trezor-suite/tree/feat/eth-definitions

after this is done it should be possible to remove these legacy fixtures https://github.com/trezor/trezor-suite/blob/develop/packages/connect/e2e/__fixtures__/ethereumSignTransactionEip155.ts#L23

this is related with https://github.com/trezor/trezor-suite/issues/8213

### PR DESCRIPTION
**Pull request by mroz22**
Since ethereum networks in coins.json in trezor-firmware repo are no longer actively maintained we need to get rid of them here too. We already use something called ethereum definitions, which is binary data we download based on path or chain_id and pass them to device for ethereum calls. These definitions are basically protobuf encoded json containing similar data to records in coins.json which means that we may decoded them and use them instead of coins.json.

### Commits

- 36c27dad1b9f7f2d2c4c00c76c0f11f270bd552c, 0d4d028ce53e8a7030f11903f776e65013ab7ca3: so far we worked with protobufs only in one place - transport. this is no longer the only case. Now there are also protobuf encoded ethereum networks and token definition that were already used before this PR but only in a very simple way, they were downloaded and blindly passed into the device. Now we would like to read them too on connect level and it does not make sense to present this API as part of @trezor/transport package. So this commits separates protobuf related logic to a new package `@trezor/protobuf` in order to make it available to other parts of code without needing to import entire transport package. It also introduces another package called `@trezor/protocol` which basically contains various recepis how to read and/or write binary messages within trezor ecosystem. At this moment there are only 2 protocols but we are already designing a new one for host-device communication so I believe this will be the place where it goes.
- 428fad8bcd9ea8ea357d542de006bf332fee4d5e: at the very begging of connect method execution, we might need to do some async operation, in this case loading ethereum definitions. I suggest keeping method.init sync for tasks such params validation, and only use initAsync method  (executed after init method) where it is needed. Other option would be to change method.init to async, I have no strong preference here.
- 7b68c3b5ce81cd28205f9708200a254d3504c7aa: in some places `method.info` is being set couple of times. since this  Since this information is only some representation of method state (typically derived from its params) and we are always able to tell some default I suggest chaging it to a getter.
- 4322eaec831e820795027d8fbca29a46e93dd767 as we can see, ethereum definitions are no longer available in newly regenerated coins.json. I suggest creating coins-eth.json where we can keep definitions for coins we are absolutely sure they are available in trezor devices. For others, from now on, we rely on data we were able to fetch a decode in method.initAsync
- 709b96d17291ce19acb035e45bd9713cea4a1e39 - unrelated addition to trezor-connect-explorer (safety checks)
- c0da29a26dfeaae89edbebc4dbb69e3cf25eacaf, a75c6319ced78d88c96c455d61ce2c20478fa9ad, 18d806af582555b04aaa7ab46a02a7d1a2595f64 - addition to trezor-connect-explorer. get address and  sign transaction with uknowns and knowns. also covered by test.
- b0c099c6b49e3da8179d7f7cc97ffcaaee146b37, 6cc17862b0668ae80a36ce93baf46dbde1539a06 -  removing never used fields from coins.json (rskip60, chain)
- 5a13ab2179cdc79816670ff02c9084a5a9f600b1 - actual implementation of decoded ethereum definitions for ethereum methods.
- 4f3a7c2d8dd934bf740cfeaf16911d152fa22387 - removing some legacy results, now all tests should be passing without them

### Consider:

- [definitions built ins](https://github.com/trezor/trezor-common/blob/master/defs/ethereum/networks.json)
- [only eth guaranteed to be there always](https://satoshilabs.slack.com/archives/CL1D61PQF/p1686036769738889?thread_ts=1686033010.980389&cid=CL1D61PQF)
- changes to definitions format are possible as too https://satoshilabs.slack.com/archives/C02V2PSDNA2/p1686653391953739?thread_ts=1686652487.573219&cid=C02V2PSDNA2

### Testing examples:
- ethereumGetAddress "m/44'/163'/0'/0/0" (Ellaism, not part of coins-eth.json)

### Issues:

- resolve #8440
- resolve #8213
- resolve #7415

### CODE REVIEW

File: packages/connect/src/api/ethereumGetAddress.ts [hunk 1]
```diff
@@ -57,26 +61,50 @@ export default class EthereumGetAddress extends AbstractMethod<'ethereumGetAddre
...
+        this.useUi = !useEventListener;
+    }
+
+    async initAsync(): Promise<void> {
+        for (let i = 0; i < this.params.length; i++) {
+            if (this.params[i].network) {
+                // network was already set from 'well-known' definition in init method.
+                continue;
+            }
+            const slip44 = getSlip44ByPath(this.params[0].address_n);
```
Comment (karliatto) [inline packages/connect/src/api/ethereumGetAddress.ts]: Is `this.params[0]` a mistake and you really wanted to get `this.params[i]`?

File: packages/connect/src/api/ethereumGetAddress.ts [hunk 2]
```diff
@@ -57,26 +61,50 @@ export default class EthereumGetAddress extends AbstractMethod<'ethereumGetAddre
...
+            const decoded = decodeEthereumDefinition(definitions);
+
+            if (decoded.network) {
+                this.params[i].network = ethereumNetworkInfoFromDefinition(decoded.network);
+            }
+            if (definitions.encoded_network) {
+                this.params[i].encoded_network = definitions.encoded_network;
+            }
+        }
+    }
```
Comment (karliatto) [inline packages/connect/src/api/ethereumGetAddress.ts]: It might make it more readable creating a variable for this.params[i] at the beginning like:

```suggestion
    async initAsync(): Promise<void> {
        for (let i = 0; i < this.params.length; i++) {
            const param = this.params[i];
            if (param.network) {
                // network was already set from 'well-known' definition in init method.
                continue;
            }
            const slip44 = getSlip44ByPath(this.params[0].address_n); // Maybe also here `param`, but I am not sure if it was intended.

            const definitions = await getEthereumDefinitions({
                slip44,
            });

            const decoded = decodeEthereumDefinition(definitions);

            if (decoded.network) {
                param.network = ethereumNetworkInfoFromDefinition(decoded.network);
            }
            if (definitions.encoded_network) {
                param.encoded_network = definitions.encoded_network;
            }
        }
    }
```

File: packages/connect/src/api/ethereumGetAddress.ts [hunk 3]
```diff
@@ -57,26 +61,50 @@ export default class EthereumGetAddress extends AbstractMethod<'ethereumGetAddre
...
+
+    get info() {
         if (this.params.length === 1) {
-            this.info = getNetworkLabel('Export #NETWORK address', this.params[0].network);
+            return getNetworkLabel('Export #NETWORK address', this.params[0].network);
```
Comment (karliatto) [inline packages/connect/src/api/ethereumGetAddress.ts:96]: Nit: Adding a `return` here makes the `} else {` bellow unnecessary.

File: packages/connect/src/api/ethereumGetAddress.ts [hunk 4]
```diff
@@ -57,26 +61,50 @@ export default class EthereumGetAddress extends AbstractMethod<'ethereumGetAddre
...
         } else {
             const requestedNetworks = this.params.map(b => b.network);
             const uniqNetworks = getUniqueNetworks(requestedNetworks);
             if (uniqNetworks.length === 1 && uniqNetworks[0]) {
-                this.info = getNetworkLabel('Export multiple #NETWORK addresses', uniqNetworks[0]);
+                return getNetworkLabel('Export multiple #NETWORK addresses', uniqNetworks[0]);
```
Comment (karliatto) [inline packages/connect/src/api/ethereumGetAddress.ts]: Nit: Adding a `return` here makes the `} else {` bellow unnecessary.

File: packages/connect/src/api/ethereumGetPublicKey.ts [hunk 5]
```diff
@@ -45,20 +45,19 @@ export default class EthereumGetPublicKey extends AbstractMethod<'ethereumGetPub
                 network,
             };
         });
+    }
 
+    get info() {
         // set info
         if (this.params.length === 1) {
-            this.info = getNetworkLabel('Export #NETWORK public key', this.params[0].network);
+            return getNetworkLabel('Export #NETWORK public key', this.params[0].network);
```
Comment (karliatto) [inline packages/connect/src/api/ethereumGetPublicKey.ts:53]: Adding a `return` here makes the `} else {` bellow unnecessary.

File: packages/connect/src/api/ethereumSignTypedData.ts [hunk 6]
```diff
@@ -124,7 +132,7 @@ export default class EthereumSignTypedData extends AbstractMethod<'ethereumSignT
                     address_n,
                     domain_separator_hash: domain_separator_hash as string, // TODO: https://github.com/trezor/trezor-suite/issues/5297
                     message_hash,
-                    ...definitionParams,
+                    encoded_network: definitions?.encoded_network,
```
Comment (karliatto) [inline packages/connect/src/api/ethereumSignTypedData.ts:134]: What happens if `definitions?.encoded_network` is undefined and it goes to device? 

I remember the device could give some sort of error if the parameter was passed without value.

File: packages/connect/src/api/getAddress.ts [hunk 7]
```diff
@@ -93,17 +93,19 @@ export default class GetAddress extends AbstractMethod<'getAddress', Params[]> {
             this.params[0].show_display;
         this.confirmed = useEventListener;
         this.useUi = !useEventListener;
+    }
 
+    get info() {
         // set info
         if (this.params.length === 1) {
-            this.info = getLabel('Export #NETWORK address', this.params[0].coinInfo);
+            return getLabel('Export #NETWORK address', this.params[0].coinInfo);
```
Comment (karliatto) [inline packages/connect/src/api/getAddress.ts:101]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect/src/api/nemGetAddress.ts [hunk 8]
```diff
@@ -77,11 +79,11 @@ export default class NEMGetAddress extends AbstractMethod<'nemGetAddress', Param
                     break;
                 // no default
             }
-            this.info = `Export NEM address for account #${
+            return `Export NEM address for account #${
```
Comment (karliatto) [inline packages/connect/src/api/nemGetAddress.ts:82]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect/src/api/rippleGetAddress.ts [hunk 9]
```diff
@@ -59,17 +59,18 @@ export default class RippleGetAddress extends AbstractMethod<'rippleGetAddress',
             this.params[0].show_display;
         this.confirmed = useEventListener;
         this.useUi = !useEventListener;
+    }
 
+    get info() {
         // set info
         if (this.params.length === 1) {
-            this.info = `Export Ripple address for account #${
+            return `Export Ripple address for account #${
```
Comment (karliatto) [inline packages/connect/src/api/rippleGetAddress.ts:67]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect/src/api/signMessage.ts [hunk 10]
```diff
@@ -55,6 +53,17 @@ export default class SignMessage extends AbstractMethod<'signMessage', PROTO.Sig
...
+    get info() {
+        // FIXME!!!!
+        let coinInfo: BitcoinNetworkInfo | undefined;
+        if (this.payload.coin) {
+            coinInfo = getBitcoinNetwork(this.payload.coin);
+        } else {
+            coinInfo = getBitcoinNetwork(this.payload.path);
+        }
+        return getLabel('Sign #NETWORK message', coinInfo);
+    }
```
Comment (karliatto) [inline packages/connect/src/api/signMessage.ts]: If something has to be fix maybe providing information about what has to be fixed would be useful. Otherwise I would just remove it.

File: packages/connect/src/api/stellarGetAddress.ts [hunk 11]
```diff
@@ -59,14 +59,15 @@ export default class StellarGetAddress extends AbstractMethod<'stellarGetAddress
             this.params[0].show_display;
         this.confirmed = useEventListener;
         this.useUi = !useEventListener;
+    }
 
-        // set info
+    get info() {
         if (this.params.length === 1) {
-            this.info = `Export Stellar address for account #${
+            return `Export Stellar address for account #${
```
Comment (karliatto) [inline packages/connect/src/api/stellarGetAddress.ts:66]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect/src/api/tezosGetAddress.ts [hunk 12]
```diff
@@ -59,14 +59,15 @@ export default class TezosGetAddress extends AbstractMethod<'tezosGetAddress', P
             this.params[0].show_display;
         this.confirmed = useEventListener;
         this.useUi = !useEventListener;
+    }
 
-        // set info
+    get info() {
         if (this.params.length === 1) {
-            this.info = `Export Tezos address for account #${
+            return `Export Tezos address for account #${
```
Comment (karliatto) [inline packages/connect/src/api/tezosGetAddress.ts:66]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect/src/api/composeTransaction.ts [hunk 13]
```diff
@@ -119,9 +112,20 @@ export default class ComposeTransaction extends AbstractMethod<'composeTransacti
...
             push: typeof payload.push === 'boolean' ? payload.push : false,
+            total,
         };
     }
 
+    get info() {
+        const sendMax = this.params?.outputs.find(o => o.type === 'send-max') !== undefined;
+
+        if (sendMax) {
+            return 'Send maximum amount';
```
Comment (karliatto) [inline packages/connect/src/api/composeTransaction.ts:123]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect/src/api/cardanoGetAddress.ts [hunk 14]
```diff
@@ -75,14 +75,15 @@ export default class CardanoGetAddress extends AbstractMethod<'cardanoGetAddress
             this.params[0].show_display;
         this.confirmed = useEventListener;
         this.useUi = !useEventListener;
+    }
 
-        // set info
+    get info() {
         if (this.params.length === 1) {
-            this.info = `Export Cardano address for account #${
+            return `Export Cardano address for account #${
```
Comment (karliatto) [inline packages/connect/src/api/cardanoGetAddress.ts:82]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect/src/api/binanceGetAddress.ts [hunk 15]
```diff
@@ -55,14 +55,16 @@ export default class BinanceGetAddress extends AbstractMethod<'binanceGetAddress
             this.params[0].show_display;
         this.confirmed = useEventListener;
         this.useUi = !useEventListener;
+    }
 
+    get info() {
         // set info
         if (this.params.length === 1) {
-            this.info = `Export Binance address for account #${
+            return `Export Binance address for account #${
```
Comment (karliatto) [inline packages/connect/src/api/binanceGetAddress.ts:63]: Nit: Adding a return here makes the } else { bellow unnecessary.

File: packages/connect-common/files/coins-eth.json [hunk 16]
```diff
@@ -0,0 +1,20 @@
+[
```
Comment (karliatto) [inline packages/connect-common/files/coins-eth.json:1]: Ok, so if I understand well, now this file should contain all the eth definition that we want to bundle with suite. Otherwise for other eth token we download when initialized?

Do we plan to add more to this array or this is all that will be there?

File: scripts/update-submodules.sh [hunk 17]
```diff
@@ -8,7 +8,7 @@ cd ../submodules/trezor-common
 commit=$(git rev-parse --short HEAD)
 echo "$commit"
 git pull origin master
-cd ../
+cd ../../
```
Comment (karliatto) [inline scripts/update-submodules.sh]: Why to levels up? if we are in `scripts/update-submodules.sh` should be only one, no?

File: packages/protocol/package.json [hunk 18]
```diff
@@ -0,0 +1,24 @@
+{
+    "name": "@trezor/protocol",
```
Comment (karliatto) [inline packages/protocol/package.json:2]: Name `protocol` seams too generic. What about binary-protocol?

**Review by karliatto — COMMENTED** [review]
It works nicely. 
I added some nitpicks and questions.

File: packages/protocol/package.json (hunk 18 above)
Comment (mroz22) [reply packages/protocol/package.json:2]: dunno, there is already something called "trezor protocol" here https://github.com/trezor/trezor-firmware/blob/ef2d2a3e7587fe90ebf56454a8486207dada89c5/common/protob/protocol.md?plain=1#L4

File: packages/connect-common/files/coins-eth.json (hunk 16 above)
Comment (mroz22) [reply packages/connect-common/files/coins-eth.json:1]: depends on fw. eth is the only one guaranteed to be always built in. if we find a way how to sync ourselves with the other built-in definitions, we could update this file similary to how we update coins.json now.

File: packages/connect/src/api/binanceGetAddress.ts (hunk 15 above)
Comment (mroz22) [reply packages/connect/src/api/binanceGetAddress.ts:63]: yes. lint:js --fix was had the same opinion on this 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/cardanoGetAddress.ts (hunk 14 above)
Comment (mroz22) [reply packages/connect/src/api/cardanoGetAddress.ts:82]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/composeTransaction.ts (hunk 13 above)
Comment (mroz22) [reply packages/connect/src/api/composeTransaction.ts:123]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/ethereumGetAddress.ts (hunk 3 above)
Comment (mroz22) [reply packages/connect/src/api/ethereumGetAddress.ts:96]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/ethereumGetAddress.ts (hunk 4 above)
Comment (mroz22) [reply packages/connect/src/api/ethereumGetAddress.ts]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/ethereumGetPublicKey.ts (hunk 5 above)
Comment (mroz22) [reply packages/connect/src/api/ethereumGetPublicKey.ts:53]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/getAddress.ts (hunk 7 above)
Comment (mroz22) [reply packages/connect/src/api/getAddress.ts:101]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/nemGetAddress.ts (hunk 8 above)
Comment (mroz22) [reply packages/connect/src/api/nemGetAddress.ts:82]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/rippleGetAddress.ts (hunk 9 above)
Comment (mroz22) [reply packages/connect/src/api/rippleGetAddress.ts:67]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/signMessage.ts (hunk 10 above)
Comment (mroz22) [reply packages/connect/src/api/signMessage.ts]: haha, I forgot myself what it was but it sounds important 🤔

File: packages/connect/src/api/stellarGetAddress.ts (hunk 11 above)
Comment (mroz22) [reply packages/connect/src/api/stellarGetAddress.ts:66]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

File: packages/connect/src/api/tezosGetAddress.ts (hunk 12 above)
Comment (mroz22) [reply packages/connect/src/api/tezosGetAddress.ts:66]: 334ac559a8b27c41bca0e2b8766267f3c6b34e51

**Comment by mroz22** [comment]
@karliatto I reacted to couple of your comments  (but not all of them yet) and pushed fixups. May I squash fixups and rebase to resolve conflicts?

**Comment by karliatto** [comment]
> @karliatto I reacted to couple of your comments (but not all of them yet) and pushed fixups. May I squash fixups and rebase to resolve conflicts?

Yes please feel free to squash fixups and rebase.

File: packages/connect/src/api/ethereumGetAddress.ts (hunk 2 above)
Comment (mroz22) [reply packages/connect/src/api/ethereumGetAddress.ts]: well, maybe yes, bu I am assigning results to this.params[i] again in each iteration, which would make this on the other hand less readable I would say. One needs to keep track of references in his head

File: packages/connect/src/api/ethereumGetAddress.ts (hunk 1 above)
Comment (mroz22) [reply packages/connect/src/api/ethereumGetAddress.ts]: yes, that was probably a mistake. or at least, it did not work properly when I was testing exporting multiple addresses.

File: packages/connect/src/api/ethereumGetAddress.ts (hunk 2 above)
Comment (karliatto) [reply packages/connect/src/api/ethereumGetAddress.ts]: Fair enough :)

File: scripts/update-submodules.sh (hunk 17 above)
Comment (mroz22) [reply scripts/update-submodules.sh]: that was probably mistake. removed that.

File: packages/transport/src/utils/bridgeApiCall.ts [hunk 19]
```diff
@@ -4,6 +4,9 @@ import { success, error, unknownError } from './result';
 
 import * as ERRORS from '../errors';
 
+// import { PROTOCOL_MALFORMED  } from '@trezor/protocol';
+export const PROTOCOL_MALFORMED = 'Malformed protocol format' as const;
```
Comment (marekrjpolak) [inline packages/transport/src/utils/bridgeApiCall.ts]: Why this and not that?

File: packages/connect/src/api/signTransaction.ts [hunk 20]
```diff
@@ -137,6 +135,11 @@ export default class SignTransaction extends AbstractMethod<'signTransaction', P
         this.params.options = enhanceSignTx(this.params.options, coinInfo);
     }
 
+    get info() {
+        const coinInfo = getBitcoinNetwork(this.payload.coin);
```
Comment (marekrjpolak) [inline packages/connect/src/api/signTransaction.ts:139]: Here we're sure that `coinInfo` is present? Meaning, the original info message `'Sign transaction'` was unused?

File: packages/connect/src/api/signMessage.ts [hunk 21]
```diff
@@ -55,6 +53,17 @@ export default class SignMessage extends AbstractMethod<'signMessage', PROTO.Sig
...
     }
 
+    get info() {
+        // FIXME!!!!
+        let coinInfo: BitcoinNetworkInfo | undefined;
+        if (this.payload.coin) {
+            coinInfo = getBitcoinNetwork(this.payload.coin);
+        } else {
+            coinInfo = getBitcoinNetwork(this.payload.path);
+        }
```
Comment (marekrjpolak) [inline packages/connect/src/api/signMessage.ts]: Same as this? Also, are we sure that `validatePath(payload.path)` is now unnecessary?
```suggestion
        const coinInfo = getBitcoinNetwork(this.payload.coin ?? this.payload.path);
```

File: packages/connect-explorer/src/data/methods/ethereum/signTransaction.ts [hunk 22]
```diff
@@ -8,7 +8,7 @@ const tx = `{
     to: '0xd0d6d6c5fe4a677d343cc433536bb717bae167dd',
     chainId: 1,
     value: '0x0',
-    data: '0xa9059cbb000000000000000000000000574bbb36871ba6b78e27f4b4dcfb76ea0091880b000000000000000000000000000000000000000000000000000000000bebc200',
+    value: '1',
```
Comment (marekrjpolak) [inline packages/connect-explorer/src/data/methods/ethereum/signTransaction.ts:10]: Second `value` field and `data` missing?

File: packages/connect/src/api/ethereumSignTypedData.ts [hunk 23]
```diff
@@ -91,16 +94,26 @@ export default class EthereumSignTypedData extends AbstractMethod<'ethereumSignT
         }
     }
 
-    async run() {
-        const cmd = this.device.getCommands();
-        const { address_n } = this.params;
+    async initAsync() {
+        if (this.params.network) return;
```
Comment (marekrjpolak) [inline packages/connect/src/api/ethereumSignTypedData.ts:98]: Why this `network` condition and missing `chainId` from `getEthereumDefinitions`?

File: packages/connect/src/api/ethereumSignTransaction.ts [hunk 24]
```diff
@@ -44,7 +52,7 @@ export default class EthereumSignTransaction extends AbstractMethod<
         this.requiredPermissions = ['read', 'write'];
 
         const { payload } = this;
-
+        console.log('payload', payload);
```
Comment (marekrjpolak) [inline packages/connect/src/api/ethereumSignTransaction.ts]: Console leftover.

**Comment by marekrjpolak** [comment]
Apart from these questions, I'm not against merging synchronous `init` with asynchronous `initAsync`.

File: packages/connect/src/api/ethereumSignTransaction.ts (hunk 24 above)
Comment (mroz22) [reply packages/connect/src/api/ethereumSignTransaction.ts]: removed 57a36cdcc9b162760a6ae1a448ddd3f3132fa570

File: packages/connect/src/api/signMessage.ts (hunk 21 above)
Comment (mroz22) [reply packages/connect/src/api/signMessage.ts]: imho it doesn't matter now. the method would die on validation in init. also changed - not using `this.payload.path` but this `this.params.address_n` instead which is result from `validatePath(payload.path);`

File: packages/connect/src/api/signTransaction.ts (hunk 20 above)
Comment (mroz22) [reply packages/connect/src/api/signTransaction.ts:139]: yes, this getLabel utility does the job.

File: packages/transport/src/utils/bridgeApiCall.ts (hunk 19 above)
Comment (mroz22) [reply packages/transport/src/utils/bridgeApiCall.ts]: fixed 57a36cdcc9b162760a6ae1a448ddd3f3132fa570

**Review by marekrjpolak — APPROVED** [review]
