### PR TITLE
fix(suite): do not remove inactive devices in pairing mode

### LINKED ISSUE #22224: `Connect & unlock your Trezor` screen briefly flashes during Bluetooth pairing in onboarding
**Describe the bug**
During the onboarding process, when connecting via Bluetooth, the screen `Connect & unlock your Trezor` flashes briefly before continuing.

https://github.com/user-attachments/assets/76548ad9-802e-4f79-9428-4148d0efd028

### PR DESCRIPTION
**Pull request by OriginalEveres**
We do filter out inactive devices after 3s and 5s on Linux, however device in pairing mode does not send a `device-update` event, so we should not filter out devices in pairing mode...

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22224

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/device-in-parining-mode-does-not-update&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/device-in-parining-mode-does-not-update&lookback=7)

### CODE REVIEW

File: packages/suite/src/actions/bluetooth/filterOutNonResponsiveDevices.ts [hunk 1]
```diff
@@ -14,5 +14,7 @@ export const filterOutNonResponsiveDevices = <T extends BluetoothDeviceCommon>(d
         ? NEARBY_DEVICES_LAST_UPDATED_LIMIT_LINUX
         : NEARBY_DEVICES_LAST_UPDATED_LIMIT;
 
-    return devices.filter(d => d.lastUpdatedTimestamp >= now - limit);
+    return devices.filter(
+        d => d.lastUpdatedTimestamp >= now - limit || d.connectionStatus.type === 'pairing',
```
Comment (peter-sanderson) [inline packages/suite/src/actions/bluetooth/filterOutNonResponsiveDevices.ts]: nit: `d` => `device`

**Review by peter-sanderson — APPROVED** [review]

File: packages/suite/src/actions/bluetooth/filterOutNonResponsiveDevices.ts (hunk 1 above)
Comment (peter-sanderson) [reply packages/suite/src/actions/bluetooth/filterOutNonResponsiveDevices.ts]: jóoj: testik kdě? :eyes: :pray:

**Review by Lemonexe — APPROVED** [review]
LGTM, I mean, even if this is a bug in FW that will be fixed, the condition will do no harm except being incomprehensible.
As fix for freeze :shipit: , but you could add a comment
```
// as of FW 2.9.3, device in pairing mode does not send a device-update event
```
