### PR TITLE
fix(suite-native): confirm on trezor spring animation

### LINKED ISSUE #23747: There is a weird bounce on some animations when confirming on device
**Describe the bug**
When I am prompted to confirm on device some tasks, the app shows an animation with a bounce to it and it looks really weird and sometimes laggy and also, it might make the send flow broken sometimes. See attached video and screenshot.

**Info:**

- Mobile Suite Version: 25.12.1
- OS: Android

**How to reproduce**

1. Connect device
2. Navigate for example to "Receive address"
3. Check receive address on device but look at the app

**Screenshots**

https://github.com/user-attachments/assets/4f2beeba-3d21-44f1-9506-8bafd47abc73

Note: 
I can't scroll at this moment and I can barely click on the send button at the bottom.

Image

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- Fixes the crazy springy animation of ConfirmOnTrezor sheet.

## Related Issue

Resolve #23747 

## Screenshots:

https://github.com/user-attachments/assets/cc9e63b3-918b-4ace-b849-cf2b2001ba1b

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/confirm-on-trezor-spring-animation&lookback=7)

### CODE REVIEW

File: suite-native/device/src/components/ConfirmOnTrezor/hooks/useConfirmOnTrezorSheet.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ export const useConfirmOnTrezorSheet = ({ controlRef }: Props) => {
             'worklet';
             const targetY = snapPoints[index];
             translateY.value = withSpring(targetY, {
-                damping: 20,
+                damping: 50,
```
Comment (BrantalikP) [inline suite-native/device/src/components/ConfirmOnTrezor/hooks/useConfirmOnTrezorSheet.ts]: would not be cleaner solution to just use `withTiming` instead of withSpring? or do we still want the spring animation just not that strong?

Comment (PeKne) [reply suite-native/device/src/components/ConfirmOnTrezor/hooks/useConfirmOnTrezorSheet.ts]: ok, why not. I though that the spring is required by design team. I will change it and send a new demo.

Comment (BrantalikP) [reply suite-native/device/src/components/ConfirmOnTrezor/hooks/useConfirmOnTrezorSheet.ts]: nah, sorry. It's on me. I probably liked it somewhere and did not really think it through. Thanks for tackling this Peto!

**Review by BrantalikP — APPROVED** [review]
Thanks for addressing this!

**Comment by zako05** [comment]
QA OK ✅

https://github.com/user-attachments/assets/df0fc952-9b11-4baf-92b1-3573193d4524
