### PR TITLE
fix(suite-common): Make selectAddressByNetworkAndPath take device into account

### LINKED ISSUE #22288: Wrong address shown in confirmation screen during sign and verify in passphrase wallet
**Describe the bug**
During sign and verify in a passphrase wallet, the confirmation screen displays addresses from the standard wallet. The correct passphrase address is then shown on the Trezor device.

**Steps to reproduce:**
1.	Open the standard wallet
2.	Open the passphrase wallet
3.	Go to Sign and Verify (e.g., in Bitcoin account)
4.	Fill out the form, select an address, and confirm
5.	The following window displays a different address than the one selected

**Info:**
 - Suite version: web 25.10.0 (967e7dcc620b9e1950e860d11d125b328ddf144e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: Trezor T3T1 2.9.1 universal (revision acd56d0113a547e9b5983510b0ce9de079e30e05)
 - Transport: WebUsbTransport

**Video:**

https://github.com/user-attachments/assets/566e64aa-5b39-4af5-a979-285300579eab

### PR DESCRIPTION
**Pull request by 5K1PY**
`selectAdressByNetworkAndPath` does need to take device into acccount, as there can be multiple addresses with same network & path (from different devices).

## Related Issue

Resolve #22288

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/sign-wrong-address&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/sign-wrong-address&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/sign-wrong-address&lookback=7)

### CODE REVIEW

File: suite-common/wallet-core/src/accounts/accountsSelectors.ts [hunk 1]
```diff
@@ -296,14 +297,17 @@ export const selectSolAccountHasStaked = createMemoizedSelector([selectAccountBy
...
+        (_state: AccountsRootState, _device?: TrezorDevice, _network?: Network, path?: string) =>
+            path,
     ],
-    (accounts, network, path) => {
+    (accounts, device, network, path) => {
         if (!network || !path) return undefined;
 
         const networkAccounts = accounts.filter(a => a.symbol === network.symbol);
         for (const account of networkAccounts) {
+            if (device?.state?.staticSessionId !== account.deviceState) continue; // Account from another device
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/accounts/accountsSelectors.ts]: Looking at it I realized, that the only device that is passed to this selector is the selected device from `DeviceContextModal`.
Which means that here, you can `selectSelectedDevice` from state and don't have to pass it as a parameter, which makes the selector more complex.

And I can see that there is already a selector `selectDeviceAccounts`, so you can just easily replace `selectAccounts` with `selectDeviceAccounts` 🙂 

Also, 3 positional arguments (besides state) is really a lot.

File: suite-common/wallet-core/src/accounts/tests/accountsSelectors.test.ts [hunk 2]
```diff
@@ -8,11 +8,26 @@ import {
     selectVisibleDeviceAccountsMap,
 } from '../accountsSelectors';
 
+const BTC_DEVICE_SSID: `${string}@${string}:${number}` =
+    'mvbu1Gdy8SUjTenqerxUaZyYjmveZvt33q@AC94BB9C1B08FE73BE1E3322:0';
+const BTC_DEVICE: TrezorDevice = {
+    state: {
+        staticSessionId: BTC_DEVICE_SSID,
+    },
+} as any as TrezorDevice;
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/accounts/tests/accountsSelectors.test.ts]: This could be typed safer with as `Partial<TrezorDevice> as TrezorDevice` , but that's still not perfect - please avoid using partial fixtures, when we have a helper to create a full device object for tests (avoids all kinds of typecasting, makes it more maintainable). 
```
import { testMocks } from '@suite-common/test-utils';
const BTC_DEVICE = testMocks.getSuiteDevice({ state: { staticSessionId: BTC_DEVICE_SSID } })
```

**Review by Lemonexe — COMMENTED** [review]
Some comments below

File: suite-common/wallet-core/src/accounts/tests/accountsSelectors.test.ts [hunk 3]
```diff
@@ -106,22 +116,27 @@ const mockState: AccountsRootState & DeviceRootState = {
...
-                staticSessionId: 'mvbu1Gdy8SUjTenqerxUaZyYjmveZvt33q@AC94BB9C1B08FE73BE1E3322:0',
-            },
-        } as unknown as TrezorDevice,
+        devices: [BTC_DEVICE, ETH_DEVICE],
         persistentDeviceData: [],
         isDeviceAutoEjectEnabled: true,
     },
 };
 
+function withSelectedDevice(
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/accounts/tests/accountsSelectors.test.ts]: naming is not clear, please name `getStateWithSelectedDevice` 🙏

File: suite-common/wallet-core/src/accounts/tests/accountsSelectors.test.ts [hunk 4]
```diff
@@ -106,22 +116,27 @@ const mockState: AccountsRootState & DeviceRootState = {
...
+    state: AccountsRootState & DeviceRootState,
+    device: TrezorDevice,
+): AccountsRootState & DeviceRootState {
+    const modifiedState = cloneDeep(state);
+    modifiedState.device.selectedDevice = device;
+
+    return modifiedState;
```
Comment (Lemonexe) [inline suite-common/wallet-core/src/accounts/tests/accountsSelectors.test.ts]: This is fine I guess, I am a little worried about including `lodash` in runtime `dependencies`, it should definitely go to `devDependencies`.
But I think it is simpler to do a spread – and consistent with how we usually do it. So the whole function can be just this, without lodash:
```
const getStateWithSelectedDevice = (
    state: AccountsRootState & DeviceRootState,
    selectedDevice: TrezorDevice,
): AccountsRootState & DeviceRootState => ({
    ...state,
    device: { ...state.device, selectedDevice },
});
```
What do you think? 🙂

**Review by Lemonexe — APPROVED** [review]
LGTM, thanks for implementing my CR 🙂
