### PR TITLE
fix(native): CoinControl design tweaks, fixed utxo comparison

### LINKED ISSUE #20193: Coin control - confirming cc again after not changing anything disables coin control
**Describe the bug**
If I go to cc and select some utxos and confirm it and then go back to cc and just confirm it without changing anything, the coin control disables itself.

**Info:**

- Mobile Suite Version: 25.7.1 e68ee7e
- OS: name, version

**How to reproduce**

1. Connect device
2. Navigate to Send form
3. Select Coin control
4. Select any utxos and confirm
5. Go to Coin control again
6. Just confirm it
7. It is disasbled now

**Expected behavior**
Coin control stays enabled

**Screenshots**

### PR DESCRIPTION
**Pull request by OriginalEveres**
**Implemented design tweaks**:
- `Show details` button
- Separator margin
- Top half of the card is now clickable
- Datetime color updated

Fixed UTXO object comparison (that was introduced in https://github.com/trezor/trezor-suite/pull/20133)

## Related Issue

Resolves https://github.com/trezor/trezor-suite/issues/20193 https://github.com/trezor/trezor-suite/issues/20194

## Screenshots:
FEEDBACK
Screenshot 2025-07-15 at 9 46 21
AFTER
Screenshot 2025-07-15 at 9 52 27

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/coincontrol-design-tweaks&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/native/coincontrol-design-tweaks&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/native/coincontrol-design-tweaks&lookback=7)

### CODE REVIEW

File: suite-native/atoms/src/Button/TextButton.tsx [hunk 1]
```diff
@@ -36,14 +37,29 @@ const buttonContainerStyle = prepareNativeStyle(() => ({
...
+                condition: isUnderlined,
+                style: {
+                    textDecorationLine: 'underline',
+                },
             },
-        },
+            {
+                condition: isBold,
+                style: {
+                    fontWeight: '700',
```
Comment (juriczech) [inline suite-native/atoms/src/Button/TextButton.tsx]: Please add this fontWeight to `packages/theme/src/fontWeights.ts` and use the available utils parameter to access it.

File: suite-native/module-send/src/components/CoinControl/UtxoCard.tsx [hunk 2]
```diff
@@ -32,6 +33,10 @@ const AccountAddressFormatterStyle = prepareNativeStyle(() => ({
     maxWidth: '80%',
 }));
 
+const CardStyle = prepareNativeStyle(utils => ({
```
Comment (juriczech) [inline suite-native/module-send/src/components/CoinControl/UtxoCard.tsx]: nit: camelCase for consts please

```suggestion
const cardStyle = prepareNativeStyle(utils => ({
```

File: suite-native/module-send/src/components/CoinControl/UtxoCard.tsx [hunk 3]
```diff
@@ -75,57 +80,62 @@ export const UtxoCard = ({ utxo, onToggle, accountKey, symbol, isSelected = fals
...
-                                </>
-                            )}
-                        </HStack>
+        <Card
+            noPadding
+            borderColor={isSelected ? 'backgroundSecondaryDefault' : 'transparent'}
+            style={applyStyle(CardStyle)}
+        >
+            <VStack spacing="sp12">
+                <Pressable onPress={() => onToggle(utxo)}>
```
Comment (juriczech) [inline suite-native/module-send/src/components/CoinControl/UtxoCard.tsx]: Nit: Extract to handler, use in both places in this component please

File: suite-native/module-send/src/components/CoinControl/UtxoCard.tsx [hunk 4]
```diff
@@ -75,57 +80,62 @@ export const UtxoCard = ({ utxo, onToggle, accountKey, symbol, isSelected = fals
...
-                            style={applyStyle(AccountAddressFormatterStyle)}
-                            value={utxo.address}
-                            variant="hint"
-                            color="textSubdued"
-                        />
-                    </VStack>
-                    <CheckBox isChecked={isSelected} onChange={() => onToggle(utxo)} />
-                </HStack>
+                            <AccountAddressFormatter
+                                style={applyStyle(AccountAddressFormatterStyle)}
```
Comment (juriczech) [inline suite-native/module-send/src/components/CoinControl/UtxoCard.tsx]: nit
```suggestion
                                style={applyStyle(accountAddressFormatterStyle)}
```

File: suite-native/module-send/src/screens/SendUtxoScreen.tsx [hunk 5]
```diff
@@ -56,10 +56,20 @@ export const SendUtxoScreen = ({
         };
     }, [accountKey, dispatch]);
 
-    const handleUtxoSelect = (utxo: Utxo) =>
-        tempSelectedUtxos.includes(utxo)
-            ? setTempSelectedUtxos(tempSelectedUtxos.filter(txid => txid !== utxo))
-            : setTempSelectedUtxos([...tempSelectedUtxos, utxo]);
+    const handleUtxoSelect = (utxo: Utxo) => {
+        const exists = tempSelectedUtxos.some(
+            selected => selected.txid === utxo.txid && selected.vout === utxo.vout,
```
Comment (juriczech) [inline suite-native/module-send/src/screens/SendUtxoScreen.tsx]: I guess you could extract this comparison into some kind of helper function that would be named. It's used in 3 places across your PR and it creates duplication of code:
```
selected.txid === utxo.txid && selected.vout === utxo.vout
```

**Review by juriczech — COMMENTED** [review]
Just some small codebase specific nits. Feel free to reach out if you disagree with something and we don't have to worry about it too much if we're pressed on time with this.

File: suite-native/atoms/src/Button/TextButton.tsx (hunk 1 above)
Comment (OriginalEveres) [reply suite-native/atoms/src/Button/TextButton.tsx]: I have to research about this one, since in Figma we use fontWeight 600, but this weight does not work in TextButton, elsewhere does - thus 700 was more of one time TextButton only weight.

File: suite-native/module-send/src/screens/SendUtxoScreen.tsx (hunk 5 above)
Comment (OriginalEveres) [reply suite-native/module-send/src/screens/SendUtxoScreen.tsx]: I agree, it make sense now since its widely used

Comment (OriginalEveres) [reply suite-native/module-send/src/screens/SendUtxoScreen.tsx]: simplified in ca5db0358ff795b5d1c4a82eb75b727594276e58

File: suite-native/module-send/src/components/CoinControl/UtxoCard.tsx (hunk 4 above)
Comment (OriginalEveres) [reply suite-native/module-send/src/components/CoinControl/UtxoCard.tsx]: nit resolved in ca5db0358ff795b5d1c4a82eb75b727594276e58

File: suite-native/module-send/src/components/CoinControl/UtxoCard.tsx (hunk 3 above)
Comment (OriginalEveres) [reply suite-native/module-send/src/components/CoinControl/UtxoCard.tsx]: nit resolved in ca5db0358ff795b5d1c4a82eb75b727594276e58

File: suite-native/module-send/src/components/CoinControl/UtxoCard.tsx (hunk 2 above)
Comment (OriginalEveres) [reply suite-native/module-send/src/components/CoinControl/UtxoCard.tsx]: nit resolved in ca5db0358ff795b5d1c4a82eb75b727594276e58

File: suite-native/atoms/src/Button/TextButton.tsx (hunk 1 above)
Comment (OriginalEveres) [reply suite-native/atoms/src/Button/TextButton.tsx]: added a comment, we need to investigate and fix later on ca5db0358ff795b5d1c4a82eb75b727594276e58

Comment (juriczech) [reply suite-native/atoms/src/Button/TextButton.tsx]: I think this is because we don't have the correct font for this font weight. Please remove the comment. If we're fine going with font weight 700, let's go with it. 

I'm just not a big fan of leaving this kind of comment in code, because if you're not planning to fix this straight after merging this PR (in which case issue would be more appropriate), the comment will just rot there and will never be resolved. If 700 is fine with design team, let's go with this, add it to theming (since it's legit option) and we're good to go IMO

File: suite-native/module-send/src/components/CoinControl/UtxoCard.tsx [hunk 6]
```diff
@@ -74,58 +80,67 @@ export const UtxoCard = ({ utxo, onToggle, accountKey, symbol, isSelected = fals
...
-                                    <BaseCurrencyAmountFormatter
-                                        color="textSubdued"
-                                        variant="highlight"
-                                        symbol={symbol}
-                                        value={fiatAmount}
-                                    />
-                                </>
-                            )}
-                        </HStack>
+        <Card
```
Comment (juriczech) [inline suite-native/module-send/src/components/CoinControl/UtxoCard.tsx:88]: Please use `TouchableOpacity` so user gets some kind of feedback. You can get inspired by `CompactCardWithIconLayout` which does similar thing

Comment (OriginalEveres) [reply suite-native/module-send/src/components/CoinControl/UtxoCard.tsx:88]: 👌 makes sense. Added

File: suite-native/atoms/src/Button/TextButton.tsx (hunk 1 above)
Comment (OriginalEveres) [reply suite-native/atoms/src/Button/TextButton.tsx]: makes sense. I added the bold font weight to the theme. 

and I also have created issue for this topic https://github.com/trezor/trezor-suite/issues/20219

**Review by juriczech — APPROVED** [review]
