### PR TITLE
Trading - Redesign receive address in swap/buy form

### LINKED ISSUE #14838: Trading DEX - swap fee does not reflect reality
**Describe the bug**

It counts fees for "send" type transaction and not for transaction with swap data.

https://github.com/user-attachments/assets/f9004ca0-4773-4e64-860e-07de4ac31eee

### LINKED ISSUE #18060: Trading - Fee estimation from network failed. Using backup value.
**Describe the bug**  
When you try to trade many ERC20 tokens (e.g. EURT), you are constantly spammed by the notification:  
`Fee estimation from network failed. Using backup value.`

Since we now use sensible backups, the notification might not be necessary anymore.

**Info:**
 - Suite version: web 25.5.0 (e2c9eec19bb352d9e48e24061fcb5d6e675608f5)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.8.9 regular (revision fad9682201cf9289bba2adb66e6e07ed1cf78936)
 - Transport: BridgeTransport 3.0.0-bundled.25.4.1

**Screenshots:**

Image

**Note(s):**
https://satoshilabs.slack.com/archives/C04DD84P4A1/p1739451913097169

### LINKED ISSUE #20416: Trading - Extracting receive address outside of the trade flow [OVERVIEW]
Overview issue to track extracting receive address outside of the trade flow

**[Design](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4823-16200&t=KzQ8wJSwa7PvA6jl-4)**

### LINKED ISSUE #21596: Trading - New receive account picker in TRADE
Follow up on moving receive account selection to initial step of TRADE (#20416)
- The design in this previous shouldn't be seen by customers as it was done mainly to simplify the implementation.
- Please process this task in the same release cycle, so we don't turn our swap into super long form.

Please change how we display and select receive account according to [Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4823-16200&t=KzQ8wJSwa7PvA6jl-4).

Notes:
- The design aims to match the picker to mobile
- BTC and XLM/XRP have a bit different flow
- Don't forget about BUY

# Proposal

Image

Image

Image

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

Redesign the receive address selection in swap/buy form.

## Related Issue

Resolve #21596 
Resolve #14838
Resolve #18060
Resolve #20416

## Screenshots

When no receive asset is selected, receive account picker is hidden.

Screenshot 2025-10-01 at 09 49 47

`Base` is not activated, so the `Receive account` shows `Not selected` and the button on the right says `Continue` (clicking on the button opens the receive account picker).

Screenshot 2025-10-01 at 09 51 03

Clicking on the `Receive account` or the `Continue` button opens the receive account modal.

Screenshot 2025-10-01 at 09 51 11

When the user clicks on `Create new Base account` a modal is opened where the user can activate their `Base` accounts.

Screenshot 2025-10-01 at 09 51 18

While the `Base` accounts are being loaded, the `Trezor Discovery` banner is shown in the modal.

Screenshot 2025-10-01 at 09 51 34

A list of `Base` receive accounts are displayed in the modal.

Screenshot 2025-10-01 at 09 51 42

After selecting an existing `Base` account, it is applied and the modal is closed.

Screenshot 2025-10-01 at 09 52 06

After clicking on the `Use an account (Base) that isn't in Trezor Suite` button in the modal, a new modal with the receive address input field is opened.

Screenshot 2025-10-01 at 09 52 20

After inputting a valid receive address and clicking on `Confirm`, the address is selected, the modal is closed and now the receive address picker displays `Receive address` with the selected address.

Screenshot 2025-10-01 at 09 54 40

If the receive crypto is `XRP` (Ripple) or `XLM` (Stellar), clicking on a receive account opens a new modal with the option to specify memo or destination tag.

Screenshot 2025-10-01 at 09 55 22

Screenshot 2025-10-01 at 09 55 26

If the user chose to specify a receive address that isn't in Trezor Suite, the option to add the memo or destination tag is shown under the receive address input field.

Screenshot 2025-10-01 at 09 55 33

If the receive crypto is `UTXO` based (Bitcoin-like networks, Cardano, ...) and the user selects an existing receive account, a new modal with new and used receive addresses is opened.

Screenshot 2025-10-01 at 09 55 58

The user can search for a specific receive address and after clicking on it, the modal is closed and the receive address is applied.

Screenshot 2025-10-01 at 09 56 06

`Buy` trading section works the same way as the `Swap` trading section.

Screenshot 2025-10-01 at 09 56 30

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/receive-address-redesign&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/receive-address-redesign&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/receive-address-redesign&lookback=7)

### CODE REVIEW

File: packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts [hunk 1]
```diff
@@ -257,24 +317,78 @@ export class TradingPage {
...
+
+        await expect(this.receiveAccountModal).toBeVisible();
+        const addSuiteOptionsCount = await this.receiveAccountModalAddSuiteOption.count();
+        expect.soft(addSuiteOptionsCount).toEqual(1);
+        await this.receiveAccountModalAddSuiteOption.nth(0).click();
+
+        await expect(this.addAccountButton).toBeVisible();
+        await this.addAccountButton.click();
+
+        await discoveryCallback();
```
Comment (Vere-Grey) [inline packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts]: discoveryShouldFinish() is method on our page object that is available intencionally everywhere.
We could do 
```suggestion
    async selectAddSuiteReceiveAccount(index: number,) {
        await expect(this.receiveAddressPicker).toBeVisible();
        await this.receiveAddressPicker.click();

        await expect(this.receiveAccountModal).toBeVisible();
        const addSuiteOptionsCount = await this.receiveAccountModalAddSuiteOption.count();
        expect.soft(addSuiteOptionsCount).toEqual(1);
        await this.receiveAccountModalAddSuiteOption.nth(0).click();

        await expect(this.addAccountButton).toBeVisible();
        await this.addAccountButton.click();
        await this.page.discoveryShouldFinish() 
```
and get rid of passing the discovery method thru params. Unless there is a purpose for that.

File: packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts [hunk 2]
```diff
@@ -257,24 +317,78 @@ export class TradingPage {
         await this.paymentMethodOption(method).click();
     }
 
+    @step()
+    async selectSuiteReceiveAccount(index: number) {
+        await expect(this.receiveAddressPicker).toBeVisible();
+        await this.receiveAddressPicker.click();
```
Comment (Vere-Grey) [inline packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts]: Playwright is super helpful and does a lot of asserts and checks for us implicitly on specific actions.
For example for click. It checks that element is visible, stable, can recieve events and is enabled.
Ergo we can save some code lines and dont do that duplicatly.
Here is [table describing all auto-waits and asserts](https://playwright.dev/docs/actionability).

**Review by tomasklim — COMMENTED** [review]
.

File: suite-common/trading/src/reducers/tradingReducer.ts [hunk 3]
```diff
@@ -172,6 +172,7 @@ export const tradingSlice = createSliceWithExtraDeps({
                 state.buy.amountLimits = undefined;
                 state.buy.quotes = [];
                 state.buy.quotesRequest = undefined;
+                //state.buy.isLoading = false;
```
Comment (tomasklim) [inline suite-common/trading/src/reducers/tradingReducer.ts]: remove

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+};
+
+const ReceiveAddressModalControlsContext = createContext<
+    ReceiveAddressModalControlsContextType | undefined
+>(undefined);
+
+export const ReceiveAddressModalControlsProvider = ({ children }: { children: ReactNode }) => {
+    const [isAccountModalOpen, setIsAccountModalOpen] = useState(false);
+    const [isAddressModalOpen, setIsAddressModalOpen] = useState(false);
+    const [isBitcoinModalOpen, setIsBitcoinModalOpen] = useState(false);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: isUtxoBasedNetwork

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+    extraFieldModal: ModalControlType;
+};
+
+const ReceiveAddressModalControlsContext = createContext<
+    ReceiveAddressModalControlsContextType | undefined
+>(undefined);
+
+export const ReceiveAddressModalControlsProvider = ({ children }: { children: ReactNode }) => {
+    const [isAccountModalOpen, setIsAccountModalOpen] = useState(false);
+    const [isAddressModalOpen, setIsAddressModalOpen] = useState(false);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: better name

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+    bitcoinAddressModal: ModalControlType;
+    extraFieldModal: ModalControlType;
+};
+
+const ReceiveAddressModalControlsContext = createContext<
+    ReceiveAddressModalControlsContextType | undefined
+>(undefined);
+
+export const ReceiveAddressModalControlsProvider = ({ children }: { children: ReactNode }) => {
+    const [isAccountModalOpen, setIsAccountModalOpen] = useState(false);
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: isAccountBasedNetworkModalOpen

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx [hunk 7]
```diff
@@ -0,0 +1,164 @@
...
+        ? cryptoIdToPlatformName(networkId)
+        : cryptoIdToCoinName(networkId);
+
+    const { selectedAccountOption, selectAccountOptions } = tradingReceiveAddress;
+
+    const form = useForm<TradingVerifyFormProps>({
+        mode: 'onChange',
+    });
+
+    const requiresExtraField =
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx]: check using quote

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+                                <>
+                                    <AccountLabeling
+                                        data-test-id="@trading/selected-receive-account"
+                                        account={selectedAccountOption.account}
+                                        accountTypeBadgeSize="small"
+                                        showAccountTypeBadge
+                                    />
+                                    <Text typographyStyle="hint" variant="tertiary">
+                                        {getTrimmedReceiveAddress(receiveAddress)}
+                                    </Text>
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx:90]: `TokenAddressRow` (remade)

**Review by tomasklim — DISMISSED** [review]
- TokenAddressRow -> AddressRow
  - no copy
- EVM acc to same EVM acc
- From to same acc on change
- Example in receive address fix
- clean unused address on utxo based networks
- align approval on small window
- gas limit is not calcualted for dex tx
- utxo also for cardano

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx:1]: Would it make sense to split this file into multiple ones?

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal.tsx [hunk 9]
```diff
@@ -0,0 +1,318 @@
...
+        amount: account.formattedBalance,
+        symbol: account.symbol,
+    });
+
+    const formattedAmount = BaseCurrencyAmountFormatter({
+        value: fiatAmount ?? BASE_CURRENCY_ZERO,
+        currency: baseCurrency,
+    });
+
+    const formattedFiatAmount = formattedAmount?.props.children;
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal.tsx]: Isn't there a better way to get this value? This seems a bit fragile and also is of type `any`

**Review by matusbalascak — COMMENTED** [review]
Just some nitpicks, otherwise LGTM ✅

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal.tsx (hunk 9 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal.tsx]: done: used the formatter directly in the `JSX`

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx:1]: done: split into multiple files

File: suite-common/trading/src/reducers/tradingReducer.ts (hunk 3 above)
Comment (TomasBoda) [reply suite-common/trading/src/reducers/tradingReducer.ts]: done

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx (hunk 4 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: done

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx (hunk 5 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: done

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx (hunk 6 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: done

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx (hunk 7 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx]: done

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 8 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx:90]: done

File: packages/suite/src/components/suite/copy/AddressRow.tsx [hunk 10]
```diff
@@ -70,33 +72,35 @@ const IconWithNoPointer = styled(Icon)`
...
 
     const copy = (event: MouseEvent) => {
         setIsClicked(true);
         event.stopPropagation();
-        onCopy();
+        onCopy?.();
     };
 
-    const shortenedTokenAddress = `${tokenContractAddress.slice(0, 6)}...${tokenContractAddress.slice(-4)}`;
+    const shortenedTokenAddress = `${address.slice(0, showStart)}...${address.slice(address.length - showEnd, address.length)}`;
```
Comment (cermakjiri) [inline packages/suite/src/components/suite/copy/AddressRow.tsx:96]: 👍

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInputs.tsx [hunk 11]
```diff
@@ -305,65 +301,77 @@ export const TradingFormInputs = () => {
...
+            <Card>
+                <Column gap={spacings.lg}>
+                    <TradingFormInputPaymentMethod label="TR_TRADING_PAYMENT_METHOD" />
+                    <TradingFormInputCountry label="TR_TRADING_COUNTRY" />
+                    <TradingFormFeesDisclamer />
+                </Column>
+            </Card>
+        </Column>
     );
 };
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInputs.tsx:28]: This component is super long and it's basically three-in-one. Wouldn't be better to decompose it to:
- `TradingFormInputs/BuyFormInputs`
- `TradingFormInputs/SellFormInputs`
- `TradingFormInputs/ExchangeFormInputs`
and in the original one just leave this:
```tsx
export const TradingFormInputs = () => {
    const context  = useTradingFormContext();

  if (isTradingSellContext(context)) {
    return <ExchangeFormInputs />
 }

if (isTradingSellContext(context) {
     return <SellFormInputs />
 }

if (isTradingBuyContext(context) {
     return  <BuyFormInputs/>
}

return null
```
? (or just using `switch(type) { ... }` in case of passing no props, therefore using these type guard fns is redundant)
This would make much more easier to read. And I know the `TradingFormInputs` has been complex even before this PR.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountSuiteOption.tsx [hunk 12]
```diff
@@ -0,0 +1,117 @@
...
+
+    const { fiatAmount } = useFiatFromCryptoValue({
+        amount: account.formattedBalance,
+        symbol: account.symbol,
+    });
+
+    const network = cryptoIdToNetwork(cryptoId);
+
+    const isUtxoBasedNetwork =
+        network?.networkType === 'bitcoin' || network?.networkType === 'cardano';
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountSuiteOption.tsx]: there's util for that `isUtxoBased`

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx [hunk 13]
```diff
@@ -0,0 +1,234 @@
...
+        amount: balanceInUnits,
+        symbol: account.symbol,
+    });
+
+    const formattedAmount = BaseCurrencyAmountFormatter({
+        value: fiatAmount ?? BASE_CURRENCY_ZERO,
+        currency: baseCurrency,
+    });
+
+    const formattedFiatAmount = formattedAmount?.props.children;
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx]: isn't there just plain util fn when there's no need for React component?

Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx]: or why not just render it like `<BaseCurrencyAmountFormatter value={...} currency={...} />` down below?

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx [hunk 14]
```diff
@@ -0,0 +1,234 @@
...
+                            account={account}
+                            addresses={usedAddresses}
+                            title={<Translation id="TR_TRADING_RECEIVE_ADDRESS_USED_ADDRESSES" />}
+                        />
+                    </>
+                )}
+            </Column>
+        </Modal>
+    );
+};
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx]: I know it's not usual practice in this codebase however wouldn't make more sense to put each component per one file so that:
- it's  easily understandable what's purpose / content of given component
- the number of lines in a file is being kept at some "normal" level
- components can been move upstream if there will become general one (required on multiple places in codebase) or otherwise refactored
and place them in tree-like folder structure so it's easily understandable what's relates to what? E.g.:

```
TradingUtxoReceiveAddressModal/TradingUtxoReceiveAddressModal.tsx
TradingUtxoReceiveAddressModal/TradingUtxoReceiveAddressList/TradingUtxoReceiveAddressList.tsx
TradingUtxoReceiveAddressModal/TradingUtxoReceiveAddressList/TradingUtxoReceiveAddressOption/TradingUtxoReceiveAddressOption.tsx
```
?

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx [hunk 15]
```diff
@@ -0,0 +1,79 @@
...
+        </ReceiveAddressModalControlsContext.Provider>
+    );
+};
+
+export const useReceiveAddressModalControls = () => {
+    const context = useContext(ReceiveAddressModalControlsContext);
+
+    if (!context) {
+        throw new Error(
+            'useReceiveAddressModalControls must be used within a ReceiveAddressModalControlsProvider',
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx:57]: 👍

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx [hunk 16]
```diff
@@ -0,0 +1,79 @@
...
+        utxoAddressModal: {
+            isOpen: isUtxoBasedNetworkModalOpen,
+            open: () => setIsUtxoBasedNetworkModalOpen(true),
+            close: () => setIsUtxoBasedNetworkModalOpen(false),
+        },
+        extraFieldModal: {
+            isOpen: isExtraFieldModalOpen,
+            open: () => setIsExtraFieldModalOpen(true),
+            close: () => setIsExtraFieldModalOpen(false),
+        },
```
Comment (cermakjiri) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: Or there could be a single `useState`:

```ts
type ReceiveAddressModal = 'accountModal' | 'customAddressModal' | 'utxoAddressModal' | 'extraFieldModal'

function useReceiveAddressModals() {
   const [activeModal, setActiveModal] = useState<ReceiveAddressModal | null>(null)

   return {
       activeModal,
       openModal(id: ReceiveAddressModal) {
           setActiveModal(id)
       },
      closeModal() {
           setActiveModal(null)
       }
   },
}

```tsx
function ReceiveAddressModalControlsProvider() {
     const { activeModal, openModal, closeModal } = useReceiveAddressModals()

return    <ReceiveAddressModalControlsContext.Provider>
 {children}
{activeModal === 'accountModal' && <TradingReceiveAccountModal />}
</ReceiveAddressModalControlsContext.Provider>
  {...}
    </ReceiveAddressModalControlsContext.Provider>
}
```
Alternatively, `useState` with `Set<ReceiveAddressModal>` in case of multiple modals can be opened.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx [hunk 17]
```diff
@@ -0,0 +1,163 @@
...
+            return context.cexQuotes?.[0];
+        }
+
+        return quotes?.[0];
+    };
+
+    const quote = getQuote();
+    const extraFieldDescription = isTradingExchangeContext(context)
+        ? (quote as ExchangeTrade)?.extraFieldDescription
+        : undefined;
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]:
```suggestion
    const extraFieldDescription = isExchangeTrade(quote)
        ? quote.extraFieldDescription
        : undefined;
```

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx [hunk 18]
```diff
@@ -0,0 +1,163 @@
...
+    }
+
+    return { cryptoId, tradingReceiveAddress, quote, extraFieldDescription, isLoading };
+};
+
+export const getTrimmedReceiveAddress = (receiveAddress?: string) => {
+    if (!receiveAddress) return undefined;
+
+    return receiveAddress.substring(0, 14) + '...';
+};
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: I don't see this being used anywhere

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx [hunk 19]
```diff
@@ -0,0 +1,163 @@
...
+    const modalControls = useReceiveAddressModalControls();
+
+    const { receiveAddress, selectedAccountOption } = tradingReceiveAddress;
+
+    const onReceiveAccountClick = () => {
+        modalControls.accountModal.open();
+    };
+
+    return (
+        <>
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: No need for fragments here, you're returning just one child

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx [hunk 20]
```diff
@@ -0,0 +1,163 @@
...
+                    justifyContent="space-between"
+                    onClick={onReceiveAccountClick}
+                    padding={{ vertical: spacings.sm, horizontal: spacings.lg }}
+                >
+                    <Text typographyStyle="body">
+                        {selectedAccountOption?.account || !receiveAddress ? (
+                            <Translation id="TR_BUY_RECEIVING_ACCOUNT" />
+                        ) : (
+                            <Translation id="TR_BUY_RECEIVING_ADDRESS" />
+                        )}
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]:
```suggestion
                   <Translation
                        id={
                            selectedAccountOption?.account || !receiveAddress
                                ? 'TR_BUY_RECEIVING_ACCOUNT'
                                : 'TR_BUY_RECEIVING_ADDRESS'
                        }
                    />

```

ultimate nitpick :D

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx [hunk 21]
```diff
@@ -0,0 +1,79 @@
...
+                {!hasSuiteAccounts && !isDiscoveryRunning && (
+                    <TradingReceiveAddressEmpty
+                        title={<Translation id="TR_TRADING_RECEIVE_ACCOUNT_NOT_FOUND_TITLE" />}
+                        text={<Translation id="TR_TRADING_RECEIVE_ACCOUNT_NOT_FOUND_TEXT" />}
+                    />
+                )}
+
+                <Card paddingType="none">
+                    {selectAccountOptions.map((option, index) => (
+                        <>
```
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx]: It would be nice to use React.Fragment with key.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx [hunk 22]
```diff
@@ -0,0 +1,79 @@
...
+                {isDiscoveryRunning && <DiscoveryWarning />}
+
+                {!hasSuiteAccounts && !isDiscoveryRunning && (
+                    <TradingReceiveAddressEmpty
+                        title={<Translation id="TR_TRADING_RECEIVE_ACCOUNT_NOT_FOUND_TITLE" />}
+                        text={<Translation id="TR_TRADING_RECEIVE_ACCOUNT_NOT_FOUND_TEXT" />}
+                    />
+                )}
+
+                <Card paddingType="none">
```
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx]: Don't render `Card` if `selectAccountOptions` is empty.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx [hunk 23]
```diff
@@ -0,0 +1,163 @@
...
+        : undefined;
+
+    if (!cryptoId) {
+        throw new Error('cryptoId must be defined');
+    }
+
+    return { cryptoId, tradingReceiveAddress, quote, extraFieldDescription, isLoading };
+};
+
+export const getTrimmedReceiveAddress = (receiveAddress?: string) => {
```
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: I don't see you using this function anywhere.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx [hunk 24]
```diff
@@ -0,0 +1,163 @@
...
+export const TradingReceiveAddressEmpty = ({ title, text }: TradingReceiveAddressEmptyProps) => (
+    <Column alignItems="center" gap={spacings.xxs} padding={{ vertical: spacings.md }}>
+        <Text typographyStyle="body">{title}</Text>
+        <Text typographyStyle="hint" variant="tertiary">
+            {text}
+        </Text>
+    </Column>
+);
+
+export const useTradingReceiveAddressValues = () => {
```
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: Maybe it would be better to take out the custom hook into its own file, wdyt?

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 19 above)
Comment (izmy) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: unnecessary fragment

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx [hunk 25]
```diff
@@ -0,0 +1,171 @@
...
+                    valid = isHexValid(value);
+                } else if (extraFieldDescription?.type === 'number') {
+                    valid = isInteger(value);
+                }
+            }
+            if (!valid) {
+                return translationString('TR_EXCHANGE_EXTRA_FIELD_INVALID', {
+                    extraFieldName: extraFieldDescription?.name,
+                });
+            }
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx:71]:
```suggestion
            const { type, name: extraFieldName } = extraFieldDescription ?? {};
            const validators = {
                hex: isHexValid,
                number: isInteger,
                text: () => true,
            };

            const valid = type ? validators[type](value) : true;

            if (!valid) {
                return translationString('TR_EXCHANGE_EXTRA_FIELD_INVALID', {
                    extraFieldName,
                });
            }

```

Just something for consideration, no need to update it. I just like to omit using `let` variables when not necessary.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx [hunk 26]
```diff
@@ -0,0 +1,171 @@
...
+
+    const onBackClick = () => {
+        onCancel();
+        modalControls.accountModal.open();
+    };
+
+    const onConfirmClick = () => {
+        const nonSuiteOption = selectAccountOptions.find(option => option.type === 'NON_SUITE');
+        if (!nonSuiteOption) return;
+        if (form.formState.errors.address || form.formState.errors.extraField) return;
```
Comment (matusbalascak) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx]: You can move this condition above the `nonSuiteOption` declaration to not run `find` unnecessarily

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInputs.tsx (hunk 11 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInputs.tsx:28]: done 276bf9d7b43a1cc580be264df1883a7195ca8d8c: split into three separate files

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountSuiteOption.tsx (hunk 12 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountSuiteOption.tsx]: done 276bf9d7b43a1cc580be264df1883a7195ca8d8c

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx (hunk 13 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx]: done 276bf9d7b43a1cc580be264df1883a7195ca8d8c

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx (hunk 14 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx]: done 276bf9d7b43a1cc580be264df1883a7195ca8d8c: created separate files for all components

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx (hunk 16 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/useReceiveAddressModalControls.tsx]: done 276bf9d7b43a1cc580be264df1883a7195ca8d8c: thanks for suggestion

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx (hunk 14 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx]: I found another thing, fixed here 27c409f1cc655c07a394a5a06b6be15d9ade9baf

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx (hunk 21 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx]: done 96675408171cc738d05a24d8197d7ad09605d3de

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx (hunk 22 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAccountModal/TradingReceiveAccountModal.tsx]: done 96675408171cc738d05a24d8197d7ad09605d3de

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 23 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: removed 96675408171cc738d05a24d8197d7ad09605d3de

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 24 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: done 96675408171cc738d05a24d8197d7ad09605d3de

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 19 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: removed 96675408171cc738d05a24d8197d7ad09605d3de

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 17 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: done a6a4dc29f106a3c0d2e071b136b92d0138cb321b

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 18 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: removed

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 19 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: removed

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx (hunk 20 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddress.tsx]: done a6a4dc29f106a3c0d2e071b136b92d0138cb321b

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx (hunk 26 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingReceiveAddressModal.tsx]: done a6a4dc29f106a3c0d2e071b136b92d0138cb321b

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx (hunk 14 above)
Comment (cermakjiri) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingReceiveAddress/TradingUtxoReceiveAddressModal.tsx]: 👍

**Review by cermakjiri — APPROVED** [review]
LGTM (at least regarding those comments I provided earlier)

**Review by matusbalascak — APPROVED** [review]

File: packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts (hunk 1 above)
Comment (TomasBoda) [reply packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts]: done

File: packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts (hunk 2 above)
Comment (TomasBoda) [reply packages/suite-desktop-core/e2e/support/pageObjects/trading/tradingPage.ts]: done

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts [hunk 27]
```diff
@@ -766,10 +766,19 @@ export const useTradingExchangeForm = ({
 
         const quote = isApproval ? selectedQuote : dexQuotes[0];
 
-        if (!quote) return;
+        if (!quote) {
+            setValue('ethereumDataHex', '');
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts]: is renamed here https://github.com/trezor/trezor-suite/pull/21508, please in case of this is merged first, resolve conflict in my PR. Thanks

Comment (TomasBoda) [reply packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts]: done
