### PR TITLE
fix(suite): fix the send form getting prefilled with an incorrect amount

### LINKED ISSUE #3004: Show Bitcoin value in Satoshis (sat)
_User's request:_
_"Add an option for viewing as whole btc or as satoshis. So if you have 0.1 btc it would show 10.000.000 satoshis"_

- Use only BTC/Sats (no bits, mBTC, uBTC, ... )
    - Bitcoin units whole names: `Bitcoin` / `Satoshis`
    - Next to amounts: `BTC` / `sat`
    
- [ ] Select in settings (not in Bitcoin card detail)
image

- [ ] Settings should be visible only with activated at least one of the coins - `Bitcoin`, `Bitcoin Testnet`, or `Bitcoin Regtest`
- [ ] Changing the displayed Bitcoin unit globally by clicking on Bitcoin amount

Location | Change units on click
-- | --
Dashboard/ Bitcoin balance | ✅
Accounts/ Listed accounts | ✅

- [ ] On hover displays tooltip
drawing

### PR DESCRIPTION
**Pull request by dahaca**
## Description

Now amounts in a draft are converted every time a user switches units, so that the form is always prefilled with relevant units.

## Related Issue

Resolves https://github.com/trezor/trezor-suite/issues/3004#issuecomment-1209278647

### CODE REVIEW

File: packages/suite/src/middlewares/wallet/walletMiddleware.ts [hunk 1]
```diff
@@ -96,6 +101,33 @@ const walletMiddleware =
...
+            const formattedDraft: FormState = { ...api.dispatch(sendFormActions.getDraft()) };
+
+            if (selectedAccount.account && formattedDraft && formattedDraft.outputs) {
+                const areSatsSelected = settings.bitcoinAmountUnit === PROTO.AmountUnit.SATOSHI;
+                const areSatsSupported = hasNetworkFeatures(selectedAccount.account, 'amount-unit');
+
+                const conversionToUse =
+                    areSatsSelected && areSatsSupported ? amountToSatoshi : formatAmount;
+
+                const selectedNetwork = selectedAccount.network as Network;
```
Comment (matejkriz) [inline packages/suite/src/middlewares/wallet/walletMiddleware.ts]: I would use `as` type assertion as last resort, better to verify (e.g. throw an error if selectedNetwork is undefined?) Or if you are sure here, that it's always defined, you could type it with exclamation mark `selectedAccount.network!`

File: packages/suite/src/middlewares/wallet/walletMiddleware.ts [hunk 2]
```diff
@@ -96,6 +101,33 @@ const walletMiddleware =
             api.dispatch(coinmarketBuyActions.dispose());
         }
 
+        if (
+            prevState.router.pathname !== '/accounts/send' &&
+            nextRouter.pathname !== '/accounts/send' &&
```
Comment (matejkriz) [inline packages/suite/src/middlewares/wallet/walletMiddleware.ts]: pathname will never be `/accounts/send` except localhost. It is `web/accounts/send` on production, `fix/satoshi-return-to-send/web/accounts/send` on this branch and so on. 

You could use router.route.name instead.

File: packages/suite/src/middlewares/wallet/walletMiddleware.ts [hunk 3]
```diff
@@ -96,6 +101,33 @@ const walletMiddleware =
...
+            action.type === WALLET_SETTINGS.SET_BITCOIN_AMOUNT_UNITS
+        ) {
+            const { selectedAccount, settings } = api.getState().wallet;
+            const formattedDraft: FormState = { ...api.dispatch(sendFormActions.getDraft()) };
+
+            if (selectedAccount.account && formattedDraft && formattedDraft.outputs) {
```
Comment (matejkriz) [inline packages/suite/src/middlewares/wallet/walletMiddleware.ts]: No account is selected while user is in settings. Also it makes no sense to me apply it on selected account only - you could have drafts on multiple accounts at the same time.

Comment (dahaca) [reply packages/suite/src/middlewares/wallet/walletMiddleware.ts]: Right, then then there is no selected acc on the dashboard either.

Comment (dahaca) [reply packages/suite/src/middlewares/wallet/walletMiddleware.ts]: fa39d3319c7953ea6e6d39c30bc33142d7481bb8

File: packages/suite/src/middlewares/wallet/walletMiddleware.ts (hunk 2 above)
Comment (dahaca) [reply packages/suite/src/middlewares/wallet/walletMiddleware.ts]: fa39d3319c7953ea6e6d39c30bc33142d7481bb8

File: packages/suite/src/middlewares/wallet/walletMiddleware.ts (hunk 1 above)
Comment (dahaca) [reply packages/suite/src/middlewares/wallet/walletMiddleware.ts]: not used anymore fa39d3319c7953ea6e6d39c30bc33142d7481bb8

File: packages/suite/src/actions/wallet/sendFormActions.ts [hunk 4]
```diff
@@ -96,6 +99,70 @@ export const removeDraft = () => (dispatch: Dispatch, getState: GetState) => {
     }
 };
 
+// TODO: replace by structuredClone() after updating TS
+const clone = <T>(info: T): T => {
```
Comment (matejkriz) [inline packages/suite/src/actions/wallet/sendFormActions.ts:103]: this one seems to belong to utils package to be used everywhere (there are lot of places where `JSON.parse(JSON.stringify(object))` is used, [i.e. 20 lines above](https://github.com/trezor/trezor-suite/pull/5970/files#diff-38581ddf07235dae32f96fa731c91cd468abdde80382d5a0571616d64662ef53R85) ), but since it makes sense to replace it soon by `structuredClone`, let's leave it like this...

**Review by matejkriz — APPROVED** [review]
