### PR TITLE
Approval Flow

### LINKED ISSUE #14839: Trading - EVM native coin does not need to be approved to interact with contract
**Describe the bug**

Suite Version: 24.10.1

This step is confusing as you cannot approve native coin only tokens

Screenshot 2024-10-14 at 19 00 45

And it allows me to do revoke 😕 

Screenshot 2024-10-14 at 19 02 43
Screenshot 2024-10-14 at 19 02 24

### LINKED ISSUE #19283: Trading - Receive account select changes back to default option
**Describe the bug**
When `Use an account that isn't in Suite` is selected, `Receive account` select changes back to default option on its own after a few seconds.

**Info:**

- Suite Version: web, 25.5.2

**How to reproduce**

1. Go to Swap section
1. Select a trade
1. In `Receive account` select `Use an account that isn't in Suite`
1. Wait a few seconds, it changes back to default option

**Screenshots**

https://github.com/user-attachments/assets/6cbad54c-a371-4320-ac59-83d2fd7dafd2

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

New approval flow:

- approval step is now the first step, before receiving address
- for native EVM coin, approval step is not shown and is skipped

## Related Issue

Resolve #14839 
Resolve https://github.com/trezor/trezor-suite/issues/19283
Prerequisite for https://github.com/trezor/trezor-suite/issues/19012

## Screenshots

When doing a DEX swap on a token, approval step goes first:

Screenshot 2025-06-11 at 16 04 41

Screenshot 2025-06-11 at 16 05 56

Screenshot 2025-06-11 at 16 04 55

\
After approval, the user is navigated to the receive address step:

Screenshot 2025-06-11 at 16 05 10

\
When swapping native EVM coin, approval step is skipped:

Screenshot 2025-06-11 at 16 06 15

Screenshot 2025-06-11 at 16 06 24

\
🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/approval&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/approval&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/approval&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.ts [hunk 1]
```diff
@@ -160,11 +160,15 @@ const useTradingVerifyAccount = ({
...
+        if (
+            preselectedAccount &&
+            preselectedAccount.type !== 'ADD_SUITE' &&
+            !selectedAccountOption
+        ) {
             selectAccountOption(preselectedAccount);
         }
         // eslint-disable-next-line react-hooks/exhaustive-deps
-    }, [accounts]);
+    }, [preselectedAccount, selectedAccountOption]);
```
Comment (TomasBoda) [inline packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.ts]: After selecting an account in receiving address step, after a few seconds, it automatically reverts back to the first account. This is a **hotfix** for this bug

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx [hunk 2]
```diff
@@ -27,31 +28,43 @@ export const TradingInfoItem = ({
...
+                                <AccountLabeling account={account} />
+                                {account.accountType !== 'normal' ? `(${account.accountType})` : ''}
+                            </Row>
+                        </Text>
+                    )}
+
+                    {account && !showReceiveAccount && (
+                        <Text variant="tertiary" typographyStyle="label" as="div">
+                            <Translation id="TR_EXCHANGE_SWAP_ACCOUNT_TO_BE_SELECTED" />
+                        </Text>
```
Comment (TomasBoda) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoItem.tsx:60]: Do not show receiving account in approval step, since the user has not yet selected a receiving account. Instead, show a message `To be selected`

File: suite-common/trading/src/utils/exchange/exchangeUtils.ts [hunk 3]
```diff
@@ -1,18 +1,33 @@
...
 import { ExchangeInfo } from '../../reducers/exchangeReducer';
 import { TradingExchangeAmountLimitProps, TradingExchangeRateType } from '../../types';
+import { cryptoIdToNetwork, parseCryptoId } from '../../utils';
 
 type GetAmountLimitsProps = {
     quotes: ExchangeTrade[];
     currency: string;
 };
 
+export const isSendingEthNativeToken = (cryptoId?: CryptoId) => {
```
Comment (tomasklim) [inline suite-common/trading/src/utils/exchange/exchangeUtils.ts]:
```suggestion
export const isSendingEvmNativeToken = (cryptoId?: CryptoId) => {
```

File: suite-common/trading/src/utils/exchange/exchangeUtils.ts [hunk 4]
```diff
@@ -1,18 +1,33 @@
...
+    if (!cryptoId) {
+        return false;
+    }
+
+    const isEthNetwork = cryptoIdToNetwork(cryptoId)?.networkType === 'ethereum';
```
Comment (tomasklim) [inline suite-common/trading/src/utils/exchange/exchangeUtils.ts]:
```suggestion
    const isEvmNetwork = cryptoIdToNetwork(cryptoId)?.networkType === 'ethereum';
```

File: suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts [hunk 5]
```diff
@@ -29,7 +29,7 @@ export const selectExchangeQuoteThunk = createThunk(
     `${TRADING_EXCHANGE_THUNK_PREFIX}/selectQuote`,
     async (
         { quote, timer, userConsent, nextStep, onCancel }: SelectExchangeQuoteThunkProps,
-        { dispatch, getState },
+        { getState, dispatch },
```
Comment (tomasklim) [inline suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts]: why this change

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: suite-common/trading/src/utils/exchange/exchangeUtils.ts (hunk 3 above)
Comment (TomasBoda) [reply suite-common/trading/src/utils/exchange/exchangeUtils.ts]: done

File: suite-common/trading/src/utils/exchange/exchangeUtils.ts (hunk 4 above)
Comment (TomasBoda) [reply suite-common/trading/src/utils/exchange/exchangeUtils.ts]: done

File: suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts (hunk 5 above)
Comment (TomasBoda) [reply suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts]: reverted back

**Comment by tomasklim** [comment]
This loading does not happen on develop 

https://github.com/user-attachments/assets/efc31afe-e99f-433d-88e8-60aeb0155dcd

**Comment by TomasBoda** [comment]
> This loading does not happen on develop
> 
>  Screen.Recording.2025-06-11.at.19.08.42.mov

@tomasklim fixed

https://github.com/user-attachments/assets/c63922c2-6d80-46f4-8733-27530bdfc2b8

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx [hunk 6]
```diff
@@ -72,6 +77,68 @@ export const TradingOfferExchangeSendApproval = () => {
 
     const explorers = useSelector(state => state.wallet.explorer);
 
+    const [step, setStep] = useState<'REQUIRED' | 'APPROVED' | 'LOADING' | 'UNKNOWN'>('UNKNOWN');
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx]: I dont like UNKNOWN step

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx [hunk 7]
```diff
@@ -72,6 +77,68 @@ export const TradingOfferExchangeSendApproval = () => {
...
+
+    const { accountAddress } = useTradingVerifyAccount({
+        cryptoId: selectedQuote?.receive,
+        nonSuiteAccount: !selectedQuote?.tags?.includes('noExternalAddress'),
+    });
+
+    useEffect(() => {
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx:89]: @adderpositive will this always work?

**Review by tomasklim — APPROVED** [review]
LGTM, most of the logic will be rewritten again in the next step

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx (hunk 6 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx]: changed to `undefined`

File: packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.ts (hunk 1 above)
Comment (adderpositive) [reply packages/suite/src/hooks/wallet/trading/form/useTradingVerifyAccount.ts]: Now `// eslint-disable-next-line react-hooks/exhaustive-deps` could be deleted, right?

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 8]
```diff
@@ -95,11 +101,41 @@ export const TradingFormOffer = () => {
...
+            dispatch(
+                tradingExchangeActions.setFormStep(
+                    isSendingEvmNativeToken(trade.send)
+                        ? 'RECEIVING_ADDRESS'
+                        : 'SEND_APPROVAL_TRANSACTION',
+                ),
+            );
+        } else {
+            dispatch(tradingExchangeActions.setFormStep('RECEIVING_ADDRESS'));
+        }
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: Can we move this logic into _useTradingExchangeForm_? It should be also cleaner there without typings issues.

File: packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx [hunk 9]
```diff
@@ -110,7 +119,34 @@ export const TradingOffersItem = ({ quote }: TradingOffersItemProps) => {
...
+            dispatch(
+                tradingExchangeActions.setFormStep(
+                    isSendingEvmNativeToken(trade.send)
+                        ? 'RECEIVING_ADDRESS'
+                        : 'SEND_APPROVAL_TRANSACTION',
+                ),
+            );
+        } else {
+            dispatch(tradingExchangeActions.setFormStep('RECEIVING_ADDRESS'));
+        }
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx]: Almost same logic as it is in _TradingFormOffer_

File: packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx [hunk 10]
```diff
@@ -110,7 +119,34 @@ export const TradingOffersItem = ({ quote }: TradingOffersItemProps) => {
 
     const { tradingDeviceDisconnected } = useTradingDeviceDisconnected();
 
-    const onSelectQuote = () => {
+    const { accountAddress } = useTradingVerifyAccount({
+        cryptoId: quote && 'receive' in quote ? quote?.receive : undefined,
+        nonSuiteAccount:
+            quote && 'receive' in quote ? !quote?.tags?.includes('noExternalAddress') : false,
+    });
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx]: I would prefer to not use this kind of overpower canon hook, maybe create small one with something like:

```ts
const { address } = methods.getValues();
const addressDictionary = useAccountAddressDictionary(account);
const accountAddress = address ? addressDictionary[address] : undefined;
```

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 11]
```diff
@@ -95,11 +101,41 @@ export const TradingFormOffer = () => {
             new BigNumber(bestScoredQuoteAmounts.receiveAmount),
         );
 
-    const onSelectQuote = () => {
+    const { accountAddress } = useTradingVerifyAccount({
+        cryptoId: quote && 'receive' in quote ? quote?.receive : undefined,
+        nonSuiteAccount:
+            quote && 'receive' in quote ? !quote?.tags?.includes('noExternalAddress') : false,
+    });
+
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: I would prefer to not use this kind of overpower canon hook, maybe create small one with something like:

```ts
const { address } = methods.getValues();
const addressDictionary = useAccountAddressDictionary(account);
const accountAddress = address ? addressDictionary[address] : undefined;
```

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx [hunk 12]
```diff
@@ -72,6 +77,68 @@ export const TradingOfferExchangeSendApproval = () => {
 
     const explorers = useSelector(state => state.wallet.explorer);
 
+    const [step, setStep] = useState<'REQUIRED' | 'APPROVED' | 'LOADING' | undefined>();
+
+    const { accountAddress } = useTradingVerifyAccount({
+        cryptoId: selectedQuote?.receive,
+        nonSuiteAccount: !selectedQuote?.tags?.includes('noExternalAddress'),
+    });
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx:87]: I would prefer to not use this kind of overpower canon hook, maybe create small one with something like:

```ts
const { address } = methods.getValues();
const addressDictionary = useAccountAddressDictionary(account);
const accountAddress = address ? addressDictionary[address] : undefined;
```

File: suite-common/trading/src/utils/exchange/exchangeUtils.ts [hunk 13]
```diff
@@ -1,18 +1,33 @@
...
 import { ExchangeInfo } from '../../reducers/exchangeReducer';
 import { TradingExchangeAmountLimitProps, TradingExchangeRateType } from '../../types';
+import { cryptoIdToNetwork, parseCryptoId } from '../../utils';
 
 type GetAmountLimitsProps = {
     quotes: ExchangeTrade[];
     currency: string;
 };
 
+export const isSendingEvmNativeToken = (cryptoId?: CryptoId) => {
```
Comment (adderpositive) [inline suite-common/trading/src/utils/exchange/exchangeUtils.ts:18]: Maybe small unit test would be nice

File: suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts [hunk 14]
```diff
@@ -55,7 +55,10 @@ export const selectExchangeQuoteThunk = createThunk(
             return;
         }
 
-        dispatch(tradingExchangeActions.saveSelectedQuote(quote));
+        if (!quote.isDex) {
```
Comment (adderpositive) [inline suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts:58]: Why is it used only for CEX?

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx [hunk 15]
```diff
@@ -72,6 +77,68 @@ export const TradingOfferExchangeSendApproval = () => {
 
     const explorers = useSelector(state => state.wallet.explorer);
 
+    const [step, setStep] = useState<'REQUIRED' | 'APPROVED' | 'LOADING' | undefined>();
```
Comment (adderpositive) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx]: Nit: I would prefer something like `approvalStep` to be more specific in this case.

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx (hunk 7 above)
Comment (adderpositive) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx:89]: I hope so!

**Review by adderpositive — CHANGES_REQUESTED** [review]

**Comment by adderpositive** [comment]
Anyway, it works well. Great job 👏 I've read @tomasklim's comment, and if you've plans to do some refactors in your next PRs, you can postpone my remarks.

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx (hunk 8 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: will do in next PR

File: packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx (hunk 9 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx]: will move it to `useTradingExchangeForm` in next PR

File: packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx (hunk 10 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingOffers/TradingOffersItem.tsx]: created a new lightweight hook `useTradingReceiveAddress`

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx (hunk 11 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx]: created a new lightweight hook `useTradingReceiveAddress`

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx (hunk 12 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx:87]: created a new lightweight hook `useTradingReceiveAddress`

File: suite-common/trading/src/utils/exchange/exchangeUtils.ts (hunk 13 above)
Comment (TomasBoda) [reply suite-common/trading/src/utils/exchange/exchangeUtils.ts:18]: will do in next PR when the flow is finalized

File: suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts (hunk 14 above)
Comment (TomasBoda) [reply suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts:58]: because `selectQuote` logic would override `quote` from the newly added `confirmTrade` logic and approval would not work

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx (hunk 15 above)
Comment (TomasBoda) [reply packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx]: done

**Review by adderpositive — APPROVED** [review]

File: packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx [hunk 16]
```diff
@@ -72,6 +77,70 @@ export const TradingOfferExchangeSendApproval = () => {
...
+        }
+
+        const forceConfirmTrade = async () => {
+            if (!accountAddress?.address) {
+                return;
+            }
+
+            await confirmTrade({
+                trade: selectedQuote,
+                receiveAddress: accountAddress?.address,
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx:118]: bug?

File: packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx [hunk 17]
```diff
@@ -95,11 +101,39 @@ export const TradingFormOffer = () => {
...
+            await confirmTrade({ trade, receiveAddress });
+            setIsDexSwapLoading(false);
+
+            dispatch(
+                tradingExchangeActions.setFormStep(
+                    isSendingEvmNativeToken(trade.send)
+                        ? 'RECEIVING_ADDRESS'
+                        : 'SEND_APPROVAL_TRANSACTION',
+                ),
+            );
```
Comment (tomasklim) [inline packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx:132]: bug?

File: suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts (hunk 14 above)
Comment (tomasklim) [reply suite-common/trading/src/thunks/exchange/selectExchangeQuoteThunk.ts:58]: maybe this logic should be here? https://github.com/trezor/trezor-suite/pull/19486/files#r2144763056 @adderpositive @TomasBoda
