### PR TITLE
fix(suite-native): Connect & Unlock: fix BT button visibility

### LINKED ISSUE #20871: Button to Connect via Bluetooth offered for trezor models without bluetooth
**Describe the bug**
We show "Connect via Bluetooth" button on Connect & unlock your Trezor screen even for trezor models without Bluetooth. If we don't know the model, of course we want to offer both options but in cases where we know the model we should respect it's capability.

**Info:**

- Mobile Suite Version: 25.8.1 develop
- OS: android & ios

**How to reproduce**

1. Connect trezor model without Bluetooth and wait for discovery to be finished
1. Unplug the trezor
1. Go to Device Settings and initiate any action that needs trezor connected

**Expected behavior**
"Connect via Bluetooth" button should not be visible if we expect trezor without Bluetooth to be connected. Ideally the image should also reflect expected trezor model.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by BrantalikP**
## Description

hide BT button if the model does not support connection via BT

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20871

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/connect-via-bt-btn-visibility&lookback=7)

### CODE REVIEW

File: suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx [hunk 1]
```diff
@@ -25,6 +30,12 @@ export const ConnectAndUnlockDeviceScreen = ({
     RootStackParamList
 >) => {
     const isBluetoothEnabled = useFeatureFlag(FeatureFlag.IsBluetoothEnabled);
+    const isBluetoothSupportedByDevice = useSelector(selectIsBluetoothSupportedByDevice);
+    const isSelectedDevice = useSelector(selectSelectedDevice);
```
Comment (BrantalikP) [inline suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: @matejkriz probably the condition here is redundant as I can see the `ConnectAndUnlock` is displayed only for the actions where the device is already known

Comment (juriczech) [reply suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: Mobile app always has selected device after onboarding, because we have portfolio tracker, so it's probably redundant.

Comment (BrantalikP) [reply suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: https://github.com/trezor/trezor-suite/pull/21761/commits/deeced880f8176b9dad4bffb457ecf6e5e3110f9

File: suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx [hunk 2]
```diff
@@ -25,6 +29,10 @@ export const ConnectAndUnlockDeviceScreen = ({
     RootStackParamList
 >) => {
     const isBluetoothEnabled = useFeatureFlag(FeatureFlag.IsBluetoothEnabled);
+    const isBluetoothSupportedByDevice = useSelector(selectIsBluetoothSupportedByDevice);
+    const isBluetoothButtonVisible =
+        // if the model does not support bluetooth, we should not show the button,
```
Comment (yanascz) [inline suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: This comment seems redundant, you can see this from the code below.

File: suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx [hunk 3]
```diff
@@ -25,6 +29,10 @@ export const ConnectAndUnlockDeviceScreen = ({
...
+        isBluetoothSupportedByDevice && isBluetoothEnabled;
```
Comment (yanascz) [inline suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: Would swap the order here:
```suggestion
        isBluetoothEnabled && isBluetoothSupportedByDevice;
```

File: suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx (hunk 2 above)
Comment (BrantalikP) [reply suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: https://github.com/trezor/trezor-suite/pull/21761/commits/daf8e413eb77ad1fe2f819a77396173187561ae3 Agree

File: suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx (hunk 3 above)
Comment (BrantalikP) [reply suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx]: https://github.com/trezor/trezor-suite/pull/21761/commits/daf8e413eb77ad1fe2f819a77396173187561ae3 done ☑️

**Review by yanascz — APPROVED** [review]
Nice, thanks for fixing this! 👏

**Review by yanascz — CHANGES_REQUESTED** [review]
I wanted to be sure and tested that on Android and it doesn't offer you the ability to connect a BT device if no device is selected.

**Review by yanascz — APPROVED** [review]
Now it works as expected. 😅
