### PR TITLE
Interaction-less fw update

### LINKED ISSUE #4383: Error when trying to update firmware while discovery is going on
**Describe the bug**
When I tried to do a FW update from 1.10.1>1.10.3 on T1 (connected through WebUSB) that I got prompted to do, while the discovery was still going on, I got an error and I couldn't proceed with the update. The device got stuck on the "restart to bootloader" screen and Suite suddenly tells me to reconnect the device in bootloader mode. Although, if I reconnect the device in bootloader mode, I can proceed with the update, the screen on the Suite and the screen on the device doesn't "match" with the instructions and it gets confusing. Video of this error is attached.

**Steps to reproduce:**
1. Kill Trezor Bridge.
2. Open Trezor Suite on Chrome
3. Connect your device
4. Quickly navigate to the FW update in Trezor Suite, while the discovery is still going
5. Click on "Install"
6. Aggree that you got your seed
7. The error is shown in the notifications and you get prompted to reconnect device in BL mode

**Info:**
 - Suite version: web 21.10.2 (3cb57ead18474b380841b479a542c0b910b3d936)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model 1 1.10.1 regular

**Expected result:**
No error is present and I can continue with the firmware update.

**Actual result:**
An error pops up and it is unclear what to do since the device and the Suite shows different information

**Video:**

https://user-images.githubusercontent.com/48477147/137503568-ac19bd00-1f9d-4380-a88f-88addac4ed59.mp4

### LINKED ISSUE #6578: Stuck on "Restarting Trezor" when installing custom unsigned firmware
**Describe the bug**
If I want to install a custom firmware which will erase my seed after the installation, I get stuck in the FW installation modal on "Restarting Trezor" point. The Trezor will restart but it will be in the "initialization" mode and the modal doesn't recognize that.

**Steps to reproduce:**
1. Go to settings
2. Click on "Install custom firmware"
3. Select any unsigned firmware and try to install it
4. Continue on your device the whole installation process
5. After the Trezor restarts, the Suite will still show "Restarting Trezor" point in the installation but the device is already restarted

**Info:**
 - Suite version: web 22.11.0 (06a5bf901f7dd05b98d7db650afbef79680efdb7)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32

**Expected result:**
Suite will recognize the restart of the device and will show the initialization page

**Actual result:**
Suite is stuck on the "Restarting Trezor" point in the custom firmware modal.

**Screenshots:**
image

### LINKED ISSUE #8108: Overlapping modals while installing custom firmware
Downgrading FW from 2.6.0 to 2.5.3. It works, but the UI looks broken. There should not be overlapping modals nor a modal without content.

Screenshot 2023-04-14 at 15 03 14

Screenshot 2023-04-14 at 15 03 43

### LINKED ISSUE #10067: Support interaction-less update
Please simplify the Device FW update/reinstallation flow according to the diagram and especially the tech specification from @matejcik  below.

Image

From [here](https://github.com/trezor/trezor-firmware/issues/2919#issuecomment-1723398691). Please discuss details with @matejcik.

> interaction-less update RFC:
> 
> 1. Firmware stage
> 
> host sends FirmwareUpdate that contains exactly the header, i.e., concatenated vendor header + firmware header
> 
> firmware verifies that:
> 
> the headers are valid (signatures match etc)
> vendor matches the currently installed one
> version is strictly higher than the current one
> if this fails, Failure is returned. (if the operation is actually what the user wants, they will need to go to bootloader to do it)
> 
> if it is OK, Trezor displays a prompt:
> "Upgrade firmware to version 2.7.9?"
> (I don't think we need to mention the vendor here, given that it is forced to be the same as current -- but we can)
> 
> when the user confirms, firmware sends Success and jumps to bootloader
> 
> host must wait until the device disappears from the bus and a bootloader reappears
> 
> 2. Bootloader stage
> 
> bootloader detects that a header was sent from firmware
> 
> bootloader verifies that:
> 
> the headers are valid
> vendor matches the currently installed one
> vendor is strictly higher than the current one
> if this fails, an error screen is displayed, asking the user to replug device (?)
> (alternately, we could either (a) continue booting as if nothing happened, or (b) jump to bootloader menu as if normal jump-to-bootloader)
> 
> if header is OK, bootloader goes to "waiting for host" screen. this should be rendered in black instead of bootloader blue
> 
> host sends FirmwareErase message indicating that it is ready to update firmware
> 
> if the host sends something else here, like UnlockBootloader or WipeDevice, we can probably go to that flow? it seems to make the impl simpler, and I can't see any problem in allowing that.
> bootloader acts as if it already received the header and jumps to verification. we need to inject an automatic response into this step -- this is already done when is_new comes out as sectrue, so that should not be a problem
> 
> firmware upgrade process continues as normal (with black progress bar)
> 
> For bonus points:
> 
> Make the interval between erasing firmware and writing first sector shorter.
> The ideal would be:
> 
> receive & validate header
> erase first sector
> write header at start of first sector
> erase rest of sectors
> proceed to ask for first chunk, then write chunk into rest of sector
> this shortens the interval when no valid header is present in flash to minimum (i.e., if we allow recovery from corrupted firmware, the only way to lose the header is if the power goes out at exactly the right moment)
> 
> unfortunately I believe it further complicates the logic of chunk handling. but maybe we could untangle and refactor the current code so that this is achievable?
> 
> cc @mroz22 for Connect-side review

### LINKED ISSUE #10099: Translations blob handling with firmware
Some `Suite`-related information about upcoming firmware translations:
- the handling will be similar to `ETH definitions` - `Suite` will not have to create any data, the whole signed binary/blob will be hosted on `trezor.io` --- with variables being the `language` (`cs`/`fr`), `version` (`2.6.3`) and `model` (`TT`/`TR`)
- creation, signing and uploading of the blob will happen outside of `Suite` - via `trezorlib` and other tools --- so `Suite` could just stream the blob into the device without having to know much about it

Supported models:
- currently, `T1` translations are not supported, and probably will not be, at least right now

Content of translations blob:
- it contains all the translations strings, but also font data --- therefore each model (`TT` vs `TR`) has different fonts, therefore different blobs

Data integrity:
- translations data are signed, and device will reject them when signature validation fails

Versioning:
- translations will be versioned according to the firmware version they belong to - e.g. firmware `2.6.4` will only accept translations of version `2.6.4` --- and reject all others when tried to load

New protobuf messages:
- one to start the process - `ChangeLanguage` - and then two exchanged in messaging driven by device - `TranslationDataRequest` and `TranslationDataAck`

https://github.com/trezor/trezor-firmware/blob/grdddj/fw_translations/common/protob/messages-management.proto#L182-L211

Trezorlib handling:
- initiating the language change by sending `data_length` - when 0, that will reset language to `english`, when positive, device will start requesting data in chunks (max 1024 bytes)

https://github.com/trezor/trezor-firmware/blob/grdddj/fw_translations/python/src/trezorlib/device.py#L66-L84

Getting the language from the device:
- what was already possible before - reading `language` string from `Features` --- `en-US` when English, otherwise the abbreviation like `cs` or `fr`

Firmware updating process:
- when the user with loaded translations updates firmware, it would be nice to offer him an update of the translations blob as well (there is a chance that the translations got changed, or new strings were added)
- device may show something like `Translations update needed` on the device homescreen, but it may be done automatically after firmware update in `Suite`

### PR DESCRIPTION
**Pull request by mroz22**
Changes here:
- moving all firmware update logic into connect. 
  - In the begging, fw update was quite simple (combination of FirmwareErase and FirmwareUpload calls + some progress faking events), so it was added into connect just like a regular method. Over the time, it has grown in complexity but the complexity was tackled on suite level which is no longer sustainable (logic scattered all over the place, actions, middlewares..). Adding support for interactionless fw update would make it only worse.
- support for interaction-less fw update
- support for changing of language of device during fw update

How well are we able to test all different scenarios in firmware update (from top of my head):
- [ ] firmware header stripping (or not)
- [ ] incremental update (was it fully replaced by intermediary?)
- [ ] intermediary update and all its versions
- [ ] reboot to bootloader "classic"
- [ ] reboot to bootloader with interactionless firmware update
- [ ] firmware hash check
- [ ] translations update.
- [ ] fw update when PIN is set
- [ ] fw update bridge vs webusb (don't forget to reset permissions to test bootloader that needs to be paired)
- [ ] switch from official to unofficial and other cases where seed is wiped during install
- [ ] device disconnected during different phases of update process
- [ ] device initially connected in bootloader mode vs normal mode
- [ ] custom fw install
  - [ ] major version 2
  - [ ] version pre 1.8.0 
  - [ ] version  after 1.8.0

did I forget something?

resolve #10067
resolve #8108
resolve #10099
resolve #6578
resolve #4383

### CODE REVIEW

**Comment by komret** [comment]
Models to test this on:

T1:
BL < 1.8.0 - to test intermediary FW v1 and manual reboot
BL >= 1.10.0, < 1.12.0 - to test intermediary FW v2 and automatic reboot

TT:
FW < 2.0.8 - to check if we can upgrade to current or if 2.1.1 is needed first and test manual reboot
FW >= 2.6.0, < 2.6.3 - to check automatic reboot (should be tested on both web and desktop)
FW >= 2.6.3 to test interaction-less update

TS3:
FW  2.6.2 to check automatic reboot
FW >= 2.6.3 to test interaction-less update

File: packages/suite/src/views/firmware/index.tsx [hunk 1]
```diff
@@ -63,19 +69,18 @@ export const Firmware = ({ shouldSwitchFirmwareType }: FirmwareProps) => {
...
+        return null;
         // device features cannot be read, device is probably used in another window
-        if (device.type === 'unacquired') return DeviceAcquire;
+        // if (device.type === 'unacquired') return DeviceAcquire;
         // Webusb unreadable device (HID)
-        if (device.type === 'unreadable') return DeviceUnreadable;
+        // if (device.type === 'unreadable') return DeviceUnreadable;
         // device features unknown (this shouldn't happened tho)
-        if (!device.features) return DeviceUnknown;
+        // if (!device.features) return DeviceUnknown;
```
Comment (komret) [inline packages/suite/src/views/firmware/index.tsx]: Why are these commented out?

File: packages/connect/src/core/index.ts [hunk 2]
```diff
@@ -1149,3 +1162,311 @@ const disableWebUSBTransport = async () => {
...
+    if (support.getFirmwareHash) {
+        log.debug('onCallFirmwareUpdate', 'getFirmwareHash supported, proceed with check');
+        const { hash, challenge } = calculateFirmwareHash(
+            device.features.major_version,
+            stripped!,
+            randomBytes(32),
+        );
+
+        try {
+            const getFirmwareHashResponse = await reconnectedDevice.commands!.typedCall(
```
Comment (komret) [inline packages/connect/src/core/index.ts]: Would be nice to notify frontend about this similarly as installation progress is handled so that something can be displayed. We currently display a message that fw is being validated - otherwise there is quite a gap between 100% progress and being actually finished. Maybe firing an event when validation starts? But I guess I can also show the message when progress === 100 and the response has not been received yet.

File: packages/connect/src/core/index.ts [hunk 3]
```diff
@@ -1149,3 +1162,311 @@ const disableWebUSBTransport = async () => {
...
+                {
+                    data_chunk: Buffer.from(chunk).toString('hex'),
+                },
+            );
+        }
+    }
+
+    log.debug('onCallFirmwareUpdate', 'waiting for device to disconnect');
+    postMessage(
+        createUiMessage(UI.FIRMWARE_DISCONNECT, {
```
Comment (komret) [inline packages/connect/src/core/index.ts]: I am getting these diconnect/reconnect events even though manual disconnect/reconnect is not needed, e.g. when reinstalling FW on TS3. Is that a bug?

Comment (mroz22) [reply packages/connect/src/core/index.ts]: these events should come always whene device is going to disconnect or reconnect. whether manual action is needed is marked by field "manual: boolean" on that event

File: packages/connect/src/core/index.ts (hunk 2 above)
Comment (mroz22) [reply packages/connect/src/core/index.ts]: no problem, we could fire some more elaborate progress events. I was thinking about someting like

1. at the start of fwupdate process, fire an event with expected steps of fw update, so that you can display some empty bullet points or have idea about what 100% actually means.
2. fire those events as points from 1 are completed

File: packages/suite/src/views/firmware/index.tsx (hunk 1 above)
Comment (mroz22) [reply packages/suite/src/views/firmware/index.tsx]: not sure, just some testing. whatever changes I made to packages/suite* are not set in stone definitely

File: packages/connect/src/core/index.ts [hunk 4]
```diff
@@ -1149,3 +1162,341 @@ const disableWebUSBTransport = async () => {
...
+            }
+            if (!bootloader && reconnectedDevice.features?.bootloader_mode) {
+                throw new Error('not in requested mode');
+            }
+
+            return reconnectedDevice;
+        } catch (err) {
+            return waitForReconnectedDevice(deviceList, bootloader);
+        }
+    };
```
Comment (marekrjpolak) [inline packages/connect/src/core/index.ts]: I've tried to simplify these. Is this equivalent?
```suggestion
    const waitForReconnectedDevice = async (
        deviceList: DeviceList,
        bootloader: boolean,
    ): Promise<Device> => {
        let device: Device | undefined;
        do {
            await createTimeoutPromise(2000);
            try {
                await deviceList.enumerate();
                const devicePath = deviceList.getFirstDevicePath();
                const reconnectedDevice = deviceList.getDevice(devicePath);
                await reconnectedDevice.waitForFirstRun();
                device = reconnectedDevice;
            } catch {}
        } while (!device || bootloader === !device.features?.bootloader_mode);

        return device;
    };
```

File: packages/connect/src/core/index.ts [hunk 5]
```diff
@@ -1149,3 +1162,341 @@ const disableWebUSBTransport = async () => {
...
+            await new Promise(resolve => {
+                setTimeout(() => {
+                    deviceList.enumerate().then(() => {
+                        resolve(undefined);
+                    });
+                }, 1000);
+            });
+            return waitForDisconnectedDevice(deviceList);
+        }
+    };
```
Comment (marekrjpolak) [inline packages/connect/src/core/index.ts]: Same thing here:
```suggestion
    const waitForDisconnectedDevice = async (deviceList: DeviceList): Promise<void> => {
        while (deviceList.allDevices.length) {
            await createTimeoutPromise(1000);
            await deviceList.enumerate();
        }
    };
```

File: packages/connect/src/core/index.ts [hunk 6]
```diff
@@ -1149,3 +1162,341 @@ const disableWebUSBTransport = async () => {
         // do nothing
     }
 };
+
+// onCallFirmwareUpdate imports
```
Comment (marekrjpolak) [inline packages/connect/src/core/index.ts]: It would be nice to have it in a separate file, even if `initDevice` must've been passed as a param because of that.

File: packages/connect/src/core/index.ts [hunk 7]
```diff
@@ -1149,3 +1162,341 @@ const disableWebUSBTransport = async () => {
...
+            confirmOnDevice: flow !== 'manual',
+        }),
+    );
+    let reconnectedDevice = await waitForReconnectedDevice(deviceList, true);
+
+    await reconnectedDevice.acquire();
+
+    let stripped: ArrayBuffer | undefined;
+
+    while (reconnectedDevice.firmwareRelease?.isNewer) {
```
Comment (marekrjpolak) [inline packages/connect/src/core/index.ts]: I would separate the nested code blocks (branches, cycles, even nested function) so it's obvious at first sight what is the main func doing. (Of course not when there would be too many params needed to pass)

File: packages/connect/src/core/index.ts [hunk 8]
```diff
@@ -1149,3 +1162,341 @@ const disableWebUSBTransport = async () => {
...
+            return res;
+        });
+    };
+
+    binary = params.binary || (await getBinaryHelper(device));
+
+    log.debug('onCallFirmwareUpdate initial binary downloaded', flow);
+
+    if (flow !== 'manual') {
+        const rebootToBooloderParams: PROTO.RebootToBootloader = {};
```
Comment (marekrjpolak) [inline packages/connect/src/core/index.ts]: Nit: you spelled `bulldozer` wrong.

File: packages/connect/src/core/index.ts [hunk 9]
```diff
@@ -1149,3 +1162,341 @@ const disableWebUSBTransport = async () => {
...
+    log.debug('onCallFirmwareUpdate flow selected: ', flow);
+
+    await device.acquire();
+    let binary: ArrayBuffer | undefined;
+    // parametrized getBinary to save some lines of code
+    const getBinaryHelper = async (forDevice: Device) => {
+        if (!forDevice.firmwareRelease) {
+            throw TypedError('Runtime', 'device.firmwareRelease is not set');
+        }
+        const btcOnly = params.btcOnly || device.firmwareType === 'bitcoin-only';
```
Comment (marekrjpolak) [inline packages/connect/src/core/index.ts]: Is it intended to read from `device` inside `getBinaryHelper` when it receives `forDevice` arg as well? Could they be devices with different properties?

File: packages/connect/src/core/index.ts [hunk 10]
```diff
@@ -1149,3 +1162,341 @@ const disableWebUSBTransport = async () => {
...
+        if (flow === 'reboot_and_upgrade') {
+            // download firmware
+
+            rebootToBooloderParams['boot_command'] = 1;
+            rebootToBooloderParams['firmware_header'] = Buffer.from(binary.slice(0, 6000)).toString(
+                'hex',
+            );
+        }
+        if (support.language_data_length) {
+            languageBlob = await getLanguage({
```
Comment (marekrjpolak) [inline packages/connect/src/core/index.ts]: If I read this correctly, `languageBlob` is fetched and transferred into device everytime when supported in non-manual flow. Is it ok even with custom firmware (`params.binary`) passed? Because then `device.release.version` is used for the language but it's not the final fw version as fw installation cycle ends after first iteration in that case.

**Review by marekrjpolak — COMMENTED** [review]
Here are some of the comments, but I'm still thinking about it. (I've reviewed only the Connect part)

File: packages/connect/src/core/index.ts (hunk 10 above)
Comment (mroz22) [reply packages/connect/src/core/index.ts]: if params.binary is passed, language update branch should be imho skipped

File: packages/connect/src/events/ui-request.ts [hunk 11]
```diff
@@ -23,6 +23,12 @@ export const UI_REQUEST = {
     FIRMWARE_NOT_COMPATIBLE: 'ui-device_firmware_not_compatible',
     FIRMWARE_NOT_INSTALLED: 'ui-device_firmware_not_installed',
     FIRMWARE_PROGRESS: 'ui-firmware-progress',
+
+    /** connect is waiting for device to automatically disconnect */
+    FIRMWARE_DISCONNECT: 'ui-firmware_disconnect',
+    /** connect is waiting for device to be automatically reconnected */
+    FIRMWARE_RECONNECT: 'ui-firmware_reconnect',
```
Comment (mroz22) [inline packages/connect/src/events/ui-request.ts:30]: maybe these should be more generic? maybe `DEVICE_REQUEST_DISCONNECT` and `DEVICE_REQUEST_RECONNECT`

File: packages/connect/src/factory.ts [hunk 12]
```diff
@@ -247,6 +247,8 @@ export const factory = ({
 
         firmwareUpdate: params => call({ ...params, method: 'firmwareUpdate' }),
 
+        firmwareUpdate_v2: params => call({ ...params, method: 'firmwareUpdate_v2' }),
```
Comment (mroz22) [inline packages/connect/src/factory.ts:250]: I will remove old firmwareUpdate in the last commit and replace it with the new one

File: docs/features/onboarding/onboarding.md [hunk 13]
```diff
@@ -197,10 +197,7 @@ User proceeds by clicking "Install firmware" CTA. Since the device without firmw
...
-
-In firmwareMiddleware we detect such a device thanks to `intermediaryInstalled` flag and the fact that it was connected in bootloader mode despite the instructions for connecting in normal mode.
-Then it triggers an installation of subsequent firmware, which will be the latest firmware available. It will follow basically same flow as with the first installation.
+T1B1 devices with old bootloader cannot be upgraded to latest firmware directly. First we'll install so called intermediary firmware (and set flag `firmware.intermediaryInstalled` to true), which will bump bootloader to newer version. After installation is completed the user will be asked to reconnect the device in normal mode (which is standard procedure after installing a regular firmware). However, because intermediary firmware only bumps bootloader and doesn't install any firmware, device will be in bootloader mode regardless of how the user reconnects it. Then it triggers an installation of subsequent firmware, which will be the latest firmware available. It will follow basically same flow as with the first installation.
```
Comment (mroz22) [inline docs/features/onboarding/onboarding.md]: note for me: is it still a thing, this `firmware.intermediarryInstalled`?

File: packages/connect/src/api/firmware/uploadFirmware.ts [hunk 14]
```diff
@@ -36,10 +38,31 @@ export const uploadFirmware = async (
...
             payload,
+        }).then(() => {
+            done = true;
         });
+
+        let i = 0;
+
+        const postProgressMessageIter = async () => {
+            i++;
+            postProgressMessage(device, Math.min(i * 2, 99), postMessage);
```
Comment (mroz22) [inline packages/connect/src/api/firmware/uploadFirmware.ts:46]: in the old code, there was distinction between model One and model T in terms of fake progress bar duration. we might need to fine-tune it here as well. At the moment it doesn't take into account model differences. cc @komret

File: packages/connect/src/factory.ts (hunk 12 above)
Comment (mroz22) [reply packages/connect/src/factory.ts:250]: or do we still need the old method? @komret

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx [hunk 15]
```diff
@@ -201,30 +143,25 @@ const ReconnectStep = ({ order, active, dataTest, children }: ReconnectStepProps
...
-        type === 'BOOTLOADER' &&
+    const type =
         deviceModelInternal === DeviceModelInternal.T1B1 &&
         semver.valid(deviceFwVersion) &&
         semver.satisfies(deviceFwVersion, '<1.8.0')
-    ) {
-        type = 'BOOTLOADER_TWO_BUTTONS';
-    }
+            ? 'BOOTLOADER_TWO_BUTTONS'
+            : 'BOOTLOADER';
```
Comment (mroz22) [inline packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx:149]: this could have beeen transefered to the new events in connect as well. just leaving a note and maybe we will do it, maybe not.

Comment (komret) [reply packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx:149]: Sounds good.

File: packages/connect/src/api/firmware/uploadFirmware.ts (hunk 14 above)
Comment (komret) [reply packages/connect/src/api/firmware/uploadFirmware.ts:46]: Not sure, maybe not necessary...
I deleted the fake timers entirely because
- newer firmware seems to send the progress info sooner so there is less or no delay
- it reduces code complexity
- it can cause [confusing bugs](https://satoshilabs.slack.com/archives/CKN5C51CJ/p1711363048471019?thread_ts=1709329814.340539&cid=CKN5C51CJ)

File: packages/connect/src/factory.ts (hunk 12 above)
Comment (komret) [reply packages/connect/src/factory.ts:250]: > or do we still need the old method? @komret

We don't, I think it can be deleted, I was afraid to do it.

File: packages/connect/src/core/onCallFirmwareUpdate.ts [hunk 16]
```diff
@@ -456,6 +457,13 @@ export const onCallFirmwareUpdate = async ({
         context: { deviceList, device: reconnectedDevice, log, postMessage },
     });
 
+    // features.firmware_present non-null value implies that device was initially connected with
+    // features.bootloader_mode=true, which means that no automatic language update was performed
+    if (reconnectedDevice.atLeast(['2.7.0']) && deviceInitiallyConnectedWithoutFirmware) {
```
Comment (komret) [inline packages/connect/src/core/onCallFirmwareUpdate.ts]: Can we pull the feature support from config rather than having the versions hard-coded? There are multiple instances in this file.

File: packages/connect/src/device/DeviceList.ts [hunk 17]
```diff
@@ -176,6 +176,16 @@ export class DeviceList extends TypedEmitter<DeviceListEvents> {
              * where transport.acquire, transport.release is called
              */
             this.transport.on(TRANSPORT.UPDATE, diff => {
+                diff.disconnected.forEach(descriptor => {
```
Comment (marekrjpolak) [inline packages/connect/src/device/DeviceList.ts:179]: Is there a reason why `diff.disconnected `must be iterated before the other ones? Was it incorrect until now or is the change needed specifically because of interactionless update?

File: packages/connect/src/api/firmware/uploadFirmware.ts [hunk 18]
```diff
@@ -36,10 +38,31 @@ export const uploadFirmware = async (
...
+            await createTimeoutPromise(300);
+            if (!done) {
+                postProgressMessageIter();
+            }
+        };
+
+        postProgressMessageIter();
+
+        await message;
```
Comment (marekrjpolak) [inline packages/connect/src/api/firmware/uploadFirmware.ts]: If you decide to keep the fake progress code ([this conversation](https://github.com/trezor/trezor-suite/pull/11300/files#r1545719604)), wouldn't this be a bit simpler? Also, I've changed `then` to `finally` so the fake progress is stopped even in case of failure.
```suggestion
        let i = 0;
        const progressTimer = setInterval(() => {
            i++;
            postProgressMessage(device, Math.min(i * 2, 99), postMessage);
        }, 300);

        const message = await typedCall('FirmwareUpload', 'Success', {
            payload,
        }).finally(() => {
            clearInterval(progressTimer);
        });        
```

File: packages/connect/src/api/firmware/parseFirmwareHeaders.ts [hunk 19]
```diff
@@ -0,0 +1,50 @@
...
+            .subarray(vendorHeaderLength, vendorHeaderLength + 4)
+            .toString('utf8');
+        restbuff = buff.subarray(vendorHeaderLength + 4);
+    } else if (vendorHeader === 'TRZR') {
+        restbuff = buff.subarray(256 + 4);
+        trezorImageHeader = buff.subarray(256 + 4, 256 + 8).toString('utf8');
+    } else {
+        restbuff = buff.subarray(4);
+        trezorImageHeader = buff.subarray(0, 4).toString('utf8');
+    }
```
Comment (marekrjpolak) [inline packages/connect/src/api/firmware/parseFirmwareHeaders.ts]: If I understand this correctly, it means roughly:

- based on header magic:
  - in case of `TRZV`, throw away first `vendorHeaderLength` bytes (variable size)
  - in case of `TRZR`, throw away first 256 bytes (constant size)
  - else don't throw away anything
- split the rest into 4 bytes of (nested) magic and the rest
- continue only for `TRZF` header and read the version bytes

If this is right, I believe `TRZR` branch might be incorrect, as a) not 256 but 260 bytes is thrown away (as opposed e.g. to `stripFwHeaders` utility) and b) `restbuff` and `trezorImageHeader` are overlapping.

Comment (marekrjpolak) [reply packages/connect/src/api/firmware/parseFirmwareHeaders.ts]: Also, it would be nice to unify it with mentioned `stripFwHeaders` utility, but it's a bit different (in `stripFwHeaders` we need `TRZV` unstripped) so we can leave it for followup.

File: packages/connect/src/device/DeviceList.ts (hunk 17 above)
Comment (mroz22) [reply packages/connect/src/device/DeviceList.ts:179]: reading the code now, it doesn't feel needeed but I will check it again. There was a problem with auto-reconnection of device over webusb not triggering disconnect event. This should be fixed hopefuly by adding `product` field to descriptor and treating it as defacto part of `descriptor.path`

File: packages/connect/src/api/changeLanguage.ts [hunk 20]
```diff
@@ -54,64 +42,12 @@ export default class ChangeLanguage extends AbstractMethod<'changeLanguage', Cha
...
-                {
-                    data_chunk: Buffer.from(chunk).toString('hex'),
-                },
-            );
-        }
-
-        return response.message;
-    }
-
     async run() {
```
Comment (komret) [inline packages/connect/src/api/changeLanguage.ts]: `async` is redundant here? Detected by linter.

File: packages/connect/src/core/onCallFirmwareUpdate.ts [hunk 21]
```diff
@@ -0,0 +1,508 @@
...
+
+        await device.acquire();
+
+        if (!language) {
+            await device.getCommands().typedCall('RebootToBootloader', 'Success', rebootParams);
+        } else {
+            const targetLanguage = params.language || device.features.language || 'en-US';
+
+            let languageBlob;
+            if (targetLanguage !== 'en-US') {
```
Comment (marekrjpolak) [inline packages/connect/src/core/onCallFirmwareUpdate.ts]: It seems that variant with `targetLanguage === 'en-US'` is equivalent to variant with `!language`, so I propose moving the condition outside the `else` branch, something like
```
const blob = language && targetLanguage !== 'en-US' ? await getLanguage(...) : undefined;
if (blob) {
    ...
} else {
    ...
}
```
That way, you don't have to check blob in while cycle condition.

File: packages/connect/src/core/onCallFirmwareUpdate.ts [hunk 22]
```diff
@@ -0,0 +1,508 @@
...
+        });
+    }
+
+    if (!params.binary && device.firmwareRelease.intermediaryVersion) {
+        log.debug('onCallFirmwareUpdate', 'installing intermediary');
+        reconnectedDevice = await waitForReconnectedDevice({
+            params: {
+                bootloader: true,
+                manual,
+                // todo: check if correct?
```
Comment (marekrjpolak) [inline packages/connect/src/core/onCallFirmwareUpdate.ts]: is correct?

File: packages/connect/src/core/onCallFirmwareUpdate.ts [hunk 23]
```diff
@@ -0,0 +1,508 @@
...
+        await waitForDisconnectedDevice({
+            params: { manual },
+            context: { deviceList, log, device: reconnectedDevice, postMessage },
+        });
+        reconnectedDevice = await waitForReconnectedDevice({
+            params: { bootloader: true, manual, confirmOnDevice: false },
+            context: { deviceList, device: reconnectedDevice, log, postMessage },
+        });
+
+        binary = await getBinaryHelper(reconnectedDevice, params, log, postMessage);
```
Comment (marekrjpolak) [inline packages/connect/src/core/onCallFirmwareUpdate.ts]: This `binary` is unused. Shouldn't it be sent to `uploadFirmware` below instead of `stripped`? One way or another, I'd better make it `const`.

File: packages/connect/src/core/onCallFirmwareUpdate.ts [hunk 24]
```diff
@@ -0,0 +1,508 @@
...
+
+        await uploadFirmware(
+            reconnectedDevice.getCommands().typedCall.bind(reconnectedDevice.getCommands()),
+            postMessage,
+            reconnectedDevice,
+            { payload: shouldStripFwHeaders(device.features) ? stripped : binary },
+        );
+
+        await reconnectedDevice.release();
+    }
```
Comment (marekrjpolak) [inline packages/connect/src/core/onCallFirmwareUpdate.ts]: This `else` branch is suspiciously similar (apart from what's sent as a fw binary) to the beginning of its `if` branch. Could it be unified like this? `if (cond) { A; B; } else { A; }` -> `A; if (cond) { B; }`

File: packages/connect/src/core/onCallFirmwareUpdate.ts (hunk 23 above)
Comment (mroz22) [reply packages/connect/src/core/onCallFirmwareUpdate.ts]: 47aac5b827b58cce74c71409080342f7fd26323e

File: packages/connect/src/api/changeLanguage.ts (hunk 20 above)
Comment (mroz22) [reply packages/connect/src/api/changeLanguage.ts]: b71f715faa69236afc5cccc8db12a375c2b5ac06

File: packages/connect/src/core/onCallFirmwareUpdate.ts [hunk 25]
```diff
@@ -0,0 +1,484 @@
...
+    device: Device,
+    params: Params,
+    log: Log,
+    postMessage: PostMessage,
+    intermediaryVersion?: IntermediaryVersion,
+) => {
+    if (!device.firmwareRelease) {
+        throw ERRORS.TypedError('Runtime', 'device.firmwareRelease is not set');
+    }
+    const btcOnly = params.btcOnly || device.firmwareType === 'bitcoin-only';
```
Comment (komret) [inline packages/connect/src/core/onCallFirmwareUpdate.ts]:
```suggestion
    const btcOnly = params.btcOnly || (params.btcOnly === undefined && device.firmwareType === 'bitcoin-only');
```

**Review by komret — CHANGES_REQUESTED** [review]

File: packages/connect/src/core/onCallFirmwareUpdate.ts (hunk 25 above)
Comment (komret) [reply packages/connect/src/core/onCallFirmwareUpdate.ts]: This way, you can't switch from bitcoin-only to regular.

**Comment by komret** [comment]
@peter-sanderson Please check the Suite part.

File: packages/connect/src/core/onCallFirmwareUpdate.ts (hunk 25 above)
Comment (mroz22) [reply packages/connect/src/core/onCallFirmwareUpdate.ts]: thanks. makes sense

File: packages/suite-web/e2e/tests/onboarding/firmware-update.test.ts [hunk 26]
```diff
@@ -63,7 +63,7 @@ describe.skip('fw update from empty device bootloader 2.0.3 to firmware 2.5.1',
         cy.prefixedVisit('/');
     });
 
-    it('firmware update error', () => {
+    it.skip('firmware update error', () => {
```
Comment (peter-sanderson) [inline packages/suite-web/e2e/tests/onboarding/firmware-update.test.ts:66]: why skip? i would rather have it fixed or removed is test is no longer valid

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx (hunk 15 above)
Comment (peter-sanderson) [reply packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx:149]: Maybe at least todo to move it to connect

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx [hunk 27]
```diff
@@ -241,69 +161,95 @@ const RebootDeviceGraphics = ({
...
+export const ReconnectDevicePrompt = ({ onClose, onSuccess }: ReconnectDevicePromptProps) => {
+    const { showManualReconnectPrompt, isWebUSB, status, uiEvent } = useFirmware();
     const { device } = useDevice();
-    const { isWebUSB } = useFirmware();
-    const { rebootPhase, rebootMethod } = useRebootRequest(device, requestedMode);
 
-    const isRebootAutomatic = rebootMethod === 'automatic';
-    const isAnimationVisible = requestedMode === 'bootloader' && rebootPhase !== 'done';
+    const isManualRebootRequired =
+        //Automatic reboot not supported:
```
Comment (peter-sanderson) [inline packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]:
```suggestion
        // Automatic reboot not supported:
```

File: packages/connect/src/core/onCallFirmwareUpdate.ts (hunk 25 above)
Comment (komret) [reply packages/connect/src/core/onCallFirmwareUpdate.ts]: 8d7bd1d680355a9b7d6219df7fdcb1273e286acd

File: packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx (hunk 27 above)
Comment (komret) [reply packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx]: cc197f7a3fc2a255a84481062916c5cd6426531d

File: packages/suite-web/e2e/tests/onboarding/firmware-update.test.ts (hunk 26 above)
Comment (komret) [reply packages/suite-web/e2e/tests/onboarding/firmware-update.test.ts:66]: We agreed with @mroz22 to skip it so that QA can fix it later :) The problem with this test is that it mocks something and the mock stopped working and I don't know how to fix it :(

File: packages/suite/src/views/firmware/FirmwareModal.tsx [hunk 28]
```diff
@@ -0,0 +1,154 @@
...
+            case 'done':
+                return (
+                    <FirmwareInstallation
+                        standaloneFwUpdate
+                        onSuccess={onClose}
+                        customFirmware={isCustom}
+                    />
+                );
+            default:
+                throw new Error(`state "${status}" is not handled here`);
```
Comment (peter-sanderson) [inline packages/suite/src/views/firmware/FirmwareModal.tsx]: can we do a Type mapping instead of throw?

File: packages/suite/src/hooks/suite/useFirmware.ts [hunk 29]
```diff
@@ -1,42 +1,127 @@
...
+
+    const getUpdateStatus = () => {
+        if (firmware.status === 'done') {
+            return {
+                operation: translationString('TR_FIRMWARE_STATUS_INSTALLATION_COMPLETED'),
+                progress: 100,
+            };
+        }
+        if (firmware.uiEvent?.type === UI.FIRMWARE_PROGRESS) {
+            switch (firmware.uiEvent.payload.operation) {
```
Comment (peter-sanderson) [inline packages/suite/src/hooks/suite/useFirmware.ts:71]: map instead of switch-case

**Review by peter-sanderson — APPROVED** [review]

**Review by komret — APPROVED** [review]

File: packages/suite/src/views/firmware/FirmwareModal.tsx (hunk 28 above)
Comment (komret) [reply packages/suite/src/views/firmware/FirmwareModal.tsx]: 676cd590775d9b45bb176e660e8673ad80750ed4

**Comment by STew790** [comment]
More info can be found here https://www.notion.so/satoshilabs/Interactionless-fw-update-d2c4c0f5382f479a8b0ba81932f423e8
(Not yet finished)
