### PR TITLE
Fix/21259 custom backend url

### LINKED ISSUE #21259: Custom backend url is not changing on change of network
https://github.com/user-attachments/assets/5f44ffc2-2021-45dd-9213-5c1b261b9792

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

- refactor: Add new `BackendUrls` component to reduce the render method size and complexity of the `AdvancedCoinSettingsModal`
- **fix: Update `backend.url` on `symbol` change**
- Based on #22087 

## Related Issue

Resolve #21259

## Screenshots:

https://github.com/user-attachments/assets/662ed9ab-5953-4208-9e7f-c74775655174

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/21259-custom-backend-url&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/21259-custom-backend-url&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/21259-custom-backend-url&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/settings/backends/useBackendsForm.ts [hunk 1]
```diff
@@ -103,8 +103,15 @@ const getStoredState = (
...
     const dispatch = useDispatch();
-    const initial = getStoredState(symbol, backends.selected, backends.urls);
-    const [currentValues, setCurrentValues] = useState(initial);
+    const [currentValues, setCurrentValues] = useState(() =>
+        getStoredState(symbol, backends.selected, backends.urls),
+    );
+
+    useEffect(() => {
+        setCurrentValues(getStoredState(symbol, backends.selected, backends.urls));
+        // Only update when symbol changes
```
Comment (matusbalascak) [inline packages/suite/src/hooks/settings/backends/useBackendsForm.ts]: I believe this comment is not necessary, it is clear it updates only when `symbol` changes when looking at the dependencies array.

Comment (cermakjiri) [reply packages/suite/src/hooks/settings/backends/useBackendsForm.ts]: I meant to point out that I am ignoring some deps. intentionally. But yeah, you're right.

**Review by TomasBoda — APPROVED** [review]
LGTM

Btw after merging the initial target branch into `develop`, its commit still resides in this PR: a26eafe46ee977068b42d868f2453c62633e2ad3 even though it has been merged an is in `develop`: 71123d10c2720b6e36a02ac74ff3d3fb0f90299d. Please rebase

**Review by matusbalascak — APPROVED** [review]
LGTM ✅
