### PR TITLE
fix(suite): cardano staking reward card

### LINKED ISSUE #22885: Cardano staking - APY shows NaN on reward card
**Describe the bug**
Cardano staking APY reward card displays "NaN" instead of the expected ADA value. The card reads: "Stake your balance and earn ~NaN ADA yearly at the current APY." 

**Screenshots**
Cardano staking APY showing NaN

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

Fixed an issue where the Cardano reward card displayed the wrong reward amount. 
Changed reward calculation for empty staking card. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22885

## Screenshots:
image
image

### CODE REVIEW

File: suite-common/staking/src/utils/staking.ts [hunk 1]
```diff
@@ -16,8 +16,8 @@ export const calculateGains = (amount: string, apy: number, days: number) => {
     return new BigNumber(rewards).toFixed(5, 1);
 };
 
-export const getNetworkAdjustedStakingBalance = (amount: string, account: Account) => {
-    if (account.networkType === 'cardano')
+export const getNetworkAdjustedStakingBalance = (amount: string, account?: Account) => {
+    if (account?.networkType === 'cardano')
         return new BigNumber(amount).minus(CARDANO_STAKING_REGISTRATION_DEPOSIT).toString();
```
Comment (tomasklim) [inline suite-common/staking/src/utils/staking.ts]: Can it get under zero? 😀

Comment (tomasklim) [reply suite-common/staking/src/utils/staking.ts]: Screenshot 2025-11-05 at 13 31 49
Screenshot 2025-11-05 at 13 31 54

Comment (tomasklim) [reply suite-common/staking/src/utils/staking.ts]: just fix the condition so that `TR_STAKING_BANNER_DETAIL_TEXT_EMPTY` is used when it is less or equal to 0

Comment (dev-pvl) [reply suite-common/staking/src/utils/staking.ts]: fixed and rebased

**Review by tomasklim — APPROVED** [review]
