### PR TITLE
Fix Suite Sync banner for missing keys when enabling Suite Sync with disconnected trezor

### LINKED ISSUE #26724: Suite Sync banner not visible on fresh wallet until page reload or wallet switch
**Describe the bug**
When Suite Sync is enabled on a fresh Suite and the device is disconnected, the Suite Sync banner should be visible — including on a fresh (newly created) wallet. However, the banner does not appear until the user performs an action such as reloading Suite or switching to another wallet and back.

Related to https://github.com/trezor/trezor-suite/issues/26651

**Steps to reproduce:**
1. Have fresh Suite
1. Connect seeded device
1. Enable Suite Sync
1. Observe that the Suite Sync banner is not displayed

**Info:**
 - Suite version: desktop 26.4.1 (5122cf53ee533a2e4110df53993a97b3a30a9094)
 - Browser: Trezor Suite 26.4.1
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3W1 2.11.0 universal (revision 725c0c01879329900f08fc453d8fd0fcb4d86090)
 - Transport: BluetoothTransport, BridgeTransport 3.2.1

**Expected result:**
The Suite Sync banner should be visible immediately when the device is disconnected and Suite Sync is enabled

### PR DESCRIPTION
**Pull request by matejkriz**
## Description
Recommended to review by commit.

We stopped initiating Suite Sync when the device is disconnected in d34f1b9. However, this introduced a bug where no error is triggered until the user re-selects the device, delaying the appearance of the error banner.

If there was any Suite Sync Error, SuiteSyncBanner was active even after disabling Suite Sync in settings, only rendered as null thanks to inner condition.

The frequent logs mentioning setSuiteSyncError were confusing, forcing developers to check the payload.

## Notes for QA

Focus banners when enabling Suite Sync with a disconnected/connected device.

## Related Issue

Resolve #26724

## 🤖 LLM Test Recommendations

**Summary:** The changes are confined to the suite-sync module (createTurnOnSuiteSync, suiteSyncSlice, and createEnsureWalletSuiteSyncOnWithErrorHandler), which manages Suite Sync labeling functionality. While these files are transitively imported by 121 tests, the actual impact is narrowly scoped to Suite Sync and metadata/labeling flows. The highest risk is in the Suite Sync E2E tests that directly exercise sync enablement, label CRUD, multi-wallet sync, and legacy-to-sync migration. A few legacy metadata tests are included at medium priority since they share labeling infrastructure that could be affected by state management changes in the sync slice.

<details><summary><b>Changed files (3)</b></summary>

- `suite-common/suite-sync/src/createTurnOnSuiteSync.ts`
- `suite-common/suite-sync/src/storage/createEnsureWalletSuiteSyncOnWithErrorHandler.ts`
- `suite-common/suite-sync/src/suiteSyncSlice.ts`

</details>

**Recommended tests (7)**

<details><summary>🔴 <b>High priority (5)</b></summary>

- `suite/e2e/tests/metadata/legacy-label-to-suiteSync.test.ts` — This test directly exercises the Suite Sync migration flow, which depends on createTurnOnSuiteSync and suiteSyncSlice. It seeds Evolu relay data and verifies label migration from Dropbox to Suite Sync, directly exercising the sync enablement path that the changed files implement.
- `suite/e2e/tests/metadata/suite-sync/create-new-labels.test.ts` — This test creates new labels via Suite Sync (account, wallet, address, output) and verifies they sync to the Evolu relay. It directly exercises the Suite Sync enablement flow via metadataPage.enableSuiteSync(), which relies on createTurnOnSuiteSync and the suiteSyncSlice state management.
- `suite/e2e/tests/metadata/suite-sync/multi-wallet.test.ts` — This test exercises Suite Sync across multiple wallets including passphrase wallets, testing the sync banner, declining/accepting Suite Sync, and verifying per-wallet isolation. It directly tests createTurnOnSuiteSync for multiple wallet contexts and the error handling in createEnsureWalletSuiteSyncOnWithErrorHandler.
- `suite/e2e/tests/metadata/suite-sync/remove-labels.test.ts` — This test enables Suite Sync, verifies labels are pulled from the relay, then removes them and confirms null values sync back. It exercises the full Suite Sync lifecycle including enablement (createTurnOnSuiteSync) and the wallet sync error handler.
- `suite/e2e/tests/metadata/suite-sync/sync-from-relay.test.ts` — This test verifies Suite Sync pulls labels from the Evolu relay server and displays them correctly. It tests the sync setup flow including device confirmation, directly exercising createTurnOnSuiteSync and the suiteSyncSlice for state management during initialization.

</details>

<details><summary>🟡 <b>Medium priority (2)</b></summary>

- `suite/e2e/tests/metadata/legacy/metadata-lifecycle.test.ts` — This test exercises the full metadata labeling lifecycle including enabling/disabling labeling, switching wallets, and re-enabling after device ejection. While it focuses on legacy labeling, the suiteSyncSlice may be involved in the labeling state management infrastructure that determines whether legacy or Suite Sync is active.
- `suite/e2e/tests/metadata/legacy/remembered-device.test.ts` — This test exercises metadata provider connect/disconnect and re-enable flows on remembered devices. The suiteSyncSlice and createEnsureWalletSuiteSyncOnWithErrorHandler may be involved in the metadata state management when toggling providers and handling device memory, making it relevant to verify no regressions in the metadata enable/disable paths.

</details>

_Updated: 2026-04-21T15:48:10.678Z_

## 🔍 Currents Test Results

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/suite-sync-banner-without-trezor&lookback=7)

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/suite-sync-banner-without-trezor&lookback=7)

## 🌐 Preview deployments

🌐 **Suite Web preview:** [https://dev.suite.sldev.cz/suite-web/fix/suite-sync-banner-without-trezor/web/](https://dev.suite.sldev.cz/suite-web/fix/suite-sync-banner-without-trezor/web/)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (web) — 29 test(s)</summary>

| Test | Type |
|------|------|
| Trading - Swap history > View swap order history details | 🤖 auto |
| Trading - Buy Negative scenarios > Buy form handles input limits and empty quotes | 🤖 auto |
| Trading - Buy Ethereum > Enable Ethereum on account by buying it | 🤖 auto |
| Trading - Buy Solana > Buy Solana Jupiter token - amount specified in crypto | 🤖 auto |
| Trading - Swap token to disabled network asset > Show provider info for disabled network asset XLM | 🤖 auto |
| Trading - Swap tokens > Swap Solana tokens | 🤖 auto |
| Send - Solana > Send max | 🤖 auto |
| Trading - Swap coins > Swap Solana to Bitcoin | 🤖 auto |
| Trading - Sell Solana > Sell Solana | 🤖 auto |
| Trading - Sell Solana > Sell Solana for compared offer | 🤖 auto |
| Trading - Swap coin to token > Swap Solana to USDC | 🤖 auto |
| Trading - Swap token to coin > Swap Solana Tether token to Bitcoin | 🤖 auto |
| sol staking > first stake on SOL account | 🤖 auto |
| sol staking > display stake rewards on SOL staking account | 🤖 auto |
| sol staking > stake more on SOL account | 🤖 auto |
| sol staking > unstake and claim on SOL account | 🤖 auto |
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Passphrase with cardano > verify cardano address behind passphrase | 🤖 auto |
| Discovery > go to wallet settings page, activate all coins and see that there is equal number of records on dashboard | 🤖 auto |
| Account types suite > Add-account-types-non-BTC-coins | 🤖 auto |
| Public Keys > Check ada XPUB | 🤖 auto |
| Cardano > Basic cardano walkthrough | 🤖 auto |
| Export transactions > Go to account and try to export all possible variants (pdf, csv, json) | 🤖 auto |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Trading - Sell inputs,Sell form % inputs and limits" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine CANARY test: "Trading - Sell BTC" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-04-22T10:26:07.280Z • 29 test(s) total_

### CODE REVIEW

**Review by peter-sanderson — APPROVED** [review]
codewise lgtm, not tested tho

File: suite-common/suite-sync/src/createTurnOnSuiteSync.ts [hunk 1]
```diff
@@ -43,6 +46,13 @@ export const createTurnOnSuiteSync =
             if (!result.success) {
                 return result;
             }
+        } else {
+            deps.dispatch(
+                setSuiteSyncError({
```
Comment (peter-sanderson) [inline suite-common/suite-sync/src/createTurnOnSuiteSync.ts:51]: Maybe, there is a change of behavior that is not deflect in the test => so there is no test case for this situation, I would consider adding it.

Comment (matejkriz) [reply suite-common/suite-sync/src/createTurnOnSuiteSync.ts:51]: good point, added e60a67ddae
