### PR TITLE
fix: hidden wallet number

### LINKED ISSUE #3133: Hidden wallet number is missing
**Info:**
 - Suite version: web 21.1.0 (ff99ab56c3837e41ad0c243d242dceea22bedf6e)
 - Browser: Chrome
 - OS: MacIntel
 - Screen: 1792x1120
 - Device: model T 2.3.4 regular

Screenshot 2020-12-04 at 19 29 49

### PR DESCRIPTION
**Pull request by mroz22**
this should fix #3133 
@szymonlesisz attention needed.

### CODE REVIEW

File: packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx [hunk 1]
```diff
@@ -123,7 +123,7 @@ const DeviceItem = (props: Props) => {
     const instancesWithState = props.instances.filter(i => i.state);
 
     const selectDeviceInstance = async (instance: Props['device']) => {
-        await props.selectDevice(instance);
+        props.selectDevice(instance);
```
Comment (mroz22) [inline packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx:126]: changes in this files are unrelated, just found some uneeded awaits and removed them

**Review by tomexx — APPROVED** [review]

**Review by szymonlesisz — APPROVED** [review]
