### PR TITLE
XRP: fix status in failed transactions with missing destination tag

### LINKED ISSUE #16281: XRP tx incorrectly mark as successful even though it failed
**How to reproduce**

1. Send money to address (`rw2ciyaNshpHe7bCHo4bRWq6pqqynnWKQg`) which requires `destinationTag` but do not specify this `destinationTag` in send form
2. Tx fails according to notification
3. Check explorer https://xrpscan.com/tx/BE4D883282BA4A16121117F382E916504D24AC90530F5575032E8F0E6A63E6C5 it is failed
4. Check Suite tx history, it is ok but balance has not changed

**How to resolve**
Problem is probably in blockchain-link. I think we incorrectly mark `failed` tx as `sent`

**Screenshots**

Image
Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by izmy**
## Description

Suite incorrectly displayed success status in XRP transactions when destination tag was missing.

I also changed the color for the Confirmed status in transaction detail, because it could have been a confusing UX.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/16281

## Screenshots:

image

image

### CODE REVIEW

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/BasicTxDetails.tsx [hunk 1]
```diff
@@ -94,7 +94,7 @@ export const BasicTxDetails = ({
                 <Row gap={spacings.xxs} margin={{ left: 'auto' }}>
                     {isConfirmed ? (
                         <InfoSegments typographyStyle="hint" variant="tertiary">
-                            <Text typographyStyle="callout" variant="primary">
+                            <Text typographyStyle="callout" variant="default">
```
Comment (tomasklim) [inline packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/BasicTxDetails.tsx]: I would omit this from this PR and let's discuss and find a solution to change it to a state that makes sense

File: packages/blockchain-link/src/workers/ripple/index.ts [hunk 2]
```diff
@@ -181,7 +181,7 @@ const getAccountInfo = async (request: Request<MessageTypes.GetAccountInfo>) =>
 const getTransaction = async ({ connect, payload }: Request<MessageTypes.GetTransaction>) => {
     const api = await connect();
     const rawtx = await api.request('tx', { transaction: payload, binary: false });
```
Comment (tomasklim) [inline packages/blockchain-link/src/workers/ripple/index.ts]: nit: rawTx

File: packages/blockchain-link-utils/src/ripple.ts [hunk 3]
```diff
@@ -15,13 +15,21 @@ export const transformServerInfo = (payload: any) => ({
...
-export const transformTransaction = (tx: any, descriptor?: string): Transaction => {
+export const transformTransaction = (meta: any, tx: any, descriptor?: string): Transaction => {
     const blockTime =
         typeof tx.date === 'number' && tx.date > 0 ? tx.date + BLOCKTIME_OFFSET : tx.date;
-    const type =
-        tx.TransactionType !== 'Payment' || !descriptor
-            ? 'unknown'
-            : (tx.Account === descriptor && 'sent') || 'recv';
+
+    let type: Transaction['type'];
```
Comment (tomasklim) [inline packages/blockchain-link-utils/src/ripple.ts]: nit:
```suggestion
    let txType: Transaction['type'];
```

**Review by tomasklim — CHANGES_REQUESTED** [review]
We should probably hide amount change. However, the problem is that ripple does not show fee so it would look weird. Let's discuss

Screenshot 2025-01-23 at 8 53 36

**Review by tomasklim — CHANGES_REQUESTED** [review]
Fix and add please new unit tests 🙏

File: packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/BasicTxDetails.tsx (hunk 1 above)
Comment (izmy) [reply packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/BasicTxDetails.tsx]: Ok, I created an issue -> https://github.com/trezor/trezor-suite/issues/16567

**Comment by izmy** [comment]
> Fix and add please new unit tests 🙏

done

**Review by tomasklim — APPROVED** [review]
