### PR TITLE
fix(connect): webextension save sessions

### LINKED ISSUE #11784: Maintain connection to session in @trezor/webextension
Maintain connection to session in @trezor/webextension so that users don't need to type passphrase every time connect-popup is called.

### PR DESCRIPTION
**Pull request by martykan**
## Description

Rabby recently switched to the new webextension architecture, but it's an issue that we don't currently remember passwords in the core in popup modes. 

This change adds the ability to save the device's internal state to storage along with rememberedDevice. 
The state's validity is limited to 15 minutes. 

## Related Issue

Resolve #11784

### CODE REVIEW

File: packages/connect/src/core/index.ts [hunk 1]
```diff
@@ -482,6 +488,37 @@ const onCall = async (message: IFrameCallMessage) => {
...
+            // Persist internal state only in case of core in popup
+            // Currently also only for webextension until we asses security implications
+            if (useCoreInPopup && env === 'webextension') {
+                return {
+                    ...store,
+                    preferredDevice: store.preferredDevice
+                        ? {
+                              ...store.preferredDevice,
+                              internalState: state,
+                              internalStateExpiration: new Date(Date.now() + 1000 * 60 * 15), // 15 minutes
```
Comment (karliatto) [inline packages/connect/src/core/index.ts]: This is using Date object, I would rather use milliseconds like  below, since that is easier serializable and less potential issues and easier comparison with other dates.
```suggestion
                              internalStateExpiration: new Date(Date.now() + 1000 * 60 * 15).getTime(), // 15 minutes
```

File: packages/connect/src/core/index.ts [hunk 2]
```diff
@@ -482,6 +488,37 @@ const onCall = async (message: IFrameCallMessage) => {
...
+            return store;
+        }, origin);
+    });
+
+    if (!device.getInternalState() && useCoreInPopup && env === 'webextension') {
+        // Restore internal state if available
+        const { preferredDevice } = storage.loadForOrigin(origin) || {};
+        if (
+            preferredDevice?.internalState &&
+            new Date(preferredDevice.internalStateExpiration!) > new Date()
```
Comment (karliatto) [inline packages/connect/src/core/index.ts]: If we use `.getTime()` then here we just need to compare like:
```suggestion
            preferredDevice.internalStateExpiration > new Date().getTime()
```

**Review by karliatto — COMMENTED** [review]
Looks good and works as expected :rocket: 

I added some comments regarding Dates comparisons.

**Review by karliatto — APPROVED** [review]
LGTM
