### PR TITLE
fix: unify disconencted state in the onboarding, ... kinda

### LINKED ISSUE #21885: Blank screen when the device is disconnected
**Describe the bug**
When I disconnect device during onboarding I get into this blank screen.

Image

This happened when I was on screen to create secure connection, but probably it can happen in more places.

### PR DESCRIPTION
**Pull request by peter-sanderson**
Resolves: https://github.com/trezor/trezor-suite/issues/21885

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix-onboaridng-disconencted-state&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix-onboaridng-disconencted-state&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix-onboaridng-disconencted-state&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/onboarding/steps/FirmwareStep.tsx [hunk 1]
```diff
@@ -131,12 +132,12 @@ export const FirmwareStep = () => {
...
         // Most users won't see this as they should come here with a connected device.
         // This is just for people who want to shoot themselves in the foot and disconnect the device before proceeding with fw update flow
-        return <PrerequisitesGuide />;
+        return <DeviceDisconnectedStep />;
     }
 
     if (thpStep !== null) {
         if (device === undefined) {
-            return null;
+            return <DeviceDisconnectedStep />;
```
Comment (peter-sanderson) [inline packages/suite/src/views/onboarding/steps/FirmwareStep.tsx:140]: It would be great to handle this on top level (ideally in the `UnexpectedState` component that wraps whole Onboarding).

However, we are disconnecting (restarting) the device during firmware installation => therefore we would need some special handling there (extra condition for this in the `UnexpectedState`). I think that change would need a bit more time and care and testing. So .. maybe later, or never - as I expect some Onboarding rework soon.

**Review by komret — APPROVED** [review]
