### PR TITLE
chore: fix some typos

### LINKED ISSUE #2983: Typo on one of the "Check Backup" screen
User's feedback

There's a typo on the "Backup seed successfully checked!" step 

The word "goint" instead of "going" in the last line on the screenshot:
Screenshot 2020-11-12 at 15 42 40

### PR DESCRIPTION
**Pull request by mroz22**
this fixes #2983 and few other typos I found along the way

### CODE REVIEW

**Review by prusnak — APPROVED** [review]

File: packages/suite/src/support/messages.ts [hunk 1]
```diff
@@ -1193,7 +1193,7 @@ const definedMessages = defineMessages({
     },
     TR_DEVICE_IS_USED_IN_OTHER_WINDOW_TEXT: {
         defaultMessage:
-            'This is a big no no. Please dont use device in other window. Close all other windows or tabs that might be using your Trezor device.',
+            "This is a big no no. Please don't use device in other window. Close all other windows or tabs that might be using your Trezor device.",
```
Comment (slowbackspace) [inline packages/suite/src/support/messages.ts]: this is already updated in crowdin, if you are gonna edit the default message use one from crowdin otherwise you are going to invalidate proper copy (meaning on the next sync this default message would used instead of proper copy)

**Review by slowbackspace — CHANGES_REQUESTED** [review]

File: packages/suite/src/support/messages.ts [hunk 2]
```diff
@@ -2989,7 +2989,7 @@ const definedMessages = defineMessages({
     TR_CHECK_RECOVERY_SEED_DESC_T1: {
         id: 'TR_CHECK_RECOVERY_SEED_DESC_T1',
         defaultMessage:
-            'Your wallet backup, the recovery seed, is entered on your computer (host) and your device shows which word to type. You will also be asked to enter words not in your seed, that is a security meassure to ensure nobody can read what key is being pressed.',
+            'Your wallet backup, the recovery seed, is entered on your computer (host) and your device shows which word to type. You will also be asked to enter words not in your seed, that is a security measure to ensure nobody can read what key is being pressed.',
```
Comment (slowbackspace) [inline packages/suite/src/support/messages.ts]: same as above

File: packages/suite/src/support/messages.ts [hunk 3]
```diff
@@ -3038,7 +3038,7 @@ const definedMessages = defineMessages({
     TR_SEED_CHECK_SUCCESS_DESC: {
         id: 'TR_SEED_CHECK_SUCCESS_DESC',
         defaultMessage:
-            'Your seed is valid and has just been successfully checked. Please take great care of it and/or hide it back where you are goint to find it.',
+            'Your seed is valid and has just been successfully checked. Please take great care of it and/or hide it back where you are going to find it.',
```
Comment (slowbackspace) [inline packages/suite/src/support/messages.ts:3041]: this one is fine as there is no copy in crowdin, this default message is really used in the app

File: packages/suite/src/support/messages.ts [hunk 4]
```diff
@@ -3983,7 +3983,7 @@ const definedMessages = defineMessages({
     },
     TR_LANDING_DESC: {
         id: 'TR_LANDING_DESC',
-        defaultMessage: 'For testing purpouses only. Please keep in mind this is a beta version.',
+        defaultMessage: 'For testing purposes only. Please keep in mind this is a beta version.',
```
Comment (slowbackspace) [inline packages/suite/src/support/messages.ts:3986]: also fine as it seems no copy is done via crowdin

**Comment by mroz22** [comment]
updated those already existing to the crowdin values

**Review by slowbackspace — APPROVED** [review]
