### PR TITLE
Fix/10449 receive address mismatch

### LINKED ISSUE #10449: Cardano address mismatch
Address mismatch on cardano. 

**Steps to reproduce:**

1. Connect device with all-seed and wait for discovery to finish (or load all cardano accounts)
2. Generate receive address on `Cardano #3` account
3. Confirm and go back
4. Generate new address on the same account and you will get address mismatch

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

- During batched discovery, wrong index was associated with an account and  later used in enhanceAddresses util to create account patch. It led to duplicated paths for different addresses.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/10449

## Screenshots:
image

### CODE REVIEW

File: suite-native/discovery/src/discoveryThunks.ts [hunk 1]
```diff
@@ -181,11 +181,9 @@ const discoverNetworkBatchThunk = createThunk(
 
         const chunkBundle: Array<DiscoveryItem> = [];
 
-        A.makeWithIndex(batchSize, index => {
-            const accountPath = network.bip43Path.replace(
-                'i',
-                (lastDiscoveredAccountIndex + index).toString(),
-            );
+        A.makeWithIndex(batchSize, batchIndex => {
+            const index = lastDiscoveredAccountIndex + batchIndex;
```
Comment (matejkriz) [inline suite-native/discovery/src/discoveryThunks.ts:185]: this index is used also on line L#198 - the fix is that chunkBundle has to use global index, not batchIndex

**Review by juriczech — APPROVED** [review]

**Review by PeKne — APPROVED** [review]
