### PR TITLE
fix(suite-native): hide send for portfolio tracker

### LINKED ISSUE #16484: Send from dashboard
As a fast-follow for send, we need to design a way to handle "Send" & "Receive" as global action.
This issue is just for Send, receive was done in https://github.com/trezor/trezor-suite/issues/16204 

AC:
- User is able to trigger send  from homepage
- User is able to choose acount for sending
- User sees only accounts with positive balances for Send

Designs: https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Small-Things-%5BMOB%5D?node-id=2067-24263&t=kXK56b5XE1bxT8tp-0

Followup issue for analytics: https://github.com/trezor/trezor-suite/issues/17070

### PR DESCRIPTION
**Pull request by PeKne**
## Description
- hides global send button for portfolio tracker device

## Related Issue

Resolve #16484

## Screenshots:
Screenshot 2025-02-26 at 12 53 43 PM

### CODE REVIEW

File: suite-native/accounts/src/selectors.ts [hunk 1]
```diff
@@ -223,6 +224,10 @@ export const selectFreshAccountAddress = (
 };
 
 export const selectHasDeviceAnySendAvailableAccount = createMemoizedSelector(
-    [selectVisibleDeviceAccounts],
-    accounts => pipe(accounts, filterSendAvailableAccounts, A.isNotEmpty),
+    [selectIsPortfolioTrackerDevice, selectVisibleDeviceAccounts],
+    (isPortfolioTrackerDevice, accounts) => {
+        if (isPortfolioTrackerDevice) return false;
```
Comment (vytick) [inline suite-native/accounts/src/selectors.ts:229]: should this be true for view only devices in case they have SendAvailableAccounts ?

Comment (PeKne) [reply suite-native/accounts/src/selectors.ts:229]: Yes, I think so. If user tries to send from view only device, he as able to fill in the send form and then if he continues, the `Connect Trezor Screen` is displayed. But I will double check, just to make sure.

EDIT: Yes, it is the way I described above. (it happens [here](https://github.com/trezor/trezor-suite/blob/5b33c28f860e0b5a07c88e18f6204655ad3ec306/suite-native/module-send/src/components/SendFeesForm.tsx#L144))

**Review by vytick — APPROVED** [review]
lgtm 🚀
