### PR TITLE
fix(suite): handle Trezor disconnect on staking dashboard

### LINKED ISSUE #19340: Missing Trezor disconnected on staking promo dashboard
**Describe the bug**

we have it here
Image

here it is missing
Image

### PR DESCRIPTION
**Pull request by dev-pvl**
## Description

- Adds Trezor disconnect handling to the staking promo dashboard.
- Update Everstake logo.
- Remove EverstakeLogo component

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/19340

## Screenshots:
image
image
image

### CODE REVIEW

File: suite-common/icons/generateIconFont.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ const usedIcons = [
     'discoverFilled',
     'eye',
     'eyeSlash',
+    'everstakeLogo',
```
Comment (tomasklim) [inline suite-common/icons/generateIconFont.ts]: please check if needed, there is `EverstakeLogo` component

If it is enough to have it once, please rather remove `EverstakeLogo` component.

File: suite-common/icons/assets/everstakeLogo.svg [hunk 2]
```diff
@@ -0,0 +1,3 @@
+<svg width="102" height="90" viewBox="0 0 102 90" fill="none" xmlns="http://www.w3.org/2000/svg">
```
Comment (tomasklim) [inline suite-common/icons/assets/everstakeLogo.svg]: Please make it be black by default. So that you can see the component preview in filesystem
Screenshot 2025-06-17 at 13 07 49

**Review by tomasklim — COMMENTED** [review]
As we discussed over slack, please move `EverstakeLogo` component into icons as well

File: suite-common/icons/generateIconFont.ts (hunk 1 above)
Comment (dev-pvl) [reply suite-common/icons/generateIconFont.ts]: removed component and added svg logo, https://github.com/trezor/trezor-suite/pull/19585/commits/436247d2f9c37dc43c725232efc73e996bbcde96

File: suite-common/icons/assets/everstakeLogo.svg (hunk 2 above)
Comment (dev-pvl) [reply suite-common/icons/assets/everstakeLogo.svg]: done, https://github.com/trezor/trezor-suite/pull/19585/commits/436247d2f9c37dc43c725232efc73e996bbcde96

File: suite-common/icons/src/icons.ts [hunk 3]
```diff
@@ -959,6 +959,8 @@ export const icons = {
     escalatorDownFilled: require('../assets/escalatorDownFilled.svg'),
     escalatorUp: require('../assets/escalatorUp.svg'),
     escalatorUpFilled: require('../assets/escalatorUpFilled.svg'),
+    everstakeLogo: require('../assets/everstakeLogo.svg'),
+    everstakeLogoAlt: require('../assets/everstakeLogoAlt.svg'),
```
Comment (tomasklim) [inline suite-common/icons/src/icons.ts]: everstakeLogoText?

**Review by tomasklim — COMMENTED** [review]
why is the mobile font deleted?

File: suite-common/icons/generateIconFont.ts (hunk 1 above)
Comment (tomasklim) [inline suite-common/icons/generateIconFont.ts]: does it need to be here / is it used?

File: suite-common/icons/src/icons.ts (hunk 3 above)
Comment (dev-pvl) [reply suite-common/icons/src/icons.ts]: renamed https://github.com/trezor/trezor-suite/pull/19585/commits/0755e34d1ae1171e5be748218877a8d6aea28693

File: suite-common/icons/generateIconFont.ts (hunk 1 above)
Comment (dev-pvl) [reply suite-common/icons/generateIconFont.ts]: It shouldn't be here. Fixed  https://github.com/trezor/trezor-suite/pull/19585/commits/0755e34d1ae1171e5be748218877a8d6aea28693

**Review by tomasklim — APPROVED** [review]
Looks good, please squash
