### PR TITLE
Fix/device selection

### LINKED ISSUE #9834: Always select newly connected device as selected
I device is connected, app should select it automatically and forward you to dashboard for that device.

### PR DESCRIPTION
**Pull request by juriczech**
## Related Issue

Resolve #9834

### CODE REVIEW

File: suite-native/device/src/middlewares/deviceMiddleware.ts [hunk 1]
```diff
@@ -63,10 +57,14 @@ export const prepareDeviceMiddleware = createMiddlewareWithExtraDeps(
             dispatch(handleDeviceDisconnect(action.payload));
         }
 
+        const isConnectEnabled = selectIsDeviceConnectFeatureFlagEnabled(getState());
+
         switch (action.type) {
             case DEVICE.CONNECT:
             case DEVICE.CONNECT_UNACQUIRED:
-                dispatch(handleDeviceConnect(action.payload));
+                if (isConnectEnabled) {
```
Comment (Nodonisko) [inline suite-native/device/src/middlewares/deviceMiddleware.ts]: I don't like name `isConnectEnabled` because first thing that popped up in my mind was TrezorConnect and if it's enabled.

File: suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx [hunk 2]
```diff
@@ -78,7 +80,7 @@ const FeatureReceiveScreenNoDevice = () => {
 };
 
 export const FeatureReceiveScreen = () => {
-    const { isUsbDeviceConnectFeatureEnabled } = useIsUsbDeviceConnectFeatureEnabled();
+    const isUsbDeviceConnectFeatureEnabled = useSelector(selectIsDeviceConnectFeatureFlagEnabled);
```
Comment (Nodonisko) [inline suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx]: Why did you deleted our custom hook? One of the key points why we had that hooks to avoid these kind of refactoring everywhere instead you should just use this selector once in the hook and keep it. Please bring it back.

**Review by Nodonisko — CHANGES_REQUESTED** [review]

File: suite-native/app/ios/Podfile.lock [hunk 3]
```diff
@@ -125,9 +125,9 @@ PODS:
   - lottie-react-native (5.1.5):
     - lottie-ios (~> 3.4.0)
     - React-Core
-  - MMKV (1.2.16):
-    - MMKVCore (~> 1.2.16)
-  - MMKVCore (1.2.16)
+  - MMKV (1.3.0):
```
Comment (PeKne) [inline suite-native/app/ios/Podfile.lock:128]: Where does these upgrades come from? Is it related?

File: suite-native/device/src/middlewares/deviceMiddleware.ts (hunk 1 above)
Comment (PeKne) [inline suite-native/device/src/middlewares/deviceMiddleware.ts]: Why is this `if` necessary? Should not it happen always? IMO the fake device will never trigger `DEVICE.CONNECT`, so it will be ignored anyway in cases where is `selectIsDeviceConnectFeatureFlagEnabled` equal to false.

File: suite-native/feature-flags/src/featureFlagsSlice.ts [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+    isDeviceConnectEnabled: Platform.OS === 'android' && isDevelopOrDebugEnv(),
+};
+
+export const featureFlagsPersistedKeys: Array<keyof FeatureFlagsState> = ['isDeviceConnectEnabled'];
+
+export const featureFlagsSlice = createSlice({
+    name: 'featureFlags',
+    initialState: featureFlagsInitialState,
+    reducers: {
+        setIsDeviceConnectEnabled: (state, { payload }: PayloadAction<boolean>) => {
```
Comment (PeKne) [inline suite-native/feature-flags/src/featureFlagsSlice.ts]: In my last `slice-related` PR you asked me to use something like `toggleIsDeviceConnectEnabled`, because then you do not have to use payload at all. Now I'm curios, is this case any different? Just trying to understand how you think about it, not requesting any change here.

File: suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx]: Yes, I agree with that and left it like that but then I thought maybe I'm just being lazy and could refactor it as there is no need for this hook anymore and likely won't be as well. But never mind, I will put it back.

File: suite-native/device/src/middlewares/deviceMiddleware.ts (hunk 1 above)
Comment (juriczech) [reply suite-native/device/src/middlewares/deviceMiddleware.ts]: Mostly as a safety net. I'd rather have it here than not.

Comment (juriczech) [reply suite-native/device/src/middlewares/deviceMiddleware.ts]: https://github.com/trezor/trezor-suite/pull/9840/commits/5f26d8a42f7657d579b87b15fda7576d67d39060

File: suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx (hunk 2 above)
Comment (juriczech) [reply suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx]: https://github.com/trezor/trezor-suite/pull/9840/commits/5f26d8a42f7657d579b87b15fda7576d67d39060

File: suite-native/feature-flags/src/featureFlagsSlice.ts (hunk 4 above)
Comment (juriczech) [reply suite-native/feature-flags/src/featureFlagsSlice.ts]: No, that's good point https://github.com/trezor/trezor-suite/pull/9840/commits/5f26d8a42f7657d579b87b15fda7576d67d39060

File: suite-native/app/ios/Podfile.lock (hunk 3 above)
Comment (juriczech) [reply suite-native/app/ios/Podfile.lock:128]: Not related. Just did an update when I cleaned my build and updated in the meantime

Comment (PeKne) [reply suite-native/app/ios/Podfile.lock:128]: Ok, let's forget it now. But could we not push these changes with PRs that are not related next time? IMO the Podfile.lock should be pushed only if you introduce/update some new pod.

Comment (juriczech) [reply suite-native/app/ios/Podfile.lock:128]: I would not be too dogmatic about this. But let's discuss within team so it's decided by everyone.

**Review by PeKne — APPROVED** [review]

**Review by Nodonisko — APPROVED** [review]
