### PR TITLE
fix(suite-native): double biometrics auth

### LINKED ISSUE #22756: Stucked on biometrics screen
**Describe the bug**
It’s hard to reproduce, but from time to time someone reports getting stuck on the biometric screen, and only leaving/restarting the app helps. Clicking the button doesn’t help.

**Info:**

- Mobile Suite Version: production, 25.10
- OS: ios

**How to reproduce**
It is hard to reproduce, happens just from time to time.

**Expected behavior**
Biometrics should always trigger and allow you to authenticate and go to the app.

**Screenshots**

Image

**Additional context**
Internal reports:
https://satoshilabs.slack.com/archives/C03FL9TCURZ/p1759394470785209
https://satoshilabs.slack.com/archives/C082Q0Y6WP3/p1760606319135809?thread_ts=1760595804.590279&cid=C082Q0Y6WP3

### PR DESCRIPTION
**Pull request by juriczech**
## Description
- stop any call to biometrics authentication if it's already in progress

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/22756

## Screenshots:

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/native/double-biometrics-auth&lookback=7)

### CODE REVIEW

File: suite-native/biometrics/src/useBiometrics.tsx [hunk 1]
```diff
@@ -82,13 +83,20 @@ export const useBiometrics = () => {
...
 
-        if (result?.success) {
-            setIsUserAuthenticated(true);
-            setIsBiometricsOverlayVisible(false);
+            if (result?.success) {
+                setIsUserAuthenticated(true);
+                setIsBiometricsOverlayVisible(false);
+            }
+        } finally {
+            // Ensure flag stays disabled until we explicitly allow new auth.
```
Comment (matejkriz) [inline suite-native/biometrics/src/useBiometrics.tsx]: nitpick: I found this comment slightly confusing.

**Review by matejkriz — APPROVED** [review]
It works as expected 👍

File: suite-native/biometrics/src/useBiometrics.tsx (hunk 1 above)
Comment (juriczech) [reply suite-native/biometrics/src/useBiometrics.tsx]: Removing 👌
