### PR TITLE
fix(suite-desktop): fix BioAuthModule initialization race condition

### LINKED ISSUE #23819: Error: BioAuth module is not initialized
Sentry Issue: [TREZOR-SUITE-1C9C](https://satoshilabs.sentry.io/issues/7102447861/?referrer=github_integration)

```
Error: BioAuth module is not initialized
  File "@trezor/suite-desktop-core/./src/modules/bioAuthModule.ts", line 212, in <anonymous>
    if (!bioAuth?.initialized) throw new Error('BioAuth module is not initialized');
```

### PR DESCRIPTION
**Pull request by vojtatranta**
## Description

Fixes several problems with initialization procedure of BioAuthModule and the communication between renderer process:

- rearrange `bioAuthThunks.init` so it never sends other requests until available is confirmed
- relax the condition in `'bio-auth/is-bio-auth-available'` to make it double as a status check
- on Windows specifically, store `initPromise` and ensure that other methods don't crash if Promise is still pending
  - Awaits the initilzation of the bioAuth module when calling the first method "isAvailable"
  - note that this is a side issue – a potential problem, not the cause of errors captured by Sentry

## Notes for QA

‼️ PLS TEST ALL THE PLATFORMS
Not visible, bio auth should work the same as it does now on macOS and Windows.
Smoke test Linux – does not crash, and bio auth not visible in settings. 

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/23819

## Screenshots:

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=23819-initilaize-bioauth-not-done-validate&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=23819-initilaize-bioauth-not-done-validate&lookback=7)

### CODE REVIEW

File: packages/suite-desktop-core/src/modules/bioAuthModule.ts [hunk 1]
```diff
@@ -135,31 +135,65 @@ class BioAuthLinux extends BioAuth {
 
 class BioAuthWindows extends BioAuth {
     private winHello?: Awaited<ReturnType<typeof createWinHelloManager>>;
```
Comment (Lemonexe) [inline packages/suite-desktop-core/src/modules/bioAuthModule.ts]: nit: for consistency I'd change it to 
```suggestion
    private winHello: Awaited<ReturnType<typeof createWinHelloManager>> | null;
```

add `this.winHello = null;` to constructor and assing `null` in the `.catch()`

**Review by Lemonexe — COMMENTED** [review]
Codewise LGTM, I'll test it on windows..

**Review by Lemonexe — APPROVED** [review]
Tested on windows 11 (VM) ✔️ 
- as is, it works as expected
- I played around with 8 sec artificial delay in `createWinHelloManager()`
  - on `develop` I did not reproduce Sentry event, but it's definitely broken ([video borken](https://github.com/user-attachments/assets/f829d518-b840-4290-b6f5-fe8f9cf8d2dd))
    - when the race condition fails, it completely derails Bio Auth
  - on this branch it works much better ([video fixed](https://github.com/user-attachments/assets/1d499545-b1e9-4f78-82f4-528480d6c2e3))
  - Bio Auth waits for the delay and eventually initializes correctlly

Smoke-tested also linux AppImage ✔️ 

In the "video fixed" you can see a small problem – while waiting for Bio Auth it does not block you from using Suite. But I can see this is no worse than develop & production, so approving nevertheless 🙈 
Also, I assume it's very rare edge case to have such delay that you get to the Suite Dashboard, but eventually have WinHello up, not failed. The delay is definitely enough to cause problems with the race condition currently, but you'd need to have a lot of time to fully load Suite UI and get to Dashboard. Oh well 🤷

**Comment by Lemonexe** [comment]
@vojtatranta  ↑ thinking about it some more, I don't think the edge case is even solvable. When you start winHello process but it does not respond early, you have to assume it's broken (perhaps unavailable on Windows OS-level). Blocking Suite would be a strict security measure, which would make you reset Suite. Idk perhaps that's the right way.. Or maybe I'm overthinking it, this is only a UI measure against random access, a malicious actor can always read unencrypted files directly..

:thought_balloon:  In future if we sync Suite state via evolu, this can easily happen by transferring setting from one machine (has WinHello) to another (does not have).

**Comment by vojtatranta** [comment]
Update: @Lemonexe says that the issue raised up on Mac weirldy

File: packages/suite-desktop-core/src/modules/bioAuthModule.ts [hunk 2]
```diff
@@ -245,14 +282,20 @@ export const initBioAuthModule = ({
         ipcMain.handle('bio-auth/validate-bio-auth', (ipcEvent, params) => {
             validateIpcMessage({ ipcEvent });
 
-            if (!bioAuth?.initialized) throw new Error('BioAuth module is not initialized');
+            if (!bioAuth?.initialized) {
+                throw new Error('BioAuth module is not initialized (calling validate-bio-auth)');
+            }
```
Comment (Lemonexe) [inline packages/suite-desktop-core/src/modules/bioAuthModule.ts:287]: 📝 Note: this never could have happened, because this is called from [requestBioAuthValidationThunk](https://github.com/trezor/trezor-suite/blob/3d4711bcb4356c522ff7a095c0907e0339c1e709/packages/suite/src/actions/suite/bioAuthThunks.ts#L94) and that's called [via useBioAuthDesktopApi](https://github.com/trezor/trezor-suite/blob/e8dbc121b0b7c8829a187f62a4b93982f74da900/packages/suite/src/hooks/suite/useBioAuthDesktopApi.ts#L57-L61) in [BioAuthGuard](https://github.com/trezor/trezor-suite/blob/e8dbc121b0b7c8829a187f62a4b93982f74da900/packages/suite/src/components/suite/BioAuthGuard/BioAuthGuard.tsx#L121-L138), only when conditions are – `isBioAuthAvailable === true` ensures it's initialized

File: packages/suite-desktop-core/src/modules/bioAuthModule.ts [hunk 3]
```diff
@@ -245,14 +282,20 @@ export const initBioAuthModule = ({
...
             return bioAuth.validate(params.message ?? PROMPT_REASON);
         });
 
         ipcMain.handle('bio-auth/get-validation-status', ipcEvent => {
             validateIpcMessage({ ipcEvent });
-            if (!bioAuth?.initialized) throw new Error('BioAuth module is not initialized');
+            if (!bioAuth?.initialized) {
+                throw new Error(
+                    'BioAuth module is not initialized (calling get-validation-status)',
+                );
```
Comment (Lemonexe) [inline packages/suite-desktop-core/src/modules/bioAuthModule.ts:297]: 📝 Note: this **could have been happening** because [this line in develop](https://github.com/trezor/trezor-suite/blob/73ff006b3c4e4e4324075c42d1413ecab12da72e/packages/suite/src/actions/suite/bioAuthThunks.ts#L41) was called from UI without any regard to BioAuthModule status, but that's fixed now.

I also changed the wording so the errors are distinguishable in case of regression.

File: packages/suite-desktop-core/src/modules/bioAuthModule.ts [hunk 4]
```diff
@@ -215,7 +251,8 @@ export const initBioAuthModule = ({
         ipcMain.handle('bio-auth/is-bio-auth-available', ipcEvent => {
             validateIpcMessage({ ipcEvent });
 
-            if (!bioAuth?.initialized) throw new Error('BioAuth module is not initialized');
+            // Necessary check for race condition: UI might ask for availability before await bioAuth.init()
+            if (!bioAuth) return Promise.resolve(false);
```
Comment (Lemonexe) [inline packages/suite-desktop-core/src/modules/bioAuthModule.ts:255]: I believe this is the one method which should be **allowed** regardless of initialized.

From renderer POV, the "initialization" of BioAuthModule is an implementation detail, so "is available" means both is initialized && is supported by system.
This call technically does two things now: it's also a status probe from renderer. I think it's OK 🤔

File: packages/suite/src/actions/suite/bioAuthThunks.ts [hunk 5]
```diff
@@ -24,29 +24,32 @@ const handleError = (error: string, dispatch: Dispatch, message: string) => {
...
-    });
+        if (!available) return;
+        // ensure this api is called only when & if BioAuthModule is available = initialized
+        desktopApi.getBioAuthStatus().then(validated => {
+            dispatch(bioAuthActions.setIsBioAuthValidationRequired(!validated));
+        });
+    };
 
-    // validation status
-    desktopApi.getBioAuthStatus().then(validated => {
```
Comment (Lemonexe) [inline packages/suite/src/actions/suite/bioAuthThunks.ts:41]: these two calls, `desktopApi.isBioAuthAvailable()` and `desktopApi.getBioAuthStatus()` were the main problem I think.
`isBioAuthAvailable` is now OK (the status probe), and `getBioAuthStatus` is now done only afterwards.

**Review by Lemonexe — APPROVED** [review]
I made a further change in 3d4711bc and now I believe it'll be reliable.
I tested it on Linux & Windows as is, and also [with artifical delay at this line](https://github.com/trezor/trezor-suite/blob/3d4711bcb4356c522ff7a095c0907e0339c1e709/packages/suite-desktop-core/src/modules/bioAuthModule.ts#L320). At this line it affects Linux too, but it seems good now. Maybe the windows fix won't even be necessary after all? Idk. It's still a double safeguard.

Approving, but now it's also my changes, so @vojtatranta what do you think?

File: packages/suite-desktop-core/src/modules/bioAuthModule.ts (hunk 4 above)
Comment (vojtatranta) [reply packages/suite-desktop-core/src/modules/bioAuthModule.ts:255]: yup

**Comment by vojtatranta** [comment]
Approve

**Comment by zako05** [comment]
QA OK ✅

* mobile (android) ✅

https://github.com/user-attachments/assets/d0edeb16-fbc0-4ff8-a951-ccea9b7016f6

* macOS (desktop) ✅

https://github.com/user-attachments/assets/a708e0f1-f7aa-495d-81a4-9bfcb096eca4
