### PR TITLE
Optimization of loading and updating fees

### LINKED ISSUE #15087: Optimise fee fetching and updating
**Description**

In our current solution the fees:
- are updated for all enabled networks even though user does not use them
	- -> useless requests
- are updated every 10 blocks. For POL that's 20 seconds, for ARB it is 3 seconds, for ETH it is 120 seconds, for BTC it is 100 minutes!
    - -> the fees are outdated

**Expected behavior**

Let's change the behaviour, that fees will not be updated periodically for all networks but only if:
- user enters send form
- user enters stake/unstake/claim
- user enters trading

**Notes**

For conditions when fee should be updated now, see `updateFeeInfoThunk`

**Question**: Does it make sense to store it in redux?

The updating redux action is:
`@common/wallet-core/blockchain/updateFee`
Screenshot 2024-10-26 at 16 48 35

Fees are stored in redux:
Screenshot 2024-10-26 at 16 46 46

**Question**: Should we allow user to update fees when he is in send form for long time?

### LINKED ISSUE #17772: When I refresh send form I get default hardcoded fees
**Describe the bug**

Image

When I leave form and enter again, it is ok

Image

### PR DESCRIPTION
**Pull request by izmy**
## Description

This update optimizes how fees are loaded and updated in the application.

1. Optimize fee updates to reduce unnecessary requests

2. Fix: Update default fees in the send form after fetching

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/15087
Resolve https://github.com/trezor/trezor-suite/issues/17772

### CODE REVIEW

File: suite-common/wallet-core/src/fees/feesThunks.ts [hunk 1]
```diff
@@ -78,6 +78,10 @@ export const updateFeeInfoThunk = createThunk(
         { networkSymbol, forceUpdate }: { networkSymbol: string; forceUpdate?: boolean },
         { dispatch, getState, extra },
     ) => {
+        const selectedAccount = extra.selectors.selectSelectedAccount(getState());
+
+        if (networkSymbol.toLowerCase() !== selectedAccount.network?.symbol) return;
+
```
Comment (tomasklim) [inline suite-common/wallet-core/src/fees/feesThunks.ts]: is this needed?

File: suite-common/wallet-core/src/fees/feesThunks.ts [hunk 2]
```diff
@@ -78,6 +78,10 @@ export const updateFeeInfoThunk = createThunk(
...
         const network = getNetworkOptional(networkSymbol.toLowerCase());
         if (!network) return;
         const blockchainInfo = selectNetworkBlockchainInfo(getState(), network.symbol);
```
Comment (tomasklim) [inline suite-common/wallet-core/src/fees/feesThunks.ts:80]: the condition logic in this method 
```
        if (
            feeInfo &&
            feeInfo.blockHeight > 0 &&
            blockchainInfo.blockHeight - feeInfo.blockHeight < 10 &&
            !forceUpdate
        ) {
            return;
        }
```
has to be dropped

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 3]
```diff
@@ -258,6 +258,19 @@ export const useSendForm = (props: UseSendFormProps): SendContextValues => {
...
     }, [getValues, composedLevels, dispatch, resetContext, props.selectedAccount.account]);
 
+    // replace default feeInfo with data loaded from the server
+    useEffect(() => {
+        const newFeeInfo = getFeeInfo({
+            networkType: state.account.networkType,
+            feeInfo: props.fees[state.account.symbol],
+        });
+
+        if (JSON.stringify(newFeeInfo) !== JSON.stringify(state.feeInfo)) {
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendForm.ts]: compare `blockHeight`

**Review by tomasklim — CHANGES_REQUESTED** [review]

**Comment by tomasklim** [comment]
When you finish it, we have to make sure it does not break mobile / mobile will not spam fee fetching

File: suite-common/wallet-core/src/fees/feesThunks.ts [hunk 4]
```diff
@@ -78,6 +78,10 @@ export const updateFeeInfoThunk = createThunk(
         { networkSymbol, forceUpdate }: { networkSymbol: string; forceUpdate?: boolean },
```
Comment (tomasklim) [inline suite-common/wallet-core/src/fees/feesThunks.ts]: I think we will be able to get rid of `forceUpdate` but not 100% sure

File: suite-common/wallet-core/src/fees/feesThunks.ts (hunk 2 above)
Comment (izmy) [reply suite-common/wallet-core/src/fees/feesThunks.ts:80]: yes, you're right... I deleted it

File: packages/suite/src/hooks/wallet/useSendForm.ts (hunk 3 above)
Comment (izmy) [reply packages/suite/src/hooks/wallet/useSendForm.ts]: sure... I didn't think of that and it's definitely better than the ugly `JSON.stringify` 😄

File: suite-common/wallet-core/src/fees/feesThunks.ts (hunk 4 above)
Comment (izmy) [reply suite-common/wallet-core/src/fees/feesThunks.ts]: yes, `forceUpdate` is now useless... I deleted it

File: packages/suite/src/middlewares/suite/suiteMiddleware.ts [hunk 5]
```diff
@@ -121,7 +121,7 @@ const suite =
                 const { enabledNetworks } = api.getState().wallet.settings;
```
Comment (tomasklim) [inline packages/suite/src/middlewares/suite/suiteMiddleware.ts]: I think you can remove the whole `case SUITE.SET_DEBUG_MODE` case

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 6]
```diff
@@ -258,6 +258,19 @@ export const useSendForm = (props: UseSendFormProps): SendContextValues => {
...
+        const newFeeInfo = getFeeInfo({
+            networkType: state.account.networkType,
+            feeInfo: props.fees[state.account.symbol],
+        });
+
+        if (newFeeInfo.blockHeight !== state.feeInfo.blockHeight) {
+            setState((prev: UseSendFormState) => ({ ...prev, feeInfo: newFeeInfo }));
+        }
+        // eslint-disable-next-line react-hooks/exhaustive-deps
+    }, [props.fees]);
```
Comment (TomasBoda) [inline packages/suite/src/hooks/wallet/useSendForm.ts]: nitpick (the `feeInfo` vs `newFeeInfo` is up to you but I think the explicit type of `prev` is not necessary)
```suggestion
    useEffect(() => {
        const feeInfo = getFeeInfo({
            networkType: state.account.networkType,
            feeInfo: props.fees[state.account.symbol],
        });

        if (feeInfo.blockHeight !== state.feeInfo.blockHeight) {
            setState(prev => ({ ...prev, feeInfo }));
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [props.fees]);
```

File: packages/suite/src/components/wallet/Fees/Fees.tsx [hunk 7]
```diff
@@ -7,9 +7,11 @@ import {
     UseFormReturn,
     UseFormSetValue,
 } from 'react-hook-form';
+import { useDispatch } from 'react-redux';
```
Comment (TomasBoda) [inline packages/suite/src/components/wallet/Fees/Fees.tsx]: I think we have custom `useDispatch` in `src/hooks/suite` that is used across the app.

File: packages/suite/src/hooks/wallet/useSendForm.ts (hunk 6 above)
Comment (izmy) [reply packages/suite/src/hooks/wallet/useSendForm.ts]: changed

File: packages/suite/src/components/wallet/Fees/Fees.tsx (hunk 7 above)
Comment (izmy) [reply packages/suite/src/components/wallet/Fees/Fees.tsx]: good catch, thanks

File: packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts [hunk 8]
```diff
@@ -1169,7 +1172,7 @@ export const setMax = [
             selectedAccount: ETH_ACCOUNT,
         },
         finalResult: {
-            estimateFeeCalls: 1,
+            estimateFeeCalls: 2,
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts:1175]: why is it 2 now? maybe it is the same problem as that it fetches fee twice when the discovery starts

Screenshot 2025-03-29 at 10 14 19

I am thinking if we even need to fetch the fee before user enters send form, it would solve this 😀

File: packages/connect/src/api/common/MiscFees.ts [hunk 9]
```diff
@@ -20,9 +20,9 @@ export class MiscFeeLevels {
         this.levels = coinInfo.defaultFees;
     }
 
-    async load(blockchain: Blockchain) {
+    async load(blockchain: Blockchain, request: Parameters<typeof blockchain.estimateFee>[0]) {
```
Comment (tomasklim) [inline packages/connect/src/api/common/MiscFees.ts:23]: For Solana, in some cases it does not work because of wrong blockhash 🤯 it is probably not caused by this PR maybe it just shows this problem

Screenshot 2025-03-29 at 10 20 56

Screenshot 2025-03-29 at 10 25 56

Probable replication: fill send form. Wait for 1 minute, enter send form again

So I will create an issue

Comment (tomasklim) [inline packages/connect/src/api/common/MiscFees.ts:23]: For Cardano it does not work either, but there is problem also on production 😀 
Screenshot 2025-03-29 at 10 57 09
Screenshot 2025-03-29 at 10 57 01

So I will create an issue

File: packages/suite/src/hooks/wallet/useSendForm.ts [hunk 10]
```diff
@@ -258,6 +258,19 @@ export const useSendForm = (props: UseSendFormProps): SendContextValues => {
...
+    // replace default feeInfo with data loaded from the server
+    useEffect(() => {
+        const feeInfo = getFeeInfo({
+            networkType: state.account.networkType,
+            feeInfo: props.fees[state.account.symbol],
+        });
+
+        if (feeInfo.blockHeight - state.feeInfo.blockHeight > 0) {
+            setState(prev => ({ ...prev, feeInfo }));
+        }
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useSendForm.ts:272]: Maybe: this is not great for bitcoin as fee can change within the same block, we should add note to the issue with bitcoin cache fee that this can be also problem

File: packages/connect/src/api/common/MiscFees.ts (hunk 9 above)
Comment (tomasklim) [reply packages/connect/src/api/common/MiscFees.ts:23]: #17976

Comment (tomasklim) [reply packages/connect/src/api/common/MiscFees.ts:23]: #17975

File: packages/connect/src/api/bitcoin/BitcoinFees.ts [hunk 11]
```diff
@@ -106,7 +106,7 @@ export class BitcoinFeeLevels {
         blocks.push(...fillGap(oneDayBlocks, oneDayBlocks / 2, oneDayBlocks * 6));
 
         try {
-            const response = await blockchain.estimateFee({ blocks });
+            const response = await blockchain.estimateFee({ ...request, blocks });
```
Comment (tomasklim) [inline packages/connect/src/api/bitcoin/BitcoinFees.ts]: can we omit changes for Bitcoin, for now? I created an issue, let's leave it for someone who will understand it better https://github.com/trezor/trezor-suite/issues/17977

File: packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts (hunk 8 above)
Comment (izmy) [reply packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts:1175]: It is correct behavior and is not related to the discovery start. The first call is just useEffect after rendering the component `<Fees />`, the second call is after filling sendForm with correct values (it calls `composeEthereumTransactionFeeLevelsThunk`).

Comment (tomasklim) [reply packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts:1175]: refresh app on dashboard

Comment (izmy) [reply packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts:1175]: it was happening because in the action `TREZOR_CONNECT_BLOCKCHAIN_ACTIONS.BLOCK` was dispatch for `updateFeeInfoThunk`, so I removed it

File: packages/suite/src/hooks/wallet/useSendForm.ts (hunk 10 above)
Comment (izmy) [reply packages/suite/src/hooks/wallet/useSendForm.ts:272]: sure, I added a comment

File: packages/connect/src/api/bitcoin/BitcoinFees.ts (hunk 11 above)
Comment (izmy) [reply packages/connect/src/api/bitcoin/BitcoinFees.ts]: reverted

File: packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts (hunk 8 above)
Comment (tomasklim) [reply packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts:1175]: Ah I see, `TREZOR_CONNECT_BLOCKCHAIN_ACTIONS.CONNECT` is fired twice

**Review by tomasklim — APPROVED** [review]

**Comment by mroz22** [comment]
please name your commits better next time! 2fc286bbdf38c411ef134de5817a88733c00803e has only changes to packages/connect yet it is named "fix(suite)". We auto pre-generate connect changelogs and a commit message like this doesn't helps us.

**Comment by mroz22** [comment]
and it sounds like a feature to me when scoped to connect
