### PR TITLE
fix(suite): DashboardGraph error when fetching data fetch failed for all

### LINKED ISSUE #19166: Graph does not reflect when data fetch failed for all accounts
**Describe the bug**

Empty graph is shown empty instead of displaying error message, when data has failed to fetch for all accounts (see screenshot below).

**Info:**

- Remembered Wallet: yes/no
- Suite Version: web, develop as of writing

**How to reproduce**

1. all seed, QA passphrase
2. enable only Ripple, nothing else
3. go to dashboard

**Screenshots**

Image

**Expected behavior**

Image

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Cherrypicked from #18724

## Related Issue

Resolve #19166 

## Screenshots:
[only XRP, before](https://github.com/user-attachments/assets/4871f765-13a6-404d-9840-a35b90c8ab9d)

[only XRP, after](https://github.com/user-attachments/assets/c85b228d-5d0e-45fa-b7ec-f18a85719b97)

[XRP + ETH, after](https://github.com/user-attachments/assets/18d6bc05-de12-466c-8bc1-ae9a1ee0f528)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/dashboard-failures&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/dashboard-failures&lookback=7)

### CODE REVIEW

**Review by mroz22 — APPROVED** [review]

File: packages/suite/src/views/dashboard/PortfolioCard/DashboardGraph.tsx [hunk 1]
```diff
@@ -57,8 +57,8 @@ export const DashboardGraph = memo(({ accounts }: DashboardGraphProps) => {
     const selectedDeviceState = selectedDevice?.state?.staticSessionId;
     const failedAccounts = graph.error?.filter(a => a.deviceState === selectedDeviceState);
     const allFailed =
-        failedAccounts &&
-        failedAccounts.every(fa => accounts.some(a => a.descriptor === fa.descriptor));
+        failedAccounts !== undefined &&
+        accounts.every(a => failedAccounts.some(fa => fa.descriptor === a.descriptor));
```
Comment (Lemonexe) [inline packages/suite/src/views/dashboard/PortfolioCard/DashboardGraph.tsx:61]: invert because `failedAccounts` can be larger than `accounts`

`accounts` in `DashboardGraph` come from "fast accounts" in `useAccounts`, which do not include `visible: false` (and there is always the first empty account with visible: false)

so if both have visible and invisible failed, we have 2 failedAccounts but only one visible `accounts` here

**Comment by Lemonexe** [comment]
Failing E2E confirmed to be broken ([slack](https://satoshilabs.slack.com/archives/CKYFBT2C9/p1748262851419529)).
Merging.
