### PR TITLE
fix(suite): hide add label from ConfirmValueModal if it would need a device call

### LINKED ISSUE #22418: Add label button appears with labelling turned off
**Describe the bug**
Add label appears in Reveal receive address modal even when Labelling is Off in Settings.
It's not broken on production.

thread with the video
https://satoshilabs.slack.com/archives/C07D260JB4H/p1760069107044449

**Info:**
 - Suite version: web 25.10.1 (f745cf95cd245ea59618a6f1a55a7ec3c97f2b00)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 2048x1152
 - Device: Trezor T3T1 2.9.1 universal (revision acd56d0113a547e9b5983510b0ce9de079e30e05)
 - Transport: BridgeTransport 3.1.0

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Fix two independent bugs, but located in the same flow in Receive address confirmation modal:
- you can turn on labeling ,but device is locked with the receive address call, so it cannot display another device confirmation, and the labeling button gets stuck
- after confirming receive address, clicking on labeling button correctly initializes the device confirmation flow, but the device confirmation modal can never get closed

Solution:
- Remove the labeling button until address is confirmed
- Always display it when labeling is already enabled (nothing blocks it now) 
- Don't `preserve` the modal after confirmation on device is done 

## Related issue

Resolve https://github.com/trezor/trezor-suite/issues/22418

## Screenshots:

Simplest case: first turn **on** labeling, then open Receive Address. During receive you can set the label at any time:

[receive labeling with already turned on.webm](https://github.com/user-attachments/assets/1aac09bc-a8f1-428a-a743-93469876581c)

Labeling is **off**, open Receive Address. Until it's confirmed you can't change label. Then you can change label, having first confirm the Confirm on Device (Enable labeling) modal. This modal **does not stay stuck** :sweat_smile: and then you can change label: 

[turning on receive labeling in modal.webm](https://github.com/user-attachments/assets/982e7ed4-b247-4e62-9648-379bbc35861e)

Edge case: like the above, but the Enable Labeling is cancelled, both from device & from suite:

[turning on BUT REJECT receive labeling in modal.webm](https://github.com/user-attachments/assets/1362b4a1-d0cb-49bf-b1fc-23bc3f28b84f)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/turn-on-labeling-in-receive&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/turn-on-labeling-in-receive&lookback=7)

### CODE REVIEW

File: packages/suite/src/views/settings/SettingsGeneral/SettingsGeneral.tsx [hunk 1]
```diff
@@ -67,7 +70,6 @@ export const SettingsGeneral = () => {
         selectHasExperimentalFeature('tor-external'),
     );
 
-    const isMetadataEnabled = metadata.enabled && !metadata.initiating;
```
Comment (Lemonexe) [inline packages/suite/src/views/settings/SettingsGeneral/SettingsGeneral.tsx:70]: this is where I got inspiration for the `selectIsMetadataEnabled` which I mainly wanted to use in `ConfirmValueModal`, → use it also here to clean it up.

**Review by 5K1PY — APPROVED** [review]

**Comment by Lemonexe** [comment]
Merging, Desktop & Web E2E test [confirmed broken](https://satoshilabs.slack.com/archives/CKYFBT2C9/p1760357525008589?thread_ts=1760356377.307229&cid=CKYFBT2C9).

**Comment by evgenysl** [comment]
QA OK
