### PR TITLE
fix(suite): fixed approval and receive address in swap

### LINKED ISSUE #19567: Swap - incorrect receive address
## Description

When doing a DEX swap that requires approval, incorrect receive address is added to the final quote.

### PR DESCRIPTION
**Pull request by TomasBoda**
## Description

After approval in swap, the `receiveAddress` in `quote` is not updated by the new user-selected receive address.

## Related Issue

Resolve #19567 

## Screenshots:

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/approval&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/approval&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/approval&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeApprovalAddress.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+import { useSelector } from 'src/hooks/suite';
+
+import { useAccountAddressDictionary } from '../../useAccounts';
+
+interface TradingApprovalAddress {
+    approvalAddress?: string;
+}
+
+export const useTradingExchangeApprovalAddress = (): TradingApprovalAddress => {
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/trading/form/useTradingExchangeApprovalAddress.ts]: I think this complication is not needed. Just use `account.descriptor` instead of this hook

**Review by tomasklim — CHANGES_REQUESTED** [review]

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeApprovalAddress.ts (hunk 1 above)
Comment (tomasklim) [reply packages/suite/src/hooks/wallet/trading/form/useTradingExchangeApprovalAddress.ts]: We need it just for EVMs, right? so it should work, the address format is same

File: suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts [hunk 2]
```diff
@@ -65,6 +65,8 @@ export const confirmExchangeTradeThunk = createThunk(
             trade = { ...trade, fromAddress: refundAddress };
         }
 
+        trade = { ...trade, receiveAddress };
```
Comment (tomasklim) [inline suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts]: how is it possible that it worked before?

Before, the address got there in `onFinishTransactionClick` in `TradingVerify.tsx`. Why it does not now?

Comment (tomasklim) [inline suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts]: probably also applies only to `trade.isDex`

Comment (tomasklim) [reply suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts]: It has to work even without this change or I dont understand. If it worked before, it has to work now 😀

**Review by tomasklim — CHANGES_REQUESTED** [review]
Those two places are sus
https://github.com/trezor/trezor-suite/pull/19486/files#r2144743092
https://github.com/trezor/trezor-suite/pull/19486/files#r2142493818

**Comment by tomasklim** [comment]
This is also sus https://github.com/trezor/trezor-suite/pull/19486/files#r2144763977

File: packages/suite/src/hooks/wallet/trading/form/useTradingExchangeApprovalAddress.ts (hunk 1 above)
Comment (TomasBoda) [reply packages/suite/src/hooks/wallet/trading/form/useTradingExchangeApprovalAddress.ts]: done

File: suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts (hunk 2 above)
Comment (TomasBoda) [reply suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts]: done

File: suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts [hunk 3]
```diff
@@ -61,8 +61,12 @@ export const confirmExchangeTradeThunk = createThunk(
             return isConfirmationOk;
         }
 
-        if (trade.isDex && !trade.fromAddress) {
-            trade = { ...trade, fromAddress: refundAddress };
+        if (trade.isDex) {
+            trade = { ...trade, receiveAddress };
+
+            if (!trade.fromAddress) {
```
Comment (adderpositive) [inline suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts:67]: We were overwriting `receiveAddress` to `undefined` in some step, right?

**Review by adderpositive — APPROVED** [review]

File: suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts (hunk 3 above)
Comment (TomasBoda) [reply suite-common/trading/src/thunks/exchange/confirmExchangeTradeThunk.ts:67]: not to `undefined`, but the `receiveAddress` after approval was not updated with the new `receiveAddress` from the receive address step, so I explicitly added it to `trade`

**Review by tomasklim — APPROVED** [review]
