### PR TITLE
fix(suite): correct max amount behavior for ETH and SOL staking

### LINKED ISSUE #20223: Solana staking – error with certain amounts.
**Describe the bug**
While staking SOL, if you have a certain amount, for example 0.035147097 SOL, in your account, you receive an error when you try to stake the maximum.

Image

**Info:**
 - Suite version: web 25.7.2 (c33cc9bef858166a7f465afa29b649897261d142)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: Trezor T3T1 2.9.0 regular (revision a09e6f04d4204607d821d9b742dcf7ffe9c4e2f5)
 - Transport: WebUsbTransport

### LINKED ISSUE #20270: Stake ETH max button is not working when having 0.1-0.13 ETH
**Describe the bug**
When I have less than 0.13 ETH. Staking `max` button is not working. Validate that Solana works as before

https://github.com/user-attachments/assets/c1ef3208-3397-4b6b-a3b4-f3e49d1fa1c0

### PR DESCRIPTION
**Pull request by izmy**
### Problem
- On **ETH**, the "Max" button subtracted `MIN_FOR_WITHDRAWALS (0.03)`, so for balances in the 0.1–0.13 range the prepared amount fell below `MIN_ETH_AMOUNT_FOR_STAKING (0.1)` and failed validation in prepareStakeEthTx.
- On **SOL**, the flow is stricter regarding fees and relies on simulation, so the subtraction is correct.

### Root cause
- `setMax()` computed: `max = balance - MIN_FOR_WITHDRAWALS (0.03)` on **ETH** as well. (`useStakeForm.ts`)
- Later, `prepareStakeEthTx` rejected `amounts < 0.1 ETH`, causing the dead zone (`ethereum-staking.ts`)

### Solution
Reworked the `setMax` logic and added `MIN_BALANCE_FOR_FEE_BUFFER` variables for SOL and ETH to ensure minimal fees required for successful staking.
Also performed a minor refactor for better readability.

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/20270
Resolve [#20223](https://github.com/trezor/trezor-suite/issues/20223)

## Screenshots

image

image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/staking-max-amount-validation&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/staking-max-amount-validation&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/staking-max-amount-validation&lookback=7)

### CODE REVIEW

File: packages/suite/src/hooks/wallet/useStakeForm.ts [hunk 1]
```diff
@@ -311,21 +311,34 @@ export const useStakeForm = ({
 
         const amount = new BigNumber(account.formattedBalance).toString();
 
-        if (amount < stakingLimits.MIN_BALANCE_FOR_STAKING.toString()) {
-            setIsLessAmountForWithdrawalWarningShown(true);
-        }
+        if (account.networkType === 'ethereum') {
+            if (amount < stakingLimits.MIN_BALANCE_FOR_STAKING.toString()) {
+                setIsAdviceForWithdrawalWarningShown(true);
```
Comment (tomasklim) [inline packages/suite/src/hooks/wallet/useStakeForm.ts]: is this correct warning? for other networks it is different (not tested, only question)

Comment (izmy) [reply packages/suite/src/hooks/wallet/useStakeForm.ts]: I added screens... but the logic after clicking **Send Max** in staking feels a bit weird. The input accepts any value. There is no validation that subtracts the withdrawal amount, so the "max" value by **Send Max** button may actually be lower than what I can enter manually.

ETH and SOL staking process behave a bit differently, so I think it would be a good idea to define proper max value handling and validation for both coins instead of shared logic

**Review by tomasklim — COMMENTED** [review]
I've run into 3 bugs

1. Fiat value shows real balance max and then drop to lowered max

https://github.com/user-attachments/assets/990dccf3-a012-47d7-83f1-9533d6b3500b

2. Fiat max misses 1 cent to work

https://github.com/user-attachments/assets/93e938c0-a206-432a-b221-3b44effa82b8

3. Solana max works just for first time

https://github.com/user-attachments/assets/55465f52-e2ca-45a2-bf89-ff2aad18e041

**Comment by Vere-Grey** [comment]
Any new flows, interactions or scenarios that would be good to automate?

**Comment by tomasklim** [comment]
Please test if it fixes this [#20223](https://github.com/trezor/trezor-suite/issues/20223)

File: packages/suite/src/actions/wallet/stake/stakeFormSolanaActions.ts [hunk 2]
```diff
@@ -166,9 +166,13 @@ export const composeTransaction =
...
         const txData = await getTransactionData(formValues, selectedAccount, blockchain);
 
+        const { amount } = formValues.outputs[0];
+
+        if (!amount || amount === '0') return;
+
         let estimatedFee;
         // it is not needed to estimate fee for empty input
-        if (formValues.cryptoInput) {
+        if (amount) {
```
Comment (cermakjiri) [inline packages/suite/src/actions/wallet/stake/stakeFormSolanaActions.ts]: The `amount` must be defined by now since it's been validated above:
```suggestion
```

File: packages/suite/src/hooks/wallet/useStakeForm.ts [hunk 3]
```diff
@@ -65,21 +61,10 @@ export const useStakeForm = ({
...
-            toFiatCurrency({
-                amount: stakingLimits.MIN_AMOUNT_FOR_STAKING.toString(),
-                rate: currentRate?.rate,
-            })?.toFixed(2) ?? undefined,
-        maxFiat:
-            toFiatCurrency({
-                amount: account.formattedBalance,
-                rate: currentRate?.rate,
-            })?.toFixed(2) ?? undefined,
-    };
```
Comment (cermakjiri) [inline packages/suite/src/hooks/wallet/useStakeForm.ts:82]: 👍

File: suite-common/staking/src/actions/stakeFormActions.ts [hunk 4]
```diff
@@ -42,7 +42,11 @@ export const calculate = (
     let amount: string;
     let max: string | undefined;
 
-    if (output.type === 'send-max' || output.type === 'send-max-noaddress') {
+    const isSendMax = output.type === 'send-max' || output.type === 'send-max-noaddress';
+
+    if (output.amount != null) {
```
Comment (cermakjiri) [inline suite-common/staking/src/actions/stakeFormActions.ts]:
```suggestion
    if (output.amount !== null) {
```

File: suite-common/wallet-constants/src/solanaStakingConstants.ts [hunk 5]
```diff
@@ -4,6 +4,7 @@ export const BACKUP_SOL_APY = 6.87;
 export const MIN_SOL_AMOUNT_FOR_STAKING = new BigNumber(0.01);
 export const MAX_SOL_AMOUNT_FOR_STAKING = new BigNumber(10_000_000);
 export const MIN_SOL_FOR_WITHDRAWALS = new BigNumber(0.05);
+export const MIN_SOL_BALANCE_FOR_FEE_BUFFER = new BigNumber(0.005);
```
Comment (cermakjiri) [inline suite-common/wallet-constants/src/solanaStakingConstants.ts:7]: 👍

File: suite-common/wallet-constants/src/ethereumStakingConstants.ts [hunk 6]
```diff
@@ -12,6 +12,7 @@ export const STAKE_GAS_LIMIT_RESERVE = 220_000;
 export const MIN_ETH_AMOUNT_FOR_STAKING = new BigNumber(0.1);
 export const MAX_ETH_AMOUNT_FOR_STAKING = new BigNumber(1_000_000);
 export const MIN_ETH_FOR_WITHDRAWALS = new BigNumber(0.03);
+export const MIN_ETH_BALANCE_FOR_FEE_BUFFER = new BigNumber(0.005);
```
Comment (cermakjiri) [inline suite-common/wallet-constants/src/ethereumStakingConstants.ts:15]: 👍

**Review by cermakjiri — APPROVED** [review]

**Comment by izmy** [comment]
> Please test if it fixes this [#20223](https://github.com/trezor/trezor-suite/issues/20223)

I tried with an amount of 0.035147097 SOL and it works

**Comment by izmy** [comment]
> Any new flows, interactions or scenarios that would be good to automate?

I don't think so... here are new cases when selecting max amount
### ETH
- If your balance is below 0.13 ETH → amount = balance − 0.005 ETH
- If your balance is above 0.13 ETH → amount = balance − 0.03 ETH
### SOL
- If your balance is below 0.06 SOL → amount = balance − 0.005 SOL
- If your balance is above 0.06 SOL → amount = balance − 0.05 SOL

**Review by Vere-Grey — APPROVED** [review]
for update in suite e2e 👍

File: suite-common/wallet-utils/src/stakingUtils.ts [hunk 7]
```diff
@@ -74,6 +77,7 @@ export const getStakingLimitsByNetworkSymbol = (
                 MIN_AMOUNT_FOR_STAKING: MIN_ETH_AMOUNT_FOR_STAKING,
                 MAX_AMOUNT_FOR_STAKING: MAX_ETH_AMOUNT_FOR_STAKING,
                 MIN_FOR_WITHDRAWALS: MIN_ETH_FOR_WITHDRAWALS,
+                MIN_BALANCE_FOR_FEE_BUFFER: MIN_ETH_BALANCE_FOR_FEE_BUFFER,
```
Comment (tomasklim) [inline suite-common/wallet-utils/src/stakingUtils.ts:80]: How about disabling max for amounts smaller than MIN_BALANCE_FOR_STAKING + MIN_BALANCE_FOR_FEE_BUFFER so that this does not happen.
(I clicked on max)
Screenshot 2025-10-30 at 10 11 50

Comment (izmy) [reply suite-common/wallet-utils/src/stakingUtils.ts:80]: Oh, another edge case 🙈 I will check it and fix it

**Review by tomasklim — APPROVED** [review]
Works great, just check the comment above 🙏 Thanks

**Review by tomasklim — APPROVED** [review]
👍

**Comment by tomasklim** [comment]
New edge case 😀 
Screenshot 2025-11-03 at 15 35 26
Screenshot 2025-11-03 at 15 35 34
