### PR TITLE
fix(react-native-usb): implement opened WebUSBDevice state and closing device when leaving the app

### LINKED ISSUE #11896: Handle connection to Trezor Suite web and connected Trezor
We want to achieve that when user connects unitialised Trezor and we linked him to Trezor Suite web on the mobile device, mobile app does not steal the session. User can do the whole onboarding on web with Trezor Suite Lite installed. And that user can use the Trezor Suite web without App stealing the session.

_1. System message to open app when Trezor is connected remains as it is._

_2. If Suite Lite missing USB persmission for the connected Trezor, new system message will appear right after user opens the app_
- If the user grants permissions (opens) another application (3rd party, web) or none from the original system message to open app, a new system window for granting USB permissions pops up right after user opens the Suite Lite. 

_3. User connects the uninitialized device_
- when user connects unitialized device, we display him message
- Uses is informed he can proceed to Trezor Suite Web 
- If user clicks on the link, he is redirected to Trezor Suite Web and the device is "released" from the app

_4. **New requirement**: After FW installation via Web Suite_
- user is possibly navigated back to Suite Lite app by system message
- We have a new alert for that case with better explanation where to continue
[FIGMA](https://www.figma.com/design/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?node-id=687-8798&t=UKVccuAiW7tl0r0H-11)

___

[Figma here](https://www.figma.com/file/xSWRW8Csq7zYJ3TiqwoIxB/Bugfixes?type=design&node-id=223-7882&mode=design&t=lWTn9tT6dPpKQhGI-11)

___

- New uninitialized device screen: 

**Current approved implementation**
image

**Original design**
image

**After FW installation, still without seed** NEW
image
___

### PR DESCRIPTION
**Pull request by matejkriz**
## Description

One more way to fix https://github.com/trezor/trezor-suite/issues/11896 🙉  This version keep the current permission flow - when you connect Trezor, Android ask you to choose if you want to open the app.

This PR unblock Trezor when Suite Lite goes into the background.

Defining `opened` state properly, Suite Lite is no longer blocking Trezor from usage in other app so it's possible to onboard via Suite Web even if Suite Lite is installed.

New UI for uninitialized device has to be implemented and I would like to use some changes from https://github.com/trezor/trezor-suite/pull/12177 to make permission handling even better in followup PR.

## Related Issue

Part of https://github.com/trezor/trezor-suite/issues/11896

## Screenshots

https://github.com/trezor/trezor-suite/assets/3729633/e99b4c3e-372c-490a-ae02-d0715bbeda94

### CODE REVIEW

File: packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt [hunk 1]
```diff
@@ -362,6 +377,6 @@ fun getWebUSBDevice(device: UsbDevice): WebUSBDevice {
             "serialNumber" to device.serialNumber,
             //"configuration" to device.configuration,
             //"configurations" to device.configurations,
-            "opened" to false,
+            "opened" to opened,
```
Comment (Nodonisko) [inline packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt]: Why not use `hasOpenedConnection(device.deviceName)` here instead of passing it as param?

Comment (Nodonisko) [reply packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt]: I see it's not method but standalone function, then we should make it method

Comment (matejkriz) [reply packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt]: I like standalone functions more :-) but of course I can make it a method here, let's do it.

Comment (Nodonisko) [reply packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt]: I think it doesn't make sense to pass information manually which could only lead to bugs.

Comment (matejkriz) [reply packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt]: 7e3b6dec61d6956cee803793fd15e4d6e26b32de

**Review by Nodonisko — APPROVED** [review]
LGTM 🎉
