### PR TITLE
fix(tor): kill tor process on app close

### LINKED ISSUE #3543: tor process doesn't close after closing Trezor Suite [macOS]
**Describe the bug**
I Trezor Suite with the built-in tor support. When I terminate Trezor Suite, I can see the tor process still running (and also staying active on the tor network). 

**Info:**
 - Suite Version: app 21.3.1 (21.3.1.10647)
 - OS: macOS 11.2.2 (20D80)

**Steps to reproduce:**
1. Start Trezor Suite 
2. Enable Tor in Trezor Suite
3. Close Trezor Suite (CMD+Q)

**Expected result:**
tor process should be terminated

**Actual result:**
tor process keeps running

### PR DESCRIPTION
**Pull request by tomasklim**

### CODE REVIEW

File: packages/suite-desktop/src-electron/modules/tor.ts [hunk 1]
```diff
@@ -99,6 +99,11 @@ const init = async ({ mainWindow, store }: Dependencies) => {
 
         cb({ cancel: false });
     });
+
+    app.on('before-quit', () => {
+        // fix: kill tor process on app close
+        toggleTor(false);
```
Comment (keraf) [inline packages/suite-desktop/src-electron/modules/tor.ts]: This will turn off Tor for any platform and save it in the settings. The next launch will have Tor disabled which is not the desired behaviour. 

The best place to look at imo would be the `stop` method in `packages/suite-desktop/src-electron/libs/processes/BaseProcess.ts`. There should be a reason why killing the process failed and maybe there should be a way to force this on Mac.

**Review by keraf — CHANGES_REQUESTED** [review]

**Review by keraf — APPROVED** [review]

**Comment by keraf** [comment]
Confirmed to be working by QA.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 21.4.1 (3ed454e4e81b72482a9ad780c5cce9846cb29fb1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.5 regular
