### PR TITLE
Fix/device manager ios fixes

### LINKED ISSUE #10011: Switcher iOS issues
- [x] #10022
- [x] #10023
- [ ] there should not be the shadow behind the switcher component

### LINKED ISSUE #10022: Big paddings above and at the bottom
There are big spaces on the top and bottom - see the printscreen from the dev:
IMG_9987

### LINKED ISSUE #10023: Missing links in the buttons
Please adjust the content of the switcher menu items (see Figma: https://www.figma.com/file/IidkuNfa5OWtPgta9jF8Gl/T-%E2%80%A2-Handoff?type=design&node-id=3987%3A21458&mode=design&t=mNQxJzRbSkapkjDD-1) 
1. Learn the basics - there is icon missing and the link should be: https://trezor.io/learn
2. Read the docs > It should be "Explore Trezor shop" and there is icon missing. The link: https://trezor.io/

### PR DESCRIPTION
**Pull request by PeKne**
Batch of fixes of device manager for iOS.
## Description
- 07f197ec5c99ca880060fd6004a9a5396c9c0609 - changes content of the device manager to be aligned with the design 
  - fixes #10023
- 6264ab49f992cbc81b0f667202811fbc64d6f492 - device switch shadow removed
- 28f4e903fa006e6466a70dbc11fe9b83ac95342f - removed Screen component from MessageSystemRender that caused glitchy screen layout problems
  - fixes #10022

## Related issue

Closes #10011 (iOS device manager bugs epic)

### CODE REVIEW

**Review by juriczech — APPROVED** [review]

File: suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx [hunk 1]
```diff
@@ -32,20 +39,42 @@ export const PortfolioTrackerDeviceManagerContent = () => {
         });
     };
 
+    const handleOpenEduLink = () => {
+        openLink('https://trezor.io/learn');
```
Comment (Nodonisko) [inline suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx:43]: Doesn't we have these link in more than one place? Maybe create some const for it?

**Review by Nodonisko — APPROVED** [review]

File: suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx (hunk 1 above)
Comment (PeKne) [reply suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx:43]: We have multiple links that starts with `https://trezor.io/learn` prefix, but there is no other place where is the URL just the same as here (all the other cases redirects to some specific subpage of `learn`). So I think there is no need for const now. Or what do you think?
