### PR TITLE
fix(suite): display loading Skeleton instead of jumping search and ad…

### LINKED ISSUE #17298: Enable coins renders on top of "Search" and activated networks for a bit
https://github.com/user-attachments/assets/092289fc-39d6-4f52-b8f1-8cdb8ceec45d

### PR DESCRIPTION
**Pull request by vojtatranta**
…d account button when suite is running discovery

## Related Issue

Resolve https://github.com/trezor/trezor-suite/issues/17298

## Screenshots:

https://github.com/user-attachments/assets/9efb6ced-2982-4303-abfc-f40fa423389c

Screenshot 2025-02-28 at 10 55 32 AM

https://github.com/user-attachments/assets/5ec6e4c4-17f8-47f5-98b7-05caed26757f

### CODE REVIEW

**Review by jvaclavik — APPROVED** [review]
Tested, and LGTM

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx [hunk 1]
```diff
@@ -71,12 +73,18 @@ export const AccountsMenu = () => {
...
-                            data-testid="@account-menu/add-account"
-                            device={device}
-                        />
+                        {isDiscoveryRunning ? (
+                            <SkeletonRectangle animate width="100%" height={38} />
+                        ) : (
+                            <>
+                                {!isEmpty && <AccountSearchBox />}
+                                <AddAccountButton
+                                    isFullWidth={isEmpty}
```
Comment (jvaclavik) [inline packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx:82]: I believe you don't need this prop anymore. It shouldn't be full width.

**Review by jvaclavik — CHANGES_REQUESTED** [review]
One comment - please delete prop `isFullWidth` and its additional functionality in `AddAccountButton`

File: packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx (hunk 1 above)
Comment (vojtatranta) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx:82]: Not my change!! :D

Comment (vojtatranta) [reply packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx:82]: Invalid: there can be no accounts

**Review by jvaclavik — APPROVED** [review]

**Comment by STew790** [comment]
**QA OK**
Already approved here https://github.com/trezor/trezor-suite/issues/17298#issuecomment-2708034634
