### PR TITLE
fix(suite): fees fixups

### LINKED ISSUE #21683: Collapse network fees
Change network fee component, so it isn't as distracting as it is now ([Figma](https://www.figma.com/design/nsDtvR2N5TmuK1QCefRdvP/Trading--Final-?node-id=4867-28661&t=6Yzg3JGrAV92cNdK-4)).

- Read carefully all the comments in Figma
- Apply this change across the whole Suite (see examples in Figma). It should be hopefully simple since this component is designed to fit anywhere (card, section, white/grey background).

# Component states

Image

# Proposal

Image

# Current state

Image

### PR DESCRIPTION
**Pull request by cermakjiri**
## Description

- add loader
- display max fee with specific precision
- ~~disable collapsible element if max fee null~~ I had reverted this. Because when you set a custom fee, the max. fee might be null at some time during recalculation. 
- adjust collapsible box padding
- fix fees content overflow

## Related Issue

Resolve #21683

## Screenshots:

https://github.com/user-attachments/assets/d33eb991-b7c2-4c8b-825b-c9cd4521b1d6

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=feat/21683-collpase-network-fees-3&lookback=7)

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=feat/21683-collpase-network-fees-3&lookback=7)

🔍🖥️ **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=feat/21683-collpase-network-fees-3&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/wallet/Fees/CollapsibleFees/InlineLoader.tsx
Comment (seibei-iguchi) [inline packages/suite/src/components/wallet/Fees/CollapsibleFees/InlineLoader.tsx:1]: Have you looked at LoadingContent?

**Review by seibei-iguchi — APPROVED** [review]

File: packages/suite/src/components/wallet/Fees/CollapsibleFees/CollapsibleFees.tsx [hunk 1]
```diff
@@ -69,26 +78,32 @@ export function CollapsibleFees({
             <Collapsible gap={20}>
                 <Row justifyContent="space-between" gap={12}>
                     <CollapsibleFeesHeader label={label} typographyStyle={headerTypographyStyle} />
-                    <Collapsible.Toggle data-testid="@wallet/fees/collapsible-fees-toggle">
+                    <Collapsible.Toggle
+                        data-testid="@wallet/fees/collapsible-fees-toggle"
+                        disabled={!collapsible}
```
Comment (seibei-iguchi) [inline packages/suite/src/components/wallet/Fees/CollapsibleFees/CollapsibleFees.tsx]: Just a nit: we use isDisabled, not just disabled. But isn't it perhaps better to do a ternary over the whole return and return either a Collapsible wrapped Row or one without a Collapsible at all? Perhaps a little less DRY but more readable, since we have all those collapsible condition inside the tree which we could remove that way

File: packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts [hunk 2]
```diff
@@ -1758,7 +1758,7 @@ type FeeChangeFixture = {
 export const feeChange: FeeChangeFixture[] = [
     {
         description: 'BTC fee changes',
-        skip: false,
+        skip: true,
```
Comment (cermakjiri) [inline packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts]: I spend a lot of time on it but the max fee didn't get calculated. There's something missing in the `store`, I assume, but I don't understand the fee logic at such level I could figure out what it's. If you've got deeper knowledge here, I'm happy to learn more. I'll fix it in the next sprint. In meantime, I disabled these two tests.

File: suite-common/wallet-utils/src/bigNumberUtils.ts
Comment (matusbalascak) [inline suite-common/wallet-utils/src/bigNumberUtils.ts:1]: If there's time, it'd be nice to cover this with unit tests

File: packages/suite/src/components/wallet/Fees/CollapsibleFees/InlineLoader.tsx [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+interface InlineLoaderProps {
+    children: ReactNode;
+    loading: boolean;
+    size?: SpinnerProps['size'];
+    testId?: string;
+}
+
+export function InlineLoader({ children, loading, size = 20, testId }: InlineLoaderProps) {
+    if (!loading) {
+        return <>{children}</>;
```
Comment (matusbalascak) [inline packages/suite/src/components/wallet/Fees/CollapsibleFees/InlineLoader.tsx:15]:
```suggestion
        return children;
```

**Review by izmy — APPROVED** [review]

File: suite-common/wallet-utils/src/bigNumberUtils.ts
Comment (cermakjiri) [reply suite-common/wallet-utils/src/bigNumberUtils.ts:1]: Good point. I'll add them in a new PR.

File: packages/suite/src/components/wallet/Fees/CollapsibleFees/InlineLoader.tsx
Comment (cermakjiri) [reply packages/suite/src/components/wallet/Fees/CollapsibleFees/InlineLoader.tsx:1]: Good point. Changed here https://github.com/trezor/trezor-suite/pull/23070/files

File: suite-common/wallet-utils/src/bigNumberUtils.ts
Comment (cermakjiri) [reply suite-common/wallet-utils/src/bigNumberUtils.ts:1]: https://github.com/trezor/trezor-suite/pull/23070/files
