### PR TITLE
Fix(suite): discreet mode placeholder cutout

### LINKED ISSUE #14736: discreet mode placeholder cutout
**Describe the bug**
discreet mode placeholder cutout 
Compare first nice fadeout from portfolio and second and third screenshot from account detail that has no fadeout of HiddenPlaceholder

**Steps to reproduce:**
1. a
2. b
3. c

**Info:**
 - Suite version: desktop 24.10.1 (6fbf039c99a65832b8acf0c0852f7df74ffea128)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.10.1

**Screenshots:**

_**OK**_
Screenshot 2024-10-05 at 9 46 41

_**QA NOK**_
Screenshot 2024-10-05 at 9 45 36
Screenshot 2024-10-05 at 9 45 31

### PR DESCRIPTION
**Pull request by Lemonexe**
## Description

Fix three instances of `HiddenPlaceholder` CSS blur being cut off for various reasons.

:information_source: this problem will likely pop up again in future, because as you can see, the blur can be clipped even from an element quite far in DOM. It's just not easily controllable - unless we would add paddings to HiddenPlaceholder just so that the blur can render into them :disappointed: 

## Related Issue

Resolve #14736

## Screenshots:

**Before:** see issue

**Sidebar after:**
image

**Fiat header after:**
[video incl. scrolling behavior](https://github.com/user-attachments/assets/01cafb29-6458-4792-ab2e-a71c4aece7ea)

**Only FYI** the `TruncateWithTooltip` isn't working, this is on develop, the value is mocked to be long:
Truncate not working

### CODE REVIEW

File: packages/suite/src/components/suite/FiatValue.tsx [hunk 1]
```diff
@@ -15,12 +15,6 @@ import { HiddenPlaceholder } from 'src/components/suite';
 
 import { HiddenPlaceholderProps } from './HiddenPlaceholder';
 
-const StyledHiddenPlaceholder = styled((props: HiddenPlaceholderProps) => (
-    <HiddenPlaceholder {...props} />
-))`
-    font-variant-numeric: tabular-nums;
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/FiatValue.tsx:21]: this is already [on HiddenPlaceholder always](https://github.com/trezor/trezor-suite/blob/e22b683733bf9069ac9a7e0190d63b35697a954f/packages/suite/src/components/suite/HiddenPlaceholder.tsx#L17)

File: packages/suite/src/views/suite/SwitchDevice/DeviceItem/WalletInstance.tsx [hunk 2]
```diff
@@ -163,13 +158,11 @@ export const WalletInstance = ({
                     </Row>
                 </Text>
 
-                <HiddenPlaceholder>
```
Comment (Lemonexe) [inline packages/suite/src/views/suite/SwitchDevice/DeviceItem/WalletInstance.tsx:166]: useless, `FiatHeader` has its own `HiddenPlaceholder` inside

File: packages/suite/src/components/suite/layouts/SuiteLayout/SubpageNavigation.tsx [hunk 3]
```diff
@@ -13,7 +13,6 @@ import { AppNavigationTooltip } from '../../AppNavigation/AppNavigationTooltip';
 const Container = styled.div`
     position: sticky;
     top: ${HEADER_HEIGHT};
-    background: ${({ theme }) => theme.backgroundSurfaceElevation0};
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/SuiteLayout/SubpageNavigation.tsx:16]: Because `SubPageNavigation` is under the `FiatHeader` in `WalletLayout`, it has higher default stacking order. And the opaque background overlays the blur, cutting it off.  
That would be a problem, but in this case the bgcolor seems useless. I didn't notice any visual difference, see screenshots.

File: packages/suite/src/components/suite/layouts/SuiteLayout/SubpageNavigation.tsx [hunk 4]
```diff
@@ -15,7 +15,7 @@ const Container = styled.div`
     top: ${HEADER_HEIGHT};
     background: ${({ theme }) => theme.backgroundSurfaceElevation0};
     border-bottom: 1px solid ${({ theme }) => theme.borderElevation1};
-    z-index: ${zIndices.pageHeader};
+    z-index: ${zIndices.stickyBar};
```
Comment (Lemonexe) [inline packages/suite/src/components/suite/layouts/SuiteLayout/SubpageNavigation.tsx:18]: I believe this was a mistake, see `zIndices`.
`pageHeader` was used twice, and `stickyBar` was unused, and by the description I think it was intended here.

**Review by jvaclavik — APPROVED** [review]
LGTM!
