### PR TITLE
Fix/various-bugs

### LINKED ISSUE #24313: Top banner is one line with scrollbars
**Describe the bug**
Banner appears with scrollbars by default.

Image

**Info:**
 - Suite version: desktop 26.2.0 (31de5514ee305ef4b92b78b8296330d772635fd9)
 - Browser: Trezor Suite 26.2.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.9.4 universal (revision ccf73fd0e9450b2407cd65f91cb06161454fc72b)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

### LINKED ISSUE #24907: The click on the edge of the button is not captured
**Describe the bug**
The click on the edge of the button is not captured, even though the click animation runs.

**Info:**

- Suite Version: web 26.1.2
- Browser: chrome 142
- OS: linux, windows

**How to reproduce**

1. Click on the edge of the button
1. Click doesn't do anything

**Screenshots**

https://github.com/user-attachments/assets/f38108a0-d83e-4ce1-bc6d-8f18891496e3

### PR DESCRIPTION
**Pull request by seibei-iguchi**
## Notes for QA
- fix text color in graph tooltips
- fix scrollbars in account labeling in header
- fix edges of buttons not responding to click
- fix floating labels in inputs and texture
- fix banners on top

## Screenshots:
image

🔍🖥️ **Suite desktop test results:** [View in Currents](https://app.currents.dev/projects/4ytF0E/runs?branch=fix/various-bugs&lookback=7)

🔍🖥️ **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/various-bugs&lookback=7)

### CODE REVIEW

File: packages/suite/src/components/suite/banners/SuiteBanners/SuiteBanners.tsx [hunk 1]
```diff
@@ -38,8 +38,6 @@ import { SuiteSyncBanner } from './SuiteSyncBanner';
 const Container = styled.div<{ $fill?: boolean }>`
     width: 100%;
     max-width: ${({ $fill }) => ($fill ? 'none' : MAX_CONTENT_WIDTH)};
-    max-height: 20vh;
-    overflow: auto;
```
Comment (jvaclavik) [inline packages/suite/src/components/suite/banners/SuiteBanners/SuiteBanners.tsx:42]: this had a reason but it's probably fine to delete it

**Review by jvaclavik — APPROVED** [review]

**Comment by zako05** [comment]
QA OK ✅

* ✅ Removed `max-height: 20vh` and `overflow: auto` from the banner container

https://github.com/user-attachments/assets/edf5fe33-5e61-430e-b35e-25a52964ec61

* ✅ Ensures that text colors and styles are consistent with the theme's intent definitions

https://github.com/user-attachments/assets/103fab2e-21a2-492c-a417-1fa697ab874e

* ✅ "click and drag" behavior - press a button and move the mouse outside the button boundaries, the component still "captures" the event

https://github.com/user-attachments/assets/a3ca4a1f-c202-492d-953e-b8d5f5a8a0d3

* ✅ Refined how placeholder text is rendered and styled

https://github.com/user-attachments/assets/a528a954-6ca1-4cc5-a043-949e50081ee3

* ✅ Prevents text from breaking the layout or overlapping other UI elements when a label is very long

https://github.com/user-attachments/assets/ee580ce6-47fe-41b6-bdd9-559d84054bac
